Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2018-10, with the labels that each got.

#335 Improve log colors
  cmd/lsp-proxy/lsp-proxy.go
  pkg/tracer/tracer.go
  xlang/proxy/log.go
Labels: ops & tools & dev

#438 cmd/frontend: make createdb error readable
  cmd/frontend/db/schemadoc/main.go
Labels: new-contributor

#441 Prepended "bash " to scripts in .huskyrc.json
  .huskyrc.json
Labels: new-contributor

#453 Correcting 404's for README doc links
  README.md
Labels: new-contributor

#471 Fix documentation links for the site configuration
  src/site-admin/SiteAdminConfigurationPage.tsx
Labels: new-contributor

#515 feat: remove client settings for Sourcegraph extensions
  package.json
  src/Layout.tsx
  src/SourcegraphWebApp.tsx
  src/extensions/ExtensionsArea.tsx
  src/extensions/ExtensionsClientCommonContext.tsx
  src/settings/configuration.ts
  src/user/settings/backend.tsx
  yarn.lock
Labels: extensions

#549 Update README.md
  README.md
Labels: new-contributor

#563 support panel views contributed by extensions
  package.json
  src/nav/NavLinks.tsx
  src/panel/Panel.tsx
  yarn.lock
Labels: extensions

#564 feat: support themable decorations from extensions
  package.json
  src/repo/blob/Blob.tsx
  src/repo/blob/BlobPage.tsx
  src/repo/blob/LineDecorationAttachment.tsx
  yarn.lock
Labels: extensions

#570 show nicer message for unauthed users who try to use extensions
  cmd/frontend/graphqlbackend/configuration.go
  package.json
  src/extensions/ExtensionsClientCommonContext.tsx
  yarn.lock
Labels: extensions

#571 remove Docker lang server management
  cmd/frontend/graphqlbackend/langservers.go
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/internal/bg/langservers.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/pkg/langservers/config.go
  cmd/frontend/internal/pkg/langservers/dockerapi.go
  cmd/frontend/internal/pkg/langservers/langservers.go
  cmd/frontend/internal/pkg/langservers/langservers_test.go
  cmd/frontend/registry/backcompat.go
  cmd/frontend/registry/backcompat_data.go
  cmd/indexer/idx/graphql.go
  cmd/indexer/idx/indexer.go
  doc/extensions/language_servers/install/aws.md
  pkg/conf/computed.go
  src/repo/actions/backend.ts
  src/site-admin/SiteAdmin.scss
  src/site-admin/SiteAdminCodeIntelligencePage.tsx
  src/site-admin/SiteAdminLangServers.scss
  src/site-admin/SiteAdminLangServers.tsx
  src/site-admin/SiteAdminOverviewPage.tsx
  src/site-admin/backend.tsx
  src/site-admin/routes.tsx
  src/site-admin/sidebaritems.ts
  src/site/backend.tsx
  src/site/index.ts
Labels: extensions
