Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2019-03, with the labels that each got.

#2488 Minimize Prop drilling
  shared/src/panel/Panel.tsx
  web/src/Layout.tsx
  web/src/components/SearchResult.tsx
  web/src/components/SearchResultMatch.tsx
  web/src/components/d3/BarChart.tsx
  web/src/enterprise/dotcom/welcome/WelcomeArea.tsx
  web/src/enterprise/dotcom/welcome/WelcomeAreaFooter.tsx
  web/src/enterprise/dotcom/welcome/WelcomeMainPage.tsx
  web/src/enterprise/dotcom/welcome/WelcomeMainPageLogos.tsx
  web/src/enterprise/dotcom/welcome/logos.tsx
  web/src/enterprise/user/productSubscriptions/NewProductSubscriptionPageOrRedirectUser.tsx
  web/src/enterprise/user/productSubscriptions/PaymentTokenFormControl.tsx
  web/src/enterprise/user/productSubscriptions/ProductSubscriptionForm.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsEditProductSubscriptionPage.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsNewProductSubscriptionPage.tsx
  web/src/explore/ExploreArea.tsx
  web/src/extensions/ExtensionsArea.tsx
  web/src/extensions/extension/ExtensionArea.tsx
  web/src/extensions/extension/RegistryExtensionContributionsPage.tsx
  web/src/extensions/extension/RegistryExtensionManifestPage.tsx
  web/src/marketing/SurveyPage.tsx
  web/src/nav/NavLinks.tsx
  web/src/org/OrgsArea.tsx
  web/src/org/account/OrgAccountArea.tsx
  web/src/org/area/OrgArea.tsx
  web/src/repo/RepoContainer.tsx
  web/src/repo/RepoRevContainer.tsx
  web/src/repo/TreePage.tsx
  web/src/repo/blob/Blob.tsx
  web/src/repo/blob/BlobPage.tsx
  web/src/repo/blob/LineDecorationAttachment.tsx
  web/src/repo/blob/panel/BlobPanel.tsx
  web/src/repo/routes.tsx
  web/src/search/results/SearchResults.tsx
  web/src/search/results/SearchResultsList.tsx
  web/src/search/saved-queries/SavedQueries.tsx
  web/src/search/saved-queries/SavedQuery.tsx
  web/src/search/saved-queries/SavedQueryRow.tsx
  web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
  web/src/settings/MonacoSettingsEditor.tsx
  web/src/settings/SettingsArea.tsx
  web/src/settings/SettingsFile.tsx
  web/src/settings/SettingsPage.tsx
  web/src/theme.ts
  web/src/user/account/UserAccountArea.tsx
  web/src/user/area/UserArea.tsx
Labels: debt, web

#2522 Fix overly restrictive auth check for user lookup on Sourcegraph.com
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: auth, web

#2405 Remove in-product /help, redirect to docs.sourcegraph.com
  cmd/frontend/docsite/graphql.go
  cmd/frontend/graphqlbackend/discussion_comments.go
  cmd/frontend/graphqlbackend/doc_site.go
  cmd/frontend/graphqlbackend/file.go
  cmd/frontend/graphqlbackend/markdown.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/internal/app/ui/help.go
  cmd/frontend/internal/app/ui/help_test.go
  cmd/frontend/internal/pkg/discussions/notify_mentions.go
  cmd/frontend/internal/pkg/markdown/markdown.go
  cmd/frontend/shared/frontend.go
  dev/check/docsite/doc.html
  doc/dev/documentation/index.md
  go.mod
  go.sum
  pkg/txemail/template.go
  pkg/version/version.go
  pkg/version/version_test.go
  web/src/SourcegraphWebApp.scss
  web/src/docSite/DocSitePage.tsx
  web/src/routes.tsx
Labels: docs

#2539 check for disconnected doc pages, fix them
  doc/admin/index.md
  doc/admin/repo/index.md
  doc/admin/tls_ssl.md
  doc/dev/index.md
  doc/dev/phabricator_gitolite.md
  doc/dev/retrospectives/index.md
  doc/dev/retrospectives/postgresql_upgrade.md
  doc/docsite.json
  doc/extensions/authoring/forking.md
  doc/extensions/authoring/tutorials/button-custom-commands.md
  doc/extensions/authoring/tutorials/hello-world.md
  doc/extensions/authoring/tutorials/lang-specific-extension-tutorial.md
  doc/quickstart.md
  go.mod
  go.sum
Labels: docs

#2543 clarify license
  LICENSE
  LICENSE.apache
  LICENSE.enterprise
  README.md
Labels: docs

#2482 Move docs.sourcegraph.com templates/assets into sourcegraph repository
  cmd/frontend/internal/app/ui/help.go
  cmd/frontend/internal/app/ui/help_test.go
  dev/Procfile
  doc/_resources/assets/content.css
  doc/_resources/assets/layout.css
  doc/_resources/assets/sourcegraph-logo.svg
  doc/_resources/assets/sourcegraph-mark.svg
  doc/_resources/templates/doc.html
  doc/dev/documentation/index.md
  doc/dev/documentation/site.md
  doc/docsite.json
  enterprise/dev/Procfile
Labels: docs

#2547 Improve integrations docs
  doc/integration/google_gsuite.md
  doc/integration/index.md
  doc/integration/lightstep.md
Labels: docs

#2548 publish correct type of TextDocument#text (can be undefined)
  client/browser/src/libs/code_intelligence/code_intelligence.tsx
  package.json
  packages/@sourcegraph/extension-api-types/node_modules/sourcegraph
  packages/@sourcegraph/extension-api-types/package.json
  packages/sourcegraph-extension-api/package.json
  packages/sourcegraph-extension-api/src/sourcegraph.d.ts
  shared/src/api/client/connection.ts
  shared/src/api/client/context/context.ts
  shared/src/api/client/model.ts
  shared/src/api/client/types/textDocument.test.ts
  shared/src/api/client/types/textDocument.ts
  shared/src/api/extension/api/documents.ts
  yarn.lock
Labels: extensions

#2332 simplify internal locations API
  shared/src/api/client/api/languageFeatures.ts
  shared/src/api/client/services.ts
  shared/src/api/client/services/location.test.ts
  shared/src/api/client/services/location.ts
  shared/src/api/integration-test/languageFeatures.test.ts
  web/src/repo/blob/panel/BlobPanel.tsx
  web/src/settings/configuration.test.ts
Labels: extensions

#2552 remove unused getJumpURL
  web/src/backend/features.ts
Labels: extensions

#2578 repo-updater: Remove old scheduler
  CHANGELOG.md
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/metrics.go
  cmd/repo-updater/repos/reposlist.go
  cmd/repo-updater/repos/scheduler.go
  cmd/repo-updater/repos/util.go
  cmd/repo-updater/repoupdater/server.go
  pkg/conf/computed.go
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
  web/src/globals.d.ts
  web/src/repo/settings/RepoSettingsMirrorPage.tsx
Labels: repos

#2563 Design-Debt Fixes
  shared/src/components/FileMatch.scss
  shared/src/components/FileMatch.tsx
  shared/src/components/ResultContainer.scss
  web/src/auth/SignInSignUpPageCommon.scss
  web/src/auth/SignUpPage.tsx
  web/src/org/account/OrgAccountArea.scss
  web/src/org/account/OrgAccountArea.tsx
  web/src/org/account/OrgAccountSidebar.scss
  web/src/org/account/OrgAccountSidebar.tsx
  web/src/repo/commits/GitCommitNode.tsx
  web/src/search/results/SearchResultsInfoBar.scss
  web/src/search/results/SearchResultsInfoBar.tsx
  web/src/search/results/SearchResultsList.scss
Labels: debt, design

#2266 repo-updater: Improved repository handling for Github external services
  cmd/frontend/db/repos.go
  cmd/frontend/db/repos_perm_test.go
  cmd/frontend/db/schema.md
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/awscodecommit.go
  cmd/repo-updater/repos/bitbucketserver_test.go
  cmd/repo-updater/repos/db.go
  cmd/repo-updater/repos/db_test.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/internal_api.go
  cmd/repo-updater/repos/metrics.go
  cmd/repo-updater/repos/other_external_services.go
  cmd/repo-updater/repos/other_external_services_test.go
  cmd/repo-updater/repos/scheduler.go
  cmd/repo-updater/repos/source.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testing.go
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repos/util_test.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  go.mod
  go.sum
  migrations/1528395566_.down.sql
  migrations/1528395566_.up.sql
  migrations/1528395567_.down.sql
  migrations/1528395567_.up.sql
  migrations/1528395568_.down.sql
  migrations/1528395568_.up.sql
  migrations/1528395569_.down.sql
  migrations/1528395569_.up.sql
  migrations/1528395570_.down.sql
  migrations/1528395570_.up.sql
  migrations/bindata.go
  pkg/api/api.go
  pkg/api/httpapi_schema.go
  pkg/extsvc/github/client.go
  pkg/extsvc/github/repos.go
  pkg/extsvc/github/repos_test.go
  pkg/repoupdater/client.go
  pkg/repoupdater/protocol/repoupdater.go
Labels: repos

#2602 Add page to docs on open company and open product
  doc/dev/index.md
  doc/dev/open_source_open_company.md
Labels: docs

#2640 Fix hover tooltip buttons to be centered
  shared/src/actions/ActionItem.scss
Labels: design

#2648 Document how to use Perforce repositories in Sourcegraph
  doc/admin/repo/add.md
  doc/admin/repo/index.md
  doc/admin/repo/perforce.md
Labels: docs

#2671 rearrange extensions docs
  doc/admin/extensions/index.md
  doc/extensions/authoring/index.md
  doc/extensions/index.md
  doc/extensions/security.md
  doc/extensions/usage.md
Labels: docs, extensions

#2674 repo-updater: Parameterise http.Client of GithubSources
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/source.go
  cmd/repo-updater/repos/util.go
  pkg/extsvc/github/client.go
  pkg/extsvc/github/repos_test.go
  pkg/httpcli/client.go
  pkg/httpcli/doc.go
  pkg/metrics/metrics.go
Labels: debt, repos

#2665 Remove cycle between enterprise/internal/authz and db pkg
  cmd/frontend/auth/provider.go
  cmd/frontend/auth/providers.go
  cmd/frontend/auth/providers/providers.go
  cmd/frontend/graphqlbackend/auth_provider.go
  cmd/frontend/graphqlbackend/auth_providers.go
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/auth/userpasswd/config_watch.go
  cmd/frontend/internal/auth/userpasswd/provider.go
  cmd/server/internal/goreman/log.go
  dev/update-changelog/main.go
  enterprise/cmd/frontend/auth/githuboauth/config.go
  enterprise/cmd/frontend/auth/githuboauth/config_test.go
  enterprise/cmd/frontend/auth/githuboauth/middleware_test.go
  enterprise/cmd/frontend/auth/githuboauth/session.go
  enterprise/cmd/frontend/auth/gitlaboauth/config.go
  enterprise/cmd/frontend/auth/gitlaboauth/config_test.go
  enterprise/cmd/frontend/auth/gitlaboauth/middleware_test.go
  enterprise/cmd/frontend/auth/gitlaboauth/session.go
  enterprise/cmd/frontend/auth/httpheader/config_watch.go
  enterprise/cmd/frontend/auth/httpheader/provider.go
  enterprise/cmd/frontend/auth/oauth/middleware.go
  enterprise/cmd/frontend/auth/oauth/provider.go
  enterprise/cmd/frontend/auth/oauth/session.go
  enterprise/cmd/frontend/auth/openidconnect/config.go
  enterprise/cmd/frontend/auth/openidconnect/config_watch.go
  enterprise/cmd/frontend/auth/openidconnect/middleware.go
  enterprise/cmd/frontend/auth/openidconnect/middleware_test.go
  enterprise/cmd/frontend/auth/openidconnect/provider.go
  enterprise/cmd/frontend/auth/openidconnect/session.go
  enterprise/cmd/frontend/auth/saml/config.go
  enterprise/cmd/frontend/auth/saml/config_watch.go
  enterprise/cmd/frontend/auth/saml/middleware.go
  enterprise/cmd/frontend/auth/saml/middleware_test.go
  enterprise/cmd/frontend/auth/saml/provider.go
  enterprise/cmd/frontend/internal/authz/authz_github.go
  enterprise/cmd/frontend/internal/authz/authz_gitlab.go
  enterprise/cmd/frontend/internal/authz/authz_test.go
  enterprise/cmd/frontend/internal/authz/gitlab/common_test.go
  enterprise/cmd/frontend/internal/authz/gitlab/gitlab_sudo.go
  enterprise/cmd/frontend/internal/authz/gitlab/gitlab_sudo_test.go
  enterprise/cmd/frontend/internal/authz/init.go
  enterprise/cmd/frontend/internal/licensing/enforcement.go
  enterprise/cmd/frontend/internal/licensing/enforcement_test.go
  enterprise/cmd/frontend/internal/licensing/licenseusercount.go
  enterprise/cmd/frontend/internal/licensing/licensing.go
  enterprise/cmd/frontend/internal/licensing/tags.go
  enterprise/cmd/frontend/internal/licensing/tags_test.go
  enterprise/cmd/frontend/main.go
Labels: debt

#2669 Clean up repository inventory code
  cmd/frontend/backend/repos.go
  cmd/frontend/backend/repos_mock.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/inventory/filelang/LICENSE
  cmd/frontend/internal/inventory/filelang/_data/languages.yml
  cmd/frontend/internal/inventory/filelang/_data/vendor.yml
  cmd/frontend/internal/inventory/filelang/data_languages.go
  cmd/frontend/internal/inventory/filelang/data_vendor.go
  cmd/frontend/internal/inventory/filelang/gen/generate.go
  cmd/frontend/internal/inventory/filelang/languages.go
  cmd/frontend/internal/inventory/filelang/languages_test.go
  cmd/frontend/internal/inventory/filelang/vendor.go
  cmd/frontend/internal/inventory/filelang/vendor_test.go
  cmd/frontend/internal/inventory/inventory.go
  cmd/frontend/internal/inventory/inventory_test.go
  cmd/frontend/internal/inventory/prom-repo-tree.txt
  pkg/api/httpapi_schema.go
  pkg/api/internal_client.go
Labels: debt

#2685 Update postgres version 9.6 -> 11
  doc/dev/local_development.md
Labels: new-contributor

#2619 UI Fixes / Debt
  cmd/frontend/internal/app/sign_out.go
  shared/src/components/FileMatch.scss
  shared/src/components/ResultContainer.scss
  web/src/e2e/index.e2e.test.tsx
  web/src/search/results/SearchResultsInfoBar.scss
Labels: debt, design

#2626 Adding HTTPS/SSL to Sourcegraph using a self-signed certificate
  doc/admin/img/sourcegraph-nginx.mermaid
  doc/admin/img/sourcegraph-nginx.svg
  doc/admin/index.md
  doc/admin/nginx.md
  doc/admin/sourcegraph-nginx-mermaid.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
Labels: docs

#2622 docs: broken content fixes
  doc/admin/img/sourcegraph-nginx.mermaid
  doc/admin/nginx.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/dev/documentation/style_guide.md
  doc/dev/img/architecture.mermaid
  doc/user/markdown.md
Labels: docs

#2716 remove upgrade notice from docs homepage
  doc/index.md
Labels: docs

#2604 show Go package "used by" counts including repository subpackages
  cmd/frontend/backend/go_importers.go
  cmd/frontend/backend/go_importers_test.go
  cmd/frontend/backend/mocks.go
  doc/user/index.md
  doc/user/repository/badges.md
  doc/user/repository/index.md
Labels: web

#2689 remove unnecessary CORS logic and corsOrigin docs + site config prop usage
  CHANGELOG.md
  client/browser/src/libs/options/ServerURLForm.tsx
  client/browser/src/shared/backend/graphql.tsx
  client/browser/src/shared/backend/headers.tsx
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/cli/serve_cmd.go
  dev/config.json
  dev/site-config.json
  doc/admin/external_service/phabricator.md
  doc/integration/browser_extension.md
  schema/site.schema.json
  schema/site_stringdata.go
Labels: auth, browser-extension, code-nav, docs

#2688 do not spellcheck/etc. browser ext URL input field
  client/browser/src/libs/options/ServerURLForm.tsx
Labels: browser-extension

#2695 repo-updater: Implement GitHub external service exclude list
  CHANGELOG.md
  cmd/repo-updater/repos/bitbucketserver_test.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/main_test.go
  cmd/repo-updater/repos/source.go
  cmd/repo-updater/repos/source_test.go
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-path-pattern.golden
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-simple.golden
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-ssh.golden
  cmd/repo-updater/repos/testdata/bitbucketserver-repos.json
  cmd/repo-updater/repos/testdata/github-source.yaml
  enterprise/cmd/frontend/db/external_services_test.go
  go.mod
  go.sum
  schema/github.schema.json
  schema/github_stringdata.go
  schema/schema.go
Labels: repos

#2718 update homepage description
  doc/index.md
Labels: docs

#2734 repo-updater: Refactor Store scanning and pagination
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
Labels: repos

#2755 add settings action for search.contextLines
  web/src/site-admin/configHelpers.ts
Labels: search

#1697 remove deprecated register{TypeDefinition,Implementation}Provider and related types
  packages/sourcegraph-extension-api/src/sourcegraph.d.ts
  shared/src/api/client/api/languageFeatures.ts
  shared/src/api/client/connection.ts
  shared/src/api/client/services.ts
  shared/src/api/extension/api/languageFeatures.ts
  shared/src/api/extension/extensionHost.ts
  shared/src/api/integration-test/languageFeatures.test.ts
  web/src/repo/blob/panel/BlobPanel.tsx
Labels: extensions

#2641 Onboarding UI
  shared/src/components/activation/ActivationChecklist.scss
  shared/src/components/activation/ActivationChecklist.tsx
  shared/src/components/activation/ActivationDropdown.scss
  shared/src/components/activation/ActivationDropdown.tsx
  shared/src/components/activation/__snapshots__/ActivationChecklist.test.tsx.snap
  shared/src/components/activation/__snapshots__/ActivationDropdown.test.tsx.snap
  ui/assets/img/onboarding-bg-dark.png
  ui/assets/img/onboarding-bg.png
  web/src/components/Overview.scss
  web/src/components/Overview.tsx
  web/src/components/PopoverButton.scss
  web/src/global-styles/dropdown.scss
  web/src/repo/GitRef.scss
  web/src/site-admin/SiteAdminOverviewPage.tsx
  web/src/site-admin/SiteAdminUsageStatisticsPage.scss
  web/src/site-admin/SiteAdminUsageStatisticsPage.tsx
  web/src/user/account/UserAccountProfilePage.scss
  web/src/user/account/UserAccountProfilePage.tsx
Labels: design

#2733 fix usage of custom location providers in extension API panel views
  shared/src/api/client/api/views.ts
  shared/src/api/client/connection.ts
  shared/src/api/client/context/context.test.ts
  shared/src/api/client/context/context.ts
  shared/src/api/client/services/location.ts
  shared/src/api/integration-test/languageFeatures.test.ts
  shared/src/panel/Panel.tsx
  shared/src/panel/views/contributions.ts
Labels: extensions

#2784 move (English) style guide here from the about repository
  doc/dev/code_style_guide.md
  doc/dev/documentation/style_guide.md
  doc/dev/index.md
  doc/dev/local_development.md
  doc/dev/style_guide.md
  doc/docsite.json
Labels: docs

#2791 Fix various minor code discussions bugs, make tweaks
  cmd/frontend/internal/pkg/discussions/url.go
  shared/src/components/Tabs.tsx
  web/src/SourcegraphWebApp.scss
  web/src/discussions/DiscussionsComment.tsx
  web/src/discussions/DiscussionsList.scss
  web/src/discussions/DiscussionsList.tsx
  web/src/discussions/DiscussionsPage.tsx
  web/src/discussions/explore/DiscussionsExploreSection.scss
  web/src/discussions/explore/DiscussionsExploreSection.tsx
  web/src/explore/exploreSections.tsx
  web/src/repo/TreePage.tsx
  web/src/repo/blob/discussions/DiscussionsNavbar.tsx
  web/src/repo/blob/discussions/DiscussionsThread.tsx
  web/src/repo/blob/discussions/DiscussionsTree.tsx
  web/src/repo/blob/panel/BlobPanel.tsx
Labels: feature:code-discussions, web

#2828 improve error message when using nonexistent publisher for extension
  enterprise/cmd/frontend/internal/registry/publishers_db.go
Labels: extensions

#2829 update links to documentation
  client/browser/src/libs/options/ServerURLForm.tsx
  web/src/site-admin/SiteAdminConfigurationPage.tsx
  web/src/site-admin/externalServices.tsx
Labels: docs

#2858 add tracking issue links
  doc/dev/roadmap/index.md
Labels: docs

#2886 update roadmap
  doc/dev/roadmap/index.md
  doc/dev/roadmap/previous_releases.md
Labels: docs

#2785 repo-updater: Extend Store with methods for external services
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/source.go
  cmd/repo-updater/repos/source_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testing.go
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: repos

#2792 external services: Change default github.repositoryQuery to ["none"]
  CHANGELOG.md
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/testing.go
  cmd/repo-updater/repos/types.go
  enterprise/cmd/frontend/db/external_services_test.go
  schema/github.schema.json
  schema/github_stringdata.go
  web/src/site-admin/externalServices.tsx
Labels: repos

#2880 Fix local repo path
  doc/admin/repo/add_from_local_disk.md
Labels: new-contributor

#2949 update docsite $VERSION config
  doc/dev/documentation/site.md
Labels: docs

#2953 capitalization Github -> GitHub
  CHANGELOG.md
  client/browser/README.md
  doc/admin/migration/3_0.md
  doc/dev/retrospectives/3_0.md
  doc/dev/retrospectives/postgresql_upgrade.md
  pkg/extsvc/github/client.go
Labels: docs

#2952 clarify GitHub ext svc docs, standardize on terms
  schema/github.schema.json
  schema/github_stringdata.go
  web/src/site-admin/externalServices.tsx
Labels: docs, repos

#2959 show custom notices on the homepage (and consolidate motd)
  CHANGELOG.md
  schema/schema.go
  schema/settings.schema.json
  schema/settings_stringdata.go
  web/src/SourcegraphWebApp.scss
  web/src/components/DismissibleAlert.scss
  web/src/global/GlobalAlerts.scss
  web/src/global/GlobalAlerts.tsx
  web/src/global/Notices.scss
  web/src/global/Notices.test.tsx
  web/src/global/Notices.tsx
  web/src/global/__snapshots__/Notices.test.tsx.snap
  web/src/search/input/SearchPage.tsx
Labels: web

#2963 add search.defaultRepositories hack for demo
  cmd/frontend/graphqlbackend/search.go
Labels: search

#2967 more legible notices
  web/src/global/Notices.tsx
  web/src/global/__snapshots__/Notices.test.tsx.snap
Labels: web

#2965 prevent query field from being autofilled with password
  web/src/search/input/QueryInput.tsx
Labels: web

#2978 Update Triggers section in Postgres guidelines
  doc/dev/postgresql.md
Labels: docs

#2932 Update product roadmap
  doc/dev/roadmap/index.md
Labels: roadmap

#3007 repo-updater: Dev friendly DSN
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/db.go
Labels: repos

#3021 docs: dotgo page with demos for attendees
  doc/docsite.json
  doc/user/dotgo-eu-2019.md
Labels: docs

#3008 repo-updater: Implement GitLab source
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/gitlab.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testdata/github/yielded-repos-are-always-enabled.yaml
  cmd/repo-updater/repos/testdata/sources/excluded-repos-are-never-yielded.yaml
  cmd/repo-updater/repos/testdata/sources/yielded-repos-are-always-enabled.yaml
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repoupdater/server.go
  pkg/extsvc/gitlab/client.go
  pkg/extsvc/gitlab/projects_test.go
  pkg/extsvc/gitlab/repositories_test.go
Labels: repos

#3028 repo-updater: Implement GitLabSetDefaultProjectQueryMigration
  CHANGELOG.md
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
  enterprise/cmd/frontend/db/external_services_test.go
  schema/gitlab.schema.json
  schema/gitlab_stringdata.go
  web/src/site-admin/externalServices.tsx
Labels: repos

#3029 repo-updater: Extend EnabledStateDeprecationMigration with Gitlab
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repos/types_test.go
Labels: repos

#3061 docs: added screencast of toggling site access URLs as another troubleshooting step
  doc/integration/browser_extension.md
  doc/integration/img/ToggleSiteAccess.gif
Labels: docs

#3064 add instructions for uploading large assets
  doc/dev/documentation/style_guide.md
Labels: docs

#3036 repo-updater: Prevent HTTPS redirect in github source tests
  cmd/repo-updater/repos/sources_test.go
Labels: repos
