Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2019-07, with the labels that each got.

#4702 graphqlbackend: Reduce allocations in zoektIndexedRepos
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/textsearch.go
  cmd/frontend/graphqlbackend/textsearch_test.go
  cmd/frontend/internal/pkg/search/repo_revs.go
  pkg/search/backend/text.go
Labels: perf, search, team/core-services

#4763 graphqlbackend: Simplify zoektIndexedRepos
  cmd/frontend/graphqlbackend/textsearch.go
  cmd/frontend/graphqlbackend/textsearch_test.go
Labels: search, team/core-services

#4546 expose EditorService#{editorsWithModels,observeEditorAndModel}
  browser/src/libs/code_intelligence/code_intelligence.test.tsx
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/text_fields.test.tsx
  go.sum
  shared/src/api/client/context/context.test.ts
  shared/src/api/client/context/context.ts
  shared/src/api/client/services/contribution.test.ts
  shared/src/api/client/services/contribution.ts
  shared/src/api/client/services/editorService.test.ts
  shared/src/api/client/services/editorService.ts
  shared/src/api/client/services/extensionsService.test.ts
  shared/src/api/client/services/extensionsService.ts
  shared/src/api/client/services/location.test.ts
  shared/src/api/client/services/location.ts
  shared/src/api/integration-test/testHelpers.ts
  shared/src/components/completion/EditorCompletionWidget.tsx
  shared/src/components/editorTextField/EditorTextField.test.tsx
  shared/src/components/editorTextField/EditorTextField.tsx
  web/src/repo/blob/panel/BlobPanel.tsx
  web/src/snippets/SnippetsPage.tsx
Labels: browser-extension, extensions

#4789 perf: Reduce external repo pointer allocations
  cmd/frontend/authz/common.go
  cmd/frontend/backend/go_importers_test.go
  cmd/frontend/backend/repos.go
  cmd/frontend/backend/repos_mock.go
  cmd/frontend/backend/repos_test.go
  cmd/frontend/backend/repos_vcs.go
  cmd/frontend/backend/repos_vcs_test.go
  cmd/frontend/db/repos.go
  cmd/frontend/db/repos_db_test.go
  cmd/frontend/db/repos_mock.go
  cmd/frontend/db/repos_perm_filter_test.go
  cmd/frontend/db/repos_perm_test.go
  cmd/frontend/db/repos_test.go
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/externallink/repository.go
  cmd/frontend/graphqlbackend/externallink/repository_test.go
  cmd/frontend/graphqlbackend/git_tree_test.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_external.go
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/repository_mirror_test.go
  cmd/frontend/graphqlbackend/repository_test.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_commits_test.go
  cmd/frontend/graphqlbackend/search_repositories_test.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_suggestions_test.go
  cmd/frontend/graphqlbackend/search_symbols_test.go
  cmd/frontend/graphqlbackend/search_test.go
  cmd/frontend/graphqlbackend/textsearch.go
  cmd/frontend/graphqlbackend/textsearch_test.go
  cmd/frontend/internal/app/editor_test.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/router_test.go
  cmd/frontend/internal/httpapi/repo_refresh_test.go
  cmd/frontend/internal/httpapi/repo_shield_test.go
  cmd/frontend/internal/pkg/search/repo_revs_test.go
  cmd/frontend/types/types.go
  cmd/repo-updater/repos/awscodecommit.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/gitlab.go
  cmd/repo-updater/repos/gitolite.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  pkg/api/api.go
  pkg/api/httpapi_schema.go
  pkg/extsvc/awscodecommit/codehost.go
  pkg/extsvc/codehost.go
  pkg/extsvc/github/codehost.go
  pkg/extsvc/gitlab/codehost.go
  pkg/extsvc/gitolite/codehost.go
  pkg/repoupdater/protocol/repoupdater.go
Labels: search, team/core-services

#4680 fix unicode highlighting in commit searches
  CHANGELOG.md
  cmd/frontend/graphqlbackend/search_commits.go
  cmd/frontend/graphqlbackend/search_commits_test.go
Labels: search

#4465 use conventional opaque (base64-encoded) GraphQL IDs for Discussion{Thread,Comment}
  cmd/frontend/graphqlbackend/discussion_comments.go
  cmd/frontend/graphqlbackend/discussion_comments_test.go
  cmd/frontend/graphqlbackend/discussion_threads.go
  cmd/frontend/graphqlbackend/discussion_threads_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  web/src/discussions/DiscussionsComment.tsx
  web/src/discussions/DiscussionsList.tsx
  web/src/discussions/backend.tsx
  web/src/repo/blob/discussions/DiscussionsCreate.tsx
  web/src/repo/blob/discussions/DiscussionsThread.tsx
  web/src/repo/blob/discussions/DiscussionsTree.tsx
Labels: feature:code-discussions, web

#4810 perf: Improve performance of computing number of not-cloned repos - Part 2
  cmd/gitserver/server/list.go
  cmd/gitserver/server/server.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  go.mod
  go.sum
  pkg/gitserver/client.go
  pkg/gitserver/protocol/gitserver.go
Labels: perf, team/core-services

#4790 db: Optimize authzFilter code path
  cmd/frontend/authz/common.go
  cmd/frontend/authz/iface.go
  cmd/frontend/authz/perms.go
  cmd/frontend/authz/perms_test.go
  cmd/frontend/db/repos_db_test.go
  cmd/frontend/db/repos_perm.go
  cmd/frontend/db/repos_perm_filter_test.go
  cmd/frontend/db/repos_perm_test.go
  enterprise/cmd/frontend/internal/authz/authz_test.go
  enterprise/cmd/frontend/internal/authz/bitbucketserver/provider.go
  enterprise/cmd/frontend/internal/authz/bitbucketserver/provider_test.go
  enterprise/cmd/frontend/internal/authz/bitbucketserver/store.go
  enterprise/cmd/frontend/internal/authz/github/github.go
  enterprise/cmd/frontend/internal/authz/github/github_cache_test.go
  enterprise/cmd/frontend/internal/authz/github/github_test.go
  enterprise/cmd/frontend/internal/authz/gitlab/common_test.go
  enterprise/cmd/frontend/internal/authz/gitlab/gitlab_oauth.go
  enterprise/cmd/frontend/internal/authz/gitlab/gitlab_oauth_test.go
  enterprise/cmd/frontend/internal/authz/gitlab/gitlab_sudo.go
  enterprise/cmd/frontend/internal/authz/gitlab/gitlab_sudo_test.go
  pkg/extsvc/codehost.go
Labels: auth, perf, team/core-services

#4823 db: Pre-partition repos to verify in authzFilter
  cmd/frontend/db/repos_perm.go
  cmd/frontend/db/repos_perm_filter_test.go
  cmd/frontend/db/repos_perm_test.go
Labels: auth, perf, team/core-services

#4824 graphqlbackend: Reduce allocations in getRevsForMatchedRepo
  cmd/frontend/graphqlbackend/search.go
Labels: perf, search, team/core-services

#4464 codemod: add 'replace:' flag to frontend search
  cmd/frontend/graphqlbackend/codemod.go
  cmd/frontend/graphqlbackend/codemod_test.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_commits.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/textsearch.go
  cmd/frontend/internal/pkg/search/query/searchquery.go
  cmd/replacer/protocol/replacer.go
  cmd/replacer/replace/replace.go
  cmd/server/shared/shared.go
  dev/launch.sh
  enterprise/dev/Procfile
  web/src/enterprise/codemod/index.ts
  web/src/search/backend.tsx
Labels: code-mod

#4829 search: Avoid sorting in searchResultsCommon.update
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/types/types.go
Labels: perf, search

#4838 Add Firefox add-on security documentation
  doc/integration/browser_extension.md
  doc/integration/firefox_security.md
  doc/integration/img/firefox-error.png
Labels: docs

#4835 DRY entrypoints
  browser/src/extension/scripts/inject.tsx
  browser/src/integration/integration.tsx
  browser/src/libs/code_intelligence/inject.ts
  browser/src/libs/phabricator/extension.tsx
  browser/src/libs/sourcegraph/inject.tsx
Labels: browser-extension

#4859 repo-updater: Fix not-cloned count by comparing lowercase repo names
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: team/core-services

#4861 Enable clone status indicator by default and remove feature flag
  CHANGELOG.md
  schema/site.schema.json
  schema/site_stringdata.go
Labels: team/core-services

#4886 repo-updater: Remove deprecated migrations
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
Labels: team/core-services

#4887 doc: add Bitbucket Cloud docs
  doc/admin/external_service/bitbucket_cloud.md
  doc/admin/external_service/bitbucket_cloud.schema.json
  doc/admin/external_service/index.md
Labels: docs

#4893 docs: added bitbucket cloud integration page plus other fixes
  doc/_resources/templates/doc.html
  doc/admin/index.md
  doc/admin/updates.md
  doc/integration/bitbucket_cloud.md
  doc/integration/index.md
Labels: docs

#4895 repo-updater: Make cloned-count ignore gitserver case-sensitivity
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: team/core-services

#4899 repo-updater: Use client factory when saving external services
  cmd/repo-updater/repoupdater/server.go
Labels: team/core-services

#4923 Enable status indicator if no config value has been set
  dev/site-config.json
  pkg/conf/computed.go
Labels: team/core-services

#4925 Allow creating and updating (user|org) names with dots
  CHANGELOG.md
  cmd/frontend/db/schema.md
  cmd/frontend/db/users_test.go
  migrations/1528395581_allows_dots_in_usernames.down.sql
  migrations/1528395581_allows_dots_in_usernames.up.sql
  migrations/bindata.go
  web/src/org/new/NewOrganizationPage.tsx
  web/src/site-admin/SiteAdminCreateUserPage.tsx
  web/src/user/index.ts
  web/src/user/settings/profile/UserSettingsProfilePage.tsx
Labels: team/core-services

#4930 Adding item from patch release and linking issues
  CHANGELOG.md
Labels: docs

#4936 fix absolute link to contact page from perf alert
  web/src/site/PerformanceWarningAlert.tsx
Labels: release-blocker

#4927 Prevent native integration & bext conflict
  browser/src/extension/scripts/inject.tsx
  browser/src/integration/integration.tsx
  browser/src/libs/sourcegraph/inject.tsx
Labels: bitbucket, release-blocker

#4969 inject routes into OrgArea in same way as for UserArea
  cmd/frontend/graphqlbackend/namespaces.go
  cmd/frontend/graphqlbackend/namespaces_test.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  web/src/Layout.tsx
  web/src/SourcegraphWebApp.scss
  web/src/SourcegraphWebApp.tsx
  web/src/enterprise/main.tsx
  web/src/enterprise/namespaces/navitems.ts
  web/src/enterprise/namespaces/routes.ts
  web/src/enterprise/organizations/navitems.ts
  web/src/enterprise/organizations/routes.ts
  web/src/enterprise/user/routes.tsx
  web/src/main.tsx
  web/src/namespaces/NamespaceArea.tsx
  web/src/namespaces/index.ts
  web/src/namespaces/navitems.ts
  web/src/namespaces/routes.ts
  web/src/org/OrgsArea.scss
  web/src/org/OrgsArea.tsx
  web/src/org/area/OrgArea.tsx
  web/src/org/area/OrgHeader.tsx
  web/src/org/area/navitems.ts
  web/src/org/area/routes.tsx
  web/src/org/new/NewOrganizationPage.tsx
  web/src/org/saved-searches/OrgSavedSearchListPage.tsx
  web/src/org/saved-searches/OrgSavedSearchesCreateForm.tsx
  web/src/org/saved-searches/OrgSavedSearchesUpdateForm.tsx
  web/src/org/settings/OrgSettingsArea.tsx
  web/src/routes.tsx
  web/src/savedSearches/RedirectToUserSavedSearches.tsx
  web/src/savedSearches/SavedSearchCreateForm.tsx
  web/src/savedSearches/SavedSearchForm.scss
  web/src/savedSearches/SavedSearchForm.tsx
  web/src/savedSearches/SavedSearchListPage.scss
  web/src/savedSearches/SavedSearchListPage.tsx
  web/src/savedSearches/SavedSearchModal.scss
  web/src/savedSearches/SavedSearchModal.tsx
  web/src/savedSearches/SavedSearchUpdateForm.tsx
  web/src/savedSearches/index.scss
  web/src/search/results/SearchResultsList.tsx
  web/src/user/area/UserArea.tsx
  web/src/user/area/routes.tsx
  web/src/user/saved-searches/UserSavedSearchListPage.tsx
  web/src/user/saved-searches/UserSavedSearchesCreateForm.tsx
  web/src/user/saved-searches/UserSavedSearchesUpdateForm.tsx
Labels: debt, web

#3959 use Babel instead of ts-jest to speed up and simplify tests
  babel.config.js
  jest.config.base.js
  package.json
  shared/src/api/integration-test/views.test.ts
  shared/src/components/completion/__snapshots__/CompletionWidget.test.tsx.snap
  shared/src/hover/__snapshots__/HoverOverlay.test.tsx.snap
  shared/src/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  yarn.lock
Labels: web

#4962 gitserver: Implement /archive endpoint
  cmd/frontend/backend/repos_mock.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/textsearch_test.go
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/serverutil.go
  cmd/replacer/main.go
  cmd/searcher/main.go
  cmd/symbols/main.go
  pkg/gitserver/client.go
  pkg/gitserver/client_test.go
  pkg/gitserver/errors.go
  pkg/vcs/git/archive.go
  pkg/vcs/git/blame_test.go
  pkg/vcs/git/commits.go
  pkg/vcs/git/commits_test.go
  pkg/vcs/git/diff_search_test.go
  pkg/vcs/git/exec.go
  pkg/vcs/git/exec_test.go
  pkg/vcs/git/gittest/testing.go
  pkg/vcs/git/merge_base_test.go
  pkg/vcs/git/object_test.go
  pkg/vcs/git/refs_test.go
  pkg/vcs/git/revisions.go
  pkg/vcs/git/revisions_test.go
  pkg/vcs/git/tree_test.go
  pkg/vcs/git/util_for_test.go
Labels: hackweek, team/core-services

#4960 ci: Improve performance of go build for server
  cmd/server/build.sh
  enterprise/cmd/frontend/pre-build.sh
Labels: hackweek

#4978 add Alt+t keybinding for cycling the color theme
  web/src/keybindings.ts
  web/src/nav/NavLinks.test.tsx
  web/src/nav/NavLinks.tsx
  web/src/nav/UserNavItem.tsx
Labels: web

#4554 more compact ExtensionCard
  shared/src/components/Toggle.scss
  web/src/extensions/ExtensionCard.scss
  web/src/extensions/ExtensionCard.tsx
  web/src/extensions/ExtensionsList.scss
  web/src/extensions/__snapshots__/ExtensionCard.test.tsx.snap
Labels: design, extensions, web

#4998 repo-updater: Include page in BitbucketServer error
  cmd/repo-updater/repos/bitbucketserver.go
Labels: team/core-services

#4983 dev: Consolidate enterprise Procfile into a single Procfile
  dev/Procfile
  dev/auth-provider/README.md
  dev/auth-provider/config/client-openid-2.json
  dev/auth-provider/config/client-openid.json
  dev/auth-provider/config/client-saml-2.json
  dev/auth-provider/config/client-saml.json
  dev/auth-provider/config/user-alice.json
  dev/auth-provider/config/user-bob.json
  dev/auth-provider/keycloak.sh
  dev/auth-provider/scripts/common.sh
  dev/auth-provider/scripts/configure-keycloak.sh
  dev/changewatch.sh
  dev/go-install.sh
  dev/launch.sh
  enterprise/dev/Procfile
  enterprise/dev/changewatch.sh
  enterprise/dev/handle-change.sh
  enterprise/dev/start.sh
Labels: hackweek

#4999 repo-updater: Migrate a repo without external and different name
  cmd/repo-updater/repos/syncer.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/types.go
Labels: customer

#3928 codemod: Dockerfile and CI integration for replacer
  cmd/replacer/Dockerfile
  cmd/replacer/build.sh
  cmd/replacer/replace/replace.go
  cmd/replacer/replace/replace_test.go
  cmd/server/Dockerfile
  cmd/server/build.sh
  enterprise/dev/ci/ci/pipeline-steps.go
Labels: code-mod

#5012 Fix mispellings and change singlequote ’ to '
  doc/admin/auth/index.md
  doc/admin/external_service/gitlab.md
  doc/admin/install/docker/index.md
  doc/dev/architecture-mermaid.md
  doc/dev/architecture.md
  doc/dev/code_style_guide.md
  doc/dev/documentation/structure.md
  doc/dev/incidents.md
  doc/dev/product/personas.md
  doc/dev/release_issue_template.md
  doc/dev/releases.md
  doc/dev/retrospectives/3_2.md
  doc/dev/retrospectives/3_3.md
  doc/dev/retrospectives/3_4.md
  doc/dev/retrospectives/3_5.md
  doc/dev/retrospectives/postgresql_upgrade.md
  doc/dev/roadmap/index.md
  doc/dev/testing.md
  doc/dev/typescript/build.md
  doc/dev/web_app.md
Labels: docs
