Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2019-12, with the labels that each got.

#6916 a8n: Validate campaign plan arguments with JSON schema
  enterprise/internal/a8n/campaign_type.go
  enterprise/internal/a8n/campaign_type_test.go
  schema/campaign-types/comby.schema.json
  schema/campaign-types/comby_stringdata.go
  schema/campaign-types/credentials.schema.json
  schema/campaign-types/credentials_stringdata.go
Labels: automation

#6950 a8n: Add tests for campaign type to remove credentials
  cmd/frontend/graphqlbackend/search_pagination.go
  cmd/frontend/graphqlbackend/search_pagination_test.go
  cmd/frontend/graphqlbackend/search_repositories.go
  cmd/frontend/graphqlbackend/search_repositories_test.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_suggestions.go
  cmd/frontend/graphqlbackend/search_suggestions_test.go
  cmd/frontend/graphqlbackend/search_symbols.go
  cmd/frontend/graphqlbackend/textsearch.go
  cmd/frontend/graphqlbackend/zoekt.go
  enterprise/internal/a8n/campaign_type.go
  enterprise/internal/a8n/campaign_type_test.go
Labels: automation

#6915 a8n: Add tracing for CreateCampaing and PreviewCampaignPlan
  enterprise/internal/a8n/resolvers/resolver.go
  enterprise/internal/a8n/runner.go
  enterprise/internal/a8n/service.go
  internal/trace/traceutil.go
Labels: automation

#6979 a8n: Fix flaky test by sorting validation errors
  enterprise/internal/a8n/campaign_type.go
Labels: automation

#6981 a8n: Allow specifying custom replacement for removed credentials
  enterprise/internal/a8n/campaign_type.go
  enterprise/internal/a8n/campaign_type_test.go
Labels: automation

#6982 a8n: Consistent naming for "ref" and "ref name"
  cmd/repo-updater/repos/bitbucketserver.go
  cmd/repo-updater/repos/bitbucketserver_test.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/github_test.go
  cmd/repo-updater/repos/testdata/golden/BitbucketServerSource_CreateChangeset_abbreviated refs
  cmd/repo-updater/repos/testdata/golden/BitbucketServerSource_CreateChangeset_success
  cmd/repo-updater/repos/testdata/sources/BitbucketServerSource_CreateChangeset_abbreviated-refs.yaml
  cmd/repo-updater/repos/testdata/sources/BitbucketServerSource_CreateChangeset_full-refs.yaml
  cmd/repo-updater/repos/testdata/sources/BitbucketServerSource_CreateChangeset_success.yaml
  cmd/repo-updater/repos/types.go
  enterprise/internal/a8n/resolvers/changesets.go
  enterprise/internal/a8n/service.go
  internal/a8n/types.go
  internal/vcs/git/refs.go
Labels: automation

#6989 a8n: Add CampaignTypes description of diff in Markdown & return description in NPM credentials campaign
  cmd/frontend/db/schema.md
  enterprise/internal/a8n/campaign_type.go
  enterprise/internal/a8n/campaign_type_test.go
  enterprise/internal/a8n/runner.go
  enterprise/internal/a8n/runner_test.go
  enterprise/internal/a8n/service.go
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
  internal/a8n/types.go
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
  internal/extsvc/bitbucketserver/testdata/golden/CreatePullRequest-description-includes-GFM-tasklist-items
  internal/extsvc/bitbucketserver/testdata/vcr/CreatePullRequest-description-includes-GFM-tasklist-items.yaml
  migrations/1528395620_add_description_to_campaign_jobs.down.sql
  migrations/1528395620_add_description_to_campaign_jobs.up.sql
  migrations/bindata.go
Labels: automation

#6998 tidy: frivolous Sprintf
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/internal/httpapi/repo_shield_test.go
  cmd/searcher/search/search_test.go
  internal/comby/comby.go
  internal/eventlogger/event_logger.go
Labels: campaign

#6898 LSIF: Docmentation updates
  doc/user/code_intelligence/lsif.md
  doc/user/code_intelligence/lsif_quickstart.md
Labels: lsif

#7015 a8n: Fix deletion of repos that are associated with Campaigns/CampaignPlans
  cmd/frontend/db/schema.md
  migrations/1528395621_add_delete_cascade_to_campaign_jobs.down.sql
  migrations/1528395621_add_delete_cascade_to_campaign_jobs.up.sql
  migrations/1528395622_add_more_delete_cascades_to_changeset_jobs.down.sql
  migrations/1528395622_add_more_delete_cascades_to_changeset_jobs.up.sql
  migrations/bindata.go
Labels: automation

#6985 LSIF: Add additional LSIF intelligence endpoints
  lsif/docs/api.yaml
  lsif/src/server/backend/backend.ts
  lsif/src/server/backend/database.ts
  lsif/src/server/middleware/validation.ts
  lsif/src/server/routes/lsif.test.ts
  lsif/src/server/routes/lsif.ts
  lsif/src/server/server.ts
  lsif/src/tests/integration/backend/linked-reference-results.test.ts
  lsif/src/tests/integration/backend/reference-pagination-monorepo.test.ts
  lsif/src/tests/integration/backend/reference-pagination.test.ts
  lsif/src/tests/integration/backend/simple.test.ts
  lsif/src/tests/integration/backend/xrepo.test.ts
  lsif/src/tests/integration/integration-test-util.ts
Labels: lsif

#6190 Browser ext e2e improvements
  browser/src/e2e/bitbucket.test.ts
  browser/src/e2e/phabricator.test.ts
  shared/src/e2e/driver.ts
Labels: browser-extension, e2e-tests

#7040 a8n: Prefill campaign plan spec with defaults
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
Labels: automation

#7036 a8n: Implement `cancelCampaignPlan` mutation
  cmd/frontend/db/schema.md
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/a8n/resolvers/resolver.go
  enterprise/internal/a8n/runner.go
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
  internal/a8n/types.go
  migrations/1528395623_add_canceled_at_to_campaign_plan.down.sql
  migrations/1528395623_add_canceled_at_to_campaign_plan.up.sql
  migrations/bindata.go
Labels: automation

#6867 LSIF: Remove scheduled jobs.
  lsif/docs/api.yaml
  lsif/package.json
  lsif/src/server/routes/jobs.ts
  lsif/src/server/server.ts
  lsif/src/server/settings.ts
  lsif/src/server/tasks/jobs.ts
  lsif/src/server/tasks/runner.ts
  lsif/src/shared/locker/locker.ts
  lsif/src/shared/locks/locks.ts
  lsif/src/worker/processors/clean-failed-jobs.ts
  lsif/src/worker/processors/clean-old-jobs.ts
  lsif/src/worker/processors/convert.ts
  lsif/src/worker/settings.ts
  lsif/src/worker/worker.ts
  lsif/yarn.lock
Labels: lsif

#7047 Declare charset in extensionHostFrame.html
  browser/src/phabricator/extensionHostFrame.html
Labels: gitlab

#7049 Show external link icon if hover action links away
  shared/src/actions/ActionItem.test.tsx
  shared/src/actions/ActionItem.tsx
  shared/src/actions/__snapshots__/ActionItem.test.tsx.snap
  shared/src/globals.d.ts
  shared/src/hover/HoverOverlay.tsx
  shared/src/util/errors.ts
  web/src/components/shared.tsx
Labels: gitlab

#7065 a8n: add hint to resolve error
  enterprise/internal/a8n/runner.go
Labels: automation

#7085 Add methods to close GitHub pull requests
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/github_test.go
  cmd/repo-updater/repos/testdata/golden/GithubSource_CloseChangeset_success
  cmd/repo-updater/repos/testdata/sources/GithubSource_CloseChangeset_success.yaml
  internal/extsvc/github/client_test.go
  internal/extsvc/github/pulls.go
  internal/extsvc/github/testdata/golden/ClosePullRequest-0
  internal/extsvc/github/testdata/golden/ClosePullRequest-1
  internal/extsvc/github/testdata/vcr/ClosePullRequest.yaml
Labels: automation

#7072 Fix display of external link icon for action items
  browser/src/libs/bitbucket/code_intelligence.tsx
  browser/src/libs/github/code_intelligence.ts
  shared/src/actions/ActionItem.tsx
  shared/src/hover/HoverOverlay.tsx
Labels: browser-extension, bug

#6856 web: Add file static suggestions
  web/src/search/searchFilterSuggestions.ts
Labels: search, web

#7098 Use thread-loader in webpack
  package.json
  web/webpack.config.js
  yarn.lock
Labels: ops & tools & dev

#7101 LSIF: Add LSIF intelligence GraphQL resolvers
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/location.go
  cmd/frontend/graphqlbackend/markdown.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/codeintel/resolvers/dump.go
  enterprise/internal/codeintel/resolvers/hover.go
  enterprise/internal/codeintel/resolvers/job.go
  enterprise/internal/codeintel/resolvers/location.go
  enterprise/internal/codeintel/resolvers/query.go
  enterprise/internal/codeintel/resolvers/resolver.go
  internal/lsif/types.go
  lsif/src/server/backend/backend.ts
  lsif/src/server/backend/database.ts
  lsif/src/server/routes/lsif.ts
Labels: lsif

#7125 a8n Store: Use sub-select instead of CTE to address performance concern
  enterprise/internal/a8n/store.go
Labels: automation

#7138 a8n: Increase default fetch timeout from 2s to 10s
  enterprise/internal/a8n/campaign_type.go
Labels: automation

#7140 Use `--silent` in npm script prettier-check
  package.json
Labels: web

#6879 LSIF: Dequeue from postgres.
  lsif/src/shared/database/postgres.ts
  lsif/src/shared/database/sqlite.ts
  lsif/src/shared/metrics.ts
  lsif/src/shared/uploads/uploads.ts
  lsif/src/worker/processors/convert.ts
  lsif/src/worker/settings.ts
  lsif/src/worker/worker.ts
Labels: lsif

#6877 LSIF: Enqueue jobs to postgres.
  lsif/src/server/routes/lsif.ts
  lsif/src/server/server.ts
  lsif/src/shared/database/postgres.ts
  lsif/src/shared/database/sqlite.ts
  lsif/src/shared/metrics.ts
  lsif/src/shared/models/xrepo.ts
  lsif/src/shared/uploads/uploads.ts
  lsif/src/worker/processors/convert.ts
  lsif/src/worker/settings.ts
  lsif/src/worker/worker.ts
Labels: lsif

#6876 LSIF: Add lsif upload endpoints.
  lsif/docs/api.yaml
  lsif/src/server/routes/dumps.ts
  lsif/src/server/routes/lsif.ts
  lsif/src/server/routes/uploads.ts
  lsif/src/server/server.ts
  lsif/src/server/settings.ts
  lsif/src/shared/database/postgres.ts
  lsif/src/shared/database/sqlite.ts
  lsif/src/shared/metrics.ts
  lsif/src/shared/models/xrepo.ts
  lsif/src/shared/uploads/uploads.ts
  lsif/src/worker/processors/convert.ts
  lsif/src/worker/settings.ts
  lsif/src/worker/worker.ts
Labels: lsif

#7136 remove recommendation for deleted stylelint extension
  .vscode/extensions.json
Labels: ops & tools & dev

#7105 a8n: Implement retryCampaign
  enterprise/internal/a8n/resolvers/resolver.go
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
  internal/extsvc/github/pulls.go
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/backend.ts
Labels: automation

#7145 a8n: Allow listing all CampaignJobs/ChangesetJobs and avoid Year 10000 Looming Pagination Bug
  enterprise/internal/a8n/service.go
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
Labels: automation

#7110 a8n: Align changesetnode rendering with campaignnode
  web/src/enterprise.scss
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.scss
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.tsx
  web/src/enterprise/campaigns/detail/changesets/__snapshots__/ChangesetNode.test.tsx.snap
  web/src/enterprise/campaigns/list/CampaignNode.tsx
  web/src/enterprise/campaigns/list/__snapshots__/CampaignNode.test.tsx.snap
Labels: automation

#7164 a8n: Bump defaultFetchTimeout from 10s to 30s
  enterprise/internal/a8n/campaign_type.go
Labels: automation

#7076 web: Fix hiding suggestions on search submit
  web/src/search/input/QueryInput.tsx
Labels: search, web

#7143 LSIF: Return null from GitBlob's LSIF resolver when no dump exists
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  enterprise/internal/codeintel/resolvers/location.go
  enterprise/internal/codeintel/resolvers/query.go
  enterprise/internal/codeintel/resolvers/resolver.go
  lsif/docs/api.yaml
  lsif/src/server/backend/backend.ts
  lsif/src/server/routes/lsif.ts
Labels: lsif

#6894 LSIF: Replace job cleanup tasks with upload cleanup tasks
  lsif/docs/api.yaml
  lsif/docs/jobs.md
  lsif/src/server/server.ts
  lsif/src/server/settings.ts
  lsif/src/server/tasks/jobs.ts
  lsif/src/server/tasks/runner.ts
  lsif/src/server/tasks/uploads.ts
  lsif/src/shared/uploads/uploads.ts
  migrations/1528395615_lsif_commit_constraints.down.sql
  migrations/bindata.go
Labels: lsif

#7113 a8n: More extensive e2e testing
  web/src/e2e/e2e.test.ts
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.tsx
  web/src/enterprise/campaigns/detail/changesets/__snapshots__/ChangesetNode.test.tsx.snap
Labels: automation

#7163 a8n: Allow closing of changesets on codehosts when deleting campaign
  cmd/frontend/graphqlbackend/a8n.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/a8n/resolvers/resolver.go
  enterprise/internal/a8n/service.go
  internal/a8n/types.go
Labels: automation

#6835 web: Update repo and file suggestions to include regex boundaries
  web/src/search/input/QueryInput.tsx
  web/src/search/input/Suggestion.tsx
Labels: search, web

#7171 a8n: Make campaign branch names globally unique
  enterprise/internal/a8n/service.go
  go.mod
  go.sum
  internal/vcs/git/refs.go
  internal/vcs/git/refs_test.go
Labels: automation

#7173 tidy: remove redundant Sprintf
  cmd/frontend/graphqlbackend/search_alert.go
  enterprise/internal/codeintel/resolvers/query.go
Labels: campaign

#7174 tidy: convert Fprintf to Fprintln when possible
  cmd/frontend/graphqlbackend/search_pagination_test.go
  cmd/server/shared/postgres.go
  internal/debugserver/expvar.go
Labels: campaign

#7158 LSIF: Add commit to LSIF query resolver.
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/codeintel/resolvers/query.go
Labels: lsif

#6875 LSIF: Replace LSIF jobs with uploads in lsif-server
  cmd/frontend/db/schema.md
  lsif/docs/api.yaml
  lsif/docs/jobs.md
  lsif/src/server/routes/dumps.ts
  lsif/src/server/routes/lsif.ts
  lsif/src/server/routes/uploads.ts
  lsif/src/server/server.ts
  lsif/src/server/settings.ts
  lsif/src/server/tasks/jobs.ts
  lsif/src/server/tasks/runner.ts
  lsif/src/server/tasks/uploads.ts
  lsif/src/shared/database/postgres.ts
  lsif/src/shared/database/sqlite.ts
  lsif/src/shared/metrics.ts
  lsif/src/shared/models/xrepo.ts
  lsif/src/shared/uploads/uploads.ts
  lsif/src/worker/processors/convert.ts
  lsif/src/worker/settings.ts
  lsif/src/worker/worker.ts
  migrations/1528395615_lsif_commit_constraints.down.sql
  migrations/1528395615_lsif_commit_constraints.up.sql
  migrations/1528395625_lsif_uploads.down.sql
  migrations/1528395625_lsif_uploads.up.sql
  migrations/bindata.go
Labels: lsif

#7157 LSIF: Update UI to reflect change from LSIF jobs to uploads
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/codeintel/resolvers/dump.go
  enterprise/internal/codeintel/resolvers/job.go
  enterprise/internal/codeintel/resolvers/resolver.go
  enterprise/internal/codeintel/resolvers/upload.go
  internal/lsif/types.go
  web/src/enterprise/repo/settings/RepoSettingsCodeIntelligencePage.tsx
  web/src/enterprise/repo/settings/backend.tsx
  web/src/enterprise/site-admin/SiteAdmin.scss
  web/src/enterprise/site-admin/SiteAdminLsifJobPage.scss
  web/src/enterprise/site-admin/SiteAdminLsifJobPage.tsx
  web/src/enterprise/site-admin/SiteAdminLsifJobsPage.tsx
  web/src/enterprise/site-admin/SiteAdminLsifUploadPage.scss
  web/src/enterprise/site-admin/SiteAdminLsifUploadPage.tsx
  web/src/enterprise/site-admin/SiteAdminLsifUploadsPage.scss
  web/src/enterprise/site-admin/SiteAdminLsifUploadsPage.tsx
  web/src/enterprise/site-admin/backend.ts
  web/src/enterprise/site-admin/routes.ts
  web/src/enterprise/site-admin/sidebaritems.ts
Labels: lsif

#6880 LSIF: Remove dead LSIF jobs code
  CHANGELOG.md
  doc/dev/architecture/architecture.dot
  doc/dev/architecture/architecture.svg
  lsif/README.md
  lsif/docs/api.yaml
  lsif/package.json
  lsif/src/search-jobs.lua
  lsif/src/server/jobs/blocking.ts
  lsif/src/server/metrics.ts
  lsif/src/server/redis/redis.ts
  lsif/src/server/routes/jobs.ts
  lsif/src/server/server.ts
  lsif/src/server/settings.ts
  lsif/src/server/tasks/uploads.ts
  lsif/src/shared/queue/queue.ts
  lsif/src/shared/tracing.ts
  lsif/src/tests/integration/integration-test-util.ts
  lsif/src/worker/conversion/conversion.ts
  lsif/src/worker/conversion/correlator.test.ts
  lsif/src/worker/conversion/correlator.ts
  lsif/src/worker/conversion/importer.ts
  lsif/src/worker/conversion/input.test.ts
  lsif/src/worker/conversion/input.ts
  lsif/src/worker/metrics.ts
  lsif/src/worker/settings.ts
  lsif/src/worker/worker.ts
  lsif/yarn.lock
Labels: lsif

#7186 LSIF: Fix use of p-retry for LSIF uploads
  lsif/src/server/routes/dumps.ts
  lsif/src/server/routes/lsif.ts
  lsif/src/shared/uploads/uploads.ts
Labels: lsif

#7096 LSIF: Refactor lsif-server client
  enterprise/internal/codeintel/lsifserver/client/client.go
  enterprise/internal/codeintel/lsifserver/client/dump.go
  enterprise/internal/codeintel/lsifserver/client/error.go
  enterprise/internal/codeintel/lsifserver/client/query.go
  enterprise/internal/codeintel/lsifserver/client/request.go
  enterprise/internal/codeintel/lsifserver/client/upload.go
  enterprise/internal/codeintel/lsifserver/proxy/upload.go
  enterprise/internal/codeintel/resolvers/dump.go
  enterprise/internal/codeintel/resolvers/location.go
  enterprise/internal/codeintel/resolvers/query.go
  enterprise/internal/codeintel/resolvers/resolver.go
  enterprise/internal/codeintel/resolvers/upload.go
Labels: lsif

#7192 Remove /lsif-jobs/:id from router.
  web/src/enterprise/site-admin/routes.ts
Labels: lsif

#7199 LSIF: Reduce duplicate work in location resolution
  enterprise/internal/codeintel/resolvers/location.go
Labels: lsif

#7228 LSIF: Proxy body to backend on upload
  enterprise/internal/codeintel/lsifserver/client/query.go
Labels: lsif

#7226 LSIF: Remove useless indirection from backend
  lsif/src/server/backend/backend.ts
  lsif/src/server/routes/dumps.ts
  lsif/src/server/server.ts
Labels: lsif

#7223 LSIF: Increase timeout for db integration tests.
  lsif/jest.config.js
  lsif/jest.setup.js
  lsif/src/tests/integration/xrepo/commits.test.ts
  lsif/src/tests/integration/xrepo/xrepo.test.ts
  lsif/src/worker/conversion/conversion.ts
Labels: lsif

#7239 LSIF: Remove isTracked methods from xrepo class.
  lsif/src/shared/xrepo/xrepo.ts
  lsif/src/tests/integration/xrepo/commits.test.ts
Labels: lsif

#7046 a8n: Show read-only campaign fields in a grid view
  web/src/enterprise.scss
  web/src/enterprise/campaigns/detail/CampaignDetails.scss
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
Labels: automation

#7251 a8n: fix Campaign.URL (is not namespaced)
  enterprise/internal/a8n/resolvers/campaigns.go
Labels: automation

#7250 a8n: allow campaign creation from locally computed diffs
  cmd/frontend/graphqlbackend/a8n.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/a8n/campaign_type.go
  enterprise/internal/a8n/resolvers/changeset_events.go
  enterprise/internal/a8n/resolvers/resolver.go
  enterprise/internal/a8n/resolvers/resolver_test.go
  enterprise/internal/a8n/service.go
  enterprise/internal/a8n/service_test.go
  internal/a8n/types.go
Labels: automation

#7227 a8n: Handle deletion of Changesets on codehosts
  cmd/frontend/db/schema.md
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/repo-updater/repos/bitbucketserver.go
  cmd/repo-updater/repos/bitbucketserver_test.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/testdata/golden/BitbucketServerSource_LoadChangesets_subset-not-found
  cmd/repo-updater/repos/testdata/sources/BitbucketServerSource_LoadChangesets_found.yaml
  cmd/repo-updater/repos/testdata/sources/BitbucketServerSource_LoadChangesets_subset-not-found.yaml
  enterprise/internal/a8n/counts.go
  enterprise/internal/a8n/counts_test.go
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
  enterprise/internal/a8n/syncer.go
  internal/a8n/types.go
  migrations/1528395627_add_external_deleted_at_to_changesets.down.sql
  migrations/1528395627_add_external_deleted_at_to_changesets.up.sql
  migrations/bindata.go
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.test.tsx
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.tsx
  web/src/enterprise/campaigns/detail/changesets/__snapshots__/ChangesetNode.test.tsx.snap
  web/src/enterprise/campaigns/detail/changesets/presentation.ts
Labels: automation

#6661 search pagination: define behavior for cloning/missing repositories
  CHANGELOG.md
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_pagination.go
  cmd/frontend/graphqlbackend/search_pagination_test.go
Labels: search-pagination

#7259 a8n: Fix generation of diffs for files in subfolders
  enterprise/internal/a8n/campaign_type.go
Labels: automation

#7252 a8n: update wording in UI
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/global/list/GlobalCampaignListPage.tsx
Labels: automation

#7264 LSIF: Fallback to original values when project root cannot be resolved
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/codeintel/resolvers/dump.go
  enterprise/internal/codeintel/resolvers/upload.go
  web/src/enterprise/repo/settings/RepoSettingsCodeIntelligencePage.tsx
  web/src/enterprise/repo/settings/backend.tsx
  web/src/enterprise/site-admin/SiteAdminLsifUploadPage.tsx
  web/src/enterprise/site-admin/SiteAdminLsifUploadsPage.tsx
  web/src/enterprise/site-admin/backend.ts
Labels: lsif

#7277 a8n: Count CampaignJobs as completed even if they didn't produce diff
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
Labels: automation

#7292 Make search examples easier to find
  doc/_resources/templates/document.html
  doc/user/index.md
  doc/user/search/examples.md
  doc/user/search/index.md
  doc/user/search/saved_searches.md
Labels: docs

#7312 LSIF: Remove orphaned word from LSIF uploads page
  web/src/enterprise/site-admin/SiteAdminLsifUploadsPage.tsx
Labels: lsif

#7311 LSIF: Do not return an LSIF resolver when the dump does not exist.
  enterprise/internal/codeintel/resolvers/resolver.go
Labels: lsif

#7323 LSIF: Refactor tree resolution in codeintel resolvers
  enterprise/internal/codeintel/resolvers/dump.go
  enterprise/internal/codeintel/resolvers/location.go
  enterprise/internal/codeintel/resolvers/query.go
  enterprise/internal/codeintel/resolvers/resolver.go
  enterprise/internal/codeintel/resolvers/tree.go
  enterprise/internal/codeintel/resolvers/tree_collection.go
  enterprise/internal/codeintel/resolvers/upload.go
Labels: lsif

#7241 LSIF: Refactor xrepo class
  lsif/README.md
  lsif/docs/datamodel.pg.md
  lsif/src/server/backend/backend.ts
  lsif/src/server/backend/cache.ts
  lsif/src/server/backend/database.test.ts
  lsif/src/server/backend/database.ts
  lsif/src/server/routes/dumps.ts
  lsif/src/server/routes/lsif.ts
  lsif/src/server/routes/uploads.ts
  lsif/src/server/server.ts
  lsif/src/server/tasks/runner.ts
  lsif/src/server/tasks/uploads.ts
  lsif/src/shared/constants.ts
  lsif/src/shared/database/metrics.ts
  lsif/src/shared/database/postgres.ts
  lsif/src/shared/datastructures/bloom-filter.test.ts
  lsif/src/shared/datastructures/bloom-filter.ts
  lsif/src/shared/gitserver/gitserver.test.ts
  lsif/src/shared/gitserver/gitserver.ts
  lsif/src/shared/gitserver/metrics.ts
  lsif/src/shared/models/hash.ts
  lsif/src/shared/models/pg.ts
  lsif/src/shared/models/queries.ts
  lsif/src/shared/models/sqlite.ts
  lsif/src/shared/store/dependencies.ts
  lsif/src/shared/store/dumps.ts
  lsif/src/shared/store/locks.ts
  lsif/src/shared/store/metrics.ts
  lsif/src/shared/store/uploads.ts
  lsif/src/shared/xrepo/metrics.ts
  lsif/src/shared/xrepo/xrepo.ts
  lsif/src/tests/integration/backend/reference-pagination-monorepo.test.ts
  lsif/src/tests/integration/integration-test-util.ts
  lsif/src/tests/integration/store/dependencies.test.ts
  lsif/src/tests/integration/store/dumps.test.ts
  lsif/src/tests/integration/xrepo/commits.test.ts
  lsif/src/tests/integration/xrepo/xrepo.test.ts
  lsif/src/worker/conversion/conversion.ts
  lsif/src/worker/conversion/correlator.ts
  lsif/src/worker/conversion/importer.ts
  lsif/src/worker/worker.ts
Labels: lsif

#7306 support previewing existing campaign plans
  cmd/frontend/graphqlbackend/a8n.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/a8n/resolvers/campaign_plans.go
  enterprise/internal/a8n/resolvers/resolver_test.go
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
Labels: automation

#7278 a8n: GraphQL API for draft campaigns
  cmd/frontend/db/schema.md
  cmd/frontend/graphqlbackend/a8n.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/a8n/resolvers/campaign_plans.go
  enterprise/internal/a8n/resolvers/campaigns.go
  enterprise/internal/a8n/resolvers/resolver.go
  enterprise/internal/a8n/resolvers/resolver_test.go
  enterprise/internal/a8n/service.go
  enterprise/internal/a8n/service_test.go
  enterprise/internal/a8n/store.go
  enterprise/internal/a8n/store_test.go
  internal/a8n/types.go
  migrations/1528395628_add_published_at_to_campaigns.down.sql
  migrations/1528395628_add_published_at_to_campaigns.up.sql
  migrations/bindata.go
Labels: automation

#7166 docs: Add search aliases
  doc/user/search/queries.md
Labels: docs, search, web

#7256 a8n: Add UI for closing campaigns and changesets
  web/src/enterprise/campaigns/detail/CampaignDetails.scss
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/backend.ts
  web/src/enterprise/campaigns/global/list/backend.ts
  web/src/enterprise/campaigns/list/CampaignNode.tsx
  web/src/enterprise/campaigns/list/__snapshots__/CampaignNode.test.tsx.snap
Labels: automation

#7357 fix #7355: make search stats page e2e test more reliable
  web/src/e2e/e2e.test.ts
Labels: e2e-tests

#7360 e2e: sort symbols list to avoid flakiness
  web/src/e2e/e2e.test.ts
Labels: e2e-tests

#7335 LSIF: Fix bad variable reference
  lsif/src/worker/conversion/conversion.ts
Labels: lsif

#7364 remove obsolete TODO
  web/src/routes.tsx
Labels: web

#7365 remove accidental leading space from filename
  browser/src/libs/code_intelligence/extensions.test.tsx
Labels: web

#7366 use "API console" as page title for API console
  cmd/frontend/internal/app/ui/router.go
  web/src/api/APIConsole.tsx
Labels: web

#7362 remove or unexport unused TypeScript exports
  browser/src/shared/backend/server.ts
  browser/src/shared/repo/index.tsx
  browser/src/shared/util/context.tsx
  shared/src/api/client/context/expr/evaluator.ts
  shared/src/api/client/context/expr/lexer.ts
  shared/src/api/client/extension.ts
  shared/src/api/extension/api/common.ts
  shared/src/api/extension/api/types.ts
  shared/src/api/extension/api/windows.ts
  shared/src/api/extension/main.worker.ts
  shared/src/api/util.ts
  shared/src/backend/errors.ts
  shared/src/components/ShadowRoot.tsx
  shared/src/components/icons.tsx
  shared/src/extensions/ExtensionStatus.tsx
  shared/src/settings/settings.ts
  shared/src/util/url.ts
  web/src/backend/backend.ts
  web/src/components/HeroPage.tsx
  web/src/enterprise/campaigns/detail/backend.ts
  web/src/enterprise/campaigns/global/GlobalCampaignsArea.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsNewProductSubscriptionPage.tsx
  web/src/marketing/util.tsx
  web/src/repo/blob/BlobPage.tsx
  web/src/repo/settings/index.ts
  web/src/routes.tsx
  web/src/search/backend.tsx
  web/src/search/helpers.tsx
  web/src/search/input/Suggestion.tsx
  web/src/search/input/interactive/AddFilterRow.tsx
  web/src/settings/configuration.ts
  web/src/site-admin/backend.tsx
  web/src/site-admin/configHelpers.ts
  web/src/site-admin/externalServices.tsx
  web/src/util/url.ts
Labels: web

#7361 remove unused pages (routes and components)
  browser/src/shared/backend/server.ts
  browser/src/shared/repo/index.tsx
  browser/src/shared/util/context.tsx
  cmd/frontend/internal/app/assets/img/Homepage/homepage-mobile.svg
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/router.go
  cmd/frontend/internal/app/ui/router_test.go
  shared/src/api/client/context/expr/evaluator.ts
  shared/src/api/client/context/expr/lexer.ts
  shared/src/api/client/extension.ts
  shared/src/api/extension/api/common.ts
  shared/src/api/extension/api/types.ts
  shared/src/api/extension/api/windows.ts
  shared/src/api/extension/main.worker.ts
  shared/src/api/util.ts
  shared/src/backend/errors.ts
  shared/src/components/ShadowRoot.tsx
  shared/src/components/icons.tsx
  shared/src/extensions/ExtensionStatus.tsx
  shared/src/settings/settings.ts
  shared/src/util/url.ts
  web/src/SourcegraphWebApp.scss
  web/src/backend/backend.ts
  web/src/components/HeroPage.tsx
  web/src/enterprise/campaigns/detail/backend.ts
  web/src/enterprise/campaigns/global/GlobalCampaignsArea.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsNewProductSubscriptionPage.tsx
  web/src/marketing/util.tsx
  web/src/open/OpenPage.scss
  web/src/open/OpenPage.tsx
  web/src/repo/blob/BlobPage.tsx
  web/src/repo/settings/index.ts
  web/src/routes.tsx
  web/src/savedSearches/RedirectToUserSavedSearches.tsx
  web/src/search/backend.tsx
  web/src/search/helpers.tsx
  web/src/search/input/Suggestion.tsx
  web/src/search/input/interactive/AddFilterRow.tsx
  web/src/settings/configuration.ts
  web/src/site-admin/backend.tsx
  web/src/site-admin/configHelpers.ts
  web/src/site-admin/externalServices.tsx
  web/src/util/url.ts
Labels: web

#7374 clearer search result tab names
  CHANGELOG.md
  web/src/e2e/e2e.test.ts
  web/src/search/results/SearchResultTab.tsx
Labels: web

#7377 skip flaky symbols e2e tests
  web/src/e2e/e2e.test.ts
Labels: e2e-tests

#7381 improve search query syntax docs
  doc/user/search/queries.md
Labels: docs, search

#7382 simplify SearchScopes component
  web/src/search/input/SearchFilterChips.tsx
  web/src/search/input/SearchPage.scss
  web/src/search/input/SearchPage.tsx
  web/src/search/input/SearchScopes.scss
  web/src/search/input/SearchScopes.test.tsx
  web/src/search/input/SearchScopes.tsx
  web/src/search/input/__snapshots__/SearchScopes.test.tsx.snap
  web/src/search/results/SearchResults.tsx
Labels: search, web

#7386 vscode settings: fix eslint.validate deprecation
  .vscode/settings.json
Labels: web

#7384 use eslint cache
  .gitignore
  .vscode/settings.json
  browser/package.json
  lsif/package.json
  shared/package.json
  web/package.json
Labels: web

#7385 QueryBuilder: show on its own page, link from home
  CHANGELOG.md
  cmd/frontend/internal/app/ui/router.go
  web/src/Layout.tsx
  web/src/SourcegraphWebApp.scss
  web/src/routes.tsx
  web/src/search/input/InfoDropdown.tsx
  web/src/search/input/QueryBuilder.tsx
  web/src/search/input/SearchPage.scss
  web/src/search/input/SearchPage.tsx
  web/src/search/input/SearchScopes.tsx
  web/src/search/input/__snapshots__/SearchScopes.test.tsx.snap
  web/src/search/input/interactive/SearchModeToggle.tsx
  web/src/search/queryBuilder/QueryBuilder.scss
  web/src/search/queryBuilder/QueryBuilder.test.tsx
  web/src/search/queryBuilder/QueryBuilder.tsx
  web/src/search/queryBuilder/QueryBuilderInputRow.scss
  web/src/search/queryBuilder/QueryBuilderInputRow.tsx
  web/src/search/queryBuilder/QueryBuilderPage.test.tsx
  web/src/search/queryBuilder/QueryBuilderPage.tsx
  web/src/search/queryBuilder/__snapshots__/QueryBuilderPage.test.tsx.snap
  web/src/search/queryBuilder/index.scss
Labels: search, web

#7387 GlobalNavbar: show nav links when hideGlobalSearchInput is true
  web/src/nav/GlobalNavbar.tsx
Labels: web

#7389 PersonLink: consolidate PersonName component
  web/src/person/PersonLink.test.tsx
  web/src/person/PersonLink.tsx
  web/src/person/__snapshots__/PersonLink.test.tsx.snap
  web/src/repo/commits/GitCommitNodeByline.test.tsx
  web/src/repo/commits/GitCommitNodeByline.tsx
  web/src/repo/commits/RepositoryCommitsPage.tsx
  web/src/repo/commits/__snapshots__/GitCommitNodeByline.test.tsx.snap
  web/src/repo/stats/RepositoryStatsContributorsPage.tsx
  web/src/user/PersonLink.test.tsx
  web/src/user/PersonLink.tsx
Labels: web
