Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2019-05, with the labels that each got.

#3670 site-admin: Add commented-out repositoryQuery to default configs
  web/src/site-admin/externalServices.tsx
Labels: site-admin

#3676 clarify nature of Phabricator integration in docs
  doc/admin/external_service/phabricator.md
  doc/integration/phabricator.md
  web/src/site-admin/externalServices.tsx
Labels: team/core-services

#3745 repo-updater: Hard deletes and fixes for swapped repos
  cmd/frontend/db/discussion_comments_test.go
  cmd/frontend/db/repos.go
  cmd/frontend/db/schema.md
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
  cmd/repo-updater/repos/observability.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testing.go
  cmd/repo-updater/repoupdater/server_test.go
  migrations/1528395574_.down.sql
  migrations/1528395574_.up.sql
  migrations/1528395575_.down.sql
  migrations/1528395575_.up.sql
  migrations/bindata.go
Labels: team/core-services

#3699 redirect unauthed users on sourcegraph.com to about.sourcegraph.com
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/handlers_test.go
Labels: web

#3775 repo-updater: Increase sourceTimeout to 30 minutes
  cmd/repo-updater/repos/sources.go
Labels: team/core-services

#3773 conf: Custom reposource validates proposed config
  pkg/conf/reposource/custom.go
Labels: team/core-services

#3801 Prevent duplicate packages in node_modules
  cmd/management-console/web/yarn.lock
  dev/check/all.sh
  dev/check/yarn-deduplicate.sh
  package.json
  yarn.lock
Labels: ops & tools & dev

#3780 Add an example for `branding` site configuration
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: docs

#3776 repo-updater: Drop repo trigger set_repo_name and unused repo columns
  cmd/frontend/db/schema.md
  migrations/1528395576_.down.sql
  migrations/1528395576_.up.sql
  migrations/bindata.go
Labels: team/core-services

#3810 make search results take up full width, less spacing
  shared/src/components/FileMatchChildren.scss
  shared/src/components/ResultContainer.scss
  web/src/search/results/SearchResultsInfoBar.tsx
  web/src/search/results/SearchResultsList.scss
  web/src/search/results/SearchResultsList.test.tsx
  web/src/search/results/SearchResultsList.tsx
Labels: design, search, web

#3813 Call setLinkComponent in Phabricator entry point
  client/browser/src/libs/phabricator/extension.tsx
Labels: bug, code-nav, phabricator

#3816 httpcli: Separate Doer and Client methods in Factory
  cmd/repo-updater/repos/bitbucketserver.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/gitlab.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/util.go
  pkg/extsvc/phabricator/client_test.go
  pkg/httpcli/client.go
Labels: team/core-services

#3797 docs: remove links to archived pages
  doc/_resources/templates/doc.html
  doc/admin/install/docker/index.md
  doc/admin/install/kubernetes_cluster.md
  doc/admin/migration/opengrok.md
  doc/admin/site_config/all.md
  doc/admin/site_config/index.md
  doc/extensions/authoring/tutorials/button-custom-commands.md
  doc/extensions/authoring/tutorials/hello-world.md
  doc/extensions/authoring/tutorials/lang-specific-extension-tutorial.md
  doc/quickstart.md
Labels: docs

#3606 Use modern browser API
  client/browser/babel.config.js
  client/browser/config/webpack/base.config.ts
  client/browser/scripts/dev.ts
  client/browser/src/browser/ExtensionStorageSubject.ts
  client/browser/src/browser/browserAction.ts
  client/browser/src/browser/omnibox.ts
  client/browser/src/browser/permissions.ts
  client/browser/src/browser/runtime.ts
  client/browser/src/browser/storage.ts
  client/browser/src/browser/storage_migrations.ts
  client/browser/src/browser/tabs.ts
  client/browser/src/browser/types.ts
  client/browser/src/context.ts
  client/browser/src/extension/scripts/background.tsx
  client/browser/src/extension/scripts/inject.tsx
  client/browser/src/extension/scripts/options.tsx
  client/browser/src/libs/cli/index.ts
  client/browser/src/libs/cli/search.ts
  client/browser/src/libs/code_intelligence/code_intelligence.tsx
  client/browser/src/libs/code_intelligence/external_links.tsx
  client/browser/src/libs/options/OptionsContainer.test.tsx
  client/browser/src/libs/options/OptionsContainer.tsx
  client/browser/src/libs/phabricator/backend.tsx
  client/browser/src/libs/sentry/index.ts
  client/browser/src/platform/context.ts
  client/browser/src/platform/extensionHost.ts
  client/browser/src/platform/settings.ts
  client/browser/src/shared/backend/graphql.ts
  client/browser/src/shared/backend/headers.tsx
  client/browser/src/shared/backend/userEvents.tsx
  client/browser/src/shared/components/NeedsRepositoryConfigurationAlert.tsx
  client/browser/src/shared/components/ServerAlert.tsx
  client/browser/src/shared/tracking/EventLogger.tsx
  client/browser/src/shared/util/browser.ts
  client/browser/src/shared/util/context.tsx
  client/browser/src/shared/util/featureFlags.ts
  client/browser/src/types/web-extensions/index.d.ts
  client/browser/tsconfig.json
  jest.config.base.js
  package.json
  shared/dev/globalThis.js
  shared/src/settings/settings.test.ts
  shared/src/settings/settings.ts
  shared/src/util/types.ts
  web/babel.config.js
  yarn.lock
Labels: browser-extension

#3809 factor out SearchResultsFilterBars
  web/src/search/results/SearchResults.scss
  web/src/search/results/SearchResults.tsx
  web/src/search/results/SearchResultsFilterBars.scss
  web/src/search/results/SearchResultsFilterBars.tsx
Labels: search, web

#3815 Better Phabricator test plan
  doc/dev/phabricator_gitolite.md
Labels: code-nav, phabricator

#3840 use more compatible flexbox align-items: flex-start value
  shared/src/notifications/NotificationItem.scss
  web/src/marketing/Toast.scss
  web/src/org/invite/InviteForm.scss
Labels: web

#3844 docs: Fix link to Sourcegraph extensions page
  doc/user/code_intelligence/index.md
Labels: docs

#3839 Simplify options page CSS
  browser/config/webpack/base.config.ts
  browser/src/app.scss
  browser/src/extension/manifest.spec.json
  browser/src/extension/scripts/options.tsx
  browser/src/extension/views/options.html
  browser/src/global-styles/colors.scss
  browser/src/libs/options/OptionsContainer.scss
  browser/src/libs/options/OptionsContainer.tsx
  browser/src/libs/options/OptionsHeader.scss
  browser/src/libs/options/OptionsHeader.tsx
  browser/src/libs/options/OptionsMenu.scss
  browser/src/libs/options/OptionsMenu.test.tsx
  browser/src/libs/options/OptionsMenu.tsx
  browser/src/libs/options/ServerURLForm.scss
  browser/src/libs/options/ServerURLForm.tsx
  browser/src/libs/options/__snapshots__/OptionsMenu.test.tsx.snap
  browser/src/libs/options/styles.scss
  browser/src/options.scss
Labels: browser-extension

#3848 repo-updater: Support external_id migrations
  cmd/repo-updater/repos/syncer.go
  cmd/repo-updater/repos/syncer_test.go
  pkg/api/api.go
Labels: team/core-services

#3850 repo-updater: Reset Bitbucket Server external ids
  migrations/1528395577_.up.sql
  migrations/bindata.go
Labels: team/core-services

#3883 Add tests for GitHub parseUrl()
  browser/src/libs/github/__snapshots__/util.test.ts.snap
  browser/src/libs/github/util.test.ts
  browser/src/libs/github/util.tsx
Labels: browser-extension, code-nav

#3879 repo-updater: Use original metadata object in Exclude
  cmd/repo-updater/repos/migrations_test.go
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repos/types_test.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: team/core-services

#3811 Fix small editor
  CHANGELOG.md
  web/src/settings/SettingsFile.scss
Labels: important

#3884 repo-updater: Integrate Gitolite with the new syncer
  CHANGELOG.md
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/gitolite.go
  cmd/repo-updater/repos/migrations_test.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testdata/sources/GITOLITE/excluded-repos-are-never-yielded.yaml
  cmd/repo-updater/repos/testdata/sources/GITOLITE/repositoryPathPattern-determines-the-repo-name.yaml
  cmd/repo-updater/repos/testdata/sources/excluded-repos-are-never-yielded.yaml
  cmd/repo-updater/repos/testdata/sources/included-repos-that-exist-are-yielded.yaml
  cmd/repo-updater/repos/testdata/sources/phabricator.yaml
  cmd/repo-updater/repos/testdata/sources/repositoryPathPattern-determines-the-repo-name.yaml
  cmd/repo-updater/repos/testdata/sources/yielded-repos-are-always-enabled.yaml
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repos/types_test.go
  cmd/repo-updater/repoupdater/server.go
  enterprise/cmd/frontend/db/external_services_test.go
  schema/gitolite.schema.json
  schema/gitolite_stringdata.go
  schema/schema.go
Labels: team/core-services

#3878 repo-updater: Migrate AWS CodeCommit to new syncer
  CHANGELOG.md
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/awscodecommit.go
  cmd/repo-updater/repos/awscodecommit_test.go
  cmd/repo-updater/repos/migrations_test.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testdata/sources/AWSCODECOMMIT/excluded-repos-are-never-yielded.yaml
  cmd/repo-updater/repos/testdata/sources/AWSCODECOMMIT/included-repos-that-exist-are-yielded.yaml
  cmd/repo-updater/repos/testdata/sources/AWSCODECOMMIT/repositoryPathPattern-determines-the-repo-name.yaml
  cmd/repo-updater/repos/testdata/sources/AWSCODECOMMIT/yielded-repos-are-always-enabled.yaml
  cmd/repo-updater/repos/testdata/sources/AWSCODECOMMIT/yielded-repos-have-authenticated-CloneURLs.yaml
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repos/types_test.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  doc/admin/external_service/aws_codecommit.md
  enterprise/cmd/frontend/db/external_services_test.go
  migrations/1528395577_.up.sql
  migrations/bindata.go
  pkg/extsvc/awscodecommit/codehost.go
  schema/aws_codecommit.schema.json
  schema/aws_codecommit_stringdata.go
  schema/schema.go
Labels: team/core-services

#3292 Refactor browser extension graphql functions
  browser/src/browser/types.ts
  browser/src/context.ts
  browser/src/extension/scripts/background.tsx
  browser/src/extension/scripts/inject.tsx
  browser/src/extension/scripts/options.tsx
  browser/src/libs/bitbucket/code_intelligence.tsx
  browser/src/libs/bitbucket/context.tsx
  browser/src/libs/cli/index.ts
  browser/src/libs/cli/search.ts
  browser/src/libs/code_intelligence/ extensions.test.tsx
  browser/src/libs/code_intelligence/code_intelligence.test.tsx
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/code_views.ts
  browser/src/libs/code_intelligence/extensions.tsx
  browser/src/libs/code_intelligence/external_links.test.tsx
  browser/src/libs/code_intelligence/external_links.tsx
  browser/src/libs/code_intelligence/util/file_info.ts
  browser/src/libs/github/code_intelligence.ts
  browser/src/libs/github/file_info.ts
  browser/src/libs/gitlab/code_intelligence.ts
  browser/src/libs/phabricator/backend.tsx
  browser/src/libs/phabricator/code_intelligence.ts
  browser/src/libs/phabricator/extension.tsx
  browser/src/libs/phabricator/file_info.ts
  browser/src/libs/phabricator/util.tsx
  browser/src/platform/context.test.tsx
  browser/src/platform/context.ts
  browser/src/platform/settings.ts
  browser/src/shared/backend/context.ts
  browser/src/shared/backend/diffs.tsx
  browser/src/shared/backend/graphql.test.tsx
  browser/src/shared/backend/graphql.ts
  browser/src/shared/backend/headers.ts
  browser/src/shared/backend/search.tsx
  browser/src/shared/backend/server.ts
  browser/src/shared/backend/userEvents.tsx
  browser/src/shared/components/CodeViewToolbar.tsx
  browser/src/shared/components/GlobalDebug.tsx
  browser/src/shared/components/OpenDiffOnSourcegraph.tsx
  browser/src/shared/components/OpenOnSourcegraph.tsx
  browser/src/shared/repo/backend.tsx
  browser/src/shared/repo/index.tsx
  browser/src/shared/util/context.tsx
  browser/src/shared/util/url.test.ts
  browser/src/shared/util/url.ts
  shared/src/api/client/services.test.ts
  shared/src/api/client/services.ts
  shared/src/api/client/services/command.ts
  shared/src/api/client/services/extensionsService.test.ts
  shared/src/api/client/services/extensionsService.ts
  shared/src/api/integration-test/testHelpers.ts
  shared/src/commands/commands.ts
  shared/src/extensions/helpers.ts
  shared/src/graphql/graphql.ts
  shared/src/platform/context.ts
  shared/src/settings/edit.ts
  web/src/backend/graphql.tsx
  web/src/extensions/ExtensionsList.tsx
  web/src/extensions/ExtensionsOverviewPage.tsx
  web/src/platform/context.ts
Labels: browser-extension, code-nav, debt

#3916 docs: now has icon and no redundant `- Sourcegraph` in <title> on home page
  doc/_resources/assets/sourcegraph-mark.png
  doc/_resources/templates/doc.html
Labels: docs

#3919 Import bootstrap alert scss in options.scss
  browser/src/options.scss
Labels: browser-extension, bug

#3918 repo-updater: Add AWSCodeCommitSetBogusGitCredentialsMigration
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
Labels: team/core-services

#3926 repo-updater: Do not sort in equality assertions
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testing.go
Labels: team/core-services

#3925 extsvc/gitolite: Support URL format in git clone URLs
  CHANGELOG.md
  pkg/extsvc/gitolite/repos.go
  pkg/extsvc/gitolite/repos_test.go
  schema/gitolite.schema.json
  schema/gitolite_stringdata.go
Labels: team/core-services

#3944 remove hacks for importing LoadingSpinner CSS
  .storybook/webpack.config.ts
  browser/config/webpack/base.config.ts
  shared/src/hover/HoverOverlay.scss
  web/src/SourcegraphWebApp.scss
  web/webpack.config.ts
Labels: web

#3955 split up SignUp{Form,Page} into 2 separate files, 1 per component
  web/src/auth/SignUpForm.tsx
  web/src/auth/SignUpPage.tsx
  web/src/site-admin/SiteInitPage.tsx
Labels: web

#3954 handle @babel/polyfill deprecation
  package.json
  shared/src/polyfills.ts
  yarn.lock
Labels: web

#3953 yarn upgrade -L webpack webpack-dev-server @types/webpack @types/webpack-dev-server
  package.json
  yarn.lock
Labels: web

#3945 remove unneeded Webpack hack for @sqs/jsonc-parser
  web/webpack.config.ts
Labels: web

#3923 repo-updater: Set log15 to DiscardHandler in tests
  cmd/frontend/backend/repos_test.go
  cmd/repo-updater/repos/util_test.go
Labels: team/core-services

#3921 repo-updater: Optimise EnabledStateDeprecationMigration
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/migrations_test.go
Labels: team/core-services

#3922 repo-updater: Use URI field as fallback for repos.GetByName
  CHANGELOG.md
  cmd/frontend/db/repos.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/types.go
Labels: team/core-services

#3965 fix websocket reload loop
  web/gulpfile.ts
Labels: web

#3994 repo-updater: Add index on repo.uri
  cmd/frontend/db/schema.md
  migrations/1528395579_.down.sql
  migrations/1528395579_.up.sql
  migrations/bindata.go
Labels: team/core-services

#3968 frontend: Deprecate enable/disable fields in GraphQL schema
  CHANGELOG.md
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: team/core-services

#3969 frontend: Remove Enabled field from types.Repo
  cmd/frontend/backend/go_importers.go
  cmd/frontend/backend/go_importers_test.go
  cmd/frontend/backend/repos_test.go
  cmd/frontend/db/repos.go
  cmd/frontend/db/repos_mock.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/types/types.go
Labels: team/core-services

#3995 frontend: Return URI in Graphql API
  cmd/frontend/db/repos.go
  cmd/frontend/db/repos_db_test.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/types/types.go
Labels: team/core-services

#3981 Fix commit view resolution when using Refined GitHub
  browser/src/libs/github/util.tsx
Labels: browser-extension, bug, code-nav, github

#3967 repo-updater: load data solely from database in `RepoLookup`
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/testdata/sources/GITHUB-DOT-COM/found.yaml
  cmd/repo-updater/repos/testdata/sources/GITHUB-DOT-COM/not-found.yaml
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: team/core-services

#3998 frontend: Remove allowEnableDisable GraphQL field
  cmd/frontend/db/repos.go
  cmd/frontend/graphqlbackend/internal.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: team/core-services

#3980 web: RepositoryErrorPage is now RepositoryNotFoundPage
  web/src/repo/RepoContainer.scss
  web/src/repo/RepoContainer.tsx
  web/src/repo/RepositoryErrorPage.tsx
  web/src/repo/RepositoryNotFoundPage.scss
  web/src/repo/RepositoryNotFoundPage.tsx
Labels: team/core-services

#4000 repo-updater: Remove syncer feature flag and remove old code
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/awscodecommit.go
  cmd/repo-updater/repos/awscodecommit_test.go
  cmd/repo-updater/repos/bitbucketserver.go
  cmd/repo-updater/repos/bitbucketserver_test.go
  cmd/repo-updater/repos/github.go
  cmd/repo-updater/repos/github_test.go
  cmd/repo-updater/repos/gitlab.go
  cmd/repo-updater/repos/gitolite.go
  cmd/repo-updater/repos/metrics.go
  cmd/repo-updater/repos/migrations.go
  cmd/repo-updater/repos/other.go
  cmd/repo-updater/repos/phabricator.go
  cmd/repo-updater/repos/sources.go
  cmd/repo-updater/repos/sources_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/syncer.go
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-path-pattern.golden
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-simple.golden
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-ssh.golden
  cmd/repo-updater/repos/testdata/bitbucketserver-repos-username.golden
  cmd/repo-updater/repos/util.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: team/core-services

#4030 repo-updater: Fix flaky test & make Github client consistent
  cmd/repo-updater/repos/sources_test.go
  pkg/extsvc/github/repos.go
  pkg/extsvc/github/repos_test.go
Labels: team/core-services

#4035 fix PHABRICATOR_ASSETS_DIRECTORY
  browser/gulpfile.ts
Labels: code-nav, phabricator

#4029 Open ActionItem links in new tabs
  shared/src/actions/ActionItem.tsx
  shared/src/components/LinkOrButton.tsx
Labels: extensions

#4025 Make context expression evaluation efficient
  browser/src/libs/code_intelligence/code_intelligence.test.tsx
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/text_fields.test.tsx
  shared/src/actions/ActionItem.tsx
  shared/src/actions/actions.ts
  shared/src/api/client/api/extensions.ts
  shared/src/api/client/connection.ts
  shared/src/api/client/context/context.test.ts
  shared/src/api/client/context/context.ts
  shared/src/api/client/context/contextService.test.ts
  shared/src/api/client/context/contextService.ts
  shared/src/api/client/context/expr/evaluator.test.ts
  shared/src/api/client/context/expr/evaluator.ts
  shared/src/api/client/context/expr/parser.test.ts
  shared/src/api/client/context/expr/parser.ts
  shared/src/api/client/services/contribution.test.ts
  shared/src/api/client/services/contribution.ts
  shared/src/api/client/services/editorService.ts
  shared/src/api/client/services/extensionsService.ts
  shared/src/api/integration-test/windows.test.ts
  shared/src/api/protocol/contribution.ts
  shared/src/commandPalette/CommandList.tsx
  shared/src/commands/commands.ts
  shared/src/contributions/contributions.ts
  shared/src/extensions/controller.ts
  shared/src/extensions/extensionManifest.ts
  shared/src/hover/actions.test.ts
  shared/src/hover/actions.ts
  shared/src/panel/views/HierarchicalLocationsView.test.tsx
  shared/src/panel/views/HierarchicalLocationsView.tsx
  shared/src/panel/views/contributions.ts
  shared/src/schema/extensionSchema.ts
  web/src/repo/blob/Blob.tsx
  web/src/search/results/SearchResults.tsx
Labels: browser-extension

#3920 Fix GitHub snippet resolution
  browser/src/libs/github/__snapshots__/util.test.ts.snap
  browser/src/libs/github/code_intelligence.ts
  browser/src/libs/github/file_info.ts
  browser/src/libs/github/index.tsx
  browser/src/libs/github/util.test.ts
  browser/src/libs/github/util.tsx
Labels: browser-extension, code-nav, github, github-enterprise

#3977 Fix handling of branch names containing forward slashes
  browser/src/libs/github/__snapshots__/util.test.ts.snap
  browser/src/libs/github/code_intelligence.ts
  browser/src/libs/github/dom_functions.ts
  browser/src/libs/github/file_info.ts
  browser/src/libs/github/index.tsx
  browser/src/libs/github/util.test.ts
  browser/src/libs/github/util.tsx
Labels: browser-extension, code-nav, github, github-enterprise

#4041 Make decorations performant
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/extensions.tsx
Labels: browser-extension

#4099 Added trailing commas for root level items in external services
  web/src/site-admin/externalServices.tsx
Labels: docs, team/core-services

#4059 repo-updater: Use NewDiff instead of Upsert for sourcegraph.com repoLookup
  cmd/repo-updater/main.go
  cmd/repo-updater/repos/integration_test.go
  cmd/repo-updater/repos/store.go
  cmd/repo-updater/repos/store_test.go
  cmd/repo-updater/repos/syncer.go
  cmd/repo-updater/repos/syncer_test.go
  cmd/repo-updater/repos/testing.go
  cmd/repo-updater/repos/types.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: team/core-services

#4100 do not show errors for trailing commas in web JSON editors
  schema/aws_codecommit.schema.json
  schema/aws_codecommit_stringdata.go
  schema/bitbucket_server.schema.json
  schema/bitbucket_server_stringdata.go
  schema/critical.schema.json
  schema/critical_stringdata.go
  schema/github.schema.json
  schema/github_stringdata.go
  schema/gitlab.schema.json
  schema/gitlab_stringdata.go
  schema/gitolite.schema.json
  schema/gitolite_stringdata.go
  schema/other_external_service.schema.json
  schema/other_external_service_stringdata.go
  schema/phabricator.schema.json
  schema/phabricator_stringdata.go
  schema/settings.schema.json
  schema/settings_stringdata.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: release-blocker, web

#4053 docs: add devrel release issue template
  doc/_resources/templates/doc.html
  doc/dev/devrel_release_issue_template.md
  doc/dev/releases.md
Labels: docs

#4128 web: Remove NoRepositoriesEnabledAlert and noRepositoriesEnabled flag
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/graphqlbackend/site_flags.go
  web/src/global/GlobalAlerts.tsx
  web/src/marketing/IntegrationsToast.tsx
  web/src/site/NoRepositoriesEnabledAlert.tsx
  web/src/site/backend.tsx
  web/src/site/index.ts
Labels: release-blocker, team/core-services

#4153 docs: add step for posting tweet or email content on LinkedIn
  doc/dev/devrel_release_issue_template.md
Labels: docs

#4159 web: Follow-up on review suggestions
  web/src/site-admin/SiteAdminAddExternalServicePage.tsx
  web/src/site-admin/SiteAdminExternalServicePage.tsx
Labels: web

#4144 support right-hand resizable panels
  shared/src/components/Resizable.scss
  shared/src/components/Resizable.tsx
Labels: web

#4142 fix infinite loading indicator on empty commit results
  web/src/components/SearchResultMatch.tsx
Labels: web

#4143 move DidSearch activation step recording to central submitSearch function
  web/src/repo/TreePage.tsx
  web/src/search/helpers.tsx
  web/src/search/input/SearchButton.tsx
  web/src/search/input/SearchNavbarItem.tsx
  web/src/search/input/SearchPage.tsx
Labels: web

#3956 use lazyComponent wrapper for React lazy-loaded components
  web/src/enterprise/dotcom/welcome/routes.ts
  web/src/enterprise/explore/exploreSections.ts
  web/src/enterprise/explore/exploreSections.tsx
  web/src/enterprise/extensions/extension/routes.tsx
  web/src/enterprise/extensions/routes.ts
  web/src/enterprise/routes.tsx
  web/src/enterprise/site-admin/overviewComponents.ts
  web/src/enterprise/site-admin/routes.ts
  web/src/enterprise/site-admin/routes.tsx
  web/src/enterprise/user/settings/routes.ts
  web/src/enterprise/user/settings/routes.tsx
  web/src/explore/exploreSections.ts
  web/src/explore/exploreSections.tsx
  web/src/extensions/extension/routes.tsx
  web/src/extensions/routes.tsx
  web/src/repo/routes.tsx
  web/src/routes.tsx
  web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
  web/src/settings/SettingsFile.tsx
  web/src/site-admin/routes.tsx
  web/src/user/area/routes.tsx
  web/src/user/settings/routes.tsx
  web/src/util/lazyComponent.tsx
Labels: web

#4170 docs: add section to Administration FAQ page and create troubleshooting page
  doc/_resources/templates/doc.html
  doc/admin/faq.md
  doc/admin/troubleshooting.md
Labels: docs

#4172 Fix registerExtensionContributions()
  shared/src/extensions/controller.test.ts
  shared/src/extensions/controller.ts
Labels: bug, code-nav, extensions

#4181 fix route definition errors for saved searches that caused those user pages to be blank
  web/src/user/area/routes.tsx
Labels: web

#4201 schema/docs: Explain when `serviceProviderIssuer` is required
  schema/critical.schema.json
  schema/critical_stringdata.go
Labels: docs

#4227 Fix single file code view detection on recent Phabricator versions
  browser/src/libs/phabricator/code_intelligence.ts
  browser/src/libs/phabricator/dom_functions.ts
Labels: bug, code-nav, phabricator

#4189 Fixes #3769 by documenting how our Markdown is rendered
  doc/user/markdown.md
Labels: docs

#4248 Add DOM function tests for all code hosts
  browser/src/libs/bitbucket/__fixtures__/code-views/pr-modified.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/split/added.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/split/copied.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/split/deleted.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/split/modified.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/split/moved.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/split/renamed.html
  browser/src/libs/bitbucket/__fixtures__/code-views/pull-request/unified/modified.html
  browser/src/libs/bitbucket/__fixtures__/code-views/single-file-diff.html
  browser/src/libs/bitbucket/__fixtures__/code-views/single-file-source.html
  browser/src/libs/bitbucket/__snapshots__/dom_functions.test.ts.snap
  browser/src/libs/bitbucket/code_intelligence.test.ts
  browser/src/libs/bitbucket/dom_functions.test.ts
  browser/src/libs/bitbucket/scrape.test.ts
  browser/src/libs/bitbucket/test-code-views.ts
  browser/src/libs/code_intelligence/code_intelligence_test_utils.ts
  browser/src/libs/github/__fixtures__/ghe-2.14.11/blob/refined-github/code-view.html
  browser/src/libs/github/__fixtures__/ghe-2.14.11/blob/vanilla/code-view.html
  browser/src/libs/github/__fixtures__/github.com/blob/refined-github/code-view.html
  browser/src/libs/github/__fixtures__/github.com/blob/refined-github/page.html
  browser/src/libs/github/__fixtures__/github.com/blob/vanilla/code-view.html
  browser/src/libs/github/__fixtures__/github.com/blob/vanilla/page.html
  browser/src/libs/github/__snapshots__/dom_functions.test.ts.snap
  browser/src/libs/github/dom_functions.test.ts
  browser/src/libs/gitlab/__fixtures__/code-views/blob.html
  browser/src/libs/gitlab/__fixtures__/code-views/merge-request/split.html
  browser/src/libs/gitlab/__fixtures__/code-views/merge-request/unified.html
  browser/src/libs/gitlab/__fixtures__/code-views/pr-unified.html
  browser/src/libs/gitlab/__snapshots__/dom_functions.test.ts.snap
  browser/src/libs/gitlab/code_intelligence.test.ts
  browser/src/libs/gitlab/dom_functions.test.ts
  browser/src/libs/phabricator/__fixtures__/code-views/commit/split.html
  browser/src/libs/phabricator/__fixtures__/code-views/commit/unified.html
  browser/src/libs/phabricator/__fixtures__/code-views/diff-side-by-side.html
  browser/src/libs/phabricator/__fixtures__/code-views/differential/split.html
  browser/src/libs/phabricator/__fixtures__/code-views/differential/unified.html
  browser/src/libs/phabricator/__fixtures__/code-views/diffusion.html
  browser/src/libs/phabricator/__snapshots__/dom_functions.test.ts.snap
  browser/src/libs/phabricator/code_intelligence.test.ts
  browser/src/libs/phabricator/code_intelligence.ts
  browser/src/libs/phabricator/dom_functions.test.ts
Labels: browser-extension

#4276 repo-updater: Move GithubSource test to github_test.go
  cmd/repo-updater/repos/github_test.go
  cmd/repo-updater/repos/sources_test.go
Labels: team/core-services
