Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2020-04, with the labels that each got.

#9438 Always show burndown chart for 7 days if campaign is not older
  enterprise/internal/campaigns/resolvers/campaigns.go
Labels: campaigns

#9416 Improve changeset creation errors
  .storybook/webpack.config.ts
  enterprise/internal/campaigns/workers.go
  package.json
  web/src/enterprise/campaigns/detail/CampaignStatus.story.tsx
  web/src/enterprise/campaigns/detail/CampaignStatus.tsx
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignStatus.test.tsx.snap
  yarn.lock
Labels: campaigns, design

#9419 Improve query speed for extension registry
  enterprise/cmd/frontend/internal/registry/releases_db.go
Labels: perf, team/core-services

#9225 Remove scoped search bar from TreePage, scope global query to the current tree or file instead
  CHANGELOG.md
  web/src/e2e/e2e.test.ts
  web/src/repo/RepoContainer.tsx
  web/src/repo/TreePage.tsx
  web/src/search/ScopePage.tsx
  web/src/search/index.tsx
  web/src/search/input/QueryInput.tsx
Labels: team/web, webapp

#9518 Quickfix the debug menu background
  browser/src/shared.scss
Labels: browser-extension, extensions, team/web

#9490 Use error names instead of error codes
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/code_views.ts
  browser/src/libs/code_intelligence/util/file_info.ts
  browser/src/libs/options/OptionsContainer.tsx
  browser/src/libs/phabricator/backend.tsx
  browser/src/shared/repo/backend.tsx
  package.json
  shared/src/api/client/services/editorService.ts
  shared/src/api/extension/api/common.ts
  shared/src/api/extension/api/documents.ts
  shared/src/backend/errors.ts
  shared/src/backend/fetch.ts
  shared/src/graphql/graphql.ts
  shared/src/hover/HoverOverlay.test.tsx
  shared/src/hover/actions.ts
  shared/src/util/errors.ts
  web/src/regression/util/api.ts
  web/src/repo/RepoContainer.tsx
  web/src/repo/RepoRevContainer.tsx
  web/src/repo/RepositoryGitDataContainer.tsx
  web/src/search/results/SearchResultsList.test.tsx
  yarn.lock
Labels: debt

#9503 Fix action bar design
  shared/src/actions/ActionItem.scss
  shared/src/actions/ActionItem.tsx
  shared/src/actions/ActionsNavItems.tsx
  shared/src/actions/__snapshots__/ActionItem.test.tsx.snap
  shared/src/actions/__snapshots__/ActionsNavItems.test.tsx.snap
  shared/src/components/LinkOrButton.tsx
  shared/src/components/__snapshots__/LinkOrButton.test.tsx.snap
  web/src/components/Breadcrumb.scss
  web/src/repo/RepoHeader.scss
  web/src/repo/RepoHeader.tsx
Labels: design, extensions, team/web, webapp

#9517 Dont break GitHub file toolbar
  browser/.stylelintrc.json
  browser/src/libs/github/code_intelligence.ts
  browser/src/libs/github/style.scss
  browser/src/libs/phabricator/code_intelligence.ts
Labels: browser-extension, team/web

#9520 Respect the revision when jumping to Sourcegraph from GitHub
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/code_views.ts
  browser/src/libs/github/__snapshots__/util.test.ts.snap
  browser/src/libs/github/code_intelligence.ts
  browser/src/libs/github/file_info.ts
  browser/src/libs/github/scrape.ts
  browser/src/libs/github/util.tsx
  browser/src/libs/gitlab/file_info.ts
  shared/src/util/rxjs/asObservable.test.ts
  shared/src/util/rxjs/asObservable.ts
Labels: browser-extension, bug, github, team/web

#9522 Wrap many action items in Bitbucket
  browser/src/libs/bitbucket/code_intelligence.tsx
  browser/src/libs/bitbucket/style.scss
Labels: bitbucket, browser-extension, design

#9531 Use explicit CSS classes in RepoHeader over child selectors
  web/src/repo/RepoHeader.scss
  web/src/repo/RepoHeader.tsx
Labels: bug, webapp

#9529 generate Grafana dashboards and Prometheus alert rules from single source of truth
  .github/CODEOWNERS
  CHANGELOG.md
  cmd/server/build.sh
  dev/changewatch.sh
  dev/grafana.sh
  dev/handle-change.sh
  dev/prometheus.sh
  doc/dev/index.md
  doc/dev/observability.md
  docker-images/grafana/Dockerfile
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/syntect-server.json
  docker-images/prometheus/Dockerfile
  docker-images/prometheus/config/.gitignore
  docker-images/prometheus/config/syntect_server_rules.yml
  observability/go.mod
  observability/go.sum
  observability/src-observability-generator.go
  observability/syntect_server.go
Labels: monitoring

#9528 CI E2E: skip pushing the image to docker registry
  .buildkite/pipeline.e2e.yml
  dev/ci/e2e.sh
  enterprise/dev/ci/ci/pipeline-steps.go
Labels: ops & tools & dev

#9495 Support using port 443 in dev with authbind
  dev/caddy.sh
  doc/dev/local_development.md
Labels: ops & tools & dev

#9532 Increase opacity of button focus rings
  web/src/SourcegraphWebApp.scss
Labels: accessibility, design, webapp

#9559 Cleanup some logspam in jest tests
  web/src/components/PageTitle.tsx
  web/src/components/__snapshots__/alerts.test.tsx.snap
  web/src/components/alerts.test.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.test.tsx
  web/src/extensions/extension/RegistryExtensionOverviewPage.test.tsx
  web/src/search/queryBuilder/QueryBuilder.test.tsx
  web/src/search/results/SearchResults.test.tsx
  web/src/site-admin/SiteAdminOverviewPage.test.tsx
Labels: debt

#9572 Remove unused eslint disables
  .github/CODEOWNERS
  .stylelintignore
  browser/src/libs/phabricator/extension.ts
  cmd/precise-code-intel/src/shared/api/pagination/cursor.ts
  cmd/precise-code-intel/src/shared/input.test.ts
  dev/release/src/google-calendar.ts
  shared/src/api/client/types/textDocument.ts
  shared/src/api/extension/worker.ts
  shared/src/commands/commands.ts
  shared/src/components/Tabs.tsx
  shared/src/util/LocalStorageSubject.ts
  shared/src/util/url.ts
  web/src/api/APIConsole.tsx
  web/src/components/FilteredConnection.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.test.tsx
  web/src/enterprise/search/stats/SearchStatsPage.test.tsx
  web/src/enterprise/search/stats/SearchStatsPage.tsx
  web/src/enterprise/user/productSubscriptions/PaymentTokenFormControl.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsNewProductSubscriptionPage.tsx
  web/src/extensions/ExtensionsList.tsx
  web/src/extensions/ExtensionsQueryInputToolbar.tsx
  web/src/extensions/extension/extension.ts
  web/src/extensions/extension/routes.tsx
  web/src/nav/UserNavItem.tsx
  web/src/repo/RepoContainer.tsx
  web/src/repo/blob/actions/ToggleRenderedFileMode.tsx
  web/src/repo/blob/discussions/DiscussionsCreate.tsx
  web/src/repo/blob/discussions/DiscussionsGutterOverlay.tsx
  web/src/repo/blob/discussions/DiscussionsNavbar.tsx
  web/src/repo/blob/discussions/DiscussionsThread.tsx
  web/src/repo/index.tsx
  web/src/repo/stats/RepositoryStatsContributorsPage.tsx
  web/src/search/input/QueryInput.tsx
  web/src/search/results/SearchResults.tsx
  web/src/site-admin/SiteAdminAddExternalServicesPage.tsx
  web/src/tree/File.tsx
  web/src/tree/Tree.tsx
  web/src/tree/TreeLayer.tsx
  web/src/tree/TreeRoot.tsx
  web/src/util/url.ts
Labels: debt

#9567 Improve access token lookup speed
  cmd/frontend/db/access_tokens.go
Labels: api, perf

#9539 observability: add support for specifying unit type of graphs
  observability/src-observability-generator.go
Labels: monitoring

#9537 observability: remove default values
  observability/src-observability-generator.go
  observability/syntect_server.go
Labels: monitoring

#9571 allow linking to downloadable data: URIs from notifications
  shared/src/notifications/NotificationItem.tsx
  shared/src/util/markdown.test.ts
  shared/src/util/markdown.ts
Labels: extensions

#9551 Track Puppeteer coverage
  .buildkite/pipeline.e2e.yml
  babel.config.js
  dev/ci/e2e.sh
  dev/codecov.yml
  doc/dev/testing.md
  enterprise/dev/ci/ci/pipeline-steps.go
  package.json
  shared/src/e2e/coverage.ts
  shared/src/e2e/driver.ts
  web/package.json
  web/src/e2e/e2e.test.ts
  web/webpack.config.js
  yarn.lock
Labels: ops & tools & dev

#9540 Enable git-extras by default
  CHANGELOG.md
  cmd/frontend/graphqlbackend/default_settings.go
Labels: extensions

#9648 Memoize calls to the Phabricator API
  CHANGELOG.md
  browser/src/libs/phabricator/backend.tsx
Labels: perf, phabricator, team/web

#5541 Use IntersectionObserver in trackViews()
  browser/src/libs/code_intelligence/MockIntersectionObserver.ts
  browser/src/libs/code_intelligence/code_intelligence.test.tsx
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/views.test.ts
  browser/src/libs/code_intelligence/views.ts
Labels: browser-extension, perf, team/web

#9657 Fix retry button API call
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/CampaignStatus.story.tsx
  web/src/enterprise/campaigns/detail/CampaignStatus.test.tsx
  web/src/enterprise/campaigns/detail/CampaignStatus.tsx
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignStatus.test.tsx.snap
  web/src/enterprise/campaigns/detail/backend.ts
Labels: bug, campaigns

#9656 Ignore changesets where repo does not exist anymore
  CHANGELOG.md
  enterprise/internal/campaigns/store.go
  enterprise/internal/campaigns/store_test.go
Labels: bug, campaigns

#9661 observability: convert frontend dashboard to generated
  CHANGELOG.md
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/frontend.json
  docker-images/prometheus/config/frontend_rules.yml
  observability/frontend.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9667 observability: convert Repo Updater dashboard to generated
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/github-proxy.json
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/repo-updater.json
  docker-images/prometheus/config/github_proxy_rules.yml
  docker-images/prometheus/config/repo_updater_rules.yml
  observability/github_proxy.go
  observability/repo_updater.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9672 observability: convert Searcher dashboard to generated
  CHANGELOG.md
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/searcher.json
  docker-images/prometheus/config/searcher_rules.yml
  observability/searcher.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9682 observability: convert LSIF Server dashboard into generated form
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/lsif-server.json
  docker-images/prometheus/config/lsif_server_rules.yml
  observability/precise_code_intel_api_server.go
  observability/precise_code_intel_bundle_manager.go
  observability/precise_code_intel_worker.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9696 Some eslint fixes
  shared/src/commands/commands.ts
  web/src/auth/ResetPasswordPage.tsx
  web/src/backend/graphql.tsx
  web/src/components/DecoratedTextLines.tsx
  web/src/components/ErrorBoundary.tsx
  web/src/components/FilteredConnection.tsx
  web/src/components/SaveToolbar.tsx
  web/src/components/SearchResult.tsx
  web/src/components/d3/BarChart.tsx
  web/src/components/diff/FileDiffNode.tsx
  web/src/discussions/DiscussionsComment.tsx
  web/src/enterprise/extensions/explore/ExtensionsExploreSection.tsx
  web/src/enterprise/extensions/extension/RegistryExtensionDeleteButton.tsx
  web/src/enterprise/extensions/extension/RegistryExtensionForm.tsx
  web/src/marketing/IntegrationsToast.tsx
  web/src/org/new/NewOrganizationPage.tsx
  web/src/org/settings/profile/OrgSettingsProfilePage.tsx
  web/src/repo/RepoRevSidebarCommits.tsx
  web/src/repo/RepoRevSidebarSymbols.tsx
  web/src/repo/RepositoryGitDataContainer.tsx
  web/src/repo/RepositoryNotFoundPage.tsx
  web/src/repo/RevisionsPopover.tsx
  web/src/repo/blob/discussions/DiscussionsCreate.tsx
  web/src/repo/blob/discussions/DiscussionsThread.tsx
  web/src/repo/compare/dom-functions.ts
  web/src/search/results/CommitSearchResult.tsx
  web/src/search/results/SearchResultsFilterBars.tsx
  web/src/search/results/SearchResultsList.tsx
  web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
  web/src/settings/SettingsFile.tsx
  web/src/site-admin/SiteAdminUpdatesPage.tsx
  web/src/symbols/backend.tsx
  web/src/tree/SingleChildTreeLayer.tsx
  web/src/tree/Tree.tsx
  web/src/tree/TreeLayer.tsx
  web/src/tree/TreeRoot.tsx
  web/src/user/area/UserArea.tsx
  web/src/user/settings/emails/AddUserEmailForm.tsx
  web/src/user/settings/emails/UserSettingsEmailsPage.tsx
  web/src/user/settings/profile/UserSettingsProfilePage.tsx
  web/src/util/url.test.ts
Labels: debt, team/web

#9709 Fix broken type checks
  web/src/repo/RepoRevSidebarCommits.tsx
  web/src/repo/RevisionsPopover.tsx
  web/src/symbols/backend.tsx
Labels: bug, webapp

#9383 Add an application name to Postgres connections
  internal/db/dbconn/dbconn.go
  internal/db/dbconn/dbconn_test.go
Labels: new-contributor

#9699 Fix error handling
  browser/src/libs/code_intelligence/SignInButton.tsx
  browser/src/libs/code_intelligence/__snapshots__/external_links.test.tsx.snap
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/libs/code_intelligence/code_views.ts
  browser/src/libs/code_intelligence/external_links.test.tsx
  browser/src/libs/code_intelligence/external_links.tsx
  browser/src/libs/code_intelligence/util/file_info.ts
  browser/src/libs/options/OptionsContainer.tsx
  browser/src/libs/phabricator/backend.tsx
  browser/src/shared/backend/server.ts
  browser/src/shared/components/Button.tsx
  browser/src/shared/components/OpenDiffOnSourcegraph.tsx
  browser/src/shared/components/OpenOnSourcegraph.tsx
  browser/src/shared/repo/backend.tsx
  shared/src/backend/errors.test.ts
  shared/src/backend/errors.ts
  shared/src/hover/actions.ts
  web/src/regression/util/api.ts
  web/src/repo/RepoContainer.tsx
  web/src/repo/RepoRevContainer.tsx
  web/src/repo/RepositoryGitDataContainer.tsx
  web/src/repo/index.tsx
Labels: team/web

#9733 observability: convert Symbols dashboard into generated form
  CHANGELOG.md
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/symbols.json
  docker-images/prometheus/config/symbols_rules.yml
  observability/src-observability-generator.go
  observability/symbols.go
Labels: monitoring, team/distribution

#9717 Fix GitHub file actions wrapping
  browser/src/libs/github/style.scss
Labels: browser-extension, bug, github, team/web

#9711 tracking-issue: Track Pull requests
  go.mod
  go.sum
  internal/cmd/tracking-issue/Dockerfile
  internal/cmd/tracking-issue/main.go
  internal/cmd/tracking-issue/main_test.go
  internal/cmd/tracking-issue/testdata/fixtures.json
  internal/cmd/tracking-issue/testdata/issue.md
  internal/cmd/tracking-issue/testdata/issues.json
Labels: team/core-services

#9749 observability: convert Replacer dashboard into generated form
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/replacer.json
  docker-images/prometheus/config/replacer_rules.yml
  observability/replacer.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#8056 clean up and add tests for SiteInitPage
  cmd/frontend/internal/app/jscontext/jscontext.go
  web/src/Layout.tsx
  web/src/SourcegraphWebApp.scss
  web/src/auth/SignUpForm.tsx
  web/src/globals.d.ts
  web/src/routes.tsx
  web/src/site-admin/init/SiteInitPage.scss
  web/src/site-admin/init/SiteInitPage.test.tsx
  web/src/site-admin/init/SiteInitPage.tsx
  web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
Labels: team/web, webapp

#9755 Fix url being passed as ariaLabel
  browser/src/libs/code_intelligence/external_links.tsx
  browser/src/shared/components/OpenDiffOnSourcegraph.tsx
  browser/src/shared/components/OpenOnSourcegraph.tsx
Labels: browser-extension, bug, team/web

#9758 observability: convert Zoekt Index Server dashboard into generated form
  CHANGELOG.md
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/zoekt-indexserver.json
  docker-images/prometheus/config/zoekt_indexserver_rules.yml
  observability/src-observability-generator.go
  observability/zoekt_index_server.go
Labels: monitoring, team/distribution

#9692 docs: GitHub background permissions syncing
  CHANGELOG.md
  doc/admin/external_service/github.md
  doc/admin/repo/permissions.md
Labels: team/core-services

#9765 observability: do not mark dashboards as non-editable
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9767 observability: correctly sort firing alerts to the tops of dashboards
  CHANGELOG.md
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9769 observability: do not cut off panels at the bottom of home dashboard
  CHANGELOG.md
  docker-images/grafana/home.json
Labels: monitoring, team/distribution

#9770 observability: convert Zoekt Web Server dashboard into generated form
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/zoekt-webserver.json
  docker-images/prometheus/config/zoekt_webserver_rules.yml
  observability/src-observability-generator.go
  observability/zoekt_web_server.go
Labels: monitoring, team/distribution

#9771 observability: add better validation of wording
  observability/src-observability-generator.go
  observability/zoekt_index_server.go
Labels: monitoring, team/distribution

#9772 observability: searcher: correct query for "unindexed search request errors"
  observability/searcher.go
Labels: monitoring, team/distribution

#9776 docs: version fix
  doc/index.md
Labels: docs

#9780 observability: add support for alerting on values that are LessOrEqual
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9781 observability: convert Git Server dashboard into generated form
  CHANGELOG.md
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/.gitignore
  docker-images/grafana/config/provisioning/dashboards/sourcegraph/gitserver.json
  docker-images/prometheus/config/gitserver_rules.yml
  observability/git_server.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9795 observability: remove deprecated and useless / bad dashboards
  docker-images/grafana/config/provisioning/dashboards/sourcegraph_internal/gitserver.json
  docker-images/grafana/config/provisioning/dashboards/sourcegraph_internal/http.json
  docker-images/grafana/config/provisioning/dashboards/sourcegraph_internal/overview.json
  docker-images/grafana/config/provisioning/dashboards/sourcegraph_internal/searcher.json
  docker-images/grafana/jsonnet/gitserver-rev2.jsonnet
  docker-images/grafana/jsonnet/zoekt-indexserver.jsonnet
Labels: monitoring, team/distribution

#9801 docker-images: fix building and publish new versions of grafana,prometheus
  docker-images/Makefile
  docker-images/grafana/.gitignore
  docker-images/grafana/Dockerfile
  docker-images/grafana/pre-build.sh
  docker-images/grafana/version.sh
  docker-images/prometheus/.gitignore
  docker-images/prometheus/Dockerfile
  docker-images/prometheus/pre-build.sh
  docker-images/prometheus/version.sh
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9805 tracking-issue: Fix top level PRs
  internal/cmd/tracking-issue/main.go
  internal/cmd/tracking-issue/testdata/issue.md
Labels: team/core-services

#9702 Make campaign.description nullable
  cmd/frontend/db/schema.md
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/campaigns.go
  enterprise/internal/campaigns/resolvers/resolver.go
  enterprise/internal/campaigns/store.go
  migrations/1528395668_campaign_description_nullable.down.sql
  migrations/1528395668_campaign_description_nullable.up.sql
  migrations/bindata.go
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
Labels: campaigns, debt

#9764 refactor Sourcegraph.com billing/license React components into function components
  shared/src/util/useObservable.ts
  web/src/enterprise/dotcom/billing/StripeWrapper.tsx
  web/src/enterprise/dotcom/productPlans/ProductPlanFormControl.test.tsx
  web/src/enterprise/dotcom/productPlans/ProductPlanFormControl.tsx
  web/src/enterprise/dotcom/productPlans/ProductSubscriptionUserCountFormControl.test.tsx
  web/src/enterprise/dotcom/productPlans/ProductSubscriptionUserCountFormControl.tsx
  web/src/enterprise/dotcom/productPlans/__snapshots__/ProductPlanFormControl.test.tsx.snap
  web/src/enterprise/dotcom/productPlans/__snapshots__/ProductSubscriptionUserCountFormControl.test.tsx.snap
  web/src/enterprise/dotcom/productSubscriptions/ProductSubscriptionNode.tsx
  web/src/enterprise/dotcom/productSubscriptions/features.ts
  web/src/enterprise/productSubscription/LicenseGenerationKeyWarning.tsx
  web/src/enterprise/site-admin/dotcom/customers/SiteAdminCustomerBillingLink.test.tsx
  web/src/enterprise/site-admin/dotcom/customers/SiteAdminCustomerBillingLink.tsx
  web/src/enterprise/site-admin/dotcom/customers/SiteAdminCustomersPage.tsx
  web/src/enterprise/site-admin/dotcom/customers/__snapshots__/SiteAdminCustomerBillingLink.test.tsx.snap
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.test.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicenseNode.test.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicenseNode.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicensesPage.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionBillingLink.test.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionBillingLink.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionNode.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.test.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
  web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminGenerateProductLicenseForSubscriptionForm.test.tsx.snap
  web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductLicenseNode.test.tsx.snap
  web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionBillingLink.test.tsx.snap
  web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  web/src/enterprise/site-admin/productSubscription/SiteAdminProductSubscriptionPage.tsx
  web/src/enterprise/user/productSubscriptions/NewProductSubscriptionPaymentSection.test.tsx
  web/src/enterprise/user/productSubscriptions/NewProductSubscriptionPaymentSection.tsx
  web/src/enterprise/user/productSubscriptions/ProductSubscriptionForm.test.tsx
  web/src/enterprise/user/productSubscriptions/ProductSubscriptionForm.tsx
  web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.test.tsx
  web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsEditProductSubscriptionPage.test.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsEditProductSubscriptionPage.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsNewProductSubscriptionPage.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.test.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
  web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
  web/src/enterprise/user/productSubscriptions/__snapshots__/NewProductSubscriptionPaymentSection.test.tsx.snap
  web/src/enterprise/user/productSubscriptions/__snapshots__/ProductSubscriptionForm.test.tsx.snap
  web/src/enterprise/user/productSubscriptions/__snapshots__/UserProductSubscriptionStatus.test.tsx.snap
  web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsEditProductSubscriptionPage.test.tsx.snap
  web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsProductSubscriptionPage.test.tsx.snap
  web/src/globals.d.ts
Labels: webapp

#9821 observability: use more color-blind friendly threshold colors
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9826 observability: do not over-count firing alerts due to number of service replicas
  CHANGELOG.md
  docker-images/grafana/home.json
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9831 observability: remove line color dividing warning/critical thresholds
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9835 observability: improved NaN handling
  CHANGELOG.md
  observability/frontend.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9552 Federate precise-code-intel-worker metrics in pure docker environments
  docker-images/prometheus/config/prometheus.yml
  docker-images/prometheus/config/prometheus_pure_docker_or_compose.yml
  docker-images/prometheus/entry.sh
Labels: release-blocker, team/distribution

#9840 observability: do not average histogram quantiles
  observability/frontend.go
Labels: monitoring, team/distribution

#9843 build Grafana and Prometheus images on CI
  docker-images/grafana/Dockerfile
  docker-images/grafana/build.sh
  docker-images/grafana/pre-build.sh
  docker-images/prometheus/Dockerfile
  docker-images/prometheus/build.sh
  docker-images/prometheus/pre-build.sh
  enterprise/dev/ci/ci/pipeline-steps.go
  enterprise/dev/ci/ci/pipeline.go
Labels: monitoring, team/distribution

#9845 docker-images: cleanup folder structure, use build scripts when appropriate
  docker-images/Makefile
  docker-images/README.md
  docker-images/alpine/build.sh
  docker-images/alpine/release.sh
  docker-images/alpine/version.sh
  docker-images/grafana/version.sh
  docker-images/prometheus/version.sh
  docker-images/version.sh
Labels: team/distribution

#9847 docker-images: republish docker images using Sourcegraph versioning and canonical names
  docker-images/README.md
  docker-images/alpine/build.sh
  docker-images/alpine/release.sh
  docker-images/indexed-searcher/build.sh
  docker-images/postgres-11.4/build.sh
  docker-images/redis-cache/build.sh
  docker-images/redis-store/build.sh
  docker-images/search-indexer/build.sh
  docker-images/syntax-highlighter/build.sh
Labels: team/distribution

#9848 enterprise/dev/ci: build republished images
  enterprise/dev/ci/ci/pipeline-steps.go
Labels: team/distribution

#9850 docker-images: fix build script permissions
  docker-images/indexed-searcher/build.sh
  docker-images/postgres-11.4/build.sh
  docker-images/redis-cache/build.sh
  docker-images/redis-store/build.sh
  docker-images/search-indexer/build.sh
  docker-images/syntax-highlighter/build.sh
Labels: team/distribution

#9813 Update firefox extension security info
  doc/integration/browser_extension.md
  doc/integration/firefox_security.md
Labels: new-contributor

#9833 include the license key in pings
  cmd/frontend/internal/app/pkg/updatecheck/client.go
  cmd/frontend/internal/app/pkg/updatecheck/handler.go
  cmd/frontend/internal/app/pkg/updatecheck/handler_test.go
  doc/admin/pings.md
Labels: team/core-services

#9628 Onboarding updates
  package.json
  shared/src/components/activation/Activation.tsx
  shared/src/components/activation/ActivationChecklist.scss
  shared/src/components/activation/ActivationChecklist.tsx
  shared/src/components/activation/ActivationDropdown.scss
  shared/src/components/activation/ActivationDropdown.story.tsx
  shared/src/components/activation/ActivationDropdown.test.tsx
  shared/src/components/activation/ActivationDropdown.tsx
  shared/src/components/activation/__snapshots__/ActivationChecklist.test.tsx.snap
  shared/src/components/activation/__snapshots__/ActivationDropdown.test.tsx.snap
  shared/src/index.scss
  web/src/SourcegraphWebApp.scss
  web/src/components/Collapsible.tsx
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.tsx
  web/src/enterprise/campaigns/detail/changesets/__snapshots__/ChangesetNode.test.tsx.snap
  web/src/enterprise/campaigns/detail/patches/PatchNode.tsx
  web/src/enterprise/campaigns/detail/patches/__snapshots__/PatchNode.test.tsx.snap
  web/src/enterprise/productSubscription/ProductCertificate.scss
  web/src/site-admin/overview/SiteAdminOverviewPage.test.tsx
  web/src/site-admin/overview/SiteAdminOverviewPage.tsx
  web/src/site-admin/overview/__snapshots__/SiteAdminOverviewPage.test.tsx.snap
  web/src/tracking/__snapshots__/withActivation.test.tsx.snap
  web/src/tracking/withActivation.test.tsx
  web/src/tracking/withActivation.tsx
  yarn.lock
Labels: onboarding, team/web

#9807 Make more clear that changeset link opens external page
  web/src/enterprise/campaigns/detail/changesets/ChangesetNode.tsx
  web/src/enterprise/campaigns/detail/changesets/__snapshots__/ChangesetNode.test.tsx.snap
Labels: campaigns, team/web

#9707 Campaigns splash screens
  web/src/SourcegraphWebApp.tsx
  web/src/enterprise.scss
  web/src/enterprise/campaigns/global/GlobalCampaignsArea.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignMarketing.scss
  web/src/enterprise/campaigns/global/marketing/CampaignsDotComPage.test.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsDotComPage.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsMarketing.test.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsMarketing.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsSiteAdminMarketingPage.test.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsSiteAdminMarketingPage.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsUserMarketingPage.test.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsUserMarketingPage.tsx
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsDotComPage.test.tsx.snap
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsMarketing.test.tsx.snap
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsSiteAdminMarketingPage.test.tsx.snap
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsUserMarketingPage.test.tsx.snap
Labels: campaigns

#9869 observability: add container monitoring in docker-compose / pure docker deployments
  docker-images/prometheus/config/cadvisor_container_restart_count_rules.yml
  docker-images/prometheus/config/cadvisor_rules.yml
  observability/frontend.go
  observability/git_server.go
  observability/github_proxy.go
  observability/precise_code_intel_api_server.go
  observability/precise_code_intel_bundle_manager.go
  observability/precise_code_intel_worker.go
  observability/query_runner.go
  observability/replacer.go
  observability/repo_updater.go
  observability/searcher.go
  observability/symbols.go
  observability/syntect_server.go
  observability/zoekt_index_server.go
  observability/zoekt_web_server.go
Labels: monitoring, team/distribution

#9871 observability: minor improvements + upgrade git (fixes CI)
  docker-images/grafana/Dockerfile
  docker-images/grafana/build.sh
  docker-images/prometheus/build.sh
  observability/frontend.go
  observability/git_server.go
Labels: monitoring, team/distribution

#9095 Add documentation pages for src cli within the app
  web/src/enterprise/campaigns/global/GlobalCampaignsArea.tsx
  web/src/enterprise/campaigns/global/create/CampaignCLIHelp.test.tsx
  web/src/enterprise/campaigns/global/create/CampaignCLIHelp.tsx
  web/src/enterprise/campaigns/global/create/CreateCampaign.test.tsx
  web/src/enterprise/campaigns/global/create/CreateCampaign.tsx
  web/src/enterprise/campaigns/global/create/__snapshots__/CampaignCLIHelp.test.tsx.snap
  web/src/enterprise/campaigns/global/create/__snapshots__/CreateCampaign.test.tsx.snap
  web/src/enterprise/campaigns/global/list/GlobalCampaignListPage.tsx
  web/src/enterprise/campaigns/global/list/__snapshots__/GlobalCampaignListPage.test.tsx.snap
Labels: campaigns, docs

#9891 Implement UI component for next sync property
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/changesets.go
  web/src/enterprise/campaigns/detail/backend.ts
  web/src/enterprise/campaigns/detail/changesets/ChangesetLastSynced.test.tsx
  web/src/enterprise/campaigns/detail/changesets/ChangesetLastSynced.tsx
  web/src/enterprise/campaigns/detail/changesets/__snapshots__/ChangesetLastSynced.test.tsx.snap
Labels: campaigns

#9892 monitoring: distinguish between browser and API requests
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/internal/httpapi/graphql.go
  internal/trace/httptrace.go
  observability/frontend.go
Labels: monitoring, release-blocker, team/distribution

#9898 monitoring: reduce src_graphql_field_seconds cardinality substantially
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
Labels: monitoring, team/distribution

#9901 observability: relax search latency alerts to match real world
  internal/trace/httptrace.go
  observability/frontend.go
Labels: monitoring, team/distribution

#9674 search: add search alert improvements
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/graphqlbackend/search_alert_test.go
  cmd/frontend/graphqlbackend/search_results.go
Labels: new-contributor

#9907 Make campaigns experience better for new users
  web/src/enterprise/campaigns/detail/AddChangesetForm.tsx
  web/src/enterprise/campaigns/detail/CampaignActionsBar.scss
  web/src/enterprise/campaigns/detail/CampaignActionsBar.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/__snapshots__/AddChangesetForm.test.tsx.snap
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignActionsBar.test.tsx.snap
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignDetails.test.tsx.snap
  web/src/enterprise/campaigns/global/GlobalCampaignsArea.tsx
  web/src/enterprise/campaigns/global/create/CampaignCLIHelp.tsx
  web/src/enterprise/campaigns/global/create/CreateCampaign.tsx
  web/src/enterprise/campaigns/global/create/__snapshots__/CampaignCLIHelp.test.tsx.snap
  web/src/enterprise/campaigns/global/create/__snapshots__/CreateCampaign.test.tsx.snap
  web/src/enterprise/campaigns/global/list/GlobalCampaignListPage.test.tsx
  web/src/enterprise/campaigns/global/list/GlobalCampaignListPage.tsx
  web/src/enterprise/campaigns/global/list/__snapshots__/GlobalCampaignListPage.test.tsx.snap
  web/src/enterprise/campaigns/global/list/backend.ts
  web/src/enterprise/campaigns/global/marketing/CampaignsDotComPage.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsMarketing.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsSiteAdminMarketingPage.tsx
  web/src/enterprise/campaigns/global/marketing/CampaignsUserMarketingPage.tsx
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsDotComPage.test.tsx.snap
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsMarketing.test.tsx.snap
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsSiteAdminMarketingPage.test.tsx.snap
  web/src/enterprise/campaigns/global/marketing/__snapshots__/CampaignsUserMarketingPage.test.tsx.snap
Labels: campaigns

#9914 Track loading states of providers
  browser/src/libs/code_intelligence/code_intelligence.tsx
  browser/src/shared/backend/ext-api-conversion.tsx
  browser/src/shared/backend/lsp.tsx
  jest.config.base.js
  package.json
  shared/src/api/client/api/views.ts
  shared/src/api/client/services/hover.test.ts
  shared/src/api/client/services/hover.ts
  shared/src/api/client/services/location.test.ts
  shared/src/api/client/services/location.ts
  shared/src/api/client/services/view.ts
  shared/src/api/client/types/hover.ts
  shared/src/api/integration-test/languageFeatures.test.ts
  shared/src/hover/HoverOverlay.tsx
  shared/src/hover/actions.test.ts
  shared/src/hover/actions.ts
  shared/src/panel/views/HierarchicalLocationsView.test.tsx
  shared/src/panel/views/HierarchicalLocationsView.tsx
  shared/src/util/types.ts
  web/src/backend/features.ts
  web/src/repo/blob/panel/BlobPanel.tsx
  yarn.lock
Labels: bug, extensions, team/web

#9946 Fix repo settings header alignment
  web/src/repo/settings/RepoSettingsArea.scss
Labels: bug, design, team/web, webapp

#9947 Only show hint for manual campaigns
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
Labels: bug, campaigns, release-blocker

#9954 Inline documentation for updating campaign patches
  web/src/enterprise/campaigns/detail/CampaignDetails.test.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignDetails.test.tsx.snap
  web/src/enterprise/campaigns/global/create/CampaignCLIHelp.test.tsx
  web/src/enterprise/campaigns/global/create/__snapshots__/CampaignCLIHelp.test.tsx.snap
Labels: campaigns

#4490 Add online extension editor and publishing
  shared/src/api/extension/api/extensions.ts
  web/src/enterprise/extensions/extension/RegistryExtensionNewReleasePage.tsx
  web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
  web/src/util/useLocalStorage.ts
Labels: extensions

#9950 debugproxies: Nicer display names for statefulset pods
  cmd/frontend/internal/app/debugproxies/handler.go
  cmd/frontend/internal/app/debugproxies/handler_test.go
  cmd/frontend/internal/app/debugproxies/scanner.go
  cmd/frontend/internal/app/debugproxies/scanner_test.go
Labels: team/core-services

#9967 docs: fix link to GitLab.com
  doc/integration/gitlab.md
Labels: new-contributor

#9935 observability: minor quality of life improvements
  observability/git_server.go
  observability/src-observability-generator.go
Labels: monitoring, team/distribution

#9986 observability: separate search-based code intelligence from regular search metrics
  cmd/frontend/graphqlbackend/search_results.go
  observability/frontend.go
Labels: monitoring, team/distribution

#9934 refactor ScopePage, add test
  web/src/SourcegraphWebApp.scss
  web/src/search/ScopePage.scss
  web/src/search/ScopePage.test.tsx
  web/src/search/ScopePage.tsx
  web/src/search/__snapshots__/ScopePage.test.tsx.snap
  web/src/search/helpers.tsx
Labels: search, webapp

#9995 avoid webpack hot reload problem with reach-ui Popover component
  shared/src/components/activation/ActivationDropdown.scss
  shared/src/components/activation/ActivationDropdown.tsx
Labels: webapp

#9961 Update campaigns docs to include screenshots
  doc/dev/documentation.md
  doc/user/campaigns/creating_manual_campaign.md
  doc/user/campaigns/index.md
  doc/user/campaigns/updating_campaigns.md
Labels: docs, docs-ux

#10032 Tiny fixes in campaign help screen in UI
  web/src/enterprise/campaigns/global/create/CampaignCLIHelp.tsx
  web/src/enterprise/campaigns/global/create/__snapshots__/CampaignCLIHelp.test.tsx.snap
Labels: campaigns

#10034 Add an example to the "Updating campaigns" documentation
  doc/user/campaigns/getting_started.md
  doc/user/campaigns/updating_campaigns.md
Labels: campaigns, docs

#10033 Fix conflicting storybook styles
  .storybook/config.ts
  .storybook/webpack.config.ts
  browser/src/globals.d.ts
  browser/src/libs/options/OptionsHeader.story.tsx
  browser/src/libs/options/OptionsMenu.story.tsx
  browser/src/libs/options/ServerURLForm.story.tsx
  package.json
  shared/src/actions/ActionItem.story.tsx
  shared/src/components/Toggle.story.tsx
  shared/src/components/activation/ActivationDropdown.story.tsx
  shared/src/components/activation/ActivationDropdown.tsx
  shared/src/components/completion/CompletionWidget.story.tsx
  shared/src/globals.d.ts
  shared/src/notifications/NotificationItem.story.tsx
  web/src/components/tooltip/Tooltip.story.tsx
  web/src/enterprise/campaigns/detail/CampaignStatus.story.tsx
  web/src/globals.d.ts
  web/src/nav/UserNavItem.story.tsx
  web/src/nav/UserNavItem.test.tsx
  yarn.lock
Labels: team/web

#10074 Add a documentation page about campaign actions
  doc/_resources/templates/document.html
  doc/user/campaigns/actions.md
  doc/user/campaigns/creating_campaign_from_patches.md
Labels: campaigns, docs

#10076 Better explain which GitHub token scopes are required for campaigns
  doc/admin/external_service/github.md
  doc/user/campaigns/configuration.md
  doc/user/campaigns/getting_started.md
  doc/user/campaigns/index.md
Labels: campaigns, docs

#10075 Fix browser extension e2e tests
  browser/src/e2e/github.test.ts
  browser/src/e2e/shared.ts
Labels: browser-extension, testing

#10077 docs: Add action scope query examples and document 'src action scope-query'
  doc/user/campaigns/actions.md
Labels: campaigns, docs

#10078 docs: Move "Are you first-time user..." further up
  doc/user/campaigns/index.md
Labels: campaigns, docs

#7636 Add instructions for updating enterprise license key
  doc/admin/subscriptions/index.md
Labels: docs

#10119 dev/watchman: merge file change events while running handle changed
  .github/CODEOWNERS
  dev/watchmanwrapper/main.go
Labels: team/core-services

#10139 monitoring: add very narrowly targeted sharing of observables
  monitoring/frontend.go
  monitoring/git_server.go
  monitoring/github_proxy.go
  monitoring/precise_code_intel_api_server.go
  monitoring/precise_code_intel_bundle_manager.go
  monitoring/precise_code_intel_worker.go
  monitoring/query_runner.go
  monitoring/replacer.go
  monitoring/repo_updater.go
  monitoring/searcher.go
  monitoring/shared.go
  monitoring/symbols.go
  monitoring/syntect_server.go
  monitoring/zoekt_index_server.go
  monitoring/zoekt_web_server.go
Labels: monitoring, okr/distribution/admin-experience, team/distribution

#10149 Uprade to comlink v4
  browser/src/extension/scripts/background.ts
  browser/src/libs/code_intelligence/code_intelligence.test.tsx
  browser/src/platform/extensionHost.ts
  package.json
  shared/src/api/client/api/codeEditor.ts
  shared/src/api/client/api/commands.ts
  shared/src/api/client/api/common.ts
  shared/src/api/client/api/configuration.ts
  shared/src/api/client/api/content.ts
  shared/src/api/client/api/context.ts
  shared/src/api/client/api/extensions.ts
  shared/src/api/client/api/languageFeatures.ts
  shared/src/api/client/api/roots.ts
  shared/src/api/client/api/search.ts
  shared/src/api/client/api/views.ts
  shared/src/api/client/api/windows.ts
  shared/src/api/client/connection.ts
  shared/src/api/extension/api/api.ts
  shared/src/api/extension/api/codeEditor.ts
  shared/src/api/extension/api/commands.ts
  shared/src/api/extension/api/common.ts
  shared/src/api/extension/api/configuration.test.ts
  shared/src/api/extension/api/configuration.ts
  shared/src/api/extension/api/content.ts
  shared/src/api/extension/api/context.ts
  shared/src/api/extension/api/documents.ts
  shared/src/api/extension/api/extensions.ts
  shared/src/api/extension/api/languageFeatures.ts
  shared/src/api/extension/api/roots.ts
  shared/src/api/extension/api/search.ts
  shared/src/api/extension/api/views.ts
  shared/src/api/extension/api/windows.ts
  shared/src/api/extension/extensionHost.ts
  shared/src/api/extension/main.worker.ts
  shared/src/api/util.ts
  shared/src/platform/context.ts
  yarn.lock
Labels: debt, team/web

#10028 Extend TypeScript documentation
  .github/CODEOWNERS
  doc/_resources/templates/document.html
  doc/dev/typescript/index.md
  doc/dev/typescript/patterns.md
  doc/dev/web_app.md
Labels: docs

#10157 tracking-issue: Implement simplified workflow
  internal/cmd/tracking-issue/main.go
  internal/cmd/tracking-issue/main_test.go
  internal/cmd/tracking-issue/testdata/fixtures.json
  internal/cmd/tracking-issue/testdata/issue.md
Labels: team/core-services

#10158 tracking-issue: Update GitHub action
  .github/workflows/tracking-issue.yml
Labels: team/core-services

#10142 monitoring: generate solutions documentation from Go monitoring definitions
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/alerting.md
  docker-images/grafana/Dockerfile
  docker-images/prometheus/Dockerfile
  monitoring/frontend.go
  monitoring/generator.go
  monitoring/git_server.go
  monitoring/replacer.go
  monitoring/searcher.go
  monitoring/shared.go
  monitoring/symbols.go
  monitoring/syntect_server.go
  monitoring/zoekt_index_server.go
  monitoring/zoekt_web_server.go
Labels: monitoring, okr/distribution/admin-experience, okr/distribution/dev-productivity, team/distribution

#10138 Update LSIF documentation and associated CI workflows
  .github/workflows/lsif.yml
  doc/_resources/templates/document.html
  doc/user/code_intelligence/adding_lsif_to_workflows.md
  doc/user/code_intelligence/index.md
  doc/user/code_intelligence/language_servers.md
  doc/user/code_intelligence/languages/go.md
  doc/user/code_intelligence/languages/index.md
  doc/user/code_intelligence/languages/typescript_and_javascript.md
  doc/user/code_intelligence/lsif.md
  doc/user/code_intelligence/lsif_quickstart.md
Labels: team/code-intelligence

#9997 extension views API
  cmd/frontend/internal/app/ui/router.go
  packages/sourcegraph-extension-api/src/sourcegraph.d.ts
  shared/src/api/client/api/views.ts
  shared/src/api/client/connection.ts
  shared/src/api/client/services.ts
  shared/src/api/client/services/contribution.ts
  shared/src/api/client/services/viewService.test.ts
  shared/src/api/client/services/viewService.ts
  shared/src/api/extension/api/views.ts
  shared/src/api/extension/extensionHost.ts
  shared/src/api/integration-test/views.test.ts
  shared/src/api/protocol/contribution.ts
  shared/src/schema/extension.schema.json
  web/src/routes.tsx
  web/src/views/QueryInputInViewContent.tsx
  web/src/views/ViewPage.test.tsx
  web/src/views/ViewPage.tsx
  web/src/views/ViewsArea.tsx
  web/src/views/__snapshots__/ViewPage.test.tsx.snap
Labels: webapp

#9885 doc: Add disclaimer about k8s namespaces
  doc/admin/faq.md
Labels: new-contributor

#10206 Allow including SVG in MarkupContent
  shared/src/util/markdown.test.ts
  shared/src/util/markdown.ts
Labels: code insights

#5327 Saved searches: Use namespace instead of userID and orgID
  CHANGELOG.md
  cmd/frontend/graphqlbackend/saved_searches.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  web/src/savedSearches/SavedSearchListPage.tsx
  web/src/search/backend.tsx
Labels: api, debt, search

#10170 Add a diffStat field on Campaign to return combined diffStat
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/campaigns.go
  enterprise/internal/campaigns/resolvers/patch_sets.go
  enterprise/internal/campaigns/resolvers/resolver.go
  enterprise/internal/campaigns/resolvers/resolver_test.go
  enterprise/internal/campaigns/service_test.go
  enterprise/internal/campaigns/testing.go
  enterprise/internal/campaigns/workers_test.go
  internal/vcs/git/exec.go
  internal/vcs/git/mocks.go
  web/src/enterprise/campaigns/detail/CampaignDetails.test.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/CampaignDiffStat.test.tsx
  web/src/enterprise/campaigns/detail/CampaignDiffStat.tsx
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignDetails.test.tsx.snap
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignDiffStat.test.tsx.snap
  web/src/enterprise/campaigns/detail/backend.ts
Labels: campaigns

#10174 Add projects to Codecov config
  dev/codecov.yml
  enterprise/dev/ci/ci/pipeline-steps.go
  enterprise/dev/ci/ci/pipeline.go
Labels: ops & tools & dev

#10234 Fix yaml definition for prometheus
  docker-images/prometheus/config/prometheus_pure_docker_or_compose.yml
Labels: bug, docker-compose

#10233 Fix campaigns e2e test
  web/src/e2e/e2e.test.ts
Labels: campaigns

#10256 Prettierignore gitignored Grafana files
  .prettierignore
Labels: ops & tools & dev

#10193 Redirect trees to blobs and vice versa
  CHANGELOG.md
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/router.go
  shared/src/panel/views/FileLocations.tsx
  shared/src/util/url.ts
  web/src/repo/TreePage.tsx
  web/src/repo/blob/BlobPage.tsx
  web/src/repo/blob/GoToRawAction.tsx
  web/src/repo/routes.tsx
  web/src/util/url.test.ts
  web/src/util/url.ts
Labels: code insights

#10166 Update tracking issue tool to preserve issue order and display whitelisted labels
  internal/cmd/tracking-issue/main.go
  internal/cmd/tracking-issue/main_test.go
  internal/cmd/tracking-issue/testdata/fixtures.json
  internal/cmd/tracking-issue/testdata/issue.md
Labels: team/code-intelligence

#10245 Unify campaigns teams into singular ownership
  .github/CODEOWNERS
Labels: campaigns

#10267 Deduplicate ChangesetEvents per Changeset before DB insert
  enterprise/internal/campaigns/syncer.go
Labels: campaigns

#10262 Remove discussions feature from webapp
  .github/CODEOWNERS
  .vscode/settings.json
  shared/src/util/url.ts
  web/src/SourcegraphWebApp.scss
  web/src/components/SearchResultMatch.tsx
  web/src/discussions/DiscussionsComment.scss
  web/src/discussions/DiscussionsComment.tsx
  web/src/discussions/DiscussionsList.scss
  web/src/discussions/DiscussionsList.tsx
  web/src/discussions/DiscussionsPage.scss
  web/src/discussions/DiscussionsPage.tsx
  web/src/discussions/backend.tsx
  web/src/discussions/index.tsx
  web/src/e2e/e2e.test.ts
  web/src/nav/NavLinks.tsx
  web/src/nav/UserNavItem.story.tsx
  web/src/nav/UserNavItem.test.tsx
  web/src/nav/UserNavItem.tsx
  web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  web/src/repo/TreePage.tsx
  web/src/repo/blob/Blob.scss
  web/src/repo/blob/Blob.tsx
  web/src/repo/blob/BlobPage.tsx
  web/src/repo/blob/actions/ToggleDiscussions.tsx
  web/src/repo/blob/actions/ToggleRenderedFileMode.tsx
  web/src/repo/blob/discussions/DiscussionsCreate.scss
  web/src/repo/blob/discussions/DiscussionsCreate.tsx
  web/src/repo/blob/discussions/DiscussionsGutterOverlay.scss
  web/src/repo/blob/discussions/DiscussionsGutterOverlay.tsx
  web/src/repo/blob/discussions/DiscussionsInput.scss
  web/src/repo/blob/discussions/DiscussionsInput.tsx
  web/src/repo/blob/discussions/DiscussionsNavbar.scss
  web/src/repo/blob/discussions/DiscussionsNavbar.tsx
  web/src/repo/blob/discussions/DiscussionsThread.scss
  web/src/repo/blob/discussions/DiscussionsThread.tsx
  web/src/repo/blob/discussions/DiscussionsTree.scss
  web/src/repo/blob/discussions/DiscussionsTree.tsx
  web/src/repo/blob/discussions/contributions.ts
  web/src/repo/blob/discussions/mentionCompletion.test.ts
  web/src/repo/blob/discussions/mentionCompletion.ts
  web/src/repo/blob/panel/BlobPanel.tsx
  web/src/routes.tsx
Labels: debt, webapp

#10284 Drop GitHub ReviewRequestedEvents when reviewer has been deleted
  internal/campaigns/types.go
  internal/campaigns/types_test.go
  internal/extsvc/github/pulls.go
Labels: campaigns

#10275 Fix typo in install guide
  web/src/enterprise/campaigns/global/create/CampaignCLIHelp.tsx
  web/src/enterprise/campaigns/global/create/__snapshots__/CampaignCLIHelp.test.tsx.snap
Labels: campaigns

#10285 Add PatchSet.DiffStat field and use that instead of computing it client side
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/apitest/types.go
  enterprise/internal/campaigns/resolvers/campaigns.go
  enterprise/internal/campaigns/resolvers/patch_sets.go
  enterprise/internal/campaigns/resolvers/resolver_test.go
  web/src/enterprise/campaigns/detail/CampaignActionsBar.test.tsx
  web/src/enterprise/campaigns/detail/CampaignActionsBar.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.test.tsx
  web/src/enterprise/campaigns/detail/CampaignDetails.tsx
  web/src/enterprise/campaigns/detail/CampaignDiffStat.test.tsx
  web/src/enterprise/campaigns/detail/CampaignDiffStat.tsx
  web/src/enterprise/campaigns/detail/__snapshots__/CampaignDetails.test.tsx.snap
  web/src/enterprise/campaigns/detail/backend.ts
Labels: campaigns

#10310 Fix GitHub file path detection on PRs
  browser/src/libs/github/util.tsx
Labels: browser-extension, bug
