Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-03, with the labels that each got.

#18535 gitserver: use fetch when cloning
  CHANGELOG.md
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/refspecoverrides.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/vcs_syncer.go
Labels: gitserver

#18729 gitserver: Read hostname from environment
  cmd/gitserver/main.go
  cmd/gitserver/server/server.go
  dev/Procfile
  dev/start.sh
Labels: team/core-application

#18692 migration: Add gitserver_repos table
  internal/database/schema.md
  migrations/frontend/1528395790_create_gitserver_repos.down.sql
  migrations/frontend/1528395790_create_gitserver_repos.up.sql
  migrations/frontend/bindata.go
Labels: team/core-application

#18665 add codeintelutils into sourcegraph/sourcegraph
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  enterprise/lib/codeintel/utils/README.md
  enterprise/lib/codeintel/utils/gzip.go
  enterprise/lib/codeintel/utils/gzip_test.go
  enterprise/lib/codeintel/utils/indexer_name.go
  enterprise/lib/codeintel/utils/indexer_name_test.go
  enterprise/lib/codeintel/utils/rate.go
  enterprise/lib/codeintel/utils/split_file.go
  enterprise/lib/codeintel/utils/split_file_test.go
  enterprise/lib/codeintel/utils/stitch_files.go
  enterprise/lib/codeintel/utils/stitch_files_test.go
  enterprise/lib/codeintel/utils/upload.go
  enterprise/lib/codeintel/utils/upload_test.go
  enterprise/lib/go.mod
  enterprise/lib/go.sum
  go.mod
  go.sum
  third-party-licenses/ThirdPartyLicenses.csv
Labels: team/code-intelligence

#18751 Update faq.md
  doc/admin/faq.md
Labels: docs

#18672 add lsif-test to main sourcegraph repo
  enterprise/lib/codeintel/lsif/test/README.md
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/args.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/context.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/ownership.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/util.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validator.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validators.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validators_edge.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validators_relationship.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validators_vertex.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/main.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/validate.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-visualize/args.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-visualize/internal/visualization/context.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-visualize/internal/visualization/util.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-visualize/internal/visualization/visualizer.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-visualize/main.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-visualize/visualize.go
  enterprise/lib/codeintel/lsif/test/internal/reader/context.go
  enterprise/lib/codeintel/lsif/test/internal/reader/errors.go
  enterprise/lib/codeintel/lsif/test/internal/reader/reader.go
  enterprise/lib/codeintel/lsif/test/internal/reader/stasher.go
  enterprise/lib/codeintel/lsif/test/scripts/combine.sh
  enterprise/lib/go.mod
  enterprise/lib/go.sum
Labels: team/code-intelligence

#18749 Prioritize global external services in campaigns syncer
  enterprise/internal/campaigns/syncer/util.go
  enterprise/internal/campaigns/syncer/util_test.go
Labels: team/campaigns

#18736 gitserver: Extract gitserver sharding logic
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/httpapi/internal_test.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/store/store.go
  internal/vcs/git/main_test.go
Labels: team/core-application

#18773 graphqlbackend: remove use of dev build tag
  cmd/frontend/graphqlbackend/gen/schema_generate.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema_dev.go
Labels: dx

#18776 dev: build without custom build tags
  dev/check/go-lint.sh
  dev/go-install.sh
Labels: dx

#18770 gitserver: Don't rely on NODE_NAME
  cmd/gitserver/main.go
Labels: team/core-application

#18718 docs: state Perforce user access level for permissions
  doc/admin/repo/perforce.md
Labels: team/core-application

#18781 db: add stub validators for Perforce
  internal/database/external_services.go
Labels: team/core-application

#18783 gitserver: add Client.P4Exec method
  cmd/gitserver/server/server.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
Labels: team/core-application

#18786 authz: change FetchUserPerms to return RepoIDType
  enterprise/cmd/repo-updater/authz/perms_syncer.go
  enterprise/cmd/repo-updater/authz/perms_syncer_test.go
  enterprise/internal/authz/authz_test.go
  internal/authz/bitbucketserver/provider.go
  internal/authz/bitbucketserver/provider_test.go
  internal/authz/github/github.go
  internal/authz/github/github_test.go
  internal/authz/gitlab/oauth.go
  internal/authz/gitlab/oauth_test.go
  internal/authz/gitlab/sudo.go
  internal/authz/gitlab/sudo_test.go
  internal/authz/iface.go
  internal/database/repos_perm_test.go
  internal/extsvc/types.go
Labels: team/core-application

#18782 database: Add GitserverRepoStore
  internal/database/dbutil/dbutil.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/repos.go
  internal/types/types.go
Labels: team/core-application

#18712 internal/vcs/git: add CommitsOptions.Before
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
Labels: insights-historical, team/code-insights, team/internal-contributor

#18711 insights: historical: add record_time to query runner jobs
  internal/database/schema.md
  migrations/frontend/1528395791_insights_query_runner_jobs_record_time.down.sql
  migrations/frontend/1528395791_insights_query_runner_jobs_record_time.up.sql
  migrations/frontend/bindata.go
Labels: insights-historical, team/code-insights, team/internal-contributor

#18714 insights: by default, show last 6mo of data & query one data point per 15d
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/store/store.go
  enterprise/internal/insights/store/store_test.go
Labels: insights-historical, team/code-insights, team/internal-contributor

#18762 internal/vcs/git: add FindNearestCommit to get commit nearest to a point in time
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
  internal/vcs/git/main_test.go
Labels: insights-historical, team/code-insights, team/internal-contributor

#18713 insights: discovery: add a way to efficiently iterate over all repos on Sourcegraph
  enterprise/internal/insights/discovery/all_repos_iterator.go
  enterprise/internal/insights/discovery/all_repos_iterator_test.go
  enterprise/internal/insights/discovery/gen.go
  enterprise/internal/insights/discovery/mock_default_repo_store.go
  enterprise/internal/insights/discovery/mock_repo_store.go
Labels: insights-historical, team/code-insights, team/internal-contributor

#18809 Group campaigns graphql schema extension
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: team/batchers

#18816 env: Add MustGet functions to env package
  cmd/gitserver/main.go
  cmd/gitserver/main_test.go
  internal/env/env.go
Labels: team/core-application

#18791 Consistently use the same clock in campaigns
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection.go
  enterprise/internal/campaigns/resolvers/changeset_connection.go
  enterprise/internal/campaigns/store/store.go
  enterprise/internal/campaigns/syncer/sync_test.go
  enterprise/internal/campaigns/syncer/syncer.go
  enterprise/internal/campaigns/syncer/syncer_test.go
  enterprise/internal/campaigns/webhooks/webhooks.go
Labels: bug

#18819 doc: Document that we sync per external service
  doc/dev/background-information/architecture/life-of-a-repository.md
Labels: team/core-application

#18825 perforce: pin p4 CLI deps to a specific commit
  cmd/gitserver/Dockerfile
  cmd/server/Dockerfile
Labels: team/core-application

#18814 Add "new" badge to product-research menu item
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/Badge.scss
  client/web/src/components/Badge.story.tsx
  client/web/src/components/Badge.tsx
  client/web/src/components/FeedbackBadge.story.tsx
  client/web/src/components/FeedbackBadge.tsx
  client/web/src/components/PageHeader.story.tsx
  client/web/src/components/StatusBadge.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/extensions/extension/ExtensionStatusBadge.tsx
  client/web/src/insights/InsightsPage.tsx
  client/web/src/user/settings/UserSettingsSidebar.tsx
  client/web/src/user/settings/sidebaritems.ts
Labels: team/frontend-platform, webapp

#18695 Add "Sign up" button to the nav-bar
  client/web/src/components/LinkWithIcon.tsx
  client/web/src/nav/MenuNavItem.tsx
  client/web/src/nav/NavLinks.scss
  client/web/src/nav/NavLinks.tsx
  client/web/src/nav/__snapshots__/MenuNavItem.test.tsx.snap
  client/web/src/nav/__snapshots__/NavLinks.test.tsx.snap
  client/web/src/util/getReactElements.test.tsx
  client/web/src/util/getReactElements.ts
Labels: team/frontend-platform, webapp

#18697 Implement UI part for campaigns SSH support
  client/branded/src/global-styles/colors.scss
  client/web/src/enterprise.scss
  client/web/src/enterprise/campaigns/settings/AddCredentialModal.scss
  client/web/src/enterprise/campaigns/settings/AddCredentialModal.story.tsx
  client/web/src/enterprise/campaigns/settings/AddCredentialModal.tsx
  client/web/src/enterprise/campaigns/settings/CampaignsSettingsArea.story.tsx
  client/web/src/enterprise/campaigns/settings/CodeHostConnectionNode.tsx
  client/web/src/enterprise/campaigns/settings/CodeHostSshPublicKey.tsx
  client/web/src/enterprise/campaigns/settings/ModalHeader.tsx
  client/web/src/enterprise/campaigns/settings/RemoveCredentialModal.story.tsx
  client/web/src/enterprise/campaigns/settings/RemoveCredentialModal.tsx
  client/web/src/enterprise/campaigns/settings/ViewCredentialModal.story.tsx
  client/web/src/enterprise/campaigns/settings/ViewCredentialModal.tsx
  client/web/src/enterprise/campaigns/settings/backend.ts
  client/web/src/integration/campaigns.test.ts
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/reconciler/executor.go
  enterprise/internal/campaigns/reconciler/executor_test.go
  enterprise/internal/campaigns/resolvers/code_host.go
  enterprise/internal/campaigns/resolvers/code_host_connection.go
  enterprise/internal/campaigns/resolvers/credential.go
  enterprise/internal/campaigns/resolvers/errors.go
  enterprise/internal/campaigns/resolvers/resolver.go
  enterprise/internal/campaigns/store/codehost.go
  enterprise/internal/campaigns/store/codehost_test.go
  enterprise/internal/campaigns/testing/repos.go
  internal/campaigns/code_host.go
  internal/extsvc/bitbucketserver/client.go
Labels: team/batchers

#18081 dev: make drop-entire-db script also drop insights DB
  dev/drop-entire-local-database-and-redis.sh
Labels: team/code-insights, team/internal-contributor

#18850 Copy adjustments and mock text area for repo view
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/core-application

#18630 Update navigation design for admin settings
  client/branded/src/global-styles/background.scss
  client/branded/src/global-styles/colors.scss
  client/web/src/components/Sidebar.scss
  client/web/src/components/Sidebar.tsx
  client/web/src/components/externalServices/ExternalServicesPage.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
  client/web/src/site-admin/sidebaritems.ts
Labels: team/frontend-platform

#18872 Fix Percy snapshot flake caused by Monaco search box taking too long to render
  client/web/src/integration/search.test.ts
Labels: team/search

#18715 insights: add historical data enqueuer
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/gen.go
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/background/mock_repo_store.go
  enterprise/internal/insights/store/mock_store_interface.go
  enterprise/internal/insights/store/store.go
Labels: insights-historical, team/code-insights, team/internal-contributor

#18883 dev: Add depgraph utility
  .gitignore
  dev/depgraph/.gitignore
  dev/depgraph/README.md
  dev/depgraph/go.mod
  dev/depgraph/graph.go
  dev/depgraph/graph/graph.go
  dev/depgraph/graph/imports.go
  dev/depgraph/graph/util.go
  dev/depgraph/lint.go
  dev/depgraph/lints/error.go
  dev/depgraph/lints/lint.go
  dev/depgraph/lints/no_dead_packages.go
  dev/depgraph/lints/no_reaching_into_commands.go
  dev/depgraph/lints/no_single_dependents.go
  dev/depgraph/lints/util.go
  dev/depgraph/main.go
  dev/depgraph/root/root.go
  dev/depgraph/trace.go
  dev/deps/main.go
Labels: dx, team/code-intelligence

#18885 insights: correct AllReposIterator initialization
  enterprise/internal/insights/background/historical_enqueuer.go
Labels: team/code-insights, team/internal-contributor

#18886 depgraph: List test imports as well
  dev/depgraph/graph/imports.go
Labels: team/code-intelligence

#18892 chore: Fix depgraph test package gathering
  dev/depgraph/graph/imports.go
Labels: team/code-intelligence

#18891 codenotoify: Add codenotify for depgraph
  dev/depgraph/CODENOTIFY
Labels: team/code-intelligence

#18890 depgraph: Add NoBinarySpecificSharedCode lint pass
  dev/depgraph/README.md
  dev/depgraph/lints/lint.go
  dev/depgraph/lints/no_binary_specific_shared_code.go
  dev/depgraph/lints/no_single_dependents.go
Labels: team/code-intelligence

#18896 chore: Fix typo in depgraph output
  dev/depgraph/lints/no_binary_specific_shared_code.go
Labels: team/code-intelligence

#18878 Finish overhaul of batch changes GraphQL API
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/batches/resolvers/permissions_test.go
Labels: team/batchers

#18852 gitserver: Sync cloned state periodically
  cmd/gitserver/main.go
  cmd/gitserver/server/gitolite_phabricator_test.go
  cmd/gitserver/server/lock.go
  cmd/gitserver/server/repo_info_test.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  cmd/gitserver/server/serverutil.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/extsvc/github/pulls.go
  internal/extsvc/github/repos.go
  internal/types/types.go
Labels: team/core-application

#18906 Remove import of repo-updater in batches code
  enterprise/cmd/repo-updater/main.go
  enterprise/internal/batches/background.go
Labels: team/batchers

#18887 chore: Remove dead packages
  cmd/frontend/internal/app/canonicalurl/canonical_url.go
  cmd/frontend/internal/app/canonicalurl/canonical_url_test.go
  cmd/frontend/internal/app/returnto/returnto.go
  cmd/frontend/internal/app/returnto/returnto_test.go
  internal/atomicvalue/atomicvalue.go
  internal/httputil/LICENSE
  internal/httputil/clone_request.go
  internal/httputil/logged_transport.go
  internal/httputil/respbuf.go
  internal/leader/leader.go
  internal/leader/leader_test.go
  internal/prefixsuffixsaver/CODENOTIFY
  internal/prefixsuffixsaver/prefixSuffixSaver.go
Labels: team/code-intelligence

#18915 depgraph: ~Make it useful~ make it fast
  .gitignore
  depgraph.cache
  dev/depgraph/README.md
  dev/depgraph/graph.go
  dev/depgraph/graph/graph.go
  dev/depgraph/graph/imports.go
  dev/depgraph/graph/packages.go
  dev/depgraph/graph/util.go
  dev/depgraph/main.go
  dev/depgraph/root/root.go
Labels: team/code-intelligence

#18907 gitserver: Perform prefix match on hostname
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
Labels: team/core-application

#18928 Switch to promauto wherever possible
  cmd/frontend/backend/trace.go
  cmd/frontend/graphqlbackend/externallink/repository.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/observability.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/user_usage_stats.go
  cmd/frontend/graphqlbackend/virtual_file.go
  cmd/frontend/internal/app/ui/landing.go
  cmd/github-proxy/github-proxy.go
  cmd/gitserver/server/server.go
  cmd/searcher/search/search.go
  cmd/searcher/search/search_structural.go
  cmd/symbols/internal/symbols/fetch.go
  cmd/symbols/internal/symbols/parse.go
  cmd/symbols/internal/symbols/service.go
  internal/api/internal_client.go
  internal/extsvc/awscodecommit/repos.go
  internal/extsvc/gitlab/projects.go
  internal/extsvc/phabricator/client.go
  internal/gitserver/client.go
  internal/search/backend/metered_searcher.go
  internal/store/store.go
  internal/vfsutil/cache.go
  internal/vfsutil/github_archive.go
  internal/vfsutil/gitserver.go
Labels: team/core-application

#18943 depgraph: Refactor
  dev/depgraph/README.md
  dev/depgraph/graph/graph.go
  dev/depgraph/graph/imports.go
  dev/depgraph/graph/names.go
  dev/depgraph/lints/error.go
  dev/depgraph/lints/lint.go
  dev/depgraph/lints/no_binary_specific_shared_code.go
  dev/depgraph/lints/no_dead_packages.go
  dev/depgraph/lints/no_loose_commands.go
  dev/depgraph/lints/no_reaching_into_commands.go
  dev/depgraph/lints/util.go
  dev/depgraph/trace.go
Labels: team/code-intelligence

#18947 chore: Remove cachefile
  depgraph.cache
Labels: team/code-intelligence

#18802 doc: Add workerutil usage docs
  doc/dev/background-information/index.md
  doc/dev/background-information/workers.md
  internal/workerutil/dbworker/store/store.go
Labels: team/code-intelligence

#18952 depgraph: Add additional lints
  dev/depgraph/README.md
  dev/depgraph/lints/lint.go
  dev/depgraph/lints/no_enterprise_imports_from_oss.go
  dev/depgraph/lints/no_unused_shared_command_code.go
  dev/depgraph/lints/util.go
Labels: team/code-intelligence

#18960 depgraph: Add additional lint passes
  dev/depgraph/README.md
  dev/depgraph/lints/error.go
  dev/depgraph/lints/lint.go
  dev/depgraph/lints/no_binary_specific_shared_code.go
  dev/depgraph/lints/no_dead_packages.go
  dev/depgraph/lints/no_enterprise_imports_from_oss.go
  dev/depgraph/lints/no_loose_commands.go
  dev/depgraph/lints/no_reaching_into_commands.go
  dev/depgraph/lints/no_unused_shared_command_code.go
  dev/depgraph/lints/util.go
Labels: team/code-intelligence

#18944 Repair ~campaigns~ batchers notify bot
  .github/workflows/batches-notify.yml
  .github/workflows/campaigns-notify.yml
Labels: team/batchers

#18957 Fix close changesets operation
  CHANGELOG.md
  enterprise/internal/batches/store/changesets.go
  migrations/frontend/1528395793_fix_invalid_changeset_reconciler_states.down.sql
  migrations/frontend/1528395793_fix_invalid_changeset_reconciler_states.up.sql
  migrations/frontend/bindata.go
Labels: bug, team/batchers

#18970 gitserver: Handle more hostname comparisons
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
Labels: team/core-application

#18963 batches: rename and update schemata
  internal/batches/batch_spec.go
  schema/batch_spec.schema.json
  schema/batch_spec_stringdata.go
  schema/changeset_spec.schema.json
  schema/changeset_spec_stringdata.go
  schema/gen.sh
  schema/schema.go
Labels: team/batchers

#18941 Rename all DB resources to new batch changes naming
  cmd/frontend/internal/app/updatecheck/client.go
  enterprise/cmd/frontend/main.go
  enterprise/internal/batches/background/spec_expire.go
  enterprise/internal/batches/background/ssh_migrator.go
  enterprise/internal/batches/background/ssh_migrator_test.go
  enterprise/internal/batches/reconciler/executor.go
  enterprise/internal/batches/reconciler/executor_test.go
  enterprise/internal/batches/reconciler/reconciler_test.go
  enterprise/internal/batches/resolvers/batch_change.go
  enterprise/internal/batches/resolvers/batch_spec.go
  enterprise/internal/batches/resolvers/code_host_connection.go
  enterprise/internal/batches/resolvers/code_host_connection_test.go
  enterprise/internal/batches/resolvers/deprecated.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/resolvers/urls.go
  enterprise/internal/batches/search/text.go
  enterprise/internal/batches/service/main_test.go
  enterprise/internal/batches/service/service_apply_batch_change_test.go
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/batch_changes_test.go
  enterprise/internal/batches/store/batch_specs.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/store/changesets.go
  internal/batches/changeset_spec.go
  internal/database/schema.md
  internal/database/user_credentials.go
  internal/database/user_credentials_test.go
  internal/usagestats/CODENOTIFY
  internal/usagestats/batches.go
  internal/usagestats/batches_test.go
  migrations/frontend/1528395794_campaigns_rename.down.sql
  migrations/frontend/1528395794_campaigns_rename.up.sql
  migrations/frontend/bindata.go
Labels: team/batchers

#18971 db: Add index on gitserver_repos clone_status
  internal/database/schema.md
  migrations/frontend/1528395795_add_clone_status_index_to_gitserver_repos.down.sql
  migrations/frontend/1528395795_add_clone_status_index_to_gitserver_repos.up.sql
  migrations/frontend/bindata.go
Labels: team/core-application

#18981 gitserver: Set repo as not_cloned when removed on disk
  cmd/gitserver/main.go
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: team/core-application

#18988 depgraph: Update trace command to accept depth
  dev/depgraph/README.md
  dev/depgraph/trace.go
Labels: team/code-intelligence

#18989 Fix license check in batches web UI
  client/web/src/enterprise/batches/list/backend.ts
  client/web/src/integration/batches.test.ts
Labels: team/batchers

#18999 depgraph: Add trace-internal command
  dev/depgraph/README.md
  dev/depgraph/main.go
  dev/depgraph/trace.go
  dev/depgraph/trace_internal.go
  dev/depgraph/visualization/dot.go
Labels: team/code-intelligence

#18979 Add settings for code insight display locations
  CHANGELOG.md
  client/web/src/nav/NavLinks.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/routes.tsx
  client/web/src/search/input/SearchPage.tsx
  schema/schema.go
  schema/settings.schema.json
  schema/settings_stringdata.go
Labels: team/code-insights, webapp

#19005 depgraph: Adopt ffcli
  dev/depgraph/go.mod
  dev/depgraph/go.sum
  dev/depgraph/lint.go
  dev/depgraph/main.go
  dev/depgraph/trace.go
  dev/depgraph/trace_internal.go
Labels: team/code-intelligence

#19000 go.mod: handle the campaignutils rename
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/store/batch_specs_test.go
  go.mod
  go.sum
  internal/batches/batch_spec.go
  internal/batches/changeset_spec.go
Labels: team/batchers

#19024 gitserver: Set clone status after attempting to clone repo
  cmd/gitserver/main.go
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
Labels: team/core-application

#19031 gitserver: Trial remove repos that are on the wrong shard
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
Labels: team/core-application

#19037 depgraph: Add summary subcommand
  dev/depgraph/README.md
  dev/depgraph/lint.go
  dev/depgraph/main.go
  dev/depgraph/summary.go
  dev/depgraph/trace.go
  dev/depgraph/trace_internal.go
Labels: team/code-intelligence

#19033 Ensure we always use the newest external service
  enterprise/internal/batches/syncer/util.go
  enterprise/internal/batches/syncer/util_test.go
Labels: team/batchers

#19045 cli: update minimum version
  internal/src-cli/consts.go
Labels: team/batchers

#18992 lib: Introduce non-enterprise lib directory
  dev/ci/go-test.sh
  doc/dependency_decisions.yml
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  enterprise/lib/README.md
  enterprise/lib/go.mod
  enterprise/lib/go.sum
  go.mod
  go.sum
  lib/README.md
  lib/codeintel/utils/README.md
  lib/codeintel/utils/gzip.go
  lib/codeintel/utils/gzip_test.go
  lib/codeintel/utils/indexer_name.go
  lib/codeintel/utils/indexer_name_test.go
  lib/codeintel/utils/rate.go
  lib/codeintel/utils/split_file.go
  lib/codeintel/utils/split_file_test.go
  lib/codeintel/utils/stitch_files.go
  lib/codeintel/utils/stitch_files_test.go
  lib/codeintel/utils/upload.go
  lib/codeintel/utils/upload_test.go
  lib/go.mod
  lib/go.sum
Labels: team/code-intelligence

#18933 Add repos from user_public_repos to the user's search context.
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/internal/search/repos/repos.go
  cmd/frontend/internal/search/repos/repos_test.go
  internal/database/default_repos_test.go
  internal/database/mockstores.go
  internal/database/repos.go
  internal/database/repos_db_test.go
  internal/database/user_public_repos.go
  internal/database/user_public_repos_mock.go
Labels: team/core-application, team/search

#19055 gitserver: Clean up repos that are on the wrong shard
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
Labels: team/core-application

#14207 server: Add parameter to start only PosgreSQL
  cmd/server/shared/postgres.go
  cmd/server/shared/redis.go
  cmd/server/shared/shared.go
  doc/admin/install/docker/index.md
Labels: team/distribution

#19060 database: Properly populate repo_id in IterateRepoGitserverStatus
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: team/core-application

#19010 codeintel: More intelligently read from result chunks
  enterprise/internal/codeintel/stores/lsifstore/locations.go
Labels: team/code-intelligence

#19063 gitserver: Setting clone status handles missing row
  cmd/gitserver/server/cleanup.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: team/core-application

#19050 doc/dev: add Code Insights developer docs
  doc/dev/background-information/insights/backend.md
  doc/dev/background-information/insights/diagrams/architecture.excalidraw
  doc/dev/background-information/insights/diagrams/architecture.svg
  doc/dev/background-information/insights/index.md
Labels: team/code-insights, team/internal-contributor

#19083 Fix confusing changeset next sync date tooltip
  client/web/src/enterprise/batches/detail/changesets/ChangesetLastSynced.tsx
Labels: bug, team/batchers

#19053 Improve performance for batch changes with many changesets
  enterprise/internal/batches/resolvers/changeset.go
  enterprise/internal/batches/resolvers/changeset_connection.go
  enterprise/internal/batches/resolvers/changeset_connection_test.go
  enterprise/internal/batches/state/state.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/batches/store/changesets_test.go
  internal/database/schema.md
  migrations/frontend/1528395797_faster_changeset_lookups.down.sql
  migrations/frontend/1528395797_faster_changeset_lookups.up.sql
  migrations/frontend/bindata.go
Labels: perf, team/batchers

#19088 Fix yield func in historical enqueuer, also a bug report for infinite looping frames
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
Labels: team/code-insights

#19082 insights: various critical bug fixes & improvements
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/background/queryrunner/graphql.go
  enterprise/internal/insights/background/queryrunner/graphql_results.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/resolvers/insight_series_resolver_test.go
  enterprise/internal/insights/store/mock_store_interface.go
  enterprise/internal/insights/store/store.go
  enterprise/internal/insights/store/store_test.go
Labels: team/code-insights, team/internal-contributor

#19013 client/web: when tracing a query, add a link to the trace
  client/web/src/search/results/streaming/StreamingSearchResults.tsx
  client/web/src/search/results/streaming/progress/StreamingProgress.story.tsx
  client/web/src/search/results/streaming/progress/StreamingProgress.tsx
  client/web/src/search/results/streaming/progress/StreamingProgressCount.test.tsx
  client/web/src/search/results/streaming/progress/StreamingProgressCount.tsx
  client/web/src/search/results/streaming/progress/__snapshots__/StreamingProgressCount.test.tsx.snap
  client/web/src/search/stream.ts
  cmd/frontend/internal/search/progress.go
  cmd/frontend/internal/search/search.go
  internal/search/streaming/api/progress.go
  internal/search/streaming/api/progress_test.go
  internal/search/streaming/api/testdata/golden/TestSearchProgress/traced.json
  internal/search/streaming/api/types.go
Labels: debugging, dx

#19069 Re-enable the 'public code' box in the Manage Repositories page, & hook up to graphql APIs
  client/web/src/site-admin/backend.ts
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  cmd/frontend/graphqlbackend/set_user_public_repos.go
  cmd/frontend/graphqlbackend/user.go
  internal/database/user_public_repos.go
Labels: team/core-application

#19117 batches: update doc image and video assets
  doc/batch_changes/explanations/introduction_to_batch_changes.md
  doc/batch_changes/how-tos/closing_or_deleting_a_batch_change.md
  doc/batch_changes/how-tos/configuring_user_credentials.md
  doc/batch_changes/how-tos/creating_a_batch_change.md
  doc/batch_changes/how-tos/handling_errored_changesets.md
  doc/batch_changes/how-tos/publishing_changesets.md
  doc/batch_changes/how-tos/tracking_existing_changesets.md
  doc/batch_changes/how-tos/viewing_batch_changes.md
  doc/batch_changes/quickstart.md
  doc/batch_changes/tutorials/search_and_replace_specific_terms.md
  doc/batch_changes/tutorials/update_base_images_in_dockerfiles.md
  doc/cli/quickstart.md
Labels: team/batchers

#19119 Fix alignment of diffstat in changesets list
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
Labels: team/batchers

#19052 Some low hanging fruit improvements for burndown chart
  client/web/src/enterprise.scss
  client/web/src/enterprise/batches/detail/BatchChangeBurndownChart.scss
  client/web/src/enterprise/batches/detail/BatchChangeBurndownChart.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeBurndownChart.tsx
  enterprise/internal/batches/resolvers/batch_change.go
  enterprise/internal/batches/resolvers/changeset_counts_test.go
  enterprise/internal/batches/state/counts.go
  enterprise/internal/batches/state/counts_test.go
Labels: team/batchers

#19153 dev: Update glock
  doc/dev/background-information/languages/testing_go_code.md
  enterprise/cmd/executor-queue/internal/server/handler.go
  enterprise/cmd/executor-queue/internal/server/handler_test.go
  enterprise/cmd/executor-queue/internal/server/lifecycle_test.go
  enterprise/cmd/executor-queue/internal/server/server.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration_test.go
  go.mod
  go.sum
  internal/goroutine/periodic.go
  internal/goroutine/periodic_test.go
  internal/oobmigration/runner.go
  internal/oobmigration/runner_test.go
  internal/workerutil/dbworker/resetter.go
  internal/workerutil/dbworker/resetter_test.go
  internal/workerutil/worker.go
  internal/workerutil/worker_test.go
Labels: team/code-intelligence

#18843 UI: Update how we badge code intelligence results
  client/branded/src/components/panel/views/FileLocations.tsx
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/branded/src/global-styles/badge.scss
  client/branded/src/global-styles/global-styles.story.tsx
  client/packages/sourcegraph-extension-api/package.json
  client/packages/sourcegraph-extension-api/src/sourcegraph.d.ts
  client/shared/src/api/client/types/hover.test.ts
  client/shared/src/api/client/types/hover.ts
  client/shared/src/api/extension/api/decorations.ts
  client/shared/src/api/extension/api/types.ts
  client/shared/src/api/extension/test/extensionHost.hover.test.ts
  client/shared/src/api/extension/test/extensionHost.providers.test.ts
  client/shared/src/api/integration-test/languageFeatures.test.ts
  client/shared/src/components/BadgeAttachment.test.tsx
  client/shared/src/components/BadgeAttachment.tsx
  client/shared/src/components/FileMatch.tsx
  client/shared/src/components/FileMatchChildren.scss
  client/shared/src/components/FileMatchChildren.tsx
  client/shared/src/components/FileMatchContext.ts
  client/shared/src/components/ResultContainer.tsx
  client/shared/src/components/__snapshots__/BadgeAttachment.test.tsx.snap
  client/shared/src/hover/HoverOverlay.scss
  client/shared/src/hover/HoverOverlay.story.tsx
  client/shared/src/hover/HoverOverlay.tsx
  client/shared/src/settings/settings.ts
  client/web/src/components/shared.tsx
  schema/schema.go
  schema/settings.schema.json
  schema/settings_stringdata.go
Labels: team/code-intelligence

#19118 Faster changeset search
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/store/changesets.go
  internal/database/schema.md
  migrations/frontend/1528395798_changeset_title.down.sql
  migrations/frontend/1528395798_changeset_title.up.sql
  migrations/frontend/bindata.go
Labels: perf, team/batchers

#18849 One-click OAuth for code host + improved usability
  client/web/src/SourcegraphWebApp.scss
  client/web/src/user/settings/UserSettingsArea.scss
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
  client/web/src/user/settings/codeHosts/AddCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/RemoveCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/UpdateCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/codeHosts/modalHints.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
  client/web/src/user/settings/routes.tsx
Labels: team/core-application

#19145 Don't show sync banner when external service was just added
  client/web/src/components/externalServices/ExternalServicePage.story.tsx
  client/web/src/components/externalServices/ExternalServicesPage.story.tsx
  client/web/src/components/externalServices/backend.ts
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
  cmd/frontend/graphqlbackend/set_external_service_repos.go
Labels: team/core-application

#18788 Update loading button labels
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: design-qa, team/core-application

#19201 insights: minor finishing touches to make historical insights better
  dev/start.sh
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  go.mod
  go.sum
  migrations/codeinsights/1000000005_wipe_data.down.sql
  migrations/codeinsights/1000000005_wipe_data.up.sql
  migrations/codeinsights/bindata.go
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: team/code-insights, team/internal-contributor

#19177 Add docs for SSH credentials
  CHANGELOG.md
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
  doc/batch_changes/how-tos/configuring_user_credentials.md
  doc/batch_changes/how-tos/handling_errored_changesets.md
  doc/batch_changes/references/requirements.md
Labels: team/batchers

#19206 insights: cleanup old completed/failed jobs in the DB
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/queryrunner/cleaner.go
Labels: team/code-insights, team/internal-contributor

#18846 codeintel: Update pings to include number of repos with intelligence
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/app/updatecheck/handler_test.go
  doc/admin/pings.md
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/types/codeintel.go
  internal/usagestats/aggregated.go
Labels: team/code-intelligence

#19200 extensibility: remove published on link from extension page
  client/web/src/extensions/extension/RegistryExtensionOverviewPage.tsx
Labels: merge-on-any-approve

#19159 db: Deprecate the repo.cloned column
  CHANGELOG.md
  cmd/frontend/graphqlbackend/repositories_test.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  go.sum
  internal/database/repos.go
  internal/database/repos_db_test.go
  internal/database/repos_perm_test.go
  internal/database/schema.md
  internal/repos/status_messages_test.go
  internal/repos/store_test.go
  internal/repos/testdata/bitbucketserver-repos-path-pattern.golden
  internal/repos/testdata/bitbucketserver-repos-simple.golden
  internal/repos/testdata/bitbucketserver-repos-ssh.golden
  internal/repos/testdata/bitbucketserver-repos-username.golden
  internal/repos/testdata/golden/BitbucketCloudSource_makeRepo_path-pattern
  internal/repos/testdata/golden/BitbucketCloudSource_makeRepo_simple
  internal/repos/testdata/golden/BitbucketCloudSource_makeRepo_ssh
  internal/repos/testdata/golden/GitLabSource_makeRepo_path-pattern
  internal/repos/testdata/golden/GitLabSource_makeRepo_simple
  internal/repos/testdata/golden/GitLabSource_makeRepo_ssh
  internal/repos/testdata/golden/GithubSource_makeRepo_path-pattern
  internal/repos/testdata/golden/GithubSource_makeRepo_simple
  internal/repos/testdata/golden/GithubSource_makeRepo_ssh
  internal/repos/testdata/golden/PerforceSource_makeRepo_path-pattern
  internal/repos/testdata/golden/PerforceSource_makeRepo_simple
  internal/repos/types_test.go
  internal/types/types.go
  migrations/frontend/1528395799_add_clone_status_conditional_indexes.down.sql
  migrations/frontend/1528395799_add_clone_status_conditional_indexes.up.sql
  migrations/frontend/bindata.go
Labels: team/core-application

#19212 Pin kubectl used for CI
  .tool-versions
Labels: team/distribution

#19172 gitserver: Store most recent clone or update error in the db
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: team/core-application

#19216 gitserver: Rename doRepoupdate2 to doBackgroundRepoUpdate
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  cmd/gitserver/server/serverutil.go
Labels: team/core-application

#19217 gitserver: Factor out testing boilerplate
  cmd/gitserver/server/server_test.go
Labels: team/core-application

#19175 Fix UserSettingsRepositoriesPage to show user repos when only added via public code (no code host connections)
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
  internal/database/repos.go
Labels: cloud/milestone-3, team/core-application

#19205 batches: add rename notice and update changelog
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Labels: team/batchers

#19207 Fix cloning status on repo page not updating
  client/web/src/repo/RepoContainer.tsx
Labels: bug

#19220 repo-updater: Use NoNamespace instead of -1
  cmd/repo-updater/shared/main.go
  internal/database/external_services.go
Labels: team/core-application

#19231 src-cli: update minimum version
  internal/src-cli/consts.go
Labels: team/batchers

#19046 doc: provide more detailed instructions for bouncing docsite
  doc/dev/how-to/documentation_implementation.md
Labels: docs

#19227 web: support repos without default branch
  client/web/src/repo/backend.ts
Labels: team/extensibility, webapp

#19252 frontend: Avoid ratelimit panic
  cmd/frontend/graphqlbackend/rate_limit.go
  cmd/frontend/internal/httpapi/graphql.go
Labels: team/core-application

#19256 migrations: use go1.16 embed directive instead of go-bindata
  dev/db/rebase_migration.sh
  internal/database/dbconn/migration.go
  migrations/README.md
  migrations/codeinsights/bindata.go
  migrations/codeinsights/gen.go
  migrations/codeinsights/migrations_test.go
  migrations/codeintel/bindata.go
  migrations/codeintel/gen.go
  migrations/codeintel/migrations_test.go
  migrations/frontend/README.md
  migrations/frontend/bindata.go
  migrations/frontend/gen.go
  migrations/frontend/migrations_test.go
  migrations/migrations.go
  migrations/migrations_test.go
Labels: dx

#19248 Error handling style changes.
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/core-application

#19156 docs: add extension dev and testing docs
  doc/dev/background-information/architecture/sourcegraph-extensions.md
  doc/dev/background-information/web/extensions-testing-onion.svg
Labels: extensions, team/extensibility

#19245 Check props for deep equality in ActionsNavItems
  client/shared/src/actions/ActionsNavItems.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
Labels: bug, merge-on-any-approve, team/extensibility

#19247 codeintel: add dev tool for diffing of semantic indexes
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
  enterprise/lib/codeintel/lsif/conversion/correlate.go
  enterprise/lib/codeintel/lsif/conversion/group.go
  enterprise/lib/codeintel/lsif/conversion/group_test.go
  enterprise/lib/codeintel/lsif/conversion/util.go
  enterprise/lib/codeintel/pathexistence/git.go
  enterprise/lib/codeintel/pathexistence/git_test.go
  enterprise/lib/codeintel/semantic/diff/diff.go
  enterprise/lib/codeintel/semantic/diff/diff_test.go
  enterprise/lib/codeintel/semantic/diff/testdata/TestDiffOnEditedDumps.golden
  enterprise/lib/codeintel/semantic/diff/testdata/project1/dump-new.lsif
  enterprise/lib/codeintel/semantic/diff/testdata/project1/dump-old.lsif
  enterprise/lib/codeintel/semantic/diff/testdata/project1/dump-permuted.lsif
  enterprise/lib/codeintel/semantic/diff/testdata/project1/dump.lsif
  enterprise/lib/codeintel/semantic/diff/testdata/project1/test.go
  enterprise/lib/codeintel/semantic/query.go
  enterprise/lib/codeintel/semantic/repl/main.go
  enterprise/lib/codeintel/semantic/types.go
  enterprise/lib/codeintel/semantic/util.go
  enterprise/lib/codeintel/tools/lsif-semantic-diff/main.go
  enterprise/lib/go.mod
  enterprise/lib/go.sum
  go.mod
  go.sum
Labels: team/code-intelligence

#19277 extensibility: remove regression tests
  client/web/package.json
  client/web/src/regression/extensions.test.ts
Labels: extensions, team/extensibility

#18679 graphqlbackend: Stub out new StatusMessage fields
  client/web/src/nav/StatusMessagesNavItem.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/status_messages.go
  internal/repos/status_messages.go
Labels: team/core-application

#19304 gitserver: Remove wrong shard cleanup task
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
Labels: team/core-application

#19184 extensibility: handle extension host sync errors for diff
  client/web/src/components/diff/FileDiffConnection.tsx
Labels: extensions, team/extensibility

#19328 database: Ignore order and limit in RepoStore.Count
  internal/database/repos.go
  internal/database/repos_test.go
Labels: team/backend-platform

#19279 Finish work inlining most assets
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/repo-updater/shared/assets/bindata.go
  cmd/repo-updater/shared/assets/gen.go
  cmd/repo-updater/shared/main.go
  cmd/repo-updater/shared/state.html.tmpl
  cmd/server/shared/assets/assets.go
  cmd/server/shared/assets/bindata.go
  cmd/server/shared/assets/gen.go
  cmd/server/shared/nginx.go
  cmd/server/shared/redis.go
  dev/db/squash_migrations.sh
  dev/tools.go
  go.mod
  go.sum
  migrations/README.md
Labels: debt

#19352 database: Change DBNameSuffix in internal/database
  internal/database/gitserver_repos_test.go
  internal/database/main_test.go
Labels: team/core-application

#19373 batches: update YouTube embed after rename
  client/web/src/enterprise/batches/global/marketing/BatchChangesDotComPage.tsx
  client/web/src/enterprise/batches/list/BatchChangesListEmpty.tsx
Labels: team/batchers

#19345 Make authenticator marshalling for DB reusable
  enterprise/internal/batches/background/ssh_migrator.go
  internal/database/authenticator.go
  internal/database/user_credentials.go
  internal/database/user_credentials_test.go
  internal/extsvc/auth/basic.go
Labels: team/batchers

#19360 Add @storybook/addon-a11y
  .storybook/main.js
  package.json
  yarn.lock
Labels: team/frontend-platform

#19355 Add internal docs for the encryption package
  internal/encryption/README.md
  internal/encryption/keyring/ring.go
Labels: security, team/core-application

#19415 Add emailHeader support to http auth proxy
  CHANGELOG.md
  doc/admin/auth/index.md
  enterprise/cmd/frontend/internal/auth/httpheader/middleware.go
  enterprise/cmd/frontend/internal/auth/httpheader/middleware_test.go
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: team/core-application

#19337 Redirect to Batch Changes marketing page on dotcom
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.story.tsx
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  client/web/src/enterprise/batches/global/marketing/BatchChangesDotComPage.tsx
  client/web/src/enterprise/batches/global/nav/BatchChangesNavItem.tsx
  client/web/src/nav/MenuNavItem.story.tsx
  client/web/src/nav/NavLinks.tsx
  cmd/frontend/internal/app/ui/router.go
Labels: team/batchers

#19413 repo-updater: Stop calling SetClonedRepos
  cmd/repo-updater/shared/main.go
  internal/database/default_repos_test.go
  internal/database/repos.go
Labels: team/core-application

#19365 Developer documentation: Add accessibility docs
  doc/dev/background-information/index.md
  doc/dev/background-information/web/accessibility.md
  doc/dev/background-information/web/index.md
Labels: team/frontend-platform

#19416 schema: Use go embed instead of stringdata tool
  schema/aws_codecommit_stringdata.go
  schema/batch_spec_stringdata.go
  schema/bitbucket_cloud_stringdata.go
  schema/bitbucket_server_stringdata.go
  schema/changeset_spec_stringdata.go
  schema/gen.sh
  schema/github_stringdata.go
  schema/gitlab_stringdata.go
  schema/gitolite_stringdata.go
  schema/other_external_service_stringdata.go
  schema/perforce_stringdata.go
  schema/phabricator_stringdata.go
  schema/settings_stringdata.go
  schema/site_stringdata.go
  schema/stringdata.go
Labels: team/core-application

#19382 Don't import from enterprise in OSS web client codebase
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/batches/BatchChangesNavItem.tsx
  client/web/src/batches/icons.tsx
  client/web/src/code-monitoring/CodeMonitoringLogo.tsx
  client/web/src/code-monitoring/CodeMonitoringNavItem.tsx
  client/web/src/code-monitoring/index.ts
  client/web/src/contributions.ts
  client/web/src/enterprise/batches/close/BatchChangeClosePage.tsx
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringNode.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
  client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.tsx
  client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.tsx
  client/web/src/enterprise/code-monitoring/global/GlobalCodeMonitoringArea.tsx
  client/web/src/enterprise/code-monitoring/index.ts
  client/web/src/enterprise/dotcom/productSubscriptions/ProductLicenseValidity.tsx
  client/web/src/enterprise/dotcom/productSubscriptions/ProductSubscriptionLabel.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/enterprise/namespaces/navitems.ts
  client/web/src/enterprise/productSubscription/ExpirationDate.tsx
  client/web/src/enterprise/productSubscription/ProductLicenseInfoDescription.tsx
  client/web/src/enterprise/productSubscription/TrueUpStatusSummary.tsx
  client/web/src/enterprise/site-admin/productSubscription/ProductSubscriptionStatus.tsx
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/enterprise/user/productSubscriptions/NewProductSubscriptionPaymentSection.tsx
  client/web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/MenuNavItem.story.tsx
  client/web/src/nav/NavLinks.test.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/productSubscription/helpers.ts
  client/web/src/routes.tsx
  client/web/src/search/results/SearchResults.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/SearchResultsList.tsx
  client/web/src/search/results/streaming/StreamingSearchResults.tsx
  client/web/src/search/stats/contributions.ts
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/sidebaritems.ts
  client/web/src/site/LicenseExpirationAlert.tsx
  dev/check/all.sh
  dev/check/ts-enterprise-import.sh
Labels: debt

#19409 web: redirect `/users/:username` -> `/users/:username/settings/profile`
  client/web/src/org/area/routes.tsx
  client/web/src/user/area/routes.tsx
Labels: team/frontend-platform

#19107 move useLocalStorage to shared folder
  client/shared/src/util/useLocalStorage.ts
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/components/shared.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionNewReleasePage.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
  client/web/src/nav/VersionContextDropdown.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/actions/GoToCodeHostAction.tsx
  client/web/src/search/input/SearchOnboardingTour.ts
Labels: team/frontend-platform

#19422 clarify docs on using configID in SAML auth providers, and referencing those providers in external service config
  doc/admin/auth/saml/azure_ad.md
  doc/admin/auth/saml/generic.md
  doc/admin/auth/saml/jump_cloud.md
  doc/admin/auth/saml/microsoft_adfs.md
  doc/admin/auth/saml/okta.md
  doc/admin/auth/saml/one_login.md
  doc/admin/repo/permissions.md
Labels: team/core-application

#19414 Improve a11y of survey page
  client/web/src/Layout.tsx
  client/web/src/marketing/SurveyPage.tsx
  client/web/src/marketing/SurveyToast.tsx
  client/web/src/marketing/Toast.scss
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
Labels: accessibility, team/frontend-platform, webapp

#19417 move syncExternalService in setExternalServiceRepos into goroutine
  cmd/frontend/graphqlbackend/set_external_service_repos.go
  cmd/frontend/graphqlbackend/set_external_service_repos_test.go
Labels: team/core-application

#19402 Add not found handler to global batch changes area
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
Labels: team/batchers

#19404 Add sass index file for batches module
  client/web/src/enterprise.scss
  client/web/src/enterprise/batches/index.scss
Labels: team/batchers

#19105 Use browser fetcher to download Puppeteer browser
  client/shared/package.json
  client/shared/scripts/download-puppeteer-browser.ts
  client/shared/src/testing/driver.ts
  client/shared/src/testing/puppeteer-browser-revision.ts
  enterprise/dev/ci/internal/ci/pipeline-steps.go
  package.json
Labels: team/extensibility, testing

#19269 encryption: Add oob migration for external service configuration
  cmd/frontend/internal/cli/serve_cmd.go
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
  internal/encryption/keyring/ring.go
  migrations/frontend/1528395802_external_service_config_migration.down.sql
  migrations/frontend/1528395802_external_service_config_migration.up.sql
Labels: team/core-application

#19366 [Insights]: Add icon and text id to each view grid ui
  client/web/src/insights/backend.ts
  client/web/src/repo/tree/ViewGrid.scss
  client/web/src/repo/tree/ViewGrid.tsx
Labels: team/code-insights

#18260 replace legacy tabs with reach/ui
  client/branded/src/components/Tabs.scss
  client/branded/src/components/Tabs.tsx
  client/branded/src/components/panel/Panel.tsx
  client/branded/src/components/panel/views/EmptyPanelView.tsx
  client/branded/src/components/panel/views/ExtensionsLoadingView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.test.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/tabs.scss
  client/web/src/SourcegraphWebApp.scss
  client/web/src/repo/RepoRevisionSidebar.scss
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
  client/web/src/repo/RevisionsPopover.tsx
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.tsx
  client/web/src/tree/Tree.scss
  client/web/src/tree/Tree.tsx
  client/web/src/tree/util.tsx
  package.json
  yarn.lock
Labels: team/frontend-platform

#19187 extensibility: fix GitLab doc not found error for deleted files
  client/browser/src/shared/code-hosts/gitlab/domFunctions.ts
  client/browser/src/shared/code-hosts/gitlab/scrape.ts
Labels: extensions, team/extensibility

#19459 Add mute comment for stopPropagation at insight description
  client/web/src/repo/tree/ViewGrid.tsx
Labels: bug, team/code-insights, webapp

#19458 fix file decorations on files sidebar
  client/web/src/tree/Directory.tsx
  client/web/src/tree/File.tsx
Labels: team/frontend-platform

#19441 frontend: Enable uncloned repo count on cloud
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
Labels: team/core-application

#19453 sg: Fix env vars in sg.config.yaml so that frontend boots up properly
  dev/sg/sg.config.example.yaml
Labels: sg
