Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-06, with the labels that each got.

#21439 Refresh: Update Breadcrumb sizing and structure
  client/web/src/repo/FilePathBreadcrumbs.tsx
  client/web/src/repo/RepoRevisionContainer.scss
  client/web/src/repo/RepoRevisionContainer.tsx
Labels: team/frontend-platform

#21455 Refresh: Update Tooltip designs
  client/branded/src/components/tooltip/Tooltip.story.tsx
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/tooltips.scss
  client/web/src/SourcegraphWebApp.scss
Labels: design refresh, team/frontend-platform

#21556 web: Allow filtering repos by failure on site admin page
  client/web/src/site-admin/SiteAdminRepositoriesPage.tsx
  client/web/src/site-admin/backend.ts
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: team/core-application

#21576 graphqlbackend: Unexport repositoryArgs
  cmd/frontend/graphqlbackend/repositories.go
Labels: team/core-application

#21561 Don't crash emails settings when no email configured
  client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
Labels: bug

#21560 web: code intel panel header + references section redesign
  client/branded/src/components/panel/Panel.scss
  client/branded/src/components/panel/Panel.tsx
  client/branded/src/components/panel/views/EmptyPanelView.tsx
  client/branded/src/components/panel/views/ExtensionsLoadingView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.scss
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsViewButton.tsx
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/branded/src/global-styles/tabs.scss
  client/shared/src/components/FileMatch.tsx
  client/shared/src/components/FileMatchChildren.scss
  client/shared/src/components/ResultContainer.scss
  client/shared/src/components/ResultContainer.tsx
Labels: design refresh, team/frontend-platform

#21580 sg: Capture stdout/stderr and print on error
  dev/sg/run.go
Labels: sg

#21575 Adjust meter colors based on Felix's feedback
  client/branded/src/global-styles/meter.scss
  client/web/src/tree/Tree.scss
Labels: team/frontend-platform

#21530 codeintel: Fix error on worker reprocessing
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
Labels: team/code-intelligence

#21557 Properly center “Show more matches” button
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
Labels: team/frontend-platform

#21477 docs: misc updates to onboarding docs
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
  doc/batch_changes/explanations/batch_changes_design.md
  doc/batch_changes/explanations/how_src_executes_a_batch_spec.md
  doc/batch_changes/explanations/introduction_to_batch_changes.md
  doc/dev/background-information/architecture/life-of-a-repository.md
  doc/dev/background-information/batch_changes/index.md
Labels: docs, team/batchers

#21288 Add support of non existent in a timeframe data-points
  client/web/src/insights/core/analytics.test.ts
  client/web/src/insights/core/backend/api/get-search-insight-content.ts
  client/web/src/views/ChartViewContent/ChartViewContent.story.tsx
  client/web/src/views/ChartViewContent/charts/line/colors.ts
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
  client/web/src/views/ChartViewContent/charts/line/components/NonActiveBackground.tsx
  client/web/src/views/ChartViewContent/charts/line/components/TooltipContent.tsx
  client/web/src/views/ChartViewContent/charts/line/constants.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/generate-accessors.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/use-scales.ts
  client/web/src/views/ChartViewContent/charts/line/types.ts
  package.json
  yarn.lock
Labels: crud-ui, team/code-insights

#21596 Try to get Chromatic components to react to theme changes
  client/branded/src/components/BrandedStory.tsx
  client/storybook/src/RedesignToggleDecorator.tsx
  client/storybook/src/chromatic-story/create-chromatic-story.tsx
  client/web/src/components/WebStory.tsx
Labels: team/frontend-platform

#21476 codeintel: Add a queue for dependency indexing
  enterprise/cmd/frontend/internal/codeintel/background/indexing/dependency_indexing_scheduler.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/dependency_indexing_scheduler_test.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/gen.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/iface.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/mock_scanner_test.go
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_references_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/gen.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/worker.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer_test.go
  enterprise/internal/codeintel/stores/dbstore/dependency_index.go
  enterprise/internal/codeintel/stores/dbstore/dependency_index_test.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/worker.go
  enterprise/internal/codeintel/stores/dbstore/xrepo.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_scanner.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_test.go
  enterprise/internal/codeintel/stores/lsifstore/types.go
  internal/database/schema.md
  migrations/frontend/1528395825_add_upload_dependency_indexing_jobs.down.sql
  migrations/frontend/1528395825_add_upload_dependency_indexing_jobs.up.sql
Labels: dependency-indexing, team/code-intelligence

#21491 cmd/repo-updater: Add navigation links in debug page
  cmd/repo-updater/shared/state.html.tmpl
Labels: team/core-application

#21467 extensibility: add padding to blob for status bar
  client/web/src/repo/blob/Blob.scss
Labels: merge-on-any-approve

#21651 #21605 document the DISABLE_CODE_INSIGHTS flag
  doc/dev/background-information/insights/backend.md
Labels: team/code-insights

#21666 batches: update Jira ticket batch changes example link
  doc/batch_changes/references/faq.md
Labels: docs, team/batchers

#21533 insights: added rate limiters for better control over code insights performance
  CHANGELOG.md
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/worker.go
  schema/schema.go
  schema/site.schema.json
Labels: team/code-insights

#21647 web: `HoverOverlay` remove extra content margin if close button is not present
  client/shared/src/hover/HoverOverlay.scss
  client/shared/src/hover/HoverOverlay.tsx
Labels: design refresh, team/frontend-platform

#21631 web: `Definition` and `History` sections Code Intel panel redesign
  client/branded/src/components/panel/Panel.scss
  client/branded/src/components/panel/Panel.tsx
  client/branded/src/components/panel/views/EmptyPanelView.tsx
  client/branded/src/components/panel/views/ExtensionsLoadingView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.scss
  client/web/src/components/FilteredConnection/ConnectionNodes.tsx
  client/web/src/components/FilteredConnection/FilteredConnection.scss
  client/web/src/components/FilteredConnection/FilteredConnection.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/repo/RepoRevisionSidebarCommits.module.scss
  client/web/src/repo/RepoRevisionSidebarCommits.tsx
  client/web/src/repo/commits/GitCommitNode.scss
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/commits/GitCommitNodeByLine.module.scss
  client/web/src/repo/commits/GitCommitNodeByline.tsx
  client/web/src/repo/commits/__snapshots__/GitCommitNodeByline.test.tsx.snap
Labels: design refresh, team/frontend-platform

#21686 graphql: Use GithubSource instead of raw client
  cmd/frontend/graphqlbackend/external_service.go
  internal/repos/types.go
  internal/repos/types_test.go
Labels: team/core-application

#21659 database/locker: Extract locker from dbstore
  enterprise/cmd/frontend/internal/codeintel/background/commitgraph/gen.go
  enterprise/cmd/frontend/internal/codeintel/background/commitgraph/iface.go
  enterprise/cmd/frontend/internal/codeintel/background/commitgraph/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/background/commitgraph/updater.go
  enterprise/cmd/frontend/internal/codeintel/background/commitgraph/updater_test.go
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/internal/codeintel/stores/dbstore/lock.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  internal/database/locker/CODENOTIFY
  internal/database/locker/locker.go
  internal/database/locker/locker_test.go
Labels: team/code-intelligence

#20967 oobmigrations: Startup check
  client/web/src/site-admin/SiteAdminMigrationsPage.test.ts
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  cmd/frontend/backend/versions.go
  cmd/frontend/backend/versions_test.go
  cmd/frontend/graphqlbackend/oobmigrations.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/internal/cli/migrations.go
  cmd/frontend/internal/cli/serve_cmd.go
  doc/dev/background-information/oobmigrations.md
  enterprise/cmd/frontend/main.go
  internal/database/schema.md
  internal/oobmigration/runner.go
  internal/oobmigration/runner_test.go
  internal/oobmigration/store.go
  internal/oobmigration/store_test.go
  internal/oobmigration/version.go
  internal/oobmigration/version_test.go
  migrations/frontend/1528395823_feature_flags.down.sql
  migrations/frontend/1528395826_track_first_version.down.sql
  migrations/frontend/1528395826_track_first_version.up.sql
  migrations/frontend/1528395827_oob_enterprise_flag.down.sql
  migrations/frontend/1528395827_oob_enterprise_flag.up.sql
  migrations/frontend/1528395828_split_oob_version_columns.down.sql
  migrations/frontend/1528395828_split_oob_version_columns.up.sql
Labels: RFC-311, team/code-intelligence

#21670 doc: Document oobmigration startup check
  CHANGELOG.md
  doc/admin/how-to/index.md
  doc/admin/how-to/unfinished_migration.md
  doc/admin/index.md
  doc/admin/migrations.md
  doc/admin/updates.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
Labels: RFC-311

#21685 Refresh: Update UserAvatar sizing
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/commits/GitCommitNodeByline.tsx
  client/web/src/user/UserAvatar.scss
Labels: team/frontend-platform

#21673 Adjust button colors, spinner and check for auth on every page refresh
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: team/core-application

#21678 batches: revise query for changeset spec expiry
  CHANGELOG.md
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/store/changeset_specs_test.go
Labels: team/batchers

#21625 Fix modify calls over user/org settings.
  client/web/src/insights/core/jsonc-operation.ts
  client/web/src/insights/pages/dashboard/hooks/use-delete-insight.ts
Labels: bug, team/code-insights

#21423 Add integration visual tests for code insight dashboard page
  client/web/src/components/alerts.tsx
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/InsightContentCard.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/core/backend/api/get-search-insight-content.ts
  client/web/src/insights/core/backend/requests/fetch-repositories.ts
  client/web/src/insights/core/backend/requests/fetch-search-insight.ts
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/components/series-card/SeriesCard.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/edit/EditInsightPage.tsx
  client/web/src/insights/pages/edit/components/EditSearchInsight.tsx
  client/web/src/integration/insights.test.ts
  client/web/src/integration/insights/insights-visual.test.ts
  client/web/src/integration/insights/utils/insight-extension-bundles.ts
  client/web/src/integration/insights/utils/insight-mock-data.ts
  client/web/src/integration/insights/utils/override-graphql-with-extensions.ts
  client/web/src/views/ChartViewContent/charts/pie/components/PieArc.tsx
Labels: team/code-insights, webapp

#21708 open batch changes as external link
  client/web/src/nav/GlobalNavbar.tsx
Labels: team/frontend-platform

#21714 batches: fix malformed links in deprecation banner
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Labels: team/batchers

#21681 web: update the web app docs
  doc/dev/background-information/web/styling.md
  doc/dev/background-information/web/web_app.md
Labels: docs, team/frontend-platform

#21692 Refresh: Update code host, repositories and account security setting pages
  client/web/src/user/settings/UserSettingsArea.scss
  client/web/src/user/settings/auth/ExternalAccount.tsx
  client/web/src/user/settings/auth/ExternalAccountsSignIn.module.scss
  client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
  client/web/src/user/settings/auth/UserSettingsSecurityPage.scss
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: design refresh, team/frontend-platform

#21619 Add code insights creation UI integration tests
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/edit/components/EditSearchInsight.tsx
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/utils/insight-mock-data.ts
  client/web/src/integration/insights/utils/override-graphql-with-extensions.ts
Labels: team/code-insights, testing

#21725 web: update secondary alert border-color
  client/branded/src/global-styles/alert-redesign.scss
  client/shared/src/hover/HoverOverlay.scss
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.story.tsx
Labels: design refresh, team/frontend-platform

#21717 Use correct color for card borders
  client/branded/src/global-styles/card.scss
Labels: design refresh

#21728 Refresh: Further updates to various settings pages
  client/web/src/user/settings/auth/ExternalAccount.tsx
  client/web/src/user/settings/auth/ExternalAccountsSignIn.module.scss
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.scss
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: team/frontend-platform

#21731 Refresh: Update event log page
  client/web/src/enterprise/user/settings/UserEventLogsPage.module.scss
  client/web/src/enterprise/user/settings/UserEventLogsPage.tsx
Labels: team/frontend-platform

#21735 Add sub directory support for test-integration command
  package.json
Labels: bug, debt

#21736 codeintel: Add Get{Uploads,Indexes}ByIDs to dbstore
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence

#21702 phabricator: Remove custom json unmarshalling
  internal/database/repos.go
  internal/extsvc/phabricator/client.go
  internal/extsvc/phabricator/client_test.go
  internal/extsvc/phabricator/testdata/golden/ListRepos-pagination.json
  internal/extsvc/phabricator/testdata/golden/ListRepos-repos-listed.json
  internal/extsvc/phabricator/testdata/vcr/GetDiffInfo.yaml
  internal/extsvc/phabricator/testdata/vcr/GetRawDiff.yaml
  internal/extsvc/phabricator/testdata/vcr/ListRepos.yaml
  internal/repos/clone_url_test.go
Labels: team/core-application

#21724 web: fix close button position in dismissible alert
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/DismissibleAlert.scss
  client/web/src/components/DismissibleAlert/DismissibleAlert.module.scss
  client/web/src/components/DismissibleAlert/DismissibleAlert.story.tsx
  client/web/src/components/DismissibleAlert/DismissibleAlert.tsx
  client/web/src/components/DismissibleAlert/index.ts
  client/web/src/enterprise/batches/detail/BulkOperationsAlerts.tsx
  client/web/src/enterprise/batches/detail/ChangesetsArchivedNotice.tsx
  client/web/src/enterprise/batches/detail/SupersedingBatchSpecAlert.tsx
  client/web/src/global/GlobalAlerts.tsx
  client/web/src/global/__snapshots__/Notices.test.tsx.snap
  client/web/src/marketing/ServerBanner.tsx
  client/web/src/site/DockerForMacAlert.tsx
  client/web/src/site/LicenseExpirationAlert.tsx
  client/web/src/site/NeedsRepositoryConfigurationAlert.tsx
  client/web/src/site/PerformanceWarningAlert.tsx
  client/web/src/site/__snapshots__/LicenseExpirationAlert.test.tsx.snap
Labels: design refresh, team/frontend-platform

#21740 codeintel: Expose associated upload id on index records
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  internal/database/schema.md
  migrations/frontend/1528395830_index_associated_index_id.down.sql
  migrations/frontend/1528395830_index_associated_index_id.up.sql
Labels: team/code-intelligence

#21745 codeintel: Expose associated index/upload id in graphql layer
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/index.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/index_connection.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/prefetcher.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/prefetcher_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/upload.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/upload_connection.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
Labels: team/code-intelligence

#21746 codeintel: Fix index out of range panic
  enterprise/cmd/frontend/internal/codeintel/background/indexing/dependency_indexing_scheduler.go
Labels: team/code-intelligence

#21474 diff page: refresh design
  client/branded/src/global-styles/colors-redesign.scss
  client/shared/src/global-styles/icons.scss
  client/web/src/components/diff/FileDiffHunks.scss
  client/web/src/components/diff/FileDiffHunks.tsx
  client/web/src/components/diff/FileDiffNode.scss
  client/web/src/components/diff/FileDiffNode.tsx
  client/web/src/extensions/components/StatusBar.scss
  client/web/src/repo/commit/DiffModeSelector.tsx
  client/web/src/repo/commit/RepositoryCommitPage.tsx
  client/web/src/repo/commits/GitCommitNode.scss
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/commits/GitCommitNodeByline.tsx
  client/web/src/repo/commits/__snapshots__/GitCommitNodeByline.test.tsx.snap
  client/web/src/user/UserAvatar.scss
Labels: design refresh, merge-on-any-approve

#21768 worker: Add skeleton service
  cmd/server/shared/shared.go
  cmd/worker/CODENOTIFY
  cmd/worker/Dockerfile
  cmd/worker/README.md
  cmd/worker/build.sh
  cmd/worker/main.go
  cmd/worker/shared/main.go
  dev/Procfile
  dev/prometheus/all/prometheus_targets.yml
  dev/prometheus/linux/prometheus_targets.yml
  dev/src-prof-services.json
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  enterprise/cmd/server/build.sh
  enterprise/cmd/worker/CODENOTIFY
  enterprise/cmd/worker/Dockerfile
  enterprise/cmd/worker/README.md
  enterprise/cmd/worker/build.sh
  enterprise/cmd/worker/main.go
  enterprise/dev/ci/images/images.go
  enterprise/dev/src-prof-services.json
  monitoring/definitions/worker.go
  monitoring/main.go
  sg.config.yaml
Labels: dx, worker

#21752 fix regression icon size
  client/shared/src/global-styles/icons.scss
Labels: merge-on-any-approve

#21737 Fix navbar jitter in redesign
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/nav.scss
  client/branded/src/global-styles/tabs.scss
  client/shared/src/extensions/devtools/index.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/enterprise/batches/BatchChangeTabs.module.scss
  client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewTabs.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.module.scss
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/extensions/extension/ExtensionArea.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/area/OrgHeader.tsx
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RevisionsPopover.tsx
  client/web/src/searchContexts/SearchContextsListPage.tsx
  client/web/src/user/area/UserArea.tsx
  client/web/src/user/area/UserAreaHeader.tsx
Labels: design refresh

#21753 chore: Fix incorrect method comment
  enterprise/internal/codeintel/gitserver/client.go
Labels: team/code-intelligence

#21774 worker: Add task runner machinery
  cmd/worker/main.go
  cmd/worker/shared/config.go
  cmd/worker/shared/main.go
  cmd/worker/shared/task.go
  enterprise/cmd/worker/main.go
  internal/env/baseconfig.go
Labels: dx, worker

#21336 Design Refresh: Enable site-wide
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/branded/src/global-styles/variables-redesign.scss
  client/shared/src/hover/__snapshots__/HoverOverlay.test.tsx.snap
  client/shared/src/testing/utils.ts
  client/shared/src/util/useRedesignToggle.ts
  client/storybook/src/chromatic-story/Chromatic.story.tsx
  client/storybook/src/chromatic-story/add-story.ts
  client/storybook/src/chromatic-story/create-chromatic-story.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/extensions/__snapshots__/ExtensionRegistrySidenav.test.tsx.snap
  client/web/src/integration/search-onboarding.test.ts
  client/web/src/integration/search.test.ts
  client/web/src/integration/utils.ts
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/nav/__snapshots__/NavLinks.test.tsx.snap
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/web/src/regression/codeintel.test.ts
  client/web/src/repo/commits/__snapshots__/GitCommitNodeByline.test.tsx.snap
  client/web/src/search/input/toggles/__snapshots__/Toggles.test.tsx.snap
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
  client/web/src/search/results/streaming/progress/StreamingProgressSkippedButton.test.tsx
  client/web/src/search/results/streaming/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/web/src/search/results/streaming/sidebar/FilterLink.test.tsx
  client/web/src/search/results/streaming/sidebar/FilterLink.tsx
  client/web/src/search/results/streaming/sidebar/__snapshots__/FilterLink.test.tsx.snap
  client/web/src/user/__snapshots__/UserAvatar.test.tsx.snap
  dev/global-settings.json
Labels: design refresh, team/frontend-platform

#21797 web: remove `text-primary` class from links under the redesign theme
  client/web/src/user/settings/auth/ExternalAccount.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/emails/UserEmail.tsx
  client/web/src/user/settings/repositories/RepositoryNode.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: design refresh, team/frontend-platform

#21809 Contributors page: ensure name and avatar are vertically centered
  client/web/src/repo/stats/RepositoryStatsContributorsPage.scss
Labels: team/frontend-platform

#21486 codeintel: Add associated upload and index records to UI
  client/web/src/components/Timeline.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelAssociatedIndex.scss
  client/web/src/enterprise/codeintel/detail/CodeIntelAssociatedIndex.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelAssociatedUpload.scss
  client/web/src/enterprise/codeintel/detail/CodeIntelAssociatedUpload.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexMeta.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexPage.story.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexPage.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadMeta.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.story.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.tsx
  client/web/src/enterprise/codeintel/index.scss
  client/web/src/enterprise/codeintel/list/CodeIntelIndexNode.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelIndexesPage.story.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelUploadNode.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelUploadsPage.story.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelState.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelUploadOrIndexCommit.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelUploadOrIndexIndexer.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelUploadOrIndexLastActivity.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelUploadOrIndexRoot.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelUploadOrIndexerRepository.tsx
  client/web/src/enterprise/codeintel/shared/backend.ts
Labels: team/code-intelligence

#21817 Minor comment fixes
  cmd/gitserver/server/server.go
  internal/repos/scheduler.go
Labels: team/core-application

#21822 resources-report: Update go.mod
  internal/cmd/resources-report/go.mod
Labels: team/core-application

#21820 web: update global alerts redesign styles
  client/web/src/components/DismissibleAlert/DismissibleAlert.module.scss
  client/web/src/global/GlobalAlerts.scss
Labels: design refresh, team/frontend-platform

#21790 batches: document how to ignore templating delimiters
  doc/_resources/assets/docsite.css
  doc/batch_changes/references/batch_spec_cheat_sheet.md
  doc/batch_changes/references/batch_spec_templating.md
  doc/batch_changes/references/batch_spec_yaml_reference.md
  doc/batch_changes/references/faq.md
Labels: docs, team/batchers

#21706 repos: Introduce repo.stars column for Github and Gitlab repos
  internal/database/dbutil/dbutil.go
  internal/database/repos.go
  internal/database/schema.md
  internal/extsvc/gitlab/projects.go
  internal/extsvc/gitlab/projects_test.go
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/gitlab.go
  internal/repos/gitlab_test.go
  internal/repos/store.go
  internal/repos/store_test.go
  internal/repos/syncer_test.go
  internal/repos/testdata/golden/GitLabSource_makeRepo_path-pattern
  internal/repos/testdata/golden/GitLabSource_makeRepo_simple
  internal/repos/testdata/golden/GitLabSource_makeRepo_ssh
  internal/types/types.go
  migrations/frontend/1528395831_add_stars_column_to_repo.down.sql
  migrations/frontend/1528395831_add_stars_column_to_repo.up.sql
Labels: team/search-core

#21468 extensibility: simplify status bar position calculation
  client/web/src/repo/blob/Blob.tsx
Labels: merge-on-any-approve

#21825 Fix code host button display logic
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
Labels: team/core-application

#21723 Disable save button when user didn't make changes
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/core-application

#20966 executor: Abandon orphaned jobs
  enterprise/cmd/executor-queue/internal/server/lifecycle.go
  enterprise/cmd/executor-queue/internal/server/lifecycle_test.go
  enterprise/cmd/executor-queue/internal/server/routes.go
  enterprise/cmd/executor/internal/apiclient/client.go
  enterprise/cmd/executor/internal/apiclient/client_test.go
  enterprise/cmd/executor/internal/command/run.go
  enterprise/cmd/executor/internal/worker/handler.go
  enterprise/cmd/executor/internal/worker/idset.go
  enterprise/cmd/executor/internal/worker/idset_test.go
  enterprise/cmd/executor/internal/worker/worker.go
Labels: team/code-intelligence

#21832 codeintel: Add more repository ids to the dependency index allowlist
  enterprise/cmd/frontend/internal/codeintel/background/indexing/dependency_indexing_scheduler.go
Labels: dependency-indexing, team/code-intelligence

#21779 worker: Add common initialize methods for external services
  cmd/worker/shared/db.go
  cmd/worker/shared/main.go
  cmd/worker/shared/memo.go
  cmd/worker/shared/service_connections.go
  cmd/worker/shared/task.go
  dev/check/go-dbconn-import.sh
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/cmd/worker/internal/codeintel/dbstore.go
  enterprise/cmd/worker/internal/codeintel/gitserver.go
  enterprise/cmd/worker/internal/codeintel/lsifstore.go
  enterprise/cmd/worker/main.go
Labels: dx, worker

#21837 worker: Rename task to job
  cmd/worker/README.md
  cmd/worker/shared/config.go
  cmd/worker/shared/job.go
  cmd/worker/shared/main.go
  enterprise/cmd/worker/README.md
  enterprise/cmd/worker/main.go
Labels: dx, worker

#21824 web: update branch selector icon padding
  client/web/src/repo/RepoRevisionContainer.scss
  client/web/src/repo/RepoRevisionContainer.tsx
Labels: design refresh, team/frontend-platform

#21846 dev: Disable flaky ioutil lint check
  dev/check/all.sh
Labels: team/core-application

#21808 Refresh: Deprecate old `border-radius` values
  client/branded/src/global-styles/border-radius.scss
  client/branded/src/global-styles/index.scss
  client/browser/src/app.scss
Labels: team/frontend-platform

#21835 repos: List default repos by descending star order
  internal/database/dbcache/cached_default_repos_test.go
  internal/database/repos.go
  internal/database/repos_test.go
Labels: team/search-core

#21852 graphql: On error, return nil scopes
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/repos/types.go
Labels: team/core-application

#20883 codeintel: use repositoryId field in event_logs.argument json instead of url column
  enterprise/internal/codeintel/stores/dbstore/repo_usage.go
  enterprise/internal/codeintel/stores/dbstore/repo_usage_test.go
Labels: private-code-for-sg, team/code-intelligence

#21861 Post refresh: Remove usage of `theme-classic`
  client/shared/src/util/useRedesignToggle.ts
  client/storybook/src/RedesignToggleDecorator.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/enterprise/batches/BatchChangeTabs.module.scss
  client/web/src/enterprise/batches/BatchChangeTabs.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.module.scss
  client/web/src/enterprise/batches/preview/BatchChangePreviewStatsBar.module.scss
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.module.scss
  client/web/src/enterprise/code-monitoring/CodeMonitoringNode.scss
  client/web/src/nav/RedesignToggle/RedesignToggle.tsx
  client/web/src/org/settings/members/InviteForm.scss
  client/web/src/user/settings/UserSettingsSidebar.scss
  client/web/src/user/settings/UserSettingsSidebar.tsx
  client/web/src/user/settings/profile/UserSettingsProfilePage.scss
  client/web/src/user/settings/profile/UserSettingsProfilePage.tsx
Labels: team/frontend-platform

#21873 Fix missing space on subscriptions setting page
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
Labels: merge-on-any-approve, team/frontend-platform

#21860 oauth: No need to request extra scope for GitLab
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
Labels: team/core-application

#21862 web: move alert styles out from the `.theme-redesign`
  client/branded/src/global-styles/alert-redesign.scss
  client/branded/src/global-styles/alert.scss
  client/branded/src/global-styles/color-scheme-mixins.scss
  client/branded/src/global-styles/index.scss
  client/shared/src/notifications/NotificationItem.scss
  client/web/src/global/GlobalAlerts.scss
Labels: design refresh, team/frontend-platform

#21857 Post refresh: Remove redesign references from Storybook
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/storybook/src/RedesignToggleDecorator.tsx
  client/storybook/src/chromatic-story/add-story.ts
  client/storybook/src/main.ts
  client/storybook/src/preview.ts
  client/storybook/src/redesign-toggle-toolbar/RedesignToggleStorybook.tsx
  client/storybook/src/redesign-toggle-toolbar/register.ts
  client/wildcard/src/components/Container/Container.story.tsx
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
Labels: team/frontend-platform

#21858 Post refresh: Remove legacy semantic colors
  client/branded/src/global-styles/colors-redesign.scss
  client/web/src/extensions/components/ActionItemsBar.scss
  client/web/src/extensions/components/StatusBar.scss
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.module.scss
  client/web/src/search/results/SearchResultsFilterBars.scss
Labels: team/frontend-platform

#20896 internal/usagestats: Stop sending url and arguments to bigquery
  internal/usagestats/event_handlers.go
Labels: june4th

#21856 Change Code Insights url hierarchy
  CHANGELOG.md
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/pages/creation/CreationRoutes.tsx
  client/web/src/insights/pages/creation/intro/IntroCreationPage.tsx
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
  client/web/src/integration/insights/create-insights.test.ts
Labels: debt, team/code-insights

#21744 Add local storage save logic for search based creation UI
  CHANGELOG.md
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useForm.ts
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
Labels: crud-ui, team/code-insights

#21886 gitlab: Backoff correctly when sync is forbidden
  internal/errcode/code.go
  internal/extsvc/gitlab/client.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
  internal/repoupdater/errors.go
Labels: team/core-application

#21912 Revert "frontend: warm default repo cache before serving traffic (#21238)"
  cmd/frontend/backend/backend.go
  cmd/frontend/internal/cli/serve_cmd.go
Labels: team/search-core

#21877 search: Resolve repositories in star ranked order
  client/shared/package.json
  client/shared/src/search/query/completion.ts
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/graphqlbackend/search_filter_suggestions.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_suggestions.go
  cmd/frontend/graphqlbackend/search_suggestions_test.go
  cmd/frontend/graphqlbackend/search_test.go
  internal/database/repos.go
  internal/search/repos/repos.go
  internal/search/run/repository.go
Labels: team/search-core

#21888 Fix default branch throwing error instead of null
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_test.go
Labels: bug, team/batchers

#21920 worker: Adjust authz
  cmd/worker/main.go
  enterprise/cmd/worker/main.go
Labels: auth, worker

#21917 monitoring: repo-updater monitoring should use max, not sum
  monitoring/definitions/repo_updater.go
Labels: team/core-application

#21939 search: compute priority with stars column value
  cmd/frontend/internal/httpapi/internal.go
Labels: team/search-core

#21173 Implement reenqueue bulk operation type
  CHANGELOG.md
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/detail/bulk-operations/BulkOperationNode.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
  client/web/src/enterprise/batches/detail/changesets/ReenqueueChangesetsModal.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  doc/batch_changes/how-tos/bulk_operations_on_changesets.md
  enterprise/internal/batches/background/bulk_processor.go
  enterprise/internal/batches/resolvers/bulk_operation.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/types/changeset_job.go
Labels: team/batchers

#21926 chore: Add worker to ENTERPRISE_COMMANDS
  enterprise/dev/start.sh
Labels: dx, worker

#21914 web: move `HoverOverlay` styles out from the `.theme-redesign`
  client/browser/src/shared/code-hosts/github/codeHost.ts
  client/shared/src/hover/HoverOverlay.scss
  client/shared/src/hover/HoverOverlayAlerts/HoverOverlayAlerts.tsx
  client/shared/src/hover/HoverOverlayContents/HoverOverlayContent/HoverOverlayContent.tsx
  client/shared/src/hover/HoverOverlayContents/HoverOverlayContents.tsx
  client/shared/src/hover/__snapshots__/HoverOverlay.test.tsx.snap
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.fixtures.ts
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.module.scss
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.story.tsx
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.tsx
Labels: design refresh, team/frontend-platform

#21964 web: Rename to code hosts on site admin page
  client/web/src/components/externalServices/ExternalServicesPage.tsx
Labels: team/core-application

#21965 repo-updater: Don't alert for user added code hosts on Cloud
  cmd/repo-updater/shared/main.go
  internal/repos/metrics.go
Labels: team/core-application

#21876 Add new design for fuzzy finder
  client/web/src/components/fuzzyFinder/FuzzyFinder.tsx
  client/web/src/components/fuzzyFinder/FuzzyModal.module.scss
  client/web/src/components/fuzzyFinder/FuzzyModal.story.tsx
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/components/fuzzyFinder/HighlightedLink.module.scss
  client/web/src/components/fuzzyFinder/HighlightedLink.tsx
  client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.ts
Labels: team/code-intelligence

#21950 Adds global CTA banner
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/components/externalServices/backend.ts
  client/web/src/global/GlobalAlerts.tsx
  client/web/src/integration/graphQlResults.ts
  client/web/src/site/GitHubCodeHostScopeAlert/GitHubScopeAlert.tsx
  client/web/src/site/GitHubCodeHostScopeAlert/GithubScopeProvider.tsx
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: team/core-application

#21948 worker: Add job metrics
  cmd/worker/shared/main.go
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/worker.go
Labels: dx, worker

#21730 Swap order of "Edit" and "Delete" buttons
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
Labels: team/code-insights

#21999 Make sure react keys are unique
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: team/core-application

#21996 Fix global alert style for GitHub private code notification
  client/web/src/global/GlobalAlert.tsx
  client/web/src/site/GitHubCodeHostScopeAlert/GitHubScopeAlert.tsx
Labels: bug, design refresh

#22003 CHANGELOG: Add an entry for the redesign
  CHANGELOG.md
Labels: team/frontend-platform

#21919 Improve accessibility of fuzzy file finder
  client/web/src/components/Dialog.scss
  client/web/src/components/fuzzyFinder/FuzzyModal.module.scss
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
Labels: team/code-intelligence

#21699 Add suggestions to repositories field in code insight creation UI
  CHANGELOG.md
  client/branded/src/global-styles/forms.scss
  client/web/src/insights/components/form/form-input/FormInput.module.scss
  client/web/src/insights/components/form/form-input/FormInput.tsx
  client/web/src/insights/components/form/form-input/types.ts
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useForm.ts
  client/web/src/insights/components/form/repositories-field/RepositoriesField.module.scss
  client/web/src/insights/components/form/repositories-field/RepositoriesField.tsx
  client/web/src/insights/components/form/repositories-field/components/flex-textarea/FlexTextArea.tsx
  client/web/src/insights/components/form/repositories-field/components/flex-textarea/FlexTextarea.module.scss
  client/web/src/insights/components/form/repositories-field/components/suggestion-panel/SuggestionPanel.module.scss
  client/web/src/insights/components/form/repositories-field/components/suggestion-panel/SuggestionPanel.tsx
  client/web/src/insights/components/form/repositories-field/hooks/use-repo-suggestions.ts
  client/web/src/insights/components/form/repositories-field/utils/get-suggestions-search-term.test.ts
  client/web/src/insights/components/form/repositories-field/utils/get-suggestions-search-term.ts
  client/web/src/insights/components/form/repositories-field/utils/memoize-async.ts
  client/web/src/insights/core/backend/api/get-repository-suggestions.ts
  client/web/src/insights/core/backend/insights-api.ts
  client/web/src/insights/core/backend/requests/fetch-repository-suggestions.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  package.json
  yarn.lock
Labels: crud-ui, team/code-insights

#22002 web: move code-intel bottom panel styles out from the `.theme-redesign`
  client/branded/src/components/panel/Panel.module.scss
  client/branded/src/components/panel/Panel.scss
  client/branded/src/components/panel/Panel.story.tsx
  client/branded/src/components/panel/Panel.tsx
  client/branded/src/components/panel/views/EmptyPanelView.module.scss
  client/branded/src/components/panel/views/EmptyPanelView.tsx
  client/branded/src/components/panel/views/ExtensionsLoadingView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.scss
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/branded/src/components/panel/views/PanelView.module.scss
  client/branded/src/components/panel/views/PanelView.tsx
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/shared/src/components/Resizable.module.scss
  client/shared/src/components/Resizable.scss
  client/shared/src/components/Resizable.tsx
  client/shared/src/index.scss
  client/shared/src/testing/driver.ts
  client/web/src/SourcegraphWebApp.scss
  client/web/src/end-to-end/end-to-end.test.ts
Labels: design refresh, team/frontend-platform

#22008 web: move `HierarchicalLocationsView` styles out from the `.theme-redesign`
  client/branded/src/components/panel/views/FileLocations.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.module.scss
  client/branded/src/components/panel/views/HierarchicalLocationsView.scss
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsViewButton.module.scss
  client/branded/src/components/panel/views/HierarchicalLocationsViewButton.tsx
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/shared/src/testing/driver.ts
  client/web/src/SourcegraphWebApp.scss
  client/web/src/regression/codeintel.test.ts
Labels: design refresh, team/frontend-platform

#21814 Add repository suggestions to code stats insight creation form.
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/integration/insights/create-insights.test.ts
Labels: crud-ui, team/code-insights

#21943 Add 1 click creation for search based insight creation UI
  CHANGELOG.md
  client/shared/src/search/query/validate.ts
  client/web/src/insights/components/Icons.tsx
  client/web/src/insights/components/InsightsNavLink/InsightsNavLink.tsx
  client/web/src/insights/components/index.ts
  client/web/src/insights/index.ts
  client/web/src/insights/pages/creation/CreationRoutes.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/hooks/use-editable-series.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/initial-insight-values.ts
  client/web/src/insights/pages/creation/search-insight/utils/use-url-query-insight/use-url-query-insight.test.ts
  client/web/src/insights/pages/creation/search-insight/utils/use-url-query-insight/use-url-query-insight.ts
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
  client/web/src/insights/utils/is-code-insights-enabled.ts
  client/web/src/search/panels/RepositoriesPanel.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/components/CreateCodeInsightButton.tsx
  client/web/src/search/results/streaming/StreamingSearchResults.tsx
Labels: crud-ui, team/code-insights

#22023 precise-code-intel-tester: do not make unnamed GraphQL requests
  internal/cmd/precise-code-intel-tester/query.go
  internal/cmd/precise-code-intel-tester/upload.go
  internal/cmd/precise-code-intel-tester/util/graphql.go
Labels: api-docs

#22026 docs: explain how to troubleshoot search-export extension
  doc/admin/how-to/troubleshoot-sg-extension.md
Labels: merge-on-any-approve

#21959 Implement bulk merge action
  CHANGELOG.md
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/detail/bulk-operations/BulkOperationNode.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
  client/web/src/enterprise/batches/detail/changesets/MergeChangesetsModal.story.tsx
  client/web/src/enterprise/batches/detail/changesets/MergeChangesetsModal.tsx
  client/web/src/enterprise/batches/detail/changesets/ReenqueueChangesetsModal.story.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  doc/batch_changes/how-tos/bulk_operations_on_changesets.md
  enterprise/internal/batches/background/bulk_processor.go
  enterprise/internal/batches/background/bulk_processor_test.go
  enterprise/internal/batches/background/bulk_processor_worker.go
  enterprise/internal/batches/resolvers/bulk_operation.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/common.go
  enterprise/internal/batches/sources/fake.go
  enterprise/internal/batches/sources/github.go
  enterprise/internal/batches/sources/gitlab.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/types/changeset_job.go
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
  internal/extsvc/bitbucketserver/testdata/golden/MergePullRequest-success
  internal/extsvc/bitbucketserver/testdata/vcr/MergePullRequest-not-mergeable.yaml
  internal/extsvc/bitbucketserver/testdata/vcr/MergePullRequest-success.yaml
  internal/extsvc/github/common.go
  internal/extsvc/github/testdata/golden/MergePullRequest-error
  internal/extsvc/github/testdata/golden/MergePullRequest-success
  internal/extsvc/github/testdata/vcr/TestMergePullRequest.yaml
  internal/extsvc/github/v4_test.go
  internal/extsvc/gitlab/merge_requests.go
  internal/extsvc/gitlab/merge_requests_test.go
  internal/extsvc/gitlab/mock.go
Labels: team/batchers

#22048 gitlab: 'api' scope is required to clone private repos
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
  internal/repos/clone_url.go
  internal/repos/clone_url_test.go
Labels: team/core-application

#22054 Make fuzzy finder accessible to screen readers
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/components/fuzzyFinder/HighlightedLink.tsx
Labels: team/code-intelligence

#22056 gitlab: On prem instance should request `api` scope by default
  enterprise/cmd/frontend/internal/auth/gitlaboauth/config_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/provider.go
Labels: team/core-application

#22027 web: fix useScrollToLocationHash on hashes containing ":", ".", etc.
  client/web/src/components/useScrollToLocationHash.ts
Labels: api-docs

#20965 doc: High-performance SQL guide
  doc/dev/background-information/index.md
  doc/dev/background-information/sql.md
Labels: team/code-intelligence

#22062 Change "New" badge from "Product research" to "Repositories"
  client/web/src/user/settings/sidebaritems.ts
Labels: team/frontend-platform

#21994 Insights: added commit index table and background job
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/compression/commits.go
  enterprise/internal/insights/compression/gen.go
  enterprise/internal/insights/compression/mock_commit_store.go
  enterprise/internal/insights/compression/worker.go
  enterprise/internal/insights/compression/worker_test.go
  migrations/codeinsights/1000000006_commit_index.down.sql
  migrations/codeinsights/1000000006_commit_index.up.sql
Labels: team/code-insights

#21671 Insights/creation UI pings
  CHANGELOG.md
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  doc/admin/pings.md
  internal/types/types.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: analytics, needs-analytics, team/code-insights

#22051 Use `withAuthenticatedUser` for insight router
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/pages/creation/CreationRoutes.tsx
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/edit/EditInsightPage.tsx
Labels: debt, team/code-insights

#22018 Fix Code Insight line chart with negative value for chart Y axis
  CHANGELOG.md
  client/web/src/views/ChartViewContent/ChartViewContent.story.tsx
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
  client/web/src/views/ChartViewContent/charts/line/helpers/get-range-with-padding.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/use-scales.ts
Labels: team/code-insights, webapp

#22044 Use single suggest `RepositoryField` instead of multi suggest`RepositoriesField` for lang stats creation UI.
  client/web/src/insights/components/form/repositories-field/RepositoriesField.tsx
  client/web/src/insights/components/form/repositories-field/RepositoryField.tsx
  client/web/src/insights/components/form/repositories-field/types.ts
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
Labels: team/code-insights

#22049 Add fix for count filter in data series query
  CHANGELOG.md
  client/web/src/insights/core/backend/api/get-search-insight-content/get-search-insight-content.ts
  client/web/src/insights/core/backend/api/get-search-insight-content/query-has-count-filter.ts
  client/web/src/insights/core/backend/api/get-search-insight-content/query-has-count.test.ts
  client/web/src/insights/core/backend/insights-api.ts
Labels: team/code-insights

#22089 usagestats: Small cleanups
  cmd/frontend/graphqlbackend/users.go
  cmd/frontend/internal/usagestatsdeprecated/action_handlers.go
  cmd/frontend/internal/usagestatsdeprecated/usage_stats.go
Labels: team/core-application

#21859 Post refresh: Remove `redesign-d-none`
  client/branded/src/global-styles/index.scss
  client/web/src/components/Sidebar.tsx
  client/web/src/components/__snapshots__/alerts.test.tsx.snap
  client/web/src/components/alerts.tsx
  client/web/src/enterprise/batches/detail/ClosedNotice.tsx
  client/web/src/enterprise/batches/detail/UnpublishedNotice.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsArea.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateBanner.tsx
  client/web/src/org/settings/OrgSettingsSidebar.tsx
  client/web/src/repo/DirectImportRepoAlert.tsx
  client/web/src/repo/actions/InstallBrowserExtensionAlert.tsx
  client/web/src/repo/actions/__snapshots__/InstallBrowserExtensionAlert.test.tsx.snap
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  client/web/src/search/results/SearchAlert.tsx
  client/web/src/search/results/StreamingSearchResultsFooter.tsx
  client/web/src/search/results/VersionContextWarning.tsx
  client/web/src/searchContexts/SearchContextForm.tsx
  client/web/src/settings/tokens/AccessTokenCreatedAlert.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/site/FreeUsersExceededAlert.tsx
  client/web/src/site/LicenseExpirationAlert.tsx
  client/web/src/site/NeedsRepositoryConfigurationAlert.tsx
  client/web/src/site/PerformanceWarningAlert.tsx
  client/web/src/site/__snapshots__/LicenseExpirationAlert.test.tsx.snap
  client/web/src/user/settings/UserSettingsSidebar.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/frontend-platform

#22090 Fix Safari RegExp support
  client/web/src/insights/core/backend/api/get-search-insight-content/query-has-count-filter.ts
  client/web/src/insights/core/backend/api/get-search-insight-content/query-has-count.test.ts
Labels: bug, team/code-insights, webapp

#22087 Remove code insights sandbox
  client/sandboxes/code-insights/.eslintrc.js
  client/sandboxes/code-insights/.stylelintrc.json
  client/sandboxes/code-insights/babel.config.js
  client/sandboxes/code-insights/package.json
  client/sandboxes/code-insights/src/demo.tsx
  client/sandboxes/code-insights/src/index.html
  client/sandboxes/code-insights/src/mock-api.ts
  client/sandboxes/code-insights/tsconfig.json
  client/sandboxes/code-insights/webpack.config.ts
  package.json
Labels: debt, team/code-insights

#22083 insights: #22079 fixing incorrect settings deserialization for code insights telemetry
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: team/code-insights

#22112 Refresh: Add `icon-muted`
  client/branded/src/global-styles/colors-redesign.scss
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
Labels: team/frontend-platform

#22057 extsvc: Support fetching granted OAuth scopes for GitLab
  internal/extsvc/gitlab/client.go
  internal/extsvc/gitlab/client_test.go
  internal/extsvc/gitlab/testdata/vcr/TestGetAuthenticatedUserOAuthScopes.yaml
  internal/httptestutil/recorder.go
  internal/repos/types.go
  internal/repos/types_test.go
Labels: team/core-application

#22113 Fix: Colors Storybook unable to retrieve CSS variables
  client/branded/src/components/BrandedStory.tsx
  client/branded/src/global-styles/GlobalStylesStory/ColorVariants/ColorVariants.tsx
  client/branded/tsconfig.json
  client/storybook/src/hooks/useStyles.ts
  client/web/src/components/WebStory.tsx
  client/web/tsconfig.json
Labels: team/frontend-platform

#22061 API docs: better handle no-LSIF-data error state
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
Labels: api-docs

#22141 codeintel: Add RefDescriptions to gitserver client
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
  enterprise/internal/codeintel/gitserver/observability.go
Labels: dependency-indexing, team/code-intelligence

#22058 Move line range from hash to query parameter
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/browser/src/shared/code-hosts/github/codeHost.test.ts
  client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts
  client/shared/src/commands/commands.ts
  client/shared/src/components/CodeExcerptUnhighlighted.tsx
  client/shared/src/components/FileMatchChildren.tsx
  client/shared/src/components/FileMatchContext.ts
  client/shared/src/hover/actions.test.ts
  client/shared/src/util/url.test.ts
  client/shared/src/util/url.ts
  client/web/src/Layout.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/regression/codeintel.test.ts
  client/web/src/repo/blob/Blob.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/actions/ToggleHistoryPanel.tsx
  client/web/src/repo/blob/panel/BlobPanel.tsx
  client/web/src/tree/Tree.tsx
  client/web/src/util/url.ts
Labels: webapp

#22147 web: update file explorer expand button styles
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepoRevisionSidebar.scss
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/tree/Directory.tsx
  client/web/src/tree/util.tsx
Labels: design refresh, team/frontend-platform

#22139 Add async repo resolve step for 1 click code insight creation flow
  client/web/src/insights/core/backend/api/get-resolved-search-repositories.ts
  client/web/src/insights/core/backend/insights-api.ts
  client/web/src/insights/core/backend/requests/fetch-repositories-by-search.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/utils/use-initial-values.ts
  client/web/src/insights/pages/creation/search-insight/utils/use-url-query-insight/use-url-query-insight.test.ts
  client/web/src/insights/pages/creation/search-insight/utils/use-url-query-insight/use-url-query-insight.ts
Labels: team/code-insights

#22148 Replace triggerarea color with icon-muted
  client/branded/src/global-styles/colors-redesign.scss
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.scss
Labels: team/frontend-platform

#22160 Add an upper bound for the search insight repositories resolve result
  client/web/src/insights/core/backend/requests/fetch-repositories-by-search.ts
Labels: bug, team/code-insights

#22155 doc/dev: Structural changes to Life of a repository for readability
  doc/dev/background-information/architecture/life-of-a-repository.md
Labels: docs-ux

#22170 insights: added commit indexer to the changelog
  CHANGELOG.md
Labels: team/code-insights

#21924 worker: Add docs
  CHANGELOG.md
  cmd/worker/README.md
  doc/admin/index.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/workers.md
Labels: dx, worker

#22177 codeintel: Update return type of RefDescriptions
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
Labels: team/code-intelligence

#22131 codeintel: Do not store self-references in lsif_references table
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  lib/codeintel/lsif/conversion/group.go
  lib/codeintel/lsif/conversion/group_test.go
Labels: dependency-indexing, team/code-intelligence

#22143 batches: 3.29 release chores
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.story.tsx
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
  internal/src-cli/consts.go
Labels: team/batchers

#22182 chore: Remove dead fields
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing_config.go
  enterprise/cmd/worker/internal/codeintel/indexing_job.go
Labels: team/code-intelligence

#22181 codeintel: Add rate limit to index scheduler
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler_test.go
Labels: team/code-intelligence

#22178 codeintel: Share common visible-at-tip subquery
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/xrepo.go
Labels: team/code-intelligence

#22189 update version of gjson
  go.mod
  go.sum
Labels: team/core-application, team/distribution

#22208 Add timeframe fix to the CHANGELOG.md
  CHANGELOG.md
Labels: team/code-insights

#22244 LSIF: conversion: allow correlation without pruning
  lib/codeintel/lsif/conversion/correlate.go
Labels: api-docs
