Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-12, with the labels that each got.

#28378 Add upgrade notes for query-runner removal
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#28343 codeintel: Move gitserver.Head and CommitExists
  enterprise/internal/codeintel/gitserver/client.go
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
Labels: team/repo-management, cla-signed

#28346 codeintel: Move gitserver CommitsUniqueToBranch into git package
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
Labels: team/repo-management, cla-signed

#28347 codeintel: Move gitserver.BranchesContaining to the git package
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
Labels: team/repo-management, cla-signed

#28360 sg: solely rely on errors to handle setup checks
  dev/sg/sg_setup.go
Labels: sg, team/devx, cla-signed

#28390 search: make missing repo revs error actually non-fatal
  dev/gqltest/search_test.go
  internal/search/repos/repos.go
Labels: cla-signed

#28130 Code Insights: [FE] Use Monaco query input for insight query field
  client/web/src/enterprise/insights/components/form/hooks/useField.ts
  client/web/src/enterprise/insights/components/live-preview-container/LivePreviewContainer.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/form-series-input/DataSeriesQueryField.module.scss
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/form-series-input/DataSeriesQueryField.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/search/input/MonacoQueryInput.tsx
Labels: team/code-insights, cla-signed

#28388 [CLOUD-151] Instrument encryption cache
  internal/encryption/cache/cache.go
  internal/encryption/cache/metrics.go
Labels: cla-signed

#28395 vfsutil: Remove gitserver archive
  cmd/frontend/internal/vfsutil/gitserver.go
Labels: team/repo-management, cla-signed

#27953 Add JH and Kristen to DevX
  .github/workflows/label-notify.yml
Labels: cla-signed

#28393 Enable CGO on sg binary releases to fix "too many open files" bug
  .github/workflows/sg-binary-release.yml
Labels: sg, dx-announce, cla-signed

#28349 Log schema errors
  enterprise/internal/insights/insights.go
  enterprise/internal/insights/migration/discovery.go
  enterprise/internal/insights/migration/migration.go
Labels: cla-signed

#28407 symbols: Reduce number of idle goroutines
  cmd/symbols/config.go
  cmd/symbols/internal/api/handler_test.go
  cmd/symbols/internal/parser/parser.go
  cmd/symbols/main.go
Labels: team/code-intelligence, cla-signed

#28397 search: concurrent rev validation in repo resolution
  internal/search/repos/repos.go
Labels: cla-signed

#28415 Add kevinwojo to delivery team label notifications
  .github/workflows/label-notify.yml
Labels: cla-signed

#28117 httpcli, actor: propagate actor on all internal requests
  cmd/frontend/internal/cli/http.go
  cmd/searcher/main.go
  enterprise/internal/batches/service/workspace_resolver.go
  enterprise/internal/codemonitors/background/graphql.go
  internal/actor/actor.go
  internal/actor/http.go
  internal/actor/http_test.go
  internal/httpcli/client.go
Labels: dx-announce, cla-signed

#28418 ot: rename Middleware to HTTPMiddleware for consistency
  cmd/frontend/internal/cli/http.go
  cmd/github-proxy/github-proxy.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  cmd/searcher/main.go
  cmd/symbols/main.go
  internal/trace/ot/ot.go
Labels: cla-signed

#28414 search: remove searchrepos.Resolved.RepoSet
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
Labels: cla-signed

#28331 Make `dbtest.NewDB()` fast for real
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
  internal/database/orgs_test.go
Labels: dx, cla-signed

#28420 bump schema version to fix pool
  internal/database/dbtest/pool.go
Labels: cla-signed

#28413 readme: update link to local dev enevironment
  README.md
Labels: cla-signed

#28437 migrator: Add skeleton service
  cmd/migrator/Dockerfile
  cmd/migrator/README.md
  cmd/migrator/build.sh
  cmd/migrator/main.go
  enterprise/dev/ci/images/images.go
Labels: decouple-migrations, cla-signed

#28440 EXECUTABLE IS EXECUTABLE
  cmd/migrator/build.sh
Labels: decouple-migrations, cla-signed

#28379 dbconn: Unexport MigrateDB
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  cmd/worker/workerdb/db.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/internal/insights/dbtesting/insights.go
  enterprise/internal/insights/insights.go
  internal/database/dbconn/migration.go
  internal/database/dbconn/new.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
  internal/database/dbtesting/dbtesting.go
  internal/database/schemadoc/main.go
Labels: cla-signed

#28398 syntax-highlighter: update version for rpm spec highlight
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/README.md
Labels: cla-signed

#28334 notebooks: generic input for file block
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.module.scss
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.story.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
  client/web/src/search/notebook/useBlockShortcuts.ts
Labels: cla-signed

#28389 codeintel: Move gitserverclient.RefsDescriptions into the git package
  cmd/frontend/backend/repos_vcs.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/iface.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater_test.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
  enterprise/internal/codeintel/policies/iface.go
  enterprise/internal/codeintel/policies/matcher.go
  enterprise/internal/codeintel/policies/matcher_common_test.go
  enterprise/internal/codeintel/policies/mock_iface_test.go
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  internal/gitserver/gitdomain/common.go
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
  internal/vcs/git/revisions.go
Labels: team/repo-management, cla-signed

#28458 search-blitz: disable mono_rev_symbol_small
  internal/cmd/search-blitz/queries.txt
Labels: cla-signed

#28455 gitserver: Fix json unmarshal
  cmd/gitserver/main.go
  cmd/gitserver/main_test.go
Labels: team/repo-management, cla-signed

#28391 sg: Wrap errors to be prepared for future problems
  dev/sg/main.go
Labels: cla-signed

#28402 Preselect radio button for org owners
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: cla-signed

#28461 Remove last references to Enzyme.
  client/shared/dev/enzymeSerializer.js
  client/shared/dev/enzymeSetup.js
  client/shared/src/util/enzymeSnapshotModifiers.ts
  jest.config.base.js
  package.json
  yarn.lock
Labels: team/frontend-platform, cla-signed

#28400 tracking-issue: Render a total days summary
  internal/cmd/tracking-issue/render.go
  internal/cmd/tracking-issue/testdata/issue-13675.md
  internal/cmd/tracking-issue/testdata/issue-13987.md
  internal/cmd/tracking-issue/testdata/issue-13988.md
  internal/cmd/tracking-issue/testdata/issue-14166.md
  internal/cmd/tracking-issue/testdata/last-update.txt
Labels: cla-signed

#28468 search: return repohascommitafter error when not nil
  internal/search/repos/repos.go
Labels: cla-signed

#28426 Remove dbtesting package
  cmd/frontend/graphqlbackend/repository_text_search_index_test.go
  cmd/frontend/graphqlbackend/search_alert_test.go
  cmd/frontend/internal/app/usage_stats_test.go
  cmd/frontend/registry/api/extensions_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_test.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/dotcom/billing/db_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_db_test.go
  enterprise/cmd/frontend/internal/registry/stores/extensions_test.go
  enterprise/cmd/frontend/internal/registry/stores/releases_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/batches/sources/sources_test.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/storetest/monitor_creator.go
  enterprise/internal/database/authz_test.go
  enterprise/internal/database/external_services_test.go
  enterprise/internal/insights/background/queryrunner/worker_test.go
  enterprise/internal/insights/resolvers/insight_series_resolver_test.go
  enterprise/internal/insights/resolvers/resolver_test.go
  internal/database/basestore/store_test.go
  internal/database/batch/batch_test.go
  internal/database/database_test.go
  internal/database/db_test.go
  internal/database/dbstore_db_test.go
  internal/database/dbtest/pool.go
  internal/database/dbtesting/CODENOTIFY
  internal/database/dbtesting/dbtesting.go
  internal/database/dbtesting/dbtesting_test.go
  internal/database/executors_test.go
  internal/database/users.go
  internal/database/users_test.go
  internal/insights/insights_test.go
  internal/oobmigration/store_test.go
  internal/usagestats/batches_test.go
  internal/usagestats/code_insights_test.go
  internal/usagestats/code_monitoring_test.go
  internal/usagestats/extensions_test.go
  internal/usagestats/retention_test.go
  internal/usagestats/usage_stats_test.go
  internal/workerutil/dbworker/store/helpers_test.go
  migrations/migrations_test.go
Labels: cla-signed

#28382 codeintel: Instrument upload endpoint
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_middleware.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/errors.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/observability.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_multipart.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_single.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_state.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_test.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/util.go
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/frontend/internal/codeintel/upload_handler.go
  enterprise/cmd/frontend/internal/executorqueue/init.go
  enterprise/cmd/frontend/main.go
  go.mod
  go.sum
Labels: team/code-intelligence, cla-signed

#28299 Extract duplicated CSS loaders configuration into a separate workspace
  client/browser/config/webpack/base.config.ts
  client/build-config/src/index.ts
  client/build-config/src/webpack/getCssLoaders.ts
  client/storybook/src/main.ts
  client/web/dev/webpack/get-css-loaders.ts
  client/web/webpack.config.js
Labels: gitstart, cla-signed

#27473 insights: OOB migration from settings to codeinsights-db
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/insights.go
  enterprise/internal/insights/migration/discovery.go
  enterprise/internal/insights/migration/migration.go
  enterprise/internal/insights/migration/migration_test.go
  enterprise/internal/insights/store/dashboard_store.go
  enterprise/internal/insights/store/settings_migration_jobs_store.go
  internal/conf/computed.go
  internal/database/schema.md
  migrations/codeinsights/1000000022_settings_migration_wipe_definition_tables.down.sql
  migrations/codeinsights/1000000022_settings_migration_wipe_definition_tables.up.sql
  migrations/frontend/1528395947_settings_migration_out_of_band.down.sql
  migrations/frontend/1528395947_settings_migration_out_of_band.up.sql
Labels: cla-signed

#28425 insights: Migrate InsightOrgVisible and InsightTimeIntervals pings to backend
  enterprise/internal/insights/background/pings/insights_ping_aggregators.go
  enterprise/internal/insights/background/pings/insights_ping_emitter.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: cla-signed

#28417 searcher: enable actor.HTTPMiddleware
  cmd/searcher/main.go
Labels: cla-signed

#28482 Fix broken link to tracing
  doc/code_intelligence/references/troubleshooting.md
Labels: cla-signed

#28464 Fix browser extension flaky e2e tests
  client/browser/src/end-to-end/shared.ts
Labels: browser-extension, merge-on-any-approve, team/extensibility, cla-signed

#28450 gitserver: use standardized actor propagation
  cmd/gitserver/main.go
  cmd/gitserver/server/server.go
  internal/gitserver/client.go
  internal/repos/gitolite.go
Labels: cla-signed

#28487 gitserver: move actor header backcompat to clientside
  cmd/gitserver/server/server.go
  internal/gitserver/client.go
Labels: cla-signed

#28441 dbconn: Refactor connection methods
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  cmd/worker/workerdb/db.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/internal/insights/dbtesting/insights.go
  enterprise/internal/insights/insights.go
  internal/conf/service_watcher.go
  internal/database/dbconn/connect.go
  internal/database/dbconn/migration.go
  internal/database/dbconn/new.go
  internal/database/dbconn/schema.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
  internal/database/schemadoc/main.go
  migrations/migrations_test.go
Labels: decouple-migrations, cla-signed

#28489 searcher: enable Google Cloud profiler profiler when running on sourcegraph.com
  cmd/searcher/main.go
Labels: cla-signed

#28449 search: factor out private user repo lookup
  cmd/frontend/graphqlbackend/search_results.go
Labels: cla-signed

#28493 search: simplify defer functions
  cmd/frontend/graphqlbackend/search_results.go
Labels: cla-signed

#28495 if test db already exists, drop it and recreate
  internal/database/dbtest/pool.go
Labels: cla-signed

#28452 search: move private user repo look up to repos package
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/repos/repos.go
Labels: cla-signed

#28496 schemadoc: Refactor use of dbconn
  internal/database/schema.codeintel.md
  internal/database/schemadoc/main.go
Labels: decouple-migrations, cla-signed

#28411 ssbc: Persist cache result on workspace
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace.go
  enterprise/cmd/frontend/internal/executorqueue/queues/batches/mock_iface_test.go
  enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform.go
  enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform_test.go
  enterprise/internal/batches/background/batch_spec_workspace_creator.go
  enterprise/internal/batches/store/batch_spec_workspaces.go
  enterprise/internal/batches/types/batch_spec_workspace.go
  internal/database/schema.md
  migrations/frontend/1528395947_cache_entry_persist.down.sql
  migrations/frontend/1528395947_cache_entry_persist.up.sql
Labels: team/batchers, cla-signed

#28500 Fixup migration
  migrations/frontend/1528395948_cache_entry_persist.down.sql
  migrations/frontend/1528395948_cache_entry_persist.up.sql
Labels: cla-signed

#28499 dbconn: Rename ClownTown -> ForTestDatabase
  enterprise/internal/insights/dbtesting/insights.go
  internal/database/dbconn/connect.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
Labels: decouple-migrations, cla-signed

#28502 Clean up codemonitors tests
  enterprise/internal/codemonitors/action_jobs_test.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/queries_test.go
  enterprise/internal/codemonitors/recipients_test.go
  enterprise/internal/codemonitors/trigger_jobs_test.go
Labels: cla-signed

#28430 updating fuzzy finder shortcut
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/keyboardShortcuts/keyboardShortcuts.ts
  client/web/src/search/input/MonacoQueryInput.tsx
Labels: cla-signed

#28506 search: qualify repo subset symbol search job
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/symbol/symbol.go
Labels: cla-signed

#28510 Change repo to apache/echarts
  doc/code_intelligence/tutorials/indexing_ts_repo.md
Labels: cla-signed

#28428 adding amplitude events
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.test.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
  client/web/src/tree/ChildTreeLayer.tsx
  client/web/src/tree/Tree.tsx
  client/web/src/tree/TreeLayer.tsx
  client/web/src/tree/TreeRoot.tsx
Labels: cla-signed

#28511 set default sidebar toggle based on settings
  client/web/src/repo/RepoRevisionSidebar.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#28503 search: create global text search job
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/unindexed/unindexed.go
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#28488 dev/ci: always assign an explicit queue to put job on
  .buildkite/pipeline.yml
  enterprise/dev/ci/internal/buildkite/buildkite.go
Labels: cla-signed

#28508 Use returned IDs for EnqueueActionJobsForQuery
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/codemonitors/action_jobs.go
  enterprise/internal/codemonitors/action_jobs_test.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/mock_store_test.go
  enterprise/internal/codemonitors/queries.go
  enterprise/internal/codemonitors/queries_test.go
  enterprise/internal/codemonitors/store.go
  enterprise/internal/codemonitors/trigger_jobs.go
  enterprise/internal/codemonitors/trigger_jobs_test.go
Labels: cla-signed

#28350 Improve Percy test coverage
  client/web/src/integration/batches.test.ts
  client/web/src/integration/notebook.test.ts
  client/web/src/integration/search.test.ts
Labels: gitstart, cla-signed

#28301 Extract duplicated Webpack Monaco configuration into a separate workspace
  client/build-config/src/index.ts
  client/build-config/src/paths.ts
  client/build-config/src/webpack/monaco-editor.ts
  client/storybook/src/main.ts
  client/storybook/src/webpack.config.common.ts
  client/storybook/src/webpack.config.dll.ts
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/monacoPlugin.ts
  client/web/dev/webpack/monacoWebpack.ts
  client/web/webpack.config.js
Labels: gitstart, cla-signed

#28446 Show a single invitation banner for Orgs
  client/web/src/org/settings/members/InviteForm.tsx
Labels: team/cloud-saas, cla-signed

#28516 sg: Remove extra character in sg config
  sg.config.yaml
Labels: cla-signed

#28490 httptrace: rename HTTPTraceMiddleware to HTTPMiddleware
  cmd/frontend/internal/cli/http.go
  cmd/github-proxy/github-proxy.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  cmd/searcher/main.go
  cmd/symbols/main.go
  internal/trace/httptrace.go
Labels: cla-signed

#28394 codeintel: Remove more uses of execResolveRevGitCommand
  enterprise/internal/codeintel/gitserver/client.go
  internal/vcs/git/commits.go
  internal/vcs/git/tree.go
Labels: team/repo-management, cla-signed

#28533 tracking-issue: Update go version
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed

#28477 codeintel: Move CommitGraph related code into the git package
  enterprise/cmd/frontend/internal/codeintel/resolvers/exists.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/exists_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/iface.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater_test.go
  enterprise/internal/codeintel/commitgraph/commit_graph.go
  enterprise/internal/codeintel/commitgraph/commit_graph_test.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/dumps_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  internal/gitserver/gitdomain/commit_graph.go
  internal/gitserver/gitdomain/commit_graph_test.go
  internal/vcs/git/commits.go
Labels: team/repo-management, cla-signed

#28536 tracking-issue: Remove summary
  internal/cmd/tracking-issue/render.go
  internal/cmd/tracking-issue/testdata/issue-13675.md
  internal/cmd/tracking-issue/testdata/issue-13987.md
  internal/cmd/tracking-issue/testdata/issue-13988.md
  internal/cmd/tracking-issue/testdata/issue-14166.md
  internal/cmd/tracking-issue/testdata/last-update.txt
Labels: team/repo-management, cla-signed

#28474 Code Insights: [FE] Update react-grid-layout library
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/built-in-insight/BuiltInInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/smart-insight/SmartInsight.tsx
  client/web/src/views/components/StaticView.tsx
  client/web/src/views/components/view/View.tsx
  package.json
  yarn.lock
Labels: team/code-insights, cla-signed

#28542 Add additional warning around allowSignup setting
  doc/admin/auth/index.md
Labels: cla-signed

#28544 Slight tweak to wording on allowSignup
  doc/admin/auth/index.md
Labels: cla-signed

#28396 Wildcard: Add `<Badge />` and `<ProductStatusBadge />`
  client/branded/src/global-styles/GlobalStylesStory/BadgeVariants/BadgeVariants.module.scss
  client/branded/src/global-styles/GlobalStylesStory/BadgeVariants/BadgeVariants.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/web/src/components/Badge.module.scss
  client/web/src/components/Badge.story.tsx
  client/web/src/components/Badge.tsx
  client/web/src/components/FeedbackBadge.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsPage.tsx
  client/web/src/extensions/extension/ExtensionStatusBadge.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/repo/docs/DocumentationNode.tsx
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  client/web/src/savedSearches/SavedSearchForm.tsx
  client/web/src/search/input/SearchContextCtaPrompt.tsx
  client/web/src/user/settings/UserSettingsSidebar.tsx
  client/web/src/user/settings/repositories/SettingsRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/wildcard/src/components/Badge/Badge.module.scss
  client/wildcard/src/components/Badge/Badge.story.tsx
  client/wildcard/src/components/Badge/Badge.tsx
  client/wildcard/src/components/Badge/ProductStatusBadge.module.scss
  client/wildcard/src/components/Badge/ProductStatusBadge.story.tsx
  client/wildcard/src/components/Badge/ProductStatusBadge.tsx
  client/wildcard/src/components/Badge/constants.ts
  client/wildcard/src/components/Badge/index.ts
  client/wildcard/src/components/index.ts
Labels: team/frontend-platform, cla-signed

#28539 searcher: listen for OS signals
  cmd/searcher/main.go
Labels: cla-signed

#28529 database: more comprehensive tests of `Repos.ListMinimalRepos` with namespace
  internal/database/repos_db_test.go
Labels: cla-signed

#28439 Insights/capture groups/migration
  enterprise/internal/insights/resolvers/dynamic_insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
  enterprise/internal/insights/store/testdata/TestCreateSeries/test_create_and_get_capture_groups_series.golden
  enterprise/internal/insights/types/types.go
  migrations/codeinsights/1000000023_generate_from_query.down.sql
  migrations/codeinsights/1000000023_generate_from_query.up.sql
Labels: cla-signed

#28548 database: Move spec + definitions into migrations package
  enterprise/internal/insights/dbtesting/insights.go
  internal/database/dbconn/connect.go
  internal/database/dbconn/migration.go
  internal/database/dbconn/new.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
  internal/database/migrations/schema.go
  migrations/migrations_test.go
Labels: decouple-migrations, cla-signed

#28551 schemadoc: Move to ./dev
  dev/schemadoc/CODENOTIFY
  dev/schemadoc/main.go
  internal/database/gen.go
Labels: cla-signed

#28553 gitserver: Update comment about DB init
  cmd/gitserver/main.go
Labels: team/repo-management, cla-signed

#28550 sg: Remove go.mod
  dev/sg/go.mod
  dev/sg/go.sum
  go.mod
  go.sum
Labels: decouple-migrations, cla-signed

#28561 remove uses of the new dbpool in dbtest
  internal/database/orgs_test.go
Labels: cla-signed

#28555 Added warning for WSL use
  doc/batch_changes/references/troubleshooting.md
Labels: cla-signed

#28566 Update default directory display flag in docs
  doc/code_insights/explanations/viewing_code_insights.md
Labels: cla-signed

#28560 Code Monitors: Return created QueryTrigger from CreateQueryTrigger
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/mock_store_test.go
  enterprise/internal/codemonitors/queries.go
  enterprise/internal/codemonitors/store.go
  enterprise/internal/codemonitors/storetest/monitor_creator.go
Labels: cla-signed

#28270 Code Insights: [FE] Update insight card layout
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/utils/grid-layout-generator.ts
  client/web/src/integration/insights/drill-down-filters.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/insights-visual.test.ts
  client/web/src/views/components/view-grid/ViewGrid.tsx
  client/web/src/views/components/view/content/chart-view-content/ChartViewContent.story.module.scss
  client/web/src/views/components/view/content/chart-view-content/ChartViewContent.story.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/LineChart.module.scss
  client/web/src/views/components/view/content/chart-view-content/charts/line/LineChart.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/LineChartContent.module.scss
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/LineChartContent.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/TooltipContent.module.scss
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/TooltipContent.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/scroll-box/ScrollBox.module.scss
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/scroll-box/ScrollBox.story.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/scroll-box/ScrollBox.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/constants.ts
  client/web/src/views/components/view/content/chart-view-content/charts/line/index.ts
  client/web/src/views/components/view/content/chart-view-content/charts/line/line-chart-settings-provider.ts
  client/web/src/views/components/view/content/chart-view-content/charts/pie/PieChart.tsx
  client/web/src/views/index.ts
  client/web/src/views/mocks/charts-content.ts
Labels: cla-signed

#28558 Code Monitors: split scanRecipient out into separate function
  enterprise/internal/codemonitors/recipients.go
Labels: cla-signed

#28559 Code Monitors: create recipientColumns and use it in ListRecipients
  enterprise/internal/codemonitors/recipients.go
Labels: cla-signed

#28557 Code Monitors: return created recipient from CreateRecipients
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/mock_store_test.go
  enterprise/internal/codemonitors/recipients.go
  enterprise/internal/codemonitors/store.go
  enterprise/internal/codemonitors/storetest/monitor_creator.go
Labels: cla-signed

#28556 Code Monitors: return all fixtures from insertTestMonitor
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/queries_test.go
Labels: cla-signed

#28564 Code Monitors: use DB ID rather than RecordID
  enterprise/internal/codemonitors/action_jobs.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/mock_store_test.go
  enterprise/internal/codemonitors/store.go
Labels: cla-signed

#28563 Code Monitors: return enqueued jobs from EnqueueActionJobsForQuery
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/codemonitors/action_jobs.go
  enterprise/internal/codemonitors/action_jobs_test.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/mock_store_test.go
  enterprise/internal/codemonitors/store.go
Labels: cla-signed

#28562 Code Monitors: make ActionJob.TriggerEvent match the db integer type
  enterprise/internal/codemonitors/action_jobs.go
Labels: cla-signed

#28565 Code Monitors: replace hard-coded IDs with returned IDs
  enterprise/internal/codemonitors/action_jobs_test.go
  enterprise/internal/codemonitors/queries.go
  enterprise/internal/codemonitors/queries_test.go
  enterprise/internal/codemonitors/recipients_test.go
  enterprise/internal/codemonitors/trigger_jobs_test.go
Labels: cla-signed

#27931 security: harden which cross-origin headers are allowed
  cmd/frontend/internal/cli/http.go
Labels: security, apidocs, cla-signed

#28567 Create simpler namespace unmarshaler
  cmd/frontend/graphqlbackend/namespaces.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
Labels: cla-signed

#28569 Code Monitors: enqueue by monitor rather than by query
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/codemonitors/action_jobs.go
  enterprise/internal/codemonitors/action_jobs_test.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/mock_store_test.go
  enterprise/internal/codemonitors/store.go
Labels: cla-signed

#28576 pgsql-exporter: correct metric type
  docker-images/postgres_exporter/config/04_standard_migration.yaml
  docker-images/postgres_exporter/config/05_codeintel_migration.yaml
Labels: cla-signed

#28578 insights: fixed insight data series global only flag fetching the appropriate series
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/compression/compression.go
  enterprise/internal/insights/store/insight_store.go
Labels: cla-signed

#28596 chore: Rename internal/db/{migrations->migration/schemas}
  enterprise/internal/insights/dbtesting/insights.go
  internal/database/dbconn/connect.go
  internal/database/dbconn/migration.go
  internal/database/dbconn/new.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
  internal/database/migration/schemas/schema.go
  migrations/migrations_test.go
Labels: decouple-migrations, cla-signed

#28274 notebooks: file block
  client/web/src/integration/notebook.test.ts
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/search/notebook/SearchNotebook.story.tsx
  client/web/src/search/notebook/SearchNotebook.tsx
  client/web/src/search/notebook/SearchNotebookAddBlockButtons.tsx
  client/web/src/search/notebook/SearchNotebookBlockMenu.tsx
  client/web/src/search/notebook/SearchNotebookPage.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.module.scss
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.story.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.module.scss
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
  client/web/src/search/notebook/index.ts
Labels: cla-signed

#28338 notebook: file block
  client/web/src/integration/notebook.test.ts
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/search/notebook/SearchNotebook.story.tsx
  client/web/src/search/notebook/SearchNotebook.tsx
  client/web/src/search/notebook/SearchNotebookAddBlockButtons.tsx
  client/web/src/search/notebook/SearchNotebookBlockMenu.tsx
  client/web/src/search/notebook/SearchNotebookPage.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.module.scss
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.story.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.module.scss
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInputs.module.scss
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInputs.story.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInputs.tsx
  client/web/src/search/notebook/fileBlock/useFileBlockInputValidation.ts
  client/web/src/search/notebook/index.ts
Labels: cla-signed

#28463 notebooks: backend serializer
  enterprise/internal/notebooks/types.go
  enterprise/internal/notebooks/types_test.go
Labels: cla-signed

#28546 doc: Add note on watching and applying updates to extsvc config file
  doc/admin/config/advanced_config_file.md
Labels: docs, cla-signed

#28603 sg: capitize rfc statuses
  dev/sg/internal/rfc/rfc.go
Labels: sg, team/devx, cla-signed

#28601 search: do not fetch if rev is missing when indexing
  cmd/frontend/internal/httpapi/search.go
Labels: cla-signed

#28610 gomod: go get -u -t ./...
  dev/depgraph/go.mod
  dev/depgraph/go.sum
  enterprise/dev/insight-data-gen/go.mod
  enterprise/dev/insight-data-gen/go.sum
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestDocumentationPage.golden
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestDocumentationSearch_resultData.golden
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestWriteDocumentationUpload/query_the_page.golden
  enterprise/internal/insights/background/queryrunner/testdata/TestJobQueueDependencies/enqueue_with_dependencies.golden
  enterprise/internal/insights/background/testdata/TestDayOfMonthFrames/one_point_first_of_month_frames.golden
  enterprise/internal/insights/background/testdata/TestDayOfMonthFrames/six_points_first_of_month_frames.golden
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_multiple_frames_ensure_previous_frame_is_used_for_compression.golden
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_no_commits_two_frames.golden
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_one_frame.golden
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_three_frames_middle_has_no_commits.golden
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_three_frames_middle_has_no_commits_but_index_is_behind.golden
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_unable_to_fetch_metadata.golden
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToQueueJob/test_to_job_with_dependents.golden
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToRecording/test_to_recording_with_dependents.golden
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToRecording/test_to_recording_without_dependents.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/no_users_or_orgs_provided_should_only_return_global.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/org_5_can_see_the_view.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/user_1_can_see_this_view.golden
  enterprise/internal/insights/store/testdata/TestCreateSeries/test_create_and_get_capture_groups_series.golden
  enterprise/internal/insights/store/testdata/TestDeleteSnapshots.golden
  enterprise/internal/insights/store/testdata/TestDirtyQueriesAggregated/write_and_read_back.golden
  enterprise/internal/insights/store/testdata/TestGetDashboard/test_get_all.golden
  enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_3_can_see_both_dashboards.golden
  enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_3_can_see_both_dashboards_after_1.golden
  enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_3_can_see_both_dashboards_limit_1.golden
  go.mod
  go.sum
  internal/cmd/progress-bot/go.mod
  internal/cmd/progress-bot/go.sum
  lib/go.mod
  lib/go.sum
Labels: cla-signed

#28608 Add monitoring panels for cache hit rate and evictions
  doc/admin/observability/dashboards.md
  monitoring/definitions/frontend.go
Labels: cla-signed

#28598 migration: Add runner package
  internal/database/migration/runner/gen.go
  internal/database/migration/runner/iface.go
  internal/database/migration/runner/mock_iface_test.go
  internal/database/migration/runner/runner.go
  internal/database/migration/runner/runner_test.go
  internal/database/migration/runner/testdata/embed.go
  internal/database/migration/runner/testdata/query-error/10001_first.down.sql
  internal/database/migration/runner/testdata/query-error/10001_first.up.sql
  internal/database/migration/runner/testdata/well-formed/10001_first.down.sql
  internal/database/migration/runner/testdata/well-formed/10001_first.up.sql
  internal/database/migration/runner/testdata/well-formed/10002_second.down.sql
  internal/database/migration/runner/testdata/well-formed/10002_second.up.sql
  internal/database/migration/runner/testdata/well-formed/10003_third.down.sql
  internal/database/migration/runner/testdata/well-formed/10003_third.up.sql
  internal/database/migration/schemas/schema.go
  migrations/migrations.go
Labels: decouple-migrations, cla-signed

#28454 Allow applying batch spec if it finished excution, even with errors
  client/web/src/enterprise/batches/execution/BatchSpecExecutionDetailsPage.tsx
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_test.go
  enterprise/internal/batches/types/batch_spec.go
Labels: cla-signed

#28554 add GitserverReposStore to repo.Store
  internal/database/database.go
  internal/database/dbmock/db_mock.go
  internal/database/gitserver_repos.go
  internal/repos/store.go
Labels: cla-signed

#28619 chore: Add codenotify
  internal/database/migration/CODENOTIFY
Labels: cla-signed

#28618 migration: Share postgres dsn resolution code
  cmd/frontend/internal/cli/config.go
  internal/database/migration/schemas/dsn.go
  internal/database/migration/schemas/names.go
Labels: decouple-migrations, cla-signed

#28616 chore: Remove unknown path from codenotify
  internal/database/dbconn/CODENOTIFY
Labels: cla-signed

#28617 chore: Clean up definitions in migrations package
  migrations/embed.go
  migrations/migrations.go
  migrations/migrations_test.go
Labels: cla-signed

#28492 Insights/capture groups/create insight cg
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/query/query_executor.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
  enterprise/internal/insights/store/testdata/TestFindMatchingSeries/match_capture_group_series.golden
Labels: cla-signed

#28568 Rename sidebarToggle in settings.schema.json
  client/web/src/repo/RepoRevisionSidebar.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#28572 security: remove our CSRF tokens to improve security and reduce complexity of our threat model
  CHANGELOG.md
  client/web/README.md
  client/web/dev/server/development.server.ts
  client/web/dev/server/production.server.ts
  client/web/dev/utils/create-js-context.ts
  client/web/dev/utils/csrf/get-csrf-token-and-cookie.ts
  client/web/dev/utils/csrf/get-csrf-token-cookie-middleware.ts
  client/web/dev/utils/csrf/index.ts
  client/web/dev/utils/get-api-proxy-settings.ts
  client/web/dev/utils/index.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/handlerutil/middleware.go
  doc/dev/security/csrf_security_model.md
  internal/gqltestutil/client.go
Labels: security, apidocs, cla-signed

#28634 Add Jennifer and Daniel to team/devops label notification
  .github/workflows/label-notify.yml
Labels: cla-signed

#28632 chore: Collapse lib/postgresdsn and internal/db/migration/schema
  cmd/frontend/internal/cli/config.go
  cmd/server/shared/shared.go
  dev/sg/internal/migration/migration.go
  dev/sg/sg_setup.go
  enterprise/internal/insights/dbtesting/insights.go
  internal/database/postgresdsn/CODENOTIFY
  internal/database/postgresdsn/postgresdsn.go
  internal/database/postgresdsn/postgresdsn_test.go
  internal/database/postgresdsn/schema.go
Labels: cla-signed

#28501 codeintel: Optionally accept uploads for unresolvable commits
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_state.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/worker/internal/codeintel/janitor/iface.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/unknown_commits.go
  enterprise/cmd/worker/internal/codeintel/janitor/unknown_commits_test.go
  enterprise/cmd/worker/internal/codeintel/janitor_config.go
  enterprise/cmd/worker/internal/codeintel/janitor_job.go
  enterprise/internal/codeintel/stores/dbstore/janitor.go
  enterprise/internal/codeintel/stores/dbstore/janitor_test.go
Labels: team/code-intelligence, cla-signed

#28624 migrations: Make repo.stars not nullable
  internal/database/schema.md
  migrations/frontend/1528395949_repo_stars_null_to_zero.down.sql
  migrations/frontend/1528395949_repo_stars_null_to_zero.up.sql
  migrations/frontend/1528395950_repo_stars_call_nulls_to_zero.down.sql
  migrations/frontend/1528395950_repo_stars_call_nulls_to_zero.up.sql
  migrations/frontend/1528395951_repo_stars_not_null.down.sql
  migrations/frontend/1528395951_repo_stars_not_null.up.sql
Labels: cla-signed

#28635 doc: Add reference page for code intelligence envarrs
  doc/code_intelligence/index.md
  doc/code_intelligence/references/envvars.md
  doc/code_intelligence/references/index.md
Labels: team/code-intelligence, cla-signed

#28636 dbconn: Use correct prefix for frontend db
  internal/database/postgresdsn/postgresdsn.go
Labels: cla-signed

#28639 Prepare patch release
  dev/release/release-config.jsonc
Labels: cla-signed

#28642 database: Split schemas code into files
  internal/database/migration/schemas/schema.go
  internal/database/migration/schemas/schemas.go
Labels: decouple-migrations, cla-signed

#28648 database: Add NewDefaultRunner
  internal/database/migration/runner/iface.go
  internal/database/migration/runner/runner.go
Labels: decouple-migrations, cla-signed

#28649 database: Add common cli flags for migration utilities
  internal/database/migration/cliutil/flags.go
Labels: decouple-migrations, cla-signed

#28644 Update changelog for 3.34.2 release
  CHANGELOG.md
Labels: cla-signed

#28656 release: sourcegraph@3.34.2
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/install/docker-compose/aws.md
  doc/admin/install/docker-compose/digitalocean.md
  doc/admin/install/docker-compose/google_cloud.md
  doc/admin/install/docker-compose/operations.md
  doc/admin/install/docker/aws.md
  doc/admin/install/docker/digitalocean.md
  doc/admin/install/docker/google_cloud.md
  doc/admin/install/docker/index.md
  doc/admin/install/docker/operations.md
  doc/admin/install/kubernetes/configure.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/dev/how-to/testing.md
  doc/index.md
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#28625 Insights: formalize insight series types
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/migration/discovery.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/resolvers/insight_view_resolvers_test.go
  enterprise/internal/insights/service/service.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/no_users_or_orgs_provided_should_only_return_global.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/org_5_can_see_the_view.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/user_1_can_see_this_view.golden
  enterprise/internal/insights/store/testdata/TestCreateSeries/test_create_and_get_capture_groups_series.golden
  enterprise/internal/insights/store/testdata/TestFindMatchingSeries/find_a_matching_series_when_one_exists.golden
  enterprise/internal/insights/store/testdata/TestFindMatchingSeries/match_capture_group_series.golden
  enterprise/internal/insights/types/types.go
  migrations/codeinsights/1000000024_insight_series_expanded_type_info.down.sql
  migrations/codeinsights/1000000024_insight_series_expanded_type_info.up.sql
Labels: cla-signed

#28657 Prepare release tooling for 3.35.0 release
  dev/release/release-config.jsonc
Labels: cla-signed

#28659 migration: Move connection creation functions into a new package
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  cmd/worker/workerdb/db.go
  dev/schemadoc/main.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/internal/insights/dbtesting/insights.go
  enterprise/internal/insights/insights.go
  internal/database/connections/new.go
  internal/database/connections/runner.go
  internal/database/dbconn/connect.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtest/dbtest_fast.go
  internal/database/dbtest/pool.go
  internal/database/migration/runner/runner.go
Labels: decouple-migrations, cla-signed

#28526 remove id from insights
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/built-in-insight/BuiltInInsight.tsx
  client/web/src/views/components/StaticView.tsx
  client/web/src/views/components/view/View.story.tsx
  client/web/src/views/components/view/content/ViewContent.tsx
  client/web/src/views/components/view/content/description/ViewDescription.module.scss
  client/web/src/views/components/view/content/description/ViewDescription.tsx
Labels: cla-signed

#28662 codeintel: Fix line highlighting
  client/web/src/repo/blob/Blob.tsx
Labels: cla-signed

#28535 notebooks: add db store and get/create functions
  enterprise/internal/notebooks/store.go
  enterprise/internal/notebooks/store_test.go
  enterprise/internal/notebooks/types.go
  enterprise/internal/notebooks/validate.go
  enterprise/internal/notebooks/validate_test.go
  internal/database/schema.md
  migrations/frontend/1528395949_notebooks.down.sql
  migrations/frontend/1528395949_notebooks.up.sql
Labels: cla-signed

#28663 Revert "notebooks: add db store and get/create functions"
  enterprise/internal/notebooks/store.go
  enterprise/internal/notebooks/store_test.go
  enterprise/internal/notebooks/types.go
  enterprise/internal/notebooks/validate.go
  enterprise/internal/notebooks/validate_test.go
  internal/database/schema.md
  migrations/frontend/1528395949_notebooks.down.sql
  migrations/frontend/1528395949_notebooks.up.sql
Labels: cla-signed

#28664 notebooks: db store (attempt 2)
  enterprise/internal/notebooks/store.go
  enterprise/internal/notebooks/store_test.go
  enterprise/internal/notebooks/types.go
  enterprise/internal/notebooks/validate.go
  enterprise/internal/notebooks/validate_test.go
  internal/database/schema.md
  migrations/frontend/1528395952_notebooks.down.sql
  migrations/frontend/1528395952_notebooks.up.sql
Labels: cla-signed

#28549 sg: fix retry check not returning soon enough
  dev/sg/sg_setup.go
Labels: bug, sg, team/devx, cla-signed

#28667 Skip two tests that only fail locally
  cmd/frontend/graphqlbackend/search_results_test.go
Labels: cla-signed

#28547 Source environment before running any command
  dev/sg/sg_setup.go
Labels: dx, sg, dx-announce, team/devx, cla-signed

#27664 Global state: Add eslint import ban to avoid creating future detached `zustand` stores
  client/web/.eslintrc.js
Labels: team/frontend-platform, cla-signed

#28670 Fix broken link in quickstart
  README.md
Labels: cla-signed

#28604 Code Insights: [FE] Fix grid layout for small layout screen sizes
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/built-in-insight/BuiltInInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/smart-insight/SmartInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/utils/grid-layout-generator.ts
  client/web/src/views/components/view-grid/ViewGrid.tsx
  client/web/src/views/components/view/content/ViewContent.tsx
  client/web/src/views/components/view/index.ts
  client/web/src/views/mocks/charts-content.ts
Labels: team/code-insights, cla-signed

#28676 Move two resolver tests to different sub test
  enterprise/cmd/frontend/internal/batches/resolvers/permissions_test.go
Labels: cla-signed

#28106 Pidoxy/move navbar from wildcard/components folder to client/web/src/nav
  client/web/src/batches/BatchChangesNavItem.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/NavBar/NavAction.module.scss
  client/web/src/nav/NavBar/NavBar.module.scss
  client/web/src/nav/NavBar/NavBar.tsx
  client/web/src/nav/NavBar/NavDropdown.module.scss
  client/web/src/nav/NavBar/NavDropdown.tsx
  client/web/src/nav/NavBar/NavItem.module.scss
  client/web/src/nav/NavBar/index.tsx
  client/web/src/nav/index.ts
  client/wildcard/src/components/index.ts
Labels: cla-signed

#28351 Improve Percy Test Coverage
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/integration/code-monitoring.test.ts
  client/web/src/integration/search.test.ts
  client/web/src/savedSearches/SavedSearchForm.tsx
  client/web/src/savedSearches/SavedSearchListPage.tsx
Labels: gitstart, cla-signed

#28355 Improve Percy Test Coverage
  client/web/src/enterprise/insights/pages/insights/creation/intro/IntroCreationPage.tsx
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/org.test.ts
Labels: gitstart, cla-signed
