Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-04, with the labels that each got.

#19590 Remove unused name property on BitbucketserverWebhook
  enterprise/internal/batches/frontend.go
  enterprise/internal/batches/state/state_test.go
  enterprise/internal/batches/webhooks/webhooks.go
  enterprise/internal/batches/webhooks/webhooks_test.go
Labels: team/batchers

#19643 sg: allow running enterprise env with `sg`, flesh out TODO/Inspiration/Quickstart/Hacking in README
  dev/sg/README.md
  sg.config.yaml
Labels: sg

#19613 Add MountedKey encryption.Key implementation
  go.mod
  go.sum
  internal/encryption/keyring/ring.go
  internal/encryption/mounted/key.go
  internal/encryption/mounted/key_test.go
  schema/schema.go
  schema/site.schema.json
Labels: security, team/core-application

#19615 Faster user repos listing
  enterprise/internal/batches/testing/repos.go
  internal/database/repos.go
  internal/database/repos_perm_test.go
  internal/database/schema.md
  internal/repos/status_messages_test.go
  internal/repos/store.go
  migrations/frontend/1528395807_add_user_id_column_to_external_service_repos.down.sql
  migrations/frontend/1528395807_add_user_id_column_to_external_service_repos.up.sql
Labels: team/core-application

#18344 RFC 311: Add site-admin UI page to view migrations
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexPage.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.story.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.tsx
  client/web/src/site-admin/SiteAdmin.scss
  client/web/src/site-admin/SiteAdminMigrationsPage.scss
  client/web/src/site-admin/SiteAdminMigrationsPage.story.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.test.ts
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/routes.tsx
  client/web/src/site-admin/sidebaritems.ts
Labels: RFC-311, code-intelligence-performance, team/code-intelligence

#19271 encryption: add oob migration for user external accounts
  cmd/frontend/internal/cli/serve_cmd.go
  internal/database/external_accounts.go
  internal/database/external_accounts_test.go
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
  internal/encryption/keyring/ring.go
  migrations/frontend/1528395807_external_account_migration.down.sql
  migrations/frontend/1528395807_external_account_migration.up.sql
Labels: team/core-application

#19661 Fix some links to example searches
  doc/code_search/tutorials/examples.md
Labels: docs

#19704 repos: Remove outdated comments and word wrap another
  internal/repos/store.go
  internal/repos/syncer.go
Labels: team/core-application

#19705 repo-updater: Clarify intention of syncer.upserts()
  internal/repos/syncer.go
Labels: team/core-application

#19690 perforce: sync changes into local branch
  CHANGELOG.md
  cmd/gitserver/server/vcs_syncer.go
Labels: team/core-application

#19649 Update Batch Changes developer docs for new team member
  doc/dev/background-information/batch_changes/campaigns_database_layout.dot
  doc/dev/background-information/batch_changes/campaigns_database_layout.svg
  doc/dev/background-information/batch_changes/index.md
Labels: docs

#19706 rename encryption.Key.ID() to Version() & return structured version data
  internal/database/external_accounts.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
  internal/encryption/cloudkms/cloud_kms.go
  internal/encryption/key.go
  internal/encryption/mounted/key.go
  internal/encryption/noop.go
  schema/schema.go
  schema/site.schema.json
Labels: team/core-application

#19692 doc: add command to get Perforce ticket value
  doc/admin/repo/perforce.md
Labels: team/core-application

#19694 monitoring: Alert on invalid indexes
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  docker-images/postgres_exporter/queries.yaml
  monitoring/definitions/postgres.go
Labels: code-intelligence-performance, team/code-intelligence

#19722 docs: Fix half-sentence in oob migration guide
  doc/dev/background-information/oobmigrations.md
Labels: team/code-intelligence

#19695 codeintel: Optimize out-of-band migration queries
  enterprise/internal/codeintel/stores/lsifstore/migration/migrator.go
  internal/database/schema.codeintel.md
  migrations/codeintel/1000000009_documents_schema_version_index.down.sql
  migrations/codeintel/1000000009_documents_schema_version_index.up.sql
  migrations/codeintel/1000000010_definitions_schema_version_index.down.sql
  migrations/codeintel/1000000010_definitions_schema_version_index.up.sql
  migrations/codeintel/1000000011_references_schema_version_index.down.sql
  migrations/codeintel/1000000011_references_schema_version_index.up.sql
  migrations/codeintel/1000000012_delete_missing_schema_versions.down.sql
  migrations/codeintel/1000000012_delete_missing_schema_versions.up.sql
Labels: code-intelligence-performance, team/code-intelligence

#19710 repo-updater: Include sync jobs in repo upater state page
  cmd/repo-updater/shared/main.go
  cmd/repo-updater/shared/state.html.tmpl
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/repos/scheduler.go
  internal/types/types.go
Labels: team/core-application

#19738 Enabling encryption: Handle external account decryption in PermsStore, add docs for reversing OOB migrations.
  doc/dev/background-information/oobmigrations.md
  enterprise/internal/database/perms_store.go
  internal/database/external_accounts.go
  internal/database/oob_migrate.go
Labels: team/core-application

#19716 gitserver: handle zero limit correctly
  CHANGELOG.md
  cmd/gitserver/server/server.go
Labels: team/core-application

#19751 perforce: support internal rate limiter
  internal/database/external_services.go
  internal/database/repos_db_test.go
  internal/extsvc/types.go
  schema/perforce.schema.json
  schema/schema.go
Labels: team/core-application

#19697 codeintel: Standardize bulk upload technique
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/packages.go
  enterprise/internal/codeintel/stores/dbstore/references.go
  enterprise/internal/codeintel/stores/lsifstore/data_write.go
  enterprise/internal/codeintel/stores/lsifstore/migration/diagnostics_count.go
  enterprise/internal/codeintel/stores/lsifstore/migration/locations_count.go
  enterprise/internal/codeintel/stores/lsifstore/migration/migrator.go
  internal/database/batch/batch.go
  internal/database/batch/batch_test.go
  internal/goroutine/parallel.go
  internal/goroutine/parallel_test.go
Labels: code-intelligence-performance, team/code-intelligence

#19798 Fix accidental reload on enter
  client/web/src/components/FilteredConnection.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: cloud/milestone-3, team/core-application

#19684 web: added theme-redesign toggles to Storybook and web-app
  .storybook/main.js
  .storybook/redesign-toggle-toolbar/preset.js
  .storybook/redesign-toggle-toolbar/register.js
  client/branded/src/global-styles/colors.scss
  client/shared/src/util/addRedesignVariants.tsx
  client/shared/src/util/useRedesignToggle.ts
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/components/Badge.tsx
  client/web/src/components/Breadcrumbs.tsx
  client/web/src/components/FeedbackBadge.tsx
  client/web/src/extensions/icons.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/nav/RedesignToggle/RedesignToggle.tsx
  client/web/src/nav/RedesignToggle/index.ts
  client/web/src/nav/UserNavItem.tsx
  package.json
  yarn.lock
Labels: redesign, team/frontend-platform, webapp

#19741 web: `Team Labeler` Github action
  .github/teams.yml
  .github/workflows/team-labeler.yml
Labels: team/frontend-platform

#19569 web: moved Storybook config into a new package
  .prettierignore
  .storybook/main.js
  .storybook/preview.js
  .storybook/redesign-toggle-toolbar/preset.js
  .storybook/redesign-toggle-toolbar/register.js
  .storybook/themes.js
  babel.config.js
  client/README.md
  client/storybook/.eslintignore
  client/storybook/.eslintrc.js
  client/storybook/README.md
  client/storybook/assets/img/wildcard-design-system.svg
  client/storybook/babel.config.js
  client/storybook/globals.d.ts
  client/storybook/jest.config.js
  client/storybook/package.json
  client/storybook/src/coverage.test.ts
  client/storybook/src/main.ts
  client/storybook/src/manager-head.html
  client/storybook/src/preview.ts
  client/storybook/src/redesign-toggle-toolbar/RedesignToggleStorybook.tsx
  client/storybook/src/redesign-toggle-toolbar/register.ts
  client/storybook/src/themes.ts
  client/storybook/tsconfig.json
  dev/foreach-ts-project.sh
  jest.config.js
  package.json
  tsconfig.all.json
  yarn.lock
Labels: team/frontend-platform

#19646 Rework EKS docs to use ekscli
  doc/admin/install/kubernetes/eks.md
Labels: docs, team/distribution

#19767 globalstatedb: Do not ignore non-nil error in func Get
  internal/database/globalstatedb/globalstatedb.go
Labels: team/core-application

#19647 Add story for branded Panel
  client/branded/src/components/panel/Panel.story.tsx
  client/branded/src/components/panel/Panel.tsx
Labels: team/frontend-platform

#19745 Add changelog and update note about sourcegraph/deploy-sourcegraph/pull/2298
  CHANGELOG.md
  doc/admin/updates/kubernetes.md
Labels: team/distribution

#19759 codeintel: Remove math.Max(X, 1000) from result chunk assignment
  enterprise/lib/codeintel/lsif/conversion/group.go
Labels: code-intelligence-performance, team/code-intelligence

#19718 perforce: force update the master branch after fetch
  CHANGELOG.md
  cmd/gitserver/server/server.go
  cmd/gitserver/server/vcs_syncer.go
Labels: team/core-application

#19731 postgres_exporter: Update build and queries
  cmd/server/Dockerfile
  dev/postgres_exporter.sh
  doc/admin/observability/dashboards.md
  docker-images/postgres_exporter/Dockerfile
  docker-images/postgres_exporter/build.sh
  docker-images/postgres_exporter/config/01_defaults.yaml
  docker-images/postgres_exporter/config/02_broken_indexes.yaml
  docker-images/postgres_exporter/config/03_migrations.yaml
  docker-images/postgres_exporter/config/04_size.yaml
  docker-images/postgres_exporter/config/05_bloat.yaml
  docker-images/postgres_exporter/queries.yaml
  monitoring/definitions/postgres.go
Labels: code-intelligence-performance, team/code-intelligence

#19805 Return count of repos that fail to clone or fetch
  internal/database/repos.go
  internal/database/repos_db_test.go
  internal/database/schema.md
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
  internal/types/types.go
  migrations/frontend/1528395811_add_gitserver_repos_last_error_idx.down.sql
  migrations/frontend/1528395811_add_gitserver_repos_last_error_idx.up.sql
Labels: team/core-application

#19824 web: Improve code host alert box styling
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: cloud/milestone-3, team/core-application

#19796 batches: add and parse window rollout schema
  enterprise/internal/batches/frontend.go
  enterprise/internal/batches/scheduler/window/config.go
  enterprise/internal/batches/scheduler/window/config_test.go
  enterprise/internal/batches/scheduler/window/rate.go
  enterprise/internal/batches/scheduler/window/rate_test.go
  enterprise/internal/batches/scheduler/window/schedule.go
  enterprise/internal/batches/scheduler/window/schedule_test.go
  enterprise/internal/batches/scheduler/window/time.go
  enterprise/internal/batches/scheduler/window/time_test.go
  enterprise/internal/batches/scheduler/window/weekday.go
  enterprise/internal/batches/scheduler/window/weekday_test.go
  enterprise/internal/batches/scheduler/window/window.go
  enterprise/internal/batches/scheduler/window/window_test.go
  go.mod
  go.sum
  schema/schema.go
  schema/site.schema.json
Labels: team/batchers

#19829 extsvc: delete unused ExtractBaseURL
  internal/extsvc/types.go
Labels: team/core-application

#19830 database: drop mgmt_password columns
  internal/database/globalstatedb/globalstatedb.go
  internal/database/schema.md
  migrations/frontend/1528395812_drop_global_state_mgmt_password_columns.down.sql
  migrations/frontend/1528395812_drop_global_state_mgmt_password_columns.up.sql
Labels: team/core-application

#19845 Refactor out sources logic into separate package
  enterprise/internal/batches/background/workers.go
  enterprise/internal/batches/reconciler/executor.go
  enterprise/internal/batches/reconciler/executor_test.go
  enterprise/internal/batches/reconciler/reconciler.go
  enterprise/internal/batches/reconciler/reconciler_test.go
  enterprise/internal/batches/reconciler/util.go
  enterprise/internal/batches/resolvers/changeset_counts_test.go
  enterprise/internal/batches/resolvers/main_test.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/sources/sources.go
  enterprise/internal/batches/sources/sources_test.go
  enterprise/internal/batches/store/codehost.go
  enterprise/internal/batches/store/codehost_test.go
  enterprise/internal/batches/syncer/syncer.go
  enterprise/internal/batches/syncer/syncer_test.go
  enterprise/internal/batches/syncer/util.go
  enterprise/internal/batches/syncer/util_test.go
  enterprise/internal/batches/testing/changeset_source.go
  enterprise/internal/batches/webhooks/webhooks_test.go
  internal/conf/computed.go
  internal/encryption/rsa.go
Labels: debt, team/batchers

#19602 Validate authenticators when storing them
  CHANGELOG.md
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/service/mocks.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/syncer/syncer_test.go
  internal/repos/bitbucketserver.go
  internal/repos/github.go
  internal/repos/gitlab.go
  internal/repos/sources.go
Labels: team/batchers

#19855 Fix permissions alert not visible when no open changesets in batch change
  client/web/src/enterprise/batches/close/BatchChangeCloseAlert.tsx
Labels: bug, team/batchers

#19869 db: Add cascading delete on gitserver_repos
  internal/database/schema.md
  migrations/frontend/1528395813_gitserver_repos_add_cascade_delete.down.sql
  migrations/frontend/1528395813_gitserver_repos_add_cascade_delete.up.sql
Labels: team/core-application

#19872 fix bug with gitolite config redaction that caused the config to return empty from the API
  internal/types/secret.go
  internal/types/secret_test.go
Labels: team/core-application

#19556 Replace recharts library with visx for code insights
  client/shared/src/components/Markdown.tsx
  client/shared/src/util/link-click-handler/linkClickHandler.test.tsx
  client/shared/src/util/link-click-handler/linkClickHandler.ts
  client/web/src/repo/tree/ViewGrid.scss
  client/web/src/repo/tree/ViewGrid.tsx
  client/web/src/views/ChartViewContent.scss
  client/web/src/views/ChartViewContent.tsx
  client/web/src/views/ChartViewContent/ChartViewContent.scss
  client/web/src/views/ChartViewContent/ChartViewContent.story.tsx
  client/web/src/views/ChartViewContent/ChartViewContent.tsx
  client/web/src/views/ChartViewContent/annotation/Label.tsx
  client/web/src/views/ChartViewContent/charts/bar/BarChart.scss
  client/web/src/views/ChartViewContent/charts/bar/BarChart.tsx
  client/web/src/views/ChartViewContent/charts/line/LineChart.scss
  client/web/src/views/ChartViewContent/charts/line/LineChart.tsx
  client/web/src/views/ChartViewContent/charts/line/colors.ts
  client/web/src/views/ChartViewContent/charts/line/components/GlyphDot.tsx
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
  client/web/src/views/ChartViewContent/charts/line/components/MaybeLink.tsx
  client/web/src/views/ChartViewContent/charts/line/components/TooltipContent.tsx
  client/web/src/views/ChartViewContent/charts/line/helpers/generate-accessors.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/get-min-max.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/get-range-with-padding.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/use-scales.ts
  client/web/src/views/ChartViewContent/charts/line/types.ts
  client/web/src/views/ChartViewContent/charts/pie/PieChart.scss
  client/web/src/views/ChartViewContent/charts/pie/PieChart.tsx
  client/web/src/views/ChartViewContent/charts/pie/components/PieArc.tsx
  client/web/src/views/ChartViewContent/charts/pie/distribute-pie-data.ts
  client/web/src/views/ChartViewContent/charts/types.ts
  client/web/src/views/ViewContent.scss
  client/web/src/views/ViewContent.tsx
  package.json
  yarn.lock
Labels: team/code-insights, webapp

#19854 Post QA repository view fixes
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: cloud/milestone-3, team/core-application

#19879 db: Set constraints as deferred in migration
  migrations/frontend/1528395813_gitserver_repos_add_cascade_delete.down.sql
  migrations/frontend/1528395813_gitserver_repos_add_cascade_delete.up.sql
Labels: team/core-application

#19875 web: Ensure alert links are always underlined
  client/branded/src/global-styles/alert.scss
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: team/core-application

#19807 There is more to ratelimits than meets the eye
  schema/bitbucket_cloud.schema.json
  schema/bitbucket_server.schema.json
  schema/github.schema.json
  schema/gitlab.schema.json
  schema/perforce.schema.json
  schema/schema.go
Labels: team/core-application

#19914 gitserver: Log error from doBackgroundRepoUpdate
  cmd/gitserver/server/server.go
Labels: team/core-application

#19920 frontend: Show error when user added repos exceed limit
  cmd/frontend/graphqlbackend/set_external_service_repos.go
  internal/conf/computed.go
  internal/repos/conf.go
  internal/repos/syncer.go
Labels: team/core-application

#19923 Add WEBPACK_DEV_SERVER to frontend procs in sg.config.yaml
  sg.config.yaml
Labels: sg

#19922 frontend: Order user repos by name
  cmd/frontend/graphqlbackend/user.go
Labels: team/core-application

#19944 codeintel: Auto index Go deps of sg/sg on Cloud
  enterprise/cmd/frontend/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/cmd/frontend/internal/codeintel/autoindex/enqueuer/sggodeps.go
Labels: team/code-intelligence

#19946 codeintel: Add ensureUnambiguousResultSets to lsif-validate
  enterprise/lib/codeintel/lsif/test/README.md
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validators.go
  enterprise/lib/codeintel/lsif/test/cmd/lsif-validate/internal/validation/validators_relationship.go
Labels: team/code-intelligence

#19827 codeintel: Refactor data migrator
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/migrations.go
  enterprise/internal/codeintel/stores/lsifstore/migration/diagnostics_count.go
  enterprise/internal/codeintel/stores/lsifstore/migration/document_column_split.go
  enterprise/internal/codeintel/stores/lsifstore/migration/locations_count.go
  enterprise/internal/codeintel/stores/lsifstore/migration/migrator.go
  enterprise/internal/codeintel/stores/lsifstore/migration/migrator_test.go
  internal/database/schema.codeintel.md
  internal/oobmigration/runner.go
  migrations/codeintel/1000000014_schema_version_index.down.sql
  migrations/codeintel/1000000014_schema_version_index.up.sql
Labels: code-intelligence-performance, team/code-intelligence

#19952 web: fix `yarn outdated`
  package.json
  yarn.lock
Labels: team/frontend-platform

#19960 Support a service account file on cloudkms encryption key
  internal/encryption/cloudkms/cloud_kms.go
  internal/encryption/keyring/ring.go
  schema/schema.go
  schema/site.schema.json
Labels: team/core-application

#19966 web: bump @sourcegraph/eslint-config version
  .eslintrc.js
  package.json
  yarn.lock
Labels: team/frontend-platform

#19965 Consistently check public code permissions
  client/web/src/user/settings/cloud-ga.ts
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/internal/search/repos/external_services.go
  cmd/frontend/internal/search/repos/repo_groups.go
  internal/conf/computed.go
  internal/database/users.go
  internal/database/users_mock.go
  internal/repos/syncer.go
Labels: team/core-application

#19977 db: Add cascading delete on external_service_sync_jobs
  internal/database/schema.md
  migrations/frontend/1528395814_add_cascase_delete_on_external_service_sync_jobs.down.sql
  migrations/frontend/1528395814_add_cascase_delete_on_external_service_sync_jobs.up.sql
Labels: team/core-application

#19976 types: fix redact Gitolite and Other that have no secret fields
  CHANGELOG.md
  internal/types/secret.go
Labels: team/core-application

#19981 doc: add notes about Perforce depot syncing
  doc/admin/repo/perforce.md
Labels: team/core-application

#19985 Unsubscribe from submit subscription on component unmount
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: cloud/milestone-3, team/core-application

#20001 docs: Update when internal rate limits are applied
  doc/admin/external_service/bitbucket_cloud.md
  doc/admin/external_service/bitbucket_server.md
  doc/admin/external_service/github.md
  doc/admin/external_service/gitlab.md
Labels: team/core-application

#19600 Add Code Insights independent MVP
  client/README.md
  client/sandboxes/code-insights/.eslintrc.js
  client/sandboxes/code-insights/.stylelintrc.json
  client/sandboxes/code-insights/babel.config.js
  client/sandboxes/code-insights/package.json
  client/sandboxes/code-insights/src/demo.tsx
  client/sandboxes/code-insights/src/index.html
  client/sandboxes/code-insights/src/mock-api.ts
  client/sandboxes/code-insights/tsconfig.json
  client/sandboxes/code-insights/webpack.config.js
  client/web/src/SourcegraphWebApp.scss
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/insights/backend.ts
  client/web/src/insights/components/Icons.tsx
  client/web/src/insights/components/InsightsNavLink/InsightsNavLink.tsx
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.scss
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
  client/web/src/insights/components/index.ts
  client/web/src/insights/core/analytics.test.ts
  client/web/src/insights/core/analytics.ts
  client/web/src/insights/core/backend/api-provider.ts
  client/web/src/insights/core/backend/insights-api.ts
  client/web/src/insights/core/backend/requests/fetch-backend-insights.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/core/backend/utils/create-view-content.ts
  client/web/src/insights/index.ts
  client/web/src/insights/pages/InsightsPage.scss
  client/web/src/insights/pages/InsightsPage.tsx
  client/web/src/nav/MenuNavItem.story.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/repo/tree/TreePage.scss
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/routes.tsx
  client/web/src/search/input/SearchPage.tsx
  client/web/src/views/ViewContent.tsx
  package.json
  yarn.lock
Labels: debt, team/code-insights, webapp

#19919 web: add CSS-modules support
  .gitignore
  client/branded/src/components/BrandedStory.tsx
  client/browser/config/webpack/base.config.ts
  client/shared/dev/generateCssModulesTypes.js
  client/shared/gulpfile.js
  client/storybook/src/main.ts
  client/web/src/SourcegraphWebApp.scss
  client/web/webpack.config.js
  client/wildcard/src/components/PageSelector/PageSelector.module.scss
  client/wildcard/src/components/PageSelector/PageSelector.scss
  client/wildcard/src/components/PageSelector/PageSelector.story.tsx
  client/wildcard/src/components/PageSelector/PageSelector.tsx
  client/wildcard/src/index.scss
  doc/dev/background-information/web/styling.md
  doc/dev/background-information/web/wildcard.md
  gulpfile.js
  package.json
  yarn.lock
Labels: ops & tools & dev, team/frontend-platform

#19999 Fix `sg run-set enterprise` not starting on Linux
  sg.config.yaml
Labels: sg

#20003 web: Log user events related to adding public code
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/core-application

#19479 Apply content-hashing to app.bundle.js and app.bundle.css filenames
  .gitignore
  client/browser/package.json
  client/web/package.json
  client/web/src/integration/context.ts
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/app.html
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/router.go
  dev/ci/yarn-build.sh
  enterprise/dev/ci/internal/ci/pipeline.go
  package.json
  ui/assets/load_manifest_dev.go
  ui/assets/load_manifest_dist.go
  ui/assets/manifest.go
  yarn.lock
Labels: team/frontend-platform

#19926 Design Refresh - Update color tokens
  client/branded/src/global-styles/code.scss
  client/branded/src/global-styles/colors-redesign.scss
  client/branded/src/global-styles/colors.scss
  client/branded/src/global-styles/dropdown.scss
  client/branded/src/global-styles/forms.scss
  client/branded/src/global-styles/index.scss
  client/browser/src/app.scss
Labels: design refresh, team/frontend-platform

#20024 frontend: Quick fix to log gitlab oauth errors in Sentry
  enterprise/cmd/frontend/internal/auth/gitlaboauth/login.go
Labels: team/core-application

#19864 Custom away prompt
  client/web/src/user/settings/repositories/AwayPrompt.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: blocker, cloud/milestone-3, team/core-application

#20029 web: Enable status messages when public code enabled
  client/web/src/nav/NavLinks.tsx
Labels: team/core-application

#20043 Implement source methods for `CreateComment`
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/bitbucketserver_test.go
  enterprise/internal/batches/sources/common.go
  enterprise/internal/batches/sources/fake.go
  enterprise/internal/batches/sources/github.go
  enterprise/internal/batches/sources/github_test.go
  enterprise/internal/batches/sources/gitlab.go
  enterprise/internal/batches/sources/gitlab_test.go
  enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateComment_success.yaml
  enterprise/internal/batches/sources/testdata/sources/GithubSource_CreateComment_success.yaml
  enterprise/internal/batches/sources/testdata/sources/GitlabSource_CreateComment_success.yaml
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
  internal/extsvc/bitbucketserver/testdata/vcr/CreatePullRequestComment-success.yaml
  internal/extsvc/github/pulls.go
  internal/extsvc/github/testdata/vcr/CreatePullRequestComment.yaml
  internal/extsvc/github/v4_test.go
  internal/extsvc/gitlab/merge_requests.go
  internal/extsvc/gitlab/merge_requests_test.go
  internal/extsvc/gitlab/mock.go
Labels: team/batchers

#20026 Update batch changes development docs to include sources
  doc/dev/background-information/batch_changes/index.md
Labels: team/batchers

#20051 Update desigh refresh colors
  client/branded/src/global-styles/colors-redesign.scss
Labels: design refresh, team/frontend-platform

#20050 user_external_accounts: Encrypt account data along with auth data, and handle null values correctly. also update the oob migration runner to use the db handle passed to it
  enterprise/internal/database/perms_store.go
  internal/database/external_accounts.go
  internal/database/oob_migrate.go
  internal/oobmigration/runner.go
Labels: team/core-application

#20021 gitserver: generate clone url from external service config
  cmd/gitserver/main.go
  internal/types/clone_url.go
  internal/types/clone_url_test.go
Labels: team/core-application

#20052 web: Log when a user clicks on 'Manage Repositories'
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: team/core-application

#20057 init keyring on gitserver, take lock when creating ring
  cmd/gitserver/main.go
  internal/encryption/keyring/ring.go
Labels: team/core-application

#20062 Use rsa mock in ssh migrator tests to speed up test suite
  enterprise/internal/batches/background/ssh_migrator_test.go
  enterprise/internal/batches/resolvers/main_test.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/testing/rsa.go
Labels: team/batchers

#19797 batches: add scheduler service
  client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetInfoCell.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/batches/background/background.go
  enterprise/internal/batches/frontend.go
  enterprise/internal/batches/global/global.go
  enterprise/internal/batches/global/global_test.go
  enterprise/internal/batches/resolvers/changeset.go
  enterprise/internal/batches/resolvers/changesets_stats.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/rewirer/rewirer.go
  enterprise/internal/batches/rewirer/rewirer_test.go
  enterprise/internal/batches/scheduler/scheduler.go
  enterprise/internal/batches/scheduler/ticker.go
  enterprise/internal/batches/scheduler/ticker_test.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/store/changeset_specs_test.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/batches/store/changesets_test.go
  enterprise/internal/batches/store/integration_test.go
  enterprise/internal/batches/testing/config.go
  enterprise/internal/batches/types/changeset.go
  enterprise/internal/batches/types/changeset_test.go
  enterprise/internal/batches/types/scheduler/config/config.go
  enterprise/internal/batches/types/scheduler/config/config_test.go
  enterprise/internal/batches/types/scheduler/window/config.go
  enterprise/internal/batches/types/scheduler/window/config_test.go
  enterprise/internal/batches/types/scheduler/window/rate.go
  enterprise/internal/batches/types/scheduler/window/rate_test.go
  enterprise/internal/batches/types/scheduler/window/schedule.go
  enterprise/internal/batches/types/scheduler/window/schedule_test.go
  enterprise/internal/batches/types/scheduler/window/time.go
  enterprise/internal/batches/types/scheduler/window/time_test.go
  enterprise/internal/batches/types/scheduler/window/weekday.go
  enterprise/internal/batches/types/scheduler/window/weekday_test.go
  enterprise/internal/batches/types/scheduler/window/window.go
  enterprise/internal/batches/types/scheduler/window/window_test.go
Labels: team/batchers

#20079 web: Add /devtooltime redirect
  cmd/frontend/internal/app/ui/help.go
  cmd/frontend/internal/app/ui/router.go
Labels: team/core-application

#20081 generate clone url from extsvc config with safe type assertions
  cmd/gitserver/main.go
  internal/types/clone_url.go
  internal/types/clone_url_test.go
Labels: team/core-application

#20065 fix background code color variable
  client/branded/src/global-styles/colors-redesign.scss
  client/branded/src/global-styles/colors.scss
Labels: merge-on-any-approve, team/frontend-platform

#20090 monitoring: Fix external service dashboards
  monitoring/definitions/repo_updater.go
Labels: team/core-application

#19553 Side by Side diff
  client/web/src/components/diff/DiffBoundary.tsx
  client/web/src/components/diff/DiffHunk.test.tsx
  client/web/src/components/diff/DiffHunk.tsx
  client/web/src/components/diff/DiffSplitHunk.test.tsx
  client/web/src/components/diff/DiffSplitHunk.tsx
  client/web/src/components/diff/FileDiffHunks.scss
  client/web/src/components/diff/FileDiffHunks.story.tsx
  client/web/src/components/diff/FileDiffHunks.tsx
  client/web/src/components/diff/FileDiffNode.story.tsx
  client/web/src/components/diff/FileDiffNode.tsx
  client/web/src/components/diff/Lines.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
  client/web/src/components/diff/addLineNumberToHunks.ts
  client/web/src/repo/commit/DiffModeSelector.tsx
  client/web/src/repo/commit/RepositoryCommitPage.scss
  client/web/src/repo/commit/RepositoryCommitPage.tsx
  client/web/src/repo/compare/dom-functions.ts
Labels: team/frontend-platform

#19648 Add further Percy visual regression tests that cover light, dark and redesign theme variants
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
  client/web/src/integration/batches.test.ts
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/code-monitoring.test.ts
  client/web/src/integration/extension-registry.test.ts
  client/web/src/integration/insights.test.ts
  client/web/src/integration/org.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/integration/search.test.ts
  client/web/src/integration/settings.test.ts
  client/web/src/integration/utils.ts
  package.json
  yarn.lock
Labels: team/frontend-platform

#20105 insights: expose job status info over GraphQL API
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/insights/background/queryrunner/worker.go
  enterprise/internal/insights/resolvers/insight_connection_resolver.go
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_series_resolver_test.go
  enterprise/internal/insights/resolvers/resolver.go
Labels: team/code-insights, team/internal-contributor

#20118 perforce: declare a type for metadata
  internal/extsvc/perforce/repos.go
  internal/repos/perforce.go
  internal/types/clone_url.go
  internal/types/clone_url_test.go
Labels: team/core-application

#20056 doc: Update comments regarding cloud_default
  cmd/frontend/internal/cli/config.go
  schema/github.schema.json
  schema/gitlab.schema.json
  schema/schema.go
Labels: team/core-application

#20089 enterprise: Enforce user and external service limits
  CHANGELOG.md
  enterprise/cmd/frontend/internal/licensing/enforcement/external_services.go
  enterprise/cmd/frontend/internal/licensing/enforcement/external_services_test.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users_test.go
  enterprise/cmd/frontend/internal/licensing/init/init.go
  enterprise/internal/batches/testing/user.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/users.go
Labels: team/core-application

#19708 Improve a11 of code insights charts
  client/branded/src/global-styles/colors.scss
  client/web/src/views/ChartViewContent/ChartViewContent.story.tsx
  client/web/src/views/ChartViewContent/ChartViewContent.tsx
  client/web/src/views/ChartViewContent/annotation/Label.tsx
  client/web/src/views/ChartViewContent/charts/MaybeLink.tsx
  client/web/src/views/ChartViewContent/charts/bar/BarChart.scss
  client/web/src/views/ChartViewContent/charts/bar/BarChart.tsx
  client/web/src/views/ChartViewContent/charts/line/LineChart.scss
  client/web/src/views/ChartViewContent/charts/line/LineChart.tsx
  client/web/src/views/ChartViewContent/charts/line/components/GlyphContent.tsx
  client/web/src/views/ChartViewContent/charts/line/components/GlyphDot.tsx
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
  client/web/src/views/ChartViewContent/charts/line/components/MaybeLink.tsx
  client/web/src/views/ChartViewContent/charts/line/components/TickComponent.tsx
  client/web/src/views/ChartViewContent/charts/line/components/TooltipContent.tsx
  client/web/src/views/ChartViewContent/charts/line/helpers/generate-accessors.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/get-min-max.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/use-event-emitters.ts
  client/web/src/views/ChartViewContent/charts/line/helpers/use-scales.ts
  client/web/src/views/ChartViewContent/charts/line/types.ts
  client/web/src/views/ChartViewContent/charts/pie/PieChart.scss
  client/web/src/views/ChartViewContent/charts/pie/PieChart.tsx
  client/web/src/views/ChartViewContent/charts/pie/components/PieArc.tsx
  client/web/src/views/ChartViewContent/charts/types.ts
  client/web/src/views/ChartViewContent/utils/get-insight-type-by-view-id.ts
  package.json
  yarn.lock
Labels: debt, team/code-insights, webapp

#20120 Fix chart label in Firefox for code insight pie chart
  client/web/src/views/ChartViewContent/annotation/Label.tsx
  client/web/src/views/ChartViewContent/annotation/Text.tsx
  client/web/src/views/ChartViewContent/charts/pie/components/PieArc.tsx
Labels: release-blocker, team/code-insights, webapp

#20111 Fix chart's tooltip position in Firefox.
  client/browser/src/browser-extension/scripts/optionsPage.main.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/platform/inlineExtensionsService.ts
  client/browser/src/shared/util/context.tsx
  client/shared/src/util/browserDetection.ts
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
Labels: bug, team/code-insights, webapp

#19868 Add sequential providers loading to code insights
  client/shared/src/api/extension/api/callViewProvidersInParallel.test.ts
  client/shared/src/api/extension/api/callViewProvidersInParallel.ts
  client/shared/src/api/extension/extensionHostApi.ts
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
Labels: team/code-insights, webapp

#20077 Support multiple GraphQL schema files
  .gitattributes
  .graphqlconfig
  .graphqlrc.yml
  .vscode/settings.json
  client/branded/tsconfig.json
  client/browser/src/end-to-end/tsconfig.json
  client/browser/tsconfig.json
  client/sandboxes/code-insights/tsconfig.json
  client/shared/dev/generateGraphQlOperations.js
  client/shared/gulpfile.js
  client/shared/src/testing/tsconfig.json
  client/shared/tsconfig.json
  client/web/src/end-to-end/tsconfig.json
  client/web/tsconfig.json
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  dev/watchmanwrapper/watch.json
  doc/dev/background-information/batch_changes/index.md
  enterprise/dev/ci/internal/ci/pipeline-steps.go
  graphql-schema-linter.config.js
  package.json
  yarn.lock
Labels: debt

#19939 extensions: log extension activation events from extension host
  client/shared/src/api/client/mainthread-api.ts
  client/shared/src/api/contract.ts
  client/shared/src/api/extension/activation.ts
  client/shared/src/api/extension/test/activation.test.ts
Labels: merge-on-all-approve

#20139 database: fix scanRepo not initialize metadata for Perforce
  internal/database/repos.go
  internal/types/clone_url.go
Labels: team/core-application

#20142 add side by side feature to changelog
  CHANGELOG.md
Labels: merge-on-any-approve, team/distribution

#20104 Update: Add Repo Updater State
  doc/admin/repo/update_frequency.md
Labels: docs

#20143 Update batch changes changelog for 3.27 release
  CHANGELOG.md
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Labels: team/batchers

#20148 codeintel: Improve logging around sg/sg dependency indexing
  enterprise/cmd/frontend/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/cmd/frontend/internal/codeintel/autoindex/enqueuer/sggodeps.go
Labels: team/code-intelligence

#20160 codeintel: Respect edge direction for referenceResult item edges
  enterprise/lib/codeintel/datastructures/default_idset_map.go
  enterprise/lib/codeintel/lsif/conversion/canonicalize.go
  enterprise/lib/codeintel/lsif/conversion/canonicalize_test.go
  enterprise/lib/codeintel/lsif/conversion/correlate.go
  enterprise/lib/codeintel/lsif/conversion/correlate_test.go
  enterprise/lib/codeintel/lsif/conversion/state.go
Labels: team/code-intelligence

#20165 codeintel: Improve logging around sg/sg dependency indexing
  enterprise/cmd/frontend/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/cmd/frontend/internal/codeintel/autoindex/enqueuer/sggodeps.go
Labels: team/code-intelligence

#20119 batches: Cleanup webhooks package
  enterprise/internal/batches/webhooks/bitbucketserver.go
  enterprise/internal/batches/webhooks/bitbucketserver_test.go
  enterprise/internal/batches/webhooks/github.go
  enterprise/internal/batches/webhooks/github_test.go
  enterprise/internal/batches/webhooks/gitlab.go
  enterprise/internal/batches/webhooks/gitlab_test.go
  enterprise/internal/batches/webhooks/main_test.go
  enterprise/internal/batches/webhooks/webhooks.go
  enterprise/internal/batches/webhooks/webhooks_test.go
Labels: debt, team/batchers

#20175 batches: add rollout window configuration docs
  doc/admin/config/batch_changes.md
  doc/admin/config/index.md
  doc/batch_changes/how-tos/site_admin_configuration.md
Labels: docs, team/batchers

#20103 Update Changelog to include a fix that was omitted (from the changelog) in 3.26.1
  CHANGELOG.md
Labels: merge-on-any-approve

#20206 Add user facing docs on configuring encryption
  doc/admin/config/encryption.md
  doc/admin/config/index.md
Labels: team/core-application

#20204 repo-updater: Scheduler backoff on update error
  CHANGELOG.md
  internal/repos/scheduler.go
Labels: team/core-application

#20063 Implement bulk processor background worker
  doc/admin/user_data_deletion.md
  enterprise/internal/batches/background/background.go
  enterprise/internal/batches/background/bulk_processor.go
  enterprise/internal/batches/background/bulk_processor_test.go
  enterprise/internal/batches/background/bulk_processor_worker.go
  enterprise/internal/batches/background/metrics.go
  enterprise/internal/batches/background/reconciler_worker.go
  enterprise/internal/batches/background/reconciler_worker_test.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/store/changeset_jobs_test.go
  enterprise/internal/batches/store/integration_test.go
  enterprise/internal/batches/testing/db.go
  enterprise/internal/batches/types/changeset_job.go
  internal/database/schema.md
  migrations/frontend/1528395816_changeset_bulk_jobs_table.down.sql
  migrations/frontend/1528395816_changeset_bulk_jobs_table.up.sql
Labels: team/batchers

#20159 add alert-link styles to anchor
  client/branded/src/global-styles/alert.scss
  client/branded/src/global-styles/global-styles.story.tsx
Labels: team/frontend-platform

#20211 Introduce `disableAutoCodeHostSyncs` site config setting
  CHANGELOG.md
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/internal/batches/resolvers/changeset.go
  enterprise/internal/batches/syncer/syncer.go
  internal/repos/syncer.go
  schema/schema.go
  schema/site.schema.json
Labels: team/core-application

#20144 Document site-credentials in Batch Changes
  doc/_resources/assets/redirects
  doc/batch_changes/explanations/permissions_in_batch_changes.md
  doc/batch_changes/how-tos/configuring_credentials.md
  doc/batch_changes/how-tos/creating_a_batch_change.md
  doc/batch_changes/how-tos/handling_errored_changesets.md
  doc/batch_changes/how-tos/index.md
  doc/batch_changes/how-tos/publishing_changesets.md
  doc/batch_changes/how-tos/site_admin_configuration.md
  doc/batch_changes/how-tos/updating_a_batch_change.md
  doc/batch_changes/index.md
  doc/batch_changes/quickstart.md
  doc/batch_changes/references/troubleshooting.md
Labels: team/batchers

#20210 Add env var to prevent down migrations decrypting tables, add encryption to CHANGELOG.md
  CHANGELOG.md
  cmd/frontend/internal/cli/serve_cmd.go
  doc/admin/config/encryption.md
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
Labels: team/core-application

#20208 Fix regexp patterns in site schema to also work in JavaScript regexp
  schema/site.schema.json
Labels: team/batchers

#20194 gitserver: respect DisableAutoGitUpdates
  CHANGELOG.md
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/server.go
Labels: team/core-application

#20218 batches: take two at explaining rollout window behaviour
  doc/admin/config/batch_changes.md
Labels: docs, team/batchers

#19978 Add Testing a pull request
  doc/dev/background-information/sourcegraph_extensions.md
  doc/dev/background-information/testing_pr.md
  doc/extensions/authoring/testing_extensions.md
Labels: docs, team/extensibility

#20169 Don't use `he` to decode response
  client/web/src/components/SearchResult.tsx
  package.json
  yarn.lock
Labels: debt

#20150 Don't require a batch changes resolver in OSS build
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/codehost_repository_connection.go
  cmd/frontend/graphqlbackend/empty_response.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/search_test.go
  enterprise/internal/batches/resolvers/resolver.go
Labels: debt, team/batchers

#20215 Refactor codeintel resolver to new format for enterprise resolvers
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
Labels: debt

#20125 Fix code insights integration flakiness
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
  client/web/src/integration/insights.test.ts
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
Labels: team/frontend-platform

#20248 gitserver: Cleanups spotted while investigating an issue
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
Labels: team/core-application

#20243 codeintel: Simplify committed at migrator batch selection query
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
Labels: team/code-intelligence

#20247 Remove credentials from repo clone urls
  internal/repos/awscodecommit.go
  internal/repos/bitbucketcloud.go
  internal/repos/bitbucketserver.go
  internal/repos/github.go
  internal/repos/gitlab.go
  internal/repos/perforce.go
  internal/repos/phabricator.go
  internal/repos/sources_test.go
  internal/repos/testdata/bitbucketserver-repos-path-pattern.golden
  internal/repos/testdata/bitbucketserver-repos-simple.golden
  internal/repos/testdata/bitbucketserver-repos-username.golden
  internal/repos/testdata/golden/BitbucketCloudSource_makeRepo_path-pattern
  internal/repos/testdata/golden/BitbucketCloudSource_makeRepo_simple
  internal/repos/testdata/golden/PerforceSource_makeRepo_path-pattern
  internal/repos/testdata/golden/PerforceSource_makeRepo_simple
Labels: team/core-application

#20251 github: Request 'repo' OAuth scope
  enterprise/cmd/frontend/internal/auth/githuboauth/provider.go
  enterprise/cmd/frontend/internal/auth/githuboauth/provider_test.go
  internal/repos/github.go
Labels: team/core-application

#20255 Revert "github: Request 'repo' OAuth scope (#20251)"
  enterprise/cmd/frontend/internal/auth/githuboauth/provider.go
  enterprise/cmd/frontend/internal/auth/githuboauth/provider_test.go
  internal/repos/github.go
Labels: team/core-application

#20256 github: Request 'repo' OAuth scope (#20251)
  enterprise/cmd/frontend/internal/auth/githuboauth/provider.go
  enterprise/cmd/frontend/internal/auth/githuboauth/provider_test.go
  internal/database/external_services.go
  internal/repos/github.go
Labels: team/core-application

#20083 web: add redesign-theme typography styles
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/GlobalStylesStory/TextStory.tsx
  client/branded/src/global-styles/GlobalStylesStory/TextVariations.module.scss
  client/branded/src/global-styles/GlobalStylesStory/TextVariations.tsx
  client/branded/src/global-styles/buttons.scss
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/typography-redesign.scss
  client/branded/src/global-styles/typography.scss
  client/shared/src/extensions/ExtensionStatus.tsx
  client/web/src/components/Breadcrumbs.story.tsx
  client/web/src/components/Breadcrumbs.tsx
  client/web/src/extensions/ExtensionCard.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/repo/FilePathBreadcrumbs.tsx
Labels: redesign, team/frontend-platform

#20246 web: add Bootstrap breakpoints mixins entry-point for CSS modules
  client/branded/src/global-styles/breakpoints.scss
  client/branded/src/global-styles/index.scss
  client/browser/config/webpack/base.config.ts
  client/browser/src/app.scss
  client/storybook/src/main.ts
  client/web/src/enterprise/productSubscription/TrueUpStatusSummary.scss
  client/web/src/repo/tree/TreeEntriesSection.scss
  client/web/src/repo/tree/TreePage.scss
  client/web/src/search/queryBuilder/QueryBuilder.scss
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.scss
  client/web/webpack.config.js
  doc/dev/background-information/web/styling.md
Labels: ops & tools & dev, team/frontend-platform

#20267 web: fix TS constructor arguments shorthand
  babel.config.js
  package.json
Labels: merge-on-any-approve, team/frontend-platform

#20264 codeintel: Fix update deadlock in commit date migrator
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
Labels: team/code-intelligence

#20273 oobmigration: Re-check progress when we get a refreshed migration record
  internal/oobmigration/runner.go
  internal/oobmigration/runner_test.go
Labels: team/code-intelligence

#20276 codeintel: Only update committed_at on records that don't already have it set
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
Labels: team/code-intelligence

#20252 Properly hide Batch Changes site-admin area on dotcom
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
Labels: team/batchers

#18927 Refactor some usages of GQL types to graphql-operations types
  client/browser/src/shared/backend/diffs.tsx
  client/browser/src/shared/components/OpenDiffOnSourcegraph.tsx
  client/web/src/enterprise/site-admin/SiteAdminExternalAccountsPage.tsx
  client/web/src/enterprise/user/settings/ExternalAccountNode.tsx
  client/web/src/enterprise/user/settings/UserSettingsExternalAccountsPage.tsx
  client/web/src/repo/GitReference.tsx
  client/web/src/repo/RevisionsPopover.tsx
  client/web/src/repo/branches/RepositoryBranchesAllPage.tsx
  client/web/src/repo/releases/RepositoryReleasesTagsPage.tsx
Labels: debt

#20288 web: skip asking for accountData in listing external accounts
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
Labels: team/core-application

#20290 Improve error handling for code host errors
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/core-application

#20094 Add ctags binary path to zoekt-indexserver
  sg.config.yaml
Labels: sg

#20291 Remove Link usage from code insights charts and use native links
  client/web/src/views/ChartViewContent/ChartViewContent.tsx
  client/web/src/views/ChartViewContent/charts/MaybeLink.tsx
Labels: bug, team/code-insights, webapp

#20284 codeintel: add explicit support for MarkupContent in lsif/protocol & optimize hover ingestion
  enterprise/lib/codeintel/lsif/protocol/hover.go
  enterprise/lib/codeintel/lsif/protocol/reader/unmarshal.go
  enterprise/lib/codeintel/lsif/protocol/reader/unmarshal_test.go
  enterprise/lib/codeintel/lsif/protocol/writer/emitter.go
Labels: team/code-intelligence

#20304 oobmigrations: Add metrics
  cmd/frontend/internal/cli/serve_cmd.go
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  enterprise/cmd/frontend/internal/codeintel/config.go
  internal/oobmigration/observability.go
  internal/oobmigration/runner.go
  internal/oobmigration/runner_test.go
  monitoring/definitions/frontend.go
Labels: RFC-311, team/code-intelligence

#20308 codeintel: Stop infinitely processing the same batch of unknown commits
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence

#20323 codeintel: Ensure commit date migrator doesn't get suck on deleted repos
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at_test.go
Labels: team/code-intelligence

#20325 batches: correctly set the Bitbucket Server authenticator
  CHANGELOG.md
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/bitbucketserver_test.go
Labels: team/batchers

#20327 codeintel: Unwrap vcs.IsRepoNotExist error when checking error
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
Labels: team/code-intelligence

#20321 github: Switch back to not requesting private repo scope
  enterprise/cmd/frontend/internal/auth/githuboauth/provider.go
  enterprise/cmd/frontend/internal/auth/githuboauth/provider_test.go
Labels: team/core-application

#20322 frontend: Separate default repos scope
  cmd/frontend/backend/repos.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/internal/search/repos/repos.go
  cmd/repo-updater/shared/main.go
  internal/database/default_repos.go
  internal/database/default_repos_test.go
  internal/database/repos.go
Labels: team/core-application

#20363 Integration tests - limit worker processes
  package.json
Labels: team/frontend-platform

#20358 frontend: Rename default repo related methods
  cmd/frontend/backend/repos.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/httpapi/internal_test.go
  cmd/frontend/internal/search/repos/repos.go
Labels: team/core-application
