Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-09, with the labels that each got.

#24494 sg: Do not run gulp with --silent option
  sg.config.yaml
Labels: sg

#24501 frontend: Add extra tracing for TreeEntries
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_tree.go
  cmd/frontend/graphqlbackend/repository.go
Labels: team/core-application

#24487 esbuild: new experimental option for web builds
  client/shared/src/util/rxjs/combineLatestOrDefault.ts
  client/web/README.md
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/manifestPlugin.ts
  client/web/dev/esbuild/monacoPlugin.ts
  client/web/dev/esbuild/packageResolutionPlugin.ts
  client/web/dev/esbuild/server.ts
  client/web/dev/esbuild/stylePlugin.ts
  client/web/dev/esbuild/workerPlugin.ts
  client/web/dev/utils/constants.ts
  client/web/dev/utils/environment-config.ts
  client/web/dev/webpack/monacoWebpack.ts
  client/web/gulpfile.js
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/app.html
  dev/start.sh
  doc/dev/background-information/web/build.md
  gulpfile.js
  package.json
  ui/assets/manifest.go
  yarn.lock
Labels: team/frontend-platform, dx, web server, dx-announce

#24534 API docs: fix missing pages
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
Labels: api-docs

#24510 frontend: Add more tracing around tree entries
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/internal/cloneurls/clone_urls.go
Labels: team/core-application

#24542 frontend: Extract logic from for loop so it can be traced
  cmd/frontend/internal/cloneurls/clone_urls.go
  internal/conf/reposource/common.go
  internal/conf/reposource/custom.go
Labels: team/core-application

#24426 add last synced icon to results
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/shared/src/components/FileMatch.tsx
  client/shared/src/components/FileMatchChildren.scss
  client/shared/src/components/FileMatchChildren.tsx
  client/shared/src/components/LastSyncedIcon.module.scss
  client/shared/src/components/LastSyncedIcon.tsx
  client/shared/src/components/ResultContainer.scss
  client/shared/src/components/ResultContainer.tsx
  client/web/src/components/CommitSearchResultMatch.module.scss
  client/web/src/components/CommitSearchResultMatch.tsx
  client/web/src/components/SearchResult.tsx
  client/web/src/components/SearchResultMatch.scss
Labels: team/search-product

#24517 ping: Fix code intelligence usage data
  internal/database/event_logs.go
Labels: team/code-intelligence

#24550 Specify the git author name, email and date for package repos.
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  internal/conf/reposource/jvm_packages.go
Labels: dependency-indexing

#24560 remove isLightTheme from search path
  client/branded/src/components/panel/views/FileLocations.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/shared/src/components/CodeExcerpt.tsx
  client/shared/src/components/FileMatch.test.tsx
  client/shared/src/components/FileMatch.tsx
  client/shared/src/components/FileMatchChildren.test.tsx
  client/shared/src/components/FileMatchChildren.tsx
  client/shared/src/components/ResultContainer.test.tsx
  client/web/src/components/CommitSearchResultMatch.tsx
  client/web/src/components/SearchResult.tsx
  client/web/src/integration/streaming-search-mocks.ts
  client/web/src/repo/backend.ts
  client/web/src/repo/docs/DocumentationExamplesListItem.tsx
  client/web/src/search/backend.tsx
  client/web/src/search/results/StreamingSearchResultsList.tsx
  cmd/frontend/graphqlbackend/file.go
  cmd/frontend/graphqlbackend/highlight.go
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/repository_comparison_test.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/internal/highlight/highlight.go
Labels: team/search-product

#24567 Fix unterminated string in doc HTML creating_an_access_token
  doc/cli/how-tos/creating_an_access_token.md
Labels: docs

#24574 dotcom: redirect sitemap.xml.gz -> GCS
  cmd/frontend/auth/non_public.go
  cmd/frontend/internal/app/app.go
  cmd/frontend/internal/app/misc_handlers.go
  cmd/frontend/internal/app/router/router.go
Labels: api-docs

#24575 cmd/sitemap: fix validation error
  cmd/sitemap/main.go
Labels: api-docs

#24578 sitemap: various bug fixes
  cmd/frontend/internal/app/misc_handlers.go
  cmd/frontend/internal/app/router/router.go
  cmd/sitemap/main.go
Labels: api-docs

#24309 Code Insights: Add Code Insights FE arch overview docs
  doc/dev/background-information/insights/assets/insight-dashboard-loading.svg
  doc/dev/background-information/insights/assets/settings-cascade-levels.svg
  doc/dev/background-information/insights/diagrams/architecture.svg
  doc/dev/background-information/insights/frontend-learning-materials.md
  doc/dev/background-information/insights/frontend.md
  doc/dev/background-information/insights/index.md
Labels: team/code-insights, insights-post-beta

#24227 move theme props from <SourcegraphWebApp> to useTheme hook
  client/browser/src/shared/code-hosts/github/codeHost.ts
  client/shared/src/theme.ts
  client/web/src/Layout.test.tsx
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/routes.tsx
  client/web/src/theme.test.ts
  client/web/src/theme.ts
Labels: webapp, team/frontend-platform

#24592 web: add missing typename to `viewerSettings` and `extensionsRegistry` queries in tests
  client/web/src/integration/batches.test.ts
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/code-monitoring.test.ts
  client/web/src/integration/extension-registry.test.ts
  client/web/src/integration/graphQlResults.ts
  client/web/src/integration/insights/utils/override-graphql-with-extensions.ts
  client/web/src/integration/notebook.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/integration/search-contexts.test.ts
  client/web/src/integration/search-onboarding.test.ts
  client/web/src/integration/search.test.ts
Labels: testing, team/frontend-platform

#24586 web: add `getGraphQLClient` to the `platformContext`
  client/browser/src/shared/backend/requestGraphQl.ts
  client/browser/src/shared/platform/context.ts
  client/shared/src/api/client/connection.ts
  client/shared/src/api/client/mainthread-api.test.ts
  client/shared/src/api/client/mainthread-api.ts
  client/shared/src/api/integration-test/testHelpers.ts
  client/shared/src/graphql/graphql.ts
  client/shared/src/platform/context.ts
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/backend/graphql.ts
  client/web/src/platform/context.ts
  client/web/src/settings/temporary/TemporarySettingsProvider.tsx
  client/web/src/settings/temporary/TemporarySettingsStorage.ts
Labels: team/frontend-platform

#24599 Deprecate "sg run-set", use "sg start" instead, rework help output
  dev/sg/main.go
Labels: dx, sg

#24634 sg: wait for cmd readers to close before waiting on cmd
  dev/sg/internal/run/command.go
Labels: sg

#24629 web: codemod template literal to `classNames` call [1]
  client/branded/src/components/Form.tsx
  client/branded/src/components/panel/views/FileLocations.tsx
  client/shared/src/actions/ActionItem.tsx
  client/shared/src/actions/__snapshots__/ActionItem.test.tsx.snap
  client/shared/src/components/CodeExcerpt.tsx
  client/shared/src/components/activation/ActivationChecklist.tsx
  client/shared/src/components/activation/__snapshots__/ActivationChecklist.test.tsx.snap
  client/shared/src/components/icons.tsx
  client/shared/src/symbols/SymbolIcon.tsx
  client/web/src/auth/SignInSignUpCommon.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/components/CopyableText.tsx
  client/web/src/components/FeedbackText.tsx
  client/web/src/components/ModalPage.tsx
  client/web/src/components/RadioButtons.tsx
  client/web/src/components/SingleValueCard.tsx
  client/web/src/components/diff/DiffBoundary.tsx
  client/web/src/components/externalServices/__snapshots__/ExternalServiceForm.test.tsx.snap
  client/web/src/enterprise/search/stats/__snapshots__/SearchStatsPage.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminGenerateProductLicenseForSubscriptionForm.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/ProductSubscriptionForm.test.tsx.snap
  client/web/src/site-admin/overview/__snapshots__/SiteAdminOverviewPage.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24631 web: codemod template literal to `classNames` call [3]
  client/web/src/insights/components/insight-view-content/chart-view-content/ChartViewContent.tsx
  client/web/src/org/OrgAvatar.tsx
  client/web/src/person/PersonLink.tsx
  client/web/src/person/__snapshots__/PersonLink.test.tsx.snap
  client/web/src/repo/DirectImportRepoAlert.tsx
  client/web/src/repo/RepositoriesPopover.tsx
  client/web/src/repo/blob/Blob.tsx
  client/web/src/repo/branches/RepositoryBranchesNavbar.tsx
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/commits/__snapshots__/GitCommitNodeByline.test.tsx.snap
  client/web/src/repo/docs/DocumentationIcon.tsx
  client/web/src/repo/docs/DocumentationIndexNode.tsx
  client/web/src/repo/docs/DocumentationNode.tsx
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  client/web/src/repo/settings/RepoSettingsIndexPage.tsx
  client/web/src/repo/settings/components/ActionContainer.tsx
  client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
  client/web/src/repo/stats/RepositoryStatsNavbar.tsx
  client/web/src/search/input/SearchBox.tsx
  client/web/src/search/queryBuilder/QueryBuilderPage.tsx
  client/web/src/settings/SettingsArea.tsx
  client/web/src/site-admin/SiteAdminAlert.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
  client/web/src/site-admin/SiteAdminTokensPage.tsx
  client/web/src/site/FreeUsersExceededAlert.tsx
  client/web/src/user/settings/emails/AddUserEmailForm.tsx
  client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
Labels: team/frontend-platform, dx, CSS Modules migration

#24630 web: codemod template literal to `classNames` call [2]
  client/web/src/components/diff/DiffHunk.tsx
  client/web/src/components/diff/DiffSplitHunk.tsx
  client/web/src/components/diff/DiffStat.tsx
  client/web/src/components/diff/FileDiffHunks.tsx
  client/web/src/components/diff/Lines.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
  client/web/src/components/externalServices/ExternalServiceCard.tsx
  client/web/src/components/externalServices/ExternalServiceForm.tsx
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/enterprise/code-monitoring/components/FormActionArea.tsx
  client/web/src/enterprise/dotcom/productPlans/ProductPlanFormControl.tsx
  client/web/src/enterprise/dotcom/productPlans/ProductSubscriptionUserCountFormControl.tsx
  client/web/src/enterprise/dotcom/productPlans/__snapshots__/ProductPlanFormControl.test.tsx.snap
  client/web/src/enterprise/dotcom/productPlans/__snapshots__/ProductSubscriptionUserCountFormControl.test.tsx.snap
  client/web/src/enterprise/dotcom/productSubscriptions/AccountEmailAddresses.tsx
  client/web/src/enterprise/dotcom/productSubscriptions/ProductLicenseValidity.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionForm.tsx
  client/web/src/enterprise/extensions/registry/RegistryExtensionSourceBadge.tsx
  client/web/src/enterprise/productSubscription/LicenseGenerationKeyWarning.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductLicenseNode.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/PaymentTokenFormControl.tsx
  client/web/src/enterprise/user/productSubscriptions/ProductSubscriptionBeforeAfterInvoiceItem.tsx
  client/web/src/enterprise/user/productSubscriptions/ProductSubscriptionForm.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/extensions/extension/ExtensionConfigurationState.tsx
  client/web/src/extensions/extension/RegistryExtensionReadme.tsx
  client/web/src/global/Notices.tsx
  client/web/src/global/__snapshots__/Notices.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24638 Don't infer lsif-java auto-index config for non-indexable repos
  lib/codeintel/autoindex/inference/java.go
  lib/codeintel/autoindex/inference/java_test.go
Labels: team/code-intelligence, dependency-indexing

#24654 sg: Fix deadlock when command fails to install/run
  dev/sg/go.mod
  dev/sg/go.sum
  dev/sg/internal/run/command.go
  lib/process/pipe.go
Labels: sg

#24559 Code Insights: Adopt built-in fetchers for search based and code stats insights
  client/shared/src/extensions/extension.ts
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/components/index.ts
  client/web/src/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
  client/web/src/insights/components/insights-view-grid/StaticInsightsViewGrid.tsx
  client/web/src/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/insights/components/insights-view-grid/components/built-in-insight/BuiltInInsight.tsx
  client/web/src/insights/components/insights-view-grid/components/smart-insight/SmartInsight.tsx
  client/web/src/insights/components/insights-view-grid/components/static-view/StaticView.tsx
  client/web/src/insights/components/insights-view-grid/index.ts
  client/web/src/insights/core/backend/api-provider.ts
  client/web/src/insights/core/backend/api/get-backend-insight.ts
  client/web/src/insights/core/backend/api/get-built-in-insight.ts
  client/web/src/insights/core/backend/api/get-combined-views.ts
  client/web/src/insights/core/backend/api/get-extension-view-by-id.ts
  client/web/src/insights/core/backend/api/get-lang-stats-insight-content.ts
  client/web/src/insights/core/backend/api/get-search-insight-content/get-search-insight-content.ts
  client/web/src/insights/core/backend/create-insights-api.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/core/backend/utils/create-extension-insight.ts
  client/web/src/insights/core/backend/utils/resolve-uri.ts
  client/web/src/insights/core/settings-action/insights.ts
  client/web/src/insights/core/types/insight/index.ts
  client/web/src/insights/core/types/insight/search-insight.ts
  client/web/src/insights/hooks/use-insight/use-insight.ts
  client/web/src/insights/index.ts
  client/web/src/insights/pages/dashboards/DasbhoardsRoutes.tsx
  client/web/src/insights/pages/dashboards/creation/InsightsDashboardCreationPage.story.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/DashboardsPage.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/components/live-preview-chart/hooks/use-lang-stats-preview-content.ts
  client/web/src/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/insights/edit-insight/hooks/use-update-settings-subjects/use-update-settings-subjects.test.tsx
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/drill-down-filters.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/insights-visual.test.ts
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/search/home/SearchPage.tsx
Labels: team/code-insights

#24659 API docs: minor fixes & improvements to page titles / descriptions
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  cmd/frontend/internal/app/ui/handlers_docs.go
Labels: api-docs

#24646 Code Insights: Fix insights muted/skipped integration tests
  client/shared/src/api/extension/activation.ts
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/drill-down-filters.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/insights-visual.test.ts
  client/web/src/integration/insights/utils/insight-extension-bundles.ts
  client/web/src/integration/insights/utils/insight-mock-data.ts
  client/web/src/integration/insights/utils/override-insights-graphql.ts
Labels: debt

#24588 Faster ReposourceCloneURLToRepoName
  cmd/frontend/internal/app/editor_test.go
  cmd/frontend/internal/cloneurls/clone_urls.go
  internal/database/external_services.go
  internal/database/repos.go
  internal/database/repos_db_test.go
  internal/database/repos_mock.go
Labels: team/core-application

#24665 docs: Add missing columns to worker docs
  doc/dev/background-information/workers.md
Labels: docs, dx

#24666 Improve integration test suite CI run script
  client/shared/dev/generateCssModulesTypes.js
  client/web/dev/server/development.server.ts
  client/web/gulpfile.js
  enterprise/dev/ci/internal/ci/pipeline-steps.go
  gulpfile.js
  package.json
Labels: dx

#24564 searcher: remove batch API v2
  cmd/searcher/protocol/searcher.go
  cmd/searcher/search/search.go
  cmd/searcher/search/search_test.go
  cmd/searcher/search/sender.go
  internal/search/searcher/client.go
  internal/search/unindexed/unindexed.go
  internal/search/unindexed/unindexed_test.go
Labels: team/search-product

#24529 Update docs for Sync All feature
  doc/cloud/getting_started_on_cloud.md
  doc/code_search/how-to/adding_repositories_to_cloud.md
Labels: team/core-application

#24522 codeintel: Avoid ref description collisions
  enterprise/cmd/worker/internal/codeintel/commitgraph/iface.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater_test.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24603 codeintel: Add BranchesContaining to gitserver client
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/client_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24613 codeintel: Update refcount when records are deleted
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24612 codeintel: Update refcount when new records are created
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24611 codeintel: Add out-of-band migration to backfill reference counts
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/migrations.go
  enterprise/internal/codeintel/stores/dbstore/migration/consts.go
  enterprise/internal/codeintel/stores/dbstore/migration/reference_count.go
  enterprise/internal/codeintel/stores/dbstore/migration/reference_count_test.go
  migrations/frontend/1528395873_lsif_upload_reference_counts_oob_migration.down.sql
  migrations/frontend/1528395873_lsif_upload_reference_counts_oob_migration.up.sql
Labels: team/code-intelligence, code-intel-data-retention

#24604 codeintel: Filter by purpose in GetConfigurationPolicies
  enterprise/internal/codeintel/stores/dbstore/configuration_policies.go
Labels: team/code-intelligence, code-intel-data-retention

#24608 codeintel: Add denormalized reference counts to uploads
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/migrations.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
  enterprise/internal/codeintel/stores/dbstore/migration/consts.go
  enterprise/internal/codeintel/stores/dbstore/migration/reference_count.go
  enterprise/internal/codeintel/stores/dbstore/migration/reference_count_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  internal/database/schema.md
  migrations/frontend/1528395872_lsif_upload_reference_counts.down.sql
  migrations/frontend/1528395872_lsif_upload_reference_counts.up.sql
  migrations/frontend/1528395873_lsif_upload_reference_counts_oob_migration.down.sql
  migrations/frontend/1528395873_lsif_upload_reference_counts_oob_migration.up.sql
Labels: team/code-intelligence, code-intel-data-retention

#24699 Fix architecture diagram font
  doc/dev/background-information/architecture/architecture.css
  doc/dev/background-information/architecture/architecture.dot
  doc/dev/background-information/architecture/architecture.svg
  doc/dev/background-information/architecture/index.md
Labels: docs

#24705 Fix can't access property "key", t is null error
  client/web/src/repo/tree/TreePage.tsx
Labels: bug

#24706 ask Google, etc. not to index useless or poor pages
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/handlers_docs.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/raw.go
  cmd/frontend/internal/app/ui/router.go
Labels: api-docs

#24626 Perf and other improvements for querying extensions
  cmd/frontend/registry/api/extensions.go
  cmd/frontend/registry/api/extensions_test.go
  cmd/frontend/registry/client/client.go
  enterprise/cmd/frontend/internal/registry/extensions_db.go
  enterprise/cmd/frontend/internal/registry/extensions_db_test.go
  enterprise/cmd/frontend/internal/registry/http_api.go
Labels: extensions, perf, team/extensibility

#22572 vscode: exclude *.scss.d.ts (generated) files from explorer
  .vscode/settings.json
Labels: team/frontend-platform

#24627 Refactors to queryConfiguredRegistryExtensions and related code
  client/shared/src/api/client/enabledExtensions.ts
  client/shared/src/extensions/extension.ts
  client/shared/src/extensions/helpers.ts
  client/shared/src/testing/integration/mockExtension.ts
  client/web/src/integration/extension-registry.test.ts
Labels: extensions, team/extensibility

#24622 support standalone dev server for esbuild
  client/web/README.md
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/manifestPlugin.ts
  client/web/dev/esbuild/server.ts
  client/web/dev/server/development.server.ts
  client/web/dev/server/production.server.ts
  client/web/dev/utils/csrf/get-csrf-token-and-cookie.ts
  client/web/dev/utils/environment-config.ts
  client/web/dev/webpack/get-html-webpack-plugins.ts
  client/web/gulpfile.js
  client/web/src/global/GlobalAlerts.tsx
  doc/dev/background-information/web/build.md
Labels: team/frontend-platform

#24632 Speed up fetching/loading of extensions via `graphql?Extensions`
  client/shared/src/api/client/enabledExtensions.ts
  client/shared/src/api/extension/test/activation.test.ts
  client/shared/src/extensions/extension.ts
  client/shared/src/extensions/helpers.test.ts
  client/shared/src/extensions/helpers.ts
  client/shared/src/testing/integration/mockExtension.ts
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/extension-registry.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/settings/configuration.test.ts
  client/web/src/settings/configuration.ts
  cmd/frontend/graphqlbackend/extension_registry.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/registry/api/extension_connection_graphql.go
  cmd/frontend/registry/api/extension_connection_graphql_test.go
  cmd/frontend/registry/api/extension_manifest.go
  cmd/frontend/registry/api/extension_manifest_test.go
  enterprise/cmd/frontend/internal/registry/extension_connection_graphql.go
  enterprise/cmd/frontend/internal/registry/extension_connection_graphql_test.go
  enterprise/cmd/frontend/internal/registry/extensions_db.go
  enterprise/cmd/frontend/internal/registry/extensions_db_test.go
Labels: extensions, team/extensibility

#24660 web: codemod `web/diff` components to CSS modules
  client/branded/src/global-styles/code.scss
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/diff/DiffBoundary.module.scss
  client/web/src/components/diff/DiffBoundary.tsx
  client/web/src/components/diff/DiffHunk.module.scss
  client/web/src/components/diff/DiffHunk.tsx
  client/web/src/components/diff/DiffSplitHunk.test.tsx
  client/web/src/components/diff/DiffSplitHunk.tsx
  client/web/src/components/diff/DiffStat.module.scss
  client/web/src/components/diff/DiffStat.scss
  client/web/src/components/diff/DiffStat.tsx
  client/web/src/components/diff/FileDiffHunks.module.scss
  client/web/src/components/diff/FileDiffHunks.scss
  client/web/src/components/diff/FileDiffHunks.tsx
  client/web/src/components/diff/FileDiffNode.module.scss
  client/web/src/components/diff/FileDiffNode.scss
  client/web/src/components/diff/FileDiffNode.tsx
  client/web/src/components/diff/Lines.module.scss
  client/web/src/components/diff/Lines.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
  client/web/src/components/diff/__snapshots__/DiffStat.test.tsx.snap
  client/web/src/repo/compare/dom-functions.ts
Labels: team/frontend-platform, dx, CSS Modules migration

#24688 Add dotcom commandset & allow setting env per commandset
  dev/sg/config.go
  dev/sg/main.go
  dev/sg/sg.config.example.yaml
  sg.config.yaml
Labels: sg

#24661 web: codemod `web/components` components to CSS modules [1]
  client/branded/src/global-styles/card.scss
  client/branded/src/global-styles/index.scss
  client/web/src/SourcegraphWebApp.scss
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/components/Badge.module.scss
  client/web/src/components/Badge.tsx
  client/web/src/components/ButtonTooltip.tsx
  client/web/src/components/Collapsible.module.scss
  client/web/src/components/Collapsible.scss
  client/web/src/components/Collapsible.tsx
  client/web/src/components/CopyableText.module.scss
  client/web/src/components/CopyableText.scss
  client/web/src/components/CopyableText.tsx
  client/web/src/components/CtaBanner.module.scss
  client/web/src/components/CtaBanner.tsx
  client/web/src/components/FilteredConnection/FilterControl.module.scss
  client/web/src/components/FilteredConnection/FilterControl.tsx
  client/web/src/components/HeroPage.module.scss
  client/web/src/components/HeroPage.scss
  client/web/src/components/HeroPage.tsx
  client/web/src/components/InputTooltip.module.scss
  client/web/src/components/InputTooltip.tsx
  client/web/src/components/ModalPage.module.scss
  client/web/src/components/ModalPage.scss
  client/web/src/components/ModalPage.tsx
  client/web/src/components/RadioButtons.module.scss
  client/web/src/components/RadioButtons.scss
  client/web/src/components/RadioButtons.tsx
  client/web/src/components/__snapshots__/ErrorBoundary.test.tsx.snap
  client/web/src/components/branding/BrandLogo.module.scss
  client/web/src/components/branding/BrandLogo.scss
  client/web/src/components/branding/BrandLogo.tsx
  client/web/src/components/branding/__snapshots__/BrandLogo.test.tsx.snap
  client/web/src/components/externalServices/AddExternalServicePage.tsx
  client/web/src/components/externalServices/AddExternalServicesPage.module.scss
  client/web/src/components/externalServices/AddExternalServicesPage.scss
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductLicenseNode.test.tsx.snap
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/web/src/repo/ConnectionPopover.scss
  client/web/src/repo/RepositoriesPopover.scss
  client/web/src/repo/RevisionsPopover/RevisionsPopover.scss
  client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
  client/web/src/site-admin/overview/__snapshots__/SiteAdminOverviewPage.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24664 web: codemod `web/components` components to CSS modules [2]
  client/shared/src/components/Markdown.tsx
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/CommitSearchResultMatch.module.scss
  client/web/src/components/CommitSearchResultMatch.tsx
  client/web/src/components/SaveToolbar.module.scss
  client/web/src/components/SaveToolbar.scss
  client/web/src/components/SaveToolbar.tsx
  client/web/src/components/SearchResult.module.scss
  client/web/src/components/SearchResult.scss
  client/web/src/components/SearchResult.tsx
  client/web/src/components/SearchResultMatch.scss
  client/web/src/components/Sidebar.module.scss
  client/web/src/components/Sidebar.scss
  client/web/src/components/Sidebar.tsx
  client/web/src/components/SingleValueCard.module.scss
  client/web/src/components/SingleValueCard.tsx
  client/web/src/components/Timeline.module.scss
  client/web/src/components/Timeline.scss
  client/web/src/components/Timeline.tsx
  client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.tsx
  client/web/src/enterprise/batches/create/examples/ExampleTabs.tsx
  client/web/src/extensions/ExtensionRegistrySidenav.tsx
  client/web/src/extensions/__snapshots__/ExtensionRegistrySidenav.test.tsx.snap
  client/web/src/integration/search.test.ts
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
  client/web/src/user/settings/UserSettingsSidebar.tsx
Labels: team/frontend-platform, dx, CSS Modules migration

#24652 codeintel: fix panic in extracting JARs with absolute paths
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_jvm_packages_test.go
Labels: team/code-intelligence, dependency-indexing

#24723 tracer: Don't load user for slow query logging
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/search_test.go
Labels: perf

#24606 codeintel: Add CommitsVisibleToUpload to dbstore
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  internal/database/schema.md
  migrations/frontend/1528395874_lsif_nearest_uploads_indexes.down.sql
  migrations/frontend/1528395874_lsif_nearest_uploads_indexes.up.sql
Labels: team/code-intelligence, code-intel-data-retention

#24708 codeintel: Optimize UpdateDependencyNumReferences query
  enterprise/internal/codeintel/stores/dbstore/uploads.go
Labels: team/code-intelligence, code-intelligence-performance

#24721 Mark code insights related deps and add code insights team as reviewers
  renovate.json
Labels: team/code-insights

#24724 Don't lookup user in temporary settings resolvers
  cmd/frontend/graphqlbackend/temporary_settings.go
  cmd/frontend/graphqlbackend/temporary_settings_test.go
Labels: perf

#24532 insights: created insight-data-gen utility to construct code insights repos
  enterprise/dev/insight-data-gen/.gitignore
  enterprise/dev/insight-data-gen/README.md
  enterprise/dev/insight-data-gen/examples/manifest.json
  enterprise/dev/insight-data-gen/go.mod
  enterprise/dev/insight-data-gen/go.sum
  enterprise/dev/insight-data-gen/main.go
Labels: team/code-insights, dx

#24725 perf: Don't fetch feature flags when not used in request
  internal/featureflag/middleware.go
Labels: perf

#24713 Set notifications polling interval to 60 seconds
  client/web/src/nav/StatusMessagesNavItem.tsx
Labels: team/core-application

#24754 chore: Fix typos
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/configuration_policy.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
  enterprise/internal/codeintel/stores/dbstore/migration/consts.go
Labels: team/code-intelligence

#24756 codeintel: Ensure generated mocks are test files
  enterprise/cmd/worker/internal/codeintel/janitor/gen.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_test.go
Labels: team/code-intelligence

#24755 web: fix search-result-star styles
  client/shared/src/components/ResultContainer.tsx
  client/shared/src/components/SearchResultStar.module.scss
  client/shared/src/components/SearchResultStar.tsx
  client/web/src/components/SearchResult.module.scss
  client/web/src/components/SearchResult.tsx
Labels: team/frontend-platform

#24760 web: fix card spacer
  client/branded/src/global-styles/card.scss
Labels: team/frontend-platform

#23908 Fix totalCount on repo batch changes connection resolver
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change_connection.go
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/batch_changes_test.go
Labels: bug, team/batchers

#24769 codeintel: Add expired flag to uploads
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  internal/database/schema.md
  migrations/frontend/1528395875_lsif_upload_expired_flag.down.sql
  migrations/frontend/1528395875_lsif_upload_expired_flag.up.sql
Labels: team/code-intelligence, code-intel-data-retention

#24770 codeintel: Add columns to track last retention scans
  internal/database/schema.md
  migrations/frontend/1528395876_lsif_last_retention_scan.down.sql
  migrations/frontend/1528395876_lsif_last_retention_scan.up.sql
Labels: team/code-intelligence, code-intel-data-retention

#24773 perf: Don't load user from DB where not necessary
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/saved_searches.go
  cmd/frontend/graphqlbackend/saved_searches_test.go
  cmd/frontend/graphqlbackend/site_admin.go
Labels: perf

#24774 perf: Don't fetch user on every request for licensing check
  enterprise/cmd/frontend/internal/authz/init.go
Labels: perf

#24216 batches: add GraphQL query for batch spec executions
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/frontend/internal/batches/resolvers/apitest/types.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_executions_connection.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_executions_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/background/executor_store.go
  enterprise/internal/batches/store/batch_spec_execution.go
  enterprise/internal/batches/store/batch_spec_execution_test.go
Labels: team/batchers, server-side

#24748 web: run puppeteer only if `client` is affected
  enterprise/dev/ci/internal/ci/is-client-affected.go
  enterprise/dev/ci/internal/ci/pipeline-steps.go
Labels: testing, team/frontend-platform, dx, ci

#24645 [Hack Time MVP] Enhance GH Search with Sourcegraph
  client/browser/config/webpack/base.config.ts
  client/browser/src/globals.d.ts
  client/browser/src/shared/code-hosts/github/codeHost.ts
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/shared/src/api/extension/extensionHostApi.ts
Labels: browser-extension, team/extensibility

#24778 codeintel: Add UpdateUploadRetention
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/hard_delete.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24795 codeintel: Define magic strings for git object types
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/configuration_policy.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/internal/codeintel/stores/dbstore/configuration_policies.go
  enterprise/internal/codeintel/stores/dbstore/configuration_policies_test.go
Labels: team/code-intelligence

#24794 codeintel: Add SoftDeleteExpiredUploads
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24777 codeintel: Add RepositoryIDsForRetentionScan
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24772 codeintel: Add skeleton upload expirer job
  enterprise/cmd/worker/internal/codeintel/janitor/gen.go
  enterprise/cmd/worker/internal/codeintel/janitor/iface.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/upload_expirer.go
  enterprise/cmd/worker/internal/codeintel/janitor_config.go
  enterprise/cmd/worker/internal/codeintel/janitor_job.go
Labels: team/code-intelligence, code-intel-data-retention

#24780 codeintel: forward $USER
  enterprise/cmd/executor/internal/command/run.go
Labels: team/code-intelligence

#24775 Let caddy wait for webpack dev server to be up
  dev/Caddyfile
Labels: dx

#24798 Add missing indexes to codeintel tables
  internal/database/schema.md
  migrations/frontend/1528395877_index-lsif-uploads-repo.down.sql
  migrations/frontend/1528395877_index-lsif-uploads-repo.up.sql
  migrations/frontend/1528395878_index-lsif-indexes-repo.down.sql
  migrations/frontend/1528395878_index-lsif-indexes-repo.up.sql
Labels: perf

#24805 Code Insights: fix Homepage extension and insight views rendering by experimental flag
  client/web/src/enterprise/insights/sections/ExtensionViewsHomepageSection.tsx
  client/web/src/enterprise/routes.tsx
  client/web/src/insights/sections/ExtensionViewsHomepageSection.tsx
  client/web/src/insights/utils/is-code-insights-enabled.ts
Labels: bug, team/code-insights

#24804 insights: add a moving daily snapshot for insights over all repos
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer_test.go
  enterprise/internal/insights/background/queryrunner/testdata/TestJobQueueDependencies/enqueue_with_dependencies.golden
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/worker.go
  enterprise/internal/insights/background/queryrunner/worker_test.go
  enterprise/internal/insights/compression/compression.go
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToRecording/test_to_recording_with_dependents.golden
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToRecording/test_to_recording_without_dependents.golden
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
  enterprise/internal/insights/store/mock_store_dataseriesstore.go
  enterprise/internal/insights/store/store.go
  enterprise/internal/insights/store/store_test.go
  enterprise/internal/insights/store/testdata/TestDeleteSnapshots.golden
  enterprise/internal/insights/types/types.go
  internal/database/schema.md
  internal/insights/insights.go
  migrations/codeinsights/1000000012_insights_snapshots.down.sql
  migrations/codeinsights/1000000012_insights_snapshots.up.sql
  migrations/frontend/1528395875_insights_queue_persist_mode.down.sql
  migrations/frontend/1528395875_insights_queue_persist_mode.up.sql
Labels: team/code-insights, backend

#24614 dev/release: improve automation for ensuring followup
  .github/ISSUE_TEMPLATE/request_patch_release.md
  dev/release/release-config.jsonc
  dev/release/src/batchChanges.ts
  dev/release/src/config.ts
  dev/release/src/github.ts
  dev/release/src/release.ts
Labels: release-tool

#24823 insights: adjust retry configuration for queries
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/background/queryrunner/worker.go
Labels: bug, team/code-insights, backend

#24759 web: codemod `web/auth` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/api/ApiConsole.module.scss
  client/web/src/api/ApiConsole.scss
  client/web/src/api/ApiConsole.tsx
  client/web/src/auth/OrDivider.module.scss
  client/web/src/auth/OrDivider.scss
  client/web/src/auth/OrDivider.tsx
  client/web/src/auth/PostSignUpPage.module.scss
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/auth/ResetPasswordPage.module.scss
  client/web/src/auth/ResetPasswordPage.scss
  client/web/src/auth/ResetPasswordPage.tsx
  client/web/src/auth/SignInPage.scss
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/SignInSignUpCommon.module.scss
  client/web/src/auth/SignInSignUpPageCommon.scss
  client/web/src/auth/SignUpForm.tsx
  client/web/src/auth/SignUpPage.scss
  client/web/src/auth/SignUpPage.tsx
  client/web/src/auth/UsernamePasswordSignInForm.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/auth/welcome/StartSearching.module.scss
  client/web/src/auth/welcome/StartSearching.tsx
  client/web/src/regression/util/helpers.ts
  client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24781 web: codemod `web/extensions/extension` components to CSS modules
  client/branded/src/components/ToggleBig.module.scss
  client/branded/src/components/ToggleBig.scss
  client/branded/src/components/ToggleBig.test.tsx
  client/branded/src/components/ToggleBig.tsx
  client/branded/src/components/__snapshots__/ToggleBig.test.tsx.snap
  client/web/src/SourcegraphWebApp.scss
  client/web/src/extensions/extension/ExtensionArea.module.scss
  client/web/src/extensions/extension/ExtensionArea.scss
  client/web/src/extensions/extension/ExtensionArea.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.module.scss
  client/web/src/extensions/extension/ExtensionAreaHeader.scss
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/extensions/extension/RegistryExtensionManifestPage.module.scss
  client/web/src/extensions/extension/RegistryExtensionManifestPage.scss
  client/web/src/extensions/extension/RegistryExtensionManifestPage.tsx
  client/web/src/extensions/extension/RegistryExtensionOverviewPage.module.scss
  client/web/src/extensions/extension/RegistryExtensionOverviewPage.scss
  client/web/src/extensions/extension/RegistryExtensionOverviewPage.tsx
  client/web/src/extensions/extension/__snapshots__/RegistryExtensionOverviewPage.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24784 web: codemod `web/global` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/DismissibleAlert/DismissibleAlert.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/global/GlobalAlerts.module.scss
  client/web/src/global/GlobalAlerts.scss
  client/web/src/global/GlobalAlerts.tsx
  client/web/src/global/Notices.module.scss
  client/web/src/global/Notices.scss
  client/web/src/global/Notices.tsx
  client/web/src/global/__snapshots__/Notices.test.tsx.snap
  client/web/src/site/CodeHostScopeAlerts/CodeHostScopeAlerts.tsx
Labels: team/frontend-platform, dx, CSS Modules migration

#24786 web: codemod `web/marketing` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/marketing/SurveyPage.module.scss
  client/web/src/marketing/SurveyPage.scss
  client/web/src/marketing/SurveyPage.tsx
  client/web/src/marketing/SurveyToast.tsx
  client/web/src/marketing/Toast.module.scss
  client/web/src/marketing/Toast.scss
  client/web/src/marketing/Toast.tsx
  client/web/src/repo/RepoRevisionContainer.scss
Labels: team/frontend-platform, dx, CSS Modules migration

#24791 web: codemod `web/site-admin` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/d3/BarChart.module.scss
  client/web/src/components/d3/BarChart.tsx
  client/web/src/components/externalServices/ExternalServicePage.tsx
  client/web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
  client/web/src/settings/SettingsFile.tsx
  client/web/src/site-admin/SiteAdmin.scss
  client/web/src/site-admin/SiteAdminAlert.module.scss
  client/web/src/site-admin/SiteAdminAlert.tsx
  client/web/src/site-admin/SiteAdminArea.module.scss
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminConfigurationPage.module.scss
  client/web/src/site-admin/SiteAdminConfigurationPage.scss
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
  client/web/src/site-admin/SiteAdminCreateUserPage.module.scss
  client/web/src/site-admin/SiteAdminCreateUserPage.scss
  client/web/src/site-admin/SiteAdminCreateUserPage.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.module.scss
  client/web/src/site-admin/SiteAdminMigrationsPage.scss
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.module.scss
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.scss
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.tsx
  client/web/src/site-admin/SiteAdminUpdatesPage.module.scss
  client/web/src/site-admin/SiteAdminUpdatesPage.scss
  client/web/src/site-admin/SiteAdminUpdatesPage.tsx
  client/web/src/site-admin/SiteAdminUsageStatisticsPage.module.scss
  client/web/src/site-admin/SiteAdminUsageStatisticsPage.scss
  client/web/src/site-admin/SiteAdminUsageStatisticsPage.tsx
  client/web/src/site-admin/init/SiteInitPage.module.scss
  client/web/src/site-admin/init/SiteInitPage.tsx
  client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
  client/web/src/site-admin/overview/__snapshots__/SiteAdminOverviewPage.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24829 Add benchmarks for hashing functions
  internal/endpoint/consistenthash_test.go
  internal/gitserver/internal_test.go
Labels: team/core-application

#24767 perf: Reduce amount of list repo and search contexts SQL queries
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  internal/database/search_contexts.go
Labels: perf

#24782 web: codemod `ExtensionCard` component to CSS modules
  client/branded/src/components/Toggle.module.scss
  client/branded/src/components/Toggle.scss
  client/branded/src/components/Toggle.tsx
  client/branded/src/components/__snapshots__/Toggle.test.tsx.snap
  client/browser/src/branded.scss
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/enterprise/code-monitoring/components/__snapshots__/FormActionArea.test.tsx.snap
  client/web/src/extensions/ExtensionCard.module.scss
  client/web/src/extensions/ExtensionCard.scss
  client/web/src/extensions/ExtensionCard.tsx
  client/web/src/extensions/ExtensionsArea.scss
  client/web/src/extensions/__snapshots__/ExtensionCard.test.tsx.snap
  client/web/src/extensions/__snapshots__/ExtensionToggle.test.tsx.snap
Labels: team/frontend-platform, dx, CSS Modules migration

#24783 web: codemod `ExtensionsArea` components to CSS modules
  client/branded/src/global-styles/index.scss
  client/web/src/SourcegraphWebApp.scss
  client/web/src/extensions/ExtensionBanner.module.scss
  client/web/src/extensions/ExtensionBanner.scss
  client/web/src/extensions/ExtensionBanner.tsx
  client/web/src/extensions/ExtensionsArea.module.scss
  client/web/src/extensions/ExtensionsArea.scss
  client/web/src/extensions/ExtensionsArea.tsx
  client/web/src/extensions/ExtensionsList.module.scss
  client/web/src/extensions/ExtensionsList.scss
  client/web/src/extensions/ExtensionsList.tsx
Labels: team/frontend-platform, dx, CSS Modules migration

#24846 codeintel: fix maven packages commit env var
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
Labels: team/code-intelligence, dependency-indexing

#24710 Enable sync all and add selection type tracking
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/auth/welcome/StartSearching.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/web/src/user/settings/repositories/SelectAffiliatedRepos.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/sidebaritems.ts
Labels: team/core-application

#24832 Fix GH search integration on "/search" page & when user is not logged in
  client/browser/src/shared/code-hosts/github/codeHost.ts
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
Labels: browser-extension, team/extensibility

#24813 Code Insights: Update frontend.md
  doc/dev/background-information/insights/frontend.md
Labels: team/code-insights

#24887 gitserver: Reduce error writing security event logs
  cmd/gitserver/main.go
  cmd/gitserver/server/server.go
Labels: team/core-application

#24916 insights: configure worker to retry on network timeout
  enterprise/internal/insights/background/queryrunner/worker.go
Labels: team/code-insights

#24917 added documentation button to site-admin panel
  CHANGELOG.md
  client/web/src/site-admin/sidebaritems.ts
Labels: quality-of-life

#24342 batches: admin batch spec executions list view
  client/shared/src/settings/settings.ts
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/batches/index.ts
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/settings/BatchSpecExecutionNode.module.scss
  client/web/src/enterprise/batches/settings/BatchSpecExecutionNode.story.tsx
  client/web/src/enterprise/batches/settings/BatchSpecExecutionNode.tsx
  client/web/src/enterprise/batches/settings/BatchSpecExecutionsPage.module.scss
  client/web/src/enterprise/batches/settings/BatchSpecExecutionsPage.story.tsx
  client/web/src/enterprise/batches/settings/BatchSpecExecutionsPage.tsx
  client/web/src/enterprise/batches/settings/backend.ts
  client/web/src/enterprise/batches/settings/testData.ts
  client/web/src/enterprise/site-admin/routes.ts
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/area/OrgHeader.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/user/settings/UserSettingsSidebar.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_execution.go
Labels: team/batchers, server-side

#24922 codeintel: Add additional config values to upload expirer
  enterprise/cmd/worker/internal/codeintel/janitor/upload_expirer.go
  enterprise/cmd/worker/internal/codeintel/janitor_config.go
  enterprise/cmd/worker/internal/codeintel/janitor_job.go
Labels: team/code-intelligence, code-intel-data-retention

#24925 codeintel: Update return of {RepositoryIDs,SelectRepositories}ForRetentionScan
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24929 codeintel: move lsifstore.Package[Reference] -> shared package
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_references_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/mock_scanner_test.go
  enterprise/internal/codeintel/stores/dbstore/helpers_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_scanner.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_test.go
  enterprise/internal/codeintel/stores/lsifstore/types.go
  enterprise/internal/codeintel/stores/shared/xrepo_types.go
Labels: api-docs

#24885 cmd/gitserver: Move doClone into it's own method
  cmd/gitserver/server/server.go
Labels: debt, refactor

#24866 web: use Apollo Client for `viewerSettings` query
  client/shared/src/graphql/fromObservableQuery.test.ts
  client/shared/src/graphql/fromObservableQuery.ts
  client/shared/src/testing/coverage.ts
  client/web/src/integration/code-monitoring.test.ts
  client/web/src/platform/context.ts
  client/web/src/settings/temporary/TemporarySettingsStorage.ts
Labels: team/frontend-platform, graphql-client/migration, UI performance

#24954 Remove starting blank line from migration template
  dev/sg/internal/migration/migration.go
Labels: sg

#24959 gitserver: Use internal actor when cloning a repo
  cmd/gitserver/server/server.go
Labels: team/core-application

#24294 codeintel: Implement upload expirer
  doc/admin/observability/dashboards.md
  enterprise/cmd/worker/internal/codeintel/janitor/abandoned_uploads.go
  enterprise/cmd/worker/internal/codeintel/janitor/deleted_repositories.go
  enterprise/cmd/worker/internal/codeintel/janitor/hard_delete.go
  enterprise/cmd/worker/internal/codeintel/janitor/iface.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_dbstore_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_gitserver_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/observability.go
  enterprise/cmd/worker/internal/codeintel/janitor/policy_matcher.go
  enterprise/cmd/worker/internal/codeintel/janitor/record_expirer.go
  enterprise/cmd/worker/internal/codeintel/janitor/repository_expiration_state.go
  enterprise/cmd/worker/internal/codeintel/janitor/upload_expirer.go
  enterprise/cmd/worker/internal/codeintel/janitor/upload_expirer_test.go
  internal/database/schema.md
  migrations/frontend/1528395885_lsif_last_retention_scan_views.down.sql
  migrations/frontend/1528395885_lsif_last_retention_scan_views.up.sql
  monitoring/definitions/shared/codeintel.go
Labels: team/code-intelligence, code-intel-data-retention

#24921 insights: added changelog entry for moving daily snapshot
  CHANGELOG.md
Labels: team/code-insights

#24969 codeintel: Add missing foreign key indexes
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  internal/database/schema.md
  migrations/frontend/1528395886_add_missing_fk_indexes1.down.sql
  migrations/frontend/1528395886_add_missing_fk_indexes1.up.sql
  migrations/frontend/1528395887_add_missing_fk_indexes2.down.sql
  migrations/frontend/1528395887_add_missing_fk_indexes2.up.sql
  migrations/frontend/1528395888_add_missing_fk_indexes3.down.sql
  migrations/frontend/1528395888_add_missing_fk_indexes3.up.sql
Labels: team/code-intelligence, postgres

#24968 Fix Github command palette icon vertical alignment
  client/browser/src/shared/code-hosts/github/codeHost.ts
Labels: browser-extension, team/extensibility

#24868 web: use Apollo Client for `extensions` query
  client/browser/src/shared/backend/requestGraphQl.ts
  client/browser/src/shared/platform/context.ts
  client/shared/src/api/client/enabledExtensions.ts
  client/shared/src/extensions/helpers.test.ts
  client/shared/src/extensions/helpers.ts
  client/shared/src/graphql/graphql.ts
  client/shared/src/platform/context.ts
  client/shared/src/testing/apollo/createGraphQLClientGetter.ts
  package.json
  yarn.lock
Labels: team/frontend-platform, graphql-client/migration

#24845 Improve repositories selector performance through `useConnection` + Apollo
  client/web/src/components/FilteredConnection/ConnectionType.ts
  client/web/src/components/FilteredConnection/hooks/useConnection.ts
  client/web/src/repo/RepoHeader.scss
  client/web/src/repo/RepositoriesPopover.scss
  client/web/src/repo/RepositoriesPopover.tsx
  client/web/src/repo/RepositoriesPopover/RepositoriesPopover.mocks.ts
  client/web/src/repo/RepositoriesPopover/RepositoriesPopover.scss
  client/web/src/repo/RepositoriesPopover/RepositoriesPopover.story.tsx
  client/web/src/repo/RepositoriesPopover/RepositoriesPopover.test.tsx
  client/web/src/repo/RepositoriesPopover/RepositoriesPopover.tsx
  client/web/src/repo/RepositoriesPopover/RepositoryNode.tsx
  client/web/src/repo/RepositoriesPopover/index.ts
  client/web/src/repo/RevisionsPopover/RevisionsPopover.test.tsx
  client/web/src/repo/RevisionsPopover/RevisionsPopoverCommits.tsx
  client/web/src/repo/RevisionsPopover/RevisionsPopoverReferences.tsx
  client/web/src/repo/compare/RepositoryCompareDiffPage.tsx
Labels: team/frontend-platform

#24987 gitserver: Switch to internal actor when fetching remote url
  cmd/gitserver/server/repo_info.go
Labels: team/core-application

#24993 no windows support for batch changes
  doc/batch_changes/references/requirements.md
Labels: team/batchers

#24793 codeintel: Convert recordExpirer janitor job to expiredUploadDeleter
  CHANGELOG.md
  enterprise/cmd/worker/internal/codeintel/janitor/expired_upload_deleter.go
  enterprise/cmd/worker/internal/codeintel/janitor/iface.go
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/record_expirer.go
  enterprise/cmd/worker/internal/codeintel/janitor_config.go
  enterprise/cmd/worker/internal/codeintel/janitor_job.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence, code-intel-data-retention

#24582 repo-updater: Observe total repos synced
  internal/repos/metrics.go
  internal/repos/syncer.go
Labels: team/core-application

#24836 Improve Symbol sidebar performance through `useConnection` + Apollo
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.test.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Labels: team/frontend-platform

#24988 Add warning to start.sh that we're switching to sg
  dev/start.sh
Labels: dx, sg, dx-announce

#24960 Phabricator support clarification
  doc/admin/external_service/phabricator.md
  doc/integration/phabricator.md
Labels: docs

#25028 oobmigrations: Add metadata column
  internal/database/schema.md
  internal/oobmigration/store.go
  internal/oobmigration/store_test.go
  migrations/frontend/1528395889_add_metadata_column_to_oobmigration.down.sql
  migrations/frontend/1528395889_add_metadata_column_to_oobmigration.up.sql
Labels: team/core-application

#25012 New cloud sign-up page redirect to post-sign-up flow
  client/web/src/auth/CloudSignUpPage.story.tsx
  client/web/src/auth/CloudSignUpPage.tsx
Labels: team/core-application

#24979 Add pricing note to topline docs page directly
  doc/code_insights/index.md
Labels: team/code-insights

#25049 Code Insights: Add fix for bad sizing of insights grid layout items
  client/web/src/enterprise/insights/sections/ExtensionViewsDirectorySection.tsx
Labels: bug, team/code-insights

#25005 Code Insights: Fix funky colors of insight data-series
  CHANGELOG.md
  client/extension-api/src/sourcegraph.d.ts
  client/web/src/views/components/content/view-content/chart-view-content/ChartViewContent.story.tsx
  client/web/src/views/components/content/view-content/chart-view-content/charts/line/components/GlyphContent.tsx
  client/web/src/views/components/content/view-content/chart-view-content/charts/line/components/LineChartContent.tsx
  client/web/src/views/components/content/view-content/chart-view-content/charts/line/components/TooltipContent.tsx
  client/web/src/views/components/content/view-content/chart-view-content/charts/line/helpers/get-processed-chart-data.ts
  client/web/src/views/components/content/view-content/chart-view-content/charts/line/types.ts
Labels: team/code-insights

#24970 Code Insights: Add code insights beta modal UI
  client/branded/src/global-styles/colors.scss
  client/web/src/enterprise/insights/InsightsRouter.tsx
  client/web/src/enterprise/insights/modals/BetaConfirmationModal.module.scss
  client/web/src/enterprise/insights/modals/BetaConfirmationModal.story.tsx
  client/web/src/enterprise/insights/modals/BetaConfirmationModal.tsx
  client/web/src/enterprise/insights/modals/components/MediaCharts.module.scss
  client/web/src/enterprise/insights/modals/components/MediaCharts.tsx
  client/web/src/insights/utils/is-code-insights-enabled.ts
  client/web/src/integration/insights/utils/override-insights-graphql.ts
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/search/home/LoggedOutHomepage.module.scss
  client/web/src/settings/temporary/TemporarySettings.ts
  client/web/src/settings/temporary/TemporarySettingsStorage.ts
  client/web/src/settings/temporary/useTemporarySetting.test.tsx
Labels: team/code-insights

#25046 insights: fix bug where historical records are missing persist mode
  enterprise/internal/insights/compression/compression.go
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToQueueJob/test_to_job_with_dependents.golden
  enterprise/internal/insights/compression/testdata/TestQueryExecution_ToQueueJob/test_to_job_without_dependents.golden
Labels: bug, team/code-insights

#25058 codeintel: Never expire upload providing intelligence for tip of default branch
  enterprise/cmd/worker/internal/codeintel/janitor/mock_iface_gitserver_test.go
  enterprise/cmd/worker/internal/codeintel/janitor/policy_matcher.go
  enterprise/cmd/worker/internal/codeintel/janitor/upload_expirer_test.go
Labels: team/code-intelligence, code-intel-data-retention

#25067 Compute GitMaxConcurrentClones and use it everywhere
  cmd/gitserver/server/server.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/repos/scheduler.go
Labels: debt, site-config, refactor

#25044 Code Insights: Add Feedback prompt to the dashboard page
  client/web/src/enterprise/insights/components/context-menu/utils.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-action/DrillDownFiltersPanel.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-action/DrillDownFiltersPanel.tsx
  client/web/src/enterprise/insights/components/popover/Popover.tsx
  client/web/src/enterprise/insights/components/popover/hooks/use-keyboard.ts
  client/web/src/enterprise/insights/components/popover/hooks/use-outside-click.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardPage.module.scss
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
Labels: team/code-insights

#25066 db: Remove repo.cloned column
  CHANGELOG.md
  enterprise/internal/insights/resolvers/insight_connection_resolver_test.go
  internal/database/repos_db_test.go
  internal/database/schema.md
  migrations/frontend/1528395890_drop_repo_cloned.down.sql
  migrations/frontend/1528395890_drop_repo_cloned.up.sql
Labels: team/repo-management

#24806 codeintel: streamline LSIF dependency autoindexing
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/dbstore.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/gen.go
  enterprise/cmd/worker/internal/codeintel/indexing/iface.go
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/mock_worker_store_test.go
  enterprise/cmd/worker/internal/codeintel/indexing_job.go
  enterprise/cmd/worker/internal/codeintel/janitor_job.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/observability.go
  enterprise/internal/codeintel/stores/dbstore/dependency_index.go
  enterprise/internal/codeintel/stores/dbstore/dependency_index_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/worker.go
  internal/database/schema.md
  migrations/frontend/1528395890_lsif_dependency_indexing_queueing.down.sql
  migrations/frontend/1528395890_lsif_dependency_indexing_queueing.up.sql
Labels: team/code-intelligence, dependency-indexing

#24892 cmd/gitserver: Add producer-consumer pipeline to clone repos
  cmd/gitserver/main.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
Labels: refactor, performance

#25032 Post-refresh: Update text-disabled/muted colors for improved contrast
  client/branded/src/global-styles/colors.scss
Labels: team/frontend-platform

#25105 internal/repos: Wrap error from Store.Transact for context
  internal/repos/store.go
Labels: debugging

#24942 batches: add button to automatically exclude repo in batch spec
  client/web/src/enterprise/batches/create/examples/ExampleTabs.tsx
  client/web/src/enterprise/batches/create/yaml-util.test.ts
  client/web/src/enterprise/batches/create/yaml-util.ts
  package.json
Labels: team/batchers, server-side

#25149 web: wait for auth redirects to fix e2e tests
  client/shared/src/testing/driver.ts
  client/web/src/components/HeroPage.tsx
  client/web/src/components/__snapshots__/ErrorBoundary.test.tsx.snap
  client/web/src/end-to-end/end-to-end.test.ts
Labels: e2e-tests, team/frontend-platform

#25121 web: add good-first-issue template
  .github/ISSUE_TEMPLATE/good_first_issue.md
Labels: team/frontend-platform

#25186 fix: search diff background colors
  client/branded/src/global-styles/highlight.scss
Labels: team/frontend-platform, team/search-product

#25190 insights: add panel and warning alert for unutilized queue
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/shared/codeinsights.go
  monitoring/definitions/worker.go
Labels: team/code-insights

#25195 doc/dev: add API docs architecture docs
  doc/dev/background-information/codeintel/apidocs/index.md
  doc/dev/background-information/codeintel/index.md
Labels: api-docs

#25193 codeintel/gitserver: add DefaultBranchContains functionality
  enterprise/internal/codeintel/gitserver/client.go
Labels: api-docs

#25197 doc/dev: document API docs search indexing architecture, tradeoffs, scaling, etc.
  doc/dev/background-information/codeintel/apidocs/index.md
Labels: api-docs

#25181 gitserver: Include route name for gitserver http handlers
  cmd/gitserver/server/server.go
Labels: team/repo-management

#25030 Post-refresh: Update semantic button + disabled/muted text colors
  client/branded/src/global-styles/colors.scss
Labels: team/frontend-platform, design refresh

#25208 Revert "monitoring: remove repo-updater: syncer_synced_repos (#24678)"
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/repo_updater.go
Labels: team/repo-management

#25123 executor: Make executor GCP images public
  enterprise/cmd/executor/release.sh
Labels: team/code-intelligence, auto-index-on-prem

#25222 Wildcard: Migrate stories to CSF
  client/wildcard/src/components/Container/Container.story.tsx
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
  client/wildcard/src/components/PageSelector/PageSelector.story.tsx
Labels: team/frontend-platform
