Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-10, with the labels that each got.

#25590 Add example to templating docs that shows combination of helpers
  doc/batch_changes/references/batch_spec_templating.md
Labels: docs

#25581 batches: Expose ops metrics on service
  doc/admin/observability/dashboards.md
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_apply_batch_change.go
  enterprise/internal/batches/store/store.go
  monitoring/definitions/frontend.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/shared/batches.go
  monitoring/definitions/worker.go
Labels: team/batchers

#25605 allow defaultCommandset to be overridden
  dev/sg/config.go
Labels: sg

#25624 SG: Add a proper secret api that can be reused across commands
  dev/sg/internal/rfc/rfc.go
  dev/sg/internal/secrets/store.go
  dev/sg/internal/secrets/store_test.go
  dev/sg/main.go
Labels: dx, sg

#25634 web: filter out empty-url events
  client/web/src/search/panels/RecentFilesPanel.tsx
  client/web/src/search/panels/RecentSearchesPanel.tsx
  client/web/src/search/panels/RepositoriesPanel.tsx
Labels: bug, team/frontend-platform

#25629 web: disable manual retry for Puppeteer agents
  enterprise/dev/ci/internal/buildkite/buildkite.go
  enterprise/dev/ci/internal/ci/operations.go
Labels: team/frontend-platform, dx, ci

#25572 ssbc: Refactor logs parsing
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_step.go
  enterprise/internal/batches/background/batch_spec_workspace_execution_worker.go
  enterprise/internal/batches/background/batch_spec_workspace_execution_worker_test.go
  enterprise/internal/batches/types/step_info.go
  enterprise/internal/batches/types/step_info_test.go
Labels: team/batchers

#25588 Markdown files: Fix switching between 'code' and 'formatted' views
  client/shared/src/util/url.ts
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/actions/ToggleRenderedFileMode.test.tsx
  client/web/src/repo/blob/actions/ToggleRenderedFileMode.tsx
  client/web/src/repo/blob/actions/utils.ts
Labels: team/frontend-platform

#25607 ci: add documentation regarding secrets management
  enterprise/dev/ci/README.md
Labels: dx, ci, team/dev-experience

#25679 web: stop reporting the `ResizeObserver loop limit exceeded` error to Sentry
  client/web/src/sentry.ts
  client/web/src/util/dom.ts
Labels: team/frontend-platform

#25635 Re-enable gzip compression for local development
  client/web/dev/server/development.server.ts
  client/web/dev/utils/index.ts
  client/web/dev/utils/should-compress-response.ts
  client/web/gulpfile.js
  package.json
  yarn.lock
Labels: team/frontend-platform

#25666 API docs: codeintel: begin indexing API docs for search
  doc/dev/background-information/codeintel/apidocs/index.md
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/stores/lsifstore/data_write_documentation.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  internal/conf/computed.go
  internal/database/schema.codeintel.md
  migrations/codeintel/1000000021_documentation_add_dump_root_column.down.sql
  migrations/codeintel/1000000021_documentation_add_dump_root_column.up.sql
  schema/schema.go
  schema/site.schema.json
Labels: apidocs-search

#25207 API docs: codeintel: add OOB migration to index API docs for search
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/migrations.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/internal/codeintel/stores/lsifstore/migration/apidocs_search.go
  enterprise/internal/codeintel/stores/lsifstore/migration/iface.go
  migrations/frontend/1528395908_oob_apidocs_search_indexing.down.sql
  migrations/frontend/1528395908_oob_apidocs_search_indexing.up.sql
Labels: apidocs, apidocs-search

#25715 backout API docs changes
  doc/dev/background-information/codeintel/apidocs/index.md
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/migrations.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/stores/lsifstore/data_write_documentation.go
  enterprise/internal/codeintel/stores/lsifstore/migration/apidocs_search.go
  enterprise/internal/codeintel/stores/lsifstore/migration/iface.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  internal/conf/computed.go
  internal/database/schema.codeintel.md
  migrations/codeintel/1000000021_documentation_add_dump_root_column.down.sql
  migrations/codeintel/1000000021_documentation_add_dump_root_column.up.sql
  migrations/frontend/1528395908_oob_apidocs_search_indexing.down.sql
  migrations/frontend/1528395908_oob_apidocs_search_indexing.up.sql
  schema/schema.go
  schema/site.schema.json
Labels: apidocs-search

#25718 migrations: add documentation for how to revert DB migrations properly
  migrations/README.md
Labels: apidocs-search

#25717 migrations: undo API docs changes to Sourcegraph.com and k8s.sgdev.org
  migrations/codeintel/1000000021_reverted.down.sql
  migrations/codeintel/1000000021_reverted.up.sql
  migrations/codeintel/1000000022_undo_apidocs_root_column.down.sql
  migrations/codeintel/1000000022_undo_apidocs_root_column.up.sql
  migrations/frontend/1528395908_reverted.down.sql
  migrations/frontend/1528395908_reverted.up.sql
  migrations/frontend/1528395909_undo_apidocs_oob_migration.down.sql
  migrations/frontend/1528395909_undo_apidocs_oob_migration.up.sql
Labels: apidocs-search

#25673 Add basic metrics to user notifications
  client/web/src/nav/StatusMessagesNavItem.tsx
Labels: team/cloud-saas

#25763 API docs: codeintel: add OOB migration to index API docs for search
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/migrations.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/internal/codeintel/stores/lsifstore/migration/apidocs_search.go
  enterprise/internal/codeintel/stores/lsifstore/migration/iface.go
  migrations/frontend/1528395912_apidocs_oob_search_indexing.down.sql
  migrations/frontend/1528395912_apidocs_oob_search_indexing.up.sql
Labels: apidocs-search

#26849 pass database into mustParseGraphQLSchema so it can be mocked
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/git_commit_test.go
  cmd/frontend/graphqlbackend/git_tree_test.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/namespaces_test.go
  cmd/frontend/graphqlbackend/org_test.go
  cmd/frontend/graphqlbackend/orgs_test.go
  cmd/frontend/graphqlbackend/repositories_test.go
  cmd/frontend/graphqlbackend/repository_mirror_test.go
  cmd/frontend/graphqlbackend/repository_test.go
  cmd/frontend/graphqlbackend/saved_searches_test.go
  cmd/frontend/graphqlbackend/set_external_service_repos_test.go
  cmd/frontend/graphqlbackend/settings_mutation_test.go
  cmd/frontend/graphqlbackend/site_admin_test.go
  cmd/frontend/graphqlbackend/status_messages_test.go
  cmd/frontend/graphqlbackend/temporary_settings_test.go
  cmd/frontend/graphqlbackend/testing.go
  cmd/frontend/graphqlbackend/user_emails_test.go
  cmd/frontend/graphqlbackend/user_test.go
  cmd/frontend/graphqlbackend/user_usage_stats_test.go
  cmd/frontend/graphqlbackend/users_create_test.go
  cmd/frontend/graphqlbackend/users_test.go
Labels: dx, cla-signed

#26739 codeintel: Improve github auth responses
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github_test.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/gen.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/iface.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/mock_iface_test.go
Labels: team/code-intelligence, cla-signed

#26851 remove global TemporarySettingsStore mocks
  cmd/frontend/graphqlbackend/temporary_settings.go
  cmd/frontend/graphqlbackend/temporary_settings_test.go
  cmd/frontend/graphqlbackend/testing.go
  internal/database/database.go
  internal/database/mockstores.go
  internal/database/temporary_settings.go
  internal/database/temporary_settings_mock.go
  internal/database/temporary_settings_test.go
Labels: dx, cla-signed

#26813 compute: add regexp substitution to output command
  internal/compute/output_command.go
  internal/compute/output_command_test.go
Labels: cla-signed

#26759 batches: implement fuzzier version of the webhook banner backend
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/internal/cli/serve_cmd.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec.go
  enterprise/cmd/frontend/internal/batches/resolvers/code_host.go
  enterprise/cmd/frontend/internal/batches/webhooks/gitlab_test.go
  enterprise/internal/batches/store/codehost.go
  enterprise/internal/batches/store/codehost_test.go
  enterprise/internal/batches/testing/repos.go
  enterprise/internal/batches/types/code_host.go
  internal/database/dbutil/dbutil.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
  internal/database/schema.md
  internal/types/types.go
  migrations/frontend/1528395923_add_has_webhooks.down.sql
  migrations/frontend/1528395923_add_has_webhooks.up.sql
Labels: cla-signed

#26827 compute: add regexp output command
  internal/compute/query.go
Labels: cla-signed

#26761 Revert "Revert "ci: add an final step that upload build logs" (#26748)"
  dev/sg/internal/bk/bk.go
  dev/sg/sg_ci.go
  enterprise/dev/ci/gen-pipeline.go
  enterprise/dev/ci/internal/buildkite/buildkite.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
  enterprise/dev/upload-build-logs.sh
Labels: cla-signed

#26607 enhancement: add reset command to sg that removes key value pairs from secrets
  dev/sg/internal/secrets/store.go
  dev/sg/main.go
  dev/sg/sg_secret.go
  doc/dev/background-information/sg/index.md
Labels: cla-signed

#26862 enhancement: add reset command to sg that removes key value pairs from secrets (#26607)
  dev/sg/internal/secrets/store.go
  dev/sg/main.go
  dev/sg/sg_secret.go
  doc/dev/background-information/sg/index.md
Labels: cla-signed
