Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-07, with the labels that each got.

#22486 API docs: various fixups
  client/web/src/repo/docs/DocumentationIcon.scss
  client/web/src/repo/docs/DocumentationIcon.tsx
  client/web/src/repo/docs/DocumentationIcons.tsx
  client/web/src/repo/docs/DocumentationIndexNode.tsx
  client/web/src/repo/docs/DocumentationNode.tsx
  client/web/src/repo/docs/RepositoryDocumentationPage.scss
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  client/web/src/repo/docs/RepositoryDocumentationSidebar.scss
  client/web/src/repo/docs/RepositoryDocumentationSidebar.tsx
  client/web/src/repo/docs/graphql.ts
  client/web/src/repo/routes.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/util/settings.ts
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_documentation.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  enterprise/internal/insights/store/store_test.go
  schema/settings.schema.json
Labels: api-docs, api-docs-public-blocker

#22461 monitoring: At 10 minute duration check for repo-updater mem
  doc/admin/observability/alert_solutions.md
  monitoring/definitions/repo_updater.go
Labels: team/core-application

#22493 monitoring: Improve gitserver janitor panel
  monitoring/definitions/git_server.go
Labels: team/core-application

#22473 Inline issue URLs in tracking issues instead of titles
  internal/cmd/tracking-issue/render.go
  internal/cmd/tracking-issue/testdata/issue-13675.md
  internal/cmd/tracking-issue/testdata/issue-13987.md
  internal/cmd/tracking-issue/testdata/issue-13988.md
  internal/cmd/tracking-issue/testdata/issue-14166.md
  internal/cmd/tracking-issue/testdata/last-update.txt
Labels: dx, ops & tools & dev

#22508 repos: Remove cloud param from FetchStatusMessages
  cmd/frontend/graphqlbackend/status_messages.go
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
Labels: team/core-application

#22395 web: integrate `DllPlugin` in Storybook development build
  .gitignore
  client/storybook/README.md
  client/storybook/package.json
  client/storybook/src/dllPlugin/ensureDllBundleIsReady.ts
  client/storybook/src/dllPlugin/getVendorModules.ts
  client/storybook/src/dllPlugin/getWebpackStats.ts
  client/storybook/src/dllPlugin/index.ts
  client/storybook/src/environment-config.ts
  client/storybook/src/main.ts
  client/storybook/src/webpack.config.common.ts
  client/storybook/src/webpack.config.dll.ts
  package.json
  yarn.lock
Labels: dx, team/frontend-platform, web build perf

#22515 GraphQL Client: Fix Apollo request headers
  client/web/src/backend/graphql.ts
Labels: team/frontend-platform

#22519 repo-updater: Reduce allocations caused by scheduler syncing
  cmd/repo-updater/shared/main.go
  internal/repos/scheduler.go
  internal/repos/scheduler_test.go
Labels: team/core-application

#22522 migrations: Add settings_user_id_idx
  internal/database/schema.md
  migrations/frontend/1528395842_add_settings_user_id_index.down.sql
  migrations/frontend/1528395842_add_settings_user_id_index.up.sql
Labels: team/search-core

#22523 dbconn: Better SQL pool stats
  enterprise/cmd/executor-queue/main.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  go.mod
  go.sum
  internal/database/dbconn/dbconn.go
  internal/database/dbconn/dbconn_test.go
  internal/database/dbtest/dbtest.go
  internal/database/schemadoc/main.go
Labels: team/search-core

#22423 Add Code Insights Dashboard page UI
  client/web/src/insights/core/types/dashboard.ts
  client/web/src/insights/pages/dashboards/DashboardsPage.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/DashboardSelect.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/DashboardSelect.story.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/DashboardSelect.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/badge/Badge.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/menu-button/MenuButton.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/menu-button/MenuButton.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/select-option/SelectOption.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/select-option/SelectOption.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/trancated-text/TrancatedText.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/trancated-text/TruncatedText.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/helpers/get-dashboard-title.ts
  client/web/src/insights/pages/dashboards/hooks/use-dashboards/use-dashboard.test.ts
  client/web/src/insights/pages/dashboards/hooks/use-dashboards/use-dashboards.ts
  package.json
  yarn.lock
Labels: code-insights-dashboard, team/code-insights

#22527 insights: aggregate insight data over 26 weeks instead of 6 months
  CHANGELOG.md
  enterprise/internal/insights/store/store.go
  enterprise/internal/insights/store/store_test.go
Labels: team/code-insights

#22545 Repo sidebar: fix missing right margin on symbol panel
  client/web/src/repo/RepoRevisionSidebar.tsx
Labels: team/frontend-platform

#22554 insights: refactor insight setting loader out of telemetry package
  internal/insights/insights.go
  internal/insights/insights_test.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: team/code-insights

#22570 monitoring: Database connections monitoring
  CHANGELOG.md
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  cmd/worker/shared/db.go
  doc/admin/observability/dashboards.md
  enterprise/cmd/executor-queue/main.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/dbtesting/insights.go
  enterprise/internal/insights/insights.go
  internal/database/basestore/handle.go
  internal/database/basestore/store.go
  internal/database/dbconn/dbconn.go
  internal/database/dbconn/dbconn_test.go
  internal/database/dbconn/metrics.go
  internal/database/dbtesting/dbtesting.go
  internal/insights/insights_test.go
  monitoring/definitions/executor_queue.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/precise_code_intel_worker.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/shared/dbconns.go
  monitoring/definitions/worker.go
  sg.config.yaml
Labels: team/search-core

#22579 Implement BatchSpecExecution resolver and mutation
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/graphqlbackend/node.go
  enterprise/internal/batches/resolvers/apitest/types.go
  enterprise/internal/batches/resolvers/batch_spec_execution.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/store/batch_spec_execution_test.go
  enterprise/internal/batches/store/integration_test.go
Labels: team/batchers

#22590 auth: Fix comment quoting
  enterprise/cmd/frontend/internal/auth/githuboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go
Labels: team/core-application

#22565 Code Insights: Remove views area page
  CHANGELOG.md
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/components/index.ts
  client/web/src/insights/components/insight-view-content/InsightViewContent.scss
  client/web/src/insights/components/insight-view-content/InsightViewContent.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/ChartViewContent.scss
  client/web/src/insights/components/insight-view-content/chart-view-content/ChartViewContent.story.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/ChartViewContent.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/annotation/Label.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/annotation/Text.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/MaybeLink.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/bar/BarChart.scss
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/bar/BarChart.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/LineChart.scss
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/LineChart.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/components/GlyphContent.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/components/LineChartContent.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/components/NonActiveBackground.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/components/TickComponent.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/components/TooltipContent.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/constants.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/helpers/generate-accessors.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/helpers/get-min-max.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/helpers/get-range-with-padding.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/helpers/use-event-emitters.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/helpers/use-scales.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/line/types.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/pie/PieChart.scss
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/pie/PieChart.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/pie/components/PieArc.tsx
  client/web/src/insights/components/insight-view-content/chart-view-content/charts/pie/distribute-pie-data.ts
  client/web/src/insights/components/insight-view-content/chart-view-content/utils/get-insight-type-by-view-id.ts
  client/web/src/insights/components/insights-nav-link/InsightsNavLink.tsx
  client/web/src/insights/components/insights-view-grid/InsightsViewGrid.scss
  client/web/src/insights/components/insights-view-grid/InsightsViewGrid.tsx
  client/web/src/insights/components/insights-view-grid/components/insight-card/InsightCard.module.scss
  client/web/src/insights/components/insights-view-grid/components/insight-card/InsightContentCard.tsx
  client/web/src/insights/components/insights-view-grid/components/insight-card/components/insight-card-description/InsightCardDescription.module.scss
  client/web/src/insights/components/insights-view-grid/components/insight-card/components/insight-card-description/InsightCardDescription.tsx
  client/web/src/insights/components/insights-view-grid/components/insight-card/components/insight-card-menu/InsightCardMenu.module.scss
  client/web/src/insights/components/insights-view-grid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/components/live-preview-container/LivePreviewContainer.tsx
  client/web/src/insights/core/backend/api/get-search-insight-content/get-search-insight-content.ts
  client/web/src/insights/pages/creation/intro/IntroCreationPage.tsx
  client/web/src/insights/pages/dashboards/DashboardsPage.tsx
  client/web/src/insights/pages/insights/InsightsPage.scss
  client/web/src/insights/pages/insights/InsightsPage.tsx
  client/web/src/nav/MenuNavItem.story.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/repo/tree/TreePage.scss
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/routes.tsx
  client/web/src/views/QueryInputInViewContent.tsx
  client/web/src/views/ViewPage.test.tsx
  client/web/src/views/ViewPage.tsx
  client/web/src/views/ViewsArea.tsx
  client/web/src/views/__snapshots__/ViewPage.test.tsx.snap
Labels: code-insights-dashboard, debt, team/code-insights

#22584 Add experimentalFeature flag for server side batch changes
  client/web/src/enterprise/batches/create/CreateBatchChangePage.story.tsx
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: team/batchers

#22474 Add URL management to Code Insights dashboard page
  client/shared/src/api/extension/api/getInsightsViews.ts
  client/web/src/insights/core/settings-action/insights.ts
  client/web/src/insights/core/types/dashboard.ts
  client/web/src/insights/core/types/dashboard/core.ts
  client/web/src/insights/core/types/dashboard/index.ts
  client/web/src/insights/core/types/dashboard/real-dashboard.ts
  client/web/src/insights/core/types/dashboard/virtual-dashboard.ts
  client/web/src/insights/pages/dashboards/DashboardsPage.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/DashboardSelect.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/DashboardSelect.story.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/DashboardSelect.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/badge/Badge.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/badge/Badge.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/menu-button/MenuButton.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/select-option/SelectOption.module.scss
  client/web/src/insights/pages/dashboards/components/dashboard-select/components/select-option/SelectOption.tsx
  client/web/src/insights/pages/dashboards/components/dashboard-select/helpers/get-dashboard-title.ts
  client/web/src/insights/pages/dashboards/components/dashboards-content/DashboardsContent.module.scss
  client/web/src/insights/pages/dashboards/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/hooks/use-dashboards/use-dashboard.test.ts
  client/web/src/insights/pages/dashboards/hooks/use-dashboards/use-dashboards.ts
  client/web/src/insights/pages/edit/EditInsightPage.tsx
  client/web/src/insights/pages/insights/hooks/use-delete-insight.ts
  schema/schema.go
  schema/settings.schema.json
Labels: code-insights-dashboard, team/code-insights

#22583 perforce: Test sample 'protects -a' output
  internal/authz/perforce/perforce.go
  internal/authz/perforce/perforce_test.go
  internal/authz/perforce/testdata/sample-protects.txt
Labels: team/core-application

#22608 Use consistent spelling of “syncing” (not “synching”)
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
  doc/admin/external_service/github.md
Labels: team/frontend-platform

#22602 monitoring: Record db conn wait duration in histogram
  doc/admin/observability/dashboards.md
  internal/database/dbconn/metrics.go
  monitoring/definitions/shared/dbconns.go
Labels: team/search-core

#22547 Implement close bulk operation for changesets
  CHANGELOG.md
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/detail/bulk-operations/BulkOperationNode.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
  client/web/src/enterprise/batches/detail/changesets/CloseChangesetsModal.story.tsx
  client/web/src/enterprise/batches/detail/changesets/CloseChangesetsModal.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  doc/batch_changes/how-tos/bulk_operations_on_changesets.md
  enterprise/internal/batches/background/bulk_processor.go
  enterprise/internal/batches/background/bulk_processor_test.go
  enterprise/internal/batches/resolvers/bulk_operation.go
  enterprise/internal/batches/resolvers/changeset_connection.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/batches/store/changesets_test.go
  enterprise/internal/batches/types/changeset_job.go
Labels: team/batchers

#22588 search-blitz: retry trace fetching
  internal/cmd/search-blitz/main.go
  internal/cmd/search-blitz/trace.go
Labels: team/search-core

#22613 users: Disallow new users with existing verified email
  internal/database/users.go
  internal/database/users_builtin_auth_test.go
Labels: team/core-application

#22599 Implement very simple first version of create batch spec execution page
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/create/backend.ts
  schema/batch_spec.schema.json
Labels: team/batchers

#22600 web: add `location.search` to the new tab URL
  client/branded/src/components/panel/Panel.tsx
Labels: bug, team/frontend-platform

#22616 web: add unit test to cover `Panel` location change
  client/branded/src/components/panel/Panel.fixtures.ts
  client/branded/src/components/panel/Panel.story.tsx
  client/branded/src/components/panel/Panel.test.tsx
  client/shared/src/testing/render-with-router.tsx
Labels: team/frontend-platform

#22622 monitoring: Fix dbconn wait monitoring
  doc/admin/observability/dashboards.md
  internal/database/dbconn/metrics.go
  monitoring/definitions/shared/dbconns.go
Labels: monitoring-for-all

#22561 flake: disable `TestMaxMatches` test
  cmd/searcher/search/search_regex_test.go
Labels: flake, testing

#22471 Insights/repo permissions
  CHANGELOG.md
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/resolvers/insight_connection_resolver_test.go
  enterprise/internal/insights/resolvers/insight_series_resolver_test.go
  enterprise/internal/insights/resolvers/resolver.go
  enterprise/internal/insights/store/permissions.go
  enterprise/internal/insights/store/store.go
  enterprise/internal/insights/store/store_test.go
Labels: team/code-insights

#22617 Add and expose namespace and initiator on batch spec execution
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/executor-queue/internal/queues/batches/transform.go
  enterprise/cmd/executor-queue/internal/queues/batches/transform_test.go
  enterprise/internal/batches/background/executor_store_test.go
  enterprise/internal/batches/resolvers/apitest/types.go
  enterprise/internal/batches/resolvers/batch_spec_execution.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/store/batch_spec_execution.go
  enterprise/internal/batches/store/batch_spec_execution_test.go
  enterprise/internal/batches/types/batch_spec_execution.go
  internal/database/schema.md
  migrations/frontend/1528395845_batch_spec_execution_namespace.down.sql
  migrations/frontend/1528395845_batch_spec_execution_namespace.up.sql
Labels: server-side, team/batchers

#21971 add coursier to gitserver, repo-updater & combined Dockerfiles (RFC 307)
  cmd/gitserver/Dockerfile
  cmd/repo-updater/Dockerfile
  cmd/server/Dockerfile
  third-party-licenses/ThirdPartyDistributedTools.csv
Labels: RFC-307, team/code-intelligence

#22642 database: Add ~175k repos to the indexed corpus
  internal/database/repos.go
Labels: team/search-core

#22620 Add Code Insights edit dashboard UI
  client/web/src/components/LoaderButton.tsx
  client/web/src/insights/core/settings-action/dashboards.ts
  client/web/src/insights/core/settings-action/utils.ts
  client/web/src/insights/core/types/dashboard/index.ts
  client/web/src/insights/core/types/dashboard/real-dashboard.ts
  client/web/src/insights/pages/dashboards/DasbhoardsRoutes.tsx
  client/web/src/insights/pages/dashboards/creation/InsightsDashboardCreationPage.tsx
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/InsightsDashboardCreationContent.tsx
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/hooks/useDashboardNameValidator.ts
  client/web/src/insights/pages/dashboards/creation/hooks/use-dashboard-settings.ts
  client/web/src/insights/pages/dashboards/creation/utils/dashboard-sanitizer.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboards/use-dashboards.ts
  client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboards/utils.ts
  client/web/src/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/insights/pages/dashboards/edit-dashboard/hooks/use-update-dashboard.ts
  client/web/src/insights/pages/insights/edit-insight/EditInsightPage.tsx
Labels: code-insights-dashboard, team/code-insights

#22172 codeintel: Protect indexes serving intel for branch and tag tips from eviction
  enterprise/cmd/worker/internal/codeintel/commitgraph/iface.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph_config.go
  enterprise/cmd/worker/internal/codeintel/commitgraph_job.go
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  enterprise/internal/codeintel/stores/dbstore/helpers_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  enterprise/internal/codeintel/stores/dbstore/xrepo.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_test.go
  internal/database/schema.md
  migrations/frontend/1528395845_expand_visible_lsif_uploads.down.sql
  migrations/frontend/1528395845_expand_visible_lsif_uploads.up.sql
  migrations/frontend/1528395846_codeintel_eviction_ages.down.sql
  migrations/frontend/1528395846_codeintel_eviction_ages.up.sql
Labels: team/code-intelligence

#22648 chore: Standardize error unwrapping
  enterprise/cmd/executor/internal/worker/handler.go
  enterprise/cmd/executor/internal/worker/worker.go
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
  enterprise/cmd/worker/internal/codeintel/janitor/unknown_commits.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/internal/codeintel/gitserver/observability.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
  internal/extsvc/bitbucketserver/client.go
  internal/goroutine/periodic.go
  internal/workerutil/dbworker/resetter.go
  internal/workerutil/worker.go
Labels: dx

#20768 Fixing broken markdown rendering on settings doc
  doc/admin/config/settings.md
Labels: docs

#22637 dx: enable `problems` auto-fix mode for VS Code ESLint extension
  .vscode/settings.json
Labels: dx, team/frontend-platform

#22639 Implement first basic version of batch spec execution UI
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/create/backend.ts
  client/web/src/enterprise/batches/execution/BatchSpecExecutionDetailsPage.tsx
  client/web/src/enterprise/batches/execution/backend.ts
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/executor-queue/internal/queues/batches/transform.go
  enterprise/internal/batches/resolvers/apitest/types.go
  enterprise/internal/batches/resolvers/batch_spec_execution.go
  enterprise/internal/batches/resolvers/resolver_test.go
Labels: team/batchers

#22672 RepositoryDiffPage: prevent scroll bar from appearing over content
  client/web/src/repo/commit/RepositoryCommitPage.tsx
Labels: team/frontend-platform

#22679 chore: Fix error checking in codeintel source
  enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
  enterprise/cmd/worker/internal/codeintel/janitor/unknown_commits.go
  enterprise/cmd/worker/internal/codeintel/janitor/unknown_commits_test.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/observability.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at_test.go
  internal/gitserver/errors.go
  internal/vcs/errors.go
Labels: dx, team/code-intelligence

#22627 GraphQL Client: Continue advice on using or bypassing Apollo's cache
  doc/dev/background-information/web/graphql.md
Labels: dx, team/frontend-platform

#22644 fix(diff ui): large lines visualization
  client/web/src/components/diff/DiffHunk.tsx
  client/web/src/components/diff/FileDiffHunks.scss
  client/web/src/components/diff/Lines.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
Labels: merge-on-any-approve

#22646 Insights: id filter argument in GraphQL API
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/discovery/discovery_test.go
  enterprise/internal/insights/discovery/series_id.go
  enterprise/internal/insights/resolvers/insight_connection_resolver.go
  enterprise/internal/insights/resolvers/insight_connection_resolver_test.go
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_series_resolver_test.go
  enterprise/internal/insights/resolvers/resolver.go
  enterprise/internal/insights/resolvers/resolver_test.go
  internal/insights/insights.go
Labels: team/code-insights

#21893 extensibility: update registry extension sorting parameters
  client/web/src/extensions/ExtensionRegistry.tsx
  client/web/src/integration/extension-registry.test.ts
  cmd/frontend/registry/api/extension_connection_graphql.go
Labels: merge-on-any-approve

#22698 dx: Fix test cockroachdb/errors
  cmd/frontend/backend/repos_vcs_test.go
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/git_commit_test.go
  cmd/frontend/graphqlbackend/git_tree_test.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/namespaces_test.go
  cmd/frontend/graphqlbackend/org_test.go
  cmd/frontend/graphqlbackend/orgs_test.go
  cmd/frontend/graphqlbackend/repositories_test.go
  cmd/frontend/graphqlbackend/repository_mirror_test.go
  cmd/frontend/graphqlbackend/repository_test.go
  cmd/frontend/graphqlbackend/set_external_service_repos_test.go
  cmd/frontend/graphqlbackend/settings_mutation_test.go
  cmd/frontend/graphqlbackend/site_admin_test.go
  cmd/frontend/graphqlbackend/status_messages_test.go
  cmd/frontend/graphqlbackend/testing.go
  cmd/frontend/graphqlbackend/user_emails_test.go
  cmd/frontend/graphqlbackend/user_test.go
  cmd/frontend/graphqlbackend/user_usage_stats_test.go
  cmd/frontend/graphqlbackend/users_create_test.go
  cmd/frontend/graphqlbackend/users_test.go
  internal/sysreq/sysreq.go
  internal/sysreq/sysreq_test.go
Labels: dx, dx-announce

#22695 Insights: filter insights based on graphQL arguments
  dev/global-settings.json
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/discovery/discovery_test.go
  enterprise/internal/insights/resolvers/insight_connection_resolver.go
  schema/schema.go
  schema/settings.schema.json
Labels: code-insights-dashboard, team/code-insights

#22682 cookie: Introduce new package to remove duplicated code
  cmd/frontend/internal/app/sign_out.go
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/auth/userpasswd/handlers.go
  cmd/frontend/internal/httpapi/graphql.go
  enterprise/cmd/frontend/internal/auth/oauth/session.go
  internal/cookie/cookie.go
  internal/featureflag/middleware.go
Labels: team/core-application

#22673 Fix #22672: Scroll parent of RepositoryCommitPage
  client/web/src/repo/commit/RepositoryCommitPage.scss
Labels: team/frontend-platform

#22686 security: Log user deletion events
  internal/database/security_event_logs.go
  internal/database/users.go
Labels: team/core-application

#22718 database: Drop unused default_repos table
  cmd/frontend/backend/repos.go
  cmd/repo-updater/shared/main.go
  enterprise/internal/insights/discovery/all_repos_iterator.go
  internal/database/dbcache/cached_indexable_repos.go
  internal/database/dbcache/cached_indexable_repos_test.go
  internal/database/repos.go
  internal/database/schema.md
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  migrations/frontend/1528395848_drop_default_repos.down.sql
  migrations/frontend/1528395848_drop_default_repos.up.sql
  migrations/frontend/1528395849_drop_unused_indexes.down.sql
  migrations/frontend/1528395849_drop_unused_indexes.up.sql
Labels: team/search-core

#22670 web: switch from `crypto` to `SubtleCrypto`
  client/shared/dev/jest-environment.js
  client/shared/src/api/extension/activation.ts
  client/shared/src/util/hashCode.test.ts
  client/shared/src/util/hashCode.ts
  package.json
  yarn.lock
Labels: dx, team/frontend-platform

#22685 security: Log AccountCreated event
  internal/database/external_accounts.go
  internal/database/security_event_logs.go
  internal/database/users.go
Labels: team/core-application

#22716 security: Log EmailVerified event
  cmd/frontend/internal/app/app.go
  cmd/frontend/internal/app/verify_email.go
  internal/database/security_event_logs.go
Labels: team/core-application

#22729 security: Add password related logging
  cmd/frontend/graphqlbackend/users_create.go
  cmd/frontend/internal/app/app.go
  cmd/frontend/internal/auth/userpasswd/reset_password.go
  cmd/frontend/internal/auth/userpasswd/reset_password_test.go
  internal/cookie/cookie.go
  internal/database/security_event_logs.go
  internal/database/users.go
Labels: team/core-application

#22706 Insights: integrate backend insights with compatible extensions insights
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer_test.go
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/discovery/discovery_test.go
  enterprise/internal/insights/resolvers/insight_connection_resolver.go
  internal/insights/gen.go
  internal/insights/insights.go
  internal/insights/insights_test.go
  internal/insights/mock_loader.go
Labels: team/code-insights

#22703 batches: refactor `DiffStat` API to support independent composition of stats + squares
  client/web/src/components/diff/DiffStat.scss
  client/web/src/components/diff/DiffStat.story.tsx
  client/web/src/components/diff/DiffStat.test.tsx
  client/web/src/components/diff/DiffStat.tsx
  client/web/src/components/diff/FileDiffNode.scss
  client/web/src/components/diff/FileDiffNode.tsx
  client/web/src/components/diff/__snapshots__/DiffStat.test.tsx.snap
  client/web/src/enterprise/batches/close/ExternalChangesetCloseNode.tsx
  client/web/src/enterprise/batches/detail/BatchChangeStatsCard.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewStatsBar.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
Labels: team/batchers

#22767 web-build: add dev-server metatags
  client/web/dev/webpack/get-html-webpack-plugins.ts
Labels: dx, team/frontend-platform, web server

#22733 dx: Add docs on error handling in Go
  .golangci.yml
  doc/dev/background-information/index.md
  doc/dev/background-information/languages/go.md
  doc/dev/background-information/languages/go_errors.md
Labels: dx, dx-announce

#22680 codeintel: Do not return deleted repos to index from dbstore
  enterprise/internal/codeintel/stores/dbstore/index_configuration.go
  enterprise/internal/codeintel/stores/dbstore/index_configuration_test.go
Labels: team/code-intelligence

#22701 database/locker: Actually unlock advisory locks
  internal/database/locker/locker.go
  internal/database/locker/locker_test.go
Labels: team/code-intelligence

#22756 repos: streaming syncer
  CHANGELOG.md
  cmd/repo-updater/shared/main.go
  dev/sg/README.md
  internal/api/api.go
  internal/database/dbtest/dbtest.go
  internal/database/repos.go
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/integration_test.go
  internal/repos/observability.go
  internal/repos/status_messages_test.go
  internal/repos/store.go
  internal/repos/store_test.go
  internal/repos/sync_worker_test.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
  internal/repos/testdata/golden/GithubSource_makeRepo_path-pattern
  internal/repos/testdata/golden/GithubSource_makeRepo_simple
  internal/repos/testdata/golden/GithubSource_makeRepo_ssh
  internal/types/testing.go
  internal/types/types.go
  sg.config.yaml
Labels: team/core-application, team/search-core

#22748 Code Insights: Add assign to dashboard functionality
  client/shared/src/settings/settings.ts
  client/shared/src/util/jsonc.test.ts
  client/web/src/insights/components/form/form-input/FormInput.module.scss
  client/web/src/insights/components/form/form-input/FormInput.tsx
  client/web/src/insights/components/form/form-input/types.ts
  client/web/src/insights/components/form/hooks/useCheckboxes.ts
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
  client/web/src/insights/core/analytics.ts
  client/web/src/insights/core/settings-action/dashboards.ts
  client/web/src/insights/core/types/dashboard/index.ts
  client/web/src/insights/core/types/dashboard/real-dashboard.ts
  client/web/src/insights/core/types/insight.ts
  client/web/src/insights/core/types/subjects.ts
  client/web/src/insights/hooks/use-dashboards/use-dashboard.test.ts
  client/web/src/insights/hooks/use-dashboards/use-dashboards.ts
  client/web/src/insights/hooks/use-dashboards/utils.ts
  client/web/src/insights/hooks/use-insight-dashboard.ts
  client/web/src/insights/hooks/use-insight-subjects/use-insight-subjects.ts
  client/web/src/insights/hooks/use-insight/use-insight.ts
  client/web/src/insights/mocks/settings-cascade.ts
  client/web/src/insights/pages/dashboards/DasbhoardsRoutes.tsx
  client/web/src/insights/pages/dashboards/creation/InsightsDashboardCreationPage.story.tsx
  client/web/src/insights/pages/dashboards/creation/InsightsDashboardCreationPage.tsx
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/InsightsDashboardCreationContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/DashboardsPage.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.story.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/components/add-insight-modal-content/AddInsightModalContent.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/components/add-insight-modal-content/AddInsightModalContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/hooks/use-reachable-insights.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/components/menu-button/MenuButton.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/components/trancated-text/TruncatedText.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/insights/pages/insights/creation/CreationRoutes.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/insights/creation/search-insight/utils/use-initial-values.ts
  client/web/src/insights/pages/insights/edit-insight/EditInsightPage.tsx
  client/web/src/insights/pages/insights/edit-insight/components/EditLangStatsInsight.tsx
  client/web/src/insights/pages/insights/edit-insight/components/EditSearchInsight.tsx
  client/web/src/insights/pages/insights/edit-insight/hooks/use-handle-submit.ts
  client/web/src/insights/pages/insights/edit-insight/hooks/utils.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
Labels: code-insights-dashboard, team/code-insights

#22792 auth: Remove unnecessary log
  cmd/frontend/internal/auth/userpasswd/handlers.go
Labels: team/core-application

#22795 sg: Make `sg start` boot up enterprise environment
  sg.config.yaml
Labels: dx, dx-announce, sg

#22770 fix double border when panel is open
  client/web/src/repo/RepoRevisionContainer.scss
Labels: team/frontend-platform

#22768 fix navbar right side button on small screens
  client/wildcard/src/components/NavBar/NavAction.module.scss
  client/wildcard/src/components/NavBar/NavBar.module.scss
Labels: team/frontend-platform

#22762 security: Log SecurityBypassGranted/Denied events
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/insights/store/permissions.go
  internal/database/repos.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  internal/database/search_contexts.go
  internal/database/security_event_logs.go
Labels: team/core-application

#22802 Revert "security: Log SecurityBypassGranted/Denied events (#22762)"
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/insights/store/permissions.go
  internal/database/repos.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  internal/database/search_contexts.go
  internal/database/security_event_logs.go
Labels: team/core-application

#22806 go.mod: update after new x/tools release
  go.mod
  go.sum
Labels: ci, debt, dependencies, go

#22808 dbtest: remove statement_timeout
  internal/database/dbtest/dbtest.go
Labels: ci

#22769 Code Insights: Add global (site) scope for the dashboards and insights
  client/web/src/insights/components/form/form-radio-input/FormRadioInput.tsx
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
  client/web/src/insights/core/types/dashboard/core.ts
  client/web/src/insights/core/types/dashboard/index.ts
  client/web/src/insights/core/types/dashboard/real-dashboard.ts
  client/web/src/insights/core/types/subjects.ts
  client/web/src/insights/hooks/use-dashboards/utils.ts
  client/web/src/insights/mocks/settings-cascade.ts
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/InsightsDashboardCreationContent.tsx
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/utils/get-global-subject-tooltip-text.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/helpers/get-dashboard-title.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/insights/pages/dashboards/edit-dashboard/hooks/use-update-dashboard.ts
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/insights/edit-insight/EditInsightPage.tsx
  client/web/src/insights/pages/insights/edit-insight/hooks/utils.ts
Labels: code-insights-dashboard, team/code-insights

#22800 Code insights: add dashboard delete modal
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/utils/is-dashboard-configurable.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/delete-dashboard-modal/DeleteDashboardModal.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/delete-dashboard-modal/DeleteDashobardModal.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/delete-dashboard-modal/hooks/use-delete-dashboard-handler.ts
Labels: code-insights-dashboard, team/code-insights

#22840 security: Log SecurityBypassGranted
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/insights/store/permissions.go
  internal/database/repos.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  internal/database/search_contexts.go
  internal/database/security_event_logs.go
Labels: team/core-application

#20936 workerutil: Remove long-running transactions
  doc/dev/background-information/workers.md
  enterprise/cmd/executor-queue/internal/queues/codeintel/queue.go
  enterprise/cmd/executor-queue/internal/server/handler.go
  enterprise/cmd/executor-queue/internal/server/handler_test.go
  enterprise/cmd/executor-queue/internal/server/lifecycle.go
  enterprise/cmd/executor-queue/internal/server/lifecycle_test.go
  enterprise/cmd/executor/internal/worker/handler.go
  enterprise/cmd/executor/internal/worker/handler_test.go
  enterprise/cmd/executor/internal/worker/mock_store_test.go
  enterprise/cmd/executor/internal/worker/store.go
  enterprise/cmd/executor/internal/worker/worker.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_worker_store_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/worker.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler_test.go
  enterprise/internal/batches/background/bulk_processor.go
  enterprise/internal/batches/background/bulk_processor_worker.go
  enterprise/internal/batches/background/executor_store.go
  enterprise/internal/batches/background/reconciler_worker.go
  enterprise/internal/batches/reconciler/reconciler.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_apply_batch_change.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/batches/store/changesets_test.go
  enterprise/internal/batches/syncer/syncer.go
  enterprise/internal/batches/syncer/syncer_test.go
  enterprise/internal/batches/testing/changeset.go
  enterprise/internal/batches/webhooks/webhooks.go
  enterprise/internal/codeintel/stores/dbstore/worker.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/store.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/worker.go
  internal/database/schema.md
  internal/repos/sync_worker.go
  internal/repos/sync_worker_test.go
  internal/repos/syncer.go
  internal/workerutil/dbworker/handler.go
  internal/workerutil/dbworker/handler_shim.go
  internal/workerutil/dbworker/store/helpers_test.go
  internal/workerutil/dbworker/store/mocks/mock_store.go
  internal/workerutil/dbworker/store/store.go
  internal/workerutil/dbworker/store/store_test.go
  internal/workerutil/dbworker/store_shim.go
  internal/workerutil/dbworker/worker.go
  internal/workerutil/handler.go
  internal/workerutil/mock_handler_test.go
  internal/workerutil/mock_store_test.go
  internal/workerutil/store.go
  internal/workerutil/worker.go
  internal/workerutil/worker_test.go
  migrations/frontend/1528395851_workerutil_last_updated_at.down.sql
  migrations/frontend/1528395851_workerutil_last_updated_at.up.sql
Labels: team/code-intelligence

#22835 Code insights: Dashboard product clean up
  CHANGELOG.md
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/components/form/form-group/FormGroup.tsx
  client/web/src/insights/components/form/form-radio-input/FormRadioInput.tsx
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
  client/web/src/insights/pages/dashboards/creation/InsightsDashboardCreationPage.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/components/add-insight-modal-content/AddInsightModalContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/hooks/use-copy-url-handler.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/hooks/use-dashboard-select-handler.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/utils/find-dashboard-by-url-id.ts
  client/web/src/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.module.scss
  client/web/src/insights/pages/insights/edit-insight/hooks/use-handle-submit.ts
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/repo/docs/DocumentationNode.tsx
Labels: code-insights-dashboard, team/code-insights

#21703 Add new "JVM Packages" external services type.
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
  client/web/src/enterprise/batches/settings/CodeHostSshPublicKey.tsx
  client/web/src/site-admin/SiteAdminReportBugPage.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/gitserver/main.go
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_jvm_packages_test.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/shared/main.go
  internal/conf/reposource/jvm_packages.go
  internal/conf/reposource/jvm_packages_test.go
  internal/database/external_services.go
  internal/database/repos.go
  internal/extsvc/codehost.go
  internal/extsvc/jvmpackages/coursier/coursier.go
  internal/extsvc/jvmpackages/repos.go
  internal/extsvc/types.go
  internal/repos/clone_url.go
  internal/repos/jvm_packages.go
  internal/repos/sources.go
  internal/types/secret.go
  schema/jvm-packages.schema.json
  schema/schema.go
  schema/site.schema.json
  schema/stringdata.go
Labels: dependency-indexing, team/code-intelligence

#22875 database: A few small perm store nits
  enterprise/internal/database/perms_store.go
Labels: team/core-application

#22851 Code insights: Add BE insight creation UI
  CHANGELOG.md
  client/shared/src/settings/settings.ts
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useInsightTitleValidator.ts
  client/web/src/insights/core/settings-action/insights.ts
  client/web/src/insights/core/types/insight.ts
  client/web/src/insights/hooks/use-insight/use-insight.ts
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/InsightsDashboardCreationContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/components/add-insight-modal-content/AddInsightModalContent.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/insights/creation/lang-stats/utils/insight-sanitizer.ts
  client/web/src/insights/pages/insights/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/hooks/use-insight-creation-form/use-insight-creation-form.ts
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/initial-insight-values.ts
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/insights/creation/search-insight/types.ts
  client/web/src/insights/pages/insights/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/insights/pages/insights/edit-insight/EditInsightPage.tsx
  client/web/src/insights/pages/insights/edit-insight/components/EditSearchInsight.tsx
  cmd/frontend/graphqlbackend/settings_cascade.go
Labels: code-insights-dashboard, team/code-insights

#22877 security: Include signout error if available
  cmd/frontend/internal/app/sign_out.go
Labels: team/core-application

#22868 Code insights: Integrate BE (all repos mode) insight with FE insights dashboards
  client/web/src/insights/components/insights-view-grid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/core/backend/api/get-combined-views.ts
  client/web/src/insights/core/backend/requests/fetch-backend-insights.ts
  client/web/src/insights/core/types/dashboard/virtual-dashboard.ts
  client/web/src/insights/hooks/use-dashboards/use-dashboard.test.ts
  client/web/src/insights/hooks/use-dashboards/use-dashboards.ts
  client/web/src/insights/hooks/use-dashboards/utils.ts
  client/web/src/insights/hooks/use-insight/use-insight.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/add-insight-modal/hooks/use-reachable-insights.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/insights/insights-page/hooks/use-delete-insight.ts
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/utils/insight-mock-data.ts
Labels: code-insights-dashboard, team/code-insights

#22744 batches: add queries for batch changes on a repo
  CHANGELOG.md
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/graphqlbackend/repository.go
  enterprise/internal/batches/resolvers/changeset_connection.go
  enterprise/internal/batches/resolvers/changesets_stats.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/batch_changes_test.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/batches/store/changesets_test.go
  enterprise/internal/batches/types/changeset.go
Labels: team/batchers

#22895 API docs: LSIF: conversion: refactor documentation grouping return type
  lib/codeintel/lsif/conversion/group.go
  lib/codeintel/lsif/conversion/group_documentation.go
Labels: api-docs

#22893 API docs: LSIF: fix nil pointer deref in DocumentationPathInfo requests
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_documentation.go
Labels: api-docs

#22897 API docs: LSIF: use a queue for documentation grouping channels
  lib/codeintel/lsif/conversion/group_documentation.go
Labels: api-docs

#22896 API docs: LSIF: use ResultSetData instead of separate field for documentation-by-result-set-ID
  lib/codeintel/lsif/conversion/correlate_documentation.go
  lib/codeintel/lsif/conversion/correlate_test.go
  lib/codeintel/lsif/conversion/state.go
  lib/codeintel/lsif/conversion/types.go
Labels: api-docs

#22886 Code insights: Implement delete insights with new dashboard functionality
  client/web/src/insights/core/settings-action/edits/apply-edit-operations.ts
  client/web/src/insights/core/settings-action/edits/edits.ts
  client/web/src/insights/core/settings-action/edits/index.ts
  client/web/src/insights/hooks/use-persist-edit-operations.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/insights/edit-insight/components/EditLangStatsInsight.tsx
  client/web/src/insights/pages/insights/edit-insight/components/EditSearchInsight.tsx
  client/web/src/insights/pages/insights/edit-insight/hooks/use-handle-submit.ts
  client/web/src/insights/pages/insights/edit-insight/hooks/utils.ts
  client/web/src/insights/pages/insights/insights-page/hooks/delete-helpers.ts
  client/web/src/insights/pages/insights/insights-page/hooks/use-delete-insight.ts
Labels: code-insights-dashboard, team/code-insights

#22932 codeintel: Order all bulk modifications to code intelligence tables
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/janitor.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/xrepo.go
  enterprise/internal/codeintel/stores/lsifstore/clear.go
Labels: team/code-intelligence

#22930 codeintel: Consider dependency graph for LSIF data retention
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/janitor.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  enterprise/internal/codeintel/stores/dbstore/xrepo.go
  enterprise/internal/codeintel/stores/lsifstore/clear.go
  internal/database/schema.md
  migrations/frontend/1528395852_lsif_add_covering_index.down.sql
  migrations/frontend/1528395852_lsif_add_covering_index.up.sql
Labels: dependency-indexing, team/code-intelligence

#22157 web: move typography and button styles out from the `.theme-redesign`
  client/branded/src/global-styles/buttons-redesign.scss
  client/branded/src/global-styles/buttons.scss
  client/branded/src/global-styles/forms.scss
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/typography-redesign.scss
  client/branded/src/global-styles/typography.scss
  client/web/src/search/results/ButtonDropdownCta.module.scss
  client/web/src/search/results/ButtonDropdownCta.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
Labels: design refresh, team/frontend-platform

#22580 Attempt #3: upgrade to `Webpack` v5
  client/browser/config/webpack/base.config.ts
  client/browser/config/webpack/development.config.ts
  client/browser/config/webpack/production.config.ts
  client/browser/scripts/build.ts
  client/browser/scripts/development.ts
  client/browser/scripts/tasks.ts
  client/shared/src/hover/HoverOverlay.tsx
  client/shared/src/testing/driver.ts
  client/storybook/src/dllPlugin/getVendorModules.ts
  client/storybook/src/dllPlugin/getWebpackStats.ts
  client/storybook/src/main.ts
  client/storybook/src/webpack.config.common.ts
  client/storybook/src/webpack.config.dll.ts
  client/web/dev/server/development.server.ts
  client/web/dev/webpack/get-html-webpack-plugins.ts
  client/web/gulpfile.js
  client/web/src/OpenSourceWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/auth/withAuthenticatedUser.tsx
  client/web/src/enterprise/EnterpriseWebApp.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/main.tsx
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/app.html
  package.json
  ui/assets/manifest.go
  yarn.lock
Labels: dx, dx-announce, team/frontend-platform, web build perf

#22953 web: change `Breader` font weight
  client/wildcard/src/components/PageHeader/PageHeader.module.scss
Labels: design refresh, team/frontend-platform

#22954 web: change code monitoring form label margins
  client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.tsx
  client/web/src/enterprise/code-monitoring/components/FormActionArea.tsx
  client/web/src/enterprise/code-monitoring/components/__snapshots__/FormActionArea.test.tsx.snap
Labels: design refresh, team/frontend-platform

#22960 Code Insights: Fix the "loading Sourcegraph extensions" loading message for the dashboard page
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
Labels: team/code-insights

#22962 Tweak global settings error message
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/utils/get-global-subject-tooltip-text.ts
Labels: team/code-insights

#22913 Add new type of dashboard initial state for the built in and settings based dashboards
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
Labels: code-insights-dashboard, team/code-insights

#22924 codeintel: temporarily use sourcegraph-shipped coursier musl binary
  cmd/gitserver/Dockerfile
  cmd/repo-updater/Dockerfile
  cmd/server/Dockerfile
Labels: dependency-indexing, team/code-intelligence

#22923 Second attempt to PR "Add new "JVM Packages" external services type. (#21703)"
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
  client/web/src/enterprise/batches/settings/CodeHostSshPublicKey.tsx
  client/web/src/site-admin/SiteAdminReportBugPage.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/gitserver/main.go
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_jvm_packages_test.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/shared/main.go
  internal/conf/reposource/jvm_packages.go
  internal/conf/reposource/jvm_packages_test.go
  internal/database/external_services.go
  internal/database/repos.go
  internal/extsvc/codehost.go
  internal/extsvc/jvmpackages/coursier/coursier.go
  internal/extsvc/jvmpackages/repos.go
  internal/extsvc/types.go
  internal/repos/clone_url.go
  internal/repos/jvm_packages.go
  internal/repos/sources.go
  internal/types/secret.go
  schema/jvm-packages.schema.json
  schema/schema.go
  schema/site.schema.json
  schema/stringdata.go
Labels: dependency-indexing, team/code-intelligence

#22964 Code Insights: Add feature flag the all repos insight mode
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/insights/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/utils/get-experimental-features.ts
  schema/schema.go
  schema/settings.schema.json
Labels: team/code-insights

#22968 Bump src cli version and update cli docs
  doc/cli/references/batch/apply.md
  doc/cli/references/batch/preview.md
  doc/cli/references/lsif/upload.md
  doc/cli/references/repos/disable.md
  doc/cli/references/repos/enable.md
  doc/cli/references/repos/index.md
  internal/src-cli/consts.go
Labels: team/batchers

#22969 web: load runtime bundle in locally executed integration tests
  client/web/src/integration/context.ts
  client/web/src/integration/environment.ts
  client/web/webpack.config.js
Labels: dx, team/frontend-platform, testing

#22967 Code Insights: Fix BE insight loading card flashing
  client/web/src/insights/core/backend/api/get-backend-insights.ts
  client/web/src/insights/core/backend/api/get-combined-views.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/utils/get-backend-insight-ids.ts
Labels: code-insights-dashboard, team/code-insights

#22927 sg: Add `sg rfc [list|search|open]` commands
  .gitignore
  dev/sg/README.md
  dev/sg/go.mod
  dev/sg/go.sum
  dev/sg/internal/db/db.go
  dev/sg/internal/migration/migration.go
  dev/sg/main.go
  dev/sg/rfc.go
Labels: dx, dx-announce, sg

#22737 codeintel: Do not delete reachable uploads
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.story.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelUploadsPage.story.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelUploadsPage.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateDescription.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateIcon.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateLabel.tsx
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/dumps_test.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/janitor.go
  enterprise/internal/codeintel/stores/dbstore/janitor_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  internal/database/schema.md
  migrations/frontend/1528395853_add_deleting_state.down.sql
  migrations/frontend/1528395853_add_deleting_state.up.sql
Labels: team/code-intelligence

#22903 API docs: LSIF: add GraphQL backend for "Go to code" / "Usage examples"
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_definitions.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/observability.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query.go
  enterprise/internal/codeintel/stores/lsifstore/documentation.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
Labels: api-docs

#22987 Remove the code insights page
  client/web/src/SourcegraphWebApp.scss
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/index.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/hooks/delete-helpers.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/hooks/use-delete-insight.ts
  client/web/src/insights/pages/insights/insights-page/InsightsPage.scss
  client/web/src/insights/pages/insights/insights-page/InsightsPage.tsx
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/insights-visual.test.ts
Labels: code-insights-dashboard, team/code-insights

#23005 Change "add" to "add/remove" so you know how to remove insights
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
Labels: team/code-insights

#22989 Code Insights: Turn off the homepage insight by default
  client/web/src/search/input/SearchPage.tsx
Labels: team/code-insights

#23017 Code Insights: Fix insight dashboard memoization and add extension insight batching
  client/shared/src/api/extension/api/getInsightsViews.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/hooks/use-backend-insight-ids.ts
Labels: code-insights-dashboard, team/code-insights

#23019 sg: remove `ulimit -n` from cmds, set on boot in `sg`
  dev/sg/main.go
  sg.config.yaml
Labels: dx, sg

#22874 Use correct Java version for JVM dependency repos.
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_jvm_packages_test.go
  internal/extsvc/jvmpackages/coursier/coursier.go
Labels: dependency-indexing, team/code-intelligence

#22804 batches: add filtered repo batch changes page and badge on repo page
  CHANGELOG.md
  client/web/src/batches/RepoBatchChangesButton.story.tsx
  client/web/src/batches/RepoBatchChangesButton.tsx
  client/web/src/batches/backend.ts
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetNode.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/list/BatchChangesListEmpty.tsx
  client/web/src/enterprise/batches/list/NewBatchChangeButton.tsx
  client/web/src/enterprise/batches/repo/BatchChangeNode.module.scss
  client/web/src/enterprise/batches/repo/BatchChangeNode.tsx
  client/web/src/enterprise/batches/repo/BatchChangeRepoPage.story.tsx
  client/web/src/enterprise/batches/repo/BatchChangeRepoPage.tsx
  client/web/src/enterprise/batches/repo/RepoBatchChanges.module.scss
  client/web/src/enterprise/batches/repo/RepoBatchChanges.tsx
  client/web/src/enterprise/batches/repo/RepositoryBatchChangesArea.tsx
  client/web/src/enterprise/batches/repo/backend.ts
  client/web/src/enterprise/batches/repo/testData.ts
  client/web/src/enterprise/repo/routes.tsx
  client/web/src/integration/graphQlResponseHelpers.ts
  client/web/src/integration/repository.test.ts
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/tree/TreePage.scss
  client/web/src/repo/tree/TreePage.tsx
  cmd/frontend/internal/app/ui/router.go
Labels: team/batchers

#22971 Update in-app changelog for 3.30
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
Labels: team/batchers

#22970 Code Insights: Add explanation tooltip on the creation insight form.
  CHANGELOG.md
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
  client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/utils/get-global-subject-tooltip-text.ts
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
Labels: code-insights-dashboard, team/code-insights

#23024 repos: Don't panic if we find unknown external service kind
  internal/repos/sources.go
Labels: team/core-application

#23022 Code Insights: Add uniqBy check for the be insight gql handler
  client/web/src/insights/core/backend/requests/fetch-backend-insights.ts
Labels: code-insights-dashboard, team/code-insights

#22859 github: automatic repositoryQuery refinement
  CHANGELOG.md
  internal/extsvc/github/testdata/golden/SearchRepos-huge-query
  internal/extsvc/github/testdata/golden/SearchRepos-narrow-query
  internal/extsvc/github/testdata/vcr/SearchRepos.yaml
  internal/extsvc/github/v4.go
  internal/extsvc/github/v4_test.go
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/testdata/golden/TestRepositoryQuery_Do/doesnt-exceed-limit
  internal/repos/testdata/golden/TestRepositoryQuery_Do/exceeds-limit
  internal/repos/testdata/sources/GITHUB/excluded-repos-are-never-yielded.yaml
  internal/repos/testdata/vcr/TestRepositoryQuery_Do/doesnt-exceed-limit.yaml
  internal/repos/testdata/vcr/TestRepositoryQuery_Do/exceeds-limit.yaml
  internal/testutil/golden.go
Labels: team/search-core

#22902 API docs: LSIF: add GraphQL backend for "Go to API docs"
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_definitions.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/ranges.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/observability.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_ranges.go
  enterprise/internal/codeintel/stores/lsifstore/documentation.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  enterprise/internal/codeintel/stores/lsifstore/ranges.go
  enterprise/internal/codeintel/stores/lsifstore/serializer_test.go
  enterprise/internal/codeintel/stores/lsifstore/types.go
  lib/codeintel/lsif/conversion/canonicalize.go
  lib/codeintel/lsif/conversion/canonicalize_test.go
  lib/codeintel/lsif/conversion/group.go
  lib/codeintel/lsif/conversion/types.go
  lib/codeintel/semantic/types.go
Labels: api-docs

#23048 extensibility: only show firefox bext alert on firefox
  client/web/src/repo/RepoContainer.tsx
Labels: merge-on-any-approve

#23047 flake: disable Puppeteer Search Feature Tour test
  client/web/src/integration/search.test.ts
Labels: flake, testing

#23004 Docs for code insights dashboards in 3.30
  doc/code_insights/explanations/index.md
  doc/code_insights/explanations/viewing_code_insights.md
  doc/code_insights/how-tos/creating_a_custom_dashboard_of_code_insights.md
  doc/code_insights/how-tos/index.md
  doc/code_insights/index.md
  doc/code_insights/language_insight_quickstart.md
  doc/code_insights/quickstart.md
Labels: team/code-insights

#22509 GraphQL Client: Generate types for Apollo `typePolicies`
  client/shared/dev/generateGraphQlOperations.js
  client/shared/src/graphql/cache.ts
  client/shared/src/graphql/graphql.ts
  client/web/src/user/settings/cloud-ga.ts
  package.json
  yarn.lock
Labels: team/frontend-platform

#22721 GraphQL Client: Update GraphQL error types
  client/browser/src/shared/repo/backend.tsx
  client/extension-api/package.json
  client/extension-api/src/sourcegraph.d.ts
  client/shared/src/graphql/graphql.ts
  client/shared/src/testing/integration/context.ts
  client/shared/src/util/errors.ts
Labels: team/frontend-platform

#23066 Code Insights: Remove `nav-link` class to keep search insight-button padding consistent
  client/web/src/search/results/components/CreateCodeInsightButton.tsx
Labels: bug, team/code-insights

#23018 authz: Sync user permissions based on external service tokens
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/authz/authz_test.go
  internal/authz/bitbucketserver/provider.go
  internal/authz/github/github.go
  internal/authz/gitlab/oauth.go
  internal/authz/gitlab/sudo.go
  internal/authz/iface.go
  internal/authz/perforce/perforce.go
  internal/database/repos_perm_test.go
Labels: team/core-application

#23076 Implement auto-inference for Java package repositories.
  lib/codeintel/autoindex/inference/java.go
  lib/codeintel/autoindex/inference/java_test.go
  lib/codeintel/autoindex/inference/recognizers.go
Labels: dependency-indexing, team/code-intelligence

#23074 Add JDK sources to "JVM Dependencies" external service type.
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/repo-updater/repoupdater/server.go
  internal/conf/reposource/jvm_packages.go
  internal/extsvc/jvmpackages/coursier/coursier.go
  internal/extsvc/types.go
Labels: dependency-indexing, team/code-intelligence

#23073 extsvc: Add helper to extract token
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  internal/extsvc/types.go
  internal/extsvc/types_test.go
Labels: team/core-application

#23020 sg: add ability to define `checks` per `commandset`
  dev/sg/config.go
  dev/sg/config_test.go
  dev/sg/main.go
  dev/sg/run.go
  dev/sg/sg.config.example.yaml
  sg.config.yaml
Labels: dx, dx-announce, sg

#22972 Move heartbeats from executor-queue to executor
  enterprise/cmd/executor-queue/internal/queues/codeintel/queue.go
  enterprise/cmd/executor-queue/internal/server/handler.go
  enterprise/cmd/executor-queue/internal/server/handler_test.go
  enterprise/cmd/executor-queue/internal/server/lifecycle.go
  enterprise/cmd/executor-queue/internal/server/lifecycle_test.go
  enterprise/cmd/executor-queue/internal/server/server.go
  enterprise/cmd/executor/internal/worker/mock_store_test.go
  enterprise/cmd/executor/internal/worker/store.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_worker_store_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/worker.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
  enterprise/internal/batches/background/bulk_processor_worker.go
  enterprise/internal/batches/background/executor_store.go
  enterprise/internal/batches/background/reconciler_worker.go
  enterprise/internal/codeintel/stores/dbstore/worker.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/insights/background/queryrunner/worker.go
  internal/repos/sync_worker.go
  internal/workerutil/dbworker/store/helpers_test.go
  internal/workerutil/dbworker/store/mocks/mock_store.go
  internal/workerutil/dbworker/store/store.go
  internal/workerutil/dbworker/store/store_test.go
  internal/workerutil/dbworker/store_shim.go
  internal/workerutil/mock_store_test.go
  internal/workerutil/store.go
  internal/workerutil/worker.go
  internal/workerutil/worker_test.go
Labels: team/batchers

#23051 flake: disable Quicklinks regression test
  client/web/src/regression/core.test.ts
Labels: flake, testing

#23083 auth: Redirect github oauth login attempt back if user cancels
  enterprise/cmd/frontend/internal/auth/githuboauth/provider.go
  enterprise/cmd/frontend/internal/auth/oauth/session.go
Labels: team/core-application

#23044 Restrict importing from `enterprise` in OSS codebase
  .eslintrc.js
  yarn.lock
Labels: dx

#23050 Insights: migrate code insights from repo-updater to worker service
  CHANGELOG.md
  doc/dev/background-information/insights/backend.md
  enterprise/cmd/repo-updater/main.go
  enterprise/cmd/worker/internal/insights/job.go
  enterprise/cmd/worker/main.go
  enterprise/internal/insights/background/background.go
  internal/goroutine/periodic.go
Labels: dx, team/code-insights

#23119 search: Index 1M repos on dotcom
  internal/database/repos.go
  internal/database/repos_test.go
Labels: team/search-core

#23120 monitoring: Tweak oldest sync alert
  internal/repos/metrics.go
Labels: team/core-application

#23123 Follow up on post-merge code style review
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  internal/extsvc/jvmpackages/coursier/coursier.go
Labels: dependency-indexing, team/code-intelligence

#23131 httpcli: add retries to NewExternalHTTPClientFactory
  go.mod
  go.sum
  internal/httpcli/client.go
  internal/httpcli/client_test.go
Labels: team/search-core

#23099 flake: disable Symbols sidebar regression test
  client/web/src/regression/codeintel.test.ts
Labels: flake, testing

#23115 API docs: LSIF: add references/definitions to tree API, not just blob API
  CHANGELOG.md
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_definitions.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/internal/codeintel/stores/lsifstore/data_write_documentation.go
  enterprise/internal/codeintel/stores/lsifstore/documentation.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  internal/database/schema.codeintel.md
  lib/codeintel/lsif/conversion/group_documentation.go
  lib/codeintel/semantic/types.go
  migrations/codeintel/1000000019_documentation_path_mapping.down.sql
  migrations/codeintel/1000000019_documentation_path_mapping.up.sql
Labels: api-docs

#23052 batches: don't show batch changes on sourcegraph.com
  client/web/src/Layout.tsx
  client/web/src/OpenSourceWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/batches/index.ts
  client/web/src/enterprise/EnterpriseWebApp.tsx
  client/web/src/enterprise/namespaces/navitems.ts
  client/web/src/enterprise/organizations/routes.tsx
  client/web/src/enterprise/repo/routes.tsx
  client/web/src/enterprise/routes.tsx
  client/web/src/enterprise/site-admin/routes.ts
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/enterprise/user/routes.tsx
  client/web/src/enterprise/user/settings/routes.tsx
  client/web/src/enterprise/user/settings/sidebaritems.ts
  client/web/src/namespaces/NamespaceArea.tsx
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/NavLinks.test.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/org/OrgsArea.tsx
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/area/OrgHeader.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/repogroups/RepogroupPage.story.tsx
  client/web/src/routes.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
  client/web/src/user/area/UserArea.tsx
  client/web/src/user/area/UserAreaHeader.tsx
  client/web/src/user/settings/UserSettingsSidebar.tsx
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/internal/batches/resolvers/errors.go
  enterprise/internal/batches/resolvers/resolver.go
Labels: team/batchers

#23101 insights: introduced query cost and priority to distribute resources across multiple insights
  CHANGELOG.md
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer_test.go
  enterprise/internal/insights/background/queryrunner/worker.go
  internal/database/schema.md
  internal/insights/priority/cost.go
  internal/insights/priority/priority.go
  internal/insights/priority/priority_test.go
  migrations/frontend/1528395854_add_priority_insights_queryrunner.down.sql
  migrations/frontend/1528395854_add_priority_insights_queryrunner.up.sql
Labels: backend, team/code-insights

#23148 docs: fix typo, bullet formatting on pings doc
  doc/dev/background-information/adding_ping_data.md
Labels: docs

#23124 Guard against a nil pointer dereference
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
Labels: dependency-indexing, team/code-intelligence

#22722 GraphQL Client: Add `useConnection` hook to replace `<FilteredConnection />`
  client/shared/src/testing/apollo.ts
  client/web/src/components/FilteredConnection/ConnectionNodes.tsx
  client/web/src/components/FilteredConnection/ConnectionType.ts
  client/web/src/components/FilteredConnection/FilteredConnection.tsx
  client/web/src/components/FilteredConnection/constants.ts
  client/web/src/components/FilteredConnection/hooks/useConnection.test.tsx
  client/web/src/components/FilteredConnection/hooks/useConnection.ts
  client/web/src/components/FilteredConnection/hooks/useConnectionUrl.ts
  client/web/src/components/FilteredConnection/utils.ts
  client/wildcard/src/hooks/index.ts
  client/wildcard/src/hooks/useSearchParameters.ts
Labels: team/frontend-platform

#23079 Use custom postion calculator for the dashboard page contex-menu popover
  client/web/src/insights/components/context-menu/utils.ts
  client/web/src/insights/components/insights-view-grid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.module.scss
  client/web/src/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
Labels: insights-dashboards-v2, team/code-insights

#23164 security: Instrument access granted for private repos
  internal/database/dbconn/dbconn.go
  internal/database/repos.go
  internal/database/security_event_logs.go
Labels: team/core-application

#23169 repos: Publish Diff after committing transaction
  internal/repos/syncer.go
Labels: 3.30.1
