Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-01, with the labels that each got.

#16907 frontend: Instrument our internal http handlers
  cmd/frontend/internal/cli/http.go
Labels: team/cloud

#16905 db: Return stale default repos and update in background
  internal/db/default_repos.go
Labels: team/cloud

#17041 gitserver: Fix typo
  cmd/gitserver/README.md
Labels: team/cloud

#17042 apiworker: Set -e to trace docker command script execution
  enterprise/internal/apiworker/handler.go
Labels: team/code-intelligence

#17049 executor: Return exit code and nil-error on command failure
  enterprise/internal/apiworker/command/run.go
Labels: team/code-intelligence

#17052 executor: Temporarily increase observability with log messages
  enterprise/internal/apiworker/command/firecracker.go
  enterprise/internal/apiworker/command/run.go
  enterprise/internal/apiworker/handler.go
Labels: team/code-intelligence

#17056 executor: Temporarily increase observability with log messages
  enterprise/internal/apiworker/command/firecracker.go
  enterprise/internal/apiworker/command/run.go
  enterprise/internal/apiworker/handler.go
Labels: team/code-intelligence

#17058 executor: Write scripts into workspace instead of another temporary directory
  enterprise/internal/apiworker/command/docker.go
  enterprise/internal/apiworker/command/docker_test.go
  enterprise/internal/apiworker/command/firecracker.go
  enterprise/internal/apiworker/command/firecracker_test.go
  enterprise/internal/apiworker/handler.go
  enterprise/internal/apiworker/handler_test.go
  enterprise/internal/apiworker/workspace.go
Labels: team/code-intelligence

#17037 gitserver: Remove deprecated code
  cmd/gitserver/server/list.go
Labels: team/cloud

#17075 monitoring: fire an alert when there is any permission syncing error
  monitoring/definitions/repo_updater.go
Labels: team/cloud

#17100 Fix import of storybook hook in react component
  client/web/src/enterprise/user/settings/UserEventLogsPage.tsx
Labels: bug

#16465 Adding kind to external link
  CHANGELOG.md
  client/web/src/integration/graphQlResponseHelpers.ts
  client/web/src/integration/repository.test.ts
  client/web/src/repo/actions/GoToCodeHostAction.story.tsx
  client/web/src/repo/actions/GoToCodeHostAction.tsx
  client/web/src/repo/actions/InstallBrowserExtensionAlert.story.tsx
  client/web/src/repo/actions/InstallBrowserExtensionAlert.test.tsx
  client/web/src/repo/actions/InstallBrowserExtensionAlert.tsx
  client/web/src/repo/actions/InstallBrowserExtensionPopover.tsx
  client/web/src/repo/actions/__snapshots__/InstallBrowserExtensionAlert.test.tsx.snap
  client/web/src/repo/backend.ts
  cmd/frontend/graphqlbackend/externallink/repository.go
  cmd/frontend/graphqlbackend/externallink/repository_test.go
  cmd/frontend/graphqlbackend/externallink/resolver.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_test.go
  enterprise/internal/campaigns/resolvers/apitest/types.go
  enterprise/internal/campaigns/resolvers/changeset_test.go
  internal/gqltestutil/repository.go
Labels: team/cloud

#17025 repo-updater: Don't lock external_services table while sourcing
  cmd/repo-updater/repoupdater/server_test.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: team/cloud

#16746 Cloud/UI tokens page
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/externalServices/ExternalServicePage.story.tsx
  client/web/src/components/externalServices/ExternalServicesPage.story.tsx
  client/web/src/components/externalServices/backend.ts
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/user/settings/UserAddCodeHostsPageContainer.tsx
  client/web/src/user/settings/UserAddExternalServicesPage.tsx
  client/web/src/user/settings/codeHosts/AddCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/RemoveCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/UpdateCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/codeHosts/modalHints.tsx
  client/web/src/user/settings/routes.tsx
  client/web/src/user/settings/sidebaritems.ts
Labels: team/cloud

#16979 doc: describe the new volume mount mode
  doc/campaigns/explanations/how_src_executes_a_campaign_spec.md
  doc/campaigns/references/requirements.md
Labels: docs, planned/CampaignsSprint7, team/campaigns

#17104 db: Only allow single user owned external service per kind
  internal/db/external_services.go
  internal/db/external_services_test.go
Labels: team/cloud

#17127 graphql: Add RepoCount to ExternalServices
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/db/external_services.go
  internal/db/external_services_test.go
Labels: team/cloud

#17160 basestore: Use Exec and add ExecResult
  internal/db/basestore/store.go
Labels: team/cloud

#17095 repo-updater: Ensure default repos stay cloned
  cmd/repo-updater/shared/main.go
  internal/db/default_repos.go
  internal/db/default_repos_test.go
  internal/db/repos.go
  internal/gitserver/client.go
  internal/repos/scheduler.go
  internal/repos/scheduler_test.go
Labels: team/cloud

#16846 Use ReposourceCloneURLToRepoName in editor endpoint
  CHANGELOG.md
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/git_tree_entry_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/internal/app/editor.go
  cmd/frontend/internal/app/editor_test.go
  internal/cloneurls/clone_urls.go
  internal/cloneurls/clone_urls_test.go
Labels: hack time, team/web

#17145 Fixes LoaderInput class, email validation errors are visible now
  client/web/src/user/settings/emails/AddUserEmailForm.tsx
Labels: bug

#17131 monitoring(postgres): fix panels, adjust transaction alerts
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/postgres.go
Labels: team/distribution

#17175 codeintel: Fix LSIF uploads going to GCS that were broken into > 32 parts
  enterprise/internal/codeintel/stores/uploadstore/gcs_api.go
Labels: team/code-intelligence

#17182 autoindexing: Limit number of jobs automatically enqueued per commit
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer_test.go
  enterprise/internal/codeintel/autoindex/inference/go.go
  enterprise/internal/codeintel/autoindex/inference/go_test.go
  enterprise/internal/codeintel/autoindex/inference/paths.go
  enterprise/internal/codeintel/autoindex/inference/typescript.go
  enterprise/internal/codeintel/autoindex/inference/typescript_test.go
Labels: team/code-intelligence

#17193 db: List default repos in batches
  cmd/repo-updater/shared/main.go
  internal/db/default_repos.go
  internal/db/default_repos_test.go
  internal/db/repos.go
Labels: team/cloud

#17034 prometheus: alert dashboard links with fixed timestamps
  CHANGELOG.md
  docker-images/prometheus/cmd/prom-wrapper/receivers.go
Labels: team/distribution

#17132 Small design adjustments and fixes for jumping content
  client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.scss
  client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.tsx
  client/web/src/enterprise/code-monitoring/components/DeleteMonitorModal.tsx
  client/web/src/enterprise/code-monitoring/components/FormActionArea.tsx
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
  client/web/src/enterprise/code-monitoring/components/__snapshots__/FormTriggerArea.test.tsx.snap
Labels: bug, design-qa, team/search

#17199 repo-updater: Fix nil connection panic
  cmd/repo-updater/shared/main.go
Labels: team/cloud

#17178 Fix filter selection in FilteredConnection
  client/web/src/components/FilteredConnection.tsx
Labels: bug

#17169 Don't display publish notice on empty campaigns
  client/web/src/enterprise/campaigns/detail/UnpublishedNotice.tsx
Labels: bug, team/campaigns

#17165 Introduce detach operation to reconciler
  client/web/src/enterprise/campaigns/preview/list/PreviewAction.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/reconciler/executor.go
  enterprise/internal/campaigns/reconciler/executor_test.go
  enterprise/internal/campaigns/reconciler/plan.go
  enterprise/internal/campaigns/reconciler/plan_test.go
  enterprise/internal/campaigns/reconciler/reconciler_test.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_test.go
  enterprise/internal/campaigns/resolvers/changeset_counts_test.go
  enterprise/internal/campaigns/resolvers/main_test.go
  enterprise/internal/campaigns/resolvers/permissions_test.go
  enterprise/internal/campaigns/rewirer/rewirer.go
  enterprise/internal/campaigns/service/service_apply_campaign_test.go
  enterprise/internal/campaigns/service/service_test.go
  enterprise/internal/campaigns/store/campaigns_test.go
  enterprise/internal/campaigns/store/changesets.go
  enterprise/internal/campaigns/store/changesets_test.go
  enterprise/internal/campaigns/testing/changeset.go
  enterprise/internal/campaigns/webhooks/webhooks_test.go
  internal/campaigns/changeset.go
  internal/campaigns/changeset_test.go
  internal/campaigns/reconciler.go
Labels: team/campaigns

#17168 Add stats resolver for preview API
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/apitest/types.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection_test.go
Labels: team/campaigns

#17185 Adds CircleDashedIcon to shared components
  client/web/src/components/CircleDashedIcon.tsx
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
Labels: estimate/0.5d, team/cloud

#17179 Fixes links between repos and code hosts pages, minor routing cleanup.
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
  client/web/src/user/settings/routes.tsx
Labels: team/cloud

#17123 Make configuration a proper heading
  doc/admin/install/kubernetes/index.md
Labels: docs, docs-ux

#17195 repo-updater: Handle GitHub account suspension
  enterprise/cmd/repo-updater/authz/perms_syncer.go
  internal/errcode/code.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: team/cloud

#17190 Add unique keys to repo page links
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: debt, team/cloud

#17209 codeintel: Add a feature flag for auto indexing
  client/web/src/enterprise/repo/settings/routes.tsx
  client/web/src/enterprise/repo/settings/sidebaritems.ts
  client/web/src/enterprise/site-admin/routes.ts
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/index_scheduler.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/index_scheduler_test.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/indexability_updater.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/indexability_updater_test.go
  enterprise/cmd/frontend/internal/codeintel/config.go
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver_test.go
  enterprise/dev/start.sh
  internal/conf/computed.go
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: team/code-intelligence

#17215 Introduce current state column
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.scss
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewList.scss
  client/web/src/enterprise/campaigns/preview/list/PreviewListHeader.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.scss
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/backend.ts
Labels: team/campaigns

#17272 repo-updater: Fix state page
  cmd/repo-updater/shared/assets/bindata.go
  cmd/repo-updater/shared/assets/state.html.tmpl
  internal/repos/scheduler.go
Labels: team/cloud

#17269 monitoring: Increase alert time range
  doc/admin/observability/alert_solutions.md
  monitoring/definitions/repo_updater.go
Labels: team/cloud

#17262 db: Convert db/users to basestore
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/set_external_service_repos_test.go
  cmd/frontend/graphqlbackend/settings_mutation_test.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users_test.go
  internal/db/external_accounts.go
  internal/db/globalstatedb/globalstatedb.go
  internal/db/org_members.go
  internal/db/stores.go
  internal/db/user_tags.go
  internal/db/users.go
  internal/db/users_builtin_auth.go
Labels: team/cloud

#17275 db: Combine files that deal with db.UserStore
  internal/db/user_tags.go
  internal/db/user_tags_test.go
  internal/db/users.go
  internal/db/users_builtin_auth.go
  internal/db/users_mock.go
  internal/db/users_test.go
Labels: team/cloud

#17248 Show all reconciler operations in actions column
  client/web/src/enterprise/campaigns/preview/CampaignPreviewPage.story.tsx
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.scss
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewAction.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewActions.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewListHeader.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.scss
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
Labels: team/campaigns

#17274 Add cost-saving help for k8s resource estimator
  doc/admin/install/resource_estimator.md
Labels: team/distribution

#17287 Implement base ref changed indicator in preview UI
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/backend.ts
  client/web/src/integration/campaigns.test.ts
Labels: team/campaigns

#17293 opensource redis exporter image, use 64bit binary
  docker-images/redis_exporter/build.sh
  enterprise/dev/ci/images/images.go
Labels: automerge

#16901 db: migrate dbconn from lib/pq to jackc/pgx
  cmd/frontend/internal/cli/serve_cmd.go
  enterprise/cmd/frontend/internal/registry/extensions_db_test.go
  enterprise/cmd/frontend/internal/registry/releases_db.go
  enterprise/internal/campaigns/store/changeset_specs.go
  enterprise/internal/campaigns/store/changesets.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/indexable_repos.go
  enterprise/internal/codeintel/stores/dbstore/references.go
  enterprise/internal/codemonitors/resolvers/resolvers_test.go
  go.mod
  go.sum
  internal/db/dbconn/CODENOTIFY
  internal/db/dbconn/dbconn.go
  internal/db/dbconn/dbconn_test.go
  internal/db/dbutil/dbutil.go
  internal/db/event_logs_test.go
  internal/db/external_accounts.go
  internal/db/globalstatedb/globalstatedb.go
  internal/db/org_invitations.go
  internal/db/org_members.go
  internal/db/orgs.go
  internal/db/users.go
  internal/env/env.go
  internal/workerutil/dbworker/store/store_test.go
Labels: team/cloud

#17308 repo-updater: Fix update queue length metric
  internal/repos/scheduler.go
Labels: team/cloud

#17302 repo-updater: Small cleanup
  cmd/repo-updater/repoupdater/server.go
Labels: team/cloud

#17316 Revert "repo-updater: Small cleanup (#17302)"
  cmd/repo-updater/repoupdater/server.go
Labels: team/cloud

#17280 Recheck changeset syncer preconditions
  enterprise/internal/campaigns/store/changesets.go
  enterprise/internal/campaigns/store/changesets_test.go
  enterprise/internal/campaigns/syncer/syncer.go
  enterprise/internal/campaigns/syncer/syncer_test.go
Labels: team/campaigns

#17285 Adopt proper changeset backdrop highlight
  client/web/src/enterprise/campaigns/detail/CampaignDetailsPage.story.tsx
  client/web/src/enterprise/campaigns/detail/changesets/CampaignChangesets.scss
  client/web/src/enterprise/campaigns/detail/changesets/CampaignChangesetsHeader.tsx
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.scss
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/campaigns/detail/changesets/HiddenExternalChangesetNode.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.scss
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
Labels: team/campaigns

#17291 Don't check 'select all' with no query hits
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/cloud

#17213 Campaign preview stats bar
  client/web/src/enterprise.scss
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/campaigns/preview/CampaignPreviewPage.story.tsx
  client/web/src/enterprise/campaigns/preview/CampaignPreviewPage.tsx
  client/web/src/enterprise/campaigns/preview/CampaignPreviewStatsBar.scss
  client/web/src/enterprise/campaigns/preview/CampaignPreviewStatsBar.tsx
  client/web/src/enterprise/campaigns/preview/CreateUpdateCampaignAlert.tsx
  client/web/src/enterprise/campaigns/preview/backend.ts
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewActions.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewList.scss
  client/web/src/enterprise/campaigns/preview/list/PreviewListHeader.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewNodeIndicator.scss
  client/web/src/enterprise/campaigns/preview/list/PreviewNodeIndicator.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/integration/campaigns.test.ts
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/changeset_apply_preview.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection_test.go
Labels: team/campaigns

#17328 Respect search terms for totalCount computation in preview list
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection.go
Labels: bug, team/campaigns

#17330 Fixes a link from repos to code hosts when no code hosts were active.
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: team/cloud

#17334 codeintel: Add source to all queries in db/lsif stores
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/index_configuration.go
  enterprise/internal/codeintel/stores/dbstore/indexable_repos.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/lock.go
  enterprise/internal/codeintel/stores/dbstore/packages.go
  enterprise/internal/codeintel/stores/dbstore/references.go
  enterprise/internal/codeintel/stores/dbstore/repo_usage.go
  enterprise/internal/codeintel/stores/dbstore/repos.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/lsifstore/clear.go
  enterprise/internal/codeintel/stores/lsifstore/data_read.go
Labels: team/code-intelligence

#17256 codeintel: Filter out dumps associated with force pushed-away commits
  enterprise/cmd/frontend/internal/codeintel/api/cursor.go
  enterprise/cmd/frontend/internal/codeintel/api/cursor_test.go
  enterprise/cmd/frontend/internal/codeintel/api/definitions.go
  enterprise/cmd/frontend/internal/codeintel/api/definitions_test.go
  enterprise/cmd/frontend/internal/codeintel/api/exists.go
  enterprise/cmd/frontend/internal/codeintel/api/exists_test.go
  enterprise/cmd/frontend/internal/codeintel/api/helpers_test.go
  enterprise/cmd/frontend/internal/codeintel/api/hover_test.go
  enterprise/cmd/frontend/internal/codeintel/api/iface.go
  enterprise/cmd/frontend/internal/codeintel/api/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/api/monikers.go
  enterprise/cmd/frontend/internal/codeintel/api/monikers_test.go
  enterprise/cmd/frontend/internal/codeintel/api/references.go
  enterprise/cmd/frontend/internal/codeintel/api/references_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query.go
  enterprise/internal/codeintel/gitserver/client.go
  enterprise/internal/codeintel/gitserver/observability.go
Labels: team/code-intelligence

#17363 sentry: allow specify a DSN for backend
  CHANGELOG.md
  internal/sentry/sentry.go
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: team/cloud

#17318 repo-updater: Don't schedule all repos for update on startup
  cmd/repo-updater/shared/main.go
  internal/db/default_repos_test.go
  internal/db/repos.go
Labels: team/cloud

#17341 codeintel: Remove old index records in the same way we expire upload records
  enterprise/cmd/frontend/internal/codeintel/background/janitor/iface.go
  enterprise/cmd/frontend/internal/codeintel/background/janitor/record_expirer.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence

#17369 repo-updater: Fix update queue debug page
  cmd/repo-updater/shared/assets/bindata.go
  cmd/repo-updater/shared/assets/state.html.tmpl
Labels: team/cloud

#17338 codeintel: Modify SoftDeleteOldDumps to delete old non-terminal uploads as well
  enterprise/cmd/frontend/internal/codeintel/background/janitor/iface.go
  enterprise/cmd/frontend/internal/codeintel/background/janitor/record_expirer.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/dumps_test.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence

#17391 bump src-cli minimum version
  doc/cli/references/lsif/upload.md
  internal/src-cli/consts.go
Labels: team/code-intelligence

#17348 repos: add Perforce code host connection type
  client/web/src/components/PerforceIcon.tsx
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/campaigns/settings/AddCredentialModal.tsx
  client/web/src/site-admin/SiteAdminReportBugPage.tsx
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/db/external_services_test.go
  internal/db/external_services.go
  internal/extsvc/types.go
  internal/repos/bitbucketcloud_test.go
  internal/repos/perforce.go
  internal/repos/perforce_test.go
  internal/repos/sources.go
  internal/repos/testdata/golden/PerforceSource_makeRepo_simple
  schema/gen.sh
  schema/perforce.schema.json
  schema/perforce_stringdata.go
  schema/schema.go
  schema/site.schema.json
  schema/site_stringdata.go
Labels: team/cloud

#17286 Document dynamic changesetTemplates and steps.outputs
  doc/_resources/assets/docsite.css
  doc/campaigns/index.md
  doc/campaigns/references/campaign_spec_templating.md
  doc/campaigns/references/campaign_spec_yaml_reference.md
  doc/campaigns/references/index.md
Labels: docs, team/campaigns

#17405 Convert the AccessToken store into a basestore
  internal/db/access_tokens.go
  internal/db/stores.go
Labels: team/cloud

#17412 Add types to campaign spec templating docs
  doc/campaigns/references/campaign_spec_templating.md
Labels: docs, team/campaigns

#17406 Convert the DefaultRepos store into a basestore
  internal/db/default_repos.go
  internal/db/stores.go
Labels: team/cloud

#17409 Replace global database by local handle in AccessTokenStore
  internal/db/access_tokens.go
Labels: team/cloud

#17410 Convert the QueryRunnerState store into a basestore
  internal/db/saved_queries.go
  internal/db/stores.go
Labels: team/cloud

#17415 db: Return tx.Done error
  internal/db/users.go
Labels: team/cloud

#17407 Convert the Phabricator store into a basestore
  internal/db/phabricator.go
  internal/db/stores.go
Labels: team/cloud

#17420 Convert the SavedSearches store into a basestore
  internal/db/saved_searches.go
  internal/db/stores.go
Labels: team/cloud

#17417 Convert the OrgMembers store into a basestore
  internal/db/org_members.go
  internal/db/org_members_db_test.go
  internal/db/stores.go
  internal/db/users.go
Labels: team/cloud

#17385 Fix FilteredConnection input style
  client/web/src/components/FilteredConnection.scss
  client/web/src/components/FilteredConnection.tsx
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.scss
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: webapp

#17435 executor: Ping the frontend before starting up
  enterprise/cmd/executor/internal/apiclient/client.go
  enterprise/cmd/executor/internal/worker/worker.go
Labels: team/code-intelligence

#17437 executor: Remove temporary observability code
  enterprise/cmd/executor/internal/command/firecracker.go
  enterprise/cmd/executor/internal/command/run.go
  enterprise/cmd/executor/internal/worker/handler.go
Labels: team/code-intelligence

#17439 codeintel: Do not enable tracing for background tasks
  enterprise/cmd/frontend/internal/codeintel/background/commitgraph/updater.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/indexability_updater.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go
  internal/workerutil/worker.go
Labels: team/code-intelligence

#17148 fix issue where scrollbars appear during resizing
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/shared/src/components/Resizable.scss
  client/shared/src/components/Resizable.tsx
Labels: bug, team/web, webapp

#17448 db: Convert userEmails to basestore
  internal/db/stores.go
  internal/db/user_emails.go
Labels: team/cloud

#17461 Delete saved searches when a user is hard deleted
  CHANGELOG.md
  internal/db/users.go
  internal/db/users_test.go
Labels: team/cloud

#17455 Convert the Settings store into a basestore
  internal/db/settings.go
  internal/db/stores.go
Labels: team/cloud

#17456 Convert the Event logs store into a basestore
  internal/db/event_logs.go
  internal/db/stores.go
Labels: team/cloud

#17457 Convert the Org invitations store into a basestore
  internal/db/org_invitations.go
  internal/db/stores.go
Labels: team/cloud

#17459 Convert the Survey Responses store into a basestore
  internal/db/stores.go
  internal/db/survey_responses.go
Labels: team/cloud

#17469 db: Convert UserCredentials store to basestore
  internal/db/stores.go
  internal/db/user_credentials.go
Labels: team/cloud

#17458 Delete the secrets store
  internal/db/mockstores.go
  internal/db/secrets.go
  internal/db/secrets_mock.go
  internal/db/secrets_test.go
  internal/db/stores.go
Labels: team/cloud

#17399 Move database connection utils to dbconn
  cmd/gitserver/main.go
  cmd/repo-updater/repoupdater/server_test.go
  cmd/repo-updater/shared/main.go
  dev/reconciler-test-script/main.go
  go.mod
  go.sum
  internal/db/basestore/handle.go
  internal/db/dbconn/dbconn.go
  internal/db/dbconn/migration.go
  internal/db/dbstore_db_test.go
  internal/db/dbtest/dbtest.go
  internal/db/dbtesting/dbtesting.go
  internal/db/dbutil/dbutil.go
  internal/types/testing.go
Labels: team/cloud

#17464 Add "Handling errored changesets" how-to to documentation
  doc/campaigns/how-tos/handling_errored_changesets.md
  doc/campaigns/how-tos/index.md
  doc/campaigns/index.md
Labels: docs

#17468 Document idempotency of campaign spec re-execution
  doc/campaigns/explanations/index.md
  doc/campaigns/explanations/reexecuting_campaign_specs_multiple_times.md
  doc/campaigns/index.md
Labels: docs, team/campaigns

#17240 Add async job indicator when saving changes in the 'Manage Repositories' page
  client/web/src/components/LoaderButton.tsx
  client/web/src/components/__snapshots__/LoaderButton.test.tsx.snap
  client/web/src/components/externalServices/ExternalServicePage.story.tsx
  client/web/src/components/externalServices/ExternalServicesPage.story.tsx
  client/web/src/components/externalServices/backend.ts
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: team/cloud, team/cloud/milestone-3

#17443 codeintel: Do not export internal methods in lsifstore
  enterprise/internal/codeintel/stores/lsifstore/bundle.go
  enterprise/internal/codeintel/stores/lsifstore/data_read.go
  enterprise/internal/codeintel/stores/lsifstore/data_read_test.go
Labels: team/code-intelligence

#17473 db: Convert UserExternalAccounts to basestore
  internal/db/external_accounts.go
  internal/db/stores.go
  internal/db/user_emails.go
Labels: team/cloud

#17501 db: Add cloud_default column to external_services
  internal/api/api.go
  internal/db/external_services.go
  internal/db/schema.md
  internal/types/types.go
  migrations/frontend/1528395775_add_cloud_default_to_external_services.down.sql
  migrations/frontend/1528395775_add_cloud_default_to_external_services.up.sql
  migrations/frontend/bindata.go
Labels: team/cloud

#17506 db: rename store constructors
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/webhooks/github_webhooks_test.go
  cmd/gitserver/main.go
  cmd/repo-updater/shared/main.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users.go
  enterprise/internal/campaigns/background.go
  enterprise/internal/campaigns/frontend.go
  enterprise/internal/campaigns/reconciler/executor.go
  enterprise/internal/campaigns/resolvers/campaign_connection_test.go
  enterprise/internal/campaigns/resolvers/campaign_spec_test.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_test.go
  enterprise/internal/campaigns/resolvers/changeset_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_counts_test.go
  enterprise/internal/campaigns/resolvers/changeset_event_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_spec_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_spec_test.go
  enterprise/internal/campaigns/resolvers/changeset_test.go
  enterprise/internal/campaigns/resolvers/permissions_test.go
  enterprise/internal/campaigns/resolvers/resolver_test.go
  enterprise/internal/campaigns/service/service.go
  enterprise/internal/campaigns/store/changeset_specs_test.go
  enterprise/internal/campaigns/store/changesets_test.go
  enterprise/internal/campaigns/store/codehost_test.go
  enterprise/internal/campaigns/testing/repos.go
  enterprise/internal/campaigns/webhooks/webhooks.go
  enterprise/internal/campaigns/webhooks/webhooks_gitlab_test.go
  enterprise/internal/campaigns/webhooks/webhooks_test.go
  internal/db/access_tokens.go
  internal/db/default_repos.go
  internal/db/event_logs.go
  internal/db/external_accounts.go
  internal/db/external_services.go
  internal/db/namespaces.go
  internal/db/org_invitations.go
  internal/db/org_members.go
  internal/db/orgs.go
  internal/db/phabricator.go
  internal/db/repos.go
  internal/db/saved_queries.go
  internal/db/saved_searches.go
  internal/db/settings.go
  internal/db/survey_responses.go
  internal/db/user_credentials.go
  internal/db/user_emails.go
  internal/db/user_public_repos.go
  internal/db/user_public_repos_test.go
  internal/db/users.go
  internal/repos/store.go
  internal/usagestats/campaigns_test.go
Labels: team/cloud

#17511 db: remove references to dbconn in store tests
  internal/db/access_tokens_test.go
  internal/db/dbstore_db_test.go
  internal/db/dbtesting/dbtesting.go
  internal/db/default_repos.go
  internal/db/default_repos_test.go
  internal/db/event_logs_test.go
  internal/db/external_accounts.go
  internal/db/external_accounts_test.go
  internal/db/external_services.go
  internal/db/external_services_test.go
  internal/db/namespaces_test.go
  internal/db/org_invitations_test.go
  internal/db/org_members.go
  internal/db/org_members_db_test.go
  internal/db/orgs.go
  internal/db/orgs_test.go
  internal/db/phabricator.go
  internal/db/repos.go
  internal/db/repos_db_test.go
  internal/db/repos_perm.go
  internal/db/repos_perm_test.go
  internal/db/repos_test.go
  internal/db/saved_searches.go
  internal/db/saved_searches_test.go
  internal/db/settings_test.go
  internal/db/survey_responses_test.go
  internal/db/user_credentials_test.go
  internal/db/user_emails_test.go
  internal/db/user_public_repos_test.go
  internal/db/users.go
  internal/db/users_builtin_auth_test.go
  internal/db/users_test.go
Labels: team/cloud

#17514 db: external_services.cloud_default column should not be nullable
  internal/db/schema.md
  migrations/frontend/1528395776_cloud_default_not_null.down.sql
  migrations/frontend/1528395776_cloud_default_not_null.up.sql
  migrations/frontend/bindata.go
Labels: team/cloud

#17524 Remove unneeded call to ensureStore
  internal/db/repos.go
Labels: team/campaigns

#17388 Associate lsif_uploads with their corresponding lsif_index record
  enterprise/cmd/executor-queue/internal/queues/codeintel/transform.go
  enterprise/cmd/executor-queue/internal/queues/codeintel/transform_test.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  enterprise/internal/codeintel/stores/dbstore/dumps.go
  enterprise/internal/codeintel/stores/dbstore/dumps_test.go
  enterprise/internal/codeintel/stores/dbstore/helpers_test.go
  enterprise/internal/codeintel/stores/dbstore/packages.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  internal/db/schema.md
  migrations/frontend/1528395777_lsif_uploads_associated_index.down.sql
  migrations/frontend/1528395777_lsif_uploads_associated_index.up.sql
  migrations/frontend/bindata.go
Labels: team/code-intelligence

#17523 codeintel: Reuse lsif-protocol
  enterprise/internal/codeintel/lsif/correlation/correlate.go
  enterprise/internal/codeintel/lsif/correlation/correlate_test.go
  enterprise/internal/codeintel/lsif/correlation/group_test.go
  enterprise/internal/codeintel/lsif/lsif/interner.go
  enterprise/internal/codeintel/lsif/lsif/interner_test.go
  enterprise/internal/codeintel/lsif/lsif/reader.go
  enterprise/internal/codeintel/lsif/lsif/reader_test.go
  enterprise/internal/codeintel/lsif/lsif/types.go
  enterprise/internal/codeintel/lsif/lsif/unmarshal.go
  enterprise/internal/codeintel/lsif/lsif/unmarshal_test.go
  go.mod
  go.sum
Labels: team/code-intelligence

#17526 Fix detach not correctly executed when changeset is in failed state
  enterprise/internal/campaigns/reconciler/plan.go
  enterprise/internal/campaigns/reconciler/plan_test.go
Labels: bug, team/campaigns

#17527 Adjust new campaign button wording
  client/web/src/enterprise/campaigns/list/CampaignListPage.tsx
Labels: team/campaigns

#17525 Fix empty RewirerMappings.Hydrate being slow
  enterprise/internal/campaigns/store/changeset_specs.go
Labels: bug, team/campaigns

#17516 db: convert PermStore into a basestore
  enterprise/cmd/frontend/authz/authz.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/repo-updater/authz/integration_test.go
  enterprise/cmd/repo-updater/authz/perms_syncer.go
  enterprise/cmd/repo-updater/authz/perms_syncer_test.go
  enterprise/cmd/repo-updater/main.go
  enterprise/internal/campaigns/testing/mock_repo_perms.go
  enterprise/internal/db/authz.go
  enterprise/internal/db/external_services.go
  enterprise/internal/db/external_services_test.go
  enterprise/internal/db/perms_store.go
  enterprise/internal/db/perms_store_test.go
Labels: team/cloud

#17474 gitserver: abstract clone and fetch operations for different VCS
  cmd/gitserver/main.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  cmd/gitserver/server/vcs_syncer.go
  internal/gitserver/client_test.go
  internal/repos/perforce.go
  internal/repos/testdata/golden/PerforceSource_makeRepo_simple
  internal/vcs/git/main_test.go
Labels: team/cloud

#17519 db: Use cloud_default column
  cmd/repo-updater/shared/main.go
  internal/db/external_services.go
  internal/db/external_services_test.go
  internal/repos/github.go
  internal/repos/gitlab.go
  schema/github.schema.json
  schema/github_stringdata.go
  schema/gitlab.schema.json
  schema/gitlab_stringdata.go
Labels: team/cloud

#17546 frontend: inject db handle into schemaResolver
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/testing.go
  cmd/frontend/internal/cli/serve_cmd.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/internal/campaigns/resolvers/campaign_connection_test.go
  enterprise/internal/campaigns/resolvers/campaign_spec_test.go
  enterprise/internal/campaigns/resolvers/campaign_test.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_test.go
  enterprise/internal/campaigns/resolvers/changeset_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_counts_test.go
  enterprise/internal/campaigns/resolvers/changeset_event_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_spec_connection_test.go
  enterprise/internal/campaigns/resolvers/changeset_spec_test.go
  enterprise/internal/campaigns/resolvers/changeset_test.go
  enterprise/internal/campaigns/resolvers/code_host_connection_test.go
  enterprise/internal/campaigns/resolvers/permissions_test.go
  enterprise/internal/campaigns/resolvers/resolver_test.go
  enterprise/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/licensing/resolvers/resolvers_test.go
Labels: team/cloud

#17450 Move onboarding tour logic to a hook
  client/shared/src/search/query/completion.ts
  client/web/src/integration/search-onboarding.test.ts
  client/web/src/search/input/LazyMonacoQueryInput.test.tsx
  client/web/src/search/input/MonacoQueryInput.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/search/input/SearchOnboardingTour.ts
  client/web/src/search/input/SearchPageInput.tsx
  client/web/src/user/settings/UserSettingsSidebar.tsx
Labels: debt, team/search

#17513 Convert MonacoQueryInput to function component
  client/web/src/search/input/MonacoQueryInput.tsx
Labels: debt, team/search

#17543 Make changesetStats use the same logic as changeset.state
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/changesets_stats.go
  enterprise/internal/campaigns/store/changesets.go
  enterprise/internal/campaigns/store/changesets_test.go
  internal/campaigns/changeset.go
Labels: team/campaigns

#17327 Implement extended expand section on preview nodes
  client/web/src/enterprise/campaigns/Description.story.tsx
  client/web/src/enterprise/campaigns/Description.tsx
  client/web/src/enterprise/campaigns/detail/CampaignDescription.tsx
  client/web/src/enterprise/campaigns/detail/CampaignDetailsPage.tsx
  client/web/src/enterprise/campaigns/preview/CampaignPreviewPage.story.tsx
  client/web/src/enterprise/campaigns/preview/CampaignPreviewPage.tsx
  client/web/src/enterprise/campaigns/preview/list/ChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/campaigns/preview/list/ChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/GitBranchChangesetDescriptionInfo.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewList.story.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewList.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/backend.ts
  client/web/src/integration/campaigns.test.ts
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/changeset.go
  internal/campaigns/changeset.go
  internal/extsvc/github/pulls.go
  internal/extsvc/gitlab/merge_requests.go
Labels: team/campaigns

#17529 Implement faster resolver for global campaign diff stat
  enterprise/internal/campaigns/resolvers/campaign.go
  enterprise/internal/campaigns/store/campaigns.go
  enterprise/internal/campaigns/store/campaigns_test.go
  enterprise/internal/campaigns/testing/changeset.go
  enterprise/internal/campaigns/testing/repos.go
  internal/db/repos.go
  internal/db/repos_perm.go
  internal/db/repos_perm_test.go
Labels: team/campaigns

#17570 Added lerna.json parsing for typescript autoindex inference
  enterprise/cmd/frontend/internal/codeintel/background/indexing/iface.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/indexability_updater.go
  enterprise/cmd/frontend/internal/codeintel/background/indexing/mock_iface_test.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/internal/codeintel/autoindex/inference/gen.go
  enterprise/internal/codeintel/autoindex/inference/go.go
  enterprise/internal/codeintel/autoindex/inference/go_test.go
  enterprise/internal/codeintel/autoindex/inference/iface.go
  enterprise/internal/codeintel/autoindex/inference/mock_iface.go
  enterprise/internal/codeintel/autoindex/inference/recognizers.go
  enterprise/internal/codeintel/autoindex/inference/typescript.go
  enterprise/internal/codeintel/autoindex/inference/typescript_test.go
Labels: lsif-node, team/code-intelligence

#17537 codeintel: Change rank behavior for uploads and indexes
  enterprise/cmd/executor-queue/internal/queues/codeintel/queue.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/worker.go
Labels: team/code-intelligence

#17579 campaigns: fix horizontal alignment of states
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.tsx
Labels: team/campaigns

#17584 code-intel: hotfix typescript autoconf lerna.json detection
  enterprise/internal/codeintel/autoindex/inference/typescript.go
Labels: lsif-node, team/code-intelligence

#17590 cli: bump minimum version
  internal/src-cli/consts.go
Labels: team/campaigns

#17550 repo-updater: Only exclude cloud_default external services from sync and index
  internal/db/default_repos_test.go
  internal/db/repos.go
  internal/repos/store.go
Labels: team/cloud

#17540 Implement overhauled campaigns stats section
  client/web/src/enterprise/campaigns/close/CampaignClosePage.story.tsx
  client/web/src/enterprise/campaigns/detail/CampaignDetailsPage.story.tsx
  client/web/src/enterprise/campaigns/detail/CampaignDetailsPage.tsx
  client/web/src/enterprise/campaigns/detail/CampaignStatsCard.scss
  client/web/src/enterprise/campaigns/detail/CampaignStatsCard.story.tsx
  client/web/src/enterprise/campaigns/detail/CampaignStatsCard.tsx
  client/web/src/enterprise/campaigns/detail/backend.ts
  client/web/src/integration/campaigns.test.ts
Labels: team/campaigns

#17564 Add commit changes column to campaigns preview UI
  client/web/src/enterprise/campaigns/preview/list/GitBranchChangesetDescriptionInfo.tsx
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/PreviewList.scss
  client/web/src/enterprise/campaigns/preview/list/PreviewListHeader.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.scss
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
Labels: team/campaigns

#17608 campaigns: Cleanup some little things
  enterprise/internal/campaigns/reconciler/executor.go
  enterprise/internal/campaigns/reconciler/util.go
  enterprise/internal/campaigns/syncer/syncer.go
  enterprise/internal/campaigns/syncer/util.go
Labels: debt, team/campaigns

#17620 Fixed bug in lerna.json value finding
  enterprise/internal/codeintel/autoindex/inference/typescript.go
  enterprise/internal/codeintel/autoindex/inference/typescript_test.go
Labels: lsif-node, team/code-intelligence

#17619 Fix configuration of multi-branch indexing in docs
  doc/code_search/explanations/features.md
Labels: docs

#17588 dev: correct codeinsights-db port; add connection info
  dev/codeinsights-db.sh
  dev/start.sh
Labels: team/code-insights, team/internal-contributor

#17551 gitserver: able to clone and fetch Perforce depots
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/vcs_syncer.go
  cmd/gitserver/server/vcs_syncer_test.go
  enterprise/internal/db/external_services_test.go
  internal/repos/perforce.go
  schema/perforce.schema.json
  schema/perforce_stringdata.go
Labels: team/cloud

#17629 db: rename enterprise/internal/db package to enterprise/internal/database
  enterprise/cmd/frontend/authz/authz.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/cmd/repo-updater/authz/integration_test.go
  enterprise/cmd/repo-updater/authz/perms_syncer.go
  enterprise/cmd/repo-updater/authz/perms_syncer_test.go
  enterprise/cmd/repo-updater/main.go
  enterprise/internal/campaigns/testing/mock_repo_perms.go
  enterprise/internal/database/CODENOTIFY
  enterprise/internal/database/authz.go
  enterprise/internal/database/authz_test.go
  enterprise/internal/database/db_test.go
  enterprise/internal/database/external_services.go
  enterprise/internal/database/external_services_test.go
  enterprise/internal/database/integration_test.go
  enterprise/internal/database/mockstores.go
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_mock.go
  enterprise/internal/database/perms_store_test.go
Labels: team/cloud

#17567 metrics: Monitor rate limit wait duration
  doc/admin/observability/dashboards.md
  internal/extsvc/github/common.go
  internal/extsvc/github/v3.go
  internal/extsvc/github/v4.go
  internal/extsvc/github/version.go
  internal/ratelimit/monitor.go
  internal/repos/github.go
  internal/repos/gitlab.go
  monitoring/definitions/repo_updater.go
Labels: team/cloud

#17613 Fix validation messages of code monitor query
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
Labels: bug

#17700 repos: Remove debugging code
  internal/repos/github.go
Labels: team/cloud

#17585 internal/db: do not run TimescaleDB migrations against singleton database
  cmd/frontend/internal/cli/serve_cmd.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/precise-code-intel-worker/main.go
  internal/database/dbconn/migration.go
  internal/database/dbstore_db_test.go
  internal/database/dbtest/dbtest.go
  internal/database/dbtesting/dbtesting.go
  internal/database/schemadoc/main.go
Labels: team/code-insights, team/internal-contributor

#17586 insights: execute database migrations
  cmd/frontend/internal/cli/config.go
  enterprise/internal/insights/insights.go
  internal/conf/conftypes/conftypes.go
Labels: team/code-insights, team/internal-contributor

#17657 Make superseding campaign spec dismissible
  client/web/src/enterprise/campaigns/detail/SupersedingCampaignSpecAlert.story.tsx
  client/web/src/enterprise/campaigns/detail/SupersedingCampaignSpecAlert.tsx
Labels: team/campaigns

#17707 Don't load all sync states when page slice is empty
  enterprise/internal/campaigns/resolvers/changeset_apply_preview_connection.go
  enterprise/internal/campaigns/resolvers/changeset_connection.go
Labels: bug, team/campaigns

#17708 db: stop using sqlhooks fork
  go.mod
  go.sum
  internal/database/dbconn/dbconn.go
Labels: team/cloud

#17610 Expose syncer errors in UI
  client/web/src/enterprise/campaigns/close/CampaignClosePage.story.tsx
  client/web/src/enterprise/campaigns/detail/CampaignDetailsPage.story.tsx
  client/web/src/enterprise/campaigns/detail/backend.ts
  client/web/src/enterprise/campaigns/detail/changesets/CampaignChangesets.story.tsx
  client/web/src/enterprise/campaigns/detail/changesets/ChangesetLastSynced.tsx
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.story.tsx
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/campaigns/detail/changesets/HiddenExternalChangesetInfoCell.tsx
  client/web/src/enterprise/campaigns/detail/changesets/HiddenExternalChangesetNode.story.tsx
  client/web/src/enterprise/campaigns/detail/changesets/HiddenExternalChangesetNode.tsx
  client/web/src/integration/campaigns.test.ts
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/campaigns/resolvers/changeset.go
  enterprise/internal/campaigns/store/changesets.go
  enterprise/internal/campaigns/syncer/syncer.go
  internal/campaigns/changeset.go
  internal/database/schema.md
  migrations/frontend/1528395778_add_syncer_error.down.sql
  migrations/frontend/1528395778_add_syncer_error.up.sql
  migrations/frontend/bindata.go
Labels: team/campaigns

#17713 fix codeintel QA tests as dir rename from database->db
  internal/cmd/precise-code-intel-tester/test_cases.go
Labels: team/code-intelligence

#17712 gitserver: Fall back to GitRepoSyncer for missing repos
  cmd/gitserver/server/server.go
Labels: team/cloud

#17717 database: Fix panic and consistent receivers
  internal/database/orgs.go
Labels: team/cloud

#17733 enterprise/internal/insights: add basic store package + testing infrastructure
  dev/ci/go-test.sh
  enterprise/internal/insights/insights.go
  enterprise/internal/insights/resolvers/resolver.go
  enterprise/internal/insights/store/insights_test.go
  enterprise/internal/insights/store/integration_test.go
  enterprise/internal/insights/store/store.go
Labels: team/code-insights, team/internal-contributor

#17735 codeinsights: do not run on server & fix CI failure
  dev/ci/backend-integration.sh
  enterprise/internal/insights/insights.go
Labels: team/code-insights, team/internal-contributor

#17738 code insights: add dev option to disable code insights backend entirely
  enterprise/internal/insights/insights.go
Labels: team/code-insights, team/internal-contributor

#17742 code insights: fully qualify Postgres DSN to avoid conflicts
  dev/ci/go-test.sh
  dev/start.sh
  enterprise/internal/insights/store/integration_test.go
Labels: team/code-insights, team/internal-contributor

#17744 dev: give codeinsights-db more time to start
  dev/ci/go-test.sh
  dev/start.sh
Labels: team/code-insights, team/internal-contributor

#17754 frontend: manually initialize the router
  cmd/frontend/auth/non_public.go
  cmd/frontend/auth/non_public_test.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/router.go
  cmd/frontend/internal/app/ui/router_test.go
  cmd/frontend/internal/cli/serve_cmd.go
Labels: team/cloud

#17602 prom-wrapper: introduce src-prometheus, migrate alerts history
  client/web/src/site-admin/backend.ts
  cmd/frontend/graphqlbackend/site_alerts.go
  cmd/frontend/graphqlbackend/site_alerts_test.go
  cmd/frontend/graphqlbackend/site_monitoring.go
  cmd/frontend/internal/app/debug.go
  cmd/frontend/internal/app/debug_test.go
  doc/dev/background-information/observability/prometheus.md
  docker-images/prometheus/cmd/prom-wrapper/README.md
  docker-images/prometheus/cmd/prom-wrapper/main.go
  docker-images/prometheus/cmd/prom-wrapper/mocks/gen.go
  docker-images/prometheus/cmd/prom-wrapper/mocks/prometheus_mock.go
  docker-images/prometheus/cmd/prom-wrapper/siteconfig.go
  docker-images/prometheus/cmd/prom-wrapper/status.go
  docker-images/prometheus/cmd/prom-wrapper/status_test.go
  internal/prometheusutil/gen.go
  internal/prometheusutil/prometheus.go
  internal/prometheusutil/prometheus_mock.go
  internal/prometheusutil/roundtripper.go
  internal/src-prometheus/prometheus.go
  internal/src-prometheus/prometheus_test.go
  internal/src-prometheus/types.go
Labels: team/distribution

#17716 Show current user count alongside max license count and actual billable user count
  client/web/src/enterprise/site-admin/productSubscription/ProductSubscriptionStatus.tsx
Labels: webapp

#17690 Add re-enqueue changeset UI action
  client/branded/src/global-styles/alert.scss
  client/web/src/enterprise/campaigns/detail/backend.ts
  client/web/src/enterprise/campaigns/detail/changesets/ChangesetStatusCell.story.tsx
  client/web/src/enterprise/campaigns/detail/changesets/ChangesetStatusCell.tsx
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.scss
  client/web/src/enterprise/campaigns/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/campaigns/detail/changesets/HiddenExternalChangesetNode.tsx
  client/web/src/enterprise/campaigns/preview/list/HiddenChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/campaigns/preview/list/VisibleChangesetApplyPreviewNode.tsx
  cmd/frontend/graphqlbackend/campaigns.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/schema.graphql
  doc/campaigns/how-tos/handling_errored_changesets.md
  enterprise/internal/campaigns/resolvers/permissions_test.go
  enterprise/internal/campaigns/resolvers/resolver.go
  enterprise/internal/campaigns/resolvers/resolver_test.go
  enterprise/internal/campaigns/rewirer/rewirer.go
  enterprise/internal/campaigns/service/service.go
  enterprise/internal/campaigns/service/service_apply_campaign_test.go
  enterprise/internal/campaigns/service/service_test.go
  enterprise/internal/campaigns/testing/changeset.go
Labels: team/campaigns

#17724 adds support for node version inference and changing via n
  enterprise/internal/codeintel/autoindex/inference/typescript.go
  enterprise/internal/codeintel/autoindex/inference/typescript_test.go
Labels: lsif-node, team/code-intelligence
