Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-11, with the labels that each got.

#26864 ci: add pipeline.yml
  .buildkite/pipeline.yml
Labels: cla-signed

#26828 [CLOUD-78] authz: re-enable user-centric perms syncing for user code host conns
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/authz/authz.go
  enterprise/internal/authz/authz_test.go
  enterprise/internal/authz/bitbucketserver/provider.go
  enterprise/internal/authz/github/github.go
  enterprise/internal/authz/gitlab/gitlab.go
  enterprise/internal/authz/gitlab/oauth.go
  enterprise/internal/authz/gitlab/sudo.go
  enterprise/internal/authz/perforce/perforce.go
  enterprise/internal/database/integration_test.go
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_mock.go
  enterprise/internal/database/perms_store_test.go
  internal/authz/iface.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/repos_perm_test.go
Labels: cla-signed

#25945 [CLOUD-78] db: update `authzQuery` to consult org-added repos
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
Labels: cla-signed

#26839 [CLOUD-78] authz: schedule background syncing for org members with outdated permissions
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_test.go
Labels: cla-signed

#26846 web: update bundlesize config
  client/web/bundlesize.config.js
Labels: team/frontend-platform, UI performance, cla-signed

#26869 perms: add missing cleanups in tests
  enterprise/internal/database/perms_store_test.go
Labels: cla-signed

#26779 Performance: Run weekly audits against Sourcegraph.com
  .github/workflows/lighthouse-production.yml
  dev/ci/generate-lighthouse-slack-report.sh
Labels: team/frontend-platform, cla-signed

#26871 sg: Update instructions for quickstart
  doc/dev/background-information/sg/index.md
Labels: dx, sg, cla-signed

#26877 gitserver: kill the zombies of CommitSearcher
  internal/gitserver/search/search.go
Labels: cla-signed

#26860 internal/search/backend: Fix log15 error
  internal/search/backend/horizontal.go
Labels: cla-signed

#26878 List a/b tests
  doc/dev/how-to/use_feature_flags.md
Labels: cla-signed

#26671 web: codemod `web/search/home` `web/search/input` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/search/QuickLinks.module.scss
  client/web/src/search/QuickLinks.tsx
  client/web/src/search/home/LoggedOutHomepage.module.scss
  client/web/src/search/home/SearchPage.module.scss
  client/web/src/search/home/SearchPage.scss
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/home/SearchPageInput.module.scss
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/home/homepage.scss
  client/web/src/search/input/InfoDropdown.module.scss
  client/web/src/search/input/InfoDropdown.scss
  client/web/src/search/input/InfoDropdown.tsx
  client/web/src/search/input/SearchBox.module.scss
  client/web/src/search/input/SearchButton.tsx
  client/web/src/search/input/SearchContextDropdown.module.scss
  client/web/src/search/input/SearchContextDropdown.scss
  client/web/src/search/input/SearchContextDropdown.tsx
  client/web/src/search/input/SearchOnboardingTour.module.scss
  client/web/src/search/input/SearchOnboardingTour.ts
  client/web/src/search/input/toggles/QueryInputToggle.tsx
  client/web/src/search/input/toggles/Toggles.module.scss
  client/web/src/search/input/toggles/Toggles.scss
  client/web/src/search/input/toggles/Toggles.tsx
  client/web/src/search/input/toggles/__snapshots__/Toggles.test.tsx.snap
Labels: cla-signed

#26769 Update create/edit dashboard UI
  client/web/src/enterprise/insights/core/backend/code-insights-backend-types.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/core/backend/code-insights-setting-cascade-backend.ts
  client/web/src/enterprise/insights/core/types/dashboard/core.ts
  client/web/src/enterprise/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/InsightsDashboardCreationContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/helpers/get-dashboard-title.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/delete-dashboard-modal/hooks/use-delete-dashboard-handler.ts
  client/web/src/enterprise/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
Labels: cla-signed

#26848 Update handbook links in doc
  .github/ISSUE_TEMPLATE/customer_feedback.md
  .github/ISSUE_TEMPLATE/request_patch_release.md
  CONTRIBUTING.md
  README.md
  client/branded/README.md
  client/shared/README.md
  client/web/src/components/Breadcrumbs.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminGenerateProductLicenseForSubscriptionForm.test.tsx.snap
  dev/licenses.sh
  dev/release/README.md
  dev/release/src/batchChanges.ts
  dev/release/src/release.ts
  doc/admin/install/managed.md
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  doc/cloud/indexing_open_source_code.md
  doc/code_search/explanations/sourcegraph_cloud.md
  doc/dev/background-information/architecture/index.md
  doc/dev/background-information/architecture/introducing_a_new_service.md
  doc/dev/background-information/architecture/sourcegraph-extensions.md
  doc/dev/background-information/code_reviews.md
  doc/dev/background-information/insights/backend.md
  doc/dev/background-information/insights/index.md
  doc/dev/background-information/languages/go.md
  doc/dev/background-information/observability/grafana.md
  doc/dev/background-information/observability/index.md
  doc/dev/background-information/observability/monitoring-generator.md
  doc/dev/background-information/observability/prometheus.md
  doc/dev/background-information/tech_stack.md
  doc/dev/background-information/testing_principles.md
  doc/dev/background-information/web/accessibility.md
  doc/dev/background-information/web/web_app.md
  doc/dev/how-to/add_monitoring.md
  doc/dev/how-to/documentation_implementation.md
  doc/dev/how-to/find_monitoring.md
  doc/dev/how-to/monitoring_local_dev.md
  doc/dev/how-to/testing.md
  doc/index.md
  docker-images/README.md
  docker-images/grafana/README.md
  docker-images/prometheus/README.md
  enterprise/dev/ci/internal/ci/pipeline.go
  enterprise/docs/deployment.md
  internal/cmd/ghe-feeder/README.md
  internal/cmd/resources-report/README.md
  internal/cmd/resources-report/slack.go
  internal/cmd/tracking-issue/README.md
  monitoring/README.md
  monitoring/definitions/shared/shared.go
  monitoring/monitoring/monitoring.go
  monitoring/monitoring/panel_options.go
Labels: cla-signed

#26883 instrument gitserver search with Prometheus
  cmd/gitserver/server/server.go
  doc/admin/observability/dashboards.md
  monitoring/definitions/git_server.go
  monitoring/monitoring/dashboards.go
Labels: cla-signed

#26727 Change Docker for Mac detection
  CHANGELOG.md
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/app/jscontext/jscontext_test.go
Labels: cla-signed

#26876 codeintel: set db field in UploadHandler to fix panic when checking site-admin
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_test.go
  enterprise/cmd/frontend/internal/codeintel/upload_handler.go
Labels: team/code-intelligence, cla-signed

#26886 run ./dev/generate.sh
  doc/admin/observability/dashboards.md
Labels: cla-signed

#26475 doc: overhaul permissions docs
  doc/admin/external_service/github.md
  doc/admin/repo/permissions.md
Labels: cla-signed

#23949 doc/dev: audit CSRF threat model; document it; add key recommendations
  doc/dev/index.md
  doc/dev/security/csrf_security_model.md
  doc/dev/security/index.md
Labels: apidocs, unicorns, rainbows, butterflies, cla-signed

#26884 database: quiet external service migration errors
  internal/database/external_services.go
  internal/database/oob_migrate_test.go
Labels: bug, team/batchers, webhooks, cla-signed

#26556 sg: add --commit to ci build
  dev/sg/sg_ci.go
  doc/dev/background-information/sg/index.md
Labels: cla-signed

#26894 docs: fix typos, update code snippets for OOB migration docs
  doc/dev/background-information/oobmigrations.md
Labels: docs, cla-signed

#26897 doc/contributing: document sg ci build --commit, add warning
  doc/dev/contributing/accepting_contribution.md
Labels: cla-signed

#26898 ci: only upload logs for main builds
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#26893 remove global EventLogs mock store
  cmd/frontend/internal/app/app.go
  cmd/frontend/internal/app/ping.go
  cmd/frontend/internal/app/ping_test.go
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/cli/serve_cmd.go
  internal/database/event_logs.go
  internal/database/event_logs_mock.go
  internal/database/mockstores.go
Labels: cla-signed

#26853 search: pass repos to structural search job
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/unindexed/structural.go
Labels: cla-signed

#26899 codeintel: Fix ignored dumps
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_references.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_references_test.go
Labels: cla-signed

#26854 search: remove Mode dependency for structural search job
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/unindexed/structural.go
Labels: cla-signed

#26856 search: add ZoektGlobalQuery abstraction
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
  internal/search/zoekt/zoekt_global.go
Labels: cla-signed

#26887 instrument gitserver search with Honeycomb logging
  cmd/gitserver/server/server.go
Labels: cla-signed

#26900 remove global mocks for SearchContextsStore
  enterprise/cmd/frontend/internal/searchcontexts/init.go
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers_test.go
  internal/database/mockstores.go
  internal/database/search_contexts.go
  internal/database/search_contexts_mock.go
  internal/search/repos/repo_groups.go
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  internal/search/searchcontexts/search_contexts.go
  internal/search/searchcontexts/search_contexts_test.go
Labels: dx, cla-signed

#26892 Disables "Go to definition" button when hovering at definition
  client/shared/src/actions/ActionItem.tsx
  client/shared/src/api/extension/api/contribution.ts
  client/shared/src/api/protocol/contribution.ts
  client/shared/src/contributions/contributions.test.ts
  client/shared/src/contributions/contributions.ts
  client/shared/src/hover/actions.test.ts
  client/shared/src/hover/actions.ts
Labels: cla-signed

#26880 ignore non-zero git error when context is cancelled
  internal/gitserver/search/search.go
Labels: cla-signed

#26691 adding launch.json debugger config
  .vscode/launch.json
Labels: cla-signed

#26771 lsifstore: add docs for regenerating testdata so others do not waste …
  enterprise/internal/codeintel/stores/lsifstore/testdata/README.md
Labels: apidocs-search, cla-signed

#26913 lsifstore: update testdata to include API docs
  enterprise/internal/codeintel/stores/lsifstore/helpers_test.go
  enterprise/internal/codeintel/stores/lsifstore/monikers_test.go
  enterprise/internal/codeintel/stores/lsifstore/packages_test.go
  enterprise/internal/codeintel/stores/lsifstore/ranges_test.go
  enterprise/internal/codeintel/stores/lsifstore/stencil_test.go
  enterprise/internal/codeintel/stores/lsifstore/testdata/README.md
  enterprise/internal/codeintel/stores/lsifstore/testdata/lsif-go@ad3507cb.sql
Labels: apidocs, cla-signed

#26560 batches: implement frontend for the webhook banner
  client/web/dev/utils/create-js-context.ts
  client/web/src/enterprise/batches/CodeHost.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.mock.ts
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx
  client/web/src/enterprise/batches/detail/WebhookAlert.module.scss
  client/web/src/enterprise/batches/detail/WebhookAlert.story.tsx
  client/web/src/enterprise/batches/detail/WebhookAlert.tsx
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/preview/MissingCredentialsAlert.tsx
  client/web/src/integration/batches.test.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
  doc/batch_changes/references/requirements.md
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#26909 convert ExternalServiceStore to an interface
  cmd/frontend/webhooks/github_webhooks.go
  enterprise/cmd/frontend/internal/auth/githuboauth/session_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/main_test.go
  enterprise/cmd/frontend/internal/batches/webhooks/gitlab_test.go
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/common.go
  enterprise/internal/batches/sources/fake.go
  enterprise/internal/batches/sources/github.go
  enterprise/internal/batches/sources/gitlab.go
  enterprise/internal/batches/sources/sources.go
  enterprise/internal/batches/sources/sources_test.go
  enterprise/internal/batches/store/store.go
  enterprise/internal/batches/syncer/mock_iface_test.go
  enterprise/internal/batches/syncer/store.go
  enterprise/internal/batches/syncer/syncer_test.go
  enterprise/internal/batches/testing/repos.go
  enterprise/internal/database/external_services.go
  internal/database/dbmock/externalservicestore_mock.go
  internal/database/dbmock/mocks.go
  internal/database/external_services.go
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
  internal/repos/store.go
Labels: dx, cla-signed

#26914 remove MockPhabricatorStore
  cmd/frontend/graphqlbackend/externallink/repository.go
  cmd/frontend/graphqlbackend/externallink/repository_test.go
  cmd/frontend/graphqlbackend/externallink/util_test.go
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/search_test.go
  internal/database/database.go
  internal/database/dbmock/db_mock.go
  internal/database/mockstores.go
  internal/database/phabricator.go
Labels: dx, cla-signed

#26920 remove global NamespaceStore mocks
  cmd/frontend/graphqlbackend/access_token.go
  cmd/frontend/graphqlbackend/event_log.go
  cmd/frontend/graphqlbackend/external_account.go
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/feature_flags.go
  cmd/frontend/graphqlbackend/namespaces.go
  cmd/frontend/graphqlbackend/namespaces_test.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitation.go
  cmd/frontend/graphqlbackend/org_members.go
  cmd/frontend/graphqlbackend/saved_searches.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/settings_cascade.go
  cmd/frontend/graphqlbackend/survey_response.go
  cmd/frontend/graphqlbackend/user.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec.go
  enterprise/cmd/frontend/internal/batches/resolvers/bulk_operation.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/dotcom/billing/customers.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/invoices_graphql.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
  enterprise/cmd/frontend/internal/registry/extension_graphql.go
  enterprise/cmd/frontend/internal/registry/publisher_connection_graphql.go
  enterprise/cmd/frontend/internal/registry/publisher_graphql.go
  enterprise/internal/batches/reconciler/executor_test.go
  internal/database/mockstores.go
  internal/database/namespaces.go
  internal/database/namespaces_mock.go
Labels: dx, cla-signed

#26793 web: codemod `web/search/results/SearchResultsInfoBar` `web/search/SearchConsolePage` `web/settings/SettingsFile` `web/settings/MonacoSettingsEditor` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/search/SearchConsolePage.module.scss
  client/web/src/search/SearchConsolePage.scss
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/results/SearchResultsInfoBar.module.scss
  client/web/src/search/results/SearchResultsInfoBar.scss
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
  client/web/src/settings/MonacoSettingsEditor.module.scss
  client/web/src/settings/MonacoSettingsEditor.tsx
  client/web/src/settings/SettingsFile.module.scss
  client/web/src/settings/SettingsFile.tsx
  client/web/src/site-admin/SiteAdminArea.module.scss
  client/web/src/site-admin/SiteAdminArea.tsx
Labels: cla-signed

#26896 ci: run slow go tests concurrently
  dev/ci/go-test.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: dx, ci, dx-announce, cla-signed

#26705 search contexts: improve validation and create/update perf
  client/web/src/enterprise/searchContexts/SearchContextForm.tsx
  client/web/src/enterprise/searchContexts/backend.ts
  client/web/src/integration/search-contexts.test.ts
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers.go
Labels: cla-signed

#26873 ChunkLoadError and AbortError handling
  client/web/src/components/ErrorBoundary.test.tsx
  client/web/src/components/ErrorBoundary.tsx
  client/web/src/components/__snapshots__/ErrorBoundary.test.tsx.snap
Labels: cla-signed

#26565 web: codemod `web/repo/tree` `web/repo/blob` components to CSS modules
  client/browser/src/shared.scss
  client/browser/src/shared/code-hosts/shared/__snapshots__/codeHost.test.tsx.snap
  client/browser/src/shared/code-hosts/shared/codeHost.test.tsx
  client/browser/src/shared/code-hosts/shared/extensions.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/repo/RepoRevisionContainer.scss
  client/web/src/repo/blob/Blob.module.scss
  client/web/src/repo/blob/Blob.scss
  client/web/src/repo/blob/Blob.tsx
  client/web/src/repo/blob/BlobPage.module.scss
  client/web/src/repo/blob/BlobPage.scss
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/LineDecorator.module.scss
  client/web/src/repo/blob/LineDecorator.scss
  client/web/src/repo/blob/LineDecorator.tsx
  client/web/src/repo/blob/RenderedFile.module.scss
  client/web/src/repo/blob/RenderedFile.tsx
  client/web/src/repo/blob/__snapshots__/LineDecorator.test.tsx.snap
  client/web/src/repo/blob/ui/BlobStatusBarContainer.module.scss
  client/web/src/repo/blob/ui/BlobStatusBarContainer.tsx
  client/web/src/repo/routes.tsx
  client/web/src/repo/tree/TreeEntriesSection.module.scss
  client/web/src/repo/tree/TreeEntriesSection.tsx
  client/web/src/repo/tree/TreePage.module.scss
  client/web/src/repo/tree/TreePage.scss
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/repo/tree/__snapshots__/TreeEntriesSection.test.tsx.snap
  client/web/src/tree/Directory.tsx
  client/web/src/tree/TreeRoot.tsx
Labels: cla-signed

#26936 Add missing metric collectors in docker registry image
  enterprise/cmd/executor/docker-mirror/install.sh
Labels: cla-signed

#26424 search: remove `repogroup` filter
  CHANGELOG.md
  client/shared/src/search/query/diagnostics.test.ts
  client/shared/src/search/query/diagnostics.ts
  client/shared/src/search/query/parserFuzz.ts
  client/shared/src/settings/settings.test.ts
  client/web/src/search/input/SearchContextDropdown.test.tsx
  client/web/src/search/panels/CommunitySearchContextPanel.story.tsx
  client/web/src/search/panels/CommunitySearchContextPanel.test.tsx
  client/web/src/search/panels/__snapshots__/CommunitySearchContextPanel.test.tsx.snap
  client/web/src/search/results/sidebar/SearchReference.tsx
  cmd/frontend/graphqlbackend/repo_groups.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_alert.go
  cmd/frontend/graphqlbackend/search_alert_test.go
  cmd/frontend/graphqlbackend/search_filter_suggestions.go
  cmd/frontend/graphqlbackend/search_filter_suggestions_test.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_suggestions.go
  dev/gqltest/search_test.go
  internal/search/query/fields.go
  internal/search/query/predicate.go
  internal/search/query/transformer_test.go
  internal/search/query/types.go
  internal/search/query/validate.go
  internal/search/repos/repo_groups.go
  internal/search/repos/repo_groups_test.go
  internal/search/repos/repos.go
  internal/search/run/repository.go
  internal/search/streaming/api/progress.go
  internal/search/streaming/api/testdata/golden/TestSearchProgress/all.json
  internal/search/streaming/api/testdata/golden/TestSearchProgress/timedout100.json
  internal/search/types.go
Labels: cla-signed

#26924 monitoring: Update possible solutions for blob_load_latency
  doc/admin/observability/alert_solutions.md
  monitoring/definitions/frontend.go
Labels: cla-signed

#26879 monitoring: Set time period for repo-updater error rate to 5m
  doc/admin/observability/alert_solutions.md
  monitoring/definitions/repo_updater.go
Labels: cla-signed

#26902 remove global mock for UserPublicRepos
  internal/database/mockstores.go
  internal/database/user_public_repos.go
  internal/database/user_public_repos_mock.go
Labels: dx, cla-signed

#26940 ci: remove Github token workaround and update LOKI_URL
  dev/ci/backend-integration.sh
  dev/ci/test/code-intel/test.sh
  enterprise/dev/upload-build-logs.sh
Labels: dx, ci, dx-announce, team/dev-experience, cla-signed

#26947 perf: Faster global settings lookup
  internal/database/schema.md
  migrations/frontend/1528395925_settings_global_index.down.sql
  migrations/frontend/1528395925_settings_global_index.up.sql
Labels: perf, cla-signed

#26857 web: codemod `web/tree` components to CSS modules
  client/web/src/SourcegraphWebApp.scss
  client/web/src/components/alerts.tsx
  client/web/src/end-to-end/end-to-end.test.ts
  client/web/src/repo/RepoRevisionContainer.scss
  client/web/src/repo/tree/__snapshots__/TreeEntriesSection.test.tsx.snap
  client/web/src/tree/ChildTreeLayer.tsx
  client/web/src/tree/Directory.tsx
  client/web/src/tree/File.tsx
  client/web/src/tree/FileDecorator.module.scss
  client/web/src/tree/FileDecorator.scss
  client/web/src/tree/FileDecorator.tsx
  client/web/src/tree/SingleChildTreeLayer.tsx
  client/web/src/tree/Tree.module.scss
  client/web/src/tree/Tree.scss
  client/web/src/tree/Tree.tsx
  client/web/src/tree/TreeLayer.tsx
  client/web/src/tree/TreeRoot.tsx
  client/web/src/tree/__snapshots__/FileDecorator.test.tsx.snap
  client/web/src/tree/components/TreeLayerCell.module.scss
  client/web/src/tree/components/TreeLayerCell.tsx
  client/web/src/tree/components/TreeLayerRowContents.module.scss
  client/web/src/tree/components/TreeLayerRowContents.tsx
  client/web/src/tree/components/TreeLayerRowContentsText.module.scss
  client/web/src/tree/components/TreeLayerRowContentsText.tsx
  client/web/src/tree/components/TreeLayerTable.module.scss
  client/web/src/tree/components/TreeLayerTable.tsx
  client/web/src/tree/components/TreeRow.module.scss
  client/web/src/tree/components/TreeRow.tsx
  client/web/src/tree/components/TreeRowAlert.module.scss
  client/web/src/tree/components/TreeRowAlert.tsx
  client/web/src/tree/components/TreeRowIcon.module.scss
  client/web/src/tree/components/TreeRowIcon.tsx
  client/web/src/tree/components/TreeRowLabel.module.scss
  client/web/src/tree/components/TreeRowLabel.tsx
  client/web/src/tree/components/index.ts
Labels: cla-signed

#26953 Added clarity to code host access tokens verbiage
  doc/batch_changes/explanations/permissions_in_batch_changes.md
Labels: cla-signed

#26961 doc: Update Postgres getting started instructions
  doc/dev/getting-started/quickstart_1_install_dependencies.md
Labels: cla-signed

#26965 web: highlight selected line in blobs
  client/web/src/repo/blob/Blob.module.scss
Labels: bug, team/frontend-platform, cla-signed

#26964 ci: ignore soft failures when uploading logs
  dev/sg/internal/bk/bk.go
Labels: dx, ci, cla-signed

#26958 database: exclude deleted services when calculating webhook status
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/oob_migrate.go
  internal/database/oob_migrate_test.go
Labels: team/batchers, webhooks, cla-signed

#26916 executors: add node_exporter dashboards for executor and docker mirror nodes
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/executor.go
  monitoring/definitions/shared/node_exporter.go
Labels: user-code-execution, cla-signed

#26915 search: create symbol search over repos function
  internal/search/symbol/symbol.go
Labels: cla-signed

#26962 fix transactions with database.DB type
  internal/database/basestore/handle.go
  internal/database/database.go
  internal/database/database_test.go
  internal/database/dbmock/db_mock.go
  internal/database/dbmock/repostore_mock.go
  internal/database/dbutil/dbutil.go
  internal/database/repos.go
Labels: dx, cla-signed

#26954 lsifstore: add API docs tests
  enterprise/internal/codeintel/stores/lsifstore/data_write_documentation_test.go
  enterprise/internal/codeintel/stores/lsifstore/documentation_test.go
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestDocumentationPage.golden
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestWriteDocumentationPathInfo/query_path_info.golden
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestWriteDocumentationUpload/query_the_page.golden
Labels: apidocs, apidocs-search, cla-signed, apidocs-tests

#26745 authz/perforce: sync sub-repo permissions
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/authz/perforce/authz.go
  enterprise/internal/authz/perforce/perforce.go
  enterprise/internal/authz/perforce/perforce_test.go
  enterprise/internal/authz/perforce/protects.go
  enterprise/internal/authz/perforce/protects_test.go
  enterprise/internal/authz/perforce/testdata/sample-protects-a.txt
  enterprise/internal/authz/perforce/testdata/sample-protects-u.txt
  internal/authz/iface.go
  schema/perforce.schema.json
  schema/schema.go
Labels: cla-signed

#26888 refactor gitserver search errors and instrumentation
  cmd/gitserver/server/server.go
Labels: cla-signed

#26928 Remove `acceptSearchSuggestionOnEnter` experimental feature
  client/shared/src/settings/settings.ts
  client/web/src/search/input/MonacoQueryInput.story.tsx
  client/web/src/search/input/MonacoQueryInput.tsx
  client/web/src/search/input/SearchBox.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#26842 authz: Add a basic SubRepoPerms client
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/database/mockstores.go
  internal/authz/sub_repo_perms.go
  internal/database/mockstores.go
  internal/database/sub_repo_perms_store.go
  internal/database/sub_repo_perms_store_test.go
Labels: team/repo-management, cla-signed

#26984 sg: correctly download jaeger
  sg.config.yaml
Labels: cla-signed

#26937 Implement retryBatchSpecWorkspaces
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/store/batch_spec_workspace.go
  enterprise/internal/batches/store/batch_spec_workspace_execution_jobs.go
  enterprise/internal/batches/store/batch_spec_workspace_execution_jobs_test.go
  enterprise/internal/batches/store/batch_spec_workspace_test.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/store/changeset_specs_test.go
  enterprise/internal/batches/store/store.go
  enterprise/internal/batches/types/batch_spec_workspace_execution_job.go
Labels: cla-signed

#26982 web: lazy-load `@sentry/browser`
  client/shared/dev/mockSentryBrowser.ts
  client/web/src/components/ErrorBoundary.tsx
  client/web/src/sentry.ts
  cmd/frontend/internal/app/ui/app.html
  jest.config.base.js
Labels: team/frontend-platform, UI performance, cla-signed

#26990 database: introduce Cursors
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repository_cursor.go
  cmd/frontend/graphqlbackend/repository_cursor_test.go
  cmd/frontend/graphqlbackend/user.go
  internal/database/cursor.go
  internal/database/repos.go
Labels: cla-signed

#26986 search: remove support for names in configuration endpoint
  cmd/frontend/internal/httpapi/search.go
  internal/search/backend/index_options.go
  internal/search/backend/index_options_test.go
Labels: cla-signed

#26989 monitoring: Set time period for repo-updater error rate to 15m
  doc/admin/observability/alert_solutions.md
  monitoring/definitions/repo_updater.go
Labels: cla-signed

#26944 migrations/frontend: Drop redundant indexes on sub_repo_permissions
  internal/database/schema.md
  migrations/frontend/1528395926_drop_redundant_sub_repo_perms_index.down.sql
  migrations/frontend/1528395926_drop_redundant_sub_repo_perms_index.up.sql
Labels: performance, cla-signed

#26996 conf: Add config option for sub-repo permissions checking
  internal/authz/sub_repo_perms.go
  schema/schema.go
  schema/site.schema.json
Labels: team/repo-management, cla-signed

#27000 Make sg installation first step in onboarding docs
  doc/dev/background-information/continuous_integration.md
  doc/dev/background-information/web/web_app.md
  doc/dev/getting-started/index.md
  doc/dev/getting-started/quickstart_1_install_sg.md
  doc/dev/getting-started/quickstart_2_install_dependencies.md
  doc/dev/getting-started/quickstart_3_clone_repository.md
  doc/dev/getting-started/quickstart_3_install_sg.md
  doc/dev/getting-started/quickstart_4_start_docker.md
  doc/dev/getting-started/quickstart_7_start_server.md
  doc/dev/index.md
Labels: dx, sg, cla-signed

#26979 [CLOUD-78] external_services: upsert "authorization" field in `Upsert` method
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  internal/database/external_services.go
  internal/database/external_services_test.go
Labels: cla-signed

#26945 remove global mock for UserCredentialsStore
  internal/database/mockstores.go
  internal/database/user_credentials.go
  internal/database/user_credentials_mock.go
Labels: dx, cla-signed

#27004 external_services: adjust the behavior of `ExcludeNamespaceUser` option
  internal/database/external_services.go
Labels: cla-signed

#27006 graphqlbackend: fix tests what are not printing the actual error
  cmd/frontend/graphqlbackend/org_test.go
Labels: cla-signed

#26966 remove global mocks for SettingsStore
  cmd/frontend/backend/external_services.go
  cmd/frontend/backend/orgs.go
  cmd/frontend/backend/site_admin.go
  cmd/frontend/backend/user_emails.go
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/graphqlbackend/access_token.go
  cmd/frontend/graphqlbackend/access_tokens.go
  cmd/frontend/graphqlbackend/default_settings.go
  cmd/frontend/graphqlbackend/execution_log_entry.go
  cmd/frontend/graphqlbackend/external_account.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/orgs.go
  cmd/frontend/graphqlbackend/person.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/settings.go
  cmd/frontend/graphqlbackend/settings_mutation.go
  cmd/frontend/graphqlbackend/settings_mutation_test.go
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/site_usage_stats.go
  cmd/frontend/graphqlbackend/survey_responses.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_emails.go
  cmd/frontend/graphqlbackend/users.go
  cmd/frontend/graphqlbackend/users_create.go
  cmd/frontend/internal/app/debug.go
  cmd/frontend/internal/app/debugproxies/handler.go
  cmd/frontend/internal/app/ping_test.go
  cmd/frontend/internal/app/usage_stats.go
  cmd/frontend/internal/app/usage_stats_test.go
  enterprise/cmd/frontend/internal/authz/init.go
  enterprise/cmd/frontend/internal/authz/resolvers/repositories.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/users.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/dotcom/billing/customers_graphql.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/invoices_graphql.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
  enterprise/cmd/frontend/internal/registry/publisher_graphql.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_apply_batch_change.go
  internal/database/mockstores.go
  internal/database/settings.go
  internal/database/settings_mock.go
  internal/search/searchcontexts/search_contexts.go
  internal/search/searchcontexts/search_contexts_test.go
Labels: dx, cla-signed

#26994 database: add Stars field to RepoName
  internal/database/repos.go
  internal/types/types.go
Labels: cla-signed

#27007 search: extract excluded repos counting from repo resolution
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
Labels: cla-signed

#26970 remove global mocks for OrgInvitationStore
  cmd/frontend/backend/external_services.go
  cmd/frontend/backend/external_services_test.go
  cmd/frontend/backend/orgs.go
  cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/status_messages.go
  internal/database/mockstores.go
  internal/database/org_invitations.go
Labels: dx, cla-signed

#26808 Insights/api/page views in dashboard
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/resolvers/dashboard_resolvers.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/no_users_or_orgs_provided_should_only_return_global.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/org_5_can_see_the_view.golden
  enterprise/internal/insights/store/testdata/TestCreateGetView_WithGrants/user_1_can_see_this_view.golden
  enterprise/internal/insights/types/types.go
Labels: cla-signed

#26960 code-intel: fix multiple fetch and re-indexing per open modal
  client/web/src/components/fuzzyFinder/FuzzyFinder.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
Labels: cla-signed

#26971 remove global mocks for FeatureFlagStore
  cmd/frontend/backend/orgs.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_test.go
  cmd/frontend/graphqlbackend/orgs.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/settings_cascade.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/registry/publisher_graphql.go
  enterprise/internal/batches/service/service.go
  internal/database/feature_flags.go
  internal/database/feature_flags_mock.go
  internal/database/mockstores.go
Labels: dx, cla-signed

#27026 [cloud][CLOUD-84] Improve performance of repo list queries
  internal/database/repos.go
Labels: cla-signed

#27008 authz: simplify SubRepoPermissionChecker, add SubRepoPermissionsSupportedChecker
  internal/authz/iface.go
  internal/authz/sub_repo_perms.go
Labels: team/repo-management, cla-signed

#27038 authz: fix SubRepoPerms enabled check, add mock
  internal/authz/mock_sub_repo_perms.go
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#26973 lsifstore: add ability to query API docs search index - take 2
  enterprise/internal/codeintel/stores/lsifstore/documentation.go
  enterprise/internal/codeintel/stores/lsifstore/documentation_test.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  enterprise/internal/codeintel/stores/lsifstore/testdata/TestDocumentationSearch_resultData.golden
  internal/database/basestore/rows.go
  lib/codeintel/precise/types.go
Labels: apidocs-search, cla-signed

#26985 ci: add timestamps in bare metal agents
  dev/ci/test/Vagrantfile
Labels: dx, ci, team/dev-experience, cla-signed

#26822 Insights/api/fix view paging
  enterprise/internal/insights/store/insight_store.go
Labels: cla-signed

#27034 insights: allow empty repository array for global series
  enterprise/internal/insights/store/insight_store.go
Labels: cla-signed

#27037 convert SubRepoPermsStore to an interface
  internal/database/database.go
  internal/database/dbmock/db_mock.go
  internal/database/dbmock/mocks.go
  internal/database/dbmock/subrepopermsstore_mock.go
  internal/database/sub_repo_perms_store.go
  internal/database/sub_repo_perms_store_test.go
Labels: dx, cla-signed

#27051 worker: refactor packages to allow for OSS usage
  cmd/worker/job/job.go
  cmd/worker/memo/memo.go
  cmd/worker/shared/job.go
  cmd/worker/shared/main.go
  cmd/worker/workerdb/db.go
  cmd/worker/workerdb/service_connections.go
  enterprise/cmd/worker/internal/batches/janitor_job.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/cmd/worker/internal/codeintel/commitgraph_job.go
  enterprise/cmd/worker/internal/codeintel/dbstore.go
  enterprise/cmd/worker/internal/codeintel/gitserver.go
  enterprise/cmd/worker/internal/codeintel/indexing_job.go
  enterprise/cmd/worker/internal/codeintel/janitor_job.go
  enterprise/cmd/worker/internal/codeintel/lsifstore.go
  enterprise/cmd/worker/internal/executorqueue/config.go
  enterprise/cmd/worker/internal/insights/job.go
  enterprise/cmd/worker/main.go
  internal/extsvc/versions/sync.go
Labels: cla-signed

#27039 codeintel: expose GraphQL API for API docs search
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/codeintel_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_documentation_search.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/observability.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
Labels: apidocs-search, cla-signed

#27054 authz: Make SubRepoPermsClient.Permissions private
  internal/authz/sub_repo_perms.go
Labels: team/repo-management, cla-signed

#26988 doc: add missing --host flag for createdb
  doc/dev/getting-started/quickstart_5_initialize_database.md
Labels: docs, sg, cla-signed

#27005 search: remove support for names in serveIndex
  cmd/frontend/internal/httpapi/search.go
  cmd/frontend/internal/httpapi/search_test.go
Labels: cla-signed

#26997 Extract createChangesetSpecs from src-cli
  go.sum
  lib/batches/batch_spec_test.go
  lib/batches/changeset_specs.go
  lib/batches/changeset_specs_test.go
  lib/batches/execution/results.go
  lib/batches/git/refs.go
  lib/batches/template/templating.go
  lib/batches/template/templating_test.go
  lib/go.mod
  lib/go.sum
Labels: cla-signed

#27056 search: deprecate GraphQL suggestions
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed

#27066 search contexts: fix repository resolving
  dev/gqltest/search_test.go
  internal/database/repos.go
  internal/gqltestutil/search.go
  internal/gqltestutil/search_context.go
  internal/search/repos/repos.go
Labels: cla-signed

#27061 SSBC caching: Add cache events to json logs
  lib/batches/json_logs.go
Labels: cla-signed

#27067 database: remove unused PatternQuery
  internal/database/query/query.go
  internal/database/query/query_test.go
  internal/database/repos.go
  internal/database/repos_db_test.go
Labels: cla-signed

#26744 insights: add/remove data series, update series visual metadata
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
Labels: team/code-insights, cla-signed

#27068 search: make it possible to test configuration handler
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/search.go
  cmd/frontend/internal/httpapi/search_test.go
Labels: cla-signed

#27071 vcs/git: Make LStat private
  internal/vcs/git/file_info.go
  internal/vcs/git/tree.go
  internal/vcs/git/tree_test.go
Labels: team/repo-management, cla-signed

#26855 insights: update series query data
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
  enterprise/internal/insights/store/testdata/TestFindMatchingSeries/find_a_matching_series_when_one_exists.golden
  enterprise/internal/insights/store/testdata/TestFindMatchingSeries/find_no_matching_series_when_none_exist.golden
Labels: team/code-insights, cla-signed

#27069 database: Add RepoSupported to SubRepoPermsStore
  internal/authz/sub_repo_perms.go
  internal/database/dbmock/subrepopermsstore_mock.go
  internal/database/sub_repo_perms_store.go
  internal/database/sub_repo_perms_store_test.go
Labels: team/repo-management, cla-signed

#26980 sg: add a --build flag to status and logs commands
  dev/sg/internal/bk/bk.go
  dev/sg/sg_ci.go
  doc/dev/background-information/sg/index.md
Labels: dx, ci, dx-announce, team/dev-experience, cla-signed

#27076 authz: make SubRepoPermissionChecker only have Permissions
  internal/authz/mock_sub_repo_perms.go
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#27084 generate descriptions in advance to speed up schemadoc
  internal/database/schemadoc/main.go
Labels: dx, cla-signed

#27040 Insights/api/default applied filters
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
Labels: cla-signed

#27085 ci: use build number to reliably identify build
  enterprise/dev/upload-build-logs.sh
Labels: dx, ci, team/dev-experience, cla-signed

#27092 search: fix race condition in doResults
  cmd/frontend/graphqlbackend/search_results.go
Labels: cla-signed

#27099 run schemadoc against dbs in parallel
  internal/database/schemadoc/main.go
Labels: cla-signed

#27047 search: create symbol search job
  internal/search/symbol/symbol.go
Labels: cla-signed

#27048 search: migrate to symbol search job
  cmd/frontend/graphqlbackend/search_results.go
Labels: cla-signed

#27086 Add code insights background jobs to the worker documentation
  doc/admin/workers.md
Labels: cla-signed

#27107 move migrators into oobmigration package
  cmd/frontend/internal/cli/serve_cmd.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/oobmigration/migrators.go
  internal/oobmigration/migrators_test.go
Labels: dx, cla-signed

#26699 batches: webhook delivery tracking backend
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/webhook_logs.go
  cmd/frontend/graphqlbackend/webhook_logs_test.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/webhooks/github_webhooks.go
  cmd/frontend/webhooks/middleware.go
  cmd/frontend/webhooks/middleware_test.go
  cmd/worker/shared/job.go
  cmd/worker/webhooks/handler.go
  cmd/worker/webhooks/handler_test.go
  cmd/worker/webhooks/janitor.go
  doc/admin/workers.md
  enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
  enterprise/cmd/frontend/internal/batches/webhooks/gitlab.go
  internal/database/database.go
  internal/database/dbmock/db_mock.go
  internal/database/dbmock/mocks.go
  internal/database/dbmock/webhooklogstore_mock.go
  internal/database/schema.md
  internal/database/webhook_logs.go
  internal/database/webhook_logs_test.go
  internal/encryption/keyring/ring.go
  internal/types/webhook_logs.go
  migrations/frontend/1528395927_webhook_logs.down.sql
  migrations/frontend/1528395927_webhook_logs.up.sql
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#27104 convert some tests to use new mock stores
  cmd/frontend/auth/user.go
  cmd/frontend/auth/user_test.go
  cmd/frontend/graphqlbackend/site_admin.go
  cmd/frontend/graphqlbackend/site_admin_test.go
  cmd/frontend/internal/auth/override.go
  enterprise/cmd/frontend/internal/auth/githuboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go
  enterprise/cmd/frontend/internal/auth/httpheader/middleware.go
  enterprise/cmd/frontend/internal/auth/openidconnect/user.go
  enterprise/cmd/frontend/internal/auth/saml/user.go
  internal/database/database.go
  internal/database/dbmock/authzstore_mock.go
  internal/database/dbmock/db_mock.go
  internal/database/dbmock/mocks.go
Labels: dx, cla-signed

#27115 db: Break dependency of RepoStore on ExternalServiceStore
  cmd/frontend/graphqlbackend/repository_external.go
  internal/database/dbmock/repostore_mock.go
  internal/database/repos.go
  internal/database/repos_db_test.go
Labels: cla-signed

#27105 push database.DB down from top of call tree
  cmd/frontend/auth/non_public_test.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/router.go
  cmd/frontend/internal/app/ui/router_test.go
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/main.go
  cmd/frontend/shared/frontend.go
  enterprise/cmd/frontend/main.go
Labels: dx, cla-signed

#27121 Remove Stephan from label notifications
  .github/workflows/label-notify.yml
Labels: cla-signed

#27065 Fix browser extension low quality toolbar icon
  client/browser/assets/img/icon-16.png
  client/browser/assets/img/icon-32.png
  client/browser/assets/img/icon-active-with-alert-16.png
  client/browser/assets/img/icon-active-with-alert-32.png
  client/browser/assets/img/icon-inactive-16.png
  client/browser/assets/img/icon-inactive-32.png
  client/browser/src/browser-extension/browser-action-icon.ts
  client/browser/src/browser-extension/manifest.spec.json
Labels: cla-signed

#27096 sg: add a check for go version and docker-compose
  sg.config.yaml
Labels: dx, sg, cla-signed

#27118 db: Don't log security event twice
  internal/database/repos.go
Labels: cla-signed

#27072 search: test for configuration httpapi
  cmd/frontend/internal/httpapi/db_test.go
  cmd/frontend/internal/httpapi/search_test.go
Labels: cla-signed

#27113 perf: Hit index in GetSearchContextRepositoryRevisions
  internal/database/search_contexts.go
Labels: perf, cla-signed

#27114 gitserver: Remove expensive count operation
  cmd/gitserver/server/server.go
Labels: perf, cla-signed

#27125 Add batch_spec_execution_cache_entries table
  enterprise/internal/batches/store/batch_spec_execution_cache_entry.go
  enterprise/internal/batches/store/batch_spec_execution_cache_entry_test.go
  enterprise/internal/batches/store/integration_test.go
  enterprise/internal/batches/store/store.go
  enterprise/internal/batches/types/batch_spec_execution_cache_entry.go
  internal/database/schema.md
  migrations/frontend/1528395928_add_batch_spec_execution_cache_entries.down.sql
  migrations/frontend/1528395928_add_batch_spec_execution_cache_entries.up.sql
Labels: cla-signed

#27126 ci: avoid diffing svg in go-generate.sh
  dev/check/go-generate.sh
Labels: ci, ci/flake, cla-signed

#27102 insights: migrate langstats insights
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/types/types.go
  internal/insights/insights.go
  internal/usagestats/code_insights_test.go
  migrations/codeinsights/1000000019_other_threshold.down.sql
  migrations/codeinsights/1000000019_other_threshold.up.sql
Labels: team/code-insights, cla-signed

#27117 db: Add missing `star` column to ListIndexableRepos
  internal/database/dbcache/cached_indexable_repos_test.go
  internal/database/repos.go
Labels: cla-signed

#27112 perf: Don't RPC all repo names from frontend to repo-updater
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/httpapi/router/router.go
  cmd/repo-updater/shared/main.go
  internal/api/internal_client.go
  internal/database/dbmock/repostore_mock.go
  internal/database/repos.go
  internal/repos/purge.go
Labels: perf, cla-signed

#27116 db: Cleanup repo store
  internal/database/repos.go
  internal/database/repos_db_test.go
  internal/database/repos_test.go
  internal/database/schema.md
  migrations/frontend/1528395929_external_service_repos_clone_url.down.sql
  migrations/frontend/1528395929_external_service_repos_clone_url.up.sql
Labels: perf, cla-signed

#27128 Update label-notify for search teams
  .github/workflows/label-notify.yml
Labels: cla-signed

#27080 Extract importing changesets into lib
  enterprise/internal/batches/service/service.go
  lib/batches/changeset_specs.go
Labels: cla-signed

#27111 Reduce load of updatecheck payload
  cmd/frontend/internal/app/updatecheck/client.go
Labels: perf, cla-signed

#27119 add DB method to mocks
  cmd/frontend/auth/user_test.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/internal/auth/userpasswd/handlers.go
  cmd/frontend/internal/httpapi/telemetry.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  internal/usagestats/event_handlers.go
  internal/usagestats/usage_stats_test.go
Labels: cla-signed

#27131 Label notify: notify all PM/EMs on catch-all label
  .github/workflows/label-notify.yml
Labels: cla-signed

#27120 clean up some unnecessary uses of dbtest.NewDB
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/internal/app/editor.go
  cmd/frontend/internal/auth/override.go
  cmd/frontend/internal/auth/override_test.go
  cmd/frontend/internal/auth/userpasswd/handlers.go
  cmd/frontend/internal/auth/userpasswd/handlers_test.go
  cmd/frontend/internal/cloneurls/clone_urls.go
  cmd/frontend/internal/cloneurls/clone_urls_test.go
Labels: cla-signed

#27073 dbtesting: detect pkg name
  cmd/frontend/backend/versions_test.go
  cmd/frontend/graphqlbackend/db_test.go
  cmd/frontend/internal/app/ping_test.go
  cmd/frontend/internal/app/usage_stats_test.go
  cmd/frontend/internal/bg/db_test.go
  cmd/frontend/internal/confdb/db_test.go
  cmd/frontend/internal/httpapi/db_test.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/dotcom/billing/db_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/db_test.go
  enterprise/cmd/frontend/internal/registry/db_test.go
  enterprise/internal/codeintel/stores/dbstore/migration/migration_test.go
  enterprise/internal/codeintel/stores/dbstore/store_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/migration_test.go
  enterprise/internal/codeintel/stores/lsifstore/store_test.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/storetest/monitor_creator.go
  enterprise/internal/database/db_test.go
  enterprise/internal/insights/background/queryrunner/worker_test.go
  enterprise/internal/insights/resolvers/resolver_test.go
  internal/codeintel/stores/dbstore/store_test.go
  internal/database/basestore/store_test.go
  internal/database/batch/batch_test.go
  internal/database/dbcache/main_test.go
  internal/database/dbtesting/dbtesting.go
  internal/database/dbtesting/dbtesting_test.go
  internal/database/globalstatedb/db_test.go
  internal/database/main_test.go
  internal/insights/insights_test.go
  internal/oobmigration/store_test.go
  internal/search/searchcontexts/search_contexts_test.go
  internal/usagestats/main_test.go
  internal/workerutil/dbworker/store/main_test.go
  migrations/migrations_test.go
Labels: cla-signed

#25604 Start with 'sg setup'
  dev/check/no-localhost-guard.sh
  dev/sg/main.go
  dev/sg/sg_install.go
  dev/sg/sg_setup.go
  doc/dev/background-information/continuous_integration.md
  doc/dev/background-information/postgresql.md
  doc/dev/background-information/web/web_app.md
  doc/dev/getting-started/configure_postgresql.md
  doc/dev/getting-started/deprecated_quickstart.md
  doc/dev/getting-started/index.md
  doc/dev/getting-started/quickstart.md
  doc/dev/getting-started/quickstart_1_install_sg.md
  doc/dev/getting-started/quickstart_2_install_dependencies.md
  doc/dev/getting-started/quickstart_3_clone_repository.md
  doc/dev/getting-started/quickstart_4_start_docker.md
  doc/dev/getting-started/quickstart_5_initialize_database.md
  doc/dev/getting-started/quickstart_6_configure_https_reverse_proxy.md
  doc/dev/getting-started/quickstart_7_start_server.md
  doc/dev/getting-started/quickstart_8_additional_resources.md
  doc/dev/index.md
  lib/output/style.go
Labels: dx, cla-signed

#26154 search: No results page
  CHANGELOG.md
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/search/documentation/ModalVideo.tsx
  client/web/src/search/input/toggles/QueryInputToggle.tsx
  client/web/src/search/input/toggles/Toggles.module.scss
  client/web/src/search/input/toggles/Toggles.tsx
  client/web/src/search/notebook/SearchNotebook.story.tsx
  client/web/src/search/notebook/SearchNotebookQueryBlock.story.tsx
  client/web/src/search/notebook/SearchNotebookQueryBlock.tsx
  client/web/src/search/results/AnnotatedSearchExample.module.scss
  client/web/src/search/results/AnnotatedSearchExample.tsx
  client/web/src/search/results/NoResultsPage.module.scss
  client/web/src/search/results/NoResultsPage.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/StreamingSearchResultsFooter.module.scss
  client/web/src/search/results/StreamingSearchResultsFooter.tsx
  client/web/src/search/results/StreamingSearchResultsList.tsx
  client/web/src/settings/temporary/TemporarySettings.ts
  ui/assets/img/vt-diff-and-commit-dark.png
  ui/assets/img/vt-diff-and-commit-light.png
  ui/assets/img/vt-diff-and-commit-search-dark.png
  ui/assets/img/vt-diff-and-commit-search-light.png
  ui/assets/img/vt-finding-error-messages-dark.png
  ui/assets/img/vt-finding-error-messages-light.png
  ui/assets/img/vt-structural-search-dark.png
  ui/assets/img/vt-structural-search-light.png
  ui/assets/img/vt-three-ways-to-search-dark.png
  ui/assets/img/vt-three-ways-to-search-light.png
Labels: cla-signed

#27142 perf: Don't request repo.Sources in search configuration endpoint
  cmd/frontend/internal/httpapi/search.go
  internal/database/repos.go
Labels: perf, cla-signed

#27091 authz: disable p4 repo-centric sync with sub-repo perms
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/internal/authz/perforce/perforce.go
  internal/authz/iface.go
  internal/authz/iface_test.go
Labels: cla-signed

#27127 Display milestone of issues in tracking issues
  internal/cmd/tracking-issue/issue.go
  internal/cmd/tracking-issue/main_test.go
  internal/cmd/tracking-issue/render.go
  internal/cmd/tracking-issue/search.go
  internal/cmd/tracking-issue/testdata/fixtures.json
  internal/cmd/tracking-issue/testdata/issue-13675.md
  internal/cmd/tracking-issue/testdata/issue-13987.md
  internal/cmd/tracking-issue/testdata/issue-13988.md
  internal/cmd/tracking-issue/testdata/issue-14166.md
  internal/cmd/tracking-issue/testdata/last-update.txt
Labels: ops & tools & dev, dx, cla-signed
