Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2021-05, with the labels that each got.

#20435 Implement API layer for bulk comments
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/graphqlbackend/node.go
  enterprise/internal/batches/background/background.go
  enterprise/internal/batches/background/bulk_processor_worker.go
  enterprise/internal/batches/resolvers/apitest/types.go
  enterprise/internal/batches/resolvers/batch_change.go
  enterprise/internal/batches/resolvers/bulk_operation.go
  enterprise/internal/batches/resolvers/bulk_operation_connection.go
  enterprise/internal/batches/resolvers/bulk_operation_connection_test.go
  enterprise/internal/batches/resolvers/bulk_operation_test.go
  enterprise/internal/batches/resolvers/changeset_job_error.go
  enterprise/internal/batches/resolvers/main_test.go
  enterprise/internal/batches/resolvers/permissions_test.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/resolvers/resolver_test.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/store/batch_specs.go
  enterprise/internal/batches/store/bulk_operations.go
  enterprise/internal/batches/store/bulk_operations_test.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/store/changeset_jobs_test.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/store/integration_test.go
  enterprise/internal/batches/store/store.go
  enterprise/internal/batches/types/bulk_operation.go
  enterprise/internal/batches/types/changeset_job.go
  internal/database/schema.md
  migrations/frontend/1528395820_changeset_job_indexes.down.sql
  migrations/frontend/1528395820_changeset_job_indexes.up.sql
Labels: team/batchers

#20514 web: extract redesign-toggle-decorator from redesign-toggle-toolbar
  client/shared/src/util/useRedesignToggle.ts
  client/storybook/src/RedesignToggleDecorator.tsx
  client/storybook/src/preview.ts
  client/storybook/src/redesign-toggle-toolbar/RedesignToggleStorybook.tsx
Labels: merge-on-any-approve, team/frontend-platform

#20600 ci: Index lib/ and enterprise/lib
  .github/workflows/lsif.yml
Labels: team/code-intelligence

#20584 Refactor some more usages of dbconn.Global
  cmd/frontend/backend/repos.go
  cmd/frontend/internal/bg/delete_old_event_logs_in_postgres.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  enterprise/cmd/frontend/internal/registry/extensions_db_test.go
  enterprise/cmd/frontend/internal/registry/publisher_graphql.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  enterprise/internal/codeintel/stores/dbstore/dumps_test.go
  enterprise/internal/codeintel/stores/dbstore/helpers_test.go
  enterprise/internal/codeintel/stores/dbstore/index_configuration_test.go
  enterprise/internal/codeintel/stores/dbstore/indexable_repos_test.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/janitor_test.go
  enterprise/internal/codeintel/stores/dbstore/lock_test.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at_test.go
  enterprise/internal/codeintel/stores/dbstore/packages_test.go
  enterprise/internal/codeintel/stores/dbstore/references_test.go
  enterprise/internal/codeintel/stores/dbstore/repo_usage_test.go
  enterprise/internal/codeintel/stores/dbstore/repos_test.go
  enterprise/internal/codeintel/stores/dbstore/store_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_test.go
  enterprise/internal/codeintel/stores/lsifstore/clear_test.go
  enterprise/internal/codeintel/stores/lsifstore/exists_test.go
  enterprise/internal/codeintel/stores/lsifstore/hover_test.go
  enterprise/internal/codeintel/stores/lsifstore/locations_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/diagnostics_count_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/document_column_split_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/locations_count_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/migrator_test.go
  enterprise/internal/codeintel/stores/lsifstore/monikers_test.go
  enterprise/internal/codeintel/stores/lsifstore/packages_test.go
  enterprise/internal/codeintel/stores/lsifstore/ranges_test.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/resolvers/main_test.go
  enterprise/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/codemonitors/storetest/monitor_creator.go
  enterprise/internal/database/authz_test.go
  internal/database/basestore/store_test.go
  internal/database/batch/batch_test.go
  internal/database/stores.go
  internal/database/users_test.go
  internal/oobmigration/store_test.go
Labels: debt

#20551 Attach default reviewers to bitbucket server PRs
  CHANGELOG.md
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/bitbucketserver_test.go
  enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_abbreviated refs
  enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_already exists
  enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_CreateChangeset_success
  enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_abbreviated-refs.yaml
  enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_already-exists.yaml
  enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_CreateChangeset_success.yaml
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
  internal/extsvc/bitbucketserver/testdata/golden/CreatePullRequest-description-includes-GFM-tasklist-items
  internal/extsvc/bitbucketserver/testdata/golden/CreatePullRequest-success
  internal/extsvc/bitbucketserver/testdata/golden/FetchDefaultReviewers-success
  internal/extsvc/bitbucketserver/testdata/vcr/CreatePullRequest-description-includes-GFM-tasklist-items.yaml
  internal/extsvc/bitbucketserver/testdata/vcr/CreatePullRequest-pull-request-already-exists.yaml
  internal/extsvc/bitbucketserver/testdata/vcr/CreatePullRequest-success.yaml
  internal/extsvc/bitbucketserver/testdata/vcr/CreatePullRequestComment-success.yaml
  internal/extsvc/bitbucketserver/testdata/vcr/FetchDefaultReviewers-success.yaml
Labels: bug, team/batchers

#20545 Design Refresh: Update colors story
  client/branded/src/global-styles/GlobalStylesStory/ColorVariants/ColorVariants.module.scss
  client/branded/src/global-styles/GlobalStylesStory/ColorVariants/ColorVariants.tsx
  client/branded/src/global-styles/GlobalStylesStory/ColorVariants/index.ts
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/GlobalStylesStory/utils.ts
Labels: team/frontend-platform

#20604 Fix spacing in stats card
  client/web/src/enterprise/batches/detail/BatchChangeStatsCard.tsx
Labels: team/batchers

#20632 Design refresh: Update outline Button focus styles
  client/branded/src/global-styles/buttons-redesign.scss
Labels: team/frontend-platform

#20641 web: fix breakpoints mixins import
  client/branded/src/global-styles/breakpoints.scss
  doc/dev/background-information/web/styling.md
Labels: team/frontend-platform

#20569 Fix: Extension ID hash function high collision rate
  client/shared/src/api/extension/activation.ts
  client/shared/src/util/hashCode.test.ts
  client/shared/src/util/hashCode.ts
Labels: bug, team/extensibility

#20385 Refresh design navbar
  client/shared/src/commandPalette/CommandList.tsx
  client/shared/src/components/icons.tsx
  client/web/src/Layout.tsx
  client/web/src/components/shared.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
  client/web/src/nav/GlobalNavbar.scss
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/nav/UserNavItem.scss
  client/web/src/nav/UserNavItem.story.tsx
  client/web/src/nav/UserNavItem.test.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/nav/__snapshots__/NavLinks.test.tsx.snap
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/web/src/user/UserAvatar.scss
  client/web/src/user/UserAvatar.test.tsx
  client/web/src/user/UserAvatar.tsx
  client/web/src/user/area/UserAreaHeader.scss
  client/wildcard/src/components/NavBar/NavAction.module.scss
  client/wildcard/src/components/NavBar/NavBar.module.scss
  client/wildcard/src/components/NavBar/NavBar.tsx
  client/wildcard/src/components/NavBar/NavItem.module.scss
  client/wildcard/src/components/NavBar/index.tsx
Labels: design refresh, team/frontend-platform

#20643 Refresh: update active button color
  client/branded/src/global-styles/buttons-redesign.scss
Labels: team/frontend-platform

#20619 graphql: Only site admin can list users
  CHANGELOG.md
  cmd/frontend/graphqlbackend/users.go
Labels: team/core-application

#20644 Revert reverted dbconn migration commits
  cmd/frontend/backend/configuration.go
  cmd/frontend/backend/repos.go
  cmd/frontend/internal/bg/delete_old_event_logs_in_postgres.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  enterprise/cmd/frontend/internal/registry/extensions_db_test.go
  enterprise/cmd/frontend/internal/registry/publisher_graphql.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/batches/syncer/syncer_test.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  enterprise/internal/codeintel/stores/dbstore/dumps_test.go
  enterprise/internal/codeintel/stores/dbstore/helpers_test.go
  enterprise/internal/codeintel/stores/dbstore/index_configuration_test.go
  enterprise/internal/codeintel/stores/dbstore/indexable_repos_test.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/janitor_test.go
  enterprise/internal/codeintel/stores/dbstore/lock_test.go
  enterprise/internal/codeintel/stores/dbstore/migration/committed_at_test.go
  enterprise/internal/codeintel/stores/dbstore/packages_test.go
  enterprise/internal/codeintel/stores/dbstore/references_test.go
  enterprise/internal/codeintel/stores/dbstore/repo_usage_test.go
  enterprise/internal/codeintel/stores/dbstore/repos_test.go
  enterprise/internal/codeintel/stores/dbstore/store_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
  enterprise/internal/codeintel/stores/dbstore/xrepo_test.go
  enterprise/internal/codeintel/stores/lsifstore/clear_test.go
  enterprise/internal/codeintel/stores/lsifstore/exists_test.go
  enterprise/internal/codeintel/stores/lsifstore/hover_test.go
  enterprise/internal/codeintel/stores/lsifstore/locations_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/diagnostics_count_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/document_column_split_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/locations_count_test.go
  enterprise/internal/codeintel/stores/lsifstore/migration/migrator_test.go
  enterprise/internal/codeintel/stores/lsifstore/monikers_test.go
  enterprise/internal/codeintel/stores/lsifstore/packages_test.go
  enterprise/internal/codeintel/stores/lsifstore/ranges_test.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/main_test.go
  enterprise/internal/codemonitors/resolvers/main_test.go
  enterprise/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/codemonitors/storetest/monitor_creator.go
  enterprise/internal/database/authz_test.go
  internal/database/access_tokens.go
  internal/database/basestore/store_test.go
  internal/database/batch/batch_test.go
  internal/database/event_logs.go
  internal/database/namespaces.go
  internal/database/org_invitations.go
  internal/database/org_members.go
  internal/database/orgs.go
  internal/database/phabricator.go
  internal/database/saved_queries.go
  internal/database/saved_searches.go
  internal/database/settings.go
  internal/database/stores.go
  internal/database/survey_responses.go
  internal/database/user_credentials.go
  internal/database/users_test.go
  internal/oobmigration/store_test.go
Labels: bug

#20627 Actually soft-fail default reviewers
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
Labels: team/batchers

#20554 Design refresh: Update Badge styles
  client/branded/src/global-styles/GlobalStylesStory/BadgeVariants/BadgeVariants.module.scss
  client/branded/src/global-styles/GlobalStylesStory/BadgeVariants/BadgeVariants.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/badge.scss
  client/branded/src/global-styles/colors-redesign.scss
  client/branded/src/global-styles/index.scss
Labels: team/frontend-platform

#20620 web: add redesign-theme alert styles
  client/branded/src/global-styles/GlobalStylesStory/AlertsStory.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/alert-redesign.scss
  client/branded/src/global-styles/alert.scss
  client/branded/src/global-styles/color-scheme-mixins.scss
  client/web/src/enterprise/batches/list/BatchChangesListIntro.module.scss
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Labels: design refresh, team/frontend-platform

#20493 authtest: to be run within backend integration test suite
  dev/authtest/code_intel_test.go
  dev/authtest/repository_test.go
  dev/authtest/site_admin_test.go
  dev/ci/backend-integration.sh
  internal/gqltestutil/client.go
  internal/gqltestutil/permissions.go
Labels: team/core-application

#20680 Design refresh - command palette
  client/shared/src/commandPalette/CommandList.scss
  client/web/src/components/shared.tsx
Labels: team/frontend-platform

#20684 Disable flaky browser extension e2e tests
  client/browser/src/end-to-end/github.test.ts
Labels: merge-on-any-approve

#20692 web: more precise typography letter-spacing
  client/branded/src/global-styles/buttons-redesign.scss
  client/branded/src/global-styles/typography-redesign.scss
Labels: design refresh, team/frontend-platform

#20647 Design refresh: Update PageHeader and move to Wildcard
  client/web/src/components/PageHeader.story.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.tsx
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexPage.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelIndexesPage.tsx
  client/web/src/enterprise/codeintel/list/CodeIntelUploadsPage.tsx
  client/web/src/extensions/ExtensionsAreaHeader.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/insights/pages/InsightsPage.tsx
  client/web/src/org/area/OrgHeader.tsx
  client/web/src/org/settings/profile/OrgSettingsProfilePage.tsx
  client/web/src/search/queryBuilder/QueryBuilderPage.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/user/area/UserAreaHeader.tsx
  client/web/src/user/settings/profile/UserSettingsProfilePage.tsx
  client/wildcard/src/components/PageHeader/PageHeader.module.scss
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
  client/wildcard/src/components/PageHeader/PageHeader.test.tsx
  client/wildcard/src/components/PageHeader/PageHeader.tsx
  client/wildcard/src/components/PageHeader/__snapshots__/PageHeader.test.tsx.snap
  client/wildcard/src/components/PageHeader/index.ts
  client/wildcard/src/components/index.ts
Labels: team/frontend-platform

#20032 Add first version of code insights creation UI
  client/branded/src/global-styles/typography.scss
  client/sandboxes/code-insights/src/demo.tsx
  client/sandboxes/code-insights/src/mock-api.ts
  client/sandboxes/code-insights/webpack.config.js
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.scss
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/core/backend/api-provider.ts
  client/web/src/insights/core/backend/insights-api.ts
  client/web/src/insights/core/backend/requests/fetch-backend-insights.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/core/types.ts
  client/web/src/insights/index.ts
  client/web/src/insights/pages/InsightsPage.scss
  client/web/src/insights/pages/dashboard/InsightsPage.scss
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
  client/web/src/insights/pages/search-insight-creation/CreationSearchInsightPage.module.scss
  client/web/src/insights/pages/search-insight-creation/CreationSearchInsightPage.story.tsx
  client/web/src/insights/pages/search-insight-creation/CreationSearchInsightPage.tsx
  client/web/src/insights/pages/search-insight-creation/components/creation-search-insight-form/CreationSearchInsightForm.module.scss
  client/web/src/insights/pages/search-insight-creation/components/creation-search-insight-form/CreationSearchInsightForm.test.tsx
  client/web/src/insights/pages/search-insight-creation/components/creation-search-insight-form/CreationSearchInsightForm.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-color-input/FormColorInput.module.scss
  client/web/src/insights/pages/search-insight-creation/components/form-color-input/FormColorInput.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-group/FormGroup.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-input-field/InputField.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-radio-input/FormRadioInput.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-series/FormSeries.module.scss
  client/web/src/insights/pages/search-insight-creation/components/form-series/FormSeries.tsx
  client/web/src/insights/pages/search-insight-creation/components/validators.ts
  client/web/src/insights/pages/search-insight-creation/hooks/useField.ts
  client/web/src/insights/pages/search-insight-creation/hooks/useForm.ts
  client/web/src/insights/pages/search-insight-creation/types.ts
  client/web/src/routes.tsx
  package.json
  yarn.lock
Labels: code-insights-creation-ui, team/code-insights, webapp

#20526 design-refresh - tabs and file sidebar
  client/branded/src/components/panel/Panel.tsx
  client/branded/src/global-styles/tabs.scss
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.scss
  client/web/src/repo/RevisionsPopover.tsx
  client/web/src/tree/Directory.tsx
  client/web/src/tree/Tree.scss
  client/web/src/tree/util.tsx
Labels: merge-on-any-approve, team/frontend-platform

#20482 Add first version of create intro page for insight creation UI
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/pages/creation-intro/CreationIntroPage.module.scss
  client/web/src/insights/pages/creation-intro/CreationIntroPage.story.tsx
  client/web/src/insights/pages/creation-intro/CreationIntroPage.tsx
  client/web/src/insights/pages/creation-intro/charts-mock.ts
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
  client/web/src/insights/pages/search-insight-creation/CreationSearchInsightPage.story.tsx
  client/web/src/insights/pages/search-insight-creation/components/form-input-field/InputField.tsx
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
  client/web/src/views/ChartViewContent/charts/pie/PieChart.tsx
  package.json
Labels: team/code-insights, webapp

#20674 authz: Add opt in for repository permissions checking for site admins
  CHANGELOG.md
  enterprise/internal/batches/background.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  schema/schema.go
  schema/site.schema.json
Labels: team/core-application

#20716 sg: improve output of install script
  dev/sg/install.sh
Labels: sg

#20126 web: add web-app server for development and production builds
  client/web/README.md
  client/web/dev/server/development.server.ts
  client/web/dev/server/production.server.ts
  client/web/dev/tsconfig.json
  client/web/dev/utils/constants.ts
  client/web/dev/utils/create-js-context.ts
  client/web/dev/utils/csrf/get-csrf-token-and-cookie.ts
  client/web/dev/utils/csrf/get-csrf-token-cookie-middleware.ts
  client/web/dev/utils/csrf/index.ts
  client/web/dev/utils/environment-config.ts
  client/web/dev/utils/get-api-proxy-settings.ts
  client/web/dev/utils/get-site-config.ts
  client/web/dev/utils/index.ts
  client/web/dev/webpack/get-html-webpack-plugins.ts
  client/web/gulpfile.js
  client/web/package.json
  client/web/src/global/GlobalAlerts.tsx
  client/web/webpack.config.js
  package.json
  sg.config.yaml
  yarn.lock
Labels: dx, ops & tools & dev, team/frontend-platform

#20563 Update indexers page
  doc/code_intelligence/references/indexers.md
Labels: team/code-intelligence

#20737 sg: No need to panic, it's just a little nil
  dev/sg/main.go
Labels: sg

#20548 Add code insights lang stats creation UI
  client/sandboxes/code-insights/webpack.config.js
  client/sandboxes/code-insights/webpack.config.ts
  client/web/dev/webpack/get-css-loaders.ts
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/components/form/form-group/FormGroup.tsx
  client/web/src/insights/components/form/form-input/FormInput.tsx
  client/web/src/insights/components/form/form-radio-input/FormRadioInput.tsx
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useForm.ts
  client/web/src/insights/components/form/hooks/useTitleValidator.ts
  client/web/src/insights/components/form/validators.ts
  client/web/src/insights/core/types.ts
  client/web/src/insights/pages/creation/intro/IntroCreationPage.module.scss
  client/web/src/insights/pages/creation/intro/IntroCreationPage.story.tsx
  client/web/src/insights/pages/creation/intro/IntroCreationPage.tsx
  client/web/src/insights/pages/creation/intro/charts-mock.ts
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.module.scss
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.module.scss
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.module.scss
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-color-input/FormColorInput.module.scss
  client/web/src/insights/pages/creation/search-insight/components/form-color-input/FormColorInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.module.scss
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.module.scss
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.test.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/types.ts
  client/web/src/insights/pages/search-insight-creation/CreationSearchInsightPage.module.scss
  client/web/src/insights/pages/search-insight-creation/components/form-input-field/InputField.tsx
  client/web/webpack.config.js
Labels: code-insights-creation-ui, team/code-insights, webapp

#20728 auth: Also request privare code scope when enabled site wide
  enterprise/cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
Labels: team/core-application

#20727 database: User added private repos should be listed
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
Labels: team/core-application

#20747 sg: Add ability to overwrite argument to tests
  dev/sg/config.go
  dev/sg/main.go
  dev/sg/run.go
  sg.config.yaml
Labels: sg

#20802 sg: Print logo in color
  dev/sg/install.sh
  dev/sg/main.go
Labels: sg

#20696 Add `@custom-media` support
  client/branded/src/global-styles/breakpoints.scss
  client/branded/src/global-styles/index.scss
  client/web/src/enterprise/batches/close/BatchChangeCloseChangesetsList.module.scss
  client/web/src/enterprise/batches/close/ChangesetCloseNode.module.scss
  client/web/src/enterprise/batches/close/CloseChangesetsListEmptyElement.module.scss
  client/web/src/enterprise/batches/close/ExternalChangesetCloseNode.module.scss
  client/web/src/enterprise/batches/close/HiddenExternalChangesetCloseNode.module.scss
  client/web/src/enterprise/batches/detail/BatchChangeBurndownChart.module.scss
  client/web/src/enterprise/batches/detail/BatchChangeStatsCard.module.scss
  client/web/src/enterprise/batches/detail/BatchSpecTab.module.scss
  client/web/src/enterprise/batches/detail/changesets/ChangesetNode.module.scss
  client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.module.scss
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.module.scss
  client/web/src/enterprise/batches/detail/changesets/HiddenExternalChangesetNode.module.scss
  client/web/src/enterprise/batches/list/BatchChangeListPage.module.scss
  client/web/src/enterprise/batches/list/BatchChangeNode.module.scss
  client/web/src/enterprise/batches/preview/BatchChangePreviewStatsBar.module.scss
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.module.scss
  client/web/src/enterprise/batches/preview/list/ChangesetApplyPreviewNode.module.scss
  client/web/src/enterprise/batches/preview/list/EmptyPreviewListElement.module.scss
  client/web/src/enterprise/batches/preview/list/HiddenChangesetApplyPreviewNode.module.scss
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.module.scss
  client/web/src/enterprise/codeintel/list/CodeIntelIndexesPage.scss
  client/web/src/enterprise/codeintel/list/CodeIntelUploadsPage.scss
  client/web/src/enterprise/codeintel/shared/CodeIntelIndexNode.scss
  client/web/src/enterprise/codeintel/shared/CodeIntelUploadNode.scss
  client/web/src/enterprise/productSubscription/TrueUpStatusSummary.scss
  client/web/src/extensions/extension/ExtensionAreaHeader.scss
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.module.scss
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.module.scss
  client/web/src/repo/tree/TreeEntriesSection.scss
  client/web/src/search/queryBuilder/QueryBuilder.scss
  client/web/src/search/results/SearchResultsList.scss
  client/web/src/site-admin/SiteAdminMigrationsPage.scss
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.scss
  client/wildcard/src/components/NavBar/NavBar.module.scss
  client/wildcard/src/components/NavBar/NavItem.module.scss
  client/wildcard/src/components/PageHeader/PageHeader.module.scss
  client/wildcard/src/global-styles/breakpoints.scss
  package.json
  postcss.config.js
  yarn.lock
Labels: team/frontend-platform

#20815 Fix CSS modules type generator not globbing correctly
  client/shared/dev/generateCssModulesTypes.js
Labels: team/frontend-platform

#20820 fix scroll regression on tabs
  client/branded/src/global-styles/tabs.scss
  client/web/src/repo/RepoRevisionSidebar.tsx
Labels: team/frontend-platform

#20714 Design refresh: user nav
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/RedesignToggle/RedesignToggle.tsx
  client/web/src/nav/UserNavItem.scss
  client/web/src/nav/UserNavItem.story.tsx
  client/web/src/nav/UserNavItem.test.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/wildcard/src/components/NavBar/NavBar.module.scss
  client/wildcard/src/components/NavBar/NavItem.module.scss
Labels: team/frontend-platform

#20769 Setup post sign-up route
  client/web/src/Layout.tsx
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/auth/SignInSignUpCommon.tsx
  client/web/src/auth/SignInSignUpPageCommon.scss
  client/web/src/auth/SignUpPage.test.tsx
  client/web/src/auth/SignUpPage.tsx
  client/web/src/routes.tsx
  schema/schema.go
  schema/site.schema.json
Labels: cloud/milestone-5, team/core-application

#20730 web: hide extra icons inside of the alert components
  client/branded/src/components/panel/views/FileLocations.tsx
  client/branded/src/global-styles/index.scss
  client/web/src/components/__snapshots__/alerts.test.tsx.snap
  client/web/src/components/alerts.tsx
  client/web/src/enterprise/batches/detail/ClosedNotice.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsArea.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateBanner.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateIcon.tsx
  client/web/src/global/GlobalAlert.tsx
  client/web/src/global/GlobalAlerts.scss
  client/web/src/repo/DirectImportRepoAlert.tsx
  client/web/src/search/results/SearchAlert.tsx
  client/web/src/search/results/SearchResultsList.tsx
  client/web/src/search/results/VersionContextWarning.tsx
  client/web/src/search/results/streaming/StreamingSearchResultsFooter.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/site/FreeUsersExceededAlert.tsx
  client/web/src/site/LicenseExpirationAlert.tsx
  client/web/src/site/NeedsRepositoryConfigurationAlert.tsx
  client/web/src/site/PerformanceWarningAlert.tsx
  client/web/src/site/__snapshots__/LicenseExpirationAlert.test.tsx.snap
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/frontend-platform

#20848 docs: Add batch spec cheat sheet
  doc/batch_changes/index.md
  doc/batch_changes/references/batch_spec_cheat_sheet.md
  doc/batch_changes/references/batch_spec_templating.md
  doc/batch_changes/references/index.md
Labels: docs, team/batchers

#20889 batches: fix some credential encryption detritus
  doc/admin/config/encryption.md
  enterprise/internal/batches/background/site_credential_migrator.go
Labels: docs, team/batchers

#20890 doc: couple of tweaks to #20848
  doc/batch_changes/references/batch_spec_cheat_sheet.md
Labels: docs, team/batchers

#20748 Design refresh: Branch/Tag/Commit selector + Repository selector
  client/web/src/components/ConnectionPopover.scss
  client/web/src/components/FilteredConnection.scss
  client/web/src/repo/GitReference.scss
  client/web/src/repo/GitReference.tsx
  client/web/src/repo/GitReferenceTag.scss
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepositoriesPopover.tsx
  client/web/src/repo/RevisionsPopover.scss
  client/web/src/repo/RevisionsPopover.tsx
  client/web/src/repo/commits/GitCommitNode.tsx
Labels: design refresh, team/frontend-platform

#20851 frontend: Site admins cannot view user owned code host config
  CHANGELOG.md
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
Labels: team/core-application

#20787 Add search based insight's live preview chart
  client/web/src/Layout.scss
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useForm.ts
  client/web/src/insights/core/backend/api/get-combined-views.ts
  client/web/src/insights/core/backend/api/get-search-insight-content.ts
  client/web/src/insights/core/backend/api/subject-settings.ts
  client/web/src/insights/core/backend/insights-api.ts
  client/web/src/insights/core/backend/requests/fetch-search-insight.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.module.scss
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.tsx
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.module.scss
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/live-preview-mock-data.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.module.scss
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/types.ts
  client/web/src/insights/pages/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/views/ChartViewContent/ChartViewContent.story.tsx
Labels: team/code-insights, webapp

#20895 web: remove jsx-no-bind ignore comments
  client/branded/src/global-styles/GlobalStylesStory/FormFieldVariants/FormFieldVariants.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/sandboxes/code-insights/src/demo.tsx
  client/shared/src/components/VirtualList.tsx
  client/storybook/src/redesign-toggle-toolbar/RedesignToggleStorybook.tsx
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  client/web/src/enterprise/code-monitoring/global/GlobalCodeMonitoringArea.tsx
  client/web/src/enterprise/extensions/registry/RegistryArea.tsx
  client/web/src/extensions/ExtensionsArea.tsx
  client/web/src/extensions/ExtensionsQueryInputToolbar.tsx
  client/web/src/extensions/components/ActionItemsBar.tsx
  client/web/src/extensions/components/StatusBar.tsx
  client/web/src/extensions/extension/ExtensionArea.tsx
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.tsx
  client/web/src/org/OrgsArea.tsx
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/settings/OrgSettingsArea.tsx
  client/web/src/org/settings/members/InviteForm.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoHeader.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RevisionsPopover.tsx
  client/web/src/repo/branches/RepositoryBranchesArea.tsx
  client/web/src/repo/compare/RepositoryCompareArea.tsx
  client/web/src/repo/releases/RepositoryReleasesArea.tsx
  client/web/src/repo/settings/RepoSettingsArea.tsx
  client/web/src/repo/stats/RepositoryStatsArea.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/savedSearches/SavedSearchUpdateForm.tsx
  client/web/src/settings/SettingsArea.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/user/area/UserArea.tsx
  client/web/src/user/settings/UserSettingsArea.tsx
  client/web/src/user/settings/accessTokens/UserSettingsTokensArea.tsx
  client/web/src/views/ChartViewContent/charts/bar/BarChart.tsx
  client/web/src/views/ChartViewContent/charts/line/components/GlyphContent.tsx
  client/web/src/views/ChartViewContent/charts/line/components/LineChartContent.tsx
  client/web/src/views/ChartViewContent/charts/pie/PieChart.tsx
  client/web/src/views/ViewsArea.tsx
  package.json
  yarn.lock
Labels: dx, team/frontend-platform

#19683 web: add commands to start web dev-server to the root package.json
  client/web/gulpfile.js
  client/web/package.json
  doc/dev/background-information/web/web_app.md
  sg.config.yaml
Labels: docs, team/frontend-platform

#20845 web: update alert redesign icons
  client/branded/src/global-styles/alert-redesign.scss
  client/web/src/enterprise/batches/detail/SupersedingBatchSpecAlert.tsx
  client/web/src/enterprise/batches/detail/UnpublishedNotice.tsx
  client/web/src/enterprise/codeintel/shared/CodeIntelStateIcon.tsx
  client/web/src/repo/actions/InstallBrowserExtensionAlert.scss
  client/web/src/repo/actions/InstallBrowserExtensionAlert.tsx
  client/web/src/repo/actions/__snapshots__/InstallBrowserExtensionAlert.test.tsx.snap
Labels: design refresh, team/frontend-platform

#20753 codeintel: enforce authz when listing uploads and indexes
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/core-application

#20937 Temporarily disable OAuth for GitLab
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: team/core-application

#20938 Don't disable OAuth code host connections for users with a private co…
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  client/web/src/user/settings/routes.tsx
Labels: team/core-application

#20905 graphql: Only the owner or org member can view saved search
  cmd/frontend/backend/orgs.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/saved_searches.go
  cmd/frontend/graphqlbackend/saved_searches_test.go
  cmd/frontend/graphqlbackend/settings_subject.go
  enterprise/cmd/frontend/internal/registry/publisher_graphql.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/codemonitors/resolvers/resolvers.go
Labels: team/core-application

#20941 oauth: Re-enable OAuth and switch to read_api for GitLab
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  enterprise/cmd/frontend/internal/auth/gitlaboauth/config_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/provider.go
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
Labels: team/core-application

#20919 fix panel tabs border
  client/branded/src/components/panel/Panel.tsx
Labels: merge-on-any-approve, team/frontend-platform

#20837 Provide link to code host if changeset is already published
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetInfoCell.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetTitle.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/batches/preview/list/backend.ts
Labels: team/batchers

#20925 codeintel-qa: Update lsif-go results
  internal/cmd/precise-code-intel-tester/scripts/clone-and-index.sh
  internal/cmd/precise-code-intel-tester/test_cases.go
Labels: team/code-intelligence

#20775 Design refresh: Dropdown nav
  client/wildcard/src/components/NavBar/NavBar.module.scss
  client/wildcard/src/components/NavBar/NavBar.tsx
  client/wildcard/src/components/NavBar/NavItem.module.scss
Labels: team/frontend-platform

#20884 complete nav bar outstanding points
  client/shared/src/commandPalette/CommandList.scss
  client/shared/src/commandPalette/EmptyCommandList.scss
  client/web/src/nav/Feedback/FeedbackPrompt.scss
  client/web/src/nav/Feedback/FeedbackPrompt.story.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.test.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
  client/web/src/nav/GlobalNavbar.scss
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/IconRadioButtons.scss
  client/web/src/nav/NavLinks.tsx
  client/wildcard/src/components/NavBar/NavAction.module.scss
  client/wildcard/src/components/NavBar/NavBar.tsx
  client/wildcard/src/components/NavBar/NavItem.module.scss
Labels: team/frontend-platform

#20950 add version context dropdown on search bar
  client/web/src/nav/GlobalNavbar.tsx
Labels: team/frontend-platform

#18375 codeintel: display LSIF upload-stage errors in the UI
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.story.tsx
  client/web/src/enterprise/codeintel/detail/CodeIntelUploadTimeline.tsx
  enterprise/cmd/frontend/internal/codeintel/httpapi/iface.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: team/code-intelligence

#20856 Add live preview chart to lang stats creation UI
  client/web/src/insights/core/backend/api/get-lang-stats-insight-content.ts
  client/web/src/insights/core/backend/insights-api.ts
  client/web/src/insights/core/backend/requests/fetch-lang-stats-insight.ts
  client/web/src/insights/core/backend/types.ts
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.module.scss
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.module.scss
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.module.scss
  client/web/src/insights/pages/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.tsx
  client/web/src/insights/pages/creation/lang-stats/components/live-preview-chart/hooks/use-lang-stats-preview-content.ts
  client/web/src/insights/pages/creation/lang-stats/components/live-preview-chart/live-preview-mock-data.ts
  client/web/src/insights/pages/creation/lang-stats/types.ts
  client/web/webpack.config.js
  package.json
  yarn.lock
Labels: code-insights-creation-ui, team/code-insights, webapp

#20952 extensibility: add logging API to changelog
  CHANGELOG.md
Labels: merge-on-any-approve

#20475 codeintel: Configure additional honey events
  enterprise/cmd/executor/internal/worker/handler.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/observability.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  internal/honey/honey.go
  internal/observation/observation.go
  internal/trace/traceutil.go
Labels: team/code-intelligence

#20931 dev: Consolidate codeintel tools
  enterprise/cmd/lsif-index-tester/.gitignore
  enterprise/cmd/lsif-index-tester/README.md
  enterprise/lib/codeintel/lsif/reader/context.go
  enterprise/lib/codeintel/lsif/reader/errors.go
  enterprise/lib/codeintel/lsif/reader/reader.go
  enterprise/lib/codeintel/lsif/reader/stasher.go
  enterprise/lib/codeintel/lsif/test/.gitignore
  enterprise/lib/codeintel/lsif/validation/context.go
  enterprise/lib/codeintel/lsif/validation/ownership.go
  enterprise/lib/codeintel/lsif/validation/validator.go
  enterprise/lib/codeintel/lsif/validation/validators.go
  enterprise/lib/codeintel/lsif/validation/validators_edge.go
  enterprise/lib/codeintel/lsif/validation/validators_relationship.go
  enterprise/lib/codeintel/lsif/validation/validators_vertex.go
  enterprise/lib/codeintel/tools/README.md
  enterprise/lib/codeintel/tools/lsif-index-tester/main.go
  enterprise/lib/codeintel/tools/lsif-index-tester/proc_profiling.go
  enterprise/lib/codeintel/tools/lsif-index-tester/spec.go
  enterprise/lib/codeintel/tools/lsif-visualize/args.go
  enterprise/lib/codeintel/tools/lsif-visualize/internal/visualization/context.go
  enterprise/lib/codeintel/tools/lsif-visualize/internal/visualization/util.go
  enterprise/lib/codeintel/tools/lsif-visualize/internal/visualization/visualizer.go
  enterprise/lib/codeintel/tools/lsif-visualize/main.go
  enterprise/lib/codeintel/tools/lsif-visualize/visualize.go
  enterprise/lib/codeintel/tools/scripts/combine.sh
  internal/cmd/precise-code-intel-tester/scripts/download.sh
Labels: team/code-intelligence

#20968 codeintel: Remove experimental disclaimer in GraphQL schema
  cmd/frontend/graphqlbackend/codeintel.graphql
Labels: team/code-intelligence

#20979 user: allow getting `accountData` of external accounts
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
  cmd/frontend/graphqlbackend/external_account.go
Labels: security, team/core-application, ux

#20945 cleanup: Use WithInternalActor
  cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
  enterprise/internal/batches/state/state.go
Labels: team/core-application

#20914 Add first implementation of delete functionality to insight page
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.scss
  client/web/src/insights/components/InsightsViewGrid/InsightsViewGrid.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/InsightCard.module.scss
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/InsightContentCard.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-description/InsightCardDescription.module.scss
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-description/InsightCardDescription.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.module.scss
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/core/jsonc-settings.ts
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
  client/web/src/insights/pages/dashboard/hooks/use-delete-insight.ts
Labels: code-insights-creation-ui, team/code-insights, webapp

#20804 Refactor: Break up FilteredConnection component
  client/web/src/components/FilteredConnection/ConnectionNodes.tsx
  client/web/src/components/FilteredConnection/ConnectionNodesSummary.tsx
  client/web/src/components/FilteredConnection/ConnectionType.ts
  client/web/src/components/FilteredConnection/FilterControl.tsx
  client/web/src/components/FilteredConnection/FilteredConnection.scss
  client/web/src/components/FilteredConnection/FilteredConnection.test.tsx
  client/web/src/components/FilteredConnection/FilteredConnection.tsx
  client/web/src/components/FilteredConnection/index.scss
  client/web/src/components/FilteredConnection/index.ts
  client/web/src/components/FilteredConnection/utils.ts
  client/web/src/components/diff/FileDiffConnection.tsx
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/searchContexts/SearchContextsListTab.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: team/frontend-platform

#20980 sg: Update go.mod to fix dev/sg/install.sh
  dev/sg/go.sum
Labels: sg

#20944 Add edit functionality via creation UI for code insight
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/InsightContentCard.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.module.scss
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useForm.ts
  client/web/src/insights/components/form/hooks/useTitleValidator.ts
  client/web/src/insights/core/jsonc-operation.ts
  client/web/src/insights/core/jsonc-settings.ts
  client/web/src/insights/core/types.ts
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/lang-stats/utils/insight-sanitizer.ts
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/insights/pages/dashboard/hooks/use-delete-insight.ts
  client/web/src/insights/pages/edit/EditInsightPage.module.scss
  client/web/src/insights/pages/edit/EditInsightPage.tsx
  client/web/src/insights/pages/edit/components/EditLangStatsInsight.tsx
  client/web/src/insights/pages/edit/components/EditSearchInsight.tsx
  yarn.lock
Labels: code-insights-creation-ui, team/code-insights

#20863 web: add redesign root color palette as CSS variables
  client/branded/src/global-styles/alert-redesign.scss
  client/branded/src/global-styles/colors-redesign.scss
  client/branded/src/global-styles/colors.scss
  client/branded/src/global-styles/forms.scss
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/variables-redesign.scss
  client/web/src/user/UserAvatar.scss
Labels: design refresh, team/frontend-platform

#20971 codeintel: Move semantic/repl to tools/lsif-repl
  lib/codeintel/CODENOTIFY
  lib/codeintel/tools/README.md
  lib/codeintel/tools/lsif-repl/main.go
Labels: team/code-intelligence

#20990 codeintel: Remove old copy of lsif-repl
  lib/codeintel/semantic/repl/main.go
Labels: team/code-intelligence

#20951 web: update redesign alert dark mode icon colors
  client/branded/src/global-styles/alert-redesign.scss
  client/branded/src/global-styles/colors-redesign.scss
Labels: design refresh, team/frontend-platform

#20774 Add notes on file permission in gitserver
  doc/admin/repo/auth.md
Labels: team/distribution

#20556 code-intel: make table rows scroll on overflow
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexTimeline.scss
  client/web/src/enterprise/codeintel/detail/CodeIntelIndexTimeline.tsx
Labels: team/code-intelligence

#20988 Site admins cannot add access tokens for any user by default
  CHANGELOG.md
  cmd/frontend/backend/site_admin.go
  cmd/frontend/graphqlbackend/access_tokens.go
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/user.go
Labels: team/core-application

#20898 Refresh popovers: Update 'Show more' styles
  client/web/src/components/FilteredConnection/ConnectionNodes.tsx
  client/web/src/components/FilteredConnection/ConnectionNodesSummary.tsx
  client/web/src/components/FilteredConnection/FilteredConnection.scss
  client/web/src/components/FilteredConnection/FilteredConnection.test.tsx
  client/web/src/enterprise/code-monitoring/__snapshots__/CodeMonitoringPage.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  client/web/src/repo/RevisionsPopover.tsx
Labels: team/frontend-platform

#21015 graphql: Return error when non site admin attempt to count all repos
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repositories_test.go
Labels: team/core-application

#21021 frontend: Small cleanups
  cmd/frontend/backend/site_admin.go
  cmd/frontend/graphqlbackend/access_tokens.go
  cmd/frontend/graphqlbackend/codehost_repository_connection.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/orgs.go
  cmd/frontend/graphqlbackend/repositories_test.go
  internal/database/access_tokens.go
Labels: team/core-application

#20955 HTTPS with customer certs on Docker compose docs
  doc/admin/http_https_configuration.md
Labels: docs

#21017 web: add redesign card styles
  client/branded/src/global-styles/GlobalStylesStory/CardsStory.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/card.scss
  client/web/src/enterprise/code-monitoring/CodeMonitoringNode.scss
Labels: design refresh, team/frontend-platform

#21044 frontend: Remove SetRepositoryEnabled mutation
  CHANGELOG.md
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  internal/repos/types_test.go
  internal/repoupdater/client.go
  internal/repoupdater/protocol/repoupdater.go
  internal/types/types.go
Labels: team/core-application

#20361 Implement actions on changeset lists
  CHANGELOG.md
  client/web/src/components/DismissibleAlert.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeTabs.tsx
  client/web/src/enterprise/batches/detail/BulkOperationsAlerts.story.tsx
  client/web/src/enterprise/batches/detail/BulkOperationsAlerts.tsx
  client/web/src/enterprise/batches/detail/BulkOperationsTab.tsx
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/detail/bulk-operations/BulkOperationNode.module.scss
  client/web/src/enterprise/batches/detail/bulk-operations/BulkOperationNode.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.module.scss
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesetsHeader.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetNode.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.module.scss
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
  client/web/src/enterprise/batches/detail/changesets/CreateCommentModal.story.tsx
  client/web/src/enterprise/batches/detail/changesets/CreateCommentModal.tsx
  client/web/src/enterprise/batches/detail/changesets/DetachChangesetsModal.story.tsx
  client/web/src/enterprise/batches/detail/changesets/DetachChangesetsModal.tsx
  client/web/src/enterprise/batches/detail/changesets/EmptyArchivedChangesetListElement.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/batches/detail/changesets/HiddenExternalChangesetNode.tsx
  client/web/src/integration/batches.test.ts
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/internal/batches/resolvers/batch_change.go
  enterprise/internal/batches/resolvers/bulk_operation.go
  enterprise/internal/batches/resolvers/bulk_operation_connection.go
  enterprise/internal/batches/resolvers/bulk_operation_connection_test.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/store/bulk_operations.go
  enterprise/internal/batches/store/bulk_operations_test.go
  enterprise/internal/batches/types/bulk_operation.go
Labels: team/batchers

#20995 Add new mechanism for listening value for insight live preview
  client/sandboxes/code-insights/webpack.config.ts
  client/web/src/components/alerts.tsx
  client/web/src/insights/components/form/form-input/FormInput.tsx
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/components/form/hooks/useForm.ts
  client/web/src/insights/components/form/hooks/utils/get-event-value.ts
  client/web/src/insights/components/form/hooks/utils/use-async-validation.ts
  client/web/src/insights/components/form/validators.ts
  client/web/src/insights/core/backend/requests/fetch-repositories.ts
  client/web/src/insights/hooks/use-distinct-value.ts
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/search-insight/components/form-color-input/FormColorInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.module.scss
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/components/series-card/SeriesCard.module.scss
  client/web/src/insights/pages/creation/search-insight/components/form-series/components/series-card/SeriesCard.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.module.scss
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/hooks/use-editable-series.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/views/ChartViewContent/charts/line/LineChart.scss
Labels: code-insights-creation-ui, team/code-insights, webapp

#21056 Add docs page for bulk operations
  client/web/src/enterprise/batches/detail/BulkOperationsTab.tsx
  doc/batch_changes/how-tos/bulk_operations_on_changesets.md
  doc/batch_changes/index.md
Labels: team/batchers

#21019 Change visibility input in order to support organization selection
  client/web/src/insights/components/form/form-radio-input/FormRadioInput.tsx
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
  client/web/src/insights/core/types.ts
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/lang-stats/types.ts
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/types.ts
  client/web/src/insights/pages/edit/EditInsightPage.tsx
  client/web/src/insights/pages/edit/components/EditLangStatsInsight.tsx
  client/web/src/insights/pages/edit/components/EditSearchInsight.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21040 batches: update UI changelog and constants for release
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
  internal/src-cli/consts.go
Labels: team/batchers

#21043 Align visual styles of code insight according to latest design layouts
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/InsightCard.module.scss
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/InsightContentCard.tsx
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.module.scss
  client/web/src/insights/components/InsightsViewGrid/components/insight-card/components/insight-card-menu/InsightCardMenu.tsx
  client/web/src/insights/components/form/form-group/FormGroup.tsx
  client/web/src/insights/components/form/form-radio-input/FormRadioInput.tsx
  client/web/src/insights/components/live-preview-container/LivePreviewContainer.module.scss
  client/web/src/insights/components/live-preview-container/LivePreviewContainer.tsx
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.module.scss
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.module.scss
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21069 graphqlbackend: only allow user to get account data for GitHub and GitLab
  cmd/frontend/graphqlbackend/external_account.go
  cmd/frontend/graphqlbackend/external_account_test.go
Labels: team/core-application

#21052 Refresh: Popover tweaks
  client/branded/src/global-styles/border-radius.scss
  client/branded/src/global-styles/dropdown.scss
  client/branded/src/global-styles/index.scss
  client/web/src/components/ConnectionPopover.scss
  client/web/src/components/FilteredConnection/FilteredConnection.scss
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepositoriesPopover.tsx
  client/web/src/repo/RevisionsPopover.scss
  client/web/src/repo/RevisionsPopover.tsx
Labels: team/frontend-platform

#20547 Design Refresh - Allow refresh toggle to be enabled on deployed environments
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/NavLinks.tsx
  client/web/src/nav/RedesignToggle/RedesignToggle.module.scss
  client/web/src/nav/RedesignToggle/RedesignToggle.tsx
  client/web/src/nav/UserNavItem.tsx
  dev/global-settings.json
  schema/schema.go
  schema/settings.schema.json
Labels: team/frontend-platform

#21023 authz: Tighten security and enable syncing for site admins
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  client/web/src/jscontext.ts
  cmd/frontend/envvar/envvar.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/internal/database/perms_store.go
  internal/authz/perms.go
Labels: team/core-application

#21107 Change the repositories field's placeholder
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21026 database: Remove repo external service indirection
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repository_external.go
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  internal/database/repos.go
  internal/database/repos_db_test.go
Labels: team/core-application

#21135 graphqlbackend: Fix old comment
  cmd/frontend/graphqlbackend/repository_mirror.go
Labels: team/core-application

#21138 database: Optimise CountUserAddedRepos
  internal/repos/store.go
Labels: team/core-application

#21064 Refresh: Adjust popover height to content
  client/web/src/components/ConnectionPopover.scss
Labels: team/frontend-platform

#21139 Automatically add extension to user/org settings
  client/web/src/insights/core/jsonc-operation.ts
Labels: code-insights-creation-ui, team/code-insights, webapp

#21108 Add org description to visibility picker
  client/web/src/insights/components/visibility-picker/VisibilityPicker.tsx
Labels: code-insights-creation-ui, team/code-insights

#21136 Refresh: Further popover tweaks
  client/branded/src/global-styles/index.scss
  client/web/src/components/ConnectionPopover.scss
  client/web/src/repo/GitReference.tsx
  client/web/src/repo/RevisionsPopover.scss
  client/web/src/repo/RevisionsPopover.tsx
Labels: team/frontend-platform

#21137 Open link via chart data points in a new browser tab by default
  client/shared/src/util/link-click-handler/linkClickHandler.ts
  client/web/src/views/ChartViewContent/ChartViewContent.tsx
  client/web/src/views/ChartViewContent/charts/bar/BarChart.tsx
  client/web/src/views/ChartViewContent/charts/line/components/GlyphContent.tsx
  client/web/src/views/ChartViewContent/charts/pie/PieChart.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21122 Change series state validation management
  client/web/src/insights/components/form/hooks/useField.ts
  client/web/src/insights/pages/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/insights/pages/creation/search-insight/components/form-series/FormSeries.tsx
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.test.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/hooks/helpers.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/hooks/use-editable-series.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-content/validators.ts
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/creation/search-insight/types.ts
  client/web/src/insights/pages/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/insights/pages/edit/components/EditSearchInsight.tsx
Labels: code-insights-creation-ui, team/code-insights

#21146 Add native styles overriding for autofill input
  client/branded/src/global-styles/forms.scss
Labels: code-insights-creation-ui, team/code-insights, webapp

#20975 Include code host kind in repo checks
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
Labels: team/core-application, ux

#21074 add refresh design sub nav styles
  client/branded/src/global-styles/nav.scss
Labels: team/frontend-platform

#21037 codeintel: ingest, process, and expose API documentation data
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/codeintel_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/query_documentation.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/observability.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/iface.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/mock_iface_test.go
  enterprise/internal/codeintel/stores/lsifstore/data_write_documentation.go
  enterprise/internal/codeintel/stores/lsifstore/documentation.go
  enterprise/internal/codeintel/stores/lsifstore/observability.go
  enterprise/internal/codeintel/stores/lsifstore/serializer_documentation.go
  internal/database/schema.codeintel.md
  lib/codeintel/lsif/conversion/correlate.go
  lib/codeintel/lsif/conversion/correlate_documentation.go
  lib/codeintel/lsif/conversion/correlate_test.go
  lib/codeintel/lsif/conversion/group.go
  lib/codeintel/lsif/conversion/group_documentation.go
  lib/codeintel/lsif/conversion/state.go
  lib/codeintel/semantic/types.go
  migrations/codeintel/1000000015_lsif_documentation.down.sql
  migrations/codeintel/1000000015_lsif_documentation.up.sql
Labels: api-docs

#20565 Cleanup the logic for FilteredConnection fallback
  client/web/src/user/settings/repositories/UserSettingsRepositoriesPage.tsx
Labels: team/core-application, ux

#21140 Convert detachChangesets to be a bulk operation
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/detail/bulk-operations/BulkOperationNode.tsx
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/internal/batches/background/bulk_processor.go
  enterprise/internal/batches/background/bulk_processor_test.go
  enterprise/internal/batches/resolvers/bulk_operation.go
  enterprise/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/types/changeset_job.go
Labels: team/batchers

#21175 Update LangStatsInsightCreationForm.tsx
  client/web/src/insights/pages/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
Labels: team/code-insights

#21086 chore: Rename receivers
  enterprise/cmd/frontend/internal/codeintel/background/indexing/iface.go
  enterprise/internal/codeintel/autoindex/enqueuer/iface.go
Labels: team/code-intelligence

#21147 Proofread all texts for code insight creation UI
  client/web/src/insights/pages/creation/intro/IntroCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/components/live-preview-chart/SearchInsightLivePreview.tsx
  client/web/src/insights/pages/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/insights/pages/edit/EditInsightPage.tsx
Labels: code-insights-creation-ui

#21178 Remove insight creation UI local storage flag
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/pages/creation/intro/IntroCreationPage.tsx
  client/web/src/insights/pages/dashboard/InsightsPage.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21177 Add insight creation UI pings
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/insights/InsightsRouter.tsx
  client/web/src/insights/core/analytics.test.ts
  client/web/src/insights/core/analytics.ts
  client/web/src/insights/pages/creation/intro/IntroCreationPage.story.tsx
  client/web/src/insights/pages/creation/intro/IntroCreationPage.tsx
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/insights/pages/creation/search-insight/SearchInsightCreationPage.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21085 executors: Fetch tags for workspace
  enterprise/cmd/executor/internal/command/observability.go
  enterprise/cmd/executor/internal/worker/workspace.go
  enterprise/cmd/executor/internal/worker/workspace_test.go
Labels: dependency-indexing, team/code-intelligence

#21080 codeintel: Improve go dependency indexing
  lib/codeintel/autoindex/inference/go.go
  lib/codeintel/autoindex/inference/go_test.go
  lib/codeintel/autoindex/inference/paths.go
  lib/codeintel/autoindex/inference/patterns.go
  lib/codeintel/autoindex/inference/typescript.go
  lib/codeintel/autoindex/inference/typescript_test.go
Labels: dependency-indexing, team/code-intelligence

#21184 graphql: Add the CodeHostSyncDue resolver
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/database/external_services.go
  internal/database/external_services_test.go
Labels: team/core-application

#20783 validate settings JSON for sideloaded extensions
  client/shared/src/api/client/mainthread-api.ts
  client/web/src/settings/SettingsArea.tsx
Labels: extensions, team/extensibility

#21189 perforce: fix descriptions of `p4.passwd` to be ticket values
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/settings/MonacoSettingsEditor.tsx
Labels: team/core-application

#21190 Run insight pings only on user/org settings change
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/insights/core/analytics.ts
Labels: code-insights-creation-ui, team/code-insights, webapp

#21192 make external services the first extension category
  client/shared/src/schema/extensionSchema.ts
  client/web/src/extensions/__snapshots__/ExtensionRegistrySidenav.test.tsx.snap
Labels: merge-on-any-approve

#21191 add extension registry redesign to changelog
  CHANGELOG.md
Labels: merge-on-any-approve

#20989 extensibility: add tooltip when action item is inactive
  client/shared/src/actions/ActionItem.tsx
  client/web/src/extensions/components/ActionItemsBar.scss
Labels: merge-on-any-approve

#21150 add file view - closed file tree trigger
  client/web/src/repo/RepoRevisionSidebar.scss
  client/web/src/repo/RepoRevisionSidebar.tsx
Labels: team/frontend-platform

#21157 disable button when textarea is empty
  client/web/src/nav/Feedback/FeedbackPrompt.test.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
Labels: team/frontend-platform

#21163 improve tabs UI for design refresh
  client/branded/src/global-styles/tabs.scss
Labels: team/frontend-platform

#21156 corrections to nav menu visuals
  client/wildcard/src/components/NavBar/NavBar.module.scss
  client/wildcard/src/components/NavBar/NavItem.module.scss
Labels: team/frontend-platform

#21204 codeintel: Do not perform part upload within transaction
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
Labels: team/code-intelligence

#21176 Two code insight quickstart guides
  doc/code_insights/index.md
  doc/code_insights/language_insight_quickstart.md
  doc/code_insights/quickstart.md
Labels: team/code-insights, v1-insights-docs

#21159 codeintel: Refactor upload package
  enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
  go.mod
  go.sum
  lib/codeintel/upload/bounded_reader.go
  lib/codeintel/upload/compress.go
  lib/codeintel/upload/indexer_name.go
  lib/codeintel/upload/indexer_name_test.go
  lib/codeintel/upload/progress_reader.go
  lib/codeintel/upload/request.go
  lib/codeintel/upload/request_logger.go
  lib/codeintel/upload/retry.go
  lib/codeintel/upload/upload.go
  lib/codeintel/upload/upload_options.go
  lib/codeintel/upload/upload_test.go
  lib/codeintel/utils/README.md
  lib/codeintel/utils/gzip.go
  lib/codeintel/utils/gzip_test.go
  lib/codeintel/utils/rate.go
  lib/codeintel/utils/split_file.go
  lib/codeintel/utils/split_file_test.go
  lib/codeintel/utils/stitch_files.go
  lib/codeintel/utils/stitch_files_test.go
  lib/codeintel/utils/upload.go
  lib/go.mod
  lib/go.sum
Labels: team/code-intelligence

#21233 Temporarily disable all LSIF uploads to dogfood to make builds green
  .github/workflows/lsif.yml
Labels: team/frontend-platform

#21202 client/web: Don't send email and username to Sentry
  client/web/src/sentry.ts
Labels: team/core-application

#21236 doc: Add Flaky Test bug template, and link to it from the doc.
  .github/ISSUE_TEMPLATE/flaky_test.md
  doc/dev/background-information/testing_principles.md
Labels: team/frontend-platform

#21024 Tweak badge transitions
  client/branded/src/global-styles/badge.scss
  client/branded/src/global-styles/index.scss
Labels: team/frontend-platform

#21221 codeintel: Queue sg/sg dependency index jobs in a goroutine on cloud
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
Labels: dependency-indexing, team/code-intelligence

#21180 Refresh: Update secondary button icon color
  client/branded/src/global-styles/buttons-redesign.scss
Labels: design refresh, team/frontend-platform

#21050 Refresh: Update search context selector
  client/web/src/search/input/SearchContextMenu.scss
  client/web/src/search/input/SearchContextMenu.tsx
  client/web/src/search/input/__snapshots__/SearchContextMenu.test.tsx.snap
Labels: team/frontend-platform

#21224 apidocs: add barebones web UI for internal testing
  client/shared/src/util/url.ts
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.scss
  client/web/src/repo/docs/DocumentationIndexNode.tsx
  client/web/src/repo/docs/DocumentationNode.tsx
  client/web/src/repo/docs/RepositoryDocumentationPage.scss
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  client/web/src/repo/docs/RepositoryDocumentationSidebar.tsx
  client/web/src/repo/routes.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/util/settings.ts
  client/web/src/util/url.ts
  cmd/frontend/internal/app/ui/router.go
  schema/schema.go
  schema/settings.schema.json
Labels: api-docs, api-docs-golang

#21251 apidocs: fix breadcrumb entries (inverted conditional)
  client/web/src/repo/docs/DocumentationNode.tsx
Labels: api-docs

#21218 Added administration and security explanation
  doc/code_insights/explanations/administration_and_security_of_code_insights.md
  doc/code_insights/explanations/index.md
  doc/code_insights/index.md
Labels: team/code-insights, v1-insights-docs

#20957 batches: view spec from preview page
  CHANGELOG.md
  client/web/src/components/FilteredConnection/FilteredConnection.tsx
  client/web/src/enterprise/batches/BatchChangeTabs.module.scss
  client/web/src/enterprise/batches/BatchChangeTabs.tsx
  client/web/src/enterprise/batches/BatchSpec.module.scss
  client/web/src/enterprise/batches/BatchSpec.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
  client/web/src/enterprise/batches/detail/BatchChangeTabs.module.scss
  client/web/src/enterprise/batches/detail/BatchChangeTabs.tsx
  client/web/src/enterprise/batches/detail/BatchSpecTab.tsx
  client/web/src/enterprise/batches/detail/BulkOperationsAlerts.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewTabs.tsx
  client/web/src/enterprise/batches/preview/backend.ts
  client/web/src/enterprise/batches/preview/list/PreviewList.tsx
  client/web/src/integration/batches.test.ts
Labels: team/batchers

#21253 Add self to users tagged when batch changes are mentioned
  .github/workflows/batches-notify.yml
Labels: team/batchers

#21237 extsvc: Add GetAuthenticatedUserOAuthScopes for github
  internal/extsvc/auth/auth.go
  internal/extsvc/github/common.go
  internal/extsvc/github/testdata/vcr/GetAuthenticatedUserOAuthScopes.yaml
  internal/extsvc/github/user.go
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
  internal/extsvc/github/v4.go
  internal/extsvc/github/version.go
Labels: team/core-application

#21248 Add warnings about one version at a time
  doc/admin/updates.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
Labels: team/distribution

#21226 Fix error message for edit code stats page
  client/web/src/insights/pages/edit/EditInsightPage.tsx
Labels: code-insights-creation-ui, team/code-insights, webapp

#21239 ci: rename master-dry-run prefix to main-dry-run
  dev/gqltest/README.md
  doc/dev/how-to/testing.md
  enterprise/dev/ci/internal/ci/helpers.go
  enterprise/dev/ci/internal/ci/pipeline-steps.go
Labels: dx

#21195 graphqlbackend: Gracefully handle some code host failures for AffiliatedRepos
  cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
  cmd/frontend/graphqlbackend/codehost_repository_connection.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/testing.go
Labels: team/core-application
