Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-06, with the labels that each got.

#36270 [SG-35732] [Accessibility]: In Code Monitors create/edit page, errors when calling webhooks/sending email should be announced
  client/web/src/enterprise/code-monitoring/components/__snapshots__/FormActionArea.test.tsx.snap
  client/web/src/enterprise/code-monitoring/components/actions/ActionEditor.tsx
  client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.tsx
  client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.tsx
Labels: gitstart, cla-signed

#36132 [SG-35169] Saved Searches ARC toolkit issues
  client/web/src/savedSearches/SavedSearchForm.tsx
  client/web/src/savedSearches/SavedSearchListPage.tsx
  client/web/src/user/area/UserAreaHeader.tsx
Labels: gitstart, cla-signed

#36203 [SG-34530] Accessibility: Focus outline on tabs pushes content down
  client/wildcard/src/components/Tabs/Tabs.module.scss
Labels: gitstart, cla-signed

#36334 web: fix duplicate stories
  client/web/src/components/ActivationDropdown/ActivationDropdown.story.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-404-insight/Standalone404Insight.story.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.story.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/components/code-insights-examples-picker/code-insights-examples-slider/CodeInsightsExamplesSlider.story.tsx
Labels: team/frontend-platform, cla-signed

#36225 Code Insights: Fix "default filters applied" appearance
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
Labels: cla-signed

#36197 search: run Zoekt to completion before any searcher jobs on Sourcegraph.com
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
Labels: cla-signed

#36296 cloud: Enable the purge worker on Cloud
  cmd/repo-updater/shared/main.go
  internal/repos/purge.go
Labels: team/repo-management, cla-signed

#36291 repo-updater: move vcs/git/MergeBase to gitserver/commands
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/repository_comparison_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/main_test.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mock_client.go
  internal/gitserver/mocks.go
  internal/vcs/git/merge_base.go
  internal/vcs/git/merge_base_test.go
Labels: cla-signed

#36309 insights: retry queries that encounter `shard-timeout` events
  enterprise/internal/insights/query/streaming/decoder.go
  enterprise/internal/insights/query/streaming_query_executor.go
Labels: cla-signed

#36349 gitserver: Track the number of repos on the wrong shard
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
Labels: team/repo-management, cla-signed

#36360 Run `yarn generate` before `scip-typescript index`
  .github/workflows/scip-typescript.yml
Labels: cla-signed, team/language-tools, iteration-22-11

#36366 migration: Simplify idempotency tests
  internal/database/connections/live/migration_test.go
Labels: cla-signed

#36335 dev/sg: add 1pass to sg setup
  dev/sg/sg_setup_mac.go
  dev/sg/sg_setup_shared.go
  dev/sg/sg_setup_ubuntu.go
Labels: cla-signed

#36356 Ref panel: don't hardcode token into line contents
  client/web/src/codeintel/ReferencesPanel.test.tsx
  client/web/src/codeintel/ReferencesPanel.tsx
Labels: cla-signed

#36369 repo-updater: move git.RevList and git.RevListEach from vcs/git to gitserver/commands
  enterprise/cmd/symbols/main.go
  enterprise/internal/rockskip/server_test.go
  internal/gitserver/commands.go
  internal/vcs/git/refs.go
Labels: cla-signed

#36275 [SG-35699] Accessibility: Email sign up form input elements are not linked to their error states properly
  client/web/src/auth/SignUpForm.tsx
  client/web/src/auth/SignupEmailField.tsx
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
Labels: gitstart, cla-signed

#36277 search: update error message for structural query alert
  dev/gqltest/search_test.go
  internal/search/alert.go
Labels: cla-signed

#36365 httpapi: handle empty IndexedIDs
  cmd/frontend/internal/httpapi/search.go
Labels: cla-signed

#36386 fix accidentally returning soft error
  enterprise/internal/insights/background/historical_enqueuer.go
Labels: cla-signed

#36331 web: revert DynamicallyImportedMonacoSettingsEditor change in #36033
  client/web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
Labels: cla-signed

#36336 dev/sg: add 1pass secret provider, use 1pass for OkayHQ token
  dev/sg/internal/secrets/secret.go
  dev/sg/internal/secrets/store.go
  dev/sg/sg_analytics.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#36315 gitserver: fix usage of loggers in cleanup
  cmd/gitserver/main.go
  cmd/gitserver/main_test.go
  cmd/gitserver/server/cleanup.go
Labels: cla-signed

#36391 batches: fix another flaky story by hardcoding a finish time
  client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.story.tsx
Labels: cla-signed

#36194 Fix popover appearing on page load without being pinned
  client/codeintellify/src/hoverifier.ts
Labels: cla-signed

#36244 refactor(repo-updater): update repo.Store to use lib/log
  cmd/repo-updater/repoupdater/server_test.go
  cmd/repo-updater/shared/main.go
  enterprise/cmd/repo-updater/internal/authz/integration_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  internal/repos/integration_test.go
  internal/repos/mocks.go
  internal/repos/status_messages_test.go
  internal/repos/store.go
  lib/log/fields.go
Labels: cla-signed

#36198 Fix token-click URL getting overwritten
  client/web/src/repo/blob/Blob.tsx
Labels: cla-signed

#36392 Search backend: fix multibyte line match conversion
  internal/search/result/file.go
  internal/search/result/file_test.go
Labels: cla-signed

#36393 Search backend: rename HunkMatch to ChunkMatch
  cmd/frontend/graphqlbackend/file_match.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_stats_languages.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_test.go
  cmd/frontend/internal/search/decorate.go
  cmd/frontend/internal/search/search.go
  enterprise/cmd/frontend/internal/compute/resolvers/resolvers_test.go
  enterprise/internal/compute/match_only_command.go
  enterprise/internal/compute/match_only_command_test.go
  internal/search/result/deduper_test.go
  internal/search/result/file.go
  internal/search/result/file_test.go
  internal/search/searcher/search.go
  internal/search/streaming/search_filters_test.go
  internal/search/streaming/stream_test.go
  internal/search/textsearch/textsearch_test.go
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#36380 fix(tracking-issue-syncer): soft fail when error is API rate limit error
  internal/cmd/tracking-issue/main.go
  internal/cmd/tracking-issue/main_test.go
Labels: cla-signed

#36400 Search backend: add chunk matches to the searcher protocol
  cmd/searcher/protocol/searcher.go
  internal/search/searcher/search.go
Labels: cla-signed

#36406 doc: include a direct link to GitHub with the right scopes
  doc/batch_changes/how-tos/configuring_credentials.md
Labels: docs, github, team/batchers, cla-signed

#36403 Add link to bottom of annotation
  dev/ci/trivy/trivy-scan-high-critical.sh
Labels: cla-signed

#36405 codeintel: Fix worker task alerts
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  enterprise/cmd/worker/main.go
  monitoring/definitions/worker.go
Labels: team/code-intelligence, cla-signed

#36413 Trivy annotation
  dev/ci/trivy/trivy-scan-high-critical.sh
Labels: cla-signed

#36410 Search backend: use ChunkMatch type for structural search
  cmd/searcher/internal/search/search_structural.go
  cmd/searcher/internal/search/search_structural_test.go
  cmd/searcher/internal/search/search_test.go
  cmd/searcher/protocol/searcher.go
  internal/search/searcher/search.go
Labels: cla-signed

#35881 chore: refactor CodeExcerpt to a function component
  client/branded/src/components/panel/TabbedPanelContent.tsx
  client/branded/src/components/panel/views/FileLocations.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/branded/src/components/panel/views/PanelView.tsx
  client/search-ui/src/components/CodeExcerpt.module.scss
  client/search-ui/src/components/CodeExcerpt.test.tsx
  client/search-ui/src/components/CodeExcerpt.tsx
  client/search-ui/src/components/FileMatchChildren.test.tsx
  client/search-ui/src/components/FileMatchChildren.tsx
  client/search-ui/src/components/FileSearchResult.test.tsx
  client/search-ui/src/components/FileSearchResult.tsx
  client/search-ui/src/components/index.ts
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/shared/src/backend/file.ts
  client/shared/src/components/CodeExcerpt.tsx
  client/vscode/src/webview/search-panel/SearchResultsView.tsx
  client/vscode/src/webview/search-panel/alias/FileMatchChildren.tsx
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
  client/web/src/notebooks/index.ts
  client/web/src/notebooks/notebookPage/EmbeddedNotebookPage.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
Labels: cla-signed

#36308 [SG-34733] Accessibility: Search box ARC checklist issues
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/search-ui/src/input/MonacoQueryInput.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.test.tsx
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.test.tsx
Labels: gitstart, cla-signed

#36345 Code Insights: Update visx packages and remove legacy unused chart packages
  client/web/src/charts/components/line-chart/LineChart.tsx
  package.json
  yarn.lock
Labels: cla-signed

#36422 monitoring: allow validation errors to aggregate and return all at once
  monitoring/main.go
  monitoring/monitoring/generator.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#36439 release: update release config for 3.41.0
  dev/release/release-config.jsonc
Labels: cla-signed, team/iam-admin-experience

#36430 web: fix `CommandList` autofocus
  client/shared/src/commandPalette/CommandList.tsx
  client/web/src/components/FilteredConnection/ui/ConnectionForm.module.scss
  client/web/src/components/FilteredConnection/ui/ConnectionForm.tsx
  client/web/src/repo/releases/__snapshots__/RepositoryReleasesTagsPage.test.tsx.snap
Labels: team/frontend-platform, cla-signed

#36440 Settings fix follow up
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
Labels: cla-signed, team/iam-admin-experience

#36357 httpapi: remove unused internal UsersGetByUsername
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/httpapi/router/router.go
  internal/api/internalapi/client.go
Labels: cla-signed

#33783 searcher: hybrid search with zoekt
  cmd/searcher/internal/search/hybrid.go
  cmd/searcher/internal/search/hybrid_test.go
  cmd/searcher/internal/search/search.go
  cmd/searcher/internal/search/store.go
  cmd/searcher/main.go
  cmd/searcher/protocol/searcher.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/printers_test.go
  internal/search/job/jobutil/repo_pager_job_test.go
  internal/search/run/repo_has_file.go
  internal/search/searcher/client.go
  internal/search/searcher/search.go
  internal/search/structural/structural.go
  internal/search/types.go
Labels: cla-signed

#36358 httpapi: remove unused internal CanSendEmail
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/httpapi/router/router.go
  internal/api/internalapi/client.go
Labels: cla-signed

#36458 web: revert sign-in `Input` layout change
  client/web/src/auth/UsernamePasswordSignInForm.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
Labels: accessibility, team/frontend-platform, cla-signed

#36341 Code Insights: Add insight dashboard pills component
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/SmartInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/deserialization/create-insight-view.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/gql/GetInsights.ts
  client/web/src/enterprise/insights/core/types/insight/common.ts
  client/web/src/enterprise/insights/core/types/insight/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/capture-group-insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/utils/insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/dashboard-pills/StandaloneInsightDashboardPills.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/components/dashboard-pills/StandaloneInsightDashboardPills.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/fixtures/insights-metadata.ts
Labels: cla-signed

#36465 codemirror: Fix aria-label for search query input
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
Labels: cla-signed

#36467 db: add explicit_permissions_bitbucket_projects_jobs table
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1654168174/down.sql
  migrations/frontend/1654168174/metadata.yaml
  migrations/frontend/1654168174/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, bitbucket-project-permissions

#36446 Correct markdown around you/private example code
  doc/admin/deploy/docker-compose/index.md
Labels: cla-signed

#36476 gitserver: Store clone error in database
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
Labels: team/repo-management, cla-signed

#36449 database: remove dbutil-based constructors
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/person.go
  cmd/frontend/graphqlbackend/set_user_public_repos.go
  cmd/frontend/graphqlbackend/site_admin.go
  cmd/frontend/graphqlbackend/site_flags.go
  cmd/frontend/graphqlbackend/tags.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/users.go
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/auth/userpasswd/handlers.go
  cmd/frontend/internal/auth/userpasswd/reset_password.go
  cmd/frontend/internal/session/session.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_middleware.go
  enterprise/cmd/frontend/internal/dotcom/billing/customers_test.go
  enterprise/cmd/frontend/internal/dotcom/billing/db_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_db_test.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users.go
  enterprise/cmd/frontend/internal/licensing/init/init.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/stars_resolvers_test.go
  enterprise/cmd/frontend/internal/registry/stores/extensions_test.go
  enterprise/cmd/frontend/internal/registry/stores/releases_test.go
  enterprise/internal/database/authz_test.go
  enterprise/internal/database/perms_store_test.go
  enterprise/internal/insights/migration/migration.go
  enterprise/internal/notebooks/store_test.go
  internal/database/access_tokens_test.go
  internal/database/event_logs_test.go
  internal/database/external_accounts_test.go
  internal/database/external_services_test.go
  internal/database/feature_flags_test.go
  internal/database/namespaces_test.go
  internal/database/org_members_db_test.go
  internal/database/orgs_test.go
  internal/database/repos_db_test.go
  internal/database/repos_perm_test.go
  internal/database/saved_searches_test.go
  internal/database/search_contexts.go
  internal/database/search_contexts_test.go
  internal/database/settings_test.go
  internal/database/survey_responses_test.go
  internal/database/temporary_settings_test.go
  internal/database/user_credentials_test.go
  internal/database/user_emails_test.go
  internal/database/user_public_repos.go
  internal/database/user_public_repos_test.go
  internal/database/users.go
  internal/database/users_builtin_auth_test.go
  internal/database/users_test.go
  internal/repos/status_messages_test.go
  internal/search/searchcontexts/search_contexts_test.go
  internal/usagestats/batches_test.go
  internal/usagestats/usage_stats.go
  internal/usagestats/usage_stats_test.go
Labels: cla-signed, team/iam-admin-experience

#36202 Add allowSignup attribute to GitLab auth provider configuration
  doc/admin/auth/index.md
  enterprise/cmd/frontend/internal/auth/gitlaboauth/provider.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam-admin-experience

#35749 FetchAccount method implementation for Gerrit
  enterprise/internal/authz/gerrit/authz.go
  enterprise/internal/authz/gerrit/client.go
  enterprise/internal/authz/gerrit/gerrit.go
  enterprise/internal/authz/gerrit/gerrit_test.go
  internal/extsvc/gerrit/account.go
  internal/extsvc/gerrit/client.go
  internal/types/external_services.go
Labels: cla-signed

#36423 proposal(monitoring): forbid critical alerts with no solutions
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/alerting.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/frontend.go
  monitoring/definitions/postgres.go
  monitoring/definitions/shared/kubernetes.go
  monitoring/definitions/zoekt.go
  monitoring/monitoring/monitoring.go
Labels: team/devx, cla-signed, devx/metrics

#36426 dev/sg: add 'sg gen' alias for generate
  dev/sg/sg_generate.go
Labels: cla-signed

#36425 dev/ci: run docker-images builds if docker-images has been changed
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/changed/diff.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#36485 Fix PGHOST env var in sg.config.yaml
  sg.config.yaml
Labels: cla-signed

#36489 dev/sg: fix interactive setup, simplify 1pass check
  dev/sg/sg_setup.go
  dev/sg/sg_setup_mac.go
  dev/sg/sg_setup_shared.go
  dev/sg/sg_setup_ubuntu.go
Labels: cla-signed

#36493 bump codenotify version in github workflow
  .github/workflows/codenotify.yml
Labels: cla-signed

#36491 Prevent IDE error message when closing a project
  client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/JCEFService.java
  client/jetbrains/src/main/java/com/sourcegraph/find/PreviewPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java
Labels: cla-signed

#36500 monitoring: rebrand PossibleSolutions as NextSteps
  doc/_resources/assets/redirects
  doc/admin/faq.md
  doc/admin/how-to/monitoring-guide.md
  doc/admin/how-to/monorepo-issues.md
  doc/admin/how-to/site-admin-quickstart.md
  doc/admin/how-to/troubleshoot-pod-eviction.md
  doc/admin/observability/alerting.md
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  doc/admin/observability/index.md
  doc/admin/observability/metrics.md
  doc/dev/background-information/observability/monitoring-generator.md
  doc/dev/how-to/monitoring_local_dev.md
  docker-images/prometheus/cmd/prom-wrapper/receivers.go
  docker-images/prometheus/cmd/prom-wrapper/receivers_test.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/github_proxy.go
  monitoring/definitions/postgres.go
  monitoring/definitions/prometheus.go
  monitoring/definitions/redis.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/searcher.go
  monitoring/definitions/shared/container.go
  monitoring/definitions/shared/dbconns.go
  monitoring/definitions/shared/frontend.go
  monitoring/definitions/shared/go.go
  monitoring/definitions/shared/kubernetes.go
  monitoring/definitions/shared/provisioning.go
  monitoring/definitions/shared/shared.go
  monitoring/definitions/worker.go
  monitoring/definitions/zoekt.go
  monitoring/monitoring/documentation.go
  monitoring/monitoring/generator.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#36502 set scoped backfill to a higher than normal priority
  enterprise/internal/insights/background/historical_enqueuer.go
Labels: cla-signed

#36416 Migration to add unique index to external_services
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1654116265/down.sql
  migrations/frontend/1654116265/metadata.yaml
  migrations/frontend/1654116265/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/iam-admin-experience

#36497 edit mutation
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/resolvers/resolver.go
  enterprise/internal/insights/service/service.go
Labels: cla-signed

#36421 added a feature flag for homePanelsComputeSuggestions
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#36429 symbols: Refactor params type
  cmd/symbols/fetcher/repository_fetcher.go
  cmd/symbols/fetcher/repository_fetcher_test.go
  cmd/symbols/internal/api/handler.go
  cmd/symbols/internal/api/search_sqlite.go
  cmd/symbols/internal/database/store/search.go
  cmd/symbols/internal/database/store/store.go
  cmd/symbols/internal/database/writer/cache.go
  cmd/symbols/internal/database/writer/writer.go
  cmd/symbols/parser/parser.go
  cmd/symbols/types/types.go
  enterprise/cmd/symbols/main.go
  enterprise/internal/rockskip/search.go
  enterprise/internal/rockskip/server_test.go
Labels: cla-signed

#36432 Search backend: DRY out searcher streams
  cmd/searcher/internal/search/search_regex.go
  cmd/searcher/internal/search/sender.go
Labels: team/search-product, cla-signed

#36433 Search backend: simplify newToMatches
  internal/search/searcher/search.go
Labels: team/search-product, cla-signed

#36200 Rockskip: add more help info to the status page and docs
  doc/code_intelligence/explanations/rockskip.md
  enterprise/internal/rockskip/status.go
Labels: cla-signed

#36508 search: make sequential job send unique results only
  internal/search/job/jobutil/combinators.go
  internal/search/job/jobutil/combinators_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/mapper.go
Labels: cla-signed

#36447 [SG-34728] Accessibility: Search results page misc mobile bugs
  client/search-ui/src/components/FileMatchChildren.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
Labels: gitstart, cla-signed

#36204 [SG-34738] Accessibility: Search results ARC checklist issues
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/search-ui/src/components/CodeHostIcon.tsx
  client/search-ui/src/components/ResultContainer.tsx
  client/search-ui/src/components/SearchResultStar.tsx
  client/search-ui/src/input/toggles/QueryInputToggle.tsx
  client/search-ui/src/input/toggles/Toggles.tsx
  client/search-ui/src/results/sidebar/FilterLink.test.tsx
  client/search-ui/src/results/sidebar/__snapshots__/FilterLink.test.tsx.snap
Labels: gitstart, cla-signed

#36160 searcher: TMPDIR on CACHE_DIR
  CHANGELOG.md
  cmd/searcher/main.go
  internal/diskcache/cache.go
  internal/diskcache/cache_test.go
Labels: cla-signed

#36474 extsvc/bitbucketserver: add function which fetches all repos of a given Bitbucket project
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
  internal/extsvc/bitbucketserver/testdata/golden/ProjectRepos
  internal/extsvc/bitbucketserver/testdata/vcr/ProjectRepos.yaml
Labels: team/repo-management, cla-signed, bitbucket-project-permissions

#35534 [SG-35284] Wildcard V2: Apply <Input /> Codemod `client/web/org` `client/web/repo` `client/web/savedSearches` `client/web/site-admin` `client/web/user`
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexesPage.tsx
  client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadPage.tsx
  client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListTab.tsx
  client/web/src/extensions/ExtensionRegistry.tsx
  client/web/src/integration/extension-registry.test.ts
  client/web/src/integration/org.test.ts
  client/web/src/integration/profile.test.ts
  client/web/src/org/new/NewOrganizationPage.tsx
  client/web/src/org/openBeta/NewOrganizationPage.tsx
  client/web/src/org/settings/members-v1/InviteForm.tsx
  client/web/src/org/settings/profile/OrgSettingsProfilePage.tsx
  client/web/src/regression/core.test.ts
  client/web/src/repo/settings/RepoSettingsMirrorPage.tsx
  client/web/src/repo/settings/RepoSettingsOptionsPage.tsx
  client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
  client/web/src/repo/tree/BranchesTab.tsx
  client/web/src/savedSearches/SavedSearchForm.tsx
  client/web/src/site-admin/SiteAdminFeatureFlagConfigurationPage.tsx
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
  client/web/src/user/settings/auth/UserSettingsPasswordPage.tsx
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
  client/web/src/user/settings/codeHosts/AddCodeHostConnectionModal.tsx
  client/web/src/user/settings/codeHosts/UpdateCodeHostConnectionModal.tsx
  client/web/src/user/settings/emails/AddUserEmailForm.tsx
  client/web/src/user/settings/profile/UserProfileFormFields.tsx
  client/web/src/user/settings/repositories/components/FilterInput/FilterInput.tsx
Labels: cla-signed

#36523 gitserver: Ensure we always record clone error
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
Labels: team/repo-management, cla-signed

#36522 database: make SetRepoPermissionsUnrestricted accept more than 65535 repo IDs
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_test.go
Labels: team/repo-management, cla-signed, bitbucket-project-permissions

#36488 Fix FeatureFlagClient to handle race conditions calls
  client/web/src/featureFlags/FeatureFlagsProvider.tsx
  client/web/src/featureFlags/lib/FeatureFlagClient.test.ts
  client/web/src/featureFlags/lib/FeatureFlagClient.ts
  client/web/src/featureFlags/useFeatureFlag.test.tsx
  client/web/src/featureFlags/useFeatureFlag.ts
  client/web/src/featureFlags/withFeatureFlag.test.tsx
  client/web/src/featureFlags/withFeatureFlag.tsx
  client/web/src/tour/GettingStartedTour.tsx
Labels: cla-signed

#34802 JetBrains: Create Java→JS bridge
  client/jetbrains/src/main/java/com/sourcegraph/browser/JavaToJSBridge.java
  client/jetbrains/src/main/java/com/sourcegraph/browser/SourcegraphJBCefBrowser.java
  client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java
  client/jetbrains/webview/src/search/index.tsx
  client/jetbrains/webview/src/search/java-to-js-bridge.ts
  client/jetbrains/webview/src/search/types.d.ts
Labels: cla-signed

#36496 JetBrains: Fix up GitUtil
  client/jetbrains/src/main/java/com/sourcegraph/git/GitUtil.java
Labels: cla-signed

#36478 JetBrains: create settings UI
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SourcegraphConfig.java
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#36464 Implement cleanup of repos that are cloned on the wrong shard
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
Labels: team/repo-management, cla-signed, team/iam-admin-experience

#36550 gomod: bump pgtype version for hstore fixes
  enterprise/internal/database/code_monitor_queries_test.go
  enterprise/internal/insights/store/store_test.go
  enterprise/internal/insights/store/testdata/TestDeleteSnapshots.golden
  go.mod
  go.sum
  internal/database/repos_test.go
Labels: cla-signed

#36205 [SG-34723] Accessibility: Search results misc keyboard bugs
  client/search-ui/src/components/LastSyncedIcon.tsx
  client/search-ui/src/results/progress/StreamingProgressCount.tsx
  client/search-ui/src/results/progress/__snapshots__/StreamingProgressCount.test.tsx.snap
  client/web/src/savedSearches/SavedSearchForm.tsx
  client/wildcard/src/components/ButtonLink/ButtonLink.tsx
Labels: gitstart, cla-signed

#36545 Update deployment flow docker compose
  doc/admin/deploy/docker-compose/index.md
Labels: cla-signed

#36472 Split large log lines up into smaller pieces
  dev/sg/internal/loki/loki.go
  dev/sg/internal/loki/loki_test.go
Labels: cla-signed

#36552 Fix highlighting fallback to plain text on error
  cmd/frontend/internal/highlight/highlight.go
Labels: cla-signed

#35709 Increase max-age of assets to 1 year
  cmd/frontend/internal/app/assetsutil/handler.go
Labels: cla-signed

#36559 doc/dev/setup: Fix typo
  doc/dev/setup/quickstart.md
Labels: docs, cla-signed

#36475 batches: allow code snippet display overflow
  client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.tsx
Labels: cla-signed

#36486 Commit/diff search: remove limits
  CHANGELOG.md
  internal/search/alert/observer.go
  internal/search/alert/observer_test.go
  internal/search/commit/commit.go
  internal/search/job/jobutil/job.go
Labels: cla-signed

#36514 search: frontend scaffolding for 'Feeling Lucky' search mode
  client/search-ui/src/input/toggles/Toggles.tsx
  client/shared/src/search/query/scanner.ts
  cmd/frontend/graphqlbackend/schema.graphql
  internal/search/query/query.go
  internal/search/query/types.go
  internal/search/run/run.go
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#36572 Update DevX and FPT notifications
  .github/workflows/label-notify.yml
Labels: cla-signed

#36518 search: export ZoektGlobalQuery fields
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/symbol_search.go
  internal/search/zoekt/zoekt_global.go
Labels: cla-signed

#36579 typo: occurrence has a double r.
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/lsif/html.ts
  cmd/frontend/internal/highlight/html.go
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
  enterprise/dev/ci/internal/buildkite/buildkite.go
  internal/cmd/tracking-issue/testdata/fixtures.json
Labels: cla-signed

#36577 dev/ci: remove set -x in all tests
  dev/ci/go-test.sh
  dev/ci/integration/backend/test.sh
  dev/ci/integration/cluster/test.sh
  dev/ci/integration/code-intel/test.sh
  dev/ci/integration/e2e/test.sh
  dev/ci/integration/qa/test.sh
  dev/ci/integration/upgrade/test.sh
  dev/ci/reset-test-db.sh
Labels: cla-signed

#36519 search: add rule transformation and unquoting to lucky search
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/alert.go
  internal/search/job/jobutil/feeling_lucky_search_job.go
  internal/search/job/jobutil/feeling_lucky_search_job_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/default_rules.golden
  internal/search/query/labels.go
  internal/search/query/mapper.go
  internal/search/query/mapper_test.go
  internal/search/query/parser.go
  internal/search/query/parser_test.go
  internal/search/query/query.go
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
  internal/search/query/types.go
  internal/search/query/validate_test.go
Labels: cla-signed

#36585 fixes whitescreen crash with datadog
  client/web/src/monitoring/datadog/datadogClient.ts
Labels: cla-signed

#36554 lib/log: add IncreaseLevel to make a quieter child logger
  lib/log/logger.go
  lib/log/logtest/logtest.go
Labels: cla-signed

#36586 Search backend: fix issues with null and zero-length offsetAndLength
  internal/search/result/file.go
  internal/search/result/file_test.go
Labels: team/search-product, cla-signed

#36574 lib/process: always pipe _exactly_ what the command outputs
  lib/process/pipe.go
  lib/process/pipe_test.go
Labels: cla-signed

#36553 wildcard `<Input />` Migration: Fixed UI regressions on Input
  client/web/src/user/settings/repositories/RepositoryNode.tsx
  client/web/src/user/settings/repositories/SelectAffiliatedRepos.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/web/src/user/settings/repositories/components/FilterInput/FilterInput.module.scss
  client/web/src/user/settings/repositories/components/FilterInput/FilterInput.tsx
Labels: cla-signed

#36602 web: fix `input` width
  client/web/src/extensions/ExtensionRegistry.tsx
  client/web/src/extensions/ExtensionRegistrySidenav.tsx
Labels: bug, team/frontend-platform, cla-signed

#36604 Code Insights: Fix drill down input font family styles
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-input/DrillDownInput.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/search-context/DrillDownSearchContextFilter.module.scss
Labels: cla-signed

#36633 fix-markdown-numbered-lists
  doc/admin/deploy/docker-compose/index.md
Labels: cla-signed

#36643 Accessibility: Update FilteredConnection to support better usage of labels
  client/web/src/components/FilteredConnection/FilteredConnection.tsx
  client/web/src/repo/releases/__snapshots__/RepositoryReleasesTagsPage.test.tsx.snap
Labels: team/frontend-platform, cla-signed

#36649 CI: Fix Tooltip imports causing TS build to fail
  client/vscode/src/webview/platform/context.ts
  client/vscode/src/webview/search-panel/index.tsx
  client/vscode/src/webview/sidebars/search/index.tsx
  tsconfig.all.json
Labels: team/frontend-platform, cla-signed

#36627 [SG-35155] Code monitoring ARC checklist issues
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/wildcard/src/components/PageHeader/Breadcrumb/Breadcrumb.tsx
  client/wildcard/src/components/PageHeader/__snapshots__/PageHeader.test.tsx.snap
Labels: gitstart, cla-signed

#36539 vcs/git: Move some types into gitdomain
  cmd/frontend/graphqlbackend/repository_git_refs.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec_test.go
  enterprise/internal/batches/reconciler/executor_test.go
  enterprise/internal/batches/reconciler/main_test.go
  enterprise/internal/batches/reconciler/reconciler_test.go
  enterprise/internal/batches/sources/bitbucketcloud.go
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/common.go
  enterprise/internal/batches/sources/github.go
  enterprise/internal/batches/sources/gitlab.go
  enterprise/internal/batches/testing/changeset.go
  enterprise/internal/batches/types/changeset.go
  internal/gitserver/commands.go
  internal/gitserver/gitdomain/common.go
  internal/gitserver/gitdomain/common_test.go
  internal/search/repo_revs.go
  internal/search/textsearch/textsearch_test.go
  internal/vcs/git/refs.go
  internal/vcs/git/refs_test.go
Labels: team/repo-management, cla-signed

#36317 checkbox misalignment fix
  client/web/src/user/settings/repositories/RepositoryNode.tsx
Labels: cla-signed

#36546 move GetBehindAhead function to gitserver package
  cmd/frontend/graphqlbackend/git_commit.go
  internal/gitserver/commands.go
  internal/vcs/git/refs.go
Labels: cla-signed

#36655 Janitor fixes
  cmd/gitserver/server/cleanup.go
Labels: team/repo-management, cla-signed

#36445 perms: remove redundant `ListExternalAccounts` method
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/database/authz.go
  enterprise/internal/database/integration_test.go
  enterprise/internal/database/mocks.go
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_test.go
Labels: cla-signed, team/iam-admin-experience

#36642 Changelog: Fix a spelling mistake
  CHANGELOG.md
Labels: team/repo-management, cla-signed

#36616 SSBC: Enable by default in dev environment
  dev/global-settings.json
Labels: cla-signed

#36408 Add docs for new startup probes on Postgres containers
  CHANGELOG.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#36196 vsce: optimize package size
  client/vscode/.vscodeignore
  client/vscode/CHANGELOG.md
  client/vscode/package.json
  client/vscode/webpack.config.js
Labels: team/integrations, cla-signed, vscode-extension

#36667 Search backend: add tracing to SequentialJob
  internal/search/job/jobutil/combinators.go
Labels: cla-signed

#36644 fix buildchecker cron schedule
  .github/workflows/buildchecker-history.yml
Labels: cla-signed, devx/ci-metrics

#36669 Code monitors: add --glob and --exclude to git rev-parse allowlist
  internal/gitserver/gitdomain/exec.go
  internal/gitserver/gitdomain/exec_test.go
Labels: team/search-product, cla-signed

#36494 Upgrade marked dependency
  package.json
  yarn.lock
Labels: cla-signed

#36670 batches: disable chromatic snapshot checking for `ExecutionWorkspaces`
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/ExecutionWorkspaces.story.tsx
Labels: team/batchers, cla-signed

#36668 vsce: remove alias for Links component
  client/vscode/package.json
  client/vscode/src/webview/search-panel/alias/Link.tsx
  client/vscode/webpack.config.js
Labels: cla-signed, vscode-extension

#36674 Saved searches: fix update permissions
  CHANGELOG.md
  cmd/frontend/graphqlbackend/saved_searches.go
  cmd/frontend/graphqlbackend/saved_searches_test.go
Labels: team/search-product, cla-signed

#36636 Prevent search input auto focus on touch device
  client/web/src/search/home/SearchPageInput.tsx
Labels: cla-signed

#34875 Search-based tree-sitter traversals for Java
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/symbols/squirrel/breadcrumbs.go
  cmd/symbols/squirrel/http_handlers.go
  cmd/symbols/squirrel/lang_java.go
  cmd/symbols/squirrel/languages.go
  cmd/symbols/squirrel/local_code_intel.go
  cmd/symbols/squirrel/local_code_intel_test.go
  cmd/symbols/squirrel/service.go
  cmd/symbols/squirrel/service_test.go
  cmd/symbols/squirrel/test_repos/java1/Sample.java
  cmd/symbols/squirrel/test_repos/java1/src/sub/Sample.java
  cmd/symbols/squirrel/test_repos/java1/src/sub/Sample2.java
  cmd/symbols/squirrel/test_repos/java1/src/sub/sub2/Sample3.java
  cmd/symbols/squirrel/util.go
  internal/types/codeintel.go
Labels: cla-signed

#36615 batches: fix ordinal representation of queue rank
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx
  package.json
  yarn.lock
Labels: cla-signed

#36682 Fix small styling issues on workspace page
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.module.scss
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceStateIcon.tsx
Labels: cla-signed

#36609 symbols: Better debug page
  cmd/symbols/squirrel/http_handlers.go
Labels: cla-signed

#36599 symbols: Consolidate spawning of ctags
  cmd/symbols/parser/parser.go
  cmd/symbols/parser/parser_factory.go
  cmd/symbols/parser/parser_factory_ctags.go
  cmd/symbols/parser/parser_factory_ctags_test.go
  cmd/symbols/parser/parser_pool.go
  cmd/symbols/shared/sqlite.go
  dev/sg/linters/liblog.go
  enterprise/cmd/symbols/main.go
  enterprise/internal/rockskip/index.go
  enterprise/internal/rockskip/search.go
  enterprise/internal/rockskip/server.go
  enterprise/internal/rockskip/server_test.go
Labels: cla-signed

#36328 remove redundant sort call on points
  client/web/src/charts/components/line-chart/LineChart.tsx
Labels: cla-signed

#36134 feat: Add jsonnet highlighting support
  cmd/frontend/internal/highlight/language.go
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/sg-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/sg-syntax/queries/jsonnet/highlights.scm
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
  internal/gosyntect/gosyntect.go
Labels: cla-signed

#36437 web: upgrade Storybook
  .eslintrc.js
  client/build-config/src/paths.ts
  client/shared/src/testing/integration/context.ts
  client/storybook/package.json
  client/storybook/src/chromatic-story/Chromatic.story.tsx
  client/storybook/src/chromatic-story/add-story.ts
  client/storybook/src/chromatic-story/create-chromatic-story.tsx
  client/storybook/src/chromatic-story/story-store.ts
  client/storybook/src/decorators/withChromaticThemes/ChromaticRoot/ChromaticRoot.module.scss
  client/storybook/src/decorators/withChromaticThemes/ChromaticRoot/ChromaticRoot.tsx
  client/storybook/src/decorators/withChromaticThemes/ChromaticRoot/index.ts
  client/storybook/src/decorators/withChromaticThemes/index.ts
  client/storybook/src/decorators/withChromaticThemes/withChromaticThemes.tsx
  client/storybook/src/environment-config.ts
  client/storybook/src/hooks/useChromaticTheme.ts
  client/storybook/src/hooks/useTheme.ts
  client/storybook/src/index.ts
  client/storybook/src/main.ts
  client/storybook/src/preview.ts
  client/storybook/src/utils/isChromatic.ts
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/manifestPlugin.ts
  client/web/dev/esbuild/monacoPlugin.ts
  client/web/dev/esbuild/server.ts
  client/web/dev/esbuild/stylePlugin.ts
  client/web/dev/server/development.server.ts
  client/web/dev/server/production.server.ts
  client/web/dev/utils/constants.ts
  client/web/dev/webpack/get-html-webpack-plugins.ts
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.story.module.scss
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.story.tsx
  client/web/src/enterprise/batches/list/BatchChangeNode.story.tsx
  client/web/src/hooks/usePersistentCadence.ts
  client/wildcard/src/components/Modal/Modal.story.tsx
  client/wildcard/src/components/Popover/Popover.tsx
  client/wildcard/src/components/Popover/components/PopoverTrigger.tsx
  client/wildcard/src/components/Popover/components/floating-panel/FloatingPanel.tsx
  client/wildcard/src/components/Popover/components/popover-content/PopoverContent.tsx
  client/wildcard/src/components/Popover/components/popover-tail/PopoverTail.tsx
  client/wildcard/src/components/Popover/contexts/internal-context.ts
  client/wildcard/src/components/Popover/contexts/public-context.ts
  client/wildcard/src/components/Popover/index.ts
  client/wildcard/src/components/Popover/story/Popover.story.tsx
  client/wildcard/src/components/index.ts
  package.json
  yarn.lock
Labels: team/frontend-platform, cla-signed

#36452 [SG-34721] Accessibility: Add saved search" button on empty saved searches panel doesn't activate with spacebar
  client/web/src/search/panels/SavedSearchesPanel.tsx
Labels: gitstart, cla-signed

#36689 search: parse 'lucky' patterntype value in url
  client/web/src/search/index.tsx
Labels: cla-signed

#36694 ci: fix adr how-to link
  doc/dev/adr/index.md
Labels: cla-signed

#36700 adr: fix template
  dev/adr-docs/index.md.tmpl
Labels: cla-signed

#36714 Stop running linters concurrently
  dev/adr-docs/index.md.tmpl
  dev/adr-docs/main.go
  dev/sg/sg_lint.go
  doc/dev/adr/index.md
Labels: ci, team/devx, cla-signed

#36720 ci: disable terminal auto detect
  enterprise/dev/ci/scripts/upload-build-logs.sh
Labels: cla-signed

#36693 Check per janitor run
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
Labels: team/repo-management, cla-signed

#36381 JetBrains: Capture all possible theme colors for the JS -> Java bridge and add debugging view in standalone mode
  client/jetbrains/gradle.properties
  client/jetbrains/src/main/java/com/sourcegraph/config/ThemeUtil.java
  client/jetbrains/src/main/resources/META-INF/plugin.xml
  client/jetbrains/standalone/src/index.html
  client/jetbrains/webview/src/bridge-mock/index.ts
  client/jetbrains/webview/src/bridge-mock/renderColorDebugger.tsx
  client/jetbrains/webview/src/bridge-mock/theme-snapshots/dark.ts
  client/jetbrains/webview/src/bridge-mock/theme-snapshots/light.ts
  client/jetbrains/webview/src/search/index.tsx
  client/jetbrains/webview/src/search/js-to-java-bridge.ts
  client/jetbrains/webview/src/search/results/FileSearchResult.module.scss
  client/jetbrains/webview/src/search/types.d.ts
Labels: cla-signed, jetbrains-ide

#36558 JetBrains: Force the popup into persistent mode and manually detect clicks into the main IDE window
  client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java
Labels: cla-signed

#36555 [iam] Add allowGroups filter to SAML auth provider
  CHANGELOG.md
  enterprise/cmd/frontend/internal/auth/saml/config.go
  enterprise/cmd/frontend/internal/auth/saml/middleware.go
  enterprise/cmd/frontend/internal/auth/saml/middleware_test.go
  enterprise/cmd/frontend/internal/auth/saml/user.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam-admin-experience

#36710 web: Fix blob view border
  client/web/src/repo/blob/BlobPage.module.scss
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/RenderedNotebookMarkdown.tsx
  client/web/src/repo/blob/ui/BlobStatusBarContainer.module.scss
Labels: team/frontend-platform, cla-signed

#36699 JetBrains: Manually emit window closing/open events to fix third-party modules that rely on those to render overlays
  client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java
Labels: cla-signed, jetbrains-ide

#36640 Fix sidebar collapse icon color
  client/web/src/repo/RepoRevisionSidebar.module.scss
Labels: team/frontend-platform, cla-signed

#36683 monitoring(repo-updater): add duration on critical rate limit alerts, update next steps
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/repo_updater.go
Labels: cla-signed

#36727 ci: re-enable concurrent linting
  dev/sg/sg_lint.go
Labels: ci, cla-signed

#36687 lib/log: add wrapper for std *log.Logger
  cmd/symbols/parser/parser.go
  cmd/symbols/shared/sqlite.go
  dev/sg/linters/liblog.go
  enterprise/cmd/symbols/main.go
  lib/log/std/std.go
  lib/log/std/std_test.go
Labels: cla-signed
