Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-11, with the labels that each got.

#43670 internal/database: Order by ID only if no order by args are present
  internal/database/repos.go
Labels: debt, performance, team/repo-management, cla-signed

#43731 doc/dev: Fix linter
  doc/dev/background-information/ci/reference.md
Labels: cla-signed

#43363 [SG-42792] Migration from `shema.ts` type usage to `graphql-operations - client/web/src/enterprise/<searchContexts, user>`
  client/search/src/backend.ts
  client/web/src/enterprise/searchContexts/DeleteSearchContextModal.story.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.story.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.tsx
  client/web/src/enterprise/searchContexts/SearchContextPage.story.tsx
  client/web/src/enterprise/searchContexts/SearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextRepositoriesFormArea.tsx
  client/web/src/enterprise/user/productSubscriptions/BackToAllSubscriptionsLink.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.test.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#43287 [SG-43130] Clicking the copy query button should maintain focus on the copy button
  client/search-ui/src/input/toggles/CopyQueryButton.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#43737 cmd/gitserver: Set repo name in errors and warnings
  cmd/gitserver/server/server.go
Labels: debt, team/repo-management, cla-signed

#43220 [SG-41997] Migration from `shema.ts` type usage to `graphql-operations - client/web/src/enterprise/site-admin`
  client/web/src/enterprise/dotcom/productSubscriptions/ProductSubscriptionLabel.tsx
  client/web/src/enterprise/productSubscription/ProductLicenseInfoDescription.tsx
  client/web/src/enterprise/productSubscription/TrueUpStatusSummary.tsx
  client/web/src/enterprise/site-admin/SiteAdminAuthenticationProvidersPage.tsx
  client/web/src/enterprise/site-admin/SiteAdminLsifUploadPage.tsx
  client/web/src/enterprise/site-admin/SiteAdminRegistryExtensionsPage.tsx
  client/web/src/enterprise/site-admin/backend.ts
  client/web/src/enterprise/site-admin/dotcom/customers/SiteAdminCustomersPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminCreateProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicenseNode.test.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicenseNode.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicensesPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionNode.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.test.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  client/web/src/enterprise/site-admin/productSubscription/ProductSubscriptionStatus.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#43474 zoekt: update to sourcegraph/zoekt@d8b79cc1c4bcbb18a9f9c485b544966f9aaa4f6c
  go.mod
  go.sum
Labels: cla-signed

#43738 ranking: introduce DocumentRankVersion
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/search.go
  cmd/frontend/internal/httpapi/search_test.go
  internal/codeintel/ranking/internal/store/store.go
  internal/codeintel/ranking/internal/store/store_test.go
  internal/codeintel/ranking/mocks_test.go
  internal/codeintel/ranking/service.go
  internal/search/backend/index_options.go
  internal/search/backend/index_options_test.go
Labels: cla-signed

#43471 Allow batch changes GitLab webhooks to use the webhooks top level path
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/webhookhandlers/handlers.go
  cmd/frontend/webhooks/github_webhooks.go
  cmd/frontend/webhooks/github_webhooks_test.go
  cmd/frontend/webhooks/gitlab_webhooks.go
  cmd/frontend/webhooks/webhooks.go
  cmd/frontend/webhooks/webhooks_test.go
  enterprise/cmd/frontend/internal/batches/webhooks/github.go
  enterprise/cmd/frontend/internal/batches/webhooks/github_test.go
  enterprise/cmd/frontend/internal/batches/webhooks/gitlab.go
  enterprise/cmd/frontend/internal/batches/webhooks/gitlab_test.go
  internal/repos/github_webhook_handler.go
  internal/repos/github_webhook_handler_test.go
Labels: cla-signed, team/iam

#43116 [SG-42337] Migration from schema.ts type usage to graphql-operations - client/web/src/<backend, batches, communitySearchContexts, components, savedSearches, settings>
  client/web/src/communitySearchContexts/CommunitySearchContextPage.story.tsx
  client/web/src/components/externalServices/ExternalServiceForm.test.tsx
  client/web/src/components/externalServices/ExternalServicePage.tsx
  client/web/src/savedSearches/SavedSearchListPage.tsx
  client/web/src/settings/SettingsArea.tsx
  client/web/src/settings/SettingsFile.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#43726 ranking: Make separate result graph key
  internal/codeintel/ranking/init.go
Labels: cla-signed, ranking

#43675 Add an audit log docs page.
  doc/admin/audit_log.md
  doc/admin/index.md
Labels: cla-signed

#43725 ranking: Mix precise and imprecise ranks
  internal/codeintel/ranking/service.go
  internal/codeintel/ranking/service_test.go
Labels: cla-signed, ranking

#43728 ranking: Do not treat path ranks as append only (forever)
  client/search-ui/src/input/toggles/CopyQueryButton.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.test.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
  client/wildcard/src/components/Popover/components/popover-tail/PopoverTail.module.scss
  internal/codeintel/ranking/internal/store/store.go
  internal/codeintel/ranking/internal/store/store_test.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1667259203_add_graph_key_to_codeintel_path_ranks/down.sql
  migrations/frontend/1667259203_add_graph_key_to_codeintel_path_ranks/metadata.yaml
  migrations/frontend/1667259203_add_graph_key_to_codeintel_path_ranks/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, ranking

#42615 [SG-41996] Migration from schema.ts type usage to graphql-operations - `client/web/src/enterprise/<executors, extensions, insights, organizations, productSubscription, search>`
  client/web/src/enterprise/executors/ExecutorsListPage.tsx
  client/web/src/enterprise/executors/useExecutors.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionManagePage.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionNewReleasePage.tsx
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
  client/web/src/enterprise/extensions/registry/backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/deserialization/create-insight-view.ts
  client/web/src/enterprise/search/stats/SearchStatsLanguages.test.tsx
  client/web/src/enterprise/search/stats/SearchStatsLanguages.tsx
  client/web/src/enterprise/search/stats/SearchStatsPage.test.tsx
  client/web/src/enterprise/search/stats/backend.ts
  client/web/src/enterprise/site-admin/productSubscription/ProductSubscriptionStatus.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#43704 Fix empty shard ID on repos page
  cmd/frontend/graphqlbackend/repository_mirror.go
Labels: cla-signed

#43751 codeintel: Add partial index to `lsif_uploads_visible_at_tip`
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1667313173_add_index_to_lsif_uploads_visible_at_tip/down.sql
  migrations/frontend/1667313173_add_index_to_lsif_uploads_visible_at_tip/metadata.yaml
  migrations/frontend/1667313173_add_index_to_lsif_uploads_visible_at_tip/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation

#43724 code monitors: remove sidebar
  client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
Labels: cla-signed

#43663 Qk/fix search toggles
  client/search-ui/src/input/toggles/Toggles.module.scss
  client/search-ui/src/input/toggles/Toggles.tsx
  client/search-ui/src/input/toggles/__snapshots__/Toggles.test.tsx.snap
Labels: design, design-debt, team/search-product, cla-signed

#43756 Code Insights: Fix dashboard select suggestion panel min width
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.module.scss
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.module.scss
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
Labels: cla-signed

#43720 Added fix mention to Changelog
  CHANGELOG.md
Labels: cla-signed

#43634 Update index.md
  doc/adopt/index.md
Labels: cla-signed

#43760 codeintel: dont return audit-log uploads when only `state='deleted'` requested
  internal/codeintel/uploads/internal/store/store_uploads.go
  internal/codeintel/uploads/internal/store/store_uploads_test.go
Labels: team/code-intelligence, performance, cla-signed, team/language-platform-and-navigation

#43758 insights: bin backfill costs and use to prioritize backfill runs #43757
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler.go
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler_test.go
  enterprise/internal/insights/scheduler/backfill_state_new_handler.go
  internal/database/schema.codeinsights.json
  internal/database/schema.codeinsights.md
  migrations/codeinsights/1667309737_backfill_priority_groups/down.sql
  migrations/codeinsights/1667309737_backfill_priority_groups/metadata.yaml
  migrations/codeinsights/1667309737_backfill_priority_groups/up.sql
  migrations/codeinsights/squashed.sql
Labels: cla-signed

#43723 search: smart search activates on No Results only
  internal/search/lucky/feeling_lucky_search_job.go
Labels: cla-signed

#43637 symbols: Hierarchical symbol sidebar
  client/web/src/repo/RepoRevisionSidebarSymbols.module.scss
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Labels: cla-signed

#43729 additions and links to learn.sourcegraph
  doc/getting-started/index.md
Labels: cla-signed

#43759 zoekt: update to sourcegraph/zoekt@fb9c22b1bdcc58a8cc4bc9e3fa8681c38f990a3d
  go.mod
  go.sum
Labels: cla-signed

#43767 small fixes
  doc/getting-started/index.md
Labels: cla-signed

#43770 Revert "symbols: Hierarchical symbol sidebar"
  client/web/src/repo/RepoRevisionSidebarSymbols.module.scss
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Labels: cla-signed

#43764 commit page: move diff mode definition next to temp settings
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/shared/src/settings/temporary/diffMode.ts
  client/web/src/repo/commit/RepositoryCommitPage.tsx
Labels: cla-signed

#43763 search ui: remove extra tab stop in smart search toggle
  client/search-ui/src/input/toggles/SmartSearchToggle.tsx
Labels: cla-signed

#43518 "Log in" button should redirect to previous URL
  client/web/src/nav/GlobalNavbar.tsx
Labels: cla-signed

#43784 Improve audit log docs.
  doc/admin/audit_log.md
Labels: cla-signed

#43785 search: log to honeycomb ranking options
  internal/search/backend/metered_searcher.go
Labels: cla-signed

#43786 search: turn on page rank for ranking search
  internal/search/zoekt/zoekt.go
Labels: cla-signed

#43788 gitserver: UID 0 is treated as internal for honeycomb
  cmd/gitserver/server/server.go
Labels: cla-signed

#43742 internal/repos: Add test case for nameWithOwner
  internal/repos/github_test.go
  internal/repos/testdata/golden/GithubSource_makeRepo_name-with-owner
Labels: cla-signed

#43789 executors: Fix invalid docker config when using no mirrors
  enterprise/cmd/executor/internal/run/util.go
Labels: cla-signed

#43791 graphqlbackend: use injected gitserver.Client
  cmd/frontend/graphqlbackend/git_blob.go
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_commits.go
  cmd/frontend/graphqlbackend/repository.go
Labels: cla-signed

#43790 metrics: Stop sending GraphQL metrics to Honeycomb
  cmd/frontend/internal/httpapi/graphql.go
Labels: team/repo-management, cla-signed

#43792 graphqlbackend: create gitserver client outside of loop
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/user.go
Labels: cla-signed

#43747 go + golangci: update to go to 1.19.3 and golanci to 1.50.1
  .github/workflows/sg-setup.yml
  .golangci.yml
  .tool-versions
  client/web/src/nav/GlobalNavbar.tsx
  cmd/frontend/internal/app/debug.go
  cmd/frontend/internal/auth/userpasswd/lockout_test.go
  cmd/frontend/internal/httpapi/internal_test.go
  cmd/gitserver/server/cleanup.go
  cmd/symbols/internal/api/search_sqlite.go
  dev/golangci-lint.sh
  dev/scaletesting/codehostcopy/gitlab.go
  dev/scaletesting/codehostcopy/runner.go
  dev/sg/adr/adr.go
  dev/sg/checks.go
  dev/sg/internal/images/compose.go
  dev/sg/sg_insights.go
  dev/sg/sg_start.go
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
  enterprise/cmd/frontend/internal/executorqueue/gitserverproxy.go
  enterprise/dev/ci/internal/ci/changed/diff.go
  enterprise/internal/authz/gerrit/gerrit.go
  enterprise/internal/insights/aggregation/aggregation.go
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/queryrunner/search.go
  enterprise/internal/insights/query/compute_executor.go
  enterprise/internal/insights/query/streaming/search.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler.go
  enterprise/internal/insights/store/store.go
  enterprise/internal/rockskip/search.go
  internal/adminanalytics/codeintelbylanguage.go
  internal/adminanalytics/codeinteltoprepositories.go
  internal/adminanalytics/fetcher.go
  internal/adminanalytics/repos.go
  internal/adminanalytics/users.go
  internal/codeintel/autoindexing/internal/store/scan.go
  internal/comby/comby.go
  internal/database/external_accounts_test.go
  internal/database/security_event_logs.go
  internal/gitserver/gitdomain/exec.go
  internal/honey/slice_wrapper.go
  internal/repos/github_webhook_handler_test.go
  internal/search/alert/observer.go
  internal/search/backend/horizontal.go
  internal/search/lucky/feeling_lucky_search_job.go
Labels: team/devx, cla-signed, devx/support/q4b1

#43806 codeintel: Remove unused filter column
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1667395984_remove_filter_from_lsif_references/down.sql
  migrations/frontend/1667395984_remove_filter_from_lsif_references/metadata.yaml
  migrations/frontend/1667395984_remove_filter_from_lsif_references/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation

#43769 Cclark/error iterator
  enterprise/internal/insights/scheduler/iterator/repo_iterator.go
  enterprise/internal/insights/scheduler/iterator/repo_iterator_test.go
Labels: cla-signed

#43615 Upgrade git version to 2.38.1 in Gitserver and Server Docker Images
  CHANGELOG.md
  cmd/gitserver/Dockerfile
  cmd/server/Dockerfile
  dev/sg/dependencies/mac.go
  dev/sg/dependencies/ubuntu.go
Labels: cla-signed

#43765 Aggregation: Add aggregation data pings again
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/components/aggregation/pings.ts
  client/web/src/search/results/sidebar/SearchAggregations.tsx
  doc/dev/background-information/insights/code_insights_pings.md
  internal/types/types.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: cla-signed

#43778 Code Insight: Move repositories methods out of context API
  client/web/src/enterprise/insights/components/form/repositories-field/RepositoriesField.tsx
  client/web/src/enterprise/insights/components/form/repositories-field/RepositoryField.tsx
  client/web/src/enterprise/insights/components/form/repositories-field/hooks/use-repo-suggestions.ts
  client/web/src/enterprise/insights/components/form/repositories-field/utils/memoize-async.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-context.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-types.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/backend/core/api/get-repository-suggestions.ts
  client/web/src/enterprise/insights/core/backend/core/api/get-resolved-search-repositories.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/use-url-query-insight/use-url-query-insight.ts
Labels: cla-signed

#43809 Fix repo code intel uploads page loop
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexesPage.tsx
  client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.tsx
Labels: cla-signed

#43733 [SG-43143] Expanding search matches should focus the first previously-hidden match, not the collapse button
  client/search-ui/src/components/FileMatchChildren.tsx
  client/web/src/search/panels/RecentFilesPanel.tsx
  client/web/src/search/panels/RecentSearchesPanel.tsx
  client/web/src/search/panels/RepositoriesPanel.tsx
  client/wildcard/src/hooks/index.ts
  client/wildcard/src/hooks/useFocusOnLoadedMore.ts
Labels: team/frontend-platform, gitstart, cla-signed

#43774 symbols: Hierarchical symbol sidebar (2)
  client/web/src/end-to-end/code-intel/repository-component.test.ts
  client/web/src/repo/RepoRevisionSidebarSymbols.module.scss
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Labels: cla-signed

#43762 search ui: don't submit search when toggles change in home
  client/web/src/integration/search.test.ts
  client/web/src/search/home/SearchPageInput.tsx
Labels: cla-signed

#43722 Add OpenIDConnect option to Account Security page
  client/web/src/user/settings/auth/ExternalAccount.tsx
  client/web/src/user/settings/auth/ExternalAccountSignIn.test.tsx
  client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
Labels: cla-signed, team/iam

#43819 search ui: fix structural search integration tests
  client/web/src/integration/search.test.ts
Labels: cla-signed

#43818 Code Insights: Remove dashboard query from class-based API
  client/web/src/enterprise/insights/core/backend/code-insights-backend-context.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/gql/GetInsightsDashboards.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/index.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-dashboards/get-dashboard-by-id.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-dashboards/get-dashboards.ts
  client/web/src/enterprise/insights/core/hooks/index.ts
  client/web/src/enterprise/insights/core/hooks/use-insight-dashboards.ts
  client/web/src/enterprise/insights/core/index.ts
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.test.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/InsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/edit-insight/hooks/use-edit-page-handlers.ts
Labels: cla-signed

#43801 zoekt: update to sourcegraph/zoekt@42b609c769a8f96d72748403f304a81c9b6bbf0e
  go.mod
  go.sum
Labels: cla-signed

#43768 gitserver: add mount_info metrics
  cmd/gitserver/server/servermetrics.go
  doc/admin/observability/dashboards.md
  go.mod
  monitoring/definitions/git_server.go
  monitoring/definitions/shared/diskmetrics.go
  monitoring/definitions/zoekt.go
Labels: cla-signed

#43700 Fuzzy finder: replace fzy with fzf
  client/web/src/Layout.tsx
  client/web/src/components/fuzzyFinder/FuzzyFsm.ts
  client/web/src/components/fuzzyFinder/LazyFuzzyFinder.tsx
  client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.ts
  package.json
  yarn.lock
Labels: cla-signed

#43833 Web: Fix decorated tokens keys
  client/shared/src/search/query/decoratedToken.ts
Labels: cla-signed

#43816 insights: integrate error retries into new backfiller
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler.go
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler_test.go
  enterprise/internal/insights/scheduler/backfill_state_new_handler.go
  enterprise/internal/insights/scheduler/iterator/repo_iterator.go
Labels: cla-signed

#43834 Code Insights: Fix use insight dashboard query by id (handle virtual dashboard case)
  client/web/src/enterprise/insights/core/hooks/use-insight-dashboards.ts
Labels: cla-signed

#43766 Dotcom Code Basics examples re-design
  client/search-ui/src/input/SearchHelpDropdownButton.tsx
  client/web/src/search/home/LoggedOutHomepage.constants.ts
  client/web/src/search/home/LoggedOutHomepage.module.scss
  client/web/src/search/home/LoggedOutHomepage.tsx
  client/web/src/search/home/QueryExamplesHomepage.module.scss
  client/web/src/search/home/QueryExamplesHomepage.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/home/TipsAndTricks.module.scss
  client/web/src/search/home/TipsAndTricks.test.tsx
  client/web/src/search/home/TipsAndTricks.tsx
  client/web/src/search/home/useQueryExamples.tsx
Labels: cla-signed, team/growth-marketing

#43810 Enable to override the update check (pings) URL
  client/web/src/enterprise/insights/components/form/repositories-field/RepositoriesField.tsx
  client/web/src/enterprise/insights/components/form/repositories-field/hooks/use-repo-suggestions.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-context.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/hooks/use-insight-dashboards.ts
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/use-url-query-insight/use-url-query-insight.ts
  client/web/src/search/home/QueryExamplesHomepage.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/useQueryExamples.tsx
  client/web/src/user/settings/auth/ExternalAccountSignIn.test.tsx
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/client_test.go
  doc/admin/how-to/index.md
  doc/admin/how-to/static-ip-for-updates-and-pings.md
Labels: cla-signed

#43389 [SG-43144]: Tables in code excerpts should use headers for line numbers
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/codeintellify/src/testutils/sourcegraph/generate.ts
  client/codeintellify/src/testutils/sourcegraph/styles.css
  client/search-ui/src/components/CodeExcerpt.module.scss
  client/search-ui/src/components/CodeExcerpt.tsx
  client/search-ui/src/components/CommitSearchResultMatch.module.scss
  client/search/src/integration/streaming-search-mocks.ts
  client/shared/src/testing/searchTestHelpers.ts
  client/vscode/src/webview/theming/highlight.scss
  client/web/src/codeintel/ReferencesPanel.mocks.ts
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/end-to-end/code-intel/repository-component.test.ts
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/notebook.test.ts
  client/web/src/repo/blob/BlameColumn.tsx
  client/web/src/repo/blob/Blob.module.scss
  client/web/src/repo/blob/Blob.tsx
  client/web/src/repo/compare/dom-functions.ts
  cmd/frontend/internal/highlight/highlight.go
  cmd/frontend/internal/highlight/highlight_test.go
  cmd/frontend/internal/highlight/html.go
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_syntect.rs
Labels: team/frontend-platform, gitstart, cla-signed

#43519 [SG-43129] Accessibility: Closing search contexts dropdown should focus the dropdown trigger
  client/search-ui/src/input/SearchBox.tsx
  client/search-ui/src/input/SearchContextDropdown.tsx
  client/wildcard/src/hooks/index.ts
  client/wildcard/src/hooks/useUpdateEffect.ts
Labels: team/frontend-platform, gitstart, cla-signed

#43829 ranking: Export development data into GCS
  internal/codeintel/ranking/init.go
  internal/codeintel/ranking/internal/store/store.go
  internal/codeintel/ranking/load-ranks.sh
  internal/codeintel/ranking/loader.go
  internal/codeintel/ranking/mocks_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43800 authz: Update handling of directories in sub-repo filtering
  enterprise/internal/authz/perforce/protects_test.go
  internal/authz/sub_repo_perms.go
  internal/authz/sub_repo_perms_test.go
  internal/gitserver/integration_tests/tree_test.go
Labels: team/repo-management, cla-signed

#43783 Disable scheduled workflows in forks
  .github/workflows/buildchecker.yml
  .github/workflows/lighthouse-production.yml-disabled
  .github/workflows/pr-preview.yml
  .github/workflows/progress.yml
  .github/workflows/resources-report.yml
  .github/workflows/tracking-issue.yml
Labels: cla-signed

#43787 workflows: bump license_finder to v7.0.1
  .github/workflows/licenses-check.yml
  .github/workflows/licenses-update.yml
  .tool-versions
  .yarn/plugins/@yarnpkg/plugin-licenses.cjs
  .yarnrc.yml
  third-party-licenses/CODEOWNERS
Labels: team/devx, cla-signed, devx/support/q4b1

#43803 Tweak git blame paddings
  client/web/src/repo/blob/BlameDecoration.tsx
Labels: cla-signed

#43850 zoekt: search for 10k results in shard before ranking
  internal/search/zoekt/zoekt.go
Labels: cla-signed

#43680 Add security events for access token deletions
  internal/database/access_tokens.go
  internal/database/access_tokens_test.go
  internal/database/security_event_logs.go
Labels: cla-signed

#43854 15-day trials
  doc/cloud/index.md
Labels: cla-signed

#43605 CodeMirror: Fix focusing selected lines
  client/web/src/repo/blob/codemirror/linenumbers.ts
  client/web/src/repo/blob/codemirror/tokens-as-links.ts
Labels: team/frontend-platform, cla-signed

#43534 Improve UX of Notebook editing and display
  client/shared/src/symbols/SymbolIcon.module.scss
  client/shared/src/symbols/SymbolIcon.tsx
  client/web/src/notebooks/blocks/NotebookBlock.module.scss
  client/web/src/notebooks/blocks/NotebookBlock.tsx
  client/web/src/notebooks/blocks/compute/NotebookComputeBlock.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.module.scss
  client/web/src/notebooks/blocks/file/NotebookFileBlock.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.module.scss
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.tsx
  client/web/src/notebooks/blocks/menu/useCommonBlockMenuActions.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.module.scss
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.story.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.module.scss
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
  client/web/src/notebooks/index.ts
  client/web/src/notebooks/notebook/NotebookBlockSeparator.module.scss
  client/web/src/notebooks/notebook/NotebookBlockSeparator.tsx
  client/web/src/notebooks/notebook/NotebookCommandPaletteInput.tsx
  client/web/src/notebooks/notebook/NotebookComponent.module.scss
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebook/index.ts
  client/web/src/notebooks/notebook/useNotebookEventHandlers.ts
Labels: cla-signed

#43856 Avoid session deletion when sessionstore host can't be found
  cmd/frontend/internal/session/session.go
Labels: cla-signed

#43826 Code Insights: Remove `getSearchInsightContent` legacy handler for live preview
  client/web/src/enterprise/insights/core/backend/code-insights-backend-context.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-types.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-built-in-insight-data/get-built-in-insight.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-built-in-insight-data/get-search-insight-content.ts
  client/web/src/enterprise/insights/pages/insights/creation/compute/ComputeInsightCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/dynamic-code-insight-example/DynamicInsightPreview.tsx
Labels: cla-signed

#43832 ranking: Remove no-longer-relevant CSV files from GCS bucket
  internal/codeintel/codenav/init.go
  internal/codeintel/codenav/internal/background/graph_serializer.go
  internal/codeintel/codenav/internal/background/iface.go
  internal/codeintel/codenav/internal/store/store.go
  internal/codeintel/codenav/mocks_test.go
  internal/codeintel/codenav/observability.go
  internal/codeintel/codenav/ranking.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43820 drift: Refactor expected schema factory to provide better output on error
  dev/sg/sg_migration.go
  internal/database/migration/cliutil/drift.go
  internal/database/migration/cliutil/drift_schema.go
  internal/database/migration/cliutil/multiversion.go
Labels: cla-signed

#43817 ranking: Ensure ranks are consistent (cheat sheet: 0=worse, 1=better)
  internal/codeintel/ranking/loader.go
  internal/codeintel/ranking/service.go
  internal/codeintel/ranking/service_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43858 ranking: Apply generated/test/vendor heuristics to ranked paths as well
  internal/codeintel/ranking/service.go
  internal/codeintel/ranking/service_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43645 auth: initial implementation of SOAP
  client/shared/src/symbols/SymbolIcon.module.scss
  client/web/src/components/externalAccounts/externalAccounts.ts
  client/web/src/enterprise/insights/pages/landing/getting-started/components/dynamic-code-insight-example/DynamicInsightPreview.tsx
  client/web/src/jscontext.ts
  client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.module.scss
  client/web/src/notebooks/blocks/menu/useCommonBlockMenuActions.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
  client/web/src/notebooks/notebook/NotebookCommandPaletteInput.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebook/useNotebookEventHandlers.ts
  client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
  enterprise/cmd/frontend/internal/auth/init.go
  enterprise/cmd/frontend/internal/auth/openidconnect/config.go
  enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go
  enterprise/cmd/frontend/internal/auth/openidconnect/middleware_test.go
  enterprise/cmd/frontend/internal/auth/openidconnect/provider.go
  enterprise/cmd/frontend/internal/auth/openidconnect/session.go
  enterprise/cmd/frontend/internal/auth/openidconnect/user.go
  enterprise/cmd/frontend/internal/auth/sourcegraphoperator/config.go
  enterprise/cmd/frontend/internal/auth/sourcegraphoperator/config_test.go
  enterprise/cmd/frontend/internal/auth/sourcegraphoperator/middleware.go
  enterprise/cmd/frontend/internal/auth/sourcegraphoperator/middleware_test.go
  enterprise/cmd/frontend/internal/auth/sourcegraphoperator/provider.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam

#43823 gitserver: fix changeset publication
  cmd/gitserver/server/patch.go
  internal/gitserver/gitdomain/exec.go
  internal/gitserver/gitdomain/exec_test.go
Labels: cla-signed

#43830 Cclark/refactor points
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler.go
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler_test.go
  enterprise/internal/insights/scheduler/backfill_state_new_handler.go
  enterprise/internal/insights/scheduler/backfill_state_new_handler_test.go
Labels: cla-signed

#43870 go.mod: bump zoekt
  go.mod
  go.sum
Labels: cla-signed

#43865 codeintel: add variable to service dashboards to filter by 'app'
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/codeintel_autoindexing.go
  monitoring/definitions/codeintel_codenav.go
  monitoring/definitions/codeintel_policies.go
  monitoring/definitions/codeintel_uploads.go
  monitoring/definitions/shared/codeintel_autoindexing.go
Labels: team/code-intelligence, monitoring, cla-signed, team/language-platform-and-navigation

#43777 codeintel: Refactor autoindexing cleanup background tasks
  internal/codeintel/autoindexing/internal/background/iface.go
  internal/codeintel/autoindexing/internal/background/job_cleanup.go
  internal/codeintel/autoindexing/internal/background/job_cleanup_test.go
  internal/codeintel/autoindexing/internal/background/mocks_test.go
  internal/codeintel/autoindexing/internal/store/observability.go
  internal/codeintel/autoindexing/internal/store/scan.go
  internal/codeintel/autoindexing/internal/store/store.go
  internal/codeintel/autoindexing/internal/store/store_sourced_commits.go
  internal/codeintel/autoindexing/internal/store/store_sourced_commits_test.go
  internal/codeintel/autoindexing/mocks_test.go
  internal/codeintel/autoindexing/service.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation

#43807 JetBrains: Add Perforce support
  client/jetbrains/CHANGELOG.md
  client/jetbrains/README.md
  client/jetbrains/gradle.properties
  client/jetbrains/src/main/java/com/sourcegraph/common/BrowserOpener.java
  client/jetbrains/src/main/java/com/sourcegraph/common/ErrorNotification.java
  client/jetbrains/src/main/java/com/sourcegraph/common/RegexEscaper.java
  client/jetbrains/src/main/java/com/sourcegraph/find/FindService.java
  client/jetbrains/src/main/java/com/sourcegraph/find/browser/JSToJavaBridgeRequestHandler.java
  client/jetbrains/src/main/java/com/sourcegraph/git/CommitViewUriBuilder.java
  client/jetbrains/src/main/java/com/sourcegraph/git/GitUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/git/RepoInfo.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/GitUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/PerforceUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoInfo.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/RevisionContext.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/VCSType.java
  client/jetbrains/src/main/java/com/sourcegraph/website/CopyAction.java
  client/jetbrains/src/main/java/com/sourcegraph/website/FileActionBase.java
  client/jetbrains/src/main/java/com/sourcegraph/website/OpenRevisionAction.java
  client/jetbrains/src/main/java/com/sourcegraph/website/SearchActionBase.java
  client/jetbrains/src/main/java/com/sourcegraph/website/URLBuilder.java
  client/jetbrains/src/main/resources/META-INF/plugin-git.xml
  client/jetbrains/src/main/resources/META-INF/plugin-perforce.xml
  client/jetbrains/src/main/resources/META-INF/plugin.xml
  client/jetbrains/src/test/java/CommitViewUriBuilderTest.java
  client/jetbrains/src/test/java/URLBuilderTest.java
Labels: cla-signed

#43871 Update protip language
  client/web/src/search/home/QueryExamplesHomepage.tsx
Labels: cla-signed

#43841 Wildcard [Tooltip]: Support controlled open prop
  client/wildcard/src/components/Tooltip/Tooltip.tsx
  client/wildcard/src/components/index.ts
Labels: cla-signed

#43877 searcher: add disk i/o prometheus metric + dashboards
  cmd/searcher/internal/search/store.go
  doc/admin/observability/dashboards.md
  monitoring/definitions/searcher.go
Labels: cla-signed

#43859 codeintel: Add missing codenav store unit tests
  internal/codeintel/codenav/internal/store/store.go
  internal/codeintel/codenav/internal/store/store_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation

#43894 codeintel: Fix overeager trigger
  client/wildcard/src/components/Tooltip/Tooltip.tsx
  client/wildcard/src/components/index.ts
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1667500111_fix_codeintel_path_ranks_trigger_condition/down.sql
  migrations/frontend/1667500111_fix_codeintel_path_ranks_trigger_condition/metadata.yaml
  migrations/frontend/1667500111_fix_codeintel_path_ranks_trigger_condition/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43892 Code Insights: Fix code insights api memoization
  client/web/src/enterprise/insights/hooks/use-api.ts
Labels: cla-signed

#43896 clarify oob migration deprecations
  doc/dev/background-information/oobmigrations.md
Labels: cla-signed

#43373 Fix styles for `mark` tags
  client/branded/src/global-styles/typography.scss
  client/web/src/components/fuzzyFinder/HighlightedLink.module.scss
  client/web/src/components/fuzzyFinder/HighlightedLink.tsx
Labels: team/frontend-platform, cla-signed

#43897 Search: do not highlight paths when selecting content
  internal/search/result/file.go
  internal/search/result/match_test.go
Labels: cla-signed

#43835 search frontend: warn on structural search without lang: filter
  CHANGELOG.md
  client/shared/src/search/query/diagnostics.test.ts
  client/shared/src/search/query/diagnostics.ts
  client/web/src/enterprise/insights/hooks/use-api.ts
Labels: cla-signed

#43825 Change signup link to signup.sg
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
Labels: cla-signed, team/growth-marketing

#43918 chore: fix missing quotes
  doc/dev/background-information/oobmigrations.md
Labels: cla-signed

#43882 codeintel: extract and decouple policies background jobs from service
  cmd/worker/internal/codeintel/policies_repomatcher_job.go
  internal/codeintel/policies/background/repomatcher/iface.go
  internal/codeintel/policies/background/repomatcher/init.go
  internal/codeintel/policies/config.go
  internal/codeintel/policies/init.go
  internal/codeintel/policies/internal/background/background_job.go
  internal/codeintel/policies/internal/background/repomatcher.go
  internal/codeintel/policies/service.go
  internal/codeintel/policies/service_test.go
Labels: team/code-intelligence, cla-signed, rfc-619, team/language-platform-and-navigation

#25068 Remove repositoryQuery results limit workaround
  doc/admin/external_service/github.md
Labels: cla-signed

#43879 monitoring/promql: guard against use of variables in regexp label match
  monitoring/monitoring/internal/promql/promql.go
  monitoring/monitoring/internal/promql/promql_test.go
Labels: cla-signed

#43926 Rename search contexts sort labels
  client/web/src/enterprise/searchContexts/SearchContextsListTab.tsx
Labels: cla-signed

#43848 docs: Fix GitLab webhooks link
  doc/admin/external_service/gitlab.md
  doc/batch_changes/how-tos/site_admin_configuration.md
Labels: team/repo-management, cla-signed

#43797 Doc update: Sourcegraph Cloud does not support SSH URLs
  doc/admin/external_service/other.md
  doc/admin/repo/auth.md
  doc/dev/how-to/sync_repositories_from_gitolite_sgdev_org.md
Labels: cla-signed, team/iam

#43929 JetBrains: 2.1.0 release
  client/jetbrains/CHANGELOG.md
Labels: cla-signed

#43931 JetBrains: Extract CONTRIBUTING.md from the readme
  client/jetbrains/CONTRIBUTING.md
  client/jetbrains/README.md
Labels: cla-signed

#43933 Scope markdown header CSS rules to the markdown block
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.module.scss
Labels: cla-signed

#43932 JetBrains: Add manual testing page, clean up IDE extension docs a bit
  client/jetbrains/CONTRIBUTING.md
  doc/integration/index.md
  doc/integration/jetbrains/index.md
  doc/integration/jetbrains/manual_testing.md
  doc/integration/vscode/index.md
Labels: cla-signed

#43849 search: Force linting pass when query parsing changes due to external triggers
  CHANGELOG.md
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
Labels: team/search-product, cla-signed, codemirror

#43325 Simplify ListIndexableRepos
  cmd/repo-updater/shared/main.go
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/compression/worker.go
  enterprise/internal/insights/discovery/all_repos_iterator.go
  enterprise/internal/insights/discovery/all_repos_iterator_test.go
  internal/database/dbcache/cached_indexable_repos.go
  internal/database/dbcache/cached_indexable_repos_test.go
  internal/database/mocks_temp.go
  internal/database/repos.go
  internal/database/repos_test.go
Labels: cla-signed

#43799 Implement resolver layer for executor secrets
  cmd/frontend/graphqlbackend/executor_secret.go
  cmd/frontend/graphqlbackend/executor_secret_access_log.go
  cmd/frontend/graphqlbackend/executor_secret_access_logs_connection.go
  cmd/frontend/graphqlbackend/executor_secret_connection.go
  cmd/frontend/graphqlbackend/executor_secrets.go
  cmd/frontend/graphqlbackend/executor_secrets_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed

#43941 Remove useless status messages tests
  internal/repos/status_messages_test.go
Labels: cla-signed

#43943 ranking: Refactor generated/vendor/path tests
  internal/codeintel/ranking/service.go
Labels: cla-signed

#43944 ranking: Squash page rank into [0, 1) range
  internal/codeintel/ranking/service.go
  internal/codeintel/ranking/service_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43945 featureflag: add MemoryStore for use in testing
  cmd/frontend/graphqlbackend/repository_test.go
  internal/featureflag/memory_store.go
Labels: cla-signed

#43922 Code Insights: Fix loading insights announcements
  client/web/src/enterprise/insights/components/views/card/InsightCard.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
Labels: cla-signed

#43948 ranking: set useDocumentRanks in collectSender
  internal/search/backend/aggregate.go
  internal/search/backend/horizontal.go
Labels: cla-signed

#43696 Fix flaky Perforce integration tests
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/graphqlbackend/authz.graphql
  dev/gqltest/sub_repo_permissions_test.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  internal/gqltestutil/permissions.go
Labels: cla-signed

#43872 featureflag: add per request overrides
  client/jetbrains/CHANGELOG.md
  client/jetbrains/CONTRIBUTING.md
  client/shared/src/search/stream.ts
  client/web/src/api/ApiConsole.tsx
  client/web/src/backend/graphql.ts
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/helpers.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  internal/featureflag/middleware.go
  internal/featureflag/override.go
  internal/featureflag/override_test.go
  package.json
  yarn.lock
Labels: cla-signed

#43916 insights: remove unused code for non-isolated settings migration
  CHANGELOG.md
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/discovery/discovery.go
  enterprise/internal/insights/discovery/discovery_test.go
  enterprise/internal/insights/discovery/mocks_temp.go
  enterprise/internal/insights/store/dashboard_store.go
  mockgen.temp.yaml
Labels: cla-signed

#43921 chore: deprecate old unused settings
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#43953 search: display debug messages in search results
  client/search-ui/src/components/FileSearchResult.tsx
  client/search-ui/src/components/ResultContainer.tsx
  client/shared/src/search/stream.ts
Labels: cla-signed

#43739 sct: enable to copy user repos instead of just orgs
  dev/scaletesting/codehostcopy/config.example.cue
  dev/scaletesting/codehostcopy/github.go
Labels: team/devx, cla-signed, devx/q3b1/scaletesting, devx/q3b1/scaletesting/testing-data

#43775 docs/deploy add storage and network config for RKE
  doc/admin/deploy/kubernetes/configure.md
Labels: cla-signed

#43963 zoekt: add ranks and rrf scores to debug string
  go.mod
  go.sum
  internal/search/backend/aggregate.go
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#43964 Revert "Fix flaky Perforce integration tests"
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/graphqlbackend/authz.graphql
  dev/gqltest/sub_repo_permissions_test.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  internal/gqltestutil/permissions.go
Labels: cla-signed

#43966 Revert "Revert "Fix flaky Perforce integration tests""
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/graphqlbackend/authz.graphql
  dev/gqltest/sub_repo_permissions_test.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  internal/gqltestutil/permissions.go
Labels: cla-signed

#43965 skip flaky test
  client/browser/src/end-to-end/ghe.test.ts
Labels: cla-signed

#42608 Render backtick in validation message properly
  client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.tsx
  client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.tsx
  client/web/src/enterprise/insights/components/form/form-group/FormGroup.tsx
  client/web/src/enterprise/insights/components/form/getDefaultInputProps.ts
  client/web/src/enterprise/insights/components/form/hooks/useForm.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/CaptureGoupCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/compute/components/ComputeInsightCreationContent.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/SearchInsightCreationForm.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
  client/wildcard/src/components/Form/Input/Input.story.tsx
  client/wildcard/src/components/Form/Input/Input.tsx
Labels: cla-signed

#43971 Revert "featureflag: add per request overrides (#43872)"
  client/jetbrains/CHANGELOG.md
  client/jetbrains/CONTRIBUTING.md
  client/shared/src/search/stream.ts
  client/web/src/api/ApiConsole.tsx
  client/web/src/backend/graphql.ts
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/helpers.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  internal/featureflag/middleware.go
  internal/featureflag/override.go
  internal/featureflag/override_test.go
  package.json
  yarn.lock
Labels: cla-signed

#43895 ranking: Fix cascade behavior on `codeintel_ranking_exports`
  client/browser/src/end-to-end/ghe.test.ts
  client/web/src/enterprise/insights/components/views/card/InsightCard.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  internal/codeintel/codenav/internal/store/store.go
  internal/codeintel/codenav/internal/store/store_test.go
  internal/codeintel/codenav/mocks_test.go
  internal/codeintel/codenav/ranking.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1667497565_fix_cascade_behavior_for_codeintel_ranking_exports/down.sql
  migrations/frontend/1667497565_fix_cascade_behavior_for_codeintel_ranking_exports/metadata.yaml
  migrations/frontend/1667497565_fix_cascade_behavior_for_codeintel_ranking_exports/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking

#43981 prettier
  client/jetbrains/CHANGELOG.md
  client/jetbrains/CONTRIBUTING.md
Labels: cla-signed

#43939 sg: do not ask for ppa confirmation in setup
  dev/sg/dependencies/ubuntu.go
Labels: cla-signed

#43979 allow running in dotcom mode w/o ranking to silence log spam
  internal/codeintel/codenav/ranking.go
Labels: cla-signed, ranking

#43781 webhooks: add first version of list webhooks UI
  client/web/src/site-admin/SiteAdminWebhooksPage.module.scss
  client/web/src/site-admin/SiteAdminWebhooksPage.story.tsx
  client/web/src/site-admin/SiteAdminWebhooksPage.tsx
  client/web/src/site-admin/WebhookNode.module.scss
  client/web/src/site-admin/WebhookNode.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/routes.tsx
Labels: webhooks, team/repo-management, cla-signed

#44002 featureflag: backend add per request overrides
  internal/featureflag/middleware.go
  internal/featureflag/override.go
  internal/featureflag/override_test.go
Labels: cla-signed

#43986 don't show Analytics in navbar for site admins
  client/web/src/nav/GlobalNavbar.tsx
Labels: team/frontend-platform, cla-signed

#44003 featureflag: support overriding in streaming search
  client/shared/src/search/stream.ts
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
Labels: cla-signed

#44007 docs: Clarify that we don't support GitLab system hooks
  doc/admin/external_service/gitlab.md
Labels: team/repo-management, cla-signed

#44014 web: hide external service sync errors under collapsible element.
  client/web/src/components/externalServices/ExternalServicePage.tsx
Labels: team/repo-management, cla-signed

#43949 JetBrains: Fix compatibility issues with 2.1.0 release
  client/jetbrains/CONTRIBUTING.md
  client/jetbrains/src/main/java/com/sourcegraph/website/OpenRevisionAction.java
  client/jetbrains/src/main/java/com/sourcegraph/website/SearchActionBase.java
  client/jetbrains/src/main/java/com/sourcegraph/website/SearchRepositoryAction.java
  client/jetbrains/src/main/java/com/sourcegraph/website/SearchSelectionAction.java
  client/web/src/site-admin/SiteAdminWebhooksPage.story.tsx
  client/web/src/site-admin/SiteAdminWebhooksPage.tsx
Labels: cla-signed

#43960 Add storybook example for the new references panel
  client/web/src/codeintel/ReferencesPanel.mocks.ts
  client/web/src/codeintel/ReferencesPanel.story.tsx
  client/web/src/codeintel/ReferencesPanel.test.tsx
  client/web/src/codeintel/ReferencesPanel.tsx
Labels: cla-signed

#44015 zoekt: remove unread SearchOptions.*MaxtImportantMatch
  internal/search/symbol/symbol.go
  internal/search/zoekt/zoekt.go
Labels: cla-signed

#44005 featureflag: support overriding in api console
  client/web/src/api/ApiConsole.tsx
Labels: cla-signed

#43999 internal/database/github_app_helper.go: Indent code
  internal/database/github_app_helper.go
Labels: cla-signed

#43798 Simplify authzQuery
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
Labels: cla-signed, team/iam

#44019 Open in Editor: Use line numbers to open the right line of the file
  client/web/src/open-in-editor/build-url.test.ts
  client/web/src/open-in-editor/build-url.ts
  client/web/src/open-in-editor/useOpenCurrentUrlInEditor.ts
Labels: cla-signed

#44022 ranking: Update conditions in which ranking runs
  cmd/frontend/internal/httpapi/search.go
  internal/codeintel/codenav/ranking.go
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation, ranking
