Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-04, with the labels that each got.

#33299 doc: use absolute images for image links in README
  README.md
Labels: cla-signed

#33261 nix: bump nixpkgs
  shell.nix
Labels: cla-signed

#33314 skip flaky test
  client/web/src/end-to-end/end-to-end.test.ts
Labels: cla-signed

#33305 perforce: Allow passing the fsyncEnable param to p4-fusion
  cmd/gitserver/main.go
  cmd/gitserver/server/vcs_syncer_perforce.go
  schema/perforce.schema.json
  schema/schema.go
Labels: team/repo-management, cla-signed

#33304 monitoring: more panels for gitserver janitor jobs
  doc/admin/observability/dashboards.md
  monitoring/definitions/git_server.go
Labels: cla-signed

#33255 insights: Add codeInsightsCriticalTelemetry into ping payload
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/app/updatecheck/handler_test.go
Labels: cla-signed

#32933 Alert user when code host is down
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: cla-signed

#33322 Add comments about public instances
  doc/admin/install/managed.md
Labels: cla-signed

#33308 search: optimize pattern expressions to native Zoekt queries
  CHANGELOG.md
  cmd/frontend/graphqlbackend/search_results_test.go
  internal/search/job/job.go
  internal/search/job/job_test.go
  internal/search/job/mapper.go
  internal/search/query/types.go
  internal/search/query_converter.go
  internal/search/query_converter_test.go
Labels: cla-signed

#33324 insights: add check for issue to be a code insights issue before adding to the project
  .github/workflows/update-project-items.ps1
Labels: cla-signed

#33306 Revert "bext: add firstSourcegraphUrl to logs (#32719)"
  client/browser/src/browser-extension/manifest.spec.json
  client/browser/src/browser-extension/scripts/backgroundPage.main.ts
  client/browser/src/browser-extension/web-extension-api/runtime.ts
  client/browser/src/browser-extension/web-extension-api/types.ts
  client/browser/src/shared/backend/userEvents.tsx
  client/browser/src/shared/tracking/eventLogger.tsx
Labels: cla-signed

#33134 [SG-27703] Wildcard: `<NavMenu />` Implementation
  client/wildcard/src/components/Menu/MenuHeader.tsx
  client/wildcard/src/components/Menu/MenuText.tsx
  client/wildcard/src/components/Menu/index.ts
  client/wildcard/src/components/NavMenu/NavMenu.module.scss
  client/wildcard/src/components/NavMenu/NavMenu.story.tsx
  client/wildcard/src/components/NavMenu/NavMenu.test.tsx
  client/wildcard/src/components/NavMenu/NavMenu.tsx
  client/wildcard/src/components/NavMenu/__snapshots__/NavMenu.test.tsx.snap
  client/wildcard/src/components/NavMenu/index.ts
  client/wildcard/src/components/index.ts
Labels: gitstart, cla-signed

#33266 gitserver: Skip remote urls for private cloud default repos
  cmd/gitserver/main.go
Labels: team/repo-management, cla-signed

#33344 Reference panel: fix scrollbars after introducing new row
  client/web/src/codeintel/ReferencesPanel.module.scss
  client/web/src/codeintel/ReferencesPanel.tsx
Labels: cla-signed

#33277 New reference panel: handle forks/archives in search-based code intel
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/codeintel/ReferencesPanelQueries.ts
  client/web/src/codeintel/searchBased.ts
  client/web/src/codeintel/settings.ts
  client/web/src/codeintel/useCodeIntel.ts
  client/web/src/codeintel/useRepoAndBlob.ts
Labels: cla-signed

#33345 [Cloud SaaS - Open Beta] - updating Tos and beta limits link
  client/web/src/org/openBeta/JoinOpenBetaPage.tsx
  client/web/src/org/openBeta/NewOrganizationPage.tsx
  client/web/src/user/settings/openBetaOrgs/OrganizationsList.tsx
Labels: cla-signed

#33311 bext: fix "Open on Sourcegraph" button for files with symbols in the filePath
  client/browser/src/browser-extension/scripts/backgroundPage.main.ts
  client/shared/src/util/url.test.ts
  client/shared/src/util/url.ts
Labels: cla-signed

#32979 searcher: use gitserver.NewClient directly
  cmd/searcher/main.go
  cmd/searcher/search/store.go
Labels: cla-signed

#33315 Move git.Diff to gitserver.Client
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/repository_comparison_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/main_test.go
  enterprise/internal/batches/state/state.go
  enterprise/internal/batches/testing/mock_sync_state.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mocks.go
  internal/vcs/git/diff.go
  internal/vcs/git/diff_test.go
Labels: team/repo-management, cla-signed

#33263 gitserver: update janitor so it sets repo sizes
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/mocks.go
Labels: gitserver, team/repo-management, cla-signed, gitserver-rendezvous

#33254 codeintel: Add auth support for GitLab
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_gitlab.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_gitlab_test.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_middleware.go
  lib/codeintel/upload/request.go
  lib/codeintel/upload/upload_options.go
Labels: team/code-intelligence, cla-signed

#33356 Validate email format / length for sign-up
  cmd/frontend/internal/auth/userpasswd/handlers.go
  cmd/frontend/internal/auth/userpasswd/handlers_test.go
Labels: cla-signed

#33329 Main dry run/dt/stateless qa
  client/shared/src/testing/config.ts
  client/web/src/end-to-end/end-to-end.test.ts
  enterprise/dev/ci/internal/ci/operations.go
Labels: dx, ci, cla-signed, devx/stateless-agents

#33362 New reference panel: duplicate more code-intel-extensions logic
  client/web/src/codeintel/promise.ts
  client/web/src/codeintel/searchBased.ts
  client/web/src/codeintel/settings.ts
  client/web/src/codeintel/useCodeIntel.ts
  client/web/src/codeintel/useSearchBasedCodeIntel.ts
Labels: cla-signed

#33365 codeintel: Hide indexer hints if root does not match
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_tree_info_resolver.go
Labels: team/code-intelligence, cla-signed

#33360 codeintel: Add repository summary resolvers
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/repository.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/indexers.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/observability.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/summary.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/indexes_test.go
  enterprise/internal/codeintel/stores/dbstore/observability.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/uploads_test.go
Labels: cla-signed

#33366 chore: Add changelog entry
  CHANGELOG.md
Labels: team/code-intelligence, cla-signed

#33380 Remove Rob from G&I notifications
  .github/workflows/label-notify.yml
Labels: cla-signed

#33364 web(repo/tree): fix link to batch changes docs
  client/web/src/repo/tree/HomeTab.tsx
Labels: cla-signed

#31879 sg: add generate command
  dev/sg/generates.go
  dev/sg/internal/generate/generate.go
  dev/sg/internal/generate/golang/golang.go
  dev/sg/lints.go
  dev/sg/main.go
  dev/sg/sg_generate.go
  dev/sg/sg_lint.go
Labels: dx, sg, team/devx, cla-signed

#33292 search: suppress Zoekt error about nil query node for symbols
  internal/search/query_converter.go
Labels: cla-signed

#33387 doc/dev: fix formatting for Linux note
  doc/dev/how-to/monitoring_local_dev.md
Labels: cla-signed

#33326 dev/ci: try to de-emphasize log upload
  .buildkite/hooks/pre-exit
  enterprise/dev/ci/scripts/upload-build-logs.sh
Labels: cla-signed

#33398 prom-wrapper: fix conf usage
  docker-images/prometheus/cmd/prom-wrapper/siteconfig.go
Labels: cla-signed

#33298 batches: open modal when clicking download spec for src-cli link
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.module.scss
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
  client/web/src/enterprise/batches/create/DownloadSpecModal.module.scss
  client/web/src/enterprise/batches/create/DownloadSpecModal.story.tsx
  client/web/src/enterprise/batches/create/DownloadSpecModal.tsx
Labels: team/batchers, cla-signed

#33357 symbols: bump ctags to 5.9.20220403.0
  cmd/symbols/ctags-install-alpine.sh
  shell.nix
Labels: cla-signed

#33391 git-combine: Add commit limit arg
  internal/cmd/git-combine/git-combine.go
Labels: cla-signed

#33270 Update schema/README with step to update TypeScript schema files
  schema/README.md
Labels: cla-signed

#31555 bext: add percy snapshots to integration tests
  client/browser/src/integration/github.test.ts
  client/browser/src/integration/gitlab.test.ts
  client/browser/src/integration/shared.ts
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#33342 Simplify use of GQL fragments to avoid warnings
  client/web/src/codeintel/ReferencesPanelQueries.ts
Labels: cla-signed

#33269 Update changelog with capture group changes
  CHANGELOG.md
Labels: cla-signed

#33408 web: remove `percy` from e2e tests
  client/web/src/end-to-end/end-to-end.test.ts
  dev/ci/integration/e2e/test.sh
Labels: team/frontend-platform, ci, cla-signed

#33409 [cloud] Redirect the user when leaving organization
  client/web/src/org/members/OrgMembersListPage.tsx
Labels: cla-signed

#33354 Remove unused props and local storage checks
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: cla-signed

#33415 New reference panel: some minor fixes and refactorings
  client/web/src/codeintel/ReferencesPanel.module.scss
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/codeintel/useCodeIntel.ts
Labels: cla-signed, ref-panel

#33410 repo-updater: Expose current rate limit settings per external service
  cmd/repo-updater/shared/main.go
  internal/ratelimit/rate_limit.go
Labels: team/repo-management, cla-signed

#33348 Charts: [Line Chart] Add better support for stacked series data
  client/web/src/charts/components/line-chart/LineChart.story.tsx
  client/web/src/charts/components/line-chart/LineChart.tsx
  client/web/src/charts/components/line-chart/components/NonActiveBackground.tsx
  client/web/src/charts/components/line-chart/components/axis/Axis.tsx
  client/web/src/charts/components/line-chart/components/stacked-area/StackedArea.tsx
  client/web/src/charts/components/line-chart/components/stacked-area/get-stacked-area-paths.ts
  client/web/src/charts/components/line-chart/components/tooltip/TooltipContent.module.scss
  client/web/src/charts/components/line-chart/components/tooltip/TooltipContent.story.tsx
  client/web/src/charts/components/line-chart/components/tooltip/TooltipContent.tsx
  client/web/src/charts/components/line-chart/types.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/get-series-data.test.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/get-series-data.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/get-stacked-series-data.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/helpers.test.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/helpers.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/index.ts
  client/web/src/charts/components/line-chart/utils/data-series-processing/types.ts
  client/web/src/charts/components/line-chart/utils/generate-points-field.ts
  client/web/src/charts/components/line-chart/utils/get-min-max-boundary.test.ts
  client/web/src/charts/components/line-chart/utils/get-min-max-boundary.ts
  client/web/src/charts/components/line-chart/utils/get-stacked-area-paths.ts
  client/web/src/charts/components/line-chart/utils/index.ts
  client/web/src/charts/types.ts
  client/web/src/enterprise/insights/components/views/series/SeriesChart.story.tsx
Labels: team/code-insights, cla-signed, data-viz

#33341 Link to batch changes library repo
  client/web/src/enterprise/batches/create/library/LibraryPane.module.scss
  client/web/src/enterprise/batches/create/library/LibraryPane.tsx
Labels: cla-signed

#32947 Make sure we use separate toggles for opening update windows
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: cla-signed

#33434 graphql: Add `GitCommit.Path` resolver
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed

#33404 searcher: add Store.FetchTarPaths
  cmd/searcher/main.go
  cmd/searcher/search/store.go
Labels: cla-signed

#33444 Revert "bext: add percy snapshots to integration tests"
  client/browser/src/integration/github.test.ts
  client/browser/src/integration/gitlab.test.ts
  client/browser/src/integration/shared.ts
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: team/frontend-platform, cla-signed

#33443 Update helm.md
  doc/admin/install/kubernetes/helm.md
Labels: cla-signed

#33332 [SG-33093] Enable accessibilityAudit on `client/web/src/integration/batches.test.ts`
  client/shared/src/commandPalette/CommandList.tsx
  client/web/src/components/ActivationDropdown/__snapshots__/ActivationDropdown.test.tsx.snap
  client/web/src/components/AppRouterContainer/AppRouterContainer.tsx
  client/web/src/enterprise/batches/list/GettingStarted.tsx
  client/web/src/extensions/__snapshots__/ExtensionRegistrySidenav.test.tsx.snap
  client/web/src/integration/batches.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/nav/NavBar/NavDropdown.tsx
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/nav/__snapshots__/MenuNavItem.test.tsx.snap
  client/web/src/nav/__snapshots__/StatusMessagesNavItem.test.tsx.snap
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/wildcard/src/components/Menu/Menu.tsx
  client/wildcard/src/components/Menu/MenuButton.tsx
  client/wildcard/src/components/NavMenu/__snapshots__/NavMenu.test.tsx.snap
  client/wildcard/src/components/PageHeader/PageHeader.tsx
  client/wildcard/src/components/PageHeader/__snapshots__/PageHeader.test.tsx.snap
Labels: gitstart, cla-signed

#33153 codeintel: Add empty code intelligence badge to repository page
  client/shared/src/settings/settings.ts
  client/web/src/OpenSourceWebApp.tsx
  client/web/src/codeintel/RepositoryMenu.module.scss
  client/web/src/codeintel/RepositoryMenu.tsx
  client/web/src/codeintel/index.ts
  client/web/src/enterprise/EnterpriseWebApp.tsx
  client/web/src/enterprise/codeintel/RepositoryMenu.module.scss
  client/web/src/enterprise/codeintel/RepositoryMenu.tsx
  client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
  client/web/src/repo/RepoContainer.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: team/code-intelligence, cla-signed

#33307 Update helm.md
  doc/admin/install/kubernetes/helm.md
Labels: cla-signed

#33452 Update Helm menu buttons
  doc/admin/install/kubernetes/helm.md
Labels: cla-signed

#33453 chore: Removed unreferenced files
  client/web/src/enterprise/codeintel/RepositoryMenu.module.scss
  client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
Labels: cla-signed

#33455 Release: update release config for 3.38.1 patch
  dev/release/release-config.jsonc
Labels: cla-signed

#33460 codeintel: Fix naked scheme for index resolver URL
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/indexers.go
Labels: team/code-intelligence, cla-signed

#33450 Disable Terraform scanning step in Buildkite pipeline
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#33459 codeintel: Add useCodeIntelStatus hook
  client/web/src/enterprise/codeintel/RepositoryMenu.tsx
  client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
Labels: team/code-intelligence, cla-signed

#33468 update changelog for v3.38.1
  CHANGELOG.md
Labels: cla-signed

#33466 codeintel: Add storybook for repo badge
  client/web/src/codeintel/RepositoryMenu.story.tsx
  client/web/src/enterprise/codeintel/RepositoryMenu.story.tsx
  client/web/src/enterprise/codeintel/RepositoryMenu.tsx
  client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
Labels: team/code-intelligence, cla-signed

#33467 Code monitors: convert tests to autogold
  enterprise/internal/codemonitors/background/email_test.go
  enterprise/internal/codemonitors/background/slack_test.go
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results/html.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results/subject.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results/text.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results_with_results/html.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results_with_results/text.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/one_result/html.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/one_result/text.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/one_result_with_results/html.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/one_result_with_results/text.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/test_message/html.golden
  enterprise/internal/codemonitors/background/testdata/TestEmail/test_message/text.golden
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/error_is_returned.golden
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_with_results.golden
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_with_truncated_results.golden
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_without_results.golden
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/no_error.golden
  enterprise/internal/codemonitors/background/testdata/TestTriggerTestSlackWebhookAction.golden
  enterprise/internal/codemonitors/background/testdata/TestTriggerTestWebhookAction.golden
  enterprise/internal/codemonitors/background/webhook_test.go
Labels: cla-signed

#33483 dev/ci: remove flakey browser ext
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#33441 Fix global keyboard shorcuts interference with CodeMirror search query input
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/shared/src/components/CodeMirrorEditor.ts
  client/shared/src/components/MonacoEditor.tsx
  client/shared/src/util/dom.test.ts
  client/shared/src/util/dom.ts
  client/web/src/notebooks/notebook/useNotebookEventHandlers.ts
  client/web/src/repo/actions/GoToPermalinkAction.tsx
Labels: cla-signed

#33361 search: Only highlight current filter when input has focus
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
Labels: cla-signed, codemirror

#33505 search-blitz: extra queries for dogfood
  internal/cmd/search-blitz/config.go
  internal/cmd/search-blitz/config_test.go
  internal/cmd/search-blitz/main.go
  internal/cmd/search-blitz/queries_dogfood.txt
Labels: cla-signed

#33487 gitserver: add logs to janitor and make the test less primitive in terms of repo names
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
Labels: gitserver, team/repo-management, cla-signed, gitserver-rendezvous

#33526 gitserver: add some grammar to log
  cmd/gitserver/server/cleanup.go
Labels: team/repo-management, cla-signed

#33490 repo-updater: Increase time allowed to sync repo in background
  cmd/repo-updater/repoupdater/server.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/internal/batches/syncer/syncer.go
  internal/metrics/operation.go
  internal/repos/sync_errored.go
  internal/repos/syncer.go
Labels: team/repo-management, cla-signed

#33454 Jdb/sort-chart-series
  CHANGELOG.md
  client/web/src/enterprise/insights/core/backend/utils/create-line-chart-content.ts
  client/web/src/insights/utils/semantic-sort.test.ts
  client/web/src/insights/utils/semantic-sort.ts
  client/web/src/views/mocks/charts-content.ts
Labels: cla-signed

#33481 codeintel: Expose additional data in useCodeIntelStatus
  client/web/src/enterprise/codeintel/RepositoryMenu.story.tsx
  client/web/src/enterprise/codeintel/queries.ts
  client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
Labels: team/code-intelligence, cla-signed

#33534 Fix "quick start" file page overflow when file tree is longer than height
  client/web/src/repo/RepoRevisionSidebar.tsx
Labels: cla-signed

#33547 ratelimit: Handle marshalling of infinite limiters
  internal/ratelimit/rate_limit.go
  internal/ratelimit/rate_limit_test.go
Labels: team/repo-management, cla-signed

#33400 add caveat to check https://lsif.dev/
  doc/code_intelligence/references/troubleshooting.md
Labels: cla-signed

#33419 New reference panel: handle `codeIntel.mixPreciseAndSearchBasedReferences`
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/codeintel/location.ts
  client/web/src/codeintel/useCodeIntel.ts
  client/web/src/codeintel/useSearchBasedCodeIntel.ts
Labels: cla-signed

#33549 codeintel: Update nullability of code intel support in graphql
  client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_blob_info_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_tree_info_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/support.go
Labels: cla-signed

#33471 batches: fix file name command error on batch preview
  client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.tsx
Labels: team/batchers, cla-signed

#33540 New reference panel: fix grouping of files by repo
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/codeintel/location.ts
Labels: cla-signed

#33535 New reference panel: filter out defs on isExternalPrivateSymbol
  client/web/src/codeintel/location.ts
  client/web/src/codeintel/searchBased.ts
  client/web/src/codeintel/useSearchBasedCodeIntel.ts
Labels: cla-signed, ref-panel

#33554 Search: close PartitionRepos trace
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#33482 codeintel: Expose debug data
  client/web/src/enterprise/codeintel/RepositoryMenu.tsx
Labels: team/code-intelligence, cla-signed

#33230 docs(helm): fix duplicated anchor ids
  doc/admin/install/kubernetes/helm.md
Labels: cla-signed

#33386 insights: Add codeinsights-db to monitoring
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  docker-images/postgres_exporter/build.sh
  docker-images/postgres_exporter/config/06_codeinsights_migration.yaml
  monitoring/definitions/postgres.go
Labels: cla-signed

#33559 update pure-docker deployment notes for 3.38.1
  doc/admin/updates/pure_docker.md
Labels: cla-signed

#33562 insights docs: emphasize backfiller gives you years of history even if you start using it today
  doc/code_insights/index.md
Labels: cla-signed

#33472 release: sourcegraph@3.38.1
  client/web/src/search/home/SelfHostInstructions.tsx
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/install/docker-compose/aws.md
  doc/admin/install/docker-compose/digitalocean.md
  doc/admin/install/docker-compose/google_cloud.md
  doc/admin/install/docker-compose/operations.md
  doc/admin/install/docker/aws.md
  doc/admin/install/docker/digitalocean.md
  doc/admin/install/docker/google_cloud.md
  doc/admin/install/docker/index.md
  doc/admin/install/docker/operations.md
  doc/admin/install/kubernetes/configure.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/server.md
  doc/index.md
Labels: cla-signed

#33564 wildcard: Add outline-secondary to badge variants
  client/wildcard/src/components/Badge/constants.ts
Labels: cla-signed

#33563 fix: Remove expanded commits from non-root directory page
  client/web/src/repo/tree/HomeTab.tsx
Labels: cla-signed

#33568 Release 3.38.1: add upgrade docs for k8s and docker_compose
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#33567 codeintel: Add rich indexer to lsif upload/indexer types
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/index.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/summary.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/upload.go
Labels: team/code-intelligence, cla-signed

#33570 Update release config for 3.39
  dev/release/release-config.jsonc
Labels: cla-signed

#33574 syntax-highlighter: Remove usage of git submodules for tree-sitter grammars
  .gitattributes
  .gitmodules
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/README.md
  docker-images/syntax-highlighter/build.sh
  docker-images/syntax-highlighter/crates/sg-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/sg-syntax/build.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
Labels: cla-signed

#33569 codeintel: Use new indexer field for uploads/indexes in SPA
  client/web/src/enterprise/codeintel/RepositoryMenu.tsx
  client/web/src/enterprise/codeintel/indexes/hooks/types.tsx
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexPage.story.tsx
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexesPage.story.tsx
  client/web/src/enterprise/codeintel/shared/components/CodeIntelIndexer.tsx
  client/web/src/enterprise/codeintel/shared/components/CodeIntelUploadOrIndexIndexer.tsx
  client/web/src/enterprise/codeintel/uploads/hooks/types.tsx
  client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadPage.story.tsx
  client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.story.tsx
Labels: team/code-intelligence, cla-signed

#33498 ci: use `PERCY_PARALLEL_TOTAL` instead of the `finalize` step
  dev/ci/yarn-web-integration.sh
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: team/frontend-platform, ci, cla-signed

#33491 Move git.DiffPath to gitserver.Client
  enterprise/cmd/frontend/internal/codeintel/resolvers/position.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/position_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mock_client.go
  internal/vcs/git/diff.go
  internal/vcs/git/diff_test.go
  internal/vcs/git/exec.go
Labels: cla-signed

#33432 gitserver: eventually re-clone after failed sg maintenance
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
Labels: cla-signed

#33347 doc: update zoekt how-to
  doc/dev/how-to/zoekt_local_dev.md
Labels: cla-signed

#33544 search-blitz: track literal queries for monorepos
  internal/cmd/search-blitz/queries.txt
  internal/cmd/search-blitz/queries_dogfood.txt
Labels: cla-signed

#33403 Move git.CommitGraph to gitserver.Client
  enterprise/cmd/frontend/internal/codeintel/resolvers/exists.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/iface.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/mock_iface_test.go
  enterprise/cmd/worker/internal/codeintel/commitgraph/updater.go
  enterprise/internal/codeintel/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/gitdomain/commit_graph.go
  internal/vcs/git/commits.go
Labels: cla-signed

#33580 search-blitz: gigarepo literal queries uniq names
  internal/cmd/search-blitz/queries_dogfood.txt
Labels: cla-signed

#33583 bext: fix show repo on Sourcegraph button rendering logic on GitHub
  client/browser/src/shared/code-hosts/shared/ViewOnSourcegraphButton.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
Labels: cla-signed

#33584 database: make `SecurityEventLogsStore` an interface
  enterprise/internal/database/mocks.go
  internal/database/database.go
  internal/database/mock_gen.go
  internal/database/mocks.go
  internal/database/security_event_logs.go
  internal/database/security_event_logs_test.go
Labels: cla-signed

#33295 search: Refactor Monaco query input suggestions
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/shared/src/search/query/completion.test.ts
  client/shared/src/search/query/completion.ts
  client/shared/src/search/query/filters.ts
  client/shared/src/search/query/providers.test.ts
  client/shared/src/search/query/providers.ts
  client/shared/src/search/stream.ts
  client/web/src/integration/search.test.ts
Labels: cla-signed

#33560 gitserver: add GetByNames function to gitserver store
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/mocks.go
Labels: gitserver, team/repo-management, cla-signed, gitserver-rendezvous

#33406 Fix native integration to pass cookies/credentials for "Extensions" info graphql request
  client/browser/scripts/build-npm.ts
  client/browser/scripts/build.ts
  client/browser/scripts/publish-npm.ts
  client/browser/src/shared/backend/requestGraphQl.ts
  client/http-client/src/graphql/apollo/client.ts
Labels: cla-signed

#33588 bext: disable integration tests
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#33589 gitserver: fix cleanup tests
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
Labels: cla-signed

#33178 Kustomize docs centralization
  doc/admin/deployment_best_practices.md
  doc/admin/install/kubernetes/configure.md
  doc/admin/install/kubernetes/index.md
  doc/admin/install/kubernetes/kustomize.md
Labels: cla-signed

#33593 Update client/browser/CHANGELOG.md
  client/browser/CHANGELOG.md
Labels: merge-on-any-approve, cla-signed

#33595 Move git.diff.DiffSymbols to gitserver.Client
  cmd/symbols/gitserver/client.go
  internal/gitserver/commands.go
  internal/vcs/git/diff.go
  internal/vcs/git/diff_test.go
Labels: cla-signed

#33545 web: wait for query highlighting to avoid Percy flakes
  client/web/src/integration/search-contexts.test.ts
Labels: team/frontend-platform, ci, ci/flake, cla-signed

#33594 repos: Tag sync errors with a reason
  internal/repos/metrics.go
  internal/repos/syncer.go
Labels: team/repo-management, cla-signed

#33550 gitserver: allow missing date in for-each-refs tags output
  enterprise/internal/codeintel/policies/matcher.go
  enterprise/internal/codeintel/policies/matcher_common_test.go
  enterprise/internal/codeintel/stores/dbstore/commits.go
  enterprise/internal/codeintel/stores/dbstore/commits_test.go
  internal/gitserver/gitdomain/common.go
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
Labels: gitserver, cla-signed

#33572 luasandbox: Initial implementation
  go.mod
  go.sum
  internal/luasandbox/CODENOTIFY
  internal/luasandbox/init.go
  internal/luasandbox/observability.go
  internal/luasandbox/service.go
  internal/luasandbox/service_test.go
Labels: team/code-intelligence, cla-signed

#33601 migration: Remove ALTER ... OWNER TO postgres from test input
  internal/database/migration/store/describe_test.go
Labels: cla-signed

#33602 ci: create client PR preview only when backend code is not changed
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: team/frontend-platform, ci, cla-signed

#33606 Fix broken overlays link
  doc/admin/install/kubernetes/configure.md
Labels: cla-signed

#33603 search: Add information about dependencies predicate to search reference
  client/search-ui/src/results/sidebar/SearchReference.tsx
Labels: cla-signed

#33605 bext: fix command palette mount container selector
  client/browser/src/shared/code-hosts/github/extensions.tsx
Labels: cla-signed

#33577 Redirect new user to org invitation page when singing up from an invitation link/email
  client/web/src/auth/SignUpPage.tsx
Labels: cla-signed

#33469 remove separate codeinsights-db pod in local development and point to…
  sg.config.yaml
Labels: cla-signed

#33556 internal/extsvc: Test edge case in ExtractRateLimitConfig
  internal/extsvc/types_test.go
Labels: cla-signed

#33195 gitserver: Add BatchLog
  cmd/gitserver/main.go
  cmd/gitserver/server/observability.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  cmd/gitserver/server/servermetrics.go
  doc/admin/observability/dashboards.md
  enterprise/internal/codeintel/gitserver/client.go
  internal/api/api.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/mock_client.go
  internal/gitserver/observability.go
  internal/gitserver/protocol/gitserver.go
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/shared/gitserver.go
Labels: cla-signed

#33620 chore: Fix merge conflict
  internal/vcs/git/commits_test.go
Labels: cla-signed

#33451 insights: Add backend integration tests
  cmd/server/shared/postgres.go
  cmd/server/shared/shared.go
  dev/ci/integration/run-integration.sh
  dev/gqltest/code_insights_test.go
  dev/run-server-image.sh
  enterprise/internal/insights/insights.go
  internal/gqltestutil/code_insights.go
Labels: cla-signed

#33624 pr-auditor: support test plans in poorly formatted markdown
  dev/pr-auditor/check.go
  dev/pr-auditor/check_test.go
  dev/pr-auditor/testdata/pull_request_body/bad-markdown.md
Labels: cla-signed

#33561 Code monitors: drop unused columns
  internal/database/schema.md
  migrations/frontend/1649269601/down.sql
  migrations/frontend/1649269601/metadata.yaml
  migrations/frontend/1649269601/up.sql
Labels: cla-signed

#33626 web(repo/tree): friendlier no-readme placeholder
  client/web/src/repo/tree/HomeTab.tsx
Labels: cla-signed

#33553 Code Insights: Refactor creation UI lang stats preview
  client/web/src/charts/components/pie-chart/PieChart.tsx
  client/web/src/charts/types.ts
  client/web/src/enterprise/insights/components/views/card/InsightCard.module.scss
  client/web/src/enterprise/insights/components/views/card/InsightCard.story.tsx
  client/web/src/enterprise/insights/components/views/card/InsightCard.tsx
  client/web/src/enterprise/insights/components/views/chart/categorical/CategoricalChart.story.tsx
  client/web/src/enterprise/insights/components/views/chart/categorical/CategoricalChart.tsx
  client/web/src/enterprise/insights/components/views/chart/index.ts
  client/web/src/enterprise/insights/components/views/chart/series/SeriesChart.story.tsx
  client/web/src/enterprise/insights/components/views/chart/series/SeriesChart.tsx
  client/web/src/enterprise/insights/components/views/index.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-context.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-types.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.module.scss
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/live-preview-chart/hooks/use-lang-stats-preview-content.ts
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/live-preview-chart/live-preview-mock-data.ts
  client/web/src/views/components/view/content/chart-view-content/charts/MaybeLink.tsx
Labels: cla-signed

#33581 ci: run go steps for any change in go sub dirs
  enterprise/dev/ci/internal/ci/changed/diff.go
  enterprise/dev/ci/internal/ci/changed/diff_test.go
Labels: cla-signed

#33608 ratelimit: Increase default burst to 10
  internal/extsvc/bitbucketcloud/client.go
  internal/ratelimit/rate_limit.go
  internal/ratelimit/rate_limit_test.go
Labels: team/repo-management, cla-signed

#33642 docs: add PR previews documentation
  dev/ci/render-pr-preview.sh
  doc/dev/how-to/client_pr_previews.md
  doc/dev/how-to/index.md
Labels: docs, team/frontend-platform, dx, ci, cla-signed

#33644 ratelimit: NPM package syncer should sync rate limit from config
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  internal/extsvc/npm/npm.go
  internal/extsvc/npm/npm_test.go
  internal/extsvc/types.go
  internal/extsvc/types_test.go
  internal/repos/npm_packages.go
Labels: team/repo-management, cla-signed

#33274 Update insights backend docs with new database state
  doc/admin/external_services/postgres.md
  doc/dev/background-information/insights/backend.md
  doc/dev/background-information/insights/diagrams/architecture.excalidraw
  doc/dev/background-information/insights/diagrams/architecture.svg
Labels: cla-signed

#33648 search-blitz: update-deploy.sh updates dogfood
  internal/cmd/search-blitz/scripts/build.sh
  internal/cmd/search-blitz/scripts/update-deploy-sourcegraph-dot-com.sh
  internal/cmd/search-blitz/scripts/update-deploy.sh
Labels: cla-signed

#33645 Update client/browser/CHANGELOG.md after Browser Extension release
  client/browser/CHANGELOG.md
Labels: cla-signed

#33542 search: Fix user settings overwriting search parameters from URL
  client/search-ui/src/results/sidebar/SearchSidebar.story.tsx
  client/search/src/searchQueryState.tsx
  client/web/src/stores/navbarSearchQueryState.test.ts
  client/web/src/stores/navbarSearchQueryState.ts
  client/web/src/util/settings.ts
Labels: cla-signed

#33537 Don't show fork indicator when not forking
  client/web/src/enterprise/batches/Branch.story.tsx
  client/web/src/enterprise/batches/Branch.tsx
Labels: cla-signed

#33647 Helm doc typos and grammar
  doc/admin/install/kubernetes/helm.md
Labels: cla-signed

#33651 gitserver: refactor TestCleanupOldLocks
  cmd/gitserver/server/cleanup_test.go
Labels: cla-signed

#33654 repo-updater: Sync rate limiter before service
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/shared/main.go
Labels: team/repo-management, cla-signed

#33649 ratelimit: Replace RateLimitConfig with rate.Limit
  internal/extsvc/types.go
  internal/extsvc/types_test.go
  internal/repos/types.go
Labels: team/repo-management, cla-signed

#33618 Add executedQuery and resultClassName props to search list
  client/search-ui/src/components/SearchResult.tsx
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebookPage/NotebookContent.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
Labels: cla-signed

#33621 VSCE: Update CTA banner and add dismiss button
  client/vscode/src/settings/LocalStorageService.ts
  client/vscode/src/webview/search-panel/SearchResultsView.tsx
  client/vscode/src/webview/search-panel/components/SearchCta.module.scss
  client/vscode/src/webview/search-panel/components/SearchCta.tsx
  client/vscode/src/webview/search-panel/index.module.scss
Labels: team/growth-and-integrations, cla-signed, vscode-extension

#33669 Backend: remove unused variable
  internal/database/users.go
Labels: cla-signed

#33658 changelog: mention updates to sg maintenance
  CHANGELOG.md
Labels: cla-signed

#33674 Update release tool to version helm chart the same as other deployment repos
  dev/release/src/release.ts
Labels: cla-signed
