Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-07, with the labels that each got.

#38056 Code monitors: refer to the correct ID when joining monitors
  enterprise/internal/database/code_monitor_emails.go
  enterprise/internal/database/code_monitor_emails_test.go
  enterprise/internal/database/code_monitor_queries.go
  enterprise/internal/database/code_monitor_queries_test.go
  enterprise/internal/database/code_monitor_slack_webhook.go
  enterprise/internal/database/code_monitor_slack_webhook_test.go
  enterprise/internal/database/code_monitor_webhook.go
  enterprise/internal/database/code_monitor_webhook_test.go
Labels: cla-signed

#37980 notebooks: Migrate query inputs from Monaco to CodeMirror
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/search-ui/src/input/extensions/completion.ts
  client/search-ui/src/input/extensions/index.ts
  client/shared/src/components/CodeMirrorEditor.ts
  client/web/src/integration/notebook.test.ts
  client/web/src/notebooks/blocks/NotebookBlock.module.scss
  client/web/src/notebooks/blocks/NotebookBlock.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.module.scss
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.module.scss
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.story.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/suggestions/SearchTypeSuggestionsInput.module.scss
  client/web/src/notebooks/blocks/suggestions/SearchTypeSuggestionsInput.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlockInput.tsx
  client/web/src/notebooks/blocks/useFocusMonacoEditorOnMount.ts
  client/web/src/notebooks/blocks/useMonacoBlockInput.ts
  client/web/src/notebooks/codemirror-utils.ts
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebook/useNotebookEventHandlers.ts
Labels: cla-signed

#38007 Enterprise: Codemod remaining `<Icon />` usage to `@mdi/js`
  client/web/src/enterprise/code-monitoring/CodeMonitoringGettingStarted.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
  client/web/src/enterprise/code-monitoring/components/logs/CollapsibleDetailsWithStatus.tsx
  client/web/src/enterprise/code-monitoring/components/logs/MonitorLogNode.tsx
  client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
  client/web/src/enterprise/executors/ExecutorsListPage.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionDeleteButton.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionManagePage.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionNewReleasePage.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/actions/CodeInsightIndependentPageActions.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/dashboard-pills/StandaloneInsightDashboardPills.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-templates/CodeInsightsTemplates.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/dynamic-code-insight-example/DynamicCodeInsightExample.tsx
  client/web/src/enterprise/search/stats/SearchStatsPage.tsx
  client/web/src/enterprise/search/stats/__snapshots__/SearchStatsPage.test.tsx.snap
  client/web/src/enterprise/searchContexts/SearchContextOwnerDropdown.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListPage.tsx
  client/web/src/enterprise/site-admin/SiteAdminRegistryExtensionsPage.tsx
  client/web/src/enterprise/site-admin/dotcom/customers/SiteAdminCustomerBillingLink.tsx
  client/web/src/enterprise/site-admin/dotcom/customers/__snapshots__/SiteAdminCustomerBillingLink.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminCreateProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionBillingLink.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionBillingLink.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/BackToAllSubscriptionsLink.tsx
  client/web/src/enterprise/user/productSubscriptions/NewProductSubscriptionPaymentSection.tsx
  client/web/src/enterprise/user/productSubscriptions/ProductSubscriptionHistory.tsx
  client/web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsEditProductSubscriptionPage.tsx
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserProductSubscriptionStatus.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsEditProductSubscriptionPage.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsProductSubscriptionPage.test.tsx.snap
Labels: team/frontend-platform, cla-signed

#38067 web: fix `web-standalone` proxy-warning contrast issue
  client/web/src/global/GlobalAlerts.module.scss
  client/web/src/global/GlobalAlerts.tsx
Labels: team/frontend-platform, cla-signed

#37836 JetBrains: Remove usage of APIs added after 2021.1
  client/jetbrains/gradle.properties
  client/jetbrains/src/main/java/com/sourcegraph/browser/JSToJavaBridge.java
  client/jetbrains/src/main/java/com/sourcegraph/browser/JavaToJSBridge.java
  client/jetbrains/src/main/java/com/sourcegraph/browser/SourcegraphJBCefBrowser.java
  client/jetbrains/src/main/java/com/sourcegraph/find/SelectionMetadataPanel.java
Labels: cla-signed

#38017 Web: Codemod `<Icon />` to `@mdi/js`
  client/web/src/components/Breadcrumbs.tsx
  client/web/src/components/Collapsible.tsx
  client/web/src/components/CopyableText.tsx
  client/web/src/components/DismissibleAlert/DismissibleAlert.tsx
  client/web/src/components/MarketingBlock/MarketingBlock.story.tsx
  client/web/src/components/SaveToolbar.tsx
  client/web/src/components/SelfHostedCta/SelfHostedCta.tsx
  client/web/src/components/Sidebar.tsx
  client/web/src/components/Timeline.story.tsx
  client/web/src/components/Timeline.tsx
  client/web/src/components/diff/FileDiffNode.tsx
  client/web/src/components/externalServices/ExternalServiceCard.tsx
  client/web/src/components/externalServices/ExternalServiceNode.tsx
  client/web/src/components/externalServices/ExternalServicesPage.tsx
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductLicenseNode.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  client/web/src/global/__snapshots__/Notices.test.tsx.snap
  client/web/src/org/members/InviteMemberModal.tsx
  client/web/src/org/members/utils.tsx
  client/web/src/org/settings/DeleteOrgModal.tsx
  client/web/src/org/settings/members-v1/InviteForm.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoHeader.tsx
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarCommits.tsx
  client/web/src/repo/RevisionsPopover/RevisionsPopover.tsx
  client/web/src/repo/actions/CopyPathAction.tsx
  client/web/src/repo/actions/GoToCodeHostAction.story.tsx
  client/web/src/repo/actions/GoToPermalinkAction.tsx
  client/web/src/repo/blob/GoToRawAction.tsx
  client/web/src/repo/blob/actions/ToggleHistoryPanel.tsx
  client/web/src/repo/blob/actions/ToggleLineWrap.tsx
  client/web/src/repo/blob/actions/ToggleRenderedFileMode.tsx
  client/web/src/repo/branches/RepositoryBranchesOverviewPage.tsx
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/compare/RepositoryCompareHeader.tsx
  client/web/src/repo/settings/RepoSettingsIndexPage.tsx
  client/web/src/repo/settings/RepoSettingsMirrorPage.tsx
  client/web/src/repo/tree/BranchesTab.tsx
  client/web/src/repo/tree/TabNavigation.tsx
  client/web/src/repo/tree/TreeEntriesSection.tsx
  client/web/src/repo/tree/TreeNavigation.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/repo/tree/TreeTabList.tsx
  client/web/src/repo/tree/__snapshots__/TreeEntriesSection.test.tsx.snap
  client/web/src/site-admin/overview/__snapshots__/SiteAdminOverviewPage.test.tsx.snap
  client/web/src/site/__snapshots__/LicenseExpirationAlert.test.tsx.snap
  client/web/src/user/settings/UserSettingsSidebar.tsx
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
  client/web/src/user/settings/accessTokens/UserSettingsTokensPage.tsx
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/components/EncryptedDataIcon.tsx
  client/web/src/user/settings/repositories/RepositoryNode.tsx
  client/web/src/user/settings/repositories/SettingsRepositoriesPage.tsx
  client/web/src/user/settings/research/ProductResearch.tsx
Labels: team/frontend-platform, cla-signed

#38010 codemirror: Migrate SiteAdminPingsPage to use CodeMirror
  client/search-ui/src/input/extensions/index.ts
  client/shared/src/components/CodeMirrorEditor.ts
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  package.json
  yarn.lock
Labels: cla-signed

#38073 notebooks: Fix markdown block height
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.tsx
Labels: cla-signed

#38083 dev: add enterprise-frontend to SRC_PROF_SERVICES
  sg.config.yaml
Labels: cla-signed

#38069 web: fix `blog-viewer` integration test flake
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/repo/blob/Blob.tsx
  client/web/src/repo/blob/BlobPage.tsx
Labels: team/frontend-platform, ci/flake, cla-signed

#38082 gitserver: Cleanups
  cmd/frontend/backend/inventory.go
  cmd/frontend/graphqlbackend/git_blob.go
  cmd/frontend/graphqlbackend/git_tree.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/internal/app/ui/raw.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/position.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/integration_tests/tree_test.go
  internal/gitserver/mocks_temp.go
  internal/httpserver/server.go
  internal/vcs/util/path.go
Labels: team/repo-management, cla-signed

#38090 docs: Add some basic docs for p4-fusion
  doc/admin/repo/perforce.md
Labels: team/repo-management, cla-signed

#38059 Insights/revert compute changes
  enterprise/internal/compute/client/compute_text_client.go
  enterprise/internal/compute/output_command.go
  enterprise/internal/compute/output_command_test.go
  enterprise/internal/compute/replace_command.go
  enterprise/internal/compute/replace_command_test.go
  enterprise/internal/compute/text_result.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/work_handler_test.go
  enterprise/internal/insights/background/queryrunner/worker.go
  enterprise/internal/insights/query/capture_group_executor.go
  enterprise/internal/insights/query/streaming/decoder.go
  enterprise/internal/insights/types/types.go
Labels: cla-signed

#38096 VSCE: update changelog
  client/vscode/CHANGELOG.md
Labels: cla-signed

#37050 Update jsonc-parser
  client/browser/src/shared/platform/settings.ts
  client/common/src/util/jsonc.ts
  client/shared/src/settings/settings.test.ts
  client/shared/src/testing/driver.ts
  client/storybook/src/webpack.config.common.ts
  client/web/dev/utils/get-site-config.ts
  client/web/src/components/externalServices/ExternalServicePage.tsx
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/searchContexts/SearchContextRepositoriesFormArea.tsx
  client/web/src/enterprise/searchContexts/repositoryRevisionsConfigParser.ts
  client/web/src/regression/codeintel.test.ts
  client/web/src/regression/core.test.ts
  client/web/src/regression/util/helpers.ts
  client/web/src/settings/MonacoSettingsEditor.tsx
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/configHelpers.ts
  dev/release/src/config.ts
  package.json
  yarn.lock
Labels: cla-signed

#38102 Code Insights: Fix query data points link generation
  CHANGELOG.md
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-backend-insight-data/deserializators.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-insight-preview.ts
  client/web/src/enterprise/insights/core/backend/utils/create-line-chart-content.ts
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
Labels: cla-signed

#38103 Revert "sg start, use local universal-ctags by default, if available"
  cmd/symbols/build-ctags.sh
  cmd/symbols/universal-ctags-dev
  dev/sg/dependencies/mac.go
  dev/sg/dependencies/ubuntu.go
  sg.config.yaml
Labels: cla-signed

#37044 rockskip: Remember to close the ctags.Parser
  enterprise/cmd/symbols/main.go
  enterprise/internal/rockskip/index.go
  enterprise/internal/rockskip/search.go
  enterprise/internal/rockskip/server.go
  enterprise/internal/rockskip/server_test.go
Labels: cla-signed

#38100 codemirror: Show a loading indicator for search query suggestions
  client/search-ui/src/input/CodeMirrorQueryInput.module.scss
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/search-ui/src/input/extensions/index.ts
  client/search-ui/src/input/extensions/loading-indicator.ts
Labels: cla-signed

#37858 Add improved code intel support for Starlark
  client/shared/src/languages.ts
  cmd/symbols/squirrel/lang_starlark.go
  cmd/symbols/squirrel/language-file-extensions.json
  cmd/symbols/squirrel/languages.go
  cmd/symbols/squirrel/service.go
  cmd/symbols/squirrel/test_repos/starlark/BUILD
  cmd/symbols/squirrel/test_repos/starlark/BUILD.bazel
  cmd/symbols/squirrel/test_repos/starlark/WORKSPACE
  cmd/symbols/squirrel/test_repos/starlark/bzl_library.bzl
  cmd/symbols/squirrel/test_repos/starlark/sample.bzl
  cmd/symbols/squirrel/util.go
Labels: cla-signed

#38055 Code Insights: clean up code insight creation UI and add high-level compute page
  client/web/src/enterprise/insights/components/creation-ui-kit/creation-ui-layout/CreationUiLayout.module.scss
  client/web/src/enterprise/insights/components/creation-ui-kit/creation-ui-layout/CreationUiLayout.tsx
  client/web/src/enterprise/insights/components/creation-ui-kit/index.ts
  client/web/src/enterprise/insights/components/form/index.ts
  client/web/src/enterprise/insights/components/index.ts
  client/web/src/enterprise/insights/hooks/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/CreationRoutes.tsx
  client/web/src/enterprise/insights/pages/insights/creation/InsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/LineChartLivePreview.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/CaptureGoupCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/CaptureGroupCreationContent.tsx
  client/web/src/enterprise/insights/pages/insights/creation/compute/ComputeInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/compute/components/ComputeInsightCreationContent.tsx
  client/web/src/enterprise/insights/pages/insights/creation/compute/components/types.ts
  client/web/src/enterprise/insights/pages/insights/creation/compute/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/lang-stats-insight-creation-content/LangStatsInsightCreationContent.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/live-preview-chart/LangStatsInsightLivePreview.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/SearchInsightCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/search-insight-creation-content/SearchInsightCreationContent.tsx
Labels: cla-signed

#38114 insights: ensure that priority from time interval does not exceed HIGH
  internal/insights/priority/priority.go
  internal/insights/priority/priority_test.go
Labels: cla-signed

#37648 Fix perforce permissions interpretation for rules where there is a wildcard in the depot name
  enterprise/internal/authz/perforce/protects.go
  enterprise/internal/authz/perforce/protects_test.go
  enterprise/internal/authz/perforce/testdata/sample-protects-m.txt
  enterprise/internal/authz/perforce/testdata/sample-protects-x.txt
Labels: cla-signed

#38113 Search backend: use efficient implementation for repo:contains.commit.after()
  internal/search/job/jobutil/job.go
  internal/search/query/predicate.go
  internal/search/query/types.go
  internal/search/query/visitor.go
Labels: cla-signed

#38117 Search backend: add logger to searchResolver
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_test.go
  enterprise/cmd/frontend/internal/compute/init.go
  enterprise/cmd/frontend/internal/compute/resolvers/resolvers.go
Labels: cla-signed

#38122 Search backend: propagate logger through compute streams
  enterprise/cmd/frontend/internal/compute/init.go
  enterprise/cmd/frontend/internal/compute/streaming/compute.go
  enterprise/cmd/frontend/internal/compute/streaming/stream.go
Labels: cla-signed

#38126 Search backend: add logger to code monitor resolver
  enterprise/cmd/frontend/internal/codemonitors/init.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/main_test.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
Labels: cla-signed

#38127 Search backend: add logger to search client
  cmd/frontend/internal/search/search.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/compute/streaming/compute.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/search.go
  internal/search/client/client.go
Labels: cla-signed

#38129 Search backend: add logger to runtime clients
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/client/client.go
  internal/search/job/job.go
Labels: cla-signed

#38061 compute: add another output command that exposes more metadata
  enterprise/internal/compute/output_command.go
  enterprise/internal/compute/output_command_test.go
  enterprise/internal/compute/query.go
  enterprise/internal/compute/result.go
  enterprise/internal/compute/text_result.go
Labels: cla-signed

#38095 feature(sg/analytics): add pending messages while your analytics are being submitted
  dev/sg/internal/analytics/actions.go
  dev/sg/sg_analytics.go
Labels: sg, team/devx, cla-signed

#38140 debugserver: remove DB interface for debug dump
  cmd/repo-updater/shared/main.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  internal/debugserver/debug.go
  internal/repos/scheduler.go
Labels: cla-signed, team/iam

#34639 Add precise examples doc
  doc/code_intelligence/index.md
  doc/code_intelligence/references/index.md
  doc/code_intelligence/references/precise_examples.md
Labels: cla-signed

#38091 insights: don't error on empty repo in commit indexer
  CHANGELOG.md
  enterprise/internal/insights/compression/worker.go
  enterprise/internal/insights/compression/worker_test.go
Labels: cla-signed

#38086 JetBrains: Add popup open action to main menu
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#38093 JetBrains: Add settings to app-level config
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SourcegraphApplicationService.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SourcegraphProjectService.java
  client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
  client/jetbrains/src/main/java/com/sourcegraph/git/GitUtil.java
Labels: cla-signed

#38081 JetBrains: Add “Open” button to bottom-right
  client/jetbrains/src/main/java/com/sourcegraph/browser/JSToJavaBridge.java
  client/jetbrains/src/main/java/com/sourcegraph/browser/JavaToJSBridge.java
  client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/FooterPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/PreviewPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/SelectionMetadataPanel.java
Labels: cla-signed

#38151 feat(ci): add grafana link to annotations
  enterprise/dev/ci/scripts/annotate.sh
Labels: ci, team/devx, cla-signed

#38145 JetBrains: Prepare for an alpha release
  client/jetbrains/CHANGELOG.md
  client/jetbrains/README.md
  client/jetbrains/gradle.properties
  client/jetbrains/scripts/release.sh
Labels: cla-signed

#38155 Add "yarn watch" to docs
  client/jetbrains/README.md
Labels: cla-signed

#38152 fix(buildchecker): do not consider cron builds
  dev/buildchecker/checker.go
  dev/buildchecker/checker_test.go
  dev/buildchecker/failures.go
Labels: ci, team/devx, cla-signed

#36915 [SG-36350] Accessibility: Global `Menu`: Focus isn't correctly captured when menus are opened
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.test.tsx
  client/web/src/nav/NavBar/NavDropdown.tsx
  client/wildcard/src/components/Menu/MenuList.tsx
  client/wildcard/src/components/Popover/README.md
  client/wildcard/src/components/Popover/components/floating-panel/FloatingPanel.tsx
  client/wildcard/src/components/Popover/components/popover-content/PopoverContent.tsx
  client/wildcard/src/components/Popover/tether/services/tether-render.ts
  client/wildcard/src/components/Popover/tether/services/types.ts
Labels: team/frontend-platform, gitstart, cla-signed

#38027 codeintel: allow listing deleted LSIF uploads reconstructed from audit logs in graphql layer
  client/web/src/enterprise/codeintel/uploads/hooks/queryLsifUploadsByRepository.tsx
  client/web/src/enterprise/codeintel/uploads/hooks/queryLsifUploadsList.tsx
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/uploads.go
  internal/codeintel/stores/dbstore/helpers_test.go
  internal/codeintel/stores/dbstore/uploads.go
  internal/codeintel/stores/dbstore/uploads_test.go
  internal/codeintel/uploads/internal/store/store_commits_test.go
  internal/codeintel/uploads/internal/store/store_uploads.go
  internal/codeintel/uploads/internal/store/store_uploads_test.go
  internal/codeintel/uploads/shared/types.go
  internal/database/schema.json
  migrations/frontend/1655226733/down.sql
  migrations/frontend/1655226733/metadata.yaml
  migrations/frontend/1655226733/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/language-platform-and-navigation

#38178 Bump sourcegraph/log
  go.mod
  go.sum
  lib/go.mod
  lib/go.sum
Labels: cla-signed

#38185 Revert "Search backend: use client logger where applicable"
  dev/sg/linters/linters.go
  internal/search/alert/observer.go
  internal/search/alert/observer_test.go
  internal/search/job/jobutil/alert.go
  internal/search/job/jobutil/repo_pager_job.go
  internal/search/job/jobutil/sub_repo_perms_job.go
  internal/search/job/jobutil/sub_repo_perms_job_test.go
  internal/search/repos/repos.go
  internal/search/run/repo_has_file.go
  internal/search/searcher/search.go
  internal/search/structural/structural.go
  internal/search/textsearch/textsearch_test.go
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
  internal/search/zoekt/symbol_search.go
Labels: cla-signed

#38186 mod: update github.com/sourcegraph/log
  go.mod
  go.sum
  lib/go.mod
  lib/go.sum
Labels: cla-signed

#38188 Update instructions for the SAML allowGroups configuration
  doc/admin/auth/saml/index.md
Labels: cla-signed, team/iam

#38189 graphqlbackend: standardize *schemaResolver instantiation
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/saved_searches_test.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_test.go
  cmd/frontend/graphqlbackend/settings_cascade.go
  cmd/frontend/graphqlbackend/site_admin_test.go
Labels: cla-signed

#38190 rockskip: Remove print statement
  enterprise/internal/rockskip/search.go
Labels: cla-signed

#38080 [SG-25227] Update Storybook stories to use Component Story Format
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetCheckStatusCell.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetReviewStatusCell.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.story.tsx
  client/web/src/enterprise/batches/list/BatchChangeNode.story.tsx
  client/web/src/enterprise/batches/list/BatchChangesListIntro.story.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx
  client/web/src/enterprise/batches/preview/list/ChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/HiddenChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/PreviewList.story.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/storyData.ts
  client/web/src/enterprise/batches/settings/AddCredentialModal.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.story.tsx
  client/web/src/site-admin/webhooks/MessagePanel.story.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#37981 Backend: create unified `lib/group` package
  enterprise/cmd/frontend/internal/compute/streaming/compute.go
  internal/search/streaming/stream_test.go
  lib/group/group.go
  lib/group/group_test.go
  lib/group/limiter.go
  lib/group/ordered.go
  lib/group/ordered_test.go
  lib/group/result.go
  lib/group/result_test.go
  lib/group/stream.go
  lib/group/stream_test.go
Labels: cla-signed

#38193 Fix duplicate history entry on selecting lines
  CHANGELOG.md
  client/web/src/repo/blob/Blob.tsx
Labels: cla-signed

#37620 Re-enable dependency search integration tests
  dev/gqltest/search_test.go
  internal/gqltestutil/policies.go
  internal/gqltestutil/repository.go
Labels: cla-signed

#38173 gitserver: Ensure we always update clone_status
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: team/repo-management, cla-signed

#38063 web: drop Datadog RUM support
  client/web/dev/utils/environment-config.ts
  client/web/src/components/ErrorBoundary.tsx
  client/web/src/jscontext.ts
  client/web/src/monitoring/datadog/datadogClient.ts
  client/web/src/monitoring/datadog/initDatadog.ts
  client/web/src/monitoring/index.ts
  client/web/src/monitoring/initMonitoring.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/app/ui/app.html
  package.json
  schema/schema.go
  schema/site.schema.json
  yarn.lock
Labels: team/frontend-platform, cla-signed

#38174 JetBrains: Remove leftover console.log
  client/jetbrains/webview/src/telemetry/EventLogger.ts
Labels: cla-signed, jetbrains-ide

#38112 Revert "Revert "Code Insights: Add pings for the standalone insight page" (#37865)"
  client/web/src/enterprise/insights/components/form/hooks/useForm.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/actions/CodeInsightIndependentPageActions.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/dashboard-pills/StandaloneInsightDashboardPills.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
  client/web/src/enterprise/insights/pings/use-code-insight-view-pings.ts
  doc/dev/background-information/insights/code_insights_pings.md
  internal/types/types.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
  package.json
  yarn.lock
Labels: cla-signed

#38202 codeintel resolvers: fix duplicate import of dbstore
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
Labels: cla-signed

#38175 Fix scrolling first selected line into view
  CHANGELOG.md
  client/codeintellify/src/helpers.ts
  client/codeintellify/src/hoverifier.ts
Labels: cla-signed

#38210 authz: Add more perforce permissions tests
  enterprise/internal/authz/perforce/protects.go
  enterprise/internal/authz/perforce/protects_test.go
  internal/authz/sub_repo_perms.go
Labels: team/repo-management, cla-signed

#38204 Avoid duplicate history entries for the same line position
  CHANGELOG.md
  client/web/src/repo/blob/Blob.tsx
Labels: cla-signed

#37619 policies: update matched repos right after policy is created
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
Labels: cla-signed

#38224 Webapp: Fix type re-exports in code insights components
  client/web/src/enterprise/insights/components/form/index.ts
  client/web/src/enterprise/insights/hooks/index.ts
Labels: cla-signed

#37776 Only redact URLs on Sourcegraph.com for paths that start with /github…
  client/web/src/tracking/util.test.ts
  client/web/src/tracking/util.ts
  internal/usagestats/event_handlers.go
  internal/usagestats/event_handlers_test.go
Labels: cla-signed

#38220 JetBrains: Make resize padding macOS-only and remove bottom padding
  client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
Labels: cla-signed, jetbrains-ide

#38238 codeintel: coalesce null columns from partial audit logs aggregation
  internal/codeintel/stores/dbstore/uploads.go
  internal/codeintel/stores/dbstore/uploads_test.go
  internal/codeintel/uploads/internal/store/store_commits_test.go
  internal/codeintel/uploads/internal/store/store_uploads.go
  internal/codeintel/uploads/internal/store/store_uploads_test.go
Labels: cla-signed, team/language-platform-and-navigation

#38138 core workflow: reserve temporary setting name
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/user/settings/UserSettingsSidebar.tsx
Labels: cla-signed

#38109 Insights/reestablish compute changes
  enterprise/internal/compute/client/compute_text_client.go
  enterprise/internal/compute/client/compute_text_client_test.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/work_handler_test.go
  enterprise/internal/insights/background/queryrunner/worker.go
  enterprise/internal/insights/query/capture_group_executor.go
  enterprise/internal/insights/query/streaming/decoder.go
  enterprise/internal/insights/query/streaming/search.go
  enterprise/internal/insights/types/types.go
Labels: cla-signed

#37113 Add notification to set project URL
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/NotificationActivity.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SourcegraphApplicationService.java
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#38251 insights: remove Just in time conversion check on backfilled_at
  enterprise/internal/insights/store/insight_store.go
Labels: cla-signed

#38244 [a11y] notepad: make into a landmark
  client/web/src/search/Notepad.test.tsx
  client/web/src/search/Notepad.tsx
Labels: cla-signed

#38257 codemirror: Fix suggestions snippet behavior
  client/search-ui/src/input/extensions/completion.ts
Labels: cla-signed

#38259 dev/pr-auditor: run on pull_request_target
  .github/workflows/pr-auditor.yml
  dev/pr-auditor/batch-changes/pr-auditor-patch.yml
  dev/pr-auditor/batch-changes/pr-auditor-rollout.yml
Labels: cla-signed

#38057 Insights/map type query builder
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/query/querybuilder/builder.go
  enterprise/internal/insights/query/querybuilder/builder_test.go
Labels: cla-signed

#38121 Correcting punctuation in test email
  cmd/frontend/graphqlbackend/send_test_email.go
Labels: cla-signed

#38110 migrator: Check previous instance version before making schema changes
  cmd/frontend/backend/versions.go
  cmd/frontend/backend/versions_test.go
  cmd/frontend/internal/cli/serve_cmd.go
  doc/dev/background-information/sg/reference.md
  internal/database/migration/cliutil/downto.go
  internal/database/migration/cliutil/undo.go
  internal/database/migration/cliutil/up.go
  internal/database/migration/cliutil/upto.go
  internal/database/migration/runner/runner.go
  internal/oobmigration/validate.go
  internal/version/upgradestore/errors.go
  internal/version/upgradestore/store.go
  internal/version/upgradestore/store_test.go
  internal/version/upgradestore/upgrade.go
  internal/version/upgradestore/upgrade_test.go
Labels: cla-signed, rfc-697, rfc-697-qol

#37909 frontend: add health check
  cmd/frontend/internal/cli/checks.go
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/router/router.go
  internal/check/check.go
Labels: cla-signed

#38084 PageHeader: Update to support `@mdi/js`
  client/vscode/src/webview/search-panel/RepoView.tsx
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
  client/web/src/enterprise/searchContexts/CreateSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/EditSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListPage.tsx
  client/web/src/extensions/ExtensionsAreaHeader.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/insights/Icons.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/org/settings/codeHosts/ConnectGitHubAppPage.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/createActions.ts
  client/wildcard/src/components/Icon/Icon.tsx
  client/wildcard/src/components/PageHeader/Breadcrumb/Breadcrumb.tsx
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
  client/wildcard/src/components/index.ts
Labels: team/frontend-platform, cla-signed

#38277 Add yarn generate to sg start web-standalone
  sg.config.yaml
Labels: team/frontend-platform, cla-signed

#38280 Revert "PageHeader: Update to support `@mdi/js`"
  client/vscode/src/webview/search-panel/RepoView.tsx
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
  client/web/src/enterprise/searchContexts/CreateSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/EditSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListPage.tsx
  client/web/src/extensions/ExtensionsAreaHeader.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/insights/Icons.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/org/settings/codeHosts/ConnectGitHubAppPage.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/createActions.ts
  client/wildcard/src/components/Icon/Icon.tsx
  client/wildcard/src/components/PageHeader/Breadcrumb/Breadcrumb.tsx
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
  client/wildcard/src/components/index.ts
Labels: team/frontend-platform, cla-signed

#38272 Upgrade p4 fusion
  cmd/gitserver/p4-fusion-install-alpine.sh
Labels: cla-signed

#38264 Insights/clean bad merge
  enterprise/internal/insights/background/historical_enqueuer.go
Labels: cla-signed

#38142 search: remove onboarding tour
  client/search-ui/src/results/sidebar/SearchSidebar.tsx
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/shared/src/settings/temporary/migrateLocalStorageToTemporarySettings.ts
  client/shared/src/testing/accessibility.ts
  client/web/.stylelintrc.json
  client/web/src/Layout.module.scss
  client/web/src/SourcegraphWebApp.scss
  client/web/src/communitySearchContexts/CommunitySearchContextPage.story.tsx
  client/web/src/integration/code-monitoring.test.ts
  client/web/src/integration/search-onboarding.test.ts
  client/web/src/integration/search.test.ts
  client/web/src/search/FeatureTour.module.scss
  client/web/src/search/ShepherdTour.scss
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/input/SearchOnboardingTour.module.scss
  client/web/src/search/input/SearchOnboardingTour.tsx
  client/web/src/search/input/tour-options.ts
  client/web/src/search/render-branded-to-string.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/useFeatureTour.ts
  client/web/src/stores/experimentalFeatures.ts
  client/web/src/user/settings/UserSettingsSidebar.tsx
  package.json
  schema/schema.go
  schema/settings.schema.json
  yarn.lock
Labels: cla-signed

#37452 executors: Forward git to gitserver directly
  enterprise/cmd/frontend/internal/executorqueue/gitserverproxy.go
  enterprise/cmd/frontend/internal/executorqueue/gitserverproxy_test.go
  enterprise/cmd/frontend/internal/executorqueue/init.go
  enterprise/cmd/frontend/internal/executorqueue/mocks_test.go
  enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
  enterprise/cmd/frontend/internal/executorqueue/reverseproxy.go
Labels: cla-signed

#38282 Fix VPC for executors
  enterprise/cmd/executor/vm-image/executor.json
Labels: cla-signed

#38208 JetBrains: Change shortcuts
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#38194 Simplify blob view line highlighting logic
  client/web/src/repo/blob/Blob.tsx
Labels: cla-signed

#38250 batches(gitlab) handle time with numeric timezone in webhook
  CHANGELOG.md
  internal/extsvc/gitlab/time.go
  internal/extsvc/gitlab/time_test.go
Labels: cla-signed

#38237 insights: update insights docs
  doc/code_insights/explanations/automatically_generated_data_series.md
  doc/code_insights/explanations/current_limitations_of_code_insights.md
  doc/code_insights/how-tos/filtering_an_insight.md
Labels: cla-signed

#38273 Accessibility: Fix `ButtonLink` blocking focus
  client/wildcard/src/components/ButtonLink/ButtonLink.tsx
Labels: team/frontend-platform, cla-signed

#38106 display banner when creating batch change from search
  client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx
  client/web/src/enterprise/batches/create/ConfigurationForm.tsx
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/create/SearchTemplatesBanner.module.scss
  client/web/src/enterprise/batches/create/SearchTemplatesBanner.story.tsx
  client/web/src/enterprise/batches/create/SearchTemplatesBanner.tsx
  client/web/src/enterprise/batches/create/useSearchTemplate.ts
Labels: team/batchers, cla-signed

#38286 JetBrains: Fix Linux focus issues
  client/jetbrains/src/main/java/com/sourcegraph/find/FindService.java
Labels: cla-signed, jetbrains-ide

#38283 PageHeader: Update to support @mdi/js
  client/vscode/src/webview/search-panel/RepoView.tsx
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
  client/web/src/enterprise/searchContexts/CreateSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/EditSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListPage.tsx
  client/web/src/extensions/ExtensionsAreaHeader.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/insights/Icons.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/org/settings/codeHosts/ConnectGitHubAppPage.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/search/results/CreateActionsMenu.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/createActions.ts
  client/wildcard/src/components/Icon/Icon.tsx
  client/wildcard/src/components/PageHeader/Breadcrumb/Breadcrumb.tsx
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
  client/wildcard/src/components/index.ts
Labels: team/frontend-platform, cla-signed

#38252 Code Insights: Render insight that are rendered in visible viewport area
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
Labels: bug, webapp, team/code-insights, cla-signed

#38172 JetBrains: 2.0.0-alpha.1 release
  client/jetbrains/README.md
  client/jetbrains/gradle.properties
Labels: cla-signed

#38298 Revert "[SG-36350] Accessibility: Global `Menu`: Focus isn't correctly captured when menus are opened"
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.test.tsx
  client/web/src/nav/NavBar/NavDropdown.tsx
  client/wildcard/src/components/Menu/MenuList.tsx
  client/wildcard/src/components/Popover/README.md
  client/wildcard/src/components/Popover/components/floating-panel/FloatingPanel.tsx
  client/wildcard/src/components/Popover/components/popover-content/PopoverContent.tsx
  client/wildcard/src/components/Popover/tether/services/tether-render.ts
  client/wildcard/src/components/Popover/tether/services/types.ts
Labels: team/frontend-platform, cla-signed

#38294 insights: support single snapshot point for compute type insights
  enterprise/internal/insights/background/insight_enqueuer.go
  enterprise/internal/insights/background/insight_enqueuer_test.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
Labels: cla-signed

#38300 Accessibility: Add `focus-visible` outline to menus
  client/wildcard/src/components/Menu/MenuList.module.scss
  client/wildcard/src/components/Menu/MenuList.tsx
  client/wildcard/src/components/NavMenu/__snapshots__/NavMenu.test.tsx.snap
Labels: team/frontend-platform, cla-signed

#38297 insights: update change log for just in time insight conversion
  CHANGELOG.md
Labels: cla-signed

#38258 Add warning to cloud pages regarding personal code
  doc/cloud/access_tokens_on_cloud.md
  doc/cloud/cloud_ent_on-prem_comparison.md
  doc/cloud/getting_started_on_cloud.md
  doc/cloud/index.md
  doc/cloud/indexing_open_source_code.md
  doc/cloud/notifications_on_cloud.md
  doc/cloud/organizations/adding_your_org_repos_to_cloud.md
  doc/cloud/organizations/code_visibility_teams_sourcegraph_cloud.md
  doc/cloud/organizations/creating_your_org_on_cloud.md
  doc/cloud/organizations/deleting_org_on_cloud.md
  doc/cloud/organizations/get_started_with_orgs_cloud.md
  doc/cloud/organizations/index.md
  doc/cloud/organizations/inviting_users_to_org_on_sourcegraph_cloud.md
  doc/cloud/organizations/searching_org_repo_sourcegraph_cloud.md
  doc/index.md
Labels: cla-signed, team/iam

#37644 squirrel: Fix some top-level symbols being considered locals
  cmd/symbols/squirrel/languages.go
  cmd/symbols/squirrel/local_code_intel.go
  cmd/symbols/squirrel/local_code_intel_test.go
Labels: cla-signed

#38191 rockskip: Update status docs
  doc/code_intelligence/explanations/rockskip.md
Labels: cla-signed

#38308 search: when clicking a dynamic filter, only log the kind
  client/search-ui/src/results/sidebar/FilterLink.test.tsx
  client/search-ui/src/results/sidebar/FilterLink.tsx
  client/search-ui/src/results/sidebar/SearchSidebar.tsx
Labels: cla-signed

#38253 [ally] notebook: fix arc toolkit issues
  client/web/src/notebooks/blocks/NotebookBlock.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
Labels: cla-signed

#38287 db: Improve performance of external service sync failure message
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1657106983_faster_failure_msg_query/down.sql
  migrations/frontend/1657106983_faster_failure_msg_query/metadata.yaml
  migrations/frontend/1657106983_faster_failure_msg_query/up.sql
  migrations/frontend/1657107627_drop_duplicate_index_sync_jobs_state/down.sql
  migrations/frontend/1657107627_drop_duplicate_index_sync_jobs_state/metadata.yaml
  migrations/frontend/1657107627_drop_duplicate_index_sync_jobs_state/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#38108 [codeintel] RFC 619: refactor of uploads commitgraph background jobs
  enterprise/cmd/worker/internal/codeintel/fresh/commitgraph_updater_job.go
  enterprise/cmd/worker/internal/codeintel/fresh/upload_janitor.go
  internal/codeintel/autoindexing/internal/store/store.go
  internal/codeintel/autoindexing/internal/store/store_indexes.go
  internal/codeintel/autoindexing/internal/store/store_indexes_test.go
  internal/codeintel/autoindexing/internal/store/store_sourced_commits.go
  internal/codeintel/autoindexing/internal/store/store_sourced_commits_test.go
  internal/codeintel/autoindexing/observability.go
  internal/codeintel/autoindexing/service.go
  internal/codeintel/uploads/background/cleanup/iface.go
  internal/codeintel/uploads/background/cleanup/mocks_test.go
  internal/codeintel/uploads/background/cleanup/unknown_commits.go
  internal/codeintel/uploads/background/cleanup/unknown_commits_test.go
  internal/codeintel/uploads/background/commitgraph/iface.go
  internal/codeintel/uploads/background/commitgraph/init.go
  internal/codeintel/uploads/background/commitgraph/mocks_test.go
  internal/codeintel/uploads/background/commitgraph/operations.go
  internal/codeintel/uploads/background/commitgraph/updater.go
  internal/codeintel/uploads/background/commitgraph/updater_job.go
  internal/codeintel/uploads/background/commitgraph/updater_job_test.go
  internal/codeintel/uploads/iface.go
  internal/codeintel/uploads/init.go
  internal/codeintel/uploads/internal/lsifstore/lsifstore.go
  internal/codeintel/uploads/internal/lsifstore/lsifstore_delete.go
  internal/codeintel/uploads/internal/lsifstore/lsifstore_delete_test.go
  internal/codeintel/uploads/internal/lsifstore/observability.go
  internal/codeintel/uploads/internal/store/observability.go
  internal/codeintel/uploads/internal/store/scan.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/internal/store/store_commits.go
  internal/codeintel/uploads/internal/store/store_commits_test.go
  internal/codeintel/uploads/internal/store/store_dumps.go
  internal/codeintel/uploads/internal/store/store_dumps_test.go
  internal/codeintel/uploads/internal/store/store_repositories.go
  internal/codeintel/uploads/internal/store/store_repositories_test.go
  internal/codeintel/uploads/internal/store/store_uploads.go
  internal/codeintel/uploads/internal/store/store_uploads_test.go
  internal/codeintel/uploads/internal/store/types.go
  internal/codeintel/uploads/observability.go
  internal/codeintel/uploads/service.go
  internal/codeintel/uploads/shared/types.go
  mockgen.test.yaml
Labels: cla-signed

#38322 migration: fix sg logger scope, add success messages to up and validate
  dev/sg/sg_db.go
  dev/sg/sg_migration.go
  doc/dev/background-information/sg/reference.md
  internal/database/migration/cliutil/up.go
  internal/database/migration/cliutil/validate.go
Labels: cla-signed

#38327 dev/sg: fix enterprise-e2e set with env hackery
  sg.config.yaml
Labels: cla-signed

#38338 adding missing interface
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/worker/internal/codeintel/fresh/commitgraph_updater_job.go
  enterprise/cmd/worker/internal/codeintel/fresh/upload_janitor.go
  internal/codeintel/uploads/init.go
  internal/codeintel/uploads/service.go
  internal/codeintel/uploads/shared/types.go
Labels: cla-signed

#38331 search frontend: highlight queries accurately everywhere
  client/branded/src/global-styles/code.scss
  client/branded/src/global-styles/colors.scss
  client/search-ui/src/components/SyntaxHighlightedSearchQuery.tsx
  client/search-ui/src/components/__snapshots__/SyntaxHighlightedSearchQuery.test.tsx.snap
  client/search-ui/src/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/search-ui/src/results/sidebar/__snapshots__/FilterLink.test.tsx.snap
  client/web/src/search/panels/__snapshots__/RecentSearchesPanel.test.tsx.snap
  client/web/src/search/panels/__snapshots__/RepositoriesPanel.test.tsx.snap
Labels: cla-signed

#38343 search: fix duplicate results in lucky search
  internal/search/job/jobutil/feeling_lucky_search_job.go
  internal/search/job/jobutil/feeling_lucky_search_job_test.go
Labels: cla-signed

#38261 insights: Generate compute insights for live preview
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/query/compute_executor.go
  enterprise/internal/insights/query/querybuilder/builder.go
  enterprise/internal/insights/resolvers/live_preview_resolvers.go
Labels: cla-signed

#38226 VSCE: Add open-vsx release step
  client/vscode/CHANGELOG.md
  client/vscode/CONTRIBUTING.md
  client/vscode/scripts/publish.ts
  client/vscode/scripts/release.ts
Labels: cla-signed

#38349 Backend: add scoped `log.Field` encoder
  internal/trace/fields.go
Labels: cla-signed

#38351 Search backend: make filename order deterministic
  internal/search/query/helpers.go
Labels: cla-signed

#37894 search: expose V3 for query interpretation
  cmd/frontend/graphqlbackend/schema.graphql
  internal/search/run/run.go
  internal/search/run/run_test.go
Labels: cla-signed

#38268 monitoring: rename Cloud SaaS to IAM
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/frontend.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed, team/iam

#38246 Search backend: bump zoekt and use chunk matches
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_test.go
  cmd/searcher/internal/search/hybrid.go
  go.mod
  go.sum
  internal/search/symbol/symbol.go
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
  internal/search/zoekt/zoekt.go
Labels: cla-signed

#38199 web: enable `storyStoreV7` in Storybook
  client/storybook/src/main.ts
  client/storybook/src/preview.ts
  client/web/src/components/WebStory.tsx
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/savedSearches/SavedSearchForm.story.tsx
  client/web/src/search/home/SearchPage.story.tsx
  jest.config.base.js
  package.json
  yarn.lock
Labels: team/frontend-platform, cla-signed

#38196 authz: support configurable parallelism of perms syncing
  CHANGELOG.md
  doc/admin/repo/permissions.md
  enterprise/cmd/repo-updater/internal/authz/metrics.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/cmd/repo-updater/internal/authz/request_queue.go
  internal/conf/parse.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam

#38360 Search: disable flaky integration test
  dev/gqltest/search_test.go
Labels: cla-signed

#38369 web: disable flaky E2E test
  client/web/src/end-to-end/frontend-platform/theme-switcher.test.ts
Labels: team/frontend-platform, ci, ci/flake, cla-signed

#37292 Accessibility: Improve tips for crossing header styles
  client/wildcard/src/components/Typography/Typography.story.tsx
  doc/dev/background-information/web/accessibility/detailed-checklist.md
Labels: accessibility, docs, team/frontend-platform, cla-signed

#38216 Accessibility: Add polite notifications to loading spinner
  client/branded/src/components/__snapshots__/LoaderInput.test.tsx.snap
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/shared/src/actions/__snapshots__/ActionItem.test.tsx.snap
  client/shared/src/components/activation/__snapshots__/ActivationChecklist.test.tsx.snap
  client/shared/src/hover/__snapshots__/HoverOverlay.test.tsx.snap
  client/web/src/components/__snapshots__/LoaderButton.test.tsx.snap
  client/web/src/components/externalServices/__snapshots__/ExternalServiceForm.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/NewProductSubscriptionPaymentSection.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsEditProductSubscriptionPage.test.tsx.snap
  client/wildcard/src/components/Form/Input/Input.test.tsx
  client/wildcard/src/components/Form/Input/__snapshots__/Input.test.tsx.snap
  client/wildcard/src/components/LoadingSpinner/LoadingSpinner.tsx
Labels: team/frontend-platform, cla-signed

#38375 Use global search query syntax highlighting classes for query input
  client/search-ui/src/components/SyntaxHighlightedSearchQuery.tsx
  client/search-ui/src/input/CodeMirrorQueryInput.module.scss
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/shared/src/search/query/decoratedToken.ts
Labels: cla-signed

#38247 [SG-35263] Collapsible sections in code-intel index pages don't explain what they contain
  client/web/src/components/ExecutionLogEntry.tsx
  client/web/src/components/LogOutput.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#37919 [SG-36606] Accessibility: Provide screen reader context for sublists of ref panel
  client/branded/src/components/panel/views/HierarchicalLocationsView.tsx
  client/branded/src/components/panel/views/HierarchicalLocationsViewButton.tsx
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/web/src/codeintel/ReferencesPanel.tsx
Labels: team/frontend-platform, cla-signed

#38209 insights: add building block for `sg insights` tool
  dev/sg/main.go
  dev/sg/sg_insights.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#38389 HK: Remove @types from dependencies and move them to devDependencies
  package.json
Labels: team/frontend-platform, cla-signed

#38307 gitserver: update janitor, so it sets repo sizes not just once, but during every run
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/server.go
Labels: cla-signed

#38336 search: Show token information for operators (CodeMirror)
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/search-ui/src/input/extensions/completion.ts
  client/search-ui/src/input/extensions/parsedQuery.ts
  client/shared/src/search/query/parser.ts
Labels: cla-signed

#38234 JetBrains add settings icons to header
  client/jetbrains/README.md
  client/jetbrains/src/main/java/com/sourcegraph/Icons.java
  client/jetbrains/src/main/java/com/sourcegraph/config/NotificationActivity.java
  client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupDialog.java
  client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/FindService.java
  client/jetbrains/src/main/java/com/sourcegraph/find/HeaderPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/PreviewPanel.java
  client/jetbrains/src/main/resources/META-INF/plugin.xml
  client/jetbrains/src/main/resources/icons/gearPlain.svg
  client/jetbrains/src/main/resources/icons/gearPlain_dark.svg
  client/jetbrains/src/main/resources/icons/sourcegraphLogo.png
  client/jetbrains/src/main/resources/icons/sourcegraphLogo@2x.png
  client/jetbrains/standalone/src/index.html
  client/jetbrains/webview/src/search/input/JetBrainsSearchBox.module.scss
Labels: cla-signed

#37767 ci: remove Junit reports for Go
  dev/ci/go-test.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: ci, team/devx, cla-signed

#38403 fix(sg): restrict grafana link to only render on main
  enterprise/dev/ci/scripts/annotate.sh
Labels: sg, ci, team/devx, cla-signed

#38409 sg: fix sg start oss
  sg.config.yaml
Labels: bug, sg, team/devx, cla-signed

#38205 [SG-35180] Accessibility: Screen reader navigation for notebooks
  client/web/src/notebooks/notebookPage/NotebookTitle.module.scss
  client/web/src/notebooks/notebookPage/NotebookTitle.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#38385 Remove CodeQL workflow
  .github/workflows/codeql.yml
Labels: cla-signed

#38181 Add a few more batch changes templates
  client/web/src/enterprise/batches/batch-spec/edit/library/LibraryPane.tsx
  client/web/src/enterprise/batches/batch-spec/edit/library/many-comby.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/monorepo-dynamic.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/sed.batch.yaml
Labels: cla-signed

#38197 [SG-35262] Upload/Index timeline time between states is not explained as such
  client/web/src/components/Timeline.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#38022 [SG-35295] Tree page (post-redesign): Navigation links are reported as buttons
  client/web/src/repo/tree/TreeTabList.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#38392 JetBrains: Decrease popup default size
  client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
Labels: cla-signed

#38313 Code Insights: Fetch only needed fields in insight view data (chart content query)
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/core/backend/gql-backend/gql/GetInsightView.ts
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
  client/web/src/integration/insights/fixtures/calculated-insights.ts
Labels: bug, webapp, team/code-insights, cla-signed

#38354 search: add generated query constructor
  internal/search/job/jobutil/feeling_lucky_search_job.go
Labels: cla-signed

#38355 search: make lucky generator return autoQuery type
  internal/search/job/jobutil/feeling_lucky_search_job.go
  internal/search/job/jobutil/feeling_lucky_search_job_test.go
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/one_of_many_patterns_as_lang.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type_multi_patterns.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type_with_expression.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/single_pattern_as_lang.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/trigger_unordered_patterns.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/trigger_unquoted_rule.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/two_basic_jobs.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/type_and_lang_multi_rule.golden
Labels: cla-signed

#38431 search ui: disable homepage panels
  CHANGELOG.md
  client/web/src/search/home/SearchPageFooter.tsx
  client/web/src/stores/experimentalFeatures.ts
  schema/settings.schema.json
Labels: cla-signed

#38436 Update admin-analytics background job cache interval
  internal/adminanalytics/cache.go
Labels: cla-signed

#38357 search: separate static vs runtime construction in lucky search
  internal/search/job/jobutil/feeling_lucky_search_job.go
  internal/search/job/jobutil/feeling_lucky_search_job_test.go
Labels: cla-signed

#38437 search: Add placeholder to fallback query input
  client/search-ui/src/input/LazyMonacoQueryInput.module.scss
  client/search-ui/src/input/LazyMonacoQueryInput.tsx
  client/shared/src/components/CodeMirrorEditor.ts
Labels: cla-signed

#38358 search: explicitly enclose regex string output in /.../
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/background/insight_enqueuer_test.go
  enterprise/internal/insights/query/querybuilder/builder_test.go
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/one_of_many_patterns_as_lang.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type_multi_patterns.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type_with_expression.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/trigger_unordered_patterns.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/two_basic_jobs.golden
  internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/type_and_lang_multi_rule.golden
  internal/search/query/printer.go
  internal/search/query/printer_test.go
Labels: cla-signed

#38386 search: Update supported languages in lang: filter suggestions
  client/shared/src/search/query/languageFilter.ts
Labels: cla-signed
