Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-02, with the labels that each got.

#30446 workerutil: Turn off logs in unit tests
  internal/workerutil/main_test.go
Labels: dx, cla-signed

#30075 Merge `ButtonTooltip` into `Button`
  client/web/src/components/ButtonTooltip.tsx
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
  client/web/src/enterprise/batches/create/workspaces-preview/PreviewPrompt.tsx
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.tsx
  client/wildcard/src/components/Button/Button.module.scss
  client/wildcard/src/components/Button/Button.test.tsx
  client/wildcard/src/components/Button/Button.tsx
  client/wildcard/src/components/Button/story/Button.story.tsx
Labels: wildcard-v2, cla-signed, wildcard-v2/button

#30449 go test: Reduce log output
  internal/database/migration/runner/logger.go
  internal/database/migration/runner/options.go
  internal/database/migration/runner/run.go
  internal/database/migration/runner/runner.go
  internal/workerutil/dbworker/resetter.go
  internal/workerutil/logger.go
  internal/workerutil/main_test.go
  internal/workerutil/worker.go
Labels: dx, cla-signed

#30456 migrations: Keep user-facing naming consistent
  dev/sg/sg_migration.go
  internal/database/migration/cliutil/downto.go
  internal/database/migration/cliutil/flags.go
Labels: cla-signed

#30419 Sub-repo permissions: move search filtering to a stream wrapper
  cmd/frontend/graphqlbackend/search_results.go
Labels: cla-signed

#30467 notebooks: log additional events and enable stories snapshotting
  client/web/src/search/notebook/CreateNotebookPage.tsx
  client/web/src/search/notebook/DeleteNotebookModal.tsx
  client/web/src/search/notebook/NotebookTitle.tsx
  client/web/src/search/notebook/SearchNotebook.story.tsx
  client/web/src/search/notebook/SearchNotebook.tsx
  client/web/src/search/notebook/SearchNotebookPage.tsx
  client/web/src/search/notebook/SearchNotebookPageHeaderActions.tsx
  client/web/src/search/notebook/listPage/SearchNotebooksList.tsx
  client/web/src/search/notebook/listPage/SearchNotebooksListPage.story.tsx
  client/web/src/search/notebook/listPage/SearchNotebooksListPage.tsx
Labels: cla-signed

#30232 Add support for NPM credentials.
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  internal/extsvc/npm/npm.go
  internal/extsvc/npm/npm_test.go
  internal/repos/npm_packages.go
  internal/types/secret.go
  internal/types/secret_test.go
  schema/npm-packages.schema.json
  schema/schema.go
Labels: cla-signed

#30410 Code Insights: Add template section to the getting started page
  client/web/src/enterprise/insights/pages/getting-started/CodeInsightsGettingStartedPage.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-examples/CodeInsightsExamples.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-temlates/CodeInsightsTemplates.module.scss
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-temlates/CodeInsightsTemplates.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-temlates/constants.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/capture-insigh-url-parsers/capture-insight-url-parsers.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/search-insight-url-parsers/search-insight-url-parsers.ts
  client/wildcard/src/components/Tabs/Tabs.tsx
Labels: team/code-insights, cla-signed

#30329 enterprise: Special case handling of internal repo in FetchRepoPerms
  enterprise/internal/authz/authz.go
  enterprise/internal/authz/github/authz.go
  enterprise/internal/authz/github/authz_test.go
  enterprise/internal/authz/github/client.go
  enterprise/internal/authz/github/github.go
  enterprise/internal/authz/github/github_test.go
Labels: cla-signed

#30474 Use wildcard Link component instead of native a tag
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-examples/CodeInsightsExamples.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-temlates/CodeInsightsTemplates.tsx
Labels: merge-on-any-approve, cla-signed

#30397 Fix long lines wrap in split diff mode
  client/web/src/components/diff/Lines.module.scss
  client/web/src/components/diff/Lines.tsx
Labels: team/frontend-platform, cla-signed

#30473 internal: Add comments for generated metric names
  internal/extsvc/bitbucketcloud/client.go
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/github/common.go
  internal/extsvc/gitlab/client.go
  internal/httpcli/client.go
  internal/search/backend/zoekt.go
Labels: cla-signed

#30458 migrations: Fix testdata naming
  internal/database/migration/definition/testdata/cycle-traversal/10003/metadata.yaml
  internal/database/migration/definition/testdata/cycle-traversal/10004/metadata.yaml
Labels: cla-signed

#30455 migrations: Remove `Definitions.First` in favor of `Root`
  internal/database/connections/live/migration_test.go
  internal/database/migration/definition/definition.go
Labels: cla-signed

#30480 codeintel: add basic queue duration field to upload worker telemetry
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
Labels: team/code-intelligence, cla-signed, observability

#30457 migrations: Remove unused `Count` method
  internal/database/migration/definition/definition.go
Labels: cla-signed

#30478 ci-flake: skip faulty code monitor tests
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
Labels: ci/flake, cla-signed

#30479 executor: quote env vars if passed as args & contain whitespace
  enterprise/cmd/executor/internal/command/docker.go
  enterprise/cmd/executor/internal/command/docker_test.go
  enterprise/cmd/executor/internal/command/firecracker.go
  enterprise/cmd/executor/internal/command/firecracker_test.go
  enterprise/cmd/executor/internal/command/util.go
  enterprise/cmd/executor/internal/command/util_test.go
Labels: team/code-intelligence, code-intelligence-platform, cla-signed

#30485 Add docs on how to deploy executor image to k8s/cloud
  doc/dev/how-to/deploy_executor_image.md
  doc/dev/how-to/index.md
  doc/dev/index.md
Labels: cla-signed

#30443 Convert `gitserver.DefaultClient` to an interface
  cmd/frontend/internal/app/ui/raw_test.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/mock_client.go
  internal/gitserver/proxy.go
  internal/repos/gitolite.go
  internal/vcs/git/main_test.go
Labels: cla-signed

#30491 use system python
  .tool-versions
Labels: dx, cla-signed

#29308 search: Enable sub-repo filtering
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  dev/gqltest/README.md
  dev/gqltest/search_test.go
  internal/authz/sub_repo_perms.go
  internal/authz/sub_repo_perms_test.go
  internal/gqltestutil/repository.go
  internal/search/alert/observer.go
  internal/search/commit/commit_new.go
  internal/search/result/commit.go
  internal/search/result/file.go
  internal/search/unindexed/unindexed.go
Labels: team/repo-management, cla-signed, PD-503

#30500 add a minimal amount of tracing to search jobs
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/commit/commit_new.go
  internal/search/repos/excluded_job.go
  internal/search/run/combinators.go
  internal/search/symbol/symbol.go
  internal/search/unindexed/structural.go
  internal/search/unindexed/unindexed.go
Labels: cla-signed

#30450 go-backcompat: Re-enable test
  dev/ci/go-backcompat/reorganize.go
  dev/ci/go-backcompat/reorganize_migrations.sh
  dev/ci/go-backcompat/test.sh
  internal/database/migration/definition/definition.go
  internal/database/migration/definition/read.go
  internal/database/migration/definition/read_test.go
Labels: cla-signed

#30452 compute: move logic to enterprise directory
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/graphqlbackend/compute.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/testing.go
  cmd/frontend/internal/cli/serve_cmd.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/bulk_operation_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/bulk_operation_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_apply_preview_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_apply_preview_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_counts_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_event_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/code_host_connection_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/permissions_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver_test.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/compute/init.go
  enterprise/cmd/frontend/internal/compute/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/compute/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/licensing/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/stars_resolvers_test.go
  enterprise/cmd/frontend/internal/orgrepos/resolvers/resolvers_test.go
  enterprise/cmd/frontend/main.go
  enterprise/internal/compute/command.go
  enterprise/internal/compute/match_context_result.go
  enterprise/internal/compute/match_only_command.go
  enterprise/internal/compute/match_only_command_test.go
  enterprise/internal/compute/output_command.go
  enterprise/internal/compute/output_command_test.go
  enterprise/internal/compute/query.go
  enterprise/internal/compute/query_test.go
  enterprise/internal/compute/replace_command.go
  enterprise/internal/compute/replace_command_test.go
  enterprise/internal/compute/result.go
  enterprise/internal/compute/template.go
  enterprise/internal/compute/template_test.go
  enterprise/internal/compute/text_result.go
Labels: cla-signed

#30504 chore: preallocate some list copies
  enterprise/cmd/frontend/internal/compute/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/compute/resolvers/resolvers_test.go
Labels: cla-signed

#30439 logging: Print iTerm link to the log's source file:line in VS Code
  internal/env/env.go
  internal/logging/main.go
  sg.config.yaml
Labels: dx-announce, cla-signed

#30462 Search backend: use sort interface of `result.Matches`
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  internal/search/result/commit.go
  internal/search/result/deduper.go
  internal/search/result/deduper_test.go
  internal/search/result/match.go
  internal/search/run/aggregator.go
  internal/search/symbol/symbol.go
Labels: cla-signed

#30451 Sub-repo perms: convert subrepo perms filtering into a job
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
  internal/search/subrepoperms/sub_repo_perms_job.go
  internal/search/subrepoperms/sub_repo_perms_job_test.go
Labels: cla-signed

#30367 for symbols: wrap handler in actor.HTTPMiddleware
  cmd/symbols/main.go
  internal/actor/http.go
Labels: cla-signed

#30516 Fix issue regex in project automation
  .github/workflows/project-automation.yml
Labels: cla-signed

#30453 dev: improve patch release instruction
  dev/release/src/release.ts
Labels: team/delivery, cla-signed

#30521 docs: clarify worker service connects to code insights db
  doc/admin/config/postgres-conf.md
Labels: cla-signed

#30522 code monitoring: add link to slack docs
  client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.tsx
Labels: cla-signed

#30284 notebooks: auto-fill inputs from file url
  client/web/src/integration/notebook.test.ts
  client/web/src/search/notebook/SearchNotebookBlockMenu.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlock.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInputs.tsx
  client/web/src/search/notebook/serialize.ts
Labels: cla-signed

#30533 executor docs: also mention how to update AWS ami
  doc/dev/how-to/deploy_executor_image.md
Labels: cla-signed

#30535 ci: extract frontend specific checks into steps
  dev/check/all.sh
  enterprise/dev/ci/internal/ci/changed/changed.go
  enterprise/dev/ci/internal/ci/operations.go
Labels: dx, ci, team/devx, ci/flake, cla-signed, okr/ci-downtime

#30526 migrations: Refactor desguar operations
  internal/database/migration/runner/options.go
Labels: cla-signed

#30520 executors: Add `X-Sourcegraph-Actor-UID: internal` to git fetch command
  enterprise/cmd/executor/internal/worker/workspace.go
  enterprise/cmd/executor/internal/worker/workspace_test.go
Labels: cla-signed

#30512 migrations: Update memoryStore methods (for tests)
  internal/database/connections/test/store.go
Labels: cla-signed

#30509 migrations: Extract `IndexStatus` into `storetypes` package
  internal/database/migration/store/store.go
  internal/database/migration/store/store_test.go
  internal/database/migration/storetypes/index_progress.go
Labels: cla-signed

#30506 Search exporter doc update
  doc/admin/how-to/troubleshoot-sg-extension.md
Labels: cla-signed

#30476 Code Insights: Add Code Insights Learn more section
  client/web/src/enterprise/insights/pages/getting-started/CodeInsightsGettingStartedPage.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-learn-more/CodeInsightsLearnMore.module.scss
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-learn-more/CodeInsightsLearnMore.tsx
Labels: team/code-insights, cla-signed

#30542 migrations: Read all applied versions when populating `schemaVersion`
  internal/database/migration/runner/iface.go
  internal/database/migration/runner/mock_iface_test.go
  internal/database/migration/runner/runner.go
Labels: cla-signed

#30501 chore: Update migration comments
  internal/database/migration/runner/options.go
Labels: cla-signed

#30544 migrations: Refactor `runSchema{Up,Down}` in runner
  internal/database/migration/runner/run.go
Labels: cla-signed

#30547 set the actor for code monitor searches to monitor owner
  enterprise/internal/codemonitors/background/workers.go
Labels: cla-signed

#30561 Update release config for 3.36.3 patch release
  dev/release/release-config.jsonc
Labels: cla-signed

#30507 add code-insights to the license tags
  enterprise/internal/licensing/data.go
  enterprise/internal/licensing/features_test.go
Labels: cla-signed

#30549 migrations: Add `withLockedSchemaState` to runner
  internal/database/migration/runner/run.go
  internal/database/migration/runner/runner.go
Labels: cla-signed

#30564 Docs updates
  doc/code_search/explanations/features.md
Labels: cla-signed

#30519 enqueue actions after updating the result set
  enterprise/internal/codemonitors/background/workers.go
Labels: cla-signed

#30517 Tracing: fix span tagging and add LazyFields
  internal/search/commit/commit_new.go
  internal/trace/traceutil.go
Labels: cla-signed

#30454 Search backend: chop out `doResults`
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_stats_languages.go
  internal/search/alert/observer.go
Labels: cla-signed

#30459 Search backend: pass stream through explicitly
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/streaming/stream.go
  internal/search/symbol/symbol.go
  internal/search/unindexed/structural.go
  internal/search/unindexed/unindexed.go
Labels: cla-signed

#30569 simplify aggregatingStream access
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_stats_languages.go
  internal/search/streaming/stream.go
  internal/search/unindexed/structural.go
  internal/search/unindexed/unindexed.go
  internal/search/zoekt/indexed_search_test.go
Labels: cla-signed

#30570 dev/team: include link to team.yml to add GitHub handle
  dev/team/team.go
Labels: cla-signed

#30573 Add 3.36.3 changelog entry
  CHANGELOG.md
Labels: cla-signed

#30580 compute: enterprise compute streaming HTTP endpoint scaffolding
  cmd/frontend/enterprise/enterprise.go
  enterprise/cmd/frontend/internal/compute/init.go
Labels: cla-signed

#30582 compute: add .api/compute/stream route
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/api_test.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/router/router.go
Labels: cla-signed

#30496 Insights/fix commits before index
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/compression/commits.go
  enterprise/internal/insights/compression/compression.go
  enterprise/internal/insights/compression/compression_test.go
  enterprise/internal/insights/compression/testdata/TestFilterFrames/test_no_commits_two_frames.golden
Labels: cla-signed

#30578 Search backend: simplify aggregator
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/run/aggregator.go
Labels: cla-signed

#30584 Search backend: simplify returns
  cmd/frontend/graphqlbackend/search_results.go
Labels: cla-signed

#30587 release: sourcegraph@3.36.3
  client/web/src/search/home/SelfHostInstructions.tsx
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/install/docker-compose/aws.md
  doc/admin/install/docker-compose/digitalocean.md
  doc/admin/install/docker-compose/google_cloud.md
  doc/admin/install/docker-compose/operations.md
  doc/admin/install/docker/aws.md
  doc/admin/install/docker/digitalocean.md
  doc/admin/install/docker/google_cloud.md
  doc/admin/install/docker/index.md
  doc/admin/install/docker/operations.md
  doc/admin/install/kubernetes/configure.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/pure_docker.md
  doc/dev/how-to/testing.md
  doc/index.md
Labels: cla-signed

#30537 codemonitors: Remove dead parameter
  enterprise/internal/codemonitors/background/graphql.go
  enterprise/internal/codemonitors/background/workers.go
Labels: team/repo-management, cla-signed

#30607 gitserver: No sources for a JVM dependency is non fatal
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_jvm_packages_test.go
  internal/extsvc/jvmpackages/coursier/coursier.go
Labels: team/repo-management, cla-signed

#30488 Code Insights: Adjust dashboard page header layout
  client/web/src/components/AppRouterContainer/AppRouterContainer.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.module.scss
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-header/DashboardHeader.module.scss
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-header/DashboardHeader.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/utils/get-dashboard-permissions.ts
Labels: team/code-insights, cla-signed

#30610 docs: Add support for Bitbucket Data Center
  doc/admin/config/authorization_and_authentication.md
  doc/admin/external_service/bitbucket_server.md
  doc/admin/external_service/index.md
  doc/admin/how-to/site-admin-quickstart.md
  doc/admin/migration/opengrok.md
  doc/admin/pings.md
  doc/admin/repo/add.md
  doc/admin/repo/permissions.md
  doc/batch_changes/explanations/introduction_to_batch_changes.md
  doc/batch_changes/how-tos/configuring_credentials.md
  doc/dev/background-information/batch_changes/index.md
  doc/dev/security/csrf_security_model.md
  doc/extensions/principles.md
  doc/integration/bitbucket_server.md
  doc/integration/browser_extension.md
  doc/integration/index.md
  schema/bitbucket_server.schema.json
  schema/schema.go
Labels: cla-signed

#30611 Fix OOB indexing in gitserver's NPM-related code.
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  cmd/gitserver/server/vcs_syncer_npm_packages_test.go
Labels: cla-signed

#30614 Fix typo in comment.
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
Labels: cla-signed

#30612 server: Add p4-fusion to image
  cmd/server/Dockerfile
Labels: team/repo-management, cla-signed

#30616 web: add missing `.btn:hover` styles
  client/wildcard/src/components/Button/Button.module.scss
Labels: team/frontend-platform, cla-signed, wildcard-v2/button

#30615 authz/github: Simplify Provider.Validate
  enterprise/internal/authz/github/github.go
Labels: debt, team/repo-management, cla-signed

#30602 migrations: Poll for advisory locks in the runner
  internal/database/connections/test/store.go
  internal/database/migration/runner/helpers_test.go
  internal/database/migration/runner/iface.go
  internal/database/migration/runner/mock_iface_test.go
  internal/database/migration/runner/runner.go
  internal/database/migration/runner/validate.go
  internal/database/migration/store/store.go
  internal/database/migration/store/store_test.go
Labels: cla-signed

#30604 lint: Fix `fmt.Errorf` guard
  .golangci.yml
  cmd/sitemap/graphql.go
  cmd/symbols/internal/gitserver/client.go
  dev/bkstats/go.mod
  dev/bkstats/go.sum
  dev/bkstats/main.go
  dev/buildchecker/branch.go
  dev/buildchecker/checker.go
  dev/buildchecker/slack.go
  dev/codeintel-qa/cmd/upload/state.go
  dev/sg/internal/bk/bk.go
  dev/sg/internal/images/images.go
  dev/sg/internal/loki/loki.go
  dev/sg/internal/migration/squash.go
  dev/sg/internal/open/url.go
  dev/sg/internal/secrets/store.go
  dev/sg/sg_ci.go
  dev/sg/sg_install.go
  dev/sg/sg_secret.go
  dev/sg/sg_setup.go
  dev/sg/sg_team.go
  dev/team/team.go
  enterprise/cmd/executor/config.go
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github_test.go
  enterprise/dev/ci/internal/ci/pipeline.go
  enterprise/internal/batches/service/workspace_resolver.go
  enterprise/internal/batches/service/workspace_resolver_test.go
  enterprise/internal/codeintel/stores/lsifstore/data_write_documentation.go
  enterprise/internal/codeintel/stores/lsifstore/migration/apidocs_search.go
  internal/conf/reposource/jvm_packages.go
  internal/database/connections/live/connect.go
  internal/database/migration/definition/definition.go
  internal/database/migration/definition/read.go
  internal/database/migration/runner/old_run_test.go
  internal/database/migration/runner/options.go
  internal/database/migration/runner/run.go
  internal/database/migration/runner/runner.go
  internal/extsvc/npm/npm.go
  internal/extsvc/npm/npmtest/npmtest.go
  internal/repos/jvm_packages.go
  internal/repos/sources.go
  internal/store/store_test.go
  lib/batches/batch_spec.go
  lib/batches/changeset_specs.go
  lib/batches/git/changes.go
Labels: cla-signed

#30636 Update 3.35.2 release config
  dev/release/release-config.jsonc
Labels: cla-signed

#30531 dev/ci: rewrite ChangedFiles as bitmask Diff
  doc/dev/background-information/continuous_integration.md
  enterprise/dev/ci/gen-pipeline.go
  enterprise/dev/ci/internal/ci/changed/changed.go
  enterprise/dev/ci/internal/ci/changed/diff.go
  enterprise/dev/ci/internal/ci/changed/diff_test.go
  enterprise/dev/ci/internal/ci/changed/files.go
  enterprise/dev/ci/internal/ci/config.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#30597 Search backend: split aggregator into resultCountingStream and statsObservingStream
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/run/aggregator.go
  internal/search/streaming/stream.go
Labels: cla-signed

#30606 Search backend: add alert as a return value to the job interface
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_stats_languages.go
  internal/search/alert.go
  internal/search/alert_test.go
  internal/search/commit/commit_new.go
  internal/search/repos/excluded_job.go
  internal/search/run/combinators.go
  internal/search/run/combinators_test.go
  internal/search/run/job_mock_test.go
  internal/search/run/repository.go
  internal/search/run/run.go
  internal/search/subrepoperms/sub_repo_perms_job.go
  internal/search/symbol/symbol.go
  internal/search/unindexed/structural.go
  internal/search/unindexed/unindexed.go
Labels: cla-signed

#30528 Add code insights iteration stats Slack bot
  .github/workflows/iteration-stats-slackbot.yml
  .github/workflows/post-iteration-stats.ps1
Labels: ops & tools & dev, team/code-insights, cla-signed

#30259 Update dashboard permissions doc
  doc/code_insights/explanations/viewing_code_insights.md
Labels: cla-signed

#30502 Add telemetry service, browser actions, and metric collection
  client/vscode/images/logomark_dark.svg
  client/vscode/images/logomark_light.svg
  client/vscode/package.json
  client/vscode/src/backend/eventLogger.ts
  client/vscode/src/contract.ts
  client/vscode/src/extension.ts
  client/vscode/src/link-commands/browserActionsNode.ts
  client/vscode/src/link-commands/browserActionsWeb.ts
  client/vscode/src/link-commands/initialize.ts
  client/vscode/src/webview/commands.ts
  client/vscode/src/webview/index.scss
  client/vscode/src/webview/initialize.ts
  client/vscode/src/webview/platform/EventLogger.ts
  client/vscode/src/webview/platform/context.ts
  client/vscode/src/webview/platform/telemetryService.ts
  client/vscode/src/webview/search-panel/SearchHomeView.tsx
  client/vscode/src/webview/search-panel/SearchResultsView.tsx
  client/vscode/src/webview/search-panel/components/HomeFooter.module.scss
  client/vscode/src/webview/search-panel/components/HomeFooter.tsx
  client/vscode/src/webview/search-panel/components/SearchCta.module.scss
  client/vscode/src/webview/search-panel/components/SearchCta.tsx
  client/vscode/src/webview/search-panel/components/SearchResultsInfoBar.tsx
  client/vscode/src/webview/search-panel/index.module.scss
  client/vscode/src/webview/search-sidebar/AuthSidebarView.module.scss
  client/vscode/src/webview/search-sidebar/AuthSidebarView.tsx
  client/vscode/src/webview/search-sidebar/HistorySidebarView.tsx
  client/vscode/src/webview/search-sidebar/SearchSidebarView.module.scss
  client/vscode/src/webview/search-sidebar/components/RecentFilesSection.tsx
  client/vscode/src/webview/search-sidebar/components/RecentRepositoriesSection.tsx
  client/vscode/src/webview/search-sidebar/components/RecentSearchesSection.tsx
  client/vscode/src/webview/search-sidebar/components/SavedSearchesSection.tsx
  client/vscode/src/webview/search-sidebar/index.tsx
  client/vscode/src/webview/theming/highlight.scss
  client/vscode/webpack.config.js
Labels: team/growth-and-integrations, cla-signed, vscode-extension

#30648 batches: tweak user-visible message for ErrMissingCredentials
  enterprise/internal/batches/sources/sources.go
Labels: team/batchers, cla-signed

#30647 diskcache: Construct correct paths
  internal/diskcache/cache.go
Labels: cla-signed

#30543 insights: Return a useful error message for invalid dashboard grants
  enterprise/internal/insights/resolvers/dashboard_resolvers.go
  enterprise/internal/insights/resolvers/dashboard_resolvers_test.go
Labels: team/code-insights, cla-signed

#30646 Extract project automation to external script
  .github/workflows/iteration-stats-slackbot.yml
  .github/workflows/project-automation.yml
  .github/workflows/update-project-item-statuses.ps1
Labels: cla-signed

#30653 Update pure_docker.md
  doc/admin/updates/pure_docker.md
Labels: cla-signed

#30641 release: sourcegraph@3.35.2
  doc/admin/updates/pure_docker.md
Labels: cla-signed

#30651 diskcache: Test multi-key eviction
  internal/diskcache/cache_test.go
Labels: cla-signed

#30613 Add onCopy callback to CopyableText
  client/web/src/components/CopyableText.tsx
Labels: cla-signed

#30589 user invites: client/http-client: fix apollo merging for Person type
  client/http-client/src/graphql/apollo/cache.ts
Labels: cla-signed

#30592 web: useExternalServices: add option to fetch collaborators
  client/web/src/auth/useExternalServicesWithCollaborators.ts
  client/web/src/components/externalServices/backend.ts
Labels: cla-signed

#30277 Removing unversioned docs links from the enterprise folder
  client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.tsx
  client/web/src/enterprise/batches/global/DotcomGettingStartedPage.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
  client/web/src/enterprise/batches/list/GettingStarted.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringGettingStarted.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
  client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.tsx
  client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.tsx
  client/web/src/enterprise/codeintel/configuration/components/EmptyPoliciesList.tsx
  client/web/src/enterprise/codeintel/indexes/components/EmptyAutoIndex.tsx
  client/web/src/enterprise/codeintel/uploads/components/EmptyUploads.tsx
  client/web/src/enterprise/executors/ExecutorsListPage.tsx
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
  client/web/src/enterprise/insights/components/beta-feedback-panel/BetaFeedbackPanel.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/DrillDownFiltersForm.tsx
  client/web/src/enterprise/insights/modals/BetaConfirmationModal.tsx
  client/web/src/enterprise/insights/pages/dashboards/creation/InsightsDashboardCreationPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/CaptureGoupCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/intro/IntroCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/form-series-input/FormSeriesInput.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/edit-insight/EditInsightPage.tsx
  client/web/src/enterprise/searchContexts/CreateSearchContextPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListPage.tsx
  client/web/src/enterprise/site-admin/SiteAdminAuthenticationProvidersPage.tsx
Labels: cla-signed

#30539 notebooks: add support for namespaces
  client/web/src/integration/notebook.test.ts
  client/web/src/routes.tsx
  client/web/src/search/notebook/CreateNotebookPage.tsx
  client/web/src/search/notebook/SearchNotebookPage.tsx
  client/web/src/search/notebook/backend.ts
  client/web/src/search/notebook/listPage/SearchNotebooksListPage.story.tsx
  cmd/frontend/graphqlbackend/notebooks.go
  cmd/frontend/graphqlbackend/notebooks.graphql
  enterprise/cmd/frontend/internal/notebooks/resolvers/apitest/convert.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/apitest/types.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/permissions.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/stars_resolvers_test.go
  enterprise/internal/notebooks/store.go
  enterprise/internal/notebooks/store_test.go
  enterprise/internal/notebooks/types.go
  internal/database/schema.md
  migrations/frontend/1528395971/down.sql
  migrations/frontend/1528395971/metadata.yaml
  migrations/frontend/1528395971/up.sql
Labels: cla-signed

#30628 go get -u ./...
  dev/depgraph/go.mod
  dev/depgraph/go.sum
  docker-images/prometheus/cmd/prom-wrapper/mocks/prometheus_mock.go
  enterprise/dev/insight-data-gen/go.mod
  enterprise/dev/insight-data-gen/go.sum
  go.mod
  go.sum
  internal/cmd/progress-bot/go.mod
  internal/cmd/progress-bot/go.sum
  internal/extsvc/auth/oauth_bearer.go
  lib/go.mod
  lib/go.sum
Labels: cla-signed

#30632 [cloud][CLOUD-226] Add email to `inviteUserToOrganization` mutation
  client/web/src/org/settings/members/InviteForm.tsx
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/schema.graphql
  dev/authtest/organization_test.go
  internal/gqltestutil/organization.go
Labels: cla-signed

#30498 [cloud] Make org invite URLs unique
  client/shared/.eslintignore
  client/shared/src/graphql/schema.ts
  client/web/src/org/OrgsArea.tsx
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/area/OrgInvitationPageLegacy.tsx
  client/web/src/org/invitations/OrgInvitationPage.tsx
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitation.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/org_invitations_test.go
  cmd/frontend/graphqlbackend/org_test.go
  cmd/frontend/graphqlbackend/schema.graphql
  go.sum
  internal/database/mocks.go
  internal/database/org_invitations.go
  internal/database/org_invitations_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#30672 sg: stop buffering command output until newlines
  dev/sg/internal/run/command.go
  lib/process/pipe.go
Labels: cla-signed

#30676 Fix invalid GraphQL query in integration tests
  internal/gqltestutil/organization.go
Labels: cla-signed

#30349 [CLOUD-209] Redirect users to connect code host connections through GitHub App
  client/web/dev/utils/create-js-context.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/org/backend.ts
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Labels: cla-signed

#30675 gitserver: Double check error type
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
Labels: team/repo-management, cla-signed

#30677 doc: Add sub-repo permissions details
  doc/admin/repo/perforce.md
Labels: team/repo-management, cla-signed

#30670 observation: Remove dead parameter
  internal/observation/observation.go
Labels: cla-signed

#30282 bext: add "https://" URL input placeholder
  client/browser/CHANGELOG.md
  client/browser/src/browser-extension/options-menu/OptionsPage.tsx
Labels: cla-signed

#30681 codeintel: add gcp profiling to precise-code-intel-worker
  enterprise/cmd/precise-code-intel-worker/main.go
Labels: team/code-intelligence, cla-signed, observability

#30679 Support resizable panel + scrollTo functionality
  client/web/src/global/CoolCodeIntel.module.scss
  client/web/src/global/CoolCodeIntel.tsx
Labels: team/frontend-platform, cla-signed

#30683 search: Fix icon alignment in search stack entries
  client/web/src/search/SearchStack.tsx
Labels: cla-signed

#30682 monitoring: Increase alert timing threshold
  doc/admin/observability/alert_solutions.md
  monitoring/definitions/repo_updater.go
Labels: team/repo-management, cla-signed

#30291 ssbc: Don't persist steps and skipped steps on workspaces
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_connection.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/permissions_test.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform.go
  enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform_test.go
  enterprise/internal/batches/background/batch_spec_workspace_creator.go
  enterprise/internal/batches/background/batch_spec_workspace_creator_test.go
  enterprise/internal/batches/service/service_test.go
  enterprise/internal/batches/service/workspace_resolver.go
  enterprise/internal/batches/service/workspace_resolver_test.go
  enterprise/internal/batches/store/batch_spec_workspace_execution_jobs.go
  enterprise/internal/batches/store/batch_spec_workspace_execution_jobs_test.go
  enterprise/internal/batches/store/batch_spec_workspaces.go
  enterprise/internal/batches/store/batch_spec_workspaces_test.go
  enterprise/internal/batches/store/worker_workspace_execution_test.go
  enterprise/internal/batches/types/batch_spec_workspace.go
  lib/batches/batch_spec.go
  lib/batches/batch_spec_test.go
  lib/batches/workspaces_execution_input.go
Labels: team/batchers, cla-signed

#30689 Fix GlobalAlert variant
  client/web/src/global/GlobalAlert.story.tsx
  client/web/src/global/GlobalAlert.tsx
Labels: team/frontend-platform, cla-signed

#30691 Temporarily disable uploads of client/web LSIF dumps to dogfood.
  .github/workflows/lsif-ts.yml
Labels: cla-signed

#30686 permissions: Instrument sub-repo perms sync timings
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/internal/database/perms_store.go
Labels: team/repo-management, cla-signed

#30037 sg: Allow checks to be built in Go
  dev/sg/config.go
  dev/sg/config_test.go
  dev/sg/internal/usershell/usershell.go
  dev/sg/sg_doctor.go
  dev/sg/sg_setup.go
  dev/sg/sg_setup_test.go
  dev/sg/sg_start.go
  sg.config.yaml
Labels: cla-signed

#30650 release: sourcegraph@3.35.2
  client/web/src/search/home/SelfHostInstructions.tsx
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/install/docker-compose/aws.md
  doc/admin/install/docker-compose/digitalocean.md
  doc/admin/install/docker-compose/google_cloud.md
  doc/admin/install/docker-compose/operations.md
  doc/admin/install/docker/aws.md
  doc/admin/install/docker/digitalocean.md
  doc/admin/install/docker/google_cloud.md
  doc/admin/install/docker/index.md
  doc/admin/install/docker/operations.md
  doc/admin/install/kubernetes/configure.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/dev/how-to/testing.md
  doc/index.md
Labels: cla-signed

#30661 compute: stream results
  enterprise/cmd/frontend/internal/compute/init.go
  enterprise/cmd/frontend/internal/compute/streaming/compute.go
  enterprise/cmd/frontend/internal/compute/streaming/event.go
  enterprise/cmd/frontend/internal/compute/streaming/stream.go
Labels: cla-signed

#30658 gitserver: Use POST for /archive
  cmd/symbols/internal/database/writer/writer.go
  internal/gitserver/client.go
Labels: cla-signed

#30657 logging: Truncate long slow log messages
  internal/trace/httptrace.go
Labels: cla-signed

#30685 Allow site-admin to remove themselves from an Org CLOUD-262
  client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
  cmd/frontend/graphqlbackend/org.go
Labels: cla-signed

#30667 Search backend: create batchingStream
  cmd/frontend/internal/search/search.go
  internal/search/streaming/stream.go
  internal/search/streaming/stream_test.go
Labels: cla-signed

#30663 symbols: Split calls to git archive
  cmd/symbols/config.go
  cmd/symbols/internal/api/handler_test.go
  cmd/symbols/internal/database/writer/writer.go
  cmd/symbols/internal/fetcher/repository_fetcher.go
  cmd/symbols/internal/fetcher/repository_fetcher_test.go
  cmd/symbols/main.go
Labels: cla-signed

#30655 Search backend: convert and/or evaluation to jobs
  cmd/frontend/graphqlbackend/search_results.go
  go.mod
  internal/search/result/merger.go
  internal/search/run/combinators.go
  internal/search/run/expression_job.go
Labels: cla-signed

#30706 fix batching stream test that didn't use goroutine safe operations
  internal/search/streaming/stream_test.go
Labels: cla-signed

#30702 search: remove visitor interface
  internal/search/query/visitor.go
Labels: cla-signed

#30708 use smaller number of parallel senders
  internal/search/streaming/stream_test.go
Labels: cla-signed

#30709 Include link to Prometheus cAdvisor scraping fix
  doc/admin/observability/troubleshooting.md
Labels: cla-signed

#30560 refactor Code Insights storybook stories
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownFiltersPanel.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/DrilDownFiltersForm.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-insight-creation-form/DrillDownInsightCreationForm.story.tsx
  client/web/src/enterprise/insights/modals/BetaConfirmationModal.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/creation/InsightsDashboardCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/intro/IntroCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/intro/cards/InsightCards.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/views/components/view-grid/ViewGrid.story.tsx
  client/web/src/views/components/view/View.story.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/scroll-box/ScrollBox.module.scss
  client/web/src/views/components/view/content/chart-view-content/charts/line/components/scroll-box/ScrollBox.story.tsx
Labels: cla-signed

#30596 Fix broken link to handbook page
  dev/release/src/release.ts
Labels: cla-signed

#30715 doc/dev: add note about Firefox certificate issues on macOS
  doc/dev/setup/troubleshooting.md
Labels: docs, dx, cla-signed

#30700 dev: improve release process
  .github/ISSUE_TEMPLATE/request_patch_release.md
  dev/release/src/main.ts
  dev/release/src/release.ts
  dev/release/src/slack.ts
  dev/release/src/util.ts
Labels: cla-signed

#30717 Correctly disable uploads of client/web LSIF dumps to dogfood.
  .github/workflows/lsif-ts.yml
Labels: cla-signed

#30720 Fix <ButtonLink> and disallow href props
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
Labels: cla-signed

#30697 dev/sg: introduce 'sg version changelog'
  dev/sg/install.sh
  dev/sg/main.go
  dev/sg/sg_version.go
Labels: dx, dx-announce, cla-signed

#30722 bkstats: remove unecessary go.mod
  dev/bkstats/go.mod
  dev/bkstats/go.sum
Labels: dx, cla-signed

#30725 dev/sg: fix update check
  dev/sg/main.go
Labels: cla-signed

#30530 dev/ci: rewrite computeRunType to use structured RunTypeMatchers
  enterprise/dev/ci/internal/ci/config.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/runtype.go
  enterprise/dev/ci/internal/ci/runtype_test.go
Labels: cla-signed

#30723 Update ci-checkov.sh
  dev/ci/ci-checkov.sh
Labels: cla-signed

#30737 notebooks: do not show suggestions on file URL paste
  client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
Labels: cla-signed

#30674 bext: filter dropdown duplicated URLs
  client/browser/src/browser-extension/scripts/optionsPage.main.tsx
Labels: cla-signed

#30726 dev/sg: do not show merges in sg version changelog
  dev/sg/sg_version.go
Labels: cla-signed

#30492 ci: caching mechanism for stateless agents
  .buildkite/hooks/pre-command
  .prettierignore
  .tool-versions
  doc/dev/background-information/continuous_integration.md
  doc/dev/how-to/cache_ci_artefacts.md
  enterprise/dev/ci/gen-pipeline.go
  enterprise/dev/ci/internal/buildkite/buildkite.go
  enterprise/dev/ci/internal/buildkite/cache.go
  enterprise/dev/ci/internal/ci/cache_helpers.go
  enterprise/dev/ci/internal/ci/operations.go
Labels: dx, dx-announce, team/devx, cla-signed

#30740 repo-updater: Remove feature flag to enable / disable repo update jitter
  internal/repos/scheduler.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#29968 ssbc: Implement filters and search on workspaces list and preview
  client/web/src/enterprise/batches/ChangesetFilter.tsx
  client/web/src/enterprise/batches/create/backend.ts
  client/web/src/enterprise/batches/create/workspaces-preview/WorkspacesPreview.tsx
  client/web/src/enterprise/batches/create/workspaces-preview/WorkspacesPreviewList.tsx
  client/web/src/enterprise/batches/execution/WorkspacesList.tsx
  client/web/src/enterprise/batches/execution/backend.ts
  client/web/src/enterprise/batches/execution/util.ts
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_resolution.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_resolution_test.go
  enterprise/internal/batches/store/batch_spec_workspaces.go
  enterprise/internal/batches/store/batch_spec_workspaces_test.go
Labels: team/batchers, cla-signed

#30692 SSBC: Skipped steps migration
  internal/database/schema.md
  migrations/frontend/1528395972/down.sql
  migrations/frontend/1528395972/metadata.yaml
  migrations/frontend/1528395972/up.sql
Labels: team/batchers, cla-signed

#30629 Code Insights: Update in-product code insights example section
  client/search-ui/src/components/SyntaxHighlightedSearchQuery.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-examples/CodeInsightsExamples.module.scss
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-examples/CodeInsightsExamples.tsx
  client/web/src/views/components/view/content/chart-view-content/charts/line/LineChart.tsx
Labels: team/code-insights

#30640 Code Insights: Update template code insights landing page section
  client/web/src/enterprise/insights/pages/getting-started/CodeInsightsGettingStartedPage.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-temlates/CodeInsightsTemplates.module.scss
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-templates/CodeInsightsTemplates.module.scss
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-templates/CodeInsightsTemplates.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-templates/constants.ts
Labels: team/code-insights, cla-signed

#30413 signup: Teams beta step
  client/web/src/auth/PostSignUpPage.module.scss
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/auth/Steps/Steps.module.scss
  client/web/src/auth/Steps/Steps.story.tsx
  client/web/src/auth/Steps/Steps.test.tsx
  client/web/src/auth/Steps/Steps.tsx
  client/web/src/auth/Steps/__snapshots__/Steps.test.tsx.snap
  client/web/src/auth/Steps/context.ts
  client/web/src/auth/Steps/reducer.ts
  client/web/src/auth/welcome/CodeHostsConnection.tsx
  client/web/src/auth/welcome/Footer.tsx
  client/web/src/auth/welcome/StartSearching.tsx
  client/web/src/auth/welcome/TeamsBeta.module.scss
  client/web/src/auth/welcome/TeamsBeta.tsx
  client/web/src/auth/welcome/useHubSpotForm.tsx
  client/web/src/user/settings/repositories/SelectAffiliatedRepos.module.scss
  client/web/src/user/settings/repositories/SelectAffiliatedRepos.tsx
Labels: cla-signed

#29920 Migrate all cases of @reach/tabs usage to Wildcard/Tabs
  client/branded/src/components/panel/Panel.tsx
  client/branded/src/global-styles/index.scss
  client/search-ui/src/results/sidebar/SearchReference.module.scss
  client/search-ui/src/results/sidebar/SearchReference.tsx
  client/search-ui/src/results/sidebar/SearchSidebarSection.module.scss
  client/shared/src/extensions/devtools/index.module.scss
  client/shared/src/extensions/devtools/index.tsx
  client/web/src/enterprise/batches/BatchChangeTabs.module.scss
  client/web/src/enterprise/batches/BatchChangeTabs.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
  client/web/src/integration/batches.test.ts
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RevisionsPopover/RevisionsPopover.tsx
  client/web/src/repo/RevisionsPopover/components/ConnectionPopover/ConnectionPopover.tsx
  client/web/src/search/results/sidebar/Revisions.tsx
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.tsx
  client/wildcard/src/components/Tabs/Tabs.module.scss
  client/wildcard/src/components/Tabs/Tabs.tsx
  client/wildcard/src/components/index.ts
Labels: team/frontend-platform, cla-signed

#30743 Bump src-cli version to latest
  doc/cli/references/batch/apply.md
  doc/cli/references/batch/exec.md
  doc/cli/references/batch/preview.md
  doc/cli/references/batch/repositories.md
  doc/cli/references/batch/validate.md
  doc/cli/references/validate.md
  internal/src-cli/consts.go
Labels: cla-signed

#30738 Organization membership section updated UX and Invitation flow
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/area/OrgHeader.tsx
  client/web/src/org/area/navitems.ts
  client/web/src/org/area/routes.tsx
  client/web/src/org/backend.ts
  client/web/src/org/members/AddMemberToOrgModal.tsx
  client/web/src/org/members/InviteMemberModal.module.scss
  client/web/src/org/members/InviteMemberModal.tsx
  client/web/src/org/members/OrgMembersArea.tsx
  client/web/src/org/members/OrgMembersListPage.module.scss
  client/web/src/org/members/OrgMembersListPage.tsx
  client/web/src/org/members/OrgMembersSidebar.module.scss
  client/web/src/org/members/OrgMembersSidebar.tsx
  client/web/src/org/members/OrgPendingInvites.tsx
  client/web/src/org/settings/OrgSettingsArea.tsx
  client/web/src/org/settings/OrgSettingsSidebar.tsx
  client/web/src/org/settings/members-v1/InviteForm.module.scss
  client/web/src/org/settings/members-v1/InviteForm.tsx
  client/web/src/org/settings/members-v1/OrgSettingsMembersPage.module.scss
  client/web/src/org/settings/members-v1/OrgSettingsMembersPage.tsx
Labels: cla-signed

#30744 bext: update changelog for #30674
  client/browser/CHANGELOG.md
Labels: cla-signed
