Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-05, with the labels that each got.

#34756 Pin protobuf-codegen version to 2.X
  dev/proto-generate.sh
Labels: dx, ci, cla-signed

#34691 repos: Blocked repos should also be counted as purgeable
  internal/repos/metrics.go
Labels: team/repo-management, cla-signed

#34643 extsvc: add client for pypi simple API
  internal/extsvc/pypi/client.go
  internal/extsvc/pypi/client_test.go
  internal/extsvc/pypi/testdata/golden/gpg-vault
  internal/extsvc/pypi/testdata/golden/requests
  internal/extsvc/pypi/testdata/vcr/download.yaml
  internal/extsvc/pypi/testdata/vcr/parse.yaml
Labels: cla-signed

#34755 lockfiles: add poetry.lock parser
  go.mod
  internal/codeintel/dependencies/internal/lockfiles/parser.go
  internal/codeintel/dependencies/internal/lockfiles/poetry.go
  internal/codeintel/dependencies/internal/lockfiles/testdata/parse/poetry.lock/textualize_rich.lock
  internal/codeintel/dependencies/internal/lockfiles/testdata/parse/poetry.lock/textualize_rich.lock.golden
  internal/conf/reposource/python_packages.go
Labels: cla-signed

#34754 Reference panel: highlight token in lines
  client/web/src/codeintel/ReferencesPanel.test.tsx
  client/web/src/codeintel/ReferencesPanel.tsx
Labels: cla-signed

#33998 Code Insights: Add code insights landing page's pings to ping documentation
  doc/admin/pings.md
  doc/dev/background-information/insights/code_insights_pings.md
Labels: cla-signed

#34620 Code Insights: Add search context filter v1
  client/branded/src/global-styles/typography.scss
  client/web/src/enterprise/insights/components/index.ts
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownFiltersPanel.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownFiltersPanel.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownFiltersPanel.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightCreationForm.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightFilters.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightFilters.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightFilters.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/DrillDownFiltersForm.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/components/drill-down-reg-exp-input/DrillDownRegExpInput.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/validators.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-input/DrillDownInput.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-input/DrillDownInput.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/filter-collapse-section/FilterCollapseSection.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/filter-collapse-section/FilterCollapseSection.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/search-context/DrillDownSearchContextFilter.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/search-context/DrillDownSearchContextFilter.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/utils.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/validators.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/index.ts
  client/web/src/enterprise/insights/components/trancated-text/TrancatedText.tsx
  client/web/src/enterprise/insights/components/trancated-text/TruncatedText.tsx
  client/web/src/enterprise/insights/core/backend/gql-backend/deserialization/create-insight-view.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-backend-insight-data/get-backend-insight-data.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/update-insight/serializators.ts
  client/web/src/enterprise/insights/core/types/insight/common.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/components/index.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/capture-group-insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/integration/insights/drill-down-filters.test.ts
Labels: cla-signed

#34749 JetBrains: Add JS→Java bridge
  client/jetbrains/src/main/java/com/sourcegraph/bridge/JSToJavaBridge.java
  client/jetbrains/src/main/java/com/sourcegraph/bridge/JSToJavaBridgeRequestHandler.java
  client/jetbrains/src/main/java/com/sourcegraph/ui/JCEFWindow.java
  client/jetbrains/src/main/java/com/sourcegraph/ui/ThemeService.java
  client/jetbrains/standalone/src/index.html
  client/jetbrains/webview/src/search/App.tsx
  client/jetbrains/webview/src/search/index.tsx
  client/jetbrains/webview/src/search/mockJavaInterface.ts
Labels: cla-signed

#34705 lib/log: add caller skip to point to line of Scope creation
  lib/log/logger.go
Labels: cla-signed

#34767 JetBrains: Add a more advanced result list
  client/jetbrains/webview/src/search/App.module.scss
  client/jetbrains/webview/src/search/App.tsx
  client/jetbrains/webview/src/search/index.tsx
  client/jetbrains/webview/src/search/results/FileSearchResult.module.scss
  client/jetbrains/webview/src/search/results/FileSearchResult.tsx
  client/jetbrains/webview/src/search/results/SearchResultList.module.scss
  client/jetbrains/webview/src/search/results/SearchResultList.tsx
  client/jetbrains/webview/src/search/results/TrimmedCodeLineWithHighlights.tsx
  client/jetbrains/webview/src/search/results/utils.ts
Labels: cla-signed, jetbrains-ide

#34712 RFC 624: (M2) Harden recognizer gitserver client
  internal/codeintel/autoindexing/internal/inference/init.go
  internal/codeintel/autoindexing/internal/inference/service.go
  internal/codeintel/autoindexing/internal/inference/service_test.go
Labels: team/code-intelligence, cla-signed, rfc-624

#34526 Docs Update: Add Scheduled Builds
  doc/dev/background-information/ci/development.md
Labels: cla-signed

#34775 JetBrains: Add minimal strategy to load file content
  client/jetbrains/webview/src/search/index.tsx
  client/jetbrains/webview/src/search/lib/blob.ts
Labels: cla-signed, jetbrains-ide

#34789 search-blitz: add queries for megarepo on k8s.sgdev.org
  internal/cmd/search-blitz/queries_dogfood.txt
Labels: cla-signed

#33289 [hackaton] Go code checkers as template insights, linking to suggested batch changes
  client/web/src/enterprise/batches/create/CodeInsightsBatchesIcon.module.scss
  client/web/src/enterprise/batches/create/CodeInsightsBatchesIcon.tsx
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.module.scss
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
  client/web/src/enterprise/batches/create/go-checker-templates.ts
  client/web/src/enterprise/batches/create/yaml-util.ts
  client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
  client/web/src/enterprise/insights/CodeInsightsRouter.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/BuiltInInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/SmartInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.test.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.story.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/CodeInsightsGettingStartedPage.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-templates/CodeInsightsTemplates.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-templates/constants.ts
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#34800 not never -> never
  doc/dev/background-information/web/web_app.md
Labels: cla-signed

#34522 VSCE: implement nightly build & automate release
  client/vscode/package.json
  client/vscode/scripts/release.ts
  dev/ci/runtype/runtype.go
  dev/ci/runtype/runtype_test.go
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/config.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#34757 Enable new reference panel & code intel badge in dev env
  dev/global-settings.json
Labels: cla-signed

#34792 fix incorrect line chart size in FireFox
  CHANGELOG.md
  client/web/src/charts/components/line-chart/LineChart.tsx
Labels: cla-signed

#34699 jc/remove-repos-mock: Fix go-mockgen in CI
  internal/repos/gen.go
  internal/repos/sync_worker.go
Labels: cla-signed

#34770 Search backend: accept only `query.Basic` for commit search
  internal/search/commit/commit.go
  internal/search/commit/commit_test.go
  internal/search/job/jobutil/job.go
Labels: cla-signed

#34239 RFC 619: (M1) Generate symbols service graphql transport skeleton
  internal/codeintel/symbols/transport/graphql/init.go
  internal/codeintel/symbols/transport/graphql/observability.go
  internal/codeintel/symbols/transport/graphql/resolver.go
Labels: team/code-intelligence, cla-signed, rfc-619

#34243 RFC 619: (M1) Generate documents service graphql transport skeleton
  internal/codeintel/documents/transport/graphql/init.go
  internal/codeintel/documents/transport/graphql/observability.go
  internal/codeintel/documents/transport/graphql/resolver.go
Labels: team/code-intelligence, cla-signed, rfc-619

#34561 tests: eliminate `repos.Mocks`
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
  cmd/repo-updater/shared/main.go
  enterprise/cmd/repo-updater/internal/authz/integration_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/cmd/repo-updater/main.go
  internal/extsvc/npm/testdata/vcr/TestNoPanicOnNonexistentRegistry.yaml
  internal/repos/gen.go
  internal/repos/integration_test.go
  internal/repos/jvm_packages.go
  internal/repos/mocks.go
  internal/repos/phabricator.go
  internal/repos/status_messages_test.go
  internal/repos/store.go
  internal/repos/store_test.go
  internal/repos/sync_errored.go
  internal/repos/sync_worker.go
  internal/repos/sync_worker_test.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: cla-signed

#34823 [Nav] fix integration tests
  client/web/src/integration/nav.test.ts
Labels: cla-signed

#34240 RFC 619: (M1) Generate policies service graphql transport skeleton
  cmd/frontend/graphqlbackend/codeintel.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/frankenresolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  internal/codeintel/policies/transport/graphql/init.go
  internal/codeintel/policies/transport/graphql/observability.go
  internal/codeintel/policies/transport/graphql/resolver.go
Labels: team/code-intelligence, cla-signed, rfc-619

#34827 Accessibility docs: Add keyboard navigation guidance
  doc/dev/background-information/web/accessibility/how-to-audit.md
Labels: team/frontend-platform, cla-signed

#34242 RFC 619: (M1) Generate uploads service graphql transport skeleton
  cmd/frontend/graphqlbackend/codeintel.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/frankenresolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  internal/codeintel/uploads/transport/graphql/init.go
  internal/codeintel/uploads/transport/graphql/observability.go
  internal/codeintel/uploads/transport/graphql/resolver.go
Labels: team/code-intelligence, cla-signed, rfc-619

#34780 Search backend: remove `PriorityJob`
  internal/search/job/jobutil/combinators.go
  internal/search/job/jobutil/combinators_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/printers_test.go
  internal/search/job/jobutil/types.go
Labels: cla-signed

#34786 Search backend: tidy up `internal/search/query` package
  internal/search/query/transformer.go
  internal/search/query/types.go
  internal/search/query/validate.go
  internal/search/query/validate_test.go
Labels: cla-signed

#34831 syntax-highlighting: default C# to tree-sitter highlighting
  cmd/frontend/internal/highlight/language.go
Labels: cla-signed

#34804 search: refactor SearchResult into CommitSearchResult and RepoSearchResult
  client/search-ui/src/components/CommitSearchResult.tsx
  client/search-ui/src/components/RepoSearchResult.tsx
  client/search-ui/src/components/SearchResult.tsx
  client/search-ui/src/components/index.ts
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/vscode/webpack.config.js
Labels: cla-signed

#34838 observation: only trace.log if trace is present
  internal/observation/observation.go
Labels: cla-signed

#34469 codeintel: Add language request telemetry
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/app/updatecheck/handler_test.go
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/database/mocks.go
  internal/types/codeintel.go
  internal/usagestats/aggregated_codeintel.go
  internal/usagestats/aggregated_codeintel_test.go
Labels: team/code-intelligence, cla-signed

#34840 Revert "search: refactor SearchResult into CommitSearchResult and RepoSearchResult"
  client/search-ui/src/components/CommitSearchResult.tsx
  client/search-ui/src/components/RepoSearchResult.tsx
  client/search-ui/src/components/SearchResult.tsx
  client/search-ui/src/components/index.ts
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/vscode/webpack.config.js
Labels: cla-signed

#34623 [SG-34403-1] Improve Percy + accessibilityAudit test coverage on User Profile Settings, User Email Settings, User Password Settings Page
  client/web/src/integration/profile.test.ts
  client/web/src/user/settings/emails/UserEmail.tsx
  client/web/src/user/settings/emails/UserSettingsEmailsPage.tsx
Labels: gitstart, cla-signed

#34845 Revert "repos: Fix external service config overwrite during long sync…
  internal/repos/integration_test.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: cla-signed

#34842 fix: remove VSCE Integration Test from core operations
  client/vscode/CONTRIBUTING.md
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: team/integrations, cla-signed

#34837 fix: filters do not work on featured extensions
  client/web/src/extensions/ExtensionsList.tsx
Labels: extensions, team/integrations, cla-signed

#34841 Revert "Revert "search: refactor SearchResult into CommitSearchResult and RepoSearchResult""
  client/search-ui/src/components/CommitSearchResult.tsx
  client/search-ui/src/components/RepoSearchResult.tsx
  client/search-ui/src/components/SearchResult.tsx
  client/search-ui/src/components/index.ts
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/vscode/webpack.config.js
Labels: cla-signed

#34805 search: rename `FileMatch` to `FileSearchResult`
  client/branded/src/components/panel/views/FileLocations.tsx
  client/search-ui/src/components/CommitSearchResult.tsx
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/shared/src/components/FileSearchResult.test.tsx
  client/shared/src/components/FileSearchResult.tsx
Labels: cla-signed

#34859 Fix hover reposition jank 2
  client/browser/src/shared/code-hosts/gitlab/codeHost.ts
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/codeintellify/src/hoverifier.ts
  client/codeintellify/src/overlayPosition.test.ts
  client/codeintellify/src/overlayPosition.ts
  client/codeintellify/src/types.ts
  client/shared/src/hover/HoverOverlay.tsx
Labels: cla-signed

#34853 fix: extension update and publish buttons accessibility issue
  client/web/src/enterprise/extensions/extension/RegistryExtensionManagePage.tsx
  client/web/src/enterprise/extensions/extension/RegistryExtensionNewReleasePage.tsx
Labels: accessibility, cla-signed

#34857 vsce: update search components
  client/vscode/src/webview/search-panel/alias/CommitSearchResult.tsx
  client/vscode/src/webview/search-panel/alias/RepoSearchResult.tsx
  client/vscode/src/webview/search-panel/alias/SearchResult.tsx
Labels: cla-signed, vscode-extension

#34863 Search backend: Rename `commit.CommitSearch` to `commit.CommitSearchJob`
  enterprise/internal/codemonitors/search.go
  enterprise/internal/codemonitors/search_test.go
  internal/search/commit/commit.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/testdata/Test_optimizeJobs/commit_with_and.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/commit_with_or.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/diff_with_and.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/diff_with_or.golden
  internal/search/job/jobutil/types.go
Labels: cla-signed

#34675 dev/ci: retry candidate image pushes automatically
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#34785 dev/ci: make dev docs more user-friendly, pipeline reference more prominent
  doc/dev/background-information/ci/development.md
  doc/dev/background-information/ci/index.md
Labels: cla-signed

#34881 web: ban `reactstrap` imports
  .eslintrc.js
  client/search-ui/src/input/SearchContextDropdown.tsx
  client/search-ui/src/input/SearchContextMenu.test.tsx
  client/search-ui/src/input/SearchContextMenu.tsx
  client/search-ui/src/results/progress/StreamingProgressSkippedPopover.tsx
  client/search-ui/src/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/vscode/src/webview/search-panel/components/ButtonDropdownCta.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/org/members/SearchUserAutocomplete.tsx
  client/web/src/org/settings/codeHosts/InstallGitHubAppSuccessPage.tsx
  client/wildcard/src/components/Tooltip/Tooltip.tsx
Labels: team/frontend-platform, cla-signed

#34324 Wildcard V2: <Checkbox /> migration
  client/branded/src/global-styles/GlobalStylesStory/FormFieldVariants/FormFieldVariants.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/browser/src/browser-extension/options-menu/OptionsPageAdvancedSettings.module.scss
  client/browser/src/browser-extension/options-menu/OptionsPageAdvancedSettings.tsx
  client/search-ui/src/results/progress/StreamingProgressSkippedPopover.tsx
  client/search-ui/src/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/vscode/src/webview/search-panel/components/SavedSearchForm.module.scss
  client/vscode/src/webview/search-panel/components/SavedSearchForm.tsx
  client/web/src/auth/SignUpForm.tsx
  client/web/src/auth/TosConsentModal.tsx
  client/web/src/enterprise/batches/close/BatchChangeCloseAlert.tsx
  client/web/src/enterprise/batches/detail/BatchChangeBurndownChart.tsx
  client/web/src/enterprise/batches/detail/changesets/MergeChangesetsModal.tsx
  client/web/src/enterprise/batches/detail/changesets/PublishChangesetsModal.tsx
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/add-insight-modal/components/add-insight-modal-content/AddInsightModalContent.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/CaptureGoupCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/SearchInsightCreationForm.tsx
  client/web/src/extensions/ExtensionRegistrySidenav.tsx
  client/web/src/notebooks/notebookPage/ShareNotebookModal.tsx
  client/web/src/savedSearches/SavedSearchForm.module.scss
  client/web/src/savedSearches/SavedSearchForm.tsx
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
  client/web/src/user/settings/repositories/RepositoryNode.tsx
  client/web/src/user/settings/repositories/SelectAffiliatedRepos.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/wildcard/src/components/Form/internal/BaseControlInput.tsx
Labels: gitstart, cla-signed

#34627 sg: create a test command to run e2e tests locally
  dev/sg/internal/run/command.go
  dev/sg/internal/run/run.go
  go.mod
  go.sum
  sg.config.yaml
Labels: dx, sg, ci, dx-announce, team/devx, cla-signed

#34884 sg: fix nil panic introduced in 284aba024
  dev/sg/internal/run/command.go
  dev/sg/internal/run/run.go
Labels: cla-signed

#34508 all: use alpine-3.14
  cmd/frontend/Dockerfile
  cmd/github-proxy/Dockerfile
  cmd/gitserver/Dockerfile
  cmd/loadtest/Dockerfile
  cmd/migrator/Dockerfile
  cmd/repo-updater/Dockerfile
  cmd/searcher/Dockerfile
  cmd/server/Dockerfile
  cmd/symbols/Dockerfile
  cmd/worker/Dockerfile
  dev/sg/Dockerfile
  dev/src-expose/Dockerfile
  docker-images/grafana/Dockerfile
  docker-images/jaeger-agent/Dockerfile
  docker-images/jaeger-all-in-one/Dockerfile
  docker-images/postgres_exporter/Dockerfile
  docker-images/prometheus/Dockerfile
  enterprise/cmd/frontend/Dockerfile
  enterprise/cmd/precise-code-intel-worker/Dockerfile
  enterprise/cmd/worker/Dockerfile
  internal/cmd/progress-bot/Dockerfile
  internal/cmd/resources-report/Dockerfile
  internal/cmd/search-blitz/Dockerfile
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed

#34874 codeintel: Add instance state check on query failures in codeintel-qa
  dev/codeintel-qa/cmd/query/main.go
  dev/codeintel-qa/cmd/query/queries.go
  dev/codeintel-qa/cmd/query/query.go
  dev/codeintel-qa/cmd/query/state.go
  dev/codeintel-qa/cmd/upload/main.go
  dev/codeintel-qa/internal/indexes.go
Labels: qa-tests, cla-signed

#34888 wildcard: Fix missing caret in textarea on Firefox
  CHANGELOG.md
  client/branded/src/global-styles/custom-forms.scss
  client/branded/src/global-styles/forms.scss
Labels: cla-signed

#34765 Wildcard Tabs: support longTabList property to make it scrollable
  client/wildcard/src/components/Tabs/Tabs.module.scss
  client/wildcard/src/components/Tabs/Tabs.story.tsx
  client/wildcard/src/components/Tabs/Tabs.tsx
  client/wildcard/src/components/Tabs/context.ts
Labels: team/frontend-platform, cla-signed

#34854 Bump src-cli version for new release.
  doc/cli/references/lsif/upload.md
  internal/src-cli/consts.go
Labels: cla-signed

#34894 ci: go-test uses a relative path to richstyle.yml
  dev/ci/go-test.sh
Labels: cla-signed

#34895 sg: Fixup precedence of cmd specific env vars
  dev/sg/internal/run/command.go
  dev/sg/internal/run/run.go
Labels: cla-signed

#34896 nix: use latest unstable
  shell.nix
Labels: cla-signed

#34898 internal: update Dockerfiles to use go 1.18
  internal/cmd/git-combine/Dockerfile
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed

#34864 RFC 624: (M3) Replace Go code
  enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go
  enterprise/internal/codeintel/autoindex/enqueuer/enqueuer_test.go
  enterprise/internal/codeintel/autoindex/enqueuer/gen.go
  enterprise/internal/codeintel/autoindex/enqueuer/iface.go
  enterprise/internal/codeintel/autoindex/enqueuer/mock_iface_test.go
  internal/codeintel/autoindexing/init.go
  lib/codeintel/autoindex/inference/clang.go
  lib/codeintel/autoindex/inference/clang_test.go
  lib/codeintel/autoindex/inference/gen.go
  lib/codeintel/autoindex/inference/gitclient.go
  lib/codeintel/autoindex/inference/go.go
  lib/codeintel/autoindex/inference/go_test.go
  lib/codeintel/autoindex/inference/helpers_test.go
  lib/codeintel/autoindex/inference/java.go
  lib/codeintel/autoindex/inference/java_test.go
  lib/codeintel/autoindex/inference/mock_gitclient_test.go
  lib/codeintel/autoindex/inference/paths.go
  lib/codeintel/autoindex/inference/paths_test.go
  lib/codeintel/autoindex/inference/patterns.go
  lib/codeintel/autoindex/inference/recognizers.go
  lib/codeintel/autoindex/inference/rust.go
  lib/codeintel/autoindex/inference/rust_test.go
  lib/codeintel/autoindex/inference/typescript.go
  lib/codeintel/autoindex/inference/typescript_test.go
  lib/codeintel/autoindex/inference/util.go
  lib/codeintel/autoindex/inference/util_test.go
Labels: team/code-intelligence, cla-signed, rfc-624

#34901 syntax-highlighter: reference sourcegraph/Packages
  docker-images/syntax-highlighter/LICENSE.syntaxes
  docker-images/syntax-highlighter/README.md
Labels: cla-signed

#34868 add sort filter panel
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
Labels: cla-signed

#34902 lib/codeintel: fix newline warning in go1.18
  lib/codeintel/tools/lsif-repl/main.go
Labels: cla-signed

#34865 Search backend: Rename `repos.ComputeExcludedRepos` to `repos.ComputeExcludedReposJob`
  enterprise/internal/codemonitors/search.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/printers_test.go
  internal/search/job/jobutil/testdata/Test_optimizeJobs/commit_with_and.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/commit_with_or.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/diff_with_and.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/diff_with_or.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_basic_expression_Zoekt_Text_Global.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_qualified_repo_with_type:symbol_expression_Zoekt_Symbol_over_repos.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos#01.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos.golden
  internal/search/job/jobutil/types.go
  internal/search/repos/excluded_job.go
Labels: cla-signed

#34801 lib/log: add logtest.NoOp
  lib/log/logtest/logtest.go
Labels: cla-signed

#34793 doc/dev: refresh logging, migrate observability to docsite
  doc/_resources/assets/redirects
  doc/admin/observability/logs.md
  doc/dev/background-information/observability/index.md
  doc/dev/how-to/add_logging.md
  doc/dev/how-to/add_observability.md
  doc/dev/how-to/index.md
  doc/dev/index.md
  internal/observation/observation.go
Labels: cla-signed

#34866 Search backend: Rename `run.RepoSearch` to `run.RepoSearchJob`
  enterprise/internal/codemonitors/search_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/printers_test.go
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_basic_expression_Zoekt_Text_Global.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos#01.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos.golden
  internal/search/job/jobutil/types.go
  internal/search/run/repo_has_file.go
  internal/search/run/repository.go
  internal/search/run/repository_test.go
Labels: cla-signed

#34903 changelog: document upgrade to alpine 3.14
  CHANGELOG.md
Labels: cla-signed

#34906 docker-images: remove alpine-3.12
  doc/dev/background-information/ci/reference.md
  docker-images/alpine-3.12/Dockerfile
  docker-images/alpine-3.12/README.md
  docker-images/alpine-3.12/build.sh
  enterprise/dev/ci/images/images.go
Labels: cla-signed

#34855 dev/sg: add logging migration linter, add repo.State to lint.Runner
  dev/sg/internal/lint/lint.go
  dev/sg/internal/repo/repo.go
  dev/sg/lints.go
  dev/sg/sg_lint.go
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#34908 Search backend: Append "Job" to job names in `searcher` package
  enterprise/internal/codemonitors/search_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/printers_test.go
  internal/search/job/jobutil/repo_pager_job.go
  internal/search/job/jobutil/repo_pager_job_test.go
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_qualified_repo_with_type:symbol_expression_Zoekt_Symbol_over_repos.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos#01.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos.golden
  internal/search/job/jobutil/types.go
  internal/search/run/repo_has_file.go
  internal/search/searcher/client.go
  internal/search/searcher/search.go
  internal/search/searcher/symbol_search_job.go
  internal/search/structural/structural.go
  internal/search/textsearch/textsearch_test.go
Labels: cla-signed

#34155 workerutil: migrate to lib/log
  cmd/repo-updater/shared/main.go
  enterprise/cmd/executor/internal/worker/handler.go
  enterprise/cmd/executor/internal/worker/handler_test.go
  enterprise/cmd/executor/main.go
  enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/handler_test.go
  enterprise/cmd/precise-code-intel-worker/internal/worker/worker.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/worker/internal/batches/workers/batch_spec_workspace_creator.go
  enterprise/cmd/worker/internal/batches/workers/bulk_processor_worker.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler_test.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go
  enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler_test.go
  enterprise/cmd/worker/internal/insights/job.go
  enterprise/cmd/worker/internal/insights/query_runner_job.go
  enterprise/internal/batches/reconciler/reconciler.go
  enterprise/internal/batches/reconciler/reconciler_test.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/worker.go
  internal/repos/main_test.go
  internal/repos/sync_worker_test.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
  internal/workerutil/handler.go
  internal/workerutil/logger.go
  internal/workerutil/main_test.go
  internal/workerutil/mock_handler_test.go
  internal/workerutil/mock_with_hooks_test.go
  internal/workerutil/mock_with_predequeue_test.go
  internal/workerutil/observability.go
  internal/workerutil/worker.go
  internal/workerutil/worker_test.go
  lib/log/fields.go
Labels: cla-signed

#34923 Search backend: Append "Job" to job names in package `zoekt`
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/printers_test.go
  internal/search/job/jobutil/repo_pager_job.go
  internal/search/job/jobutil/repo_pager_job_test.go
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_basic_expression_Zoekt_Text_Global.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_qualified_repo_with_type:symbol_expression_Zoekt_Symbol_over_repos.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos#01.golden
  internal/search/job/jobutil/testdata/Test_optimizeJobs/optimize_repo-qualified_expression_Zoekt_Text_over_repos.golden
  internal/search/job/jobutil/types.go
  internal/search/run/repo_has_file.go
  internal/search/textsearch/textsearch_test.go
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
  internal/search/zoekt/symbol_search_job.go
Labels: cla-signed

#34926 dev/sg: migrate hadolint script to sg, add shared download.Executable
  .hadolint.yaml
  dev/check/docker-lint.sh
  dev/sg/internal/download/download.go
  dev/sg/lints.go
  dev/sg/sg_lint.go
  dev/sg/sg_update.go
  doc/dev/background-information/ci/index.md
  go.mod
  go.sum
Labels: cla-signed

#34924 Search backend: Return "RepoPagerJob" from (jobutil.repoPagerJob).Name()
  internal/search/job/jobutil/repo_pager_job.go
Labels: cla-signed

#34910 tweak padding of series filter panel
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
Labels: merge-on-any-approve, cla-signed

#34935 chore: refactor CommitSearchResultMatch into a functional component
  client/search-ui/src/components/CommitSearchResultMatch.tsx
  client/shared/src/components/Markdown.tsx
Labels: cla-signed

#34944 Search backend: Format output of (search.RepoOptions).String()
  internal/search/types.go
Labels: cla-signed

#34783 Code Insights: [FE] Add scaffolding for the insight standalone page
  client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
  client/web/src/enterprise/insights/CodeInsightsRouter.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/BuiltInInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/SmartInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.test.tsx
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.story.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/CodeInsightsGettingStartedPage.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-templates/CodeInsightsTemplates.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-templates/constants.ts
Labels: cla-signed

#34931 doc/cli: use latest release of src-cli
  doc/cli/references/doc.go
Labels: cla-signed

#34956 web: integrate `@sourcegraph/stylelint-plugin-sourcegraph` and ban `bootstrap` imports
  .stylelintrc.json
  client/branded/.stylelintrc.json
  client/branded/src/global-styles/dropdown.scss
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/popover.scss
  client/branded/src/global-styles/typography.scss
  client/browser/.stylelintrc.json
  client/browser/src/app.scss
  client/jetbrains/.stylelintrc.json
  client/shared/.stylelintrc.json
  client/stylelint-plugin-sourcegraph/README.md
  client/stylelint-plugin-sourcegraph/lib/index.js
  client/stylelint-plugin-sourcegraph/lib/rules/filenames-match-regex.js
  client/stylelint-plugin-sourcegraph/package.json
  client/vscode/.stylelintrc.json
  client/vscode/src/webview/forkedBranded.scss
  client/web/.stylelintrc.json
  client/web/src/search/home/LoggedOutHomepage.module.scss
  client/wildcard/.stylelintrc.json
  package.json
  yarn.lock
Labels: team/frontend-platform, cla-signed

#34883 Code Insights: Add header actions to the insight standalone page
  client/web/src/enterprise/insights/components/insights-view-grid/components/BuiltInInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/ConfirmDeleteModal.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/ConfirmRemoveModal.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
  client/web/src/enterprise/insights/components/modals/ConfirmDeleteModal.tsx
  client/web/src/enterprise/insights/components/modals/ConfirmationModal/ConfirmationModal.tsx
  client/web/src/enterprise/insights/components/modals/ConfirmationModal/index.ts
  client/web/src/enterprise/insights/hooks/use-copy-url-handler.ts
  client/web/src/enterprise/insights/hooks/use-delete-insight.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/actions/CodeInsightIndependentPageActions.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/components/actions/CodeInsightIndependentPageActions.tsx
  client/wildcard/src/components/PageHeader/PageHeader.module.scss
  client/wildcard/src/components/PageHeader/PageHeader.tsx
Labels: cla-signed

#34897 actions: update github workflows to use go1.18
  .github/workflows/buildchecker-history.yml
  .github/workflows/buildchecker.yml
  .github/workflows/licenses-check.yml
  .github/workflows/licenses-update.yml
  .github/workflows/lsif-typescript.yml
  .github/workflows/pr-auditor.yml
  .github/workflows/sg-binary-release.yml
  dev/pr-auditor/batch-changes/pr-auditor-patch.yml
  dev/pr-auditor/batch-changes/pr-auditor-rollout.yml
Labels: cla-signed

#34957 Accessibility: Add tips for fixing common screen reader problems
  doc/dev/background-information/web/accessibility/how-to-screen-reader.md
Labels: accessibility, docs, cla-signed

#34964 web: fix insights checkbox label
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
Labels: team/frontend-platform, cla-signed

#34886 repos: Introduce Python dependency repos integration
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
  client/web/src/enterprise/batches/settings/CodeHostSshPublicKey.tsx
  client/web/src/site-admin/SiteAdminReportBugPage.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/gitserver/main.go
  cmd/gitserver/server/testdata/golden/requests.json
  cmd/gitserver/server/testdata/vcr/requests.yaml
  cmd/gitserver/server/vcs_syncer_python_packages.go
  cmd/gitserver/server/vcs_syncer_python_packages_test.go
  dev/gqltest/search_test.go
  internal/codeintel/dependencies/consts.go
  internal/codeintel/dependencies/shared/consts.go
  internal/conf/reposource/python_packages.go
  internal/database/external_services.go
  internal/database/repos.go
  internal/extsvc/codehost.go
  internal/extsvc/pypi/client.go
  internal/extsvc/pypi/client_test.go
  internal/extsvc/types.go
  internal/repos/clone_url.go
  internal/repos/python_packages.go
  internal/repos/python_packages_test.go
  internal/repos/sources.go
  internal/repos/testdata/sources/TestPythonPackageSource_ListRepos
  internal/repos/testdata/sources/TestPythonPackageSource_ListRepos.yaml
  internal/types/secret.go
  internal/types/secret_test.go
  schema/python-packages.schema.json
  schema/schema.go
  schema/stringdata.go
Labels: cla-signed

#34982 ci: invalidate asdf cache before using it
  dev/ci/asdf-install.sh
Labels: cla-signed

#34986 codeintel: Remove a full read from gitserver archive in inference service
  internal/codeintel/autoindexing/internal/inference/service.go
  internal/codeintel/autoindexing/internal/inference/service_test.go
  internal/codeintel/autoindexing/internal/inference/util.go
  internal/codeintel/dependencies/internal/lockfiles/service_test.go
  internal/unpack/unpacktest/pack.go
Labels: team/code-intelligence, cla-signed

#34920 [SG-34403.7] Improve Percy + accessibilityAudit test coverage on `Contributors Page`
  client/web/src/integration/graphQlResponseHelpers.ts
  client/web/src/integration/nav.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
Labels: gitstart, cla-signed

#34929 dev/sg: add linter for preventing certain dependencies from being upgraded
  dev/sg/lints.go
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#34942 dev/sg: unify ExternalSecrets with secrets store, minor fixes for frontend-e2e
  dev/sg/internal/run/command.go
  dev/sg/internal/run/run.go
  dev/sg/internal/secrets/secret.go
  dev/sg/internal/secrets/store.go
  sg.config.yaml
Labels: cla-signed

#34995 dev/sg: force push by default with runtype builds, increase timeout
  dev/sg/sg_ci.go
Labels: cla-signed

#34998 symbols: go-build only builds target binary
  cmd/symbols/Dockerfile
  cmd/symbols/build.sh
  cmd/symbols/go-build.sh
Labels: cla-signed

#35002 ci: run asdf in compare-hash
  enterprise/dev/ci/scripts/compare-hash.sh
Labels: cla-signed

#34911 Code Insights: Implement a special layout mode for the drill down filter panel
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightCreationForm.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightFilters.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightFilters.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightFilters.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/filter-collapse-section/FilterCollapseSection.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/filter-collapse-section/FilterCollapseSection.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.tsx
Labels: cla-signed

#35001 Ignore fmt.Fprintf() return values in RepoOptions.String()
  internal/search/types.go
Labels: cla-signed

#35004 all: pin golang builder layers to go1.18.1
  cmd/symbols/Dockerfile
  internal/cmd/git-combine/Dockerfile
  internal/cmd/progress-bot/Dockerfile
  internal/cmd/resources-report/Dockerfile
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed

#34997 dev/sg: add gcloud setup, fix 'setup' -> 'set up'
  dev/sg/sg_setup.go
  dev/sg/sg_setup_mac.go
  dev/sg/sg_setup_shared.go
  dev/sg/sg_setup_ubuntu.go
Labels: cla-signed

#34947 search: alias 'path:' to 'file:'
  CHANGELOG.md
  client/shared/src/search/query/filters.ts
  client/shared/src/search/query/hover.test.ts
  internal/search/query/fields.go
  internal/search/query/transformer_test.go
Labels: cla-signed

#34899 all: use go1.18
  .tool-versions
  CHANGELOG.md
  dev/sg/checks.go
  go.mod
  go.sum
Labels: cla-signed

#35016 dev/sg: do not fail on new 'log15.' reference
  dev/sg/lints.go
Labels: cla-signed

#35020 dev/sg: fix repo state diff by comparing from merge base
  dev/sg/internal/repo/repo.go
Labels: cla-signed

#35015 codeintel: Fix index of a nil Lua table
  internal/codeintel/autoindexing/internal/inference/lua/typescript.lua
Labels: team/code-intelligence, cla-signed

#34869 remove file tag from GoToRawAction
  client/web/src/repo/blob/GoToRawAction.tsx
Labels: bug, cla-signed, frontend

#34954 Repo syncer: construct stores on the fly
  cmd/repo-updater/repoupdater/server_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  internal/repos/store.go
Labels: cla-signed

#34985 extsvc/github: migrate mocks to vcr
  internal/extsvc/github/testdata/golden/ListRepositoriesForSearch
  internal/extsvc/github/testdata/vcr/ListRepositoriesForSearch.yaml
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
Labels: cla-signed

#35005 Search backend: Add trace tags to ComputeExcludedReposJob
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/printers_test.go
  internal/search/repos/excluded_job.go
Labels: cla-signed

#34949 search: tasteful updates to 'language:' filter
  CHANGELOG.md
  client/shared/src/search/query/filters.ts
  doc/code_search/reference/queries.md
Labels: cla-signed

#35022 generics: make MemoizedConstructor generic
  cmd/worker/memo/memo.go
  cmd/worker/workerdb/db.go
  enterprise/cmd/worker/internal/batches/dbstore.go
  enterprise/cmd/worker/internal/codeintel/clients.go
  enterprise/cmd/worker/internal/codeintel/codeinteldb.go
  enterprise/cmd/worker/internal/codeintel/dbstore.go
  enterprise/cmd/worker/internal/codeintel/lsifstore.go
  enterprise/cmd/worker/internal/executorqueue/config.go
Labels: go, cla-signed, generics

#35024 codeintel: Add `-allow-dirty-instance` to codeintel-qa test
  dev/codeintel-qa/cmd/query/main.go
  dev/codeintel-qa/cmd/query/queries.go
  dev/codeintel-qa/cmd/query/state.go
Labels: team/code-intelligence, cla-signed

#34664 Batches: Fix minor accessibility issues
  client/web/src/enterprise/batches/preview/list/PreviewFilterRow.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
Labels: cla-signed

#35026 extsvc/github: delete mock function
  internal/extsvc/github/common.go
Labels: cla-signed

#35023 bacthes: change r to repository for onquery or on repo error func
  lib/batches/batch_spec.go
Labels: team/batchers, cla-signed

#33625 batches: change filename in diffnode from link to plain text
  client/web/src/components/diff/FileDiffNode.tsx
Labels: team/batchers, cla-signed

#34965 Code Insights: Add insight card to the standalone page
  client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/hooks/use-insight-data.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-backend-insight-data/get-backend-insight-data.ts
  client/web/src/enterprise/insights/hooks/use-parallel-requests/use-parallel-request.ts
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/SmartStandaloneInsight.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/context-menu/StandaloneInsightContextMenu.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/components/context-menu/StandaloneInsightContextMenu.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-runtime-insight/StandaloneRuntimeInsight.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-runtime-insight/StandaloneRuntimeInsight.tsx
Labels: cla-signed

#34984 repoupdater: do not initialize database twice
  cmd/repo-updater/repoupdater/server.go
Labels: cla-signed

#34698 bext: fix git-extras extension blame for selected lines issue on the code hosts
  client/browser/CHANGELOG.md
  client/browser/src/shared/code-hosts/bitbucket-cloud/codeHost.test.ts
  client/browser/src/shared/code-hosts/bitbucket-cloud/codeHost.ts
  client/browser/src/shared/code-hosts/bitbucket/codeHost.test.ts
  client/browser/src/shared/code-hosts/bitbucket/codeHost.tsx
  client/browser/src/shared/code-hosts/github/codeHost.test.ts
  client/browser/src/shared/code-hosts/github/codeHost.tsx
  client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts
  client/browser/src/shared/code-hosts/gitlab/codeHost.ts
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
Labels: cla-signed

#34709 Improve Percy + accessibilityAudit `View Extension Detail Page` and `Extension Create Form Page`
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
  client/web/src/extensions/extension/ExtensionAreaHeader.tsx
  client/web/src/extensions/extension/RegistryExtensionOverviewPage.tsx
  client/web/src/extensions/extension/RegistryExtensionReadme.tsx
  client/web/src/extensions/extension/__snapshots__/RegistryExtensionOverviewPage.test.tsx.snap
  client/web/src/integration/extension-registry.test.ts
Labels: gitstart, cla-signed

#35047 dev: Make zoekt services listen on 127.0.0.1
  sg.config.yaml
Labels: cla-signed

#35052 Search backend: fix user-facing error strings
  internal/search/run/run.go
  internal/search/run/run_test.go
Labels: cla-signed

#35029 Search backend: Add trace tags to RepoSearchJob
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/printers_test.go
  internal/search/run/repository.go
Labels: cla-signed

#35043 Code Insights: Add filters section to standalone page (backend insight)
  client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
  client/web/src/enterprise/insights/components/form/hooks/use-async-insight-title-validator.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/DrillDownInsightCreationForm.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/utils.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/validators.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/index.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/index.ts
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.module.scss
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
Labels: cla-signed

#35032 dev/okay: add metrics constructors, make UniqueKeys and Properties required
  dev/okay/event.go
  dev/okay/metric.go
  dev/okay/okay.go
  dev/okay/okay_test.go
Labels: cla-signed

#34618 changelog: Add entry for search-based locals
  CHANGELOG.md
Labels: cla-signed

#35013 Code monitors: fix repo-aware creation of code monitors
  enterprise/internal/codemonitors/search.go
  enterprise/internal/codemonitors/search_test.go
  internal/search/job/jobutil/alert.go
  internal/search/job/jobutil/combinators.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/mapper.go
  internal/search/job/jobutil/printers.go
  internal/search/job/jobutil/types.go
Labels: cla-signed

#34573 doc: add info about user/repo pending permissions
  doc/admin/repo/permissions.md
Labels: team/repo-management, cla-signed

#35048 batches: fix error handling for github CreateChangeset
  CHANGELOG.md
  internal/extsvc/github/common.go
Labels: bug, cla-signed

#35056 Code monitors: small roundtrip optimization
  enterprise/internal/codemonitors/search.go
Labels: cla-signed

#35021 Code monitors: add transition step to switch over to repo-aware monitors
  enterprise/internal/codemonitors/search.go
  enterprise/internal/database/code_monitor_last_searched.go
  enterprise/internal/database/code_monitor_last_searched_test.go
  enterprise/internal/database/code_monitors.go
  enterprise/internal/database/mocks.go
Labels: cla-signed

#34890 codemirror: Fix initial pattern type not being recognized
  client/search-ui/src/input/CodeMirrorQueryInput.tsx
  client/search-ui/src/input/extensions/parsedQuery.ts
Labels: cla-signed

#35010 insights: allow commit indexer to continue if it attempts to record the same commit twice
  enterprise/internal/insights/compression/commits.go
  enterprise/internal/insights/compression/commits_test.go
Labels: cla-signed

#35062 Product Education: Add some redirect links to address recent doc changes
  doc/_resources/assets/redirects
Labels: cla-signed

#35065 Add changelog entry for batch changes on docker compose
  CHANGELOG.md
Labels: cla-signed

#35051 codeintel: Add file content limits to inference service
  internal/codeintel/autoindexing/internal/inference/init.go
  internal/codeintel/autoindexing/internal/inference/service.go
  internal/codeintel/autoindexing/internal/inference/service_test.go
Labels: team/code-intelligence, cla-signed

#35066 batches: update PAT label for Bitbucket Cloud
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
Labels: team/batchers, cla-signed

#35067 Update release tool to update new doc directory location
  dev/release/src/release.ts
Labels: cla-signed

#35068 codeintel: Respond to missed inference service feedback
  internal/codeintel/autoindexing/internal/inference/init.go
  internal/codeintel/autoindexing/internal/inference/service.go
Labels: team/code-intelligence, cla-signed

#35073 Add Randell to batches-notify.yml
  .github/workflows/batches-notify.yml
Labels: cla-signed

#35081 Self-hosted executors only
  doc/batch_changes/explanations/server_side.md
Labels: cla-signed

#34806 search: make search expr heuristic more strict to avoid confusion
  internal/search/query/parser_test.go
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
Labels: cla-signed

#35064 Code monitors: ignore context errors
  enterprise/internal/codemonitors/search.go
  internal/search/commit/commit.go
  lib/errors/filter.go
Labels: cla-signed

#34693 gitserver: List purgeable repos from the database
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/mocks.go
  internal/database/repos.go
  internal/repos/purge.go
  internal/types/types.go
Labels: team/repo-management, cla-signed

#35049 repo-updater: Delete repos that are unavailable for legal reasons
  internal/errcode/code.go
  internal/extsvc/github/v3.go
  internal/repos/syncer.go
Labels: team/repo-management, cla-signed

#35038 dx: enable VSCode search for `.go` files inside of the `ui/assets/` folder
  .vscode/settings.json
Labels: team/frontend-platform, dx, cla-signed

#34905 insights: migrate compute search to the streaming endpoint
  CHANGELOG.md
  enterprise/cmd/frontend/internal/compute/streaming/stream.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/queryrunner/worker.go
  enterprise/internal/insights/query/capture_group_executor.go
  enterprise/internal/insights/query/streaming/decoder.go
Labels: cla-signed

#35097 Migrations <Icon /> accessibility: `client/browser`, `client/branded`, `client/jetbrains`, `client/vscode`
  client/branded/src/components/panel/TabbedPanelContent.tsx
  client/branded/src/components/panel/views/EmptyPanelView.tsx
  client/branded/src/components/panel/views/ExtensionsLoadingView.tsx
  client/branded/src/components/panel/views/FileLocations.tsx
  client/browser/src/browser-extension/after-install-page/AfterInstallPageContent.tsx
  client/browser/src/browser-extension/options-menu/OptionsPage.tsx
  client/jetbrains/webview/src/search/results/FileSearchResult.tsx
  client/vscode/src/webview/search-panel/RepoView.tsx
  client/vscode/src/webview/search-panel/components/SearchResultsInfoBar.tsx
  client/vscode/src/webview/sidebars/history/components/RecentFilesSection.tsx
  client/vscode/src/webview/sidebars/history/components/RecentRepositoriesSection.tsx
  client/vscode/src/webview/sidebars/history/components/RecentSearchesSection.tsx
  client/vscode/src/webview/sidebars/history/components/SavedSearchesSection.tsx
  client/wildcard/src/components/Icon/Icon.story.tsx
  client/wildcard/src/components/Icon/Icon.tsx
Labels: gitstart, cla-signed

#35100 permissions: Remove some code duplication using generics
  enterprise/internal/database/perms_store.go
Labels: team/repo-management, cla-signed

#34960 Improve Percy + accessibilityAudit test coverage on `commits Page`
  client/web/src/integration/repository.test.ts
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/commits/RepositoryCommitsPage.tsx
  client/web/src/repo/tree/TreePageContent.tsx
Labels: gitstart, cla-signed

#35014 insights: refactor- update insight view resolver to always preload series data
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/resolvers/dynamic_insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_connection_resolver_test.go
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_series_resolver_test.go
  enterprise/internal/insights/resolvers/insight_view_resolvers_test.go
Labels: cla-signed
