Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-09, with the labels that each got.

#39728 [SG-39284] Upgrade yarn to the latest version
  .buildkite/pipeline.async.yml
  .github/workflows/scip-typescript.yml
  .gitignore
  .tool-versions
  .vscode/tasks.json
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.2.3.cjs
  .yarnrc
  .yarnrc.yml
  client/branded/package.json
  client/browser/gulpfile.js
  client/browser/package.json
  client/browser/scripts/test-integration.js
  client/build-config/package.json
  client/client-api/package.json
  client/codeintellify/package.json
  client/common/package.json
  client/extension-api-types/package.json
  client/extension-api/package.json
  client/http-client/package.json
  client/jetbrains/package.json
  client/observability-client/package.json
  client/observability-server/package.json
  client/search-ui/package.json
  client/search/package.json
  client/shared/dev/generateCssModulesTypes.js
  client/shared/package.json
  client/shared/src/testing/driver.ts
  client/storybook/README.md
  client/storybook/package.json
  client/template-parser/package.json
  client/vscode/CONTRIBUTING.md
  client/vscode/package.json
  client/web/package.json
  client/wildcard/package.json
  cmd/frontend/pre-build.sh
  dev/check/yarn-deduplicate.sh
  dev/ci/yarn-build.sh
  dev/ci/yarn-install-with-retry.sh
  dev/ci/yarn-run.sh
  dev/ci/yarn-test.sh
  dev/release/.yarn/install-state.gz
  dev/release/package.json
  dev/release/yarn.lock
  dev/sg/dependencies/helpers.go
  dev/sg/linters/svg.go
  dev/sg/sg.config.example.yaml
  doc/code_navigation/explanations/auto_indexing_inference.md
  doc/dev/background-information/ci/development.md
  doc/dev/background-information/web/web_app.md
  doc/dev/how-to/cache_ci_artefacts.md
  doc/dev/how-to/ci_soft_failure_and_still_notify.md
  enterprise/cmd/frontend/pre-build.sh
  enterprise/dev/ci/internal/ci/cache_helpers.go
  enterprise/dev/ci/internal/ci/operations.go
  package.json
  sg.config.yaml
  yarn.lock
Labels: team/frontend-platform, gitstart, cla-signed

#41102 [P&P] Display storage warning when repo storage almost full or exceeded
  client/web/src/jscontext.ts
  client/web/src/site-admin/SiteAdminRepositoriesPage.tsx
  cmd/frontend/graphqlbackend/site_alerts.go
  cmd/frontend/hooks/hooks.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/cmd/frontend/internal/licensing/init/init.go
Labels: cla-signed, team/iam

#41126 status messages: change to admin-only, remove old code
  cmd/frontend/graphqlbackend/status_messages.go
  cmd/frontend/graphqlbackend/status_messages_test.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/mocks_temp.go
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
Labels: cla-signed

#41052 sg: add sg page to automate alerts creation
  dev/sg/main.go
  dev/sg/sg_page.go
  doc/dev/background-information/sg/reference.md
  go.mod
  go.sum
Labels: sg, team/devx, cla-signed

#40028 ci: run linters on yaml and json files
  enterprise/dev/ci/internal/ci/changed/diff.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: ci, team/devx, cla-signed

#40936 doc: document how to configure OpenTelemetry and update Kubernetes (no Helm)
  CHANGELOG.md
  doc/admin/deploy/kubernetes/configure.md
  doc/admin/observability/index.md
  doc/admin/observability/opentelemetry.md
  doc/admin/observability/tracing.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#41163 ci: upsert license key for backend integration tests
  dev/ci/integration/backend/run.sh
  dev/gqltest/main_test.go
  dev/run-server-image.sh
  internal/gqltestutil/product_subscription.go
Labels: cla-signed, team/iam

#41185 status messages: remove cloud-v1 user notification tracking
  client/web/src/nav/StatusMessagesNavItem.tsx
Labels: cla-signed

#41178 docs: how to sample traces with the open telemetry collector
  doc/admin/deploy/kubernetes/configure.md
  doc/admin/observability/opentelemetry.md
Labels: team/devx, cla-signed, opentelemetry

#41164 web: add `Analyzing the Bundlesize check failure` docs
  .gitignore
  client/build-config/src/webpack/plugins.ts
  client/web/dev/utils/environment-config.ts
  client/web/webpack.config.js
  doc/dev/how-to/testing.md
Labels: docs, team/frontend-platform, dx, cla-signed

#40772 Add feature flag to disable proactive aggregation insights
  client/search-ui/src/index.ts
  client/shared/dev/generateGraphQlOperations.js
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/integration/context.ts
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/helpers.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/components/aggregation/AggregationChart.tsx
  client/web/src/search/results/components/aggregation/AggregationChartCard.module.scss
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/AggregationModeControls.module.scss
  client/web/src/search/results/components/aggregation/AggregationModeControls.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.module.scss
  client/web/src/search/results/components/aggregation/SearchAggregationResult.story.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/constants.ts
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/components/aggregation/index.ts
  client/web/src/search/results/components/aggregation/types.ts
  client/web/src/search/results/sidebar/SearchAggregations.module.scss
  client/web/src/search/results/sidebar/SearchAggregations.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
  client/wildcard/src/components/Charts/components/bar-chart/components/GroupedBars.tsx
Labels: cla-signed

#41100 Allow external service card to be disabled with required tiers
  client/web/src/components/externalServices/AddExternalServicePage.tsx
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/components/externalServices/ExternalServiceCard.tsx
  client/web/src/jscontext.ts
  enterprise/cmd/frontend/internal/licensing/enforcement/external_services.go
  enterprise/cmd/frontend/internal/licensing/enforcement/external_services_test.go
Labels: cla-signed, team/iam

#41176 otel: bundle probabilistic sampling processor
  docker-images/opentelemetry-collector/builder.template.yaml
Labels: team/devx, cla-signed, opentelemetry

#41147 insights: fix not available reasonType schema type
  cmd/frontend/graphqlbackend/insights_aggregations.graphql
Labels: cla-signed

#41085 codeintel: Handle ConfigurationPolicy nil case
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/util.go
Labels: cla-signed

#41148 internal/trace: remove ENABLE_GRAFANA_CLOUD_TRACE_URL
  internal/trace/url.go
Labels: cla-signed

#41190 Update FPT issue/PR automation
  .github/teams.yml
  .github/workflows/label-notify.yml
Labels: team/frontend-platform, cla-signed

#41090 batches: Batch spec list improvements
  client/web/src/enterprise/batches/BatchSpecNode.tsx
  client/web/src/enterprise/batches/backend.ts
  client/web/src/enterprise/batches/testData.ts
  client/web/src/integration/batches.test.ts
Labels: cla-signed

#41210 insights: disable aggregation types that don't work
  enterprise/internal/insights/aggregation/aggregation.go
  enterprise/internal/insights/resolvers/aggregates_resolvers.go
  enterprise/internal/insights/resolvers/aggregates_resolvers_test.go
Labels: cla-signed

#41159 upgrades: Support 3.20 -> 4.0
  internal/database/migration/cliutil/run_oobmigrations.go
  internal/database/migration/shared/types.go
  internal/database/migration/shared/upgradedata/cmd/generator/consts.go
  internal/database/migration/shared/upgradedata/stitched-migration-graph.json
  internal/database/migration/stitch/git.go
  internal/database/migration/stitch/rewriter.go
  internal/database/migration/stitch/stitch.go
  internal/database/migration/store/store_test.go
Labels: cla-signed, rfc-697, rfc-697-testing

#40877 lucky search: initial styling work
  client/shared/src/search/stream.ts
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/search/suggestion/DidYouMean.tsx
  client/web/src/search/suggestion/LuckySearch.tsx
  client/web/src/search/suggestion/QuerySuggestion.module.scss
  cmd/frontend/graphqlbackend/search_query_description.go
  internal/search/lucky/feeling_lucky_search_job.go
  internal/search/lucky/feeling_lucky_search_job_test.go
Labels: cla-signed

#41217 lib: upgrade github.com/sourcegraph/log
  go.mod
  go.sum
  lib/go.mod
  lib/go.sum
Labels: cla-signed

#41221 dev/sg: rename cloud to dotcom in sg live
  dev/sg/live.go
  dev/sg/sg_live.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#41219 dev/sg: only list commits if deployment is found in sg live
  dev/sg/live.go
  dev/sg/sg_live.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#41226 dev/sg: remove unused import
  dev/sg/sg_live.go
Labels: cla-signed

#41225 migrator: Backfill drift schema to 3.20
  internal/database/migration/cliutil/drift-schemas/.gitignore
  internal/database/migration/cliutil/drift-schemas/generate-all.sh
  internal/database/migration/cliutil/drift-schemas/generate.sh
Labels: cla-signed, rfc-697, rfc-697-testing

#41150 licensing: fix setup for creating license keys locally and for testing features in a local instance
  enterprise/internal/license/generate-license.go
  sg.config.yaml
Labels: cla-signed, team/iam

#41228 Remove Justin from label notifications
  .github/workflows/label-notify.yml
Labels: cla-signed

#41229 search: Remove `file:contains()`
  CHANGELOG.md
  client/shared/src/search/query/metrics.test.ts
  client/shared/src/search/query/metrics.ts
  client/shared/src/search/query/predicates.test.ts
  client/shared/src/search/query/predicates.ts
  dev/gqltest/search_test.go
  doc/code_insights/explanations/automatically_generated_data_series.md
  internal/search/job/jobutil/job.go
  internal/search/query/predicate.go
Labels: cla-signed

#41227 insights: Truncate capture group matches to 100 characters
  enterprise/internal/insights/aggregation/aggregation.go
  enterprise/internal/insights/aggregation/aggregation_test.go
Labels: cla-signed

#41034 doc/admin: document docker-compose otel-collector and optional jaeger
  doc/admin/deploy/docker-compose/operations.md
  doc/admin/deploy/kubernetes/configure.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#41240 dev/release: remove random punctuation
  dev/release/src/update.ts
Labels: cla-signed

#41186 docs/ci: add additional wording about adding secrets to the ci pipeline
  doc/dev/background-information/ci/development.md
Labels: cla-signed

#41184 log15 migration: migrate log15 usage in frontend/backend (+friends) to sourcegraph/log
  cmd/frontend/backend/external_services.go
  cmd/frontend/backend/inventory.go
  cmd/frontend/backend/repos.go
  cmd/frontend/backend/repos_test.go
  cmd/frontend/backend/repos_vcs.go
  cmd/frontend/backend/user_emails.go
  cmd/frontend/backend/user_emails_test.go
  cmd/frontend/graphqlbackend/access_tokens.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_stats_languages.go
  cmd/frontend/graphqlbackend/set_external_service_repos.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_emails.go
  cmd/frontend/internal/auth/userpasswd/reset_password.go
  enterprise/cmd/frontend/internal/auth/githuboauth/config.go
  enterprise/cmd/frontend/internal/auth/githuboauth/config_test.go
  enterprise/cmd/frontend/internal/auth/githuboauth/middleware_test.go
  enterprise/cmd/frontend/internal/auth/githuboauth/provider.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/config.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/config_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/provider.go
  enterprise/cmd/frontend/internal/auth/init.go
  enterprise/cmd/frontend/internal/auth/oauth/session.go
  enterprise/cmd/frontend/main.go
Labels: cla-signed, migration/log

#41234 Aggregation: Adjust aggregation url params
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/results/components/aggregation/constants.ts
  client/web/src/search/results/components/aggregation/hooks.ts
Labels: cla-signed

#41249 Tooltip: Add additional documentation around component triggers
  client/wildcard/src/components/Tooltip/Tooltip.tsx
Labels: team/frontend-platform, cla-signed

#41160 insights: add 4.0 docs scaffolding
  doc/code_insights/explanations/search_results_aggregations.md
  doc/code_insights/index.md
Labels: cla-signed

#41215 Migrate StatusMessagesNavItem to be function component
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/StatusMessagesNavItem.mocks.ts
  client/web/src/nav/StatusMessagesNavItem.story.tsx
  client/web/src/nav/StatusMessagesNavItem.test.tsx
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/nav/StatusMessagesNavItemQueries.ts
  client/web/src/nav/__snapshots__/StatusMessagesNavItem.test.tsx.snap
Labels: cla-signed

#40781 admin-analytics: change "Unique users / Active users" to use registered users count instead of anonymous count
  client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/queries.ts
  client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsExtensionsPage/queries.ts
  client/web/src/site-admin/analytics/AnalyticsNotebooksPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsNotebooksPage/queries.ts
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/queries.ts
  client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsSearchPage/queries.ts
  client/web/src/site-admin/analytics/AnalyticsUsersPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsUsersPage/queries.ts
  client/web/src/site-admin/analytics/useChartFilters.ts
Labels: cla-signed, team/admin-analytics

#41252 Move wildcard/Calendar to web/site-admin/user-management dir
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/Calendar/Calendar.module.scss
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/Calendar/Calendar.tsx
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/Calendar/index.ts
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/DateRangeSelect.tsx
  client/wildcard/src/components/Calendar/Calendar.story.tsx
  client/wildcard/src/components/index.ts
Labels: cla-signed

#41238 oobmigration: Update UI to handle warnings for 3.43 -> 4.0 transition
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
Labels: cla-signed, rfc-697, rfc-697-testing

#41261 executors: Bump sourcegraph/ignite to 0.10.4
  enterprise/cmd/executor/vm-image/install.sh
Labels: cla-signed

#41254 status messages: change text to make it easier to digest
  client/web/src/nav/StatusMessagesNavItem.mocks.ts
  client/web/src/nav/StatusMessagesNavItem.module.scss
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/nav/StatusMessagesNavItemQueries.ts
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
Labels: cla-signed

#40830 Fix `ButtonGroup` styles for disabled buttons w/ `Tooltip`
  client/wildcard/src/components/Button/Button.module.scss
  client/wildcard/src/components/Button/story/Button.story.tsx
Labels: team/frontend-platform, cla-signed

#41244 cmd/server: remove jaeger, disable opentelemetry by default
  CHANGELOG.md
  cmd/server/build.sh
  cmd/server/jaeger.sh
  cmd/server/shared/observability.go
  cmd/server/shared/shared.go
  doc/admin/deploy/docker-single-container/index.md
Labels: team/devx, cla-signed, devx/otel-default

#41243 otlp: treat OTEL_EXPORTER_OTLP_ENDPOINT='' as OpenTelemetry being disabled
  cmd/frontend/internal/app/debug.go
  internal/otlpenv/otlpenv.go
  internal/tracer/internal/exporters/otlp.go
  internal/tracer/tracer.go
Labels: team/devx, cla-signed, devx/otel-default

#41241 changelog: consolidate OpenTelemetry collector changelog items
  CHANGELOG.md
Labels: cla-signed

#41259 cliutil: Standardize privileged operation flags
  doc/dev/background-information/sg/reference.md
  internal/database/migration/cliutil/downgrade.go
  internal/database/migration/cliutil/downto.go
  internal/database/migration/cliutil/multiversion.go
  internal/database/migration/cliutil/undo.go
  internal/database/migration/cliutil/up.go
  internal/database/migration/cliutil/upgrade.go
  internal/database/migration/cliutil/upto.go
Labels: cla-signed, rfc-697, rfc-697-testing

#41140 Update migrator doc
  doc/admin/how-to/manual_database_migrations.md
Labels: cla-signed

#41212 Aggregation: Polish up aggregation UI
  client/web/src/search/results/components/aggregation/AggregationChart.tsx
  client/web/src/search/results/components/aggregation/AggregationChartCard.module.scss
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/AggregationLimitLabel.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.module.scss
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/components/aggregation/index.ts
  client/web/src/search/results/sidebar/SearchAggregations.module.scss
  client/web/src/search/results/sidebar/SearchAggregations.tsx
  client/wildcard/src/components/Charts/components/bar-chart/BarChart.tsx
  client/wildcard/src/components/Charts/components/bar-chart/components/GroupedBars.module.scss
  client/wildcard/src/components/Charts/core/components/SvgRoot.tsx
  client/wildcard/src/components/Charts/core/components/axis/Axis.tsx
Labels: cla-signed

#41288 simple ui: add back search reference panel (again)
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
Labels: cla-signed

#40698 Adding info on how to add critical telemetry
  doc/dev/background-information/adding_ping_data.md
Labels: cla-signed

#41021 search ui: permanently enable simple ui (but keep temp setting)
  CHANGELOG.md
  client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
  client/search-ui/src/components/ResultContainer.tsx
  client/search-ui/src/results/progress/StreamingProgress.story.tsx
  client/search-ui/src/results/progress/StreamingProgressSkippedButton.test.tsx
  client/search-ui/src/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/search-ui/src/results/sidebar/SidebarButtonStrip.tsx
  client/shared/src/search/stream.ts
  client/shared/src/settings/CoreWorkflowImprovementsEnabledProvider.tsx
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/shared/src/settings/useCoreWorkflowImprovementsEnabled.ts
  client/storybook/src/preview.ts
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/nav/UserNavItem.tsx
  client/web/src/search/home/SearchPage.story.tsx
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
Labels: cla-signed

#40681 analytics: Add lang breakdown to code-intel analytics page
  client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.module.scss
  client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/queries.ts
  client/web/src/site-admin/analytics/components/TimeSavedCalculatorGroup.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site_analytics.go
  internal/adminanalytics/codeintelbylanguage.go
  internal/adminanalytics/codeinteltoprepositories.go
Labels: cla-signed

#41264 doc/admin: link to deployment configuration from OpenTelemetry
  doc/admin/deploy/docker-compose/operations.md
  doc/admin/deploy/kubernetes/configure.md
  doc/admin/observability/opentelemetry.md
Labels: cla-signed

#41295 search ui: fix symbol search snapshot test
  client/search-ui/src/components/FileMatchChildren.tsx
  client/web/src/integration/search.test.ts
Labels: cla-signed

#41293 search: Add field for storing path match ranges
  client/shared/src/search/stream.ts
  internal/search/job/jobutil/select_test.go
  internal/search/result/file.go
  internal/search/streaming/http/events.go
Labels: cla-signed

#40826 licensing: add new features and checks for repo permissions
  enterprise/cmd/frontend/internal/authz/init.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/cmd/repo-updater/main.go
  enterprise/cmd/worker/main.go
  enterprise/internal/authz/authz.go
  enterprise/internal/authz/authz_test.go
  enterprise/internal/authz/bitbucketserver/authz.go
  enterprise/internal/authz/github/authz.go
  enterprise/internal/authz/github/authz_test.go
  enterprise/internal/authz/gitlab/authz.go
  enterprise/internal/authz/perforce/authz.go
  enterprise/internal/database/external_services_test.go
  enterprise/internal/licensing/data.go
  enterprise/internal/licensing/features.go
  enterprise/internal/licensing/features_test.go
Labels: cla-signed, team/iam

#41263 gomod: update zoekt for improved List performance
  go.mod
  go.sum
Labels: cla-signed

#41258 conf: cache getMode
  internal/conf/conf.go
Labels: cla-signed

#41257 authz: introduce benchmark for FilterActorPaths
  internal/authz/sub_repo_perms_test.go
Labels: cla-signed

#41300 No-op extensions controller should mark initial extensions as loaded
  client/shared/src/extensions/createNoopLoadedController.ts.ts
Labels: team/integrations, cla-signed, sunset-extensions

#41302 sg: set license generation key for codeintel-worker
  sg.config.yaml
Labels: cla-signed, team/iam

#40997 Aggregation: Add aggregation FE pings
  client/search-ui/src/results/sidebar/SearchFilterSection.module.scss
  client/search-ui/src/results/sidebar/SearchFilterSection.tsx
  client/search-ui/src/results/sidebar/SearchSidebar.tsx
  client/search-ui/src/results/sidebar/SearchSidebarSection.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/AggregationModeControls.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.story.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/index.ts
  client/web/src/search/results/components/aggregation/pings.ts
  client/web/src/search/results/sidebar/SearchAggregations.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
  client/wildcard/src/components/Charts/components/bar-chart/BarChart.tsx
  client/wildcard/src/components/Charts/components/bar-chart/BarChartContent.tsx
  client/wildcard/src/components/Charts/components/bar-chart/components/GroupedBars.tsx
  client/wildcard/src/components/Charts/components/bar-chart/components/StackedBars.tsx
  client/wildcard/src/components/Charts/components/pie-chart/PieChart.tsx
  client/wildcard/src/components/Charts/types.ts
  internal/types/types.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: cla-signed

#41272 [SG-41230] New version available "Reload to update" button lost button styles (browser native button look)
  client/web/src/SourcegraphWebApp.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#40574 [SG-40293] Extract bootstrap style import @import 'bootstrap/scss/reboot.scss'
  client/branded/src/global-styles/base.scss
  client/branded/src/global-styles/code.scss
  client/branded/src/global-styles/forms.scss
  client/branded/src/global-styles/reboot.scss
  client/branded/src/global-styles/tables.scss
  client/branded/src/global-styles/typography.scss
  client/branded/src/global-styles/utilities.scss
  client/branded/src/global-styles/variables.scss
  client/shared/src/hover/HoverOverlayContents/HoverOverlayContent/HoverOverlayContent.module.scss
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/SignUpForm.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/enterprise/batches/BatchSpec.tsx
  client/web/src/enterprise/site-admin/SiteAdminAuthenticationProvidersPage.tsx
  client/web/src/enterprise/user/settings/ExternalAccountNode.tsx
  client/web/src/org/members/InviteMemberModal.tsx
  client/web/src/org/members/OrgMembersListPage.module.scss
  client/web/src/org/members/OrgMembersListPage.tsx
  client/web/src/org/members/OrgPendingInvites.module.scss
  client/web/src/org/members/OrgPendingInvites.tsx
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/index.tsx
  client/web/src/site-admin/SiteAdminUsageStatisticsPage.tsx
  client/wildcard/src/components/Button/Button.test.tsx
  client/wildcard/src/components/Button/__snapshots__/Button.test.tsx.snap
  client/wildcard/src/components/Button/story/Button.story.tsx
Labels: team/frontend-platform, gitstart, cla-signed

#41305 gitserver: Disable colour for p4-fusion
  cmd/gitserver/server/vcs_syncer_perforce.go
Labels: team/repo-management, cla-signed

#41308 frontend: set logger for editorRequest
  cmd/frontend/internal/app/editor.go
Labels: cla-signed

#41301 log15 migration: use sourcgraph/log instead log15 for licensing logging
  enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration_test.go
  enterprise/cmd/frontend/internal/licensing/init/init.go
Labels: cla-signed, migration/log

#41306 otel: enable SQLCommenter
  go.mod
  go.sum
  internal/database/dbconn/open.go
Labels: team/devx, cla-signed, observability

#41231 executors: Publish VM image to docker hub
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexPage.story.tsx
  doc/admin/deploy_executors.md
  doc/dev/background-information/ci/reference.md
  docker-images/executor-vm/Dockerfile
  docker-images/executor-vm/README.md
  docker-images/executor-vm/autologin.conf
  docker-images/executor-vm/build.sh
  enterprise/cmd/executor/config.go
  enterprise/cmd/executor/internal/command/firecracker_test.go
  enterprise/cmd/executor/vm-image/build.sh
  enterprise/cmd/executor/vm-image/executor.json
  enterprise/cmd/executor/vm-image/ignite-ubuntu/README.md
  enterprise/cmd/executor/vm-image/install.sh
  enterprise/dev/ci/images/images.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#41320 status messages: add a tail to the popover
  client/web/src/nav/StatusMessagesNavItem.tsx
Labels: cla-signed

#40961 batches: Changeset Spec Exceeds Database Limit
  enterprise/internal/batches/store/changeset_specs.go
Labels: team/batchers, cla-signed

#41239 Update query to include case sensitive flag
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.story.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/sidebar/SearchAggregations.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.story.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
Labels: cla-signed

#41289 search docs: reflect default Standard search in query syntax
  doc/code_search/reference/queries.md
Labels: cla-signed

#41338 use theme background for get started card (Analytics)
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.module.scss
Labels: cla-signed

#41339 search: remove nodes value annotation
  internal/search/query/transformer.go
Labels: cla-signed

#41323 Add first integration tests for `repositories()` GraphQL query
  cmd/frontend/graphqlbackend/repositories_test.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed

#41313 Aggregation: Fix sidebar aggregation label rotation
  client/web/src/search/results/components/aggregation/AggregationChart.tsx
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/wildcard/src/components/Charts/components/bar-chart/BarChart.tsx
  client/wildcard/src/components/Charts/core/components/SvgRoot.tsx
Labels: cla-signed

#41343 More tiny cleanups for `repositories()` GraphQL query
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repositories_test.go
  cmd/frontend/graphqlbackend/user.go
Labels: cla-signed

#41332 log: lower log level for some less important auth errors
  cmd/frontend/internal/auth/userpasswd/handlers.go
  cmd/frontend/internal/auth/userpasswd/reset_password.go
Labels: team/devx, cla-signed, sentry, devx/logging

#41344 Insights: Fix insight storybook story
  client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx
  client/web/src/insights/utils/semantic-sort.test.ts
  client/web/src/insights/utils/semantic-sort.ts
Labels: cla-signed

#41286 Aggregation: Fix squished aggregation chart
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.story.tsx
  client/wildcard/src/components/Charts/core/components/SvgRoot.tsx
  client/wildcard/src/components/Charts/core/components/axis/Tick.tsx
Labels: cla-signed

#41321 insights: use experimental settings for aggregations instead of feature flags
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
  doc/code_insights/explanations/search_results_aggregations.md
  schema/README.md
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#41349 Aggregation: Fix aggregation cache invalidation when case sensitivity has changed
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/results/components/aggregation/hooks.ts
Labels: cla-signed

#32572 Fix BC list flashing incorrect header
  client/web/src/enterprise/batches/list/BatchChangeListFilters.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
Labels: cla-signed

#41360 authz: remove unused WithGetter
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#41356 [Admin Analytics] UI improvements
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/UsersList.tsx
  client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/index.module.scss
  client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx
  client/web/src/site-admin/analytics/useChartFilters.ts
Labels: cla-signed

#41067 upgrade: Add documentation
  doc/admin/deploy/docker-compose/operations.md
  doc/admin/deploy/docker-compose/upgrade.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/kubernetes/update.md
  doc/admin/how-to/dirty_database.md
  doc/admin/how-to/manual_database_migrations.md
  doc/admin/how-to/privileged_migrations.md
  doc/admin/how-to/rollback_database.md
  doc/admin/how-to/unfinished_migration.md
  doc/admin/index.md
  doc/admin/migration/index.md
  doc/admin/troubleshooting.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/index.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  doc/dev/background-information/oobmigrations.md
Labels: cla-signed, rfc-697, rfc-697-testing

#41265 Fix context canceled errors when triggering manual sync
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: cla-signed

#41361 authz: cache prometheus metric lookup in subrepo
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#41189 insights: document aggregations feature and limitations
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  doc/code_insights/explanations/search_results_aggregations.md
Labels: cla-signed

#41348 Update dependencies
  package.json
  yarn.lock
Labels: cla-signed

#41105 Sunset extensions: Open in Editor
  client/shared/src/actions/SimpleActionItem.module.scss
  client/shared/src/actions/SimpleActionItem.tsx
  client/shared/src/api/client/enabledExtensions.ts
  client/web/src/extensions/components/ActionItemsBar.tsx
  client/web/src/open-in-editor/OpenInEditorActionItem.tsx
  client/web/src/open-in-editor/OpenInEditorPopover.module.scss
  client/web/src/open-in-editor/OpenInEditorPopover.tsx
  client/web/src/open-in-editor/build-url.test.ts
  client/web/src/open-in-editor/build-url.ts
  client/web/src/open-in-editor/editor-settings.ts
  client/web/src/open-in-editor/editors.ts
  client/web/src/open-in-editor/migrate-legacy-settings.test.ts
  client/web/src/open-in-editor/migrate-legacy-settings.ts
  client/web/src/open-in-editor/useOpenCurrentUrlInEditor.ts
  doc/integration/editor.md
  doc/integration/img/editors/appcode.svg
  doc/integration/img/editors/atom.svg
  doc/integration/img/editors/clion.svg
  doc/integration/img/editors/custom.svg
  doc/integration/img/editors/goland.svg
  doc/integration/img/editors/idea.svg
  doc/integration/img/editors/jetbrains.svg
  doc/integration/img/editors/phpstorm.svg
  doc/integration/img/editors/pycharm.svg
  doc/integration/img/editors/rider.svg
  doc/integration/img/editors/rubymine.svg
  doc/integration/img/editors/sublime.svg
  doc/integration/img/editors/vscode.svg
  doc/integration/img/editors/webstorm.svg
  doc/integration/img/open-in-editor.svg
  doc/integration/index.md
  doc/integration/open_in_editor.md
  schema/schema.go
  schema/settings.schema.json
  ui/assets/img/editors/appcode.svg
  ui/assets/img/editors/atom.svg
  ui/assets/img/editors/clion.svg
  ui/assets/img/editors/custom.svg
  ui/assets/img/editors/goland.svg
  ui/assets/img/editors/idea.svg
  ui/assets/img/editors/phpstorm.svg
  ui/assets/img/editors/pycharm.svg
  ui/assets/img/editors/rider.svg
  ui/assets/img/editors/rubymine.svg
  ui/assets/img/editors/sublime.svg
  ui/assets/img/editors/vscode.svg
  ui/assets/img/editors/webstorm.svg
  ui/assets/img/open-in-editor.svg
Labels: cla-signed

#41294 Nathan downs event level data docs
  doc/dev/background-information/adding_event_level_data.md
  doc/dev/background-information/index.md
Labels: cla-signed

#41362 gitserver: remove deprecated tracing functions usage.
  cmd/gitserver/server/server.go
  enterprise/internal/insights/store/dashboard_store_test.go
  enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_4_in_org_1_can_see_both_dashboards_with_view.golden
  enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_4_in_org_1_can_see_both_global_and_org_private_dashboard.golden
  internal/codeintel/stores/dbstore/configuration_policies_test.go
  internal/trace/trace.go
Labels: team/repo-management, cla-signed

#41277 Render "no data" error message for searches with no results
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/components/aggregation/AggregationBarsBackground.module.scss
  client/web/src/search/results/components/aggregation/AggregationBarsBackground.tsx
  client/web/src/search/results/components/aggregation/AggregationChartCard.module.scss
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/AggregationDataContainer.module.scss
  client/web/src/search/results/components/aggregation/AggregationDataContainer.tsx
  client/web/src/search/results/components/aggregation/AggregationErrorContainer.module.scss
  client/web/src/search/results/components/aggregation/AggregationErrorContainer.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
Labels: cla-signed

#41380 [Admin Analytics] update default extensions mins saved
  client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx
Labels: cla-signed

#41381 Search backend: add changelog entry for predicates improvements
  CHANGELOG.md
Labels: team/search-product, cla-signed

#41379 Fix aggregation cache across different ui modes
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/sidebar/SearchAggregations.tsx
Labels: cla-signed

#41384 doc/dev: add warnings for common mistakes, update link to trace.Logger
  doc/dev/how-to/add_logging.md
Labels: cla-signed

#41377 insights: stop aggregation counting if the context is canceled
  enterprise/internal/insights/aggregation/aggregation.go
  enterprise/internal/insights/aggregation/aggregation_test.go
  enterprise/internal/insights/resolvers/aggregates_resolvers.go
Labels: cla-signed

#41296 search: highlight file path matches
  client/search-ui/src/components/FileSearchResult.tsx
  client/search-ui/src/components/RepoFileLink.tsx
  cmd/frontend/internal/search/search.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/searcher/search.go
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
  internal/search/zoekt/symbol_search.go
Labels: cla-signed

#41373 upgrade: Add doc clarifications
  doc/admin/index.md
  doc/admin/updates/index.md
Labels: cla-signed, rfc-697, rfc-697-testing

#41382 search: simplify query generator control flow
  internal/search/lucky/feeling_lucky_search_job.go
  internal/search/lucky/generator.go
  internal/search/lucky/generator_test.go
Labels: cla-signed

#41390 changelog: Add note about multi-version upgrade
  CHANGELOG.md
Labels: cla-signed, rfc-697

#41385 search: highlight matching path ranges on content matches
  CHANGELOG.md
  client/search-ui/src/components/FileSearchResult.tsx
  client/shared/src/search/stream.ts
  cmd/frontend/internal/search/search.go
  internal/search/streaming/http/events.go
Labels: cla-signed

#41375 batches: increase aggressiveness of GitLab minimum version site alert
  cmd/frontend/graphqlbackend/site_alerts.go
Labels: team/batchers, cla-signed, 4.0

#41211 Aggregations: add extended timeout feature
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/search/results/components/aggregation/AggregationBarsBackground.module.scss
  client/web/src/search/results/components/aggregation/AggregationBarsBackground.tsx
  client/web/src/search/results/components/aggregation/AggregationChartCard.module.scss
  client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
  client/web/src/search/results/components/aggregation/AggregationErrorContainer.module.scss
  client/web/src/search/results/components/aggregation/SearchAggregationResult.tsx
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/sidebar/SearchAggregations.tsx
Labels: cla-signed

#41322 user-management: exclude non-active-user-events from "events_count" aggregation
  internal/database/event_logs.go
  internal/eventlogger/event_logger.go
  internal/users/update_aggregated_stats_job.go
Labels: cla-signed

#40982 Performance: Reduce waterfall fetching by making repo and resolvedRev optional
  client/web/src/enterprise/repo/routes.tsx
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/graphQlResponseHelpers.ts
  client/web/src/integration/nav.test.ts
  client/web/src/integration/notebook.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/integration/search-contexts.test.ts
  client/web/src/integration/search.test.ts
  client/web/src/repo/FilePathBreadcrumbs.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoHeader.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepositoryFileTreePage.tsx
  client/web/src/repo/RepositoryGitDataContainer.tsx
  client/web/src/repo/RevisionsPopover/RevisionsPopover.mocks.ts
  client/web/src/repo/RevisionsPopover/RevisionsPopover.tsx
  client/web/src/repo/backend.ts
  client/web/src/repo/blame/useBlameHunks.ts
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/PrefetchableFile.tsx
  client/web/src/repo/blob/backend.ts
  client/web/src/repo/blob/panel/BlobPanel.tsx
  client/web/src/repo/commit/RepositoryCommitPage.tsx
  client/web/src/repo/commits/RepositoryCommitsPage.tsx
  client/web/src/repo/compare/RepositoryCompareArea.tsx
  client/web/src/repo/compare/RepositoryComparePopover.tsx
  client/web/src/repo/releases/RepositoryReleasesTagsPage.tsx
  client/web/src/repo/routes.tsx
  client/web/src/repo/stats/RepositoryStatsArea.tsx
  client/web/src/repo/tree/BranchesTab.tsx
  client/web/src/repo/tree/HomeTab.tsx
  client/web/src/repo/tree/TagTab.tsx
  client/web/src/repo/tree/TreeNavigation.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/tree/ChildTreeLayer.tsx
Labels: team/frontend-platform, UI performance, cla-signed

#41366 [SG-40295] Extract bootstrap style import @import 'bootstrap/scss/function', @import 'bootstrap/scss/mixins'
  client/branded/src/global-styles/base.scss
  client/branded/src/global-styles/functions.scss
  client/branded/src/global-styles/grid.scss
  client/branded/src/global-styles/mixins.scss
  client/branded/src/global-styles/typography.scss
  client/branded/src/global-styles/variables.scss
  client/browser/src/app.scss
Labels: team/frontend-platform, gitstart, cla-signed

#41369 authz: cache duration metric for subrepo perms
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#40887 zoekt: update to include ctagsPath fix
  go.mod
  go.sum
Labels: cla-signed

#41351 authz: Use conf.Watch in SubRepoPermsClient
  internal/authz/sub_repo_perms.go
Labels: team/repo-management, cla-signed

#41307 log: lower level for enqueuing errors on repo-updater
  cmd/repo-updater/repoupdater/server.go
Labels: repo-updater, dx, cla-signed, sentry

#41403 Remove GitHub and GitLab Enterprise from business tier
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
Labels: cla-signed, team/iam

#41352 Tweak Git blame UI/UX
  client/web/bundlesize.config.js
  client/web/src/repo/blame/useBlameHunks.ts
  client/web/src/repo/blob/BlameDecoration.module.scss
  client/web/src/repo/blob/BlameDecoration.tsx
Labels: cla-signed

#41370 GraphQL repositories: allow TotalCount for cloned/uncloned/cloneStatus
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repositories_test.go
Labels: cla-signed

#41401 web: drop `bootstrap` depenedency
  .stylelintrc.json
  client/branded/README.md
  client/branded/src/components/Form.tsx
  client/branded/src/components/panel/TabbedPanelContent.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/branded/src/global-styles/GlobalStylesStory/TextStory.tsx
  client/branded/src/global-styles/background.scss
  client/branded/src/global-styles/base.scss
  client/branded/src/global-styles/utilities.scss
  client/browser/config/webpack/base.config.ts
  client/browser/src/branded.scss
  client/shared/README.md
  client/shared/src/actions/ActionsNavItems.tsx
  client/wildcard/src/components/Form/MultiSelect/styles.ts
  client/wildcard/src/components/Form/Select/Select.tsx
  client/wildcard/src/components/Form/internal/FormFieldMessage.tsx
  client/wildcard/src/components/Form/internal/utils.ts
  client/wildcard/src/components/Typography/Typography.story.tsx
  doc/dev/background-information/web/styling.md
  package.json
  yarn.lock
Labels: team/frontend-platform, cla-signed

#41409 Delete extension authoring docs
  doc/dev/background-information/architecture/sourcegraph-extensions.md
  doc/dev/background-information/codeintel/diagrams/code-intel-definitions.mermaid
  doc/dev/background-information/codeintel/diagrams/code-intel-definitions.svg
  doc/dev/background-information/codeintel/diagrams/code-intel-hover.mermaid
  doc/dev/background-information/codeintel/diagrams/code-intel-hover.svg
  doc/dev/background-information/codeintel/diagrams/code-intel-references.mermaid
  doc/dev/background-information/codeintel/diagrams/code-intel-references.svg
  doc/dev/background-information/codeintel/extensions.md
  doc/dev/background-information/index.md
  doc/dev/background-information/sourcegraph_extensions.md
  doc/dev/background-information/telemetry.md
  doc/dev/index.md
  doc/extensions/authoring/activation.md
  doc/extensions/authoring/builtin_commands.md
  doc/extensions/authoring/context_key_expressions.md
  doc/extensions/authoring/contributions.md
  doc/extensions/authoring/cookbook.md
  doc/extensions/authoring/creating.md
  doc/extensions/authoring/debugging.md
  doc/extensions/authoring/development_environment.md
  doc/extensions/authoring/forking.md
  doc/extensions/authoring/img/enable-sourcegraph-extensions.png
  doc/extensions/authoring/importing_sourcegraph.md
  doc/extensions/authoring/index.md
  doc/extensions/authoring/local_development.md
  doc/extensions/authoring/manifest.md
  doc/extensions/authoring/publishing.md
  doc/extensions/authoring/testing_extensions.md
  doc/extensions/authoring/tutorials/button_custom_commands.md
  doc/extensions/authoring/tutorials/file_decorations.md
  doc/extensions/authoring/tutorials/hello_world.md
  doc/extensions/authoring/tutorials/img/command-palette.png
  doc/extensions/authoring/tutorials/img/contribution-points-github.jpg
  doc/extensions/authoring/tutorials/img/file-decorations.png
  doc/extensions/authoring/tutorials/img/line-counter.png
  doc/extensions/authoring/tutorials/img/python-button.png
  doc/extensions/authoring/tutorials/img/status-bar.png
  doc/extensions/authoring/tutorials/index.md
  doc/extensions/authoring/tutorials/lang_specific_extension_tutorial.md
  doc/extensions/authoring/tutorials/status_bar.md
  doc/extensions/authoring/ux_style_guide.md
  doc/extensions/index.md
  doc/extensions/usage.md
Labels: cla-signed

#41411 scanprotects: Mention use of jq
  enterprise/internal/authz/perforce/cmd/scanprotects/README.md
Labels: team/repo-management, cla-signed

#41414 Update ref panel visual
  doc/code_navigation/explanations/features.md
Labels: cla-signed

#41407 Remove references to external services
  doc/integration/index.md
  doc/integration/lightstep.md
Labels: cla-signed

#41417 authz: factor out actorSubRepoEnabled
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#41421 Remove broken link
  client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
Labels: cla-signed

#41422 ci: ensure namespace is always deleted
  dev/ci/integration/cluster/test.sh
Labels: cla-signed

#41336 internal/actor: migrate middleware to use new logger
  cmd/frontend/internal/cli/http.go
  cmd/gitserver/main.go
  cmd/searcher/main.go
  cmd/symbols/shared/main.go
  enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
  internal/actor/http.go
  internal/actor/http_test.go
Labels: cla-signed

#41387 doc/admin: update otelcol -> jaeger guidance to point to deploy docs
  doc/admin/observability/opentelemetry.md
Labels: cla-signed

#41372 doc: align on opentelemetry docs naming
  doc/admin/deploy/docker-compose/operations.md
  doc/admin/observability/opentelemetry.md
  doc/dev/background-information/observability/index.md
  doc/dev/how-to/add_observability.md
  doc/dev/how-to/monitoring_local_dev.md
  doc/dev/how-to/opentelemetry_local_dev.md
  doc/dev/index.md
Labels: cla-signed

#41359 docs: add OpenTelemetry configuration instructions for Helm
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/observability/opentelemetry.md
Labels: cla-signed

#41432 Performance: Avoid refetching blob when commitID changes
  client/web/src/repo/blob/BlobPage.tsx
Labels: team/frontend-platform, cla-signed

#41416 insights: update aggregation docs for running explicit aggregations
  doc/code_insights/explanations/search_results_aggregations.md
Labels: cla-signed

#41433 authz: introduce FilePermissionsFunc
  internal/authz/mocks_temp.go
  internal/authz/sub_repo_perms.go
Labels: cla-signed

#41415 insights: add changelog entry for aggregations
  CHANGELOG.md
Labels: cla-signed

#41438 insights: lock aggregation updates
  enterprise/internal/insights/aggregation/aggregation.go
  enterprise/internal/insights/aggregation/limited_aggregator.go
Labels: cla-signed

#41004 [codenav]: refactor of upload resolver
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/audit_log.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/audit_logs.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/prefetcher.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/prefetcher_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/retention_policy_matcher_connection.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/retention_policy_matches.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/summary.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/types.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/upload.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/upload_connection.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/util.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mocks_temp.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/transport/uploads/mocks_uploads.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/types.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  enterprise/cmd/worker/internal/codeintel/indexing/iface.go
  enterprise/cmd/worker/internal/codeintel/indexing/mocks_test.go
  internal/codeintel/stores/dbstore/audit_logs.go
  internal/codeintel/stores/dbstore/audit_logs_test.go
  internal/codeintel/stores/dbstore/configuration_policies.go
  internal/codeintel/stores/dbstore/configuration_policies_test.go
  internal/codeintel/stores/dbstore/dependency_index.go
  internal/codeintel/stores/dbstore/dumps_test.go
  internal/codeintel/stores/dbstore/helpers_test.go
  internal/codeintel/stores/dbstore/uploads.go
  internal/codeintel/stores/dbstore/uploads_test.go
  internal/codeintel/stores/lsifstore/documents_test.go
  internal/codeintel/uploads/internal/lsifstore/lsifstore.go
  internal/codeintel/uploads/internal/lsifstore/lsifstore_documents.go
  internal/codeintel/uploads/internal/lsifstore/lsifstore_documents_test.go
  internal/codeintel/uploads/internal/lsifstore/testdata/lsif-go@ad3507cb.sql
  internal/codeintel/uploads/internal/store/observability.go
  internal/codeintel/uploads/internal/store/scan.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/internal/store/store_audit_logs.go
  internal/codeintel/uploads/internal/store/store_audit_logs_test.go
  internal/codeintel/uploads/internal/store/store_dumps_test.go
  internal/codeintel/uploads/internal/store/store_uploads.go
  internal/codeintel/uploads/internal/store/store_uploads_test.go
  internal/codeintel/uploads/mocks_test.go
  internal/codeintel/uploads/observability.go
  internal/codeintel/uploads/service.go
  internal/codeintel/uploads/shared/types.go
  internal/codeintel/uploads/transport/graphql/commitgraph_resolver.go
  internal/codeintel/uploads/transport/graphql/init.go
  internal/codeintel/uploads/transport/graphql/observability.go
  internal/codeintel/uploads/transport/graphql/resolver.go
  internal/codeintel/uploads/transport/graphql/uploads_resolver.go
  mockgen.temp.yaml
  mockgen.test.yaml
Labels: cla-signed

#41386 licensing: add documentation on how to generate a license key for testing and debugging
  doc/dev/how-to/generate_license_key_for_testing.md
  doc/dev/index.md
Labels: cla-signed, team/iam

#41061 [codeplatform] Move symbols service to Codenav service.
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_blob_info_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_tree_info_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/support.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mocks_temp.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/support.go
  enterprise/cmd/frontend/internal/codeintel/services.go
  internal/codeintel/codenav/init.go
  internal/codeintel/codenav/internal/store/observability.go
  internal/codeintel/codenav/internal/store/scan.go
  internal/codeintel/codenav/internal/store/store.go
  internal/codeintel/codenav/internal/store/store_test.go
  internal/codeintel/codenav/mocks_test.go
  internal/codeintel/codenav/observability.go
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_definitions_test.go
  internal/codeintel/codenav/service_diagnostics_test.go
  internal/codeintel/codenav/service_hover_test.go
  internal/codeintel/codenav/service_implementations_test.go
  internal/codeintel/codenav/service_ranges_test.go
  internal/codeintel/codenav/service_references_test.go
  internal/codeintel/codenav/service_stencil_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/observability.go
  internal/codeintel/codenav/transport/graphql/resolver.go
  internal/codeintel/stores/dbstore/support.go
Labels: cla-signed

#41393 search ui: rename lucky search to smart search
  client/search-ui/src/input/toggles/SmartSearchToggle.module.scss
  client/search-ui/src/input/toggles/SmartSearchToggle.tsx
  client/search-ui/src/input/toggles/Toggles.tsx
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/search-ui/src/util/events.ts
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/suggestion/SmartSearch.tsx
Labels: cla-signed

#41434 authz: use FilePermissionsFunc for batch path operations
  internal/authz/sub_repo_perms.go
  internal/authz/sub_repo_perms_test.go
  internal/gitserver/commands_test.go
  internal/search/job/jobutil/sub_repo_perms_job_test.go
Labels: cla-signed

#41383 dev/sg: update categories, clean up 'sg page' command
  dev/sg/linters/go_checks.go
  dev/sg/main.go
  dev/sg/sg_analytics.go
  dev/sg/sg_doctor.go
  dev/sg/sg_feedback.go
  dev/sg/sg_page.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#41242 tracing: enable opentelemetry by default, remove legacy values
  CHANGELOG.md
  doc/admin/observability/opentelemetry.md
  doc/admin/observability/tracing.md
  internal/trace/url.go
  internal/tracer/switchable_ot.go
  internal/tracer/switchable_otel.go
  internal/tracer/tracer.go
  internal/tracer/watch.go
  internal/tracer/watch_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#41326 ranking: flush result queue after X ms
  internal/search/backend/horizontal.go
  internal/search/backend/horizontal_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#41141 search ui: lucky search toggle menu
  client/jetbrains/webview/src/search/input/JetBrainsToggles.tsx
  client/search-ui/src/input/toggles/QueryInputToggle.tsx
  client/search-ui/src/input/toggles/SmartSearchToggle.module.scss
  client/search-ui/src/input/toggles/SmartSearchToggle.tsx
  client/search-ui/src/input/toggles/Toggles.tsx
  client/search-ui/src/input/toggles/__snapshots__/Toggles.test.tsx.snap
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/search-ui/src/util/events.ts
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/suggestion/SmartSearch.tsx
  client/wildcard/src/components/Popover/components/popover-content/PopoverContent.tsx
Labels: cla-signed

#41450 doc/admin: add link to Kubernetes with Helm otelcol docs
  doc/admin/observability/opentelemetry.md
Labels: cla-signed

#41290 search docs: collapsible regex mode section
  doc/code_search/reference/queries.md
Labels: cla-signed

#41388 insights: aggregations only capture the match's content if needed for the group type
  enterprise/internal/insights/aggregation/aggregation.go
  enterprise/internal/insights/aggregation/aggregation_test.go
Labels: cla-signed

#41392 case sensitive drilldowns
  enterprise/internal/insights/query/querybuilder/builder.go
  enterprise/internal/insights/query/querybuilder/builder_test.go
  enterprise/internal/insights/resolvers/aggregates_resolvers.go
  enterprise/internal/insights/resolvers/aggregates_resolvers_test.go
Labels: cla-signed

#41424 codeintel: Fix "Code graph" casing
  client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx
  client/web/src/repo/tree/TabNavigation.tsx
  client/web/src/repo/tree/TreeNavigation.tsx
  doc/code_navigation/how-to/index_other_languages.md
Labels: team/code-intelligence, cla-signed, team/language-platform-and-navigation
