Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-03, with the labels that each got.

#31682 code monitoring: logs can be expanded
  client/web/src/enterprise/code-monitoring/CodeMonitoringLogs.module.scss
  client/web/src/enterprise/code-monitoring/CodeMonitoringLogs.story.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringLogs.tsx
  client/web/src/enterprise/code-monitoring/components/logs/CodeMonitorLogsHeader.module.scss
  client/web/src/enterprise/code-monitoring/components/logs/CodeMonitorLogsHeader.tsx
  client/web/src/enterprise/code-monitoring/components/logs/CollapsibleDetailsWithStatus.module.scss
  client/web/src/enterprise/code-monitoring/components/logs/CollapsibleDetailsWithStatus.tsx
  client/web/src/enterprise/code-monitoring/components/logs/MonitorLogNode.module.scss
  client/web/src/enterprise/code-monitoring/components/logs/MonitorLogNode.tsx
  client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.module.scss
  client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
  client/web/src/enterprise/code-monitoring/testing/util.ts
Labels: cla-signed

#31966 usagestats: Add utm_cid to query param allowlist
  client/web/src/tracking/util.test.ts
  client/web/src/tracking/util.ts
  internal/usagestats/event_handlers.go
  internal/usagestats/event_handlers_test.go
Labels: cla-signed

#31970 Add Datadog traceID support
  internal/trace/traceutil.go
Labels: cla-signed

#31974 Fix ctags bug by resetting protobuf syntax
  cmd/symbols/ctags-install-alpine.sh
Labels: cla-signed

#31699 repo-updater: Remove scheduler interface
  cmd/repo-updater/shared/main.go
  internal/repos/scheduler.go
  internal/repos/scheduler_test.go
Labels: team/repo-management, cla-signed

#31836 Fix getting-started-tour external link steps
  client/web/src/onboarding-tour/OnboardingTourSteps.tsx
  client/web/src/onboarding-tour/utils.tsx
Labels: bug, cla-signed

#31917 ci: add number field to analytics report
  dev/ci/go-test.sh
  dev/ci/yarn-test.sh
Labels: dx, ci, team/devx, cla-signed

#31956 disable broken jest tests
  client/codeintellify/src/hoverifier.test.ts
  client/common/src/util/hashCode.test.ts
  package.json
Labels: cla-signed

#31986 codeintel/lockfiles: Restore `package-lock.json` dev dependencies
  go.mod
  go.sum
  internal/codeintel/lockfiles/npm.go
  internal/codeintel/lockfiles/parser.go
  internal/codeintel/lockfiles/parser_test.go
  internal/codeintel/lockfiles/service.go
  internal/codeintel/lockfiles/service_test.go
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_many.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_many.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_normal.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_normal.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_react.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_react.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_realworld.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_realworld.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_many.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_many.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_normal.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_normal.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_react.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_react.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_with_dev.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_v2_with_dev.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_with_dev.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_with_dev.lock.golden
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_with_npm.lock
  internal/codeintel/lockfiles/testdata/parse/yarn.lock/yarn_with_npm.lock.golden
  internal/conf/reposource/npm_packages.go
  internal/conf/reposource/npm_packages_test.go
Labels: cla-signed

#31992 database: Add observability to batch insertion
  internal/database/batch/batch.go
  internal/database/batch/observability.go
Labels: cla-signed

#31965 dev/ci: provide annotation opts as env instead of args
  .buildkite/hooks/pre-command
  enterprise/dev/ci/internal/buildkite/buildkite.go
  enterprise/dev/ci/scripts/annotated-command.sh
Labels: cla-signed

#31996 codeintel locations: fix URLs by using git blob as resource
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations_test.go
Labels: cla-signed

#31969 dev/ci: integrate test reports with AnnotatedCmd
  .gitignore
  dev/ci/go-test.sh
  dev/ci/yarn-test.sh
  doc/dev/background-information/ci/index.md
  enterprise/dev/ci/internal/buildkite/buildkite.go
  enterprise/dev/ci/internal/ci/changed/diff.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/scripts/annotated-command.sh
  enterprise/dev/ci/scripts/upload-test-report.sh
Labels: cla-signed

#31910 gitserver: relax npm package file limits
  cmd/gitserver/server/vcs_syncer_npm_packages.go
Labels: cla-signed

#32003 database: Fix duration in batch insert traces
  internal/database/batch/batch.go
Labels: cla-signed

#32005 Add migration to add create_at column in external_service_repo table
  internal/database/schema.md
  migrations/frontend/1646153853/down.sql
  migrations/frontend/1646153853/metadata.yaml
  migrations/frontend/1646153853/up.sql
Labels: cla-signed

#31999 sg: Change sg.config.yaml to point to insiders for syntax-highlighter
  sg.config.yaml
Labels: cla-signed

#32004 soft fail cluster tests for data gathering
  dev/ci/integration/cluster/test.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#32009 Code Insights: Migrate insight integration test to GQL API
  client/shared/src/testing/driver.ts
  client/web/src/enterprise/insights/pages/dashboards/creation/components/InsightsDashboardCreationContent.tsx
  client/web/src/integration/insights/create-insights.test.ts
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/drill-down-filters.test.ts
  client/web/src/integration/insights/edit-search-insights.test.ts
  client/web/src/integration/insights/fixtures/calculated-insights.ts
  client/web/src/integration/insights/fixtures/insights-metadata.ts
  client/web/src/integration/insights/fixtures/runtime-insights.ts
  client/web/src/integration/insights/insights-visual.test.ts
  client/web/src/integration/insights/utils/override-insights-graphql-api.ts
Labels: team/code-insights, cla-signed

#31727 [cloud] Fix invitation bugs
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/org_invitations_test.go
  internal/database/org_invitations.go
  internal/database/org_invitations_test.go
  internal/database/schema.md
  migrations/frontend/1645635177/down.sql
  migrations/frontend/1645635177/metadata.yaml
  migrations/frontend/1645635177/up.sql
Labels: cla-signed

#32017 Revert "[cloud] Fix invitation bugs"
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/org_invitations_test.go
  internal/database/org_invitations.go
  internal/database/org_invitations_test.go
  internal/database/schema.md
  migrations/frontend/1645635177/down.sql
  migrations/frontend/1645635177/metadata.yaml
  migrations/frontend/1645635177/up.sql
Labels: cla-signed

#32013 dev/sg: add update and update -local command
  dev/sg/internal/run/helpers.go
  dev/sg/main.go
  dev/sg/sg_update.go
  doc/dev/background-information/sg/index.md
Labels: sg, dx-announce, team/devx, cla-signed

#32012 dev/sg: only look for revisions in main
  dev/sg/main.go
  dev/sg/sg_version.go
Labels: sg, team/devx, cla-signed

#32020 Add Datadog profiler
  go.mod
  go.sum
  internal/profiler/profiler.go
Labels: cla-signed

#32018 Search backend: remove unused Inputs() from SearchImplementer
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/search_alert.go
Labels: cla-signed

#32021 Search backend: remove settings from SearchArgs
  cmd/frontend/graphqlbackend/search.go
Labels: cla-signed

#32041 Revert "Revert "[cloud] Fix invitation bugs" (#32017)"
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/org_invitations_test.go
  internal/database/org_invitations.go
  internal/database/org_invitations_test.go
  internal/database/schema.md
  migrations/frontend/1645635177/down.sql
  migrations/frontend/1645635177/metadata.yaml
  migrations/frontend/1645635177/up.sql
Labels: cla-signed

#29966 Improve acquisition CTA – pings
  CHANGELOG.md
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/app/updatecheck/handler_test.go
  doc/admin/pings.md
  internal/types/types.go
  internal/usagestats/growth.go
  internal/usagestats/growth_test.go
Labels: cla-signed

#31389 Add IDE CTA pings
  CHANGELOG.md
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  doc/admin/pings.md
  internal/types/types.go
  internal/usagestats/growth.go
  internal/usagestats/growth_test.go
Labels: team/growth-and-integrations, cla-signed

#32037 search: add suggestions for repo:deps predicate
  client/shared/src/search/query/completion.test.ts
  client/shared/src/search/query/completion.ts
  client/shared/src/search/query/predicates.ts
  client/shared/src/search/query/providers.test.ts
  client/shared/src/search/query/providers.ts
Labels: cla-signed

#32056 gitserver: read HOSTNAME env var
  cmd/gitserver/main.go
Labels: cla-signed

#30830 Enable eslint-plugin-wildcard globally
  .eslintrc.js
  client/eslint-plugin-wildcard/lib/index.js
  client/shared/.eslintrc.js
  client/shared/src/components/activation/ActivationDropdown.test.tsx
  client/shared/src/components/utils/linkClickHandler.test.tsx
  client/web/.eslintrc.js
  client/web/src/auth/TosConsentModal.tsx
  client/web/src/enterprise/batches/execution/TimelineModal.tsx
  client/web/src/enterprise/codeintel/indexes/components/CodeIntelIndexTimeline.tsx
  client/web/src/enterprise/embed/OpenNewTabAnchorLink.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/DrillDownFiltersForm.tsx
  client/web/src/enterprise/insights/pages/dashboards/creation/components/InsightsDashboardCreationContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/add-insight-modal/components/add-insight-modal-content/AddInsightModalContent.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/code-insights-templates/CodeInsightsTemplates.tsx
  client/web/src/enterprise/insights/pages/getting-started/components/dynamic-code-insight-example/DynamicCodeInsightExample.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/CaptureGoupCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/components/lang-stats-insight-creation-form/LangStatsInsightCreationForm.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/components/search-insight-creation-form/SearchInsightCreationForm.tsx
  client/web/src/extensions/ExtensionsAreaHeader.tsx
  client/web/src/org/area/OrgHeader.tsx
  client/web/src/org/invitations/OrgInvitationPage.tsx
  client/web/src/util/dom.ts
  client/wildcard/src/components/Form/Select/Select.tsx
  client/wildcard/src/components/Form/TextArea/TextArea.tsx
  client/wildcard/src/components/Link/AnchorLink/AnchorLink.tsx
  package.json
Labels: gitstart, cla-signed

#32067 Revert "gitserver: read HOSTNAME env var"
  cmd/gitserver/main.go
Labels: cla-signed

#32068 Clarify formatting on no review required
  doc/dev/background-information/testing_principles.md
Labels: cla-signed

#31984 Experimental ref panel: restore click2j2d behaviour
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.story.tsx
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.tsx
  client/web/src/enterprise/batches/close/BatchChangeCloseChangesetsList.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
  client/web/src/global/CoolCodeIntel.tsx
  client/web/src/global/CoolCodeIntelQueries.tsx
  client/web/src/global/usePreciseCodeIntel.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/blob/Blob.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/commit/RepositoryCommitPage.tsx
  client/web/src/repo/compare/RepositoryCompareArea.tsx
Labels: cla-signed

#31994 Adding user search autocomplete to new org member invitation
  client/web/src/org/members/InviteMemberModal.tsx
  client/web/src/org/members/SearchUserAutocomplete.module.scss
  client/web/src/org/members/SearchUserAutocomplete.tsx
  client/web/src/org/members/gqlQueries.ts
  cmd/frontend/graphqlbackend/org_members.go
  cmd/frontend/graphqlbackend/org_members_test.go
  cmd/frontend/graphqlbackend/schema.graphql
  doc/cli/references/api.md
  internal/database/mocks.go
  internal/database/org_members.go
  internal/database/org_members_db_test.go
  internal/types/types.go
Labels: cla-signed

#32022 dev/sg: use TrimPrefix instead of TrimLeft
  dev/sg/checks.go
  dev/sg/main.go
  dev/sg/sg_version.go
Labels: cla-signed

#32078 Make created_at in external_service_repos not nullable
  internal/database/schema.md
  migrations/frontend/1646239940/down.sql
  migrations/frontend/1646239940/metadata.yaml
  migrations/frontend/1646239940/up.sql
Labels: cla-signed

#32073 dev/gqltest: Test dependencies search
  dev/gqltest/search_test.go
  internal/conf/conf.go
  internal/conf/server.go
  internal/conf/store.go
  internal/gqltestutil/search.go
Labels: cla-signed

#31948 Update external database docs to mention migrator
  doc/admin/external_services/postgres.md
Labels: cla-signed

#32083 search: simplify search results tests
  cmd/frontend/graphqlbackend/search_results_test.go
Labels: cla-signed

#30499 insights: update dev docs
  doc/dev/background-information/insights/backend.md
Labels: cla-signed

#32082 add resetable sync.Once for timed caching of ctags globs
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  internal/resetonce/resetable_once.go
  internal/symbols/client.go
Labels: team/code-intelligence, symbols, cla-signed

#32093 chore: Use `errgroup` over `goroutine.Parallel`
  enterprise/internal/codeintel/stores/dbstore/commits.go
  internal/goroutine/parallel.go
  internal/goroutine/parallel_test.go
Labels: cla-signed

#31275 internal/extsvc/github: Use conditional requests in ListOrganizations
  internal/extsvc/github/common.go
  internal/extsvc/github/testdata/vcr/ListOrganizations.yaml
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
Labels: cla-signed

#32100 internal/extsvc/github: Remove unused arg from newOrgsCache
  internal/extsvc/github/v3.go
Labels: cla-signed

#31831 batches: enable filtering BC connection by multiple states
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change_connection.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/batch_changes_test.go
Labels: team/batchers, server-side, cla-signed

#32028 search: create dedicated searcher job
  internal/search/run/repository.go
  internal/search/searcher/search.go
  internal/search/structural/structural.go
  internal/search/textsearch/textsearch.go
  internal/search/textsearch/textsearch_test.go
Labels: cla-signed

#32079 Code monitors: update email code to fit existing patterns
  enterprise/internal/codemonitors/background/email.go
  enterprise/internal/codemonitors/background/email_template.html.tmpl
  enterprise/internal/codemonitors/background/email_template.txt.tmpl
  enterprise/internal/codemonitors/background/email_test.go
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results/html.html
  enterprise/internal/codemonitors/background/testdata/TestEmail/multiple_results/text.txt
  enterprise/internal/codemonitors/background/testdata/TestEmail/one_result/html.html
  enterprise/internal/codemonitors/background/testdata/TestEmail/one_result/text.txt
  enterprise/internal/codemonitors/background/testdata/TestEmail/test_message/html.html
  enterprise/internal/codemonitors/background/testdata/TestEmail/test_message/text.txt
  enterprise/internal/codemonitors/background/workers.go
Labels: cla-signed

#31964 Code monitors: execute searches from worker, not through GraphQL
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  enterprise/internal/codemonitors/background/action.go
  enterprise/internal/codemonitors/background/graphql.go
  enterprise/internal/codemonitors/background/slack.go
  enterprise/internal/codemonitors/background/slack_test.go
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_with_results.json
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_with_truncated_results.json
  enterprise/internal/codemonitors/background/testdata/TestWebhook/error_is_returned.json
  enterprise/internal/codemonitors/background/testdata/TestWebhook/no_error.json
  enterprise/internal/codemonitors/background/webhook_test.go
  enterprise/internal/codemonitors/background/workers.go
  enterprise/internal/codemonitors/background/workers_test.go
  enterprise/internal/codemonitors/types/graphql.go
  enterprise/internal/database/code_monitor_action_jobs.go
  enterprise/internal/database/code_monitor_action_jobs_test.go
  enterprise/internal/database/code_monitor_trigger_jobs.go
  enterprise/internal/database/code_monitors.go
  enterprise/internal/database/mocks.go
Labels: cla-signed

#32106 Search backend: fix bad merge
  enterprise/internal/codemonitors/background/graphql.go
Labels: cla-signed

#32110 Fix buildkite after merging Rockskip
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/images/images.go
Labels: cla-signed

#32038 git-combine: Fix too many commits bug
  internal/cmd/git-combine/git-combine.go
  internal/cmd/git-combine/git-combine_test.go
Labels: cla-signed

#32113 auth: show GitLab icon for signin button
  client/web/src/auth/SignInPage.tsx
Labels: cla-signed

#31918 [CLOUD-255] Cache GitHub App installation access token in external service config
  cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
  cmd/frontend/graphqlbackend/external_service.go
  cmd/gitserver/main.go
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/shared/main.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_counts_test.go
  enterprise/cmd/frontend/internal/batches/webhooks/github_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/internal/authz/authz.go
  enterprise/internal/authz/authz_test.go
  enterprise/internal/authz/github/app.go
  enterprise/internal/authz/github/app_test.go
  enterprise/internal/authz/github/authz.go
  enterprise/internal/authz/github/authz_test.go
  enterprise/internal/database/external_services.go
  internal/database/external_services.go
  internal/database/schema.md
  internal/extsvc/versions/sync.go
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/sources.go
  internal/repos/sources_test.go
  internal/repos/types.go
  internal/repos/types_test.go
  internal/types/types.go
  migrations/frontend/1646027072/down.sql
  migrations/frontend/1646027072/metadata.yaml
  migrations/frontend/1646027072/up.sql
Labels: cla-signed

#31785 bext: track browser extensions installs and uninstalls
  client/browser/src/browser-extension/scripts/backgroundPage.main.ts
  client/browser/src/browser-extension/scripts/optionsPage.main.tsx
  client/browser/src/shared/backend/userEvents.tsx
  client/browser/src/shared/tracking/eventLogger.tsx
  doc/dev/background-information/telemetry.md
Labels: cla-signed

#31924 ci: run all jest tests in one operation
  dev/ci/yarn-test.sh
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: testing, team/frontend-platform, ci, cla-signed

#30287 Remove bootstrap style import `@import 'bootstrap/scss/forms'`
  client/branded/src/global-styles/forms.scss
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/typography.scss
  client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
Labels: gitstart, cla-signed

#32112 gitserver: read GITSERVER_ADDR env var
  cmd/gitserver/main.go
Labels: cla-signed

#32108 dev/team: make ResolveByGitHubHandle case-insensitive
  dev/team/team.go
Labels: cla-signed

#32057 Code Insights: Remove the setting based api
  client/web/src/enterprise/insights/components/form/hooks/useInsightTitleValidator.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend-types.ts
  client/web/src/enterprise/insights/core/backend/code-insights-backend.ts
  client/web/src/enterprise/insights/core/backend/core/api/subject-settings.ts
  client/web/src/enterprise/insights/core/backend/gql-api/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-api/deserialization/create-insight-view.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/code-insights-setting-cascade-backend.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/gql-handlers/get-backend-insight.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/delete-helpers.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/find-insight-by-id.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/get-insights-dashboards/get-insights-dashboards.test.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/get-insights-dashboards/get-insights-dashboards.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/get-insights-dashboards/index.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/get-insights-dashboards/utils.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/get-updated-subject-settings.ts
  client/web/src/enterprise/insights/core/backend/setting-based-api/utils/persist-changes.ts
  client/web/src/enterprise/insights/core/settings-action/dashboards.ts
  client/web/src/enterprise/insights/core/settings-action/edits/apply-edit-operations.ts
  client/web/src/enterprise/insights/core/settings-action/edits/edits.ts
  client/web/src/enterprise/insights/core/settings-action/edits/index.ts
  client/web/src/enterprise/insights/core/settings-action/insights.ts
  client/web/src/enterprise/insights/core/types/dashboard/index.ts
  client/web/src/enterprise/insights/core/types/dashboard/real-dashboard.ts
  client/web/src/enterprise/insights/core/types/insight/common.ts
  client/web/src/enterprise/insights/core/types/insight/index.ts
  client/web/src/enterprise/insights/mocks/settings-cascade.ts
  client/web/src/enterprise/insights/pages/dashboards/creation/hooks/use-dashboard-settings.ts
  client/web/src/enterprise/insights/pages/dashboards/creation/utils/dashboard-sanitizer.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/add-insight-modal/AddInsightModal.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/add-insight-modal/utils/get-reachable-insights.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/hooks/use-dashboard-select-handler.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/utils/find-dashboard-by-url-id.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/delete-dashboard-modal/hooks/use-delete-dashboard-handler.ts
  client/web/src/enterprise/insights/pages/dashboards/edit-dashboard/EditDashobardPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/capture-group-insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/utils/insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/insight-sanitizer.ts
  client/web/src/enterprise/insights/pages/insights/edit-insight/hooks/use-edit-page-handlers.ts
Labels: team/code-insights, cla-signed

#31977 Wildcard: Fix `FeedbackPrompt.tsx` spacing visual bug
  client/wildcard/src/components/Feedback/FeedbackPrompt/FeedbackPrompt.tsx
  client/wildcard/src/components/Feedback/FeedbackPrompt/IconRadioButtons.tsx
  client/wildcard/src/components/Feedback/FeedbackPrompt/__snapshots__/FeedbackPrompt.test.tsx.snap
Labels: cla-signed, wildcard-v2/feedback-widget

#32132 Client side pagination to Organization members and pending invites
  client/web/src/org/members/OrgMembersListPage.tsx
  client/web/src/org/members/OrgPendingInvites.tsx
  client/web/src/org/members/utils.tsx
Labels: cla-signed

#32053 Add dependencies search button to repository page
  client/web/src/repo/tree/TreePage.tsx
Labels: cla-signed

#32135 dev/gqltest: Skip flaky repo:deps predicate test
  dev/gqltest/search_test.go
Labels: cla-signed

#32131 sg: fix loading of the overwrite config
  dev/sg/sg_start.go
  dev/sg/sg_tests.go
Labels: cla-signed

#32134 db: Remove deprecated permissions columns
  internal/database/schema.md
  migrations/frontend/1646306565/down.sql
  migrations/frontend/1646306565/metadata.yaml
  migrations/frontend/1646306565/up.sql
Labels: team/repo-management, cla-signed

#32136 Paginating public GitHub repos identifies the last page
  internal/extsvc/github/v3.go
  internal/repos/github_test.go
  internal/repos/testdata/sources/GITHUB-ENTERPRISE/list-public-repos.yaml
Labels: cla-signed

#32008 database: Track payload sizes in batch inserter
  internal/database/batch/batch.go
  internal/database/batch/batch_test.go
Labels: cla-signed

#32034 dependencies api: Batch database updates
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  enterprise/internal/batches/store/batch_spec_workspaces.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/testing/batch_spec_workspace_execution_jobs.go
  internal/codeintel/dependencies/service.go
  internal/codeintel/dependencies/store/observability.go
  internal/codeintel/dependencies/store/store.go
  internal/codeintel/dependencies/store/store_test.go
  internal/database/batch/batch.go
  internal/database/batch/batch_test.go
  internal/repos/jvm_packages.go
  internal/repos/npm_packages.go
Labels: team/code-intelligence, cla-signed

#32155 Revert "dependencies api: Batch database updates (#32034)"
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  enterprise/internal/batches/store/batch_spec_workspaces.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/testing/batch_spec_workspace_execution_jobs.go
  internal/codeintel/dependencies/service.go
  internal/codeintel/dependencies/store/observability.go
  internal/codeintel/dependencies/store/store.go
  internal/codeintel/dependencies/store/store_test.go
  internal/database/batch/batch.go
  internal/database/batch/batch_test.go
  internal/repos/jvm_packages.go
  internal/repos/npm_packages.go
Labels: cla-signed

#32090 unify git archive
  cmd/frontend/internal/app/ui/raw.go
  cmd/searcher/main.go
  cmd/symbols/gitserver/client.go
  internal/codeintel/lockfiles/iface.go
  internal/vcs/git/archive.go
  internal/vcs/git/archive_test.go
Labels: cla-signed

#32104 Streaming search: stream filters
  client/web/src/search/results/SearchResultsCacheProvider.tsx
  cmd/frontend/internal/search/search.go
Labels: cla-signed

#32145 Search backend: remove newSearchClient from streamHandler
  cmd/frontend/internal/search/search.go
  cmd/frontend/internal/search/search_test.go
Labels: cla-signed

#32119 notebooks: add compute block scaffolding
  client/web/src/notebooks/blocks/compute/NotebookComputeBlock.module.scss
  client/web/src/notebooks/blocks/compute/NotebookComputeBlock.tsx
  client/web/src/notebooks/createPage/CreateNotebookPage.tsx
  client/web/src/notebooks/index.ts
  client/web/src/notebooks/listPage/ImportMarkdownNotebookButton.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebook/index.ts
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/notebooks/serialize/index.ts
Labels: cla-signed

#32148 Search backend: store db on `searchClient`
  cmd/frontend/internal/search/search.go
  cmd/frontend/internal/search/search_test.go
  enterprise/cmd/frontend/internal/compute/streaming/compute.go
  enterprise/internal/codemonitors/background/graphql.go
  internal/search/client/client.go
  internal/search/client/mock_client.go
Labels: cla-signed

#32159 Revert "dev/gqltest: Add back repo:deps integration test (#32140)"
  dev/gqltest/search_test.go
Labels: cla-signed

#32156 dependencies api: Batch database updates
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  enterprise/internal/batches/store/batch_spec_workspaces.go
  enterprise/internal/batches/store/changeset_jobs.go
  enterprise/internal/batches/store/changeset_specs.go
  enterprise/internal/batches/testing/batch_spec_workspace_execution_jobs.go
  internal/codeintel/dependencies/service.go
  internal/codeintel/dependencies/store/observability.go
  internal/codeintel/dependencies/store/store.go
  internal/codeintel/dependencies/store/store_test.go
  internal/database/batch/batch.go
  internal/database/batch/batch_test.go
  internal/repos/jvm_packages.go
  internal/repos/npm_packages.go
Labels: team/code-intelligence, cla-signed

#32102 Transitioning to esxtsvc.json
  doc/admin/config/advanced_config_file.md
Labels: cla-signed

#32169 code monitoring: fix unstable storybook tests due to dates
  client/web/src/enterprise/code-monitoring/components/logs/MonitorLogNode.tsx
  client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
Labels: cla-signed

#32183 dev/ci: annotate failures with test summary
  dev/ci/go-test-failures.richstyle.yml
  dev/ci/go-test.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#32186 Fixing repo-updater sync alerts
  doc/admin/observability/dashboards.md
  monitoring/definitions/repo_updater.go
Labels: cla-signed

#32144 authz: No need to optimise bitmaps
  enterprise/internal/database/perms_store.go
Labels: team/repo-management, cla-signed

#32142 gitserver: add sg config to run multiple shards locally
  dev/gitserver/README.md
  dev/gitserver/sg.config.yaml
Labels: cla-signed

#31406 user invites: Add home page invite colleagues feature
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/search/backend.tsx
  client/web/src/search/home/SearchPage.module.scss
  client/web/src/search/home/SearchPage.story.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/index.tsx
  client/web/src/search/panels/ActionButtonGroup.module.scss
  client/web/src/search/panels/ActionButtonGroup.tsx
  client/web/src/search/panels/CollaboratorsPanel.module.scss
  client/web/src/search/panels/CollaboratorsPanel.story.tsx
  client/web/src/search/panels/CollaboratorsPanel.tsx
  client/web/src/search/panels/CommunitySearchContextPanel.tsx
  client/web/src/search/panels/HomePanels.module.scss
  client/web/src/search/panels/HomePanels.tsx
  client/web/src/search/panels/PanelContainer.module.scss
  client/web/src/search/panels/PanelContainer.tsx
  client/web/src/search/panels/SavedSearchesPanel.tsx
  client/web/src/search/panels/utils.ts
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#32195 user invites: Update email text
  cmd/frontend/graphqlbackend/email_invitation.go
Labels: cla-signed, growth

#32193 external_services: only execute update once
  internal/database/external_services.go
  internal/database/external_services_test.go
Labels: cla-signed

#32187 repo-updater: Update out parameter on missed code path
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: cla-signed

#32168 dev/gqltest: Test dependencies search
  dev/gqltest/search_test.go
Labels: cla-signed

#32198 web: Fix regex and rev from Dependencies button in repo page
  client/web/src/repo/tree/TreePage.tsx
Labels: cla-signed

#32146 Experimental ref panel: when clicking definition in mini code view, open code view immediately
  client/web/src/global/CoolCodeIntel.tsx
Labels: cla-signed

#32202 migrations: Add test to ensure extension modifications are marked as privileged
  dev/sg/internal/migration/add.go
  dev/sg/internal/migration/squash.go
  dev/sg/internal/migration/util.go
  internal/database/migration/definition/read.go
  internal/database/migration/definition/read_test.go
  internal/database/migration/definition/testdata/privileged/10001/down.sql
  internal/database/migration/definition/testdata/privileged/10001/metadata.yaml
  internal/database/migration/definition/testdata/privileged/10001/up.sql
  internal/database/migration/definition/testdata/unmarked-privilege/10001/down.sql
  internal/database/migration/definition/testdata/unmarked-privilege/10001/metadata.yaml
  internal/database/migration/definition/testdata/unmarked-privilege/10001/up.sql
  internal/database/migration/runner/helpers_test.go
  internal/database/migration/schemas/schemas.go
  migrations/codeinsights/1000000027/metadata.yaml
  migrations/frontend/1528395953/metadata.yaml
Labels: dx, cla-signed

#32006 user invites: Add user invites info text
  client/web/src/search/panels/CollaboratorsPanel.module.scss
  client/web/src/search/panels/CollaboratorsPanel.tsx
Labels: cla-signed, growth

#32208 codeintel/dependencies: Simplify lockfileDependencies
  internal/codeintel/dependencies/service.go
Labels: cla-signed

#32166 code monitoring: equalize row spacing in list
  client/web/src/enterprise/code-monitoring/CodeMonitorList.module.scss
  client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
Labels: cla-signed

#32173 code monitoring logs: show link to results with count
  client/web/src/enterprise/code-monitoring/CodeMonitoringLogs.tsx
  client/web/src/enterprise/code-monitoring/components/logs/MonitorLogNode.tsx
  client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
  client/web/src/enterprise/code-monitoring/testing/util.ts
Labels: cla-signed

#32216 rockskip: Small optimization for AppendHop
  enterprise/internal/rockskip/index.go
  enterprise/internal/rockskip/postgres.go
Labels: cla-signed

#32158 remove dead code monitor GraphQL code
  cmd/frontend/graphqlbackend/code_monitors.go
  cmd/frontend/graphqlbackend/code_monitors.graphql
  cmd/frontend/graphqlbackend/search.go
  enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
Labels: cla-signed

#32226 cmd/repo-updater: Update error message in handleSchedulePermsSync
  cmd/repo-updater/repoupdater/server.go
  cmd/repo-updater/repoupdater/server_test.go
Labels: cla-signed

#32236 codeintel: Add setting codeIntelligence.clickToGoToDefinition
  client/shared/src/hover/HoverOverlay.fixtures.ts
  client/web/src/components/WebHoverOverlay/WebHoverOverlay.tsx
  client/web/src/enterprise/batches/close/BatchChangeCloseChangesetsList.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
  client/web/src/repo/commit/RepositoryCommitPage.tsx
  client/web/src/repo/compare/RepositoryCompareArea.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#32237 site-admin: add feature flags list view
  client/web/src/site-admin/SiteAdminFeatureFlagsPage.module.scss
  client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/routes.tsx
  client/web/src/site-admin/sidebaritems.ts
Labels: cla-signed

#32242 zoekt: Fix nil panic
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#32243 site-admin: fix loading state when loading feature flags
  client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
Labels: cla-signed

#32200 Add deleted_at IS NULL check for GetUserIDsByExternalAccounts
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_test.go
Labels: cla-signed

#32058 Ask for GitHub App OAuth and login connection during Org Code Host Connection
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
Labels: cla-signed

#32245 repos: remove global DB mocks in fetching status messages
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
Labels: cla-signed

#32248 docs: Remove warning about Batch Changes renaming
  doc/batch_changes/index.md
Labels: docs, cla-signed

#32251 Fix broken badges in code intel indexer docs 🟢🟡🟠🟣
  doc/code_intelligence/references/indexers.md
Labels: cla-signed

#32250 search: Find correct Zoekt branch
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#32252 Revert "Ask for GitHub App OAuth and login connection during Org Code Host Connection (#32058)
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
Labels: cla-signed

#32256 Do not use legacy URL format in code intel docs
  doc/code_intelligence/index.md
Labels: cla-signed

#32247 github: Avoid potential panic
  internal/extsvc/github/v3.go
Labels: team/repo-management, cla-signed

#32261 Correcting syntax in query
  doc/admin/how-to/mutate-user-api.md
Labels: cla-signed

#31721 [SG-312492][Accessibility]: NavDropdown
  client/web/src/nav/NavBar/NavDropdown.module.scss
  client/web/src/nav/NavBar/NavDropdown.tsx
  client/web/src/nav/NavBar/NavItem.module.scss
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
Labels: gitstart, cla-signed

#32260 Initially implement new empty avatar background
  client/web/src/nav/__snapshots__/UserNavItem.test.tsx.snap
  client/web/src/user/UserAvatar.module.scss
  client/web/src/user/UserAvatar.tsx
  client/web/src/user/__snapshots__/UserAvatar.test.tsx.snap
Labels: cla-signed

#32268 fix: Always highlight to the end of the line for lsif
  client/web/src/lsif/html.ts
Labels: cla-signed

#31972 ssbc: Decrease minimum width of editor container
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.module.scss
Labels: cla-signed

#32267 Simplify tests for comparing branches/tags
  internal/vcs/git/refs_test.go
Labels: cla-signed

#32264 repo-updater: Reduce memory usage when prioritising uncloned repos
  cmd/repo-updater/shared/main.go
  internal/repos/scheduler.go
  internal/repos/scheduler_test.go
Labels: team/repo-management, cla-signed

#32212 dev/sg: remove deprecated check comand
  dev/sg/main.go
  dev/sg/sg_lint.go
Labels: cla-signed

#32213 dev/sg: clean up linter structure
  dev/sg/internal/docker/lints.go
  dev/sg/internal/docker/lints_test.go
  dev/sg/internal/lint/lint.go
  dev/sg/lints.go
  dev/sg/sg_lint.go
Labels: cla-signed

#31687 pr-auditor: add batch change templates for rollout/updates
  .github/workflows/pr-auditor.yml
  dev/pr-auditor/batch-changes/README.md
  dev/pr-auditor/batch-changes/pr-auditor-patch.yml
  dev/pr-auditor/batch-changes/pr-auditor-rollout.yml
Labels: cla-signed

#31538 dev: support fish shell in sg
  dev/sg/checks.go
  dev/sg/internal/usershell/usershell.go
Labels: cla-signed

#32230 rockskip: Drop DISTINCT from query
  enterprise/internal/rockskip/search.go
Labels: cla-signed

#32219 code monitoring: add url validation for slack and webhooks
  client/web/src/enterprise/code-monitoring/components/__snapshots__/FormActionArea.test.tsx.snap
  client/web/src/enterprise/code-monitoring/components/actions/EmailAction.tsx
  client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.story.tsx
  client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.test.tsx
  client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.tsx
  client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.story.tsx
  client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.tsx
Labels: cla-signed

#30086 insights: Fix pagination for insights in GetAll
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
Labels: team/code-insights, cla-signed

#32240 rockskip: Add an index on file extension
  enterprise/internal/rockskip/search.go
  enterprise/internal/rockskip/search_test.go
  internal/database/schema.codeintel.md
  migrations/codeintel/1000000033/down.sql
  migrations/codeintel/1000000033/metadata.yaml
  migrations/codeintel/1000000033/up.sql
Labels: cla-signed

#32210 migrator: Auto-retry to apply one failed migration in local dev
  cmd/migrator/main.go
  dev/sg/sg_migration.go
  internal/database/migration/cliutil/downto.go
  internal/database/migration/cliutil/undo.go
  internal/database/migration/cliutil/up.go
  internal/database/migration/cliutil/upto.go
  internal/database/migration/runner/options.go
  internal/database/migration/runner/run.go
  internal/database/migration/runner/run_test.go
  internal/database/migration/runner/runner.go
  internal/database/migration/runner/validate.go
Labels: dx, dx-announce, cla-signed

#31820 uploadstore: Support auth via EC2 role credentials
  CHANGELOG.md
  doc/admin/external_services/object_storage.md
  enterprise/internal/codeintel/stores/lsifuploadstore/config.go
  internal/uploadstore/s3_client.go
Labels: cla-signed

#32303 search contexts: integration tests flake
  client/web/src/integration/search-contexts.test.ts
Labels: cla-signed

#32278 Validate an insight has data series before view creation or update
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
Labels: team/code-insights, cla-signed

#32269 Add example for how to use <MockTemporarySettings> to the docs
  doc/dev/background-information/web/temporary_settings.md
Labels: docs, cla-signed

#31611 Fix bad url linter false positives
  dev/check/broken-urls.bash
  dev/release/src/github.ts
Labels: dx, team/devx, cla-signed

#31614 Handle hadolint curl failure due to missing arch
  dev/check/docker-lint.sh
Labels: bug, dx, sg, cla-signed

#32310 gitserver: Ignore "no sources" errors for JVM deps
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
Labels: team/repo-management, cla-signed

#32255 user invites: Small accessibility improvements for homepage invites
  client/web/src/search/panels/CollaboratorsPanel.tsx
Labels: cla-signed, growth

#32223 search: Add keybindings to Notepad open state
  client/web/src/search/SearchStack.module.scss
  client/web/src/search/SearchStack.test.tsx
  client/web/src/search/SearchStack.tsx
Labels: cla-signed

#32270 Remove no contributors found text when emails are disabled
  client/web/src/search/panels/CollaboratorsPanel.tsx
Labels: cla-signed, growth

#32291 Remove needless %x00 separator in git log.
  internal/vcs/git/commits.go
  internal/vcs/git/commits_test.go
Labels: cla-signed

#32199 bext: fix GitHub client-side routing support
  client/browser/src/shared/code-hosts/github/codeHost.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/code-hosts/shared/inject.ts
Labels: cla-signed

#32254 Revert "Revert "Ask for GitHub App OAuth and login connection during Org Code Host Connection (#32058)" (#32252)"
  client/web/src/user/settings/codeHosts/CodeHostItem.tsx
  client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
  enterprise/cmd/frontend/internal/auth/oauth/middleware.go
Labels: cla-signed

#32241 [SG-31914] Fix failing unit tests on `client/common`, `client/codeintellify` packages
  client/codeintellify/src/hoverifier.test.ts
  client/codeintellify/src/hoverifier.ts
  client/common/src/util/hashCode.test.ts
  client/shared/dev/jest-environment.js
Labels: cla-signed

#31901 insights: Add 4 new backend dashboard pings
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  enterprise/internal/insights/background/pings/insights_ping_aggregators.go
  enterprise/internal/insights/background/pings/insights_ping_emitter.go
  internal/types/types.go
  internal/usagestats/code_insights.go
  internal/usagestats/code_insights_test.go
Labels: cla-signed

#32092 insights: Add more backend pings to docs
  doc/dev/background-information/insights/code_insights_pings.md
Labels: cla-signed

#32273 user invites: Disable user invites when instance signup is disabled and on on-prem
  client/web/src/search/home/SearchPage.story.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/SearchPage.tsx
Labels: cla-signed, growth

#32266 Fix unnecessary recreation of temporary settings hook updater callback
  client/shared/src/settings/temporary/useTemporarySetting.test.tsx
  client/shared/src/settings/temporary/useTemporarySetting.ts
Labels: cla-signed

#32209 Do not show IDE CTAs to users who have these products installed
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/src/IdeExtensionTracker.test.tsx
  client/web/src/IdeExtensionTracker.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/repo/actions/InstallIntegrationsAlert.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
Labels: cla-signed, growth

#32333 batches: Remove use of database.Mocks.ExternalServices
  enterprise/internal/batches/syncer/syncer_test.go
Labels: cla-signed

#32334 ci: ship sg image without deploy
  enterprise/dev/ci/images/images.go
Labels: cla-signed

#32339 ci: fix missing ci docs update
  doc/dev/background-information/ci/reference.md
Labels: cla-signed
