Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2022-01, with the labels that each got.

#29211 Convert PermsStore to an interface
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/internal/database/authz.go
  enterprise/internal/database/authz_test.go
  enterprise/internal/database/database.go
  enterprise/internal/database/mock_gen.go
  enterprise/internal/database/mocks.go
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_mock.go
  enterprise/internal/database/perms_store_test.go
Labels: cla-signed

#29216 Convert a bunch of tests using global perms mocks
  cmd/frontend/graphqlbackend/user.go
  enterprise/cmd/frontend/internal/authz/resolvers/repositories.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/cmd/frontend/internal/authz/resolvers/users.go
Labels: cla-signed

#29201 Add sg db command to reset databases & create site-admin users
  dev/sg/config.go
  dev/sg/main.go
  dev/sg/sg_db.go
  dev/sg/sg_reset.go
  doc/dev/background-information/sg/index.md
Labels: dx, sg, dx-announce, cla-signed

#29381 Revert #29381
  dev/sg/config.go
  dev/sg/main.go
  dev/sg/sg_db.go
  dev/sg/sg_reset.go
  doc/dev/background-information/sg/index.md
Labels: cla-signed

#29174 Add SSBC FAQ from CEs
  doc/batch_changes/explanations/server_side.md
Labels: cla-signed

#29384 Fix sg broken release process
  .github/workflows/sg-binary-release.yml
Labels: dx, sg, team/devx, cla-signed

#29212 Moving executor to service
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/codeintel.go
  cmd/frontend/graphqlbackend/executor_connection_resolver.go
  cmd/frontend/graphqlbackend/executor_ids.go
  cmd/frontend/graphqlbackend/executors.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/node.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace.go
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/exists_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver_test.go
  enterprise/cmd/frontend/internal/executorqueue/handler/gen.go
  enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
  enterprise/cmd/frontend/internal/executorqueue/handler/handler_test.go
  enterprise/cmd/frontend/internal/executorqueue/handler/mock_iface_test.go
  enterprise/cmd/frontend/internal/executorqueue/handler/routes.go
  enterprise/cmd/frontend/internal/executorqueue/init.go
  enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
  enterprise/cmd/worker/internal/executors/janitor_job.go
  enterprise/internal/database/mocks.go
  internal/database/database.go
  internal/database/mocks.go
  internal/services/executors/service.go
  internal/services/executors/store/db/db.go
  internal/services/executors/store/db/db_executors.go
  internal/services/executors/store/db/db_executors_test.go
  internal/services/executors/store/store.go
  internal/services/executors/transport/graphql/executor_paginated_connection_resolver.go
  internal/services/executors/transport/graphql/executor_resolver.go
  internal/services/executors/transport/graphql/resolver.go
  internal/services/executors/transport/graphql/types.go
  internal/services/executors/transport/graphql/validation.go
Labels: cla-signed

#29385 Remove unused global mock methods
  internal/database/external_accounts.go
  internal/database/external_services.go
  internal/database/repos.go
  internal/database/repos_mock.go
  internal/database/sub_repo_perms_store.go
  internal/database/user_emails.go
  internal/database/user_emails_mock.go
  internal/database/users.go
  internal/database/users_mock.go
Labels: cla-signed

#29376 Codeintel doc updates
  doc/admin/external_services/index.md
  doc/admin/external_services/object_storage.md
  doc/code_intelligence/how-to/index_a_typescript_and_javascript_repository.md
  doc/code_intelligence/tutorials/indexing_ts_repo.md
Labels: cla-signed

#29366 Add headers env var to docs
  doc/cli/explanations/env.md
Labels: cla-signed

#29363 Grafana: Create optional directories to silence errors when overrides aren't present
  docker-images/grafana/Dockerfile
Labels: cla-signed

#29390 remove MockRepos.Get
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver_test.go
  internal/database/repos.go
  internal/database/repos_mock.go
Labels: cla-signed

#29389 migration: Add additional docs
  dev/ci/go-test-backcompat.sh
  doc/dev/background-information/index.md
  doc/dev/background-information/sql/batch_operations.md
  doc/dev/background-information/sql/index.md
  doc/dev/background-information/sql/materialized_cache.md
  doc/dev/background-information/sql/migrations.md
  doc/dev/index.md
  migrations/README.md
Labels: cla-signed

#29395 fix migrations that are out of sequence between 3.34.2 and 3.35 by moving them to the end of the migration queue.
  internal/database/schema.md
  migrations/frontend/1528395945_noop.down.sql
  migrations/frontend/1528395945_noop.up.sql
  migrations/frontend/1528395946_noop.down.sql
  migrations/frontend/1528395946_noop.up.sql
  migrations/frontend/1528395947_noop.down.sql
  migrations/frontend/1528395947_noop.up.sql
  migrations/frontend/1528395948_noop.down.sql
  migrations/frontend/1528395948_noop.up.sql
  migrations/frontend/1528395961_make_batch_change_last_applied_at_nullable.down.sql
  migrations/frontend/1528395961_make_batch_change_last_applied_at_nullable.up.sql
  migrations/frontend/1528395962_drop_unused_last_external_service_column.down.sql
  migrations/frontend/1528395962_drop_unused_last_external_service_column.up.sql
  migrations/frontend/1528395963_settings_migration_out_of_band.down.sql
  migrations/frontend/1528395963_settings_migration_out_of_band.up.sql
  migrations/frontend/1528395964_cache_entry_persist.down.sql
  migrations/frontend/1528395964_cache_entry_persist.up.sql
Labels: cla-signed

#29171 notebooks: list API
  cmd/frontend/graphqlbackend/notebooks.go
  cmd/frontend/graphqlbackend/notebooks.graphql
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
Labels: cla-signed

#29039 notebooks: update and delete API
  cmd/frontend/graphqlbackend/notebooks.go
  cmd/frontend/graphqlbackend/notebooks.graphql
  enterprise/cmd/frontend/internal/notebooks/resolvers/apitest/convert.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
Labels: cla-signed

#29038 notebooks: create, update, delete, and list API
  cmd/frontend/graphqlbackend/notebooks.go
  cmd/frontend/graphqlbackend/notebooks.graphql
  enterprise/cmd/frontend/internal/notebooks/resolvers/apitest/convert.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
Labels: cla-signed

#29364 CI: fix build logs uploading and drop now unused sg flag
  dev/sg/main.go
  enterprise/dev/upload-build-logs.sh
Labels: dx, sg, ci, cla-signed

#29398 dev/release Update configuration file for patch 3.35.1
  dev/release/release-config.jsonc
Labels: cla-signed

#29382 Add `sg db ...` to create users and resed dbs
  dev/sg/config.go
  dev/sg/internal/run/run.go
  dev/sg/main.go
  dev/sg/sg_db.go
  dev/sg/sg_reset.go
  doc/dev/background-information/sg/index.md
  internal/conf/conf.go
Labels: dx, dx-announce, team/devx, cla-signed

#29407 Do not parse current browser location for every symbol
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Labels: cla-signed

#29415 buildchecker: remove unused GitHubClient and email func
  dev/buildchecker/checker.go
  dev/buildchecker/main.go
  dev/buildchecker/slack_user_resolver.go
Labels: cla-signed

#29388 Remove log4j banner from homepage
  client/web/src/search/home/LoggedOutHomepage.tsx
  client/web/src/search/home/VulnerabilityAnnouncement.module.scss
  client/web/src/search/home/VulnerabilityAnnouncement.tsx
  client/web/src/search/panels/HomePanels.tsx
  client/web/src/settings/temporary/TemporarySettings.ts
Labels: cla-signed

#29391 cleanup old vagrant tests
  .buildkite/vagrant-run.sh
  .dockerignore
  .gitignore
  dev/ci/test/README.md
  dev/ci/test/Vagrantfile
  dev/ci/test/e2e/test.sh
  dev/ci/test/qa/test.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: dx, team/devx, cla-signed

#28915 ci: add a command to capture errors in scripts
  dev/ci/sentry-capture.sh
  enterprise/dev/upload-build-logs.sh
Labels: dx, ci, dx-announce, cla-signed, RFC-497

#29418 ci: use sg as binary name to fix issues with conf
  enterprise/dev/upload-build-logs.sh
Labels: dx, ci, cla-signed

#29397 Fix: CTA margins
  client/web/src/repo/actions/InstallBrowserExtensionAlert.tsx
  client/web/src/repo/actions/__snapshots__/InstallBrowserExtensionAlert.test.tsx.snap
Labels: cla-signed

#29423 make initsg more friendly for local use
  dev/ci/test/cluster/cluster-test.sh
  dev/ci/test/code-intel/test-against-server.sh
  dev/ci/test/qa/test.sh
  dev/ci/test/upgrade/test.sh
  internal/cmd/init-sg/main.go
Labels: dx, team/devx, cla-signed

#29425 Warn users against updating to 3.35 for the time being
  CHANGELOG.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
Labels: cla-signed

#29426 enable enterprise mode oob migrations after oobmigrator moved to worker
  enterprise/cmd/frontend/main.go
  enterprise/cmd/worker/main.go
Labels: cla-signed

#28775 security: enable public access of our GraphQL/Search/etc APIs from any domain/origin
  CHANGELOG.md
  cmd/frontend/internal/cli/http.go
  doc/dev/security/csrf_security_model.md
Labels: security, apidocs, cla-signed

#29428 enable enterprise mode oob migrations after oobmigrator moved to worker
  enterprise/cmd/frontend/main.go
Labels: cla-signed

#29417 Use sourcegraph/syntect with a newer syntect version.
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/src/main.rs
Labels: cla-signed

#29405 perms_syncer: reduce usage of `database.Mocks`
  enterprise/cmd/repo-updater/internal/authz/integration_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  enterprise/cmd/repo-updater/main.go
Labels: cla-signed

#29409 Remove tooltips from symbol sidebar
  client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Labels: team/frontend-platform, cla-signed

#29433 Revert "Use sourcegraph/syntect with a newer syntect version."
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/src/main.rs
Labels: cla-signed

#29402 Use radio buttons to toggle retention & indexing in policy
  client/web/src/components/FilteredConnection/FilterControl.tsx
  client/web/src/components/RadioButtons.tsx
  client/web/src/enterprise/codeintel/configuration/components/DurationSelect.tsx
  client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx
  client/web/src/enterprise/codeintel/configuration/components/RetentionSettings.module.scss
  client/web/src/enterprise/codeintel/configuration/components/RetentionSettings.tsx
  client/web/src/site-admin/SiteAdminUsageStatisticsPage.tsx
Labels: cla-signed

#29337 HK: Replace literal "/search" with corresponding route constant
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/auth/welcome/StartSearching.tsx
  client/web/src/nav/NavBar/NavBar.tsx
  client/web/src/routes.tsx
  client/web/src/search/home/SearchPageFooter.tsx
  client/web/src/site-admin/init/SiteInitPage.tsx
  client/web/src/tracking/withActivation.tsx
Labels: team/frontend-platform, cla-signed

#29437 Update CHANGELOG with GQL suggestions removal
  CHANGELOG.md
Labels: cla-signed

#29303 monitoring: add panels for shard merging
  doc/admin/observability/dashboards.md
  monitoring/definitions/zoekt_index_server.go
Labels: cla-signed

#29431 doc: use .api/search/stream in stream API docs
  CHANGELOG.md
  doc/api/stream_api/index.md
Labels: cla-signed

#29432 `<Tooltip />`: Improve webapp performance
  client/branded/src/components/BrandedStory.tsx
  client/web/.eslintrc.js
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/components/WebStory.tsx
  client/web/src/enterprise/codeintel/configuration/components/ReposMatchingPattern.tsx
  client/wildcard/src/components/Tooltip/Tooltip.tsx
Labels: team/frontend-platform, cla-signed

#29440 Remove official docs for blue-green deployments
  doc/admin/install/kubernetes/update.md
Labels: cla-signed

#29442 migrations: Fix conflicting migration number
  migrations/frontend/1528395965_add_search_contexts_query.down.sql
  migrations/frontend/1528395965_add_search_contexts_query.up.sql
Labels: cla-signed

#29439 Fix MonacoQueryInput log spam
  client/web/src/enterprise/insights/components/form/monaco-field/MonacoField.tsx
  client/web/src/search/input/MonacoQueryInput.tsx
Labels: team/frontend-platform, cla-signed

#29421 Remove `MockUsers`
  cmd/frontend/internal/app/debug_test.go
  cmd/frontend/internal/session/session.go
  cmd/frontend/internal/session/session_test.go
  enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go
  enterprise/cmd/frontend/internal/auth/openidconnect/middleware_test.go
  enterprise/cmd/frontend/internal/auth/saml/middleware.go
  enterprise/cmd/frontend/internal/auth/saml/middleware_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/resolver_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration_test.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users.go
  enterprise/cmd/frontend/internal/licensing/enforcement/users_test.go
  enterprise/internal/batches/store/batch_changes.go
  enterprise/internal/batches/store/changesets.go
  enterprise/internal/codeintel/stores/dbstore/configuration_policies.go
  enterprise/internal/codeintel/stores/dbstore/indexes.go
  enterprise/internal/codeintel/stores/dbstore/repo.go
  enterprise/internal/codeintel/stores/dbstore/uploads.go
  enterprise/internal/codeintel/stores/dbstore/xrepo.go
  enterprise/internal/insights/store/permissions.go
  internal/database/mockstores.go
  internal/database/repos.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  internal/database/search_contexts.go
  internal/database/users.go
  internal/database/users_mock.go
  internal/search/commit/commit_new.go
  internal/search/commit/commit_new_test.go
Labels: cla-signed

#29220 buildchecker: allow multiple channel announcements
  .github/workflows/buildchecker.yml
  dev/buildchecker/main.go
  dev/buildchecker/run.sh
  dev/buildchecker/slack.go
Labels: cla-signed, okr/ci-downtime

#29424 monitoring: create uniform variables API for dashboards
  doc/dev/how-to/monitoring_local_dev.md
  monitoring/definitions/executor.go
  monitoring/definitions/git_server.go
  monitoring/definitions/zoekt_index_server.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#28522 Background task to check for any repos w/ last_error nonempty and update
  cmd/repo-updater/shared/main.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/repos/integration_test.go
  internal/repos/sync_errored.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: team/repo-management, cla-signed

#29453 search: do not parenthesize query
  client/shared/src/search/stream.ts
Labels: cla-signed

#29448 search: Handle empty repository revisions in context UI
  client/web/src/enterprise/searchContexts/SearchContextForm.tsx
Labels: cla-signed

#29422 Remove additional unused global mock stores
  internal/database/external_accounts.go
  internal/database/mockstores.go
  internal/database/sub_repo_perms_store.go
  internal/database/user_emails.go
  internal/database/user_emails_mock.go
Labels: cla-signed

#29451 search: Improve tracing of dynamic search contexts
  cmd/frontend/graphqlbackend/search.go
  internal/search/searchcontexts/search_contexts.go
Labels: cla-signed

#29450 Update index.md
  doc/index.md
Labels: cla-signed

#29461 release: sourcegraph@3.35.1
  CHANGELOG.md
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/install/docker-compose/aws.md
  doc/admin/install/docker-compose/digitalocean.md
  doc/admin/install/docker-compose/google_cloud.md
  doc/admin/install/docker-compose/operations.md
  doc/admin/install/docker/aws.md
  doc/admin/install/docker/digitalocean.md
  doc/admin/install/docker/google_cloud.md
  doc/admin/install/docker/index.md
  doc/admin/install/docker/operations.md
  doc/admin/install/kubernetes/configure.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  doc/dev/how-to/testing.md
  doc/index.md
Labels: cla-signed

#29464 release: Update for 3.36.0 release
  dev/release/release-config.jsonc
Labels: cla-signed

#29465 release: Add new get-started page to about batch change
  dev/release/src/release.ts
Labels: cla-signed

#29463 compute: fix match-only command to add all matches on a single line
  internal/compute/match_only_command.go
  internal/compute/match_only_command_test.go
Labels: cla-signed

#29441 frontend: remove redundant route registration for GitHub webhook
  cmd/frontend/internal/httpapi/httpapi.go
Labels: cla-signed

#28721 Wildcard V2: `<Panel />` Implementation
  client/wildcard/src/components/Panel/Panel.module.scss
  client/wildcard/src/components/Panel/Panel.story.tsx
  client/wildcard/src/components/Panel/Panel.test.tsx
  client/wildcard/src/components/Panel/Panel.tsx
  client/wildcard/src/components/Panel/__snapshots__/Panel.test.tsx.snap
  client/wildcard/src/components/Panel/constants.ts
  client/wildcard/src/components/Panel/index.ts
  client/wildcard/src/components/Panel/useResizablePanel.ts
  client/wildcard/src/components/index.ts
Labels: gitstart, cla-signed

#29466 monitoring: fix typo in panel legend
  monitoring/definitions/zoekt_index_server.go
Labels: cla-signed

#29443 Update web-standalone success banner to be informative and green
  client/web/dev/server/development.server.ts
  client/web/dev/utils/success-banner.js
  client/web/gulpfile.js
  sg.config.yaml
Labels: team/frontend-platform, cla-signed

#29469 search: Handle empty repository revisions in GraphQL resolver
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers.go
Labels: cla-signed

#29430 search: use /.api/search/stream for backend integration tests
  internal/gqltestutil/search.go
Labels: cla-signed

#29065 syntax: add sampled honeycomb to syntax highlighting
  cmd/frontend/internal/highlight/highlight.go
  doc/admin/observability/dashboards.md
  monitoring/definitions/syntect_server.go
Labels: team/code-intelligence, syntect_server, cla-signed, observability

#29458 search: promote "required" property of search jobs before doResults
  cmd/frontend/graphqlbackend/search_results.go
  internal/search/symbol/symbol.go
Labels: cla-signed

#29478 remove unused args and return values
  cmd/frontend/graphqlbackend/search_contexts.go
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers.go
Labels: cla-signed

#29324 Code Insights: Fix bad capture group specific tracking keys
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx
Labels: bug, team/code-insights, cla-signed

#29480 Do not exit early on partial commit search failure
  internal/search/commit/commit_new.go
Labels: cla-signed

#22692 add repo rev to predicate evaluation
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_test.go
Labels: cla-signed

#29489 search: fix issue preventing search patterns with @
  CHANGELOG.md
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  internal/search/run/repository.go
  internal/search/run/repository_test.go
Labels: cla-signed

#29493 images: update dependencies to always use >=
  .hadolint.yaml
  cmd/gitserver/Dockerfile
  cmd/migrator/Dockerfile
  cmd/searcher/Dockerfile
  cmd/server/Dockerfile
  cmd/symbols/Dockerfile
  cmd/worker/Dockerfile
  dev/src-expose/Dockerfile
  docker-images/alpine-3.12/Dockerfile
  docker-images/alpine-3.14/Dockerfile
  docker-images/cadvisor/Dockerfile
  docker-images/cadvisor/build.sh
  docker-images/codeinsights-db/Dockerfile
  docker-images/grafana/Dockerfile
  docker-images/jaeger-agent/Dockerfile
  docker-images/jaeger-all-in-one/Dockerfile
  docker-images/postgres-12.6-alpine/Dockerfile
  docker-images/redis-cache/Dockerfile
  docker-images/redis-store/Dockerfile
  docker-images/syntax-highlighter/Dockerfile
  enterprise/cmd/precise-code-intel-worker/Dockerfile
  enterprise/cmd/worker/Dockerfile
  internal/cmd/git-combine/Dockerfile
  internal/cmd/progress-bot/Dockerfile
  internal/cmd/resources-report/Dockerfile
Labels: cla-signed

#29010 Enabling fuzzy finder to be GA
  CHANGELOG.md
  client/web/src/components/fuzzyFinder/FuzzyFinder.tsx
  client/web/src/components/fuzzyFinder/FuzzyModal.story.tsx
  client/web/src/integration/blob-viewer.test.ts
  client/web/src/integration/repository.test.ts
  client/web/src/search/input/SearchNavbarItem.tsx
  schema/settings.schema.json
Labels: cla-signed

#29360 branded: remove Bootstrap Style `@import bootstrap/scss/progress`
  client/branded/src/global-styles/index.scss
  client/branded/src/global-styles/progress.scss
Labels: gitstart, cla-signed

#29358 branded: remove Bootstrap style `@import bootstrap/scss/button-group`
  client/branded/src/global-styles/button-group.scss
  client/branded/src/global-styles/index.scss
Labels: gitstart, cla-signed

#29497 lib/gitservice: Set pack.windowMemory=100m in git-upload-pack
  cmd/gitserver/server/gitservice.go
  doc/admin/observability/dashboards.md
  lib/gitservice/gitservice.go
  monitoring/definitions/git_server.go
Labels: cla-signed

#29500 settings: Deep merge experimental features
  cmd/frontend/graphqlbackend/search.go
  cmd/frontend/graphqlbackend/settings_cascade.go
  cmd/frontend/graphqlbackend/settings_cascade_test.go
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#29499 insights: Fix for deleted users/orgs in oob settings migration
  enterprise/internal/insights/migration/migration.go
Labels: team/code-insights, cla-signed

#29481 monitoring: add networking dashboard for Zoekt pods
  doc/admin/observability/dashboards.md
  doc/dev/how-to/monitoring_local_dev.md
  monitoring/definitions/shared/container.go
  monitoring/definitions/shared/provisioning.go
  monitoring/definitions/shared/shared.go
  monitoring/definitions/zoekt_index_server.go
  monitoring/monitoring/dashboards.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#29494 search frontend: helper to detect operators for queries with context
  client/shared/src/search/query/transformer.test.ts
  client/shared/src/search/query/transformer.ts
  client/shared/src/search/query/validate.ts
Labels: cla-signed

#29507 search frontend: mint query.ts for query helper functions
  client/shared/src/search/query/query.ts
  client/shared/src/search/query/transformer.test.ts
  client/shared/src/search/query/transformer.ts
  client/shared/src/search/query/validate.test.ts
  client/shared/src/search/query/validate.ts
  client/shared/src/util/url.ts
  client/web/src/Layout.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/search/helpers/queryExample.ts
  client/web/src/search/index.tsx
  client/web/src/search/input/toggles/Toggles.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/components/CreateSearchContextButton.tsx
  client/web/src/search/results/sidebar/helpers.ts
  client/web/src/stores/searchStack.ts
Labels: cla-signed

#29510 search frontend: highlight query filter separator ':' specially
  client/branded/src/global-styles/code.scss
  client/branded/src/global-styles/colors.scss
  client/shared/src/search/query/decoratedToken.test.ts
  client/shared/src/search/query/decoratedToken.ts
  client/shared/src/search/query/hover.test.ts
  client/web/src/components/MonacoEditor.tsx
  client/web/src/components/SyntaxHighlightedSearchQuery.tsx
  client/web/src/components/__snapshots__/SyntaxHighlightedSearchQuery.test.tsx.snap
  client/web/src/search/input/SearchContextDropdown.test.tsx
  client/web/src/search/input/SearchContextDropdown.tsx
  client/web/src/search/panels/__snapshots__/RecentSearchesPanel.test.tsx.snap
  client/web/src/search/panels/__snapshots__/RepositoriesPanel.test.tsx.snap
  client/web/src/search/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/web/src/search/results/sidebar/__snapshots__/FilterLink.test.tsx.snap
Labels: cla-signed

#29429 dev/ci: restructure integration tests, unify test server setup
  .buildkite/pipeline.yml
  dev/ci/backend-integration.sh
  dev/ci/e2e.sh
  dev/ci/integration/README.md
  dev/ci/integration/backend/run.sh
  dev/ci/integration/backend/test.sh
  dev/ci/integration/cleanup-display.sh
  dev/ci/integration/cluster/run.sh
  dev/ci/integration/cluster/storageClass.yaml
  dev/ci/integration/cluster/test.sh
  dev/ci/integration/code-intel/repos.json
  dev/ci/integration/code-intel/run.sh
  dev/ci/integration/code-intel/test.sh
  dev/ci/integration/e2e/run.sh
  dev/ci/integration/e2e/test.sh
  dev/ci/integration/qa/run.sh
  dev/ci/integration/qa/test.sh
  dev/ci/integration/run-integration.sh
  dev/ci/integration/setup-deps.sh
  dev/ci/integration/setup-display.sh
  dev/ci/integration/upgrade/run.sh
  dev/ci/integration/upgrade/test.sh
  dev/ci/test/qa/test.sh
  dev/ci/test/servers.yaml
  dev/run-server-image.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#29511 CHANGELOG: Add entry for query based search contexts
  CHANGELOG.md
Labels: cla-signed

#29517 nix: bump nixpkgs to latest commit
  shell.nix
Labels: cla-signed

#29521 Update lsif-clang installation link
  doc/code_intelligence/how-to/index_a_cpp_repository.md
Labels: cla-signed

#29523 Use repo param in gitserver.CommitsUniqueToBranch
  internal/vcs/git/commits.go
Labels: cla-signed

#28872 migration: Add backwards compatibility check back into CI
  dev/ci/go-backcompat/README.md
  dev/ci/go-backcompat/flakefiles/.gitkeep
  dev/ci/go-backcompat/flakefiles/v3.35.0.json
  dev/ci/go-backcompat/test.sh
  doc/dev/background-information/index.md
  doc/dev/background-information/sql/batch_operations.md
  doc/dev/background-information/sql/index.md
  doc/dev/background-information/sql/materialized_cache.md
  doc/dev/background-information/sql/migrations.md
  doc/dev/index.md
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
  migrations/README.md
Labels: decouple-migrations, cla-signed

#29203 Migrate searchPatternType to global store
  client/web/src/Layout.test.tsx
  client/web/src/Layout.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/communitySearchContexts/CommunitySearchContextPage.tsx
  client/web/src/enterprise/batches/repo/RepositoryBatchChangesArea.tsx
  client/web/src/namespaces/NamespaceArea.tsx
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/org/OrgsArea.tsx
  client/web/src/org/area/OrgArea.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/routes.tsx
  client/web/src/repo/stats/RepositoryStatsArea.tsx
  client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/savedSearches/SavedSearchListPage.tsx
  client/web/src/savedSearches/SavedSearchModal.tsx
  client/web/src/search/helpers.tsx
  client/web/src/search/home/SearchPage.story.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/index.tsx
  client/web/src/search/input/MonacoQueryInput.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/search/input/toggles/QueryInputToggle.tsx
  client/web/src/search/input/toggles/Toggles.tsx
  client/web/src/search/panels/HomePanels.tsx
  client/web/src/search/panels/SavedSearchesPanel.tsx
  client/web/src/search/results/DidYouMean.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/components/CreateCodeInsightButton.tsx
  client/web/src/search/results/sidebar/SearchSidebar.tsx
  client/web/src/search/results/sidebar/SearchTypeLink.tsx
  client/web/src/stores/index.ts
  client/web/src/stores/navbarSearchQueryState.ts
  client/web/src/user/area/UserArea.tsx
Labels: cla-signed

#29272 wildcard: implement FeedbackPrompt
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/components/FeedbackBadge.story.tsx
  client/web/src/components/FeedbackBadge.tsx
  client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
  client/web/src/enterprise/batches/execution/BatchSpecExecutionDetailsPage.tsx
  client/web/src/enterprise/insights/components/beta-feedback-panel/BetaFeedbackPanel.tsx
  client/web/src/extensions/extension/SourcegraphExtensionFeedback.tsx
  client/web/src/marketing/SurveyPage.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.story.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.test.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
  client/web/src/nav/Feedback/index.ts
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/repo/docs/RepositoryDocumentationPage.tsx
  client/web/src/repo/settings/RepoSettingsMirrorPage.tsx
  client/web/src/search/notebook/SearchNotebookPage.tsx
  client/wildcard/src/components/Feedback/FeedbackBadge/FeedbackBadge.module.scss
  client/wildcard/src/components/Feedback/FeedbackBadge/FeedbackBadge.story.tsx
  client/wildcard/src/components/Feedback/FeedbackBadge/FeedbackBadge.test.tsx
  client/wildcard/src/components/Feedback/FeedbackBadge/FeedbackBadge.tsx
  client/wildcard/src/components/Feedback/FeedbackBadge/__snapshots__/FeedbackBadge.test.tsx.snap
  client/wildcard/src/components/Feedback/FeedbackBadge/constant.ts
  client/wildcard/src/components/Feedback/FeedbackBadge/index.ts
  client/wildcard/src/components/Feedback/FeedbackText/FeedbackText.story.tsx
  client/wildcard/src/components/Feedback/FeedbackText/FeedbackText.test.tsx
  client/wildcard/src/components/Feedback/FeedbackText/FeedbackText.tsx
  client/wildcard/src/components/Feedback/FeedbackText/__snapshots__/FeedbackText.test.tsx.snap
  client/wildcard/src/components/Feedback/FeedbackText/index.ts
  client/wildcard/src/components/Feedback/index.ts
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
  client/wildcard/src/components/index.ts
Labels: gitstart, cla-signed

#29037 Add newcomers onboarding tour
  client/shared/src/telemetry/telemetryService.ts
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/featureFlags/FeatureFlagsAgent.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/featureFlags/lib/getOverrideKey.ts
  client/web/src/onboarding-tour/OnboardingTour.module.scss
  client/web/src/onboarding-tour/OnboardingTour.story.tsx
  client/web/src/onboarding-tour/OnboardingTour.tsx
  client/web/src/onboarding-tour/lib/data.ts
  client/web/src/onboarding-tour/lib/useOnboardingTour.ts
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/routes.tsx
  client/web/src/search/documentation/ModalVideo.module.scss
  client/web/src/search/documentation/ModalVideo.tsx
  client/web/src/search/home/LoggedOutHomepage.constants.ts
  client/web/src/search/home/LoggedOutHomepage.module.scss
  client/web/src/search/home/LoggedOutHomepage.tsx
  client/web/src/search/results/NoResultsPage.module.scss
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/sidebar/SearchSidebar.tsx
  client/web/src/tracking/analyticsUtils.tsx
  client/web/src/tracking/eventLogger.ts
Labels: cla-signed

#29449 Move parsedSearchQuery data to query state store
  client/web/src/Layout.tsx
  client/web/src/communitySearchContexts/CommunitySearchContextPage.tsx
  client/web/src/integration/search.test.ts
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/routes.tsx
  client/web/src/search/home/SearchPage.story.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/index.tsx
  client/web/src/search/results/DidYouMean.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/stores/navbarSearchQueryState.ts
Labels: cla-signed

#29508 oobmigration: Validate on frontend startup
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/worker/internal/migrations/init.go
  internal/oobmigration/validate.go
Labels: RFC-311, cla-signed

#29529 Notes added to guide users on C++ LSIF upload errors
  doc/code_intelligence/how-to/index_a_cpp_repository.md
Labels: cla-signed

#29537 Revert "search: concurrent evaluation of OR queries (#29281)"
  cmd/frontend/graphqlbackend/search_results.go
  dev/gqltest/search_test.go
  internal/search/result/file.go
  internal/search/zoekt/indexed_search_test.go
Labels: cla-signed

#29509 increment errored repo metric every iteration
  internal/repos/sync_errored.go
Labels: cla-signed

#29532 dev/ci/integration: unify docker cleanup
  dev/authtest/main_test.go
  dev/ci/integration/e2e/run.sh
  dev/ci/integration/qa/run.sh
  dev/ci/integration/run-integration.sh
  dev/ci/integration/upgrade/run.sh
  dev/ci/integration/upgrade/test.sh
  dev/gqltest/main_test.go
  internal/cmd/init-sg/main.go
  internal/gqltestutil/client.go
Labels: cla-signed

#29485 insights: Add docs for known oob migration issue
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  doc/code_insights/how-tos/Troubleshooting.md
Labels: team/code-insights, cla-signed

#29528 Move owner of Distribution alerts to Devops team
  doc/admin/observability/alert_solutions.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/prometheus.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#29206 tos consent: fix qa tests and some extra fixes
  CHANGELOG.md
  client/web/src/Layout.test.tsx
  client/web/src/Layout.tsx
  client/web/src/auth.ts
  client/web/src/auth/SignUpForm.tsx
  client/web/src/auth/TosConsentModal.module.scss
  client/web/src/auth/TosConsentModal.story.tsx
  client/web/src/auth/TosConsentModal.test.tsx
  client/web/src/auth/TosConsentModal.tsx
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/communitySearchContexts/CommunitySearchContextPage.story.tsx
  client/web/src/enterprise/code-monitoring/testing/util.ts
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.story.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.story.tsx
  client/web/src/integration/extension-registry.test.ts
  client/web/src/integration/graphQlResults.ts
  client/web/src/integration/insights/utils/override-insights-graphql.ts
  client/web/src/regression/codeintel.test.ts
  client/web/src/regression/core.test.ts
  client/web/src/regression/util/api.ts
  client/web/src/search/input/SearchContextCtaPrompt.story.tsx
  client/web/src/search/panels/utils.ts
  client/web/src/site-admin/init/SiteInitPage.tsx
  client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
  client/web/src/util/features.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/hubspot/contacts.go
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/auth/userpasswd/handlers.go
  internal/database/mocks.go
  internal/database/user_emails.go
  internal/database/users.go
Labels: cla-signed

#29541 user invites: web: remove out-of-band margin from welcome page
  client/web/src/auth/PostSignUpPage.module.scss
  client/web/src/auth/PostSignUpPage.tsx
Labels: cla-signed

#29158 Add sg ops update-images
  dev/sg/internal/images/images.go
  dev/sg/internal/images/images_test.go
  dev/sg/main.go
  dev/sg/sg_ops.go
  enterprise/dev/ci/images/images.go
  enterprise/dev/ci/internal/ci/config.go
  go.mod
  go.sum
  lib/output/output.go
Labels: cla-signed

#29365 Apply sub-repo permissions filtering for git.ListFiles
  cmd/worker/workerdb/db.go
  enterprise/internal/codeintel/gitserver/client.go
  internal/vcs/git/tree.go
  internal/vcs/git/tree_test.go
Labels: team/repo-management, cla-signed

#29506 Remove MockRepos
  cmd/frontend/internal/search/metadata.go
  cmd/frontend/internal/search/search_test.go
  cmd/repo-updater/repoupdater/server_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
  internal/database/mockstores.go
  internal/database/repos.go
  internal/database/repos_mock.go
  internal/repos/store.go
Labels: cla-signed

#29344 refactor: extract the new `template-parser` package
  .github/workflows/lsif-ts.yml
  .vscode/settings.json
  client/shared/src/actions/ActionsNavItems.tsx
  client/shared/src/api/client/services/util.test.ts
  client/shared/src/api/client/services/util.ts
  client/shared/src/api/extension/api/context/context.ts
  client/shared/src/api/extension/api/contribution.test.ts
  client/shared/src/api/extension/api/contribution.ts
  client/shared/src/api/extension/extensionHostApi.ts
  client/shared/src/api/extension/extensionHostState.ts
  client/shared/src/api/protocol/contribution.ts
  client/shared/src/hover/actions.ts
  client/shared/tsconfig.json
  client/template-parser/.eslintignore
  client/template-parser/.eslintrc.js
  client/template-parser/README.md
  client/template-parser/babel.config.js
  client/template-parser/jest.config.js
  client/template-parser/package.json
  client/template-parser/src/expr/evaluator.test.ts
  client/template-parser/src/expr/evaluator.ts
  client/template-parser/src/expr/index.ts
  client/template-parser/src/expr/lexer.test.ts
  client/template-parser/src/expr/lexer.ts
  client/template-parser/src/expr/parser.test.ts
  client/template-parser/src/expr/parser.ts
  client/template-parser/src/index.ts
  client/template-parser/src/types.ts
  client/template-parser/tsconfig.json
  dev/foreach-ts-project.sh
  jest.config.js
  tsconfig.all.json
Labels: gitstart, cla-signed

#29513 auth: eliminate usage of global DB mocks
  enterprise/cmd/frontend/internal/auth/githuboauth/main_test.go
  enterprise/cmd/frontend/internal/auth/githuboauth/session.go
  enterprise/cmd/frontend/internal/auth/githuboauth/session_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session_test.go
Labels: cla-signed

#29297 hacktoberfest: fix sentence case in the subheading
  hacktoberfest/hacktoberfest-2021.md
Labels: cla-signed

#29320 Instrument GraphQL requests to publish metrics to Prometheus
  cmd/frontend/internal/httpapi/graphql.go
  cmd/frontend/internal/httpapi/metrics.go
Labels: cla-signed

#29245 Refresh org list on membership acceptance
  client/web/src/org/area/OrgInvitationPage.tsx
Labels: cla-signed

#29561 Ensure sign up form help icon doesn't wrap by itself
  client/web/src/auth/SignUpForm.tsx
Labels: cla-signed

#29336 git: Apply sub-repo permissions to git.ListDirectoryChildren
  enterprise/cmd/precise-code-intel-worker/main.go
  enterprise/internal/codeintel/gitserver/client.go
  internal/vcs/git/tree.go
  internal/vcs/git/tree_test.go
Labels: team/repo-management, cla-signed, PD-503

#29565 Revert "Move parsedSearchQuery data to query state store"
  client/web/src/Layout.tsx
  client/web/src/communitySearchContexts/CommunitySearchContextPage.tsx
  client/web/src/integration/search.test.ts
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/routes.tsx
  client/web/src/search/home/SearchPage.story.tsx
  client/web/src/search/home/SearchPage.test.tsx
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/index.tsx
  client/web/src/search/results/DidYouMean.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/stores/navbarSearchQueryState.ts
Labels: cla-signed

#29563 docs: Fix typo
  doc/dev/background-information/languages/typescript.md
Labels: cla-signed

#29287 Get rid of Bootstrap style imports `client/branded/src/global-styles/nav.scss`
  client/branded/src/global-styles/nav.scss
Labels: gitstart, cla-signed

#29538 codeintel: Upload QOL improvements
  enterprise/cmd/frontend/internal/codeintel/httpapi/auth_middleware.go
  lib/codeintel/upload/progress_reader.go
  lib/codeintel/upload/request.go
  lib/codeintel/upload/retry.go
  lib/codeintel/upload/upload.go
  lib/codeintel/upload/upload_test.go
Labels: team/code-intelligence, cla-signed

#29328 codeintel: add sub-repo permissions filtering as a part of path adjustment process
  enterprise/cmd/frontend/internal/codeintel/resolvers/query.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_definitions_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_diagnostics_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_hover_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_implementations_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_ranges_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_references_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_stencil_test.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_util.go
  enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
  internal/authz/sub_repo_perms.go
Labels: team/repo-management, cla-signed, PD-503

#29568 Wire buildkite analytics to go tests
  dev/ci/go-test.sh
  dev/sg/sg_ci.go
Labels: cla-signed

#29335 codeintel: add tests which cover sub-repo permissions filtering logic for implementations query
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_implementations_test.go
Labels: team/repo-management, cla-signed, PD-503

#29269 add happy path insight dashboards test
  client/web/dev/utils/create-js-context.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardPage.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.test.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
Labels: cla-signed

#29332 codeintel: add tests which cover sub-repo permissions filtering logic for references query
  enterprise/cmd/frontend/internal/codeintel/resolvers/query_references_test.go
Labels: team/repo-management, cla-signed, PD-503

#29577 depgraph: Document syntax to use for {package}.
  dev/depgraph/README.md
Labels: cla-signed

#29572 Code Insights: Remove `allowSiteSettingsEdits` checks
  client/web/src/enterprise/insights/components/creation-ui-kit/visibility-picker/VisibilityPicker.tsx
  client/web/src/enterprise/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/InsightsDashboardCreationContent.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
Labels: team/code-insights, cla-signed

#29213 git: Apply sub-repo filtering on git.NewFileReader
  cmd/frontend/backend/inventory.go
  cmd/frontend/internal/app/ui/raw.go
  cmd/frontend/internal/cli/serve_cmd.go
  internal/authz/sub_repo_perms.go
  internal/vcs/git/blame.go
  internal/vcs/git/blob.go
  internal/vcs/git/blob_test.go
Labels: team/repo-management, cla-signed

#28942 [SG-27732] wildcard: manual migration TextArea
  client/branded/src/global-styles/GlobalStylesStory/FormFieldVariants/FormFieldVariants.tsx
  client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  client/eslint-plugin-wildcard/lib/index.js
  client/web/src/enterprise/batches/detail/changesets/CreateCommentModal.tsx
  client/web/src/enterprise/batches/settings/CodeHostSshPublicKey.tsx
  client/web/src/enterprise/insights/components/form/repositories-field/RepositoriesField.tsx
  client/web/src/enterprise/insights/components/form/repositories-field/RepositoryField.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-filters-form/components/drill-down-reg-exp-input/DrillDownRegExpInput.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.tsx
  client/web/src/marketing/SurveyForm.tsx
  client/web/src/nav/Feedback/FeedbackPrompt.tsx
  client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
  client/wildcard/src/components/Form/FlexTextArea/FlexTextArea.module.scss
  client/wildcard/src/components/Form/FlexTextArea/FlexTextArea.tsx
  client/wildcard/src/components/Form/FlexTextArea/index.ts
  client/wildcard/src/components/Form/TextArea/TextArea.module.scss
  client/wildcard/src/components/Form/TextArea/TextArea.story.tsx
  client/wildcard/src/components/Form/TextArea/TextArea.test.tsx
  client/wildcard/src/components/Form/TextArea/TextArea.tsx
  client/wildcard/src/components/Form/TextArea/__snapshots__/TextArea.test.tsx.snap
  client/wildcard/src/components/Form/index.ts
  client/wildcard/src/components/index.ts
  package.json
Labels: gitstart, cla-signed

#29302 Get rid of Bootstrap style imports `global-styles/list-group.scss`
  client/branded/src/global-styles/list-group.scss
Labels: gitstart, cla-signed

#29362 handle sub-repo permissions filtering in git.DiffPath
  enterprise/cmd/frontend/internal/codeintel/resolvers/position.go
  internal/vcs/git/diff.go
  internal/vcs/git/diff_test.go
Labels: team/repo-management, cla-signed

#29491 Add team to devops notify
  .github/workflows/label-notify.yml
Labels: cla-signed

#29373 Apply sub-repo permissions filtering to git.ReadFile sub repo perms
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/internal/search/decorate.go
  cmd/searcher/search/filter.go
  enterprise/internal/codeintel/gitserver/client.go
  internal/compute/output_command.go
  internal/compute/replace_command.go
  internal/vcs/git/blame.go
  internal/vcs/git/blob.go
  internal/vcs/git/blob_test.go
  internal/vcs/git/tree_test.go
Labels: team/repo-management, cla-signed

#29566 honeycomb: increase syntax highlighting sample rate
  cmd/frontend/internal/highlight/highlight.go
Labels: team/code-intelligence, cla-signed, observability

#29353 batches: Bitbucket Server fork support
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/bitbucketserver_test.go
  enterprise/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetUserFork_already_forked
  enterprise/internal/batches/sources/testdata/golden/TestBitbucketServerSource_GetUserFork_new_fork
  enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetUserFork_already_forked.yaml
  enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetUserFork_bad_username.yaml
  enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetUserFork_new_fork.yaml
  enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetUserFork_not_a_fork.yaml
  enterprise/internal/batches/sources/testdata/sources/TestBitbucketServerSource_GetUserFork_not_forked_from_parent.yaml
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/bitbucketserver/client_test.go
  internal/extsvc/bitbucketserver/testdata/golden/CreateFork
  internal/extsvc/bitbucketserver/testdata/vcr/CreateFork.yaml
Labels: bitbucket, team/batchers, forks, cla-signed

#29581 tos consent: fix hubspot sync
  cmd/frontend/hubspot/contacts.go
Labels: cla-signed

#29585 dev/ci: fix default version format
  enterprise/dev/ci/images/images.go
  enterprise/dev/ci/internal/ci/config.go
Labels: cla-signed

#29557 docs: fix not found pages and version fallback
  doc/_resources/templates/document.html
Labels: team/devx, cla-signed

#29457 RFC 519: Add LSIF typed schema
  buf.gen.yaml
  buf.work.yaml
  lib/codeintel/lsif_typed/lsif.pb.go
  lib/go.mod
  lib/go.sum
  proto/buf.yaml
  proto/lib/codeintel/lsif_typed/lsif.proto
Labels: cla-signed

#29367 batches: add fork indicators in the UI
  client/web/src/enterprise/batches/Branch.story.tsx
  client/web/src/enterprise/batches/Branch.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.mock.ts
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.mock.ts
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetInfoCell.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.story.tsx
  client/web/src/enterprise/batches/execution/WorkspacesList.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/batches/preview/list/backend.ts
  client/web/src/enterprise/batches/repo/testData.ts
  client/web/src/integration/batches.test.ts
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec.go
Labels: team/batchers, forks, cla-signed, frontend

#29484 redact auth provider secrets in UI
  cmd/frontend/graphqlbackend/site.go
  internal/conf/validate.go
  internal/conf/validate_test.go
Labels: team/repo-management, cla-signed

#29606 honeycomb: fix double adding fields to honeycomb event
  internal/observation/observation.go
Labels: cla-signed, observability

#29605 Add protobuf generation check to CI
  dev/proto-generate.sh
  dev/tools.go
  go.mod
  go.sum
  lib/codeintel/lsif_typed/lsif.pb.go
  proto/gen.go
  proto/lib/codeintel/lsif_typed/lsif.proto
Labels: cla-signed

#29603 Add TypeScript bindings for LSIF typed
  .prettierignore
  buf.gen.yaml
  lib/codeintel/lsif_typed/lsif.ts
  lib/codeintel/lsif_typed/package.json
  package.json
  yarn.lock
Labels: cla-signed

#29608 CI: Install yarn deps prior to generate
  dev/proto-generate.sh
Labels: cla-signed

#29614 mailmap: update replacements for Joe
  .mailmap
Labels: cla-signed

#29616 set default clock on codeMonitorStore
  enterprise/internal/database/database.go
Labels: cla-signed

#29549 Link to docs on incoming webhooks
  doc/admin/observability/alerting.md
Labels: cla-signed

#29512 httptrace: delete deleted lines
  internal/trace/httptrace.go
Labels: cla-signed

#29611 Run clang-format
  lib/codeintel/lsif_typed/lsif.pb.go
  proto/lib/codeintel/lsif_typed/lsif.proto
Labels: cla-signed

#29626 gomod: bump zoekt
  go.mod
  go.sum
Labels: cla-signed

#29625 monitoring: use streaming endpoint for search duration
  CHANGELOG.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/frontend.go
Labels: cla-signed

#29627 ci: make server volume unique per build
  dev/run-server-image.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: dx, ci, team/devx, cla-signed

#29612 Code Insights: Remove `allowSiteSettingsEdits` check in dashboard visibility tooltip
  client/web/src/enterprise/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/utils/get-global-subject-tooltip-text.ts
Labels: team/code-insights

#29628 Delete unused `InfoDropdown` component
  client/web/src/search/input/InfoDropdown.module.scss
  client/web/src/search/input/InfoDropdown.tsx
Labels: team/frontend-platform, cla-signed
