Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-01, with the labels that each got.

#46020 update go-jsonschema dep
  go.mod
  go.sum
Labels: cla-signed

#46009 internal/repos: Add ping like check to checkConnection
  internal/repos/check_connection.go
  internal/repos/check_connection_test.go
Labels: feature, cla-signed, site-admin-ux

#46022 remove deprecated browser extension completion and link preview providers
  client/browser/src/browser-extension/options-menu/OptionsPage.story.tsx
  client/browser/src/browser-extension/web-extension-api/types.ts
  client/browser/src/shared/code-hosts/gerrit/codeHost.ts
  client/browser/src/shared/code-hosts/github/codeHost.tsx
  client/browser/src/shared/code-hosts/github/contentViews.ts
  client/browser/src/shared/code-hosts/github/tooltip.test.ts
  client/browser/src/shared/code-hosts/github/tooltip.ts
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/code-hosts/shared/contentViews.test.ts
  client/browser/src/shared/code-hosts/shared/contentViews.ts
  client/browser/src/shared/util/optionFlags.ts
  client/extension-api/src/sourcegraph.d.ts
  client/shared/src/api/contract.ts
  client/shared/src/api/extension/extensionApi.ts
  client/shared/src/api/extension/extensionHostApi.ts
  client/shared/src/api/extension/extensionHostState.ts
  client/shared/src/api/integration-test/content.test.ts
  client/shared/src/codeintel/legacy-extensions/api.ts
  client/shared/src/components/linkPreviews/linkPreviews.test.ts
  client/shared/src/components/linkPreviews/linkPreviews.ts
Labels: cla-signed

#46002 [Users Management] update sorting nulls last
  internal/users/stats.go
Labels: cla-signed, team/iam

#46028 fix(sg): Added ZDOTDIR to usershell guess
  dev/sg/internal/usershell/usershell.go
Labels: dx, sg, cla-signed

#46030 use term `code host` instead of `external service` `ExternalServicePage` component
  client/web/src/components/externalServices/ExternalServicePage.tsx
Labels: team/repo-management, cla-signed

#46029 externalServices: Better tooltip description of test button
  client/web/src/components/externalServices/ExternalServiceNode.tsx
Labels: cla-signed

#46038 CHANGELOG: Add note about new test code host connection button 🎉
  CHANGELOG.md
Labels: cla-signed

#45864 Set Cloud Trial prefill form data by URL param vs. cookies
  client/search-ui/src/input/SearchContextMenu.tsx
  client/shared/src/util/url.ts
  client/web/src/Layout.tsx
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.story.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/list/GettingStarted.story.tsx
  client/web/src/enterprise/batches/list/GettingStarted.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringGettingStarted.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/insights/CodeInsightsRouter.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.story.tsx
  client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
  client/web/src/enterprise/searchContexts/SearchContextsListPage.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/search/home/QueryExamplesHomepage.tsx
  client/web/src/search/home/SearchPage.tsx
  client/web/src/search/results/SearchResultsInfoBar.test.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
  client/web/src/tour/data/index.tsx
Labels: cla-signed, team/growth-marketing

#45995 site config and settings schemas: allow additionalProperties
  internal/conf/validate_test.go
  schema/schema.go
  schema/settings.schema.json
  schema/site.schema.json
Labels: cla-signed, rm-extension-api

#45599 Search: switch repo pagination to iterator interface
  internal/search/commit/commit.go
  internal/search/job/jobutil/repo_pager_job.go
  internal/search/job/jobutil/repos.go
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  internal/search/structural/structural.go
Labels: cla-signed

#46040 Remove the custom built gitserver using Microsoft fork of git
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: ci, team/devx, cla-signed

#46017 Update block.md with note on default patterntype
  doc/notebooks/blocks.md
Labels: cla-signed

#46046 Remove extension sideloading and GlobalDebug
  client/browser/src/browser-extension/web-extension-api/types.ts
  client/browser/src/shared/code-hosts/shared/codeHost.test.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/code-hosts/shared/extensions.tsx
  client/browser/src/shared/components/GlobalDebug.tsx
  client/browser/src/shared/platform/context.ts
  client/shared/src/api/client/connection.ts
  client/shared/src/api/client/enabledExtensions.ts
  client/shared/src/api/client/mainthread-api.test.ts
  client/shared/src/api/client/mainthread-api.ts
  client/shared/src/api/contract.ts
  client/shared/src/api/integration-test/testHelpers.ts
  client/shared/src/extensions/createLazyLoadedController.ts
  client/shared/src/extensions/createSyncLoadedController.ts
  client/shared/src/extensions/devtools/ActiveExtensionsPanel.tsx
  client/shared/src/extensions/devtools/index.module.scss
  client/shared/src/extensions/devtools/index.tsx
  client/shared/src/platform/context.ts
  client/vscode/src/webview/platform/context.ts
  client/web/src/Layout.tsx
  client/web/src/global/GlobalDebug.module.scss
  client/web/src/global/GlobalDebug.tsx
  client/web/src/platform/context.ts
  client/web/src/settings/SettingsArea.tsx
  client/web/src/settings/SettingsFile.tsx
  client/web/src/settings/SettingsPage.tsx
Labels: cla-signed, rm-extension-api

#46045 remove many removed and unused fields from settings and site config schemas
  client/shared/src/settings/settings.ts
  client/web/src/integration/graphQlResults.ts
  client/web/src/repo/blob/BlobPage.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/settings_cascade.go
  cmd/frontend/graphqlbackend/settings_cascade_test.go
  cmd/frontend/graphqlbackend/site_flags.go
  dev/global-settings.json
  dev/gqltest/search_test.go
  doc/dev/security/csrf_security_model.md
  internal/conf/diff_test.go
  internal/database/conf_test.go
  internal/database/settings_test.go
  internal/search/job/jobutil/job_test.go
  schema/schema.go
  schema/settings.schema.json
  schema/site.schema.json
Labels: cla-signed, rm-extension-api

#45996 remove experimental search stats page (/stats)
  client/web/src/contributions.ts
  client/web/src/enterprise/insights/core/hooks/live-preview-insight/use-live-preview-lang-stats-insight.ts
  client/web/src/enterprise/routes.tsx
  client/web/src/enterprise/search/stats/SearchStatsLanguages.test.tsx
  client/web/src/enterprise/search/stats/SearchStatsLanguages.tsx
  client/web/src/enterprise/search/stats/SearchStatsPage.test.tsx
  client/web/src/enterprise/search/stats/SearchStatsPage.tsx
  client/web/src/enterprise/search/stats/__snapshots__/SearchStatsLanguages.test.tsx.snap
  client/web/src/enterprise/search/stats/__snapshots__/SearchStatsPage.test.tsx.snap
  client/web/src/enterprise/search/stats/backend.ts
  client/web/src/integration/insights/fixtures/runtime-insights.ts
  client/web/src/routes.constants.ts
  client/web/src/search/stats/contributions.ts
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed, rm-extension-api

#46058 Revert "Remove the custom built gitserver using Microsoft fork of git"
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#46060 Search: Improve ref glob check for search context queries
  internal/search/repo_revs.go
  internal/search/searchcontexts/search_contexts.go
  internal/search/searchcontexts/search_contexts_test.go
Labels: cla-signed

#46054 DEV_WEB_BUILDER_OMIT_SLOW_DEPS env var to speed up esbuild rebuild by ~40%
  client/build-config/src/esbuild/packageResolutionPlugin.ts
  client/build-config/src/esbuild/stylePlugin.ts
  client/shared/src/components/NoMonacoEditor.tsx
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/server.ts
  client/web/dev/utils/environment-config.ts
  client/web/src/api/NoApiConsole.tsx
Labels: cla-signed

#46041 graphqlbackend: fix name of repo being added to code host config exclusion.
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
Labels: team/repo-management, cla-signed

#46063 fix apollo cache merge error for Repository by fetching ID in queries
  client/shared/src/codeintel/legacy-extensions/util/api.ts
  client/web/src/batches/backend.ts
  client/web/src/codeintel/ReferencesPanelQueries.ts
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.mock.ts
  client/web/src/enterprise/batches/detail/backend.ts
  client/web/src/integration/graphQlResponseHelpers.ts
Labels: cla-signed

#46055 add 2 env vars to speed up frontend builds
  client/shared/gulpfile.js
  client/web/dev/esbuild/build.ts
  client/web/dev/utils/environment-config.ts
Labels: cla-signed

#46072 build-tracker: rewrite test to not use golden file
  dev/build-tracker/slack_test.go
  dev/build-tracker/testdata/build_golden.json
Labels: team/devx, cla-signed

#45943 Fix auto scroll logic between blob view and reference panel
  .eslintrc.js
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/linenumbers.ts
  client/web/src/repo/blob/codemirror/token-selection/definition.ts
  client/web/src/repo/blob/use-blob-store.ts
  client/web/src/stores/experimentalFeatures.ts
Labels: cla-signed

#46057 search ui: make actions buttone more explicit
  client/web/src/search/results/SearchActionsMenu.tsx
  client/web/src/search/results/__snapshots__/SearchResultsInfoBar.test.tsx.snap
Labels: cla-signed

#46061 docs: fix links to install script
  doc/index.md
Labels: cla-signed

#45966 monitoring: zoekt.go - add p99/90/75 charts for search request duration
  CHANGELOG.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/zoekt.go
Labels: cla-signed

#46042 web: add exclude repo button.
  client/web/src/repo/settings/RepoSettingsOptionsPage.tsx
  client/web/src/repo/settings/backend.ts
  client/web/src/repo/settings/components/ExternalServiceEntry.module.scss
  client/web/src/repo/settings/components/ExternalServiceEntry.tsx
Labels: team/repo-management, cla-signed, site-admin-ux

#46083 search contexts: remove auto-defined contexts graphql api
  CHANGELOG.md
  cmd/frontend/graphqlbackend/search_contexts.go
  cmd/frontend/graphqlbackend/search_contexts.graphql
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/searchcontexts/resolvers/resolvers_test.go
  internal/search/repos/repos_test.go
  internal/search/searchcontexts/search_contexts.go
  internal/search/searchcontexts/search_contexts_test.go
Labels: cla-signed

#46085 email.templates: make 'text' template optional
  CHANGELOG.md
  go.mod
  go.sum
  internal/txemail/siteconfig.go
  internal/txemail/siteconfig_test.go
  internal/txemail/template.go
  internal/txemail/template_test.go
  internal/txemail/txtypes/types.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#45675 Search: reuse goroutine group across all repo revs
  internal/search/commit/commit.go
  internal/search/repos/repos.go
Labels: cla-signed

#46092 monitoring: add more robust UID validation
  monitoring/monitoring/dashboards.go
  monitoring/monitoring/generator.go
  monitoring/monitoring/generator_test.go
  monitoring/monitoring/internal/grafana/uid.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#45676 Search: make `DiffModifiesFile` predicate more efficient
  cmd/gitserver/server/server.go
  internal/gitserver/search/lazy_commit.go
  internal/gitserver/search/match_tree.go
  internal/gitserver/search/search.go
  internal/gitserver/search/search_test.go
Labels: cla-signed

#46106 web: bump `.card-header` specificity
  client/web/src/codeintel/ReferencesPanel.module.scss
Labels: cla-signed, team/code-exploration

#46064 graphqlbackend: move external service exclusion logic to `backend` package.
  cmd/frontend/backend/external_services.go
  cmd/frontend/backend/external_services_test.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
  internal/repoupdater/client.go
Labels: team/repo-management, cla-signed

#46111 graphqlbackend: make `excludeRepoFromExternalService` accept an array of external services.
  client/web/src/repo/settings/backend.ts
  client/web/src/repo/settings/components/ExternalServiceEntry.tsx
  cmd/frontend/backend/external_services.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: team/repo-management, cla-signed, site-admin-ux

#46076 token selection: fix occurrence position in hover request
  client/web/src/repo/blob/codemirror/token-selection/hover.ts
Labels: cla-signed

#46105 fix typo
  cmd/frontend/graphqlbackend/site_admin.go
  cmd/frontend/graphqlbackend/site_admin_test.go
Labels: cla-signed

#46086 search: clean up feature flags
  CHANGELOG.md
  client/search-ui/src/results/StreamingSearchResultsList.tsx
  client/vscode/src/webview/search-panel/SearchResultsView.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/enterprise/embed/EmbeddedWebApp.tsx
  client/web/src/enterprise/routes.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/notebook/NotebookComponent.story.tsx
  client/web/src/notebooks/notebookPage/EmbeddedNotebookPage.tsx
  client/web/src/notebooks/notebookPage/NotebookContent.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepositoryFileTreePage.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/home/SearchPageInput.tsx
  client/web/src/search/index.test.ts
  client/web/src/search/index.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  cmd/frontend/graphqlbackend/settings_cascade_test.go
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#46089 Insights: handle repo revs when filtering by search context
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_view_resolvers_test.go
Labels: cla-signed

#46084 Fuzzy finder: add personalized ranking based on history
  client/web/src/Layout.tsx
  client/web/src/components/fuzzyFinder/FuzzyFiles.tsx
  client/web/src/components/fuzzyFinder/FuzzyFinder.mocks.tsx
  client/web/src/components/fuzzyFinder/FuzzyFinder.tsx
  client/web/src/components/fuzzyFinder/FuzzyFsm.ts
  client/web/src/components/fuzzyFinder/FuzzyLocalCache.ts
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/components/fuzzyFinder/FuzzyQuery.ts
  client/web/src/components/fuzzyFinder/FuzzyRepos.tsx
  client/web/src/components/fuzzyFinder/FuzzySymbols.tsx
  client/web/src/components/fuzzyFinder/FuzzyTabs.tsx
  client/web/src/components/fuzzyFinder/HighlightedLink.tsx
  client/web/src/components/useUserHistory.ts
  client/web/src/fuzzyFinder/AggregateFuzzySearch.ts
  client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.ts
  client/web/src/fuzzyFinder/FuzzySearch.ts
  client/web/src/fuzzyFinder/SearchValue.ts
  client/web/src/fuzzyFinder/SearchValueRankingCache.ts
  client/web/src/fuzzyFinder/WordSensitiveFuzzySearch.ts
Labels: cla-signed

#46132 Insights: clarify docs for repo filters
  doc/code_insights/explanations/code_insights_filters.md
Labels: cla-signed

#46123 Revert "search: fail ListAllIndexed if zoekt is partially available (#45519)"
  internal/search/env.go
Labels: cla-signed

#46119 Comby: move scanner error checking out of loop
  cmd/searcher/internal/search/search_structural.go
  internal/comby/comby.go
Labels: cla-signed

#46122 Comby: use logger.Error instead of log.NamedError
  cmd/searcher/internal/search/search_structural.go
Labels: cla-signed

#46135 proposal: Alternative fix to `NewFirstScanner` behavior
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
  internal/database/basestore/scan_collections.go
Labels: cla-signed

#46128 Code Insights: Add totalCount to the insights connection api
  cmd/frontend/graphqlbackend/insights.go
  cmd/frontend/graphqlbackend/insights.graphql
  enterprise/internal/insights/resolvers/dashboard_resolvers.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
Labels: cla-signed

#46133 Update Store First Scanners to return data from 1st row instead of the last
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
  internal/database/basestore/scan_collections.go
  internal/database/basestore/store_test.go
Labels: cla-signed

#46100 chore: Make variable name more specific
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46099 oobmigration: Run SCIP migrator concurrently
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46102 oobmigration: Hoist scanning functions in SCIP migrator
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46101 oobmigration: Improve error message for SCIP migration
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46104 oobmigration: Make the processDocument method in SCIP migrator pure
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46142 syntax-highlighter: add structured logging
  docker-images/syntax-highlighter/Dockerfile
Labels: cla-signed

#45976 web: eliminate `storybook` & `wildcard` circle
  client/branded/tsconfig.json
  client/browser/tsconfig.json
  client/http-client/src/stories/MockedStoryProvider.tsx
  client/http-client/src/stories/index.ts
  client/http-client/tsconfig.json
  client/jetbrains/tsconfig.json
  client/jetbrains/webview/src/search/input/JetBrainsSearchBox.story.tsx
  client/jetbrains/webview/src/search/results/SearchResultList.story.tsx
  client/search-ui/tsconfig.json
  client/shared/tsconfig.json
  client/storybook/src/decorators/withChromaticThemes/ChromaticRoot/ChromaticRoot.tsx
  client/storybook/src/index.ts
  client/storybook/src/preview.ts
  client/storybook/tsconfig.json
  client/vscode/tsconfig.json
  client/web/src/components/WebStory.tsx
  client/web/src/enterprise/batches/list/BatchChangeNode.story.tsx
  client/web/src/marketing/page/SurveyPage.story.tsx
  client/web/tsconfig.json
  client/wildcard/src/stories/BrandedStory.tsx
  client/wildcard/src/stories/hooks/index.ts
  client/wildcard/src/stories/hooks/useChromaticTheme.ts
  client/wildcard/src/stories/hooks/usePrependStyles.ts
  client/wildcard/src/stories/hooks/useTheme.ts
  client/wildcard/src/stories/index.ts
  client/wildcard/src/stories/utils/isChromatic.ts
  client/wildcard/tsconfig.json
Labels: cla-signed, bazel, team/code-exploration

#45977 web: eliminate `http-client` & `shared` circle
  client/browser/src/shared/backend/requestGraphQl.ts
  client/http-client/src/graphql/apollo/client.ts
  client/http-client/src/graphql/apollo/index.ts
  client/shared/src/api/client/mainthread-api.test.ts
  client/shared/src/backend/apolloCache.ts
  client/shared/src/stories/MockedStoryProvider.tsx
  client/shared/src/stories/index.ts
  client/shared/src/testing/apollo/mockedTestProvider.tsx
  client/web/src/backend/graphql.ts
  client/web/src/backend/persistenceMapper.test.ts
  client/web/src/backend/persistenceMapper.ts
  client/web/src/components/WebStory.tsx
Labels: cla-signed, bazel, team/code-exploration

#46144 web: prevent infinite loop on error in use-feature-flag
  client/web/src/featureFlags/useFeatureFlag.ts
Labels: cla-signed, team/code-exploration

#46118 web: add support of excluding a repo from all code hosts.
  client/web/src/repo/settings/RepoSettingsOptionsPage.module.scss
  client/web/src/repo/settings/RepoSettingsOptionsPage.tsx
  client/web/src/repo/settings/components/ExternalServiceEntry.tsx
Labels: team/repo-management, cla-signed, site-admin-ux

#46140 references panel: fix double scrollbar
  client/web/src/codeintel/ReferencesPanel.module.scss
Labels: cla-signed

#46146 chore: use mock history instead of custom variables.
  cmd/frontend/graphqlbackend/external_services_test.go
Labels: team/repo-management, cla-signed

#46112 security: redact unrecognized auth HTTP headers from logs
  cmd/frontend/internal/httpapi/auth.go
Labels: security, team/devx, cla-signed

#46148 web: add a spinner to code hosts being in sync.
  client/web/src/components/externalServices/ExternalServiceNode.tsx
  client/web/src/components/externalServices/ExternalServicePage.tsx
  client/web/src/components/externalServices/ExternalServicesPage.story.tsx
  client/web/src/components/externalServices/backend.ts
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/site-admin/fixtures.ts
Labels: team/repo-management, cla-signed, site-admin-ux

#45778 Expire credential when changing code host URL
  internal/types/secret.go
  internal/types/secret_test.go
Labels: cla-signed, SSDLC

#46151 chore: Fix local warning from sg lint -fix go
  cmd/server/shared/postgres.go
  internal/txemail/txemail.go
Labels: cla-signed

#46154 chore: disable flaky test
  client/web/src/integration/codemirror-blob-view.test.ts
Labels: cla-signed

#46156 doc: highlight steps for flaky test disabling.
  dev/build-tracker/slack.go
  doc/dev/background-information/ci/index.md
Labels: cla-signed

#46121 Remove the custom built gitserver using Microsoft fork of git (continued)
  dev/build-tracker/build.sh
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: ci, team/devx, cla-signed

#46025 externalServices: Stop fetching fields that are not needed
  client/web/src/components/externalServices/backend.ts
Labels: debt, cla-signed

#46160 Update release-config.jsonc for 4.3.1 patch release
  dev/release/release-config.jsonc
Labels: cla-signed

#46053 rbac: update database permissions on startup
  cmd/frontend/internal/bg/update_permissions.go
  cmd/frontend/internal/cli/serve_cmd.go
  internal/database/permissions.go
  internal/database/permissions_test.go
  internal/rbac/permissions.go
  internal/rbac/schema.yaml
  internal/rbac/types.go
Labels: cla-signed, rbac

#46162 add feature flag for rbac
  client/web/src/featureFlags/featureFlags.ts
Labels: team/batchers, cla-signed, rbac

#46159 rbac: create table for namespace permissions
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1672884222_create_namespace_permissions_table/down.sql
  migrations/frontend/1672884222_create_namespace_permissions_table/metadata.yaml
  migrations/frontend/1672884222_create_namespace_permissions_table/up.sql
  migrations/frontend/squashed.sql
Labels: team/batchers, cla-signed, rbac

#46091 codeintel: Infer index name when converting LSIF to SCIP
  lib/codeintel/lsif/scip/index.go
  lib/codeintel/lsif/scip/index_test.go
  lib/codeintel/lsif/scip/testdata/dump1.lsif.gz
Labels: cla-signed

#46090 Code Insights: Fix drill-down filters UI panel on the dashboard page
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-input/DrillDownInput.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-popover/DrillDownFiltersPopover.tsx
Labels: cla-signed

#46165 codeintel: use new upstream musl coursier builds
  cmd/gitserver/Dockerfile
  cmd/repo-updater/Dockerfile
  cmd/server/Dockerfile
  enterprise/cmd/gitserver/Dockerfile
Labels: team/code-intelligence, cla-signed, package-repos, scip-java

#46137 Code Insights: Add pagination to the all insights view
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/deserialization/create-insight-view.ts
  client/web/src/enterprise/insights/core/backend/gql-backend/index.ts
  client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
  client/web/src/enterprise/insights/pages/all-insights-view/AllInsightsView.module.scss
  client/web/src/enterprise/insights/pages/all-insights-view/AllInsightsView.tsx
  client/web/src/enterprise/insights/pages/all-insights-view/index.ts
  client/web/src/enterprise/insights/pages/all-insights-view/query.ts
  client/web/src/enterprise/insights/pages/dashboards/dashboard-view/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-view/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.story.tsx
  client/web/src/enterprise/insights/pages/dashboards/dashboard-view/components/dashboards-content/components/empty-insight-dashboard/EmptyInsightDashboard.tsx
  client/web/src/integration/insights/dashboards/add-remove-insights.test.ts
  client/web/src/integration/insights/delete-insights.test.ts
  client/web/src/integration/insights/drill-down-filters.test.ts
  client/web/src/integration/insights/utils/override-insights-graphql-api.ts
Labels: cla-signed

#46168 Update CHANGELOG.md for 4.3.1 release
  CHANGELOG.md
Labels: cla-signed

#46097 codeintel: Sanitize SCIP string fields
  enterprise/internal/codeintel/shared/types/scip_canonicalize.go
  enterprise/internal/codeintel/shared/types/scip_sanitize.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46098 oobmigration: Tune SCIP migrator
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46103 oobmigration: Preload additional result chunks in SCIP migrator
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46131 uploads: Read SCIP data along with LSIF data to expose document paths
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents_test.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/testdata/code-intel-extensions@7802976b.sql
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46129 codeintel: Rewrite ranking graph export to use SCIP data
  enterprise/internal/codeintel/uploads/internal/background/mocks_test.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/observability.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/scip_decompressor.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/stream.go
  enterprise/internal/codeintel/uploads/mocks_test.go
  enterprise/internal/codeintel/uploads/ranking.go
Labels: team/code-intelligence, cla-signed, team/language-platform, ranking, rfc-740

#46180 docs: update pure_docker.md for 4.3.1 patch release
  doc/admin/updates/pure_docker.md
Labels: cla-signed

#46181 codeintel: Fix test
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#46147 Smartsearch: map repo filters with GitHub clone URLs to the appropriate regex
  internal/search/smartsearch/rules.go
  internal/search/smartsearch/rules_test.go
  internal/search/smartsearch/smart_search_job.go
  internal/search/smartsearch/testdata/Test_rewriteRepoFilter/rewrite_repo_filter#01.golden
  internal/search/smartsearch/testdata/Test_rewriteRepoFilter/rewrite_repo_filter#02.golden
  internal/search/smartsearch/testdata/Test_rewriteRepoFilter/rewrite_repo_filter#03.golden
  internal/search/smartsearch/testdata/Test_rewriteRepoFilter/rewrite_repo_filter#04.golden
  internal/search/smartsearch/testdata/Test_rewriteRepoFilter/rewrite_repo_filter#05.golden
  internal/search/smartsearch/testdata/Test_rewriteRepoFilter/rewrite_repo_filter.golden
Labels: cla-signed

#46173 release: sourcegraph@4.3.1
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/configure.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
Labels: cla-signed

#46198 web: add polling so that loading spinner can stop when the sync is complete on ExternalServicesPage.
  client/web/src/components/externalServices/ExternalServicesPage.tsx
  client/web/src/site-admin/fixtures.ts
Labels: team/repo-management, cla-signed, site-admin-ux

#46202 sg: Fix incorrect matching of comments in `sg lint -fix go`
  cmd/server/shared/postgres.go
  dev/check/no-localhost-guard.sh
  internal/txemail/txemail.go
Labels: cla-signed

#46043 ci: save golangci-lint across builds
  .gitignore
  enterprise/dev/ci/internal/ci/operations.go
Labels: go, ci, team/devx, cla-signed

#46200 web: do not redirect after excluding the repo in case of many code hosts.
  client/web/src/repo/settings/RepoSettingsOptionsPage.tsx
  client/web/src/repo/settings/components/ExternalServiceEntry.tsx
  client/web/src/repo/settings/components/RedirectionAlert.tsx
Labels: team/repo-management, cla-signed, site-admin-ux

#46203 codeintel: Fix pointer <> nullable column issue
  enterprise/internal/codeintel/uploads/internal/store/store_uploads.go
  enterprise/internal/codeintel/uploads/internal/store/store_uploads_test.go
Labels: cla-signed

#46191 Make line-number layout always align to top
  client/web/src/repo/blob/codemirror/linenumbers.ts
Labels: cla-signed

#46174 [language-platform] infer name and version from scip index
  lib/codeintel/upload/indexer_name.go
Labels: cla-signed

#46166 insights: adjust query costing to add more weight to number of repos
  enterprise/internal/insights/priority/analyzer.go
  enterprise/internal/insights/priority/analyzer_test.go
  enterprise/internal/insights/priority/cost.go
Labels: cla-signed

#45963 insights: remove v1 backfill & just in time insights
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/historical_enqueuer.go
  enterprise/internal/insights/background/historical_enqueuer_test.go
  enterprise/internal/insights/query/capture_group_executor.go
  enterprise/internal/insights/query/compute_executor.go
  enterprise/internal/insights/query/preview_executor.go
  enterprise/internal/insights/query/streaming_query_executor.go
  enterprise/internal/insights/resolvers/dynamic_insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  enterprise/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/internal/insights/resolvers/insight_view_resolvers_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#46182 remove beyang from CODENOTIFY files
  cmd/searcher/CODENOTIFY
  enterprise/cmd/precise-code-intel-worker/CODENOTIFY
  internal/search/CODENOTIFY
Labels: cla-signed

#46185 resendVerificationEmail: do not error if verification email was never sent
  CHANGELOG.md
  cmd/frontend/backend/user_emails.go
Labels: cla-signed

#46186 resetPassword: check if email was sent in UI indicator
  client/web/src/site-admin/UserManagement/components/useUserListActions.tsx
  client/web/src/site-admin/backend.ts
Labels: cla-signed

#46183 client: remove deprecated authenticatedUser.email
  client/shared/src/auth.ts
  client/shared/src/util/url.ts
  client/web/src/Layout.tsx
  client/web/src/auth/SignInPage.test.tsx
  client/web/src/auth/SignUpPage.test.tsx
  client/web/src/communitySearchContexts/CommunitySearchContextPage.story.tsx
  client/web/src/enterprise/batches/list/GettingStarted.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.tsx
  client/web/src/enterprise/batches/preview/list/ChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/PreviewList.story.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.story.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.test.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.story.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.test.tsx
  client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.story.tsx
  client/web/src/enterprise/code-monitoring/components/actions/EmailAction.tsx
  client/web/src/enterprise/code-monitoring/testing/util.ts
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.story.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.story.tsx
  client/web/src/integration/graphQlResults.ts
  client/web/src/marketing/toast/SurveyToast.test.tsx
  client/web/src/repo/RepoHeader.story.tsx
  client/web/src/search/results/SearchResultsInfoBar.test.tsx
  client/web/src/search/results/SearchResultsInfoBar.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/user/settings/research/ProductResearch.test.tsx
  client/web/src/user/settings/research/ProductResearch.tsx
Labels: cla-signed

#46136 Search: return parsed repo filters from queries
  cmd/frontend/graphqlbackend/search_test.go
  enterprise/internal/insights/resolvers/insight_series_resolver.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/query/repo_revs.go
  internal/search/query/repo_revs_test.go
  internal/search/query/types.go
  internal/search/query/validate.go
  internal/search/repo_revs.go
  internal/search/repo_revs_test.go
  internal/search/repos/excluded_job_test.go
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  internal/search/searchcontexts/search_contexts.go
  internal/search/types.go
  internal/search/zoekt/indexed_search_test.go
Labels: cla-signed

#46221 Search: remove unused globbing code
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
  internal/search/query/validate_test.go
Labels: cla-signed

#46230 faster function-incomplete local dev builds without cgo
  cmd/symbols/internal/api/handler.go
  cmd/symbols/internal/api/handler_cgo.go
  cmd/symbols/internal/api/handler_nocgo.go
  cmd/symbols/squirrel/breadcrumbs.go
  cmd/symbols/squirrel/http_handlers.go
  cmd/symbols/squirrel/service.go
Labels: cla-signed, single-program

#45688 batches: restore increased limit of 10 changesets for unlicensed instances
  enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
  enterprise/cmd/frontend/internal/batches/resolvers/resolver_test.go
Labels: bug, team/batchers, cla-signed

#46232 [Manage Code Hosts] fix ui bug
  client/web/src/components/externalServices/ExternalServiceNode.tsx
Labels: cla-signed, team/iam, bug-fix

#43828 batches: use user name/e-mail with unauthored batch specs
  enterprise/cmd/worker/internal/batches/workers/batch_spec_workspace_creator.go
  enterprise/internal/batches/store/author/author.go
  enterprise/internal/batches/store/author/author_test.go
  enterprise/internal/batches/store/worker_workspace_execution.go
  lib/batches/changeset_specs.go
  lib/batches/changeset_specs_test.go
  lib/batches/execution/cache/cache.go
Labels: team/batchers, cla-signed

#46234 Revert "batches: use user name/e-mail with unauthored batch specs"
  enterprise/cmd/worker/internal/batches/workers/batch_spec_workspace_creator.go
  enterprise/internal/batches/store/author/author.go
  enterprise/internal/batches/store/author/author_test.go
  enterprise/internal/batches/store/worker_workspace_execution.go
  lib/batches/changeset_specs.go
  lib/batches/changeset_specs_test.go
  lib/batches/execution/cache/cache.go
Labels: cla-signed

#46188 build: add missing regenerator-runtime dependency
  package.json
  yarn.lock
Labels: cla-signed

#46189 bazel: wrap module style typings in js_library() rule
  client/shared/dev/tools.bzl
Labels: cla-signed

#46150 internal: Persist author in site config
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/internal/cli/config.go
  cmd/frontend/internal/cli/config_test.go
  internal/conf/conf.go
  internal/conf/mocks_test.go
  internal/conf/server.go
  internal/database/conf.go
  internal/database/conf_test.go
  internal/database/mocks_temp.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1672897105_add_column_author_user_id_to_critical_and_site_config/down.sql
  migrations/frontend/1672897105_add_column_author_user_id_to_critical_and_site_config/metadata.yaml
  migrations/frontend/1672897105_add_column_author_user_id_to_critical_and_site_config/up.sql
  migrations/frontend/squashed.sql
Labels: feature-request, site-admin, cla-signed, site-admin-ux

#46235 graphqlbackend: Extract availabilityState into its own resolver
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/external_services_test.go
Labels: debt, cla-signed

#46220 scaletesting: use config path in bitbucket copy
  dev/scaletesting/codehostcopy/bitbucket.go
Labels: team/devx, cla-signed

#46169 FuzzyFinder: add a ctrl-g binding to close the popup
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
Labels: cla-signed

#46238 web: make current ExternalServicePage and ExternalServiceEditPage.
  client/web/src/components/externalServices/AddExternalServicePage.tsx
  client/web/src/components/externalServices/ExternalServiceEditPage.module.scss
  client/web/src/components/externalServices/ExternalServiceEditPage.story.tsx
  client/web/src/components/externalServices/ExternalServiceEditPage.tsx
  client/web/src/components/externalServices/ExternalServiceNode.tsx
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/repo/settings/components/ExternalServiceEntry.tsx
  client/web/src/site-admin/SiteAdminExternalServicesArea.tsx
  cmd/repo-updater/shared/main.go
Labels: team/repo-management, cla-signed, site-admin-ux

#46206 insights: enqueue retention work from a separate goroutine
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/background/queryrunner/work_handler.go
  enterprise/internal/insights/background/retention_enqueuer.go
Labels: cla-signed

#45805 zoekt: update to sourcegraph/zoekt@e83da22a8767fbdf3bacf22d30706ce979bf44ff
  go.mod
  go.sum
Labels: cla-signed

#46209 codeintel: bring audit logs upload_size type in-line with lsif_uploads table
  CHANGELOG.md
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1673019611_lsif_uploads_audit_logs_bigint_upload_size/down.sql
  migrations/frontend/1673019611_lsif_uploads_audit_logs_bigint_upload_size/metadata.yaml
  migrations/frontend/1673019611_lsif_uploads_audit_logs_bigint_upload_size/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform

#46246 codeintel: show commit tags in dependents/dependencies list for upload
  client/web/src/enterprise/codeintel/uploads/components/DependencyOrDependentNode.tsx
Labels: team/code-intelligence, cla-signed

#46229 Code Insights: Fix code insights creation UI pages headers
  client/web/src/enterprise/insights/pages/insights/creation/InsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/compute/ComputeInsightCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/compute/ComputeInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.story.tsx
  client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.tsx
  client/web/src/enterprise/insights/pages/insights/edit-insight/EditInsightPage.tsx
Labels: cla-signed

#46228 Code Insights: Adjust insight routes
  client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/lang-stats-insight-card/LangStatsInsightCard.tsx
Labels: cla-signed

#45667 repos: log corruption events per repo
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/mocks_temp.go
  internal/database/repos_test.go
  internal/database/schema.json
  internal/database/schema.md
  internal/types/types.go
  migrations/frontend/1670934184_add_gitserver_corruption_columns/down.sql
  migrations/frontend/1670934184_add_gitserver_corruption_columns/metadata.yaml
  migrations/frontend/1670934184_add_gitserver_corruption_columns/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#46252 codeintel: fix upload expiration dashboard
  doc/admin/observability/dashboards.md
  monitoring/definitions/shared/codeintel_uploads.go
Labels: monitoring, monitoring-generator, cla-signed, team/language-platform

#46241 web: make Exclude repository button width consistent during loading + fix spinner.
  client/web/src/repo/settings/RepoSettingsOptionsPage.tsx
  client/web/src/repo/settings/components/ExternalServiceEntry.module.scss
  client/web/src/repo/settings/components/ExternalServiceEntry.tsx
Labels: team/repo-management, cla-signed, site-admin-ux

#46251 Revert "Remove noop extension controler (#45926)"
  client/shared/src/codeintel/api.ts
  client/shared/src/extensions/createNoopLoadedController.ts
  client/web/src/SourcegraphWebApp.tsx
Labels: cla-signed, team/code-exploration

#45988 Expose corruptedAt and CorruptionLog on Graphql API
  client/web/src/repo/settings/backend.ts
  client/web/src/site-admin/backend.ts
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/types/types.go
Labels: cla-signed

#46257 monitoring: change heatmap color scheme from viridis to turbo
  monitoring/monitoring/panel_options.go
Labels: monitoring, monitoring-generator, cla-signed

#46255 update use of validation script
  doc/admin/validation.md
Labels: cla-signed

#46256 Code Insights: Extend processing insight state message
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-alerts/BackendInsightAlerts.module.scss
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-alerts/BackendInsightAlerts.tsx
Labels: cla-signed

#46254 Code Insights: Add human-readable gateway error message
  client/web/src/enterprise/insights/core/hooks/live-preview-insight/use-live-preview-series-insight.ts
Labels: cla-signed

#46210 Update release config for 4.4.0 release
  dev/release/release-config.jsonc
Labels: cla-signed

#46259 Update release-config.jsonc
  dev/release/release-config.jsonc
Labels: cla-signed

#45794 map host.docker.internal in executors to the Docker host
  enterprise/cmd/executor/internal/command/docker.go
  enterprise/cmd/executor/internal/command/docker_test.go
  enterprise/cmd/executor/internal/command/runner.go
  enterprise/cmd/executor/internal/run/util.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, single-program

#46194 vscode: migrate to pnpm
  client/vscode/.vscodeignore
  client/vscode/scripts/package.ts
  client/vscode/scripts/publish.ts
  client/vscode/webpack.config.js
Labels: cla-signed, bazel, team/code-exploration, aspect-dev

#46272 graphqlbackend: remove duplicate import in test
  cmd/frontend/graphqlbackend/org_test.go
Labels: cla-signed

#46279 ci: remove useless flag when building containers
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#46277 dbworker: do not return pointer to ResetterMetrics
  enterprise/internal/insights/background/background.go
  enterprise/internal/insights/scheduler/backfill_state_inprogress_handler.go
  enterprise/internal/insights/scheduler/backfill_state_new_handler.go
  internal/repos/webhook_build_job.go
  internal/workerutil/dbworker/resetter.go
Labels: cla-signed

#46274 web: lower `.card` priority
  client/wildcard/src/components/Card/Card.module.scss
Labels: cla-signed, css-order-in-production, team/code-exploration

#46281 codeintel: dont swallow errors in upload retry mechanism
  lib/codeintel/upload/retry.go
  lib/codeintel/upload/upload.go
Labels: team/code-intelligence, src-cli, cla-signed, team/language-platform

#46262 sg: Allow dev build of src-cli in checks
  dev/sg/dependencies/helpers.go
Labels: cla-signed

#46271 web: add support of created and updated dates without authors in CreatedByAndUpdatedByInfoByline.
  client/web/src/components/Byline/CreatedByAndUpdatedByInfoByline.story.tsx
  client/web/src/components/Byline/CreatedByAndUpdatedByInfoByline.tsx
Labels: team/repo-management, cla-signed, site-admin-ux

#45951 token selection: highlight hovered token
  client/web/src/repo/blob/codemirror/hovercard.tsx
  client/web/src/repo/blob/codemirror/occurrence-utils.ts
  client/web/src/repo/blob/codemirror/token-selection/extension.ts
  client/web/src/repo/blob/codemirror/token-selection/hover.ts
Labels: cla-signed

#46208 token selection: fix infer occurrence at position method
  client/web/src/repo/blob/codemirror/occurrence-utils.ts
Labels: cla-signed

#46287 codeintel: add scip-ruby to indexers list for graphql resolver
  enterprise/internal/codeintel/shared/types/indexers.go
Labels: team/code-intelligence, auto-index, cla-signed, team/language-platform

#46223 Add more clarity to the LastSyncIcon
  client/search-ui/src/components/LastSyncedIcon.tsx
  package.json
  yarn.lock
Labels: cla-signed

#46211 scaletesitng: respect limit when listing repos
  dev/scaletesting/codehostcopy/runner.go
Labels: team/devx, cla-signed

#46184 email: do not send certain emails to unverified emails
  CHANGELOG.md
  client/web/src/enterprise/code-monitoring/components/actions/EmailAction.tsx
  cmd/frontend/backend/user_emails.go
  cmd/frontend/internal/auth/userpasswd/config.go
  enterprise/cmd/frontend/internal/auth/githuboauth/session.go
  enterprise/cmd/frontend/internal/auth/httpheader/middleware.go
  enterprise/internal/codemonitors/background/email.go
  internal/api/internalapi/client.go
  internal/conf/computed.go
  internal/txemail/txemail.go
Labels: cla-signed

#46237 batches: fix `currentSpec` resolution when batch change has no spec applied
  CHANGELOG.md
  enterprise/cmd/frontend/internal/batches/resolvers/apitest/types.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change.go
  enterprise/cmd/frontend/internal/batches/resolvers/batch_change_test.go
  enterprise/internal/batches/store/batch_specs.go
  enterprise/internal/batches/store/batch_specs_test.go
Labels: bug, team/batchers, cla-signed

#46292 monitoring: export (*Dashboard).RenderPrometheusRules()
  monitoring/monitoring/generator.go
  monitoring/monitoring/monitoring.go
  monitoring/monitoring/prometheus.go
Labels: cla-signed

#46294 Wildcard: Fix combobox ui
  client/wildcard/src/components/Combobox/Combobox.tsx
Labels: cla-signed

#46296 prom-wrapper: migrate to sourcegraph/log
  docker-images/prometheus/cmd/prom-wrapper/change.go
  docker-images/prometheus/cmd/prom-wrapper/cmd.go
  docker-images/prometheus/cmd/prom-wrapper/main.go
  docker-images/prometheus/cmd/prom-wrapper/siteconfig.go
  docker-images/prometheus/cmd/prom-wrapper/status.go
Labels: cla-signed

#46298 migration: Fix graphql casing
  cmd/frontend/graphqlbackend/oobmigrations.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed
