Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-11, with the labels that each got.

#58031 Changelog update
  CHANGELOG.md
Labels: cla-signed, team/source

#58037 [Cody Web] update pathname from /cody to /cody/chat
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/routes.constants.ts
  client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
  client/web/src/tour/data/index.tsx
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed

#58022 search jobs: fix query highlighting
  client/shared/src/search/query/scanner.ts
  client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
Labels: cla-signed

#58028 Cody: Update Bedrock endpoint to match documentation
  internal/completions/client/awsbedrock/bedrock.go
Labels: cla-signed, backport 5.2

#58041 Changelog entry for AWS Bedrock endpoint update
  CHANGELOG.md
Labels: cla-signed

#58043 gomod: update zoekt to 5.2 release branch
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, backport/bugfix, backported-to-5.2

#58044 nix: assert typescript version and reduce repetition in nodejs.nix
  dev/nix/nodejs.nix
Labels: cla-signed

#58036 dbworker: include recordID in fetchDebugInformationForJob error
  internal/workerutil/dbworker/store/store.go
Labels: cla-signed

#57998 SCIP ctags: add kinds for Kotlin
  docker-images/syntax-highlighter/crates/scip-syntax/queries/kotlin/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.kt.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_globals.kt.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/globals.kt
Labels: cla-signed

#57882 Auto-update Wolfi base images to latest
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, backport 5.2, wolfi-auto-update

#57990 httpapi: put internal API router next to handlers
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/autoupgrade_servers.go
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal_test.go
  cmd/frontend/internal/httpapi/router/BUILD.bazel
  cmd/frontend/internal/httpapi/router/router.go
Labels: cla-signed, team/source

#58038 github test: make the sorting more stable in test
  internal/authz/providers/github/github_test.go
Labels: cla-signed

#58045 sec: use fresh grafana image
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, backport 5.2

#58050 Chore: remove team notification every time "batch" is mentioned
  .github/workflows/batches-notify.yml
Labels: cla-signed

#58052 remove duplicate option in streams API example
  doc/api/stream_api/index.md
Labels: docs, cla-signed

#58025 Code Navigation: optimize repo link picker
  client/web/BUILD.bazel
  client/web/src/repo/RepoLinkPicker.tsx
  client/web/src/repo/constants.ts
  client/web/src/repo/utils.test.ts
  client/web/src/repo/utils.tsx
Labels: cla-signed

#58010 code intel: Remove search context from search based code intel
  CHANGELOG.md
  client/shared/BUILD.bazel
  client/shared/src/codeintel/legacy-extensions/util/api.ts
  client/shared/src/codeintel/searchContext.ts
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
Labels: cla-signed

#58056 Add back 'ui/assets/' to .prettierignore
  .prettierignore
Labels: cla-signed

#58054 cody-gateway/embeddings: record input_character_count
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
Labels: cla-signed

#58055 Perf: optimize fetching last file commit
  cmd/frontend/graphqlbackend/git_commits.go
Labels: cla-signed

#58062 Release tool: fix a few issues
  dev/release/src/release.ts
  dev/release/src/util.ts
Labels: cla-signed

#58042 blob: Refactor blame decorations
  CHANGELOG.md
  client/shared/src/components/CodeMirrorEditor.tsx
  client/web/BUILD.bazel
  client/web/src/repo/blob/BlameColumn.module.scss
  client/web/src/repo/blob/BlameColumn.tsx
  client/web/src/repo/blob/BlameDecoration.module.scss
  client/web/src/repo/blob/BlameDecoration.tsx
  client/web/src/repo/blob/BlameRecency.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/blameRecency.tsx
  client/web/src/repo/blob/codemirror/blame-decorations.tsx
  client/web/src/repo/blob/codemirror/linenumbers.ts
  client/wildcard/src/global-styles/colors.scss
Labels: cla-signed, code-search

#58051 [Backport 5.2] SCIP ctags: improve kind output
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/queries/c_sharp/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/javascript/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/kotlin/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/python/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/ruby/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/rust/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/typescript/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__ctags__test__ctags_runner_basic.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__globals__test__enclosing_range.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_ctags-empty-scope.rs.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_example.go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.cs.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.js.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.kt.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.py.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.ts.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_go-globals.go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_internal_go.go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_javascript-object.js.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_python-repo-comp.py.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_ruby-globals.rb.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_scopes.rs.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_ctags-empty-scope.rs.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_globals.cs.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_globals.kt.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_globals.py.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_go-globals.go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_ruby-globals.rb.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/ctags-empty-scope.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/globals.kt
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/go-globals.go
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/ruby-globals.rb
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/go/highlights.scm
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__golang.go.snap
Labels: cla-signed, backport/bugfix

#58070 bazel: upgrade rules rust
  WORKSPACE
Labels: cla-signed

#58067 Auto-update Wolfi base images to latest
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, backport 5.2, wolfi-auto-update

#57959 gitserver: Add observability around ensureRevision
  cmd/gitserver/internal/BUILD.bazel
  cmd/gitserver/internal/ensurerevision.go
  cmd/gitserver/internal/server.go
Labels: cla-signed, team/source

#58073 bazel: fix depgard regexp typo
  dev/ci/internal/ci/BUILD.bazel
  dev/ci/internal/ci/bazel_operations.go
  dev/linters/depguard/depguard.go
  dev/sg/ci/BUILD.bazel
  dev/sg/ci/subcommands.go
  dev/sg/internal/wolfi/BUILD.bazel
  dev/sg/internal/wolfi/update_hashes.go
  dev/sg/sg_app.go
  internal/codycontext/BUILD.bazel
  internal/codycontext/context.go
  internal/database/migration/drift/BUILD.bazel
  internal/database/migration/drift/util_search.go
Labels: cla-signed

#58065 Release: add qdrant to images list
  dev/ci/images/images.go
Labels: cla-signed

#58034 do not show "repo last fetched" if it is recent
  client/branded/BUILD.bazel
  client/branded/src/search-ui/components/LastSyncedIcon.tsx
  client/branded/src/search-ui/components/LegacyResultContainer.module.scss
  client/branded/src/search-ui/components/LegacyResultContainer.test.tsx
  client/branded/src/search-ui/components/LegacyResultContainer.tsx
  client/branded/src/search-ui/components/ResultContainer.module.scss
  client/branded/src/search-ui/components/index.ts
Labels: cla-signed

#58061 Admin: add search indexing to repo menu
  client/web/src/site-admin/RepositoryNode.tsx
Labels: cla-signed

#58068 tracer: enforce trace policy entirely via Sampler
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/search_test.go
  internal/instrumentation/http.go
  internal/trace/policy/policy.go
  internal/tracer/BUILD.bazel
  internal/tracer/logged_otel.go
  internal/tracer/otel.go
  internal/tracer/otel_should_trace.go
  internal/tracer/policy_sampler.go
  internal/tracer/policy_sampler_test.go
Labels: cla-signed, backport 5.2, backport/bugfix

#58079 chore: replace tj/assert with testify/assert
  cmd/gitserver/internal/integration_tests/BUILD.bazel
  cmd/gitserver/internal/integration_tests/tree_test.go
  deps.bzl
  go.mod
  internal/extsvc/github/auth/BUILD.bazel
  internal/extsvc/github/auth/auth_test.go
Labels: cla-signed

#58063 release: sourcegraph@5.2.2
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  internal/updatecheck/handler.go
Labels: cla-signed

#58072 blob: Simplify/cleanup some extension usage
  client/shared/src/components/CodeMirrorEditor.tsx
  client/web/BUILD.bazel
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/eof.ts
  client/web/src/repo/blob/codemirror/links.ts
Labels: cla-signed

#58081 Release: deactivate 5.2.2 release
  CHANGELOG.md
  dev/release/release-config.jsonc
Labels: cla-signed

#58086 svelte: Fix build process
  client/shared/dev/generateGraphQlOperations.ts
  client/web-sveltekit/src/routes/UserMenu.svelte
  client/web-sveltekit/vite.config.ts
Labels: cla-signed

#58066 [Cody GA Launch] Improvements to Cody main overview docs page
  doc/_resources/assets/redirects
  doc/cody/core-concepts/cody_clients.md
  doc/cody/overview/index.md
Labels: docs, cla-signed

#58084 [Backport 5.2] tracer: enforce trace policy entirely via Sampler (#58068)
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/search_test.go
  internal/instrumentation/http.go
  internal/trace/policy/policy.go
  internal/tracer/BUILD.bazel
  internal/tracer/logged_otel.go
  internal/tracer/otel.go
  internal/tracer/otel_should_trace.go
  internal/tracer/policy_sampler.go
  internal/tracer/policy_sampler_test.go
Labels: cla-signed, backport/bugfix

#58069 squirrel: Do case-insensitive comparison of file extensions
  cmd/symbols/squirrel/language-file-extensions.json
  cmd/symbols/squirrel/util.go
Labels: cla-signed, backport 5.2, backport/bugfix

#57912 use swc instead of babel for faster bazel typescript transpilation
  .swcrc
  BUILD.bazel
  WORKSPACE
  client/browser/BUILD.bazel
  client/browser/config/BUILD.bazel
  client/browser/src/types/webextension-polyfill/index.d.ts
  client/build-config/BUILD.bazel
  client/shared/src/testing/BUILD.bazel
  client/shared/src/testing/integration/polly/CdpAdapter.ts
  client/web/BUILD.bazel
  client/web/dev/BUILD.bazel
  client/web/scripts/BUILD.bazel
  client/web/src/end-to-end/BUILD.bazel
  client/web/src/integration/BUILD.bazel
  dev/babel.bzl
  dev/defs.bzl
  dev/mocha.bzl
Labels: cla-signed

#58030 fix: Check for known Squirrel errors inside GraphQL responses
  client/shared/src/codeintel/legacy-extensions/util/api.ts
  cmd/symbols/internal/api/handler_cgo.go
  cmd/symbols/squirrel/http_handlers.go
  cmd/symbols/squirrel/util.go
Labels: cla-signed, backport 5.2, backport/bugfix

#58093 client: Remove needless useMemo calls in ref panel code
  client/web/src/codeintel/ReferencesPanel.tsx
Labels: cla-signed

#58094 local: don't let pre-commit run no DB md files
  .pre-commit-config.yaml
Labels: cla-signed

#58095 sg: web-standalone now points at S2
  sg.config.yaml
Labels: cla-signed

#58077 gitserver: more robust DiffSymbols
  cmd/searcher/internal/search/hybrid.go
  internal/gitserver/commands.go
Labels: cla-signed

#58074 [Cody PLG] add mutation & gql field to upgrade users to Cody Pro
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  internal/database/dbmocks/mocks_temp.go
  internal/database/schema.json
  internal/database/schema.md
  internal/database/users.go
  internal/types/types.go
  migrations/frontend/1698836192_add_cody_pro_enabled_at_to_users/down.sql
  migrations/frontend/1698836192_add_cody_pro_enabled_at_to_users/metadata.yaml
  migrations/frontend/1698836192_add_cody_pro_enabled_at_to_users/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#58076 dev: show developer settings for Sourcegraphers
  client/shared/src/settings/temporary/TemporarySettingsStorage.ts
  client/web/src/LegacyLayout.tsx
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/backend/graphql.ts
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/UserNavItem.test.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/stores/devSettings.ts
  client/web/src/storm/app-shell-init.ts
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
Labels: cla-signed

#58100 Search blitz: increase poll interval to 5m
  internal/cmd/search-blitz/main.go
Labels: cla-signed

#58098 syntax-highlighter: update scip to version 0.3.2
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
Labels: cla-signed, team/source

#58101 bzl: do not mount data volumes for e2e tests
  testing/tools/integration_runner.sh
Labels: cla-signed

#58088 GraphQL: add history to TreeEntry
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_tree_history.go
  cmd/frontend/graphqlbackend/git_tree_test.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed, code-search

#58102 Chore: Fix CVE & bump golang dependencies
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, SSDLC

#58104 Code Navigation: Commit expand clean up
  client/web/src/repo/commits/GitCommitNode.module.scss
  client/web/src/repo/commits/GitCommitNodeTableRow.tsx
Labels: cla-signed

#58106 Code Navigation: fix offset diff header
  client/web/src/components/diff/DiffBoundary.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
Labels: cla-signed

#58085 [Backport 5.2] client/web: add telemetry v2 client (#57939)
  client/browser/src/shared/platform/context.ts
  client/shared/BUILD.bazel
  client/shared/package.json
  client/shared/src/platform/context.ts
  client/shared/src/telemetry/index.ts
  client/shared/src/telemetry/telemetryService.ts
  client/web/BUILD.bazel
  client/web/bundlesize.config.js
  client/web/package.json
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/enterprise/embed/EmbeddedWebApp.tsx
  client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.test.tsx
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  client/web/src/platform/context.ts
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/settings/RepoSettingsArea.tsx
  client/web/src/repo/tree/TreePage.test.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
  client/web/src/site-admin/routes.tsx
  client/web/src/telemetry/apolloTelemetryExporter.ts
  client/web/src/telemetry/index.ts
  client/web/src/tracking/eventLogger.ts
  client/web/src/tracking/services/serverAdminWrapper.tsx
  client/web/src/user/area/routes.tsx
  client/web/src/user/settings/UserSettingsArea.tsx
  client/web/src/user/settings/backend.tsx
  enterprise/cmd/worker/internal/telemetrygatewayexporter/exporter.go
  internal/api/internalapi/v1/BUILD.bazel
  internal/licensing/telemetryexport.go
  pnpm-lock.yaml
  sg.config.yaml
Labels: cla-signed, backport/improvement

#58060 eventlogs: add automatic propagation for trace ID
  internal/database/BUILD.bazel
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/telemetry/teestore/teestore.go
  internal/telemetry/teestore/teestore_test.go
  internal/telemetrygateway/v1/BUILD.bazel
  internal/telemetrygateway/v1/backcompat_test.go
  internal/telemetrygateway/v1/event_test.go
  internal/trace/tracetest/BUILD.bazel
  internal/trace/tracetest/tracetest.go
Labels: cla-signed, backport 5.2, backport/improvement

#58080 Code Navigation: fix jumpy revision selector
  client/web/src/repo/RepoRevisionContainer.tsx
Labels: cla-signed

#58111 Update troubleshoot.md
  doc/admin/deploy/kubernetes/troubleshoot.md
Labels: cla-signed

#58113 codehost tests: improve error description
  client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts
Labels: cla-signed

#57854 Unskip flaky sub-repo permissions tests
  cmd/gitserver/internal/perforce/login.go
  dev/gqltest/code_insights_test.go
  dev/gqltest/compute_test.go
  dev/gqltest/external_service_test.go
  dev/gqltest/feature_flag_test.go
  dev/gqltest/sub_repo_permissions_test.go
  internal/gitserver/git_command.go
  internal/gqltestutil/repository.go
Labels: cla-signed, team/source

#58118 prettier: add package to prettier ignore
  .prettierignore
Labels: cla-signed

#58082 scip-ctags: add `kinds` support for C
  docker-images/syntax-highlighter/crates/scip-syntax/queries/c/scip-tags.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_ctags-empty-scope.rs.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_example.c.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.js.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.py.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.ts.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_go-diff.go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_go-globals.go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_javascript-object.js.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_python-repo-comp.py.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_ruby-globals.rb.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_example.c.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/example.c
Labels: cla-signed, team/source

#58092 [Backport 5.2] fix: Check for known Squirrel errors inside GraphQL responses (#58030)
  client/shared/src/codeintel/legacy-extensions/util/api.ts
  cmd/symbols/internal/api/handler_cgo.go
  cmd/symbols/squirrel/http_handlers.go
  cmd/symbols/squirrel/util.go
Labels: cla-signed, backports, backport/bugfix, backported-to-5.2

#58129 blob: Fix missing blame decoration
  client/web/src/repo/blob/codemirror/blame-decorations.tsx
Labels: cla-signed

#58132 Bump hermetic_cc_toolchain to v2.1.2
  WORKSPACE
Labels: cla-signed

#58141 codygateway: Expose allowed models in limiter status endpoint
  cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
Labels: cla-signed, team/source

#58146 bzl: add missing test data for squirrel test
  cmd/symbols/squirrel/BUILD.bazel
Labels: cla-signed

#58152 bzl: add manual tags to a `go_cross_binary` rules that are used with local e2e testing
  dev/codeintel-qa/cmd/clear/BUILD.bazel
  dev/codeintel-qa/cmd/clone-and-index/BUILD.bazel
  dev/codeintel-qa/cmd/download/BUILD.bazel
  dev/codeintel-qa/cmd/query/BUILD.bazel
  dev/codeintel-qa/cmd/upload-gcs/BUILD.bazel
  dev/codeintel-qa/cmd/upload/BUILD.bazel
  internal/cmd/init-sg/BUILD.bazel
Labels: cla-signed

#58096 syntax-highlighter: add `cargo clippy` to bazel builds and fix warnings
  .bazelrc
  dev/codeintel-qa/cmd/clear/BUILD.bazel
  dev/codeintel-qa/cmd/clone-and-index/BUILD.bazel
  dev/codeintel-qa/cmd/download/BUILD.bazel
  dev/codeintel-qa/cmd/query/BUILD.bazel
  dev/codeintel-qa/cmd/upload-gcs/BUILD.bazel
  dev/codeintel-qa/cmd/upload/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/symbols.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/main.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_sciptect.rs
  docker-images/syntax-highlighter/src/main.rs
  internal/cmd/init-sg/BUILD.bazel
Labels: cla-signed, team/source

#58153 Add gpt-4-turbo and new Fireworks model support
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  cmd/cody-gateway/shared/config.go
  internal/completions/httpapi/codecompletion.go
  internal/conf/computed.go
Labels: cla-signed, team/code-exploration

#58155 Add troubleshooting for localStorage in Cody Web
  doc/cody/troubleshooting.md
Labels: cla-signed

#58157 changelog update
  CHANGELOG.md
Labels: cla-signed

#58159 chore: fix typo in csrf_security_model
  doc/dev/security/csrf_security_model.md
Labels: cla-signed

#58135 [Cody GA Docs] Improve Cody for JetBrains extension
  doc/cody/overview/install-jetbrains.md
Labels: docs, cla-signed

#58161 Code Navigation: align EOF message with code mirror content
  client/web/src/repo/blob/codemirror/blame-decorations.tsx
Labels: cla-signed

#58117 sec: Define GraphQL cost limits
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/rate_limit.go
  cmd/frontend/graphqlbackend/search_test.go
  cmd/frontend/graphqlbackend/testing.go
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed, SSDLC, backport 5.2

#58166 Add histogram for GraphQL cost
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed, team/source

#58134 Git blame: make ignoring whitespace configurable
  CHANGELOG.md
  cmd/frontend/graphqlbackend/git_blob.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/gitserver/commands.go
Labels: cla-signed

#58138 Diff view: fix line wrapping
  CHANGELOG.md
  client/web/src/components/diff/DiffHunk.module.scss
  client/web/src/components/diff/DiffHunk.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
Labels: code-navigation, cla-signed

#57930 dev/msp: cron job, private images support
  deps.bzl
  dev/managedservicesplatform/internal/resource/loadbalancer/loadbalancer.go
  dev/managedservicesplatform/internal/resource/privatenetwork/BUILD.bazel
  dev/managedservicesplatform/internal/resource/privatenetwork/privatenetwork.go
  dev/managedservicesplatform/internal/resource/serviceaccount/serviceaccount.go
  dev/managedservicesplatform/internal/stack/cloudrun/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/adapters.go
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun_test.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/builder.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/job/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/job/job.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/service/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/service/service.go
  dev/managedservicesplatform/internal/stack/project/BUILD.bazel
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/spec/BUILD.bazel
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/spec/service.go
  dev/managedservicesplatform/spec/spec.go
  dev/sg/msp/sg_msp.go
  go.mod
  go.sum
  lib/pointers/ptr.go
Labels: cla-signed

#58127 doc/dev: improve cody-gateway setup docs
  doc/dev/how-to/cody_gateway.md
Labels: cla-signed

#58171 dev/msp: fix redis endpoint
  dev/managedservicesplatform/internal/resource/redis/redis.go
Labels: cla-signed

#58139 Web client: fix copyability of text
  client/web/src/components/diff/DiffHunk.module.scss
  client/web/src/components/diff/DiffHunk.tsx
  client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
  client/web/src/repo/blob/codemirror/eof.ts
Labels: code-navigation, cla-signed

#58165 dev/msp: add explicit outputs to stack workspaces
  dev/managedservicesplatform/internal/stack/BUILD.bazel
  dev/managedservicesplatform/internal/stack/README.md
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/builder.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/job/job.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/service/service.go
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/internal/stack/stacks.go
Labels: cla-signed

#58173 dev/msp: fix redis configuration drift
  dev/managedservicesplatform/internal/resource/redis/redis.go
Labels: cla-signed

#58174 Code Navigation: edit tooltip to reflect new RBAC permissions paradigm
  client/web/src/repo/tree/TreePageContent.tsx
Labels: cla-signed

#58163 [Cody GA Docs] Add DatGrip to list of supported JetBrains IDEs
  doc/cody/overview/install-jetbrains.md
Labels: docs, cla-signed

#58140 Fix broken link on the main docs landing page
  doc/getting-started/index.md
Labels: docs, cla-signed, docs-issue

#58172 dev/msp: 'generate -all' to generate all services and all envs
  dev/managedservicesplatform/BUILD.bazel
  dev/managedservicesplatform/cdktf.go
  dev/sg/msp/repo/repo.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#58143 squirrel: Do a lowercase check only if the case-sensitive check fails
  cmd/symbols/squirrel/BUILD.bazel
  cmd/symbols/squirrel/util.go
Labels: team/graph, cla-signed, bug-fix, backports, backport 5.2, backport/bugfix

#58176 dev/msp: add SSL_CERT_DIR when configuring Redis
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
Labels: cla-signed

#58175 [Cody GA Docs] Improve and Update Cody Gateway docs
  doc/_resources/assets/redirects
  doc/cody/core-concepts/cody-gateway.md
  doc/cody/core-concepts/cody_gateway.md
  doc/cody/core-concepts/embeddings/index.md
  doc/cody/faq.md
  doc/cody/overview/app/index.md
  doc/cody/overview/enable-cody-enterprise.md
  doc/dev/how-to/cody_gateway.md
  doc/dev/how-to/index.md
Labels: docs, cla-signed

#58178 [Cody GA Docs] Remove Cody App from main docs navigation
  doc/cody/overview/cody-with-sourcegraph.md
  doc/cody/overview/index.md
  doc/sidebar.md
Labels: docs, cla-signed, docs-issue

#58156 code-search: handle changeset fork when creating a batch change via src-cli
  lib/batches/changeset_spec.go
  lib/batches/changeset_spec_test.go
  lib/batches/schema/changeset_spec_stringdata.go
  schema/changeset_spec.schema.json
  schema/schema.go
Labels: cla-signed

#58185 Fix nil panic in cost prom metric when estimation failed
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed, team/source

#58169 search: Refactor new search input
  client/branded/BUILD.bazel
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
  client/branded/src/search-ui/input/experimental/Suggestions.tsx
  client/branded/src/search-ui/input/experimental/SyntaxHighlightedSearchQuery.tsx
  client/branded/src/search-ui/input/experimental/codemirror/example-suggestions.ts
  client/branded/src/search-ui/input/experimental/codemirror/history.ts
  client/branded/src/search-ui/input/experimental/codemirror/searchcontext.ts
  client/branded/src/search-ui/input/experimental/index.ts
  client/branded/src/search-ui/input/experimental/optionRenderer.tsx
  client/branded/src/search-ui/input/experimental/placeholder.ts
  client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
  client/branded/src/search-ui/input/experimental/utils.test.ts
  client/branded/src/search-ui/input/experimental/utils.ts
  client/shared/src/search/query/decoratedToken.ts
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/search/input/V2SearchInput.tsx
  client/web/src/search/input/suggestions.ts
  client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
Labels: cla-signed, code-search

#58187 Temporarily log costly queries
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed, SSDLC

#58148 squirrel: Re-enable code nav for .pcc/.pc files
  cmd/symbols/squirrel/BUILD.bazel
  cmd/symbols/squirrel/language-file-extensions.json
  cmd/symbols/squirrel/languages.go
Labels: team/graph, cla-signed, backports, backport 5.2, backport/bugfix

#58192 Fix another nil panic with cost estimation
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed, team/source

#57862 Fix cursor jumping when typing in GraphQL API console
  CHANGELOG.md
  client/web/src/api/ApiConsole.tsx
Labels: cla-signed, team/source

#58128 SCIP ctags: explain the 'kind' naming
  docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
Labels: cla-signed

#58180 dev/msp: extract resolved image tag to tfvars, add stable generate mode
  dev/managedservicesplatform/cdktf.go
  dev/managedservicesplatform/internal/resource/tfvar/BUILD.bazel
  dev/managedservicesplatform/internal/resource/tfvar/tfvar.go
  dev/managedservicesplatform/internal/stack/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/options/cloudflareprovider/cloudflareprovider.go
  dev/managedservicesplatform/internal/stack/options/dynamicvariables/BUILD.bazel
  dev/managedservicesplatform/internal/stack/options/dynamicvariables/dynamicvariables.go
  dev/managedservicesplatform/internal/stack/options/googleprovider/google.go
  dev/managedservicesplatform/internal/stack/options/randomprovider/randomprovider.go
  dev/managedservicesplatform/internal/stack/options/terraformversion/terraformversion.go
  dev/managedservicesplatform/internal/stack/options/tfcbackend/tfcbackend.go
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/internal/stack/stacks.go
  dev/managedservicesplatform/internal/stack/stacks_test.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#58206 Code Navigation: cleans up blob view search
  client/web/src/repo/blob/codemirror/search.tsx
  client/wildcard/src/global-styles/code.scss
Labels: cla-signed

#58214 [Cody GA Docs] Add info for enabling Code Graph with VS Code extension
  doc/cody/overview/install-vscode.md
Labels: docs, docs-ux, cla-signed

#58212 dev/msp: render explicit outputs as locals
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/internal/stack/stacks.go
Labels: cla-signed

#58216 dev/msp: migrate service accounts, IAM to 'iam' module
  dev/managedservicesplatform/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/iam/BUILD.bazel
  dev/managedservicesplatform/internal/stack/iam/iam.go
  dev/managedservicesplatform/internal/stack/iam/iam_test.go
  dev/managedservicesplatform/internal/stack/project/BUILD.bazel
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/terraformcloud/BUILD.bazel
  dev/managedservicesplatform/terraformcloud/terraformcloud.go
Labels: cla-signed

#58035 remove "Copy full query" button from search box
  client/branded/BUILD.bazel
  client/branded/src/search-ui/input/SearchBox.tsx
  client/branded/src/search-ui/input/toggles/CopyQueryButton.tsx
  client/branded/src/search-ui/input/toggles/Toggles.test.tsx
  client/branded/src/search-ui/input/toggles/Toggles.tsx
  client/branded/src/search-ui/input/toggles/index.ts
  client/jetbrains/webview/src/search/input/JetBrainsToggles.tsx
  client/shared/src/keyboardShortcuts/keyboardShortcuts.ts
  client/shared/src/util/url.ts
  client/web/src/components/KeyboardShortcutsHelp/__snapshots__/KeyboardShortcutsHelp.test.tsx.snap
  client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
Labels: cla-signed, code-search

#58227 gomod: update zoekt with symbol perf fix
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#58221 bzl: Remove library target from Rust crate
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/io.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/main.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/progress.rs
Labels: cla-signed

#58211 Fix input focus ring styles in MultiCombobox UI
  client/wildcard/src/components/Combobox/MultiCombobox.module.scss
Labels: cla-signed

#58230 Return better error for GQL cost violations
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed, SSDLC, backport 5.2

#58236 [Backport 5.2 (manual)] Return better error for GQL cost violations
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed

#58209 [Repository page]: Show initial repository query value in initial picker state
  client/web/src/repo/RepoLinkPicker.tsx
  client/web/src/repo/utils.tsx
Labels: cla-signed

#58217 [Notebooks]: Remove notepad UI from notebooks feature
  CHANGELOG.md
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
  client/web/src/notebooks/listPage/NotebooksListPageHeader.tsx
  client/web/src/notebooks/listPage/NotepadCta.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.module.scss
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/search/Notepad.module.scss
  client/web/src/search/Notepad.story.tsx
  client/web/src/search/Notepad.test.tsx
  client/web/src/search/Notepad.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/stores/index.ts
  client/web/src/stores/notepad.test.ts
  client/web/src/stores/notepad.ts
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
  doc/notebooks/index.md
  doc/notebooks/notepad.md
Labels: cla-signed

#58218 Code Navigation: fix borked regex filter
  client/web/src/repo/blob/codemirror/search.tsx
Labels: cla-signed

#58239 dev/msp: fix custom role ID, update resourceid with warnings
  dev/managedservicesplatform/internal/resource/cloudflare/cloudflare.go
  dev/managedservicesplatform/internal/resource/cloudflareorigincert/cloudflareorigincert.go
  dev/managedservicesplatform/internal/resource/gsmsecret/gsmsecret.go
  dev/managedservicesplatform/internal/resource/loadbalancer/loadbalancer.go
  dev/managedservicesplatform/internal/resource/managedcert/managedcert.go
  dev/managedservicesplatform/internal/resource/random/random.go
  dev/managedservicesplatform/internal/resource/redis/redis.go
  dev/managedservicesplatform/internal/resource/serviceaccount/serviceaccount.go
  dev/managedservicesplatform/internal/resource/tfvar/tfvar.go
  dev/managedservicesplatform/internal/resourceid/resourceid.go
  dev/managedservicesplatform/internal/stack/iam/iam.go
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/internal/stack/stacks.go
Labels: cla-signed

#58241 Code Navigation: remove white corners from tooltips in dark mode
  client/web/src/repo/blob/codemirror/codeintel/extension.ts
Labels: cla-signed

#58033 tweak wording and remove obtrusive CTA from cody chat messages
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/components/ChatUI/ChatUi.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
  client/web/src/cody/widgets/CodyRecipesWidget.tsx
  client/web/src/get-cody/GetCodyPage.tsx
  client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx
  client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
  client/web/src/util/constants.ts
Labels: cla-signed

#58243 internal/tracer: silence opentelemetry debug logs
  go.mod
  internal/tracer/BUILD.bazel
  internal/tracer/tracer.go
  internal/tracer/watch_test.go
Labels: cla-signed

#58245 Revert "[Cody GA Docs] Remove Cody App from main docs navigation"
  doc/cody/overview/cody-with-sourcegraph.md
  doc/cody/overview/index.md
  doc/sidebar.md
Labels: docs, cla-signed, docs-issue

#58247 dev/msp: fixup resource IDs
  dev/managedservicesplatform/internal/resourceid/resourceid.go
  dev/managedservicesplatform/internal/stack/iam/iam.go
Labels: cla-signed

#58164 [Search UI]: Add new experimental search UI navigation
  client/branded/src/search-ui/input/SearchBox.story.tsx
  client/branded/src/search-ui/input/SearchBox.tsx
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.module.scss
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
  client/branded/src/search-ui/input/toggles/Toggles.test.tsx
  client/branded/src/search-ui/input/toggles/Toggles.tsx
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/components/externalServices/ExternalServiceEditPage.story.tsx
  client/web/src/components/externalServices/ExternalServicePage.story.tsx
  client/web/src/devsettings/DeveloperSettingsGlobalNavItem.tsx
  client/web/src/nav/GlobalNavbar.module.scss
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/NavBar/NavBar.tsx
  client/web/src/nav/NavBar/NavItem.module.scss
  client/web/src/nav/UserNavItem.story.tsx
  client/web/src/nav/UserNavItem.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.story.tsx
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  client/web/src/search/input/LazyV2SearchInput.module.scss
  client/web/src/search/input/LazyV2SearchInput.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/search/input/V2SearchInput.tsx
  client/web/src/site-admin/AccessRequestsPage/AccessRequestsGlobalNavItem.tsx
  client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed, code-search, search-results

#58251 dev/msp: do not mutate package variable
  dev/managedservicesplatform/internal/stack/iam/iam.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#58225 refer to `sg help` instead of auto-generating markdown docs for `sg`
  dev/BUILD.bazel
  dev/sg/BUILD.bazel
  dev/sg/main.go
  doc/BUILD.bazel
  doc/dev/background-information/ci/index.md
  doc/dev/background-information/insights/backend.md
  doc/dev/background-information/sg/BUILD.bazel
  doc/dev/background-information/sg/index.md
  doc/dev/index.md
  doc/dev/setup/quickstart.md
Labels: cla-signed

#58204 file/cody: Refactor cody widget extension
  client/web/src/repo/blob/codemirror/tooltips/CodyTooltip.tsx
Labels: cla-signed, code-search

#58254 remove "!" from global navbar site admin status messages
  client/web/src/nav/StatusMessagesNavItem.tsx
Labels: cla-signed

#58257 build: Separate out integration test and re-add library target for scip-treesitter-cli
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/main.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/integration_test.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/snapshots/integration_test__globals.java.snap
Labels: cla-signed

#58256 fix sg in CI
  dev/sg/dependencies/mac.go
  dev/sg/dependencies/shared.go
  dev/sg/dependencies/ubuntu.go
Labels: cla-signed

#58120 remove search-ranking feature flag
  CHANGELOG.md
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  dev/gqltest/search_test.go
Labels: cla-signed

#58261 bzl: do not show full commmand line for ctags in dev
  dev/universal-ctags-dev
Labels: cla-signed

#58219 Update get-cody copy for the optional app
  client/web/src/get-cody/GetCodyPage.tsx
Labels: cla-signed

#58246 dev/msp: add cute pending spinners for slower commands
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#58264 Zoekt: bump version for index memory fix
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#58203 Session state improvements
  cmd/frontend/internal/auth/oauth/provider.go
  cmd/frontend/internal/auth/openidconnect/BUILD.bazel
  cmd/frontend/internal/auth/openidconnect/middleware.go
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, SSDLC, backport 5.2

#58242 Add Protocol Check for `getReturnTo` method
  client/web/src/auth/SignInSignUpCommon.tsx
Labels: cla-signed, SSDLC, backport 5.2

#58250 Chore: remove empty BUILD.bazel files
  cmd/executor/shared/BUILD.bazel
  cmd/frontend/internal/registry/scripts/BUILD.bazel
  cmd/frontend/internal/registry/stores/BUILD.bazel
  cmd/frontend/internal/registry/stores/dbmocks/BUILD.bazel
  dev/backcompat/BUILD.bazel
  internal/codeintel/shared/gitserver/BUILD.bazel
  internal/github_apps/BUILD.bazel
  internal/repos/webhookworker/BUILD.bazel
  internal/search/codeownership/BUILD.bazel
  internal/search/exhaustive/BUILD.bazel
Labels: cla-signed

#58249 Fix panic for empty blobs
  cmd/frontend/graphqlbackend/git_tree_entry.go
Labels: cla-signed

#58273 Code Navigation: add background inline code and code blocks
  client/web/src/repo/blob/RenderedFile.module.scss
Labels: cla-signed

#58277 doc: update aws private code host docs
  doc/cloud/private_connectivity_aws.md
Labels: cla-signed

#58252 consolidate enterprise/ contributions code in web app
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/enterprise/EnterpriseWebApp.tsx
  client/web/src/enterprise/app/routes.tsx
  client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.tsx
  client/web/src/enterprise/namespaces/navitems.ts
  client/web/src/enterprise/namespaces/routes.ts
  client/web/src/enterprise/organizations/navitems.ts
  client/web/src/enterprise/organizations/routes.tsx
  client/web/src/enterprise/organizations/settings/routes.tsx
  client/web/src/enterprise/organizations/settings/sidebaritems.ts
  client/web/src/enterprise/repo/repoHeaderActionButtons.tsx
  client/web/src/enterprise/repo/settings/routes.tsx
  client/web/src/enterprise/routes.tsx
  client/web/src/enterprise/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/enterprise/site-admin/overview/overviewComponents.ts
  client/web/src/enterprise/site-admin/routes.tsx
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/enterprise/user/navitems.ts
  client/web/src/enterprise/user/routes.tsx
  client/web/src/enterprise/user/settings/routes.tsx
  client/web/src/enterprise/user/settings/sidebaritems.ts
  client/web/src/namespaces/navitems.ts
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  client/web/src/notebooks/GlobalNotebooksArea.tsx
  client/web/src/notebooks/createPage/CreateNotebookPage.tsx
  client/web/src/notebooks/listPage/NotebookNode.tsx
  client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/notebooks/listPage/NotebooksListPageHeader.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/org/area/routes.tsx
  client/web/src/org/settings/routes.tsx
  client/web/src/org/settings/sidebaritems.ts
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/RepoHeader.story.tsx
  client/web/src/repo/RepoHeader.tsx
  client/web/src/repo/repoHeaderActionButtons.tsx
  client/web/src/repo/settings/routes.tsx
  client/web/src/routes.constants.ts
  client/web/src/routes.tsx
  client/web/src/site-admin/routes.tsx
  client/web/src/site-admin/sidebaritems.ts
  client/web/src/staticAppConfig.ts
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
  client/web/src/user/area/routes.tsx
  client/web/src/user/settings/routes.tsx
  client/web/src/user/settings/sidebaritems.ts
  client/web/src/util/contributions.ts
Labels: cla-signed

#58058 Fixup GitTree behavior after adding test suite
  cmd/frontend/graphqlbackend/git_tree.go
  cmd/frontend/graphqlbackend/git_tree_test.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed, team/source

#58275 msp: provision and load EXTERNAL_DNS_NAME envvar
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  lib/managedservicesplatform/service/config.go
Labels: cla-signed

#58284 Update troubleshooting.md
  doc/batch_changes/references/troubleshooting.md
Labels: cla-signed

#58285 Update deploy_executors_kubernetes.md
  doc/admin/executors/deploy_executors_kubernetes.md
Labels: cla-signed

#58286 release: instruct release_issue_template to update RC instance
  dev/release/templates/release_issue_template.md
Labels: cla-signed

#58290 Update broken links
  doc/integration/vscode/index.md
Labels: cla-signed

#58291 Don't do expensive ping queries for dotcom; these are causing timeouts
  internal/updatecheck/client.go
Labels: cla-signed

#58262 embeddings: fix default size limit
  CHANGELOG.md
  internal/conf/computed.go
  internal/conf/computed_test.go
Labels: cla-signed

#58090 Auto-update Wolfi base images to latest
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, backport 5.2, wolfi-auto-update

#57894 SCIP Tree-sitter CLI evaluation logic + workspace indexing mode
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/README.md
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/evaluate.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/index.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/io.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/main.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/progress.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/integration_test.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/snapshots/integration_test__globals.java.snap
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/parsers.rs
  docker-images/syntax-highlighter/crates/scip-treesitter/src/types.rs
Labels: cla-signed
