Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-07, with the labels that each got.

#54471 remove "Optimize Code" recipe due to poor quality
  client/cody-shared/BUILD.bazel
  client/cody-shared/src/chat/recipes/optimize-code.ts
  client/cody-shared/src/chat/recipes/recipe.ts
  client/cody/CHANGELOG.md
  client/cody/package.json
  client/cody/src/chat/recipes.ts
  client/cody/src/main.ts
  client/cody/webviews/Recipes.tsx
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/OptimizeCodeAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/OptimizeCodePromptProvider.java
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#54480 JetBrains: display more informative message when no context found
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Labels: cla-signed

#54521 bzl: update deps.bzl (go.mod update was not reflected)
  WORKSPACE
  deps.bzl
Labels: cla-signed, backport 5.1

#54442 own: add an example of a query to find commits in given release for given owner.
  doc/own/index.md
Labels: cla-signed, own

#54483 own: rename "Sourcegraph Own" to "Code ownership"
  client/web/src/enterprise/own/OwnPage.tsx
  client/web/src/enterprise/own/RepositoryOwnEditPage.tsx
  client/web/src/enterprise/own/RepositoryOwnPage.tsx
  client/web/src/enterprise/sentinel/SentinelLandingPage.tsx
  client/web/src/repo/blob/own/OwnerList.tsx
  client/web/src/search/results/StreamingSearchResults.story.tsx
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  doc/admin/pings.md
  doc/admin/teams/index.md
  doc/code_search/reference/queries.md
  doc/own/codeowners_ingestion.md
  doc/own/index.md
  enterprise/cmd/worker/internal/own/job.go
  enterprise/internal/own/background/background.go
  internal/search/alert.go
Labels: cla-signed, own

#54524 cody web: fix 404 errors when loading /cody
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed, team/iam

#53013 executors/multi-queue: implement queue selection fairness
  deps.bzl
  doc/admin/observability/dashboards.md
  enterprise/cmd/frontend/internal/executorqueue/handler/BUILD.bazel
  enterprise/cmd/frontend/internal/executorqueue/handler/multihandler.go
  enterprise/cmd/frontend/internal/executorqueue/handler/multihandler_test.go
  enterprise/cmd/worker/internal/executors/BUILD.bazel
  enterprise/cmd/worker/internal/executors/janitor_config.go
  enterprise/cmd/worker/internal/executors/janitor_job.go
  enterprise/cmd/worker/internal/executors/multiqueue_cache_cleaner.go
  enterprise/cmd/worker/internal/executors/multiqueue_cache_cleaner_test.go
  enterprise/internal/executor/types/BUILD.bazel
  enterprise/internal/executor/types/cache.go
  go.mod
  go.sum
  monitoring/definitions/executor.go
  monitoring/definitions/shared/executors.go
  monitoring/definitions/shared/queues.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, backport 5.1

#54535 update release config
  dev/release/release-config.jsonc
Labels: cla-signed

#54533 Update prometheus tools
  dev/oci_deps.bzl
  wolfi-images/batcheshelper.yaml
  wolfi-images/bundled-executor.yaml
  wolfi-images/node-exporter.yaml
  wolfi-images/postgres-exporter.yaml
  wolfi-images/server.yaml
Labels: cla-signed, backport 5.1

#54352 Own configuration reference
  doc/own/configuration_reference.md
  doc/own/index.md
  doc/sidebar.md
Labels: cla-signed

#54529 [Backport 5.1] bzl: update deps.bzl (go.mod update was not reflected) (#54521)
  deps.bzl
Labels: cla-signed, backports, backported-to-5.1

#54537 update changelog with 5.1.2 fixes
  CHANGELOG.md
Labels: cla-signed

#54517 bzl: bazlify lsif/protocol stringer uses
  dev/BUILD.bazel
  dev/go_stringer.bzl
  lib/codeintel/lsif/protocol/BUILD.bazel
  lib/codeintel/lsif/protocol/symbol.go
  lib/codeintel/lsif/protocol/symbolkind_string.go
  lib/codeintel/lsif/protocol/symboltag_string.go
Labels: cla-signed, dev-infra/go-generate

#54536 own: remove forgotten "Own" references in favor of "Code ownership".
  client/web/src/enterprise/own/OwnPage.tsx
  client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
  client/web/src/enterprise/own/admin-ui/OwnStatusPage.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/site-admin/sidebaritems.ts
  doc/own/codeowners_format.md
  doc/sidebar.md
Labels: cla-signed, own

#54544 packages: skip duplicates when extracting
  cmd/gitserver/server/vcs_syncer_go_modules.go
  cmd/gitserver/server/vcs_syncer_jvm_packages.go
  cmd/gitserver/server/vcs_syncer_npm_packages.go
  cmd/gitserver/server/vcs_syncer_python_packages.go
Labels: team/code-intelligence, cla-signed, package-repos

#54545 codeintel: bump indexer shas
  enterprise/internal/codeintel/autoindexing/internal/inference/libs/indexes.go
Labels: team/code-intelligence, auto-index, cla-signed

#54546 Chore: remove redundant err check
  enterprise/cmd/embeddings/shared/main.go
Labels: cla-signed

#54550 Fix broken link in wolfi docs
  doc/dev/how-to/wolfi/add_update_images.md
Labels: cla-signed

#54548 Add default values for mode context sizes
  internal/conf/computed.go
  internal/conf/computed_test.go
Labels: cla-signed, backport 5.1

#54242 batches: allow non-admins to view rollout window configuration
  client/web/src/enterprise/batches/backend.ts
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/site_config_change_test.go
  cmd/frontend/graphqlbackend/site_test.go
  internal/conf/validate.go
  internal/conf/validate_test.go
  internal/database/conf.go
Labels: cla-signed, backport 5.1

#54449 cody-gateway: treat no-source as 401, fix source for unauthorized
  enterprise/cmd/cody-gateway/internal/actor/actor.go
  enterprise/cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  enterprise/cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  enterprise/cmd/cody-gateway/internal/actor/source.go
  enterprise/cmd/cody-gateway/internal/auth/auth.go
Labels: cla-signed

#54453 cody-gateway: have workers release lock on extend failure, increase expiry
  enterprise/cmd/cody-gateway/internal/actor/source.go
  enterprise/cmd/cody-gateway/internal/actor/source_test.go
  enterprise/cmd/cody-gateway/shared/main.go
Labels: cla-signed

#54556 pluralize variable names when representing slices/arrays
  enterprise/cmd/frontend/internal/insights/httpapi/export.go
  enterprise/cmd/frontend/internal/insights/resolvers/dashboard_resolvers.go
  enterprise/cmd/frontend/internal/insights/resolvers/insight_view_resolvers.go
  enterprise/cmd/frontend/internal/insights/resolvers/validator.go
  enterprise/internal/insights/store/dashboard_store.go
  enterprise/internal/insights/store/dashboard_store_test.go
  enterprise/internal/insights/store/insight_store.go
  enterprise/internal/insights/store/insight_store_test.go
Labels: cla-signed

#54551 App - remove ability to add remote repos
  CHANGELOG.app.md
  client/web/BUILD.bazel
  client/web/src/enterprise/app/settings/AppSettingsArea.tsx
  client/web/src/enterprise/app/setup/AppSetupWizard.tsx
  client/web/src/setup-wizard/SetupWizard.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/RemoteRepositoriesStep.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-picker/AppRemoteNotice.module.scss
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-picker/AppRemoteNotice.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-picker/index.ts
  client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
Labels: cla-signed

#54561 sg: remove extra semaphore release
  dev/sg/internal/run/run.go
Labels: cla-signed

#54559 App/Insights: provide fallback for Intl.ListFormat
  client/web/src/enterprise/insights/components/creation-ui/code-insight-time-step-picker/get-interval-descrtiption-text/get-interval-description-text.tsx
Labels: cla-signed

#54519 Refactor unified context fetcher
  client/cody-shared/src/codebase-context/index.ts
  client/cody-shared/src/sourcegraph-api/graphql/queries.ts
  client/cody-shared/src/unified-context/client.ts
  client/cody-shared/src/unified-context/index.ts
Labels: cla-signed, team/iam, cody

#54566 release: sourcegraph@5.1.2
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/migrator/BUILD.bazel
  cmd/migrator/generate.sh
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
Labels: cla-signed

#54522 Cody: Use typewriter effect for chat responses
  client/cody-shared/BUILD.bazel
  client/cody-shared/src/chat/chat.ts
  client/cody-shared/src/chat/typewriter.ts
Labels: cla-signed, team/code-exploration

#54572 Cody: Update changelog
  client/cody/CHANGELOG.md
Labels: cla-signed, team/code-exploration

#54477 dev/gqltest: Unskip bitbucket project perms tests
  dev/gqltest/bitbucket_projects_perms_sync_test.go
Labels: cla-signed

#54355 app: move latest + update cody app routes to own package
  cmd/frontend/codyapp/BUILD.bazel
  cmd/frontend/codyapp/latest_version_handler.go
  cmd/frontend/codyapp/latest_version_handler_test.go
  cmd/frontend/codyapp/manifest.go
  cmd/frontend/codyapp/resolvers.go
  cmd/frontend/codyapp/update_check_handler.go
  cmd/frontend/codyapp/update_check_handler_test.go
  cmd/frontend/internal/app/router/BUILD.bazel
  cmd/frontend/internal/app/router/router.go
  cmd/frontend/internal/app/updatecheck/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
Labels: cla-signed

#54562 release: update SRC endpoint for release Batch Change
  dev/release/src/batchChanges.ts
Labels: cla-signed

#54574 update release config
  dev/release/release-config.jsonc
Labels: cla-signed

#54575 JetBrains: Embeddings status in footer
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/Icons.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatus.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusNotAvailableYet.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/NoGitRepositoryEmbeddingStatus.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/RepoAvailableEmbeddingStatus.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/RepositoryIndexedEmbeddingStatus.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/RepositoryMissingEmbeddingStatus.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/embeddings/EmbeddingsSearcher.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/embeddings/EmbeddingsStatusLoader.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/editor/EditorUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
  client/jetbrains/src/main/resources/icons/repositoryIndexed.svg
  client/jetbrains/src/main/resources/icons/repositoryMissing.svg
  client/jetbrains/src/test/java/com/sourcegraph/cody/context/RepositoryIndexedEmbeddingStatusTest.java
Labels: cla-signed

#54571 own: add an error in a weird case of a team not found by ID.
  enterprise/internal/own/ownref.go
Labels: cla-signed, own

#54578 Fix cancel button on token create form page
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
Labels: cla-signed

#54579 JetBrains: Refactor `unstable-codegen` completions
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/SSEClient.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CompletionsProviderType.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/UnstableCodegenLanguageUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CodyCompletionItemProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CompletionProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/SourcegraphNodeCompletionsClient.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/UnstableCodegenEndOfLineCompletionProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/WebviewErrorMessenger.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppManager.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppPaths.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/IntelliJTextDocument.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/TextDocument.java
  client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
  client/jetbrains/src/test/java/LocalAppManagerTest.java
  client/jetbrains/src/test/java/com/sourcegraph/cody/completions/UnstableCodegenLanguageUtilTest.java
  client/jetbrains/src/test/java/com/sourcegraph/cody/vscode/TestTextDocument.java
Labels: cla-signed

#54580 cody admin: update estimated time to finish
  client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.tsx
Labels: cla-signed

#54587 bzl: re-enable code-intel-qa (only on main)
  enterprise/dev/ci/internal/ci/bazel_operations.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
  testing/BUILD.bazel
Labels: cla-signed

#54564 Tracing: remove LazyPrintf
  cmd/repo-updater/repoupdater/server.go
  cmd/searcher/internal/search/search.go
  internal/search/client/BUILD.bazel
  internal/search/client/client.go
  internal/search/job/jobutil/limit.go
  internal/search/repos/repos.go
  internal/search/searchcontexts/BUILD.bazel
  internal/search/searchcontexts/search_contexts.go
  internal/search/searcher/client.go
  internal/search/zoekt/indexed_search.go
  internal/trace/trace.go
Labels: cla-signed

#54586 app: remove old release scripts and config
  enterprise/dev/app/goreleaser.yaml
  enterprise/dev/app/release.sh
Labels: cla-signed

#54565 silence errors when redis is reporting key does not exist
  enterprise/cmd/worker/internal/executors/BUILD.bazel
  enterprise/cmd/worker/internal/executors/multiqueue_cache_cleaner.go
Labels: cla-signed

#54588 update relicense changelog entry with more info
  CHANGELOG.md
Labels: cla-signed

#54576 ci: introduce a bazel-do runtype to run user given bazel commands only
  dev/ci/runtype/runtype.go
  doc/dev/background-information/bazel/cookbook.md
  doc/dev/background-information/bazel/index.md
  doc/dev/background-information/ci/reference.md
  doc/dev/background-information/sg/reference.md
  enterprise/dev/ci/gen-pipeline.go
  enterprise/dev/ci/internal/ci/BUILD.bazel
  enterprise/dev/ci/internal/ci/bazel_operations.go
  enterprise/dev/ci/internal/ci/bazel_operations_test.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#54595 Update note on pricing page.
  doc/admin/subscriptions/index.md
Labels: cla-signed, team/iam

#54581 gateway: Add endpoints to read limits
  enterprise/cmd/cody-gateway/internal/actor/limits.go
  enterprise/cmd/cody-gateway/internal/httpapi/BUILD.bazel
  enterprise/cmd/cody-gateway/internal/httpapi/completions/upstream.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  enterprise/cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
  enterprise/cmd/cody-gateway/internal/httpapi/handler.go
  enterprise/cmd/cody-gateway/internal/limiter/limiter.go
  internal/codygateway/types.go
Labels: cla-signed

#54591 Remove some outdated cody config disclaimers
  doc/cody/explanations/code_graph_context.md
  doc/cody/explanations/cody_gateway.md
  doc/cody/explanations/enabling_cody_enterprise.md
Labels: cla-signed

#54584 gateway: Pretty print limit numbers
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyGatewayRateLimitModal.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/utils.ts
Labels: cla-signed

#54582 gateway: Add confirmation modal for toggling access
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
Labels: cla-signed

#54466 app: resolve port :9000 conflicts (change to :49000)
  cmd/blobstore/shared/BUILD.bazel
  cmd/blobstore/shared/shared.go
  cmd/server/shared/BUILD.bazel
  cmd/server/shared/blobstore.go
  enterprise/internal/codeintel/shared/lsifuploadstore/BUILD.bazel
  enterprise/internal/codeintel/shared/lsifuploadstore/config.go
  enterprise/internal/embeddings/BUILD.bazel
  enterprise/internal/embeddings/uploadstore.go
  internal/conf/deploy/BUILD.bazel
  internal/conf/deploy/endpoints.go
  internal/singleprogram/singleprogram.go
Labels: cla-signed

#54560 redirect batchers notifications to the Code Search team
  .github/workflows/batches-notify.yml
Labels: cla-signed

#54601 deploy: correct blobstore endpoint in sourcegraph/server image (fix 'main' CI)
  internal/conf/deploy/endpoints.go
Labels: cla-signed

#54570 own: make Own resolver nil-safe by adding relevant checks.
  enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
Labels: cla-signed, own

#54583 JetBrains: show editor context recipe actions when cody app is available
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/BaseRecipeAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/DownloadCodyAppAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeDetailedAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeHighLevelAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/FindCodeSmellsAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateDocStringAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateUnitTestAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ImproveVariableNamesAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/RunCodyAppAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SimpleRecipeAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguageAction.java
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#54607 ci: drop metadata step
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#54488 Cody: Add support for server-side token limits to Chat
  client/cody-cli/src/completions.ts
  client/cody-shared/src/chat/chat.ts
  client/cody-shared/src/prompt/constants.ts
  client/cody-shared/src/sourcegraph-api/graphql/client.ts
  client/cody-shared/src/sourcegraph-api/graphql/queries.ts
  client/cody-slack/src/services/stream-completions.ts
  client/cody/CHANGELOG.md
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/src/chat/protocol.ts
  client/cody/src/chat/utils.ts
  client/cody/src/services/AuthProvider.ts
Labels: cla-signed, cody

#54609 docs/executors: specify feature flag for native k8s deployment
  doc/admin/executors/deploy_executors_kubernetes.md
Labels: cla-signed

#54593 sg: add ci bazel helper command to run bazel commands in CI
  dev/sg/BUILD.bazel
  dev/sg/internal/bk/bk.go
  dev/sg/sg_ci.go
  doc/dev/background-information/sg/reference.md
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#54611 App: fix blobstore port for sg start app
  sg.config.yaml
Labels: cla-signed

#54610 JetBrains: show currently opened file name in footer
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/CurrentlyOpenFileListener.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
  client/jetbrains/src/main/java/com/sourcegraph/common/ProjectFileUtils.java
Labels: cla-signed

#54617 highlight: Move client into internal package
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/file.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/highlight.go
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/repository_comparison_test.go
  cmd/frontend/graphqlbackend/virtual_file.go
  cmd/frontend/graphqlbackend/virtual_file_test.go
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/config.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/search/BUILD.bazel
  cmd/frontend/internal/search/decorate.go
  internal/gosyntect/BUILD.bazel
  internal/gosyntect/gosyntect.go
  internal/highlight/BUILD.bazel
  internal/highlight/chroma.go
  internal/highlight/highlight.go
  internal/highlight/highlight_test.go
  internal/highlight/html.go
  internal/highlight/html_test.go
  internal/highlight/language.go
  internal/highlight/language_test.go
  internal/highlight/mocks.go
  internal/highlight/syntect_language_map.go
  internal/highlight/testdata/telemetry-raw.txt
  internal/highlight/testdata/telemetry.scip
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.1

#54554 Embeddings: remove extra retries
  enterprise/cmd/embeddings/qa/embed_queries/main.go
  enterprise/cmd/embeddings/shared/main.go
  enterprise/internal/embeddings/embed/client/client.go
  enterprise/internal/embeddings/embed/client/openai/client.go
  enterprise/internal/embeddings/embed/client/openai/client_test.go
  enterprise/internal/embeddings/embed/client/sourcegraph/client.go
  enterprise/internal/embeddings/embed/embed.go
  enterprise/internal/embeddings/embed/embed_test.go
Labels: cla-signed

#54602 Improve open source messaging and add Cody
  doc/getting-started/index.md
Labels: docs, cla-signed

#54119 Update `extensionDetails` in EventLogger.ts
  client/jetbrains/webview/src/telemetry/EventLogger.ts
Labels: cla-signed

#54557 App: use unwrap_or_else() with shell::open()
  src-tauri/src/common.rs
  src-tauri/src/tray.rs
Labels: cla-signed

#54620 backcompat: fixes to better handle file movement
  dev/backcompat/defs.bzl
  dev/backcompat/flakes.bzl
Labels: cla-signed

#54627 App - make App check for new repos faster
  internal/conf/confdefaults/confdefaults.go
  internal/repos/BUILD.bazel
  internal/repos/conf.go
Labels: cla-signed

#54628 codenav: Add service method to search by symbol name
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_definitions_test.go
  internal/codeintel/codenav/service_diagnostics_test.go
  internal/codeintel/codenav/service_hover_test.go
  internal/codeintel/codenav/service_implementations_test.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/service_ranges_test.go
  internal/codeintel/codenav/service_references_test.go
  internal/codeintel/codenav/service_stencil_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/observability.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
  internal/codeintel/codenav/transport/graphql/root_resolver_diagnostics.go
  internal/codeintel/codenav/transport/graphql/root_resolver_hover.go
  internal/codeintel/codenav/transport/graphql/root_resolver_implementations.go
  internal/codeintel/codenav/transport/graphql/root_resolver_ranges.go
  internal/codeintel/codenav/transport/graphql/root_resolver_references.go
  internal/codeintel/codenav/transport/graphql/root_resolver_stencil.go
  internal/codeintel/codenav/types.go
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.1

#54633 codeintel: Add symbols method to syntect client
  internal/gosyntect/gosyntect.go
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.1

#54603 sveltekit-prototype: Upgrade to Svelte 4.0
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/lib/search/SearchBox.svelte
  client/web-sveltekit/src/routes/Header.svelte
  pnpm-lock.yaml
Labels: cla-signed

#54630 Backport 54617 to 5.1
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/file.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/highlight.go
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/repository_comparison_test.go
  cmd/frontend/graphqlbackend/virtual_file.go
  cmd/frontend/graphqlbackend/virtual_file_test.go
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/config.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/search/BUILD.bazel
  cmd/frontend/internal/search/decorate.go
  internal/gosyntect/BUILD.bazel
  internal/gosyntect/gosyntect.go
  internal/highlight/BUILD.bazel
  internal/highlight/chroma.go
  internal/highlight/highlight.go
  internal/highlight/highlight_test.go
  internal/highlight/html.go
  internal/highlight/html_test.go
  internal/highlight/language.go
  internal/highlight/language_test.go
  internal/highlight/mocks.go
  internal/highlight/syntect_language_map.go
  internal/highlight/testdata/telemetry-raw.txt
  internal/highlight/testdata/telemetry.scip
Labels: cla-signed

#54598 cody-gateway/events: do not let bufferedLogger.Stop time out
  enterprise/cmd/cody-gateway/internal/events/buffered.go
Labels: cla-signed

#54640 soap: fix missing display name
  enterprise/cmd/frontend/internal/auth/sourcegraphoperator/provider.go
Labels: cla-signed, backport 5.1

#54612 sveltekit-prototype: Remove (global) platformContext and fix React integration
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/ReactComponent.svelte
  client/web-sveltekit/src/lib/context.ts
  client/web-sveltekit/src/lib/loader/repo.ts
  client/web-sveltekit/src/lib/loader/settings.ts
  client/web-sveltekit/src/lib/react-interop.tsx
  client/web-sveltekit/src/lib/repo/api/contributors.ts
  client/web-sveltekit/src/lib/search/api/highlighting.ts
  client/web-sveltekit/src/lib/search/results.ts
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/lib/stores.ts
  client/web-sveltekit/src/lib/user/api/settings.ts
  client/web-sveltekit/src/routes/(enterprise)/insights/[...path]/+page.svelte
  client/web-sveltekit/src/routes/(enterprise)/notebooks/[...path]/+page.svelte
  client/web-sveltekit/src/routes/(enterprise)/notebooks/[...path]/+page.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/+layout.ts
  client/web-sveltekit/src/routes/[...repo]/-/stats/contributors/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/-/stats/contributors/+page.ts
  client/web-sveltekit/src/routes/search/CodeExcerpt.svelte
  client/web-sveltekit/src/routes/search/FileMatchChildren.svelte
  client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
  pnpm-lock.yaml
Labels: cla-signed

#54645 accesstokens: only allow SOAP users to delete SOAP user access tokens
  cmd/frontend/graphqlbackend/access_tokens.go
  cmd/frontend/graphqlbackend/access_tokens_test.go
Labels: cla-signed, backport 5.1

#54654 Cody Typewriter: Use a dynamic character chunk size
  client/cody-shared/src/chat/typewriter.ts
Labels: cla-signed, team/code-exploration

#54655 Cody: Update CHANGELOG.md
  client/cody/CHANGELOG.md
Labels: cla-signed, team/code-exploration

#54666 Add docs about support for rsa-sha signatures
  CHANGELOG.md
  doc/admin/repo/auth.md
Labels: cla-signed

#53594 JetBrains: Auto-grow textarea
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/ui/AutoGrowingTextArea.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/ui/RoundedJBTextArea.java
Labels: cla-signed

#54600 Allow filtering embedding files by include regex and max file size
  doc/cody/explanations/code_graph_context.md
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/cmd/worker/internal/embeddings/repo/handler_test.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/conf/conftypes/consts.go
  internal/embeddings/embed/BUILD.bazel
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
  internal/embeddings/embed/files.go
  internal/embeddings/embed/files_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#54683 Web: Fix flaky storybook build due to React errors
  client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
Labels: cla-signed, team/code-exploration

#54657 sveltekit-prototyp: Properly use kit's "streaming promises" feature
  client/web-sveltekit/src/lib/utils.ts
  client/web-sveltekit/src/routes/[...repo]/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo]/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo]/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/(code)/+page.ts
  client/web-sveltekit/src/routes/[...repo]/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/(code)/-/blob/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo]/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/(code)/-/tree/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo]/-/branches/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/-/branches/+page.ts
  client/web-sveltekit/src/routes/[...repo]/-/branches/all/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/-/branches/all/+page.ts
  client/web-sveltekit/src/routes/[...repo]/-/commit/[...revspec]/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/-/commit/[...revspec]/+page.ts
  client/web-sveltekit/src/routes/[...repo]/-/commits/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/-/commits/+page.ts
  client/web-sveltekit/src/routes/[...repo]/-/tags/+page.svelte
  client/web-sveltekit/src/routes/[...repo]/-/tags/+page.ts
Labels: cla-signed

#54688 sg: silence most bazel output for docsite
  sg.config.yaml
Labels: dx-announce, cla-signed

#54648 cody-gateway: use subscription account name for usage notification
  enterprise/cmd/cody-gateway/internal/actor/actor.go
  enterprise/cmd/cody-gateway/internal/actor/anonymous/anonymous.go
  enterprise/cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  enterprise/cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  enterprise/cmd/cody-gateway/internal/actor/productsubscription/productsubscription_test.go
  enterprise/cmd/cody-gateway/internal/auth/auth_test.go
  enterprise/cmd/cody-gateway/internal/auth/mocks_test.go
  enterprise/cmd/cody-gateway/internal/dotcom/BUILD.bazel
  enterprise/cmd/cody-gateway/internal/dotcom/mocks.go
  enterprise/cmd/cody-gateway/internal/dotcom/operations.go
  enterprise/cmd/cody-gateway/internal/dotcom/operations.graphql
  enterprise/cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
  enterprise/cmd/cody-gateway/internal/notify/rate_limit.go
  enterprise/cmd/cody-gateway/internal/notify/rate_limit_test.go
  internal/codygateway/BUILD.bazel
  internal/codygateway/ifaces.go
  internal/codygateway/types.go
  mockgen.test.yaml
Labels: cla-signed

#54674 sveltekit-prototype: Add separator component and setup storybook
  client/web-sveltekit/.eslintrc.cjs
  client/web-sveltekit/.storybook/main.js
  client/web-sveltekit/.storybook/preview.js
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/Separator.svelte
  client/web-sveltekit/src/lib/stores.ts
  client/web-sveltekit/src/routes/[...repo]/(code)/+layout.svelte
  client/web-sveltekit/src/stories/Separator.stories.ts
  client/web-sveltekit/src/stories/SeparatorExample.svelte
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#54690 sg: add --legacy to run command
  dev/sg/sg_run.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#54615 Don't overwrite external service config changes when sync is running
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/repos/syncer.go
Labels: cla-signed, backport 5.1

#54703 chore: remove IAM/RM related GH actions in favour of Source.
  .github/workflows/label-move.yml
  .github/workflows/label-notify.yml
  .github/workflows/move-labled-issues-to-project.yml
Labels: cla-signed, team/source

#54675 Cody Inline Chat: Add "Collapse All Comments"
  client/cody/CHANGELOG.md
  client/cody/package.json
  client/cody/src/main.ts
Labels: cla-signed, team/code-exploration

#54707 sg generate: fix typo and add missing newline
  dev/sg/generates.go
Labels: cla-signed, team/iam

#54676 graphql api: add `user.completedPostSignup` and `setCompletedPostSignup`
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
  internal/database/schema.json
  internal/database/schema.md
  internal/database/users.go
  internal/database/users_test.go
  internal/types/types.go
  migrations/BUILD.bazel
  migrations/frontend/1688649829_user_completed_post_signup/down.sql
  migrations/frontend/1688649829_user_completed_post_signup/metadata.yaml
  migrations/frontend/1688649829_user_completed_post_signup/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/iam

#54682 uploadstore: add method to list all keys
  cmd/blobstore/internal/blobstore/blobstore_test.go
  internal/embeddings/BUILD.bazel
  internal/embeddings/index_storage_test.go
  internal/uploadstore/BUILD.bazel
  internal/uploadstore/gcs_client.go
  internal/uploadstore/gcs_client_test.go
  internal/uploadstore/lazy_client.go
  internal/uploadstore/mocks/BUILD.bazel
  internal/uploadstore/mocks/mocks_temp.go
  internal/uploadstore/observability.go
  internal/uploadstore/s3_client.go
  internal/uploadstore/store.go
Labels: cla-signed

#54622 env: add MustGetBytes
  doc/cody/explanations/code_graph_context.md
  enterprise/cmd/embeddings/shared/config.go
  enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
  enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
  internal/embeddings/types.go
  internal/env/BUILD.bazel
  internal/env/env.go
Labels: cla-signed

#54681 create migrations for file embeddings
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1688654272_create_file_embeddings_jobs_table/down.sql
  migrations/frontend/1688654272_create_file_embeddings_jobs_table/metadata.yaml
  migrations/frontend/1688654272_create_file_embeddings_jobs_table/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#54539 [Backport 5.1] Update prometheus tools
  dev/oci_deps.bzl
  wolfi-images/batcheshelper.yaml
  wolfi-images/node-exporter.yaml
  wolfi-images/postgres-exporter.yaml
  wolfi-images/server.yaml
Labels: cla-signed, backported-to-5.1

#54649 release: improve minor release template
  dev/release/templates/release_issue_template.md
Labels: cla-signed

#54619 bzl: convert go generate + stringer to bazel
  dev/BUILD.bazel
  enterprise/internal/batches/search/syntax/BUILD.bazel
  enterprise/internal/batches/search/syntax/scanner.go
  enterprise/internal/batches/search/syntax/tokentype_string.go
  lib/codeintel/lsif/protocol/BUILD.bazel
Labels: cla-signed, dev-infra/go-generate

#54452 Autocomplete: Check for additional completion providers when sending logs
  client/cody/src/completions/logger.ts
Labels: cla-signed, team/code-exploration

#54716 App - Add a settings screen to display rate limit info when using sourcegraph provdier
  CHANGELOG.app.md
  client/web/BUILD.bazel
  client/web/src/enterprise/app/settings/AppSettingsArea.tsx
  client/web/src/enterprise/app/settings/rate-limits/RateLimitsTab.module.scss
  client/web/src/enterprise/app/settings/rate-limits/RateLimitsTab.tsx
  cmd/frontend/graphqlbackend/app.go
  cmd/frontend/graphqlbackend/app.graphql
  enterprise/cmd/frontend/internal/app/resolvers/BUILD.bazel
  enterprise/cmd/frontend/internal/app/resolvers/app.go
  enterprise/cmd/frontend/internal/app/resolvers/cody_rate_limit.go
Labels: cla-signed

#54643 Markprompt v0.10.0
  doc/_resources/assets/docsite.css
  doc/_resources/templates/root.html
Labels: cla-signed

#54719 github: show bazel diff again
  .gitattributes
Labels: cla-signed

#54718 App - disable gitserver cleanup
  src-tauri/src/main.rs
Labels: cla-signed

#54722 App - add sg app reset command to clear local app dev data
  dev/sg/sg_app.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#54724 App - add a developer menu for dev mode
  src-tauri/src/tray.rs
Labels: cla-signed

#54689 cody-gateway/embeddings: forward 400s from OpenAI
  enterprise/cmd/cody-gateway/internal/actor/source.go
  enterprise/cmd/cody-gateway/internal/events/instrumented.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
  enterprise/cmd/cody-gateway/internal/limiter/limiter.go
Labels: cla-signed

#54725 release: make release event attendees optional
  dev/release/src/google-calendar.ts
Labels: cla-signed

#54730 App - disable debug endpoints on port 6060
  CHANGELOG.app.md
  src-tauri/src/main.rs
Labels: cla-signed

#54720 chore: add label notify for `cody-gateway`
  .github/workflows/label-notify.yml
Labels: cla-signed

#54644 Implements `sg rfc [--private] create <rfc title>`
  .vscode/launch.json
  dev/sg/internal/rfc/BUILD.bazel
  dev/sg/internal/rfc/rfc.go
  dev/sg/internal/rfc/rfc_create.go
  dev/sg/sg_rfc.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#54733 JetBrains: set minimum 3 rows for input text area
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Labels: cla-signed

#54668 JetBrains: Cody: improve prompt
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/AnthropicAutoCompleteProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/AutoCompleteProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/CodyAutoCompleteItemProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/EndOfLineAutoCompleteProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/PostProcess.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/TextProcessing.java
  client/jetbrains/src/test/java/PostProcessTest.java
Labels: cla-signed

#54739 bazel generate doc suggestions / fixes
  doc/dev/background-information/bazel/go_generate.md
Labels: cla-signed

#54685 bzl: migrate genqlient go:generate to Bazel
  cmd/frontend/graphqlbackend/BUILD.bazel
  dev/BUILD.bazel
  dev/write_generated_to_source_files.bzl
  doc/dev/background-information/bazel/go.md
  doc/dev/background-information/bazel/go_generate.md
  doc/dev/background-information/bazel/index.md
  enterprise/cmd/cody-gateway/internal/dotcom/BUILD.bazel
  enterprise/cmd/cody-gateway/internal/dotcom/gen.go
  enterprise/cmd/frontend/internal/guardrails/dotcom/BUILD.bazel
  enterprise/cmd/frontend/internal/guardrails/dotcom/gen.go
Labels: cla-signed, dev-infra/go-generate

#54717 sg: add runtype manually triggered
  dev/ci/runtype/runtype.go
  dev/sg/sg_ci.go
  doc/dev/background-information/ci/reference.md
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#54726 Embeddings: add file name to the error message from OpenAI weirdness
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
  internal/embeddings/embed/client/client.go
  internal/embeddings/embed/client/openai/BUILD.bazel
  internal/embeddings/embed/client/openai/client.go
  internal/embeddings/embed/client/sourcegraph/BUILD.bazel
  internal/embeddings/embed/client/sourcegraph/client.go
  internal/embeddings/embed/client/sourcegraph/client_test.go
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
Labels: cla-signed

#54732 chore: remove unused ListFiles in gitserver client
  enterprise/internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/protocol/gitserver.go
Labels: cla-signed, team/source

#54747 bzl: enable go_test to turn off race detector
  dev/go_defs.bzl
Labels: cla-signed, backport 5.1

#54752 wolfi: build prometheus-gcp image
  dev/oci_deps.bzl
  doc/dev/background-information/ci/reference.md
  docker-images/prometheus-gcp/BUILD.bazel
  docker-images/prometheus-gcp/image_test.yaml
  enterprise/dev/ci/internal/ci/pipeline.go
  wolfi-images/prometheus-gcp.yaml
  wolfi-packages/prometheus-gcp.yaml
Labels: cla-signed

#54745 conf: Fix httpcli config
  CHANGELOG.md
  enterprise/cmd/frontend/shared/shared.go
  internal/conf/init.go
Labels: cla-signed, backport 5.1

#54762 go: linting fix
  doc/dev/background-information/ci/reference.md
Labels: cla-signed

#54764 cody-gateway: commit usage with background context
  enterprise/cmd/cody-gateway/internal/limiter/limiter.go
Labels: cla-signed

#54641 context: Schema experiments
  doc/admin/how-to/clear_codeintel_data.md
  enterprise/internal/oobmigration/migrations/codeintel/scip/BUILD.bazel
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_migrator.go
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_util.go
  internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
  internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
  internal/codeintel/uploads/internal/lsifstore/BUILD.bazel
  internal/codeintel/uploads/internal/lsifstore/cleanup.go
  internal/codeintel/uploads/internal/lsifstore/insert.go
  internal/codeintel/uploads/internal/lsifstore/insert_util.go
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  internal/oobmigration/oobmigrations.yaml
  migrations/BUILD.bazel
  migrations/codeintel/1685132632_update_scip_symbols_tables/down.sql
  migrations/codeintel/1685132632_update_scip_symbols_tables/metadata.yaml
  migrations/codeintel/1685132632_update_scip_symbols_tables/up.sql
  migrations/codeintel/1688674706_update_scip_symbol_tables/down.sql
  migrations/codeintel/1688674706_update_scip_symbol_tables/metadata.yaml
  migrations/codeintel/1688674706_update_scip_symbol_tables/up.sql
  migrations/codeintel/squashed.sql
  sg.config.yaml
Labels: cla-signed

#54693 context: Misc bugfixes
  client/cody-shared/src/graph-context/index.ts
  client/cody/src/graph-context/graph-context-fetcher.ts
  doc/admin/how-to/clear_codeintel_data.md
  enterprise/internal/oobmigration/migrations/codeintel/scip/BUILD.bazel
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_migrator.go
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_util.go
  internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
  internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
  internal/codeintel/context/service.go
  internal/codeintel/uploads/internal/lsifstore/BUILD.bazel
  internal/codeintel/uploads/internal/lsifstore/cleanup.go
  internal/codeintel/uploads/internal/lsifstore/insert.go
  internal/codeintel/uploads/internal/lsifstore/insert_util.go
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  internal/oobmigration/oobmigrations.yaml
  migrations/BUILD.bazel
  migrations/codeintel/1685132632_update_scip_symbols_tables/down.sql
  migrations/codeintel/1685132632_update_scip_symbols_tables/metadata.yaml
  migrations/codeintel/1685132632_update_scip_symbols_tables/up.sql
  migrations/codeintel/1688674706_update_scip_symbol_tables/down.sql
  migrations/codeintel/1688674706_update_scip_symbol_tables/metadata.yaml
  migrations/codeintel/1688674706_update_scip_symbol_tables/up.sql
  migrations/codeintel/squashed.sql
  sg.config.yaml
Labels: team/code-intelligence, cla-signed, team/language-platform

#54691 context: cleanup paths-not-taken
  client/cody-shared/src/chat/recipes/helpers.ts
  client/cody-shared/src/graph-context/index.ts
  client/cody-shared/src/sourcegraph-api/graphql/client.ts
  client/cody/src/graph-context/graph-context-fetcher.ts
  cmd/frontend/internal/cli/config.go
  doc/admin/how-to/clear_codeintel_data.md
  enterprise/internal/oobmigration/migrations/codeintel/scip/BUILD.bazel
  enterprise/internal/oobmigration/migrations/codeintel/scip/migrator.go
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_migrator.go
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_util.go
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
  internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
  internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
  internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
  internal/codeintel/codenav/internal/lsifstore/observability.go
  internal/codeintel/codenav/internal/lsifstore/store.go
  internal/codeintel/codenav/internal/lsifstore/util.go
  internal/codeintel/codenav/mocks_test.go
  internal/codeintel/codenav/request_state.go
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/context/BUILD.bazel
  internal/codeintel/context/iface.go
  internal/codeintel/context/init.go
  internal/codeintel/context/internal/scipstore/BUILD.bazel
  internal/codeintel/context/internal/scipstore/observability.go
  internal/codeintel/context/internal/scipstore/store.go
  internal/codeintel/context/internal/scipstore/store_test.go
  internal/codeintel/context/service.go
  internal/codeintel/context/transport/graphql/root_resolver.go
  internal/codeintel/context/transport/graphql/types.go
  internal/codeintel/services.go
  internal/codeintel/shared/symbols/symbols.go
  internal/codeintel/types/context.go
  internal/codeintel/uploads/internal/lsifstore/BUILD.bazel
  internal/codeintel/uploads/internal/lsifstore/cleanup.go
  internal/codeintel/uploads/internal/lsifstore/insert.go
  internal/codeintel/uploads/internal/lsifstore/insert_util.go
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  internal/gosyntect/gosyntect.go
  internal/highlight/chroma.go
  internal/highlight/highlight.go
  internal/highlight/highlight_test.go
  internal/highlight/language.go
  internal/oobmigration/oobmigrations.yaml
  migrations/BUILD.bazel
  migrations/codeintel/1685132632_update_scip_symbols_tables/down.sql
  migrations/codeintel/1685132632_update_scip_symbols_tables/metadata.yaml
  migrations/codeintel/1685132632_update_scip_symbols_tables/up.sql
  migrations/codeintel/1688674706_update_scip_symbol_tables/down.sql
  migrations/codeintel/1688674706_update_scip_symbol_tables/metadata.yaml
  migrations/codeintel/1688674706_update_scip_symbol_tables/up.sql
  migrations/codeintel/squashed.sql
  sg.config.yaml
Labels: team/code-intelligence, cla-signed, team/language-platform

#54736 source: add database methods for embedding plugin files
  internal/database/BUILD.bazel
  internal/database/database.go
  internal/database/embedding_plugin_files.go
  internal/database/embedding_plugin_files_test.go
  internal/database/mocks_temp.go
  internal/types/types.go
Labels: cla-signed

#54779 go: bump sourcegraph/log
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#54534 [Backport 5.1] executors/multi-queue: implement queue selection fairness
  deps.bzl
  doc/admin/observability/dashboards.md
  enterprise/cmd/frontend/internal/executorqueue/handler/BUILD.bazel
  enterprise/cmd/frontend/internal/executorqueue/handler/multihandler.go
  enterprise/cmd/frontend/internal/executorqueue/handler/multihandler_test.go
  enterprise/cmd/worker/internal/executors/BUILD.bazel
  enterprise/cmd/worker/internal/executors/janitor_config.go
  enterprise/cmd/worker/internal/executors/janitor_job.go
  enterprise/cmd/worker/internal/executors/multiqueue_cache_cleaner.go
  enterprise/cmd/worker/internal/executors/multiqueue_cache_cleaner_test.go
  enterprise/internal/executor/types/BUILD.bazel
  enterprise/internal/executor/types/cache.go
  go.mod
  go.sum
  monitoring/definitions/executor.go
  monitoring/definitions/shared/executors.go
  monitoring/definitions/shared/queues.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#54710 JetBrains: show stop generating button while receiving the response
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/CompletionsService.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/SSEClient.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/SourcegraphNodeCompletionsClient.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Chat.java
Labels: cla-signed

#54786 JetBrains: disable gradle copyAgentBinariesToPluginPath task
  client/jetbrains/build.gradle.kts
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
Labels: cla-signed

#54789 App - update changelog for release
  CHANGELOG.app.md
Labels: cla-signed

#54748 graphqlbackend: update throttled to use Ctx stores
  cmd/frontend/graphqlbackend/rate_limit.go
  cmd/frontend/graphqlbackend/rate_limit_test.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/api_test.go
  cmd/frontend/internal/httpapi/graphql.go
  deps.bzl
  dev/backcompat/defs.bzl
  go.mod
  go.sum
Labels: cla-signed

#54790 Add Windows ETA
  doc/app/index.md
Labels: cla-signed

#54793 doc: mention json_gcp format for logs
  doc/admin/observability/logs.md
Labels: cla-signed

#54791 [Backport 5.1] Change default for Claude model (#54784)
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  doc/cody/explanations/cody_gateway.md
  doc/cody/explanations/enabling_cody_enterprise.md
  doc/dev/how-to/cody_gateway.md
  enterprise/cmd/cody-gateway/internal/actor/anonymous/anonymous.go
  enterprise/cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  enterprise/cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  enterprise/cmd/cody-gateway/shared/config.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
Labels: cla-signed

#54785 JetBrains: Fix NullPointerException if there's no chat component
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChatHolderService.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Chat.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatMessage.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/RefreshCodyAppDetection.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ResetCurrentConversationAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SimpleRecipeAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguageAction.java
Labels: cla-signed

#54769 ci: surpress pre-exit hook warnings
  .buildkite/hooks/pre-exit
Labels: cla-signed

#54801 Chore: remove unused code
  cmd/frontend/graphqlbackend/settings.go
  internal/api/api.go
  internal/api/httpapi_schema.go
Labels: cla-signed

#54792 Add unit tests
  enterprise/internal/oobmigration/migrations/codeintel/scip/BUILD.bazel
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_migrator.go
  enterprise/internal/oobmigration/migrations/codeintel/scip/symbols_migrator_test.go
  enterprise/internal/oobmigration/migrations/codeintel/scip/testdata/trie.sql
  internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
  internal/codeintel/codenav/internal/lsifstore/document_metadata_test.go
  internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
  internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
  internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
  internal/codeintel/codenav/internal/lsifstore/lsifstore_documents_test.go
  internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
  internal/codeintel/codenav/internal/lsifstore/metadata_by_position_test.go
  internal/codeintel/codenav/internal/lsifstore/symbols_by_position_test.go
  internal/codeintel/codenav/internal/lsifstore/testdata/go-mockgen@d061eb0.sql
  internal/codeintel/uploads/internal/lsifstore/insert.go
  internal/codeintel/uploads/internal/lsifstore/insert_test.go
  internal/codeintel/uploads/internal/lsifstore/testdata/code-intel-extensions@7802976b.sql
Labels: cla-signed

#54803 codesearch: Handle error if not a pushCommitError
  enterprise/internal/batches/reconciler/executor.go
  enterprise/internal/batches/reconciler/executor_test.go
Labels: team/batchers, cla-signed, backport 5.1

#54805 Switch to uncached doer in cody gateway
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/openai.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/BUILD.bazel
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#54673 refactor file writing
  internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
Labels: cla-signed

#54811 Redact command before logging during create-commit-from-patch
  cmd/gitserver/server/patch.go
Labels: cla-signed, backport 5.1, team/source

#54698 Cody App about page
  client/web/BUILD.bazel
  client/web/src/enterprise/app/settings/AppSettingsArea.tsx
  client/web/src/enterprise/app/settings/about/AboutPage.module.scss
  client/web/src/enterprise/app/settings/about/AboutPage.story.tsx
  client/web/src/enterprise/app/settings/about/AboutPage.tsx
  client/web/src/site-admin/SiteAdminUpdatesPage.tsx
  client/web/src/site-admin/sidebaritems.ts
  ui/assets/img/cody-logo-filled.png
Labels: cla-signed

#54816 JetBrains: 3.0.4 release
  client/jetbrains/CHANGELOG.md
  client/jetbrains/gradle.properties
Labels: cla-signed

#54818 sg: print jobs output even if all done before exit
  dev/sg/internal/background/background.go
Labels: cla-signed

#54814 backcompat: use keyword args to format and generate build commands seds
  dev/backcompat/defs.bzl
Labels: cla-signed

#54815 JetBrains: show insert code at current position button
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/CodeEditorFactory.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/ui/TransparentButton.java
Labels: cla-signed

#54852 gateway: Add actor tracking to upstream requests
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/embeddings/openai.go
Labels: cla-signed

#54858 postgresdsn: Fix double port
  CHANGELOG.md
  internal/database/postgresdsn/postgresdsn.go
  internal/database/postgresdsn/postgresdsn_test.go
Labels: cla-signed, backport 5.1
