Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-03, with the labels that each got.

#48392 Docs: update docs for AWS one-click installation
  doc/admin/deploy/machine-images/aws-diagram.svg
  doc/admin/deploy/machine-images/aws-oneclick-diagram.png
  doc/admin/deploy/machine-images/aws-oneclick.md
Labels: cla-signed

#48385 ranking: Do incremental vacuuming, not all-or-nothing deletes
  enterprise/internal/codeintel/uploads/internal/store/store_ranking.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1677627515_add_scan_column_to_ranking_definitionsreferences/down.sql
  migrations/frontend/1677627515_add_scan_column_to_ranking_definitionsreferences/metadata.yaml
  migrations/frontend/1677627515_add_scan_column_to_ranking_definitionsreferences/up.sql
  migrations/frontend/1677627559_add_index_to_definition_scan_column/down.sql
  migrations/frontend/1677627559_add_index_to_definition_scan_column/metadata.yaml
  migrations/frontend/1677627559_add_index_to_definition_scan_column/up.sql
  migrations/frontend/1677627566_add_index_to_reference_scan_column/down.sql
  migrations/frontend/1677627566_add_index_to_reference_scan_column/metadata.yaml
  migrations/frontend/1677627566_add_index_to_reference_scan_column/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#48219 internal/database: avoid potential performance issue in db driver
  internal/database/dbconn/open.go
Labels: cla-signed

#48315 own: Cache compiled rule expressions
  enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go
  internal/own/codeowners/file.go
  internal/own/codeowners/find_owners.go
  internal/own/codeowners/find_owners_test.go
  internal/own/codeowners/parse.go
  internal/own/codeowners/parse_test.go
  internal/own/codeowners/repr.go
  internal/own/service.go
  internal/own/service_test.go
  internal/search/codeownership/rules_cache.go
Labels: cla-signed

#48401 Optionally hide major and minor update from alerts banner
  cmd/frontend/graphqlbackend/site_alerts.go
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#48403 Fix paths not absolute in test.CODEOWNERS
  .github/test.CODEOWNERS
Labels: cla-signed

#48161 Ranking: small fix to search aggregator
  internal/search/backend/aggregate.go
  internal/search/backend/aggregate_test.go
Labels: cla-signed

#48383 Cclark/fix data retention minimum samples
  enterprise/internal/insights/background/retention/worker.go
  enterprise/internal/insights/background/retention/worker_test.go
Labels: cla-signed

#48406 web: remove ignore plugin from the webpack.bazel.config.js
  client/web/webpack.bazel.config.js
Labels: cla-signed, team/code-exploration, JF/bazel

#48407 web: test web app enteprise build with Bazel
  client/build-config/src/paths.ts
  client/web/dev/server/production.server.ts
  client/web/dev/utils/environment-config.ts
  client/web/dev/utils/get-index-html.ts
  client/web/webpack.bazel.config.js
Labels: cla-signed, team/code-exploration, JF/bazel

#48413 fix name of the story in Storybook.
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
Labels: cla-signed

#48415 web: add missing static assets to bazel bundle target
  client/web/BUILD.bazel
Labels: cla-signed, JF/bazel

#48411 bazel: add `.bazeliskrc` with Aspect-CLI
  .bazeliskrc
Labels: cla-signed, team/code-exploration, JF/bazel

#48417 httpcli: remove high cardinality prometheus label internal transport
  internal/httpcli/client.go
Labels: cla-signed

#48354 Clean up data-loading in file tree
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarFileTree.tsx
Labels: cla-signed, team/code-exploration

#48436 servegit: restructure Walk code to be more idiomatic
  internal/service/servegit/serve.go
Labels: cla-signed

#48390 Remove Sign Out when in App
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/UserNavItem.story.tsx
  client/web/src/nav/UserNavItem.test.tsx
  client/web/src/nav/UserNavItem.tsx
Labels: cla-signed, app

#48444 servegit: skip files unlikely to contain code
  dev/internal/cmd/app-discover-repos/app-discover-repos.go
  internal/fastwalk/fastwalk.go
  internal/service/servegit/serve.go
Labels: cla-signed

#48450 completions: redact access token
  internal/conf/validate.go
Labels: cla-signed

#48439 ci: exclude internal/database from all go test
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#48451 Add missing directive for gazelle go
  BUILD.bazel
Labels: cla-signed, JF/bazel

#48454 syntax-highlighter: update tree-sitter-csharp back to crates.io
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/sg-syntax/Cargo.toml
Labels: team/code-intelligence, cla-signed

#48412 Update bazel dependencies file
  WORKSPACE
  deps.bzl
Labels: cla-signed

#48380 Setup Experience: Fix try unmarshal external service ID
  cmd/frontend/graphqlbackend/external_service.go
Labels: cla-signed

#48453 SCIM: Add test for PUT, fix silly mistake around changes
  enterprise/internal/scim/user.go
  enterprise/internal/scim/user_patch.go
  enterprise/internal/scim/user_replace.go
  enterprise/internal/scim/user_replace_test.go
Labels: cla-signed

#48469 own: Fix error when no codeowners data is present
  enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
Labels: cla-signed

#48464 rbac: allow permissions to be assigned on role creation
  cmd/frontend/graphqlbackend/rbac.go
  cmd/frontend/graphqlbackend/rbac.graphql
  enterprise/cmd/frontend/internal/rbac/resolvers/roles.go
  enterprise/cmd/frontend/internal/rbac/resolvers/roles_test.go
  internal/database/mocks_temp.go
  internal/database/role_permissions.go
  internal/database/role_permissions_test.go
Labels: cla-signed, rbac

#48388 validate there are no release blocking issues prior to critical momen…
  dev/release/src/release.ts
  dev/release/src/util.ts
Labels: cla-signed

#48374 Fix docs links in App and add UTM, version, and OS parameters
  cmd/frontend/internal/app/ui/help.go
Labels: cla-signed, app

#48471 Hide experimental k8s docs
  doc/admin/executors.md
Labels: cla-signed

#48088 Add generated API docs
  doc/_resources/spectaql/stylesheets/main.scss
  doc/_resources/spectaql/stylesheets/paraiso-dark-theme.css
  doc/api/graphql/api-docs.md
  doc/api/graphql/index.md
Labels: cla-signed, hackathon

#48445 [Permissions] add user permissions info ui
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.module.scss
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  client/web/src/enterprise/user/settings/auth/backend.ts
  client/web/src/site-admin/UserManagement/components/Table.module.scss
  client/web/src/site-admin/UserManagement/components/Table.tsx
  client/web/src/site-admin/UserManagement/components/UsersList.tsx
  enterprise/cmd/frontend/internal/authz/resolvers/permissions_info.go
Labels: cla-signed, team/iam

#48477 Update free-plan table
  doc/getting-started/oss-enterprise.md
Labels: cla-signed, team/iam

#48305 monitoring: add codeintel, batches multi-instance executor queue
  doc/admin/observability/dashboards.md
  monitoring/definitions/executor.go
  monitoring/definitions/shared/batches.go
  monitoring/definitions/shared/codeintel.go
  monitoring/definitions/shared/codeintel_autoindexing.go
  monitoring/definitions/shared/executors.go
  monitoring/definitions/shared/shared.go
  monitoring/definitions/worker.go
Labels: cla-signed

#48475 own: fix avatar size
  client/web/src/repo/blob/own/FileOwnershipEntry.tsx
  client/web/src/repo/blob/own/FileOwnershipPanel.story.tsx
  client/web/src/repo/blob/own/HistoryAndOwnBar.module.scss
  client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
  client/web/src/repo/blob/own/HistoryAndOwnBar.tsx
Labels: cla-signed

#48466 codeintel: Add comparison key to index configuration-like things
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/internal/codeintel/autoindexing/transport/graphql/index_configuration_resolver.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
  internal/codeintel/resolvers/all.go
Labels: cla-signed

#48400 ranking: Move all related logic into ranking service
  doc/admin/observability/dashboards.md
  doc/admin/workers.md
  enterprise/cmd/worker/internal/codeintel/ranking_sourcer.go
  enterprise/cmd/worker/internal/codeintel/uploads_graph_exporter.go
  enterprise/cmd/worker/shared/shared.go
  enterprise/internal/codeintel/ranking/BUILD.bazel
  enterprise/internal/codeintel/ranking/config.go
  enterprise/internal/codeintel/ranking/iface.go
  enterprise/internal/codeintel/ranking/init.go
  enterprise/internal/codeintel/ranking/internal/background/BUILD.bazel
  enterprise/internal/codeintel/ranking/internal/background/file_reference_graph.go
  enterprise/internal/codeintel/ranking/internal/background/iface.go
  enterprise/internal/codeintel/ranking/internal/background/indexer.go
  enterprise/internal/codeintel/ranking/internal/background/indexer_test.go
  enterprise/internal/codeintel/ranking/internal/background/job_graph_exporter.go
  enterprise/internal/codeintel/ranking/internal/background/loader.go
  enterprise/internal/codeintel/ranking/internal/background/loader_metrics.go
  enterprise/internal/codeintel/ranking/internal/background/merger.go
  enterprise/internal/codeintel/ranking/internal/background/merger_metrics.go
  enterprise/internal/codeintel/ranking/internal/background/observabililty.go
  enterprise/internal/codeintel/ranking/internal/background/pagerank.go
  enterprise/internal/codeintel/ranking/internal/background/streaming_graph.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/BUILD.bazel
  enterprise/internal/codeintel/ranking/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/lsifstore_ranking.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/observability.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/stream.go
  enterprise/internal/codeintel/ranking/internal/store/BUILD.bazel
  enterprise/internal/codeintel/ranking/internal/store/observability.go
  enterprise/internal/codeintel/ranking/internal/store/ranking.go
  enterprise/internal/codeintel/ranking/internal/store/ranking_test.go
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/codeintel/ranking/internal/store/store_export.go
  enterprise/internal/codeintel/ranking/internal/store/store_export_test.go
  enterprise/internal/codeintel/ranking/internal/store/store_test.go
  enterprise/internal/codeintel/ranking/load-ranks.sh
  enterprise/internal/codeintel/ranking/mocks_test.go
  enterprise/internal/codeintel/ranking/observability.go
  enterprise/internal/codeintel/ranking/ranking.go
  enterprise/internal/codeintel/ranking/service.go
  enterprise/internal/codeintel/ranking/service_test.go
  enterprise/internal/codeintel/services.go
  enterprise/internal/codeintel/uploads/config.go
  enterprise/internal/codeintel/uploads/init.go
  enterprise/internal/codeintel/uploads/internal/background/mocks_test.go
  enterprise/internal/codeintel/uploads/internal/background/observability.go
  enterprise/internal/codeintel/uploads/internal/store/observability.go
  enterprise/internal/codeintel/uploads/internal/store/store.go
  enterprise/internal/codeintel/uploads/mocks_test.go
  enterprise/internal/codeintel/uploads/observability.go
  go.mod
  go.sum
  mockgen.test.yaml
  monitoring/definitions/codeintel_ranking.go
  monitoring/definitions/shared/codeintel_ranking.go
Labels: cla-signed

#48479 basestore: Add NewFilteredSliceScanner
  internal/database/basestore/scan_collections.go
Labels: cla-signed

#48480 sentinel: Make skeleton backend service
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/cmd/frontend/internal/codeintel/resolvers.go
  enterprise/cmd/worker/internal/codeintel/sentinel_job.go
  enterprise/cmd/worker/shared/shared.go
  enterprise/internal/codeintel/sentinel/config.go
  enterprise/internal/codeintel/sentinel/init.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_downloader.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_matcher.go
  enterprise/internal/codeintel/sentinel/internal/background/metrics.go
  enterprise/internal/codeintel/sentinel/internal/store/observability.go
  enterprise/internal/codeintel/sentinel/internal/store/store.go
  enterprise/internal/codeintel/sentinel/observability.go
  enterprise/internal/codeintel/sentinel/service.go
  enterprise/internal/codeintel/sentinel/transport/graphql/iface.go
  enterprise/internal/codeintel/sentinel/transport/graphql/observability.go
  enterprise/internal/codeintel/sentinel/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/services.go
  internal/codeintel/resolvers/all.go
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48438 [Request access] Add empty list content + update docs
  client/web/src/site-admin/AccessRequestsPage/index.tsx
  doc/admin/auth/index.md
Labels: cla-signed

#48478 sentinel: Draft table schemas
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1677694168_add_vulnerability_tables/down.sql
  migrations/frontend/1677694168_add_vulnerability_tables/metadata.yaml
  migrations/frontend/1677694168_add_vulnerability_tables/up.sql
  migrations/frontend/1677694170_add_vulnerability_match_tables/down.sql
  migrations/frontend/1677694170_add_vulnerability_match_tables/metadata.yaml
  migrations/frontend/1677694170_add_vulnerability_match_tables/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48494 Remove unused setters on EnterpriseSearchJobs
  enterprise/internal/search/jobs.go
Labels: cla-signed

#48344 [Request access] Add admin analytics
  client/web/src/site-admin/UserManagement/index.tsx
  client/web/src/site-admin/UserManagement/queries.tsx
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/queries.ts
  client/web/src/site-admin/analytics/AnalyticsUsersPage/AnalyticsUsersPage.story.tsx
  client/web/src/site-admin/analytics/AnalyticsUsersPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsUsersPage/queries.ts
Labels: merge-on-any-approve, cla-signed

#48495 codeintel: Split counts from upload/index fetches
  enterprise/internal/codeintel/autoindexing/internal/store/store_indexes.go
  enterprise/internal/codeintel/uploads/internal/store/store_uploads.go
Labels: cla-signed

#48497 experimental search input: Support Ctrl-n/p navigation for suggestions on macOS
  client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
Labels: cla-signed

#48498 oobmigration: Parse new version string
  internal/oobmigration/version.go
  internal/oobmigration/version_test.go
Labels: cla-signed

#48492 codeintel: Improve index usage for upload/index fetching
  enterprise/internal/codeintel/autoindexing/internal/store/store_indexes.go
  enterprise/internal/codeintel/uploads/internal/store/store_uploads.go
Labels: cla-signed

#48505 Add k3s deployType
  internal/conf/deploy/deploytype.go
Labels: cla-signed

#48506 fix: executor docs formatting
  doc/admin/deploy_executors.md
Labels: cla-signed

#48502 Remove "prototype" status badge
  client/web/src/team/area/TeamHeader.tsx
  client/web/src/team/list/TeamListPage.tsx
  client/wildcard/src/components/Badge/ProductStatusBadge.tsx
  client/wildcard/src/components/Badge/constants.ts
  client/wildcard/src/components/Feedback/FeedbackBadge/__snapshots__/FeedbackBadge.test.tsx.snap
  client/wildcard/src/components/Feedback/FeedbackBadge/constant.ts
  client/wildcard/src/components/PageHeader/PageHeader.story.tsx
Labels: cla-signed

#48514 ranking: Split map/reduce batch sizes
  enterprise/internal/codeintel/ranking/config.go
  enterprise/internal/codeintel/ranking/ranking.go
Labels: team/code-intelligence, cla-signed, team/language-platform, ranking

#48513 ranking: Ensure we write graph key
  enterprise/internal/codeintel/ranking/internal/store/ranking.go
Labels: team/code-intelligence, cla-signed, team/language-platform, ranking

#48399 Optimize matching performance on average and for specific edge-cases
  internal/own/codeowners/file.go
  internal/own/codeowners/find_owners.go
  internal/own/codeowners/find_owners_test.go
Labels: cla-signed

#48398 Setup Wizard: Support code host connection edit UI
  client/web/src/setup-wizard/SetupWizard.tsx
  client/web/src/setup-wizard/components/ProgressBar.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-delete-modal/CodeHostDeleteModal.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/CodeHostCreation.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/CodeHostEdit.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubConnectView.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubEntityPickers.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/helpers.ts
  client/web/src/setup-wizard/components/remote-repositories-step/queries.ts
  client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
Labels: cla-signed

#46127 LSIF: Remove tables from schema
  dev/ci/go-backcompat/flakefiles/v4.5.0.json
  enterprise/internal/oobmigration/migrations/codeintel/diagnostics_count_test.go
  enterprise/internal/oobmigration/migrations/codeintel/document_column_split_test.go
  enterprise/internal/oobmigration/migrations/codeintel/locations_count_test.go
  enterprise/internal/oobmigration/migrations/codeintel/migrator_test.go
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator_test.go
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/frozen/3.34.2.json
  internal/database/migration/shared/data/frozen/4.5.0.json
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  migrations/codeintel/1676423214_remove_lsif_data/down.sql
  migrations/codeintel/1676423214_remove_lsif_data/metadata.yaml
  migrations/codeintel/1676423214_remove_lsif_data/up.sql
  migrations/codeintel/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform, rfc-740

#47704 rbac: implement mutation for assigning permissions to a role
  cmd/frontend/graphqlbackend/rbac.go
  cmd/frontend/graphqlbackend/rbac.graphql
  enterprise/cmd/frontend/internal/rbac/resolvers/permissions.go
  enterprise/cmd/frontend/internal/rbac/resolvers/permissions_test.go
  internal/database/mocks_temp.go
  internal/database/role_permissions.go
  internal/database/role_permissions_test.go
Labels: team/batchers, cla-signed, rbac

#48418 web: fix web bazel build
  client/web/BUILD.bazel
  client/web/src/components/WebStory.tsx
  client/web/src/components/legacyLayoutRouteContext.ts
Labels: cla-signed, team/code-exploration, JF/bazel

#48520 bazel: enable js+go plugins
  BUILD.bazel
Labels: cla-signed

#48414 cody: admin page
  client/web/dev/utils/create-js-context.ts
  client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.module.scss
  client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.tsx
  client/web/src/enterprise/site-admin/cody/SiteAdminCodyPage.module.scss
  client/web/src/enterprise/site-admin/cody/SiteAdminCodyPage.tsx
  client/web/src/enterprise/site-admin/cody/backend.ts
  client/web/src/enterprise/site-admin/routes.tsx
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  cmd/frontend/graphqlbackend/embeddings.go
  cmd/frontend/graphqlbackend/embeddings.graphql
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs.go
  enterprise/cmd/frontend/internal/embeddings/resolvers/resolvers.go
  enterprise/cmd/worker/internal/embeddings/contextdetection/handler.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/internal/embeddings/background/contextdetection/store.go
  enterprise/internal/embeddings/background/contextdetection/types.go
  enterprise/internal/embeddings/background/repo/mocks_temp.go
  enterprise/internal/embeddings/background/repo/store.go
  enterprise/internal/embeddings/background/repo/store_test.go
  enterprise/internal/embeddings/background/repo/types.go
  internal/conf/computed.go
  schema/site.schema.json
Labels: cla-signed

#48470 [docs] fixed papercuts in new permission docs
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  doc/admin/index.md
  doc/admin/observability/dashboards.md
  doc/admin/permissions/api.md
  doc/admin/permissions/index.md
  doc/admin/permissions/syncing.md
  doc/admin/permissions/webhooks.md
  doc/sidebar.md
  monitoring/definitions/repo_updater.go
  schema/github.schema.json
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam

#48488 experimental search input: Don't show symbol suggestions in (only) global context
  client/web/src/search/input/suggestions.ts
Labels: cla-signed

#48491 experimental search input: Add "go to" support for repo/file filter value suggestions
  client/web/src/search/input/suggestions.ts
Labels: cla-signed

#48026 [Request access] Add pings
  client/web/src/auth/RequestAccessPage.test.tsx
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  client/web/src/util/checkRequestAccessAllowed.ts
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/app/updatecheck/handler_test.go
  cmd/frontend/internal/auth/accessrequest/handlers.go
  cmd/frontend/internal/auth/accessrequest/handlers_test.go
  doc/admin/pings.md
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/database/schema.json
  internal/database/schema.md
  internal/types/types.go
  internal/usagestats/growth.go
  internal/usagestats/growth_test.go
  migrations/frontend/1677607213_add_indexes_on_access_requests_create_at_and_status_columns/down.sql
  migrations/frontend/1677607213_add_indexes_on_access_requests_create_at_and_status_columns/metadata.yaml
  migrations/frontend/1677607213_add_indexes_on_access_requests_create_at_and_status_columns/up.sql
  migrations/frontend/squashed.sql
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/growth

#48496 [Request access] Add capturing of decision maker admin user id
  cmd/frontend/graphqlbackend/access_requests.go
  cmd/frontend/graphqlbackend/access_requests_test.go
  internal/database/access_requests.go
  internal/database/access_requests_test.go
  internal/database/schema.json
  internal/database/schema.md
  internal/types/types.go
  migrations/frontend/1677700103_add_access_requests_decision_by_user_id_column/down.sql
  migrations/frontend/1677700103_add_access_requests_decision_by_user_id_column/metadata.yaml
  migrations/frontend/1677700103_add_access_requests_decision_by_user_id_column/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#47948 schema: Fix typo in ADO doc string
  schema/azuredevops.schema.json
  schema/schema.go
Labels: cla-signed

#48317 rbac: display roles and their permissions in UI
  client/web/src/enterprise/rbac/SiteAdminRolesPage.module.scss
  client/web/src/enterprise/rbac/SiteAdminRolesPage.story.tsx
  client/web/src/enterprise/rbac/SiteAdminRolesPage.tsx
  client/web/src/enterprise/rbac/backend.ts
  client/web/src/enterprise/rbac/components/ConfirmDeleteRoleModal.story.tsx
  client/web/src/enterprise/rbac/components/ConfirmDeleteRoleModal.tsx
  client/web/src/enterprise/rbac/components/Permissions.story.tsx
  client/web/src/enterprise/rbac/components/Permissions.tsx
  client/web/src/enterprise/rbac/components/RoleNode.module.scss
  client/web/src/enterprise/rbac/components/RoleNode.story.tsx
  client/web/src/enterprise/rbac/components/RoleNode.tsx
  client/web/src/enterprise/rbac/mock.ts
  client/web/src/enterprise/site-admin/routes.tsx
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/web/src/featureFlags/featureFlags.ts
  cmd/frontend/graphqlbackend/directives.go
  enterprise/cmd/frontend/internal/rbac/resolvers/role.go
  enterprise/cmd/frontend/internal/rbac/resolvers/roles.go
  enterprise/cmd/frontend/internal/rbac/resolvers/roles_test.go
Labels: cla-signed, rbac

#48482 search input: Refactor "focused filter" logic
  client/branded/src/search-ui/input/CodeMirrorQueryInput.module.scss
  client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
  client/branded/src/search-ui/input/codemirror/active-filter.ts
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
Labels: cla-signed

#48533 embeddings: compress indexes for storage
  enterprise/cmd/embeddings/shared/context_detection_cache.go
  enterprise/cmd/embeddings/shared/download_file.go
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/worker/internal/embeddings/contextdetection/handler.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/internal/embeddings/index_storage.go
  enterprise/internal/embeddings/index_storage_test.go
Labels: cla-signed

#48531 Packages: Remove permalink shortcut and button
  client/web/src/repo/RepoRevisionContainer.tsx
Labels: cla-signed, rfc-698, team/code-exploration, package-repos, packages-starship

#48500 SCIM: Remove unused fields from user schema
  enterprise/internal/scim/user_schema.go
Labels: cla-signed

#48534 bazel: fix gazelle lang directive
  BUILD.bazel
Labels: cla-signed, JF/bazel

#48250 Code Intel: Add global and repo-specific dashboards
  client/web/src/enterprise/batches/Branch.tsx
  client/web/src/enterprise/codeintel/badge/hooks/queries.ts
  client/web/src/enterprise/codeintel/dashboard/backend.ts
  client/web/src/enterprise/codeintel/dashboard/components/ConfigurationStateBadge.tsx
  client/web/src/enterprise/codeintel/dashboard/components/DataSummary.module.scss
  client/web/src/enterprise/codeintel/dashboard/components/DataSummary.tsx
  client/web/src/enterprise/codeintel/dashboard/components/IndexStateBadge.module.scss
  client/web/src/enterprise/codeintel/dashboard/components/IndexStateBadge.tsx
  client/web/src/enterprise/codeintel/dashboard/components/tree/DashboardTree.module.scss
  client/web/src/enterprise/codeintel/dashboard/components/tree/DashboardTree.tsx
  client/web/src/enterprise/codeintel/dashboard/components/tree/util.ts
  client/web/src/enterprise/codeintel/dashboard/constants.ts
  client/web/src/enterprise/codeintel/dashboard/hooks/useRepoCodeIntelStatus.ts
  client/web/src/enterprise/codeintel/dashboard/pages/GlobalDashboardPage.module.scss
  client/web/src/enterprise/codeintel/dashboard/pages/GlobalDashboardPage.tsx
  client/web/src/enterprise/codeintel/dashboard/pages/RepoDashboardPage.module.scss
  client/web/src/enterprise/codeintel/dashboard/pages/RepoDashboardPage.tsx
  client/web/src/enterprise/codeintel/indexes/hooks/queryCommitGraph.tsx
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
  client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx
  client/web/src/enterprise/site-admin/routes.tsx
  client/web/src/enterprise/site-admin/sidebaritems.ts
  client/wildcard/src/components/Badge/Badge.story.tsx
  client/wildcard/src/components/Badge/Badge.tsx
  client/wildcard/src/components/Badge/ProductStatusBadge.tsx
  client/wildcard/src/components/LoadingSpinner/LoadingSpinner.tsx
Labels: team/code-intelligence, cla-signed, team/language-platform, team/code-exploration, auto-index-experience

#48209 ADO: Implement user permissions sync
  enterprise/cmd/frontend/internal/auth/azureoauth/login.go
  enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
  enterprise/cmd/frontend/internal/auth/azureoauth/session.go
  enterprise/internal/authz/authz.go
  enterprise/internal/authz/authz_test.go
  enterprise/internal/authz/azuredevops/provider.go
  enterprise/internal/authz/azuredevops/provider_test.go
  internal/database/external_services.go
  internal/extsvc/azuredevops/client.go
  internal/extsvc/azuredevops/types.go
  internal/extsvc/azuredevops/users.go
  internal/oauthutil/oauth2.go
  internal/oauthutil/token.go
  internal/types/external_services.go
  schema/azuredevops.schema.json
  schema/schema.go
Labels: cla-signed, feature/permissions, ADO

#48452 servegit: introduce MaxDepth and Timeout to discovery
  dev/internal/cmd/app-discover-repos/app-discover-repos.go
  internal/service/servegit/serve.go
  internal/service/servegit/serve_test.go
  internal/service/servegit/service.go
Labels: cla-signed

#48465 internal/authz/azuredevops: Implement ValidateConnection
  enterprise/cmd/frontend/internal/auth/azureoauth/login.go
  enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
  enterprise/cmd/frontend/internal/auth/azureoauth/session.go
  enterprise/internal/authz/azuredevops/provider.go
  enterprise/internal/authz/azuredevops/provider_test.go
  internal/extsvc/azuredevops/client.go
  internal/extsvc/azuredevops/users.go
Labels: cla-signed, ADO

#48467 app: Add App outbound url params in navbar Cloud CTA
  client/shared/src/util/url.ts
  client/web/src/nav/GlobalNavbar.tsx
Labels: cla-signed, app

#48535 web: sync init of the GraphQL client
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/enterprise/EnterpriseWebApp.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/storm/app-shell-init.ts
Labels: cla-signed, team/code-exploration, storm

#48538 Fix analytics page date selector being squished
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.tsx
Labels: cla-signed, team/iam

#48547 doc: add sg start + bazel
  doc/dev/background-information/bazel.md
Labels: cla-signed, JF/bazel

#48544 Fix search result outline being cut-off
  client/branded/src/search-ui/components/ResultContainer.module.scss
Labels: cla-signed, team/code-exploration

#48548 permissions-center: fix a bug with case difference between GQL and database layer.
  internal/database/permission_sync_jobs.go
Labels: cla-signed, permissions-center

#48522 Fix enterprise search jobs sometimes not initialized in insights
  enterprise/cmd/frontend/shared/shared.go
Labels: cla-signed

#47935 doc: add a FAQ entry about updating bazelrc
  doc/dev/background-information/bazel.md
Labels: cla-signed, JF/bazel

#47263 vsce: fix content security policy config
  client/vscode/CHANGELOG.md
  client/vscode/CONTRIBUTING.md
  client/vscode/src/webview/initialize.ts
Labels: cla-signed

#48231 Implement permissions matrix for teams
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/teams.go
  cmd/frontend/graphqlbackend/teams_test.go
  cmd/frontend/graphqlbackend/user.go
  internal/database/fakedb/teams.go
  internal/database/mocks_temp.go
  internal/database/teams.go
  internal/database/teams_test.go
Labels: cla-signed

#48549 authz/azuredevops: Check enforcePermissions in NewAuthzProviders
  enterprise/internal/authz/azuredevops/provider.go
  enterprise/internal/authz/azuredevops/provider_test.go
Labels: cla-signed, ADO

#48408 Move own codebase to enterprise
  cmd/frontend/internal/search/BUILD.bazel
  cmd/frontend/internal/search/search.go
  enterprise/cmd/frontend/internal/own/BUILD.bazel
  enterprise/cmd/frontend/internal/own/init.go
  enterprise/cmd/frontend/internal/own/resolvers/BUILD.bazel
  enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go
  enterprise/internal/database/BUILD.bazel
  enterprise/internal/database/codeowners.go
  enterprise/internal/database/codeowners_test.go
  enterprise/internal/own/BUILD.bazel
  enterprise/internal/own/codeowners/BUILD.bazel
  enterprise/internal/own/codeowners/README.md
  enterprise/internal/own/codeowners/file.go
  enterprise/internal/own/codeowners/find_owners.go
  enterprise/internal/own/codeowners/find_owners_test.go
  enterprise/internal/own/codeowners/owner_types.go
  enterprise/internal/own/codeowners/parse.go
  enterprise/internal/own/codeowners/parse_test.go
  enterprise/internal/own/codeowners/repr.go
  enterprise/internal/own/codeowners/v1/BUILD.bazel
  enterprise/internal/own/codeowners/v1/buf.gen.yaml
  enterprise/internal/own/codeowners/v1/codeowners.pb.go
  enterprise/internal/own/codeowners/v1/codeowners.proto
  enterprise/internal/own/search/BUILD.bazel
  enterprise/internal/own/search/filter_job.go
  enterprise/internal/own/search/filter_job_test.go
  enterprise/internal/own/search/rules_cache.go
  enterprise/internal/own/search/select_job.go
  enterprise/internal/own/search/select_job_test.go
  enterprise/internal/own/service.go
  enterprise/internal/own/service_test.go
  enterprise/internal/own/types/BUILD.bazel
  enterprise/internal/own/types/types.go
  enterprise/internal/search/BUILD.bazel
  enterprise/internal/search/jobs.go
  internal/search/result/BUILD.bazel
  internal/search/result/owner.go
  internal/types/BUILD.bazel
  internal/types/types.go
  migrations/BUILD.bazel
Labels: cla-signed

#48556 lint: Fix unused codeintel vars
  enterprise/internal/codeintel/autoindexing/internal/store/scan.go
  enterprise/internal/codeintel/sentinel/internal/store/observability.go
  enterprise/internal/codeintel/sentinel/observability.go
  enterprise/internal/codeintel/uploads/internal/store/scan.go
  enterprise/internal/codeintel/uploads/observability.go
Labels: cla-signed

#48391 Ingest Webhooks from Azure DevOps
  client/web/src/site-admin/WebhookCreateUpdatePage.tsx
  cmd/frontend/backend/webhooks.go
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/api_test.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/webhooks/azuredevops_webhooks.go
  cmd/frontend/webhooks/webhooks.go
  cmd/frontend/webhooks/webhooks_test.go
  enterprise/cmd/frontend/internal/batches/init.go
  enterprise/cmd/frontend/internal/batches/webhooks/azuredevops.go
  enterprise/cmd/frontend/internal/batches/webhooks/webhooks.go
  internal/extsvc/azuredevops/events.go
  internal/extsvc/azuredevops/events_test.go
Labels: cla-signed

#48551 experimental search input: Remove filter field background
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
  client/branded/src/search-ui/input/experimental/Suggestions.module.scss
  client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
  client/branded/src/search-ui/input/experimental/optionRenderer.tsx
Labels: cla-signed

#48521 ranking: Do not re-process references for the same project for a single map step
  enterprise/internal/codeintel/ranking/config.go
  enterprise/internal/codeintel/ranking/internal/store/ranking.go
  enterprise/internal/codeintel/ranking/internal/store/ranking_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform, ranking

#48369 [fixes #2761] Update remote selection to prefer 'upstream' and 'origin'
  client/vscode/CHANGELOG.md
  client/vscode/src/commands/git-helpers.ts
Labels: cla-signed

#48462 permissions-center: add permissions sync jobs filters by `reason` and `state`.
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.module.scss
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
  client/web/src/site-admin/permissions-center/backend.ts
Labels: cla-signed, permissions-center

#48543 Treeview: Fix scrolling in symbol tree
  client/web/src/repo/RepoRevisionSidebarSymbolTree.tsx
  client/web/src/repo/RepoRevisionSidebarSymbols.module.scss
  client/wildcard/src/components/Tree/Tree.tsx
Labels: cla-signed, team/code-exploration

#48455 Make more fields as deprecated and explaining the newer alternatives
  client/shared/src/platform/context.ts
Labels: cla-signed, team/code-exploration, storm

#48182 own: add graphql schema and resolvers for manual codeowners files
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/graphqlbackend/own.go
  cmd/frontend/graphqlbackend/own.graphql
  cmd/frontend/graphqlbackend/repository.go
  enterprise/cmd/frontend/internal/own/init.go
  enterprise/cmd/frontend/internal/own/resolvers/codeowners_resolvers.go
  enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
  enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go
  enterprise/internal/database/codeowners.go
  enterprise/internal/database/codeowners_test.go
  enterprise/internal/own/codeowners/file.go
Labels: cla-signed

#48566 zoekt: update to sourcegraph/zoekt@a4018300b2727b72268ad18459a89c34eb4bb278
  go.mod
  go.sum
Labels: cla-signed

#48554 Proposal: simplify wording
  client/web/src/repo/blob/own/FileOwnershipPanel.tsx
Labels: cla-signed

#48563 setup-experience: add setup info to `jscontext`.
  cmd/frontend/envvar/envvar.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/site_flags.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/app/ui/handlers_test.go
Labels: backend, cla-signed, team/setup-experience, march-mvp

#48485 sentinel: Add store methods to insert and query vulnerabilities
  enterprise/internal/codeintel/sentinel/internal/store/observability.go
  enterprise/internal/codeintel/sentinel/internal/store/store.go
  enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities.go
  enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities_test.go
  enterprise/internal/codeintel/sentinel/shared/types.go
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48260 add auto_upgrade column to versions table
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1677483453_add_auto_upgrade_to_versions/down.sql
  migrations/frontend/1677483453_add_auto_upgrade_to_versions/metadata.yaml
  migrations/frontend/1677483453_add_auto_upgrade_to_versions/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#48486 sentinel: Add store methods to insert and query vulnerability matches
  enterprise/internal/codeintel/sentinel/internal/store/matches.go
  enterprise/internal/codeintel/sentinel/internal/store/matches_test.go
  enterprise/internal/codeintel/sentinel/internal/store/observability.go
  enterprise/internal/codeintel/sentinel/internal/store/store.go
  enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities_test.go
  enterprise/internal/codeintel/sentinel/shared/types.go
  go.mod
  go.sum
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48570 sentinel: Add GraphQL layer for direct object access
  cmd/frontend/graphqlbackend/codeintel.graphql
  cmd/frontend/graphqlbackend/node.go
  enterprise/cmd/frontend/internal/codeintel/resolvers.go
  enterprise/internal/codeintel/sentinel/service.go
  enterprise/internal/codeintel/sentinel/transport/graphql/iface.go
  enterprise/internal/codeintel/sentinel/transport/graphql/observability.go
  enterprise/internal/codeintel/sentinel/transport/graphql/root_resolver.go
  internal/codeintel/resolvers/all.go
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48575 sentinel: Add GraphQL layer for basic listing of vuln/vuln matches
  cmd/frontend/graphqlbackend/codeintel.graphql
  enterprise/cmd/frontend/internal/codeintel/resolvers.go
  enterprise/internal/codeintel/sentinel/service.go
  enterprise/internal/codeintel/sentinel/transport/graphql/iface.go
  enterprise/internal/codeintel/sentinel/transport/graphql/observability.go
  enterprise/internal/codeintel/sentinel/transport/graphql/root_resolver.go
  internal/codeintel/resolvers/all.go
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48552 search input: Move query validation to reusable module
  client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
  client/branded/src/search-ui/input/codemirror/diagnostics.ts
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
Labels: cla-signed

#48583 Fix GitHub pull links for blame lines
  client/web/src/repo/commit/CommitMessageWithLinks.test.tsx
  client/web/src/repo/commit/CommitMessageWithLinks.tsx
  client/web/src/repo/commit/__snapshots__/CommitMessageWithLinks.test.tsx.snap
Labels: cla-signed, team/code-exploration

#48537 Only link update if available, link changelog
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.tsx
  client/web/src/site-admin/analytics/AnalyticsOverviewPage/queries.ts
Labels: cla-signed

#48584 own: Small ingestion API fixes
  cmd/frontend/graphqlbackend/own.go
  cmd/frontend/graphqlbackend/own.graphql
  enterprise/cmd/frontend/internal/own/resolvers/codeowners_resolvers.go
  enterprise/internal/database/codeowners.go
Labels: cla-signed

#48476 app: Add app outbound url params on notebooks page
  client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
Labels: cla-signed, app

#48232 Own discoverability
  client/branded/src/components/panel/TabbedPanelContent.tsx
  client/branded/src/search-ui/components/QueryExamples.tsx
  client/branded/src/search-ui/components/useQueryExamples.tsx
  client/branded/src/search-ui/results/NoResultsPage.tsx
  client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/vscode/src/webview/search-panel/SearchResultsView.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebookPage/NotebookContent.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/repo/blob/own/FileOwnershipEntry.module.scss
  client/web/src/repo/blob/own/FileOwnershipEntry.tsx
  client/web/src/repo/blob/own/FileOwnershipPanel.module.scss
  client/web/src/repo/blob/own/FileOwnershipPanel.tsx
  client/web/src/repo/blob/panel/BlobPanel.tsx
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
  doc/own/index.md
Labels: cla-signed

#48600 permissions-center: remove unnecessary `useEffect` usage for jobs refetch.
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
Labels: cla-signed, permissions-center

#48577 SCIM: More fixes
  enterprise/internal/scim/init.go
  enterprise/internal/scim/mock_db.go
  enterprise/internal/scim/user.go
  enterprise/internal/scim/user_account_data.go
  enterprise/internal/scim/user_create.go
  enterprise/internal/scim/user_create_test.go
  enterprise/internal/scim/user_get.go
  enterprise/internal/scim/user_get_test.go
  enterprise/internal/scim/user_patch.go
  enterprise/internal/scim/user_patch_test.go
  enterprise/internal/scim/user_replace.go
  enterprise/internal/scim/user_replace_test.go
  enterprise/internal/scim/user_schema.go
  internal/database/external_accounts.go
  internal/database/mocks_temp.go
Labels: cla-signed

#48558 [feat] Read only from unified perms table if feature flag is set
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  internal/database/zoekt_repos_test.go
Labels: cla-signed, team/iam

#48604 permissions-center: fix counting jobs with search predicates.
  internal/database/permission_sync_jobs.go
  internal/database/permission_sync_jobs_test.go
Labels: cla-signed, permissions-center

#48572 azuredevops: Add client method ListAuthorizedUserOrganizations
  enterprise/internal/batches/sources/mocks_test.go
  internal/extsvc/azuredevops/client.go
  internal/extsvc/azuredevops/client_test.go
  internal/extsvc/azuredevops/testdata/golden/ListAuthorizedUserOrganizations.json
  internal/extsvc/azuredevops/testdata/vcr/ListAuthorizedUserOrganizations.yaml
  internal/extsvc/azuredevops/types.go
  internal/extsvc/azuredevops/users.go
  internal/extsvc/azuredevops/users_test.go
Labels: cla-signed, ADO

#48560 Run VSCode build on main CI again
  client/vscode/package.json
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/code-exploration

#48597 teams: Allow creator to manage team
  client/web/src/team/area/TeamProfilePage.tsx
  client/web/src/team/area/backend.ts
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/teams.go
  cmd/frontend/graphqlbackend/teams_test.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1677811663_make_team_creator_nullable/down.sql
  migrations/frontend/1677811663_make_team_creator_nullable/metadata.yaml
  migrations/frontend/1677811663_make_team_creator_nullable/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#48423 Add configurable option to wait for GitHub external rate limiter
  CHANGELOG.md
  doc/admin/external_service/github.md
  enterprise/internal/authz/github/client.go
  enterprise/internal/authz/github/github.go
  enterprise/internal/authz/github/mocks_test.go
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
  internal/extsvc/types.go
  internal/extsvc/types_test.go
  internal/ratelimit/monitor.go
  internal/repos/github.go
  internal/repos/types_test.go
Labels: cla-signed, team/iam

#48579 sentinel: Vulnerability database syncer routine
  enterprise/internal/codeintel/sentinel/config.go
  enterprise/internal/codeintel/sentinel/init.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_downloader.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_source_github.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_source_govulndb.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_source_osv.go
  enterprise/internal/codeintel/sentinel/internal/background/metrics.go
  enterprise/internal/codeintel/sentinel/internal/store/matches_test.go
  enterprise/internal/codeintel/sentinel/internal/store/store.go
  enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities.go
  enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities_test.go
  go.mod
  go.sum
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48607 permissions-center: add search form for permissions sync jobs.
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.module.scss
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
  client/web/src/site-admin/permissions-center/backend.ts
Labels: cla-signed, permissions-center

#48612 azuredevops: Support allowOrgs in azure auth provider
  enterprise/cmd/frontend/internal/auth/azureoauth/login.go
  enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
  enterprise/cmd/frontend/internal/auth/azureoauth/session.go
  enterprise/cmd/frontend/internal/auth/azureoauth/session_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, ADO

#48613 Highlighting: use more variety of colors in Scala
  docker-images/syntax-highlighter/crates/sg-syntax/queries/scala/highlights.scm
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/scala.scala
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__.__plugins.scala.snap
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__.__scala.scala.snap
Labels: cla-signed

#48620 sg: bazel command sets block until bazel build is complete before anything else.
  dev/sg/checks.go
  dev/sg/internal/run/bazel_build.go
  dev/sg/internal/run/bazel_command.go
  dev/sg/internal/run/run_bazel.go
  dev/sg/sg_run.go
  dev/sg/sg_start.go
  sg.config.yaml
Labels: cla-signed, JF/bazel

#48621 Fix not counting the number of retries on GitHub rate limit requests
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
Labels: cla-signed, team/iam

#48603 servegit: Walk has logic for using the root
  dev/internal/cmd/app-discover-repos/app-discover-repos.go
  internal/service/servegit/serve.go
Labels: cla-signed

#48618 Highlighting: improve quailty for Go
  docker-images/syntax-highlighter/crates/sg-syntax/queries/go/highlights.scm
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/golang.go
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__.__golang.go.snap
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__highlights_simple_main.snap
Labels: cla-signed

#48615 SCIM: MockDB fixes: add comment, remove function, fix next ID
  enterprise/internal/scim/mock_db.go
Labels: cla-signed

#48624 permissions-center: fix search prompt for users.
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
Labels: cla-signed, permissions-center

#48625 sg: bump github.com/moby/buildkit
  go.mod
  go.sum
Labels: sg, cla-signed

#48511 release-tool: automate src-cli release in sourcegraph major and minor releases
  dev/release/src/config.ts
  dev/release/src/git.ts
  dev/release/src/github.ts
  dev/release/src/release.ts
  dev/release/src/util.ts
  dev/release/templates/release_issue_template.md
  doc/cli/references/doc.go
Labels: cla-signed

#48623 upgrade: Fix insiders version string parsing
  cmd/frontend/graphqlbackend/site.go
  internal/database/migration/cliutil/drift_schema.go
  internal/database/migration/cliutil/multiversion.go
  internal/oobmigration/version.go
  internal/oobmigration/version_test.go
Labels: cla-signed

#48626 bzl: update buildfiles
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/internal/app/jscontext/BUILD.bazel
  cmd/frontend/webhooks/BUILD.bazel
  deps.bzl
  enterprise/cmd/embeddings/shared/BUILD.bazel
  enterprise/cmd/frontend/internal/auth/azureoauth/BUILD.bazel
  enterprise/cmd/frontend/internal/batches/webhooks/BUILD.bazel
  enterprise/cmd/frontend/internal/embeddings/resolvers/BUILD.bazel
  enterprise/cmd/frontend/internal/own/resolvers/BUILD.bazel
  enterprise/internal/authz/BUILD.bazel
  enterprise/internal/authz/azuredevops/BUILD.bazel
  enterprise/internal/codeintel/ranking/internal/store/BUILD.bazel
  enterprise/internal/codeintel/sentinel/BUILD.bazel
  enterprise/internal/codeintel/sentinel/internal/background/BUILD.bazel
  enterprise/internal/codeintel/sentinel/internal/store/BUILD.bazel
  enterprise/internal/codeintel/sentinel/shared/BUILD.bazel
  enterprise/internal/codeintel/sentinel/transport/graphql/BUILD.bazel
  enterprise/internal/embeddings/BUILD.bazel
  enterprise/internal/embeddings/background/repo/BUILD.bazel
  enterprise/internal/oobmigration/migrations/codeintel/BUILD.bazel
  enterprise/internal/scim/BUILD.bazel
  internal/database/migration/shared/BUILD.bazel
  internal/extsvc/azuredevops/BUILD.bazel
  internal/extsvc/github/BUILD.bazel
  internal/instrumentation/BUILD.bazel
  internal/ratelimit/BUILD.bazel
  internal/usagestats/BUILD.bazel
  migrations/BUILD.bazel
Labels: cla-signed

#48568 bazel: add nogo and define bodyclose linter locally
  BUILD.bazel
  WORKSPACE
  dev/linters/bodyclose/BUILD.bazel
  dev/linters/bodyclose/bodyclose.go
  dev/linters/go.mod
  dev/linters/go.sum
  doc/dev/background-information/bazel.md
  linter_deps.bzl
  nogo_config.json
Labels: cla-signed, JF/bazel

#48267 syntax highlighting: fix building grammars that require c++
  docker-images/syntax-highlighter/.cargo/config.toml
  docker-images/syntax-highlighter/.dockerignore
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Dockerfile
  docker-images/syntax-highlighter/crates/sg-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/sg-syntax/build.rs
  docker-images/syntax-highlighter/crates/sg-syntax/queries/cpp/highlights.scm
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/cpp_example.cc
Labels: team/code-intelligence, cla-signed

#48630 Treeview: Fix invalid tabIndex setting when loading from a blob view
  client/wildcard/src/components/Tree/Tree.tsx
Labels: cla-signed, team/code-exploration

#48582 sentinel: Vulnerability matcher routine
  enterprise/internal/codeintel/sentinel/config.go
  enterprise/internal/codeintel/sentinel/init.go
  enterprise/internal/codeintel/sentinel/internal/background/cve_matcher.go
  enterprise/internal/codeintel/sentinel/internal/background/metrics.go
  enterprise/internal/codeintel/sentinel/internal/store/matches.go
  enterprise/internal/codeintel/sentinel/internal/store/matches_test.go
  enterprise/internal/codeintel/sentinel/internal/store/store.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1677803354_add_vulnerability_scan_log_table/down.sql
  migrations/frontend/1677803354_add_vulnerability_scan_log_table/metadata.yaml
  migrations/frontend/1677803354_add_vulnerability_scan_log_table/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, cla-signed, team/language-platform, jobfair/sentinel

#48634 bzl: fix broken :gazelle-update-repos
  WORKSPACE
  deps.bzl
  dev/linters/bodyclose/BUILD.bazel
  linter_deps.bzl
Labels: cla-signed

#48590 Flake fix: remove timing considerations from test
  internal/search/job/jobutil/combinators_test.go
Labels: cla-signed

#48387 ranking: Update API for document ranks
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/internal/httpapi/search.go
  cmd/frontend/internal/httpapi/search_test.go
  enterprise/internal/codeintel/ranking/iface.go
  enterprise/internal/codeintel/ranking/init.go
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/codeintel/ranking/internal/store/store_test.go
  enterprise/internal/codeintel/ranking/mocks_test.go
  enterprise/internal/codeintel/ranking/service.go
  enterprise/internal/codeintel/ranking/service_test.go
  enterprise/internal/codeintel/services.go
  internal/codeintel/types/ranking.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1677716184_add_columns_for_ranking_statistics/down.sql
  migrations/frontend/1677716184_add_columns_for_ranking_statistics/metadata.yaml
  migrations/frontend/1677716184_add_columns_for_ranking_statistics/up.sql
  migrations/frontend/1677716470_add_trigger_for_ranking_statistics/down.sql
  migrations/frontend/1677716470_add_trigger_for_ranking_statistics/metadata.yaml
  migrations/frontend/1677716470_add_trigger_for_ranking_statistics/up.sql
  migrations/frontend/squashed.sql
  mockgen.test.yaml
Labels: team/code-intelligence, cla-signed, team/language-platform, ranking

#48606 add note about SYMBOLS_CACHE_DIR bug in helm charts
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#48493 Event logs query for pings
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/database/mocks_temp.go
  internal/types/types.go
Labels: cla-signed

#48622 Fix typo in insights UI
  client/web/src/enterprise/insights/components/creation-ui/insight-repo-section/use-repo-fields.ts
Labels: cla-signed

#48635 zoekt: update to sourcegraph/zoekt@120aebf6db233e5f5179f0e1223e3a7b6b70ec5c
  go.mod
  go.sum
Labels: cla-signed

#48576 Setup Wizard: Add config alerts and fix redirection
  client/web/dev/utils/create-js-context.ts
  client/web/src/Layout.tsx
  client/web/src/LegacyLayout.tsx
  client/web/src/components/externalServices/index.ts
  client/web/src/components/legacyLayoutRouteContext.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/setup-wizard/SetupWizard.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/RemoteRepositoriesStep.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/CodeHostExternalServiceAlert.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.tsx
  client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
  client/web/src/staticAppConfig.ts
Labels: cla-signed

#48598 Fix teams pages flashing 404 error on page load
  client/web/src/team/TeamsArea.tsx
Labels: cla-signed

#48638 symbols: fix regression where old env var names were not respected
  CHANGELOG.md
  cmd/symbols/types/types.go
Labels: cla-signed

#48629 Simplify automating batch changes in-app changelog for release
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
  client/web/src/enterprise/batches/list/BatchChangesListIntro.module.scss
  client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Labels: cla-signed

#47390 codeintel(resolvers): Temporarily duplicate gqlhelpers to remove dependency on cmd/frontend
  cmd/frontend/enterprise/BUILD.bazel
  cmd/frontend/internal/httpapi/BUILD.bazel
  deps.bzl
  enterprise/internal/codeintel/autoindexing/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/autoindexing/transport/graphql/utils.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/utils_test.go
  enterprise/internal/codeintel/codenav/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/codenav/transport/graphql/gitblob_lsif_data_resolver_test.go
  enterprise/internal/codeintel/policies/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/policies/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/ranking/BUILD.bazel
  enterprise/internal/codeintel/shared/resolvers/BUILD.bazel
  enterprise/internal/codeintel/shared/resolvers/indexes_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/uploads/transport/graphql/utils_test.go
  internal/codeintel/resolvers/BUILD.bazel
  internal/codeintel/resolvers/all.go
  internal/codeintel/resolvers/hack.go
  internal/codeintel/types/BUILD.bazel
  migrations/BUILD.bazel
Labels: cla-signed

#48640 Remove flaky table test from event logs
  internal/database/event_logs_test.go
Labels: cla-signed

#48644 Scj/update helm version for hotfix in charts
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed
