Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-09, with the labels that each got.

#56305 grpc: Stream patch data in gitserver to avoid exceeding maximum message size
  cmd/gitserver/server/server_grpc.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
Labels: cla-signed, backport 5.1

#56299 Trufflehog as Github Action Check
  .github/workflows/container-scanning.yml
  .github/workflows/trufflehog.yml
Labels: cla-signed

#56327 Use env var for token
  dev/update-embeddings-list/src/index.ts
Labels: cla-signed

#56016 codygateway: Fix -1 resolvedStatusCode value
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
Labels: cla-signed

#56326 Fix GitLab project name with new navigation enabled
  client/browser/src/shared/code-hosts/gitlab/scrape.ts
Labels: cla-signed

#56329 Regenerate schema.go
  schema/schema.go
Labels: cla-signed

#55733 batches: change chevrons from up/down to down/right
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
  client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
Labels: cla-signed, team/iam

#56239 Revert progress made on "Enhanced admin onboarding"
  client/http-client/src/graphql/types.ts
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/global/GlobalAlerts.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/regression/util/api.ts
  client/web/src/setup-wizard/SetupWizard.test.tsx
  client/web/src/setup-wizard/__snapshots__/SetupWizard.test.tsx.snap
  client/web/src/site-admin/SiteAdminConfigurationPage.module.scss
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
  client/web/src/site-admin/SiteConfigurationChangeList.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/notifications/NotificationsNavbarItem.module.scss
  client/web/src/site-admin/notifications/NotificationsNavbarItem.tsx
  client/web/src/site-admin/notifications/hooks/useNotifications.tsx
  client/web/src/site-admin/routes.tsx
  client/web/src/site-admin/setup-checklist/hooks/useSetupChecklist.tsx
  client/web/src/site-admin/site-config/ConfigPanel.tsx
  client/web/src/site-admin/site-config/SiteAdminConfigurationPage.tsx
  client/web/src/site-admin/site-config/forms/external-url/index.tsx
  client/web/src/site-admin/site-config/forms/license/index.tsx
  client/web/src/site-admin/site-config/forms/smtp/SendTestEmailForm.tsx
  client/web/src/site-admin/site-config/forms/smtp/index.tsx
  client/web/src/site-admin/site-config/hooks/useJsoncParser.test.ts
  client/web/src/site-admin/site-config/hooks/useJsoncParser.ts
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/license.go
  cmd/frontend/graphqlbackend/license.graphql
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/send_test_email.go
  cmd/frontend/graphqlbackend/send_test_email_test.go
  cmd/frontend/graphqlbackend/site_alerts.go
  cmd/frontend/graphqlbackend/site_alerts_test.go
  enterprise/cmd/frontend/internal/auth/BUILD.bazel
  enterprise/cmd/frontend/internal/auth/init.go
  enterprise/cmd/frontend/internal/auth/init_test.go
  enterprise/cmd/frontend/internal/authz/init.go
  enterprise/cmd/frontend/internal/licensing/resolvers/resolvers.go
  internal/conf/validate_custom.go
  internal/licensing/BUILD.bazel
  internal/licensing/data.go
  internal/licensing/features.go
  internal/licensing/licensing.go
  internal/txemail/txemail.go
  lib/pointers/ptr.go
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/iam

#56330 auth: Check provider account creation date
  enterprise/cmd/frontend/internal/auth/githuboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/login.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session_test.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/user.go
  internal/authz/providers/gitlab/common_test.go
  internal/authz/providers/gitlab/sudo.go
  internal/authz/providers/gitlab/sudo_test.go
  internal/extsvc/gitlab/mock.go
  internal/extsvc/gitlab/user.go
  internal/extsvc/gitlab/users.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#56332 Fix up external creation date changes
  enterprise/cmd/frontend/internal/auth/githuboauth/session.go
  enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#56337 docs: Cover gotcha for SCIP indexers implemented in C++
  doc/code_navigation/explanations/writing_an_indexer.md
Labels: cla-signed

#56308 searchjobs: hook up graphql CreateSearchJob and NodeResolvers
  enterprise/cmd/frontend/internal/search/BUILD.bazel
  enterprise/cmd/frontend/internal/search/init.go
  enterprise/cmd/frontend/internal/search/resolvers/BUILD.bazel
  enterprise/cmd/frontend/internal/search/resolvers/resolver.go
  enterprise/cmd/frontend/internal/search/resolvers/search_job.go
  internal/search/exhaustive/service/BUILD.bazel
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/store/BUILD.bazel
  internal/search/exhaustive/store/exhaustive_search_jobs.go
  internal/search/exhaustive/store/exhaustive_search_jobs_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_jobs.go
  internal/search/exhaustive/store/exhaustive_search_repo_jobs_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs_test.go
  internal/search/exhaustive/store/store.go
  internal/search/exhaustive/store/store_test.go
  internal/search/exhaustive/types/worker.go
Labels: cla-signed

#56322 searchjobs: implement exhaustive search worker
  enterprise/cmd/worker/internal/search/BUILD.bazel
  enterprise/cmd/worker/internal/search/exhaustive_search.go
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  enterprise/cmd/worker/internal/search/job.go
  internal/search/exhaustive/store/exhaustive_search_repo_jobs.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
Labels: cla-signed

#56309 searchjobs: PoC of listing search jobs
  enterprise/cmd/frontend/internal/search/resolvers/resolver.go
  enterprise/cmd/frontend/internal/search/resolvers/search_jobs_connection.go
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/store/BUILD.bazel
  internal/search/exhaustive/store/exhaustive_search_jobs.go
  internal/search/exhaustive/store/store.go
Labels: cla-signed

#56328 searchjob: refactor worker job to be e2e testable
  enterprise/cmd/worker/internal/search/BUILD.bazel
  enterprise/cmd/worker/internal/search/exhaustive_search.go
  enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
  enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision.go
  enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision_test.go
  enterprise/cmd/worker/internal/search/exhaustive_search_repo_test.go
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  enterprise/cmd/worker/internal/search/job.go
Labels: cla-signed

#56347 JetBrains: Cody: Removing autocomplete when esc pressed using IdeaVIM…
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.java
  client/jetbrains/src/main/java/com/sourcegraph/common/EditorUtils.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/editor/CommandListener.kt
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#56334 JetBrains: ensure nonnull line separator method can't return a null
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Labels: cla-signed

#56352 actor: ID bugfix
  internal/actor/http.go
  internal/completions/client/client.go
Labels: cla-signed

#56354 bumped trufflehog version to v3.54.3
  .github/workflows/trufflehog.yml
Labels: cla-signed

#56353 docs: add gcp private code host support
  doc/cloud/index.md
  doc/cloud/private_connectivity_aws.md
  doc/cloud/private_connectivity_gcp.md
Labels: cla-signed

#56356 actor: alternative fix (revert #56352)
  internal/completions/client/client.go
  internal/completions/client/codygateway/BUILD.bazel
  internal/completions/client/codygateway/codygateway.go
Labels: cla-signed

#56357 Update kubernetes.md
  CHANGELOG.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#56348 search jobs: remove constraint
  internal/database/schema.json
  internal/database/schema.md
  internal/search/exhaustive/store/exhaustive_search_jobs_test.go
  migrations/BUILD.bazel
  migrations/frontend/1693825517_exhaustive_search_jobs_remove_constraint/down.sql
  migrations/frontend/1693825517_exhaustive_search_jobs_remove_constraint/metadata.yaml
  migrations/frontend/1693825517_exhaustive_search_jobs_remove_constraint/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#56359 search-blitz: run list-tags in build help output
  internal/cmd/search-blitz/scripts/build.sh
Labels: cla-signed

#56228 SGM-6462 - Add About Sourcegraph CTA to main nav in dotcom
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  junit.xml
Labels: gitstart, cla-signed, team/frontend-platform

#56271 Improve and update Cody VS Code extension setup guide
  doc/_resources/assets/redirects
  doc/cody/capabilities.md
  doc/cody/overview/install-vscode.md
Labels: docs, cla-signed

#56367 graphqlbackend: replicate validation to backend for post signup flow
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: cla-signed

#56291 Improve and update Cody desktop app setup guide
  doc/cody/overview/app/index.md
Labels: docs, cla-signed

#56343 source: update profile link for github
  client/web/src/user/settings/auth/ExternalAccount.tsx
  internal/extsvc/github/common.go
Labels: cla-signed

#56351 search jobs: implement exhaustiveSearchRepoHandler
  enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  enterprise/cmd/worker/internal/search/job.go
Labels: cla-signed

#56383 sveltekit: Fix error when rendering repo search results
  client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
Labels: cla-signed

#56368 Add 3 GIFs to Cody capabilities
  doc/cody/capabilities.md
Labels: cla-signed

#56390 docs: fix link to Bazel cheat sheet
  doc/dev/background-information/bazel/intro.md
Labels: cla-signed, team/iam

#56391 JetBrains: customize autocomplete color new branch
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/AutocompleteRenderUtils.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/CodyAutocompleteElementRenderer.java
  client/jetbrains/src/main/java/com/sourcegraph/config/CodyApplicationService.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
Labels: cla-signed

#56229 JetBrains: Rename "recipes" to "commands" in docs and UI
  client/jetbrains/README.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Labels: cla-signed

#56392 populate monitors_enabled field
  internal/usagestats/code_monitoring.go
  internal/usagestats/code_monitoring_test.go
  internal/usagestats/code_monitoring_usage_stats.sql
Labels: cla-signed

#56394 httpapi/auth: use audit logs for user errors
  cmd/frontend/internal/httpapi/auth.go
Labels: cla-signed

#56361 search jobs: implement exhaustiveSearchRepoRevHandler
  enterprise/cmd/worker/internal/search/BUILD.bazel
  enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
  enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision.go
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  enterprise/cmd/worker/internal/search/job.go
  internal/search/exhaustive/service/BUILD.bazel
  internal/search/exhaustive/service/search.go
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
  internal/search/exhaustive/types/BUILD.bazel
  internal/search/exhaustive/types/exhaustive_search.go
Labels: cla-signed

#56400 changelog catchup
  CHANGELOG.md
Labels: cla-signed

#56404 Update add Global service account token instructions
  doc/batch_changes/how-tos/configuring_credentials.md
Labels: cla-signed

#56401 httpapi/graphql: add error wrapping to graphql serving
  cmd/frontend/internal/handlerutil/BUILD.bazel
  cmd/frontend/internal/handlerutil/error_reporting.go
  cmd/frontend/internal/handlerutil/handler.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/graphql.go
  cmd/frontend/internal/httpapi/httpapi.go
  deps.bzl
  go.mod
  go.sum
  internal/trace/httptrace.go
Labels: cla-signed

#56405 release: sourcegraph@5.1.8
  cmd/migrator/BUILD.bazel
  cmd/migrator/generate.sh
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/updatecheck/handler.go
Labels: cla-signed

#56406 close 5.1.8 release
  dev/release/release-config.jsonc
Labels: cla-signed

#56407 add changelog section for 5.1.9
  CHANGELOG.md
Labels: cla-signed

#56398 search job: remove redundant db checks in test
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
Labels: cla-signed

#55748 source: add query for retrieving gitserver information
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/apitest/types.go
  cmd/frontend/graphqlbackend/gitserver.go
  cmd/frontend/graphqlbackend/gitserver_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/graphqlbackend/permission_test.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/settings_subject.go
  cmd/gitserver/server/BUILD.bazel
  cmd/gitserver/server/disk.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_grpc.go
  internal/batches/sources/mocks_test.go
  internal/diskusage/BUILD.bazel
  internal/diskusage/diskusage.go
  internal/diskusage/diskusage_test.go
  internal/gitserver/BUILD.bazel
  internal/gitserver/addrs.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
Labels: cla-signed

#56415 exhaustive search store: refactor scanning
  internal/search/exhaustive/store/exhaustive_search_jobs.go
Labels: cla-signed, team/iam

#56418 exhaustive search store: refactoring 2 - return of the scan helpers (and also: unit test & cleanup)
  internal/search/exhaustive/store/BUILD.bazel
  internal/search/exhaustive/store/exhaustive_search_jobs_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_jobs_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs_test.go
  internal/search/exhaustive/store/store_test.go
Labels: cla-signed, team/iam

#56420 bzl: update sha256 for ctags
  dev/tool_deps.bzl
Labels: cla-signed

#56385 source: improvement to user management date selector
  client/web/src/site-admin/UserManagement/components/DateRangeSelect.tsx
Labels: cla-signed

#56429 Add temporary logging to dotcom sudo handler
  cmd/frontend/internal/httpapi/auth.go
  internal/authz/BUILD.bazel
  internal/authz/header.go
  internal/authz/header_test.go
Labels: cla-signed

#56431 Resolve sudo error for empty token header
  internal/authz/header.go
  internal/authz/header_test.go
Labels: cla-signed, SSDLC

#56435 Update health checks docs to include instance version in response
  doc/admin/observability/health_checks.md
Labels: cla-signed

#56430 grpc: otelgrpc: upgrade to v0.43.0
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, backport 5.1

#56439 ci/wolfi: upgrade packages and images build deps
  enterprise/dev/ci/scripts/wolfi/build-base-image.sh
  enterprise/dev/ci/scripts/wolfi/build-package.sh
Labels: cla-signed, backport 5.1

#56442 feature-flag: support disallow unlink external accounts
  cmd/frontend/graphqlbackend/external_accounts.go
Labels: cla-signed

#56413 codeintel: Make update-sha script more flexible
  internal/codeintel/autoindexing/internal/inference/libs/update-shas.sh
Labels: cla-signed

#56414 chore: Bump autoindexing image SHAs
  internal/codeintel/autoindexing/internal/inference/libs/indexes.go
Labels: cla-signed

#56422 searchjobs: factor out newSearcher test logic
  internal/search/exhaustive/service/BUILD.bazel
  internal/search/exhaustive/service/search_test.go
Labels: cla-signed

#56419 JetBrains: manually construct server url to fix any issues with it
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SourcegraphServerPath.kt
  client/jetbrains/src/test/kotlin/com/sourcegraph/cody/config/SourcegraphServerPathTest.kt
Labels: cla-signed

#56454 JetBrains: make accounts panel smaller
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
Labels: cla-signed

#56365 search jobs: implement Resolver.CancelSearchJob
  enterprise/cmd/frontend/internal/search/resolvers/resolver.go
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/store/exhaustive_search_jobs.go
  internal/search/exhaustive/store/store.go
Labels: cla-signed

#56411 JetBrains: Cody: Allow to enable/disable autocomplete per-language
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
  client/jetbrains/src/main/java/com/sourcegraph/common/EditorUtils.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AutoCompleteLanguageTableWrapper.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AutocompleteLanguageTable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyApplicationSettings.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/LanguageCheckboxColumn.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/LanguageEntry.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/LanguageEntryColumn.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsModel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyLanguageUtil.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CollectionUtil.kt
Labels: cla-signed

#56276 source: surface disk info for gitservers UI
  client/web/BUILD.bazel
  client/web/src/enterprise/batches/BatchSpecNode.tsx
  client/web/src/enterprise/batches/utils/size.ts
  client/web/src/site-admin/SiteAdminGitservers.story.tsx
  client/web/src/site-admin/SiteAdminGitserversPage.module.scss
  client/web/src/site-admin/SiteAdminGitserversPage.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/routes.tsx
  client/web/src/site-admin/sidebaritems.ts
  client/web/src/util/size.test.ts
  client/web/src/util/size.ts
Labels: cla-signed

#56470 searcher: always do hybrid search
  cmd/searcher/internal/search/hybrid_test.go
  cmd/searcher/internal/search/search.go
  cmd/searcher/internal/search/search_test.go
  cmd/searcher/protocol/searcher.go
Labels: cla-signed

#56452 JetBrains: stop logging `completion:started` events
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Labels: cla-signed

#56471 dbconn: wrap did not start error
  internal/database/dbconn/open.go
Labels: cla-signed

#56463 search jobs: add blobstore
  enterprise/cmd/frontend/internal/search/BUILD.bazel
  enterprise/cmd/frontend/internal/search/init.go
  enterprise/cmd/frontend/shared/service.go
  enterprise/cmd/worker/internal/search/BUILD.bazel
  enterprise/cmd/worker/internal/search/job.go
  internal/search/exhaustive/uploadstore/BUILD.bazel
  internal/search/exhaustive/uploadstore/store.go
  sg.config.yaml
Labels: cla-signed

#56472 dbtest: mention bazel tag needed when we don't connect to DB
  internal/database/dbtest/dbtest.go
Labels: cla-signed

#56447 app: Move out of enterprise and merge with cmd/sourcegraph-oss
  .gitignore
  .vscode/launch.json
  cmd/blobstore/BUILD.bazel
  cmd/blobstore/main.go
  cmd/frontend/BUILD.bazel
  cmd/frontend/main.go
  cmd/github-proxy/BUILD.bazel
  cmd/github-proxy/github-proxy.go
  cmd/gitserver/BUILD.bazel
  cmd/gitserver/main.go
  cmd/precise-code-intel-worker/BUILD.bazel
  cmd/precise-code-intel-worker/main.go
  cmd/repo-updater/BUILD.bazel
  cmd/repo-updater/main.go
  cmd/searcher/BUILD.bazel
  cmd/searcher/main.go
  cmd/sourcegraph-oss/BUILD.bazel
  cmd/sourcegraph-oss/main.go
  cmd/sourcegraph-oss/osscmd/BUILD.bazel
  cmd/sourcegraph/BUILD.bazel
  cmd/sourcegraph/README.md
  cmd/sourcegraph/main.go
  cmd/sourcegraph/osscmd/BUILD.bazel
  cmd/sourcegraph/osscmd/osscmd.go
  cmd/symbols/BUILD.bazel
  cmd/symbols/main.go
  cmd/worker/BUILD.bazel
  cmd/worker/main.go
  dev/check/go-dbconn-import.sh
  enterprise/cmd/embeddings/BUILD.bazel
  enterprise/cmd/embeddings/main.go
  enterprise/cmd/sourcegraph/enterprisecmd/BUILD.bazel
  enterprise/cmd/sourcegraph/enterprisecmd/enterprisecmd.go
  enterprise/cmd/sourcegraph/enterprisecmd/executorcmd/executorcmd.go
  enterprise/cmd/symbols/BUILD.bazel
  enterprise/cmd/symbols/main.go
  enterprise/cmd/worker/BUILD.bazel
  enterprise/cmd/worker/main.go
  enterprise/dev/app/build-backend.sh
  enterprise/dev/app/build-windows.sh
  internal/service/svcmain/svcmain.go
  sg.config.yaml
  src-tauri/README.md
Labels: cla-signed

#56449 Move executor-kubernetes out of enterprise
  cmd/executor-kubernetes/BUILD.bazel
  cmd/executor-kubernetes/image_test.yaml
  cmd/executor/kubernetes/README.md
  sg.config.yaml
Labels: cla-signed

#56451 Remove self from CODENOTIFY/OWNERS
  .github/test.CODEOWNERS
  client/web/src/enterprise/batches/CODENOTIFY
  client/web/src/integration/CODENOTIFY
  cmd/frontend/graphqlbackend/CODENOTIFY
  doc/batch_changes/CODENOTIFY
Labels: cla-signed

#56474 github source: tiny refactor to make `paginate` a function
  internal/repos/github.go
Labels: cla-signed, team/iam

#56448 ci/wolfi: fix building base image
  enterprise/dev/ci/scripts/wolfi/build-base-image.sh
Labels: cla-signed, backport 5.1

#56426 wolfi-images: update mi2 base image
  wolfi-images/cloud-mi2.yaml
  wolfi-packages/gke-gcloud-auth-plugin.yaml
  wolfi-packages/terraform.yaml
Labels: cla-signed

#56403 repos, codemonitors: remove duplicate error logging
  internal/codemonitors/background/workers.go
  internal/repos/syncer.go
Labels: cla-signed

#56477 [Backport 5.1] ci/wolfi: fix building base image (#56448)
  enterprise/dev/ci/scripts/wolfi/build-base-image.sh
Labels: cla-signed

#56479 Update /fix command to /edit in Cody docs
  doc/cody/capabilities.md
  doc/cody/use-cases.md
Labels: cla-signed

#56437 JetBrains: Update README
  client/jetbrains/README.md
Labels: cla-signed

#56408 Wildcard Adjust exhaustive search creation alert banner styles
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.module.scss
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
  client/branded/src/search-ui/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
  client/wildcard/src/components/Alert/Alert.module.scss
  client/wildcard/src/components/Alert/Alert.story.tsx
  client/wildcard/src/components/Alert/Alert.tsx
Labels: cla-signed

#56369 [Exhaustive Search] Add search jobs list page
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/LegacyRouteContext.tsx
  client/web/src/components/ZeroStates/ListPageZeroState.module.scss
  client/web/src/components/ZeroStates/ListPageZeroState.tsx
  client/web/src/enterprise/app/components/index.ts
  client/web/src/enterprise/app/components/zero-states/AppZeroStates.module.scss
  client/web/src/enterprise/app/components/zero-states/AppZeroStates.tsx
  client/web/src/enterprise/routes.tsx
  client/web/src/enterprise/search-jobs/SearchJobsPage.module.scss
  client/web/src/enterprise/search-jobs/SearchJobsPage.story.tsx
  client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
  client/web/src/enterprise/search-jobs/UsersPicker.module.scss
  client/web/src/enterprise/search-jobs/UsersPicker.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/routes.constants.ts
  client/wildcard/src/components/Combobox/Combobox.module.scss
  client/wildcard/src/components/Combobox/MultiCombobox.module.scss
  client/wildcard/src/components/Combobox/MultiCombobox.tsx
Labels: webapp, cla-signed

#56487 [backport 5.1] gRPC: use byte slices for exec args (#55990)
  cmd/gitserver/server/server_grpc.go
  cmd/gitserver/server/server_test.go
  internal/gitserver/client.go
  internal/gitserver/commands_test.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: cla-signed

#56039 cody web: provide suggestions in context selector
  .gitignore
  client/web/BUILD.bazel
  client/web/package.json
  client/web/src/LegacyLayout.tsx
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/components/ChatUI/ChatUi.tsx
  client/web/src/cody/components/CodeMirrorEditor.ts
  client/web/src/cody/components/FileContentEditor.ts
  client/web/src/cody/components/GettingStarted.module.scss
  client/web/src/cody/components/GettingStarted.tsx
  client/web/src/cody/components/RepoContainerEditor.ts
  client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
  client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
  client/web/src/cody/components/ScopeSelector/backend.ts
  client/web/src/cody/components/ScopeSelector/useRepoSuggestions.ts
  client/web/src/cody/sidebar/CodySidebar.tsx
  client/web/src/cody/sidebar/Provider.tsx
  client/web/src/cody/useCodyChat.tsx
  client/web/src/components/useUserHistory.ts
  client/web/src/repo/RepoContainer.tsx
  client/web/src/routes.tsx
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
  pnpm-lock.yaml
Labels: cla-signed, cody, cody/web, cody/context-selector

#56360 Redirect to a specified returnTo path after the post-sign-up survey
  client/web/src/auth/PostSignUpPage.test.tsx
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/auth/SignInSignUpCommon.tsx
  client/web/src/auth/__snapshots__/PostSignUpPage.test.tsx.snap
  client/web/src/marketing/toast/CodySurveyToast.tsx
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed

#55745 codeintel: prioritize manual autoindexing jobs
  deps.bzl
  go.mod
  go.sum
  internal/codeintel/autoindexing/internal/background/dependencies/BUILD.bazel
  internal/codeintel/autoindexing/internal/background/dependencies/index_worker_store_test.go
  internal/codeintel/autoindexing/internal/background/dependencies/utils.go
  internal/codeintel/autoindexing/internal/store/BUILD.bazel
  internal/codeintel/autoindexing/internal/store/enqueuer.go
  internal/codeintel/autoindexing/internal/store/enqueuer_test.go
  internal/codeintel/uploads/internal/store/indexes.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/internal/store/summary.go
  internal/codeintel/uploads/shared/types.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1691595214_autoindexing_manual_priority/down.sql
  migrations/frontend/1691595214_autoindexing_manual_priority/metadata.yaml
  migrations/frontend/1691595214_autoindexing_manual_priority/up.sql
  migrations/frontend/1691759644_autoindexing_manual_priority_index/down.sql
  migrations/frontend/1691759644_autoindexing_manual_priority_index/metadata.yaml
  migrations/frontend/1691759644_autoindexing_manual_priority_index/up.sql
  migrations/frontend/squashed.sql
Labels: team/code-intelligence, auto-index, cla-signed, team/language-platform, auto-index-experience

#56491 Remove unnecessary test for GET request in GH V4 client
  internal/extsvc/github/v4_test.go
Labels: cla-signed, team/iam

#56478 github: fix erratic 404s by keeping URL stable
  CHANGELOG.md
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
  internal/extsvc/github/v4.go
  internal/extsvc/github/v4_test.go
Labels: cla-signed, backport 5.1, team/iam

#56425 source: copy go-disk-usage lib
  cmd/gitserver/server/BUILD.bazel
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/servermetrics.go
  deps.bzl
  go.mod
  go.sum
  internal/diskusage/diskusage.go
  internal/metrics/BUILD.bazel
  internal/metrics/metrics.go
Labels: cla-signed

#56480 source: return full repository when fetching public github repos
  internal/repos/github.go
Labels: cla-signed

#56496 update changelog
  CHANGELOG.md
Labels: cla-signed

#56495 backport: github: fix erratic 404s by keeping URL stable (#56478)
  CHANGELOG.md
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
  internal/extsvc/github/v4.go
  internal/extsvc/github/v4_test.go
Labels: cla-signed, backports, team/iam

#56492 Add feature flags to perms syncer context
  CHANGELOG.md
  cmd/repo-updater/internal/authz/BUILD.bazel
  cmd/repo-updater/internal/authz/integration_test.go
  cmd/repo-updater/internal/authz/perms_syncer.go
  cmd/repo-updater/internal/authz/testdata/vcr/TestIntegration_GitLabPermissions/test_gitLabProjectVisibilityExperimental_feature_flag.yaml
  internal/authz/providers/gitlab/authz.go
  internal/authz/providers/gitlab/oauth.go
Labels: cla-signed, backport 5.1, team/iam

#56493 JetBrains: add ability to edit account from context menu
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AddCodyAccountWithTokenAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/BaseLoginDialog.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginRequest.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/AccountsPanelFactoryExtensions.kt
Labels: cla-signed

#56264 JetBrains: forward SOCKS `proxy` setting to agent
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/ExtensionConfiguration.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
Labels: cla-signed

#56263 JetBrains: update CONTRIBUTING.md docs to mention steps to use unstable-codegen through a proxy
  client/jetbrains/CONTRIBUTING.md
Labels: cla-signed

#56473 JetBrains: Cody: Allow manual autocomplete to be triggered even when implicit completions are disabled
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyCompatibility.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutocompleteAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteActionHandler.kt
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/TriggerAutocompleteAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/editor/EditorUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/common/EditorUtils.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/editor/CommandListener.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyLanguageUtil.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyProjectUtil.kt
Labels: cla-signed

#56500 chore: Bump autoindexing image SHAs
  internal/codeintel/autoindexing/internal/inference/libs/indexes.go
Labels: cla-signed

#56486 sg: Fixup monitoring stack
  dev/postgres_exporter.sh
  sg.config.yaml
Labels: cla-signed

#56483 Don't configure empty dummy authz providers in OSS apps
  cmd/sourcegraph/osscmd/BUILD.bazel
  cmd/sourcegraph/osscmd/osscmd.go
Labels: cla-signed

#56446 Merge enterprise and non-enterprise server images
  cmd/server/BUILD.bazel
  cmd/server/image_test.yaml
  cmd/server/image_tests/BUILD.bazel
  cmd/server/image_tests/test_packages.sh
  cmd/server/image_tests/test_services.sh
  cmd/server/image_tests/test_zoekt.sh
  cmd/server/main.go
  cmd/server/shared/shared.go
  doc/dev/background-information/bazel/server_integration_tests.md
  enterprise/.gitignore
  enterprise/cmd/server/BUILD.bazel
  enterprise/cmd/server/README.md
  enterprise/cmd/server/docker.go
  enterprise/cmd/server/image_test.yaml
  enterprise/cmd/server/main.go
  enterprise/dev/ci/internal/ci/bazel_operations.go
  testing/BUILD.bazel
  testing/defs.bzl
Labels: cla-signed

#56389 bzl: wrap migrations schemas/describe scripts
  .aspect/bazelrc/ci.sourcegraph.bazelrc
  .github/workflows/sg-setup.yml
  dev/migrations.bzl
  dev/sg/dependencies/BUILD.bazel
  dev/sg/dependencies/helpers.go
  dev/sg/dependencies/mac.go
  docker-images/postgres-12-alpine/BUILD.bazel
  docker-images/postgres-12-alpine/rootfs/BUILD.bazel
  internal/database/BUILD.bazel
  migrations/BUILD.bazel
  migrations/codeinsights/BUILD.bazel
  migrations/codeintel/BUILD.bazel
  migrations/frontend/BUILD.bazel
Labels: cla-signed

#56506 JetBrains: Cody: disable autocomplete with IdeaVIM visual mode
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
Labels: cla-signed

#56509 source: properly display size in terabytes
  client/web/src/util/size.test.ts
  client/web/src/util/size.ts
Labels: cla-signed

#56514 grpc: gitserver: exec: change EnsureRevision field to be bytes instead of string
  cmd/gitserver/server/server_grpc.go
  internal/gitserver/client.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: cla-signed, backport 5.1

#56490 docs: Tweak examples & describe IndexJob fields
  doc/code_navigation/references/auto_indexing_configuration.md
  doc/code_navigation/references/inference_configuration.md
  internal/codeintel/autoindexing/internal/store/config_inference.go
Labels: cla-signed

#56489 Add custom Cody commands documentation
  doc/cody/custom-commands.md
  doc/sidebar.md
Labels: cla-signed

#56531 JetBrains: Just use \n
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Labels: cla-signed

#56513 JetBrains: update contributing docs
  client/jetbrains/CONTRIBUTING.md
Labels: cla-signed

#56533 JetBrains: release 3.1.0-alpha.4
  client/jetbrains/gradle.properties
Labels: cla-signed

#56505 JetBrains: clear last autocomplete candidate after acceptance
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutocompleteAction.java
Labels: cla-signed

#56535 Delve for all packages
  sg.config.yaml
Labels: cla-signed

#56536 Access tokens: add URL search parameter to control default description
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
Labels: cla-signed

#56539 JetBrains: fix unstable IntelliJ public API changes
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/Account.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/AccountDetails.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/AccountManager.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/AccountManagerBase.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/AccountsListener.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/AccountsRepository.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/PersistentDefaultAccountHolder.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ServerAccount.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ServerPath.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/SingleValueModel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/AccountsDetailsProvider.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/AccountsListModel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/AccountsListModelBase.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/AccountsPanelFactoryExtensions.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/LoadingAccountsDetailsProvider.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/SimpleAccountsListCellRenderer.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CachingCodyUserAvatarLoader.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountDetails.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountDetailsProvider.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountManager.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyCredentialsUi.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginPanel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyPersisentAccounts.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyProjectDefaultAccountHolder.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyTokenCredentialsUi.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SourcegraphServerPath.kt
Labels: cla-signed

#56515 JetBrains: update autocomplete provider list and default to null
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteProviderType.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
Labels: cla-signed

#56540 JetBrains: Fix formatting
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Labels: cla-signed

#56532 JetBrains: add link to generate new token
  client/jetbrains/src/main/java/com/sourcegraph/common/BrowserErrorNotification.java
  client/jetbrains/src/main/java/com/sourcegraph/common/BrowserOpener.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginPanel.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyTokenCredentialsUi.kt
Labels: cla-signed

#56541 JetBrains: document `auth` package
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/package.md
Labels: cla-signed

#56523 go: Upgrade to 1.20.8
  .github/workflows/sg-setup.yml
  .tool-versions
  WORKSPACE
  dev/sg/checks.go
Labels: cla-signed

#56524 cody: Apply config fix
  .vscode/cody.json
Labels: cla-signed

#56545 Fix GetPublicExternalAccountData panicing with empty fields
  cmd/frontend/graphqlbackend/external_account_data_resolver.go
  cmd/frontend/graphqlbackend/external_account_data_resolver_test.go
  cmd/frontend/graphqlbackend/teams.go
  cmd/frontend/internal/auth/httpheader/provider.go
  cmd/frontend/internal/auth/openidconnect/BUILD.bazel
  cmd/frontend/internal/auth/openidconnect/user.go
  cmd/frontend/internal/auth/openidconnect/user_test.go
  cmd/frontend/internal/auth/saml/user.go
  cmd/frontend/internal/auth/saml/user_test.go
  internal/extsvc/azuredevops/users.go
  internal/extsvc/bitbucketcloud/user.go
  internal/extsvc/gerrit/account.go
  internal/extsvc/github/common.go
  internal/extsvc/gitlab/user.go
  internal/extsvc/types.go
  internal/own/BUILD.bazel
  internal/own/ownref.go
  internal/own/ownref_test.go
Labels: cla-signed, team/iam

#56547 bzl: suppress an irrelevant warning from gazelle
  migrations/BUILD.bazel
Labels: cla-signed

#56499 dev: add a pre-commit hook to searches for tokens
  .pre-commit-config.yaml
  .tool-versions
  dev/check-tokens.sh
  dev/sg/dependencies/dependencies.go
  dev/sg/dependencies/helpers.go
  dev/sg/dependencies/shared.go
  dev/sg/sg_setup.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#55561 Fix issue of gerrit response being trimmed when they didn't need to be
  internal/extsvc/gerrit/BUILD.bazel
  internal/extsvc/gerrit/client.go
  internal/extsvc/gerrit/client_test.go
Labels: cla-signed, team/source

#56525 zoekt: update to 3ce1f2b24c80b3dea89d237600d2b0879342ed1b
  deps.bzl
  doc/admin/observability/dashboards.md
  go.mod
  go.sum
  internal/search/backend/BUILD.bazel
  internal/search/backend/grpc.go
  internal/search/backend/zoekt.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/searcher.go
  monitoring/definitions/shared/grpc.go
  monitoring/definitions/symbols.go
  monitoring/definitions/zoekt.go
Labels: cla-signed, backport 5.1

#56552 updating wolfi images for realease 5.1.9
  wolfi-images/batcheshelper.yaml
  wolfi-images/blobstore.yaml
  wolfi-images/bundled-executor.yaml
  wolfi-images/cadvisor.yaml
  wolfi-images/cloud-mi2.yaml
  wolfi-images/executor-kubernetes.yaml
  wolfi-images/executor.yaml
  wolfi-images/gitserver.yaml
  wolfi-images/jaeger-agent.yaml
  wolfi-images/jaeger-all-in-one.yaml
  wolfi-images/node-exporter.yaml
  wolfi-images/opentelemetry-collector.yaml
  wolfi-images/postgres-exporter.yaml
  wolfi-images/postgresql-12-codeinsights.yaml
  wolfi-images/postgresql-12.yaml
  wolfi-images/prometheus-gcp.yaml
  wolfi-images/prometheus.yaml
  wolfi-images/qdrant.yaml
  wolfi-images/redis-exporter.yaml
  wolfi-images/redis.yaml
  wolfi-images/repo-updater.yaml
  wolfi-images/search-indexer.yaml
  wolfi-images/searcher.yaml
  wolfi-images/server.yaml
  wolfi-images/sourcegraph-base.yaml
  wolfi-images/sourcegraph-dev.yaml
  wolfi-images/sourcegraph.yaml
  wolfi-images/symbols.yaml
  wolfi-images/syntax-highlighter.yaml
  wolfi-packages/jaeger.yaml
Labels: cla-signed

#56551 [Backport 5.1] zoekt: update to 3ce1f2b24c80b3dea89d237600d2b0879342ed1b
  deps.bzl
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  go.mod
  go.sum
  internal/search/backend/BUILD.bazel
  internal/search/backend/grpc.go
  internal/search/backend/zoekt.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/github_proxy.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/searcher.go
  monitoring/definitions/shared/gitserver.go
  monitoring/definitions/shared/grpc.go
  monitoring/definitions/shared/http.go
  monitoring/definitions/symbols.go
  monitoring/definitions/worker.go
  monitoring/definitions/zoekt.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#56521 grpc: gitserver: exec: change EnsureRevision field to be bytes instead of string (#56514)
  cmd/gitserver/server/server_grpc.go
  internal/gitserver/client.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: cla-signed

#56450 Add config to allow for ignoring Perforce protects rules that specify a Host
  CHANGELOG.md
  doc/admin/repo/perforce.md
  internal/authz/providers/perforce/authz.go
  internal/authz/providers/perforce/cmd/scanprotects/main.go
  internal/authz/providers/perforce/cmd/scanprotects/main_test.go
  internal/authz/providers/perforce/perforce.go
  internal/authz/providers/perforce/perforce_test.go
  internal/authz/providers/perforce/protects.go
  internal/authz/providers/perforce/protects_test.go
  schema/perforce.schema.json
  schema/schema.go
Labels: cla-signed

#56475 search jobs: add blobstore csv writer
  enterprise/cmd/worker/internal/search/BUILD.bazel
  enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision.go
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  enterprise/cmd/worker/internal/search/job.go
  internal/search/exhaustive/service/BUILD.bazel
  internal/search/exhaustive/service/search.go
  internal/search/exhaustive/service/search_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
  internal/search/exhaustive/uploadstore/store.go
Labels: cla-signed

#56481 hide access token by default after creation
  client/web/src/components/CopyableText.tsx
  client/web/src/settings/tokens/AccessTokenCreatedAlert.tsx
Labels: cla-signed

#56542 JetBrains: move caching graphql query loader to our sources from IntelliJ
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/api/CachingGraphQLQueryLoader.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/api/GraphQLFileNotFoundException.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/api/SourcegraphGQLQueryLoader.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/DeferredIconRepaintScheduler.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/ScaleContextCache.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/ScalingAsyncImageIcon.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/SimpleAccountsListCellRenderer.kt
Labels: cla-signed

#56563 more changelog cleanup
  CHANGELOG.md
Labels: cla-signed

#56564 JetBrains: removes code search onboarding
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/NotificationActivity.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyApplicationSettings.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt
Labels: cla-signed

#56561 cleanup: More idiomatic cmp.Diff API usage
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/site_test.go
  internal/database/repo_statistics_test.go
Labels: cla-signed

#56575 JetBrains: Cody: Fixing manual autocomplete trigger
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Labels: cla-signed

#56574 Rename release cache rate limiter urn
  cmd/frontend/internal/httpapi/releasecache/config.go
Labels: cla-signed, team/iam

#56576 Fix capitalization
  client/web/src/get-cody/GetCodyPage.tsx
Labels: cla-signed

#56579 JetBrains: Cody: Switch to master-layout-based settings UI
  client/jetbrains/CHANGELOG.md
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyOnboardingPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/OpenPluginSettingsAction.java
  client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeActionNotifier.java
  client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
  client/jetbrains/src/main/java/com/sourcegraph/find/browser/BrowserAndLoadingPanel.java
  client/jetbrains/src/main/java/com/sourcegraph/find/browser/SourcegraphJBCefBrowser.java
  client/jetbrains/src/main/java/com/sourcegraph/telemetry/PostStartupActivity.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountDetailsProvider.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/AccountSettingChangeActionNotifier.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/AccountSettingChangeContext.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/AccountSettingChangeListener.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/ChangeListener.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeActionNotifier.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeContext.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeListener.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/AccountConfigurable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodeSearchConfigurable.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#56581 JetBrains: Cody: Hotfix: notify agent of configuration change on account settings change
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/AccountSettingChangeListener.kt
Labels: cla-signed

#56577 globallimiter: Improve reliability
  cmd/gitserver/shared/shared.go
  cmd/worker/internal/ratelimit/job.go
  internal/extsvc/azuredevops/client.go
  internal/extsvc/bitbucketcloud/BUILD.bazel
  internal/extsvc/bitbucketcloud/client.go
  internal/extsvc/bitbucketserver/BUILD.bazel
  internal/extsvc/bitbucketserver/client.go
  internal/extsvc/crates/BUILD.bazel
  internal/extsvc/crates/client.go
  internal/extsvc/gerrit/BUILD.bazel
  internal/extsvc/gerrit/client.go
  internal/extsvc/github/v3.go
  internal/extsvc/github/v4.go
  internal/extsvc/gitlab/client.go
  internal/extsvc/gomodproxy/BUILD.bazel
  internal/extsvc/gomodproxy/client.go
  internal/extsvc/npm/npm.go
  internal/extsvc/pagure/BUILD.bazel
  internal/extsvc/pagure/client.go
  internal/extsvc/pypi/BUILD.bazel
  internal/extsvc/pypi/client.go
  internal/extsvc/rubygems/BUILD.bazel
  internal/extsvc/rubygems/client.go
  internal/ratelimit/BUILD.bazel
  internal/ratelimit/globallimiter.go
  internal/ratelimit/globallimiter_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#56560 codeintel: Use snapshots for auto-inference testing
  internal/codeintel/autoindexing/internal/inference/BUILD.bazel
  internal/codeintel/autoindexing/internal/inference/lang_go_test.go
  internal/codeintel/autoindexing/internal/inference/lang_java_test.go
  internal/codeintel/autoindexing/internal/inference/lang_python_test.go
  internal/codeintel/autoindexing/internal/inference/lang_ruby_test.go
  internal/codeintel/autoindexing/internal/inference/lang_rust_test.go
  internal/codeintel/autoindexing/internal/inference/lang_typescript_test.go
  internal/codeintel/autoindexing/internal/inference/service_generator_test.go
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Gradle.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Gradle_build_file_but_no_sources.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Maven.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Maven_build_file_but_no_sources.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Mill_build_file_but_no_sources.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_SBT.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_SBT_build_file_but_no_sources.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_lsif-java.json.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_without_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_WITHOUT_top-level_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_with_top-level_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/disable_default.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/empty.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_files_in_non-root_(no_match).yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_files_in_root.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_modules.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/javascript_project_with_no_tsconfig.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/javascript_project_with_no_tsconfig_1.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/javascript_project_with_no_tsconfig_2.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/override.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_1.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_2.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_3.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/rust-analyzer.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/scip-ruby.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/simple_tsconfig.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/tsconfig_in_subdirectories.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/typescript_installation_steps.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/typescript_with_lerna_configuration.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/typescript_with_node_version.yaml
Labels: cla-signed

#56583 Bump up cody-shared package version
  client/web/package.json
  pnpm-lock.yaml
Labels: cla-signed, team/iam

#56585 doc: sg setup and pre-commit
  dev/sg/sg_setup.go
  doc/dev/background-information/sg/index.md
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#56565 JetBrains: release 3.1.0-alpha.7
  client/jetbrains/gradle.properties
Labels: cla-signed

#56543 JetBrains: Cody: Disable autocomplete when navigating with arrow keys
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
Labels: cla-signed

#56591 sg: avoid silently discarding files if lint go is ran locally
  dev/sg/linters/gogenerate.go
Labels: cla-signed

#56546 Bump NodeJS to v18
  .aspect/bazelrc/rules_ts.bazelrc
  .bazelrc
  .github/workflows/licenses-check.yml
  .github/workflows/update-embeddings-list.yml
  .tool-versions
  WORKSPACE
  client/branded/BUILD.bazel
  client/shared/src/testing/driver.ts
  client/web/src/enterprise/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
  client/wildcard/BUILD.bazel
  dev/defs.bzl
  package.json
  pnpm-lock.yaml
  shell.nix
Labels: cla-signed

#56554 updating hash for wolfi
  dev/oci_deps.bzl
Labels: cla-signed

#56516 [Search Jobs]: Add special zero state for the initial empty state
  client/web/src/enterprise/search-jobs/SearchJobsPage.module.scss
  client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
  client/web/src/enterprise/search-jobs/UsersPicker.module.scss
  ui/assets/img/no-jobs-state-dark.png
  ui/assets/img/no-jobs-state-light.png
Labels: cla-signed

#56588 JetBrains: refine autocomplete trigger
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Labels: cla-signed
