Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-10, with the labels that each got.

#57223 [Backport 5.2] telemetrygatewayexporter: increase default export rates
  enterprise/cmd/worker/internal/telemetrygatewayexporter/telemetrygatewayexporter.go
Labels: cla-signed, backport/stability

#50000 improve search query examples on homepage
  client/branded/src/search-ui/components/QueryExamples.constants.ts
  client/branded/src/search-ui/components/QueryExamples.module.scss
  client/branded/src/search-ui/components/QueryExamples.tsx
  client/branded/src/search-ui/components/useQueryExamples.tsx
  client/branded/src/search-ui/results/NoResultsPage.tsx
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web-sveltekit/src/lib/search/queryExamples.ts
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
Labels: cla-signed

#57224 Embeddings: tolerate some failure when generating embeddings
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
Labels: cla-signed

#57191 search jobs: check feature flag in CreateSearchJob
  cmd/frontend/internal/search/httpapi/BUILD.bazel
  cmd/frontend/internal/search/httpapi/export_test.go
  enterprise/cmd/worker/internal/search/BUILD.bazel
  enterprise/cmd/worker/internal/search/exhaustive_search_test.go
  internal/search/exhaustive/service/service.go
Labels: cla-signed, backport 5.2, backport/improvement

#57177 Update docker dind image to 24.0.6 to fix vulns
  docker-images/dind/Dockerfile
Labels: cla-signed, backport 5.2

#57202 Check for returnTo in openidconnect redirect check
  client/web/src/LegacyLayout.tsx
  client/web/src/auth/SignInPage.test.tsx
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  cmd/frontend/internal/auth/openidconnect/middleware.go
Labels: cla-signed

#57072 [OCT Launch] Search and Platform: Docs for Search Jobs
  client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
  doc/code_search/how-to/index.md
  doc/code_search/how-to/search-jobs.md
Labels: docs, cla-signed, backport 5.2, backport/bugfix, backport/improvement

#57237 telemetry-gateway: copy range variable
  cmd/telemetry-gateway/internal/events/BUILD.bazel
  cmd/telemetry-gateway/internal/events/events.go
  cmd/telemetry-gateway/internal/events/events_test.go
  cmd/telemetry-gateway/internal/server/publish_events_test.go
  internal/database/telemetry_export_store_test.go
  internal/pubsub/pubsubtest/BUILD.bazel
  internal/pubsub/pubsubtest/pubsubtest.go
Labels: cla-signed, backport 5.2, backport/bugfix

#57252 local: fix scip-ctags install script
  dev/scip-ctags-dev
Labels: cla-signed

#57222 monitoring: add queue growth panel and alert
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/telemetry.go
Labels: cla-signed, backport 5.2, backport/improvement

#57250 [OCT Launch] Add JetBrains supported IDEs for Cody
  doc/cody/overview/install-jetbrains.md
Labels: docs, cla-signed

#57234 telemetry-export: add teestore, queue store metrics
  internal/database/telemetry_export_store.go
  internal/telemetry/teestore/BUILD.bazel
  internal/telemetry/teestore/teestore.go
Labels: cla-signed, backport 5.2, backport/improvement

#57259 switching ctags to tagged versions
  wolfi-packages/ctags.yaml
Labels: cla-signed

#57243 Configurable embedding batch size
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
Labels: cla-signed

#57194 JetBrains: Cody: Add actions for cycling over autocomplete items
  client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/InlineAutocompleteItem.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/AcceptAutocompleteActionHandler.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/AcceptCodyAutocompleteAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/AutocompleteActionHandler.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/CycleBackwardAutocompleteAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/CycleCodyAutocompleteActionHandler.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/action/CycleForwardAutocompleteAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/render/AutocompleteRenderUtil.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/render/CodyAutocompleteBlockElementRenderer.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/render/CodyAutocompleteElementRenderer.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/render/CodyAutocompleteSingleLineRenderer.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/vscode/InlineAutocompleteItem.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed

#57185 JetBrains: validate git url in codebase selection asynchronously without blocking the EDT
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/EditCodebaseContextAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/LoadingLayerUI.kt
Labels: cla-signed

#57251 JetBrains: show icon when agent doesnt start/crashes
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentManager.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/initialization/PostStartupActivity.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyAutocompleteStatus.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyAutocompleteStatusService.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyDisableAutocompleteAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyEnableAutocompleteAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyManageAccountsAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyOpenSettingsAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyStatusBarActionGroup.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/OpenLogAction.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/ReportCodyBugAction.kt
  client/jetbrains/src/main/resources/META-INF/plugin.xml
Labels: cla-signed, jetbrains-ide

#57232 remove more ENTERPRISE=1 remnants
  client/build-config/src/paths.ts
  client/observability-server/src/webBundleSize/index.ts
  client/web-sveltekit/.env
  client/web-sveltekit/src/routes/(enterprise)/+layout.ts
  client/web/BUILD.bazel
  client/web/bundlesize.config.js
  client/web/dev/esbuild/build.ts
  client/web/dev/utils/environment-config.ts
  client/web/package.json
  client/web/scripts/BUILD.bazel
  client/web/src/OpenSourceWebApp.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/enterprise/site-admin/routes.tsx
  client/web/src/integration/BUILD.bazel
  client/web/src/main.tsx
  client/web/src/site-admin/UserManagement/components/UsersList.tsx
  client/web/src/site-admin/UserManagement/index.tsx
  client/web/src/site-admin/routes.tsx
  client/web/webpack.bazel.config.js
  client/web/webpack.config.js
  dev/auth-provider/keycloak.sh
  dev/ci/pnpm-build.sh
  dev/sg/internal/sgconf/config_test.go
  dev/webpack.bzl
  doc/dev/background-information/bazel/web.md
  doc/dev/background-information/bazel/web_overview.md
  doc/dev/contributing/frontend_contribution.md
  doc/dev/how-to/testing.md
  enterprise/dev/app/build-backend.sh
  enterprise/dev/app/build-windows.sh
  enterprise/dev/ci/internal/ci/bazel_operations.go
  enterprise/dev/ci/internal/ci/operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
  enterprise/dev/dev-sourcegraph-server.sh
  sg.config.yaml
  ui/assets/doc.go
  ui/assets/enterprise/BUILD.bazel
  ui/assets/oss/BUILD.bazel
  ui/assets/oss/assets.go
  ui/assets/oss/webpack.manifest.json
Labels: cla-signed

#57229 clean up browser extension webpack build
  client/browser/BUILD.bazel
  client/browser/README.md
  client/browser/config/BUILD.bazel
  client/browser/config/webpack/auto-reloading.ts
  client/browser/config/webpack/base.config.bazel.ts
  client/browser/config/webpack/base.config.ts
  client/browser/config/webpack/development.config.ts
  client/browser/scripts/auto-reloading.ts
  client/browser/scripts/development.ts
  client/browser/scripts/tasks.ts
  client/browser/src/browser-extension/manifest.spec.json
  client/browser/src/browser-extension/pages/after_install.html
  client/browser/src/browser-extension/pages/options.html
  client/browser/src/browser-extension/scripts/backgroundPage.main.ts
  client/browser/src/browser-extension/scripts/contentPage.main.ts
  client/browser/src/browser-extension/scripts/optionsPage.main.tsx
  client/browser/src/config/background.entry.ts
  client/browser/src/config/content.entry.ts
  client/browser/src/config/extension.entry.ts
  client/browser/src/config/options.entry.ts
  client/browser/src/config/page.entry.ts
  client/browser/src/native-integration/nativeIntegration.main.ts
  client/browser/src/native-integration/phabricator/phabricatorNativeIntegration.main.ts
  client/web/src/regression/integrations.test.ts
  package.json
  pnpm-lock.yaml
  third-party-licenses/ThirdPartyLicenses.csv
Labels: cla-signed

#55996 Add initial version of dropdown menu and update user menu
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/stores.ts
  client/web-sveltekit/src/lib/theme.ts
  client/web-sveltekit/src/lib/utils/context.ts
  client/web-sveltekit/src/lib/utils/stores.ts
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/lib/wildcard/menu/Menu.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuLink.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuRadioGroup.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuSeparator.svelte
  client/web-sveltekit/src/lib/wildcard/menu/Submenu.svelte
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/Header.svelte
  client/web-sveltekit/src/routes/UserMenu.svelte
  pnpm-lock.yaml
Labels: cla-signed, code-search

#57265 cody-gateway: forward identifier that includes actor ID to upstreams
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#57264 release-branch: v5.2.0 bake constants and static content
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
  cmd/migrator/BUILD.bazel
  cmd/migrator/generate.sh
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/migration/stitch/reader.go
  internal/src-cli/consts.go
Labels: cla-signed

#56711 encryption: Standardize envelope encryption
  doc/admin/config/encryption.md
  internal/encryption/README.md
  internal/encryption/aeshelper/BUILD.bazel
  internal/encryption/aeshelper/aeshelper.go
  internal/encryption/aeshelper/aeshelper_test.go
  internal/encryption/awskms/BUILD.bazel
  internal/encryption/awskms/aws_kms.go
  internal/encryption/awskms/aws_kms_test.go
  internal/encryption/awskms/testdata/awskms.yaml
  internal/encryption/cloudkms/BUILD.bazel
  internal/encryption/cloudkms/cloud_kms.go
  internal/encryption/cloudkms/cloud_kms_test.go
  internal/encryption/cloudkms/testdata/cloudkms.yaml
  internal/encryption/encryptable.go
  internal/encryption/envelope/BUILD.bazel
  internal/encryption/envelope/envelope.go
  internal/encryption/envelope/envelope_test.go
  internal/encryption/mounted/BUILD.bazel
  internal/encryption/mounted/key.go
  internal/encryption/mounted/key_test.go
  internal/encryption/wrapper/BUILD.bazel
  internal/encryption/wrapper/encryptedvalue.go
  internal/encryption/wrapper/encryptedvalue_test.go
Labels: cla-signed

#57273 grpc: searcher: change file_path and content type to be bytes instead of string
  cmd/searcher/protocol/BUILD.bazel
  cmd/searcher/protocol/searcher.go
  cmd/searcher/protocol/searcher_test.go
  internal/search/searcher/search.go
  internal/searcher/v1/searcher.pb.go
  internal/searcher/v1/searcher.proto
Labels: cla-signed, backport 5.2, backport/bugfix

#57277 Regenerate schema.go file
  schema/schema.go
Labels: cla-signed

#57281 proto: Add editorconfig to ident using two spaces
  .editorconfig
Labels: cla-signed

#57285 Remove accidentally committed playwright file
  .gitignore
  playwright/requires_a_valid_auth_token_and_allows_logouts/db6496ac67f95e0445ab29296f3454ae.webm
Labels: cla-signed

#57290 fix background page bundle name
  client/browser/src/browser-extension/pages/background.html
Labels: cla-signed

#57288 Log frontend events and then strip ?signup and ?signin query paramete…
  client/web/src/tracking/eventLogger.ts
Labels: cla-signed

#57294 ctags: update darwin ctags sha256
  dev/tool_deps.bzl
Labels: cla-signed

#57295 Add redirect to post-signup survey on token routes
  client/web/src/user/settings/accessTokens/UserSettingsTokensArea.tsx
Labels: cla-signed, team/iam

#57300 search: exhaustive panic on uploadstore error
  internal/search/exhaustive/service/service.go
Labels: cla-signed, backport 5.2, backport/bugfix

#57297 embeddings: remove weaviate integration
  deps.bzl
  enterprise/cmd/embeddings/shared/BUILD.bazel
  enterprise/cmd/embeddings/shared/config.go
  enterprise/cmd/embeddings/shared/context_qa_test.go
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/embeddings/shared/main_test.go
  enterprise/cmd/embeddings/shared/search.go
  enterprise/cmd/embeddings/shared/weaviate.go
  go.mod
  go.sum
Labels: cla-signed

#57305 Remove empty package
  internal/accesstoken/BUILD.bazel
Labels: cla-signed

#57289 Remove replace directive for graphql-go/graphql
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#57258 [OCT Launch] Improvements to Cody Clients Feature Parity docs
  doc/cody/feature-reference.md
Labels: docs, cla-signed

#57308 bzl: fix schema.go not being up todate and still passing
  BUILD.bazel
  client/web/BUILD.bazel
  client/web/src/rbac/BUILD.bazel
  cmd/cody-gateway/internal/dotcom/BUILD.bazel
  cmd/frontend/internal/guardrails/dotcom/BUILD.bazel
  dev/BUILD.bazel
  dev/sg/BUILD.bazel
  dev/write_generated_to_source_files.bzl
  doc/admin/observability/BUILD.bazel
  doc/cli/references/BUILD.bazel
  doc/dev/background-information/bazel/go_generate.md
  doc/dev/background-information/sg/BUILD.bazel
  doc/dev/background-information/telemetry/BUILD.bazel
  internal/database/BUILD.bazel
  internal/rbac/BUILD.bazel
  internal/rbac/types/BUILD.bazel
  lib/batches/schema/BUILD.bazel
  schema/BUILD.bazel
Labels: cla-signed

#57313 codenotify: dr. fritz is kil
  client/web/src/enterprise/codeintel/CODENOTIFY
  client/web/src/enterprise/executors/CODENOTIFY
  cmd/executor/CODENOTIFY
  cmd/frontend/graphqlbackend/CODENOTIFY
  cmd/frontend/internal/codeintel/CODENOTIFY
  cmd/frontend/internal/executorqueue/CODENOTIFY
  cmd/precise-code-intel-worker/CODENOTIFY
  cmd/worker/CODENOTIFY
  cmd/worker/internal/executorqueue/CODENOTIFY
  cmd/worker/internal/executors/CODENOTIFY
  dev/codeintel-qa/CODENOTIFY
  dev/depgraph/CODENOTIFY
  doc/code_navigation/CODENOTIFY
  doc/dev/background-information/codeintel/CODENOTIFY
  enterprise/cmd/migrator/CODENOTIFY
  internal/codeintel/CODENOTIFY
  internal/database/basestore/CODENOTIFY
  internal/database/batch/CODENOTIFY
  internal/database/connections/CODENOTIFY
  internal/database/dbconn/CODENOTIFY
  internal/database/dbtest/CODENOTIFY
  internal/database/dbutil/CODENOTIFY
  internal/database/locker/CODENOTIFY
  internal/database/migration/CODENOTIFY
  internal/database/postgresdsn/CODENOTIFY
  internal/env/CODENOTIFY
  internal/executor/CODENOTIFY
  internal/goroutine/CODENOTIFY
  internal/luasandbox/CODENOTIFY
  internal/oobmigration/CODENOTIFY
  internal/usagestats/CODENOTIFY
  internal/workerutil/CODENOTIFY
  lib/codeintel/CODENOTIFY
  monitoring/CODENOTIFY
Labels: cla-signed

#57314 ctags: update universal-ctags sha
  dev/tool_deps.bzl
Labels: cla-signed

#57262 v5.2.0 bake constants and static content
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/migration/stitch/reader.go
  internal/src-cli/consts.go
Labels: cla-signed

#57286 sg: Install p4 cli for local dev
  dev/sg/dependencies/mac.go
  dev/sg/dependencies/ubuntu.go
Labels: cla-signed

#57160 auth: return 401 for invalid auth headers on DotCom
  cmd/frontend/internal/httpapi/auth.go
Labels: cla-signed, SSDLC

#57315 release: sourcegraph@5.2.0
  cmd/migrator/BUILD.bazel
  cmd/migrator/generate.sh
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/pipeline.go
  internal/updatecheck/handler.go
Labels: cla-signed

#57282 release: formalize 5.2.0 CHANGELOG
  CHANGELOG.md
Labels: cla-signed

#57320 release: close 5.2
  dev/release/release-config.jsonc
  dev/release/templates/release_issue_template.md
Labels: cla-signed

#57309 fix export file name format for windows
  client/web/src/search/results/export/searchResultsExport.test.ts
  client/web/src/search/results/export/searchResultsExport.ts
Labels: cla-signed

#57119 repoupdater: Break dependency on cmd/gitserver
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_grpc.go
  cmd/gitserver/server/vcs_syncer_perforce.go
  doc/dev/background-information/gitserver-api.md
  internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
  internal/repos/BUILD.bazel
  internal/repos/perforce.go
  internal/repos/perforce_test.go
Labels: cla-signed

#57120 repoupdater: Remove p4 binary from docker image
  cmd/repo-updater/image_test.yaml
  wolfi-images/repo-updater.yaml
Labels: cla-signed

#57316 gitserver: Prevent concurrent writes to errs
  internal/gitserver/BUILD.bazel
  internal/gitserver/client.go
Labels: cla-signed

#57083 chore: Remove dead code
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_definitions_test.go
  internal/codeintel/codenav/service_implementations_test.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/service_references_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
  internal/codeintel/codenav/transport/graphql/root_resolver_implementations.go
  internal/codeintel/codenav/transport/graphql/root_resolver_references.go
  internal/codeintel/codenav/transport/graphql/root_resolver_test.go
Labels: cla-signed

#57322 Stop pinging efritz
  .github/test.CODEOWNERS
  .github/workflows/label-notify.yml
Labels: cla-signed

#57121 perforce: Make connection check a proper RPC call
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_grpc.go
  cmd/gitserver/server/vcs_syncer_perforce.go
  doc/dev/background-information/gitserver-api.md
  internal/batches/sources/mocks_test.go
  internal/batches/sources/perforce.go
  internal/batches/sources/perforce_test.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
  internal/repos/perforce.go
Labels: cla-signed

#57304 Don't import soap package across cmds
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/external_accounts.go
  cmd/frontend/internal/auth/sourcegraphoperator/BUILD.bazel
  cmd/frontend/internal/auth/sourcegraphoperator/associate.go
  cmd/frontend/internal/auth/sourcegraphoperator/associate_test.go
  cmd/frontend/internal/auth/sourcegraphoperator/config.go
  cmd/frontend/internal/auth/sourcegraphoperator/middleware.go
  cmd/worker/internal/auth/BUILD.bazel
  cmd/worker/internal/auth/sourcegraph_operator_cleaner.go
  cmd/worker/internal/auth/sourcegraph_operator_cleaner_test.go
  internal/sourcegraphoperator/BUILD.bazel
  internal/sourcegraphoperator/account.go
  internal/sourcegraphoperator/associate.go
Labels: cla-signed

#57291 Move embeddings service out of enterprise
  WORKSPACE
  cmd/embeddings/BUILD.bazel
  cmd/embeddings/image_test.yaml
  cmd/embeddings/main.go
  cmd/embeddings/qa/BUILD.bazel
  cmd/embeddings/qa/context_data.tsv
  cmd/embeddings/qa/embed_queries/BUILD.bazel
  cmd/embeddings/qa/embed_queries/main.go
  cmd/embeddings/qa/eval.go
  cmd/embeddings/shared/BUILD.bazel
  cmd/embeddings/shared/assets.bzl
  cmd/embeddings/shared/config.go
  cmd/embeddings/shared/context_qa_test.go
  cmd/embeddings/shared/main.go
  cmd/embeddings/shared/main_test.go
  cmd/embeddings/shared/repo_embedding_index_cache.go
  cmd/embeddings/shared/repo_embedding_index_cache_test.go
  cmd/embeddings/shared/search.go
  cmd/embeddings/shared/service.go
  cmd/embeddings/shared/testdata/.gitkeep
  cmd/server/BUILD.bazel
  cmd/sourcegraph/BUILD.bazel
  cmd/sourcegraph/main.go
  dev/check/go-dbconn-import.sh
  dev/sg/BUILD.bazel
  dev/sg/sg_embeddings_qa.go
  enterprise/dev/ci/internal/ci/bazel_operations.go
  sg.config.yaml
Labels: cla-signed

#57328 Add docs for the new custom commands mode property
  doc/cody/custom-commands.md
Labels: cla-signed

#57329 release: update release config
  .prettierignore
  dev/release/release-config.jsonc
Labels: cla-signed

#57331 search jobs: add changelog entry
  CHANGELOG.md
Labels: cla-signed

#57333 gitserver: remove lazy constructor for atomicGitServerConns
  internal/gitserver/client.go
  internal/gitserver/gitolite.go
  internal/gitserver/grpc_test.go
Labels: cla-signed

#57296 ctags actions: only upload when a change to ctags nix is pushed to main
  .github/workflows/universal-ctags.yml
  dev/nix/ctags.nix
Labels: cla-signed

#57332 Display all external accounts for each auth provider
  client/web/BUILD.bazel
  client/web/src/user/settings/auth/ExternalAccount.test.tsx
  client/web/src/user/settings/auth/ExternalAccount.tsx
  client/web/src/user/settings/auth/ExternalAccountsSignIn.test.tsx
  client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
  client/web/src/user/settings/auth/__snapshots__/ExternalAccountsSignIn.test.tsx.snap
Labels: cla-signed, team/iam

#57339 ctags: fix push branch target
  .github/workflows/universal-ctags.yml
  dev/nix/ctags.nix
Labels: cla-signed

#57340 gitserver: Move cloneurl into internal package
  cmd/gitserver/internal/cloneurl/BUILD.bazel
  cmd/gitserver/internal/cloneurl/clone_url.go
  cmd/gitserver/internal/cloneurl/clone_url_test.go
  cmd/gitserver/shared/BUILD.bazel
  cmd/gitserver/shared/shared.go
Labels: cla-signed

#57279 Remove dead code from org invites
  client/web/BUILD.bazel
  client/web/src/org/area/OrgArea.tsx
  client/web/src/org/settings/codeHosts/InstallGitHubAppSuccessPage.module.scss
  client/web/src/org/settings/codeHosts/InstallGitHubAppSuccessPage.tsx
  client/web/src/org/settings/members/InviteForm.tsx
  client/web/src/routes.constants.ts
  client/web/src/routes.tsx
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/email_invitation.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/org_invitations_test.go
  cmd/frontend/graphqlbackend/schema.graphql
  dev/authtest/organization_test.go
  doc/admin/observability/dashboards.md
  internal/gqltestutil/organization.go
  monitoring/definitions/frontend.go
Labels: cla-signed

#57284 Remove unused oauthTokenHelper for external services
  internal/oauthtoken/BUILD.bazel
  internal/oauthtoken/oauth_token_helper.go
  internal/oauthtoken/oauth_token_helper_test.go
Labels: cla-signed

#56804 Remove references to user_id and org_id fields on external services and repos
  cmd/frontend/oneclickexport/export_test.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/repos.go
  internal/database/sub_repo_perms_store_test.go
  internal/database/users_test.go
  internal/types/types.go
Labels: cla-signed

#57341 Update README.md of JetBrains
  client/jetbrains/README.md
Labels: cla-signed

#56990 [OCT Launch] Cody Client: Docs updates for VS Code
  doc/cody/overview/install-vscode.md
Labels: docs, cla-signed

#56677 Sync GitHub internal repos during user perms sync
  CHANGELOG.md
  cmd/frontend/internal/auth/githuboauth/session.go
  cmd/repo-updater/internal/authz/BUILD.bazel
  cmd/repo-updater/internal/authz/integration_test.go
  cmd/repo-updater/internal/authz/testdata/vcr/TestIntegration_GitHubInternalRepositories.yaml
  cmd/repo-updater/internal/authz/testdata/vcr/TestIntegration_GitHubPermissions/repo-centric/groups-enabled.yaml
  cmd/repo-updater/internal/authz/testdata/vcr/TestIntegration_GitHubPermissions/repo-centric/no-groups.yaml
  cmd/repo-updater/internal/authz/testdata/vcr/TestIntegration_GitHubPermissions/user-centric/groups-enabled.yaml
  cmd/repo-updater/internal/authz/testdata/vcr/TestIntegration_GitHubPermissions/user-centric/no-groups.yaml
  doc/admin/external_service/github.md
  internal/authz/providers/github/BUILD.bazel
  internal/authz/providers/github/authz.go
  internal/authz/providers/github/client.go
  internal/authz/providers/github/github.go
  internal/authz/providers/github/github_test.go
  internal/authz/providers/github/mocks_test.go
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_existing_fork
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_new_fork
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_existing_fork
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_new_fork
  internal/extsvc/github/common.go
  internal/extsvc/github/testdata/golden/ListRepositoriesForSearch
  internal/extsvc/github/testdata/golden/SearchRepos-Enterprise-narrow-query-enterprise
  internal/extsvc/github/testdata/golden/TestGetRepository/cached-response/first_run
  internal/extsvc/github/testdata/golden/TestGetRepository/cached-response/second_run
  internal/extsvc/github/testdata/golden/TestGetRepository/forked_repo
  internal/extsvc/github/testdata/golden/TestV3Client_Fork_success_sourcegraph-testing
  internal/extsvc/github/testdata/golden/TestV3Client_Fork_success_user
  internal/extsvc/github/v3.go
  internal/extsvc/github/v3_test.go
  internal/extsvc/github/v4.go
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/testdata/sources/GITHUB-ENTERPRISE/internal-repo-in-github-enterprise.yaml
  schema/github.schema.json
  schema/schema.go
Labels: cla-signed, team/iam

#56989 [OCT Launch] Cody Client: Docs updates for Neovim
  doc/cody/overview/install-neovim.md
  doc/sidebar.md
Labels: docs, cla-signed

#57334 search jobs: mention bucket config in the docs
  doc/code_search/how-to/search-jobs.md
Labels: cla-signed

#57343 Fix syntect scip off-by-one
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_sciptect.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__off-by-one.yaml.snap
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/syntect_files/off-by-one.yaml
Labels: cla-signed, backport 5.2, backport/bugfix

#57318 gitserver: disk-info: make test hit two separate gitserver addresses
  internal/gitserver/BUILD.bazel
  internal/gitserver/client.go
  internal/gitserver/client_test.go
Labels: cla-signed, backport 5.2

#57280 gitserver: Speedup slow test
  cmd/gitserver/internal/sshagent/ssh_agent_test.go
Labels: cla-signed

#57350 Chore: remove enteprise/docs
  enterprise/docs/deployment.md
  enterprise/docs/glossary.md
  enterprise/docs/saml-adfs.md
  enterprise/docs/xrepo-find-all-refs.png
  enterprise/docs/xrepo-j2d.png
Labels: cla-signed

#57349 Chore: remove unused enterprise assets
  enterprise/ui/assets/img/codemonitoring-icon.svg
  enterprise/ui/assets/img/logo-chrome.svg
  enterprise/ui/assets/img/logo-firefox.svg
  enterprise/ui/assets/img/sourcegraph-logo-dark.svg
  enterprise/ui/assets/img/sourcegraph-logo-light.svg
  enterprise/ui/assets/img/sourcegraph-mark.svg
Labels: cla-signed

#57317 gitserver: Revert hexagonal architecture
  cmd/frontend/backend/inventory.go
  cmd/frontend/backend/repos.go
  cmd/frontend/graphqlbackend/git_object.go
  cmd/gitserver/internal/BUILD.bazel
  cmd/gitserver/internal/commands.go
  cmd/gitserver/internal/git/BUILD.bazel
  cmd/gitserver/internal/git/git.go
  cmd/gitserver/internal/git/object.go
  cmd/gitserver/internal/git/object_test.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/serverutil.go
  internal/codeintel/resolvers/BUILD.bazel
  internal/codeintel/resolvers/git.go
  internal/gitserver/adapters/BUILD.bazel
  internal/gitserver/adapters/git.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/gitdomain/BUILD.bazel
  internal/gitserver/gitdomain/common_test.go
  internal/gitserver/gitdomain/services.go
  internal/gitserver/gitdomain/services_test.go
Labels: cla-signed

#57283 extsvc: Ensure created_at is set
  internal/database/external_services.go
Labels: cla-signed

#57310 Docs: Update feature parity matrix
  doc/cody/feature-reference.md
Labels: cla-signed

#57311 dotcom: Don't depend on gitserver for repo.add
  cmd/frontend/backend/BUILD.bazel
  cmd/frontend/backend/repos.go
  cmd/frontend/backend/repos_test.go
  cmd/gitserver/internal/server.go
Labels: cla-signed

#57267 gitserver: Reduce janitor spam of context canceled errors
  cmd/gitserver/internal/cleanup.go
Labels: cla-signed

#57354 Chore: move dev tools out of enterprise
  dev/deployment-lag-notifier/.gitignore
  dev/deployment-lag-notifier/BUILD.bazel
  dev/deployment-lag-notifier/Makefile
  dev/deployment-lag-notifier/README.md
  dev/deployment-lag-notifier/github.go
  dev/deployment-lag-notifier/main.go
  dev/deployment-lag-notifier/main_test.go
  dev/deployment-lag-notifier/slack.go
  dev/deployment-notifier/BUILD.bazel
  dev/deployment-notifier/OWNERS
  dev/deployment-notifier/README.md
  dev/deployment-notifier/deployment_notifier.go
  dev/deployment-notifier/deployment_notifier_test.go
  dev/deployment-notifier/main.go
  dev/deployment-notifier/manifest_differ.go
  dev/deployment-notifier/manifest_differ_test.go
  dev/deployment-notifier/slack.go
  dev/deployment-notifier/testdata/TestDeploymentNotifier/NOK_deploying_twice.yaml
  dev/deployment-notifier/testdata/TestDeploymentNotifier/OK_deploying_twice.yaml
  dev/deployment-notifier/testdata/TestDeploymentNotifier/OK_no_relevant_changed_files.yaml
  dev/deployment-notifier/testdata/TestDeploymentNotifier/OK_normal.yaml
  dev/deployment-notifier/testdata/TestDeploymentNotifier/OK_single_commit.yaml
  dev/deployment-notifier/testdata/TestDeploymentNotifier/Summary.yaml
  dev/deployment-notifier/trace.go
  dev/deployment-notifier/trace_test.go
  dev/insight-data-gen/.gitignore
  dev/insight-data-gen/BUILD.bazel
  dev/insight-data-gen/README.md
  dev/insight-data-gen/examples/manifest.json
  dev/insight-data-gen/go.mod
  dev/insight-data-gen/go.sum
  dev/insight-data-gen/main.go
  enterprise/dev/check/build.sh
  enterprise/dev/src-prof-services.json
Labels: cla-signed

#57358 Chore: remove committed junit.xml
  .gitignore
  junit.xml
Labels: cla-signed

#57344 search: remove UserID logic for dotcom repo resolution
  internal/database/repos.go
  internal/search/zoekt/BUILD.bazel
  internal/search/zoekt/indexed_search.go
Labels: cla-signed

#57292 name client/web entrypoint bundles after their entrypoint, not a custom name
  client/app-shell/src/app-shell.tsx
  client/build-config/src/esbuild/stylePlugin.ts
  client/observability-server/BUILD.bazel
  client/observability-server/src/webBundleSize/__mocks__/assets/scripts/app.js
  client/observability-server/src/webBundleSize/__mocks__/assets/scripts/app.js.br
  client/observability-server/src/webBundleSize/__mocks__/assets/scripts/app.js.gz
  client/observability-server/src/webBundleSize/__mocks__/assets/styles/app.123.bundle.br
  client/observability-server/src/webBundleSize/__mocks__/assets/styles/app.123.css
  client/observability-server/src/webBundleSize/__mocks__/assets/styles/app.123.css.gz
  client/observability-server/src/webBundleSize/getBundleSizeStats.test.ts
  client/web/BUILD.bazel
  client/web/bundlesize.config.js
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/manifestPlugin.ts
  client/web/dev/utils/get-index-html.ts
  client/web/src/enterprise/app/main.tsx
  cmd/frontend/internal/app/ui/app.html
  cmd/frontend/internal/app/ui/embed.html
  doc/dev/how-to/test_phabricator.md
  doc/dev/setup/troubleshooting.md
  ui/assets/manifest.go
Labels: cla-signed

#57376 Revert "name client/web entrypoint bundles after their entrypoint, no…
  client/app-shell/src/app-shell.tsx
  client/build-config/src/esbuild/stylePlugin.ts
  client/observability-server/BUILD.bazel
  client/observability-server/src/webBundleSize/__mocks__/assets/scripts/app.bundle.js
  client/observability-server/src/webBundleSize/__mocks__/assets/scripts/app.bundle.js.br
  client/observability-server/src/webBundleSize/__mocks__/assets/scripts/app.bundle.js.gz
  client/observability-server/src/webBundleSize/__mocks__/assets/styles/app.123.bundle.css
  client/observability-server/src/webBundleSize/__mocks__/assets/styles/app.123.bundle.css.br
  client/observability-server/src/webBundleSize/__mocks__/assets/styles/app.123.bundle.css.gz
  client/observability-server/src/webBundleSize/getBundleSizeStats.test.ts
  client/web/BUILD.bazel
  client/web/bundlesize.config.js
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/manifestPlugin.ts
  client/web/dev/utils/get-index-html.ts
  client/web/src/enterprise/app-main.tsx
  cmd/frontend/internal/app/ui/app.html
  cmd/frontend/internal/app/ui/embed.html
  doc/dev/how-to/test_phabricator.md
  doc/dev/setup/troubleshooting.md
  ui/assets/manifest.go
Labels: cla-signed

#57372 [bug] Fix user permissions page with no external accounts
  CHANGELOG.md
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  client/web/src/enterprise/user/settings/auth/__snapshots__/UserSettingsPermissionsPage.test.tsx.snap
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/internal/authz/resolvers/permissions_info.go
  cmd/frontend/internal/authz/resolvers/resolver.go
Labels: cla-signed, team/iam, backport 5.2

#57380 bzl: fix ownership of generated monitoring config
  monitoring/BUILD.bazel
Labels: cla-signed

#57375 [bug] Display user permissions even if the GQL resolver has errors
  CHANGELOG.md
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/internal/authz/resolvers/permissions_info.go
  internal/database/perms_store.go
  internal/database/perms_store_test.go
Labels: cla-signed, team/iam

#57388 Chore: move app scripts out of enterprise
  cmd/sourcegraph/README.md
  dev/app/app-stamp-vars.sh
  dev/app/app-version.sh
  dev/app/build-backend.sh
  dev/app/build-windows.sh
  dev/app/build.sh
  dev/app/create-github-release.sh
  dev/app/create-update-manifest.sh
  dev/app/detect-platform.sh
  dev/app/tauri-build.sh
  doc/cody/overview/app/release-pipeline.md
  doc/dev/background-information/app/windows.md
  enterprise/dev/ci/scripts/release-app.sh
  src-tauri/README.md
Labels: cla-signed

#57390 Chore: move migrator out of enterprise
  cmd/migrator/BUILD.bazel
  cmd/migrator/main.go
  cmd/server/BUILD.bazel
  dev/backcompat/bazel-backcompat.sh
  dev/check/go-dbconn-import.sh
  doc/admin/updates/migrator/migrator-operations.md
  enterprise/cmd/README.md
  enterprise/cmd/migrator/BUILD.bazel
  enterprise/cmd/migrator/CODENOTIFY
  enterprise/cmd/migrator/README.md
  enterprise/cmd/migrator/image_test.yaml
  enterprise/cmd/migrator/main.go
Labels: cla-signed

#57393 Chore: simplify enterprise init in `worker`
  cmd/worker/shared/BUILD.bazel
  cmd/worker/shared/main.go
  cmd/worker/shared/service.go
Labels: cla-signed

#57397 Fixup script path after move
  dev/ci/integration/executors/run.sh
Labels: cla-signed

#57395 chore: Delete commented out code
  dev/codeintel-qa/cmd/clone-and-index/main.go
Labels: cla-signed

#57398 Fixup script path after move
  dev/ci/integration/executors/test.sh
Labels: cla-signed

#57394 Telemetry: fix nil panic
  internal/telemetry/besteffort.go
  internal/telemetry/telemetrytest/BUILD.bazel
  internal/telemetry/telemetrytest/telemetrytest_test.go
Labels: cla-signed, backport 5.2, backport/bugfix

#57364 release: update 5.2.1 release to 10am SAST
  dev/release/release-config.jsonc
Labels: cla-signed

#57406 remove lighthouse (frontend auditing for perf, etc.)
  .buildkite/pipeline.async.yml
  dev/ci/generate-lighthouse-slack-report.sh
  doc/dev/how-to/testing.md
  lighthouserc.js
  package.json
  pnpm-lock.yaml
  third-party-licenses/ThirdPartyLicenses.csv
Labels: cla-signed

#57381 JetBrains: handle nullable agent properties including `displayText`
  client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/AutocompleteContext.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/ChatMessage.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/Message.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/RecipeInfo.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/ServerInfo.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/api/Message.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Chat.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatMessage.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Interaction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Transcript.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/InlineAutocompleteList.java
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt
  client/jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/MessagePanel.kt
Labels: cla-signed

#57408 remove unused/unneeded esbuild plugins
  client/app-shell/dev/esbuild/build.ts
  client/build-config/src/esbuild/plugins.ts
  client/web/dev/esbuild/build.ts
  client/web/dev/esbuild/htmlIndexPlugin.ts
Labels: cla-signed

#57338 Flagged prompt data in events
  cmd/cody-gateway/internal/actor/actor.go
  cmd/cody-gateway/internal/events/events.go
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#57403 Allow to edit code host config temporarily in local dev by default
  sg.config.yaml
Labels: cla-signed

#57383 search jobs: add state aggregation to GetSearchJob
  cmd/frontend/internal/search/httpapi/export.go
  cmd/frontend/internal/search/resolvers/search_job.go
  cmd/worker/internal/search/exhaustive_search_test.go
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/store/exhaustive_search_jobs.go
  internal/search/exhaustive/store/store.go
Labels: cla-signed

#57417 sg: fix sg ops issue with dogfood-k8s
  dev/sg/internal/images/dockerhub.go
  dev/sg/internal/images/gcr.go
  dev/sg/internal/images/helm.go
  dev/sg/internal/images/registry.go
Labels: cla-signed

#57416 graphqlbackend: remove unused repositoryConnectionResolver
  cmd/frontend/graphqlbackend/repositories.go
Labels: cla-signed

#57387 Use focus-visible instead of focus pseudo selector
  BUILD.bazel
  client/branded/src/search-ui/components/QueryExamples.module.scss
  client/branded/src/search-ui/components/RepoMetadata.module.scss
  client/branded/src/search-ui/input/SearchContextDropdown.module.scss
  client/jetbrains/webview/src/search/input/JetBrainsToggles.module.scss
  client/web/src/enterprise/insights/components/views/card/InsightCard.module.scss
  client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.module.scss
  client/wildcard/src/components/Button/Button.module.scss
  client/wildcard/src/global-styles/base.scss
  client/wildcard/src/global-styles/custom-forms.scss
  client/wildcard/src/global-styles/forms.scss
Labels: cla-signed

#57410 rename env var WEBPACK_DEV_SERVER to WEB_BUILDER_DEV_SERVER
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/tmpl.go
  cmd/frontend/main.go
  cmd/sourcegraph/main.go
  dev/sg/sg.config.example.yaml
  sg.config.yaml
  ui/assets/doc.go
Labels: cla-signed

#57422 nix: use go1.21
  flake.lock
  shell.nix
Labels: cla-signed

#57363 gomod: update zoekt to allow CTAGS_COMMAND=ctags
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#57423 nix: do not manage bazel on MacOS
  shell.nix
Labels: cla-signed

#57409 add sentry esbuild plugin
  client/web/dev/esbuild/build.ts
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57275 bext: skip github e2e tests
  client/browser/src/end-to-end/github.test.ts
  client/browser/src/end-to-end/gitlab.test.ts
Labels: browser-extension, cla-signed

#56800 Add MATLAB search-based code navigation
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/scip-syntax/queries/matlab/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/languages.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_matlab.snap
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/matlab/highlights.scm
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/matlab/injections.scm
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/matlab/locals.scm
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/highlights.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/parsers.rs
  internal/gosyntect/languages.go
  internal/highlight/language.go
Labels: cla-signed

#57421 graphqlbackend: remove experimental User.invitableCollaborators
  CHANGELOG.md
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user_collaborators.go
  cmd/frontend/graphqlbackend/user_collaborators_test.go
Labels: cla-signed

#57420 search: do not specify user or org id from search contexts
  internal/search/repos/repos.go
Labels: cla-signed

#57425 database: remove ReposListOptions UserID and OrgID
  internal/database/repos.go
  internal/database/repos_test.go
Labels: cla-signed

#57439 add back bazel dep for postcss-focus-visible
  BUILD.bazel
Labels: cla-signed

#57432 show "Reload" for esbuild dynamic import errors
  client/web/src/components/ErrorBoundary.test.tsx
  client/web/src/components/ErrorBoundary.tsx
  client/web/src/components/__snapshots__/ErrorBoundary.test.tsx.snap
  client/web/src/monitoring/index.ts
  client/web/src/monitoring/shouldErrorBeReported.ts
Labels: cla-signed

#57446 clean up client/vscode usage of icons and monaco
  client/vscode/.stylelintrc.json
  client/vscode/BUILD.bazel
  client/vscode/scripts/build.ts
  client/vscode/src/webview/index.scss
  client/vscode/src/webview/initialize.ts
  client/vscode/src/webview/search-panel/api.ts
  client/vscode/src/webview/search-panel/index.tsx
  client/vscode/src/webview/sidebars/help/HelpSidebarView.tsx
  client/vscode/src/webview/theming/highlight.scss
  client/vscode/src/webview/theming/monaco.scss
  client/vscode/src/webview/theming/monacoTheme.ts
  client/vscode/tests/vsce.test.ts
  client/vscode/webpack.config.js
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57436 migrate from storybook deprecated argTypes.defaultValue
  client/browser/src/browser-extension/options-menu/OptionsPage.story.tsx
  client/web/src/batches/RepoBatchChangesButton.story.tsx
  client/web/src/components/diff/DiffStat.story.tsx
  client/web/src/components/diff/FileDiffHunks.story.tsx
  client/web/src/components/diff/FileDiffNode.story.tsx
  client/web/src/components/time/Duration.story.tsx
  client/web/src/enterprise/batches/DropdownButton.story.tsx
  client/web/src/enterprise/batches/batch-spec/TabBar.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/editor/EditorFeedbackPanel.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/editor/MonacoBatchSpecEditor.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/library/ReplaceSpecModal.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/ImportingChangesetsPreviewList.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreview.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreviewList.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/CancelExecutionModal.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ExecutionStatsBar.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ReadOnlyBatchSpecForm.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceStateIcon.story.tsx
  client/web/src/enterprise/batches/close/BatchChangeCloseAlert.story.tsx
  client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx
  client/web/src/enterprise/batches/detail/ActiveExecutionNotice.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeStatsCard.story.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.story.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.story.tsx
  client/web/src/enterprise/batches/list/BatchChangeNode.story.tsx
  client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.story.tsx
  client/web/src/enterprise/batches/list/BatchChangesListIntro.story.tsx
  client/web/src/enterprise/batches/list/GettingStarted.story.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.story.tsx
  client/web/src/enterprise/batches/preview/list/PreviewList.story.tsx
  client/web/src/enterprise/batches/settings/AddCredentialModal.story.tsx
  client/web/src/nav/UserNavItem.story.tsx
  client/web/src/repo/commits/GitCommitNode.story.tsx
  client/web/src/site-admin/WebhookInfoLogPageHeader.story.tsx
  client/web/src/site-admin/webhooks/MessagePanel.story.tsx
  client/web/src/site-admin/webhooks/StatusCode.story.tsx
  client/web/src/site-admin/webhooks/WebhookLogNode.story.tsx
  client/web/src/site-admin/webhooks/WebhookLogPage.story.tsx
  client/web/src/site-admin/webhooks/WebhookLogPageHeader.story.tsx
  client/wildcard/src/components/Button/story/Button.story.tsx
  client/wildcard/src/components/Charts/core/components/SvgRoot.story.tsx
  client/wildcard/src/components/Feedback/FeedbackPrompt/FeedbackPrompt.story.tsx
  client/wildcard/src/components/LoadingSpinner/LoadingSpinner.story.tsx
  client/wildcard/src/components/PageSelector/PageSelector.story.tsx
  client/wildcard/src/components/PageSwitcher/PageSwitcher.story.tsx
  client/wildcard/src/components/Popover/story/Popover.story.tsx
  client/wildcard/src/components/Typography/Typography.story.tsx
  client/wildcard/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
Labels: cla-signed

#57437 migrate to storybook 7
  .eslintrc.js
  BUILD.bazel
  client/storybook/BUILD.bazel
  client/storybook/package.json
  client/storybook/src/decorators/withChromaticThemes/withChromaticThemes.tsx
  client/storybook/src/main.ts
  client/storybook/src/preview.ts
  client/storybook/src/themes.ts
  client/web-sveltekit/package.json
  client/web/BUILD.bazel
  client/web/src/cody/update/AboutPageUpdate.story.tsx
  client/web/src/cody/update/InstallModal.story.tsx
  client/web/src/cody/update/ReviewAndInstallModal.story.tsx
  client/web/src/cody/update/UpdateGlobalNav.story.tsx
  client/web/src/cody/update/UpdateInfoContent.story.tsx
  client/web/src/enterprise/insights/components/form/repositories-field/RepositoriesField.tsx
  client/wildcard/BUILD.bazel
  client/wildcard/src/components/Alert/Alert.story.tsx
  client/wildcard/src/components/Button/story/ButtonVariants.tsx
  client/wildcard/src/global-styles/GlobalStylesStory/FormFieldVariants/FormFieldVariants.tsx
  client/wildcard/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
  dev/sg/linters/linters.go
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57449 rename {webpack => web}.manifest.json
  .gitignore
  client/observability-server/src/webBundleSize/getBundleSizeStats.test.ts
  client/observability-server/src/webBundleSize/getBundleSizeStats.ts
  client/observability-server/src/webBundleSize/index.ts
  client/web/dev/esbuild/manifestPlugin.ts
  client/web/dev/server/bazel.server.ts
  client/web/dev/server/development.server.ts
  client/web/dev/server/production.server.ts
  client/web/dev/utils/get-index-html.ts
  client/web/src/integration/context.ts
  client/web/webpack.bazel.config.js
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/handlers_test.go
  dev/Caddyfile
  dev/sg/linters/linters.go
  doc/dev/setup/troubleshooting.md
  ui/assets/assets.go
  ui/assets/dev.go
  ui/assets/doc.go
  ui/assets/enterprise/assets.go
  ui/assets/manifest.go
Labels: cla-signed

#57448 rename {WEBPACK => WEB_BUILDER}_SERVE_INDEX env var
  client/web/README.md
  client/web/dev/server/production.server.ts
  client/web/dev/utils/create-js-context.ts
  client/web/dev/utils/environment-config.ts
  client/web/webpack.bazel.config.js
  client/web/webpack.config.js
  sg.config.yaml
Labels: cla-signed

#57438 use vite instead of webpack for storybooks
  client/storybook/BUILD.bazel
  client/storybook/README.md
  client/storybook/package.json
  client/storybook/src/dllPlugin/ensureDllBundleIsReady.ts
  client/storybook/src/dllPlugin/getVendorModules.ts
  client/storybook/src/dllPlugin/getWebpackStats.ts
  client/storybook/src/dllPlugin/index.ts
  client/storybook/src/dummyEventSourcePolyfill.ts
  client/storybook/src/environment-config.ts
  client/storybook/src/main.ts
  client/storybook/src/webpack.config.common.ts
  client/storybook/src/webpack.config.dll.ts
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57450 fix storybook npm deps
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57451 remove client/extension-api stub
  client/extension-api/BUILD.bazel
  client/extension-api/package.json
  client/extension-api/src/index.js
  client/extension-api/tsconfig.json
Labels: cla-signed

#57447 use esbuild for building client/vscode
  .vscode/launch.json
  client/vscode/.vscodeignore
  client/vscode/BUILD.bazel
  client/vscode/CONTRIBUTING.md
  client/vscode/globals.d.ts
  client/vscode/gulpfile.js
  client/vscode/package.json
  client/vscode/scripts/build.ts
  client/vscode/webpack.config.js
  package.json
Labels: cla-signed

#57231 use esbuild for browser extension builds
  client/browser/BUILD.bazel
  client/browser/README.md
  client/browser/config/BUILD.bazel
  client/browser/config/esbuild.bazel.js
  client/browser/config/esbuild.ts
  client/browser/config/utils.ts
  client/browser/config/webpack/base.config.bazel.ts
  client/browser/config/webpack/base.config.ts
  client/browser/config/webpack/development.config.ts
  client/browser/config/webpack/production.config.bazel.ts
  client/browser/config/webpack/production.config.ts
  client/browser/scripts/build.ts
  client/browser/scripts/development.ts
  client/browser/scripts/esbuildPlugins.ts
  client/browser/scripts/tasks.ts
  client/browser/src/shared/extensionHostWorker.ts
  client/build-config/BUILD.bazel
  client/build-config/src/esbuild/BUILD.bazel
  client/build-config/src/esbuild/stylePlugin.ts
  client/shared/BUILD.bazel
  client/shared/src/api/extension/worker.ts
  client/web/BUILD.bazel
Labels: cla-signed

#57452 globally disable the id-length rule (long live vars named `i`)
  .eslintrc.js
  client/branded/src/components/ToggleBig.story.tsx
  client/branded/src/search-ui/input/codemirror/active-filter.ts
  client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
  client/branded/src/search-ui/results/AnnotatedSearchExample.tsx
  client/shared/src/search/query/patternMatcher.test.ts
  client/web/src/repo/blob/codemirror/blame-decorations.tsx
  client/wildcard/src/components/Typography/Heading/H1.tsx
  client/wildcard/src/components/Typography/Heading/H2.tsx
  client/wildcard/src/components/Typography/Heading/H3.tsx
  client/wildcard/src/components/Typography/Heading/H4.tsx
  client/wildcard/src/components/Typography/Heading/H5.tsx
  client/wildcard/src/components/Typography/Heading/H6.tsx
  dev/release/src/release.ts
Labels: cla-signed

#57455 temporarily disable Chromatic upload that is failing on main
  dev/ci/internal/ci/operations.go
  doc/dev/background-information/ci/reference.md
Labels: cla-signed

#57268 search: Cleanup CodeMirror query input (part 1)
  client/branded/BUILD.bazel
  client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.story.tsx
  client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
  client/branded/src/search-ui/input/CodeMirrorQueryInput.module.scss
  client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
  client/branded/src/search-ui/input/codemirror/active-filter.ts
  client/branded/src/search-ui/input/codemirror/parsedQuery.ts
  client/branded/src/search-ui/input/codemirror/token-info.ts
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
  client/branded/src/search-ui/input/experimental/codemirror/history.ts
  client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
  client/shared/src/components/CodeMirrorEditor.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/suggestions/SearchTypeSuggestionsInput.tsx
  client/web/src/search/SearchConsolePage.tsx
  client/web/src/search/input/ExperimentalSearchInput.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
Labels: cla-signed

#57453 Update changelog for 5.2.1 backports
  CHANGELOG.md
Labels: cla-signed, team/iam

#57463 Revert "temporarily disable Chromatic upload that is failing on main (#57455)"
  client/storybook/src/main.ts
  dev/ci/internal/ci/operations.go
  doc/dev/background-information/ci/reference.md
Labels: cla-signed

#57444 gitserver: Drop vcs_syncer filename prefix
  cmd/gitserver/internal/vcssyncer/BUILD.bazel
  cmd/gitserver/internal/vcssyncer/git.go
  cmd/gitserver/internal/vcssyncer/go_modules.go
  cmd/gitserver/internal/vcssyncer/go_modules_test.go
  cmd/gitserver/internal/vcssyncer/jvm_packages.go
  cmd/gitserver/internal/vcssyncer/jvm_packages_test.go
  cmd/gitserver/internal/vcssyncer/npm_packages.go
  cmd/gitserver/internal/vcssyncer/npm_packages_test.go
  cmd/gitserver/internal/vcssyncer/packages_syncer.go
  cmd/gitserver/internal/vcssyncer/packages_syncer_test.go
  cmd/gitserver/internal/vcssyncer/perforce.go
  cmd/gitserver/internal/vcssyncer/perforce_test.go
  cmd/gitserver/internal/vcssyncer/python_packages.go
  cmd/gitserver/internal/vcssyncer/python_packages_test.go
  cmd/gitserver/internal/vcssyncer/ruby_packages.go
  cmd/gitserver/internal/vcssyncer/rust_packages.go
  cmd/gitserver/internal/vcssyncer/syncer.go
  cmd/gitserver/internal/vcssyncer/syncer_test.go
Labels: cla-signed

#57442 cleanup: Move PermSyncOpts out of protocol package
  cmd/frontend/auth/BUILD.bazel
  cmd/frontend/auth/user.go
  cmd/frontend/backend/user_emails.go
  cmd/frontend/graphqlbackend/external_accounts.go
  cmd/frontend/graphqlbackend/external_accounts_test.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_invitations.go
  cmd/frontend/graphqlbackend/org_invitations_test.go
  cmd/frontend/graphqlbackend/org_test.go
  cmd/frontend/graphqlbackend/user_emails_test.go
  cmd/frontend/internal/authz/resolvers/BUILD.bazel
  cmd/frontend/internal/authz/resolvers/resolver.go
  cmd/frontend/internal/authz/resolvers/resolver_test.go
  cmd/frontend/internal/authz/webhooks/BUILD.bazel
  cmd/frontend/internal/authz/webhooks/github.go
  cmd/frontend/internal/authz/webhooks/github_test.go
  cmd/frontend/internal/httpapi/webhookhandlers/BUILD.bazel
  cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
  cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
  internal/authz/permssync/BUILD.bazel
  internal/authz/permssync/permssync.go
  internal/authz/permssync/permssync_test.go
  internal/repoupdater/protocol/BUILD.bazel
  internal/repoupdater/protocol/repoupdater.go
Labels: cla-signed

#57430 Cleanup auth and init pages design
  client/web/BUILD.bazel
  client/web/src/auth/AuthPageWrapper.module.scss
  client/web/src/auth/AuthPageWrapper.tsx
  client/web/src/auth/CloudSignUpPage.module.scss
  client/web/src/auth/CloudSignUpPage.story.tsx
  client/web/src/auth/CloudSignUpPage.tsx
  client/web/src/auth/OrDivider.story.tsx
  client/web/src/auth/PostSignUpPage.story.tsx
  client/web/src/auth/RequestAccessPage.module.scss
  client/web/src/auth/RequestAccessPage.story.tsx
  client/web/src/auth/RequestAccessPage.tsx
  client/web/src/auth/ResetPasswordPage.module.scss
  client/web/src/auth/ResetPasswordPage.story.tsx
  client/web/src/auth/ResetPasswordPage.tsx
  client/web/src/auth/SignInPage.module.scss
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/SignInSignUpCommon.module.scss
  client/web/src/auth/SignUpForm.tsx
  client/web/src/auth/SignUpPage.module.scss
  client/web/src/auth/SignUpPage.story.tsx
  client/web/src/auth/SignUpPage.tsx
  client/web/src/auth/SignupEmailField.tsx
  client/web/src/auth/UnlockAccount.module.scss
  client/web/src/auth/UnlockAccount.story.tsx
  client/web/src/auth/UnlockAccount.tsx
  client/web/src/auth/VsCodeSignUpPage.story.tsx
  client/web/src/auth/VsCodeSignUpPage.tsx
  client/web/src/auth/__snapshots__/RequestAccessPage.test.tsx.snap
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/auth/components/ExternalsAuth.module.scss
  client/web/src/auth/components/ExternalsAuth.tsx
  client/web/src/components/branding/BrandLogo.tsx
  client/web/src/components/externalServices/ExternalServiceEditPage.story.tsx
  client/web/src/components/externalServices/ExternalServicePage.story.tsx
  client/web/src/routes.tsx
  client/web/src/site-admin/init/SiteInitPage.module.scss
  client/web/src/site-admin/init/SiteInitPage.story.tsx
  client/web/src/site-admin/init/SiteInitPage.test.tsx
  client/web/src/site-admin/init/SiteInitPage.tsx
  client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
Labels: cla-signed

#57465 remove CI reference auto-generated documentation
  dev/ci/gen-pipeline.go
  dev/sg/ci/subcommands.go
  doc/dev/background-information/ci/development.md
  doc/dev/background-information/ci/index.md
  doc/dev/background-information/ci/reference.md
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#57467 bzl: add a `--config go-verbose` to enable verbose tests
  .bazelrc
  dev/ci/internal/ci/bazel_operations.go
  doc/dev/background-information/bazel/faq.md
Labels: cla-signed

#57441 repoupdater: Remove endpoints for external services
  cmd/frontend/backend/BUILD.bazel
  cmd/frontend/backend/external_services.go
  cmd/frontend/backend/external_services_test.go
  cmd/frontend/backend/mocks_temp.go
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/repo-updater/internal/repoupdater/BUILD.bazel
  cmd/repo-updater/internal/repoupdater/grpc_server.go
  cmd/repo-updater/internal/repoupdater/server.go
  cmd/repo-updater/internal/repoupdater/server_test.go
  internal/repoupdater/client.go
  internal/repoupdater/protocol/BUILD.bazel
  internal/repoupdater/protocol/repoupdater.go
  internal/repoupdater/protocol/repoupdater_test.go
  internal/repoupdater/v1/repoupdater.pb.go
  internal/repoupdater/v1/repoupdater.proto
  internal/repoupdater/v1/repoupdater_grpc.pb.go
  mockgen.temp.yaml
Labels: cla-signed

#57382 search: Refactor CodeMirror query input (part 2)
  client/branded/BUILD.bazel
  client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.story.tsx
  client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
  client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
  client/branded/src/search-ui/input/QueryInput.ts
  client/branded/src/search-ui/input/SearchBox.tsx
  client/branded/src/search-ui/input/codemirror/event-handlers.ts
  client/branded/src/search-ui/input/codemirror/index.ts
  client/branded/src/search-ui/input/codemirror/multiline.ts
  client/branded/src/search-ui/input/codemirror/queryState.ts
  client/branded/src/search-ui/input/codemirror/react.ts
  client/branded/src/search-ui/input/codemirror/token-info.ts
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
  client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
  client/jetbrains/webview/src/search/input/JetBrainsSearchBox.tsx
  client/shared/src/components/CodeMirrorEditor.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/suggestions/SearchTypeSuggestionsInput.tsx
  client/web/src/search/SearchConsolePage.tsx
Labels: cla-signed

#57466 app: remove old app release scripts and release types
  dev/ci/internal/ci/operations.go
  dev/ci/internal/ci/pipeline.go
  dev/ci/scripts/release-app.sh
Labels: cla-signed

#57483 update go to 1.20.9
  .github/workflows/sg-setup.yml
  .tool-versions
  WORKSPACE
  dev/sg/checks.go
Labels: cla-signed

#57469 sg: remove bazel gen notice
  dev/sg/sg_generate.go
Labels: cla-signed

#57471 authz: Don't return error for subrepoperm constructor
  cmd/embeddings/shared/main.go
  cmd/frontend/internal/authz/BUILD.bazel
  cmd/frontend/internal/authz/init.go
  cmd/gitserver/internal/integration_tests/tree_test.go
  cmd/gitserver/shared/shared.go
  cmd/precise-code-intel-worker/shared/shared.go
  cmd/repo-updater/shared/main.go
  cmd/worker/shared/main.go
  internal/authz/providers/authz.go
  internal/authz/providers/authz_test.go
  internal/authz/providers/bitbucketcloud/provider_test.go
  internal/authz/providers/perforce/protects_test.go
  internal/authz/subrepoperms/sub_repo_perms.go
  internal/authz/subrepoperms/sub_repo_perms_test.go
  internal/search/symbol/symbol_test.go
Labels: cla-signed

#57493 Verify signup and login pages in chromatic
  client/web/src/auth/CloudSignUpPage.story.tsx
  client/web/src/auth/RequestAccessPage.story.tsx
  client/web/src/auth/ResetPasswordPage.story.tsx
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/auth/SignUpPage.story.tsx
  client/web/src/auth/UnlockAccount.story.tsx
  client/web/src/auth/VsCodeSignUpPage.story.tsx
  client/web/src/site-admin/init/SiteInitPage.story.tsx
Labels: cla-signed

#57494 chromatic: Fixup project detection and emit TurboSnap metadata with vite
  client/storybook/BUILD.bazel
  client/storybook/src/main.ts
  dev/ci/internal/ci/operations.go
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57492 e2e tests: update sourcegraph group name
  client/browser/src/end-to-end/gitlab.test.ts
Labels: cla-signed

#57497 remove storybook addon-docs
  client/storybook/src/main.ts
  client/storybook/src/preview.ts
  client/web-sveltekit/.storybook/main.ts
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#57501 bazelignore storybook static files
  .bazelignore
Labels: cla-signed

#57491 Doc: update doc link for release.channel and pings
  doc/admin/pings.md
Labels: cla-signed

#57504 app: fix script paths
  dev/app/app-version.sh
  dev/app/build-backend.sh
  dev/app/build.sh
  dev/app/create-github-release.sh
  dev/app/create-update-manifest.sh
  dev/app/tauri-build.sh
Labels: cla-signed
