Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-04, with the labels that each got.

#50248 dep: resolve CVE-2023-0464 in base image 1/2
  docker-images/alpine-3.14/Dockerfile
Labels: cla-signed

#50241 embeddings: per repo mutex when getting/downloading an index
  enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
  enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
Labels: cla-signed, backport 5.0

#49791 webhooks: wait to enqueue webhook jobs until transaction completes
  doc/admin/config/webhooks/outgoing.md
  enterprise/cmd/worker/internal/batches/workers/bulk_processor_worker.go
  enterprise/internal/batches/processor/bulk_processor.go
  enterprise/internal/batches/processor/bulk_processor_test.go
  enterprise/internal/batches/reconciler/executor.go
  enterprise/internal/batches/reconciler/executor_test.go
  enterprise/internal/batches/reconciler/reconciler.go
  enterprise/internal/batches/reconciler/reconciler_test.go
  enterprise/internal/batches/service/service.go
  enterprise/internal/batches/service/service_apply_batch_change.go
  internal/database/mocks_temp.go
  internal/database/outbound_webhook_jobs.go
  internal/httpcli/client.go
Labels: team/batchers, webhooks, cla-signed, confirm-no-backport

#50261 dep: resolve CVE-2023-0464 in base image 2/2
  cmd/blobstore/Dockerfile
  cmd/frontend/Dockerfile
  cmd/github-proxy/Dockerfile
  cmd/gitserver/Dockerfile
  cmd/loadtest/Dockerfile
  cmd/migrator/Dockerfile
  cmd/repo-updater/Dockerfile
  cmd/searcher/Dockerfile
  cmd/server/Dockerfile
  cmd/symbols/Dockerfile
  cmd/worker/Dockerfile
  dev/build-tracker/Dockerfile
  dev/sg/Dockerfile
  dev/src-expose/Dockerfile
  docker-images/blobstore/Dockerfile
  docker-images/grafana/Dockerfile
  docker-images/jaeger-agent/Dockerfile
  docker-images/jaeger-all-in-one/Dockerfile
  docker-images/opentelemetry-collector/Dockerfile
  docker-images/postgres_exporter/Dockerfile
  docker-images/prometheus/Dockerfile
  docker-images/syntax-highlighter/Dockerfile
  enterprise/cmd/batcheshelper/Dockerfile
  enterprise/cmd/bundled-executor/Dockerfile
  enterprise/cmd/embeddings/Dockerfile
  enterprise/cmd/executor/docker-image/Dockerfile
  enterprise/cmd/frontend/Dockerfile
  enterprise/cmd/gitserver/Dockerfile
  enterprise/cmd/precise-code-intel-worker/Dockerfile
  enterprise/cmd/worker/Dockerfile
  internal/cmd/progress-bot/Dockerfile
  internal/cmd/search-blitz/Dockerfile
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed, SSDLC, backport 5.0

#50265 embeddings: encode RepoEmbeddingIndex in chunks suggestions
  enterprise/internal/embeddings/index_storage.go
  enterprise/internal/embeddings/index_storage_test.go
Labels: cla-signed

#50254 repositories list: change label from "View Permissions" to "Permissions"
  client/web/src/site-admin/RepositoryNode.tsx
Labels: cla-signed, team/iam

#50275 docs: update admin code host page
  doc/admin/external_service/index.md
Labels: cla-signed, team/iam

#50274 [docs] Support GitHub fine-grained access tokens with limitations
  CHANGELOG.md
  doc/admin/external_service/github.md
Labels: cla-signed, team/iam

#50228 chore: load user only once from the database in `UserResolver`.
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/graphqlbackend/default_settings.go
  cmd/frontend/graphqlbackend/event_logs_test.go
  cmd/frontend/graphqlbackend/executor_secret_access_log.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/person.go
  cmd/frontend/graphqlbackend/settings.go
  cmd/frontend/graphqlbackend/settings_subject.go
  cmd/frontend/graphqlbackend/teams.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
  cmd/frontend/graphqlbackend/users_create.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  enterprise/cmd/frontend/internal/authz/resolvers/permissions_info.go
  enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
  enterprise/cmd/frontend/internal/authz/resolvers/users.go
  internal/actor/actor.go
  internal/auth/site_admin.go
  internal/database/survey_responses.go
Labels: debt, team/repo-management, cla-signed, storm

#50224 [embeddings][optimise] Encode RepoEmbeddingIndex in chunks
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/internal/embeddings/index_storage.go
  enterprise/internal/embeddings/index_storage_test.go
Labels: cla-signed, team/iam, backport 5.0

#50119 update team reviewers
  .github/workflows/licenses-update.yml
  dev/comby-install-or-upgrade.sh
Labels: cla-signed

#50287 codeintel: Move SCIP utilities to `sourcegraph/scip`
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_hover.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_locations.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_monikers.go
  enterprise/internal/codeintel/shared/types/scip_canonicalize.go
  enterprise/internal/codeintel/shared/types/scip_flatten.go
  enterprise/internal/codeintel/shared/types/scip_sanitize.go
  enterprise/internal/codeintel/shared/types/scip_sort.go
  enterprise/internal/codeintel/shared/types/scip_test.go
  enterprise/internal/codeintel/uploads/internal/background/scip.go
  enterprise/internal/codeintel/uploads/shared/scip_symbols.go
  enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
  go.mod
  go.sum
Labels: team/code-intelligence, cla-signed, team/language-platform

#50243 Print stack trace on panic in GraphQL tests
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/testing.go
Labels: cla-signed

#50083 Code monitors: truncate long Slack blocks
  enterprise/internal/codemonitors/background/email.go
  enterprise/internal/codemonitors/background/slack.go
  enterprise/internal/codemonitors/background/slack_test.go
  enterprise/internal/codemonitors/background/test_mocks.go
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_with_truncated_matches.golden
Labels: cla-signed

#50143 Cody: locally configure embedding upload URL
  sg.config.yaml
Labels: cla-signed

#50244 zoekt: update to sourcegraph/zoekt@0cb60676ea92e8904e4075743174adbb1ea47af6
  go.mod
  go.sum
Labels: cla-signed

#50292 permissions-center: fix the story, so it is not broken.
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
Labels: cla-signed, permissions-center

#50269 Revert PR#50153
  client/branded/src/search-ui/components/RepoFileLink.tsx
  client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
Labels: cla-signed

#50293 [backport][embeddings][optimise] Encode RepoEmbeddingIndex in chunks (#50224)
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/internal/embeddings/embed/embed.go
  enterprise/internal/embeddings/index_storage.go
  enterprise/internal/embeddings/index_storage_test.go
  enterprise/internal/embeddings/types.go
Labels: cla-signed

#50300 Update buildfiles 03/04
  WORKSPACE
  deps.bzl
  enterprise/internal/codeintel/shared/types/BUILD.bazel
  enterprise/internal/codeintel/uploads/internal/background/BUILD.bazel
  enterprise/internal/codeintel/uploads/shared/BUILD.bazel
Labels: cla-signed

#50211 blobstore: fix multipart uploads
  cmd/blobstore/internal/blobstore/blobstore_test.go
  cmd/blobstore/internal/blobstore/multipart.go
Labels: cla-signed

#50304 codeintel: Reorganize store interface methods
  enterprise/internal/codeintel/autoindexing/internal/background/mocks_test.go
  enterprise/internal/codeintel/autoindexing/internal/jobselector/job_selector.go
  enterprise/internal/codeintel/autoindexing/internal/store/BUILD.bazel
  enterprise/internal/codeintel/autoindexing/internal/store/store.go
  enterprise/internal/codeintel/autoindexing/internal/store/store_repositories.go
  enterprise/internal/codeintel/autoindexing/mocks_test.go
  enterprise/internal/codeintel/autoindexing/service.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/policies/internal/store/store.go
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/codeintel/ranking/mocks_test.go
  enterprise/internal/codeintel/sentinel/internal/store/store.go
  enterprise/internal/codeintel/uploads/internal/background/mocks_test.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents_test.go
  enterprise/internal/codeintel/uploads/internal/store/store.go
  enterprise/internal/codeintel/uploads/mocks_test.go
  enterprise/internal/codeintel/uploads/service.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50297 Bugfix: always return when an error is returned
  cmd/frontend/internal/httpapi/stream_blame.go
Labels: cla-signed

#50279 clean up Cody CSS to increase shareability and improve display in web app
  client/browser/src/shared/components/HoverOverlay.story.tsx
  client/cody-ui/.stylelintrc.json
  client/cody-ui/src/Chat.module.css
  client/cody-ui/src/Chat.tsx
  client/cody-ui/src/chat/CodeBlocks.module.css
  client/cody-ui/src/chat/CodeBlocks.tsx
  client/cody-ui/src/chat/ContextFiles.module.css
  client/cody-ui/src/chat/ContextFiles.tsx
  client/cody-ui/src/typings.d.ts
  client/cody-ui/src/utils/icons.tsx
  client/cody-ui/tsconfig.json
  client/cody-web/.stylelintrc.json
  client/cody-web/src/App.tsx
  client/cody-web/src/Chat.module.css
  client/cody-web/src/Chat.tsx
  client/cody-web/src/settings/Settings.tsx
  client/cody-web/vite.config.ts
  client/cody/.stylelintrc.json
  client/cody/tsconfig.json
  client/cody/vite.config.ts
  client/cody/webviews/App.css
  client/cody/webviews/Chat.css
  client/cody/webviews/Chat.module.css
  client/cody/webviews/Chat.tsx
  client/cody/webviews/FileLink.module.css
  client/cody/webviews/FileLink.tsx
  client/cody/webviews/UserHistory.tsx
  client/cody/webviews/typings.d.ts
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/repoRevisionSidebar/cody/RepoRevisionSidebarCody.module.scss
  client/web/src/repo/repoRevisionSidebar/cody/RepoRevisionSidebarCody.tsx
  client/web/webpack.config.js
  prettier.config.js
Labels: cla-signed, cody

#50309 [Backport 5.0] Code monitors: truncate long Slack blocks
  CHANGELOG.md
  enterprise/internal/codemonitors/background/email.go
  enterprise/internal/codemonitors/background/slack.go
  enterprise/internal/codemonitors/background/slack_test.go
  enterprise/internal/codemonitors/background/test_mocks.go
  enterprise/internal/codemonitors/background/testdata/TestSlackWebhook/golden_with_truncated_matches.golden
Labels: cla-signed

#50212 dev: use new Go blobstore implementation in dev env
  sg.config.yaml
Labels: cla-signed

#50320 bazel: bazel configure
  client/cody-shared/BUILD.bazel
  client/cody-ui/BUILD.bazel
  client/cody-ui/src/globals.d.ts
  client/cody-ui/tsconfig.json
  client/cody-web/src/globals.d.ts
  client/cody-web/tsconfig.json
  client/cody/tsconfig.json
  client/cody/webviews/globals.d.ts
Labels: cla-signed, team/code-exploration, JF/bazel

#50319 Fix bug with current period usage statistics calculation
  client/cody-ui/BUILD.bazel
  internal/database/event_logs.go
Labels: cla-signed

#50091 Fix external accounts data resolver
  cmd/frontend/graphqlbackend/external_account_data_resolver.go
  enterprise/cmd/frontend/internal/auth/saml/user.go
Labels: cla-signed, team/iam

#49821 Add permissions syncying stats api.
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/graphqlbackend/authz.graphql
  enterprise/cmd/frontend/internal/authz/resolvers/BUILD.bazel
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  enterprise/cmd/frontend/worker/auth/perms_syncer_scheduler.go
  enterprise/internal/database/mocks_temp.go
  enterprise/internal/database/perms_store.go
  enterprise/internal/database/perms_store_test.go
Labels: cla-signed, team/iam, confirm-no-backport

#49924 build frontend based on bzl artifact
  .bazelrc
  BUILD.bazel
  client/cody-ui/BUILD.bazel
  client/web/BUILD.bazel
  cmd/frontend/BUILD.bazel
  cmd/frontend/build.sh
  cmd/frontend/pre-build.sh
  enterprise/cmd/frontend/BUILD.bazel
  enterprise/cmd/frontend/build.sh
  enterprise/cmd/frontend/pre-build.sh
  enterprise/internal/codeintel/shared/gitserver/BUILD.bazel
  internal/insights/BUILD.bazel
  ui/assets/BUILD.bazel
  ui/assets/assets_dist.go
  ui/assets/load_manifest_dist.go
Labels: cla-signed

#50296 embeddings: disable document ranks per default
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/embeddings/shared/search.go
  enterprise/internal/embeddings/client.go
  enterprise/internal/embeddings/similarity_search.go
  enterprise/internal/embeddings/similarity_search_test.go
Labels: cla-signed

#50195 Add queue rank to permissions sync jobs table
  client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
  client/web/src/site-admin/permissions-center/backend.ts
  cmd/frontend/graphqlbackend/authz.graphql
  cmd/frontend/graphqlbackend/permissions_sync_jobs.go
  enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
  internal/database/permission_sync_jobs.go
Labels: cla-signed, team/iam

#50324 add default value for DOCKER_BAZEL
  cmd/blobstore/build.sh
  cmd/frontend/build.sh
  cmd/frontend/pre-build.sh
  cmd/github-proxy/build.sh
  cmd/gitserver/build.sh
  cmd/loadtest/build.sh
  cmd/migrator/build.sh
  cmd/repo-updater/build.sh
  cmd/searcher/build.sh
  cmd/worker/build.sh
  enterprise/cmd/frontend/build.sh
  enterprise/cmd/frontend/pre-build.sh
Labels: cla-signed

#50325 fix bash default for frontend build
  enterprise/cmd/frontend/build.sh
Labels: cla-signed

#50326 Revert docker bazel frontend
  .bazelrc
  BUILD.bazel
  client/web/BUILD.bazel
  cmd/frontend/BUILD.bazel
  cmd/frontend/build.sh
  cmd/frontend/pre-build.sh
  enterprise/cmd/frontend/BUILD.bazel
  enterprise/cmd/frontend/pre-build.sh
  enterprise/internal/codeintel/shared/gitserver/BUILD.bazel
  internal/insights/BUILD.bazel
  ui/assets/BUILD.bazel
  ui/assets/assets_dist.go
  ui/assets/load_manifest_dist.go
Labels: cla-signed

#50329 bazel: do not use `babel-preset-env` for mocha tests
  babel.config.js
  client/shared/src/testing/BUILD.bazel
  client/web/src/integration/BUILD.bazel
  dev/babel.bzl
  dev/defs.bzl
  dev/mocha.bzl
Labels: cla-signed, team/code-exploration, JF/bazel

#50315 codeintel: Reorganize git resolvers
  enterprise/cmd/frontend/internal/codeintel/BUILD.bazel
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  enterprise/internal/codeintel/codenav/transport/graphql/util_locations.go
  enterprise/internal/codeintel/policies/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/policies/transport/graphql/configuration_policy_resolver.go
  enterprise/internal/codeintel/policies/transport/graphql/root_resolver_previews.go
  enterprise/internal/codeintel/shared/resolvers/BUILD.bazel
  enterprise/internal/codeintel/shared/resolvers/cached_location_resolver.go
  enterprise/internal/codeintel/shared/resolvers/cached_location_resolver_factory.go
  enterprise/internal/codeintel/shared/resolvers/cached_location_resolver_test.go
  enterprise/internal/codeintel/shared/resolvers/git_commit_resolver.go
  enterprise/internal/codeintel/shared/resolvers/git_tree_entry_resolver.go
  enterprise/internal/codeintel/shared/resolvers/git_tree_submodule_resolver.go
  enterprise/internal/codeintel/shared/resolvers/gitresolvers/BUILD.bazel
  enterprise/internal/codeintel/shared/resolvers/gitresolvers/commit.go
  enterprise/internal/codeintel/shared/resolvers/gitresolvers/external_repo.go
  enterprise/internal/codeintel/shared/resolvers/gitresolvers/repo.go
  enterprise/internal/codeintel/shared/resolvers/gitresolvers/tree_entry.go
  enterprise/internal/codeintel/shared/resolvers/repository_resolver.go
  internal/codeintel/resolvers/git.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50310 codeintel: Reorganize store interface categories
  enterprise/internal/codeintel/autoindexing/internal/store/store.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/policies/internal/store/store.go
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/uploads/internal/store/store.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50327 Update to Go 1.19.7
  .tool-versions
Labels: cla-signed, SSDLC, backport 5.0

#50312 executors: Cleanup nightly AMI images after 60 days
  enterprise/cmd/executor/docker-mirror/build.sh
  enterprise/cmd/executor/docker-mirror/docker-mirror.pkr.hcl
  enterprise/cmd/executor/vm-image/build.sh
  enterprise/cmd/executor/vm-image/executor.pkr.hcl
Labels: cla-signed

#50337 Fix empty symbolInfo returned from gRPC causing non-nil value in API
  internal/symbols/client.go
  internal/symbols/v1/conversion.go
  internal/symbols/v1/conversion_test.go
Labels: cla-signed

#50288 Add embeddings to server behind env var
  cmd/server/shared/globals.go
  dev/prometheus/all/prometheus_targets.yml
  dev/prometheus/linux/prometheus_targets.yml
  dev/src-prof-services.json
  enterprise/cmd/server/build.sh
  enterprise/cmd/server/main.go
  enterprise/dev/src-prof-services.json
  sg.config.yaml
Labels: cla-signed

#50345 Ritza editing march 2023
  doc/code_navigation/how-to/configure_data_retention.md
  doc/code_navigation/how-to/index.md
  doc/code_navigation/how-to/index_a_go_repository.md
  doc/code_navigation/how-to/index_a_typescript_and_javascript_repository.md
  doc/code_navigation/index.md
  doc/code_search/reference/language.md
  doc/code_search/reference/structural.md
Labels: cla-signed

#50352 Fix timestamp window for event_logs queries to account for WAU edge cases
  internal/database/event_logs.go
Labels: cla-signed

#50239 fix typo in tooltip
  client/web/src/enterprise/insights/pages/insights/insight/components/actions/CodeInsightIndependentPageActions.tsx
Labels: cla-signed

#50355 standardize on cody-experimental feature flag name (not cody)
  client/web/src/enterprise/cody/search/CodySearchPage.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/nav/GlobalNavbar.tsx
Labels: cla-signed, cody

#50364 Code graph: provide server-side HTML title for settings page
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed

#50360 codeintel: Large-chunk reorganize sentinel store
  enterprise/internal/codeintel/sentinel/internal/store/matches.go
  enterprise/internal/codeintel/sentinel/internal/store/observability.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50350 codeintel: Large-chunk reorganize policies store
  enterprise/internal/codeintel/policies/internal/store/BUILD.bazel
  enterprise/internal/codeintel/policies/internal/store/configurations.go
  enterprise/internal/codeintel/policies/internal/store/configurations_test.go
  enterprise/internal/codeintel/policies/internal/store/global_metadata.go
  enterprise/internal/codeintel/policies/internal/store/global_metadata_test.go
  enterprise/internal/codeintel/policies/internal/store/observability.go
  enterprise/internal/codeintel/policies/internal/store/repository_matches.go
  enterprise/internal/codeintel/policies/internal/store/repository_matches_test.go
  enterprise/internal/codeintel/policies/internal/store/scan.go
  enterprise/internal/codeintel/policies/internal/store/store_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50347 codeintel: Large-chunk reorganize codenav lsifstore
  enterprise/internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
  enterprise/internal/codeintel/codenav/internal/lsifstore/document_metadata.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/document_metadata_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_diagnostics.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_diagnostics_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_exists.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_exists_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_monikers_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_packages.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_packages_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_stencil.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_stencil_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/metadata_by_position_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/observability.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/scan.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/store.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/symbols_by_position.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/symbols_by_position_test.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/types.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/util.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50358 codeintel: Large-chunk reorganize ranking store
  enterprise/internal/codeintel/ranking/internal/lsifstore/BUILD.bazel
  enterprise/internal/codeintel/ranking/internal/lsifstore/lsifstore.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/lsifstore_ranking.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/observability.go
  enterprise/internal/codeintel/ranking/internal/lsifstore/stream.go
  enterprise/internal/codeintel/ranking/internal/store/BUILD.bazel
  enterprise/internal/codeintel/ranking/internal/store/definitions.go
  enterprise/internal/codeintel/ranking/internal/store/definitions_test.go
  enterprise/internal/codeintel/ranking/internal/store/mapper.go
  enterprise/internal/codeintel/ranking/internal/store/mapper_test.go
  enterprise/internal/codeintel/ranking/internal/store/observability.go
  enterprise/internal/codeintel/ranking/internal/store/paths.go
  enterprise/internal/codeintel/ranking/internal/store/paths_test.go
  enterprise/internal/codeintel/ranking/internal/store/ranking.go
  enterprise/internal/codeintel/ranking/internal/store/ranking_test.go
  enterprise/internal/codeintel/ranking/internal/store/reducer.go
  enterprise/internal/codeintel/ranking/internal/store/reducer_test.go
  enterprise/internal/codeintel/ranking/internal/store/references.go
  enterprise/internal/codeintel/ranking/internal/store/references_test.go
  enterprise/internal/codeintel/ranking/internal/store/retrieval.go
  enterprise/internal/codeintel/ranking/internal/store/retrieval_test.go
  enterprise/internal/codeintel/ranking/internal/store/store.go
  enterprise/internal/codeintel/ranking/internal/store/store_test.go
  enterprise/internal/codeintel/ranking/internal/store/uploads.go
  enterprise/internal/codeintel/ranking/internal/store/uploads_test.go
  enterprise/internal/codeintel/ranking/internal/store/util.go
  enterprise/internal/codeintel/ranking/internal/store/util_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#49913 batches: handle default reviewers for Bitbucket Cloud & Server
  enterprise/internal/batches/sources/bitbucketcloud.go
  enterprise/internal/batches/sources/bitbucketcloud_test.go
  enterprise/internal/batches/sources/bitbucketserver.go
  enterprise/internal/batches/sources/bitbucketserver_test.go
  enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_UpdateChangeset_outdated
  enterprise/internal/batches/sources/testdata/golden/BitbucketServerSource_UpdateChangeset_success
  enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_UpdateChangeset_outdated.yaml
  enterprise/internal/batches/sources/testdata/sources/BitbucketServerSource_UpdateChangeset_success.yaml
  internal/extsvc/bitbucketcloud/pull_requests.go
  internal/extsvc/bitbucketserver/client.go
Labels: team/batchers, cla-signed

#50234 Display cloning progress
  client/browser/src/shared/repo/backend.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/components/RepoMirrorInfo.tsx
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/repository_mirror_test.go
Labels: cla-signed

#50371 chore: prepare 5.0.1
  CHANGELOG.md
  dev/release/release-config.jsonc
Labels: cla-signed

#50339 site-admin: remove unnecessary `source: 'server'` from some site-admin sidebar items.
  client/web/src/components/Sidebar.tsx
  client/web/src/site-admin/sidebaritems.ts
Labels: bug, site-admin, cla-signed, site-admin-ux

#50207 Offline drift check improvements
  cmd/migrator/build.sh
  cmd/migrator/shared/main.go
Labels: cla-signed, backport 5.0

#50278 Update GitLab docs to recommend read_api scope
  doc/admin/auth/index.md
  enterprise/cmd/frontend/internal/auth/gitlaboauth/config_test.go
  internal/extsvc/gitlab/auth.go
Labels: cla-signed, team/iam

#45827 cloud: hide o11y for non-operator users
  client/web/BUILD.bazel
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/hooks/useUserExternalAccounts.ts
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/sidebaritems.ts
Labels: cla-signed, backport 5.0

#50376 dep: Update Grafana alpine base image
  docker-images/alpine-3.14/update-all-dockerfiles.sh
  docker-images/grafana/Dockerfile.alpine
Labels: cla-signed, SSDLC

#50217 permission sync jobs: don't highlight if 0 added/0 removed
  client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
  client/web/src/site-admin/permissions-center/styles.module.scss
Labels: cla-signed, team/iam

#50377 Update Grafana Wolfi base image to patch CVE-2023-0464
  docker-images/grafana/Dockerfile
Labels: cla-signed, backport 5.0

#50379 cody: fix extension styling
  client/cody-ui/src/Chat.module.css
  client/cody-ui/src/Chat.tsx
  client/cody-ui/src/chat/ContextFiles.module.css
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/webviews/App.css
  client/cody/webviews/Chat.module.css
  client/cody/webviews/Chat.tsx
  client/cody/webviews/FileLink.module.css
Labels: cla-signed

#50112 site-admin: Show username if displayName is null
  client/web/src/site-admin/SiteConfigurationChangeList.tsx
  client/web/src/site-admin/SiteConfigurationHistoryItem.story.tsx
  internal/extsvc/gitlab/BUILD.bazel
Labels: cla-signed, bug-fix, site-admin-ux

#50384 ranking: Fix bad vacuum targets
  enterprise/internal/codeintel/ranking/internal/background/job_graph_exporter.go
Labels: team/code-intelligence, cla-signed, team/language-platform, ranking, confirm-no-backport

#50385 lint: Remove unreferenced code
  enterprise/internal/codeintel/autoindexing/service.go
  enterprise/internal/codeintel/codenav/transport/graphql/util_locations.go
  enterprise/internal/codeintel/services.go
  enterprise/internal/codeintel/uploads/transport/graphql/precise_index_resolver.go
  internal/codeintel/dependencies/internal/store/scan.go
  internal/codeintel/dependencies/internal/store/store.go
Labels: cla-signed

#50328 zoekt: update to sourcegraph/zoekt@18a074f890028128e75ed158ddb83b966491a932
  go.mod
  go.sum
Labels: cla-signed

#50340 bazel: mark integration tests as flaky
  client/web/src/integration/BUILD.bazel
Labels: cla-signed

#50375 [Backport 5.0] cloud: hide o11y for non-operator users
  client/web/BUILD.bazel
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/hooks/useUserExternalAccounts.ts
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/sidebaritems.ts
Labels: cla-signed, backports, backported-to-5.0

#50284 feat: control how many auth providers we show on login screen
  client/web/dev/utils/create-js-context.ts
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/auth/SignInPage.test.tsx
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
  internal/conf/computed.go
  schema/schema.go
  schema/site.schema.json
Labels: design-qa, cla-signed, team/iam, confirm-no-backport

#50388 Don't run old puppeteer jobs if bazel is enabled
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#50381 cody: include context for last interaction with non-empty context messages
  client/cody-shared/src/chat/recipes/chat-question.ts
  client/cody-shared/src/chat/transcript/index.ts
  client/cody-shared/src/chat/transcript/interaction.ts
  client/cody-shared/src/chat/transcript/transcript.test.ts
Labels: cla-signed

#50341 Update to go 1.19.8
  .github/workflows/sg-setup.yml
  .tool-versions
  WORKSPACE
  cmd/symbols/Dockerfile
  dev/build-tracker/Dockerfile
  dev/ci/integration/code-intel/install-src.sh
  dev/sg/checks.go
  docker-images/opentelemetry-collector/Dockerfile
  internal/cmd/git-combine/Dockerfile
  internal/cmd/progress-bot/Dockerfile
  internal/cmd/search-blitz/Dockerfile
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed, SSDLC, backport 5.0

#50391 [Request access] [telemetry]: Add allowlist event logs
  migrations/frontend/1680707560_sg_telemetry_allowlist/down.sql
  migrations/frontend/1680707560_sg_telemetry_allowlist/metadata.yaml
  migrations/frontend/1680707560_sg_telemetry_allowlist/up.sql
Labels: cla-signed, backport 5.0

#50394 syntax-highlighter: load all tree-sitter highlight configurations at startup
  .vscode/settings.json
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/highlights.rs
  docker-images/syntax-highlighter/src/main.rs
Labels: team/code-intelligence, cla-signed

#50393 zoekt: update to sourcegraph/zoekt@b247fb51dece2d026582f7870a3449edff0f8500
  go.mod
  go.sum
Labels: cla-signed

#50389 codeintel: GraphQL dependency reduction
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/autoindexing/transport/graphql/iface.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver_inference.go
  enterprise/internal/codeintel/codenav/transport/graphql/iface.go
  enterprise/internal/codeintel/codenav/transport/graphql/mocks_test.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  enterprise/internal/codeintel/policies/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/sentinel/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/sentinel/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/uploads/transport/graphql/precise_index_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/precise_index_resolver_factory.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_coverage.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_index_queries.go
  mockgen.test.yaml
Labels: team/code-intelligence, cla-signed, team/language-platform

#50400 fix migration parents for 5.0 backport
  docker-images/syntax-highlighter/BUILD.bazel
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  migrations/BUILD.bazel
  migrations/frontend/1680707560_sg_telemetry_allowlist/metadata.yaml
Labels: cla-signed

#50404 backport 50341 to 5.0
  .github/workflows/sg-setup.yml
  .tool-versions
  WORKSPACE
  cmd/symbols/Dockerfile
  dev/build-tracker/Dockerfile
  dev/ci/integration/code-intel/install-src.sh
  dev/sg/checks.go
  docker-images/opentelemetry-collector/Dockerfile
  internal/cmd/git-combine/Dockerfile
  internal/cmd/progress-bot/Dockerfile
  internal/cmd/search-blitz/Dockerfile
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed, backported-to-5.0

#50390 add items to 5.0.1 changelog
  CHANGELOG.md
Labels: cla-signed

#50411 release: sourcegraph@5.0.1
  cmd/frontend/internal/app/updatecheck/handler.go
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
Labels: cla-signed

#50361 add telemetry for /cody/search and cody sidebar
  client/web/src/enterprise/cody/search/CodySearchPage.tsx
  client/web/src/repo/repoRevisionSidebar/cody/RepoRevisionSidebarCody.tsx
Labels: cla-signed, cody

#50430 cody: add docs on the excludedFilePathPatterns setting and how to enable codebase-aware answers
  doc/cody/index.md
Labels: cla-signed

#50398 feat(licensing): add 'mau' tag to MiscTags list
  enterprise/internal/licensing/tags.go
Labels: cla-signed

#50431 Fix CVE-2023-0465 in Grafana image
  docker-images/grafana/Dockerfile
Labels: cla-signed, backport 5.0

#50363 Code intel: don't show search-based results for non-interactive tokens
  client/web/src/repo/blob/codemirror/token-selection/code-intel-tooltips.ts
Labels: cla-signed

#50367 Update embedded-repos.md
  doc/cody/embedded-repos.md
Labels: cla-signed, cody

#50435 bazel: add mocha retries
  dev/mocha.bzl
Labels: cla-signed, team/code-exploration, JF/bazel

#50436 ci: skip bazel build //... before bazel test //...
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/bazel_operations.go
Labels: cla-signed

#50438 ci: enable bazel tests on main
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/bazel_operations.go
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#50440 bazel: add faq entry about rust dependencies
  doc/dev/background-information/bazel.md
Labels: cla-signed, JF/bazel

#50443 docs: Bazel: Add FAQ entry about artifact exclusion in IDEs
  doc/dev/background-information/bazel.md
Labels: cla-signed

#50439 codeintel: Add stub context service
  enterprise/internal/codeintel/BUILD.bazel
  enterprise/internal/codeintel/context/BUILD.bazel
  enterprise/internal/codeintel/context/config.go
  enterprise/internal/codeintel/context/iface.go
  enterprise/internal/codeintel/context/init.go
  enterprise/internal/codeintel/context/internal/store/BUILD.bazel
  enterprise/internal/codeintel/context/internal/store/observability.go
  enterprise/internal/codeintel/context/internal/store/store.go
  enterprise/internal/codeintel/context/internal/store/store_test.go
  enterprise/internal/codeintel/context/observability.go
  enterprise/internal/codeintel/context/service.go
  enterprise/internal/codeintel/context/service_test.go
  enterprise/internal/codeintel/services.go
Labels: team/code-intelligence, cla-signed, team/language-platform, cody

#50434 feat: add ordering to auth providers in login screen
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/auth/SignInPage.test.tsx
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/jscontext.ts
  cmd/frontend/auth/providers/BUILD.bazel
  cmd/frontend/auth/providers/providers.go
  cmd/frontend/auth/providers/providers_test.go
  cmd/frontend/graphqlbackend/auth_providers.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam, confirm-no-backport

#50453 client/cody-ui: update terms of use
  client/cody-ui/src/Terms.tsx
Labels: cla-signed

#50451 Remove views api from extension api
  client/client-api/src/contribution.ts
  client/common/src/util/types.ts
  client/extension-api/src/sourcegraph.d.ts
  client/shared/BUILD.bazel
  client/shared/src/api/contract.ts
  client/shared/src/api/extension/api/callViewProvidersInParallel.test.ts
  client/shared/src/api/extension/api/callViewProvidersInParallel.ts
  client/shared/src/api/extension/api/contribution.ts
  client/shared/src/api/extension/api/directoryViewer.ts
  client/shared/src/api/extension/api/getInsightsViews.ts
  client/shared/src/api/extension/extensionApi.ts
  client/shared/src/api/extension/extensionHostApi.ts
  client/shared/src/api/extension/extensionHostState.ts
  client/shared/src/api/integration-test/views.test.ts
  client/shared/src/codeintel/api.ts
  client/shared/src/codeintel/legacy-extensions/api.ts
Labels: cla-signed

#50456 client/cody: release 0.0.5
  client/cody/package.json
Labels: cla-signed

#50372 context-aware completions
  client/cody-shared/src/configuration.ts
  client/cody/package.json
  client/cody/src/command/CommandsProvider.ts
  client/cody/src/completions/context.test.ts
  client/cody/src/completions/context.ts
  client/cody/src/completions/docprovider.ts
  client/cody/src/completions/history.ts
  client/cody/src/completions/index.ts
  client/cody/src/completions/prompts.ts
  client/cody/src/configuration.test.ts
  client/cody/src/configuration.ts
  client/cody/src/integration-test/extension.test.ts
  client/cody/src/wink-nlp-utils.d.ts
  pnpm-lock.yaml
Labels: cla-signed

#50450 Revert "feat: add ordering to auth providers in login screen"
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/auth/SignInPage.test.tsx
  client/web/src/auth/SignInPage.tsx
  client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
  client/web/src/jscontext.ts
  cmd/frontend/auth/providers/BUILD.bazel
  cmd/frontend/auth/providers/providers.go
  cmd/frontend/auth/providers/providers_test.go
  cmd/frontend/graphqlbackend/auth_providers.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#50175 codeintel: display SCIP snapshot lines in codemirror
  client/web/BUILD.bazel
  client/web/src/codeintel/BrainDot.tsx
  client/web/src/enterprise/codeintel/dashboard/backend.ts
  client/web/src/enterprise/codeintel/dashboard/components/BrainDot.module.scss
  client/web/src/enterprise/codeintel/dashboard/components/BrainDot.tsx
  client/web/src/enterprise/codeintel/dashboard/hooks/useVisibleIndexes.ts
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/backend.ts
  client/web/src/repo/blob/codemirror/scip-snapshot.ts
  cmd/frontend/graphqlbackend/codeintel.codenav.graphql
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/internal/codeintel/codenav/BUILD.bazel
  enterprise/internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
  enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/observability.go
  enterprise/internal/codeintel/codenav/internal/lsifstore/store.go
  enterprise/internal/codeintel/codenav/mocks_test.go
  enterprise/internal/codeintel/codenav/observability.go
  enterprise/internal/codeintel/codenav/service.go
  enterprise/internal/codeintel/codenav/shared/types.go
  enterprise/internal/codeintel/codenav/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/codenav/transport/graphql/iface.go
  enterprise/internal/codeintel/codenav/transport/graphql/mocks_test.go
  enterprise/internal/codeintel/codenav/transport/graphql/observability.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_raw_scip.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  enterprise/internal/codeintel/codenav/utils.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_index_mutations.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_index_queries.go
  enterprise/internal/codeintel/uploads/transport/graphql/util_identifiers.go
  internal/codeintel/resolvers/codenav.go
Labels: team/code-intelligence, cla-signed, team/language-tools, team/language-platform

#50468 Add link to the handbook
  doc/cody/index.md
Labels: cla-signed

#50473 Move prerequisites to the doc
  doc/cody/index.md
Labels: cla-signed

#50014 typo
  doc/api/graphql/index.md
Labels: cla-signed

#50458 Update embedded-repos.md
  doc/cody/embedded-repos.md
Labels: docs, cla-signed, cody

#50476 Clarify sourcegraph.com is only for public code
  doc/cody/index.md
Labels: cla-signed

#50317 Chore: No Repos Detected status message
  client/cody-shared/BUILD.bazel
  client/web/src/nav/StatusMessagesNavItem.tsx
  client/web/src/nav/StatusMessagesNavItemQueries.ts
  client/web/src/site-admin/backend.ts
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/status_messages.go
  cmd/frontend/graphqlbackend/status_messages_test.go
  internal/repos/status_messages.go
  internal/repos/status_messages_test.go
Labels: cla-signed

#50455 expose LLM completions over graphql
  CHANGELOG.md
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/completions.go
  cmd/frontend/graphqlbackend/completions.graphql
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/schema.go
  enterprise/cmd/frontend/internal/completions/BUILD.bazel
  enterprise/cmd/frontend/internal/completions/init.go
  enterprise/cmd/frontend/internal/completions/resolvers/BUILD.bazel
  enterprise/cmd/frontend/internal/completions/resolvers/resolver.go
  enterprise/cmd/frontend/internal/completions/streaming/stream.go
Labels: cla-signed

#50480 Update embedded-repos.md
  doc/cody/embedded-repos.md
Labels: docs, cla-signed, cody

#50486 codeintel: Disable inference when autoindexing is not enabled
  enterprise/internal/codeintel/uploads/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_coverage.go
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.0

#50501 Remove public code mentions except embeddings
  doc/cody/index.md
Labels: cla-signed

#50452 Conditionally render cody for repo sidebar web
  client/web/src/repo/repoRevisionSidebar/cody/RepoRevisionSidebarCody.tsx
  client/web/src/repo/repoRevisionSidebar/cody/backend.tsx
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/schema.graphql
  enterprise/internal/embeddings/background/repo/store_test.go
  internal/database/mocks_temp.go
  internal/database/repos.go
Labels: cla-signed, team/iam, cody

#50502 cleanup: make logging consistent, clean up code.
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/repo_info.go
Labels: team/repo-management, cla-signed

#50489 backport 50486 to 5.0
  enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/BUILD.bazel
Labels: cla-signed

#50475 Prompt engineering and updates for cody magical web search [no-bazel]
  client/web/src/enterprise/cody/search/CodySearchPage.tsx
  client/web/src/enterprise/cody/search/translateToQuery.ts
  client/web/src/enterprise/routes.tsx
Labels: cla-signed, team/iam

#50510 Bazel: fix client build
  client/web/BUILD.bazel
Labels: cla-signed

#50509 gRPC: commit search refinements
  internal/gitserver/addrs.go
  internal/gitserver/client.go
  internal/gitserver/protocol/gitserver.go
Labels: cla-signed

#50505 cody: trigger autocomplete less aggressively
  client/cody/src/completions/index.ts
Labels: cla-signed

#50514 remove debug statement
  client/cody/src/completions/index.ts
Labels: cla-signed

#50519 Cody: add patterns for queries that require context
  enterprise/cmd/embeddings/shared/BUILD.bazel
  enterprise/cmd/embeddings/shared/context_detection.go
  enterprise/cmd/embeddings/shared/context_detection_test.go
Labels: cla-signed

#50383 bazel: fix the web application bundle in Bazel
  BUILD.bazel
  babel.config.jest.js
  babel.config.js
  client/web/BUILD.bazel
  client/web/bundlesize.config.js
  client/web/webpack.bazel.config.js
  client/web/webpack.config.js
  dev/babel.bzl
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/code-exploration, JF/bazel

#50465 Cody: Fix IME composition, reply in the IDE/browser's language
  client/cody-shared/BUILD.bazel
  client/cody-shared/src/chat/transcript/interaction.ts
  client/cody-shared/src/prompt/prompt-mixin.ts
  client/cody-ui/src/Chat.tsx
  client/cody-web/src/index.tsx
  client/cody/src/extension.ts
Labels: cla-signed, cody

#50472 Update bazel to 6.1.1
  .bazelversion
Labels: cla-signed

#50523 docs: add a FAQ entry for "no-bazel"
  doc/dev/background-information/bazel.md
Labels: cla-signed

#50522 Cody: Replace Recipe.getInteraction arguments with parameter object.
  client/cody-shared/src/chat/client.ts
  client/cody-shared/src/chat/recipes/chat-question.ts
  client/cody-shared/src/chat/recipes/explain-code-detailed.ts
  client/cody-shared/src/chat/recipes/explain-code-high-level.ts
  client/cody-shared/src/chat/recipes/generate-docstring.ts
  client/cody-shared/src/chat/recipes/generate-test.ts
  client/cody-shared/src/chat/recipes/git-log.ts
  client/cody-shared/src/chat/recipes/improve-variable-names.ts
  client/cody-shared/src/chat/recipes/recipe.ts
  client/cody-shared/src/chat/recipes/translate.ts
  client/cody-shared/src/chat/transcript/transcript.test.ts
  client/cody-shared/src/test/mocks.ts
  client/cody/src/chat/ChatViewProvider.ts
Labels: cla-signed, cody

#50524 Disabling Cody
  doc/cody/index.md
Labels: cla-signed

#50513 Add powered by cody label
  client/web/src/enterprise/cody/search/CodySearchPage.module.scss
  client/web/src/enterprise/cody/search/CodySearchPage.tsx
  client/web/src/enterprise/cody/search/translateToQuery.ts
Labels: cla-signed, team/iam

#50530 sg: do not release with CGO enabled
  .github/workflows/sg-binary-release.yml
Labels: cla-signed

#50529 Fix k8s logkey regex
  enterprise/cmd/executor/kubernetes/README.md
  enterprise/internal/codeintel/uploads/transport/graphql/index_steps_resolver.go
Labels: cla-signed

#50349 Go to definition: push current location into browser history
  client/client-api/src/contribution.ts
  client/shared/src/actions/ActionItem.tsx
  client/web/src/repo/blob/codemirror/tooltips/CodeIntelTooltip.tsx
Labels: cla-signed

#50457 codeintel: Standardize use of dataloaders
  enterprise/cmd/frontend/internal/codeintel/init.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver_inference.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  enterprise/internal/codeintel/sentinel/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/sentinel/transport/graphql/dataloader.go
  enterprise/internal/codeintel/sentinel/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/shared/resolvers/dataloader/BUILD.bazel
  enterprise/internal/codeintel/shared/resolvers/dataloader/cache.go
  enterprise/internal/codeintel/shared/resolvers/dataloader/loader.go
  enterprise/internal/codeintel/shared/resolvers/dataloader/loader_factory.go
  enterprise/internal/codeintel/uploads/transport/graphql/BUILD.bazel
  enterprise/internal/codeintel/uploads/transport/graphql/dataloader.go
  enterprise/internal/codeintel/uploads/transport/graphql/precise_index_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/precise_index_resolver_factory.go
  enterprise/internal/codeintel/uploads/transport/graphql/prefetcher.go
  enterprise/internal/codeintel/uploads/transport/graphql/prefetcher_factory.go
  enterprise/internal/codeintel/uploads/transport/graphql/prefetcher_test.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_coverage.go
  enterprise/internal/codeintel/uploads/transport/graphql/root_resolver_index_queries.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#50511 Update embedded-repos.md
  doc/cody/embedded-repos.md
Labels: cla-signed

#50534 Add docs about firewall rules for executors on K8s
  doc/admin/executors/deploy_executors_kubernetes.md
Labels: cla-signed

#50537 bazel: fail script if configure fails
  dev/ci/bazel-configure.sh
Labels: cla-signed

#50525 JetBrains: Fix standalone build
  client/jetbrains/standalone/src/index.html
  client/jetbrains/webview/BUILD.bazel
  client/jetbrains/webview/src/bridge-mock/call-java-mock.ts
  client/jetbrains/webview/src/search/index.tsx
Labels: cla-signed, team/code-exploration

#50536 [Backport 5.0] Cody: add patterns for queries that require context
  enterprise/cmd/embeddings/shared/BUILD.bazel
  enterprise/cmd/embeddings/shared/context_detection.go
  enterprise/cmd/embeddings/shared/context_detection_test.go
Labels: cla-signed

#50521 Add sitename to structured data
  cmd/frontend/internal/app/ui/app.html
Labels: gitstart, cla-signed, team/frontend-platform

#50471 batches: surface batch change rollout window in JSContext
  client/web/dev/utils/create-js-context.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
Labels: cla-signed

#50433 Docs: Add Bitbucket server guidance on possible CSP errors
  doc/integration/bitbucket_server.md
Labels: cla-signed, team/code-exploration

#50550 bazel: run graphql-schema-linter as part of tests
  BUILD.bazel
  cmd/frontend/graphqlbackend/BUILD.bazel
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#50545 admin-analytics: make `ValueLegendList` accept/render 2 numbers.
  client/web/src/site-admin/analytics/components/ValueLegendList.story.tsx
  client/web/src/site-admin/analytics/components/ValueLegendList.tsx
Labels: cla-signed, team/iam

#50553 bazel: ensure all analyzers respect nolint
  dev/linters/bodyclose/BUILD.bazel
  dev/linters/bodyclose/bodyclose.go
  dev/linters/exportloopref/BUILD.bazel
  dev/linters/exportloopref/exportloopref.go
  dev/linters/forbidigo/BUILD.bazel
  dev/linters/forbidigo/forbidigo.go
  dev/linters/gocritic/BUILD.bazel
  dev/linters/gocritic/gocritic.go
  dev/linters/ineffassign/BUILD.bazel
  dev/linters/ineffassign/ineffassign.go
  dev/linters/nolint/BUILD.bazel
  dev/linters/nolint/nolint.go
  dev/linters/staticcheck/BUILD.bazel
  dev/linters/staticcheck/cmd/gen.go
  dev/linters/staticcheck/staticcheck.go
Labels: cla-signed, JF/bazel

#50548 Force line break before cloning progress
  client/web/src/site-admin/components/RepoMirrorInfo.tsx
Labels: cla-signed

#50541 Cody: more required context patterns
  enterprise/cmd/embeddings/shared/context_detection.go
  enterprise/cmd/embeddings/shared/context_detection_test.go
Labels: cla-signed

#50562 Update faq.md
  doc/cody/faq.md
Labels: cla-signed

#50570 hotfix: temporarily revert to curl 7.X
  cmd/gitserver/Dockerfile
  cmd/server/Dockerfile
  docker-images/alpine-3.14/Dockerfile
  enterprise/cmd/batcheshelper/Dockerfile
  enterprise/cmd/bundled-executor/Dockerfile
  enterprise/cmd/executor-kubernetes/Dockerfile
  enterprise/cmd/executor/docker-image/Dockerfile
  enterprise/cmd/gitserver/Dockerfile
Labels: cla-signed

#50574 bazel: bundlesize check
  client/web/BUILD.bazel
  client/web/bundlesize.config.js
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed, team/code-exploration, JF/bazel

#50547 cody: highlight file path hallucinations
  client/cody-shared/BUILD.bazel
  client/cody-shared/src/chat/transcript/index.ts
  client/cody-shared/src/hallucinations-detector/index.test.ts
  client/cody-shared/src/hallucinations-detector/index.ts
  client/cody-shared/src/prompt/prompt-mixin.ts
  client/cody-ui/src/Chat.tsx
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/webviews/Chat.module.css
Labels: cla-signed, cody

#50576 Documentation: add row for C# status
  doc/code_navigation/references/indexers.md
Labels: cla-signed

#50546 JetBrains: Various fixes and support for 2023.1
  client/branded/src/search-ui/components/CodeHostIcon.tsx
  client/jetbrains/CHANGELOG.md
  client/jetbrains/build.gradle.kts
  client/jetbrains/gradle.properties
  client/jetbrains/scripts/build.ts
  client/jetbrains/webview/src/search/input/JetBrainsSearchBox.module.scss
  client/jetbrains/webview/src/search/input/JetBrainsSearchBox.tsx
  client/jetbrains/webview/src/search/results/SearchResultLayout.module.scss
  client/jetbrains/webview/src/search/results/SearchResultLayout.tsx
Labels: cla-signed, team/code-exploration

#50578 Update cody doc index.md
  doc/cody/index.md
Labels: cla-signed
