Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-05, with the labels that each got.

#51278 CHANGELOG update for #50353
  CHANGELOG.md
Labels: cla-signed

#51290 sg: include test and misc images in `ops update-images` selection
  dev/sg/internal/images/images.go
Labels: cla-signed

#51292 Revert "cloud: guard o11y for non-operator users"
  cmd/frontend/internal/app/debug.go
  cmd/frontend/internal/app/debug_test.go
  cmd/frontend/internal/app/debugproxies/BUILD.bazel
  cmd/frontend/internal/app/debugproxies/handler.go
  cmd/frontend/internal/app/debugproxies/handler_test.go
Labels: cla-signed

#51193 App: Add sourcegraph:// url scheme handler
  client/app-shell/src/app-shell.tsx
  cmd/frontend/internal/auth/userpasswd/app.go
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/Info.plist
  src-tauri/src/main.rs
Labels: cla-signed, app

#51227 [Backport 5.0] reconcile embeddings service with main
  enterprise/cmd/embeddings/shared/context_detection.go
  enterprise/cmd/embeddings/shared/context_detection_test.go
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/embeddings/shared/query_embeddings_cache.go
  enterprise/cmd/embeddings/shared/search.go
  enterprise/cmd/frontend/internal/completions/streaming/anthropic/decoder.go
  enterprise/cmd/frontend/internal/completions/streaming/anthropic/decoder_test.go
  enterprise/cmd/worker/internal/embeddings/contextdetection/handler.go
  enterprise/cmd/worker/internal/embeddings/repo/BUILD.bazel
  enterprise/cmd/worker/internal/embeddings/repo/document_ranks.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/cmd/worker/internal/embeddings/repo/worker.go
  enterprise/internal/embeddings/BUILD.bazel
  enterprise/internal/embeddings/client.go
  enterprise/internal/embeddings/embed/BUILD.bazel
  enterprise/internal/embeddings/embed/api.go
  enterprise/internal/embeddings/embed/embed.go
  enterprise/internal/embeddings/embed/embed_test.go
  enterprise/internal/embeddings/embed/files.go
  enterprise/internal/embeddings/embed/files_test.go
  enterprise/internal/embeddings/index_storage.go
  enterprise/internal/embeddings/index_storage_test.go
  enterprise/internal/embeddings/quantize.go
  enterprise/internal/embeddings/similarity_search.go
  enterprise/internal/embeddings/similarity_search_test.go
  enterprise/internal/embeddings/types.go
Labels: cla-signed

#51307 #50353 CHANGELOG copy update
  CHANGELOG.md
Labels: cla-signed

#51289 gitserver: quote commit message in `createCommitFromPatch`
  CHANGELOG.md
  cmd/gitserver/server/patch.go
Labels: gitserver, team/batchers, cla-signed

#51282 testing: document how to update react snapshots
  doc/dev/how-to/testing.md
Labels: cla-signed

#51228 dev/sg: set sg.config.yaml env when generating
  dev/sg/sg_generate.go
Labels: cla-signed

#51242 dotcom: add llm-proxy access state
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.test.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductSubscriptionPage.test.tsx.snap
  client/web/src/featureFlags/featureFlags.ts
  cmd/frontend/graphqlbackend/dotcom.go
  cmd/frontend/graphqlbackend/dotcom.graphql
  enterprise/cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
  enterprise/cmd/frontend/internal/dotcom/productsubscription/llmproxy_graphql.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/llmproxy_graphql_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/mock_db.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_db_test.go
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
  enterprise/internal/licensing/BUILD.bazel
  enterprise/internal/licensing/llmproxy.go
  enterprise/internal/licensing/plans.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1682626931_subscription_llm_proxy_state/down.sql
  migrations/frontend/1682626931_subscription_llm_proxy_state/metadata.yaml
  migrations/frontend/1682626931_subscription_llm_proxy_state/up.sql
  migrations/frontend/squashed.sql
  pnpm-lock.yaml
Labels: cla-signed

#51322 Remove Cody CTA from home page and closes #51319
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
Labels: cla-signed

#51316 Add instructions for building p4-fusion manually
  doc/dev/background-information/build_p4_fusion.md
Labels: cla-signed

#51329 Update index.md (cody docs)
  doc/cody/index.md
Labels: cla-signed

#51300 doc: add "Migrations overview" page
  doc/dev/background-information/index.md
  doc/dev/background-information/sql/index.md
  doc/dev/background-information/sql/migrations_overview.md
Labels: cla-signed

#51226 llm-proxy: basic requests proxying
  enterprise/cmd/llm-proxy/shared/BUILD.bazel
  enterprise/cmd/llm-proxy/shared/config.go
  enterprise/cmd/llm-proxy/shared/main.go
Labels: cla-signed

#51333 release: activate 5.0.3
  dev/release/release-config.jsonc
Labels: cla-signed

#51337 bzl: add missing img folder to ent assets
  ui/assets/enterprise/BUILD.bazel
Labels: cla-signed

#51294 Selectively enabling Cody
  doc/cody/explanations/enabling_cody_enterprise.md
Labels: cla-signed

#51208 Document OpenAI API compatibility for completions
  doc/cody/explanations/enabling_cody_enterprise.md
  doc/cody/faq.md
  doc/cody/index.md
Labels: cla-signed

#51274 Cody: Add support for more git clone urls and remove reload on codebase update
  client/cody/CHANGELOG.md
  client/cody/package.json
  client/cody/src/chat/ChatViewProvider.test.ts
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/src/configuration.ts
  client/cody/src/external-services.ts
  client/cody/src/main.ts
  client/cody/webviews/App.css
Labels: cla-signed, cody

#51334 5.0: manually fix backend integration tests
  dev/authtest/site_admin_test.go
Labels: cla-signed

#51351 llm-proxy: response error in JSON format
  enterprise/cmd/llm-proxy/shared/main.go
Labels: cla-signed

#51350 Cody completions: Add metrics for completion events
  client/cody/CHANGELOG.md
  client/cody/src/completions/index.ts
  client/cody/src/main.ts
Labels: cla-signed, team/code-exploration

#51328 Add mention for Sourcegraph Cloud customers
  doc/cody/explanations/code_graph_context.md
Labels: cla-signed

#51335 app: tauri+bazel; fix permissions issue / enable Tauri API access from localhost:3080
  dev/bazel_stamp_vars.sh
  enterprise/cmd/sourcegraph/BUILD.bazel
  enterprise/dev/app/build-release.sh
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
Labels: cla-signed

#51359 containers: fix prometheus permissions
  docker-images/prometheus/Dockerfile.bazel
Labels: cla-signed

#50941 site-admin: fix parseProductReference
  client/web/BUILD.bazel
  client/web/src/site-admin/SiteAdminFeatureFlagsPage.test.ts
  client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
Labels: cla-signed

#51318 llm-proxy: add graphql client generator
  deps.bzl
  dev/tools.go
  enterprise/cmd/llm-proxy/internal/dotcom/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/dotcom/dotcom.go
  enterprise/cmd/llm-proxy/internal/dotcom/gen.go
  enterprise/cmd/llm-proxy/internal/dotcom/genql.yaml
  enterprise/cmd/llm-proxy/internal/dotcom/operations.go
  enterprise/cmd/llm-proxy/internal/dotcom/operations.graphql
  go.mod
  go.sum
Labels: cla-signed

#51330 Update link to docs on browser extension
  client/browser/src/browser-extension/options-menu/OptionsPage.tsx
Labels: cla-signed

#51308 Add diagrams for the different executor runtimes
  doc/admin/executors/executors_arch.svg
  doc/admin/executors/index.md
Labels: cla-signed

#51356 autoindexing: Guard summary builder with config flag
  enterprise/internal/codeintel/autoindexing/internal/background/summary/BUILD.bazel
  enterprise/internal/codeintel/autoindexing/internal/background/summary/job_summary_builder.go
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.0

#51233 app: open external and help links in system default web browser
  client/web/BUILD.bazel
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/app/TauriLink.tsx
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/app-main.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/help.go
  sg.config.yaml
  src-tauri/tauri.conf.json
Labels: cla-signed

#51299 App: Support deep link launch on non-mac and move funcs to common lib file
  src-tauri/src/common.rs
  src-tauri/src/main.rs
  src-tauri/src/tray.rs
Labels: cla-signed, app

#51306 executors: Add high-level documentation on firecracker
  doc/admin/executors/firecracker.md
  doc/admin/executors/index.md
Labels: docs, cla-signed, executors

#51372 Embeddings: search with SIMD
  enterprise/cmd/embeddings/shared/context_detection.go
  enterprise/internal/embeddings/BUILD.bazel
  enterprise/internal/embeddings/dot.go
  enterprise/internal/embeddings/dot_amd64.go
  enterprise/internal/embeddings/dot_amd64.s
  enterprise/internal/embeddings/dot_noamd64.go
  enterprise/internal/embeddings/dot_test.go
  enterprise/internal/embeddings/similarity_search.go
  enterprise/internal/embeddings/similarity_search_test.go
  go.mod
  go.sum
Labels: cla-signed, backport 5.0

#51383 autoindexing: Guard summary builder with config flag (#51356)
  enterprise/internal/codeintel/autoindexing/internal/background/job_summary_builder.go
Labels: cla-signed

#51387 Embeddings: fix frame size
  enterprise/internal/embeddings/dot_amd64.s
Labels: cla-signed, backport 5.0

#51325 llm-proxy: add stub rate-limiter implementation
  enterprise/cmd/llm-proxy/internal/limiter/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/limiter/error.go
  enterprise/cmd/llm-proxy/internal/limiter/limiter.go
  enterprise/cmd/llm-proxy/internal/limiter/limiter_test.go
  enterprise/cmd/llm-proxy/internal/limiter/store.go
Labels: cla-signed

#51381 [Backport 5.0] Embeddings: add SIMD search capability
  enterprise/cmd/embeddings/shared/context_detection.go
  enterprise/internal/embeddings/BUILD.bazel
  enterprise/internal/embeddings/dot.go
  enterprise/internal/embeddings/dot_amd64.go
  enterprise/internal/embeddings/dot_amd64.s
  enterprise/internal/embeddings/dot_noamd64.go
  enterprise/internal/embeddings/dot_test.go
  enterprise/internal/embeddings/similarity_search.go
  enterprise/internal/embeddings/similarity_search_test.go
  go.mod
  go.sum
Labels: cla-signed

#50629 batches: adjust configuration form size on ultra-wide screens
  client/web/src/enterprise/batches/create/ConfigurationForm.module.scss
Labels: team/batchers, cla-signed

#51370 batches: upade doc string for OrgsAllMembersBatchChangesAdmin
  schema/schema.go
  schema/settings.schema.json
Labels: team/batchers, cla-signed

#51395 bazel: build cody-web typescript files with Bazel
  client/cody-web/BUILD.bazel
Labels: cla-signed, bazel, team/code-exploration, JF/bazel

#51394 ci: fix chromatic preview script
  dev/ci/post-chromatic.sh
  package.json
  pnpm-lock.yaml
Labels: ci, cla-signed, team/code-exploration

#51397 ci: update the Chomatic preview message
  dev/ci/post-chromatic.sh
Labels: cla-signed, team/code-exploration

#51403 Revert "app: open external and help links in system default web brows…
  client/web/BUILD.bazel
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/app/TauriLink.tsx
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/app-main.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/help.go
  sg.config.yaml
  src-tauri/tauri.conf.json
Labels: cla-signed

#51398 feat: add icon for azure devops code host
  client/web/src/components/externalServices/externalServices.tsx
Labels: cla-signed, team/iam

#51341 feat: add support for multiple github app installations
  enterprise/cmd/frontend/internal/auth/githubappauth/middleware.go
  enterprise/internal/github_apps/store/mocks_temp.go
  enterprise/internal/github_apps/store/store.go
  enterprise/internal/github_apps/store/store_test.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1682598027_add_github_app_installations_table/down.sql
  migrations/frontend/1682598027_add_github_app_installations_table/metadata.yaml
  migrations/frontend/1682598027_add_github_app_installations_table/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/iam, confirm-no-backport

#51405 admin: rename the "Code host" to "Code host connections"
  client/web/src/components/externalServices/AddExternalServicePage.tsx
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/components/externalServices/ExternalServiceForm.tsx
  client/web/src/components/externalServices/ExternalServicesPage.tsx
  client/web/src/components/externalServices/__snapshots__/ExternalServiceForm.test.tsx.snap
  client/web/src/components/externalServices/backend.ts
  client/web/src/site-admin/SiteAdminArea.module.scss
  client/web/src/site-admin/sidebaritems.ts
Labels: cla-signed, team/iam

#51406 zoekt: update to sourcegraph/zoekt@f818d968ddad0bb708b958cfb66ab08ee6ec4aa5
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#51409 nix: set formatter & use nil instead of rnix-lsp
  flake.nix
  shell.nix
Labels: nix, cla-signed

#51407 Updating pnpm to 8.1.x
  .tool-versions
  WORKSPACE
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#51380 bazel: run gazelle and add keeps for backwards compat
  deps.bzl
Labels: cla-signed

#51371 drift: be more lenient in -version flag
  doc/dev/background-information/sg/reference.md
  internal/database/migration/cliutil/drift.go
Labels: cla-signed, Multiversion Upgrade

#51411 [Backport 5.0] zoekt: update to sourcegraph/zoekt@f818d968ddad0bb708b958cfb66ab08ee6ec4aa5
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, backports, backported-to-5.0

#51352 [github app] Add resolvers to list and delete GitHub Apps
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/githubapps.go
  cmd/frontend/graphqlbackend/githubapps.graphql
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/node.go
  cmd/frontend/graphqlbackend/schema.go
  enterprise/cmd/frontend/internal/auth/githubappauth/BUILD.bazel
  enterprise/cmd/frontend/internal/auth/githubappauth/init.go
  enterprise/cmd/frontend/internal/auth/githubappauth/resolver.go
  enterprise/cmd/frontend/internal/auth/githubappauth/resolver_test.go
  enterprise/cmd/frontend/shared/BUILD.bazel
  enterprise/cmd/frontend/shared/shared.go
  enterprise/internal/github_apps/store/mocks_temp.go
  enterprise/internal/github_apps/store/store.go
Labels: cla-signed, team/iam

#51379 remove events `SearchSubmitted`, `AccessRequest...` from managed Instance allowList
  migrations/BUILD.bazel
  migrations/frontend/1683053825_sg_telemetry_allowlist/down.sql
  migrations/frontend/1683053825_sg_telemetry_allowlist/metadata.yaml
  migrations/frontend/1683053825_sg_telemetry_allowlist/up.sql
Labels: cla-signed, backport 5.0

#51188 own: index recent contributors for ownership signals
  enterprise/internal/own/background/BUILD.bazel
  enterprise/internal/own/background/background.go
  enterprise/internal/own/background/recent_contributors.go
  enterprise/internal/own/background/recent_contributors_test.go
  internal/database/recent_contribution_signal.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mocks_temp.go
Labels: cla-signed

#51413 [Backport 5.0] remove events `SearchSubmitted`, `AccessRequest...` from managed Instance allowList
  migrations/BUILD.bazel
  migrations/frontend/1683053825_sg_telemetry_allowlist/down.sql
  migrations/frontend/1683053825_sg_telemetry_allowlist/metadata.yaml
  migrations/frontend/1683053825_sg_telemetry_allowlist/up.sql
Labels: cla-signed

#51220 scip-go: nit ci fixups
  .github/workflows/scip-go.yml
Labels: cla-signed

#51083 app: add Tauri readme
  src-tauri/README.md
Labels: cla-signed

#51416 license-check: update pnpm
  .github/workflows/licenses-check.yml
Labels: cla-signed

#51076 Structural Search: Modify revisions values to match on Zoekt branches
  CHANGELOG.md
  internal/search/structural/structural.go
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
Labels: cla-signed, backport 5.0

#51420 Embeddings: update changelog with embeddings notes
  CHANGELOG.md
Labels: cla-signed

#50835 Cody aggregated ping additions.
  CHANGELOG.md
  cmd/frontend/internal/app/updatecheck/BUILD.bazel
  cmd/frontend/internal/app/updatecheck/client.go
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/frontend/internal/app/updatecheck/handler_test.go
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/database/mocks_temp.go
  internal/types/types.go
  internal/usagestats/aggregated_search.go
Labels: cla-signed, backport 5.0

#51385 app: move back/forward buttons into global navbar, remove overlay titlebar
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/app/TauriNavigation.module.scss
  client/web/src/app/TauriNavigation.tsx
  client/web/src/app/TauriTitleBar.module.scss
  client/web/src/app/TauriTitleBar.tsx
  client/web/src/nav/GlobalNavbar.story.tsx
  client/web/src/nav/GlobalNavbar.test.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/NavBar/NavItem.module.scss
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
  src-tauri/tauri.conf.json
Labels: cla-signed

#51368 bazel: run executor tests
  enterprise/dev/ci/integration/executors/run.sh
  enterprise/dev/ci/integration/executors/test.sh
  enterprise/dev/ci/integration/executors/tester/BUILD.bazel
  enterprise/dev/ci/integration/executors/tester/config/BUILD.bazel
  enterprise/dev/ci/integration/executors/tester/config/config.go
  enterprise/dev/ci/integration/executors/tester/config/repos.json
  enterprise/dev/ci/integration/executors/tester/config/site-config.json
  enterprise/dev/ci/integration/executors/tester/init.go
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#51324 redigo, redigomock: use correct versions of packages
  deps.bzl
  go.mod
  go.sum
  internal/featureflag/BUILD.bazel
  internal/featureflag/middleware_test.go
Labels: cla-signed

#51428 chore: cut CHANGELOG for 5.0.3
  CHANGELOG.md
Labels: cla-signed

#51311 docs: Add instructions for custom certs for executors
  doc/admin/executors/deploy_executors.md
Labels: cla-signed

#51421 Revert "Revert "app: open external and help links in system default browser""
  client/web/BUILD.bazel
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/SourcegraphWebApp.tsx
  client/web/src/app/TauriLink.tsx
  client/web/src/components/externalServices/AddExternalServicePage.tsx
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/enterprise/app-main.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/common/CodeHostConnection.tsx
  client/web/webpack.config.js
  cmd/frontend/internal/app/ui/help.go
  sg.config.yaml
  src-tauri/tauri.conf.json
Labels: cla-signed

#51427 own: use internal actor for recent contributors indexing
  enterprise/internal/own/background/BUILD.bazel
  enterprise/internal/own/background/recent_contributors.go
  enterprise/internal/own/background/recent_contributors_test.go
Labels: cla-signed

#51355 Create App troubleshooting guide
  doc/app/index.md
  doc/app/troubleshooting.md
Labels: cla-signed

#51439 release: sourcegraph@5.0.3
  cmd/frontend/internal/app/updatecheck/handler.go
  cmd/migrator/build.sh
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
Labels: cla-signed

#51441 release: wrap up 5.0.3 release
  dev/release/release-config.jsonc
Labels: cla-signed

#51444 cody: hide cody.experimental.suggest
  client/cody/package.json
Labels: cla-signed

#51446 migrator: fix v5.0.3
  cmd/migrator/build.sh
Labels: cla-signed

#50622 doc: add custom domain instruction
  doc/cloud/index.md
Labels: cla-signed

#51447 ci: fix scip-typescript
  .github/workflows/scip-typescript.yml
Labels: dx, ci, cla-signed, team/code-exploration

#51457 Update packge.json pnpm engine field
  package.json
Labels: team/devx, cla-signed

#51402 Cody completions: Don't send request when VS Code would not use the result
  client/cody/src/completions/index.ts
Labels: cla-signed, team/code-exploration

#51417 Cody: Add suffix to prompt knowledge base and better cut-off for multiline suggestions
  client/cody/CHANGELOG.md
  client/cody/src/completions/docprovider.ts
  client/cody/src/completions/index.ts
  client/cody/src/completions/provider.test.ts
  client/cody/src/completions/provider.ts
Labels: cla-signed, team/code-exploration

#51452 [gitlab] Disable repo permissions syncing if auth type is oauth
  CHANGELOG.md
  doc/admin/external_service/gitlab.md
  enterprise/internal/authz/gitlab/BUILD.bazel
  enterprise/internal/authz/gitlab/oauth.go
  enterprise/internal/authz/gitlab/oauth_test.go
  enterprise/internal/authz/gitlab/sudo_test.go
Labels: cla-signed, team/iam, backport 5.0

#51429 App: Update CodyEnabled logic to support usage in App
  internal/cody/BUILD.bazel
  internal/cody/feature_flag.go
  internal/cody/feature_flag_test.go
Labels: cla-signed

#51454 [Backport 5.0] feat: allow disabling of user centric or repo centric permission sync
  enterprise/cmd/frontend/worker/auth/perms_syncer_scheduler.go
  enterprise/cmd/frontend/worker/auth/perms_syncer_scheduler_test.go
  enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam, backports, backported-to-5.0

#51091 cody web ui: fix cody in web not working locally
  client/cody-shared/src/chat/client.ts
  client/cody-web/src/settings/useConfig.ts
  client/web/src/stores/codyChat.ts
Labels: cla-signed, team/iam

#51463 nix: run nix fmt
  dev/nix/comby.nix
  dev/nix/p4-fusion.nix
Labels: cla-signed

#51462 nix: start redis on localhost
  dev/nix/start-redis.sh
Labels: cla-signed

#51348 Improved Cody header logo and layout details
  client/cody-ui/src/utils/icons.tsx
  client/cody/webviews/App.css
  client/cody/webviews/Header.module.css
  client/cody/webviews/Header.tsx
  client/cody/webviews/NavBar.module.css
  client/cody/webviews/NavBar.tsx
Labels: cla-signed, cody, cody/vscode

#51461 embeddings: metric for search throughput
  enterprise/internal/embeddings/similarity_search_test.go
Labels: cla-signed

#51400 Disable injectHTML by default
  CHANGELOG.md
  cmd/frontend/internal/app/ui/handlers.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#51467 Cody: Release 0.0.10
  client/cody/CHANGELOG.md
  client/cody/package.json
Labels: cla-signed, team/code-exploration

#51298 App: Change system tray icon
  src-tauri/icons/tray.png
  src-tauri/tauri.conf.json
Labels: cla-signed, app

#51469 release: add missing "v" for build script
  dev/release/src/release.ts
Labels: cla-signed

#51474 Cody: Log chat prediction usage
  client/cody-ui/src/Chat.tsx
  client/cody/CHANGELOG.md
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/src/chat/protocol.ts
  client/cody/webviews/Chat.tsx
Labels: cla-signed, team/code-exploration

#51477 output: change grey colour to darker
  lib/output/style.go
Labels: cla-signed

#51293 own: add `own_aggregate_recent_view` table for recent view signal pro…
  internal/database/BUILD.bazel
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/database/recent_contribution_signal.go
  internal/database/recent_view_signal.go
  internal/database/recent_view_signal_test.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1682683129_add_recent_view_ownership_signal/down.sql
  migrations/frontend/1682683129_add_recent_view_ownership_signal/metadata.yaml
  migrations/frontend/1682683129_add_recent_view_ownership_signal/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, own

#51410 Add screens for github apps in site admin
  client/web/BUILD.bazel
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/components/externalServices/externalServices.tsx
  client/web/src/components/gitHubApps/AddGitHubAppPage.tsx
  client/web/src/components/gitHubApps/GitHubAppCard.module.scss
  client/web/src/components/gitHubApps/GitHubAppCard.tsx
  client/web/src/components/gitHubApps/GitHubAppPage.tsx
  client/web/src/components/gitHubApps/GitHubAppsPage.tsx
  client/web/src/components/gitHubApps/backend.ts
  client/web/src/site-admin/SiteAdminExternalServicesArea.tsx
  client/web/src/site-admin/SiteAdminGitHubAppsArea.tsx
  client/web/src/site-admin/routes.tsx
  cmd/frontend/graphqlbackend/githubapps.go
  cmd/frontend/graphqlbackend/githubapps.graphql
  enterprise/cmd/frontend/internal/auth/githubappauth/BUILD.bazel
  enterprise/cmd/frontend/internal/auth/githubappauth/middleware.go
  enterprise/cmd/frontend/internal/auth/githubappauth/resolver.go
Labels: cla-signed, team/iam, confirm-no-backport

#51475 wildcard: Add missing description field to Select
  client/wildcard/src/components/Form/Select/Select.story.tsx
  client/wildcard/src/components/Form/Select/Select.tsx
Labels: cla-signed

#51450 llm-proxy: enable GCP tracing, add more debug utils
  deps.bzl
  enterprise/cmd/llm-proxy/shared/BUILD.bazel
  enterprise/cmd/llm-proxy/shared/main.go
  enterprise/cmd/llm-proxy/shared/tracing.go
  go.mod
  go.sum
Labels: cla-signed

#51291 graphqlbackend: Support perforce changelists in repo and commits API
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_commit_test.go
  cmd/frontend/graphqlbackend/perforce_changelist.go
  cmd/frontend/graphqlbackend/perforce_changelist_test.go
  cmd/frontend/graphqlbackend/repositories_test.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/source_type.go
Labels: perforce, cla-signed

#51386 Embeddings: replace closures with structs
  enterprise/cmd/embeddings/shared/BUILD.bazel
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
  enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
Labels: cla-signed, backport 5.0

#51480 llm-proxy: move debug endpoints to /-/
  enterprise/cmd/llm-proxy/shared/main.go
Labels: cla-signed

#51415 App: Sync the site config to file
  cmd/frontend/graphqlbackend/site.go
  internal/conf/conf.go
  internal/singleprogram/singleprogram.go
Labels: cla-signed, app

#51435 Embeddings: simplify embeddings search index
  enterprise/cmd/embeddings/shared/search.go
  enterprise/internal/embeddings/similarity_search.go
Labels: cla-signed, backport 5.0

#51434 App: apply recommended tauri rust build config
  src-tauri/Cargo.toml
Labels: cla-signed

#51389 app: reduce Go binary size by 20M
  enterprise/cmd/sourcegraph/BUILD.bazel
Labels: cla-signed

#51487 remove tests and linter from backend integration branch
  doc/dev/background-information/ci/reference.md
Labels: cla-signed

#51489 App: Change tray icon to ico format
  src-tauri/icons/tray.ico
  src-tauri/icons/tray.png
  src-tauri/tauri.conf.json
Labels: cla-signed, app

#51077 cody: slash chat commands and display context search results
  client/cody-cli/src/app.ts
  client/cody-cli/src/context.ts
  client/cody-shared/BUILD.bazel
  client/cody-shared/src/chat/recipes/context-search.ts
  client/cody-shared/src/chat/recipes/vscode-recipes.ts
  client/cody-shared/src/chat/transcript/transcript.test.ts
  client/cody-shared/src/codebase-context/index.ts
  client/cody-shared/src/editor/index.ts
  client/cody-shared/src/keyword-context/index.ts
  client/cody-shared/src/test/mocks.ts
  client/cody-slack/src/app.ts
  client/cody-slack/src/services/codebase-context.ts
  client/cody-web/src/App.tsx
  client/cody/CHANGELOG.md
  client/cody/package.json
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/src/editor/vscode-editor.ts
  client/cody/src/keyword-context/local-keyword-context-fetcher.ts
  client/cody/src/main.ts
  client/cody/webviews/Recipes.tsx
  client/web/src/cody/CodeMirrorEditor.ts
Labels: cla-signed

#51412 migrations: change `-db` flag to be alias for `-schema` & allow container name as values
  dev/sg/sg_migration.go
  doc/dev/background-information/sg/reference.md
  internal/database/migration/cliutil/addlog.go
  internal/database/migration/cliutil/describe.go
  internal/database/migration/cliutil/downto.go
  internal/database/migration/cliutil/drift.go
  internal/database/migration/cliutil/undo.go
  internal/database/migration/cliutil/up.go
  internal/database/migration/cliutil/upto.go
  internal/database/migration/cliutil/util.go
  internal/database/migration/cliutil/validate.go
Labels: cla-signed, Multiversion Upgrade

#51493 llm-proxy: close redis conn after healthcheck
  enterprise/cmd/llm-proxy/shared/main.go
Labels: cla-signed

#51391 llm-proxy: implement authentication middleware
  enterprise/cmd/llm-proxy/internal/actor/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/actor/actor.go
  enterprise/cmd/llm-proxy/internal/dotcom/operations.go
  enterprise/cmd/llm-proxy/internal/dotcom/operations.graphql
  enterprise/cmd/llm-proxy/shared/BUILD.bazel
  enterprise/cmd/llm-proxy/shared/config.go
  enterprise/cmd/llm-proxy/shared/main.go
  enterprise/cmd/llm-proxy/shared/main_test.go
  enterprise/cmd/llm-proxy/shared/mocks_test.go
  mockgen.test.yaml
Labels: cla-signed

#51473 codeintel: Improve `io.ReadAll` by supplying size hint
  enterprise/internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
  enterprise/internal/codeintel/uploads/internal/background/processor/scip.go
  enterprise/internal/codeintel/uploads/internal/background/processor/scip_test.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#51496 codeintel: Differentiate expiration of (directly) unreferenced and (indirectly) unreferenced expired uploads
  enterprise/internal/codeintel/uploads/internal/store/expiration.go
Labels: team/code-intelligence, cla-signed, team/language-platform

#51470 [github app] Add resolver to get GitHubApp by ID
  cmd/frontend/graphqlbackend/githubapps.go
  cmd/frontend/graphqlbackend/githubapps.graphql
  cmd/frontend/graphqlbackend/graphqlbackend.go
  enterprise/cmd/frontend/internal/auth/githubappauth/resolver.go
  enterprise/cmd/frontend/internal/auth/githubappauth/resolver_test.go
Labels: cla-signed, team/iam

#51468 dev: improve description of embeddings-qa
  dev/sg/sg_embeddings_qa.go
  doc/dev/background-information/sg/reference.md
Labels: cla-signed

#51404 bazel: disable `build-ts` and build `client/cody` with Bazel
  .bazelignore
  client/app-shell/BUILD.bazel
  client/cody-shared/BUILD.bazel
  client/cody-ui/BUILD.bazel
  client/cody/BUILD.bazel
  client/cody/integration-test/BUILD.bazel
  client/cody/integration-test/tsconfig.json
  client/cody/scripts/BUILD.bazel
  client/cody/scripts/release.ts
  client/cody/scripts/tsconfig.json
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed, bazel, team/code-exploration, JF/bazel, cody

#51451 (feat) emphasize cody for new users on dotcom
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/BUILD.bazel
  client/web/src/auth/CloudSignUpPage.module.scss
  client/web/src/auth/CloudSignUpPage.tsx
  client/web/src/auth/VsCodeSignUpPage.tsx
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/auth/components/ExternalsAuth.module.scss
  client/web/src/auth/components/ExternalsAuth.tsx
  client/web/src/auth/components/FeatureList.module.scss
  client/web/src/auth/components/FeatureList.tsx
  client/web/src/components/MarketingBlock/MarketingBlock.module.scss
  client/web/src/components/MarketingBlock/MarketingBlock.story.tsx
  client/web/src/components/MarketingBlock/MarketingBlock.tsx
  client/web/src/components/SelfHostedCta/SelfHostedCta.story.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/TryCodyWidget.module.scss
  client/web/src/repo/blob/TryCodyWidget.tsx
  client/web/src/stores/codyChat.ts
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
  client/web/src/storm/pages/SearchPage/TryCodyCtaSection.module.scss
  client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
  client/web/src/storm/pages/SearchPage/TryCodySignUpCtaSection.module.scss
  client/web/src/storm/pages/SearchPage/TryCodySignUpCtaSection.tsx
  client/web/src/util/constants.ts
Labels: cla-signed

#51518 [github apps] Add app_url to github_apps table
  enterprise/internal/github_apps/store/store.go
  enterprise/internal/github_apps/store/store_test.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1683295546_add_app_url_column_for_github_apps/down.sql
  migrations/frontend/1683295546_add_app_url_column_for_github_apps/metadata.yaml
  migrations/frontend/1683295546_add_app_url_column_for_github_apps/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/iam

#51476 Embeddings: add repo source to results
  enterprise/cmd/embeddings/shared/search.go
  enterprise/cmd/embeddings/shared/weaviate.go
  enterprise/internal/embeddings/similarity_search.go
  enterprise/internal/embeddings/similarity_search_test.go
  enterprise/internal/embeddings/types.go
Labels: cla-signed

#51456 docs: add how-to for updating pnpm
  doc/dev/how-to/index.md
  doc/dev/how-to/update_pnpm.md
Labels: docs, team/devx, cla-signed

#51507 llmproxy: Make anonymous access opt-in
  enterprise/cmd/llm-proxy/shared/config.go
  sg.config.yaml
Labels: cla-signed

#51525 httpapi: Use repo.Name instead of URI for URL construction
  cmd/frontend/internal/httpapi/stream_blame.go
  cmd/frontend/internal/httpapi/stream_blame_test.go
Labels: bug, customer, cla-signed

#51321 adds `extensionDetails` to `public_argument` on JetBrains Logger
  client/jetbrains/webview/src/telemetry/EventLogger.ts
Labels: cla-signed

#51510 otel: add more processors and change filter ex to group ex.
  docker-images/opentelemetry-collector/builder.template.yaml
  docker-images/opentelemetry-collector/configs/group.yaml
Labels: dx, cla-signed

#51514 Use second rate limit bucket for code completions
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
  enterprise/cmd/frontend/internal/completions/resolvers/resolver.go
  enterprise/internal/completions/streaming/codecompletion.go
  enterprise/internal/completions/streaming/limiter.go
  enterprise/internal/completions/streaming/stream.go
  internal/database/mocks_temp.go
  internal/database/schema.json
  internal/database/schema.md
  internal/database/users.go
  internal/database/users_test.go
  migrations/BUILD.bazel
  migrations/frontend/1683290474_user_code_completions_quota/down.sql
  migrations/frontend/1683290474_user_code_completions_quota/metadata.yaml
  migrations/frontend/1683290474_user_code_completions_quota/up.sql
  migrations/frontend/squashed.sql
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/iam

#51505 Cody completions: Fix prompt size calculation for inline suggestions
  client/cody/CHANGELOG.md
  client/cody/src/completions/index.ts
Labels: cla-signed, team/code-exploration

#51527 bazel: migrate codeintele2e to bazel
  dev/ci/integration/code-intel/install-src.sh
  dev/ci/integration/code-intel/test.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#51522 Use second rate limit bucket for code completions
  client/web/src/user/settings/quota/UserQuotaProfilePage.tsx
  client/web/src/user/settings/quota/backend.ts
Labels: cla-signed, team/code-exploration

#51500 llm-proxy: implement initial rate-limiting and rate limit updates
  enterprise/cmd/llm-proxy/internal/actor/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/actor/actor.go
  enterprise/cmd/llm-proxy/internal/actor/productsubscription/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/actor/productsubscription/productsubscription.go
  enterprise/cmd/llm-proxy/internal/actor/source.go
  enterprise/cmd/llm-proxy/internal/dotcom/operations.go
  enterprise/cmd/llm-proxy/internal/dotcom/operations.graphql
  enterprise/cmd/llm-proxy/internal/limiter/error.go
  enterprise/cmd/llm-proxy/internal/limiter/limiter.go
  enterprise/cmd/llm-proxy/internal/limiter/limiter_test.go
  enterprise/cmd/llm-proxy/shared/BUILD.bazel
  enterprise/cmd/llm-proxy/shared/main.go
  enterprise/cmd/llm-proxy/shared/main_test.go
  sg.config.yaml
Labels: cla-signed

#51521 Cody: fix error notification display pattern for rate limit
  client/cody/CHANGELOG.md
  client/cody/src/chat/ChatViewProvider.ts
  client/cody/src/completions/index.ts
  client/cody/src/main.ts
  client/cody/webviews/App.css
Labels: cla-signed, cody

#51511 Fix build and update grpc/protobuf deps
  BUILD.bazel
  WORKSPACE
  cmd/gitserver/server/accesslog/BUILD.bazel
  deps.bzl
  internal/gitserver/v1/BUILD.bazel
  internal/repoupdater/v1/BUILD.bazel
  internal/searcher/v1/BUILD.bazel
  internal/symbols/v1/BUILD.bazel
Labels: cla-signed

#51478 own: recent view signal indexing background job.
  enterprise/cmd/worker/internal/own/job.go
  enterprise/cmd/worker/internal/telemetry/telemetry_job_test.go
  enterprise/internal/database/mocks_temp.go
  enterprise/internal/own/background/BUILD.bazel
  enterprise/internal/own/background/background.go
  enterprise/internal/own/background/recent_contributors.go
  enterprise/internal/own/background/recent_views.go
  enterprise/internal/own/background/recent_views_test.go
  internal/database/BUILD.bazel
  internal/database/database.go
  internal/database/event_logs.go
  internal/database/event_logs_scrape_state_own.go
  internal/database/event_logs_test.go
  internal/database/mocks_temp.go
  internal/database/recent_view_signal.go
  internal/database/recent_view_signal_test.go
Labels: cla-signed, own

#51513 own: make view signal listing support options.
  internal/database/recent_view_signal.go
  internal/database/recent_view_signal_test.go
Labels: cla-signed, own

#51534 llm-proxy: scaffold framework for full-sync sources and streamline auth
  enterprise/cmd/llm-proxy/internal/actor/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/actor/actor.go
  enterprise/cmd/llm-proxy/internal/actor/anonymous/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/actor/anonymous/anonymous.go
  enterprise/cmd/llm-proxy/internal/actor/productsubscription/productsubscription.go
  enterprise/cmd/llm-proxy/internal/actor/source.go
  enterprise/cmd/llm-proxy/internal/actor/source_test.go
  enterprise/cmd/llm-proxy/internal/auth/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/auth/auth.go
  enterprise/cmd/llm-proxy/internal/response/BUILD.bazel
  enterprise/cmd/llm-proxy/internal/response/response.go
  enterprise/cmd/llm-proxy/shared/BUILD.bazel
  enterprise/cmd/llm-proxy/shared/config.go
  enterprise/cmd/llm-proxy/shared/main.go
  enterprise/cmd/llm-proxy/shared/main_test.go
Labels: cla-signed

#51494 Add Cody across docsite
  doc/cody/explanations/enabling_cody.md
  doc/cody/explanations/index.md
  doc/cody/explanations/installing_vs_code.md
  doc/cody/index.md
  doc/cody/quickstart.md
  doc/getting-started/index.md
  doc/index.md
  doc/sidebar.md
  doc/tutorials/index.md
Labels: cla-signed

#51551 (fix) fix TryCodyCtaSection and TryCodyWidget not showing & flashing once dismissed
  client/web/src/repo/blob/TryCodyWidget.tsx
  client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
Labels: bug, merge-on-any-approve, cla-signed

#51559 Add the cody-icons font
  client/cody-ui/cody-icons-font/.gitignore
  client/cody-ui/cody-icons-font/.svgtofontrc
  client/cody-ui/cody-icons-font/README.md
  client/cody-ui/cody-icons-font/font/cody-icons.ttf
  client/cody-ui/cody-icons-font/font/cody-icons.woff
  client/cody-ui/cody-icons-font/font/cody-icons.woff2
  client/cody-ui/cody-icons-font/package.json
  client/cody-ui/cody-icons-font/svg/A.svg
Labels: cla-signed

#51562 bazel: add new info to docs
  doc/dev/background-information/bazel.md
  doc/dev/background-information/bazel_web.md
Labels: cla-signed, bazel, team/code-exploration, JF/bazel

#51516 [github app] Allow GitHub App installation connections to be validated
  enterprise/internal/database/external_services_test.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/repos/github.go
Labels: cla-signed, team/iam

#51570 CHANGELOG: Add src serve-git bug fix for 5.0.4
  CHANGELOG.md
Labels: cla-signed, backport 5.0

#51567 Revert "cody: hide cody.experimental.suggest (#51444)"
  client/cody/package.json
Labels: cla-signed, team/code-exploration

#51565 Cody completions: Ignore crashes when reading history files
  client/cody/CHANGELOG.md
  client/cody/src/completions/context.ts
Labels: cla-signed, team/code-exploration

#51555 nix: drop static bazel tools hack
  shell.nix
Labels: nix, cla-signed

#51564 search: remove unread stream parameters for decoration
  cmd/frontend/internal/search/search.go
Labels: cla-signed

#51563 search-plan: increase verbosity of output
  dev/internal/cmd/search-plan/BUILD.bazel
  dev/internal/cmd/search-plan/search-plan.go
Labels: cla-signed

#51566 search: apply limits in zoekt when doing select:repo
  internal/search/zoekt/indexed_search_test.go
  internal/search/zoekt/zoekt.go
Labels: cla-signed

#51535 Add tree-sitter highlighting for Kotlin
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/kotlin/highlights.scm
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/kotlin/injections.scm
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/kotlin/locals.scm
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/highlights.rs
  docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/parsers.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/kotlin.kt
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__kotlin.kt.snap
  internal/gosyntect/languages.go
Labels: cla-signed

#51583 app docs: fix social image sizes on Safari
  doc/app/index.md
Labels: cla-signed

#51580 Cody completions: Don't bubble errors
  client/cody-shared/src/sourcegraph-api/completions/nodeClient.ts
  client/cody/src/completions/index.ts
Labels: cla-signed, team/code-exploration
