Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-08, with the labels that each got.

#55380 File sidebar min width
  client/web/src/repo/RepoRevisionSidebar.tsx
Labels: cla-signed, cody/web-app

#55466 updatecheck: move up for others to imports
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/site_alerts.go
  cmd/frontend/graphqlbackend/site_update_check.go
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  internal/updatecheck/BUILD.bazel
  internal/updatecheck/build.go
  internal/updatecheck/build_test.go
  internal/updatecheck/client.go
  internal/updatecheck/client_test.go
  internal/updatecheck/doc.go
  internal/updatecheck/handler.go
  internal/updatecheck/handler_test.go
Labels: cla-signed

#55474 sveltekit: Add support for feature flags (and improve testing)
  client/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/featureflags/api.ts
  client/web-sveltekit/src/lib/featureflags/index.ts
  client/web-sveltekit/src/lib/featureflags/stores.test.ts
  client/web-sveltekit/src/lib/featureflags/stores.ts
  client/web-sveltekit/src/lib/stores.ts
  client/web-sveltekit/src/lib/utils/__snapshots__/time.test.ts.snap
  client/web-sveltekit/src/lib/utils/time.test.ts
  client/web-sveltekit/src/lib/web.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/+layout.ts
  client/web-sveltekit/src/testing/mocks.ts
  client/web-sveltekit/src/testing/setup.ts
  client/web-sveltekit/svelte.config.js
  client/web-sveltekit/tsconfig.json
  client/web-sveltekit/vite.config.ts
  pnpm-lock.yaml
Labels: cla-signed

#55481 sveltekit: Add badge wildcard component
  client/web-sveltekit/src/lib/wildcard/Badge.module.scss
  client/web-sveltekit/src/lib/wildcard/Badge.svelte
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/stories/Badge.stories.ts
  client/web-sveltekit/src/stories/BadgeExample.svelte
Labels: cla-signed

#55486 source: rename "Last repo commands" tab
  client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.tsx
  client/web/src/enterprise/repo/settings/__snapshots__/RepoSettingsLogsPage.test.tsx.snap
Labels: cla-signed

#55480 Update docs to reference `sg wolfi` commands
  doc/dev/how-to/wolfi/add_update_images.md
  doc/dev/how-to/wolfi/add_update_packages.md
Labels: cla-signed

#55243 Upgrade to Markprompt 0.14
  doc/_resources/assets/docsite.css
  doc/_resources/templates/root.html
Labels: cla-signed

#55485 source: reword text displayed when there's no output from the last sync
  client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.tsx
Labels: cla-signed

#55478 Update release nots with v5.1.x migrator inmage build bugs
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#55381 grpc: add interceptor that tracks the sizes of all messages sent by servers/clients
  CHANGELOG.md
  doc/admin/observability/dashboards.md
  internal/grpc/defaults/defaults.go
  internal/grpc/grpcutil/BUILD.bazel
  internal/grpc/grpcutil/util.go
  internal/grpc/grpcutil/util_test.go
  internal/grpc/internalerrs/BUILD.bazel
  internal/grpc/internalerrs/common.go
  internal/grpc/internalerrs/common_test.go
  internal/grpc/internalerrs/logging.go
  internal/grpc/internalerrs/prometheus.go
  internal/grpc/messagesize/BUILD.bazel
  internal/grpc/messagesize/messagesize.go
  internal/grpc/messagesize/prometheus.go
  internal/grpc/messagesize/prometheus_test.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/searcher.go
  monitoring/definitions/shared/grpc.go
  monitoring/definitions/symbols.go
Labels: cla-signed, backport 5.1

#55479 bazel: run gofmt as part of bazel configure step
  dev/ci/bazel-configure.sh
  dev/ci/bazel-prechecks.sh
  doc/dev/background-information/ci/reference.md
  enterprise/dev/ci/internal/ci/bazel_operations.go
Labels: cla-signed

#55456 Don't log certain high-volume events in local (postgres) databases
  internal/eventlogger/event_logger.go
  internal/usagestats/BUILD.bazel
  internal/usagestats/event_handlers.go
Labels: cla-signed

#55490 sveltekit: Add Timestamp component
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/Commit.svelte
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/lib/Timestamp.svelte
  client/web-sveltekit/src/lib/Timestamp.test.ts
  client/web-sveltekit/src/lib/Tooltip.svelte
  client/web-sveltekit/src/lib/__snapshots__/Timestamp.test.ts.snap
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/lib/repo/GitReference.svelte
  client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
  client/web-sveltekit/src/lib/utils/__snapshots__/time.test.ts.snap
  client/web-sveltekit/src/lib/utils/index.ts
  client/web-sveltekit/src/lib/utils/time.test.ts
  client/web-sveltekit/src/lib/utils/time.ts
  client/web-sveltekit/src/lib/wildcard/Badge.svelte
  client/web-sveltekit/src/lib/wildcard/Button.svelte
  client/web-sveltekit/src/lib/wildcard/ButtonGroup.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
  client/web-sveltekit/src/routes/search/StreamingProgress.svelte
  client/web-sveltekit/src/stories/BadgeExample.svelte
  client/web-sveltekit/src/stories/Timestamp.stories.ts
  client/web-sveltekit/src/stories/TimestampExample.svelte
  client/web-sveltekit/src/stories/Tooltip.stories.ts
  client/web-sveltekit/src/stories/TooltipExample.svelte
  client/web-sveltekit/src/testing/setup.ts
  client/web-sveltekit/vite.config.ts
  pnpm-lock.yaml
Labels: cla-signed

#55498 grpc: monitoring: remove needless prometheus namespace
  internal/grpc/defaults/BUILD.bazel
  internal/grpc/defaults/defaults.go
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/searcher.go
  monitoring/definitions/shared/grpc.go
  monitoring/definitions/symbols.go
Labels: cla-signed, backport 5.1

#55180 Allow embeddings job to exclude failed files from the index
  CHANGELOG.md
  enterprise/cmd/embeddings/qa/embed_queries/main.go
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/conf/conftypes/consts.go
  internal/database/schema.json
  internal/database/schema.md
  internal/embeddings/background/repo/store.go
  internal/embeddings/background/repo/store_test.go
  internal/embeddings/background/repo/types.go
  internal/embeddings/embed/BUILD.bazel
  internal/embeddings/embed/client/azureopenai/client.go
  internal/embeddings/embed/client/azureopenai/client_test.go
  internal/embeddings/embed/client/client.go
  internal/embeddings/embed/client/openai/client.go
  internal/embeddings/embed/client/openai/client_test.go
  internal/embeddings/embed/client/sourcegraph/client.go
  internal/embeddings/embed/client/sourcegraph/client_test.go
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
  migrations/BUILD.bazel
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/down.sql
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/metadata.yaml
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/up.sql
  migrations/frontend/squashed.sql
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, cody/context, backport 5.1

#55500 updatecheck: read `HasCodyEnabled` from ping request
  internal/updatecheck/handler.go
Labels: cla-signed

#55037 sveltekit: Add line selection to blob view
  client/web-sveltekit/src/app.html
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/Timestamp.test.ts
  client/web-sveltekit/src/lib/__snapshots__/Timestamp.test.ts.snap
  client/web-sveltekit/src/lib/common.ts
  client/web-sveltekit/src/lib/repo/blob.test.ts
  client/web-sveltekit/src/lib/repo/blob.ts
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/lib/web.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/search/FileSearchResult.svelte
  client/web/src/repo/blob/codemirror/highlight.ts
Labels: cla-signed

#55372 Embeddings: implement db package
  deps.bzl
  go.mod
  go.sum
  internal/embeddings/db/BUILD.bazel
  internal/embeddings/db/chunk_point.go
  internal/embeddings/db/chunk_point_test.go
  internal/embeddings/db/db.go
  internal/embeddings/db/migrate.go
  internal/embeddings/db/qdrant.go
Labels: cla-signed

#55459 Backend: remove internalClient.SendEmail
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  cmd/frontend/internal/httpapi/internal_test.go
  cmd/frontend/internal/httpapi/router/router.go
  internal/api/internalapi/BUILD.bazel
  internal/api/internalapi/client.go
  internal/codemonitors/background/email.go
Labels: cla-signed, backport 5.1

#55528 Update exclude chunks migration metadata to align with 5.1 release branch
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/metadata.yaml
Labels: cla-signed

#55463 Backend: remove internalClient.ExternalURL
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/router/router.go
  internal/api/internalapi/client.go
  internal/batches/reconciler/BUILD.bazel
  internal/batches/reconciler/executor_test.go
  internal/batches/reconciler/reconciler_test.go
  internal/batches/types/BUILD.bazel
  internal/batches/types/batch_change.go
  internal/batches/types/batch_change_test.go
  internal/codemonitors/background/BUILD.bazel
  internal/codemonitors/background/email.go
  internal/codemonitors/background/workers.go
Labels: cla-signed, backport 5.1

#55530 [Backport 5.1] Allow embeddings job to exclude failed files from the index
  CHANGELOG.md
  enterprise/cmd/embeddings/qa/embed_queries/main.go
  enterprise/cmd/embeddings/shared/main.go
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/conf/conftypes/consts.go
  internal/database/schema.json
  internal/database/schema.md
  internal/embeddings/background/repo/store.go
  internal/embeddings/background/repo/store_test.go
  internal/embeddings/background/repo/types.go
  internal/embeddings/embed/BUILD.bazel
  internal/embeddings/embed/client/azureopenai/client.go
  internal/embeddings/embed/client/azureopenai/client_test.go
  internal/embeddings/embed/client/client.go
  internal/embeddings/embed/client/openai/client.go
  internal/embeddings/embed/client/openai/client_test.go
  internal/embeddings/embed/client/sourcegraph/client.go
  internal/embeddings/embed/client/sourcegraph/client_test.go
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
  migrations/BUILD.bazel
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/down.sql
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/metadata.yaml
  migrations/frontend/1690323910_add_chunks_excluded_embeddings_stats/up.sql
  migrations/frontend/squashed.sql
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, backports, backported-to-5.1

#55520 Add API version header to Anthropic API requests
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  internal/completions/client/anthropic/anthropic.go
Labels: cla-signed, backport 5.1

#55402 Add database layer for code hosts table
  internal/database/BUILD.bazel
  internal/database/code_hosts.go
  internal/database/code_hosts_test.go
  internal/database/conf.go
  internal/database/database.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/mocks_temp.go
  internal/extsvc/types.go
  internal/extsvc/types_test.go
  internal/types/types.go
  internal/types/typestest/typestest.go
Labels: cla-signed

#55531 grpc: monitoring: fix method label query
  monitoring/definitions/frontend.go
  monitoring/definitions/git_server.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/searcher.go
  monitoring/definitions/shared/grpc.go
  monitoring/definitions/symbols.go
Labels: cla-signed

#55543 web: don't disable "Settings" menu item for uncloned repos.
  client/web/src/site-admin/RepositoryNode.tsx
Labels: cla-signed, team/source

#55549 embeddings: apply model transformations (backport #54302 to 5.1)
  enterprise/cmd/embeddings/qa/embed_queries/main.go
  enterprise/cmd/embeddings/shared/main.go
  internal/embeddings/embed/client/azureopenai/BUILD.bazel
  internal/embeddings/embed/client/azureopenai/client.go
  internal/embeddings/embed/client/azureopenai/client_test.go
  internal/embeddings/embed/client/client.go
  internal/embeddings/embed/client/modeltransformations/BUILD.bazel
  internal/embeddings/embed/client/modeltransformations/model_transformations.go
  internal/embeddings/embed/client/modeltransformations/model_transformations_test.go
  internal/embeddings/embed/client/openai/BUILD.bazel
  internal/embeddings/embed/client/openai/client.go
  internal/embeddings/embed/client/openai/client_test.go
  internal/embeddings/embed/client/sourcegraph/BUILD.bazel
  internal/embeddings/embed/client/sourcegraph/client.go
  internal/embeddings/embed/client/sourcegraph/client_test.go
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
Labels: cla-signed

#55519 attribution: stop searching as soon as we hit our limit
  enterprise/cmd/frontend/internal/guardrails/attribution/attribution.go
  enterprise/cmd/frontend/internal/guardrails/attribution/attribution_test.go
Labels: cla-signed

#55550 Fix docs logo on the website
  doc/_resources/assets/logo-theme-dark.svg
  doc/_resources/assets/logo-theme-light.svg
Labels: docs, docs-ux, cla-signed

#55557 github: Fetch parent repo information from API
  go.sum
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_existing_fork
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_existing_changeset_and_new_fork
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_existing_fork
  internal/batches/sources/testdata/golden/GithubSource_GetFork_success_with_new_changeset_and_new_fork
  internal/extsvc/github/common.go
  internal/extsvc/github/testdata/golden/TestGetRepository/cached-response/first_run
  internal/extsvc/github/testdata/golden/TestGetRepository/cached-response/second_run
  internal/extsvc/github/testdata/golden/TestGetRepository/forked_repo
  internal/extsvc/github/testdata/golden/TestGetRepository/repo_not_found
  internal/extsvc/github/testdata/golden/TestV3Client_Fork_success_sourcegraph-testing
  internal/extsvc/github/testdata/golden/TestV3Client_Fork_success_user
  internal/extsvc/github/testdata/vcr/GetRepository.yaml
  internal/extsvc/github/v3_test.go
  internal/extsvc/github/v4.go
  internal/extsvc/github/v4_test.go
Labels: cla-signed, git-dedupe

#55551 Add small tweaks to Cody intro
  doc/cody/index.md
Labels: docs, cla-signed

#55088 Update Discord channel name
  doc/cody/troubleshooting.md
Labels: cla-signed

#55537 cody-gateway: fix adding validation errors, remove custom Validate()
  cmd/cody-gateway/shared/config.go
Labels: cla-signed

#55565 cloud doc: fixed broken header link
  doc/cloud/index.md
Labels: docs, cla-signed

#55556 cody chat: do not recreate empty chat
  client/web/src/cody/useCodyChat.tsx
Labels: cla-signed

#55488 update hash for p4-fusion.nix
  dev/nix/p4-fusion.nix
Labels: nix, cla-signed

#55526 Add new section for Cody Capabilities
  doc/_resources/assets/redirects
  doc/cody/autocomplete.md
  doc/cody/capabilities.md
  doc/sidebar.md
Labels: docs, cla-signed

#55569 Make docs links open in a new tab by default
  doc/_resources/templates/root.html
Labels: docs, docs-ux, cla-signed

#55564 sg: add argo app to template
  dev/sg/sg_deploy.go
Labels: cla-signed

#55583 Revert "Make docs links open in a new tab by default"
  doc/_resources/templates/root.html
Labels: cla-signed

#55585 Revert "AMI executor docs"
  doc/admin/deploy/machine-images/aws-ami.md
  doc/admin/deploy/machine-images/gce.md
Labels: cla-signed

#55546 blob: Always select search input value when pressing Mod-f
  CHANGELOG.md
  client/web/src/repo/blob/codemirror/search.tsx
Labels: cla-signed, code-search

#55605 Update wolfi base images for 5.1.6
  dev/oci_deps.bzl
Labels: cla-signed, backport 5.1

#55513 Add GH App code host connection check
  cmd/gitserver/shared/shared.go
  cmd/repo-updater/shared/BUILD.bazel
  cmd/repo-updater/shared/main.go
  enterprise/cmd/frontend/internal/batches/resolvers/changeset_counts_test.go
  enterprise/cmd/frontend/internal/batches/webhooks/github_test.go
  enterprise/cmd/gitserver/shared/BUILD.bazel
  enterprise/cmd/gitserver/shared/shared.go
  internal/authz/providers/github/BUILD.bazel
  internal/authz/providers/github/authz.go
  internal/batches/sources/github.go
  internal/batches/sources/github_test.go
  internal/batches/sources/sources.go
  internal/extsvc/github/auth/BUILD.bazel
  internal/extsvc/github/auth/auth.go
  internal/extsvc/github/auth/auth_test.go
  internal/github_apps/auth/BUILD.bazel
  internal/github_apps/auth/auth.go
  internal/github_apps/auth/auth_test.go
  internal/repos/BUILD.bazel
  internal/repos/clone_url.go
  internal/repos/clone_url_test.go
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/sources.go
Labels: cla-signed, team/iam

#55510 Update Docker-in-Docker image from 23.0.1 -> 23.0.6
  doc/dev/background-information/ci/reference.md
  docker-images/dind/Dockerfile
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed, backport 5.1

#55607 [Backport 5.1] Update wolfi base images for 5.1.6
  dev/oci_deps.bzl
Labels: cla-signed

#55610 [Backport 5.1] Update Docker-in-Docker image from 23.0.1 -> 23.0.6
  doc/dev/background-information/ci/reference.md
  docker-images/dind/Dockerfile
  enterprise/dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#55612 Update moby/buildkit to v0.11.6
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#55586 AMI executor instructions
  doc/admin/deploy/machine-images/aws-ami.md
  doc/admin/deploy/machine-images/aws-oneclick.md
  doc/admin/deploy/machine-images/gce.md
Labels: cla-signed

#55617 gitserver: Removed test that was never enabled
  internal/gitserver/client_test.go
Labels: cla-signed

#55560 httpcli: set httpcli.retried=false on first attempt
  internal/httpcli/client.go
Labels: cla-signed

#55596 Add links to Cody features on main homepage
  doc/cody/index.md
Labels: docs-ux, cla-signed

#55619 release: changelog update for 5.1.6
  CHANGELOG.md
Labels: cla-signed

#55618 Add concept of Raw executable
  cmd/frontend/graphqlbackend/access_requests_test.go
  internal/database/accessrequests/access_requests.go
  internal/database/database.go
  internal/database/database_test.go
  internal/database/mockclient.go
Labels: cla-signed, team/iam

#55584 Fix Markprompt search links
  doc/_resources/templates/root.html
Labels: cla-signed

#55614 Update aside/beta section
  doc/cody/index.md
Labels: docs, cla-signed

#55621 Fix title links
  doc/_resources/templates/root.html
Labels: cla-signed

#55620 Place FAQ last in Cody nav order
  doc/sidebar.md
Labels: docs-ux, cla-signed

#55626 Docs: fix link colors
  doc/_resources/assets/docsite.css
  doc/_resources/templates/root.html
Labels: cla-signed

#55636 Security updates in changelog for 5.1.6
  CHANGELOG.md
Labels: cla-signed

#55542 sveltekit: Add support missing search result types
  client/web-sveltekit/.prettierignore
  client/web-sveltekit/.storybook/main.ts
  client/web-sveltekit/.storybook/preview.ts
  client/web-sveltekit/package.json
  client/web-sveltekit/src/app.html
  client/web-sveltekit/src/lib/UserAvatar.svelte
  client/web-sveltekit/src/lib/common.ts
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/lib/intersection-observer.ts
  client/web-sveltekit/src/lib/search/results.ts
  client/web-sveltekit/src/lib/search/state.ts
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/lib/utils/stores.ts
  client/web-sveltekit/src/routes/+layout.ts
  client/web-sveltekit/src/routes/search/+page.svelte
  client/web-sveltekit/src/routes/search/CodeExcerpt.svelte
  client/web-sveltekit/src/routes/search/CodeHostIcon.svelte
  client/web-sveltekit/src/routes/search/CommitSearchResult.svelte
  client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
  client/web-sveltekit/src/routes/search/FilePathSearchResult.svelte
  client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
  client/web-sveltekit/src/routes/search/PersonSearchResult.svelte
  client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
  client/web-sveltekit/src/routes/search/RepoStars.svelte
  client/web-sveltekit/src/routes/search/SearchResult.svelte
  client/web-sveltekit/src/routes/search/SearchResults.stories.svelte
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
  client/web-sveltekit/src/routes/search/TeamSearchResult.svelte
  client/web-sveltekit/src/routes/search/searchResultFactory.ts
  client/web-sveltekit/src/testdata.ts
  client/web-sveltekit/src/testing/mocks.ts
  client/web-sveltekit/static/mockServiceWorker.js
  client/web-sveltekit/vite.config.ts
  pnpm-lock.yaml
Labels: cla-signed, code-search

#55616 sveltekit: Show readme on repo and tree pages
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
  client/web-sveltekit/src/lib/repo/FileTable.svelte
  client/web-sveltekit/src/lib/repo/api/tree.ts
  client/web-sveltekit/src/lib/repo/tree.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.ts
Labels: cla-signed

#55637 Migrate to command pattern
  cmd/frontend/graphqlbackend/access_requests.go
  cmd/frontend/graphqlbackend/access_requests_test.go
  internal/auth/accessrequest/handlers.go
  internal/auth/accessrequest/handlers_test.go
  internal/database/accessrequests/access_requests.go
  internal/database/accessrequests/access_requests_test.go
  internal/database/accessrequests/count.go
  internal/database/accessrequests/count_test.go
  internal/database/accessrequests/create.go
  internal/database/accessrequests/create_test.go
  internal/database/accessrequests/get_by_email.go
  internal/database/accessrequests/get_by_email_test.go
  internal/database/accessrequests/get_by_id.go
  internal/database/accessrequests/get_by_id_test.go
  internal/database/accessrequests/list.go
  internal/database/accessrequests/list_test.go
  internal/database/accessrequests/store.go
  internal/database/accessrequests/update.go
  internal/database/accessrequests/update_test.go
  internal/database/database.go
  internal/database/mockclient.go
  internal/database/mocks_temp.go
Labels: cla-signed, team/iam

#55631 Docs bitbucket server test plan
  doc/dev/background-information/test-plans/code-hosts/bitbucket_server.md
  doc/dev/background-information/test-plans/code-hosts/index.md
  doc/dev/background-information/test-plans/index.md
  doc/dev/index.md
Labels: cla-signed, team/iam

#55613 feat(setup-checklist): add setup wizard checklist steps behind ff
  client/web/BUILD.bazel
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/global/GlobalAlerts.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/setup-wizard/SetupWizard.test.tsx
  client/web/src/setup-wizard/SetupWizard.tsx
  client/web/src/setup-wizard/__snapshots__/SetupWizard.test.tsx.snap
  client/web/src/site-admin/setup-checklist/index.tsx
  client/web/src/site-admin/setup-checklist/useSetupChecklist.tsx
Labels: cla-signed

#55604 sveltekit: Enable graphql generation and inspect modes
  client/shared/dev/generateGraphQlOperations.js
  client/web-sveltekit/package.json
  client/web-sveltekit/svelte.config.js
  client/web-sveltekit/vite.config.ts
  package.json
  pnpm-lock.yaml
Labels: cla-signed, code-search

#55640 codygateway: Always return all Sourcegraph access tokens
  enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
Labels: cla-signed

#55643 codeintel: Upload sg/sg to codyintel
  .github/workflows/scip-go.yml
  .github/workflows/scip-typescript.yml
Labels: cla-signed

#55559 Embeddings: minimal local qdrant ingestion
  cmd/frontend/internal/cli/config.go
  doc/dev/background-information/sg/reference.md
  enterprise/cmd/worker/internal/embeddings/repo/BUILD.bazel
  enterprise/cmd/worker/internal/embeddings/repo/handler.go
  enterprise/cmd/worker/internal/embeddings/repo/worker.go
  internal/conf/conftypes/conftypes.go
  internal/embeddings/db/BUILD.bazel
  internal/embeddings/db/qdrant.go
  sg.config.yaml
Labels: cla-signed

#55646 5.1.6 patch: Update CHANGELOG.md for gRPC changes
  CHANGELOG.md
Labels: cla-signed

#55647 Linting: add `unused` lint
  BUILD.bazel
  dev/linters/unused/BUILD.bazel
  dev/linters/unused/unused.go
Labels: cla-signed

#55650 migrations: Update backfill assumptions
  internal/database/migration/store/store.go
  internal/database/migration/store/store_test.go
Labels: cla-signed, backport 5.1

#54410 codeintel: Make codenav results more consistent
  dev/ci/integration/code-intel/repos.json
  dev/codeintel-qa/README.md
  dev/codeintel-qa/cmd/clone-and-index/main.go
  dev/codeintel-qa/cmd/query/BUILD.bazel
  dev/codeintel-qa/cmd/query/queries.go
  dev/codeintel-qa/cmd/query/query.go
  dev/codeintel-qa/cmd/query/query_types.go
  dev/codeintel-qa/cmd/query/state.go
  dev/codeintel-qa/cmd/query/test_cases.go
  dev/codeintel-qa/cmd/query/test_cases_utils.go
  dev/codeintel-qa/cmd/upload/state.go
  dev/codeintel-qa/cmd/upload/upload.go
  dev/codeintel-qa/internal/indexes.go
  internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
  internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
  internal/codeintel/codenav/transport/graphql/root_resolver_implementations.go
  internal/codeintel/codenav/transport/graphql/root_resolver_references.go
  internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  testing/BUILD.bazel
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.1, cody-intel

#55591 httpcli: respect retry-after on all error responses, set retry-after in Cody Gateway responses
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/embeddings/openai.go
  cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
  cmd/sitemap/graphql.go
  internal/httpcli/client.go
  internal/httpcli/client_test.go
Labels: cla-signed, backport 5.1

#55651 [5.1.6] Changelog update: new excludeChunkOnError config setting
  CHANGELOG.md
Labels: cla-signed

#55645 docs: fix outdated commands in release tooling
  dev/release/templates/patch_release_issue_template.md
  dev/release/templates/release_issue_template.md
Labels: cla-signed, dev-infra/rfc-795

#55660 extsvc: remove unused vars
  internal/extsvc/types.go
Labels: cla-signed, team/iam

#55343 [Backport 5.1] uploads: Simplify code for streaming indexes
  internal/codeintel/uploads/internal/background/processor/BUILD.bazel
  internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
  internal/codeintel/uploads/internal/background/processor/scip.go
  internal/codeintel/uploads/internal/background/processor/scip_test.go
  internal/codeintel/uploads/internal/lsifstore/BUILD.bazel
  internal/codeintel/uploads/internal/lsifstore/insert.go
  lib/codeintel/precise/types.go
Labels: cla-signed, backports, backported-to-5.1

#55394 chore: improve User Permissions screen
  client/web/BUILD.bazel
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.test.tsx
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
  client/web/src/enterprise/user/settings/auth/__snapshots__/UserSettingsPermissionsPage.test.tsx.snap
  client/web/src/enterprise/user/settings/auth/backend.ts
  client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
  cmd/frontend/graphqlbackend/authz.go
  cmd/frontend/graphqlbackend/authz.graphql
  enterprise/cmd/frontend/internal/authz/resolvers/permissions_info.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
  enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
  internal/authz/perms.go
  internal/database/perms_store.go
  internal/database/perms_store_test.go
Labels: cla-signed, team/iam

#55630 chore: remove unused `CloneFromShard` from `RepoUpdateRequest`.
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_test.go
  internal/gitserver/client_test.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: gitserver, cla-signed

#55654 cleanup: Simplify Lua sandbox code using generics
  internal/codeintel/autoindexing/internal/inference/libs/patterns.go
  internal/codeintel/autoindexing/internal/inference/luatypes/index_job.go
  internal/codeintel/autoindexing/internal/inference/luatypes/index_job_hint.go
  internal/codeintel/autoindexing/internal/inference/luatypes/path_patterns.go
  internal/codeintel/autoindexing/internal/inference/luatypes/recognizers.go
  internal/codeintel/autoindexing/internal/inference/service.go
  internal/luasandbox/util/util.go
Labels: cla-signed

#55649 gitserver: Cleanup config
  cmd/gitserver/shared/BUILD.bazel
  cmd/gitserver/shared/config.go
  cmd/gitserver/shared/config_test.go
  cmd/gitserver/shared/shared.go
  cmd/gitserver/shared/shared_test.go
Labels: cla-signed

#55655 codeintel: Make codenav results more consistent (#54410)
  dev/ci/integration/code-intel/repos.json
  dev/codeintel-qa/README.md
  dev/codeintel-qa/cmd/clone-and-index/main.go
  dev/codeintel-qa/cmd/query/BUILD.bazel
  dev/codeintel-qa/cmd/query/queries.go
  dev/codeintel-qa/cmd/query/query.go
  dev/codeintel-qa/cmd/query/query_types.go
  dev/codeintel-qa/cmd/query/state.go
  dev/codeintel-qa/cmd/query/test_cases.go
  dev/codeintel-qa/cmd/query/test_cases_utils.go
  dev/codeintel-qa/cmd/upload/state.go
  dev/codeintel-qa/cmd/upload/upload.go
  dev/codeintel-qa/internal/indexes.go
  internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
  internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
  internal/codeintel/codenav/transport/graphql/root_resolver_implementations.go
  internal/codeintel/codenav/transport/graphql/root_resolver_references.go
  internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  testing/BUILD.bazel
Labels: cla-signed

#55667 feat(setup-checklist): add checklist validity checking & redirecting base
  client/web/BUILD.bazel
  client/web/src/LegacyLayout.tsx
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/setup-wizard/SetupWizard.test.tsx
  client/web/src/setup-wizard/SetupWizard.tsx
  client/web/src/setup-wizard/__snapshots__/SetupWizard.test.tsx.snap
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
  client/web/src/site-admin/setup-checklist/ChecklistInfo.tsx
  client/web/src/site-admin/setup-checklist/ChecklistNavbarItem.tsx
  client/web/src/site-admin/setup-checklist/hooks/useSetupChecklist.tsx
  client/web/src/site-admin/setup-checklist/useSetupChecklist.tsx
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
Labels: cla-signed

#55627 Update use_cases.md
  doc/cody/explanations/use_cases.md
Labels: cla-signed, docs-issue

#55659 add release notes and reference to resolution issue
  doc/admin/updates/docker_compose.md
  doc/admin/updates/kubernetes.md
Labels: cla-signed

#55683 ci: add check for dangling docker containers
  .buildkite/hooks/pre-command
Labels: cla-signed

#54851 GitLab extension: Fix for repositories with `repositoryPathPattern` set
  client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts
  client/browser/src/shared/code-hosts/gitlab/scrape.ts
Labels: cla-signed, team/code-exploration

#55624 cody-gateway, sourcegraph: disable code completions for OpenAI
  CHANGELOG.md
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  doc/app/app_configuration.md
  doc/cody/explanations/cody_gateway.md
  internal/completions/client/azureopenai/openai.go
  internal/completions/client/openai/openai.go
Labels: cla-signed, backport 5.1

#55679 [Backport 5.1] Add site admin banner warning when exceeding Cody limits (#55460)
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/app.go
  cmd/frontend/graphqlbackend/cody_gateway_rate_limit.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site_alerts.go
  cmd/worker/internal/codygateway/BUILD.bazel
  cmd/worker/internal/codygateway/usageworker.go
  cmd/worker/shared/BUILD.bazel
  cmd/worker/shared/main.go
  internal/codygateway/BUILD.bazel
  internal/codygateway/client.go
  internal/codygateway/consts.go
  internal/codygateway/types.go
Labels: cla-signed

#55686 Chore: remove a handful of unused code
  internal/database/BUILD.bazel
  internal/database/code_monitors.go
  internal/database/recent_contribution_signal.go
  internal/database/test_util.go
  internal/database/users.go
  internal/database/util_test.go
  internal/embeddings/client.go
  internal/embeddings/embed/embed.go
  internal/extsvc/types.go
  internal/goroutine/periodic.go
  internal/goroutine/periodic_test.go
  internal/observation/observation.go
  internal/own/service.go
  internal/search/keyword/BUILD.bazel
  internal/search/keyword/keywords.go
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
  internal/ttlcache/cache.go
  internal/ttlcache/cache_test.go
Labels: cla-signed

#55687 Chore: replace pointer helpers with pointers package
  internal/database/external_services_test.go
  internal/database/org_members_db_test.go
  internal/database/permission_sync_jobs_test.go
  internal/database/user_emails_test.go
  internal/database/users_test.go
  internal/database/util_test.go
Labels: cla-signed

#55623 Web: Fix TypeScript problems on main
  client/web/src/auth/CloudSignUpPage.story.tsx
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.story.tsx
  client/web/src/cody/update/UpdateInfoContent.story.tsx
  client/web/src/enterprise/batches/list/BatchChangesListIntro.story.tsx
  client/web/src/repo/blob/own/FileOwnershipPanel.story.tsx
Labels: cla-signed

#55689 [Backport 5.1] cody-gateway, sourcegraph: disable code completions for OpenAI (#55624)
  CHANGELOG.md
  deps.bzl
  doc/cody/explanations/cody_gateway.md
  enterprise/cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  enterprise/cmd/cody-gateway/internal/httpapi/completions/openai.go
  enterprise/cmd/cody-gateway/internal/httpapi/completions/upstream.go
  internal/completions/client/azureopenai/openai.go
  internal/completions/client/openai/openai.go
Labels: cla-signed

#55693 remove references to Recipes for Cody
  doc/cloud/index.md
  doc/cody/capabilities.md
  doc/cody/explanations/enabling_cody_enterprise.md
  doc/cody/explanations/use_cases.md
Labels: cla-signed

#55692 changelog: disabled openai code completions in 5.1.6
  CHANGELOG.md
Labels: cla-signed

#55656 [Backport 5.1] httpcli: respect retry-after on all error responses, set retry-after in Cody Gateway responses
  cmd/sitemap/graphql.go
  enterprise/cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  enterprise/cmd/cody-gateway/internal/httpapi/completions/openai.go
  enterprise/cmd/cody-gateway/internal/httpapi/completions/upstream.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
  internal/httpcli/client.go
  internal/httpcli/client_test.go
Labels: cla-signed

#55642 codeintel: Do not store empty packages in `lsif_{packages,references}` tables
  internal/codeintel/uploads/internal/background/processor/scip.go
Labels: team/code-intelligence, cla-signed, team/language-platform, backport 5.1

#55699 Move bundled executor out of enterprise/cmd
  cmd/bundled-executor/BUILD.bazel
  cmd/bundled-executor/README.md
  cmd/bundled-executor/image_test.yaml
Labels: cla-signed

#55698 Fix: Repo embedding scheduler job routine as internal actor
  CHANGELOG.md
  enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
Labels: cla-signed, backport 5.1

#55702 cleanup: Remove unused function
  internal/gitserver/gitdomain/common.go
Labels: cla-signed

#55703 Fix main build due to broken paths in scripts
  cmd/executor/build_binary.sh
  cmd/executor/docker-mirror/build.sh
  cmd/executor/release_binary.sh
  cmd/executor/vm-image/build.sh
  enterprise/dev/ci/internal/ci/operations.go
Labels: cla-signed

#55538 internal/event_logs: optimize ping cte
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/database/schema.json
  internal/database/schema.md
  migrations/BUILD.bazel
  migrations/frontend/1691043630_event_logs_indexing/down.sql
  migrations/frontend/1691043630_event_logs_indexing/metadata.yaml
  migrations/frontend/1691043630_event_logs_indexing/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, backports

#55701 [Backport 5.1] Fix: Repo embedding scheduler job routine as internal actor (#55698)
  CHANGELOG.md
  enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
Labels: cla-signed

#55716 backport: stitch migration change
  migrations/frontend/1691043630_event_logs_indexing/metadata.yaml
Labels: cla-signed

#55685 sveltekit: Refactor graphql setup
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/context.ts
  client/web-sveltekit/src/lib/featureflags/api.ts
  client/web-sveltekit/src/lib/graphql/apollo.ts
  client/web-sveltekit/src/lib/graphql/index.ts
  client/web-sveltekit/src/lib/http-client.ts
  client/web-sveltekit/src/lib/loader/auth.ts
  client/web-sveltekit/src/lib/loader/blob.ts
  client/web-sveltekit/src/lib/loader/repo.ts
  client/web-sveltekit/src/lib/repo/BottomPanel.svelte
  client/web-sveltekit/src/lib/repo/FileTable.svelte
  client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
  client/web-sveltekit/src/lib/repo/Permalink.svelte
  client/web-sveltekit/src/lib/repo/api/blob.ts
  client/web-sveltekit/src/lib/repo/api/commits.ts
  client/web-sveltekit/src/lib/repo/api/contributors.ts
  client/web-sveltekit/src/lib/repo/api/refs.ts
  client/web-sveltekit/src/lib/repo/api/repo.ts
  client/web-sveltekit/src/lib/repo/api/tree.ts
  client/web-sveltekit/src/lib/repo/tree.ts
  client/web-sveltekit/src/lib/repo/utils.ts
  client/web-sveltekit/src/lib/search/api/highlighting.ts
  client/web-sveltekit/src/lib/search/symbolIcons.ts
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/lib/stores.ts
  client/web-sveltekit/src/lib/user/api/settings.ts
  client/web-sveltekit/src/lib/user/api/user.ts
  client/web-sveltekit/src/lib/web.ts
  client/web-sveltekit/src/routes/(enterprise)/notebooks/[...path]/+page.svelte
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/RepoNotFoundError.svelte
  client/web-sveltekit/src/testdata.ts
  client/web-sveltekit/svelte.config.js
  client/web-sveltekit/vite.config.ts
Labels: cla-signed, code-search

#55670 nitpick rename: rename IsCloud to IsDotCom
  cmd/repo-updater/shared/main.go
  internal/repos/store.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: cla-signed, team/iam

#55398 Wolfi CI improvements
  dev/ci/runtype/runtype.go
  doc/dev/background-information/ci/reference.md
  doc/dev/background-information/sg/reference.md
  doc/dev/how-to/wolfi/add_update_images.md
  enterprise/dev/ci/glossary.md
  enterprise/dev/ci/internal/ci/BUILD.bazel
  enterprise/dev/ci/internal/ci/pipeline.go
  enterprise/dev/ci/internal/ci/test/BUILD.bazel
  enterprise/dev/ci/internal/ci/test/wolfi-images/wolfi-test-image-1.yaml
  enterprise/dev/ci/internal/ci/test/wolfi-images/wolfi-test-image-2.yaml
  enterprise/dev/ci/internal/ci/wolfi_operations.go
  enterprise/dev/ci/internal/ci/wolfi_operations_test.go
  enterprise/dev/ci/scripts/wolfi/build-base-image.sh
  enterprise/dev/ci/scripts/wolfi/build-repo-index.sh
  enterprise/dev/ci/scripts/wolfi/upload-package.sh
  wolfi-images/redis.yaml
  wolfi-packages/ctags.yaml
  wolfi-packages/jaeger.yaml
Labels: cla-signed

#55719 sveltekit: Remove faker from production build
  client/web-sveltekit/src/lib/dom.ts
Labels: cla-signed, code-search

#55662 upgrade `cody-shared` package version
  client/web/package.json
  client/web/src/cody/components/CodeMirrorEditor.ts
  client/web/src/cody/components/FileContentEditor.ts
  client/web/src/cody/components/RepoContainerEditor.ts
  pnpm-lock.yaml
Labels: cla-signed

#55723 sveltekit: Remove React pages
  client/web-sveltekit/src/lib/context.ts
  client/web-sveltekit/src/lib/http-client.ts
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/lib/web.ts
  client/web-sveltekit/src/routes/(enterprise)/insights/[...path]/+page.svelte
  client/web-sveltekit/src/routes/(enterprise)/notebooks/[...path]/+page.svelte
  client/web-sveltekit/src/routes/(enterprise)/notebooks/[...path]/+page.ts
  client/web-sveltekit/src/routes/Header.svelte
  client/web-sveltekit/src/routes/HeaderNavLink.svelte
  client/web-sveltekit/vite.config.ts
Labels: cla-signed, code-search

#55671 gitserver: Start cleaning up server struct
  cmd/gitserver/server/BUILD.bazel
  cmd/gitserver/server/cleanup.go
  cmd/gitserver/server/cleanup_test.go
  cmd/gitserver/server/clone.go
  cmd/gitserver/server/patch.go
  cmd/gitserver/server/repo_info.go
  cmd/gitserver/server/server.go
  cmd/gitserver/server/server_grpc.go
  cmd/gitserver/server/server_test.go
  cmd/gitserver/server/servermetrics.go
  cmd/gitserver/server/serverutil.go
  cmd/gitserver/shared/BUILD.bazel
  cmd/gitserver/shared/config.go
  cmd/gitserver/shared/debug.go
  cmd/gitserver/shared/service.go
  cmd/gitserver/shared/shared.go
  cmd/gitserver/shared/shared_test.go
  enterprise/cmd/gitserver/shared/service.go
  internal/gitserver/client.go
Labels: cla-signed

#55732 docs: elaborate on the purpose of test plans
  .github/PULL_REQUEST_TEMPLATE.md
  doc/dev/background-information/testing_principles.md
Labels: cla-signed, okr/soc2, team/dev-infra

#55087 Fix for Arbitrary File Read in gitserver using diff command
  cmd/gitserver/server/patch.go
  cmd/gitserver/server/server.go
  internal/gitserver/gitdomain/exec.go
  internal/gitserver/gitdomain/exec_test.go
Labels: cla-signed

#55744 gitserver: Remove unnecessary call to cmd.CombinedOutput
  cmd/gitserver/server/run.go
Labels: cla-signed

#55648 gRPC: migrate conf endpoint
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/internal.go
  internal/api/internalapi/BUILD.bazel
  internal/api/internalapi/client.go
  internal/api/internalapi/v1/BUILD.bazel
  internal/api/internalapi/v1/buf.gen.yaml
  internal/api/internalapi/v1/internalapi.pb.go
  internal/api/internalapi/v1/internalapi.proto
  internal/api/internalapi/v1/internalapi_grpc.pb.go
  internal/conf/conftypes/BUILD.bazel
  internal/conf/conftypes/conftypes.go
  internal/conf/conftypes/conftypes_test.go
  sg.config.yaml
Labels: cla-signed

#55752 Add negative test for `git commit -F`
  internal/gitserver/gitdomain/exec_test.go
Labels: cla-signed

#55759 Search: fix tracing so "first results" is an event
  internal/search/job/observe.go
Labels: cla-signed

#55771 releasetool: update `updatecheck/handler` path in comby commands
  dev/release/src/release.ts
Labels: cla-signed

#55777 chore: Bump autoindexing image SHAs
  internal/codeintel/autoindexing/internal/inference/libs/indexes.go
Labels: cla-signed

#55735 JetBrains: Add java install instructions
  client/jetbrains/CONTRIBUTING.md
Labels: cla-signed

#55770 JetBrains: Add more comprehensive autocomplete telemetry
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutoCompleteAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutoCompleteTextAtCaret.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteTelemetry.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompletionStatus.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/AutoCompleteProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/CodyAutoCompleteItemProvider.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SimpleRecipeAction.java
  client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
Labels: cla-signed

#55781 Add support for Claude Instant 1.2
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  cmd/cody-gateway/shared/config.go
Labels: cla-signed, team/code-exploration

#55638 JetBrains: add autocomplete support via Agent
  client/jetbrains/build.gradle.kts
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/ConnectionConfiguration.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/AutocompleteContext.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/AutocompleteExecuteParams.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutoCompleteAction.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutoCompleteProviderType.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutoCompleteText.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/InlayModelUtils.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/CodyAutoCompleteBlockElementRenderer.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/CodyAutoCompleteElementRenderer.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/CodyAutoCompleteSingleLineRenderer.java
  client/jetbrains/src/main/java/com/sourcegraph/common/EditorUtils.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
  client/jetbrains/src/test/java/AutocompleteDiffTest.java
Labels: cla-signed

#55788 migrations: Validate concurrent index creations are isolated
  internal/database/migration/definition/read.go
  internal/database/migration/definition/read_test.go
  internal/database/migration/definition/testdata/BUILD.bazel
  internal/database/migration/definition/testdata/concurrent-extra/10001/down.sql
  internal/database/migration/definition/testdata/concurrent-extra/10001/metadata.yaml
  internal/database/migration/definition/testdata/concurrent-extra/10001/up.sql
  internal/database/migration/definition/testdata/concurrent-extra/10002/down.sql
  internal/database/migration/definition/testdata/concurrent-extra/10002/metadata.yaml
  internal/database/migration/definition/testdata/concurrent-extra/10002/up.sql
Labels: cla-signed

#55774 metrics/RequestMeter: add label for X-From-Cache
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
Labels: cla-signed, backport 5.1

#55704 source: fix redundant @ in Okta accounts
  client/web/BUILD.bazel
  client/web/src/user/settings/auth/ExternalAccount.test.tsx
  client/web/src/user/settings/auth/ExternalAccount.tsx
  client/web/src/user/settings/auth/__snapshots__/ExternalAccount.test.tsx.snap
Labels: cla-signed, backport 5.1

#55760 docsite link fix for Native K8s executors
  doc/admin/executors/deploy_executors_kubernetes.md
Labels: docs, cla-signed, executors

#55792 Build bundled-executor with shell build tag again
  cmd/bundled-executor/BUILD.bazel
  cmd/executor/BUILD.bazel
  cmd/executor/internal/util/BUILD.bazel
Labels: cla-signed

#55798 release: fix improper formatting when generating migrator bazel build
  dev/release/src/util.ts
Labels: cla-signed

#55808 Build bundled-executor with shell build tag again
  enterprise/cmd/bundled-executor/BUILD.bazel
  enterprise/cmd/executor/BUILD.bazel
  enterprise/cmd/executor/internal/util/BUILD.bazel
Labels: cla-signed

#55797 Fix docker build scripts for bundled-executor
  enterprise/cmd/bundled-executor/build-wolfi.sh
  enterprise/cmd/bundled-executor/build.sh
Labels: cla-signed

#55694 Make repo updater jobs observable
  cmd/repo-updater/shared/BUILD.bazel
  cmd/repo-updater/shared/debug.go
  cmd/repo-updater/shared/main.go
  internal/repos/BUILD.bazel
  internal/repos/phabricator.go
  internal/repos/purge.go
  internal/repos/sync_errored.go
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: cla-signed

#55812 chore: update zoekt to 956d775e32b369708c457dc612fd5b69ba85523e
  go.mod
  go.sum
Labels: cla-signed, backport 5.1

#55802 Improve performance of gitserver_repos store methods
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/gitserver/server/server_test.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/mocks_temp.go
  internal/types/types.go
Labels: cla-signed

#55803 gitserver: Register background routines with recorder
  cmd/gitserver/shared/BUILD.bazel
  cmd/gitserver/shared/shared.go
Labels: cla-signed

#55789 JetBrains: delete unused method
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
Labels: cla-signed

#55824 [dbmocks] Minor docs update
  doc/dev/background-information/languages/testing_go_code.md
Labels: cla-signed, team/iam

#55826 JetBrains: fix miscellaneous issues
  client/jetbrains/build.gradle.kts
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
  client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
  client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
Labels: cla-signed

#55799 codeintel: limit package filter list modal height
  client/web/src/site-admin/packages/PackagesModal.module.scss
  client/web/src/site-admin/packages/modal-content/ManagePackageFiltersModalContent.module.scss
Labels: cla-signed, package-repos, backport 5.1

#55830 Update buildkite aspect cli to latest version (which include BKA integration)
  .aspect/cli/config.yaml
Labels: cla-signed

#55563 Fix Site Admin Repositories page from over-querying and hitting rate limits
  client/web/src/site-admin/RepositoryNode.tsx
  client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
Labels: cla-signed

#55822 cleanup: Inline/Simplify function used only in one place
  internal/codeintel/autoindexing/internal/inference/libs/recognizers.go
  internal/codeintel/autoindexing/internal/inference/luatypes/recognizers.go
Labels: cla-signed

#55548 cody chat: add getting started widget
  client/web/BUILD.bazel
  client/web/package.json
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/chat/CodyPageIcon.tsx
  client/web/src/cody/components/ChatUI/ChatUi.tsx
  client/web/src/cody/components/GettingStarted.module.scss
  client/web/src/cody/components/GettingStarted.tsx
  client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
  client/web/src/cody/components/ScopeSelector/ScopeSelector.module.scss
  client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
  pnpm-lock.yaml
Labels: cla-signed

#55839 sg: fix devx-support#154
  dev/sg/sg_ci.go
Labels: sg, cla-signed

#55779 database: sample 4x less events for honeycomb database-batch
  internal/database/batch/observability.go
Labels: cla-signed

#55678 Log the batch size of embeddings requests in Cody Gateway
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
Labels: cla-signed

#55843 ci: bump aspect-cli plugin for BK
  .aspect/cli/config.yaml
Labels: cla-signed

#55821 JetBrains: add settings for debugging agent
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentClient.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/ConnectionConfiguration.java
  client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/DebugMessage.java
  client/jetbrains/src/main/java/com/sourcegraph/config/CodyApplicationService.java
  client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
  client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
  client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
Labels: cla-signed

#55844 chore: fix extra space that confused Markdown render
  doc/cody/explanations/index.md
Labels: cla-signed
