Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2023-12, with the labels that each got.

#58696 sg/msp: better templates on init
  dev/sg/msp/example/BUILD.bazel
  dev/sg/msp/example/example-service.service.yaml
  dev/sg/msp/example/example.go
  dev/sg/msp/example/example_test.go
  dev/sg/msp/example/job.template.yaml
  dev/sg/msp/example/service.template.yaml
  dev/sg/msp/repo/repo.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#58699 [Backport] Auto-update Wolfi base images to latest (#58641)
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, backport/stability, backported-to-5.2

#58705 bzl: bump src-cli to 5.2.1
  dev/tool_deps.bzl
Labels: cla-signed

#58704 bazel+rbac: mention correct target in generated files
  client/web/src/rbac/constants.ts
  internal/rbac/constants.go
  internal/rbac/gen/yamldata.go
  internal/rbac/types/action.go
  internal/rbac/types/namespace.go
Labels: cla-signed

#58702 nix: update flake for clang 16 and assert typescript 5.3.2
  dev/nix/nodejs.nix
  flake.lock
Labels: cla-signed

#58706 buildtracker: fix readme
  dev/build-tracker/README.md
Labels: cla-signed

#58707 bzl: fix repo name for executor-vm
  docker-images/executor-vm/BUILD.bazel
Labels: cla-signed

#58703 Recreate repo statistics every Sunday morning
  cmd/worker/internal/repostatistics/BUILD.bazel
  cmd/worker/internal/repostatistics/compactor.go
  cmd/worker/internal/repostatistics/resetter.go
  cmd/worker/shared/main.go
  doc/admin/workers.md
  internal/database/dbmocks/mocks_temp.go
  internal/database/repo_statistics.go
  internal/database/repo_statistics_test.go
Labels: cla-signed, team/source

#58710 repo statistics: coalesce when compacting table
  internal/database/repo_statistics.go
  internal/database/repo_statistics_test.go
Labels: cla-signed, team/source

#58697 dev/sg: use urfave/cli native suggestions
  dev/sg/BUILD.bazel
  dev/sg/main.go
  dev/sg/suggest.go
  dev/sg/suggest_test.go
  go.mod
Labels: cla-signed

#58669 Redesign and add are you sure to Cody pricing
  client/web/BUILD.bazel
  client/web/src/cody/subscription/CancelProModal.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.module.scss
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
Labels: cla-signed

#58714 docker-images/dind: upgrade to 24.0.7
  docker-images/dind/Dockerfile
Labels: cla-signed

#58679 Auto enroll user to Cody Pro
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.module.scss
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/cody/sidebar/CodySidebar.tsx
  client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
  client/web/src/storm/pages/SearchPage/TryCodySignUpCtaSection.module.scss
  client/web/src/storm/pages/SearchPage/TryCodySignUpCtaSection.tsx
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: cla-signed

#58664 SSC: Add x-is-cody-pro-user header
  internal/completions/httpapi/chat.go
  internal/completions/httpapi/codecompletion.go
  internal/completions/httpapi/handler.go
Labels: cla-signed

#58591 SSC: Add "rate limits exceeded" feature flag to aid client testing
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/httpapi/limiter.go
Labels: cla-signed

#58715 bumping go grpc to 1.57.1
  deps.bzl
  go.mod
  go.sum
  lib/go.mod
Labels: cla-signed

#58735 sg generate: report duration for bazel step
  dev/sg/generates.go
Labels: cla-signed, team/source

#58713 bazel: use script_path with run docsite
  sg.config.yaml
Labels: cla-signed

#58691 Dev tool: python script for text clustering based on local embeddings
  .tool-versions
  dev/clustering/README.md
  dev/clustering/cluster.py
  dev/clustering/requirements.txt
Labels: cla-signed

#58728 wofli: do not update digest if there is a failure fetching the digest
  dev/sg/internal/wolfi/update_hashes.go
  dev/sg/sg_wolfi.go
Labels: cla-signed

#58733 search jobs: allow explicit type:file
  internal/search/exhaustive/service/searcher.go
  internal/search/exhaustive/service/searcher_test.go
Labels: cla-signed

#58732 Allow refreshing usage limits for dotcom users
  cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  cmd/cody-gateway/internal/actor/source.go
  cmd/cody-gateway/internal/actor/source_test.go
  cmd/cody-gateway/internal/httpapi/featurelimiter/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#58741 sg+docsite: remove outdated comment
  sg.config.yaml
Labels: cla-signed

#58743 statistics resetter: try again on Tuesday
  cmd/worker/internal/repostatistics/resetter.go
Labels: cla-signed, team/source

#58747 bazel: remove unused rules_rust patch
  dev/nix/001-rules-rust-cargo-bazel-env.patch
Labels: cla-signed, bazel

#58745 release: sourcegraph@5.2.4
  doc/admin/deploy/docker-compose/aws.md
  doc/admin/deploy/docker-compose/azure.md
  doc/admin/deploy/docker-compose/digitalocean.md
  doc/admin/deploy/docker-compose/google_cloud.md
  doc/admin/deploy/docker-compose/index.md
  doc/admin/deploy/docker-single-container/aws.md
  doc/admin/deploy/docker-single-container/digitalocean.md
  doc/admin/deploy/docker-single-container/google_cloud.md
  doc/admin/deploy/docker-single-container/index.md
  doc/admin/deploy/kubernetes/helm.md
  doc/admin/deploy/machine-images/gce.md
  doc/admin/executors/deploy_executors_kubernetes.md
  doc/admin/external_services/postgres.md
  doc/admin/external_services/redis.md
  doc/admin/http_https_configuration.md
  doc/admin/ssl_https_self_signed_cert_nginx.md
  doc/admin/updates/docker_compose.md
  doc/admin/updates/pure_docker.md
  doc/admin/updates/server.md
  internal/updatecheck/handler.go
Labels: cla-signed

#58749 release: remove manual migration bazel output generation func
  dev/release/src/release.ts
  dev/release/src/util.ts
Labels: cla-signed

#58750 5.2.4 changelog update
  CHANGELOG.md
Labels: cla-signed

#58748 Remove unused OAuth stateconfig
  cmd/frontend/internal/auth/azureoauth/BUILD.bazel
  cmd/frontend/internal/auth/azureoauth/provider.go
  cmd/frontend/internal/auth/azureoauth/provider_test.go
  cmd/frontend/internal/auth/azureoauth/session.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/BUILD.bazel
  cmd/frontend/internal/auth/bitbucketcloudoauth/config.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/config_test.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/middleware_test.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/provider.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/session.go
  cmd/frontend/internal/auth/githuboauth/BUILD.bazel
  cmd/frontend/internal/auth/githuboauth/config.go
  cmd/frontend/internal/auth/githuboauth/config_test.go
  cmd/frontend/internal/auth/githuboauth/middleware_test.go
  cmd/frontend/internal/auth/githuboauth/provider.go
  cmd/frontend/internal/auth/githuboauth/session.go
  cmd/frontend/internal/auth/gitlaboauth/BUILD.bazel
  cmd/frontend/internal/auth/gitlaboauth/config_test.go
  cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
  cmd/frontend/internal/auth/gitlaboauth/provider.go
  cmd/frontend/internal/auth/gitlaboauth/session.go
  cmd/frontend/internal/auth/oauth/provider.go
  cmd/frontend/internal/auth/oauth/session.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware_test.go
  cmd/frontend/internal/auth/sourcegraphoperator/middleware.go
  cmd/frontend/internal/auth/sourcegraphoperator/middleware_test.go
  doc/admin/auth/troubleshooting.md
Labels: cla-signed, SSDLC

#58759 Use clear map function from go 1.21
  internal/authz/providers/perforce/protects.go
Labels: cla-signed

#58365 [Cody GA Docs] Improvements to Cody Troubleshooting docs
  doc/cody/troubleshooting.md
Labels: docs, docs-ux, cla-signed, docs-issue

#58760 auth: allow exempted list from the minimumExternalAccountAge
  cmd/frontend/internal/auth/githuboauth/session.go
  cmd/frontend/internal/auth/gitlaboauth/session.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#58541 dev/msp: add BigQuery support
  cmd/msp-example/internal/example/BUILD.bazel
  cmd/msp-example/internal/example/example.go
  dev/managedservicesplatform/internal/resource/bigquery/BUILD.bazel
  dev/managedservicesplatform/internal/resource/bigquery/bigquery.go
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/spec/service.go
  dev/managedservicesplatform/spec/spec.go
  dev/sg/msp/sg_msp.go
  lib/managedservicesplatform/bigquerywriter/BUILD.bazel
  lib/managedservicesplatform/bigquerywriter/bigquerywriter.go
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/go.sum
  lib/managedservicesplatform/runtime/BUILD.bazel
  lib/managedservicesplatform/runtime/contract.go
  lib/managedservicesplatform/runtime/contract_bigquery.go
  lib/managedservicesplatform/runtime/contract_postgresql.go
  lib/managedservicesplatform/runtime/service.go
Labels: cla-signed

#58708 docs: support for private registries on AWS/GCP/public LB
  doc/cloud/index.md
  doc/cloud/private_connectivity_aws.md
  doc/cloud/private_connectivity_gcp.md
  doc/cloud/private_connectivity_public_lb.md
  doc/cloud/private_connectivity_sourcegraph_connect.md
Labels: cla-signed

#58752 Bump wolfi images to make use of latest p4-fusion
  dev/oci_deps.bzl
Labels: cla-signed, team/source

#58674 Remove deprecated license features and tags
  cmd/frontend/auth/BUILD.bazel
  cmd/frontend/auth/non_public.go
  cmd/frontend/auth/non_public_test.go
  cmd/frontend/external/app/app.go
  cmd/frontend/internal/app/BUILD.bazel
  cmd/frontend/internal/app/debug.go
  cmd/frontend/internal/app/debug_test.go
  cmd/frontend/internal/auth/BUILD.bazel
  cmd/frontend/internal/auth/confauth/BUILD.bazel
  cmd/frontend/internal/auth/confauth/middleware.go
  cmd/frontend/internal/auth/confauth/middleware_test.go
  cmd/frontend/internal/auth/init.go
  cmd/frontend/internal/batches/resolvers/resolver_test.go
  cmd/frontend/internal/licensing/enforcement/BUILD.bazel
  cmd/frontend/internal/licensing/enforcement/monitoring.go
  cmd/frontend/internal/licensing/init/init.go
  cmd/frontend/internal/licensing/resolvers/resolvers_test.go
  internal/licensing/data.go
  internal/licensing/features.go
  internal/licensing/features_test.go
  internal/licensing/tags.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/source

#58770 deactivate release
  dev/release/release-config.jsonc
Labels: cla-signed

#58767 statistics resetter: run on Sunday, between 2 and 2:30am
  cmd/worker/internal/repostatistics/resetter.go
Labels: cla-signed, team/source

#58766 Improve cursor based pagination implementation
  cmd/frontend/graphqlbackend/access_requests.go
  cmd/frontend/graphqlbackend/access_requests_test.go
  cmd/frontend/graphqlbackend/graphqlutil/BUILD.bazel
  cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
  cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_test.go
  cmd/frontend/graphqlbackend/permission_connection_store.go
  cmd/frontend/graphqlbackend/permissions.go
  cmd/frontend/graphqlbackend/repositories.go
  cmd/frontend/graphqlbackend/repository_contributors.go
  cmd/frontend/graphqlbackend/repository_contributors_test.go
  cmd/frontend/graphqlbackend/repository_metadata.go
  cmd/frontend/graphqlbackend/role.go
  cmd/frontend/graphqlbackend/role_connection_store.go
  cmd/frontend/graphqlbackend/saved_searches.go
  cmd/frontend/graphqlbackend/saved_searches_test.go
  cmd/frontend/graphqlbackend/site_config_change_connection.go
  cmd/frontend/graphqlbackend/site_config_change_connection_test.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/internal/authz/resolvers/permissions_info.go
  cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
  cmd/frontend/internal/bg/update_permissions.go
  cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs.go
  cmd/frontend/internal/insights/resolvers/admin_resolver.go
  cmd/frontend/internal/search/resolvers/resolver.go
  internal/database/access_requests_test.go
  internal/database/conf_test.go
  internal/database/helpers.go
  internal/database/permission_sync_jobs_test.go
  internal/database/perms_store_test.go
  internal/insights/scheduler/backfill.go
Labels: cla-signed, team/source

#58771 add localDevDenyList for denylists
  internal/httpcli/client.go
Labels: cla-signed

#58774 Revert "Bump wolfi images to make use of latest p4-fusion (#58752)"
  dev/oci_deps.bzl
Labels: cla-signed, team/source

#58769 bzl+doc: Add a FAQ entry about git log and mailmap
  doc/dev/background-information/bazel/faq.md
Labels: cla-signed

#58775 bump go version in buildchecker
  .github/workflows/buildchecker-history.yml
  .github/workflows/buildchecker.yml
Labels: team/devx, cla-signed

#58758 Fix post-email verification return URL to /search
  cmd/frontend/internal/app/verify_email.go
Labels: cla-signed

#58772 [fix] Updating an code host config maintains the correct unrestricted state
  CHANGELOG.md
  internal/database/external_services.go
  internal/database/external_services_test.go
Labels: cla-signed, team/source, backport 5.2

#58777 sg wolfi: fix update-hashes to ignore legacy images
  dev/oci_deps.bzl
  dev/sg/internal/wolfi/update_hashes.go
Labels: cla-signed

#58549 search jobs: unify query validation
  client/branded/BUILD.bazel
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
  client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.test.ts
  client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.ts
  cmd/frontend/graphqlbackend/search_jobs.go
  cmd/frontend/graphqlbackend/search_jobs.graphql
  cmd/frontend/internal/search/resolvers/resolver.go
  internal/search/exhaustive/service/service.go
  internal/search/job/jobutil/exhaustive_job.go
  internal/search/job/jobutil/exhaustive_job_test.go
  internal/types/types.go
  internal/usagestats/BUILD.bazel
  internal/usagestats/search_jobs.go
  internal/usagestats/search_jobs_test.go
Labels: cla-signed

#58553 dotcom: don't lazy add repos with `size >= 1GB && stars < 100`
  client/shared/src/backend/errors.ts
  client/web/src/repo/RepoContainerError.tsx
  client/web/src/repo/backend.ts
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/internal/app/ui/handlers.go
  cmd/repo-updater/internal/repoupdater/server.go
  internal/errcode/code.go
  internal/repos/syncer.go
  internal/repoupdater/client.go
  internal/repoupdater/errors.go
  internal/repoupdater/protocol/repoupdater.go
  internal/repoupdater/v1/repoupdater.pb.go
  internal/repoupdater/v1/repoupdater.proto
Labels: cla-signed, team/source

#58781 Bump base images again
  dev/oci_deps.bzl
Labels: cla-signed, team/source

#58778 buildtracker: ignore inprogress jobs when determining final status
  dev/build-tracker/main.go
  dev/build-tracker/main_test.go
  dev/build-tracker/notify/slack.go
Labels: cla-signed

#58785 completions: include model in 'unsupported model' error
  internal/completions/httpapi/codecompletion.go
Labels: cla-signed

#58744 bazel: update rules_ts, rules_js and bazel-lib
  WORKSPACE
Labels: cla-signed

#58768 bazel: write docsite script to .bin
  sg.config.yaml
Labels: cla-signed

#58797 errored repos syncer: do not try to sync blocked repos
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: cla-signed, team/source

#58791 SSC: Fix Gateway bug and add tests
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
Labels: cla-signed

#58737 Add Cody PLG Telemetry
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/cody/subscription/CancelProModal.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/cody/subscription/UpgradeToProModal.tsx
  client/web/src/util/constants.ts
Labels: cla-signed

#58792 SSC: Hook up exempted users with cody-pro FF
  cmd/frontend/auth/user.go
  cmd/frontend/internal/auth/oauth/session.go
Labels: cla-signed

#58802 wolfi: add redis cli to server image
  wolfi-images/redis.yaml
  wolfi-images/server.yaml
Labels: cla-signed, backport 5.2

#58779 Code Navigation: change Java icon and add vue icon
  client/web/src/repo/RepoRevisionSidebarFileTree.module.scss
  client/web/src/repo/constants.ts
Labels: cla-signed

#58805 update schema descriptions 5.2
  cmd/migrator/BUILD.bazel
  cmd/migrator/generate.sh
  dev/gqltest/external_service_test.go
  dev/gqltest/sub_repo_permissions_test.go
Labels: cla-signed

#58800 SSC: Fix Cody Web
  internal/accesstoken/personal_access_token.go
  internal/completions/httpapi/BUILD.bazel
  internal/completions/httpapi/chat.go
  internal/completions/httpapi/codecompletion.go
  internal/completions/httpapi/handler.go
  internal/database/access_tokens.go
  internal/database/access_tokens_test.go
  internal/database/dbmocks/mocks_temp.go
Labels: cla-signed

#58787 Embeddings: refactor job scheduling code
  cmd/frontend/internal/app/resolvers/app.go
  cmd/frontend/internal/embeddings/resolvers/resolvers.go
  cmd/worker/internal/embeddings/repo/scheduler.go
  internal/embeddings/background/repo/types.go
  internal/embeddings/schedule.go
  internal/embeddings/schedule_test.go
Labels: cla-signed

#58812 docs: fix up caa records requirement
  doc/cloud/index.md
Labels: cla-signed

#58813 oidc: store access token into auth_data
  cmd/frontend/internal/auth/openidconnect/BUILD.bazel
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/user.go
  cmd/frontend/internal/auth/openidconnect/user_test.go
Labels: cla-signed

#58822 Rg/fix response flushing
  cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
  cmd/cody-gateway/internal/httpapi/requestlogger/requestlogger.go
  cmd/cody-gateway/internal/response/response.go
  cmd/cody-gateway/internal/response/response_test.go
Labels: cla-signed

#58823 Rewrite ST models to MT equivalents
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#58795 [Backport 5.2] Updating an code host config maintains the correct unrestricted…
  internal/database/external_services.go
  internal/database/external_services_test.go
Labels: cla-signed, backports, team/iam

#58825 nix: empty out before writing to it .bazelrc-nix
  dev/nix/shell-hook.sh
Labels: cla-signed

#58809 Use document element for class theme in code hosts integrations
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
Labels: cla-signed

#58793 Admin: avoid false impression that Zoekt is indexing
  client/web/src/repo/settings/RepoSettingsIndexPage.tsx
Labels: cla-signed

#58567 requestclient: add SRC_USE_CLOUDFLARE_HEADERS to use CF headers
  cmd/cody-gateway/shared/main.go
  cmd/frontend/internal/cli/http.go
  internal/requestclient/BUILD.bazel
  internal/requestclient/http.go
Labels: cla-signed

#58837 telemetry-gateway: add attributes to pubsub events
  cmd/telemetry-gateway/internal/events/BUILD.bazel
  cmd/telemetry-gateway/internal/events/events.go
  cmd/telemetry-gateway/internal/events/events_test.go
  internal/pubsub/pubsubtest/pubsubtest.go
  internal/pubsub/topic.go
Labels: cla-signed

#58841 Revert - disable chromatic
  dev/ci/internal/ci/operations.go
Labels: cla-signed

#58842 purge worker: fix bug in gRPC handler and bump log level
  cmd/gitserver/internal/server_grpc.go
  cmd/repo-updater/shared/main.go
  internal/repos/purge.go
Labels: cla-signed, team/source

#58846 Disable chromatic again
  dev/ci/internal/ci/operations.go
Labels: cla-signed

#58845 Don't run janitor after removing wrong shard repo
  cmd/gitserver/internal/cleanup.go
Labels: cla-signed, team/source

#58844 gitserver repos: do not log corruption from wrong shard
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/database/repos_test.go
Labels: cla-signed, team/source

#58850 database: simplify test helper
  internal/database/gitserver_repos_test.go
  internal/database/zoekt_repos_test.go
Labels: cla-signed, team/source

#58834 build-tracker: only account for terminal job states
  dev/build-tracker/build/build.go
  dev/build-tracker/build/build_test.go
  dev/build-tracker/build/steps.go
  dev/build-tracker/integration_test.go
  dev/build-tracker/main.go
  dev/build-tracker/main_test.go
  dev/build-tracker/notify/slack.go
  dev/build-tracker/server_test.go
Labels: cla-signed

#58829 sg: add config to run backend-integration tests locally
  sg.config.yaml
  testing/tools/integration_runner.sh
Labels: cla-signed

#58856 internal/database: remove test that takes 10s and is not worth it
  internal/database/BUILD.bazel
  internal/database/perms_store_test.go
Labels: cla-signed, team/source

#58854 SSC: Handle returnTo params on /cody/manage
  client/web/src/cody/onboarding/CodyOnboarding.tsx
Labels: cla-signed

#58833 SSC: Refresh limits on plan change
  cmd/cody-gateway/internal/actor/dotcomuser/BUILD.bazel
  cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
  cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
  internal/accesstoken/cody_access_token.go
  internal/completions/httpapi/handler.go
Labels: cla-signed

#58839 Ranking: hide site admin panel by default
  client/web/dev/utils/create-js-context.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/site-admin/sidebaritems.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
Labels: cla-signed

#58814 telemetry-gateway: migrate to MSP runtime
  cmd/telemetry-gateway/BUILD.bazel
  cmd/telemetry-gateway/main.go
  cmd/telemetry-gateway/service/BUILD.bazel
  cmd/telemetry-gateway/service/config.go
  cmd/telemetry-gateway/service/service.go
  cmd/telemetry-gateway/shared/BUILD.bazel
  cmd/telemetry-gateway/shared/config.go
  cmd/telemetry-gateway/shared/main.go
  cmd/telemetry-gateway/shared/metrics.go
  cmd/telemetry-gateway/shared/service.go
  cmd/telemetry-gateway/shared/tracing.go
  dev/prometheus/all/prometheus_targets.yml
  internal/telemetrygateway/v1/BUILD.bazel
  lib/background/background.go
  lib/managedservicesplatform/runtime/service.go
  sg.config.yaml
Labels: cla-signed

#58782 svelte: Add Svelte prototype toggle button to global navbar
  client/web-sveltekit/src/lib/icons/BatchChanges.svelte
  client/web-sveltekit/src/lib/icons/CodeMonitoring.svelte
  client/web-sveltekit/src/lib/icons/Cody.svelte
  client/web-sveltekit/src/lib/images.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/Header.svelte
  client/web-sveltekit/src/routes/HeaderNavLink.svelte
  client/web-sveltekit/src/routes/InfoBanner.svelte
  client/web-sveltekit/src/routes/styles.scss
  client/web-sveltekit/static/react-logo.svg
  client/web/BUILD.bazel
  client/web/dist/img/svelte-logo-disabled.svg
  client/web/dist/img/svelte-logo.svg
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/sveltekit/SvelteKitNavItem.tsx
  client/web/src/sveltekit/util.ts
Labels: cla-signed

#58851 embeddings: Return a 429 code when getting 429 from upstream
  cmd/embeddings/shared/BUILD.bazel
  cmd/embeddings/shared/main.go
Labels: cla-signed

#58875 Measure time to first event for streaming completions
  internal/completions/httpapi/BUILD.bazel
  internal/completions/httpapi/handler.go
Labels: cla-signed

#58794 client: Rename api -> apiAdapter for clarity
  client/web/src/repo/blob/codemirror/codeintel/api.ts
  client/web/src/repo/blob/codemirror/codeintel/extension.ts
Labels: cla-signed

#58866 [Backport 5.2] Admin: improve search indexing page
  client/web/src/repo/settings/RepoSettingsIndexPage.tsx
  client/web/src/site-admin/RepositoryNode.tsx
Labels: cla-signed, backport/improvement

#58879 Surfaces errors in autoindex configuration
  internal/codeintel/autoindexing/transport/graphql/root_resolver_configuration_repository.go
Labels: cla-signed

#58859 cody-gateway: For streaming requests, flush response after every write
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/internal/response/BUILD.bazel
  cmd/cody-gateway/internal/response/response.go
  cmd/cody-gateway/internal/response/response_test.go
  cmd/cody-gateway/shared/config.go
  cmd/cody-gateway/shared/main.go
  internal/completions/client/fireworks/fireworks.go
Labels: cla-signed

#58888 ci: fix legacy image build emoji
  dev/ci/internal/ci/bazel_operations.go
Labels: cla-signed

#58862 Cody: Azure OpenAI allow authentication requests to use a proxy
  doc/cody/core-concepts/embeddings/index.md
  doc/cody/overview/enable-cody-enterprise.md
  internal/completions/client/azureopenai/openai.go
  internal/embeddings/embed/client/azureopenai/BUILD.bazel
  internal/embeddings/embed/client/azureopenai/client.go
Labels: cla-signed, backport 5.2, backport/improvement

#58889 Additional scope information for each ADO scope section
  doc/admin/external_service/azuredevops.md
Labels: cla-signed

#58852 Use document element for class theme in code hosts integrations (#58809)
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
Labels: cla-signed

#58893 bazel: provide p4-fusion via bazel
  cmd/gitserver/README.md
  dev/p4-fusion-dev
  dev/tool_deps.bzl
  dev/tools/BUILD.bazel
Labels: cla-signed, bazel, team/dev-infra

#58869 Embeddings: fail job immediately if rate limited exceeded
  cmd/worker/internal/embeddings/repo/scheduler.go
  doc/cody/core-concepts/embeddings/configure-embeddings.md
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
Labels: cla-signed

#58870 SSC: Add redirect from /post-sign-up to /cody/manage for users with the cody-pro feature flag
  client/web/src/LegacyLayout.tsx
  client/web/src/auth/PostSignUpPage.tsx
  client/web/src/user/settings/accessTokens/UserSettingsTokensArea.tsx
Labels: cla-signed

#58288 [Cody GA Docs] Guides on Cody Capabilities — Chat, Autocomplete, Bug Fixes, Commands
  .vscode/cody.json
  doc/_resources/assets/redirects
  doc/cody/capabilities.md
  doc/cody/capabilities/autocomplete.md
  doc/cody/capabilities/chat.md
  doc/cody/capabilities/commands.md
  doc/cody/capabilities/debug-code.md
  doc/cody/capabilities/index.md
  doc/cody/custom-commands.md
  doc/cody/feature-reference.md
  doc/cody/overview/install-vscode.md
  doc/sidebar.md
Labels: docs, cla-signed

#58358 [Cody GA Docs] Improvements to Cody Quickstart tutorial
  doc/cody/quickstart.md
Labels: docs, cla-signed, docs-issue

#58849 search: hack in new search language
  client/shared/BUILD.bazel
  client/shared/src/search/searchSimple.test.ts
  client/shared/src/search/searchSimple.ts
  client/shared/src/search/stream.ts
  client/web/src/featureFlags/featureFlags.ts
Labels: cla-signed

#58761 [Cody GA Docs] Improvements to VS Code Cody Client docs
  doc/cody/overview/index.md
  doc/cody/overview/install-vscode.md
Labels: docs, docs-ux, cla-signed

#58897 Cody UI Updates
  client/web/src/cody/management/CodyManagementPage.module.scss
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/cody/onboarding/instructions/JetBrains.tsx
  client/web/src/cody/onboarding/instructions/VsCode.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.module.scss
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/cody/subscription/UpgradeToProModal.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: cla-signed

#58914 Enable Chromatic - Revert "Disable chromatic again (#58846)"
  dev/ci/internal/ci/operations.go
Labels: cla-signed

#58918 dev: issue tracker, bump Go version
  internal/cmd/tracking-issue/Dockerfile
Labels: cla-signed

#58901 Feature images, Copy, and links on Dashboard
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/onboarding/CodyOnboarding.module.scss
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/cody/onboarding/instructions/JetBrains.tsx
  client/web/src/cody/onboarding/instructions/NeoVim.tsx
  client/web/src/cody/onboarding/instructions/VsCode.tsx
Labels: cla-signed

#58919 Remove emacs documentation link text from cody management page
  client/web/src/cody/management/CodyManagementPage.tsx
Labels: cla-signed

#58920 database: speed up UpdateRepoSizes
  cmd/gitserver/internal/cleanup.go
  internal/database/dbmocks/BUILD.bazel
  internal/database/dbmocks/mocks_temp.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
Labels: cla-signed, team/source

#58923 Flush for code completions only
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#58925 dev: fix pr-auditor label owner
  dev/pr-auditor/main.go
Labels: cla-signed

#58933 pr-auditor: use token secret
  .github/workflows/pr-auditor.yml
Labels: cla-signed

#58902 Search: fix CSV export with special values
  client/web/src/search/results/export/searchResultsExport.test.ts
  client/web/src/search/results/export/searchResultsExport.ts
Labels: cla-signed, backport 5.2

#58470 [Cody GA Docs] Add Use Cases
  doc/cody/use-cases.md
  doc/cody/use-cases/generate-unit-tests.md
  doc/cody/use-cases/index.md
  doc/sidebar.md
Labels: docs, docs-ux, cla-signed

#58848 Add Cody providers to pings
  CHANGELOG.md
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  doc/admin/pings.md
  internal/types/BUILD.bazel
  internal/types/types.go
  internal/updatecheck/client.go
  internal/updatecheck/handler.go
  internal/updatecheck/handler_test.go
  internal/usagestats/BUILD.bazel
  internal/usagestats/cody_providers.go
Labels: cla-signed, backport 5.2

#58931 Gitlab Native integration: Fix code element target selector
  client/browser/src/shared/code-hosts/gitlab/domFunctions.ts
Labels: cla-signed

#58936 Code Navigation: cleanup file icons
  client/web/BUILD.bazel
  client/web/src/repo/RepoRevisionSidebarFileTree.tsx
  client/web/src/repo/constants.ts
  client/web/src/repo/fileIcons.ts
  client/web/src/repo/tree/TreePagePanels.tsx
  client/web/src/repo/utils.test.ts
  client/web/src/repo/utils.tsx
Labels: cla-signed

#58868 msp/runtime: provide query params to healthcheck
  cmd/msp-example/internal/example/diagnostics.go
  cmd/telemetry-gateway/service/service.go
  lib/managedservicesplatform/runtime/contract.go
Labels: cla-signed

#58899 chore: remove gotest.tools/assert
  cmd/frontend/internal/auth/saml/BUILD.bazel
  cmd/frontend/internal/auth/saml/user_test.go
  cmd/gitserver/internal/gitserverfs/BUILD.bazel
  cmd/gitserver/internal/gitserverfs/fs_test.go
  cmd/gitserver/internal/perforce/BUILD.bazel
  cmd/gitserver/internal/perforce/util_test.go
  cmd/telemetry-gateway/internal/events/BUILD.bazel
  cmd/telemetry-gateway/internal/events/events_test.go
  go.mod
  internal/auth/accessrequest/BUILD.bazel
  internal/auth/accessrequest/handlers_test.go
  internal/database/BUILD.bazel
  internal/database/ownership_stats_test.go
  internal/extsvc/azuredevops/BUILD.bazel
  internal/extsvc/azuredevops/client_test.go
  internal/scim/BUILD.bazel
  internal/scim/init_test.go
  lib/go.mod
  lib/go.sum
  lib/managedservicesplatform/go.sum
  lib/pointers/BUILD.bazel
  lib/pointers/ptr_test.go
  monitoring/go.sum
Labels: cla-signed

#58938 Copy changes and new video
  client/web/src/cody/management/CodyManagementPage.module.scss
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/onboarding/CodyOnboarding.module.scss
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/cody/subscription/UpgradeToProModal.tsx
Labels: cla-signed

#58945 Search: correct comments in query planning
  internal/search/query/transformer.go
Labels: cla-signed

#58907 msp/cloudrun: allow GSuite-based service authentication
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/builder.go
  dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/service/service.go
  dev/managedservicesplatform/spec/environment.go
Labels: cla-signed

#58944 graphqlbackend/telemetry: allow client-provided timestamp in events
  cmd/frontend/graphqlbackend/telemetry.go
  cmd/frontend/graphqlbackend/telemetry.graphql
  cmd/frontend/graphqlbackend/telemetry_test.go
  cmd/frontend/internal/telemetry/resolvers/BUILD.bazel
  cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
  cmd/frontend/internal/telemetry/resolvers/telemetrygateway_test.go
Labels: cla-signed, backport 5.2, backport/improvement

#58790 grpc: make example package for how to use grpc RPC types
  internal/grpc/example/BUILD.bazel
  internal/grpc/example/client/BUILD.bazel
  internal/grpc/example/client/main.go
  internal/grpc/example/client/run-client.sh
  internal/grpc/example/client/sun.svg
  internal/grpc/example/doc.go
  internal/grpc/example/server/BUILD.bazel
  internal/grpc/example/server/conversion.go
  internal/grpc/example/server/conversion_test.go
  internal/grpc/example/server/main.go
  internal/grpc/example/server/run-server.sh
  internal/grpc/example/server/service/BUILD.bazel
  internal/grpc/example/server/service/service.go
  internal/grpc/example/weather/v1/BUILD.bazel
  internal/grpc/example/weather/v1/buf.gen.yaml
  internal/grpc/example/weather/v1/weather.pb.go
  internal/grpc/example/weather/v1/weather.proto
  internal/grpc/example/weather/v1/weather_grpc.pb.go
Labels: cla-signed, team/source

#58867 gRPC: remove duplicate implementation
  internal/search/searcher/search.go
Labels: cla-signed

#58894 Docs: fix batch changes settings names
  doc/batch_changes/explanations/permissions_in_batch_changes.md
Labels: docs, cla-signed

#58909 msp/iam: provison secret access for external secrets
  dev/managedservicesplatform/internal/stack/iam/BUILD.bazel
  dev/managedservicesplatform/internal/stack/iam/iam.go
  dev/managedservicesplatform/internal/stack/iam/iam_test.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/spec/environment.go
Labels: cla-signed

#58942 actor: always preserve anonymousUID, even on authenticated actors
  internal/actor/actor.go
  internal/actor/grpc.go
  internal/actor/grpc_test.go
  internal/actor/http.go
  internal/actor/http_test.go
Labels: cla-signed, backport 5.2, backport/bugfix

#58853 Turns the `sh_binary` into a `sh_test`
  WORKSPACE
  testing/tools/upgradetest/BUILD.bazel
Labels: cla-signed

#58898 Add HubSpot cookie logging to all relevant syncuser calls
  cmd/frontend/hubspot/contacts.go
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/auth/azureoauth/BUILD.bazel
  cmd/frontend/internal/auth/azureoauth/session.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/session.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/session_test.go
  cmd/frontend/internal/auth/githuboauth/session.go
  cmd/frontend/internal/auth/githuboauth/session_test.go
  cmd/frontend/internal/auth/gitlaboauth/session.go
  cmd/frontend/internal/auth/gitlaboauth/session_test.go
  cmd/frontend/internal/auth/oauth/BUILD.bazel
  cmd/frontend/internal/auth/oauth/session.go
  cmd/frontend/internal/auth/openidconnect/BUILD.bazel
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/user.go
  cmd/frontend/internal/auth/openidconnect/user_test.go
  internal/auth/userpasswd/handlers.go
Labels: cla-signed

#58930 Fix Cody Usage Metrics SQL Query
  cmd/frontend/graphqlbackend/user.go
Labels: cla-signed

#58953 [Cody] fix limit reached UI
  client/web/src/cody/management/CodyManagementPage.module.scss
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/cody/subscription/UpgradeToProModal.tsx
  client/web/src/cody/subscription/queries.tsx
  client/web/src/marketing/components/HubSpotForm.module.scss
  internal/database/users.go
Labels: cla-signed

#58957 [Cody] disable dotcom level rate limitting for Cody GA
  internal/completions/httpapi/handler.go
Labels: cla-signed

#58959 dev: add a --skip-status flag to pr auditor
  dev/pr-auditor/README.md
  dev/pr-auditor/main.go
Labels: cla-signed

#58895 [Backport 5.2] Cody: Azure OpenAI allow authentication requests to use a proxy
  internal/completions/client/azureopenai/openai.go
  internal/embeddings/embed/client/azureopenai/BUILD.bazel
  internal/embeddings/embed/client/azureopenai/client.go
Labels: release-blocker, cla-signed, backport 5.2, backport/improvement

#58961 janitor: improve repo size update perf from 5.5sec to 200ms
  internal/database/gitserver_repos.go
Labels: cla-signed, team/source

#58913 feat: add neovim to cody redirects, instead of re-using jetbrains
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
Labels: cla-signed

#58905 Web: remove aggregableBadge from `ChunkMatch` and `LineMatch`
  client/branded/src/search-ui/components/FileContentSearchResult.tsx
  client/shared/src/components/ranking/PerFileResultRanking.ts
  client/shared/src/search/stream.ts
  client/web-sveltekit/src/lib/search/utils.ts
Labels: cla-signed

#58960 Search: convert searcher tests to autogold
  cmd/searcher/internal/search/BUILD.bazel
  cmd/searcher/internal/search/search_test.go
Labels: cla-signed

#58932 SSC: Handle model permissions correctly
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/httpapi/chat.go
Labels: cla-signed

#58948 Add URL param checking to all event types, not just page view events
  client/web/src/tracking/eventLogger.ts
Labels: cla-signed

#58950 Searcher: factor out structural search logic
  cmd/searcher/internal/search/search.go
  cmd/searcher/internal/search/search_regex_test.go
  cmd/searcher/internal/search/store.go
  cmd/searcher/internal/search/store_test.go
  cmd/searcher/internal/search/zipcache_test.go
Labels: cla-signed

#58963 Change log entry for azure auth proxy for cody provider
  CHANGELOG.md
Labels: cla-signed

#58965 release 5.2.5 in progress
  dev/release/release-config.jsonc
Labels: cla-signed

#58935 [Backport 5.2] Search: fix delimiting escape sequences
  internal/insights/query/querybuilder/builder_test.go
  internal/insights/query/querybuilder/regexp.go
  internal/insights/query/querybuilder/regexp_test.go
  internal/search/query/parser.go
  internal/search/query/parser_test.go
  internal/search/query/printer.go
  internal/search/query/testdata/TestStringHuman/printer#08.golden
Labels: cla-signed

#58934 Add Mixtral and support for chat endpoints via Fireworks
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/shared/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/client/fireworks/fireworks.go
  internal/completions/httpapi/chat.go
  internal/completions/httpapi/codecompletion.go
Labels: cla-signed, team/code-exploration

#58939 [Backport 5.2] Embeddings: fail job immediately if rate limited exceeded
  enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
  internal/embeddings/embed/embed.go
  internal/embeddings/embed/embed_test.go
Labels: cla-signed, backport/improvement

#58949 msp: Add alerts if Redis is configured
  dev/managedservicesplatform/internal/resource/monitoringalertpolicy/BUILD.bazel
  dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy.go
  dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy_test.go
  dev/managedservicesplatform/internal/resource/redis/redis.go
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/spec/monitoring.go
  lib/pointers/ptr.go
  lib/pointers/ptr_test.go
Labels: cla-signed

#58816 msp: add monitoring stack
  dev/managedservicesplatform/BUILD.bazel
  dev/managedservicesplatform/internal/resource/monitoringalertpolicy/BUILD.bazel
  dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy.go
  dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy_test.go
  dev/managedservicesplatform/internal/resource/redis/redis.go
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/monitoring/BUILD.bazel
  dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/spec/BUILD.bazel
  dev/managedservicesplatform/spec/monitoring.go
  dev/managedservicesplatform/spec/spec.go
  dev/sg/msp/sg_msp.go
  lib/pointers/ptr.go
  lib/pointers/ptr_test.go
Labels: cla-signed

#58970 5.2.5 changelog update
  CHANGELOG.md
Labels: cla-signed
