Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-08, with the labels that each got.

#64205 fix(release): check for marker in container files instead of binary
  release.yaml
Labels: cla-signed

#64208 refactor: renames usage cursor and adds fields for future syntactic cursor
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
  internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  internal/codeintel/codenav/types.go
  internal/codeintel/resolvers/codenav.go
  internal/codeintel/resolvers/codenav_test.go
Labels: team/graph, cla-signed, team/product-platform

#64174 Policy patch - leave fields unchanged if they're missing from request
  internal/codeintel/policies/internal/store/configurations.go
  internal/codeintel/policies/internal/store/store.go
  internal/codeintel/policies/mocks_test.go
  internal/codeintel/policies/service.go
  internal/codeintel/policies/shared/types.go
  internal/codeintel/policies/transport/graphql/BUILD.bazel
  internal/codeintel/policies/transport/graphql/iface.go
  internal/codeintel/policies/transport/graphql/root_resolver_policy_mutations.go
  internal/codeintel/policies/transport/graphql/root_resolver_test.go
  internal/codeintel/syntactic_indexing/scheduler_test.go
Labels: cla-signed

#64212 chunk cleaner: remove comment
  client/web/dev/esbuild/chunkCleaner.ts
Labels: cla-signed, no-changelog

#64209 sg cloud eph: simplify status
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/cloud/instance.go
  dev/sg/internal/cloud/instance_test.go
  dev/sg/internal/cloud/printers.go
Labels: cla-signed

#64210 chore: Factor out sub-query for locating nearest uploads
  internal/codeintel/uploads/internal/commitgraph/commit_graph.go
  internal/codeintel/uploads/internal/store/BUILD.bazel
  internal/codeintel/uploads/internal/store/commitgraph.go
  internal/codeintel/uploads/internal/store/commitgraph_test.go
  internal/codeintel/uploads/internal/store/util.go
Labels: team/graph, cla-signed, team/product-platform

#64207 search: apply phrase boosting to more queries
  internal/search/client/client.go
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64186 chore(search_jobs): add janitor job
  cmd/frontend/internal/search/httpapi/export.go
  cmd/worker/internal/search/BUILD.bazel
  cmd/worker/internal/search/janitor.go
  cmd/worker/internal/search/janitor_test.go
  cmd/worker/internal/search/job.go
  internal/database/schema.json
  internal/database/schema.md
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/store/BUILD.bazel
  internal/search/exhaustive/store/exhaustive_search_jobs.go
  internal/search/exhaustive/store/exhaustive_search_jobs_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_jobs_test.go
  internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs_test.go
  internal/search/exhaustive/store/store_test.go
  internal/search/exhaustive/store/storetest/BUILD.bazel
  internal/search/exhaustive/store/storetest/store.go
  internal/search/exhaustive/types/exhaustive_search_job.go
  internal/search/exhaustive/types/worker.go
  migrations/frontend/1722348497_exhaustive_search_jobs_add_column/down.sql
  migrations/frontend/1722348497_exhaustive_search_jobs_add_column/metadata.yaml
  migrations/frontend/1722348497_exhaustive_search_jobs_add_column/up.sql
  migrations/frontend/squashed.sql
Labels: team/search-platform, cla-signed, team/product-platform

#64147 Add option for --noConvertLabels
  cmd/gitserver/internal/vcssyncer/perforce.go
  schema/perforce.schema.json
  schema/schema.go
Labels: cla-signed, team/source, team/product-platform

#64194 feat(search): Add support to all Apex language extensions
  lib/codeintel/languages/extensions.go
  lib/codeintel/languages/extensions_test.go
Labels: cla-signed, team/product-platform

#64195 Bump @sourcegraph/cody-web to 0.3.2
  client/web-sveltekit/package.json
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#64216 fix(appliance): reliably redirect to site-admin post-install
  internal/appliance/frontend/maintenance/src/Frame.tsx
Labels: cla-signed

#64213 fix(appliance): cache authorization status
  internal/appliance/auth.go
Labels: cla-signed

#64201 Surface modelconfig validation errors
  cmd/frontend/internal/modelconfig/init.go
Labels: cla-signed

#64224 Bump @sourcegraph/cody-web to 0.3.4
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebar.svelte
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#64222 Svelte: welcome banner followups
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/WelcomeOverlay.svelte
  client/web-sveltekit/src/testing/integration.ts
  client/web/src/sveltekit/SvelteKitNavItem.tsx
Labels: cla-signed

#64223 Cody web: add server-side fetching for URL mentions
  cmd/frontend/graphqlbackend/cody_context.go
  cmd/frontend/graphqlbackend/cody_context.graphql
  cmd/frontend/internal/context/resolvers/BUILD.bazel
  cmd/frontend/internal/context/resolvers/context.go
Labels: cla-signed

#64227 fix(appliance): Make Appliance URL envvars strings
  client/web/dev/utils/create-js-context.ts
  client/web/src/enterprise/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/nav/UserNavItem.tsx
  client/web/src/routes.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
  client/web/src/site-admin/sidebaritems.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
  internal/conf/computed.go
Labels: cla-signed

#64200 Don't block `frontend` initialization with invalid modelconfig
  cmd/frontend/internal/modelconfig/init.go
  cmd/frontend/internal/modelconfig/service.go
  internal/modelconfig/validation.go
  internal/modelconfig/validation_test.go
Labels: cla-signed

#64017 Update the legacy link to sg doc
  client/web/README.md
  cmd/gitserver/README.md
  dev/sg/README.md
  dev/sg/VISION.md
  dev/sg/internal/check/common.go
  dev/sg/main.go
Labels: cla-signed

#64202 fix(docs): update quickstart guide links
  doc/dev/setup/quickstart.md
Labels: cla-signed

#64228 cherry-pick 856e41e with resolved conflicts
  client/web/dev/utils/create-js-context.ts
  client/web/src/enterprise/site-admin/SiteAdminSidebar.story.tsx
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/nav/UserNavItem.tsx
  client/web/src/routes.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminSidebar.tsx
  client/web/src/site-admin/sidebaritems.ts
  cmd/frontend/internal/app/jscontext/jscontext.go
  internal/conf/computed.go
Labels: cla-signed

#64229 Chore: remove enablePreciseOccurrences feature flag
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#64234 Revert "soap: Fix auto-redirect to IdP when SOAP is enabled"
  cmd/frontend/internal/auth/oauth/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/providers/BUILD.bazel
  cmd/frontend/internal/auth/providers/providers.go
  cmd/frontend/internal/auth/saml/middleware.go
Labels: cla-signed

#64217 fix: Prefer SCIP uploads over LSIF uploads
  internal/codeintel/uploads/internal/commitgraph/commit_graph.go
  internal/codeintel/uploads/internal/store/commitgraph.go
  internal/codeintel/uploads/internal/store/commitgraph_test.go
  internal/codeintel/uploads/internal/store/util.go
Labels: team/graph, cla-signed, team/product-platform

#64233 chore: Bump version of sourcegraph/log library
  deps.bzl
  go.mod
  go.sum
Labels: team/graph, cla-signed, team/product-platform

#64232 chore: De-duplicate CTE for visible uploads
  internal/codeintel/uploads/internal/store/uploads.go
Labels: team/graph, cla-signed, team/product-platform

#64237 ephemerals: fix feature flag name
  dev/sg/internal/cloud/instance.go
Labels: cla-signed

#64101 Enable p4-fusion by default for Perforce code host connections
  cmd/gitserver/internal/vcssyncer/perforce.go
  dev/gqltest/external_service_test.go
  dev/gqltest/sub_repo_permissions_test.go
  schema/perforce.schema.json
  schema/schema.go
Labels: cla-signed, team/source, team/product-platform

#64240 chore: Use binary search over symbols array
  deps.bzl
  go.mod
  go.sum
  internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
Labels: team/graph, cla-signed, team/product-platform

#64238 gomod: update Zoekt
  deps.bzl
  go.mod
  go.sum
Labels: team/search-platform, cla-signed, team/product-platform

#64244 Reapply "soap: Fix auto-redirect to IdP when SOAP is enabled" (#64234)
  cmd/frontend/internal/auth/oauth/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/providers/BUILD.bazel
  cmd/frontend/internal/auth/providers/providers.go
  cmd/frontend/internal/auth/saml/middleware.go
Labels: cla-signed, team/source, team/product-platform

#64245 gitserver: RawDiff checks if commits exist
  cmd/gitserver/internal/git/gitcli/diff.go
  cmd/gitserver/internal/git/gitcli/diff_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64243 fix(batches): show warning instead of error when the changeset status is not FAILED
  client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
Labels: cla-signed

#64248 fix: block URLs without a hostname
  internal/httpcli/client.go
Labels: cla-signed, SSDLC

#64221 Styling updates throughout
  client/web-sveltekit/src/lib/TabsHeader.svelte
  client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
  client/web-sveltekit/src/lib/navigation/FeedbackDialog.svelte
  client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
  client/web-sveltekit/src/lib/repo/LastCommit.svelte
  client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
  client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte
  client/web-sveltekit/src/lib/repo/filePopover/FilePopover.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/HelpFooter.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/SectionItem.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#64204 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/appliance-frontend.lock.json
  wolfi-images/appliance.lock.json
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#64251 Svelte: fix welcome banner flashing on reload
  client/web-sveltekit/src/routes/+layout.svelte
Labels: cla-signed

#64180 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/appliance.lock.json
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#64230 Web: fix git blame for files that have `/stream/` in their path
  client/web/src/repo/blame/shared.ts
  cmd/frontend/internal/httpapi/httpapi.go
Labels: cla-signed

#64249 Chore: remove non-null assertions
  client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
  client/web-sveltekit/src/lib/codenav/ExplorePanelFileUsages.svelte
Labels: cla-signed

#64254 Cody Web: Update Cody Web to 0.3.6 [React version]
  client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.tsx
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.module.scss
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.module.scss
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#64014 [Svelte]: UI Updates for Perforce Depots and Git Repos
  client/web-sveltekit/src/lib/Commit.gql
  client/web-sveltekit/src/lib/Commit.svelte
  client/web-sveltekit/src/lib/repo/RepositoryRevPicker.gql
  client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
  client/web-sveltekit/src/lib/routes.ts
  client/web-sveltekit/src/params/commit_or_changelist.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/-/compare/[...rangeSpec]/+page.svelte
  client/web/src/sveltekit/routes.ts
  cmd/frontend/internal/app/ui/sveltekit/gen/gen_routes.go
  cmd/frontend/internal/app/ui/sveltekit/routes.go
Labels: cla-signed

#64241 fix: Handle sub-repo permissions in CodeGraphData API
  internal/codeintel/codenav/transport/graphql/BUILD.bazel
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/codenav/transport/graphql/root_resolver_test.go
Labels: team/graph, cla-signed, team/product-platform

#64263 fix: Don't propagate un-translated source ranges
  internal/codeintel/codenav/service.go
Labels: team/graph, cla-signed, team/product-platform

#64247 servicecatalog: remove searcher dep on database
  lib/servicecatalog/service-catalog.yaml
Labels: team/search-platform, cla-signed, team/product-platform

#64265 fix: Handle potential nil reference properly
  internal/codeintel/codenav/transport/graphql/root_resolver_code_graph.go
  internal/codeintel/codenav/transport/graphql/root_resolver_test.go
  internal/codeintel/resolvers/codenav.go
Labels: team/graph, cla-signed, team/product-platform

#64267 chore: Remove incorrectly logged warning
  internal/codeintel/codenav/service_new.go
Labels: team/graph, cla-signed, team/product-platform

#64264 gomod: update zoekt for shard scanning improvement
  deps.bzl
  go.mod
  go.sum
Labels: team/search-platform, cla-signed, team/product-platform

#64133 feat(cody): add circuit breaker to handle timed-out requests and rate limit hits
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/loadtracker.go
  cmd/cody-gateway/internal/httpapi/completions/loadtracker_test.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#64266 Update p4-fusion-sg wolfi-package
  wolfi-packages/p4-fusion-sg.yaml
Labels: cla-signed, team/source, team/product-platform

#64155 frontend: Remove global conf server variable
  cmd/frontend/auth/non_public_test.go
  cmd/frontend/globals/BUILD.bazel
  cmd/frontend/globals/globals.go
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/access_tokens_test.go
  cmd/frontend/graphqlbackend/executor_secrets_test.go
  cmd/frontend/graphqlbackend/external_accounts_test.go
  cmd/frontend/graphqlbackend/external_services_test.go
  cmd/frontend/graphqlbackend/gitserver_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/guardrails_test.go
  cmd/frontend/graphqlbackend/permission_test.go
  cmd/frontend/graphqlbackend/permissions_test.go
  cmd/frontend/graphqlbackend/repository_metadata_test.go
  cmd/frontend/graphqlbackend/role_test.go
  cmd/frontend/graphqlbackend/roles_test.go
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/search_test.go
  cmd/frontend/graphqlbackend/settings_cascade.go
  cmd/frontend/graphqlbackend/settings_mutation_test.go
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/site_admin_test.go
  cmd/frontend/graphqlbackend/site_config_change_test.go
  cmd/frontend/graphqlbackend/site_test.go
  cmd/frontend/graphqlbackend/status_messages_test.go
  cmd/frontend/graphqlbackend/telemetry_test.go
  cmd/frontend/graphqlbackend/testing.go
  cmd/frontend/graphqlbackend/user_emails_test.go
  cmd/frontend/graphqlbackend/user_test.go
  cmd/frontend/internal/app/jscontext/BUILD.bazel
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/app/ui/BUILD.bazel
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/app/ui/legacy_extensions_redirects_test.go
  cmd/frontend/internal/app/ui/raw.go
  cmd/frontend/internal/app/ui/raw_test.go
  cmd/frontend/internal/app/ui/router.go
  cmd/frontend/internal/app/ui/router_test.go
  cmd/frontend/internal/authz/resolvers/resolver_test.go
  cmd/frontend/internal/batches/resolvers/main_test.go
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
  cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs_test.go
  cmd/frontend/internal/githubapp/resolver_test.go
  cmd/frontend/internal/guardrails/resolvers/resolver_test.go
  cmd/frontend/internal/licensing/resolvers/resolvers_test.go
  cmd/frontend/internal/notebooks/resolvers/resolvers_test.go
  cmd/frontend/internal/notebooks/resolvers/stars_resolvers_test.go
  cmd/frontend/internal/own/resolvers/codeowners_resolvers_test.go
  cmd/frontend/internal/own/resolvers/resolvers_test.go
  cmd/frontend/internal/rbac/resolvers/main_test.go
  cmd/frontend/internal/repos/webhooks/resolvers/resolver_test.go
Labels: cla-signed, team/source, team/product-platform

#64157 chore: Move cmd/frontend/webhooks to cmd/frontend/internal
  cmd/frontend/enterprise/BUILD.bazel
  cmd/frontend/enterprise/enterprise.go
  cmd/frontend/internal/app/jscontext/BUILD.bazel
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/authz/webhooks/BUILD.bazel
  cmd/frontend/internal/authz/webhooks/github.go
  cmd/frontend/internal/authz/webhooks/github_test.go
  cmd/frontend/internal/batches/webhooks/BUILD.bazel
  cmd/frontend/internal/batches/webhooks/azuredevops.go
  cmd/frontend/internal/batches/webhooks/bitbucketcloud.go
  cmd/frontend/internal/batches/webhooks/bitbucketserver.go
  cmd/frontend/internal/batches/webhooks/github.go
  cmd/frontend/internal/batches/webhooks/github_test.go
  cmd/frontend/internal/batches/webhooks/gitlab.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/webhookhandlers/BUILD.bazel
  cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
  cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
  cmd/frontend/internal/httpapi/webhookhandlers/handlers.go
  cmd/frontend/internal/repos/webhooks/BUILD.bazel
  cmd/frontend/internal/repos/webhooks/handlers.go
  cmd/frontend/internal/repos/webhooks/handlers_test.go
  cmd/frontend/internal/webhooks/BUILD.bazel
  cmd/frontend/internal/webhooks/azuredevops_webhooks.go
  cmd/frontend/internal/webhooks/bitbucketcloud_webhooks.go
  cmd/frontend/internal/webhooks/bitbucketserver_webhooks.go
  cmd/frontend/internal/webhooks/github_webhooks.go
  cmd/frontend/internal/webhooks/github_webhooks_test.go
  cmd/frontend/internal/webhooks/gitlab_webhooks.go
  cmd/frontend/internal/webhooks/middleware.go
  cmd/frontend/internal/webhooks/middleware_test.go
  cmd/frontend/internal/webhooks/testdata/bitbucketcloud_body.json
  cmd/frontend/internal/webhooks/webhooks.go
  cmd/frontend/internal/webhooks/webhooks_test.go
Labels: cla-signed, team/source, team/product-platform

#64256 Svelte: make closing the welcome overlay more obvious
  client/web-sveltekit/src/routes/WelcomeOverlay.svelte
Labels: cla-signed

#64274 refactor(svelte): Reduce logo complexity
  client/web-sveltekit/src/lib/assets/sourcegraph-logo.svg
  client/web-sveltekit/src/lib/images.ts
  client/web-sveltekit/src/routes/search/SearchHome.svelte
Labels: cla-signed

#64275 Revert "[Svelte]: UI Updates for Perforce Depots and Git Repos"
  client/web-sveltekit/src/lib/Commit.gql
  client/web-sveltekit/src/lib/Commit.svelte
  client/web-sveltekit/src/lib/repo/RepositoryRevPicker.gql
  client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
  client/web-sveltekit/src/lib/routes.ts
  client/web-sveltekit/src/params/commit_or_changelist.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/-/compare/[...rangeSpec]/+page.svelte
  client/web/src/sveltekit/routes.ts
  cmd/frontend/internal/app/ui/sveltekit/gen/gen_routes.go
  cmd/frontend/internal/app/ui/sveltekit/routes.go
Labels: cla-signed

#64277 Svelte: remove site admin gate on code intel preview
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
Labels: cla-signed

#64282 appliance(chore): Remove legacy maintenance API
  internal/appliance/maintenance/backend/api/BUILD.bazel
  internal/appliance/maintenance/backend/api/auth.go
  internal/appliance/maintenance/backend/api/install.go
  internal/appliance/maintenance/backend/api/json.go
  internal/appliance/maintenance/backend/api/server.go
  internal/appliance/maintenance/backend/api/stage.go
  internal/appliance/maintenance/backend/api/status.go
  internal/appliance/maintenance/backend/api/task.go
Labels: cla-signed, no-changelog

#64278 Improving Azure errors for customer containers
  cmd/customer-2315/main.go
  cmd/customer-4512/main.go
Labels: cla-signed

#64276 Return 'sourcegraph' as the CodyLLMConfigurationResolver.Provider
  cmd/frontend/internal/modelconfig/BUILD.bazel
  cmd/frontend/internal/modelconfig/resolver.go
  cmd/frontend/internal/modelconfig/resolver_test.go
Labels: cla-signed

#64285 Enable SCIP based APIs by default
  internal/conf/computed.go
  schema/site.schema.json
Labels: team/graph, cla-signed, team/product-platform

#64288 chore: Reduce frequency of COUNT(*) on lsif_indexes
  cmd/worker/internal/executorqueue/reporter.go
Labels: team/graph, cla-signed, team/product-platform

#64286 chore: Consolidate mocks for uploads's Store type
  dev/BUILD.bazel
  internal/codeintel/uploads/internal/background/backfiller/BUILD.bazel
  internal/codeintel/uploads/internal/background/backfiller/job_backfill_test.go
  internal/codeintel/uploads/internal/background/expirer/BUILD.bazel
  internal/codeintel/uploads/internal/background/expirer/job_expirer_test.go
  internal/codeintel/uploads/internal/background/expirer/mocks_test.go
  internal/codeintel/uploads/internal/background/processor/BUILD.bazel
  internal/codeintel/uploads/internal/background/processor/job_worker_handler_test.go
  internal/codeintel/uploads/internal/background/processor/mocks_test.go
  internal/codeintel/uploads/internal/storemocks/BUILD.bazel
  internal/codeintel/uploads/internal/storemocks/mocks_temp.go
  mockgen.temp.yaml
  mockgen.test.yaml
Labels: team/graph, cla-signed, team/product-platform

#64287 fix(search_jobs): progress reporting
  client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
  cmd/frontend/internal/search/resolvers/search_job.go
Labels: team/search-platform, cla-signed, team/product-platform

#64292 searcher: fix benchmarks
  cmd/searcher/internal/search/chunk_test.go
  cmd/searcher/internal/search/search_regex_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64290 fix: uses the same base64 for decoding we use for encoding the UsageCursor
  internal/codeintel/resolvers/codenav.go
Labels: team/graph, cla-signed, team/product-platform

#64272 fix(svelte): Update top-level route list
  client/web-sveltekit/.env
  client/web-sveltekit/.env.dotcom
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/dev/vite-sg-proxy.ts
  client/web-sveltekit/playwright.config.ts
  client/web-sveltekit/src/app.html
  client/web-sveltekit/src/lib/navigation.ts
  client/web-sveltekit/src/params/reporev.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
  client/web-sveltekit/src/routes/layout.spec.ts
  client/web-sveltekit/src/testing/integration.ts
  client/web-sveltekit/vite.config.ts
  cmd/frontend/internal/app/router/BUILD.bazel
  cmd/frontend/internal/app/router/router.go
  cmd/frontend/internal/app/ui/sveltekit/sveltekit.go
Labels: cla-signed

#64294 chore: Consolidate mocks for dbworker/store.Store type
  internal/codeintel/autoindexing/internal/background/dependencies/BUILD.bazel
  internal/codeintel/autoindexing/internal/background/dependencies/job_dependency_indexing_scheduler_test.go
  internal/codeintel/autoindexing/internal/background/dependencies/job_dependency_sync_scheduler_test.go
  internal/codeintel/autoindexing/internal/background/dependencies/mocks_test.go
  internal/codeintel/uploads/BUILD.bazel
  internal/codeintel/uploads/internal/background/expirer/BUILD.bazel
  internal/codeintel/uploads/internal/background/expirer/mocks_test.go
  internal/codeintel/uploads/internal/background/processor/BUILD.bazel
  internal/codeintel/uploads/internal/background/processor/job_worker_handler_test.go
  internal/codeintel/uploads/internal/background/processor/mocks_test.go
  internal/codeintel/uploads/mocks_test.go
  mockgen.test.yaml
Labels: team/graph, cla-signed, team/product-platform

#64293 Search: re-add support for 'lucky' patterntype
  internal/search/client/client.go
  internal/search/client/client_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64273 chore: Frontend does not need disk
  cmd/frontend/image_test.yaml
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/serve_cmd.go
  wolfi-images/appliance-frontend.lock.json
  wolfi-images/appliance.lock.json
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-base.yaml
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, team/source, team/product-platform

#64158 chore: Remove unnecessary _ imports
  cmd/frontend/internal/licensing/init/BUILD.bazel
  cmd/frontend/internal/licensing/init/init.go
  cmd/frontend/internal/modelconfig/BUILD.bazel
  cmd/frontend/internal/modelconfig/init.go
Labels: cla-signed, team/source, team/product-platform

#64298 Search: boost matches on quoted terms
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64295 fix(svelte): Make /cody/dashboard work with the new web app
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed

#64297 fix: Add Exists method to dbworker Store to avoid COUNT(*)
  cmd/frontend/internal/executorqueue/handler/multihandler.go
  cmd/frontend/internal/executorqueue/handler/multihandler_test.go
  internal/workerutil/dbworker/store/mocks/mocks_temp.go
  internal/workerutil/dbworker/store/observability.go
  internal/workerutil/dbworker/store/store.go
  internal/workerutil/dbworker/store/store_test.go
Labels: team/graph, cla-signed, team/product-platform

#64300 fix(search_jobs): fail validation for repo searches
  internal/search/job/jobutil/exhaustive_job.go
  internal/search/job/jobutil/exhaustive_job_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64303 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/appliance-frontend.lock.json
  wolfi-images/appliance.lock.json
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#64281 Update the default Sourcegraph-supplied LLM models
  cmd/cody-gateway-config/dotcom_models.go
  cmd/cody-gateway-config/main.go
  cmd/cody-gateway-config/providers.go
  cmd/frontend/internal/httpapi/completions/get_model_test.go
  internal/modelconfig/embedded/models.json
  internal/modelconfig/validation.go
Labels: cla-signed

#64309 fix(svelte): Center file tree loading indicator
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#64307 Return model IDs from GraphQL, not model Names
  cmd/frontend/internal/modelconfig/resolver.go
  cmd/frontend/internal/modelconfig/resolver_test.go
  cmd/frontend/internal/modelconfig/siteconfig_completions.go
  cmd/frontend/internal/modelconfig/siteconfig_completions_test.go
Labels: cla-signed

#64312 fix(own): Prevent infinite UI update loop in own pages
  client/web/src/enterprise/own/RepositoryOwnEditPage.tsx
  client/web/src/enterprise/own/RepositoryOwnPage.tsx
Labels: cla-signed

#64313 chore(svelte): Add manual entries for repo sub pages to development proxy
  client/web-sveltekit/dev/vite-sg-proxy.ts
Labels: cla-signed

#64280 feat(sg): report user os information via analytics
  dev/sg/internal/analytics/analytics.go
  dev/sg/internal/analytics/bigquery.go
Labels: cla-signed

#64214 fix(bazel): surface error message when gazelle cant process glob expression
  dev/ci/bazel-configure.sh
  dev/sg/sg_bazel.go
Labels: cla-signed

#64296 Update Cody Web to 0.3.7
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  client/web/BUILD.bazel
  client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
  client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.module.scss
  client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.tsx
  client/web/src/cody/chat/new-chat/components/chat-ui/ChatUi.tsx
  client/web/src/cody/chat/new-chat/components/skeleton/Skeleton.module.scss
  client/web/src/cody/chat/new-chat/components/skeleton/Skeleton.tsx
  client/web/src/cody/chat/old-chat/CodyChatPage.tsx
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.module.scss
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.module.scss
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#64319 refactor: handles Cursor uniformly over all usage provenances
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_syntactic_usages_test.go
  internal/codeintel/codenav/syntactic.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/codenav/types.go
Labels: team/graph, cla-signed, team/product-platform

#64320 Fix Cody Web Svelte Sidebar
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
Labels: cla-signed

#64302 chore: Replace QueuedCount -> CountByState with bitset parameter
  cmd/worker/internal/executormultiqueue/multiqueue_metrics_reporter.go
  cmd/worker/internal/executorqueue/external_emitter.go
  cmd/worker/internal/executorqueue/reporter.go
  cmd/worker/internal/permissions/BUILD.bazel
  cmd/worker/internal/permissions/bitbucket_projects_test.go
  cmd/worker/internal/search/job.go
  internal/codeintel/syntactic_indexing/BUILD.bazel
  internal/codeintel/syntactic_indexing/scheduler_test.go
  internal/codeintel/syntactic_indexing/store_test.go
  internal/insights/background/queryrunner/worker.go
  internal/own/background/BUILD.bazel
  internal/own/background/background_test.go
  internal/workerutil/dbworker/metrics.go
  internal/workerutil/dbworker/store/mocks/mocks_temp.go
  internal/workerutil/dbworker/store/observability.go
  internal/workerutil/dbworker/store/store.go
  internal/workerutil/dbworker/store/store_test.go
  internal/workerutil/dbworker/store_shim.go
Labels: team/graph, cla-signed, team/product-platform

#64318 chore: Move and clean up test code for syntactic usages
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/helpers_test.go
  internal/codeintel/codenav/mapped_index_test.go
  internal/codeintel/codenav/syntactic_test.go
  internal/codeintel/codenav/utils_test.go
Labels: team/graph, cla-signed, team/product-platform

#64324 Center align Cody logo in Cody Web Sidebar
  client/web-sveltekit/src/lib/cody/CodySidebar.svelte
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
Labels: cla-signed

#64321 refactor: steps the usage cursor provenance state in a single place
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/codenav/types.go
  internal/codeintel/resolvers/codenav.go
Labels: team/graph, cla-signed, team/product-platform

#64299 fix(batches): don't request unnecessary info that's likely to cause GH errors
  internal/batches/sources/github.go
  internal/batches/sources/testdata/golden/GithubSource_CreateChangeset_already_exists
  internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_already-exists.yaml
  internal/batches/sources/testdata/sources/GithubSource_CreateChangeset_already_exists.yaml
  internal/extsvc/github/common.go
Labels: cla-signed

#64328 fix: Try workaround for bad index choice when updating execution logs
  internal/workerutil/dbworker/store/store.go
Labels: team/graph, cla-signed, team/product-platform

#64308 feat(svelte): Add support for creating search jobs from search results
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
  client/web-sveltekit/src/app.html
  client/web-sveltekit/src/lib/LoadingSpinner.stories.svelte
  client/web-sveltekit/src/lib/LoadingSpinner.svelte
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/routes/search/+page.svelte
  client/web-sveltekit/src/routes/search/+page.ts
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web-sveltekit/src/routes/search/StreamingProgress.svelte
  client/web-sveltekit/src/routes/search/page.spec.ts
  client/web-sveltekit/src/routes/search/searchJob.gql
  client/web-sveltekit/src/routes/search/searchJob.ts
  client/web-sveltekit/src/routes/styles.scss
  client/web-sveltekit/src/testing/graphql-mocking.ts
  client/web-sveltekit/src/testing/integration.ts
Labels: cla-signed

#64334 upgrade Cody Web, always create a new chat
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  client/web/src/cody/chat/new-chat/NewCodyChatPage.module.scss
  client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#64327 fix(svelte): Better preloading in file tree
  client/web-sveltekit/src/lib/TreeNode.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed

#64331 fix(svelte): Properly redirect to cody marketing page
  client/web-sveltekit/src/lib/navigation.ts
Labels: cla-signed

#64283 chore: Add docs for RepoStore methods
  internal/database/repos.go
Labels: team/graph, cla-signed, team/product-platform

#64325 fix(sg): provide suggestions we fail to get local gcp account email address
  dev/sg/internal/cloud/client.go
  dev/sg/internal/cloud/common.go
  dev/sg/internal/cloud/dashboard_command.go
  dev/sg/internal/cloud/delete_command.go
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/cloud/lease_command.go
  dev/sg/internal/cloud/list_command.go
  dev/sg/internal/cloud/status_command.go
  dev/sg/internal/cloud/upgrade_command.go
Labels: cla-signed

#64311 Svelte: more welcome banner behavior updates
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web-sveltekit/src/lib/navigation/FeedbackDialog.svelte
  client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/WelcomeOverlay.svelte
  client/web/BUILD.bazel
  client/web/dist/img/welcome-overlay-screenshot-dark.svg
  client/web/dist/img/welcome-overlay-screenshot-light.svg
  client/web/src/sveltekit/LearnMoreOverlay.module.scss
  client/web/src/sveltekit/LearnMoreOverlay.tsx
  client/web/src/sveltekit/SvelteKitNavItem.module.scss
  client/web/src/sveltekit/SvelteKitNavItem.tsx
Labels: cla-signed

#64340 Svelte: enable toggle by default
  cmd/frontend/internal/app/ui/sveltekit/sveltekit.go
Labels: cla-signed

#64122 chore(local): clear ambiguity in between sg version|live
  dev/sg/sg_version.go
Labels: cla-signed

#64343 chore(rel): prepare stitch graph for 5.6
  WORKSPACE
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/stitched-migration-graph.json
Labels: cla-signed, no-changelog

#63858 feat/enterpriseportal: import data from dotcom
  cmd/cody-gateway/internal/notify/rate_limit.go
  cmd/enterprise-portal/internal/database/BUILD.bazel
  cmd/enterprise-portal/internal/database/codyaccess/BUILD.bazel
  cmd/enterprise-portal/internal/database/codyaccess/codyaccess.go
  cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
  cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
  cmd/enterprise-portal/internal/database/database.go
  cmd/enterprise-portal/internal/database/importer/BUILD.bazel
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
  cmd/enterprise-portal/internal/database/subscriptions/licenses.go
  cmd/enterprise-portal/internal/database/subscriptions/licenses_test.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
  cmd/enterprise-portal/internal/database/types.go
  cmd/enterprise-portal/internal/dotcomdb/BUILD.bazel
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  cmd/enterprise-portal/service/BUILD.bazel
  cmd/enterprise-portal/service/config.go
  cmd/enterprise-portal/service/redis.go
  cmd/enterprise-portal/service/service.go
  internal/redislock/BUILD.bazel
  internal/redislock/redislock.go
  internal/redislock/redislock_test.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.proto
Labels: cla-signed

#64346 fix/enterpriseportal/importer: make generated display name more unique
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
Labels: cla-signed

#64348 fix/enterpriseportal/importer: import all subscriptions
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
Labels: cla-signed

#64349 feat(svelte): Support 'got to defintion' for multiple definitions and 'find implementations'
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
  client/web-sveltekit/src/lib/repo/blob.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#63829 refactor: upgrade to rules_oci 2.0 (2nd attempt)
  WORKSPACE
  cmd/appliance/BUILD.bazel
  cmd/batcheshelper/BUILD.bazel
  cmd/blobstore/BUILD.bazel
  cmd/bundled-executor/BUILD.bazel
  cmd/cody-gateway/BUILD.bazel
  cmd/customer-2315/BUILD.bazel
  cmd/customer-4512/BUILD.bazel
  cmd/embeddings/BUILD.bazel
  cmd/enterprise-portal/BUILD.bazel
  cmd/executor-kubernetes/BUILD.bazel
  cmd/executor/BUILD.bazel
  cmd/executor/vm-image/BUILD.bazel
  cmd/executor/vm-image/_ami.build.sh
  cmd/frontend/BUILD.bazel
  cmd/gitserver/BUILD.bazel
  cmd/loadtest/BUILD.bazel
  cmd/migrator/BUILD.bazel
  cmd/msp-example/BUILD.bazel
  cmd/pings/BUILD.bazel
  cmd/precise-code-intel-worker/BUILD.bazel
  cmd/repo-updater/BUILD.bazel
  cmd/searcher/BUILD.bazel
  cmd/server/BUILD.bazel
  cmd/server/macro.bzl
  cmd/symbols/BUILD.bazel
  cmd/syntactic-code-intel-worker/BUILD.bazel
  cmd/telemetry-gateway/BUILD.bazel
  cmd/worker/BUILD.bazel
  dev/build-tracker/BUILD.bazel
  dev/ci/push_all.sh
  dev/linearhooks/BUILD.bazel
  dev/oci_defs.bzl
  doc/dev/background-information/bazel/containers.md
  doc/dev/background-information/bazel/faq.md
  doc/dev/background-information/sg/index.md
  docker-images/appliance-frontend/BUILD.bazel
  docker-images/cadvisor/BUILD.bazel
  docker-images/codeinsights-db/BUILD.bazel
  docker-images/dind/BUILD.bazel
  docker-images/executor-vm/BUILD.bazel
  docker-images/grafana/BUILD.bazel
  docker-images/indexed-searcher/BUILD.bazel
  docker-images/jaeger-all-in-one/BUILD.bazel
  docker-images/opentelemetry-collector/BUILD.bazel
  docker-images/postgres-12-alpine/BUILD.bazel
  docker-images/postgres_exporter/BUILD.bazel
  docker-images/prometheus/BUILD.bazel
  docker-images/redis-cache/BUILD.bazel
  docker-images/redis-store/BUILD.bazel
  docker-images/search-indexer/BUILD.bazel
  docker-images/sg/BUILD.bazel
  docker-images/syntax-highlighter/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  internal/appliance/frontend/maintenance/BUILD.bazel
  internal/version/BUILD.bazel
  sg.config.yaml
Labels: cla-signed

#64347 Changing azureUseDeprecatedCompletionsAPIForOldModels to default to true
  schema/site.schema.json
Labels: cla-signed

#64351 Revert "refactor: upgrade to rules_oci 2.0 (2nd attempt)"
  WORKSPACE
  cmd/appliance/BUILD.bazel
  cmd/batcheshelper/BUILD.bazel
  cmd/blobstore/BUILD.bazel
  cmd/bundled-executor/BUILD.bazel
  cmd/cody-gateway/BUILD.bazel
  cmd/customer-2315/BUILD.bazel
  cmd/customer-4512/BUILD.bazel
  cmd/embeddings/BUILD.bazel
  cmd/enterprise-portal/BUILD.bazel
  cmd/executor-kubernetes/BUILD.bazel
  cmd/executor/BUILD.bazel
  cmd/executor/vm-image/BUILD.bazel
  cmd/executor/vm-image/_ami.build.sh
  cmd/frontend/BUILD.bazel
  cmd/gitserver/BUILD.bazel
  cmd/loadtest/BUILD.bazel
  cmd/migrator/BUILD.bazel
  cmd/msp-example/BUILD.bazel
  cmd/pings/BUILD.bazel
  cmd/precise-code-intel-worker/BUILD.bazel
  cmd/repo-updater/BUILD.bazel
  cmd/searcher/BUILD.bazel
  cmd/server/BUILD.bazel
  cmd/server/macro.bzl
  cmd/symbols/BUILD.bazel
  cmd/syntactic-code-intel-worker/BUILD.bazel
  cmd/telemetry-gateway/BUILD.bazel
  cmd/worker/BUILD.bazel
  dev/build-tracker/BUILD.bazel
  dev/ci/push_all.sh
  dev/linearhooks/BUILD.bazel
  dev/oci_defs.bzl
  doc/dev/background-information/bazel/containers.md
  doc/dev/background-information/bazel/faq.md
  doc/dev/background-information/sg/index.md
  docker-images/appliance-frontend/BUILD.bazel
  docker-images/cadvisor/BUILD.bazel
  docker-images/codeinsights-db/BUILD.bazel
  docker-images/dind/BUILD.bazel
  docker-images/executor-vm/BUILD.bazel
  docker-images/grafana/BUILD.bazel
  docker-images/indexed-searcher/BUILD.bazel
  docker-images/jaeger-all-in-one/BUILD.bazel
  docker-images/opentelemetry-collector/BUILD.bazel
  docker-images/postgres-12-alpine/BUILD.bazel
  docker-images/postgres_exporter/BUILD.bazel
  docker-images/prometheus/BUILD.bazel
  docker-images/redis-cache/BUILD.bazel
  docker-images/redis-store/BUILD.bazel
  docker-images/search-indexer/BUILD.bazel
  docker-images/sg/BUILD.bazel
  docker-images/syntax-highlighter/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  internal/appliance/frontend/maintenance/BUILD.bazel
  internal/version/BUILD.bazel
  sg.config.yaml
Labels: cla-signed

#64352 fix/enterpriseportal/importer: disable query tracing when importing
  cmd/enterprise-portal/internal/database/importer/BUILD.bazel
  cmd/enterprise-portal/internal/database/importer/importer.go
  lib/managedservicesplatform/cloudsql/tracer.go
Labels: cla-signed

#64159 oidc: Don't require to run refresh on provider init
  cmd/frontend/graphqlbackend/external_account_data_resolver_test.go
  cmd/frontend/internal/auth/gerrit/config.go
  cmd/frontend/internal/auth/httpheader/provider.go
  cmd/frontend/internal/auth/oauth/provider.go
  cmd/frontend/internal/auth/openidconnect/config.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware_test.go
  cmd/frontend/internal/auth/openidconnect/provider.go
  cmd/frontend/internal/auth/openidconnect/session.go
  cmd/frontend/internal/auth/openidconnect/user.go
  cmd/frontend/internal/auth/openidconnect/user_test.go
  cmd/frontend/internal/auth/providers/mock_auth_provider.go
  cmd/frontend/internal/auth/providers/providers.go
  cmd/frontend/internal/auth/saml/config.go
  cmd/frontend/internal/auth/saml/provider.go
  cmd/frontend/internal/auth/sourcegraphoperator/config.go
  cmd/frontend/internal/auth/sourcegraphoperator/middleware.go
  cmd/frontend/internal/auth/sourcegraphoperator/middleware_test.go
  cmd/frontend/internal/auth/sourcegraphoperator/provider.go
  cmd/frontend/internal/auth/userpasswd/provider.go
Labels: cla-signed, team/source, team/product-platform

#64353 fix(build): forward runfiles in custom oci_image_cross rule
  dev/oci_defs.bzl
Labels: cla-signed

#64260 auth: Remove redirects to session package
  cmd/frontend/auth/BUILD.bazel
  cmd/frontend/auth/sign_out_cookie.go
  cmd/frontend/internal/app/BUILD.bazel
  cmd/frontend/internal/app/sign_out.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/middleware_test.go
  cmd/frontend/internal/auth/githuboauth/middleware_test.go
  cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
  cmd/frontend/internal/auth/oauth/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware_test.go
  cmd/frontend/internal/auth/saml/middleware.go
  cmd/frontend/internal/auth/saml/middleware_test.go
  cmd/frontend/internal/auth/session/session.go
Labels: cla-signed, team/source, team/product-platform

#64354 Revert "Revert "refactor: upgrade to rules_oci 2.0 (2nd attempt)""
  WORKSPACE
  cmd/appliance/BUILD.bazel
  cmd/batcheshelper/BUILD.bazel
  cmd/blobstore/BUILD.bazel
  cmd/bundled-executor/BUILD.bazel
  cmd/cody-gateway/BUILD.bazel
  cmd/customer-2315/BUILD.bazel
  cmd/customer-4512/BUILD.bazel
  cmd/embeddings/BUILD.bazel
  cmd/enterprise-portal/BUILD.bazel
  cmd/executor-kubernetes/BUILD.bazel
  cmd/executor/BUILD.bazel
  cmd/executor/vm-image/BUILD.bazel
  cmd/executor/vm-image/_ami.build.sh
  cmd/frontend/BUILD.bazel
  cmd/gitserver/BUILD.bazel
  cmd/loadtest/BUILD.bazel
  cmd/migrator/BUILD.bazel
  cmd/msp-example/BUILD.bazel
  cmd/pings/BUILD.bazel
  cmd/precise-code-intel-worker/BUILD.bazel
  cmd/repo-updater/BUILD.bazel
  cmd/searcher/BUILD.bazel
  cmd/server/BUILD.bazel
  cmd/server/macro.bzl
  cmd/symbols/BUILD.bazel
  cmd/syntactic-code-intel-worker/BUILD.bazel
  cmd/telemetry-gateway/BUILD.bazel
  cmd/worker/BUILD.bazel
  dev/build-tracker/BUILD.bazel
  dev/ci/push_all.sh
  dev/linearhooks/BUILD.bazel
  dev/oci_defs.bzl
  doc/dev/background-information/bazel/containers.md
  doc/dev/background-information/bazel/faq.md
  doc/dev/background-information/sg/index.md
  docker-images/appliance-frontend/BUILD.bazel
  docker-images/cadvisor/BUILD.bazel
  docker-images/codeinsights-db/BUILD.bazel
  docker-images/dind/BUILD.bazel
  docker-images/executor-vm/BUILD.bazel
  docker-images/grafana/BUILD.bazel
  docker-images/indexed-searcher/BUILD.bazel
  docker-images/jaeger-all-in-one/BUILD.bazel
  docker-images/opentelemetry-collector/BUILD.bazel
  docker-images/postgres-12-alpine/BUILD.bazel
  docker-images/postgres_exporter/BUILD.bazel
  docker-images/prometheus/BUILD.bazel
  docker-images/redis-cache/BUILD.bazel
  docker-images/redis-store/BUILD.bazel
  docker-images/search-indexer/BUILD.bazel
  docker-images/sg/BUILD.bazel
  docker-images/syntax-highlighter/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  internal/appliance/frontend/maintenance/BUILD.bazel
  internal/version/BUILD.bazel
  sg.config.yaml
Labels: cla-signed

#64350 fix(svelte): Improve hovercard UI for search based info
  client/web-sveltekit/src/lib/repo/HovercardContent.svelte
Labels: cla-signed

#64333 refactor(svelte): Improve integration with `sg`
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/README.md
  client/web-sveltekit/dev/vite-sg-proxy.ts
  client/web-sveltekit/package.json
  client/web-sveltekit/playwright.config.ts
  client/web-sveltekit/vite.config.ts
  dev/Caddyfile-sveltekit
  sg.config.yaml
Labels: cla-signed

#64358 fix(svelte): Don't animate menu icon
  client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
Labels: cla-signed

#64341 chore(local): rename experiment single-program commandset
  dev/sg/internal/sgconf/config.go
  dev/sg/sg_start.go
  sg.config.yaml
Labels: cla-signed, no-changelog

#64335 chore(backend): enable diskcache for multi-tenant
  internal/diskcache/BUILD.bazel
  internal/diskcache/cache.go
  internal/diskcache/cache_test.go
  internal/tenant/BUILD.bazel
  internal/tenant/context.go
  internal/tenant/enforcement.go
Labels: team/search-platform, cla-signed, team/product-platform

#64359 tenant: Ensure tenant table also exists in codeintel and codeinsights DBs
  internal/database/schema.codeinsights.json
  internal/database/schema.codeinsights.md
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  migrations/codeinsights/1723117231_add_tenants_table/down.sql
  migrations/codeinsights/1723117231_add_tenants_table/metadata.yaml
  migrations/codeinsights/1723117231_add_tenants_table/up.sql
  migrations/codeinsights/squashed.sql
  migrations/codeintel/1723117227_add_tenants_table/down.sql
  migrations/codeintel/1723117227_add_tenants_table/metadata.yaml
  migrations/codeintel/1723117227_add_tenants_table/up.sql
  migrations/codeintel/squashed.sql
Labels: cla-signed, team/source, team/product-platform

#64362 ci: provide a more descriptive error when pipegen fails
  dev/ci/internal/ci/config.go
Labels: cla-signed

#64357 fix(svelte): Always close navigation sidebar when navigating to a different page
  client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
Labels: cla-signed

#64355 build(svelte): Build Svelte app with enterprise runset
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/README.md
  client/web-sveltekit/package.json
  client/web-sveltekit/svelte.config.js
  sg.config.yaml
Labels: cla-signed

#64337 database: optional pprof for tenantless_queries
  internal/database/dbconn/BUILD.bazel
  internal/database/dbconn/open.go
  internal/database/dbconn/tenant_pprof.go
Labels: team/search-platform, cla-signed, team/product-platform

#64363 tenant: update FromContext to return error
  internal/database/dbconn/tenant_pprof.go
  internal/diskcache/cache.go
  internal/tenant/context.go
  internal/tenant/context_test.go
  internal/tenant/externalhttp_test.go
  internal/tenant/grpc.go
  internal/tenant/grpc_test.go
  internal/tenant/http.go
  internal/tenant/http_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#63925 feat/enterpriseportal: use database for reading Cody Gateway access
  cmd/enterprise-portal/internal/codyaccessservice/BUILD.bazel
  cmd/enterprise-portal/internal/codyaccessservice/adapters.go
  cmd/enterprise-portal/internal/codyaccessservice/adapters_test.go
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/codyaccessservice/v1_store.go
  cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
  cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
  cmd/enterprise-portal/internal/database/database.go
  cmd/enterprise-portal/internal/database/databasetest/BUILD.bazel
  cmd/enterprise-portal/internal/database/databasetest/databasetest.go
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/dotcomdb/BUILD.bazel
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
  cmd/enterprise-portal/service/service.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql.go
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
Labels: cla-signed

#64370 Fix Cody Web CSS
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
Labels: cla-signed, backport 5.6.x

#64374 Doc and README update: Replace all usages of GH discussions with the SG community link.
  client/vscode/CONTRIBUTING.md
  client/vscode/README.md
  client/vscode/src/common/links.ts
  doc/dev/background-information/sg/index.md
  doc/dev/background-information/sg/vision.md
  doc/dev/how-to/add_logging.md
  doc/index.md
  internal/cmd/tracking-issue/testdata/fixtures.json
Labels: cla-signed

#63926 feat/enterpriseportal: implement UpdateCodyGatewayAccess
  cmd/enterprise-portal/internal/codyaccessservice/BUILD.bazel
  cmd/enterprise-portal/internal/codyaccessservice/mocks_test.go
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/codyaccessservice/v1_store.go
  cmd/enterprise-portal/internal/codyaccessservice/v1_test.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  dev/BUILD.bazel
  mockgen.test.yaml
Labels: cla-signed

#64376 fix/enterpriseportal/codyaccess: allow removing rate limit overrides
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/codyaccessservice/v1_test.go
  cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
  cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/database/types.go
Labels: cla-signed

#64090 feat/dotcom: UI tracks Cody Gateway access directly in Enterprise Portal
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyGatewayRateLimitModal.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/backend.ts
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/enterpriseportal.ts
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/utils.ts
  cmd/enterprise-portal/internal/database/importer/BUILD.bazel
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/dotcomdb/BUILD.bazel
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
Labels: cla-signed

#64365 build(bazel): upgrade to latest aspect bazel-lib and rules_js rules
  WORKSPACE
Labels: cla-signed

#64345 Remove old Cody Web completely
  client/shared/src/settings/settings.tsx
  client/web/BUILD.bazel
  client/web/src/cody/chat/CodyChatPage.module.scss
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
  client/web/src/cody/chat/old-chat/CodyChatPage.module.scss
  client/web/src/cody/chat/old-chat/CodyChatPage.tsx
  client/web/src/cody/codyRoutes.tsx
  client/web/src/cody/components/ChatUI.module.scss
  client/web/src/cody/components/ChatUI/ChatUi.module.scss
  client/web/src/cody/components/ChatUI/ChatUi.tsx
  client/web/src/cody/components/ChatUI/index.tsx
  client/web/src/cody/components/ChatUi.tsx
  client/web/src/cody/components/GettingStarted.module.scss
  client/web/src/cody/components/GettingStarted.tsx
  client/web/src/cody/components/HistoryList/HistoryList.module.scss
  client/web/src/cody/components/HistoryList/HistoryList.tsx
  client/web/src/cody/components/HistoryList/index.tsx
  client/web/src/cody/components/ScopeSelector/Callout.module.scss
  client/web/src/cody/components/ScopeSelector/Callout.tsx
  client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
  client/web/src/cody/components/ScopeSelector/ScopeSelector.module.scss
  client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
  client/web/src/cody/components/ScopeSelector/backend.ts
  client/web/src/cody/components/ScopeSelector/index.tsx
  client/web/src/cody/components/ScopeSelector/useRepoSuggestions.ts
  client/web/src/cody/sidebar/CodySidebar.module.scss
  client/web/src/cody/sidebar/CodySidebar.tsx
  client/web/src/cody/sidebar/CodySidebarWebChat.tsx
  client/web/src/cody/sidebar/Provider.tsx
  client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
  client/web/src/cody/sidebar/old-cody-sidebar/CodySidebar.module.scss
  client/web/src/cody/sidebar/old-cody-sidebar/CodySidebar.tsx
  client/web/src/cody/widgets/CodyRecipesWidget.tsx
  client/web/src/cody/widgets/components/Recipe.tsx
  client/web/src/cody/widgets/components/RecipeAction.tsx
  client/web/src/cody/widgets/components/Recipes.module.scss
  client/web/src/cody/widgets/components/Recipes.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/tooltips/CodyTooltip.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#64369 Search: avoid phrase boost for non-text searches
  internal/search/query/BUILD.bazel
  internal/search/query/transformer.go
  internal/search/query/transformer_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64380 Search: update Zoekt for telemetry improvement
  deps.bzl
  go.mod
  go.sum
Labels: team/search-platform, cla-signed, team/product-platform

#64379 tenant: update test to enforce tenant
  internal/diskcache/cache_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#64361 db: Don't lose context when marking savepoints as done
  internal/database/basestore/handle.go
Labels: cla-signed, team/source, team/product-platform

#64323 tenant: Introduce tenant_id to every table
  dev/backcompat/flakes.json
  internal/database/schema.codeinsights.json
  internal/database/schema.codeinsights.md
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  internal/database/schema.json
  internal/database/schema.md
  internal/insights/store/dashboard_store.go
  migrations/codeinsights/1723127349_add_tenant_id_to_most_tables/down.sql
  migrations/codeinsights/1723127349_add_tenant_id_to_most_tables/metadata.yaml
  migrations/codeinsights/1723127349_add_tenant_id_to_most_tables/up.sql
  migrations/codeinsights/squashed.sql
  migrations/codeintel/1723127341_add_tenant_id_to_most_tables/down.sql
  migrations/codeintel/1723127341_add_tenant_id_to_most_tables/metadata.yaml
  migrations/codeintel/1723127341_add_tenant_id_to_most_tables/up.sql
  migrations/codeintel/squashed.sql
  migrations/frontend/1723016879_add_tenant_id_to_most_tables/down.sql
  migrations/frontend/1723016879_add_tenant_id_to_most_tables/metadata.yaml
  migrations/frontend/1723016879_add_tenant_id_to_most_tables/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/source, team/product-platform

#64239 feat/API: add publicly available `/api/v1/chat/completions` REST endpoint
  cmd/frontend/internal/cli/BUILD.bazel
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/handlerutil/handler.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/modelconfig/service.go
  cmd/frontend/internal/publicrestapi/BUILD.bazel
  cmd/frontend/internal/publicrestapi/chat_completions_handler.go
  cmd/frontend/internal/publicrestapi/chat_completions_handler_test.go
  cmd/frontend/internal/publicrestapi/chat_completions_models.go
  cmd/frontend/internal/publicrestapi/chat_completions_models_test.go
  cmd/frontend/internal/publicrestapi/golly-recordings/TestChatCompletionsHandler.recording.yaml
  cmd/frontend/internal/publicrestapi/httpapi.go
  cmd/frontend/internal/publicrestapi/utils_test.go
  dev/export-http-recording-tokens.sh
  internal/golly/BUILD.bazel
  internal/golly/doc.go
  internal/golly/env_variables.go
  internal/golly/golly.go
  internal/golly/recording.go
  internal/golly/testing_credentials.go
Labels: cla-signed

#64382 chore(local): fix outdated frontend target being used
  sg.config.yaml
Labels: cla-signed, no-changelog

#64383 Use correct DSN for schema validation in syntactic worker
  cmd/syntactic-code-intel-worker/shared/shared.go
Labels: cla-signed

#64385 Redis: always use pointer receiver in keyvalue
  internal/redispool/keyvalue.go
Labels: team/search-platform, cla-signed, team/product-platform

#64364 build(bazel): upgrade to rules_oci 2.0.0-beta2
  WORKSPACE
Labels: cla-signed

#64386 Revert "tenant: Introduce tenant_id to every table (#64323)"
  dev/backcompat/flakes.json
  internal/database/schema.codeinsights.json
  internal/database/schema.codeinsights.md
  internal/database/schema.codeintel.json
  internal/database/schema.codeintel.md
  internal/database/schema.json
  internal/database/schema.md
  internal/insights/store/dashboard_store.go
  migrations/codeinsights/1723127349_add_tenant_id_to_most_tables/down.sql
  migrations/codeinsights/1723127349_add_tenant_id_to_most_tables/metadata.yaml
  migrations/codeinsights/1723127349_add_tenant_id_to_most_tables/up.sql
  migrations/codeinsights/squashed.sql
  migrations/codeintel/1723127341_add_tenant_id_to_most_tables/down.sql
  migrations/codeintel/1723127341_add_tenant_id_to_most_tables/metadata.yaml
  migrations/codeintel/1723127341_add_tenant_id_to_most_tables/up.sql
  migrations/codeintel/squashed.sql
  migrations/frontend/1723016879_add_tenant_id_to_most_tables/down.sql
  migrations/frontend/1723016879_add_tenant_id_to_most_tables/metadata.yaml
  migrations/frontend/1723016879_add_tenant_id_to_most_tables/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/source, team/product-platform

#64387 chore(ci): bump the tag on which backcompat operates
  dev/backcompat/bazel-backcompat.sh
  dev/backcompat/flakes.json
Labels: cla-signed, no-changelog

#64317 feat/enterpriseportal: license expiry checker
  cmd/enterprise-portal/internal/database/codyaccess/BUILD.bazel
  cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
  cmd/enterprise-portal/internal/database/importer/BUILD.bazel
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
  cmd/enterprise-portal/internal/database/subscriptions/license_conditions.go
  cmd/enterprise-portal/internal/database/subscriptions/licenses.go
  cmd/enterprise-portal/internal/database/subscriptions/licenses_test.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions_conditions.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
  cmd/enterprise-portal/internal/database/utctime/BUILD.bazel
  cmd/enterprise-portal/internal/database/utctime/utctime.go
  cmd/enterprise-portal/internal/routines/licenseexpiration/BUILD.bazel
  cmd/enterprise-portal/internal/routines/licenseexpiration/licenseexpiration.go
  cmd/enterprise-portal/internal/routines/licenseexpiration/licenseexpiration_test.go
  cmd/enterprise-portal/internal/routines/licenseexpiration/mocks_test.go
  cmd/enterprise-portal/internal/routines/licenseexpiration/store.go
  cmd/enterprise-portal/service/BUILD.bazel
  cmd/enterprise-portal/service/config.go
  cmd/enterprise-portal/service/service.go
  dev/BUILD.bazel
  mockgen.test.yaml
Labels: cla-signed

#64087 chore/enterpriseportal: make sf_opp_id license-level
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
  cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.proto
Labels: cla-signed

#63927 feat/enterpriseportal: existing subscriptions read APIs use enterprise portal DB
  cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
  cmd/enterprise-portal/internal/database/importer/importer.go
  cmd/enterprise-portal/internal/database/subscriptions/licenses.go
  cmd/enterprise-portal/internal/database/subscriptions/licenses_test.go
  cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
  cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
  cmd/enterprise-portal/internal/subscriptionsservice/mocks_test.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1_store.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go
  cmd/enterprise-portal/service/service.go
Labels: cla-signed

#64381 fix(cody): filter out deprecated models
  cmd/frontend/internal/modelconfig/builder.go
  cmd/frontend/internal/modelconfig/builder_test.go
Labels: cla-signed

#64114 feat/enterpriseportal: more list options for subscriptions and licenses
  cmd/enterprise-portal/internal/database/subscriptions/licenses.go
  cmd/enterprise-portal/internal/database/subscriptions/licenses_test.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
  cmd/enterprise-portal/internal/routines/licenseexpiration/store.go
  cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.proto
Labels: cla-signed
