Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-02, with the labels that each got.

#60029 release: activate 5.3 release
  dev/release/release-config.jsonc
Labels: cla-signed

#60030 lib/msp: implement OTEL_SDK_DISABLED
  lib/managedservicesplatform/runtime/contract.go
  lib/managedservicesplatform/runtime/internal/opentelemetry/opentelemetry.go
Labels: cla-signed

#60034 msp/monitoring: only use Opsgenie for critical alerts, make external_health_check the only critical alert
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/stacks/monitoring/cloudsql.go
  dev/managedservicesplatform/stacks/monitoring/common.go
  dev/managedservicesplatform/stacks/monitoring/job.go
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
  dev/managedservicesplatform/stacks/monitoring/redis.go
  dev/managedservicesplatform/stacks/monitoring/response_codes.go
  dev/managedservicesplatform/stacks/monitoring/service.go
Labels: cla-signed

#60036 oidc: add prompt login option
  cmd/frontend/internal/auth/openidconnect/middleware.go
Labels: cla-signed

#59978 Move GItHub App creation routes to HTTP API
  client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
  client/web/src/components/gitHubApps/GitHubAppPage.tsx
  cmd/frontend/internal/app/app.go
  cmd/frontend/internal/app/router/router.go
  cmd/frontend/internal/app/ui/BUILD.bazel
  cmd/frontend/internal/app/ui/router.go
  cmd/frontend/internal/auth/BUILD.bazel
  cmd/frontend/internal/auth/githubappauth/middleware.go
  cmd/frontend/internal/auth/init.go
  cmd/frontend/internal/batches/resolvers/BUILD.bazel
  cmd/frontend/internal/batches/resolvers/code_host.go
  cmd/frontend/internal/batches/resolvers/main_test.go
  cmd/frontend/internal/cli/http.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/githubapp/BUILD.bazel
  cmd/frontend/internal/githubapp/httpapi.go
  cmd/frontend/internal/githubapp/httpapi_test.go
  cmd/frontend/internal/githubapp/init.go
  cmd/frontend/internal/githubapp/resolver.go
  cmd/frontend/internal/githubapp/resolver_test.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/shared/BUILD.bazel
  cmd/frontend/shared/shared.go
Labels: cla-signed, team/source

#60044 search: up display limit to 1500
  client/shared/src/search/stream.ts
Labels: cla-signed

#59944 Enterprise attribution client refreshes on site config changes
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/cody_gateway_rate_limit.go
  cmd/frontend/graphqlbackend/guardrails_test.go
  cmd/frontend/internal/guardrails/attribution/attribution.go
  cmd/frontend/internal/guardrails/init.go
  cmd/frontend/internal/guardrails/resolvers/resolver.go
  internal/codygateway/client.go
  internal/conf/client.go
  internal/conf/computed.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#60043 Fix Cody subscription ends at display logic in UI
  client/web/src/cody/management/CodyManagementPage.tsx
Labels: cla-signed

#60022 Keyword search: add feedback modal
  client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.module.scss
  client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx
Labels: cla-signed

#60037 highlighter: Simplify OffsetManager::new a bit
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
Labels: cla-signed

#60038 highlighter: Rename PackedRange -> Range
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/evaluate.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/range.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshot.rs
Labels: cla-signed

#59770 licensing: implement cody landing page
  client/shared/src/components/UserAvatar.tsx
  client/web/BUILD.bazel
  client/web/src/cody/components/CodyLogo.tsx
  client/web/src/cody/upsell/ChatBrandIcon.tsx
  client/web/src/cody/upsell/CodyUpsellPage.module.scss
  client/web/src/cody/upsell/CodyUpsellPage.tsx
  client/web/src/cody/upsell/CompletionsBrandIcon.tsx
  client/web/src/cody/upsell/ContextDiagram.tsx
  client/web/src/cody/upsell/ContextExample.tsx
  client/web/src/cody/upsell/IntelliJ.tsx
  client/web/src/cody/upsell/MultilineCompletion.tsx
  client/web/src/cody/upsell/vs-code.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
  client/web/src/routes.tsx
Labels: cla-signed, backport 5.3

#60054 svelte: Make compatible with keyword search; remove structural and smart search buttons
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web-sveltekit/src/lib/search/input/SmartSearchToggleButton.svelte
  client/web-sveltekit/src/lib/search/state.ts
  client/web-sveltekit/src/lib/web.ts
  client/web-sveltekit/src/routes/search/+page.ts
  client/web-sveltekit/src/routes/search/SearchResults.svelte
Labels: cla-signed, code-search

#59936 gitserver: Fixup and improve error handling
  cmd/gitserver/internal/search.go
  cmd/gitserver/internal/server_grpc.go
  internal/gitserver/BUILD.bazel
  internal/gitserver/addrs.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/errwrap.go
Labels: cla-signed, team/source

#60041 msp/monitoring: add pending requests alert
  dev/managedservicesplatform/stacks/monitoring/service.go
Labels: cla-signed

#60060 msp/monitoring: make alertpolicy subjects consistent
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
Labels: cla-signed

#60070 Allow sg wolfi image opentelemetry-collector to work
  dev/sg/internal/wolfi/base-image.go
Labels: cla-signed

#60042 msp/monitoring: add CloudSQL connections alert, prefix all
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/stacks/monitoring/cloudsql.go
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
Labels: cla-signed

#60082 Test for jansson shared library rather than .la file
  cmd/symbols/image_test.yaml
  docker-images/search-indexer/image_test.yaml
Labels: cla-signed

#58701 Auto-update Wolfi base images to latest
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, wolfi-auto-update

#60040 msp/monitoring: alert on Cloud Run status logs indicating service failure
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
  dev/managedservicesplatform/internal/resource/logcountmetric/BUILD.bazel
  dev/managedservicesplatform/internal/resource/logcountmetric/logcountmetric.go
  dev/managedservicesplatform/stacks/monitoring/BUILD.bazel
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
  dev/managedservicesplatform/stacks/monitoring/service.go
Labels: cla-signed

#60027 sg: remove repo root detection and improve help messages
  dev/sg/sg_bazel.go
Labels: sg, cla-signed, bazel

#60086 all: use stdlib slices package
  cmd/cody-gateway/internal/actor/productsubscription/BUILD.bazel
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
  cmd/frontend/internal/authz/resolvers/BUILD.bazel
  cmd/frontend/internal/authz/resolvers/resolver.go
  cmd/frontend/internal/executorqueue/handler/BUILD.bazel
  cmd/frontend/internal/executorqueue/handler/multihandler.go
  cmd/gitserver/internal/vcssyncer/BUILD.bazel
  cmd/gitserver/internal/vcssyncer/packages_syncer_test.go
  cmd/worker/internal/auth/BUILD.bazel
  cmd/worker/internal/auth/sourcegraph_operator_cleaner_test.go
  cmd/worker/internal/permissions/BUILD.bazel
  cmd/worker/internal/permissions/bitbucket_projects_test.go
  dev/managedservicesplatform/internal/imageupdater/BUILD.bazel
  dev/managedservicesplatform/internal/imageupdater/imageupdater.go
  dev/managedservicesplatform/stacks/cloudrun/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
  dev/sg/BUILD.bazel
  dev/sg/sg_bazel.go
  internal/authz/providers/github/BUILD.bazel
  internal/authz/providers/github/github_test.go
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/service.go
  internal/codeintel/dependencies/internal/store/BUILD.bazel
  internal/codeintel/dependencies/internal/store/store.go
  internal/database/BUILD.bazel
  internal/database/authz_test.go
  internal/database/perms_store_test.go
  internal/gitserver/BUILD.bazel
  internal/gitserver/addrs.go
  internal/licensing/BUILD.bazel
  internal/licensing/codygateway.go
  internal/licensing/telemetryexport.go
  internal/oobmigration/BUILD.bazel
  internal/oobmigration/store.go
  internal/search/backend/BUILD.bazel
  internal/search/backend/index_options.go
  internal/search/exhaustive/service/BUILD.bazel
  internal/search/exhaustive/service/searcher_test.go
  internal/search/job/jobutil/BUILD.bazel
  internal/search/job/jobutil/filter_file_contains.go
  internal/search/job/jobutil/job_test.go
  internal/search/query/repo_revs.go
  internal/search/repos/BUILD.bazel
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  internal/search/result/match.go
  internal/search/result/range.go
  internal/search/streaming/client/BUILD.bazel
  internal/search/streaming/client/progress.go
  internal/search/zoekt/BUILD.bazel
  internal/search/zoekt/query_test.go
Labels: cla-signed

#60087 Update migrator schemas to 5.2.7
  tools/release/schema_deps.bzl
Labels: cla-signed

#59907 cody web: do not include ignored files in context
  CHANGELOG.md
  client/web/BUILD.bazel
  client/web/src/cody/components/ChatUI/ChatUi.tsx
  client/web/src/cody/components/ChatUI/useIsFileIgnored.ts
  client/web/src/cody/components/GettingStarted.tsx
  client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#60093 gomod: update zoekt to fix several CVEs in dependencies
  deps.bzl
  dev/zoekt/update
  go.mod
  go.sum
Labels: cla-signed, backport 5.3

#60067 Search jobs: support boolean patterns
  internal/search/job/jobutil/exhaustive_job.go
  internal/search/job/jobutil/exhaustive_job_test.go
Labels: cla-signed

#60033 licensing: implement code search landing page
  client/web/BUILD.bazel
  client/web/src/routes.tsx
  client/web/src/search/upsell/CodeSearchIcon.tsx
  client/web/src/search/upsell/Feature.tsx
  client/web/src/search/upsell/IntegrationsIcon.tsx
  client/web/src/search/upsell/SearchExample.tsx
  client/web/src/search/upsell/SearchUpsellPage.module.scss
  client/web/src/search/upsell/SearchUpsellPage.tsx
Labels: cla-signed, backport 5.3

#60028 Search filters: do not select a type by default
  client/branded/BUILD.bazel
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.module.scss
  client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
  client/branded/src/search-ui/results/filters/types.ts
  client/shared/src/search/stream.ts
  cmd/frontend/graphqlbackend/search_results_test.go
  cmd/frontend/graphqlbackend/site_test.go
  internal/search/streaming/filters.go
  internal/search/streaming/search_filters.go
  internal/search/streaming/search_filters_test.go
Labels: cla-signed, backport 5.3

#60074 Add resourcedetectionprocessor to OTEL
  docker-images/opentelemetry-collector/builder.template.yaml
  wolfi-packages/opentelemetry-collector.yaml
  wolfi-packages/opentelemetry-collector/builder.template.yaml
Labels: cla-signed

#60106 Cody context: handle empty queries
  internal/search/codycontext/job.go
  internal/search/codycontext/query_transformer.go
  internal/search/codycontext/query_transformer_test.go
  internal/search/job/jobutil/job.go
Labels: cla-signed, backport 5.3

#60089 repo: Add back link to commits page
  client/web/src/repo/tree/TreePage.tsx
Labels: cla-signed, code-search

#60075 Correct discrepancy between "subscription end" and "trial end" on Cody Management Page
  client/web/src/cody/management/CodyManagementPage.tsx
Labels: cla-signed

#60104 licensing: cleanup logic for conditonally mounting route
  client/web/src/LegacyRouteContext.tsx
  client/web/src/LegacySourcegraphWebApp.tsx
  client/web/src/components/legacyLayoutRouteContext.mock.ts
  client/web/src/routes.tsx
  client/web/src/search/upsell/SearchUpsellPage.tsx
Labels: cla-signed, backport 5.3

#60111 search input: Add background color to operators/keywords
  client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
  client/wildcard/src/global-styles/colors.scss
Labels: cla-signed

#60065 auth: be fully compatible with our creative redirect params
  cmd/frontend/internal/auth/oauth/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
Labels: cla-signed

#60120 licensing: ignore redirect check on dotcom
  cmd/frontend/internal/app/ui/handlers.go
Labels: cla-signed

#60122 fix: Use repoId instead of array for rockskip_symbols delete
  internal/rockskip/postgres.go
Labels: cla-signed

#60123 licensing-ui: cody Icon should not be colored until active
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
Labels: cla-signed, backport 5.3

#60073 Search results design tweaks
  client/branded/BUILD.bazel
  client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
  client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/components/filter-skeleton/SearchFilterSkeleton.module.scss
  client/branded/src/search-ui/results/filters/components/filter-skeleton/SearchFilterSkeleton.tsx
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.tsx
  client/branded/src/search-ui/results/filters/types.ts
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
Labels: cla-signed, backport 5.3

#60115 Symbol search: fix panic on empty query
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
Labels: cla-signed, backport 5.3

#60084 ctags: ensure that binary has correct featureset
  cmd/symbols/image_test.yaml
  docker-images/search-indexer/image_test.yaml
Labels: cla-signed

#60039 highlighter: De-couple server code from highlighting
  docker-images/syntax-highlighter/BUILD.bazel
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/syntax-analysis/Cargo.toml
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_html.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/src/bin/scip-dump-response.rs
  docker-images/syntax-highlighter/src/lib.rs
  docker-images/syntax-highlighter/src/main.rs
Labels: cla-signed

#60130 gomod: update or vendor buildkit, docker, hostmatcher and saml to resolve CVEs
  WORKSPACE
  cmd/blobstore/internal/blobstore/blobstore_test.go
  deps.bzl
  go.mod
  go.sum
  internal/hostmatcher/BUILD.bazel
  internal/hostmatcher/LICENSE
  internal/hostmatcher/README.md
  internal/hostmatcher/hostmatcher.go
  internal/hostmatcher/hostmatcher_test.go
  internal/hostmatcher/http.go
  internal/httpcli/BUILD.bazel
  internal/httpcli/client.go
  internal/uploadstore/s3_client.go
  internal/webhooks/outbound/BUILD.bazel
  internal/webhooks/outbound/outbound.go
Labels: cla-signed, backport 5.3

#60077 highlighter: Rename scip-treesitter-cli -> scip-syntax
  WORKSPACE
  cmd/syntactic-code-intel-worker/BUILD.bazel
  cmd/syntactic-code-intel-worker/image_test.yaml
  cmd/syntactic-code-intel-worker/shared/config.go
  cmd/syntactic-code-intel-worker/shared/shared.go
  dev/check/shellcheck.sh
  dev/scip-syntax-dev
  dev/scip-syntax-install.sh
  dev/scip-treesitter-dev
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/README.md
  docker-images/syntax-highlighter/crates/scip-syntax/.gitignore
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/README.md
  docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/progress.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/globals.java
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/.gitignore
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/build.gradle
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/gradle/wrapper/gradle-wrapper.jar
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/gradle/wrapper/gradle-wrapper.properties
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/gradlew
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/gradlew.bat
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/index.scip
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/src/main/java/Main.java
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/src/main/java/TodoList.java
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/scip-index.sh
  docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__globals.java.snap
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_evaluation.snap
  sg.config.yaml
Labels: cla-signed

#60078 Fix `sg rfc search` 403 failures
  dev/sg/internal/rfc/rfc.go
Labels: cla-signed

#60051 Implement new UI for generating 5.3 licenses
  client/web/src/enterprise/productSubscription/ProductLicenseTags.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminCreateProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.module.scss
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminLicenseKeyLookupPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicenseNode.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminGenerateProductLicenseForSubscriptionForm.test.tsx.snap
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminProductLicenseNode.test.tsx.snap
Labels: cla-signed

#60035 Build and push candidate images in parallel
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/pipeline.go
Labels: cla-signed

#60031 Updated pre-commit regex for new token format
  dev/check-tokens.sh
Labels: cla-signed

#60047 search: default keyword search to on
  client/web/src/featureFlags/useFeatureFlag.ts
  client/web/src/integration/search.test.ts
  client/web/src/stores/navbarSearchQueryState.test.ts
  client/web/src/util/settings.ts
  schema/settings.schema.json
Labels: cla-signed, backport 5.3

#60152 client: remove search-simple experiment
  client/shared/BUILD.bazel
  client/shared/src/search/searchSimple.test.ts
  client/shared/src/search/searchSimple.ts
  client/shared/src/search/stream.ts
  client/web/src/featureFlags/featureFlags.ts
Labels: cla-signed

#60164 Fixup tag of cody enterprise plan
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/plandata.ts
Labels: cla-signed, team/source

#60161 Uses Result over panics in scip evaluation
  docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
  docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
Labels: cla-signed

#60094 Update Azure OpenAI client
  deps.bzl
  go.mod
  go.sum
  internal/completions/client/azureopenai/openai.go
  internal/embeddings/embed/client/azureopenai/client.go
Labels: cla-signed, backport 5.3

#60165 codeintel: Downgrade queue size critical alert to warning
  doc/admin/observability/alerts.md
  monitoring/definitions/shared/codeintel.go
Labels: cla-signed

#60168 svelte: Escape repository name in repo search input
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
Labels: cla-signed, code-search, backport 5.3

#60117 Search filters: make repository singular
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
Labels: cla-signed, backport 5.3

#60146 codemirror: Fix text selection color in search input and blob
  client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
Labels: cla-signed

#60175 sg/msp: enable security audit logging for production projects
  dev/managedservicesplatform/stacks/project/project.go
Labels: cla-signed

#60113 Search filters: increase backend limits on dynamic filters
  cmd/frontend/internal/search/search.go
  internal/search/streaming/search_filters.go
Labels: cla-signed, backport 5.3

#60109 Search: remove search-phrase-boost feature flag
  internal/search/client/client.go
  internal/search/types.go
Labels: cla-signed

#60114 Search: increase default search limit
  cmd/frontend/internal/search/search.go
  cmd/frontend/internal/search/search_test.go
  internal/search/job/jobutil/job_test.go
  internal/search/limits/limits.go
  internal/search/smartsearch/smart_search_job_test.go
  internal/search/types_test.go
Labels: cla-signed, backport 5.3

#60066 Keyword search: support patterntype in other features
  client/shared/src/search/query/filters.ts
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts
  cmd/frontend/graphqlbackend/saved_searches.go
Labels: cla-signed, backport 5.3

#60178 licensing: Don't offer disabled deprecated plans
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
Labels: cla-signed, team/source

#59924 Add banner on old docs
  doc/_resources/assets/docsite.css
  doc/_resources/templates/root.html
Labels: docs, docs-ux, cla-signed, docs-issue

#60127 v2 telemetry: add v2 telemetry to src/api
  client/web/src/api/ApiConsole.tsx
  client/web/src/routes.tsx
Labels: cla-signed

#60134 Update wording once we start accepting payments
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
Labels: cla-signed

#60190 Update Access token defaults
  CHANGELOG.md
  cmd/frontend/graphqlbackend/access_tokens_test.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/database/access_tokens_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, backport 5.3

#59718 SG start bazel enhancements
  .bazel_fix_commands.json
  deps.bzl
  dev/bazel_configure_accept_changes.sh
  dev/sg/internal/run/BUILD.bazel
  dev/sg/internal/run/bazel_build.go
  dev/sg/internal/run/bazel_command.go
  dev/sg/internal/run/command.go
  dev/sg/internal/run/ibazel.go
  dev/sg/internal/run/installer.go
  dev/sg/internal/run/logger.go
  dev/sg/internal/run/prefix_suffix_saver.go
  dev/sg/internal/run/run.go
  dev/sg/internal/run/run_bazel.go
  dev/sg/internal/run/sgconfig_command.go
  dev/sg/sg_run.go
  dev/sg/sg_start.go
  dev/sg/sg_start_test.go
  dev/sg/sg_tests.go
  go.mod
  go.sum
  sg.config.yaml
Labels: cla-signed

#60179 Search results design tweaks (#60073)
  client/branded/BUILD.bazel
  client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
  client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/components/filter-skeleton/SearchFilterSkeleton.module.scss
  client/branded/src/search-ui/results/filters/components/filter-skeleton/SearchFilterSkeleton.tsx
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.tsx
  client/branded/src/search-ui/results/filters/types.ts
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
Labels: cla-signed, backports, backport/improvement, backported-to-5.3

#60085 dev: rename trace to Plan
  internal/search/client/client.go
Labels: cla-signed

#60169 search: Don't show drop shadow for when autofocused
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.module.scss
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
Labels: cla-signed, code-search

#60186 Gateway /v1/attribution allowed for BYOK customers
  cmd/cody-gateway/internal/actor/actor.go
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  cmd/cody-gateway/internal/auth/auth.go
  cmd/cody-gateway/internal/auth/auth_test.go
Labels: cla-signed

#60145 [dotcom] add refresh token endpoint with sams authenticator
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/auth.go
  cmd/frontend/internal/httpapi/httpapi.go
  cmd/frontend/internal/httpapi/ssc.go
  internal/cody/BUILD.bazel
  internal/cody/rate_limits.go
  internal/sams/BUILD.bazel
  internal/sams/auth.go
  internal/sams/client.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#60194 completions: fix HTTP double error-write bug
  internal/completions/httpapi/handler.go
Labels: cla-signed, backport/bugfix, backport 5.3

#60157 keyword search: implicit operators and parens as groups
  internal/search/query/parser.go
  internal/search/query/parser_test.go
  internal/search/query/query.go
  internal/search/query/testdata/TestConcat/#12.golden
  internal/search/query/testdata/TestConcat/#13.golden
  internal/search/query/transformer.go
Labels: cla-signed

#60188 cody: Improve error messages for isCodyEnabled
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/completions/resolvers/resolver.go
  cmd/frontend/internal/embeddings/resolvers/resolvers.go
  internal/cody/BUILD.bazel
  internal/cody/feature_flag.go
  internal/cody/feature_flag_test.go
  internal/codycontext/context.go
  internal/completions/httpapi/handler.go
Labels: cla-signed, team/source, backport/bugfix, backport 5.3

#60200 chore: Remove accidental debugging leftovers
  cmd/frontend/internal/httpapi/ssc.go
Labels: cla-signed

#60024 Filters Panel: Add reset all filters button
  client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
Labels: cla-signed

#60116 Search filters: add approximate count tooltip
  client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
Labels: cla-signed, backport 5.3

#60206 ci: do not push to prod on main-dry-run builds
  dev/ci/push_all.sh
Labels: cla-signed

#60210 Keyword Search: re-space keyword search cta
  client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.module.scss
Labels: cla-signed

#60211 tweet colors on search results
  client/web/src/nav/GlobalNavbar.module.scss
  client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
Labels: cla-signed

#60189 Keyword search: add 'beta' labels and fix URL parsing
  client/web/src/search/index.ts
  client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx
  client/web/src/stores/navbarSearchQueryState.test.ts
  client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.tsx
Labels: cla-signed

#60217 [Cody Manage] make ssc url configurable for testing
  client/web/BUILD.bazel
  client/web/src/cody/featureFlags.ts
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/featureFlags/featureFlags.ts
Labels: cla-signed

#59997 gitserver: introduce abstraction around p4 exec
  cmd/gitserver/internal/perforce/BUILD.bazel
  cmd/gitserver/internal/perforce/command.go
  cmd/gitserver/internal/perforce/command_test.go
Labels: cla-signed, team/source

#59998 gitsever: use NewBaseCommand utility in internal/perforce package
  cmd/gitserver/internal/p4exec.go
  cmd/gitserver/internal/patch.go
  cmd/gitserver/internal/perforce/BUILD.bazel
  cmd/gitserver/internal/perforce/changelist.go
  cmd/gitserver/internal/perforce/cloneable.go
  cmd/gitserver/internal/perforce/depots.go
  cmd/gitserver/internal/perforce/groups.go
  cmd/gitserver/internal/perforce/login.go
  cmd/gitserver/internal/perforce/protects.go
  cmd/gitserver/internal/perforce/users.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/vcssyncer/perforce.go
  cmd/gitserver/internal/vcssyncer/syncer.go
Labels: cla-signed, team/source

#60187 gitserver: perforce: refactor functions to use argument structs
  cmd/gitserver/internal/p4exec.go
  cmd/gitserver/internal/patch.go
  cmd/gitserver/internal/perforce/changelist.go
  cmd/gitserver/internal/perforce/cloneable.go
  cmd/gitserver/internal/perforce/depots.go
  cmd/gitserver/internal/perforce/groups.go
  cmd/gitserver/internal/perforce/login.go
  cmd/gitserver/internal/perforce/protects.go
  cmd/gitserver/internal/perforce/users.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/vcssyncer/perforce.go
Labels: cla-signed, team/source

#59999 gitserver: replace deprecated P4Exec command with stub unimplemented interface
  cmd/gitserver/internal/BUILD.bazel
  cmd/gitserver/internal/p4exec.go
  cmd/gitserver/internal/p4exec_test.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_grpc.go
Labels: cla-signed, team/source

#60001 gitserver: fix cmd/gitserver/internal/patch.go to use new perforce.NewBaseCommand utility
  cmd/gitserver/internal/patch.go
Labels: cla-signed, team/source

#60223 [Backport 5.3] Search: increase default search limit
  cmd/frontend/internal/search/search.go
  cmd/frontend/internal/search/search_test.go
  internal/search/job/jobutil/job_test.go
  internal/search/limits/limits.go
  internal/search/smartsearch/smart_search_job_test.go
  internal/search/types_test.go
Labels: cla-signed, backports, backport/improvement, backported-to-5.3

#60224 Keyword search: center beta badge
  client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx
  client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.tsx
Labels: cla-signed

#60006 cmd/gitserver/internal/vcssyncer/perforce.go: set P4CLIENTPATH environment variable for git p4 invocations
  cmd/gitserver/internal/vcssyncer/perforce.go
  cmd/gitserver/internal/vcssyncer/perforce_test.go
Labels: cla-signed, team/source

#60052 Drop Cody for GA from old plans
  internal/licensing/data.go
Labels: cla-signed, team/source, backport/customer-critical, backport 5.3

#60228 search: introduce max-line-len streaming parameter
  client/branded/src/search-ui/components/FileContentSearchResult.tsx
  client/shared/src/search/stream.ts
  client/web/src/search/results/StreamingSearchResults.test.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/export/searchResultsExport.ts
  cmd/frontend/internal/search/search.go
  internal/search/BUILD.bazel
  internal/search/exhaustive/service/matchjson.go
  internal/search/streaming/http/events.go
  internal/search/truncate.go
  internal/search/truncate_test.go
  internal/search/type_converters.go
Labels: cla-signed, backport 5.3

#60237 Update CHANGELOG.md to announce gRPC as the only internal comunication method
  CHANGELOG.md
Labels: cla-signed, team/source

#60128 Fixing Hubspot Form Proxy issue
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/marketing/components/HubSpotForm.tsx
Labels: cla-signed

#60240 [Cody Manage] remove revert to trial banner
  client/web/src/cody/management/CodyManagementPage.tsx
Labels: cla-signed

#60238 gitserver: Fix goroutine leak when reader is not drained
  cmd/gitserver/internal/git/gitcli/clibackend.go
  cmd/gitserver/internal/git/gitcli/odb.go
  cmd/gitserver/internal/git/gitcli/odb_test.go
Labels: cla-signed, team/source, backport/stability, backport 5.3

#60241 [Cody Manage] update redirection URLs
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/util/constants.ts
Labels: cla-signed

#60108 Fixup and improve Blame error handling
  client/web/src/repo/blame/useBlameHunks.ts
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/backend.ts
  cmd/frontend/graphqlbackend/git_blob.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/gitserver/internal/git/gitcli/blame.go
  cmd/gitserver/internal/git/gitcli/blame_test.go
  cmd/gitserver/internal/git/gitcli/odb.go
  cmd/gitserver/internal/git/iface.go
  cmd/gitserver/internal/git/mock.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_test.go
  internal/gitserver/BUILD.bazel
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: cla-signed, team/source, backport/bugfix, backport 5.3

#60254 Add default value for ssc.apiBaseURL
  internal/ssc/ssc.go
Labels: cla-signed

#60255 Hide free trial tile if cc added
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
Labels: cla-signed

#60173 changelog: cut sourcegraph@5.3.0
  CHANGELOG.md
Labels: cla-signed, backport 5.3

#60260 Update changelog after backport
  CHANGELOG.md
Labels: cla-signed, backport 5.3

#60097 Build our own grafana base image
  docker-images/grafana/BUILD.bazel
  docker-images/grafana/image_test.yaml
  wolfi-images/grafana.yaml
Labels: cla-signed

#60250 snippetAttribution responds with search lower bounds, and whether it ran at all
  cmd/frontend/graphqlbackend/guardrails.go
  cmd/frontend/graphqlbackend/guardrails.graphql
  cmd/frontend/internal/guardrails/resolvers/BUILD.bazel
  cmd/frontend/internal/guardrails/resolvers/resolver.go
  cmd/frontend/internal/guardrails/resolvers/resolver_test.go
  internal/guardrails/BUILD.bazel
  internal/guardrails/attribution_filter.go
  internal/guardrails/attribution_threshold.go
Labels: cla-signed, backport 5.3

#60204 code nav: Respect history.preferAbsoluteTimestamps user setting
  client/web/src/repo/RepoRevisionSidebarCommits.tsx
  client/web/src/repo/blob/panel/BlobPanel.tsx
  client/web/src/repo/commits/GitCommitNode.tsx
  client/web/src/repo/tree/TreePagePanels.module.scss
  client/web/src/repo/tree/TreePagePanels.tsx
Labels: cla-signed, code-search

#60263 Use internally-built grafana base image
  dev/oci_deps.bzl
Labels: cla-signed

#60247 sg doctor: add disk category to sg doctor
  sg.doctor.yaml
Labels: cla-signed

#60261 licensing: ui design tweaks
  client/web/BUILD.bazel
  client/web/src/cody/upsell/CodyUpsellPage.module.scss
  client/web/src/cody/upsell/CodyUpsellPage.tsx
  client/web/src/search/upsell/BatchChangesLogo.tsx
  client/web/src/search/upsell/CodeNavLogo.tsx
  client/web/src/search/upsell/Feature.tsx
  client/web/src/search/upsell/SearchUpsellPage.module.scss
  client/web/src/search/upsell/SearchUpsellPage.tsx
  client/web/src/storm/pages/SearchPage/CodyUpsell.module.scss
  client/web/src/storm/pages/SearchPage/CodyUpsell.tsx
  client/web/src/storm/pages/SearchPage/MultilineCompletion.tsx
  client/web/src/storm/pages/SearchPage/SearchPageContent.module.scss
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
  client/wildcard/src/global-styles/colors.scss
Labels: cla-signed, backport 5.3

#60205 code nav: Better truncation of revision names in revision selector
  client/web/src/repo/RepoRevisionContainer.module.scss
  client/web/src/repo/RepoRevisionContainer.tsx
Labels: cla-signed, code-search

#60271 Update SSC release feature flag name
  client/web/src/cody/featureFlags.ts
  client/web/src/featureFlags/featureFlags.ts
  internal/cody/subscription.go
Labels: cla-signed

#60274 sg ops: sanitize raw image values more
  dev/sg/internal/images/images_test.go
  dev/sg/internal/images/registry.go
Labels: cla-signed

#60275 Add inline styling in old docs banner
  doc/_resources/assets/docsite.css
  doc/_resources/templates/root.html
Labels: docs, cla-signed, docs-issue, bug-fix

#60280 Keyword search: add a changelog entry
  CHANGELOG.md
Labels: cla-signed, backport 5.3

#60277 licensing: hide ask cody button when cody feature isn't enabled
  client/web/src/repo/RepoContainer.tsx
Labels: backport 5.3

#60281 Docs: update `/help` redirect to point to new docs site
  cmd/frontend/internal/app/ui/help.go
  cmd/frontend/internal/app/ui/help_test.go
Labels: cla-signed, backport 5.3

#60285 Made all file watches in `sg start` recursive
  dev/sg/internal/run/sgconfig_command.go
  sg.config.yaml
Labels: cla-signed

#60290 Update PLG launch dates hard coded in frontend
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
Labels: cla-signed

#59780 executor: Add audit log mode
  cmd/executor/internal/config/config.go
  cmd/executor/internal/config/config_test.go
  cmd/executor/internal/run/util.go
  cmd/executor/internal/worker/BUILD.bazel
  cmd/executor/internal/worker/cmdlogger/logger.go
  cmd/executor/internal/worker/cmdlogger/logger_test.go
  cmd/executor/internal/worker/command/command.go
  cmd/executor/internal/worker/handler.go
  cmd/executor/internal/worker/worker.go
Labels: cla-signed, team/source

#60216 Search filters: visual updates
  client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
  client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx
Labels: cla-signed, backport 5.3

#60220 Search results: add a message for when the display limit is hit
  client/branded/src/search-ui/results/StreamingSearchResultsFooter.tsx
  cmd/frontend/internal/search/search_test.go
  internal/search/streaming/api/progress.go
Labels: cla-signed, backport 5.3

#60305 client: remove unread FEATURE_FLAGS
  client/web/src/featureFlags/featureFlags.ts
Labels: cla-signed

#60309 Set wolfi auto-update backport target branch to 5.3
  dev/ci/scripts/wolfi/update-base-image-hashes.sh
Labels: cla-signed, SSDLC

#60198 Unifies error handling between globals and locals detection
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/bin/scip-local-nav.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/bin/scip-perf.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/ctags.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
Labels: cla-signed

#60100 licensing: create dashboard page for Cody enterprise
  client/web/BUILD.bazel
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/dashboard/CodyDashboardPage.module.scss
  client/web/src/cody/dashboard/CodyDashboardPage.tsx
  client/web/src/cody/dashboard/UpsellImage.tsx
  client/web/src/routes.tsx
Labels: cla-signed, backport 5.3

#60301 code-search: handle mobile responsiveness for cody banner on search page
  client/web/src/search/home/SearchPage.tsx
  client/web/src/storm/pages/SearchPage/CodyUpsell.module.scss
  client/web/src/storm/pages/SearchPage/CodyUpsell.tsx
  client/web/src/storm/pages/SearchPage/SearchPage.tsx
  client/web/src/storm/pages/SearchPage/SearchPageContent.story.tsx
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
Labels: cla-signed, backport 5.3

#60314 [Backport 5.3] licensing: create dashboard page for Cody enterprise
  client/web/BUILD.bazel
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/dashboard/CodyDashboardPage.module.scss
  client/web/src/cody/dashboard/CodyDashboardPage.tsx
  client/web/src/cody/dashboard/UpsellImage.tsx
  client/web/src/routes.tsx
Labels: cla-signed, backport/improvement

#60302 Update Add CC Link
  client/web/src/cody/management/CodyManagementPage.tsx
Labels: cla-signed

#60321 sg: ensure sg expected output is sorted before compare
  dev/sg/sg_start_test.go
Labels: cla-signed

#60319 database: remove telemetry-export feature flag
  internal/database/telemetry_export_store.go
  internal/database/telemetry_export_store_test.go
Labels: cla-signed, backport 5.3

#60239 Search filters: update empty state for dynamic filter searches
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
Labels: cla-signed, backport 5.3

#60055 Syntactic indexing: add database schema and dbworker
  cmd/syntactic-code-intel-worker/shared/BUILD.bazel
  cmd/syntactic-code-intel-worker/shared/config.go
  cmd/syntactic-code-intel-worker/shared/indexing_worker.go
  cmd/syntactic-code-intel-worker/shared/shared.go
  cmd/syntactic-code-intel-worker/shared/store.go
  cmd/syntactic-code-intel-worker/shared/store_helpers_test.go
  cmd/syntactic-code-intel-worker/shared/store_test.go
  dev/scip-syntax-install.sh
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1706710430_add_syntactic_scip_indexes_table/down.sql
  migrations/frontend/1706710430_add_syntactic_scip_indexes_table/metadata.yaml
  migrations/frontend/1706710430_add_syntactic_scip_indexes_table/up.sql
  migrations/frontend/squashed.sql
  sg.config.yaml
Labels: cla-signed

#60286 Search Result: Fix search result padding problem
  client/branded/src/search-ui/components/ResultContainer.tsx
  client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
  client/web/src/search/results/components/aggregation/SearchAggregationResult.module.scss
  client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
Labels: cla-signed, backport 5.3

#60316 search: fix hoisting heuristic for nested queries
  internal/search/job/jobutil/job_test.go
  internal/search/query/parser.go
  internal/search/query/parser_test.go
  internal/search/query/testdata/TestConcat/#13.golden
  internal/search/query/testdata/TestParseKeywordPattern/parens_around_slash...slash.golden
  internal/search/query/testdata/TestParseStandard/parens_around_slash...slash.golden
  internal/search/query/transformer.go
Labels: cla-signed

#60307 svelte: Improve scroll behavior on repo pages
  client/web-sveltekit/src/app.html
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed, code-search

#60288 Search filters: final design tweaks
  client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
Labels: cla-signed, backport 5.3

#60339 auth: append random suffix when derive username from email
  cmd/frontend/auth/BUILD.bazel
  cmd/frontend/auth/auth.go
  cmd/frontend/auth/auth_test.go
  cmd/frontend/auth/user.go
  cmd/frontend/auth/user_test.go
  cmd/frontend/internal/auth/httpheader/BUILD.bazel
  cmd/frontend/internal/auth/httpheader/middleware_test.go
  internal/auth/userpasswd/handlers.go
  internal/scim/BUILD.bazel
  internal/scim/user.go
  internal/scim/user_create_test.go
Labels: cla-signed

#60347 Add external URL to pings
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  internal/updatecheck/client.go
  internal/updatecheck/handler.go
  internal/updatecheck/handler_test.go
Labels: cla-signed, backport 5.3

#60345 licensing: Rename new plans
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/plandata.ts
  internal/licensing/data.go
  internal/licensing/tags_test.go
Labels: cla-signed, team/source, backport/improvement, backport 5.3

#60350 Auto-update Wolfi base images to latest
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, wolfi-auto-update, backport 5.3

#60262 Autocomplete attribution requires site config setting but can be individually disabled with feature flag
  internal/completions/httpapi/handler.go
Labels: cla-signed, backport 5.3

#60344 Blob view: bandaid selection coloring
  client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
  client/web-sveltekit/src/lib/search/BaseQueryInput.svelte
  client/web/src/repo/blob/codemirror/codeintel/keybindings.ts
Labels: cla-signed, backport 5.3

#60352 licensing: Rename new plans (#60345)
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/plandata.ts
  internal/licensing/data.go
  internal/licensing/tags_test.go
Labels: cla-signed, backport/improvement, backported-to-5.3

#60356 aw: use two different jobs for e2e and normal testing
  .aspect/workflows/config.yaml
Labels: cla-signed

#60332 Add Llama Code 13b to all PLG users and remove unused model conversation
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/httpapi/codecompletion.go
Labels: cla-signed

#60362 Revert recent sg changes that cause high load and instability in dev
  .bazel_fix_commands.json
  deps.bzl
  dev/bazel_configure_accept_changes.sh
  dev/sg/internal/run/BUILD.bazel
  dev/sg/internal/run/bazel_build.go
  dev/sg/internal/run/bazel_command.go
  dev/sg/internal/run/command.go
  dev/sg/internal/run/ibazel.go
  dev/sg/internal/run/installer.go
  dev/sg/internal/run/logger.go
  dev/sg/internal/run/prefix_suffix_saver.go
  dev/sg/internal/run/run.go
  dev/sg/internal/run/run_bazel.go
  dev/sg/internal/run/sgconfig_command.go
  dev/sg/sg_run.go
  dev/sg/sg_start.go
  dev/sg/sg_start_test.go
  dev/sg/sg_tests.go
  go.mod
  go.sum
  sg.config.yaml
Labels: cla-signed, team/source

#60199 Remove code for rewriting st models
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/shared/config/config.go
Labels: cla-signed

#60358 mig: fix out-of-date-detection
  internal/database/migration/cliutil/util.go
Labels: cla-signed
