Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-03, with the labels that each got.

#60382 v2 telemetry: add v2 telemetry to all monaco editors
  client/web/src/components/externalServices/AddExternalServicePage.tsx
  client/web/src/components/externalServices/AddExternalServicesPage.story.tsx
  client/web/src/components/externalServices/AddExternalServicesPage.tsx
  client/web/src/components/externalServices/ExternalServiceEditPage.story.tsx
  client/web/src/components/externalServices/ExternalServiceEditPage.tsx
  client/web/src/components/externalServices/ExternalServiceForm.test.tsx
  client/web/src/components/externalServices/ExternalServiceForm.tsx
  client/web/src/components/externalServices/ExternalServicePage.story.tsx
  client/web/src/components/externalServices/ExternalServicePage.tsx
  client/web/src/components/externalServices/ExternalServicesPage.story.tsx
  client/web/src/components/externalServices/ExternalServicesPage.tsx
  client/web/src/enterprise/codeintel/configuration/components/ConfigurationEditor.tsx
  client/web/src/enterprise/codeintel/configuration/components/inference-script/InferenceScriptEditor.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelInferenceConfigurationPage.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelRepositoryIndexConfigurationPage.tsx
  client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx
  client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.tsx
  client/web/src/enterprise/searchContexts/SearchContextRepositoriesFormArea.tsx
  client/web/src/routes.tsx
  client/web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
  client/web/src/settings/MonacoSettingsEditor.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/RemoteRepositoriesStep.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/CodeHostCreation.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/CodeHostEdit.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/common/CodeHostConnection.tsx
  client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubConnectView.tsx
  client/web/src/site-admin/SiteAdminArea.tsx
  client/web/src/site-admin/SiteAdminConfigurationPage.tsx
  client/web/src/site-admin/SiteAdminExternalServicesArea.tsx
  client/web/src/site-admin/SiteAdminReportBugPage.tsx
Labels: cla-signed

#60789 Add v2t to src/enterprise/codeintel
  client/web/src/enterprise/codeintel/admin/AdminCodeIntelArea.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPolicyPage.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelInferenceConfigurationPage.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelRepositoryIndexConfigurationPage.tsx
  client/web/src/enterprise/codeintel/dashboard/pages/GlobalDashboardPage.tsx
  client/web/src/enterprise/codeintel/dashboard/pages/RepoDashboardPage.tsx
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexPage.tsx
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
  client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
  client/web/src/enterprise/cody/repo/CodyRepoArea.tsx
  client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx
Labels: cla-signed

#60219 v2 telemetry: add v2 telemetry to src/codeintel
  client/branded/src/search-ui/components/CopyPathAction.tsx
  client/branded/src/search-ui/components/FileContentSearchResult.tsx
  client/branded/src/search-ui/components/FilePathSearchResult.tsx
  client/branded/src/search-ui/components/SymbolSearchResult.tsx
  client/web/src/codeintel/ReferencesPanel.mocks.ts
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/codeintel/SideBlob.tsx
  client/web/src/enterprise/own/RepositoryOwnEditPage.tsx
  client/web/src/enterprise/own/RepositoryOwnPage.tsx
  client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx
  client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.test.tsx
  client/web/src/repo/FilePathBreadcrumbs.tsx
  client/web/src/repo/RepoHeader.story.tsx
  client/web/src/repo/RepoRevisionContainer.tsx
  client/web/src/repo/RepoRevisionSidebar.tsx
  client/web/src/repo/RepoRevisionSidebarFileTree.tsx
  client/web/src/repo/RepositoryFileTreePage.tsx
  client/web/src/repo/actions/CopyPermalinkAction.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/actions/GoToRawAction.tsx
  client/web/src/repo/blob/own/FileOwnershipPanel.story.tsx
  client/web/src/repo/blob/own/FileOwnershipPanel.tsx
  client/web/src/repo/blob/panel/BlobPanel.tsx
  client/web/src/repo/commits/RepositoryCommitsPage.tsx
  client/web/src/repo/components/TryCodyWidget/TryCodyWidget.tsx
  client/web/src/repo/stats/RepositoryStatsArea.tsx
  client/web/src/repo/tree/TreePage.tsx
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
  client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
Labels: cla-signed

#60788 V2t src/enterprise code monitoring
  client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringGettingStarted.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.story.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.test.tsx
  client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.story.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.test.tsx
  client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
  client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.story.tsx
  client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.test.tsx
  client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.tsx
  client/web/src/enterprise/code-monitoring/global/GlobalCodeMonitoringArea.tsx
Labels: cla-signed

#60764 v2 telemetry: add v2 telemetry to src/components/fuzzyFinder
  client/web/src/LegacyLayout.tsx
  client/web/src/components/fuzzyFinder/FuzzyFinder.mocks.tsx
  client/web/src/components/fuzzyFinder/FuzzyFinder.tsx
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
  client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
Labels: cla-signed

#60765 v2t: add v2t to src/components/gitHubApps
  client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
  client/web/src/components/gitHubApps/GitHubAppPage.tsx
  client/web/src/components/gitHubApps/GitHubAppsPage.tsx
  client/web/src/enterprise/batches/settings/BatchChangesCreateGitHubAppPage.tsx
  client/web/src/site-admin/SiteAdminGitHubAppsArea.tsx
  client/web/src/site-admin/routes.tsx
Labels: cla-signed

#60737 Update cody ping payload
  internal/database/dbmocks/mocks_temp.go
  internal/database/event_logs.go
  internal/database/event_logs_test.go
  internal/types/types.go
  internal/updatecheck/client.go
  internal/updatecheck/handler.go
  internal/updatecheck/handler_test.go
  internal/usagestats/BUILD.bazel
  internal/usagestats/aggregated_cody.go
  internal/usagestats/aggregated_search.go
Labels: cla-signed

#60644 gitserver: Reduce logspam from expected errors
  cmd/gitserver/internal/git/observability.go
Labels: cla-signed, team/source

#60823 ci: Disable flaky 'highlights correct line for Go' test
  client/web/src/end-to-end/code-intel/repository-component.test.ts
Labels: cla-signed

#60826 frontend: GetAggregatedCodyStats: add nil guard for events
  internal/usagestats/aggregated_cody.go
Labels: cla-signed, team/source

#60829 ci: Disable typescript symbol sidebar test
  client/web/src/end-to-end/code-intel/repository-component.test.ts
Labels: cla-signed

#60804 Remove accidentally committed file
  docsite_run.sh
Labels: cla-signed, team/source

#60437 grpc: Use native gRPC serve handler in repo-updater
  cmd/repo-updater/internal/repoupdater/BUILD.bazel
  cmd/repo-updater/internal/repoupdater/observability.go
  cmd/repo-updater/internal/repoupdater/server.go
  cmd/repo-updater/shared/BUILD.bazel
  cmd/repo-updater/shared/main.go
  internal/grpc/grpcserver/BUILD.bazel
  internal/grpc/grpcserver/grpcserver.go
Labels: cla-signed, team/source

#60588 conf: Allow a local stub file
  internal/conf/conf.go
Labels: cla-signed, team/source

#60330 packages: Temporarily disable failing for invalid versions on dotcom
  cmd/gitserver/internal/vcssyncer/BUILD.bazel
  cmd/gitserver/internal/vcssyncer/packages_syncer.go
Labels: cla-signed, team/source

#60298 gitserver: Improve error reporting for context deadlines for clones and updates
  cmd/gitserver/internal/ensurerevision.go
  cmd/gitserver/internal/mocks_test.go
  cmd/gitserver/internal/repo_info_test.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_test.go
Labels: cla-signed, team/source

#60839 vcssyncer: fix dotcommode check
  cmd/gitserver/internal/vcssyncer/BUILD.bazel
  cmd/gitserver/internal/vcssyncer/packages_syncer.go
Labels: cla-signed

#60583 gitserver: Populate last_changed and last_fetched fields for clone
  cmd/gitserver/internal/server.go
Labels: cla-signed, team/source

#60834 Search: skip context lines when converting to line matches
  internal/search/result/file.go
  internal/search/result/file_test.go
Labels: cla-signed

#60840 tracer/exporters: use internalerrs loggers on OTEL gRPC exporter
  internal/tracer/oteldefaults/exporters/BUILD.bazel
  internal/tracer/oteldefaults/exporters/otlp.go
Labels: cla-signed

#60819 syntax-highlighter: Add snapshot test for Groovy
  docker-images/syntax-highlighter/README.md
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__syntect_scip__test__groovy.groovy.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntect_files/groovy.groovy
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs
Labels: cla-signed

#60803 v2t: add v2t to src/enterprise/cody and src/enterprise/executors
  client/web/src/enterprise/cody/configuration/pages/CodyConfigurationPage.tsx
  client/web/src/enterprise/executors/ExecutorsSiteAdminArea.tsx
  client/web/src/enterprise/executors/ExecutorsUserArea.tsx
  client/web/src/enterprise/executors/instances/ExecutorsListPage.tsx
  client/web/src/enterprise/executors/secrets/ExecutorSecretsListPage.story.tsx
  client/web/src/enterprise/executors/secrets/ExecutorSecretsListPage.tsx
  client/web/src/org/settings/routes.tsx
  client/web/src/site-admin/routes.tsx
  client/web/src/user/settings/routes.tsx
Labels: cla-signed

#60842 dbconn/otelsql: run all string attributes through strings.ToValidUTF8
  internal/database/dbconn/dynamic_metadata.go
  internal/database/dbconn/open.go
Labels: cla-signed

#60768 v2t: add src/enterprise/batches
  client/web/src/enterprise/batches/BatchSpec.tsx
  client/web/src/enterprise/batches/BatchSpecNode.story.tsx
  client/web/src/enterprise/batches/BatchSpecNode.tsx
  client/web/src/enterprise/batches/BatchSpecsPage.story.tsx
  client/web/src/enterprise/batches/BatchSpecsPage.tsx
  client/web/src/enterprise/batches/batch-spec/edit/DownloadSpecModal.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/DownloadSpecModal.tsx
  client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx
  client/web/src/enterprise/batches/batch-spec/edit/RunBatchSpecButton.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/RunBatchSpecButton.tsx
  client/web/src/enterprise/batches/batch-spec/edit/library/LibraryPane.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/library/LibraryPane.tsx
  client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreview.story.tsx
  client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreview.tsx
  client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreviewPanel.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ActionsMenu.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ActionsMenu.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ReadOnlyBatchSpecForm.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ReadOnlyBatchSpecForm.tsx
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/ExecutionWorkspaces.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/ExecutionWorkspaces.tsx
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.story.tsx
  client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsActionSection.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx
  client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx
  client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.story.tsx
  client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
  client/web/src/enterprise/batches/detail/changesets/DetachChangesetsModal.story.tsx
  client/web/src/enterprise/batches/detail/changesets/DetachChangesetsModal.tsx
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.story.tsx
  client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
  client/web/src/enterprise/batches/list/GettingStarted.story.tsx
  client/web/src/enterprise/batches/list/GettingStarted.tsx
  client/web/src/enterprise/batches/list/NewBatchChangeButton.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewPage.tsx
  client/web/src/enterprise/batches/preview/BatchChangePreviewTabs.tsx
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.story.tsx
  client/web/src/enterprise/batches/preview/CreateUpdateBatchChangeAlert.tsx
  client/web/src/enterprise/batches/repo/BatchChangeRepoPage.story.tsx
  client/web/src/enterprise/batches/repo/BatchChangeRepoPage.tsx
  client/web/src/enterprise/batches/repo/RepoBatchChanges.tsx
  client/web/src/enterprise/batches/repo/RepositoryBatchChangesArea.tsx
  client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx
  client/web/src/org/area/routes.tsx
  client/web/src/routes.tsx
  client/web/src/site-admin/routes.tsx
  client/web/src/user/area/routes.tsx
Labels: cla-signed

#60798 soap cleaner: guard all delete ops on whether the set is non-empty
  cmd/worker/internal/auth/sourcegraph_operator_cleaner.go
  cmd/worker/internal/auth/sourcegraph_operator_cleaner_test.go
Labels: release-blocker, cla-signed, backport/bugfix, backport 5.3

#60832 svelte: Introduce new feature flag for incremental rollout of Svelte on S2
  client/web-sveltekit/src/lib/navigation.ts
  client/web-sveltekit/src/params/reporev.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web/src/featureFlags/featureFlags.ts
  cmd/frontend/internal/app/ui/sveltekit.go
Labels: cla-signed

#60833 search: use repoPagerJob for diff/commit search
  internal/search/commit/BUILD.bazel
  internal/search/commit/commit.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/repo_pager_job.go
Labels: cla-signed

#60822 search jobs: fix typo in creation popover
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
Labels: cla-signed

#60687 SG Start Bazel Improvements Take 2
  .bazel_fix_commands.json
  deps.bzl
  dev/sg/internal/run/BUILD.bazel
  dev/sg/internal/run/bazel_build.go
  dev/sg/internal/run/bazel_command.go
  dev/sg/internal/run/command.go
  dev/sg/internal/run/ibazel.go
  dev/sg/internal/run/installer.go
  dev/sg/internal/run/logger.go
  dev/sg/internal/run/prefix_suffix_saver.go
  dev/sg/internal/run/run.go
  dev/sg/internal/run/run_bazel.go
  dev/sg/internal/run/sgconfig_command.go
  dev/sg/sg_run.go
  dev/sg/sg_start.go
  dev/sg/sg_start_test.go
  dev/sg/sg_tests.go
  go.mod
  go.sum
  sg.config.yaml
Labels: cla-signed

#60317 ci: use aspect workflow agents
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  cmd/executor/docker-mirror/_ami.build.sh
  cmd/executor/vm-image/_ami.build.sh
  dev/ci/bazel-build-sg.sh
  dev/ci/bazel-configure.sh
  dev/ci/bazel-gomodtidy.sh
  dev/ci/bazel-prechecks.sh
  dev/ci/bazel.sh
  dev/ci/gen-pipeline.sh
  dev/ci/integration/executors/docker-compose.yml
  dev/ci/integration/executors/run.sh
  dev/ci/integration/executors/test.sh
  dev/ci/internal/ci/BUILD.bazel
  dev/ci/internal/ci/aspect_workflows.go
  dev/ci/internal/ci/bazel_helpers.go
  dev/ci/internal/ci/bazel_operations.go
  dev/ci/internal/ci/executor_operations.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/legacy_operations.go
  dev/ci/internal/ci/misc_operations.go
  dev/ci/internal/ci/operations.go
  dev/ci/internal/ci/pipeline.go
  dev/ci/internal/ci/security_operations.go
  dev/ci/internal/ci/wolfi_operations.go
  dev/ci/push_all.sh
  dev/ci/runtype/runtype.go
  dev/ci/runtype/runtype_test.go
  dev/ci/scripts/annotate.sh
  dev/ci/scripts/wolfi/build-base-image.sh
  dev/ci/scripts/wolfi/build-repo-index.sh
  dev/ci/scripts/wolfi/update-base-image-hashes.sh
  dev/ci/scripts/wolfi/upload-package.sh
Labels: cla-signed

#60856 Revert "ci: use aspect workflow agents (#60317)"
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  cmd/executor/docker-mirror/_ami.build.sh
  cmd/executor/vm-image/_ami.build.sh
  dev/ci/bazel-build-sg.sh
  dev/ci/bazel-configure.sh
  dev/ci/bazel-gomodtidy.sh
  dev/ci/bazel-prechecks.sh
  dev/ci/bazel.sh
  dev/ci/gen-pipeline.sh
  dev/ci/integration/executors/docker-compose.yml
  dev/ci/integration/executors/run.sh
  dev/ci/integration/executors/test.sh
  dev/ci/internal/ci/BUILD.bazel
  dev/ci/internal/ci/aspect_workflows.go
  dev/ci/internal/ci/bazel_helpers.go
  dev/ci/internal/ci/bazel_operations.go
  dev/ci/internal/ci/executor_operations.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/legacy_operations.go
  dev/ci/internal/ci/misc_operations.go
  dev/ci/internal/ci/operations.go
  dev/ci/internal/ci/pipeline.go
  dev/ci/internal/ci/security_operations.go
  dev/ci/internal/ci/wolfi_operations.go
  dev/ci/push_all.sh
  dev/ci/runtype/runtype.go
  dev/ci/runtype/runtype_test.go
  dev/ci/scripts/annotate.sh
  dev/ci/scripts/wolfi/build-base-image.sh
  dev/ci/scripts/wolfi/build-repo-index.sh
  dev/ci/scripts/wolfi/update-base-image-hashes.sh
  dev/ci/scripts/wolfi/upload-package.sh
Labels: cla-signed

#60854 search-jobs: fix typo (part 2)
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
Labels: cla-signed

#60532 web: add date-fns/utc package
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/source

#60838 Allow site-admins to view user events on Dotcom
  cmd/frontend/graphqlbackend/event_logs.go
  cmd/frontend/graphqlbackend/event_logs_test.go
Labels: cla-signed

#60837 Remove dotcom specific gmail abuse check
  cmd/frontend/auth/BUILD.bazel
  cmd/frontend/auth/user.go
  internal/auth/userpasswd/BUILD.bazel
  internal/auth/userpasswd/handlers.go
  internal/security/BUILD.bazel
  internal/security/security.go
  internal/security/security_test.go
  internal/telemetry/events.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#60857 Log if one of main LLM providers is not enabled
  cmd/cody-gateway/internal/httpapi/handler.go
Labels: cla-signed

#60489 sg backport?
  dev/sg/BUILD.bazel
  dev/sg/internal/backport/BUILD.bazel
  dev/sg/internal/backport/backport.go
  dev/sg/internal/backport/exec.go
  dev/sg/main.go
  dev/sg/sg_backport.go
Labels: cla-signed

#60865 ci: fix executors image family for nightly builds
  dev/ci/internal/ci/executor_operations.go
Labels: cla-signed

#60533 web: subscriptions: fix: make all license expiration calculations use utc instead of the browser's local timezone
  client/branded/BUILD.bazel
  client/branded/src/components/Timestamp/Timestamp.tsx
  client/web/BUILD.bazel
  client/web/src/enterprise/dotcom/productSubscriptions/ProductLicenseValidity.tsx
  client/web/src/enterprise/productSubscription/ExpirationDate.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionNode.tsx
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserProductSubscriptionStatus.test.tsx.snap
Labels: cla-signed, team/source

#60866 ci: use .aspect/workflows/bazelrc for Aspect Workflows flags
  .aspect/workflows/bazelrc
  .aspect/workflows/config.yaml
Labels: cla-signed

#60844 Search: protect against panic
  internal/search/result/BUILD.bazel
  internal/search/result/file.go
  internal/search/result/file_test.go
Labels: cla-signed

#60494 Svelte: port most of the filter panel behavior
  client/web-sveltekit/src/lib/LanguageIcon.svelte
  client/web-sveltekit/src/lib/icons/ArrowBend.svelte
  client/web-sveltekit/src/lib/icons/LinkShare.svelte
  client/web-sveltekit/src/lib/icons/OpenBook.svelte
  client/web-sveltekit/src/lib/search/CodeHostIcon.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/CountBadge.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/HelpFooter.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/LoadingSkeleton.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/TypeSection.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
  client/web-sveltekit/src/lib/search/index.ts
  client/web-sveltekit/src/lib/search/utils.ts
  client/web-sveltekit/src/routes/search/+page.svelte
  client/web-sveltekit/src/routes/search/+page.ts
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  cmd/frontend/graphqlbackend/search_results_test.go
  internal/search/streaming/search_filters.go
Labels: cla-signed

#60871 Svelte: respect trace=1 query param
  client/web-sveltekit/src/lib/search/state.ts
  client/web-sveltekit/src/routes/search/+page.ts
Labels: cla-signed

#60873 Svelte: use JSON_SCIP format for highlighting
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.gql
Labels: cla-signed

#60850 v2t: add v2t to src/enterprise/own
  client/web/src/enterprise/own/RepositoryOwnEditPage.story.tsx
  client/web/src/enterprise/own/RepositoryOwnEditPage.tsx
  client/web/src/enterprise/own/RepositoryOwnPageContents.tsx
  client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.story.tsx
  client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
  client/web/src/enterprise/own/admin-ui/OwnStatusPage.tsx
  client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx
  client/web/src/site-admin/routes.tsx
Labels: cla-signed

#60874 Svelte: fix code submission
  client/web-sveltekit/src/lib/search/state.ts
Labels: cla-signed

#60875 Add latency section to Cloud FAQ
  doc/cloud/index.md
Labels: cla-signed

#60860 Revert "Revert "ci: use aspect workflow agents (#60317)" (#60856)"
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  cmd/executor/docker-mirror/_ami.build.sh
  cmd/executor/vm-image/_ami.build.sh
  dev/ci/bazel-build-sg.sh
  dev/ci/bazel-configure.sh
  dev/ci/bazel-gomodtidy.sh
  dev/ci/bazel-prechecks.sh
  dev/ci/bazel.sh
  dev/ci/gen-pipeline.sh
  dev/ci/integration/executors/docker-compose.yml
  dev/ci/integration/executors/run.sh
  dev/ci/integration/executors/test.sh
  dev/ci/internal/ci/BUILD.bazel
  dev/ci/internal/ci/aspect_workflows.go
  dev/ci/internal/ci/bazel_helpers.go
  dev/ci/internal/ci/bazel_operations.go
  dev/ci/internal/ci/executor_operations.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/legacy_operations.go
  dev/ci/internal/ci/misc_operations.go
  dev/ci/internal/ci/operations.go
  dev/ci/internal/ci/pipeline.go
  dev/ci/internal/ci/security_operations.go
  dev/ci/internal/ci/wolfi_operations.go
  dev/ci/push_all.sh
  dev/ci/runtype/runtype.go
  dev/ci/runtype/runtype_test.go
  dev/ci/scripts/annotate.sh
  dev/ci/scripts/wolfi/build-base-image.sh
  dev/ci/scripts/wolfi/build-repo-index.sh
  dev/ci/scripts/wolfi/update-base-image-hashes.sh
  dev/ci/scripts/wolfi/upload-package.sh
Labels: cla-signed

#60835 Block bad phrases for flagged requests
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/shared/config/config.go
Labels: cla-signed

#60885 update description for sg backport
  dev/sg/sg_backport.go
Labels: cla-signed

#60886 Fix small typo in gitserver scope
  internal/codeintel/autoindexing/internal/inference/iface.go
Labels: cla-signed, team/source

#60869 bump aspect bazel-lib to 1.40.3
  .aspect/bazelrc/BUILD.bazel
  .aspect/bazelrc/bazel7.bazelrc
  .aspect/bazelrc/javascript.bazelrc
  .aspect/bazelrc/performance.bazelrc
  .bazelrc
  WORKSPACE
  dev/mocha.bzl
  third_party/bazel_lib/BUILD.bazel
  third_party/bazel_lib/use_default_shell_env.patch
  third_party/rules_js/BUILD.bazel
  third_party/rules_js/use_default_shell_env.patch
Labels: cla-signed, bazel

#60888 ci: disable posting of annotations by aspect buildkite plugin
  .aspect/cli/config.yaml
Labels: cla-signed

#60891 Record pattern that was blocked
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#60892 ci: disable Workflows runner observabilty to resolve slow post-task agent health check
  .aspect/workflows/config.yaml
Labels: cla-signed

#60828 feat: extend graphql User with evaluateFeatureFlag operation
  CHANGELOG.md
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: cla-signed

#60896 bazel: transition oci_image ourselves instead of via with_cfg.bzl
  WORKSPACE
  dev/oci_defs.bzl
Labels: cla-signed, bazel

#60887 Bump src-cli to 5.3.0 for executors (#60705)
  dev/tool_deps.bzl
Labels: cla-signed

#60895 Enforce authz check for individual codehosts
  cmd/frontend/graphqlbackend/code_hosts.go
  cmd/frontend/graphqlbackend/code_hosts_test.go
Labels: cla-signed, SSDLC

#60898 ci: label the integration tests properly
  .aspect/workflows/config.yaml
  dev/ci/internal/ci/aspect_workflows.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/wolfi_operations.go
Labels: cla-signed

#60830 Add support for Claude 3 to Cody Gateway
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages_test.go
  cmd/cody-gateway/internal/httpapi/completions/flagging.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/client/anthropicmessages/BUILD.bazel
  internal/completions/client/anthropicmessages/decoder.go
  internal/completions/client/anthropicmessages/decoder_test.go
  internal/completions/httpapi/chat.go
Labels: cla-signed

#60858 svelte: Update top navigation to match S2 navigation
  client/web-sveltekit/src/lib/navigation.ts
  client/web-sveltekit/src/routes/Header.svelte
  client/web-sveltekit/src/routes/HeaderNavLink.svelte
  client/web-sveltekit/src/routes/MainNavigationEntry.svelte
  client/web-sveltekit/src/routes/MainNavigationLink.svelte
  client/web-sveltekit/src/routes/mainNavigation.ts
Labels: cla-signed, team/code-search

#60880 Svelte: remove weird background color
  client/web-sveltekit/src/lib/search/BaseQueryInput.svelte
Labels: cla-signed

#60878 Search: avoid crashing on frontend panic
  cmd/frontend/internal/compute/streaming/BUILD.bazel
  cmd/frontend/internal/compute/streaming/compute.go
  internal/search/backend/BUILD.bazel
  internal/search/backend/horizontal.go
Labels: cla-signed

#60877 Allow to get Blame information for a whole file
  cmd/frontend/graphqlbackend/git_blob.go
  cmd/frontend/graphqlbackend/schema.graphql
Labels: cla-signed, team/source

#60906 test: Remove wrong dot in local symbol names
  internal/codeintel/codenav/service_new_test.go
Labels: cla-signed

#60907 Own: remove in-product marketing
  client/web/BUILD.bazel
  client/web/src/enterprise/own/OwnPage.tsx
  client/web/src/repo/blob/own/OwnerList.tsx
  client/web/src/routes.tsx
Labels: cla-signed

#60911 rename "Subscriptions" to "Enterprise licenses" to avoid confusion with Cody Pro
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
  client/web/src/site-admin/sidebaritems.ts
  client/web/src/user/settings/sidebaritems.ts
Labels: cla-signed

#60913 Merge cody subscription details from multiple associated SAMS accounts
  internal/cody/subscription.go
  internal/cody/subscription_test.go
Labels: cla-signed

#60914 Expose API to fetch cody subscription associated with SAMS identity
  cmd/frontend/graphqlbackend/external_account.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/cody/subscription.go
Labels: cla-signed

#60872 web: Trigger page refresh to load SvelteKit for supported/enabled routes
  client/web-sveltekit/src/lib/navigation.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web/BUILD.bazel
  client/web/src/communitySearchContexts/routes.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/routes.constants.ts
  client/web/src/sveltekit/SvelteKitNavItem.tsx
  client/web/src/sveltekit/WebNextAwareLink.tsx
  client/web/src/sveltekit/util.ts
  cmd/frontend/internal/app/ui/sveltekit.go
Labels: cla-signed

#57327 gitserver: Pass HTTPS remote URL password as env var
  cmd/gitserver/internal/executil/BUILD.bazel
  cmd/gitserver/internal/executil/executil.go
  cmd/gitserver/internal/executil/executil_test.go
  cmd/gitserver/internal/patch.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/vcssyncer/git.go
Labels: cla-signed

#60901 ci: remove include_eternal_tests as it is no longer needed in Aspect Workflows 5.9.18
  .aspect/workflows/config.yaml
  dev/sg/internal/images/BUILD.bazel
Labels: cla-signed

#60923 Fix external_account.cody_subscription logic
  cmd/frontend/graphqlbackend/external_account.go
Labels: cla-signed

#60932 Svelte: fix jumpy filters panel
  client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
Labels: cla-signed

#60933 Svelte: scroll result list without actions
  client/web-sveltekit/src/routes/search/SearchResults.svelte
Labels: cla-signed

#60931 Updates vitest macro
  client/web-sveltekit/BUILD.bazel
  dev/defs.bzl
Labels: cla-signed

#60927 svelte/ci: Add vitest target for client/web-sveltekit
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  dev/defs.bzl
  pnpm-lock.yaml
Labels: cla-signed, team/code-search

#60936 svelte: Fix repo playwright test
  client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
Labels: cla-signed, team/code-search

#60937 Limit empty/zero data in json output from aggregate Cody ping data
  internal/types/types.go
  internal/usagestats/aggregated_cody.go
Labels: cla-signed

#60343 v2 telemetry: add v2 telemetry to src/cody
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/components/ChatUI/ChatUi.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.story.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
  client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
  client/web/src/cody/dashboard/CodyDashboardPage.tsx
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/onboarding/CodyOnboarding.tsx
  client/web/src/cody/search/CodySearchPage.tsx
  client/web/src/cody/sidebar/CodySidebar.tsx
  client/web/src/cody/sidebar/Provider.tsx
  client/web/src/cody/subscription/CancelProModal.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/cody/subscription/UpgradeToProModal.tsx
  client/web/src/cody/useCodyChat.tsx
  client/web/src/cody/widgets/CodyRecipesWidget.tsx
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/tooltips/CodyTooltip.tsx
  client/web/src/routes.tsx
Labels: cla-signed

#60943 Bug: remove extra GraphQL validation
  cmd/frontend/internal/httpapi/graphql.go
Labels: cla-signed

#60903 Svelte: fix no matches messages with show more
  client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
Labels: cla-signed

#60944 Search: simplify goroutine params
  internal/search/backend/horizontal.go
Labels: cla-signed

#60924 search jobs: fail validation for select: queries
  internal/search/job/jobutil/exhaustive_job.go
  internal/search/job/jobutil/exhaustive_job_test.go
Labels: cla-signed

#60889 search: update patternType suggestions
  client/shared/src/search/query/diagnostics.test.ts
  client/shared/src/search/query/filters.ts
Labels: cla-signed

#60952 go: update bobheadxi/streamline to 1.3.2
  deps.bzl
  go.mod
  go.sum
  internal/insights/background/queryrunner/testdata/TestGetSeries/series_definition_does_exist.golden
  internal/insights/background/queryrunner/testdata/TestJobQueueDependencies/enqueue_with_dependencies.golden
  internal/insights/background/queryrunner/testdata/TestQueryExecution_ToQueueJob/test_to_job_with_dependents.golden
  internal/insights/background/queryrunner/testdata/TestQueryExecution_ToQueueJob/test_to_job_without_dependents.golden
  internal/insights/compression/testdata/TestQueryExecution_ToRecording/test_to_recording_with_dependents.golden
  internal/insights/compression/testdata/TestQueryExecution_ToRecording/test_to_recording_without_dependents.golden
  internal/insights/store/testdata/TestCreateGetView_WithGrants/no_users_or_orgs_provided_should_only_return_global.golden
  internal/insights/store/testdata/TestCreateGetView_WithGrants/org_5_can_see_the_view.golden
  internal/insights/store/testdata/TestCreateGetView_WithGrants/user_1_can_see_this_view.golden
  internal/insights/store/testdata/TestCreateSeries/test_create_and_get_capture_groups_series.golden
  internal/insights/store/testdata/TestDeleteSnapshots.golden
  internal/insights/store/testdata/TestFindMatchingSeries/find_a_matching_series_when_one_exists.golden
  internal/insights/store/testdata/TestFindMatchingSeries/match_capture_group_series.golden
Labels: cla-signed

#60940 Cleanup Cody Pro pre-feb release stuff
  client/web/BUILD.bazel
  client/web/src/cody/featureFlags.ts
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CancelProModal.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/cody/subscription/UpgradeToProModal.tsx
  client/web/src/cody/subscription/queries.tsx
  client/web/src/featureFlags/featureFlags.ts
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
  internal/cody/subscription.go
  internal/cody/subscription_test.go
  internal/cody/utils.go
  internal/cody/utils_test.go
  internal/database/users.go
  internal/ssc/types.go
  internal/types/types.go
Labels: cla-signed

#60957 sg: add a cody-gateway-bazel commandset
  sg.config.yaml
Labels: cla-signed

#60945 oidc: Add option to allow only a single identity per provider
  cmd/frontend/auth/user.go
  cmd/frontend/auth/user_test.go
  cmd/frontend/internal/auth/openidconnect/user.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/source

#60955 Integrate the new Triton-server hosted Embeddings model
  cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
  cmd/cody-gateway/internal/httpapi/embeddings/sourcegraph.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/qa/e2e_test.go
  cmd/cody-gateway/shared/config/BUILD.bazel
  cmd/cody-gateway/shared/config/config.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#60968 Release: prepare 5.3.2 release
  dev/release/release-config.jsonc
Labels: cla-signed

#60970 Release: activate 5.3.2 release
  dev/release/release-config.jsonc
Labels: cla-signed

#60863 [Backport 5.3] update roles page description
  client/web/src/enterprise/rbac/SiteAdminRolesPage.tsx
Labels: cla-signed, backports, backported-to-5.3

#60964 sg: embed sg.doctor.yaml and make output stable
  dev/sg/BUILD.bazel
  dev/sg/sg.doctor.yaml
  dev/sg/sg_doctor.go
Labels: cla-signed

#60967 Fix link feature flag check within code intel card
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/tooltips/HovercardView.tsx
Labels: cla-signed

#60974 sg/msp: add `bigqueryconnection.googleapis.com` api
  dev/managedservicesplatform/stacks/project/project.go
Labels: cla-signed

#60973 backport: update schema descriptions for 5.3.2
  tools/release/schema_deps.bzl
Labels: cla-signed

#60978 Release: update changelog for v5.3.2
  CHANGELOG.md
Labels: cla-signed

#60979 release: sourcegraph@5.3.2
  internal/updatecheck/handler.go
Labels: cla-signed

#60982 Revert "web: Trigger page refresh to load SvelteKit for supported/enabled routes"
  client/web-sveltekit/src/lib/navigation.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web/BUILD.bazel
  client/web/src/communitySearchContexts/routes.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/routes.constants.ts
  client/web/src/sveltekit/SvelteKitNavItem.tsx
  client/web/src/sveltekit/WebNextAwareLink.tsx
  client/web/src/sveltekit/util.ts
  cmd/frontend/internal/app/ui/sveltekit.go
Labels: cla-signed

#60987 client: Quote language name in code nav search queries
  client/web/src/enterprise/codeintel/searchBased.ts
Labels: cla-signed, backport 5.3

#60993 Github Acionts: update workflows to use go 1.22
  .github/workflows/buildchecker-history.yml
  .github/workflows/buildchecker.yml
  .github/workflows/licenses-check.yml
  .github/workflows/pr-auditor.yml
  .github/workflows/sg-binary-release.yml
  .github/workflows/sg-setup.yml
Labels: cla-signed

#60883 search jobs: support diff, commit and path search
  CHANGELOG.md
  internal/search/exhaustive/service/searcher.go
  internal/search/job/jobutil/exhaustive_job.go
  internal/search/job/jobutil/exhaustive_job_test.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/result/result_type.go
Labels: cla-signed

#60956 Allowlist the new triton model we use for testing
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Labels: cla-signed

#60996 Removed unused bazel macro arg
  client/build-config/BUILD.bazel
  dev/defs.bzl
  sg.config.yaml
Labels: cla-signed

#60947 gomod: update zoekt
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#60963 bazel: include //dev:go_mockgen in //dev:write_all_generated
  WORKSPACE
  dev/BUILD.bazel
  dev/go-mockgen-gazelle/go-mockgen.go
Labels: cla-signed, bazel

#60992 graphqlbackend: allow siteadmins to view roles on dotcom
  cmd/frontend/graphqlbackend/roles_test.go
  cmd/frontend/graphqlbackend/user.go
Labels: cla-signed

#60986 msp/operationdocs: link to msp repo setup
  dev/managedservicesplatform/operationdocs/operationdocs.go
  dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden
Labels: cla-signed

#60984 sg msp: improve cloudsqlproxy installation UX
  dev/sg/cloudsqlproxy/binary.go
  dev/sg/msp/repo/root.go
Labels: cla-signed

#61004 bazel: patch rules_oci to run tar with --no-xattrs
  WORKSPACE
  third_party/rules_oci/BUILD.bazel
  third_party/rules_oci/no_xattr.patch
Labels: cla-signed, bazel

#61003 Include traceID in blocked responses
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
  cmd/cody-gateway/internal/httpapi/completions/flagging.go
Labels: cla-signed

#61007 oidc: Rename singleProvider property to singleIdentityPerUser
  cmd/frontend/auth/user.go
  cmd/frontend/auth/user_test.go
  cmd/frontend/internal/auth/openidconnect/user.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/source

#61012 Svelte: add hover to separator and remove size change
  client/web-sveltekit/src/lib/Separator.svelte
Labels: cla-signed

#60994 web: Trigger page refresh to load SvelteKit for supported/enabled routes (take 2)
  client/web-sveltekit/src/lib/navigation.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web/BUILD.bazel
  client/web/src/communitySearchContexts/routes.tsx
  client/web/src/enterprise/main.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/repo/blob/BlameDecoration.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/react-interop.tsx
  client/web/src/repo/blob/codemirror/search.tsx
  client/web/src/repo/blob/codemirror/static-highlights.tsx
  client/web/src/repo/blob/codemirror/tooltips/HovercardView.tsx
  client/web/src/routes.constants.ts
  client/web/src/sveltekit/SvelteKitNavItem.tsx
  client/web/src/sveltekit/WebNextAwareLink.tsx
  client/web/src/sveltekit/util.ts
  cmd/frontend/internal/app/ui/sveltekit.go
Labels: cla-signed

#60796 productsubscription: service accounts with RBAC, instead of feature flags
  cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go
  cmd/frontend/internal/dotcom/productsubscription/service_account.go
  cmd/frontend/internal/dotcom/productsubscription/service_account_test.go
  cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
  cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql_test.go
  cmd/frontend/internal/dotcom/productsubscription/tokens_graphql.go
Labels: cla-signed

#61025 bazel: buildifier 6.4.0
  WORKSPACE
Labels: cla-signed

#61026 ci: bazel do - skip adding of aspect workflows
  .buildkite/pipeline.yml
  dev/sg/ci/subcommands.go
  dev/sg/internal/bk/BUILD.bazel
  dev/sg/internal/bk/bk.go
  dev/sg/internal/bk/create_build_opts.go
Labels: cla-signed

#61015 Remove limit while fetching sams account ids
  internal/cody/subscription.go
Labels: cla-signed

#61024 Check for scheduled or processing jobs when scheduling permission syncs
  CHANGELOG.md
  cmd/worker/internal/authz/perms_syncer.go
  internal/database/perms_store.go
  internal/database/perms_store_test.go
Labels: cla-signed, team/source

#61028 chore: fixup go-mockgen run statement
  gen.go
Labels: cla-signed

#61029 Remove Sonarcloud SAST
  dev/ci/internal/ci/pipeline.go
  dev/ci/internal/ci/security_operations.go
  dev/ci/sonarcloud-scan.sh
  sonar-project.properties
Labels: cla-signed

#61005 Cody: Update Azure OpenAI client and force api-version to a stable one
  CHANGELOG.md
  deps.bzl
  go.mod
  go.sum
  internal/completions/client/azureopenai/BUILD.bazel
  internal/completions/client/azureopenai/openai.go
Labels: cla-signed, backport 5.3

#61008 Chore: remove Own from global navbar
  client/web/src/LegacyLayout.tsx
  client/web/src/nav/GlobalNavbar.tsx
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.story.tsx
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
Labels: cla-signed

#61009 Simplify goroutine params
  cmd/executor/internal/worker/cmdlogger/logger.go
  cmd/frontend/graphqlbackend/observability.go
  cmd/frontend/internal/auth/openidconnect/config.go
  cmd/frontend/internal/auth/saml/config.go
  cmd/gitserver/internal/server.go
  cmd/loadtest/main.go
  cmd/repo-updater/internal/scheduler/scheduler.go
  cmd/server/internal/goreman/proc.go
  cmd/worker/internal/executorqueue/external_emitter.go
  cmd/worker/shared/main.go
  dev/codeintel-qa/cmd/upload/upload.go
  dev/sg/internal/run/installer.go
  internal/batches/service/workspace_resolver.go
  internal/batches/store/changesets_test.go
  internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
  internal/database/migration/runner/runner.go
  internal/diskcache/cache.go
  internal/grpc/defaults/cache_test.go
  internal/repos/bitbucketserver.go
  internal/repos/gitlab.go
  internal/search/backend/horizontal.go
  internal/search/backend/index_options.go
  lib/output/output_unix.go
Labels: cla-signed

#60962 rfc795: new release process foundations
  .buildkite/pipeline.yml
  WORKSPACE
  cmd/executor/_binary.push.sh
  cmd/executor/vm-image/_ami.build.sh
  cmd/frontend/BUILD.bazel
  cmd/migrator/BUILD.bazel
  cmd/migrator/airgappedgen/BUILD.bazel
  cmd/migrator/airgappedgen/README.md
  cmd/migrator/airgappedgen/gcs_versions.json
  cmd/migrator/airgappedgen/main.go
  cmd/migrator/airgappedgen/schema_description.go
  cmd/migrator/image_test.yaml
  dev/ci/images/images.go
  dev/ci/integration/executors/run.sh
  dev/ci/internal/ci/BUILD.bazel
  dev/ci/internal/ci/bazel_helpers.go
  dev/ci/internal/ci/config.go
  dev/ci/internal/ci/executor_operations.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/pipeline.go
  dev/ci/internal/ci/release_operations.go
  dev/ci/push_all.sh
  dev/ci/runtype/runtype.go
  dev/ci/runtype/runtype_test.go
  dev/sg/BUILD.bazel
  dev/sg/internal/images/dockerhub.go
  dev/sg/internal/images/gcr.go
  dev/sg/internal/release/BUILD.bazel
  dev/sg/internal/release/config.go
  dev/sg/internal/release/cve.go
  dev/sg/internal/release/release.go
  dev/sg/main.go
  dev/sg/sg_release.go
  internal/database/migration/cliutil/util.go
  internal/database/migration/shared/data/cmd/generator/BUILD.bazel
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/cmd/generator/version/BUILD.bazel
  internal/database/migration/shared/data/cmd/generator/version/version.go
  lib/output/style.go
  release.yaml
  tools/release/BUILD.bazel
  tools/release/README.md
  tools/release/generate_schemas_archive.sh
  tools/release/promote_images.sh
  tools/release/schema_deps.bzl
  tools/release/upload_current_schemas.sh
Labels: cla-signed

#61037 Pin third-party actions
  .github/workflows/buf-breaking-check.yml
  .github/workflows/licenses-check.yml
  .github/workflows/licenses-update.yml
  .github/workflows/pull-request.yml
  .github/workflows/scip-typescript.yml
  .github/workflows/team-labeler.yml
  .github/workflows/universal-ctags.yml
  .github/workflows/update-embeddings-list.yml
Labels: cla-signed

#60977 svelte: Add search history mode to search input
  client/branded/src/search-ui/input/experimental/modes.ts
  client/web-sveltekit/src/lib/branded.ts
  client/web-sveltekit/src/lib/search/SyntaxHighlightedQuery.svelte
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web-sveltekit/src/lib/search/input/recentSearches.ts
  client/web-sveltekit/src/lib/search/state.ts
  client/web-sveltekit/src/routes/search/+page.svelte
  client/web-sveltekit/src/routes/search/+page.ts
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web-sveltekit/vite.config.ts
  client/web/BUILD.bazel
  client/web/src/search/input/recentSearches.test.ts
  client/web/src/search/input/recentSearches.ts
  client/web/src/search/input/useRecentSearches.test.tsx
  client/web/src/search/input/useRecentSearches.ts
Labels: cla-signed, team/code-search

#61041 fix: ci: remove safeguard for prod registry
  dev/ci/images/images.go
Labels: cla-signed

#61042 fix: ci: restore pushing on prod registry
  dev/ci/push_all.sh
Labels: cla-signed

#61036 web/ExternalsAuth: fix dotcom sign-in widget
  client/web/src/auth/CloudSignUpPage.story.tsx
  client/web/src/auth/CloudSignUpPage.tsx
  client/web/src/auth/SignUpPage.story.tsx
  client/web/src/auth/SignUpPage.test.tsx
  client/web/src/auth/SignUpPage.tsx
  client/web/src/auth/VsCodeSignUpPage.story.tsx
  client/web/src/auth/VsCodeSignUpPage.tsx
  client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
  client/web/src/auth/components/ExternalsAuth.tsx
  client/web/src/cody/chat/CodyChatPage.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.module.scss
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.story.tsx
  client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
  client/web/src/get-cody/GetCodyPage.tsx
  client/web/src/repo/RepositoryFileTreePage.tsx
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/components/TryCodyWidget/TryCodyWidget.tsx
  client/web/src/repo/tree/TreePage.test.tsx
  client/web/src/repo/tree/TreePage.tsx
Labels: cla-signed

#61044 executors: Fix version detection for V2 payloads
  cmd/frontend/internal/executorqueue/handler/handler.go
  cmd/frontend/internal/executorqueue/handler/multihandler.go
Labels: cla-signed, team/source, backport/bugfix, backport/customer-critical, backport 5.3

#60870 gitserver: Cleanup grafana dashboard
  cmd/gitserver/internal/cleanup.go
  cmd/gitserver/internal/server.go
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/git_server.go
  monitoring/definitions/shared/gitserver.go
Labels: cla-signed, team/source

#60577 gitserver: Fix some lint warnings
  cmd/gitserver/internal/cleanup.go
  cmd/gitserver/internal/search.go
  cmd/gitserver/internal/server_test.go
  cmd/gitserver/internal/vcssyncer/jvm_packages.go
  cmd/gitserver/internal/vcssyncer/npm_packages_test.go
Labels: cla-signed, team/source

#60910 Add basic global notification UI
  client/web-sveltekit/src/lib/global-notifications/DismissibleAlert.svelte
  client/web-sveltekit/src/lib/global-notifications/GlobalNotifications.gql
  client/web-sveltekit/src/lib/global-notifications/GlobalNotifications.svelte
  client/web-sveltekit/src/lib/wildcard/Alert.svelte
  client/web-sveltekit/src/lib/wildcard/Markdown.module.scss
  client/web-sveltekit/src/lib/wildcard/Markdown.svelte
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/+layout.ts
  client/web-sveltekit/src/routes/layout.gql
  client/web-sveltekit/src/routes/layout.spec.ts
  client/web-sveltekit/vite.config.ts
  client/web/src/global/GlobalAlerts.tsx
  client/web/src/global/Notices.tsx
Labels: cla-signed

#60809 Remove watcher for permission mapper
  cmd/embeddings/shared/BUILD.bazel
  cmd/embeddings/shared/main.go
  cmd/frontend/globals/globals.go
  cmd/frontend/internal/authz/resolvers/BUILD.bazel
  cmd/frontend/internal/authz/resolvers/resolver.go
  cmd/frontend/internal/authz/resolvers/resolver_test.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/repo-updater/shared/main.go
  cmd/worker/internal/permissions/BUILD.bazel
  cmd/worker/internal/permissions/bitbucket_projects.go
  cmd/worker/shared/BUILD.bazel
  cmd/worker/shared/main.go
  internal/authz/providers/BUILD.bazel
  internal/authz/providers/authz_test.go
  internal/codeintel/policies/internal/store/BUILD.bazel
  internal/codeintel/policies/internal/store/repository_matches_test.go
  internal/codeintel/uploads/internal/store/BUILD.bazel
  internal/codeintel/uploads/internal/store/indexes_test.go
  internal/codeintel/uploads/internal/store/uploads_test.go
  internal/conf/computed.go
  internal/database/BUILD.bazel
  internal/database/authz.go
  internal/database/authz_test.go
  internal/database/external_services.go
  internal/database/external_services_test.go
  internal/database/perms_store_test.go
  internal/database/repos_perm.go
  internal/database/repos_perm_test.go
  internal/insights/discovery/BUILD.bazel
  internal/insights/discovery/scoped_repo_iterator_test.go
  internal/oobmigration/migrations/iam/BUILD.bazel
  internal/oobmigration/migrations/iam/unified_permissions_migrator.go
  internal/oobmigration/migrations/iam/unified_permissions_migrator_test.go
  internal/own/background/BUILD.bazel
  internal/own/background/recent_contributors_test.go
Labels: cla-signed, team/source

#61049 rename 'Enterprise licenses' to 'Enterprise subscriptions' to accurately represent enterprise accounts
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminLicenseKeyLookupPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
  client/web/src/site-admin/sidebaritems.ts
  client/web/src/user/settings/sidebaritems.ts
Labels: cla-signed

#60603 Make username key configurable for SAML auth providers
  CHANGELOG.md
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/user.go
  cmd/frontend/internal/auth/saml/user.go
  cmd/frontend/internal/auth/saml/user_test.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed, team/source

#61047 svelte: Improve TS types for GraphQL mocks
  client/web-sveltekit/dev/graphql-type-mocks.cjs
  client/web-sveltekit/src/testing/integration.ts
Labels: cla-signed, team/code-search

#61040 Clean-up Dotcom specific checks
  cmd/frontend/graphqlbackend/orgs.go
  cmd/frontend/graphqlbackend/orgs_test.go
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: cla-signed

#61051 gomod: update zoekt to fix symbol .* perf regression
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#61054 Add basic focus ring styles to svelte button, links, input elements
  client/web-sveltekit/src/routes/MainNavigationEntry.svelte
  client/web-sveltekit/src/routes/styles.scss
Labels: cla-signed

#61045 executor: Fix global secrets across namespaces colliding
  internal/database/executor_secrets.go
  internal/database/executor_secrets_test.go
Labels: cla-signed, team/source

#61059 chore: bumps deps
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, SSDLC

#61050 msp/runtime: add -help handling for config options
  lib/managedservicesplatform/runtime/env.go
  lib/managedservicesplatform/runtime/service.go
Labels: cla-signed

#61048 worker: Fix test after go 1.22 upgrade
  internal/workerutil/worker_test.go
Labels: cla-signed, team/source

#61092 bazel: bump to 7.1
  .bazelversion
Labels: cla-signed, bazel

#61104 telemetry-gateway: discard oversized events after logging some content
  cmd/telemetry-gateway/internal/events/BUILD.bazel
  cmd/telemetry-gateway/internal/events/events.go
  cmd/telemetry-gateway/internal/events/events_test.go
  cmd/telemetry-gateway/internal/server/server.go
Labels: cla-signed

#61103 ci: let backcompat tests run on aspect workflow agents
  .buildkite/pipeline.backcompat.yml
  dev/backcompat/bazel-backcompat.sh
Labels: cla-signed
