Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-04, with the labels that each got.

#61290 Refactor URL helpers
  client/branded/src/search-ui/components/FileMatchChildren.tsx
  client/browser/BUILD.bazel
  client/browser/src/shared/backend/extension-api-conversion.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/code-hosts/shared/util/selections.test.ts
  client/browser/src/shared/code-hosts/shared/util/selections.ts
  client/browser/src/shared/repo/backend.tsx
  client/common/BUILD.bazel
  client/common/src/util/url.test.ts
  client/common/src/util/url.ts
  client/shared/src/api/extension/extensionHostApi.ts
  client/shared/src/backend/file.ts
  client/shared/src/backend/repo.ts
  client/shared/src/codeintel/api.ts
  client/shared/src/codeintel/legacy-extensions/util/uri.ts
  client/shared/src/commands/commands.ts
  client/shared/src/hover/actions.ts
  client/shared/src/util/url.test.ts
  client/shared/src/util/url.ts
  client/vscode/src/code-intel/SourcegraphDefinitionProvider.ts
  client/vscode/src/code-intel/SourcegraphHoverProvider.ts
  client/vscode/src/code-intel/SourcegraphReferenceProvider.ts
  client/vscode/src/code-intel/initialize.ts
  client/vscode/src/file-system/SourcegraphUri.ts
  client/vscode/src/webview/search-panel/alias/FileMatchChildren.tsx
  client/web-sveltekit/src/lib/common.ts
  client/web-sveltekit/src/lib/repo/blob.test.ts
  client/web-sveltekit/src/lib/repo/blob.ts
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
  client/web/src/codeintel/ReferencesPanel.tsx
  client/web/src/enterprise/codeintel/searchBased.ts
  client/web/src/enterprise/own/IngestedFileViewer.tsx
  client/web/src/repo/RepositoryFileTreePage.tsx
  client/web/src/repo/backend.ts
  client/web/src/repo/blame/useBlameHunks.ts
  client/web/src/repo/blob/BlobPage.tsx
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/actions/ToggleHistoryPanel.tsx
  client/web/src/repo/blob/actions/utils.ts
  client/web/src/repo/blob/backend.ts
  client/web/src/repo/blob/codemirror/codeintel/api.ts
  client/web/src/repo/blob/definitions.ts
  client/web/src/repo/blob/panel/BlobPanel.tsx
  client/web/src/search/suggestion/SmartSearch.tsx
  client/web/src/util/url.ts
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/code-search

#61486 Generalize prompt recording for all upstream LLM providers
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages_test.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/flagging.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/BUILD.bazel
  cmd/cody-gateway/shared/config/config.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#61511 msp: ignore ErrSchemaMismatch OTel error
  deps.bzl
  go.mod
  go.sum
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/go.sum
  lib/managedservicesplatform/runtime/internal/opentelemetry/BUILD.bazel
  lib/managedservicesplatform/runtime/internal/opentelemetry/opentelemetry.go
Labels: cla-signed

#61367 code monitors: don't fail job if repo empty
  cmd/frontend/internal/codemonitors/resolvers/resolvers.go
  internal/codemonitors/BUILD.bazel
  internal/codemonitors/background/workers.go
  internal/codemonitors/search.go
  internal/codemonitors/search_test.go
  internal/database/code_monitor_trigger_jobs.go
  internal/database/code_monitor_trigger_jobs_test.go
  internal/database/code_monitors.go
  internal/database/dbmocks/mocks_temp.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1711538234_code_monitors_add_column_for_structured_logging/down.sql
  migrations/frontend/1711538234_code_monitors_add_column_for_structured_logging/metadata.yaml
  migrations/frontend/1711538234_code_monitors_add_column_for_structured_logging/up.sql
  migrations/frontend/squashed.sql
Labels: team/search-platform, cla-signed, team/product-platform

#61515 gomod: update zoekt to remove perf regression in go 1.22
  deps.bzl
  go.mod
  go.sum
  internal/search/job/jobutil/job_test.go
  internal/search/zoekt/query_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#61497 ci+release: update manifest to tag during finalization
  release.yaml
Labels: cla-signed

#60958 Extract reposcheduler and add support for syntactic indexes
  cmd/worker/internal/codeintel/autoindexing_scheduler.go
  internal/codeintel/BUILD.bazel
  internal/codeintel/autoindexing/BUILD.bazel
  internal/codeintel/autoindexing/init.go
  internal/codeintel/autoindexing/internal/background/BUILD.bazel
  internal/codeintel/autoindexing/internal/background/dependencies/mocks_test.go
  internal/codeintel/autoindexing/internal/background/init.go
  internal/codeintel/autoindexing/internal/background/scheduler/BUILD.bazel
  internal/codeintel/autoindexing/internal/background/scheduler/iface.go
  internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
  internal/codeintel/autoindexing/internal/store/BUILD.bazel
  internal/codeintel/autoindexing/internal/store/scheduler_test.go
  internal/codeintel/autoindexing/internal/store/store.go
  internal/codeintel/autoindexing/internal/store/store_test.go
  internal/codeintel/autoindexing/mocks_test.go
  internal/codeintel/autoindexing/service.go
  internal/codeintel/reposcheduler/BUILD.bazel
  internal/codeintel/reposcheduler/init.go
  internal/codeintel/reposcheduler/options.go
  internal/codeintel/reposcheduler/store.go
  internal/codeintel/reposcheduler/store_observability.go
  internal/codeintel/reposcheduler/store_test.go
  internal/codeintel/services.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1709738515_add_syntactic_indexing_support_to_policies/down.sql
  migrations/frontend/1709738515_add_syntactic_indexing_support_to_policies/metadata.yaml
  migrations/frontend/1709738515_add_syntactic_indexing_support_to_policies/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/product-platform

#61476 Adding changes to redis caching to be able to support redis store for durability
  internal/rcache/rcache.go
  internal/rcache/rcache_test.go
Labels: cla-signed

#61504 v2t: add v2t to src/open-in-editor
  client/web/src/open-in-editor/OpenInEditorActionItem.tsx
  client/web/src/open-in-editor/editors.ts
  client/web/src/repo/blob/BlobPage.tsx
Labels: cla-signed

#61522 [gitserver] ArchiveReader correctly handles paths with spaces
  cmd/gitserver/internal/git/gitcli/BUILD.bazel
  cmd/gitserver/internal/git/gitcli/archivereader.go
  cmd/gitserver/internal/git/gitcli/archivereader_test.go
  internal/byteutils/BUILD.bazel
  internal/byteutils/nullscanner.go
Labels: cla-signed, team/source, team/product-platform

#61419 chore: remove unused darwin-arm64 cross binaries for codeintel-qa
  dev/codeintel-qa/cmd/clear/BUILD.bazel
  dev/codeintel-qa/cmd/clone-and-index/BUILD.bazel
  dev/codeintel-qa/cmd/download/BUILD.bazel
  dev/codeintel-qa/cmd/query/BUILD.bazel
  dev/codeintel-qa/cmd/upload-gcs/BUILD.bazel
  dev/codeintel-qa/cmd/upload/BUILD.bazel
Labels: cla-signed

#61519 release: Add release test to check schema descriptions
  dev/ci/internal/ci/release_operations.go
  release.yaml
Labels: cla-signed

#61529 chore(sg): rfc flags are now position independent
  dev/sg/sg_rfc.go
Labels: sg, cla-signed

#60594 Upgrade test CLI tool
  cmd/frontend/BUILD.bazel
  cmd/migrator/BUILD.bazel
  testing/tools/upgradetest/BUILD.bazel
  testing/tools/upgradetest/README.md
  testing/tools/upgradetest/main.go
  testing/tools/upgradetest/test.sh
  testing/tools/upgradetest/tests-util.go
  testing/tools/upgradetest/tests.go
Labels: cla-signed

#61530 wolfi: add debugging and use switch for new branch
  dev/ci/scripts/wolfi/update-base-image-hashes.sh
Labels: cla-signed

#61506 v2t: add v2t to src/openCodeGraph
  client/web/src/opencodegraph/global/ToggleOpenCodeGraphVisibility.tsx
  client/web/src/repo/blob/BlobPage.tsx
Labels: cla-signed

#61514 Add maintenance APIs to Cody Gateway
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/maintenance.go
  cmd/cody-gateway/internal/httpapi/maintenance_test.go
  cmd/cody-gateway/shared/config/config.go
  cmd/cody-gateway/shared/main.go
  internal/sams/auth.go
  internal/sams/client.go
Labels: cla-signed

#61348 httpcli: add prometheus metric for monitoring the rate that Sourcegraph issues requests to external services
  CHANGELOG.md
  doc/admin/observability/dashboards.md
  internal/httpcli/client.go
  internal/httpcli/client_test.go
  monitoring/definitions/frontend.go
Labels: cla-signed, team/source, team/product-platform

#61533 Fix SAMS client configuration; make more flexible
  cmd/cody-gateway/internal/httpapi/maintenance.go
  internal/sams/client.go
Labels: cla-signed

#61426 Blob View [svelte]: Add last commit data to the blobview
  client/web-sveltekit/src/lib/Avatar.svelte
  client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
  client/web-sveltekit/src/lib/repo/LastCommit.gql
  client/web-sveltekit/src/lib/repo/LastCommit.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/layout.gql
Labels: cla-signed

#61527 svelte/ci: Run `svelte-check` in CI
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/dev/generate-graphql.ts
  client/web-sveltekit/dev/vite-graphql-codegen.ts
  client/web-sveltekit/src/lib/graphql/urql.ts
  client/web-sveltekit/src/lib/wildcard/Button.svelte
  client/web-sveltekit/src/lib/wildcard/menu/Menu.svelte
  client/web-sveltekit/src/routes/layout.gql
  client/web-sveltekit/vite.config.ts
Labels: cla-signed, team/code-search

#61510 build-tracker: deploy to MSP
  dev/build-tracker/BUILD.bazel
  dev/build-tracker/Dockerfile
  dev/build-tracker/background.go
  dev/build-tracker/build.sh
  dev/build-tracker/config/BUILD.bazel
  dev/build-tracker/config/config.go
  dev/build-tracker/image_test.yaml
  dev/build-tracker/integration_test.go
  dev/build-tracker/main.go
  dev/build-tracker/notify/slack.go
  dev/build-tracker/server_test.go
Labels: cla-signed, team/dev-infra, di/ci-obs

#61538 svelte: Upgrade to Storybook 8
  client/web-sveltekit/.storybook/main.ts
  client/web-sveltekit/.storybook/preview.ts
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/repo/HistoryPanel.stories.svelte
  client/web-sveltekit/src/routes/search/SearchResults.stories.svelte
  pnpm-lock.yaml
Labels: cla-signed, team/code-search

#61540 chore(rel): remove placeholder in release test
  release.yaml
Labels: cla-signed

#61542 build-tracker: fix BUILDTRACKER_DEBUG_PASSWORD env var key
  dev/build-tracker/config/config.go
Labels: cla-signed, team/dev-infra

#61539 Add OpenAI models to supported chat models for enterprise customers
  CHANGELOG.md
  cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql_test.go
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
Labels: cla-signed

#61543 monitoring: Make gitserver alert less trigger-friendly
  doc/admin/observability/alerts.md
  monitoring/definitions/git_server.go
Labels: cla-signed, team/source, team/product-platform

#61475 release: add sg command for sending calendar invites
  dev/release/calendar.jsonc
  dev/sg/internal/release/BUILD.bazel
  dev/sg/internal/release/calendar.go
  dev/sg/internal/release/release.go
  go.mod
Labels: cla-signed

#61549 build-tracker: fix nil pointer in old build purger & enabling auto-rollout with MSP
  dev/build-tracker/BUILD.bazel
  dev/build-tracker/background.go
  dev/build-tracker/main.go
Labels: cla-signed, di/ci-obs

#60688 Auto-update Wolfi base images to latest
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC, wolfi-auto-update

#61550 msp: look in //... for msp-deliverables, not only //cmd/...
  .aspect/workflows/config.yaml
Labels: cla-signed, managed-services-platform

#61554 build-tracker: update healthz endpoint for MSP deployment expectations
  dev/build-tracker/main.go
Labels: cla-signed, di/ci-obs

#61553 build-tracker: uncomment that which was commented
  dev/build-tracker/BUILD.bazel
Labels: cla-signed

#61532 auth/oidc: attempt to revokve SAMS session when sign out
  cmd/frontend/internal/auth/openidconnect/BUILD.bazel
  cmd/frontend/internal/auth/openidconnect/session.go
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#61572 telemetry-gateway: re-enable msp delivery
  cmd/telemetry-gateway/BUILD.bazel
Labels: cla-signed

#61547 symbols: add metrics and panels for Rockskip
  doc/admin/observability/dashboards.md
  internal/rockskip/BUILD.bazel
  internal/rockskip/index.go
  internal/rockskip/search.go
  internal/rockskip/server.go
  monitoring/definitions/symbols.go
Labels: team/search-platform, cla-signed, team/product-platform

#61578 fix(docs): no delivery if triggered without changes
  doc/_generated.push.sh
Labels: cla-signed

#61579 chore(rel): exit if no steps are defined
  dev/sg/internal/release/config.go
Labels: cla-signed

#61567 ci: make pushed images annotation collapsible
  dev/ci/push_all.sh
Labels: ci, cla-signed

#61583 Rename allowlisted PLG model
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Labels: cla-signed

#61592 sg: detect and use dockerhub registry
  dev/sg/sg_ops.go
Labels: cla-signed

#61581 Add code insight alert fix to the 5.4 CHANGELOG.md
  CHANGELOG.md
Labels: cla-signed

#61360 rfc-795: use docker hub for public releases
  dev/ci/internal/ci/release_operations.go
Labels: cla-signed

#61588 rockskip: monitor indexing queue
  doc/admin/observability/dashboards.md
  internal/rockskip/index.go
  internal/rockskip/search.go
  internal/rockskip/server.go
  monitoring/definitions/symbols.go
Labels: team/search-platform, cla-signed, team/product-platform

#61134 Adding Token counting support for bring your own key customers using Redis cache
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages_test.go
  cmd/cody-gateway/internal/httpapi/completions/flagging.go
  cmd/cody-gateway/internal/httpapi/completions/flagging_test.go
  cmd/cody-gateway/internal/tokenizer/BUILD.bazel
  cmd/cody-gateway/internal/tokenizer/tokenizer.go
  cmd/frontend/internal/bg/BUILD.bazel
  cmd/frontend/internal/bg/store_token_usage_in_postgres.go
  cmd/frontend/internal/cli/serve_cmd.go
  cmd/frontend/internal/completions/resolvers/resolver.go
  internal/completions/client/BUILD.bazel
  internal/completions/client/anthropic/BUILD.bazel
  internal/completions/client/anthropic/anthropic.go
  internal/completions/client/anthropic/anthropic_test.go
  internal/completions/client/awsbedrock/BUILD.bazel
  internal/completions/client/awsbedrock/bedrock.go
  internal/completions/client/azureopenai/BUILD.bazel
  internal/completions/client/azureopenai/openai.go
  internal/completions/client/azureopenai/openai_test.go
  internal/completions/client/client.go
  internal/completions/client/codygateway/BUILD.bazel
  internal/completions/client/codygateway/codygateway.go
  internal/completions/client/fireworks/BUILD.bazel
  internal/completions/client/fireworks/fireworks.go
  internal/completions/client/fireworks/fireworks_test.go
  internal/completions/client/observe.go
  internal/completions/client/openai/BUILD.bazel
  internal/completions/client/openai/openai.go
  internal/completions/client/openai/openai_test.go
  internal/completions/httpapi/handler.go
  internal/completions/tokenizer/BUILD.bazel
  internal/completions/tokenizer/claude.go
  internal/completions/tokenizer/claude.json
  internal/completions/tokenizer/tokenizer.go
  internal/completions/tokenizer/tokenizer_test.go
  internal/completions/tokenusage/BUILD.bazel
  internal/completions/tokenusage/tokenusage.go
  internal/completions/tokenusage/tokenusage_test.go
  internal/completions/types/types.go
  internal/rcache/rcache.go
  internal/redispool/keyvalue.go
  internal/redispool/mocks.go
  internal/telemetry/telemetry.go
  internal/updatecheck/BUILD.bazel
  internal/updatecheck/client.go
  internal/updatecheck/handler.go
  internal/updatecheck/handler_test.go
Labels: cla-signed

#61591 Read PLG embeddings limits directly from site config
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Labels: cla-signed

#61570 Cody: increase size of context snippet
  internal/codycontext/context.go
Labels: team/search-platform, cla-signed, team/product-platform

#61478 Add syntax highlighting for Pkl files
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/injections.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/locals.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/pkl.pkl
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/Cargo.toml
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/src/lib.rs
  internal/gosyntect/languages.go
  lib/codeintel/languages/extensions.go
  lib/codeintel/languages/extensions_test.go
Labels: cla-signed, team/product-platform

#61601 Adding new anthropic claude 3 models family to supported chat models for enterprise customers
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
Labels: cla-signed

#61586 Cody Gateway: Antropic messages handler returns error out if request doesn't have required "messages" field
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
Labels: cla-signed

#61614 auth: bitbucket: fix slice indexing error when constructing oauth error messages
  cmd/frontend/internal/auth/bitbucketcloudoauth/BUILD.bazel
  cmd/frontend/internal/auth/bitbucketcloudoauth/session.go
  cmd/frontend/internal/auth/bitbucketcloudoauth/session_test.go
Labels: cla-signed, team/source, team/product-platform

#61555 Svelte: Avatar size bug fix
  client/web-sveltekit/src/lib/Avatar.stories.svelte
  client/web-sveltekit/src/lib/Avatar.svelte
  client/web-sveltekit/src/lib/Commit.svelte
  client/web-sveltekit/src/lib/repo/LastCommit.stories.svelte
  client/web-sveltekit/src/lib/repo/LastCommit.svelte
  client/web-sveltekit/src/routes/UserMenu.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
  client/web-sveltekit/src/routes/search/PersonSearchResult.svelte
Labels: cla-signed

#61577 Improve git blame performance and fix previous commit location when file was renamed
  CHANGELOG.md
  client/web/src/repo/blame/useBlameHunks.ts
  client/web/src/repo/blob/BlameDecoration.tsx
  client/web/src/util/url.test.ts
  client/web/src/util/url.ts
  cmd/frontend/internal/httpapi/stream_blame.go
  cmd/gitserver/internal/git/gitcli/blame.go
  cmd/gitserver/internal/git/gitcli/blame_test.go
  internal/gitserver/gitdomain/common.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: cla-signed, team/source, team/product-platform

#61624 release: changelog update
  CHANGELOG.md
Labels: cla-signed

#61582 Revert #61209
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config/config.go
Labels: cla-signed

#61625 changelog: add header for april patch release
  CHANGELOG.md
Labels: cla-signed

#61619 msp/opentelemetry: downgrade OTEL error logs, add metrics instead
  cmd/msp-example/internal/example/BUILD.bazel
  cmd/msp-example/internal/example/example.go
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/runtime/internal/opentelemetry/BUILD.bazel
  lib/managedservicesplatform/runtime/internal/opentelemetry/metrics.go
  lib/managedservicesplatform/runtime/internal/opentelemetry/opentelemetry.go
  lib/managedservicesplatform/runtime/internal/opentelemetry/tracing.go
  lib/managedservicesplatform/runtime/service.go
Labels: cla-signed

#61620 sg/msp: retrieve service/env more consistently, provide possible values in errors
  dev/managedservicesplatform/spec/spec.go
  dev/sg/msp/helpers.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#61643 backport #61360 change of release public registry
  dev/ci/internal/ci/release_operations.go
Labels: cla-signed

#61338 Notices: Add customization for background color, text color, and text position.
  CHANGELOG.md
  client/web/src/components/DismissibleAlert/DismissibleAlert.tsx
  client/web/src/global/Notices.test.tsx
  client/web/src/global/Notices.tsx
  client/web/src/global/__snapshots__/Notices.test.tsx.snap
  client/wildcard/src/components/Alert/Alert.tsx
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#61646 Bug: fixes UI bug causing the history panel not to fill the full space
  client/web-sveltekit/src/lib/repo/LastCommit.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#61645 search jobs: fix feature flag eval in backend
  internal/search/exhaustive/service/BUILD.bazel
  internal/search/exhaustive/service/service.go
  internal/search/exhaustive/service/service_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#61648 msp/privatenetwork: allow PrivateIpGoogleAccess from subnet
  dev/managedservicesplatform/internal/resource/privatenetwork/privatenetwork.go
Labels: cla-signed

#61647 Update changelog to add Pkl highlighting update
  CHANGELOG.md
Labels: cla-signed, team/product-platform

#61651 Svelte [results indicator]: Remove timer until search completes
  client/web-sveltekit/src/lib/search/resultsIndicator/ProgressMessage.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/ProgressMessage.test.ts
  client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
Labels: cla-signed

#61512 build-tracker: trigger build-metrics pipeline on build.finished
  dev/build-tracker/BUILD.bazel
  dev/build-tracker/build/build.go
  dev/build-tracker/config/config.go
  dev/build-tracker/integration_test.go
  dev/build-tracker/main.go
  dev/build-tracker/server_test.go
Labels: cla-signed, di/ci-obs

#61649 msp/opentelemetry: fix metrics export instrumentation
  lib/managedservicesplatform/runtime/internal/opentelemetry/metrics.go
Labels: cla-signed

#61657 Svelte [ResultsIndicator]: Add 'Search Jobs' message to popover
  client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.test.ts
  client/web-sveltekit/src/routes/search/StreamingProgress.svelte
Labels: cla-signed

#61662 Svelte [bug]: adjust conditional to stay consistent with types
  client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
Labels: cla-signed

#61580 fix: allow more than 65535 repos in deny list
  CHANGELOG.md
  internal/insights/store/store.go
  internal/insights/store/store_test.go
Labels: cla-signed

#61661 web: Switch to absolute blame recency calculation
  client/web/BUILD.bazel
  client/web/src/repo/blame/useBlameHunks.ts
  client/web/src/repo/blob/blameRecency.tsx
  client/web/src/repo/blob/codemirror/blame-decorations.tsx
  client/wildcard/src/global-styles/colors.scss
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/code-search

#61552 Create syntactic_indexing module, extract job store into it
  cmd/syntactic-code-intel-worker/shared/BUILD.bazel
  cmd/syntactic-code-intel-worker/shared/indexing_worker.go
  cmd/syntactic-code-intel-worker/shared/shared.go
  cmd/syntactic-code-intel-worker/shared/store.go
  internal/codeintel/syntactic_indexing/BUILD.bazel
  internal/codeintel/syntactic_indexing/jobstore/BUILD.bazel
  internal/codeintel/syntactic_indexing/jobstore/job.go
  internal/codeintel/syntactic_indexing/jobstore/store.go
  internal/codeintel/syntactic_indexing/jobstore/store_helpers_test.go
  internal/codeintel/syntactic_indexing/jobstore/store_test.go
Labels: team/graph, cla-signed, team/product-platform

#61584 Rename Triton model in Cody Gateway
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
  cmd/cody-gateway/internal/httpapi/embeddings/sourcegraph.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/qa/e2e_test.go
  cmd/cody-gateway/shared/config/config.go
Labels: cla-signed

#61420 Use simple projects endpoint for GItLab permissions syncing
  cmd/worker/internal/authz/testdata/vcr/TestIntegration_GitLabPermissions/test_gitLabProjectVisibilityExperimental_feature_flag.yaml
  internal/authz/providers/gitlab/oauth_test.go
  internal/authz/providers/gitlab/sudo.go
  internal/authz/providers/gitlab/sudo_test.go
Labels: cla-signed, team/source, team/product-platform

#61683 backport: remove patch version check
  dev/sg/sg_backport.go
Labels: cla-signed

#60510 bazel: bump rules_{oci,pkg}
  WORKSPACE
  cmd/server/macro.bzl
Labels: cla-signed, bazel

#61640 Syntactic indexing support in policy matcher
  internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
  internal/codeintel/policies/internal/store/configurations.go
  internal/codeintel/policies/internal/store/configurations_test.go
  internal/codeintel/policies/shared/types.go
  internal/codeintel/policies/transport/graphql/root_resolver_policy_queries.go
Labels: team/graph, cla-signed, team/product-platform

#61686 logging: remove use of log15 in uploadstore
  internal/uploadstore/BUILD.bazel
  internal/uploadstore/gcs_client.go
  internal/uploadstore/store_test.go
Labels: cla-signed

#61536 Add support for naming repo explicitly for Bitbucket Cloud
  CHANGELOG.md
  internal/repos/bitbucketcloud.go
  internal/repos/bitbucketcloud_test.go
  internal/repos/testdata/sources/BITBUCKETCLOUD-LIST-REPOS/with-repos.yaml
  schema/bitbucket_cloud.schema.json
  schema/schema.go
Labels: cla-signed, team/source, team/product-platform

#61699 Searcher: remove stray comment
  internal/search/job/jobutil/job.go
Labels: team/search-platform, cla-signed, team/product-platform

#61679 msp/project: enable accesscontextmanager APIs
  dev/managedservicesplatform/stacks/project/project.go
Labels: cla-signed

#61503 v2t: add v2t to notebooks
  client/web/src/notebooks/GlobalNotebooksArea.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.story.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
  client/web/src/notebooks/createPage/CreateNotebookPage.tsx
  client/web/src/notebooks/index.ts
  client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
  client/web/src/notebooks/listPage/NotebooksList.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.story.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/notebooks/listPage/NotebooksListPageHeader.tsx
  client/web/src/notebooks/notebook/NotebookComponent.story.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebookPage/DeleteNotebookModal.tsx
  client/web/src/notebooks/notebookPage/EmbeddedNotebookPage.tsx
  client/web/src/notebooks/notebookPage/NotebookContent.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/notebooks/notebookPage/NotebookPageHeaderActions.tsx
  client/web/src/notebooks/notebookPage/NotebookShareOptionsDropdown.tsx
  client/web/src/notebooks/notebookPage/NotebookTitle.tsx
  client/web/src/notebooks/notebookPage/ShareNotebookModal.tsx
  client/web/src/routes.tsx
Labels: cla-signed

#61697 sg msp: add interactive version of 'sg msp init' and 'sg msp init-env'
  dev/sg/internal/std/BUILD.bazel
  dev/sg/internal/std/prompt.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#61658 nix: build pg-utils with nix & upload to GCS
  .github/workflows/pg-utils.yml
  dev/nix/pg-utils.nix
  flake.nix
Labels: nix, cla-signed

#61715 Adding an extra field for the tokenizer computed tokens for Anthropic API
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#61718 symbols: remove unused channel parseRequests
  cmd/symbols/parser/parser.go
Labels: team/search-platform, cla-signed, team/product-platform

#61701 Symbols: Remove unused ctags config
  cmd/symbols/internal/api/handler.go
  cmd/symbols/internal/api/handler_test.go
  cmd/symbols/shared/main.go
  cmd/symbols/shared/setup.go
  cmd/symbols/shared/sqlite.go
Labels: team/search-platform, cla-signed, team/product-platform

#61663 Context: remove key words from stopwords
  internal/search/codycontext/query_transformer_test.go
  internal/search/codycontext/stop_words.go
Labels: team/search-platform, cla-signed, team/product-platform

#61726 observation: use pedantic prometheus registry for TestContextTB
  internal/observation/context.go
Labels: team/search-platform, cla-signed, team/product-platform

#61664 Context: match on filename
  internal/codycontext/BUILD.bazel
  internal/codycontext/context.go
  internal/codycontext/context_test.go
  internal/search/codycontext/query_transformer.go
  internal/search/codycontext/query_transformer_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#61728 schema: remove non-determinism from TestSchemaValidationUUID
  schema/validation_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#61733 svelte: Fix file view text selection issue
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/routes/search/PreviewPanel.svelte
Labels: cla-signed, team/code-search

#61736 web: Fix blame recency color "direction"
  client/web/src/repo/blob/codemirror/blame-decorations.tsx
Labels: cla-signed, team/code-search

#61737 rbac: check for undefined permissions in PermissionsList
  client/web/src/enterprise/rbac/components/Permissions.story.tsx
  client/web/src/enterprise/rbac/components/Permissions.tsx
Labels: cla-signed

#61484 Trigger AMI Pipeline on release
  .github/workflows/release-amis.yml
Labels: cla-signed

#61739 release: move release caalendar config
  dev/sg/internal/release/calendar.go
  tools/release/config/calendar.jsonc
Labels: cla-signed

#61734 nix: build pg-utils with nix [static edition]
  dev/nix/pg-utils.nix
  flake.nix
Labels: nix, cla-signed

#61220 release: drop legacy release tooling
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  .bazelignore
  .prettierignore
  .vscode/settings.json
  .vscode/tasks.json
  dev/ci/internal/ci/changed/diff.go
  dev/foreach-non-web-client-project.sh
  dev/release/.eslintrc.js
  dev/release/.gitignore
  dev/release/.yarn/install-state.gz
  dev/release/README.md
  dev/release/package.json
  dev/release/src/batchChanges.ts
  dev/release/src/changelog.ts
  dev/release/src/chart.ts
  dev/release/src/config.ts
  dev/release/src/git.ts
  dev/release/src/github.ts
  dev/release/src/google-calendar.ts
  dev/release/src/main.ts
  dev/release/src/release.ts
  dev/release/src/slack.ts
  dev/release/src/static-updates.ts
  dev/release/src/update.ts
  dev/release/src/util.ts
  dev/release/templates/patch_release_issue_template.md
  dev/release/templates/release_issue_template.md
  dev/release/templates/security_assessment.md
  dev/release/testdata/test-batch-change-import.json
  dev/release/tsconfig.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: cla-signed

#61742 database: Format metadata as multiline string
  internal/database/dbconn/dynamic_metadata.go
Labels: cla-signed, team/source, team/product-platform

#61724 svelte: Show correct last commit information
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
Labels: bug, cla-signed

#61719 symbols: canceling ParseRequest does not spam logs
  cmd/symbols/parser/BUILD.bazel
  cmd/symbols/parser/observability.go
  cmd/symbols/parser/observability_test.go
  cmd/symbols/parser/parser.go
Labels: team/search-platform, cla-signed, team/product-platform

#61681 search: wrap structural search with repoPagerRob
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/job/jobutil/repo_pager_job.go
  internal/search/structural/BUILD.bazel
  internal/search/structural/structural.go
Labels: team/search-platform, cla-signed, team/product-platform

#61753 Cody PLG: Add GPT 4 Turbo GA version identifiers
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/httpapi/chat.go
  internal/conf/computed.go
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
Labels: cla-signed

#61752 streaming: only call flush if writes succeeded
  internal/search/streaming/http/writer.go
Labels: team/search-platform, cla-signed, team/product-platform, backport 5.3.9104

#61757 ci: set timeouts - gazelle 5 min and buildifier to 2 min
  .aspect/workflows/config.yaml
Labels: cla-signed

#61615 Remove clone progress DB experiment
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
  client/web/src/site-admin/backend.ts
  client/web/src/site-admin/components/RepoMirrorInfo.tsx
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/repository_mirror_test.go
  cmd/gitserver/internal/BUILD.bazel
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_test.go
  internal/database/dbmocks/mocks_temp.go
  internal/database/gitserver_repos.go
  internal/database/gitserver_repos_test.go
  internal/types/types.go
Labels: cla-signed, team/source, team/product-platform

#61725 gitserver: Match paths in ArchiveReader validation literally
  cmd/gitserver/internal/git/gitcli/archivereader.go
Labels: cla-signed, team/source, team/product-platform

#61759 svelte: Show favicon in production
  client/web-sveltekit/src/app.prod.html
Labels: cla-signed, team/code-search

#61723 svelte: Redesign file header
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
  client/web-sveltekit/src/lib/repo/FileIcon.gql
  client/web-sveltekit/src/lib/repo/FileIcon.svelte
  client/web-sveltekit/src/lib/repo/Permalink.svelte
  client/web-sveltekit/src/lib/repo/api/tree.gql
  client/web-sveltekit/src/lib/repo/shared/codehost.ts
  client/web-sveltekit/src/lib/search/CodeHostIcon.svelte
  client/web-sveltekit/src/lib/utils/formatting.test.ts
  client/web-sveltekit/src/lib/utils/formatting.ts
  client/web-sveltekit/src/lib/utils/index.ts
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/lib/wildcard/menu/DropdownMenu.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuButton.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuLink.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuRadioGroup.svelte
  client/web-sveltekit/src/lib/wildcard/menu/MenuSeparator.svelte
  client/web-sveltekit/src/lib/wildcard/menu/Submenu.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileViewModeSwitcher.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FormatAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/OpenInCodeHostAction.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/OpenInCodeHostAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/util.test.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/util.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+error.svelte
  client/web-sveltekit/vite.config.ts
Labels: cla-signed

#61670 gitserver: Don't reclone repos every 45 days
  cmd/gitserver/internal/cleanup.go
  cmd/gitserver/internal/cleanup_test.go
  cmd/gitserver/shared/shared.go
Labels: cla-signed, team/source, team/product-platform

#61766 Revert "bazel: bump rules_{oci,pkg}"
  WORKSPACE
  cmd/server/macro.bzl
Labels: cla-signed

#61767 ci: temporary mitigation - make backcompat soft fail on exit code 1
  .buildkite/pipeline.backcompat.yml
Labels: cla-signed

#61720 code-search: fix vertical alignment in search results list
  client/web-sveltekit/src/routes/search/RepoRev.svelte
Labels: cla-signed

#61763 Cody PLG: add identifier for Fireworks Mixtral-8x22b model
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/completions/client/fireworks/fireworks.go
  internal/completions/httpapi/chat.go
Labels: cla-signed

#61706 cmd/appliance: Add appliance service boilerplate / stub the service
  cmd/appliance/BUILD.bazel
  cmd/appliance/README.md
  cmd/appliance/main.go
  cmd/appliance/shared/BUILD.bazel
  cmd/appliance/shared/config.go
  cmd/appliance/shared/main.go
  cmd/appliance/shared/service.go
  cmd/executor/internal/worker/command/kubernetes.go
  deps.bzl
  go.mod
  go.sum
  internal/appliance/BUILD.bazel
  internal/appliance/spec.go
  internal/k8s/resource/pvc/pvc.go
  internal/k8s/resource/pvc/pvc_test.go
  internal/k8s/resource/statefulset/statefulset_test.go
Labels: cla-signed

#61769 chore: Bump autoindexing image SHAs
  internal/codeintel/autoindexing/internal/inference/libs/indexes.go
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Gradle.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Maven.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_SBT.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_lsif-java.json.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_WITHOUT_top-level_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_with_top-level_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_files_in_root.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_modules.yaml
Labels: team/graph, cla-signed, team/product-platform

#61732 symbols: avoid spamming handleParseRequest on context cancelation
  cmd/symbols/parser/parser.go
Labels: team/search-platform, cla-signed, team/product-platform

#61668 Improving tokenization for OpenAI models and stop claude 3 tokenization
  internal/completions/client/azureopenai/openai.go
  internal/completions/client/openai/openai.go
  internal/completions/tokenizer/BUILD.bazel
  internal/completions/tokenizer/claude.go
  internal/completions/tokenizer/tokenizer.go
  internal/completions/tokenusage/BUILD.bazel
  internal/completions/tokenusage/tokenusage.go
  internal/completions/tokenusage/tokenusage_test.go
Labels: cla-signed

#61773 backport: fix gen pipeline
  .buildkite/pipeline.backcompat.yml
  dev/ci/internal/ci/config.go
Labels: cla-signed

#61775 chore(sg+ci): remove doc changes protection
  dev/ci/internal/ci/changed/linters.go
  dev/sg/linters/BUILD.bazel
  dev/sg/linters/doc_changes.go
  dev/sg/linters/linters.go
Labels: cla-signed

#61778 IGNORE ME: debug screaming
  dev/ci/internal/ci/config.go
Labels: cla-signed

#61777 pipeline: more pipeline config fixes
  dev/ci/internal/ci/config.go
Labels: cla-signed

#61779 Revert "chore(sg): rfc flags are now position independent"
  dev/sg/sg_rfc.go
Labels: cla-signed

#61760 test execution log artifact
  .aspect/bazelrc/ci.sourcegraph.bazelrc
Labels: ci, cla-signed, bazel

#61783 ci: disable emitting execution log for bazel
  .aspect/bazelrc/ci.sourcegraph.bazelrc
Labels: cla-signed, bazel

#61671 gitserver: Remove RepoClone gRPC API
  cmd/frontend/backend/mocks_temp.go
  cmd/frontend/backend/repos.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/gitserver/internal/mocks_test.go
  cmd/gitserver/internal/server_grpc.go
  internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/errwrap.go
  internal/gitserver/mock.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/observability.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/retry.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
Labels: cla-signed, team/source, team/product-platform

#61774 svelte: Refactor search cache URL parameter processing
  client/web-sveltekit/src/lib/search/constants.ts
  client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
  client/web-sveltekit/src/lib/search/state.ts
  client/web-sveltekit/src/routes/search/+page.ts
Labels: cla-signed, team/code-search

#61765 Cody Gateway: correct Triton embeddings dimension
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
Labels: team/search-platform, cla-signed, team/product-platform

#61786 Update docs for adding syntax highlighting
  doc/dev/how-to/add_support_for_a_language.md
Labels: cla-signed, team/product-platform

#61764 ci: publish release images to public artifact registry
  dev/ci/images/images.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/push_all.sh
Labels: cla-signed

#61784 Move Gateway Rate Limit Status to dotcom resolver
  cmd/frontend/graphqlbackend/cody_gateway_rate_limit.go
  cmd/frontend/graphqlbackend/dotcom.go
  cmd/frontend/graphqlbackend/dotcom.graphql
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Labels: cla-signed

#61788 bazel: migrate dind dockerfile to rules_oci
  WORKSPACE
  dev/bazel_stamp_vars.sh
  dev/oci_deps.bzl
  docker-images/dind/BUILD.bazel
  docker-images/dind/Dockerfile
  docker-images/dind/build.sh
Labels: ci, cla-signed, bazel

#61789 Revert "ci: publish release images to public artifact registry"
  dev/ci/images/images.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/push_all.sh
Labels: cla-signed

#61790 Revert "bazel: migrate dind dockerfile to rules_oci"
  WORKSPACE
  dev/bazel_stamp_vars.sh
  dev/oci_deps.bzl
  docker-images/dind/BUILD.bazel
  docker-images/dind/Dockerfile
  docker-images/dind/build.sh
Labels: cla-signed

#61672 gitserver: Don't trigger clones in hot requests
  cmd/gitserver/internal/BUILD.bazel
  cmd/gitserver/internal/clone.go
  cmd/gitserver/internal/mocks_test.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_test.go
  cmd/gitserver/internal/server_test.go
  mockgen.test.yaml
Labels: cla-signed, team/source, team/product-platform

#61787 sec: emit security event for RBAC changes
  cmd/frontend/internal/rbac/resolvers/resolver.go
  internal/database/security_event_logs.go
Labels: cla-signed

#61741 bazel: use pgutil binaries from GCS instead of from the host
  dev/BUILD.bazel
  dev/migrations.bzl
  dev/sg/dependencies/BUILD.bazel
  dev/sg/dependencies/helpers.go
  dev/sg/dependencies/mac.go
  dev/sg/internal/migration/squash.go
  dev/sg/internal/run/helpers.go
  dev/tool_deps.bzl
  dev/tools/BUILD.bazel
  shell.nix
Labels: cla-signed, bazel

#61464 bazel: include zoekt version stamp in github.com/sourcegraph/zoekt.Version
  deps.bzl
  dev/bazel_stamp_vars.sh
  third_party/com_github_sourcegraph_zoekt/BUILD.bazel
  third_party/com_github_sourcegraph_zoekt/x_defs_version.patch
  third_party/com_github_sourcegraph_zoekt/zoekt_archive_index.patch
  third_party/com_github_sourcegraph_zoekt/zoekt_git_index.patch
  third_party/com_github_sourcegraph_zoekt/zoekt_indexserver.patch
  third_party/com_github_sourcegraph_zoekt/zoekt_webserver.patch
  third_party/com_github_strum355_gomockgen/BUILD.bazel
  third_party/com_github_strum355_gomockgen/debug.patch
Labels: zoekt, cla-signed, bazel

#61673 gitserver: Simplify clone
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_test.go
  cmd/gitserver/shared/shared.go
Labels: cla-signed, team/source, team/product-platform

#61802 sg: install postgres 12 instead of 15
  dev/sg/dependencies/mac.go
Labels: sg, cla-signed

#61674 gitserver: Move gitservice off of server struct
  cmd/gitserver/internal/gitservice.go
  cmd/gitserver/internal/integration_tests/clone_test.go
  cmd/gitserver/internal/integration_tests/resolverevisions_test.go
  cmd/gitserver/internal/integration_tests/test_utils.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/shared/shared.go
Labels: cla-signed, team/source, team/product-platform

#61746 Svelte: Implements the RepoPopover component
  client/web-sveltekit/src/lib/Timestamp.svelte
  client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.gql
  client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.stories.svelte
  client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte
  client/web-sveltekit/src/lib/repo/RepoStars.svelte
  client/web-sveltekit/src/routes/search/CommitSearchResult.svelte
  client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
  client/web-sveltekit/src/routes/search/FilePathSearchResult.svelte
  client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
  client/web-sveltekit/src/routes/search/RepoStars.svelte
  client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
Labels: cla-signed

#61675 gitserver: Light code cleanup
  cmd/gitserver/internal/BUILD.bazel
  cmd/gitserver/internal/main_test.go
  cmd/gitserver/internal/patch.go
  cmd/gitserver/internal/search.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/servermetrics.go
  cmd/gitserver/shared/shared.go
Labels: cla-signed, team/source, team/product-platform

#61805 Sveltekit: implement new avatar design
  client/web-sveltekit/src/lib/Avatar.stories.svelte
  client/web-sveltekit/src/lib/Avatar.svelte
Labels: cla-signed

#61676 gitserver: Remove double negation for ensure revision
  cmd/frontend/backend/repos.go
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_commits.go
  cmd/frontend/graphqlbackend/git_revision.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_comparison.go
  cmd/frontend/graphqlbackend/repository_text_search_index.go
  cmd/frontend/internal/httpapi/search.go
  cmd/gitserver/internal/integration_tests/resolverevisions_test.go
  internal/batches/service/workspace_resolver.go
  internal/batches/state/state.go
  internal/codeintel/autoindexing/internal/enqueuer/enqueuer.go
  internal/codeintel/shared/resolvers/gitresolvers/cached_resolvers.go
  internal/codeintel/uploads/internal/background/janitor/job_cleanup.go
  internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
  internal/codemonitors/search.go
  internal/gitserver/commands.go
  internal/own/background/analytics.go
  internal/search/repos/repos.go
  internal/search/searcher/search.go
  internal/search/searcher/symbol_search_job.go
Labels: cla-signed, team/source, team/product-platform

#61708 vscsyncer: introduce syncer wrapper which calculates latencies for all operations
  CHANGELOG.md
  cmd/gitserver/internal/vcssyncer/BUILD.bazel
  cmd/gitserver/internal/vcssyncer/instrumented_syncer.go
  cmd/gitserver/internal/vcssyncer/syncer.go
  doc/admin/observability/dashboards.md
  monitoring/definitions/BUILD.bazel
  monitoring/definitions/git_server.go
Labels: cla-signed, team/source, team/product-platform

#61803 Revert "Revert "ci: publish release images to public artifact registry""
  dev/ci/images/images.go
  dev/ci/internal/ci/images_operations.go
  dev/ci/push_all.sh
Labels: cla-signed

#61677 Move accessrequest package to frontend
  cmd/frontend/internal/app/BUILD.bazel
  cmd/frontend/internal/app/app.go
  cmd/frontend/internal/auth/accessrequest/BUILD.bazel
  cmd/frontend/internal/auth/accessrequest/handlers.go
  cmd/frontend/internal/auth/accessrequest/handlers_test.go
Labels: cla-signed, team/source, team/product-platform

#61678 Move scim package to frontend
  cmd/frontend/internal/auth/scim/BUILD.bazel
  cmd/frontend/internal/auth/scim/filter/BUILD.bazel
  cmd/frontend/internal/auth/scim/filter/filter.go
  cmd/frontend/internal/auth/scim/filter/filter_test.go
  cmd/frontend/internal/auth/scim/filter/op_binary.go
  cmd/frontend/internal/auth/scim/filter/op_boolean.go
  cmd/frontend/internal/auth/scim/filter/op_boolean_test.go
  cmd/frontend/internal/auth/scim/filter/op_datetime.go
  cmd/frontend/internal/auth/scim/filter/op_datetime_test.go
  cmd/frontend/internal/auth/scim/filter/op_decimal.go
  cmd/frontend/internal/auth/scim/filter/op_decimal_test.go
  cmd/frontend/internal/auth/scim/filter/op_integer.go
  cmd/frontend/internal/auth/scim/filter/op_integer_test.go
  cmd/frontend/internal/auth/scim/filter/op_string.go
  cmd/frontend/internal/auth/scim/filter/op_string_test.go
  cmd/frontend/internal/auth/scim/filter/operators.go
  cmd/frontend/internal/auth/scim/filter/operators_test.go
  cmd/frontend/internal/auth/scim/filter/path.go
  cmd/frontend/internal/auth/scim/init.go
  cmd/frontend/internal/auth/scim/init_test.go
  cmd/frontend/internal/auth/scim/mock_db.go
  cmd/frontend/internal/auth/scim/resourceHandler.go
  cmd/frontend/internal/auth/scim/resource_create.go
  cmd/frontend/internal/auth/scim/resource_delete.go
  cmd/frontend/internal/auth/scim/resource_get.go
  cmd/frontend/internal/auth/scim/resource_patch.go
  cmd/frontend/internal/auth/scim/resource_replace.go
  cmd/frontend/internal/auth/scim/test_util.go
  cmd/frontend/internal/auth/scim/user.go
  cmd/frontend/internal/auth/scim/user_create_test.go
  cmd/frontend/internal/auth/scim/user_get_test.go
  cmd/frontend/internal/auth/scim/user_patch_test.go
  cmd/frontend/internal/auth/scim/user_replace_test.go
  cmd/frontend/internal/auth/scim/user_schema.go
  cmd/frontend/internal/auth/scim/user_service.go
  cmd/frontend/internal/auth/scim/user_update_action.go
  cmd/frontend/internal/scim/BUILD.bazel
  cmd/frontend/internal/scim/scim.go
Labels: cla-signed, team/source, team/product-platform

#61810 conf: Move most confvalidators into common package
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/site_alerts.go
  cmd/frontend/graphqlbackend/site_config_change_connection_test.go
  cmd/frontend/internal/app/BUILD.bazel
  cmd/frontend/internal/app/debug.go
  cmd/frontend/internal/app/debug_test.go
  cmd/frontend/internal/authz/init.go
  cmd/frontend/internal/batches/BUILD.bazel
  cmd/frontend/internal/batches/init.go
  cmd/symbols/parser/BUILD.bazel
  cmd/symbols/parser/config.go
  internal/auth/userpasswd/BUILD.bazel
  internal/auth/userpasswd/config.go
  internal/auth/userpasswd/config_test.go
  internal/auth/validateconf/BUILD.bazel
  internal/auth/validateconf/config.go
  internal/cody/feature_flag.go
  internal/conf/BUILD.bazel
  internal/conf/reposource/BUILD.bazel
  internal/conf/reposource/custom.go
  internal/conf/validate_custom.go
  internal/conf/validation/BUILD.bazel
  internal/conf/validation/app.go
  internal/conf/validation/auth.go
  internal/conf/validation/auth_test.go
  internal/conf/validation/batches.go
  internal/conf/validation/cody.go
  internal/conf/validation/encryption.go
  internal/conf/validation/highlight.go
  internal/conf/validation/licensing.go
  internal/conf/validation/prometheus.go
  internal/conf/validation/prometheus_test.go
  internal/conf/validation/reposource.go
  internal/conf/validation/session.go
  internal/conf/validation/symbols.go
  internal/conf/validation/trace.go
  internal/conf/validation/txemail.go
  internal/conf/validation/txemail_test.go
  internal/conf/validation/validation.go
  internal/encryption/keyring/BUILD.bazel
  internal/encryption/keyring/ring.go
  internal/highlight/BUILD.bazel
  internal/highlight/language.go
  internal/licensing/BUILD.bazel
  internal/licensing/licensing.go
  internal/licensing/plans.go
  internal/licensing/plans_test.go
  internal/session/BUILD.bazel
  internal/session/session.go
  internal/tracer/BUILD.bazel
  internal/tracer/tracer.go
  internal/txemail/BUILD.bazel
  internal/txemail/siteconfig.go
Labels: cla-signed, team/source, team/product-platform
