Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-01, with the labels that each got.

#59214 Add slack webhook notifications on license creation
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#59266 Minor refactoring and remove redundant checks
  cmd/frontend/auth/user.go
  internal/security/security.go
Labels: cla-signed, team/source

#59243 Add logic to auto disable google signups from non-gmail domain for 24hrs if too many signups from same domain.
  cmd/frontend/auth/BUILD.bazel
  cmd/frontend/auth/user.go
  internal/security/BUILD.bazel
  internal/security/security.go
  internal/telemetry/events.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#59268 Mock current time for stability
  client/branded/src/components/Timestamp/Timestamp.test.tsx
Labels: cla-signed

#59215 bazel: migrate go:generate for staticcheck
  dev/BUILD.bazel
  dev/linters/staticcheck/BUILD.bazel
  dev/linters/staticcheck/cmd/gen.go
  dev/linters/staticcheck/staticcheck.go
  dev/linters/staticcheck/targets.bzl
Labels: cla-signed, bazel, dev-infra/go-generate

#59203 chore: upgrade to Aspect CLI 5.8.19
  .bazeliskrc
  client/browser/BUILD.bazel
  client/shared/BUILD.bazel
  client/shared/src/testing/BUILD.bazel
  client/web/src/regression/BUILD.bazel
Labels: cla-signed

#58803 bzl: remove go:generate remnants (already migrated)
  internal/database/BUILD.bazel
  internal/database/gen.go
  internal/database/gen.sh
Labels: cla-signed

#59240 bazel: update rules-rust to 0.34.1
  WORKSPACE
  docker-images/syntax-highlighter/Cargo.Bazel.lock
Labels: cla-signed

#59278 depguard: only allow github.com/sourcegraph/sourcegraph/lib/pointers
  cmd/executor/internal/run/BUILD.bazel
  cmd/executor/internal/run/util.go
  cmd/executor/internal/worker/command/BUILD.bazel
  cmd/executor/internal/worker/command/kubernetes.go
  dev/linters/depguard/depguard.go
Labels: cla-signed, bazel

#59239 bazel: update rules-go to 0.44
  WORKSPACE
Labels: cla-signed

#59279 sg: clarify setup restart message
  dev/sg/dependencies/mac.go
  dev/sg/dependencies/ubuntu.go
Labels: cla-signed

#59264 Notebooks: fix highlighted code
  client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
Labels: cla-signed

#59280 nix: use interactive bash instead of non-interactive in shell
  dev/nix/nodejs.nix
  flake.lock
  shell.nix
Labels: nix, cla-signed

#59246 cody-gateway: include operation name as query param
  cmd/cody-gateway/internal/dotcom/BUILD.bazel
  cmd/cody-gateway/internal/dotcom/dotcom.go
  cmd/cody-gateway/internal/dotcom/dotcom_test.go
Labels: cla-signed

#59286 msp/runtime: add checks to detect capabilities
  lib/managedservicesplatform/runtime/contract_bigquery.go
  lib/managedservicesplatform/runtime/contract_postgresql.go
Labels: cla-signed

#59289 msp/monitoring: fix redis alert
  dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
Labels: cla-signed

#59290 monitoring: improve registerObservableOwner and TestOwner docstrings
  monitoring/monitoring/owners.go
  monitoring/monitoring/owners_test.go
Labels: cla-signed

#59292 productsubscription: fix panic on license creation
  cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
Labels: cla-signed

#58526 ci: remove svgo
  dev/ci/internal/ci/changed/linters.go
  dev/sg/linters/BUILD.bazel
  dev/sg/linters/linters.go
  dev/sg/linters/svg.go
  package.json
  pnpm-lock.yaml
  svgo.config.js
Labels: cla-signed

#59263 Gateway attribution handler
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/attribution/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/attribution/handler.go
  cmd/cody-gateway/internal/httpapi/attribution/handler_test.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/BUILD.bazel
  cmd/cody-gateway/shared/config.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#58924 New implementation for tree-sitter based local detection
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/README.md
  docker-images/syntax-highlighter/crates/scip-syntax/docs/locals-query-dsl.md
  docker-images/syntax-highlighter/crates/scip-syntax/docs/locals-scoping.md
  docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/java/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/matlab/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/perl/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/bin/scip-local-nav.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/bin/scip-perf.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__globals__test__can_parse_javascript_object.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__globals__test__can_parse_javascript_tree.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__globals__test__can_parse_ruby_internal_tree.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_java-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_matlab-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_matlab.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_nested_locals-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_nested_locals.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_perl-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_perl.snap
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/index.rs
  docker-images/syntax-highlighter/crates/scip-treesitter/src/lib.rs
  docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
Labels: cla-signed

#59186 Fix reset password link input cut off
  client/web/src/site-admin/UserManagement/components/UsersList.tsx
  client/web/src/site-admin/UserManagement/components/useUserListActions.tsx
  client/web/src/site-admin/components/AccountCreatedAlert.tsx
Labels: cla-signed, team/source

#59300 ci: fix typo in executor op
  dev/ci/internal/ci/executor_operations.go
Labels: cla-signed

#59301 Fix broken test due to 3rd parties licenses update
  cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
Labels: cla-signed

#59288 Search: remove TextPatternInfo.IsWordMatch
  cmd/searcher/internal/search/matcher.go
  cmd/searcher/internal/search/search.go
  cmd/searcher/internal/search/search_structural.go
  cmd/searcher/internal/search/search_test.go
  cmd/searcher/protocol/searcher.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/searcher/client.go
  internal/search/searcher/client_grpc.go
  internal/search/types.go
  internal/searcher/v1/searcher.pb.go
  internal/searcher/v1/searcher.proto
Labels: cla-signed

#59178 Search Results: Add new filters panel
  client/branded/BUILD.bazel
  client/branded/src/search-ui/index.ts
  client/branded/src/search-ui/input/codemirror/completion.test.ts
  client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
  client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
  client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.tsx
  client/branded/src/search-ui/results/filters/hooks.ts
  client/branded/src/search-ui/results/filters/types.ts
  client/branded/src/search-ui/results/filters/utils.ts
  client/browser/src/shared/code-hosts/gitlab/scrape.ts
  client/common/BUILD.bazel
  client/common/src/index.ts
  client/common/src/languages.ts
  client/shared/src/backend/repo.ts
  client/shared/src/search/query/filters.ts
  client/shared/src/search/query/languageFilter.test.ts
  client/shared/src/search/query/languageFilter.ts
  client/shared/src/search/query/scanner.ts
  client/shared/src/search/query/transformer.ts
  client/shared/src/search/stream.ts
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web/BUILD.bazel
  client/web/src/integration/graphQlResponseHelpers.ts
  client/web/src/integration/repository.test.ts
  client/web/src/repo/RepoRevisionSidebarFileTree.module.scss
  client/web/src/repo/RepoRevisionSidebarFileTree.tsx
  client/web/src/repo/fileIcons.test.ts
  client/web/src/repo/fileIcons.ts
  client/web/src/repo/icon-utils.test.ts
  client/web/src/repo/icon-utils.ts
  client/web/src/repo/tree/TreePagePanels.tsx
  client/web/src/search/autocompletion/hooks.ts
  client/web/src/search/results/SearchResultsCacheProvider.tsx
  client/web/src/search/results/StreamingSearchResults.tsx
  client/web/src/search/results/components/aggregation/hooks.ts
  client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
  client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx
  client/web/src/search/suggestion/DidYouMean.tsx
  client/wildcard/BUILD.bazel
  client/wildcard/src/components/Icon/index.ts
  client/wildcard/src/components/Icon/language-icon/LanguageIcon.module.scss
  client/wildcard/src/components/Icon/language-icon/LanguageIcon.tsx
  client/wildcard/src/components/Icon/language-icon/language-icons.test.ts
  client/wildcard/src/components/Icon/language-icon/language-icons.ts
  client/wildcard/src/components/index.ts
  client/wildcard/src/hooks/index.ts
  client/wildcard/src/hooks/useSyncedWithUrlState.ts
  schema/schema.go
  schema/settings.schema.json
Labels: cla-signed

#59303 syntax-highlighter: bump serde to version that works with bazel
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
Labels: cla-signed, bazel, syntax-highlighter

#59311 productsubscription: stabilize license notification test
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
Labels: cla-signed

#59245 Using new function for security even logs
  cmd/frontend/backend/user_emails.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/orgs.go
  cmd/frontend/graphqlbackend/site_admin.go
  cmd/frontend/graphqlbackend/site_admin_test.go
  cmd/frontend/internal/app/sign_out.go
  cmd/frontend/internal/app/verify_email.go
  cmd/frontend/internal/auth/oauth/session.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/middleware_test.go
  cmd/frontend/internal/auth/sourcegraphoperator/middleware.go
  cmd/frontend/internal/httpapi/auth.go
  cmd/frontend/internal/httpapi/auth_test.go
  internal/auth/userpasswd/handlers.go
  internal/auth/userpasswd/reset_password.go
  internal/database/BUILD.bazel
  internal/database/access_tokens.go
  internal/database/external_accounts.go
  internal/database/repos.go
  internal/database/security_event_logs.go
  internal/database/security_event_logs_test.go
  internal/database/users.go
Labels: cla-signed, SSDLC

#59302 fixing error handling
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
Labels: cla-signed

#59257 msp: provision notification channels by requiring Opsgenie teams and Slack channels
  deps.bzl
  dev/managedservicesplatform/googlesecretsmanager/googlesecretsmanager.go
  dev/managedservicesplatform/internal/resource/alertpolicy/BUILD.bazel
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy_test.go
  dev/managedservicesplatform/internal/stack/monitoring/BUILD.bazel
  dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
  dev/managedservicesplatform/internal/stack/options/opsgenieprovider/BUILD.bazel
  dev/managedservicesplatform/internal/stack/options/opsgenieprovider/opsgenieprovider.go
  dev/managedservicesplatform/internal/stack/options/slackprovider/BUILD.bazel
  dev/managedservicesplatform/internal/stack/options/slackprovider/slackprovider.go
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/spec/service.go
  go.mod
  go.sum
Labels: cla-signed

#59314 msp: base startup latency alert on probe, add docstring and labels
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
  dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/spec/monitoring.go
Labels: cla-signed

#59317 gitserver: Update out-of-date doc comment for ReadFile
  internal/gitserver/client.go
  internal/gitserver/commands.go
Labels: cla-signed

#59192 Fix overflowing of clone progress
  client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.story.tsx
  client/web/src/enterprise/user/settings/auth/__snapshots__/UserSettingsPermissionsPage.test.tsx.snap
  client/web/src/repo/settings/RepoSettingsMirrorPage.story.tsx
  client/web/src/repo/settings/RepoSettingsMirrorPage.tsx
  client/web/src/repo/settings/components/ActionContainer.module.scss
  client/web/src/repo/settings/components/ActionContainer.tsx
Labels: cla-signed, team/source

#59319 Syntax highlight package.json files
  cmd/frontend/graphqlbackend/git_tree_entry.go
Labels: cla-signed

#59085 ci: enable chromatic again and update chromatic to latest
  dev/ci/internal/ci/client_operations.go
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#59327 nix: bump to bazel 7
  flake.lock
  shell.nix
Labels: nix, cla-signed

#59267 Adjust license anomalies checks
  cmd/frontend/internal/dotcom/productsubscription/license_anomaly.go
  cmd/frontend/internal/dotcom/productsubscription/license_anomaly_test.go
  cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go
  cmd/frontend/internal/dotcom/productsubscription/license_check_handler_test.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
  cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
  internal/types/types.go
Labels: cla-signed, team/source

#59321 Add rate limit information to RateLimited events
  cmd/cody-gateway/internal/events/events.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
  cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
Labels: cla-signed

#59312 Svelte: add topic badges to repo search results
  client/web-sveltekit/src/lib/search/results.ts
  client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
Labels: cla-signed

#59318 codeintel: Refine language detection for extensions
  client/wildcard/src/components/Icon/language-icon/language-icons.ts
  lib/codeintel/languages/BUILD.bazel
  lib/codeintel/languages/extensions.go
  lib/codeintel/languages/extensions_test.go
  lib/codeintel/languages/languages.go
Labels: cla-signed

#59293 ci: cleanup hooks and clear containers on aspect
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
Labels: cla-signed

#59306 Searcher: fix issues with negated patterns
  cmd/searcher/internal/search/hybrid_test.go
  cmd/searcher/internal/search/matcher.go
  cmd/searcher/internal/search/search.go
  cmd/searcher/internal/search/search_regex.go
  cmd/searcher/internal/search/search_regex_test.go
  cmd/searcher/internal/search/search_structural.go
  cmd/searcher/internal/search/search_test.go
Labels: cla-signed

#59283 Code Navigation: Add aggregated counts for various result types
  internal/search/result/symbol.go
  internal/search/streaming/BUILD.bazel
  internal/search/streaming/search_filters.go
  internal/search/streaming/search_filters_test.go
Labels: cla-signed

#59325 svelte: Fix `svelte-check`, lint and TS errors
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/app.d.ts
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/Paginator.svelte
  client/web-sveltekit/src/lib/ReactComponent.svelte
  client/web-sveltekit/src/lib/Separator.stories.svelte
  client/web-sveltekit/src/lib/Separator.svelte
  client/web-sveltekit/src/lib/Timestamp.stories.svelte
  client/web-sveltekit/src/lib/Tooltip.stories.svelte
  client/web-sveltekit/src/lib/TreeView.stories.svelte
  client/web-sveltekit/src/lib/UserAvatar.stories.svelte
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/lib/featureflags/stores.test.ts
  client/web-sveltekit/src/lib/react-interop.tsx
  client/web-sveltekit/src/lib/repo/ActionItem.svelte
  client/web-sveltekit/src/lib/repo/FileTable.svelte
  client/web-sveltekit/src/lib/repo/HistoryPanel.stories.svelte
  client/web-sveltekit/src/lib/repo/HovercardContent.svelte
  client/web-sveltekit/src/lib/repo/HovercardView.ts
  client/web-sveltekit/src/lib/repo/api/commits.ts
  client/web-sveltekit/src/lib/repo/api/refs.ts
  client/web-sveltekit/src/lib/repo/utils.ts
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web-sveltekit/src/lib/search/input/SmartSearchToggleButton.svelte
  client/web-sveltekit/src/lib/wildcard/Badge.stories.svelte
  client/web-sveltekit/src/lib/wildcard/Button.svelte
  client/web-sveltekit/src/lib/wildcard/ButtonGroup.svelte
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/routes/Header.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/FileDiff.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/FileDiff.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/FileDiffHunks.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/FileDiffHunks.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/RepoNotFoundError.svelte
  client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
  client/web-sveltekit/src/routes/search/SearchResults.stories.svelte
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web-sveltekit/src/routes/search/StreamingProgress.svelte
  client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
  client/web-sveltekit/src/stories/Badge.stories.ts
  client/web-sveltekit/src/stories/BadgeExample.svelte
  client/web-sveltekit/src/stories/ForceUpdate.svelte
  client/web-sveltekit/src/stories/HistoryPanel.stories.ts
  client/web-sveltekit/src/stories/Separator.stories.ts
  client/web-sveltekit/src/stories/Timestamp.stories.ts
  client/web-sveltekit/src/stories/Tooltip.stories.ts
  client/web-sveltekit/src/stories/TooltipExample.svelte
  client/web-sveltekit/src/stories/TreeView.example.svelte
  client/web-sveltekit/src/stories/TreeView.stories.ts
  client/web-sveltekit/src/stories/UserAvatar.stories.ts
  client/web-sveltekit/src/testdata.ts
  client/web-sveltekit/src/testing/graphql.ts
  client/web-sveltekit/src/testing/mocks.ts
  client/web-sveltekit/svelte.config.js
  client/web-sveltekit/vite.config.ts
  pnpm-lock.yaml
Labels: cla-signed, code-search

#59313 Monitoring: update owners for code insights and batches
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/go.mod
  monitoring/monitoring/BUILD.bazel
  monitoring/monitoring/owners.go
  monitoring/monitoring/owners_test.go
Labels: cla-signed

#59316 Monitoring: update owner for search platform
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/monitoring/owners.go
  monitoring/monitoring/owners_test.go
Labels: cla-signed

#59339 msp/runtime: always enable Cloud Profiler
  cmd/pings/service/BUILD.bazel
  cmd/pings/service/service.go
  deps.bzl
  go.mod
  go.sum
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/go.sum
  lib/managedservicesplatform/runtime/BUILD.bazel
  lib/managedservicesplatform/runtime/service.go
Labels: cla-signed

#59341 msp: emit StackLocals as GSM secrets
  dev/managedservicesplatform/googlesecretsmanager/googlesecretsmanager.go
  dev/managedservicesplatform/internal/resource/cloudflareorigincert/cloudflareorigincert.go
  dev/managedservicesplatform/internal/stack/BUILD.bazel
  dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
  dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
  dev/managedservicesplatform/internal/stack/options/googleprovider/google.go
  dev/managedservicesplatform/internal/stack/project/project.go
  dev/managedservicesplatform/internal/stack/stacks.go
  dev/managedservicesplatform/internal/stack/tfcworkspaces/tfcworkspaces.go
  dev/sg/msp/helpers.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#59284 Allow last_used_at to be semi-stale
  cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
  cmd/frontend/internal/dotcom/productsubscription/tokens_db_test.go
  internal/database/access_tokens.go
  internal/database/access_tokens_test.go
Labels: cla-signed

#59345 msp: restructure to export stacks implementations
  dev/managedservicesplatform/BUILD.bazel
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/stacks/README.md
  dev/managedservicesplatform/stacks/cloudrun/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/builder.go
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/job.go
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go
  dev/managedservicesplatform/stacks/iam/BUILD.bazel
  dev/managedservicesplatform/stacks/iam/iam.go
  dev/managedservicesplatform/stacks/iam/iam_test.go
  dev/managedservicesplatform/stacks/monitoring/BUILD.bazel
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
  dev/managedservicesplatform/stacks/project/BUILD.bazel
  dev/managedservicesplatform/stacks/project/project.go
  dev/managedservicesplatform/stacks/tfcworkspaces/BUILD.bazel
  dev/managedservicesplatform/stacks/tfcworkspaces/tfcworkspaces.go
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#59346 sg msp: use env GSM only, fix 'sg msp logs' for jobs
  dev/managedservicesplatform/internal/stack/BUILD.bazel
  dev/managedservicesplatform/internal/stack/stacks.go
  dev/managedservicesplatform/stacks/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
  dev/managedservicesplatform/stacks/iam/iam.go
  dev/managedservicesplatform/stacks/stacks.go
  dev/managedservicesplatform/terraformcloud/BUILD.bazel
  dev/managedservicesplatform/terraformcloud/runs.go
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/helpers.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#59344 Filters panel: refine type icons
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
Labels: cla-signed

#59348 sg/msp: add prototype 'sg msp docs'
  dev/managedservicesplatform/internal/resource/bigquery/bigquery.go
  dev/managedservicesplatform/managedservicesplatform.go
  dev/managedservicesplatform/operationdocs/BUILD.bazel
  dev/managedservicesplatform/operationdocs/internal/markdown/BUILD.bazel
  dev/managedservicesplatform/operationdocs/internal/markdown/inline.go
  dev/managedservicesplatform/operationdocs/internal/markdown/inline_test.go
  dev/managedservicesplatform/operationdocs/internal/markdown/markdown.go
  dev/managedservicesplatform/operationdocs/links.go
  dev/managedservicesplatform/operationdocs/operationdocs.go
  dev/managedservicesplatform/operationdocs/operationdocs_test.go
  dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/spec/service.go
  dev/managedservicesplatform/spec/spec.go
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/job.go
  dev/managedservicesplatform/stacks/iam/iam.go
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/sg_msp.go
  go.mod
Labels: cla-signed

#59338 monitoring: remove very long description
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/frontend.go
  monitoring/monitoring/monitoring.go
Labels: cla-signed

#59233 code-search: fix for regression introduced by actions discoverability
  client/web/src/enterprise/codeintel/dashboard/components/BrainDot.module.scss
  client/web/src/enterprise/codeintel/dashboard/components/BrainDot.tsx
  client/web/src/repo/RepoHeader.tsx
Labels: cla-signed

#59322 Use interfaces instead of using structs with methods
  cmd/cody-gateway/internal/events/events.go
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/anthropic.go
  cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#59328 search: don't highlight operators inside "..."
  client/shared/src/search/query/decoratedToken.test.ts
  client/shared/src/search/query/scanner.test.ts
  client/shared/src/search/query/scanner.ts
Labels: cla-signed

#59324 Extract token count from streaming Fireworks requests
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/internal/httpapi/completions/fireworks_test.go
Labels: cla-signed

#59320 Improves locals queries for Go
  docker-images/syntax-highlighter/crates/scip-syntax/docs/locals-query-dsl.md
  docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/java/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/queries/matlab/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_nested_locals-2.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_nested_locals.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__go_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__go_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__java_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__java_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__matlab_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__matlab_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__perl_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__perl_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/funcs.go
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals-nested.go
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.go
  docker-images/syntax-highlighter/crates/sg-syntax/src/lib.rs
Labels: cla-signed

#59361 code-search: nitpitck for rbac refactor
  client/web/src/util/permission.ts
  internal/rbac/gen/yamldata.go
Labels: cla-signed

#59360 Update unified cody context to only use search when embeddings are disabled
  cmd/frontend/internal/context/resolvers/context_test.go
  internal/codycontext/context.go
Labels: cla-signed

#59365 New Filters Panel: Fix limitHit value on filters
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/types.ts
  client/branded/src/search-ui/results/filters/utils.ts
  client/branded/src/search-ui/results/sidebar/FilterLink.test.tsx
  client/branded/src/search-ui/results/sidebar/SearchFilterSection.test.tsx
  client/branded/src/search-ui/results/sidebar/__snapshots__/FilterLink.test.tsx.snap
  client/branded/src/search-ui/results/sidebar/helpers.test.ts
  client/shared/src/search/integration/streaming-search-mocks.ts
  client/shared/src/search/stream.ts
  client/shared/src/testing/searchTestHelpers.ts
  client/web/src/integration/search-aggregation.test.ts
  client/web/src/integration/search.test.ts
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/internal/search/event_writer.go
  cmd/frontend/internal/search/search.go
  internal/search/client/telemetry.go
  internal/search/job/jobutil/alert.go
  internal/search/job/jobutil/job_test.go
  internal/search/repo_status.go
  internal/search/repo_status_test.go
  internal/search/streaming/client/progress.go
  internal/search/streaming/filters.go
  internal/search/streaming/filters_test.go
  internal/search/streaming/http/events.go
  internal/search/streaming/search_filters.go
  internal/search/streaming/search_filters_test.go
  internal/search/zoekt/indexed_search.go
  internal/search/zoekt/indexed_search_test.go
Labels: cla-signed

#59368 web: Revert <kbd> tag styling
  client/wildcard/src/global-styles/code.scss
Labels: cla-signed, code-search

#59355 chore: Bump autoindexing image SHAs
  internal/codeintel/autoindexing/internal/inference/libs/indexes.go
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Gradle.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Maven.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_SBT.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_lsif-java.json.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_WITHOUT_top-level_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_with_top-level_build_file.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_files_in_root.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/go_modules.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/javascript_project_with_no_tsconfig_1.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/javascript_project_with_no_tsconfig_2.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_multiple_config_files_at_root.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_multiple_roots.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_1.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_2.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_3.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_package_with_pyproject.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_pyproject.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_requirements.txt.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/python_setup.py.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/simple_tsconfig.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/tsconfig_in_subdirectories.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/typescript_installation_steps.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/typescript_with_lerna_configuration.yaml
  internal/codeintel/autoindexing/internal/inference/testdata/typescript_with_node_version.yaml
Labels: cla-signed

#59323 Add Semgrep SAST Scan
  dev/ci/internal/ci/pipeline.go
  dev/ci/internal/ci/security_operations.go
  dev/ci/semgrep-scan.sh
Labels: cla-signed

#59373 svelte: Fix issues reported by svelte-check
  client/web-sveltekit/src/lib/fileIcons.ts
  client/web-sveltekit/src/lib/search/utils.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed

#59377 Update locals DSL to @occurrences.skip for skipping defs and refs
  docker-images/syntax-highlighter/crates/scip-syntax/docs/locals-query-dsl.md
  docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
Labels: cla-signed

#59379 Uses a debug_assert over assert for non-critical locals error
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
Labels: cla-signed

#59376 Improves locals queries for Java
  docker-images/syntax-highlighter/crates/scip-syntax/queries/java/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__java_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__java_scopes.snap
  docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/snapshots/integration_test__globals.java.snap
Labels: cla-signed

#59380 Unify handling of skipped occurrences between refs and defs
  docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__go_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__java_scopes.snap
Labels: cla-signed

#59349 sg: add 'fix all' choice in setup
  dev/sg/internal/check/input.go
  dev/sg/internal/check/runner.go
  dev/sg/internal/check/runner_test.go
Labels: cla-signed

#59176 Remove experimental indexRepositoryName for rust packages
  CHANGELOG.md
  cmd/worker/internal/codeintel/BUILD.bazel
  cmd/worker/internal/codeintel/dependencies_crates_syncer.go
  cmd/worker/shared/main.go
  internal/codeintel/dependencies/BUILD.bazel
  internal/codeintel/dependencies/init.go
  internal/codeintel/dependencies/internal/background/BUILD.bazel
  internal/codeintel/dependencies/internal/background/job_cratesyncer.go
  internal/codeintel/dependencies/internal/background/job_cratesyncer_test.go
  schema/rust-packages.schema.json
  schema/schema.go
Labels: cla-signed, team/source

#59209 Consolidate GitBlame client method and improve performance
  cmd/frontend/graphqlbackend/git_blob.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/internal/httpapi/stream_blame.go
  internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/observability.go
Labels: cla-signed, team/source

#59367 Streaming search: only flush filters when dirty
  cmd/frontend/internal/search/search.go
  internal/search/streaming/search_filters.go
Labels: cla-signed

#59362 Fix storybook type errors and add CI test
  client/web/BUILD.bazel
  client/web/src/enterprise/own/RepositoryOwnEditPage.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlock.story.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.story.tsx
  client/web/src/notebooks/notebook/NotebookComponent.story.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.story.tsx
Labels: cla-signed

#59390 Chore: bump conc
  deps.bzl
  go.mod
  go.sum
  lib/go.mod
  lib/go.sum
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/go.sum
Labels: cla-signed

#59393 chromatic: fix auto accept args
  dev/ci/internal/ci/client_operations.go
  dev/ci/run-chromatic.sh
Labels: cla-signed

#59183 gitserver: Fixup date parsing in RefDescriptions
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
Labels: cla-signed, team/source

#59396 Build: bump hash for perforce API
  wolfi-packages/p4-fusion.yaml
Labels: cla-signed

#59197 Fix logic for when to show add access token button
  client/web/src/site-admin/SiteAdminTokensPage.tsx
  client/web/src/user/settings/accessTokens/UserSettingsTokensPage.tsx
Labels: cla-signed, team/source

#59387 Extract token count from streaming OpenAI responses
  cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/completions/fireworks_test.go
  cmd/cody-gateway/internal/httpapi/completions/openai.go
  cmd/cody-gateway/internal/httpapi/completions/openai_test.go
Labels: cla-signed

#59395 Code Insights: Remove no new line check from capture group insight
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.test.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts
Labels: cla-signed, bug-fix

#59229 Adding Config options for Siteadmins to configure whether clients can use Chat/autocomplete/commands
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/conf/conftypes/consts.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#59366 Search: integrate new backend filters
  client/branded/BUILD.bazel
  client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/hooks.ts
  client/branded/src/search-ui/results/filters/types.ts
  client/branded/src/search-ui/results/filters/utils.ts
  client/shared/src/search/stream.ts
  client/web/src/search/results/SearchResultsCacheProvider.tsx
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
  internal/search/streaming/search_filters.go
Labels: cla-signed

#59409 Filters panel: make search case-insensitive
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
Labels: cla-signed

#59382 Adjust blobstore latency alert
  doc/admin/observability/alerts.md
  monitoring/definitions/frontend.go
Labels: cla-signed, team/source

#59411 Refactor calcUnrestricted function
  internal/database/external_services.go
  internal/database/external_services_test.go
Labels: cla-signed, team/source

#57584 search: disable structural search by default
  CHANGELOG.md
  client/web/src/integration/search.test.ts
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
  dev/gqltest/search_test.go
  dev/gqltest/sub_repo_permissions_test.go
  internal/conf/computed.go
  schema/site.schema.json
Labels: cla-signed

#59378 bzl: handle stitched migration graph generation
  dev/BUILD.bazel
  dev/sg/internal/migration/rewrite.go
  internal/database/migration/shared/BUILD.bazel
  internal/database/migration/shared/data/cmd/generator/README.md
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/cmd/generator/main.go
  internal/database/migration/shared/data/cmd/migrationdump/BUILD.bazel
  internal/database/migration/shared/data/cmd/migrationdump/main.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/migration/shared/embed.go
  internal/database/migration/stitch/BUILD.bazel
  internal/database/migration/stitch/archives.go
  internal/database/migration/stitch/content.go
  internal/database/migration/stitch/git.go
  internal/database/migration/stitch/reader.go
  internal/database/migration/stitch/rewriter.go
  internal/database/migration/stitch/stitch.go
  internal/database/migration/stitch/stitch_test.go
Labels: cla-signed

#59381 search: revert glob filter values from new keyword pattern type
  client/branded/src/search-ui/input/toggles/SmartSearchToggleExtended.tsx
  client/shared/src/search/query/filters.ts
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web/src/repo/RepoContainer.tsx
  client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
  client/web/src/repo/tree/TreePageContent.tsx
  client/web/src/search/index.test.ts
  client/web/src/search/index.ts
  client/web/src/search/input/V2SearchInput.tsx
  client/web/src/search/input/suggestions.ts
  internal/search/query/labels.go
  internal/search/query/parser.go
  internal/search/query/parser_test.go
  internal/search/query/transformer_test.go
Labels: cla-signed

#59388 nix: unset TMP and TMPDIR for bazel
  shell.nix
Labels: nix, cla-signed

#59428 sg: bump git version requirement
  dev/sg/dependencies/mac.go
  dev/sg/dependencies/ubuntu.go
Labels: cla-signed

#59392 Remove embeddings indicators from cody web chat
  client/web/src/cody/components/GettingStarted.tsx
  client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
  client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
  client/web/src/cody/components/ScopeSelector/backend.ts
  client/web/src/cody/components/ScopeSelector/useRepoSuggestions.ts
Labels: cla-signed

#59402 Chore: clean up `RepositoryResolver`
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/perforce_changelist.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_test.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/symbols.go
  cmd/frontend/internal/compute/resolvers/resolvers.go
  internal/cmd/search-blitz/search.graphql
Labels: cla-signed

#59410 [Backport 5.2] Code Insights: Remove no new line check from capture group insight
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.test.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts
Labels: cla-signed, backports, backported-to-5.2

#59434 chore: unexport version.MockTimestamp as it's only used in tests
  internal/version/version.go
  internal/version/version_test.go
Labels: cla-signed

#59090 [Backport 5.2] Embeddings: avoid constantly rerunning job if it failed
  cmd/frontend/internal/app/resolvers/app.go
  cmd/frontend/internal/embeddings/resolvers/resolvers.go
  enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
  internal/embeddings/background/repo/types.go
  internal/embeddings/schedule.go
  internal/embeddings/schedule_test.go
Labels: cla-signed

#59437 Filters panel: fix label for commit dates
  internal/search/streaming/search_filters.go
Labels: cla-signed

#59405 Chore: clean up `RepositoryResolver`, part II
  cmd/frontend/backend/mocks_temp.go
  cmd/frontend/backend/repos.go
  cmd/frontend/backend/repos_mock.go
  cmd/frontend/backend/repos_test.go
  cmd/frontend/backend/repos_vcs_test.go
  cmd/frontend/graphqlbackend/commit_search_result.go
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_commit_test.go
  cmd/frontend/graphqlbackend/git_tree_entry.go
  cmd/frontend/graphqlbackend/git_tree_test.go
  cmd/frontend/graphqlbackend/perforce_changelist.go
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_external.go
  cmd/frontend/graphqlbackend/repository_mirror.go
  cmd/frontend/graphqlbackend/repository_test.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/search_results_stats_languages.go
  cmd/frontend/internal/app/editor.go
  cmd/frontend/internal/app/editor_test.go
  cmd/frontend/internal/app/ui/handlers_test.go
  cmd/frontend/internal/batches/resolvers/main_test.go
  cmd/frontend/internal/compute/resolvers/resolvers.go
  cmd/frontend/internal/context/resolvers/context.go
  cmd/frontend/internal/handlerutil/repo.go
  cmd/frontend/internal/httpapi/repo_shield_test.go
  cmd/frontend/internal/httpapi/search_test.go
  cmd/frontend/internal/httpapi/stream_blame_test.go
  cmd/frontend/internal/own/resolvers/resolvers_test.go
  cmd/frontend/internal/searchcontexts/resolvers/resolvers.go
  internal/codeintel/uploads/internal/background/processor/job_worker_handler_test.go
  internal/codeintel/uploads/transport/http/handler.go
  internal/codeintel/uploads/transport/http/handler_test.go
  internal/codeintel/uploads/transport/http/iface.go
  internal/search/repos/repos_test.go
  internal/types/types.go
  internal/uploadhandler/upload_handler_test.go
Labels: cla-signed

#59442 Filters panel: skip unknown symbol kinds
  internal/search/streaming/search_filters.go
Labels: cla-signed

#59423 pre-commit: add pre-commit directives to token tests
  internal/accesstoken/personal_access_token_test.go
  internal/database/access_tokens_test.go
Labels: cla-signed

#59439 ci: avoid dropping ALL executors binary if BUILDKITE_TAG is empty
  cmd/executor/_binary.push.sh
Labels: cla-signed

#59334 search: json encode repo metadata for csv export
  CHANGELOG.md
  client/web/src/search/results/export/searchResultsExport.test.ts
  client/web/src/search/results/export/searchResultsExport.ts
Labels: cla-signed

#59400 Added ts_projects for storybook files in client/*
  client/BUILD.bazel
  client/branded/BUILD.bazel
  client/browser/BUILD.bazel
  client/jetbrains/BUILD.bazel
  client/jetbrains/webview/BUILD.bazel
  client/shared/BUILD.bazel
  client/web/BUILD.bazel
  client/wildcard/BUILD.bazel
Labels: cla-signed

#59433 chore: drop unused go pkg
  deps.bzl
  go.mod
  go.sum
  internal/version/minversion/BUILD.bazel
  internal/version/minversion/minversion.go
Labels: cla-signed

#59424 token: disable Authorize button on mobile device
  client/common/BUILD.bazel
  client/common/src/util/deviceDetection.ts
  client/common/src/util/index.ts
  client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
Labels: cla-signed

#59441 Filters panel: title-case symbol kind
  internal/search/streaming/BUILD.bazel
  internal/search/streaming/search_filters.go
  internal/search/streaming/search_filters_test.go
Labels: cla-signed

#59445 Filters: update repo rendering
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
Labels: cla-signed

#59416 Minor PR feedback
  cmd/frontend/graphqlbackend/schema.graphql
  internal/database/users.go
Labels: cla-signed, team/source

#59404 backport: grpc: add automatic retry support to all services
  CHANGELOG.md
  go.mod
  internal/api/internalapi/BUILD.bazel
  internal/api/internalapi/client.go
  internal/api/internalapi/retry.go
  internal/api/internalapi/v1/internalapi.pb.go
  internal/api/internalapi/v1/internalapi.proto
  internal/gitserver/BUILD.bazel
  internal/gitserver/addrs.go
  internal/gitserver/gitdomain/exec.go
  internal/gitserver/retry.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
  internal/grpc/defaults/BUILD.bazel
  internal/grpc/defaults/defaults.go
  internal/grpc/defaults/retry.go
  internal/grpc/defaults/retry_test.go
  internal/grpc/retry/BUILD.bazel
  internal/grpc/retry/backoff.go
  internal/grpc/retry/doc.go
  internal/grpc/retry/examples_test.go
  internal/grpc/retry/options.go
  internal/grpc/retry/retry.go
  internal/grpc/retry/retry_test.go
  internal/repoupdater/BUILD.bazel
  internal/repoupdater/client.go
  internal/repoupdater/retry.go
  internal/repoupdater/v1/repoupdater.pb.go
  internal/repoupdater/v1/repoupdater.proto
  internal/search/backend/BUILD.bazel
  internal/search/backend/retry.go
  internal/search/backend/zoekt.go
  internal/search/searcher/BUILD.bazel
  internal/search/searcher/client_grpc.go
  internal/search/searcher/retry_grpc.go
  internal/searcher/v1/searcher.pb.go
  internal/searcher/v1/searcher.proto
  internal/symbols/BUILD.bazel
  internal/symbols/client.go
  internal/symbols/retry.go
  internal/symbols/v1/symbols.pb.go
  internal/symbols/v1/symbols.proto
  nogo_config.json
Labels: cla-signed

#59363 Searcher: Implement 'and' and 'or' match trees
  cmd/searcher/internal/search/BUILD.bazel
  cmd/searcher/internal/search/hybrid.go
  cmd/searcher/internal/search/matcher_test.go
  cmd/searcher/internal/search/matchtree.go
  cmd/searcher/internal/search/matchtree_test.go
  cmd/searcher/internal/search/search_regex.go
  cmd/searcher/internal/search/search_regex_test.go
Labels: cla-signed

#59406 Allow repo wide pr-auditor opt-out of test plans and reviews
  dev/pr-auditor/check-pr.sh
  dev/pr-auditor/check.go
  dev/pr-auditor/check_test.go
  dev/pr-auditor/issue.go
  dev/pr-auditor/issue_test.go
  dev/pr-auditor/main.go
Labels: cla-signed

#59340 Logging previous values during setting changes
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/internal/app/verify_email.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  internal/auth/userpasswd/reset_password.go
Labels: cla-signed

#59457 Filters: fix icon for nonstandard codehosts
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
Labels: cla-signed

#59459 New Filters Panel: encase before/after values in double quotes where necessary
  internal/search/streaming/search_filters.go
Labels: cla-signed

#59438 chore: remove unused bundle diff reporter
  client/web/package.json
  client/web/scripts/BUILD.bazel
  client/web/scripts/report-bundle-diff.ts
  client/web/scripts/report-bundle-jora-query
Labels: cla-signed

#59466 gomod: update zoekt to include chunkmatch perf fix
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed

#59469 Add non-blocking error handling for semgrep findings
  dev/ci/semgrep-scan.sh
Labels: cla-signed

#59285 Copying dotcom attribution client to gateway
  cmd/cody-gateway/internal/dotcom/BUILD.bazel
  cmd/cody-gateway/internal/dotcom/genql.yaml
  cmd/cody-gateway/internal/dotcom/operations.go
  cmd/cody-gateway/internal/dotcom/operations.graphql
  cmd/cody-gateway/internal/httpapi/attribution/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/attribution/handler.go
  cmd/cody-gateway/internal/httpapi/attribution/handler_test.go
Labels: cla-signed

#59467 sg: use release from package
  dev/sg/BUILD.bazel
  dev/sg/internal/images/helm.go
  dev/sg/internal/release/release.go
  dev/sg/main.go
  dev/sg/sg_release.go
Labels: cla-signed

#59453 Comments, Cleanups, Tests for `naman/reset-cody-usage-cache`
  cmd/cody-gateway/internal/actor/actor.go
  cmd/cody-gateway/internal/actor/dotcomuser/BUILD.bazel
  cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser_test.go
  cmd/cody-gateway/internal/limiter/BUILD.bazel
  cmd/cody-gateway/internal/limiter/limiter.go
  cmd/cody-gateway/internal/limiter/store.go
  cmd/cody-gateway/internal/limiter/store_test.go
Labels: cla-signed

#59330 Reset Cody Gateway usage cache automatically during limits sync on interval & TTL mismatch
  cmd/cody-gateway/internal/actor/actor.go
  cmd/cody-gateway/internal/actor/dotcomuser/BUILD.bazel
  cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
  cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser_test.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/internal/limiter/BUILD.bazel
  cmd/cody-gateway/internal/limiter/limiter.go
  cmd/cody-gateway/internal/limiter/prefix.go
  cmd/cody-gateway/internal/limiter/store.go
  cmd/cody-gateway/internal/limiter/store_test.go
  cmd/cody-gateway/shared/main.go
Labels: cla-signed

#59474 New Filters Panel: change background on hover
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
  client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
Labels: cla-signed

#59477 chore: fix universal-ctags darwin GHA workflow
  .github/workflows/universal-ctags.yml
Labels: cla-signed

#59454 New Filters Panel: replace 'show all' logic with 'show more/less' logic
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
Labels: cla-signed

#59462 sg msp: expand destroy protection to more features
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/terraformcloud/terraformcloud.go
  dev/sg/msp/helpers.go
Labels: cla-signed

#59482 nixos: add zig-cc platform sha for nixos
  WORKSPACE
Labels: nix, cla-signed

#59486 Search: add missing changelog entries for 5.2
  CHANGELOG.md
Labels: cla-signed

#59487 Fix data access race condition in gRPC retry logic
  internal/grpc/retry/options.go
  internal/grpc/retry/retry.go
Labels: cla-signed, backports, team/source, backport 5.2

#59489 go: Remove override for go-tiktoken
  deps.bzl
  go.mod
  go.sum
Labels: cla-signed, team/source

#59490 grpc: retry: add test that exectures parallel requests
  internal/grpc/retry/retry_test.go
Labels: cla-signed, team/source

#59495 add a few changes for v5.2.6 release
  CHANGELOG.md
Labels: cla-signed

#59471 handle deleted users when listing team members
  internal/database/teams.go
  internal/database/teams_test.go
Labels: cla-signed

#59497 Removed pr-auditor and left redirect notice
  dev/pr-auditor/BUILD.bazel
  dev/pr-auditor/README.md
  dev/pr-auditor/batch-changes/README.md
  dev/pr-auditor/batch-changes/pr-auditor-patch.yml
  dev/pr-auditor/batch-changes/pr-auditor-rollout.yml
  dev/pr-auditor/check-pr.sh
  dev/pr-auditor/check.go
  dev/pr-auditor/check_test.go
  dev/pr-auditor/issue.go
  dev/pr-auditor/issue_test.go
  dev/pr-auditor/main.go
  dev/pr-auditor/testdata/pull_request_body/bad-markdown.md
  dev/pr-auditor/testdata/pull_request_body/has-plan-fancy.md
  dev/pr-auditor/testdata/pull_request_body/has-plan.md
  dev/pr-auditor/testdata/pull_request_body/inline-plan.md
  dev/pr-auditor/testdata/pull_request_body/no-plan.md
  dev/pr-auditor/testdata/pull_request_body/no-review-required.md
  dev/pr-auditor/webhook.go
Labels: cla-signed

#59507 monitoring: relax mean_blocked_seconds_per_conn_request alerts
  doc/admin/observability/alerts.md
  monitoring/definitions/shared/dbconns.go
Labels: cla-signed, backport 5.2, backport/improvement

#59501 otel: Log at most 128 characters for generic pq Arrays
  internal/database/dbconn/open.go
Labels: cla-signed, team/source

#59504 release: sourcegraph@5.2.6
  internal/updatecheck/handler.go
Labels: cla-signed

#59415 Improves locals queries for MATLAB
  docker-images/syntax-highlighter/crates/scip-syntax/queries/matlab/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__matlab_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__matlab_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
Labels: cla-signed

#59465 Improves locals queries for Perl
  docker-images/syntax-highlighter/crates/scip-syntax/queries/perl/scip-locals.scm
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__perl_occurrences.snap
  docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__perl_scopes.snap
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/perl.pm
  docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__cmp.pl.snap
Labels: cla-signed

#59517 Enables tree-sitter based locals references for Go
  internal/highlight/language.go
Labels: cla-signed

#59468 search jobs: refactor SearchQuery interface
  cmd/worker/internal/search/exhaustive_search_repo_revision.go
  cmd/worker/internal/search/exhaustive_search_test.go
  internal/search/exhaustive/service/matchcsv.go
  internal/search/exhaustive/service/search.go
  internal/search/exhaustive/service/search_test.go
  internal/search/exhaustive/service/searcher.go
  internal/search/exhaustive/service/searcher_test.go
Labels: cla-signed

#59485 add shellcheck & shfmt to pre-commit's `pre-push` hook
  .pre-commit-config.yaml
  dev/ci/parallel_run.sh
  dev/ci/scripts/wolfi/build-package.sh
  dev/ci/trivy/trivy-scan-high-critical.sh
  dev/comby-install-or-upgrade.sh
  dev/licenses.sh
  dev/phabricator/start.sh
Labels: cla-signed

#59520 Remove no longer used cody-autocomplete-default-starcoder-hybrid-sourcegraph feature flag
  internal/completions/httpapi/codecompletion.go
Labels: cla-signed

#59499 Add a Cody enabled check to getCodyContext
  cmd/frontend/internal/context/resolvers/BUILD.bazel
  cmd/frontend/internal/context/resolvers/context_test.go
  internal/codycontext/BUILD.bazel
  internal/codycontext/context.go
Labels: cla-signed

#59521 Flush chat responses
  cmd/cody-gateway/internal/httpapi/completions/upstream.go
Labels: cla-signed

#59500 Symbol search: clean up job logic
  cmd/frontend/internal/search/BUILD.bazel
  cmd/frontend/internal/search/search.go
  internal/search/alert.go
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/query/types.go
  internal/search/searcher/symbol_search_job.go
Labels: cla-signed

#59483 sg msp: use static list of stack names, remove --tfc=false
  dev/managedservicesplatform/managedservicesplatform.go
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/helpers.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#59505 msp/cloudflare: proxy by default
  dev/managedservicesplatform/internal/resource/cloudflare/cloudflare.go
  dev/managedservicesplatform/operationdocs/operationdocs.go
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go
Labels: cla-signed

#59525 License desk update—fix broken URL
  cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
  cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
Labels: cla-signed
