Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-07, with the labels that each got.

#63564 perf(scip-syntax): uses the same parse tree for globals and locals
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/src/lib.rs
Labels: team/graph, cla-signed, team/product-platform

#63443 scip-syntax: adds strict SCIP symbol parsing and formatting
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/benches/symbol_parsing.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict/context_error.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict/format.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict/parse.rs
Labels: team/graph, cla-signed, team/product-platform

#63567 remove unused code for org member summary & autocomplete
  client/web/src/org/area/OrgHeader.tsx
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/org_members.go
  cmd/frontend/graphqlbackend/org_members_test.go
  cmd/frontend/graphqlbackend/schema.graphql
  internal/database/dbmocks/mocks_temp.go
  internal/database/org_members.go
  internal/database/org_members_db_test.go
  internal/types/types.go
Labels: cla-signed, no-changelog

#63571 narrow NamespaceProps type
  client/web/src/namespaces/NamespaceArea.tsx
  client/web/src/namespaces/index.ts
  client/web/src/org/area/OrgArea.tsx
  client/web/src/savedSearches/SavedSearchCreateForm.tsx
  client/web/src/savedSearches/SavedSearchForm.story.tsx
  client/web/src/savedSearches/SavedSearchForm.test.tsx
  client/web/src/savedSearches/SavedSearchListPage.tsx
  client/web/src/savedSearches/SavedSearchUpdateForm.tsx
  client/web/src/user/area/UserArea.tsx
Labels: cla-signed

#63472 notebooks: store default pattern type per notebook
  client/shared/src/search/stream.ts
  client/shared/src/search/suggestions/index.ts
  client/web/src/integration/nav.test.ts
  client/web/src/integration/notebook.test.ts
  client/web/src/notebooks/backend.ts
  client/web/src/notebooks/blocks/file/NotebookFileBlock.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.story.tsx
  client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
  client/web/src/notebooks/blocks/markdown/NotebookMarkdownBlock.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.story.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/notebooks/blocks/suggestions/suggestions.ts
  client/web/src/notebooks/blocks/symbol/NotebookSymbolBlockInput.tsx
  client/web/src/notebooks/index.ts
  client/web/src/notebooks/listPage/NotebooksListPage.story.tsx
  client/web/src/notebooks/notebook/NotebookComponent.story.tsx
  client/web/src/notebooks/notebook/NotebookComponent.tsx
  client/web/src/notebooks/notebook/index.ts
  client/web/src/notebooks/notebookPage/EmbeddedNotebookPage.tsx
  client/web/src/notebooks/notebookPage/NotebookContent.tsx
  client/web/src/notebooks/notebookPage/NotebookPage.tsx
  client/web/src/repo/blob/BlobPage.tsx
  cmd/frontend/graphqlbackend/notebooks.go
  cmd/frontend/graphqlbackend/notebooks.graphql
  cmd/frontend/internal/notebooks/resolvers/resolvers.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.json
  internal/database/schema.md
  internal/notebooks/store.go
  internal/notebooks/types.go
  migrations/frontend/1719214941_notebooks_add_field_pattern_type/down.sql
  migrations/frontend/1719214941_notebooks_add_field_pattern_type/metadata.yaml
  migrations/frontend/1719214941_notebooks_add_field_pattern_type/up.sql
  migrations/frontend/squashed.sql
Labels: team/search-platform, cla-signed, team/product-platform

#63536 scip-syntax: implements parallel processing for workspace and tar commands
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
  docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
Labels: team/graph, cla-signed, team/product-platform

#63574 chore: Simplify path trimming logic in perm checking
  internal/authz/subrepoperms/sub_repo_perms.go
Labels: team/graph, cla-signed, team/product-platform

#63554 update config for workflows 5.10
  .aspect/workflows/config.yaml
Labels: cla-signed

#63562 chore(search) VSCode Search extension: Update README and CHANGELOG
  client/vscode/CHANGELOG.md
  client/vscode/README.md
Labels: cla-signed

#63558 chore(search): VSCode Search extension: Remove signup link for sourcegraph.com
  client/vscode/src/webview/sidebars/auth/AuthSidebarView.tsx
Labels: cla-signed, vscode-search

#63561 chore: preserve format imposed by bazel
  .vscode/settings.json
Labels: cla-signed

#63568 make `<Label>` element focus & select at end to match native label behavior
  client/wildcard/src/components/Typography/Label/Label.tsx
Labels: cla-signed

#63570 cosmetic improvements to OrgSettingsMemberPage, UserEmail
  client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
  client/web/src/user/settings/emails/UserEmail.module.scss
  client/web/src/user/settings/emails/UserEmail.tsx
Labels: cla-signed

#63559 chore(search): VSCode Search extension: Remove url and token from configuration
  client/vscode/package.json
Labels: cla-signed, vscode-search

#63556 chore/linearhooks: use MSP rollouts
  dev/linearhooks/BUILD.bazel
Labels: cla-signed

#63581 chore(local): add FORBIDCOMMIT pragma to prevent accidental commits
  .pre-commit-config.yaml
  dev/check-tokens.sh
  dev/forbidcommit.sh
Labels: cla-signed, no-changelog

#63569 fix bug preventing site admins from directly adding org members when email.smtp was set
  cmd/frontend/graphqlbackend/org.go
  cmd/frontend/graphqlbackend/org_test.go
Labels: cla-signed

#63523 feat(appliance): admin password gates most pages
  cmd/appliance/README.md
  cmd/appliance/shared/shared.go
  deps.bzl
  go.mod
  go.sum
  internal/appliance/BUILD.bazel
  internal/appliance/appliance.go
  internal/appliance/auth.go
  internal/appliance/auth_test.go
  internal/appliance/errors.go
  internal/appliance/html.go
  internal/appliance/routes.go
  internal/appliance/web/template/error.gohtml
  internal/appliance/web/template/landing.gohtml
Labels: cla-signed, no-changelog

#63537 add LazyQueryInputFormControl, remove duplicated common pattern
  client/branded/src/search-ui/input/LazyQueryInput.module.scss
  client/branded/src/search-ui/input/LazyQueryInput.tsx
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.module.scss
  client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
  client/web/src/enterprise/searchContexts/SearchContextForm.module.scss
  client/web/src/enterprise/searchContexts/SearchContextForm.tsx
  client/web/src/savedSearches/SavedSearchForm.module.scss
  client/web/src/savedSearches/SavedSearchForm.test.tsx
  client/web/src/savedSearches/SavedSearchForm.tsx
Labels: cla-signed

#63576 Marks search-based usages as definitions or references
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/syntactic.go
  internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
Labels: team/graph, cla-signed, team/product-platform

#63594 fix(svelte): Fix unplugin icons usage in storybook
  client/web-sveltekit/.storybook/main.ts
Labels: cla-signed

#63595 chore(local): remove outdated `dx` command
  dev/dx/BUILD.bazel
  dev/dx/main.go
Labels: cla-signed, no-changelog

#63577 feat: introduce database fields for github apps <-> batch changes integration, and update database layer
  internal/batches/store/BUILD.bazel
  internal/batches/store/integration_test.go
  internal/batches/store/site_credentials.go
  internal/batches/store/site_credentials_test.go
  internal/batches/types/site_credential.go
  internal/database/BUILD.bazel
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.json
  internal/database/schema.md
  internal/database/user_credentials.go
  internal/database/user_credentials_test.go
  internal/github_apps/store/store.go
  internal/github_apps/types/types.go
  migrations/frontend/1719498032_add_github_app_batch_changes_site_credential/down.sql
  migrations/frontend/1719498032_add_github_app_batch_changes_site_credential/metadata.yaml
  migrations/frontend/1719498032_add_github_app_batch_changes_site_credential/up.sql
  migrations/frontend/1719498091_add_github_app_id_user_credentials/down.sql
  migrations/frontend/1719498091_add_github_app_id_user_credentials/metadata.yaml
  migrations/frontend/1719498091_add_github_app_id_user_credentials/up.sql
  migrations/frontend/1719498128_add_kind_column_github_app/down.sql
  migrations/frontend/1719498128_add_kind_column_github_app/metadata.yaml
  migrations/frontend/1719498128_add_kind_column_github_app/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed

#63597 Implement UI for Github Apps <> Batch Changes integration
  .vscode/settings.json
  client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
  client/web/src/enterprise/batches/settings/AddCredentialModal.module.scss
  client/web/src/enterprise/batches/settings/AddCredentialModal.story.tsx
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
  client/web/src/enterprise/batches/settings/BatchChangesCreateGitHubAppPage.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.story.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsPage.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.story.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/site-admin/SiteAdminGitHubAppsArea.tsx
  client/web/src/site-admin/routes.tsx
  cmd/frontend/graphqlbackend/githubapps.graphql
Labels: cla-signed

#63599 fix(ci): panic using correct err
  dev/ci/internal/ci/config.go
Labels: cla-signed

#63583 Chore(release): Calendar Updates
  dev/sg/internal/release/calendar.go
  tools/release/config/calendar.jsonc
Labels: cla-signed

#63600 fix(svelte): Remove rogue console.log statement
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
Labels: cla-signed

#63145 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/appliance.lock.json
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#63531 feat/enterpriseportal: define GetCodyGatewayUsage RPC, use uint64 for rate limits
  cmd/enterprise-portal/internal/codyaccessservice/adapters.go
  lib/enterpriseportal/codyaccess/v1/BUILD.bazel
  lib/enterpriseportal/codyaccess/v1/codyaccess.pb.go
  lib/enterpriseportal/codyaccess/v1/codyaccess.proto
  lib/enterpriseportal/codyaccess/v1/codyaccess_grpc.pb.go
  lib/enterpriseportal/codyaccess/v1/v1connect/codyaccess.connect.go
Labels: cla-signed

#63555 feat/enterpriseportal: implement GetCodyGatewayUsage RPC
  cmd/enterprise-portal/internal/codyaccessservice/BUILD.bazel
  cmd/enterprise-portal/internal/codyaccessservice/adapters.go
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/codyaccessservice/v1_store.go
  cmd/enterprise-portal/service/BUILD.bazel
  cmd/enterprise-portal/service/codygatewayevents.go
  cmd/enterprise-portal/service/config.go
  cmd/enterprise-portal/service/service.go
  internal/codygateway/codygatewayevents/BUILD.bazel
  internal/codygateway/codygatewayevents/codygatewayevents.go
Labels: cla-signed

#63585 Cody context: fix an issue with anchoring repo names
  cmd/frontend/internal/codycontext/context.go
  cmd/frontend/internal/codycontext/context_test.go
Labels: cla-signed

#63550 (chore)analytics: consistent naming of web code copied events
  client/branded/src/search-ui/components/FileMatchChildren.tsx
  client/branded/src/search-ui/components/SymbolSearchResult.tsx
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web/src/repo/blob/CodeMirrorBlob.tsx
Labels: cla-signed

#63534 release/appliance: resource def jaeger
  internal/appliance/config/defaults.go
  internal/appliance/config/spec.go
  internal/appliance/development.md
  internal/appliance/reconciler/BUILD.bazel
  internal/appliance/reconciler/jaeger.go
  internal/appliance/reconciler/jaeger_test.go
  internal/appliance/reconciler/reconcile.go
  internal/appliance/reconciler/testdata/golden-fixtures/jaeger/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/jaeger/with-replicas.yaml
  internal/appliance/reconciler/testdata/sg/jaeger/default.yaml
  internal/appliance/reconciler/testdata/sg/jaeger/with-replicas.yaml
Labels: cla-signed

#63596 chore: Use api.RepoID and api.CommitID in more places
  internal/codeintel/codenav/commit_cache.go
  internal/codeintel/codenav/gittree_translator.go
  internal/codeintel/codenav/request_state.go
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/service_references_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/codenav/types.go
  internal/codeintel/resolvers/codenav.go
  internal/codeintel/uploads/internal/background/backfiller/mocks_test.go
  internal/codeintel/uploads/internal/background/expirer/mocks_test.go
  internal/codeintel/uploads/internal/background/processor/mocks_test.go
  internal/codeintel/uploads/internal/store/commitgraph.go
  internal/codeintel/uploads/internal/store/commitgraph_test.go
  internal/codeintel/uploads/internal/store/misc.go
  internal/codeintel/uploads/internal/store/misc_test.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/mocks_test.go
  internal/codeintel/uploads/service.go
  internal/codeintel/uploads/shared/BUILD.bazel
  internal/codeintel/uploads/shared/types.go
Labels: team/graph, cla-signed, team/product-platform

#63590 clean up FilteredConnection filter types and code
  client/web/src/components/FilteredConnection/FilterControl.tsx
  client/web/src/components/FilteredConnection/FilteredConnection.tsx
  client/web/src/components/FilteredConnection/ui/ConnectionForm.tsx
  client/web/src/components/FilteredConnection/utils.ts
  client/web/src/components/externalServices/ExternalServicesPage.tsx
  client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.tsx
  client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
  client/web/src/enterprise/executors/instances/ExecutorsListPage.tsx
  client/web/src/enterprise/searchContexts/SearchContextsList.tsx
  client/web/src/notebooks/listPage/NotebooksList.tsx
  client/web/src/notebooks/listPage/NotebooksListPage.tsx
  client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
  client/web/src/site-admin/SiteAdminPackagesPage.tsx
  client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
  client/web/src/site-admin/SiteAdminSlowRequestsPage.tsx
  client/web/src/site-admin/SiteAdminSurveyResponsesPage.tsx
  client/web/src/site-admin/packages/AddFilterModal.tsx
  client/web/src/site-admin/packages/ManageFiltersModal.tsx
  client/web/src/site-admin/packages/components/MultiPackageForm.tsx
  client/web/src/site-admin/packages/components/SinglePackageForm.tsx
  client/web/src/site-admin/packages/modal-content/AddPackageFilterModalContent.tsx
  client/web/src/site-admin/packages/modal-content/EditPackageFilterModalContent.tsx
Labels: cla-signed

#63579 insights: persist patternType in db
  client/web/BUILD.bazel
  client/web/src/enterprise/insights/components/creation-ui/form-series/components/form-series-input/FormSeriesInput.tsx
  client/web/src/enterprise/insights/components/creation-ui/form-series/components/form-series-input/get-pattern-type-filter.test.ts
  client/web/src/enterprise/insights/components/creation-ui/form-series/components/form-series-input/get-pattern-type-filter.ts
  client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
  client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-backend-insight-data/deserializators.ts
  client/web/src/enterprise/insights/core/backend/utils/create-line-chart-content.ts
  client/web/src/enterprise/insights/core/hooks/live-preview-insight/use-live-preview-series-insight.ts
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
  client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts
  client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
  client/web/src/enterprise/insights/pages/landing/getting-started/components/dynamic-code-insight-example/DynamicCodeInsightExample.tsx
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.codeinsights.json
  internal/database/schema.codeinsights.md
  migrations/codeinsights/1719914228_insight_series_modify_query/down.sql
  migrations/codeinsights/1719914228_insight_series_modify_query/metadata.yaml
  migrations/codeinsights/1719914228_insight_series_modify_query/up.sql
  migrations/codeinsights/squashed.sql
Labels: team/search-platform, cla-signed, team/product-platform

#63609 remove autocomplete limit from Cody dashboard page
  client/web/src/cody/management/SubscriptionStats.tsx
  client/web/src/cody/subscription/queries.tsx
  cmd/frontend/graphqlbackend/user.go
Labels: cla-signed

#63612 chore(local): sg warns about opposite default value on dev builds
  dev/sg/main.go
Labels: cla-signed

#63617 vsce: patch release v2.2.17
  client/vscode/CHANGELOG.md
  client/vscode/package.json
Labels: cla-signed

#63605 fix/cody-gateway: use keepalive/idle timeout options for Enterprise Portal
  cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/BUILD.bazel
  cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/enterpriseportal.go
Labels: cla-signed

#63608 fix(search): Don't show inline cody widget when new cody web is enabled
  client/web/src/repo/blob/CodeMirrorBlob.tsx
Labels: cla-signed

#63601 Trivial additions
  cmd/frontend/internal/httpapi/completions/handler.go
  internal/modelconfig/types/site_config.go
Labels: cla-signed

#63615 feat(svelte): Make diff headers on commit page sticky
  client/web-sveltekit/src/lib/repo/FileDiff.svelte
Labels: cla-signed

#63413 feat(cody-gateway): add support for Gemini models with context cache
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/httpapi/completions/get_model.go
  internal/completions/client/google/models.go
Labels: cla-signed

#63457 feat/enterpriseportal: init Cody Gateway Access table
  cmd/enterprise-portal/internal/database/codyaccess/BUILD.bazel
  cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
  cmd/enterprise-portal/internal/database/internal/tables/BUILD.bazel
  cmd/enterprise-portal/internal/database/internal/tables/tables.go
Labels: cla-signed

#63496 fix/internal/observation: make ErrCollector type threadsafe
  dev/rockskipintegration/main_test.go
  internal/observation/observation.go
Labels: cla-signed, team/source, team/product-platform

#63620 Svelte: add mutation observer to `sizeToFit`
  client/web-sveltekit/src/lib/dom.ts
Labels: cla-signed

#63621 Pick up CompletionsConfig.User for the AzureOpenAI API Provider
  cmd/frontend/internal/modelconfig/siteconfig_completions.go
  cmd/frontend/internal/modelconfig/siteconfig_completions_test.go
  internal/modelconfig/types/configuration.go
Labels: cla-signed

#63623 Fix annoying consistency
  internal/completions/client/azureopenai/openai.go
  internal/completions/client/client.go
Labels: cla-signed

#63619 Add SourcegraphModelConfig.AccessToken
  cmd/frontend/internal/modelconfig/siteconfig_completions_test.go
  internal/modelconfig/types/site_config.go
Labels: cla-signed

#63626 Add GenericProviderConfig.ServiceName
  cmd/frontend/internal/modelconfig/siteconfig_completions.go
  internal/modelconfig/types/configuration.go
  internal/modelconfig/validation.go
  internal/modelconfig/validation_test.go
Labels: cla-signed

#63591 Add a better Cody client server-sent configuration mechanism
  client/cody-shared/src/sourcegraph-api/graphql/client.ts
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/internal/clientconfig/BUILD.bazel
  cmd/frontend/internal/clientconfig/clientconfig.go
  cmd/frontend/internal/clientconfig/httpapi.go
  cmd/frontend/internal/clientconfig/httpapi_test.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  internal/clientconfig/BUILD.bazel
  internal/clientconfig/types.go
  internal/conf/computed.go
  internal/conf/computed_test.go
  internal/conf/conftypes/consts.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#63458 Add v2 telemetry infrastructure to browser extensions and native inte…
  client/browser/BUILD.bazel
  client/browser/package.json
  client/browser/src/browser-extension/scripts/backgroundPage.main.ts
  client/browser/src/browser-extension/scripts/optionsPage.main.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/platform/context.ts
  client/browser/src/shared/telemetry/gqlTelemetryExporter.ts
  client/browser/src/shared/telemetry/index.ts
  client/browser/src/shared/util/context.tsx
  pnpm-lock.yaml
Labels: cla-signed

#63529 backend/appliance: Introduce a basic utils package for appliance sourcegraph upgrades
  internal/appliance/upgrades/BUILD.bazel
  internal/appliance/upgrades/util.go
  internal/appliance/upgrades/util_test.go
  internal/oobmigration/version.go
  internal/version/version.go
Labels: cla-signed

#63629 Documents that usages are first bucketed by provenance
  cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Labels: team/graph, cla-signed, team/product-platform

#63632 fix(actions): update pinned SHA for `pnpm/action-setup` action
  .github/workflows/licenses-check.yml
Labels: cla-signed

#63592 fetch NamespaceSelector namespaces from GraphQL (`viewer { affiliatedNamespaces }`)
  client/web/BUILD.bazel
  client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx
  client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.tsx
  client/web/src/enterprise/batches/create/ConfigurationForm.story.tsx
  client/web/src/enterprise/batches/create/ConfigurationForm.tsx
  client/web/src/enterprise/batches/create/CreateBatchChangePage.story.tsx
  client/web/src/enterprise/batches/create/CreateBatchChangePage.tsx
  client/web/src/enterprise/batches/create/NamespaceSelector.tsx
  client/web/src/enterprise/batches/create/useNamespaces.ts
  client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
  client/web/src/namespaces/NamespaceSelector.story.tsx
  client/web/src/namespaces/NamespaceSelector.tsx
  client/web/src/namespaces/useAffiliatedNamespaces.test.tsx
  client/web/src/namespaces/useAffiliatedNamespaces.ts
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/affiliated_namespaces.go
  cmd/frontend/graphqlbackend/affiliated_namespaces_test.go
  cmd/frontend/graphqlbackend/graphqlbackend.go
  cmd/frontend/graphqlbackend/namespaces.go
  cmd/frontend/graphqlbackend/org_members.go
  cmd/frontend/graphqlbackend/schema.go
  cmd/frontend/graphqlbackend/viewer.go
  cmd/frontend/graphqlbackend/viewer.graphql
  cmd/frontend/graphqlbackend/visitor.go
  internal/auth/BUILD.bazel
  internal/auth/visitor.go
Labels: cla-signed

#63616 feat(batches): implement {site,user} credential authenticator for github apps
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/internal/batches/resolvers/BUILD.bazel
  cmd/frontend/internal/batches/resolvers/code_host_connection.go
  cmd/frontend/internal/batches/resolvers/credential.go
  cmd/frontend/internal/batches/resolvers/resolver.go
  cmd/frontend/internal/batches/resolvers/resolver_test.go
  internal/batches/sources/sources.go
  internal/batches/types/BUILD.bazel
  internal/batches/types/site_credential.go
  internal/database/BUILD.bazel
  internal/database/authenticator.go
  internal/database/user_credentials.go
  internal/database/user_credentials_test.go
  internal/github_apps/auth/BUILD.bazel
  internal/github_apps/auth/auth.go
  internal/github_apps/auth/credential.go
Labels: cla-signed

#63633 fix(batches): display failure alert depending on github app kind
  client/web/src/enterprise/batches/settings/CommitSigningIntegrations.tsx
Labels: cla-signed

#63634 Fix the scheduling interval for syntactic indexing
  cmd/worker/shared/BUILD.bazel
  cmd/worker/shared/main.go
  internal/codeintel/syntactic_indexing/scheduler_config.go
  internal/codeintel/syntactic_indexing/scheduler_job.go
Labels: team/graph, cla-signed, team/product-platform

#63637 Adds Option for codeintel
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/core/BUILD.bazel
  internal/codeintel/core/option.go
  internal/codeintel/core/option_test.go
Labels: team/graph, cla-signed, team/product-platform

#63642 fix(local): fix race in sg_start_test.go
  dev/sg/internal/run/logger.go
  dev/sg/sg_start_test.go
  lib/output/outputtest/buffer.go
Labels: cla-signed, no-changelog

#63643 Add ModelRef.APIVersionID()
  internal/modelconfig/types/refs.go
  internal/modelconfig/types/refs_test.go
  internal/modelconfig/validation.go
Labels: cla-signed

#63638 feat(svelte): Add Cody chat sidebar
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebar.gql
  client/web-sveltekit/src/lib/cody/CodySidebar.svelte
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
  client/web-sveltekit/src/lib/repo/stores.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/layout.gql
  client/web-sveltekit/vite.config.ts
  pnpm-lock.yaml
  sg.config.yaml
Labels: cla-signed

#63665 fix(svelte): Use 'pointer' pointer for cody button
  client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
Labels: cla-signed

#63548 chore(local): add dotcom-cody-e2e commandset
  sg.config.yaml
Labels: cla-signed

#63635 feat: implement functionality to create credential GitHub apps
  client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.story.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsPage.story.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.story.tsx
  client/web/src/enterprise/batches/settings/RemoveCredentialModal.story.tsx
  client/web/src/enterprise/batches/settings/ViewCredentialModal.story.tsx
  client/web/src/enterprise/batches/settings/backend.ts
  client/web/src/integration/batches.test.ts
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/internal/batches/resolvers/BUILD.bazel
  cmd/frontend/internal/batches/resolvers/batch_spec.go
  cmd/frontend/internal/batches/resolvers/changeset_counts_test.go
  cmd/frontend/internal/batches/resolvers/code_host.go
  cmd/frontend/internal/batches/resolvers/credential.go
  cmd/frontend/internal/batches/resolvers/errors.go
  cmd/frontend/internal/batches/resolvers/resolver.go
  cmd/frontend/internal/batches/webhooks/bitbucketserver_test.go
  cmd/frontend/internal/batches/webhooks/github_test.go
  cmd/frontend/internal/githubapp/BUILD.bazel
  cmd/frontend/internal/githubapp/httpapi.go
  cmd/frontend/internal/githubapp/httpapi_test.go
  cmd/frontend/internal/githubapp/parser.go
  cmd/worker/internal/githubapps/worker/installation_backfill_test.go
  internal/batches/reconciler/BUILD.bazel
  internal/batches/reconciler/executor.go
  internal/batches/service/BUILD.bazel
  internal/batches/service/errors.go
  internal/batches/service/service.go
  internal/batches/service/service_test.go
  internal/batches/sources/BUILD.bazel
  internal/batches/sources/sources.go
  internal/batches/sources/sources_test.go
  internal/batches/sources/testing/BUILD.bazel
  internal/batches/sources/testing/fake.go
  internal/batches/syncer/syncer.go
  internal/batches/types/site_credential.go
  internal/database/user_credentials.go
  internal/github_apps/store/mocks_temp.go
  internal/github_apps/store/store.go
  internal/github_apps/store/store_test.go
  internal/github_apps/types/BUILD.bazel
  internal/github_apps/types/types.go
Labels: cla-signed

#63670 remove long-unused UI routes
  cmd/frontend/internal/app/ui/router.go
Labels: cla-signed

#63092 feat/msp: allow enablement of logical replication features for Datastream
  deps.bzl
  dev/managedservicesplatform/internal/resource/cloudsql/cloudsql.go
  dev/managedservicesplatform/internal/resource/datastreamconnection/BUILD.bazel
  dev/managedservicesplatform/internal/resource/datastreamconnection/datastreamconnection.go
  dev/managedservicesplatform/internal/resource/postgresqllogicalreplication/BUILD.bazel
  dev/managedservicesplatform/internal/resource/postgresqllogicalreplication/postgresqllogicalreplication.go
  dev/managedservicesplatform/internal/resource/postgresqlroles/BUILD.bazel
  dev/managedservicesplatform/internal/resource/postgresqlroles/postgresqlroles.go
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/stacks/cloudrun/BUILD.bazel
  dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
  dev/managedservicesplatform/stacks/iam/BUILD.bazel
  dev/managedservicesplatform/stacks/iam/iam.go
  dev/managedservicesplatform/stacks/project/project.go
  go.mod
  go.sum
Labels: cla-signed

#63544 fix(appliance): allow services to be opted into
  internal/appliance/config/config.go
  internal/appliance/config/defaults.go
  internal/appliance/reconciler/frontend.go
  internal/appliance/reconciler/precise_code_intel.go
  internal/appliance/reconciler/testdata/golden-fixtures/cadvisor/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/grafana/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/grafana/with-existing-configmap.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/grafana/with-replicas.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/jaeger/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/jaeger/with-replicas.yaml
Labels: cla-signed, no-changelog

#63663 fix(svelte): Render correct error page
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/src/hooks.client.ts
  client/web-sveltekit/src/routes/+error.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/RepoNotFoundError.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
Labels: cla-signed

#63675 Bump code-web-experimental version to 0.2.0
  client/web/bundlesize.config.js
  client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
  client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.module.scss
  client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.tsx
  client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#63654 add new "modelConfiguration" schema to site config
  internal/modelconfig/types/configuration.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#63679 fix(svelte): Fixes excessive 'the hotkey ... has already been registered' messages
  client/web-sveltekit/src/lib/Hotkey.ts
  client/web-sveltekit/src/lib/Popover.svelte
Labels: cla-signed

#63673 chore(batches): simplify Sourcer interface
  cmd/frontend/internal/batches/resolvers/changeset_counts_test.go
  cmd/frontend/internal/batches/webhooks/bitbucketserver_test.go
  cmd/frontend/internal/batches/webhooks/github_test.go
  internal/batches/reconciler/executor.go
  internal/batches/reconciler/executor_test.go
  internal/batches/service/service.go
  internal/batches/sources/sources.go
  internal/batches/sources/sources_test.go
  internal/batches/sources/testing/BUILD.bazel
  internal/batches/sources/testing/fake.go
  internal/batches/syncer/syncer.go
Labels: cla-signed

#63504 feat(codeintel): Add scip-ctags support for Magik
  .github/workflows/scip-typescript.yml
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/scip-tags.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/languages.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_globals.magik.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__tags_snapshot_globals.magik.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/testdata/globals.magik
  internal/ctags_config/ctags_config.go
Labels: cla-signed, team/product-platform

#63688 fix(svelte): Properly load/serve version.json
  client/web-sveltekit/src/testing/integration.ts
  client/web-sveltekit/svelte.config.js
Labels: cla-signed

#63691 chore(svelte): Cleanup dependencies
  client/shared/BUILD.bazel
  client/shared/src/search/helpers.ts
  client/shared/src/search/index.ts
  client/shared/src/search/searchQueryState.tsx
  client/shared/src/search/stream.ts
  client/shared/src/search/types.ts
  client/shared/src/util/url.ts
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
  client/web/BUILD.bazel
  client/web/src/repo/blob/blameRecency.ts
  client/web/src/repo/blob/codemirror/tooltips/TemporaryTooltip.ts
  client/web/src/search/index.ts
  client/web/src/search/input/suggestions.ts
  client/web/src/util/settings.ts
  pnpm-lock.yaml
Labels: cla-signed

#63587 Search: restore snippets to filters sidebar
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
  client/branded/src/search-ui/results/filters/types.ts
  client/shared/src/search/stream.ts
  client/web-sveltekit/src/lib/search/dynamicFilters/CountBadge.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/SectionItem.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
  client/web-sveltekit/src/lib/wildcard/Badge.module.scss
  client/web-sveltekit/src/routes/search/page.spec.ts
Labels: cla-signed

#63676 feat(batches): allow use of github app token for gitserver push
  internal/batches/reconciler/executor.go
  internal/batches/sources/azuredevops.go
  internal/batches/sources/azuredevops_test.go
  internal/batches/sources/bitbucketcloud.go
  internal/batches/sources/bitbucketcloud_test.go
  internal/batches/sources/bitbucketserver.go
  internal/batches/sources/common.go
  internal/batches/sources/gerrit.go
  internal/batches/sources/gerrit_test.go
  internal/batches/sources/github.go
  internal/batches/sources/gitlab.go
  internal/batches/sources/mocks_test.go
  internal/batches/sources/perforce.go
  internal/batches/sources/sources.go
  internal/batches/sources/sources_test.go
  internal/batches/sources/testing/fake.go
Labels: cla-signed

#63692 fix/codygateway: tweak enterprise-portal dial options
  cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/enterpriseportal.go
Labels: cla-signed

#63693 fix(batches): fix broken `ghauth` import
  internal/batches/sources/sources.go
Labels: cla-signed

#63694 React app: bump cody web to 0.2.1
  client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#63695 Svelte: encode path components in file header
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
Labels: cla-signed

#63698 feat/dotcom: remove per-user Enterprise subscriptions UI
  client/web/BUILD.bazel
  client/web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.test.tsx
  client/web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.test.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
  client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserProductSubscriptionStatus.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsProductSubscriptionPage.test.tsx.snap
  client/web/src/enterprise/user/productSubscriptions/backend.ts
  client/web/src/user/settings/routes.tsx
  client/web/src/user/settings/sidebaritems.ts
Labels: cla-signed

#63697 site config: minor fixes, make modelConfiguration enable new backend models API, initial self-hosted model config
  client/web/src/site-admin/SiteAdminReportBugPage.tsx
  cmd/frontend/internal/clientconfig/clientconfig.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#63662 notebooks: set default pattern type to keyword
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.json
  internal/database/schema.md
  migrations/frontend/1720165387_notebooks_default_to_keyword_search/down.sql
  migrations/frontend/1720165387_notebooks_default_to_keyword_search/metadata.yaml
  migrations/frontend/1720165387_notebooks_default_to_keyword_search/up.sql
  migrations/frontend/squashed.sql
Labels: team/search-platform, cla-signed, team/product-platform

#63677 fix(svelte): Respect cody ignore settings
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebar.svelte
  client/web-sveltekit/src/lib/cody/config.test.ts
  client/web-sveltekit/src/lib/cody/config.ts
  client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/layout.gql
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
  client/web-sveltekit/src/testing/integration.ts
  pnpm-lock.yaml
Labels: cla-signed

#63701 chore(batches): remove `batches-github-app-integration` feature flag
  client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
Labels: cla-signed

#63689 chore(appliance): extract envtest helper package
  internal/appliance/k8senvtest/BUILD.bazel
  internal/appliance/k8senvtest/envtest.go
  internal/appliance/reconciler/BUILD.bazel
  internal/appliance/reconciler/helpers_test.go
  internal/appliance/reconciler/reconcile.go
Labels: cla-signed, no-changelog

#63667 chore(local): simplify sg teammate
  dev/sg/BUILD.bazel
  dev/sg/sg_teammate.go
Labels: cla-signed

#63613 batches: use "keyword" as default pattern type
  CHANGELOG.md
  client/web/src/enterprise/batches/batch-spec/edit/library/comby.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/go-imports.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/hello-world.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/many-comby.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/minimal.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/monorepo-dynamic.batch.yaml
  client/web/src/enterprise/batches/batch-spec/edit/library/sed.batch.yaml
  internal/batches/service/BUILD.bazel
  internal/batches/service/workspace_resolver.go
  internal/batches/service/workspace_resolver_test.go
  internal/search/streaming/http/BUILD.bazel
  internal/search/streaming/http/client.go
  internal/search/streaming/http/client_test.go
  lib/batches/batch_spec.go
  lib/batches/batch_spec_test.go
  lib/batches/schema/batch_spec_stringdata.go
  schema/batch_spec.schema.json
  schema/schema.go
Labels: team/search-platform, cla-signed, team/product-platform

#63705 feat(batches): Add "check" action to validate Github apps connection
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
  client/web/src/enterprise/batches/settings/GitHubAppControls.tsx
Labels: cla-signed

#63710 fix(svelte): Update cody web
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  pnpm-lock.yaml
Labels: cla-signed

#63684 feat(svelte): Add cody button to repo home page
  client/web-sveltekit/src/lib/cody/CodySidebar.svelte
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
  client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
Labels: cla-signed

#63603 feat(sg): one-time oauth login to persist user email for analytics
  dev/BUILD.bazel
  dev/sg/internal/analytics/BUILD.bazel
  dev/sg/internal/analytics/mocks_test.go
  dev/sg/internal/analytics/oauth.go
  dev/sg/internal/analytics/oauth_test.go
  dev/sg/main.go
  mockgen.test.yaml
Labels: sg, cla-signed

#63578 feat(sg): sqlite-backed local store for sg analytics
  deps.bzl
  dev/sg/BUILD.bazel
  dev/sg/analytics.go
  dev/sg/internal/analytics/BUILD.bazel
  dev/sg/internal/analytics/analytics.go
  dev/sg/internal/analytics/analytics_test.go
  dev/sg/internal/analytics/background.go
  dev/sg/internal/analytics/bigquery.go
  dev/sg/internal/analytics/context.go
  dev/sg/internal/analytics/spans.go
  dev/sg/internal/analytics/sqlite.go
  dev/sg/internal/analytics/tracer.go
  dev/sg/internal/background/BUILD.bazel
  dev/sg/internal/background/background.go
  dev/sg/internal/check/BUILD.bazel
  dev/sg/internal/check/runner.go
  dev/sg/internal/run/BUILD.bazel
  dev/sg/internal/run/installer.go
  dev/sg/main.go
  dev/sg/sg_analytics.go
  dev/sg/sg_update.go
  go.mod
  go.sum
Labels: cla-signed

#63709 chore: drop isGitHubApp field from batch changes credentials
  client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.story.tsx
  client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsPage.story.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.story.tsx
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
  client/web/src/enterprise/batches/settings/RemoveCredentialModal.story.tsx
  client/web/src/enterprise/batches/settings/ViewCredentialModal.story.tsx
  client/web/src/enterprise/batches/settings/backend.ts
  cmd/frontend/graphqlbackend/batches.go
  cmd/frontend/graphqlbackend/batches.graphql
  cmd/frontend/internal/batches/resolvers/resolver.go
Labels: cla-signed

#63702 adding deepseek-v2 and deepseek fine-tuned model trained on symbol graph context
  cmd/cody-gateway/internal/httpapi/completions/fireworks.go
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/httpapi/completions/get_model.go
  internal/completions/client/fireworks/fireworks.go
Labels: cla-signed

#63712 sg: when in CI we do not need to prompt for an identity
  dev/sg/main.go
Labels: cla-signed

#63717 fix: better alignemnt of github credentials and check success notice
  client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
  client/web/src/enterprise/batches/settings/GitHubAppControls.tsx
Labels: cla-signed

#63722 chore(local): sg analytics use the proper open wrapper
  dev/sg/internal/analytics/BUILD.bazel
  dev/sg/internal/analytics/oauth.go
Labels: cla-signed, no-changelog

#63720 keyword search: remove beta badge
  client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.tsx
Labels: team/search-platform, cla-signed, team/product-platform

#63715 update changelog: Keyword search GA
  CHANGELOG.md
Labels: team/search-platform, cla-signed, team/product-platform

#63723 Cody Web: bump cody web to 0.2.3
  client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#63714 chore: reword headline from tokens to credentials
  client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
Labels: cla-signed

#63718 chore(redis): set max active redis connections to 1000
  internal/redispool/redispool.go
Labels: cla-signed

#63725 chore(security): Updated dind image to 27-0-3
  dev/oci_deps.bzl
Labels: cla-signed, SSDLC

#63624 fix/client/dev: update proxy overwrite to respect authProviders
  client/web/dev/utils/get-api-proxy-settings.ts
Labels: cla-signed

#63563 feat(search): Make search aware of perforce changelist id mapping
  .vscode/settings.json
  client/web/src/repo/commits/GitCommitNode.tsx
  cmd/frontend/graphqlbackend/repository.go
  cmd/frontend/graphqlbackend/repository_test.go
  internal/database/dbmocks/mocks_temp.go
  internal/database/repo_commits_changelists.go
  internal/database/repo_commits_changelists_test.go
  internal/database/repos.go
  internal/database/repos_test.go
  internal/search/repos/BUILD.bazel
  internal/search/repos/repos.go
  internal/search/repos/repos_test.go
  internal/types/types.go
Labels: cla-signed, team/product-platform

#63706 modelconfig: handle converting site config JSON -> internal data types
  cmd/frontend/internal/modelconfig/BUILD.bazel
  cmd/frontend/internal/modelconfig/init.go
  cmd/frontend/internal/modelconfig/siteconfig.go
Labels: cla-signed

#63700 searcher: Modernize entrypoint and gRPC server
  cmd/searcher/internal/search/BUILD.bazel
  cmd/searcher/internal/search/filter.go
  cmd/searcher/internal/search/filter_test.go
  cmd/searcher/internal/search/hybrid.go
  cmd/searcher/internal/search/hybrid_test.go
  cmd/searcher/internal/search/search.go
  cmd/searcher/internal/search/search_grpc.go
  cmd/searcher/internal/search/search_grpc_logger.go
  cmd/searcher/internal/search/search_regex_test.go
  cmd/searcher/internal/search/search_test.go
  cmd/searcher/internal/search/store.go
  cmd/searcher/internal/search/store_test.go
  cmd/searcher/shared/BUILD.bazel
  cmd/searcher/shared/config.go
  cmd/searcher/shared/config_test.go
  cmd/searcher/shared/debug.go
  cmd/searcher/shared/service.go
  cmd/searcher/shared/shared.go
  internal/searcher/protocol/searcher.go
  internal/searcher/protocol/searcher_test.go
  internal/searcher/v1/searcher.pb.go
  internal/searcher/v1/searcher.proto
Labels: cla-signed, team/source, team/product-platform

#63727 feat(svelte): Add reblame support to blame column
  client/web-sveltekit/src/auto-imports.d.ts
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/blame/ReblameMarker.svelte
  client/web-sveltekit/src/lib/blame/reblame.ts
  client/web-sveltekit/src/lib/web.ts
  client/web/src/repo/blob/codemirror/blame-decorations.ts
Labels: cla-signed

#63726 Backend: add line index
  internal/byteutils/BUILD.bazel
  internal/byteutils/lineindex.go
  internal/byteutils/lineindex_test.go
Labels: cla-signed

#63729 squirrel: Correctly use request context
  cmd/symbols/squirrel/util.go
Labels: cla-signed, team/source, team/product-platform

#63731 Several refactoring to prepare for rolling out modelconfig
  cmd/frontend/internal/httpapi/completions/BUILD.bazel
  cmd/frontend/internal/httpapi/completions/entconfig_anthropic_test.go
  cmd/frontend/internal/httpapi/completions/entconfig_base_test.go
  cmd/frontend/internal/modelconfig/builder.go
  cmd/frontend/internal/modelconfig/service.go
  internal/completions/client/anthropic/anthropic.go
  internal/completions/client/awsbedrock/bedrock.go
  internal/completions/client/azureopenai/openai.go
  internal/completions/client/codygateway/codygateway.go
  internal/completions/client/fireworks/BUILD.bazel
  internal/completions/client/fireworks/fireworks.go
  internal/completions/client/fireworks/types.go
  internal/completions/client/google/google.go
  internal/completions/client/google/google_test.go
  internal/modelconfig/validation.go
  internal/modelconfig/validation_test.go
Labels: cla-signed

#63732 chore(svelte): Update to latest cody web version
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
  pnpm-lock.yaml
Labels: cla-signed

#63652 feat/dotcom: add Enterprise Portal auth proxy
  cmd/frontend/internal/enterpriseportal/BUILD.bazel
  cmd/frontend/internal/enterpriseportal/enterpriseportal_proxy.go
  cmd/frontend/internal/enterpriseportal/enterpriseportal_proxy_test.go
  cmd/frontend/internal/enterpriseportal/scopes.go
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  deps.bzl
  go.mod
  go.sum
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#63703 feat/enterpriseportal: database layer for subscriptions upsert
  cmd/enterprise-portal/internal/database/internal/upsert/BUILD.bazel
  cmd/enterprise-portal/internal/database/internal/upsert/upsert.go
  cmd/enterprise-portal/internal/database/internal/upsert/upsert_test.go
  cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
  cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
  cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.proto
Labels: cla-signed

#63728 feat(Source): Properly render multi-line changelist messages from Perforce
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/frontend/graphqlbackend/git_commit_test.go
  cmd/frontend/graphqlbackend/perforce_changelist.go
  cmd/frontend/graphqlbackend/perforce_changelist_test.go
Labels: cla-signed, team/product-platform

#63733 chore(svelte): Use MDI icons for seach input pattern type toggles
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/auto-imports.d.ts
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  pnpm-lock.yaml
Labels: cla-signed

#63740 fix(svelte): Prefill search home page query input with (default) context filter
  client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
  client/web-sveltekit/src/lib/search/BaseQueryInput.svelte
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web-sveltekit/src/lib/search/results.ts
  client/web-sveltekit/src/lib/search/state.ts
  client/web-sveltekit/src/routes/search/+page.ts
  client/web-sveltekit/src/routes/search/page.gql
  client/web-sveltekit/vite.config.ts
Labels: cla-signed

#63739 pass ModelConfigInfo down to client.Get() for self-hosted-models
  cmd/frontend/internal/clientconfig/clientconfig.go
  cmd/frontend/internal/completions/resolvers/BUILD.bazel
  cmd/frontend/internal/completions/resolvers/resolver.go
  cmd/frontend/internal/httpapi/completions/BUILD.bazel
  cmd/frontend/internal/httpapi/completions/get_model.go
  cmd/frontend/internal/httpapi/completions/handler.go
  cmd/frontend/internal/modelconfig/siteconfig.go
  internal/completions/client/BUILD.bazel
  internal/completions/client/client.go
  internal/completions/types/BUILD.bazel
  internal/completions/types/types.go
  internal/conf/computed.go
Labels: cla-signed

#63708 symbols: Minor code cleanup
  cmd/symbols/shared/setup.go
  internal/symbols/BUILD.bazel
  internal/symbols/client.go
Labels: cla-signed, team/source, team/product-platform

#63644 rcache: Explicitly pass redis pool to use
  cmd/cody-gateway/shared/main.go
  cmd/frontend/backend/BUILD.bazel
  cmd/frontend/backend/go_importers.go
  cmd/frontend/backend/inventory.go
  cmd/frontend/graphqlbackend/graphqlbackend_test.go
  cmd/frontend/graphqlbackend/main_test.go
  cmd/frontend/graphqlbackend/recorded_commands.go
  cmd/frontend/graphqlbackend/recorded_commands_test.go
  cmd/frontend/graphqlbackend/search_results.go
  cmd/frontend/graphqlbackend/slow_requests_tracer.go
  cmd/frontend/graphqlbackend/user_emails_test.go
  cmd/frontend/internal/executorqueue/handler/BUILD.bazel
  cmd/frontend/internal/executorqueue/handler/multihandler.go
  cmd/frontend/internal/githubapp/BUILD.bazel
  cmd/frontend/internal/githubapp/httpapi.go
  cmd/frontend/internal/githubapp/httpapi_test.go
  cmd/worker/internal/executors/BUILD.bazel
  cmd/worker/internal/executors/janitor_job.go
  cmd/worker/internal/executors/multiqueue_cache_cleaner_test.go
  cmd/worker/internal/licensecheck/BUILD.bazel
  cmd/worker/internal/licensecheck/check.go
  cmd/worker/internal/licensecheck/check_test.go
  cmd/worker/internal/licensecheck/worker.go
  internal/auth/userpasswd/BUILD.bazel
  internal/auth/userpasswd/lockout.go
  internal/authz/providers/github/BUILD.bazel
  internal/authz/providers/github/github.go
  internal/codeintel/uploads/transport/http/auth/BUILD.bazel
  internal/codeintel/uploads/transport/http/auth/github_cache.go
  internal/completions/tokenusage/BUILD.bazel
  internal/completions/tokenusage/tokenusage.go
  internal/completions/tokenusage/tokenusage_test.go
  internal/extsvc/awscodecommit/BUILD.bazel
  internal/extsvc/awscodecommit/client.go
  internal/extsvc/gitlab/BUILD.bazel
  internal/extsvc/gitlab/client.go
  internal/extsvc/gitlab/util_test.go
  internal/github_apps/auth/BUILD.bazel
  internal/github_apps/auth/auth.go
  internal/goroutine/recorder/BUILD.bazel
  internal/goroutine/recorder/common.go
  internal/goroutine/recorder/common_test.go
  internal/httpcli/BUILD.bazel
  internal/httpcli/client.go
  internal/httpcli/redis_logger_middleware.go
  internal/rcache/fifo_list.go
  internal/rcache/fifo_list_test.go
  internal/rcache/rcache.go
  internal/rcache/rcache_test.go
  internal/wrexec/BUILD.bazel
  internal/wrexec/recording_cmd.go
  internal/wrexec/recording_cmd_test.go
Labels: cla-signed

#63625 codygateway: Use only one redis pool and make REDIS_ENDPOINT a clear requirement in config
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/diagnostics.go
  cmd/cody-gateway/shared/BUILD.bazel
  cmd/cody-gateway/shared/config/config.go
  cmd/cody-gateway/shared/main.go
  cmd/cody-gateway/shared/redis.go
Labels: cla-signed, team/source, team/product-platform

#63645 Remove old cache cleanup method
  cmd/frontend/internal/bg/BUILD.bazel
  cmd/frontend/internal/bg/delete_old_cache_data_in_redis.go
  cmd/frontend/internal/cli/serve_cmd.go
  internal/rcache/rcache.go
Labels: cla-signed, team/source, team/product-platform

#63682 phabricator: Move syncer to worker
  cmd/repo-updater/shared/BUILD.bazel
  cmd/repo-updater/shared/main.go
  cmd/worker/internal/phabricator/BUILD.bazel
  cmd/worker/internal/phabricator/job.go
  cmd/worker/internal/phabricator/phabricator.go
Labels: cla-signed, team/source, team/product-platform

#63681 scheduler: Simplify query for uncloned repos
  cmd/repo-updater/shared/main.go
Labels: cla-signed, team/source, team/product-platform

#63646 Remove unused package
  go.mod
  internal/security/gsm/BUILD.bazel
  internal/security/gsm/gsm.go
  internal/security/gsm/gsm_test.go
Labels: cla-signed, team/source, team/product-platform

#63647 Unexport some externally irrelevant symbols from uploadstore
  internal/uploadstore/gcs_client.go
  internal/uploadstore/pool.go
  internal/uploadstore/reader.go
  internal/uploadstore/s3_client.go
Labels: cla-signed, team/source, team/product-platform

#63742 Bump cody-web-experimental to 0.2.4
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#63746 fix: remove watch path that's gone
  sg.config.yaml
Labels: cla-signed

#63747 chore(svelte): Update cody web version
  client/web-sveltekit/package.json
  pnpm-lock.yaml
Labels: cla-signed

#63606 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/appliance.lock.json
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#63640 docs: Fix inaccuracies in RangeInput GraphQL docs
  cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Labels: team/graph, cla-signed, team/product-platform

#63748 feat(sg/cloud): trigger build on cloud-ephemeral pipeline
  dev/sg/internal/cloud/deploy_command.go
Labels: cla-signed

#63610 Adds a test for search-based usages
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_syntactic_usages_test.go
  internal/codeintel/codenav/syntactic.go
  internal/codeintel/codenav/utils_test.go
Labels: team/graph, cla-signed, team/product-platform

#63750 chore(security) : upgrade src-cli version to address CVE
  dev/tool_deps.bzl
Labels: cla-signed, SSDLC

#63751 fix(batches): enable check for creating source as non credential
  internal/batches/reconciler/executor.go
Labels: cla-signed

#63749 chore(appliance): SetupEnvtest returns k8s config, not client
  internal/appliance/k8senvtest/BUILD.bazel
  internal/appliance/k8senvtest/envtest.go
  internal/appliance/reconciler/BUILD.bazel
  internal/appliance/reconciler/helpers_test.go
Labels: cla-signed, no-changelog

#63738 Chore: remove gorilla/schema
  cmd/frontend/internal/httpapi/BUILD.bazel
  cmd/frontend/internal/httpapi/httpapi.go
  deps.bzl
  go.mod
  go.sum
  internal/errcode/BUILD.bazel
  internal/errcode/code.go
  third-party-licenses/ThirdPartyLicenses.csv
Labels: cla-signed

#63611 fix(perforce) Fix support for p4breaker workaround scripts
  cmd/gitserver/internal/perforce/protects.go
  cmd/gitserver/internal/perforce/protects_test.go
Labels: cla-signed, team/source, team/product-platform

#63171 chore/otel-collector: upgrade to v0.103.0, remove jaegerexporter
  cmd/frontend/internal/app/otlpadapter/otlp.go
  cmd/frontend/internal/app/otlpadapter/register.go
  deps.bzl
  doc/dependency_decisions.yml
  docker-images/jaeger-all-in-one/BUILD.bazel
  docker-images/opentelemetry-collector/builder.template.yaml
  docker-images/opentelemetry-collector/configs/group.yaml
  docker-images/opentelemetry-collector/configs/honeycomb.yaml
  docker-images/opentelemetry-collector/configs/jaeger-tailsampling.yaml
  docker-images/opentelemetry-collector/configs/jaeger.yaml
  go.mod
  go.sum
  internal/search/job/jobutil/exhaustive_job_test.go
  internal/search/job/jobutil/job_test.go
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/go.sum
  sg.config.yaml
  wolfi-packages/opentelemetry-collector.yaml
  wolfi-packages/opentelemetry-collector/builder.template.yaml
Labels: cla-signed

#63756 chore: add changelog entry for Batch Changes <> GitHub apps integration
  CHANGELOG.md
Labels: cla-signed

#63755 fix(build): update wolfi image lock for otel
  wolfi-images/opentelemetry-collector.lock.json
Labels: cla-signed

#63653 feat/dotcom: use Enterprise Portal for Cody Gateway usage
  .eslintrc.js
  .prettierignore
  client/shared/package.json
  client/web/BUILD.bazel
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminCreateProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/backend.ts
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/enterpriseportal.ts
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/enterpriseportalgen/codyaccess-CodyAccessService_connectquery.ts
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/enterpriseportalgen/codyaccess_pb.ts
  lib/enterpriseportal/codyaccess/v1/buf.gen.yaml
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#63759 fix/internal/txemail: add timeout for SMTP connection establishment
  internal/txemail/txemail.go
Labels: cla-signed, team/source, team/product-platform

#63760 feat/graphql/access_tokens: send access token creation/deletion emails in background and create special message for dial errors
  cmd/frontend/graphqlbackend/access_tokens.go
Labels: cla-signed, team/source, team/product-platform

#63719 feat(svelte): Add 'y' shortcut to navigate to permalink
  client/web-sveltekit/src/lib/repo/Permalink.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts
Labels: cla-signed
