Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-05, with the labels that each got.

#62315 sg/msp: add service lists to help text, improve completions
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/helpers.go
  dev/sg/msp/repo/repo.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#61770 Fix OOB migrations progress updates
  client/web/src/site-admin/SiteAdminMigrationsPage.story.tsx
  client/web/src/site-admin/SiteAdminMigrationsPage.tsx
  client/web/src/site-admin/backend.ts
  cmd/frontend/graphqlbackend/oobmigrations.go
  cmd/frontend/graphqlbackend/schema.graphql
  cmd/frontend/graphqlbackend/site.go
  cmd/frontend/graphqlbackend/site_test.go
  cmd/worker/internal/migrations/BUILD.bazel
  cmd/worker/internal/migrations/init.go
  internal/oobmigration/runner.go
  internal/oobmigration/version.go
  internal/updatecheck/client.go
Labels: cla-signed

#62165 gitserver: port FirstEverCommit functionality from client to git cli backend
  cmd/gitserver/internal/git/gitcli/odb.go
  cmd/gitserver/internal/git/gitcli/odb_test.go
  cmd/gitserver/internal/git/iface.go
  cmd/gitserver/internal/git/mock.go
  cmd/gitserver/internal/git/observability.go
  internal/gitserver/gitdomain/errors.go
  internal/insights/gitserver/BUILD.bazel
  internal/insights/gitserver/first_commit.go
  internal/insights/gitserver/first_commit_test.go
Labels: cla-signed, team/source, team/product-platform

#62169 gitserver: grpc: create FirstEverCommit RPC method and server implementation
  cmd/gitserver/internal/git/observability.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_logger.go
  cmd/gitserver/internal/server_grpc_test.go
  internal/gitserver/errwrap.go
  internal/gitserver/mock.go
  internal/gitserver/retry.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
Labels: cla-signed, team/source, team/product-platform

#62173 gitserver: grpc: switch clientImplementor to use new dedicated gRPC method for FirstEverCommit
  CHANGELOG.md
  internal/gitserver/BUILD.bazel
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/insights/gitserver/first_commit.go
Labels: cla-signed, team/source, team/product-platform

#62302 codeinsights: remove now useless empty repo string error check
  internal/insights/gitserver/first_commit.go
  internal/insights/gitserver/first_commit_test.go
Labels: cla-signed, team/source, team/product-platform

#62328 Update wording on account mismatch for Cody PLG Manage page
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/switch-account/CodySwitchAccountPage.tsx
Labels: cla-signed

#62330 chore: Remove empty graphql file
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/codeintel.graphql
Labels: team/graph, cla-signed, team/product-platform

#62333 release: allow development flag in release ops
  dev/ci/internal/ci/release_operations.go
Labels: cla-signed

#62291 build-tracker: change trigger-build values for not checking out sg/sg
  dev/build-tracker/BUILD.bazel
  dev/build-tracker/config/config.go
  dev/build-tracker/main.go
Labels: cla-signed, team/dev-infra, di/ci-obs

#62278 [Svelte]: Visual fixes for svelte blame panel
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/Timestamp.svelte
  client/web-sveltekit/src/lib/blame/BlameDecoration.svelte
  client/web/src/repo/blob/codemirror/blame-decorations.ts
Labels: cla-signed

#62339 ci: don't emit bep for non-test commands
  .aspect/bazelrc/ci.sourcegraph.bazelrc
Labels: ci, cla-signed

#62213 sg/msp: architecture diagrams
  deps.bzl
  dev/managedservicesplatform/operationdocs/diagram/BUILD.bazel
  dev/managedservicesplatform/operationdocs/diagram/assets/BUILD.bazel
  dev/managedservicesplatform/operationdocs/diagram/assets/README.md
  dev/managedservicesplatform/operationdocs/diagram/assets/assets.go
  dev/managedservicesplatform/operationdocs/diagram/assets/bigquery
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudarmor
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudflare
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudmemorystore
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudmonitoring
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudrun
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudsql
  dev/managedservicesplatform/operationdocs/diagram/assets/cloudtrace
  dev/managedservicesplatform/operationdocs/diagram/assets/externalipaddress
  dev/managedservicesplatform/operationdocs/diagram/assets/internet
  dev/managedservicesplatform/operationdocs/diagram/assets/loadbalancer
  dev/managedservicesplatform/operationdocs/diagram/assets/opsgenie
  dev/managedservicesplatform/operationdocs/diagram/assets/sentry
  dev/managedservicesplatform/operationdocs/diagram/assets/vpc
  dev/managedservicesplatform/operationdocs/diagram/components.go
  dev/managedservicesplatform/operationdocs/diagram/diagram.go
  dev/managedservicesplatform/operationdocs/diagram/msp.go
  dev/managedservicesplatform/operationdocs/diagram/options.go
  dev/managedservicesplatform/operationdocs/index.go
  dev/managedservicesplatform/operationdocs/operationdocs.go
  dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/multi_env_rollout.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/with_README.golden
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/sg_msp.go
  doc/dependency_decisions.yml
  go.mod
  go.sum
Labels: cla-signed

#62340 build-tracker: fix convenience urls in env
  dev/build-tracker/BUILD.bazel
  dev/build-tracker/main.go
  dev/build-tracker/server_test.go
  internal/testutil/istest.go
Labels: ci, cla-signed

#62342 docs: Fix Sourcegraph Secret regex format
  doc/dev/security/secret_formats.md
Labels: cla-signed

#62286 appliance: default config
  internal/appliance/BUILD.bazel
  internal/appliance/blobstore.go
  internal/appliance/config/config.go
  internal/appliance/defaults.go
  internal/appliance/reconcile.go
  internal/appliance/spec.go
  internal/appliance/symbols.go
  internal/appliance/testdata/golden-fixtures/blobstore-default.yaml
  internal/appliance/testdata/golden-fixtures/blobstore-subsequent-disable.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater-default.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater-with-no-resources.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater-with-pod-template-config.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater-with-resources.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater-with-sa-annotations.yaml
  internal/appliance/testdata/golden-fixtures/symbols-default.yaml
  internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml
  internal/k8s/resource/service/service.go
Labels: cla-signed

#62316 svelte: Update some aspects diff view and history panel
  client/web-sveltekit/src/app.d.ts
  client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/CloseViewAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
Labels: cla-signed, team/code-search

#62287 Svelte: simplify file header
  client/web-sveltekit/src/lib/shared.ts
  client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
Labels: cla-signed

#62254 Code monitors: add some levers for tuning resource usage
  internal/codemonitors/background/workers.go
  internal/codemonitors/search.go
  internal/conf/computed.go
  internal/search/commit/commit.go
  internal/search/job/jobutil/exhaustive_job.go
  internal/search/job/jobutil/job.go
  schema/schema.go
  schema/site.schema.json
Labels: cla-signed

#62323 svelte: Fix code/blame view for rich HTML files
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
Labels: bug, cla-signed, team/code-search

#62337 Svelte: Visual update to history and reference bottom panel
  client/web-sveltekit/src/lib/Tabs.svelte
  client/web-sveltekit/src/lib/repo/LastCommit.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#62298 Svelte: Fix width of revision picker
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte
Labels: cla-signed

#62223 Remove 'cody-payments-testing-mode'
  client/web/BUILD.bazel
  client/web/src/cody/featureFlags.ts
  client/web/src/cody/management/CodyManagementPage.tsx
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
  client/web/src/cody/util.ts
  client/web/src/featureFlags/featureFlags.ts
Labels: cla-signed

#62312 Build AMIs on release
  .github/workflows/release-amis.yml
Labels: cla-signed

#62346 Pass go debug flags to zoekt to enable better debugging
  sg.config.yaml
Labels: cla-signed, team/product-platform

#62343 Svelte: Color and style changes throughout search results and file view
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/lib/repo/FileDiffHunks.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/HelpFooter.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
  client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/Picker.svelte
  client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
  client/web-sveltekit/src/routes/search/SearchResult.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#62347 Svelte: hide commit body if null
  client/web-sveltekit/src/lib/Commit.svelte
Labels: cla-signed

#62317 Svelte: compress progress indicator
  client/web-sveltekit/src/lib/LoadingSpinner.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web-sveltekit/src/routes/search/StreamingProgress.svelte
Labels: cla-signed

#62352 use row-gap instead of padding
  client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
Labels: cla-signed

#62351 Svelte: Font size tweaks for results indicator
  client/web-sveltekit/src/lib/search/resultsIndicator/ProgressMessage.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
  client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#62356 svelte: Fix user name in "last commit" message
  client/web-sveltekit/src/lib/repo/LastCommit.gql
  client/web-sveltekit/src/lib/repo/LastCommit.svelte
Labels: cla-signed, team/code-search

#62357 svelte: Set max width for repo page
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
Labels: cla-signed, team/code-search

#62070 gitserver: Simplify invocation of p4-fusion
  cmd/gitserver/BUILD.bazel
  cmd/gitserver/README.md
  cmd/gitserver/image_test.yaml
  cmd/gitserver/p4-fusion-wrapper-detect-kill.sh
  cmd/gitserver/process-stats-watcher.sh
  cmd/server/BUILD.bazel
  cmd/server/image_test.yaml
  wolfi-images/gitserver.lock.json
  wolfi-images/server.lock.json
Labels: cla-signed, team/source, team/product-platform

#62259 rockskip: Switch from long-running process to pagination
  cmd/symbols/gitserver/client.go
  internal/batches/sources/mocks_test.go
  internal/gitserver/BUILD.bazel
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/gitdomain/log.go
  internal/gitserver/mocks_temp.go
  internal/rockskip/BUILD.bazel
  internal/rockskip/server_test.go
Labels: cla-signed, team/source, team/product-platform

#62344 Use newer config settings if available (allow local SAMS/SSC dev)
  cmd/frontend/graphqlbackend/external_account.go
  cmd/frontend/internal/app/ui/router.go
  cmd/frontend/internal/cody/subscription.go
  cmd/frontend/internal/cody/subscription_test.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
  cmd/frontend/internal/httpapi/ssc.go
  cmd/frontend/internal/ssc/ssc.go
Labels: cla-signed

#62365 Svelte: Revert code bg changes
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/repo/FileDiffHunks.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
  client/web-sveltekit/src/routes/search/SearchResult.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#62276 sg: add command to list versions from cloud ephemeral registry
  deps.bzl
  dev/sg/internal/cloud/BUILD.bazel
  dev/sg/internal/cloud/list_versions_command.go
  dev/sg/sg_cloud.go
  go.mod
  go.sum
Labels: cla-signed

#62269 release: handle more registries for promotion
  dev/ci/internal/ci/images_operations.go
  dev/ci/internal/ci/release_operations.go
  dev/ci/push_all.sh
  tools/release/promote_images.sh
Labels: cla-signed

#62366 Svelte: Fixes shadows on file view
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#62349 Svelte: Highlight file/dir name on selected item in file tree.
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed

#62372 svelte: Fix author avatar size on commit page
  client/web-sveltekit/src/lib/Commit.svelte
Labels: bug, cla-signed, team/code-search

#62379 Svelte: Support custom position target for Popover element
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte
Labels: cla-signed

#62371 chore: Enable rustfmt
  .bazelrc
  docker-images/syntax-highlighter/BUILD.bazel
  docker-images/syntax-highlighter/README.md
  docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
  docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/ctags.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_html.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/languages.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/testdata/ts-tags.rs
  docker-images/syntax-highlighter/src/bin/scip-ctags.rs
  docker-images/syntax-highlighter/src/lib.rs
Labels: team/graph, cla-signed, team/product-platform

#61721 Add modal to remind users to connect external accounts
  client/shared/src/settings/temporary/TemporarySettings.ts
  client/web/BUILD.bazel
  client/web/dev/utils/create-js-context.ts
  client/web/src/LegacyLayout.tsx
  client/web/src/auth/SignInPage.story.tsx
  client/web/src/auth/SignInPage.test.tsx
  client/web/src/auth/SignUpPage.story.tsx
  client/web/src/auth/SignUpPage.test.tsx
  client/web/src/auth/UnlockAccount.story.tsx
  client/web/src/external-account-modal/ExternalAccountsModal.module.scss
  client/web/src/external-account-modal/ExternalAccountsModal.tsx
  client/web/src/featureFlags/featureFlags.ts
  client/web/src/integration/jscontext.ts
  client/web/src/jscontext.ts
  client/web/src/user/settings/auth/ExternalAccount.test.tsx
  client/web/src/user/settings/auth/ExternalAccountsSignIn.test.tsx
  client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
  cmd/frontend/internal/app/jscontext/BUILD.bazel
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/authz/resolvers/resolver_test.go
Labels: cla-signed, team/source, team/product-platform

#62384 Svelte: Fix blame decoration line layout
  client/web-sveltekit/src/lib/blame/BlameDecoration.svelte
Labels: cla-signed

#62266 Add 'internal' case for repositoryQuery
  CHANGELOG.md
  internal/repos/github.go
  internal/repos/github_test.go
  internal/repos/testdata/golden/TestGitHubSource_InternalRepositories
  internal/repos/testdata/sources/TestGitHubSource_InternalRepositories.yaml
  schema/github.schema.json
  schema/schema.go
Labels: cla-signed, team/source, team/product-platform

#62385 Fix test for SignInPage
  client/web/src/auth/SignInPage.test.tsx
Labels: cla-signed, team/source, team/product-platform

#62388 fix: update link for fuzzyfinder feedback
  client/web/src/components/fuzzyFinder/FuzzyModal.tsx
Labels: cla-signed

#62383 svelte: Make several improvements to the commit page
  client/web-sveltekit/src/lib/repo/DiffSquares.svelte
  client/web-sveltekit/src/lib/repo/FileDiff.svelte
  client/web-sveltekit/src/lib/wildcard/CopyButton.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/page.gql
  client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
  client/web-sveltekit/src/routes/search/SearchResult.svelte
  client/wildcard/src/components/Button/Button.module.scss
Labels: cla-signed, team/code-search

#62373 svelte: Improve tooltip target logic
  client/web-sveltekit/src/lib/Timestamp.test.ts
  client/web-sveltekit/src/lib/Tooltip.svelte
Labels: cla-signed, team/code-search

#62318 httpcli: Move init function from conf package into httpcli
  cmd/frontend/shared/BUILD.bazel
  cmd/frontend/shared/shared.go
  internal/conf/BUILD.bazel
  internal/conf/init.go
  internal/httpcli/BUILD.bazel
  internal/httpcli/external.go
  internal/httpcli/init.go
  internal/httpcli/redis_logger_middleware.go
  internal/httpcli/redis_logger_middleware_test.go
  internal/service/svcmain/BUILD.bazel
  internal/service/svcmain/svcmain.go
Labels: cla-signed, team/source, team/product-platform

#62345 scip-ctags: Fix line number mismatch due to scopes
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/python/scip-tags.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/ctags.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_globals.cs.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_globals.py.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__tags_snapshot_globals.cs.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__tags_snapshot_globals.py.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__tags_snapshot_globals.ts.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/testdata/globals.cs
Labels: cla-signed, team/product-platform

#62319 embeddings: Use default InternalDoer
  internal/embeddings/client.go
Labels: cla-signed, team/source, team/product-platform

#62320 httpcli: Unexport internal client factory
  internal/httpcli/client.go
Labels: cla-signed, team/source, team/product-platform

#62321 httpcli: Remove useless err check
  internal/httpcli/client.go
Labels: cla-signed, team/source, team/product-platform

#62406 Fix(sg/release): Create branch if it doesn't exist
  dev/sg/internal/release/cut.go
  dev/sg/internal/repo/git_repo.go
Labels: cla-signed

#62212 gitserver: grpc: port GetBehindAhead from client to gitcli backend
  cmd/gitserver/internal/git/gitcli/odb.go
  cmd/gitserver/internal/git/gitcli/odb_test.go
  cmd/gitserver/internal/git/iface.go
  cmd/gitserver/internal/git/mock.go
  cmd/gitserver/internal/git/observability.go
Labels: cla-signed, team/source, team/product-platform

#62229 chore(gh): FR template tells where to submit them
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla-signed

#62335 chore: Group upload matching options into struct
  internal/codeintel/codenav/iface.go
  internal/codeintel/codenav/mocks_test.go
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/resolvers/BUILD.bazel
  internal/codeintel/resolvers/codenav.go
  internal/codeintel/uploads/BUILD.bazel
  internal/codeintel/uploads/internal/background/backfiller/mocks_test.go
  internal/codeintel/uploads/internal/background/expirer/mocks_test.go
  internal/codeintel/uploads/internal/background/processor/mocks_test.go
  internal/codeintel/uploads/internal/store/commitgraph.go
  internal/codeintel/uploads/internal/store/commitgraph_test.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/mocks_test.go
  internal/codeintel/uploads/service.go
  internal/codeintel/uploads/shared/BUILD.bazel
  internal/codeintel/uploads/shared/types.go
Labels: team/graph, cla-signed, team/product-platform

#62414 Revert "ci: remove softfail backcompat mitigation (#62230)"
  .buildkite/pipeline.backcompat.yml
Labels: cla-signed

#62411 svelte: Use file icons on tree page
  client/web-sveltekit/src/lib/repo/FileTable.svelte
  client/web-sveltekit/src/lib/repo/api/tree.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed, team/code-search

#62412 svelte: Improve file sidebar's scroll into view behavior
  client/web-sveltekit/src/lib/TreeView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed, team/code-search

#62407 svelte: Hide commit message toggle button when there is no commit message
  client/web-sveltekit/src/lib/Commit.svelte
Labels: cla-signed, team/code-search

#62336 release: disable promotion of development release & add --development flag to baseFlags
  dev/sg/internal/release/config.go
  dev/sg/internal/release/release.go
Labels: cla-signed

#62419 release: update changelog
  CHANGELOG.md
Labels: cla-signed

#62422 sg: improve error message when watching files
  dev/sg/internal/run/sgconfig_command.go
Labels: cla-signed

#62353 Updates to cookies sent to HubSpot
  cmd/frontend/hubspot/contacts.go
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/auth/oauth/session.go
  cmd/frontend/internal/auth/openidconnect/middleware.go
  cmd/frontend/internal/auth/openidconnect/user_test.go
  internal/auth/userpasswd/handlers.go
Labels: cla-signed

#62216 gitserver: grpc: create server implementation for GetBehindAhead
  cmd/frontend/graphqlbackend/git_commit.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_logger.go
  cmd/gitserver/internal/server_grpc_test.go
  doc/dev/background-information/gitserver-api.md
  internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/errwrap.go
  internal/gitserver/gitdomain/common.go
  internal/gitserver/gitdomain/common_test.go
  internal/gitserver/mock.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/observability.go
  internal/gitserver/retry.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
Labels: cla-signed, team/source, team/product-platform

#62217 gitserver: grpc: swap client implementation of GetAheadBehind from Exec to bespoke gRPC endpoint
  CHANGELOG.md
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
Labels: cla-signed, team/source, team/product-platform

#62178 gitserver: Improve signal handling and maxRSS reporting
  cmd/gitserver/internal/git/gitcli/archivereader_test.go
  cmd/gitserver/internal/git/gitcli/blame_test.go
  cmd/gitserver/internal/git/gitcli/command.go
  cmd/gitserver/internal/git/gitcli/diff_test.go
  cmd/gitserver/internal/git/gitcli/exec_test.go
  cmd/gitserver/internal/git/gitcli/odb_test.go
  cmd/gitserver/internal/git/gitcli/refs_test.go
  cmd/gitserver/shared/shared.go
Labels: cla-signed, team/source, team/product-platform

#62424 gitserver: Fixup confusing label on monitoring dashboard
  doc/admin/observability/dashboards.md
  monitoring/definitions/shared/gitserver.go
Labels: cla-signed, team/source, team/product-platform

#62325 msp/operationdocs: write to Notion instead of Markdown
  deps.bzl
  dev/managedservicesplatform/operationdocs/BUILD.bazel
  dev/managedservicesplatform/operationdocs/diagram/diagram.go
  dev/managedservicesplatform/operationdocs/index.go
  dev/managedservicesplatform/operationdocs/internal/markdown/BUILD.bazel
  dev/managedservicesplatform/operationdocs/internal/markdown/headings/BUILD.bazel
  dev/managedservicesplatform/operationdocs/internal/markdown/headings/headings.go
  dev/managedservicesplatform/operationdocs/internal/markdown/inline.go
  dev/managedservicesplatform/operationdocs/internal/markdown/markdown.go
  dev/managedservicesplatform/operationdocs/notion.go
  dev/managedservicesplatform/operationdocs/operationdocs.go
  dev/managedservicesplatform/operationdocs/operationdocs_test.go
  dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/multi_env_rollout.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRender/with_README.golden
  dev/managedservicesplatform/operationdocs/testdata/TestRenderIndexPage.golden
  dev/managedservicesplatform/spec/service.go
  dev/sg/msp/BUILD.bazel
  dev/sg/msp/helpers.go
  dev/sg/msp/notion.go
  dev/sg/msp/sg_msp.go
  go.mod
  go.sum
Labels: cla-signed

#62434 gitserver: Temporarily disable highmem reporting
  cmd/gitserver/internal/git/gitcli/command.go
Labels: cla-signed, team/source, team/product-platform

#62433 bug/release: Add nil check for undeprecated oob migrations
  internal/oobmigration/runner.go
Labels: cla-signed, backport/bugfix

#62409 [Svelte]: Fix popover onHover mode
  client/web-sveltekit/src/lib/Popover.svelte
Labels: cla-signed

#62439 appliance: symbols: fix PVC name
  internal/appliance/repo_updater.go
  internal/appliance/symbols.go
  internal/appliance/testdata/golden-fixtures/symbols-default.yaml
  internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml
  internal/k8s/resource/container/container.go
  internal/k8s/resource/pvc/pvc.go
Labels: cla-signed

#62163 Fixing OpenAI TokenUsage to replace internally implemented token counter with openai response
  internal/completions/client/anthropic/anthropic.go
  internal/completions/client/awsbedrock/bedrock.go
  internal/completions/client/openai/openai.go
  internal/completions/tokenusage/tokenusage.go
Labels: cla-signed

#62421 Svelte: Calm down shadows and strip down blame header
  client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/svelte-overrides.scss
Labels: cla-signed

#62431 svelte: Improve page title updates
  client/web-sveltekit/src/routes/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FilePreview.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
  client/web-sveltekit/src/routes/search/+page.svelte
  client/web-sveltekit/src/routes/search/SearchResults.svelte
Labels: cla-signed, team/code-search

#62423 svelte: Improve utility of commits page
  client/web-sveltekit/src/lib/Commit.svelte
  client/web-sveltekit/src/lib/search/input/SearchInput.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.gql
  client/web-sveltekit/vite.config.ts
Labels: cla-signed, team/code-search

#62449 sg: cloud handle ephemeral lease extension/reduction
  dev/sg/internal/cloud/BUILD.bazel
  dev/sg/internal/cloud/client.go
  dev/sg/internal/cloud/common.go
  dev/sg/internal/cloud/delete_command.go
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/cloud/instance.go
  dev/sg/internal/cloud/lease_command.go
  dev/sg/internal/cloud/list_command.go
  dev/sg/internal/cloud/list_versions_command.go
  dev/sg/internal/cloud/printers.go
  dev/sg/internal/cloud/status_command.go
  dev/sg/sg_cloud.go
Labels: cla-signed

#62387 gitserver: Remove duplicative test
  cmd/gitserver/internal/integration_tests/BUILD.bazel
  cmd/gitserver/internal/integration_tests/clone_test.go
  cmd/gitserver/internal/integration_tests/resolverevisions_test.go
Labels: cla-signed, team/source, team/product-platform

#62368 gitserver: Implement CommitGraph using Commits
  internal/batches/sources/mocks_test.go
  internal/codeintel/uploads/BUILD.bazel
  internal/codeintel/uploads/internal/background/backfiller/BUILD.bazel
  internal/codeintel/uploads/internal/background/backfiller/mocks_test.go
  internal/codeintel/uploads/internal/background/commitgraph/BUILD.bazel
  internal/codeintel/uploads/internal/background/commitgraph/job_commitgraph.go
  internal/codeintel/uploads/internal/background/expirer/BUILD.bazel
  internal/codeintel/uploads/internal/background/expirer/mocks_test.go
  internal/codeintel/uploads/internal/background/processor/BUILD.bazel
  internal/codeintel/uploads/internal/background/processor/mocks_test.go
  internal/codeintel/uploads/internal/commitgraph/BUILD.bazel
  internal/codeintel/uploads/internal/commitgraph/commit_graph.go
  internal/codeintel/uploads/internal/commitgraph/commit_graph_test.go
  internal/codeintel/uploads/internal/commitgraph/commit_graph_view.go
  internal/codeintel/uploads/internal/commitgraph/git_commit_graph.go
  internal/codeintel/uploads/internal/store/BUILD.bazel
  internal/codeintel/uploads/internal/store/commitgraph.go
  internal/codeintel/uploads/internal/store/commitgraph_test.go
  internal/codeintel/uploads/internal/store/misc_test.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/internal/store/store_test.go
  internal/codeintel/uploads/internal/store/uploads_test.go
  internal/codeintel/uploads/mocks_test.go
  internal/codeintel/uploads/service.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/gitdomain/BUILD.bazel
  internal/gitserver/gitdomain/commit_graph.go
  internal/gitserver/gitdomain/commit_graph_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/observability.go
  internal/insights/gitserver/client.go
Labels: cla-signed, team/source, team/product-platform

#62418 chore: Remove duplicate code for upload filtering
  internal/codeintel/codenav/commit_cache.go
  internal/codeintel/codenav/service.go
Labels: team/graph, cla-signed, team/product-platform

#62460 chore(rel): fix wrong stage name when checking reqs
  dev/sg/internal/release/config.go
Labels: cla-signed, backport 5.3.14141

#62348 misc(docs): annotate release build
  release.yaml
Labels: cla-signed

#62436 msp: prefer env token before setting up GSM client
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#62467 Update Enterprise license copyright notice
  LICENSE.enterprise
Labels: cla-signed

#62435 msp: update msp-ops links
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
  dev/managedservicesplatform/spec/service.go
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#62468 Add copyright to README
  README.md
Labels: cla-signed

#62469 Svelte: Fix breadcrumbs layout
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
Labels: cla-signed

#62253 remove unused get-cody page code
  client/web/BUILD.bazel
  client/web/src/get-cody/DownloadAppButton.module.scss
  client/web/src/get-cody/DownloadAppButton.tsx
  client/web/src/get-cody/GetCodyPage.module.scss
  client/web/src/get-cody/GetCodyPage.tsx
  client/web/src/get-cody/GetCodyPageIcon.tsx
  client/web/src/get-cody/SourceSans3VF-Upright.ttf.woff2
  client/web/src/routes.tsx
Labels: cla-signed

#62454 [Svelte]: Bring resize panels to blob page
  client/web-sveltekit/src/lib/Tabs.svelte
  client/web-sveltekit/src/lib/wildcard/index.ts
  client/web-sveltekit/src/lib/wildcard/resizable-panel/Panel.svelte
  client/web-sveltekit/src/lib/wildcard/resizable-panel/PanelGroup.svelte
  client/web-sveltekit/src/lib/wildcard/resizable-panel/PanelResizeHandleRegistry.ts
  client/web-sveltekit/src/lib/wildcard/resizable-panel/ResizablePanels.stories.svelte
  client/web-sveltekit/src/lib/wildcard/resizable-panel/types.ts
  client/web-sveltekit/src/lib/wildcard/resizable-panel/utils/callPanelsCallbacks.ts
  client/web-sveltekit/src/lib/wildcard/resizable-panel/utils/common.ts
  client/web-sveltekit/src/lib/wildcard/resizable-panel/utils/resizePanel.ts
  client/web-sveltekit/src/lib/wildcard/resizable-panel/utils/storage.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanel.svelte
Labels: cla-signed

#62470 msp/runtime: make Sentry contract integration usable without runtime
  lib/managedservicesplatform/runtime/BUILD.bazel
  lib/managedservicesplatform/runtime/contract/BUILD.bazel
  lib/managedservicesplatform/runtime/contract/contract.go
  lib/managedservicesplatform/runtime/contract/diagnostics.go
  lib/managedservicesplatform/runtime/service.go
Labels: cla-signed

#62466 Executors: run script as script, not as command
  cmd/executor/internal/worker/runtime/kubernetes.go
  cmd/executor/internal/worker/runtime/kubernetes_test.go
Labels: cla-signed

#62367 dev/linearhooks: add POC
  .gitattributes
  .prettierignore
  deps.bzl
  dev/linearhooks/.env.example
  dev/linearhooks/BUILD.bazel
  dev/linearhooks/README.md
  dev/linearhooks/config.example.yaml
  dev/linearhooks/image_test.yaml
  dev/linearhooks/internal/handlers/BUILD.bazel
  dev/linearhooks/internal/handlers/config.go
  dev/linearhooks/internal/handlers/handlers.go
  dev/linearhooks/internal/handlers/handlers_test.go
  dev/linearhooks/internal/handlers/middleware.go
  dev/linearhooks/internal/lineargql/BUILD.bazel
  dev/linearhooks/internal/lineargql/client.go
  dev/linearhooks/internal/lineargql/gen.go
  dev/linearhooks/internal/lineargql/generated.go
  dev/linearhooks/internal/lineargql/genqlient.yaml
  dev/linearhooks/internal/lineargql/gqltest/BUILD.bazel
  dev/linearhooks/internal/lineargql/gqltest/fake_client.go
  dev/linearhooks/internal/lineargql/gqltest/gqltest.go
  dev/linearhooks/internal/lineargql/operations.graphql
  dev/linearhooks/internal/lineargql/schema.graphql
  dev/linearhooks/internal/linearschema/BUILD.bazel
  dev/linearhooks/internal/linearschema/schema.go
  dev/linearhooks/internal/linearschema/schema_test.go
  dev/linearhooks/internal/linearschema/testdata/TestUnmarshalJSON/update_issue_description.golden
  dev/linearhooks/internal/linearschema/testdata/TestUnmarshalJSON/update_issue_labels.golden
  dev/linearhooks/internal/linearschema/testdata/update_issue_description.json
  dev/linearhooks/internal/linearschema/testdata/update_issue_labels.json
  dev/linearhooks/internal/service/BUILD.bazel
  dev/linearhooks/internal/service/service.go
  dev/linearhooks/main.go
  dev/tool_deps.bzl
  dev/tools.go
  go.mod
  go.sum
Labels: cla-signed

#62440 appliance: test standard config features in one suite
  internal/appliance/BUILD.bazel
  internal/appliance/blobstore_test.go
  internal/appliance/development.md
  internal/appliance/gitserver_test.go
  internal/appliance/repo_updater_test.go
  internal/appliance/standard_config_test.go
  internal/appliance/testdata/golden-fixtures/gitserver-with-no-resources.yaml
  internal/appliance/testdata/golden-fixtures/gitserver-with-resources.yaml
  internal/appliance/testdata/sg/gitserver-with-no-resources.yaml
  internal/appliance/testdata/sg/gitserver-with-resources.yaml
Labels: cla-signed

#62441 appliance: some directory structure for testdata
  internal/appliance/blobstore_test.go
  internal/appliance/dev/compare-helm/README.md
  internal/appliance/gitserver_test.go
  internal/appliance/golden_test.go
  internal/appliance/repo_updater_test.go
  internal/appliance/standard_config_test.go
  internal/appliance/symbols_test.go
  internal/appliance/testdata/golden-fixtures/blobstore/default.yaml
  internal/appliance/testdata/golden-fixtures/gitserver/default.yaml
  internal/appliance/testdata/golden-fixtures/gitserver/with-storage.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater-subsequent-disable.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater/default.yaml
  internal/appliance/testdata/golden-fixtures/standard/blobstore-subsequent-disable.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-no-resources.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-pod-template-config.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-resources.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-sa-annotations.yaml
  internal/appliance/testdata/golden-fixtures/symbols/default.yaml
  internal/appliance/testdata/golden-fixtures/symbols/with-storage.yaml
  internal/appliance/testdata/sg/blobstore/default.yaml
  internal/appliance/testdata/sg/gitserver/default.yaml
  internal/appliance/testdata/sg/gitserver/with-storage.yaml
  internal/appliance/testdata/sg/repo-updater/default.yaml
  internal/appliance/testdata/sg/standard/everything-disabled.yaml
  internal/appliance/testdata/sg/standard/repo-updater-with-no-resources.yaml
  internal/appliance/testdata/sg/standard/repo-updater-with-pod-template-config.yaml
  internal/appliance/testdata/sg/standard/repo-updater-with-resources.yaml
  internal/appliance/testdata/sg/standard/repo-updater-with-sa-annotations.yaml
  internal/appliance/testdata/sg/symbols/default.yaml
  internal/appliance/testdata/sg/symbols/with-storage.yaml
Labels: cla-signed

#62443 appliance: fix owner references for new objects
  internal/appliance/golden_test.go
  internal/appliance/kubernetes.go
  internal/appliance/testdata/golden-fixtures/blobstore/default.yaml
  internal/appliance/testdata/golden-fixtures/gitserver/default.yaml
  internal/appliance/testdata/golden-fixtures/gitserver/with-storage.yaml
  internal/appliance/testdata/golden-fixtures/repo-updater/default.yaml
  internal/appliance/testdata/golden-fixtures/standard/blobstore-subsequent-disable.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-no-resources.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-pod-template-config.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-resources.yaml
  internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-sa-annotations.yaml
  internal/appliance/testdata/golden-fixtures/standard/symbols-with-custom-image.yaml
  internal/appliance/testdata/golden-fixtures/symbols/default.yaml
  internal/appliance/testdata/golden-fixtures/symbols/with-storage.yaml
Labels: cla-signed

#62447 sg: cloud handle deploying a version
  dev/sg/internal/bk/bk.go
  dev/sg/internal/cloud/BUILD.bazel
  dev/sg/internal/cloud/artifact_registry.go
  dev/sg/internal/cloud/client.go
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/cloud/instance.go
  dev/sg/internal/cloud/list_versions_command.go
Labels: cla-signed

#62478 [Svelte]: Fix default blob page panel distribution
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#62482 Cody Ignore: allow pre-release JetBrains versions
  cmd/frontend/internal/httpapi/completions/BUILD.bazel
  cmd/frontend/internal/httpapi/completions/handler.go
  cmd/frontend/internal/httpapi/completions/handler_test.go
Labels: cla-signed

#62374 svelte: Enable repo routes by default
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.svelte
  cmd/frontend/internal/app/ui/sveltekit/routes.go
Labels: cla-signed, team/code-search

#62180 Load and pass API token to SMEGA
  cmd/cody-gateway/internal/httpapi/embeddings/sourcegraph.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config/config.go
Labels: cla-signed

#62486 [Svelte]: Fix blob content panels css selectors
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#62490 chore(rel): bump minor for stitch graph + add support invalidating migrations repo rule
  WORKSPACE
  dev/schema_migrations.bzl
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/stitched-migration-graph.json
Labels: cla-signed

#62491 Cody PLG: Change fine-tuned model identifier for completions
  internal/completions/client/fireworks/fireworks.go
Labels: cla-signed

#62493 chore(rel): remove broken annotation code
  release.yaml
Labels: cla-signed

#62476 sg: skip honey event duration if event is nil
  dev/sg/linters/BUILD.bazel
  dev/sg/linters/linters.go
  dev/sg/linters/misc.go
Labels: cla-signed

#62322 Migrate "New Cody Subscription" page
  client/web/BUILD.bazel
  client/web/src/cody/management/subscription/new/CodyProCheckoutForm.tsx
  client/web/src/cody/management/subscription/new/NewCodyProSubscriptionPage.tsx
  client/web/src/cody/util.ts
  client/web/src/jscontext.ts
  client/web/src/routes.constants.ts
  client/web/src/routes.tsx
  cmd/frontend/internal/app/jscontext/jscontext.go
  cmd/frontend/internal/app/ui/router.go
  package.json
  pnpm-lock.yaml
Labels: cla-signed

#62496 release: wrap interpolated value with single quote
  release.yaml
Labels: cla-signed, backport 5.4.0

#62262 gitserver: grpc: create changed files RPC implementation for gRPC server
  cmd/gitserver/internal/git/gitcli/diff.go
  cmd/gitserver/internal/git/gitcli/diff_test.go
  cmd/gitserver/internal/git/iface.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_logger.go
  cmd/gitserver/internal/server_grpc_test.go
  internal/gitserver/errwrap.go
  internal/gitserver/gitdomain/BUILD.bazel
  internal/gitserver/gitdomain/log.go
  internal/gitserver/gitdomain/log_test.go
  internal/gitserver/mock.go
  internal/gitserver/retry.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
  mockgen.temp.yaml
Labels: cla-signed, team/source, team/product-platform

#62354 gitserver: grpc: add new ChangedFiles method to gitserver client
  cmd/gitserver/internal/server_grpc_logger.go
  internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/client_test.go
  internal/gitserver/commands.go
  internal/gitserver/commands_test.go
  internal/gitserver/mocks_temp.go
  internal/gitserver/observability.go
Labels: cla-signed, team/source, team/product-platform

#62355 symbols: replace usage of gitserver client's DiffSymbols method with new ChangedFiles method
  cmd/symbols/fetcher/BUILD.bazel
  cmd/symbols/fetcher/mocks_test.go
  cmd/symbols/gitserver/BUILD.bazel
  cmd/symbols/gitserver/client.go
  cmd/symbols/gitserver/client_test.go
  cmd/symbols/gitserver/observability.go
  cmd/symbols/internal/api/BUILD.bazel
  cmd/symbols/internal/api/mocks_test.go
  cmd/symbols/internal/database/writer/BUILD.bazel
  cmd/symbols/internal/database/writer/writer.go
  internal/gitserver/commands.go
Labels: cla-signed, team/source, team/product-platform

#62358 searcher: replace usage of gitserver.DiffSymbols with new gitserver.ChangedFiles client method
  cmd/searcher/internal/search/BUILD.bazel
  cmd/searcher/internal/search/hybrid.go
  cmd/searcher/internal/search/hybrid_test.go
  cmd/searcher/internal/search/search.go
  cmd/searcher/shared/shared.go
Labels: cla-signed, team/source, team/product-platform

#62359 worker: embeddings: replace usage of old gitserver.DiffSymbols client method with new gitserver.ChangedFiles method
  cmd/worker/internal/embeddings/repo/BUILD.bazel
  cmd/worker/internal/embeddings/repo/handler.go
  cmd/worker/internal/embeddings/repo/handler_test.go
Labels: cla-signed, team/source, team/product-platform

#62503 Fix panic on startup
  cmd/frontend/internal/app/jscontext/jscontext.go
Labels: cla-signed

#62360 gitserver: grpc: remove now unused DiffSymbols func
  CHANGELOG.md
  internal/batches/sources/mocks_test.go
  internal/gitserver/client.go
  internal/gitserver/commands.go
  internal/gitserver/mocks_temp.go
Labels: cla-signed, team/source, team/product-platform

#62363 searcher: remove unused diff.ParseGitDiffNameStatus package
  cmd/searcher/diff/BUILD.bazel
  cmd/searcher/diff/diff.go
Labels: cla-signed, team/source, team/product-platform

#62501 telemetry/resolvers: improve logging on RecordEvents errors
  cmd/frontend/internal/telemetry/resolvers/BUILD.bazel
  cmd/frontend/internal/telemetry/resolvers/resolvers.go
  cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
Labels: cla-signed

#62504 gomod: Bump zoekt for UseKeywordScoring rename
  deps.bzl
  go.mod
  go.sum
  internal/conf/computed.go
  internal/search/backend/metered_searcher.go
  internal/search/types.go
  internal/search/types_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#62326 Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update, backport 5.4.0

#62511 chore(rel): bump minor for stitch graph + add support invalidating migrations repo rule
  WORKSPACE
  dev/schema_migrations.bzl
  internal/database/migration/shared/data/cmd/generator/consts.go
  internal/database/migration/shared/data/stitched-migration-graph.json
Labels: cla-signed

#62522 chore: Rename function to reduce confusion
  dev/linearhooks/internal/handlers/handlers.go
  dev/linearhooks/internal/handlers/handlers_test.go
Labels: team/graph, cla-signed, team/product-platform

#62527 chore: Fix function name in comment
  internal/codeintel/uploads/service.go
Labels: team/graph, cla-signed, team/product-platform

#62530 chore: Rename locals id -> uploadID, dump -> upload
  internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
  internal/codeintel/codenav/internal/lsifstore/store.go
  internal/codeintel/codenav/service.go
Labels: team/graph, cla-signed, team/product-platform

#62532 chore: fix typos
  cmd/worker/internal/githubapps/job.go
  doc/dev/background-information/insights/backend.md
  internal/insights/background/background.go
Labels: cla-signed

#62479 sg: cloud ephemeral fetch license key from gcp secrets manager
  dev/sg/internal/bk/bk.go
  dev/sg/internal/cloud/BUILD.bazel
  dev/sg/internal/cloud/client.go
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/rfc/rfc.go
  dev/sg/internal/secrets/store.go
  dev/sg/sg_analytics.go
Labels: cla-signed

#62456 sg: cloud ephemeral check if deployment exists already
  dev/sg/internal/bk/bk.go
  dev/sg/internal/cloud/BUILD.bazel
  dev/sg/internal/cloud/client.go
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/rfc/rfc.go
  dev/sg/internal/secrets/store.go
  dev/sg/sg_analytics.go
Labels: cla-signed

#62415 fix: Correctly filter uploads with commit and path existence checks
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_closest_uploads_test.go
Labels: team/graph, cla-signed, team/product-platform

#62534 Svelte: Visual updates to diff summary
  client/web-sveltekit/src/lib/repo/DiffSquares.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffSummaryHeader.svelte
  client/web/src/components/diff/DiffStat.module.scss
Labels: cla-signed

#62537 chore: Inline method at single usage site
  internal/codeintel/codenav/service.go
Labels: team/graph, cla-signed, team/product-platform

#62457 svelte: Reduce imported global CSS
  client/web-sveltekit/src/lib/Commit.svelte
  client/web-sveltekit/src/lib/Icon.svelte
  client/web-sveltekit/src/lib/TreeNode.svelte
  client/web-sveltekit/src/lib/TreeView.stories.svelte
  client/web-sveltekit/src/lib/breakpoints.scss
  client/web-sveltekit/src/lib/repo/DiffSquares.svelte
  client/web-sveltekit/src/lib/search/SyntaxHighlightedQuery.svelte
  client/web-sveltekit/src/lib/search/input/SuggestionOption.svelte
  client/web-sveltekit/src/lib/styles/breakpoints.scss
  client/web-sveltekit/src/lib/styles/dropdown.scss
  client/web-sveltekit/src/lib/styles/popover.scss
  client/web-sveltekit/src/lib/styles/utilities.scss
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
  client/web-sveltekit/src/routes/search/CommitSearchResult.svelte
  client/web-sveltekit/src/routes/search/PersonSearchResult.svelte
  client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
  client/web-sveltekit/src/routes/search/StreamingProgress.svelte
  client/web-sveltekit/src/routes/search/TeamSearchResult.svelte
  client/web-sveltekit/src/routes/styles.scss
  client/web-sveltekit/vite.config.ts
Labels: cla-signed, team/code-search

#62539 chore: remove overridden repository cache flag from bazelrc
  .aspect/bazelrc/ci.sourcegraph.bazelrc
Labels: cla-signed

#62541 release: return an error when promoting a dev release
  dev/sg/internal/release/config.go
Labels: cla-signed

#62545 Cody Ignore: use "cache-and-network" fetch policy for context filters query
  client/web/src/cody/useCodyIgnore.tsx
Labels: cla-signed

#62546 release: disable promotion criteria validation
  release.yaml
Labels: cla-signed, backport 5.4.0

#62544 chore(ci): Remove dead boards
  .github/workflows/label-move.yml
Labels: cla-signed

#62510 Rockskip: simplify ruler function
  internal/rockskip/server.go
  internal/rockskip/server_test.go
Labels: team/search-platform, cla-signed, team/product-platform

#62538 svelte: Fix file tree behavior
  client/web-sveltekit/src/lib/TreeNode.svelte
  client/web-sveltekit/src/lib/repo/api/tree.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/fileTreeStore.ts
Labels: cla-signed, team/code-search

#62529 chore: Document post-condition for upload matching
  internal/codeintel/codenav/iface.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/uploads/internal/store/store.go
  internal/codeintel/uploads/internal/store/util.go
Labels: team/graph, cla-signed, team/product-platform

#62543 chore: Move helper function to database package
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/repository_contributors.go
  internal/database/BUILD.bazel
  internal/database/helpers.go
  internal/database/helpers_test.go
Labels: team/graph, cla-signed, team/product-platform

#62542 chore: Add missing interface assertion for codenav Resolver
  internal/codeintel/resolvers/root_resolver.go
Labels: team/graph, cla-signed, team/product-platform

#62540 chore: Make receiver names consistent in codenav/service.go
  internal/codeintel/codenav/service.go
Labels: team/graph, cla-signed, team/product-platform

#62551 release: pass in `IS_DEVELOPMENT_RELEASE` flag to buildkite
  release.yaml
Labels: cla-signed

#62494 svelte: First pass on fuzzy finder
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/Hotkey.ts
  client/web-sveltekit/src/lib/Tabs.svelte
  client/web-sveltekit/src/lib/TabsHeader.svelte
  client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.gql
  client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.svelte
  client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinderContainer.svelte
  client/web-sveltekit/src/lib/fuzzyfinder/keys.ts
  client/web-sveltekit/src/lib/fuzzyfinder/sources.ts
  client/web-sveltekit/src/lib/web.ts
  client/web-sveltekit/src/lib/wildcard/Input.svelte
  client/web-sveltekit/src/routes/+layout.svelte
  client/web/src/search/autocompletion/source.ts
  package.json
  pnpm-lock.yaml
Labels: cla-signed, team/code-search

#62552 release: pass in `IS_DEVELOPMENT_RELEASE` flag to buildkite
  release.yaml
Labels: cla-signed

#62553 release: execute gh via bazel
  release.yaml
Labels: cla-signed

#62521 dev/linearhooks: add support for project modifier
  dev/linearhooks/config.example.yaml
  dev/linearhooks/internal/handlers/BUILD.bazel
  dev/linearhooks/internal/handlers/config.go
  dev/linearhooks/internal/handlers/handlers.go
  dev/linearhooks/internal/handlers/handlers_test.go
  dev/linearhooks/internal/lineargql/generated.go
  dev/linearhooks/internal/lineargql/gqltest/gqltest.go
  dev/linearhooks/internal/lineargql/operations.graphql
Labels: cla-signed

#62364 v2t: add v2t to client/branded
  client/branded/src/components/panel/TabbedPanelContent.fixtures.ts
  client/branded/src/components/panel/TabbedPanelContent.tsx
  client/branded/src/search-ui/components/FileContentSearchResult.test.tsx
  client/branded/src/search-ui/components/FileContentSearchResult.tsx
  client/branded/src/search-ui/components/FileMatchChildren.tsx
  client/branded/src/search-ui/components/FilePathSearchResult.tsx
  client/branded/src/search-ui/components/OwnerSearchResult.tsx
  client/branded/src/search-ui/components/QueryExamples.tsx
  client/branded/src/search-ui/components/SearchResultPreviewButton.tsx
  client/branded/src/search-ui/components/SymbolSearchResult.tsx
  client/branded/src/search-ui/input/SearchBox.story.tsx
  client/branded/src/search-ui/input/SearchBox.tsx
  client/branded/src/search-ui/input/SearchContextDropdown.test.tsx
  client/branded/src/search-ui/input/SearchContextDropdown.tsx
  client/branded/src/search-ui/input/SearchContextMenu.story.tsx
  client/branded/src/search-ui/input/SearchContextMenu.test.tsx
  client/branded/src/search-ui/input/SearchContextMenu.tsx
  client/branded/src/search-ui/input/SearchHelpDropdownButton.tsx
  client/branded/src/search-ui/input/SearchHistoryDropdown.tsx
  client/branded/src/search-ui/input/toggles/Toggles.test.tsx
  client/branded/src/search-ui/input/toggles/Toggles.tsx
  client/branded/src/search-ui/results/NoResultsPage.tsx
  client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
  client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/branded/src/search-ui/results/progress/StreamingProgress.story.tsx
  client/branded/src/search-ui/results/progress/StreamingProgress.tsx
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedButton.test.tsx
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedButton.tsx
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.story.tsx
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.test.tsx
  client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
  client/branded/src/search-ui/results/sidebar/SearchReference.tsx
  client/jetbrains/webview/src/search/input/JetBrainsSearchBox.tsx
  client/shared/src/search/stream.ts
  client/shared/src/tracking/event-log-creators.ts
  client/vscode/src/webview/platform/context.ts
  client/vscode/src/webview/search-panel/SearchHomeView.tsx
  client/vscode/src/webview/search-panel/SearchResultsView.tsx
  client/vscode/src/webview/sidebars/search/SearchSidebarView.tsx
  client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
  client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
  client/web/src/search/input/SearchNavbarItem.tsx
  client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
  client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
  client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
  client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
Labels: cla-signed
