Repository sourcegraph/sourcegraph-public-snapshot, pull requests merged in 2024-06, with the labels that each got.

#63030 chore: Remove unused codeintel utils code
  lib/codeintel/precise/util.go
Labels: team/graph, cla-signed, team/product-platform

#63002 fix(scip-syntax): Fixes a couple CLI annoyances
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
Labels: team/graph, cla-signed, team/product-platform

#62999 chore(appliance): fix race condition in tests
  internal/appliance/reconciler/blobstore_test.go
  internal/appliance/reconciler/cadvisor_test.go
  internal/appliance/reconciler/codeintel_test.go
  internal/appliance/reconciler/gitserver_test.go
  internal/appliance/reconciler/helpers_test.go
  internal/appliance/reconciler/pgsql_test.go
  internal/appliance/reconciler/precise_code_intel_test.go
  internal/appliance/reconciler/prometheus_test.go
  internal/appliance/reconciler/redis_test.go
  internal/appliance/reconciler/repo_updater_test.go
  internal/appliance/reconciler/standard_config_test.go
  internal/appliance/reconciler/symbols_test.go
  internal/appliance/reconciler/syntect_test.go
Labels: cla-signed

#63032 sg: speed up interrupt execution
  dev/sg/interrupt/interrupt.go
Labels: cla-signed

#63033 feat(release): rename code freeze event to `branch cut` event
  dev/sg/internal/release/calendar.go
  tools/release/config/calendar.jsonc
Labels: cla-signed

#63025 chore: Enable traces for uploads
  internal/uploadhandler/BUILD.bazel
  internal/uploadhandler/upload_handler.go
  internal/uploadhandler/upload_handler_state.go
Labels: team/graph, cla-signed, team/product-platform

#63027 chore: Remove unused code for precise defs by symbol
  internal/codeintel/codenav/service_new.go
Labels: team/graph, cla-signed, team/product-platform

#63029 chore: Use new cmp package to simplify comparisons
  internal/api/api.go
  lib/codeintel/precise/util.go
Labels: team/graph, cla-signed, team/product-platform

#62992 chore: Add tests documenting error invariants
  deps.bzl
  go.sum
  lib/errors/.gitignore
  lib/errors/BUILD.bazel
  lib/errors/cockroach.go
  lib/errors/invariants_test.go
  lib/go.mod
  lib/go.sum
  lib/managedservicesplatform/go.sum
  monitoring/go.sum
Labels: team/graph, cla-signed, team/product-platform

#63004 Remove echo test alert
  doc/admin/observability/alerts.md
  doc/admin/observability/dashboards.md
  monitoring/definitions/git_server.go
Labels: cla-signed, team/source, team/product-platform

#63031 Publish sourcegraph-dev image
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-dev.yaml
  wolfi-images/sourcegraph-dev/BUILD.bazel
Labels: cla-signed

#63028 gitserver: Remove IsCloneable check from clone path
  cmd/gitserver/internal/integration_tests/clone_test.go
  cmd/gitserver/internal/server.go
  cmd/gitserver/internal/server_test.go
  cmd/gitserver/internal/vcssyncer/git.go
Labels: cla-signed, team/source, team/product-platform

#63026 gitserver: Add observability for repo service
  cmd/repo-updater/internal/gitserver/BUILD.bazel
  cmd/repo-updater/internal/gitserver/observability.go
  cmd/repo-updater/internal/gitserver/repositoryservice.go
  cmd/repo-updater/internal/purge/purge.go
  cmd/repo-updater/internal/repoupdater/server.go
  cmd/repo-updater/shared/main.go
  doc/admin/observability/dashboards.md
  monitoring/definitions/git_server.go
  monitoring/definitions/repo_updater.go
  monitoring/definitions/shared/gitserver.go
Labels: cla-signed, team/source, team/product-platform

#63044 Use anyhow context, bail, and ensure instead of panicking
  docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs
Labels: team/graph, cla-signed, team/product-platform

#63034 feat(release): allow creation of multiple patch release events
  dev/sg/internal/release/calendar.go
  tools/release/config/calendar.jsonc
Labels: cla-signed

#63045 chore/enterpriseportal: add instrumentation for RPC handlers
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  cmd/enterprise-portal/service/BUILD.bazel
  cmd/enterprise-portal/service/service.go
  go.mod
Labels: cla-signed

#63046 chore: Temporarily disable syntactic indexing worker job
  cmd/worker/shared/BUILD.bazel
  cmd/worker/shared/main.go
Labels: team/graph, cla-signed, team/product-platform

#63049 chore/msp/runtime: disable telemetry on Google Monitoring/Trace APIs
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/runtime/internal/opentelemetry/BUILD.bazel
  lib/managedservicesplatform/runtime/internal/opentelemetry/metrics.go
  lib/managedservicesplatform/runtime/internal/opentelemetry/tracing.go
Labels: cla-signed

#63050 chore/msp/spec: tidy up custom alerts spec
  dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
  dev/managedservicesplatform/spec/monitoring.go
  dev/managedservicesplatform/stacks/monitoring/custom.go
Labels: cla-signed

#62977 cmd: frontend: add note that clarifies that your code host needs to be accessible over the network to test connection button
  cmd/frontend/graphqlbackend/external_service.go
  cmd/frontend/graphqlbackend/external_services.go
  cmd/frontend/graphqlbackend/external_services_test.go
Labels: cla-signed, team/source, team/product-platform

#63051 worker: add SAMS notifications subscriber
  cmd/worker/internal/sourcegraphaccounts/BUILD.bazel
  cmd/worker/internal/sourcegraphaccounts/mocks_test.go
  cmd/worker/internal/sourcegraphaccounts/notifications_subscriber.go
  cmd/worker/internal/sourcegraphaccounts/notifications_subscriber_handlers.go
  cmd/worker/internal/sourcegraphaccounts/notifications_subscriber_handlers_test.go
  cmd/worker/internal/sourcegraphaccounts/notifications_subscriber_store.go
  cmd/worker/shared/BUILD.bazel
  cmd/worker/shared/main.go
  deps.bzl
  dev/BUILD.bazel
  go.mod
  go.sum
  mockgen.test.yaml
Labels: cla-signed

#63054 Chore: remove plausible scripts
  cmd/frontend/internal/app/ui/app.html
  doc/_resources/assets/docsite.js
  doc/_resources/templates/root.html
Labels: cla-signed

#62586 v2t: add v2 telemetry to the client/shared folder
  client/browser/src/shared/code-hosts/shared/codeHost.test.tsx
  client/browser/src/shared/code-hosts/shared/codeHost.tsx
  client/browser/src/shared/components/CodeViewToolbar.tsx
  client/client-api/src/contribution.ts
  client/shared/package.json
  client/shared/src/actions/ActionItem.story.tsx
  client/shared/src/actions/ActionItem.test.tsx
  client/shared/src/actions/ActionItem.tsx
  client/shared/src/actions/ActionsNavItems.test.tsx
  client/shared/src/actions/ActionsNavItems.tsx
  client/shared/src/api/client/connection.ts
  client/shared/src/api/client/mainthread-api.test.ts
  client/shared/src/api/client/mainthread-api.ts
  client/shared/src/api/contract.ts
  client/shared/src/api/extension/activation.ts
  client/shared/src/api/extension/api/contribution.test.ts
  client/shared/src/api/extension/test/activation.test.ts
  client/shared/src/codeintel/legacy-extensions/api.ts
  client/shared/src/codeintel/legacy-extensions/providers.ts
  client/shared/src/codeintel/legacy-extensions/telemetry.ts
  client/shared/src/commands/commands.ts
  client/shared/src/contributions/contributions.test.ts
  client/shared/src/extensions/createSyncLoadedController.ts
  client/shared/src/hover/HoverOverlay.fixtures.ts
  client/shared/src/hover/HoverOverlay.test.tsx
  client/shared/src/hover/HoverOverlay.tsx
  client/shared/src/hover/actions.ts
  client/shared/src/hover/useLogTelemetryEvent.ts
  client/shared/src/search/searchQueryState.tsx
  client/shared/src/testing/testHelpers.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/search/PreviewPanel.svelte
  client/web/package.json
  client/web/src/repo/blob/CodeMirrorBlob.tsx
  client/web/src/repo/blob/codemirror/codeintel/api.ts
  client/web/src/repo/blob/codemirror/tooltips/HovercardView.tsx
  client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
  pnpm-lock.yaml
Labels: cla-signed

#63061 chore(codeintel): Simplify map[T]struct{} logic to use Set
  internal/codeintel/codenav/commit_cache.go
  internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
  internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
  internal/codeintel/codenav/internal/lsifstore/scan.go
  internal/codeintel/codenav/service_new.go
Labels: team/graph, cla-signed, team/product-platform

#63060 chore(codeintel): Document prepareCandidateUploads function
  internal/codeintel/codenav/service_new.go
Labels: team/graph, cla-signed, team/product-platform

#63041 Svelte: Add telemetry v2 to svelte client
  client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
  client/shared/src/search/helpers.ts
  client/shared/src/search/stream.ts
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
  client/web-sveltekit/src/lib/telemetry2.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/OpenInCodeHostAction.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
  client/web-sveltekit/src/routes/search/SearchHome.svelte
  client/web-sveltekit/src/routes/search/SearchResults.svelte
  client/web/src/search/helpers.tsx
  pnpm-lock.yaml
Labels: cla-signed, i-acknowledge-this-goes-into-the-release

#63062 chore: Rename Contains to IsSupersetOf
  internal/collections/set.go
  internal/collections/set_test.go
Labels: team/graph, cla-signed, team/source, team/product-platform

#63056 chore: Make GetDefinitions API consistent with GetReferences etc.
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/transport/graphql/iface.go
  internal/codeintel/codenav/transport/graphql/mocks_test.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
Labels: team/graph, cla-signed, team/product-platform

#63070 chore(pnpm): add telemetry package
  pnpm-lock.yaml
Labels: cla-signed

#62941 schema: Document perf scaling for occurrences(...)
  cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Labels: team/graph, cla-signed, team/product-platform

#63040 chore: Simplify RequestState/PositionalRequestArgs o11y code
  internal/codeintel/codenav/request_state.go
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_new.go
  internal/codeintel/codenav/transport/graphql/observability.go
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
  internal/codeintel/codenav/transport/graphql/root_resolver_ranges.go
  internal/codeintel/codenav/types.go
  internal/observation/BUILD.bazel
  internal/observation/fields.go
  internal/observation/fields_test.go
Labels: team/graph, cla-signed, team/product-platform

#63042 feat(appliance): deploy codeinsights-db
  internal/appliance/config/BUILD.bazel
  internal/appliance/config/defaults.go
  internal/appliance/config/embed.go
  internal/appliance/config/postgres/codeinsights.conf
  internal/appliance/config/spec.go
  internal/appliance/dev/compare-helm/compare-helm.go
  internal/appliance/reconciler/BUILD.bazel
  internal/appliance/reconciler/codeinsights.go
  internal/appliance/reconciler/codeinsights_test.go
  internal/appliance/reconciler/reconcile.go
  internal/appliance/reconciler/testdata/golden-fixtures/codeinsights/default.yaml
  internal/appliance/reconciler/testdata/sg/codeinsights/default.yaml
Labels: cla-signed

#63059 chore(codeintel): usagesForSymbol - make start/end non-optional for now
  cmd/frontend/graphqlbackend/codeintel.codenav.graphql
  internal/codeintel/resolvers/codenav.go
Labels: team/graph, cla-signed, team/product-platform

#63022 build(bazel): upgrade to rules_js 2.0 RC
  WORKSPACE
  dev/esbuild.bzl
  dev/eslint.bzl
  dev/js_lib.bzl
  dev/mocha.bzl
Labels: cla-signed

#63071 feat(sg: add `list-build` subcommand to ci
  dev/sg/ci/BUILD.bazel
  dev/sg/ci/command.go
  dev/sg/ci/subcommands.go
  dev/sg/internal/bk/bk.go
Labels: cla-signed

#63009 Svelte: clean up file tree
  client/web-sveltekit/src/lib/TreeNode.svelte
  client/web-sveltekit/src/lib/TreeView.svelte
  client/web-sveltekit/src/lib/wildcard/Button.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed

#63055 Cody Gateway: remove feature flag requirement for Gemini models
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
Labels: cla-signed

#62991 Svelte: make search header primary
  client/web-sveltekit/src/auto-imports.d.ts
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/lib/Tabs.svelte
  client/web-sveltekit/src/lib/TabsHeader.svelte
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/lib/search/CodeHostIcon.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
Labels: cla-signed

#63079 sg: add command to fetch versions from release registry
  dev/sg/internal/release/BUILD.bazel
  dev/sg/internal/release/release.go
  dev/sg/internal/release/release_registry.go
Labels: cla-signed

#63058 fix/enterpriseportal: fix registration of connectRPC handler options
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
Labels: cla-signed

#63073 Change JetBrains IDE statuses from Beta to Stable
  client/web/src/cody/editorGroups.ts
Labels: cla-signed

#62891 repo-updater: Hydrate schedule on startup
  cmd/repo-updater/internal/scheduler/BUILD.bazel
  cmd/repo-updater/internal/scheduler/scheduler.go
  cmd/repo-updater/internal/scheduler/scheduler_test.go
  cmd/repo-updater/shared/main.go
Labels: cla-signed, team/source, team/product-platform

#63080 Svelte: fix editor button styling
  client/web-sveltekit/src/lib/repo/open-in-editor/OpenInEditor.svelte
Labels: cla-signed

#63066 gitserver(fs): Remove caching of cloned state
  cmd/gitserver/internal/gitserverfs/fs.go
Labels: cla-signed, team/source, team/product-platform

#63086 repoupdater(scheduler): Prevent race condition of schedule preloading
  internal/repos/syncer.go
  internal/repos/syncer_test.go
Labels: cla-signed, team/source, team/product-platform

#63084 fix/msp: flatten custom alert promQL query for GCP
  dev/managedservicesplatform/internal/resource/alertpolicy/BUILD.bazel
  dev/managedservicesplatform/internal/resource/alertpolicy/customalert.go
  dev/managedservicesplatform/internal/resource/alertpolicy/customalert_test.go
Labels: cla-signed

#62911 feat/cody-gateway: use wildcard for enterprise allowlists
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  cmd/cody-gateway/qa/BUILD.bazel
  cmd/cody-gateway/qa/README.md
  cmd/cody-gateway/qa/e2e_test.go
  sg.config.yaml
Labels: cla-signed

#63053 Cody Gateway: Add Gemini models to PLG and Enterprise users
  CHANGELOG.md
  client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
  client/web/src/site-admin/SiteAdminPingsPage.tsx
  cmd/cody-gateway/internal/httpapi/completions/google.go
  cmd/cody-gateway/internal/httpapi/completions/google_test.go
  cmd/cody-gateway/shared/config/BUILD.bazel
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/httpapi/completions/BUILD.bazel
  cmd/frontend/internal/httpapi/completions/chat.go
  internal/completions/client/BUILD.bazel
  internal/completions/client/client.go
  internal/completions/client/codygateway/BUILD.bazel
  internal/completions/client/codygateway/codygateway.go
  internal/completions/client/google/BUILD.bazel
  internal/completions/client/google/decoder.go
  internal/completions/client/google/decoder_test.go
  internal/completions/client/google/google.go
  internal/completions/client/google/google_test.go
  internal/completions/client/google/models.go
  internal/completions/client/google/prompt.go
  internal/completions/client/google/prompt_test.go
  internal/completions/client/google/types.go
  internal/conf/BUILD.bazel
  internal/conf/computed.go
  internal/licensing/codygateway.go
  internal/licensing/codygateway_test.go
  schema/site.schema.json
Labels: cla-signed

#63087 chore/msp/runtime: add args as trace attributes, clean up tracing code
  lib/managedservicesplatform/cloudsql/BUILD.bazel
  lib/managedservicesplatform/cloudsql/cloudsql.go
  lib/managedservicesplatform/cloudsql/tracer.go
Labels: cla-signed

#63069 feat(sg): respect the context when executing interrupt hooks
  dev/sg/internal/run/command.go
  dev/sg/internal/run/run.go
  dev/sg/interrupt/interrupt.go
Labels: cla-signed

#63094 chore(sg): move `registry list` cmd to `release list`
  dev/sg/internal/release/BUILD.bazel
  dev/sg/internal/release/list_release.go
  dev/sg/internal/release/release.go
Labels: cla-signed

#63095 bazel: rules_js rc3 and remove deprecated "exclude_declarations" option
  .aspect/bazelrc/local.bazelrc
  WORKSPACE
Labels: cla-signed

#63048 GRAPH-646: scip syntax java package namespace fix
  docker-images/syntax-highlighter/crates/scip-syntax/.gitignore
  docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/index.scip
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__globals.java.snap
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_evaluation.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/java/scip-tags.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_globals.java.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_package-info.java.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/testdata/package-info.java
Labels: team/graph, cla-signed, team/product-platform

#63000 Cody Gateway embeddings: powering with generated metadata
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/embeddings/metadata.go
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config/config.go
  internal/codygateway/types.go
  internal/completions/client/fireworks/fireworks.go
Labels: cla-signed

#63096 Fix Cody onboarding redirect problem
  client/web/src/cody/onboarding/CodyOnboarding.tsx
Labels: cla-signed

#63098 Revert "Cody Gateway embeddings: powering with generated metadata"
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/embeddings/metadata.go
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config/config.go
  internal/codygateway/types.go
  internal/completions/client/fireworks/fireworks.go
Labels: cla-signed

#63082 Svelte: collapse path when too long
  client/web-sveltekit/src/auto-imports.d.ts
  client/web-sveltekit/src/lib/dom.ts
  client/web-sveltekit/src/lib/repo/FileHeader.svelte
Labels: cla-signed

#61969 chore(bazel): enable rules_esbuild sandbox with object-inspect workaround
  WORKSPACE
  client/testing/BUILD.bazel
  dev/esbuild.bzl
  dev/mocha.bzl
  package.json
  pnpm-lock.yaml
  third_party/rules_esbuild/BUILD.bazel
  third_party/rules_esbuild/sandbox-plugin-fixes.patch
Labels: cla-signed

#63085 chore: upgrade to latest rules_oci 1.x
  WORKSPACE
  third_party/rules_oci/BUILD.bazel
  third_party/rules_oci/no_xattr.patch
Labels: cla-signed

#63099 Initialise authProviders array in Go code
  cmd/frontend/internal/app/jscontext/jscontext.go
Labels: cla-signed, team/source, team/product-platform

#63101 cleanup: fix typo: scretTokenKey --> secretTokenKey
  client/vscode/src/backend/authenticatedUser.ts
  client/vscode/src/extension.ts
  client/vscode/src/settings/accessTokenSetting.ts
  client/vscode/src/webview/commands.ts
  client/vscode/src/webview/platform/AuthProvider.ts
Labels: cla-signed

#63067 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#63102 Revert "security: Auto-update package lockfiles for Sourcegraph base images (#63067)"
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed

#63103 chore(graph): Add changelog entry for Python CTags fix
  CHANGELOG.md
Labels: cla-signed, team/product-platform

#63104 security: Auto-update package lockfiles for Sourcegraph base images
  wolfi-images/batcheshelper.lock.json
  wolfi-images/blobstore.lock.json
  wolfi-images/bundled-executor.lock.json
  wolfi-images/caddy.lock.json
  wolfi-images/cadvisor.lock.json
  wolfi-images/cloud-mi2.lock.json
  wolfi-images/executor-kubernetes.lock.json
  wolfi-images/executor.lock.json
  wolfi-images/gitserver.lock.json
  wolfi-images/grafana.lock.json
  wolfi-images/jaeger-agent.lock.json
  wolfi-images/jaeger-all-in-one.lock.json
  wolfi-images/node-exporter.lock.json
  wolfi-images/opentelemetry-collector.lock.json
  wolfi-images/postgres-exporter.lock.json
  wolfi-images/postgresql-12-codeinsights.lock.json
  wolfi-images/postgresql-12.lock.json
  wolfi-images/prometheus.lock.json
  wolfi-images/redis-exporter.lock.json
  wolfi-images/redis.lock.json
  wolfi-images/repo-updater.lock.json
  wolfi-images/search-indexer.lock.json
  wolfi-images/searcher.lock.json
  wolfi-images/server.lock.json
  wolfi-images/sourcegraph-base.lock.json
  wolfi-images/sourcegraph-dev.lock.json
  wolfi-images/sourcegraph-template.lock.json
  wolfi-images/symbols.lock.json
  wolfi-images/syntax-highlighter.lock.json
Labels: cla-signed, SSDLC, security-auto-update/images, security-auto-update

#63089 feat/msp: update handbook link in alerts dashboard, sort custom alerts first
  dev/managedservicesplatform/stacks/monitoring/BUILD.bazel
  dev/managedservicesplatform/stacks/monitoring/dashboard.go
  dev/managedservicesplatform/stacks/monitoring/dashboard_test.go
  dev/managedservicesplatform/stacks/monitoring/monitoring.go
Labels: cla-signed

#63109 fix(gateway): update Google model names in allowed custom chat models
  cmd/frontend/internal/httpapi/completions/chat.go
Labels: cla-signed

#63108 msp/deploy: add 'author' and 'commit_message' annotations
  dev/ci/msp_deploy.sh
Labels: cla-signed

#63113 fix(Cody Gateway): add model field to Google completion request
  internal/completions/client/google/google.go
  internal/completions/client/google/types.go
Labels: cla-signed

#63105 enterprise-portal: update RPC for subscription domain and members
  lib/enterpriseportal/README.md
  lib/enterpriseportal/subscriptions/v1/BUILD.bazel
  lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.proto
  lib/enterpriseportal/subscriptions/v1/subscriptions_grpc.pb.go
  lib/enterpriseportal/subscriptions/v1/v1connect/subscriptions.connect.go
Labels: cla-signed

#63118 feat/sg-msp-pg: add suggestion to check msp-ops page on perms error
  dev/sg/cloudsqlproxy/cloudsqlproxy.go
  dev/sg/msp/helpers.go
  dev/sg/msp/sg_msp.go
Labels: cla-signed

#63119 fix(release): allow release tooling to rerun finalize promotion on err
  release.yaml
Labels: cla-signed

#63121 fix(release): remove generate-notes from github release creation
  release.yaml
Labels: cla-signed

#63122 scim: Fix random suffix added to every user on resync
  CHANGELOG.md
  cmd/frontend/internal/auth/scim/BUILD.bazel
  cmd/frontend/internal/auth/scim/user.go
  cmd/frontend/internal/auth/scim/user_service.go
  cmd/frontend/internal/auth/scim/user_test.go
  cmd/frontend/internal/auth/scim/user_update_action.go
Labels: cla-signed, team/source, team/product-platform

#62774 gitserver: Sunset Exec endpoint
  cmd/gitserver/internal/git/gitcli/command.go
  cmd/gitserver/internal/git/gitcli/commitlog.go
  cmd/gitserver/internal/git/gitcli/config.go
  cmd/gitserver/internal/git/gitcli/contributors.go
  cmd/gitserver/internal/git/gitcli/exec.go
  cmd/gitserver/internal/git/gitcli/head.go
  cmd/gitserver/internal/git/gitcli/head_test.go
  cmd/gitserver/internal/git/gitcli/mergebase.go
  cmd/gitserver/internal/git/gitcli/object.go
  cmd/gitserver/internal/git/gitcli/odb.go
  cmd/gitserver/internal/git/gitcli/resolverevision.go
  cmd/gitserver/internal/git/iface.go
  cmd/gitserver/internal/git/mock.go
  cmd/gitserver/internal/git/observability.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_logger.go
  cmd/gitserver/internal/server_test.go
  internal/gitserver/errwrap.go
  internal/gitserver/mock.go
  internal/gitserver/retry.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
  internal/gitserver/v1/gitserver_grpc.pb.go
  mockgen.temp.yaml
Labels: cla-signed, team/source, team/product-platform

#63064 gitserver(client): Reintroduce 500 maximum connections limit
  doc/admin/observability/dashboards.md
  internal/gitserver/connection/BUILD.bazel
  internal/gitserver/connection/addrs.go
  internal/grpc/concurrencylimiter/BUILD.bazel
  internal/grpc/concurrencylimiter/limiter.go
  internal/grpc/concurrencylimiter/limiter_test.go
  monitoring/definitions/git_server.go
Labels: cla-signed, team/source, team/product-platform

#63124 chore(tooling): bump Go version to 1.22.4
  .tool-versions
  WORKSPACE
  dev/ci/images/go.mod
  go.mod
  internal/cmd/progress-bot/go.mod
  lib/go.mod
Labels: cla-signed

#63127 sg: deny cloud ephemeral builds from main
  dev/sg/internal/cloud/build_command.go
  dev/sg/internal/cloud/deploy_command.go
Labels: cla-signed

#63088 Svelte: inject into primary `app.html`
  client/web-sveltekit/src/app.prod.html
  client/web/dev/esbuild/server.ts
  cmd/frontend/internal/app/ui/app.html
  cmd/frontend/internal/app/ui/handlers.go
  cmd/frontend/internal/app/ui/sveltekit/sveltekit.go
  sg.config.yaml
Labels: cla-signed

#63132 Revert "gitserver(client): Reintroduce 500 maximum connections limit (#63064)"
  doc/admin/observability/dashboards.md
  internal/gitserver/connection/BUILD.bazel
  internal/gitserver/connection/addrs.go
  internal/grpc/concurrencylimiter/BUILD.bazel
  internal/grpc/concurrencylimiter/limiter.go
  internal/grpc/concurrencylimiter/limiter_test.go
  monitoring/definitions/git_server.go
Labels: cla-signed, team/source, team/product-platform

#63130 fix(SCIM): don't allow SCIM users to change fields
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/graphqlbackend/user_test.go
Labels: cla-signed, SSDLC

#63097 Syntactic Indexing: add TAR archive indexing mode to scip-syntax CLI
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
  docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
  docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
  docker-images/syntax-highlighter/crates/scip-syntax/testdata/package-info.java
  docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_files_indexing.snap
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_tar_file_indexing.snap
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_tar_stream_indexing.snap
  docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_workspace_indexing.snap
Labels: team/graph, cla-signed, team/product-platform

#62560 feat(ci): Adds playwright tests for sveltekit to bazel
  .bazelrc
  client/browser/BUILD.bazel
  client/shared/dev/generateGraphQlOperations.ts
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/playwright.config.ts
  client/web-sveltekit/src/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.spec.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
  client/web-sveltekit/src/routes/search/page.spec.ts
  client/web-sveltekit/src/testing/integration.ts
  client/web-sveltekit/svelte.config.js
  client/web-sveltekit/utils.bzl
  client/web/BUILD.bazel
  client/web/dev/BUILD.bazel
  client/web/package.json
  client/web/src/integration/BUILD.bazel
  client/web/tests-examples/demo-todo-app.spec.ts
  cmd/cody-gateway/internal/auth/auth_test.go
  dev/sg/dependencies/mac.go
  dev/tool_deps.bzl
  dev/tools/BUILD.bazel
  package.json
  pnpm-lock.yaml
  sg.config.yaml
Labels: cla-signed

#63123 fix(search): Properly handle URLs with file paths that contain route segments
  client/web-sveltekit/src/hooks.test.ts
  client/web-sveltekit/src/hooks.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.ts
  client/web-sveltekit/src/routes/layout.spec.ts
Labels: cla-signed

#63137 enterprise-portal: rename "scope" to "permission" for query RPC
  lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
  lib/enterpriseportal/subscriptions/v1/subscriptions.proto
Labels: cla-signed

#63133 bug(release): update hard coded consts
  internal/updatecheck/handler.go
Labels: cla-signed

#62770 feat(search): Add Syntax Highlighting for Hack Language
  CHANGELOG.md
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/injections.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/locals.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__react.jsx.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/Cargo.toml
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/src/lib.rs
  internal/gosyntect/languages.go
Labels: cla-signed, team/product-platform

#63135 scim: Fix user updates when SCIM was previously enabled
  internal/database/external_accounts_test.go
  internal/database/migration/shared/data/stitched-migration-graph.json
  internal/database/schema.json
  internal/database/schema.md
  internal/users/stats.go
  migrations/frontend/1717699555_fix_unique_index_for_scim_external_account_connection/down.sql
  migrations/frontend/1717699555_fix_unique_index_for_scim_external_account_connection/metadata.yaml
  migrations/frontend/1717699555_fix_unique_index_for_scim_external_account_connection/up.sql
  migrations/frontend/squashed.sql
Labels: cla-signed, team/source, team/product-platform

#62919 feat(search): Add Syntax Highlighting for Magik language
  CHANGELOG.md
  docker-images/syntax-highlighter/Cargo.Bazel.lock
  docker-images/syntax-highlighter/Cargo.lock
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/injections.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/locals.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/magik.magik
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__magik.magik.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/Cargo.toml
  docker-images/syntax-highlighter/crates/tree-sitter-all-languages/src/lib.rs
  internal/gosyntect/languages.go
  lib/codeintel/languages/extensions.go
Labels: cla-signed, team/product-platform

#63140 chore/msp: document gRPC notes in spec docstrings
  dev/managedservicesplatform/spec/environment.go
  dev/managedservicesplatform/spec/service.go
Labels: cla-signed

#63142 feat/enterprise-portal: rudimentary audit logging
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/enterprise-portal/internal/samsm2m/samsm2m.go
  cmd/enterprise-portal/internal/samsm2m/samsm2m_test.go
  cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
Labels: cla-signed

#63143 build(bazel): fixup custom eslint test rule after bump to rules_js 2
  dev/eslint.bzl
Labels: cla-signed

#63139 enterprise-portal: init database schema and handler store
  cmd/enterprise-portal/README.md
  cmd/enterprise-portal/internal/database/BUILD.bazel
  cmd/enterprise-portal/internal/database/database.go
  cmd/enterprise-portal/internal/database/migrate.go
  cmd/enterprise-portal/internal/database/permissions.go
  cmd/enterprise-portal/internal/database/subscriptions.go
  cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
  cmd/enterprise-portal/internal/subscriptionsservice/v1.go
  cmd/enterprise-portal/internal/subscriptionsservice/v1_store.go
  cmd/enterprise-portal/service/BUILD.bazel
  cmd/enterprise-portal/service/redis.go
  cmd/enterprise-portal/service/service.go
  deps.bzl
  go.mod
  go.sum
  internal/rcache/rcache.go
  internal/redislock/BUILD.bazel
  internal/redislock/mutex.go
  internal/redislock/mutex_test.go
  lib/managedservicesplatform/runtime/contract/postgresql.go
  sg.config.yaml
Labels: cla-signed

#63144 Remove references to 'rate-limits-exceeded-for-testing' feature flag
  cmd/frontend/graphqlbackend/user.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
  cmd/frontend/internal/httpapi/completions/limiter.go
Labels: cla-signed

#63128 svelte: Add bottom panel close button
  client/web-sveltekit/src/auto-imports.d.ts
  client/web-sveltekit/src/lib/Tabs.svelte
  client/web-sveltekit/src/lib/TabsHeader.svelte
  client/web-sveltekit/src/lib/wildcard/Button.module.scss
  client/web-sveltekit/src/lib/wildcard/Button.stories.svelte
  client/web-sveltekit/src/lib/wildcard/Button.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#63129 svelte: Migrate repo sidebar toggle button to use lucide icon
  client/web-sveltekit/src/auto-imports.d.ts
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Labels: cla-signed

#62781 gitserver: Cleanup CreateCommitFromPatch
  cmd/gitserver/internal/patch.go
  cmd/gitserver/internal/server_grpc.go
  cmd/gitserver/internal/server_grpc_logger.go
  internal/batches/sources/common.go
  internal/gitserver/client_test.go
  internal/gitserver/protocol/gitserver.go
  internal/gitserver/v1/gitserver.pb.go
  internal/gitserver/v1/gitserver.proto
Labels: cla-signed, team/source, team/product-platform

#63134 Reapply "gitserver(client): Reintroduce 500 maximum connections limit"
  doc/admin/observability/dashboards.md
  internal/gitserver/connection/BUILD.bazel
  internal/gitserver/connection/addrs.go
  internal/grpc/concurrencylimiter/BUILD.bazel
  internal/grpc/concurrencylimiter/limiter.go
  internal/grpc/concurrencylimiter/limiter_test.go
  monitoring/definitions/git_server.go
Labels: cla-signed, team/source, team/product-platform

#63075 fix(appliance): use version for image tags
  internal/appliance/config/BUILD.bazel
  internal/appliance/config/defaults.go
  internal/appliance/reconciler/blobstore.go
  internal/appliance/reconciler/cadvisor.go
  internal/appliance/reconciler/codeinsights.go
  internal/appliance/reconciler/codeintel.go
  internal/appliance/reconciler/gitserver.go
  internal/appliance/reconciler/pgsql.go
  internal/appliance/reconciler/precise_code_intel.go
  internal/appliance/reconciler/prometheus.go
  internal/appliance/reconciler/redis.go
  internal/appliance/reconciler/repo_updater.go
  internal/appliance/reconciler/symbols.go
  internal/appliance/reconciler/syntect.go
  internal/appliance/reconciler/testdata/golden-fixtures/blobstore/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/cadvisor/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/codeinsights/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/codeintel/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/gitserver/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/pgsql/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/precise-code-intel/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/precise-code-intel/with-blobstore.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/precise-code-intel/with-num-workers.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/precise-code-intel/with-replicas.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/prometheus/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/prometheus/privileged.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/prometheus/with-existing-configmap.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/redis/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/repo-updater/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/blobstore-with-named-storage-class.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/precise-code-intel-with-env-vars.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/redis-with-storage.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/repo-updater-with-no-resources.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/repo-updater-with-pod-template-config.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/repo-updater-with-resources.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/standard/repo-updater-with-sa-annotations.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/symbols/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/symbols/with-storage.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/syntect/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/syntect/with-replicas.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/worker/default.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/worker/with-blobstore-and-embeddings.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/worker/with-blobstore.yaml
  internal/appliance/reconciler/testdata/golden-fixtures/worker/with-replicas.yaml
  internal/appliance/reconciler/worker.go
Labels: cla-signed

#63148 [Backport 5.4.5099] fix(release): remove generate-notes from github r…
  release.yaml
Labels: cla-signed, backports, backported-to-5.4.5099

#63112 Cody Gateway embeddings: powering with generated metadata - take 2
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/embeddings/handler.go
  cmd/cody-gateway/internal/httpapi/embeddings/metadata.go
  cmd/cody-gateway/internal/httpapi/embeddings/models.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  internal/codygateway/types.go
  internal/completions/client/fireworks/fireworks.go
Labels: cla-signed

#63149 sg: add some messaging around generating a token
  dev/sg/sg_cody_gateway.go
Labels: cla-signed

#63125 feat(sg): add command to generate a dotcom user gateway access token
  dev/sg/BUILD.bazel
  dev/sg/main.go
  dev/sg/sg_cody_gateway.go
Labels: cla-signed

#63151 chore: Fix lint error (unparam)
  cmd/frontend/internal/cli/sysreq.go
Labels: team/graph, cla-signed, team/product-platform

#63150 chore(release): remind releasers of tag pipeline
  release.yaml
Labels: cla-signed

#63093 fix(sg): fix cloud eph suggested commands
  dev/sg/internal/cloud/delete_command.go
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/cloud/printers.go
  dev/sg/internal/cloud/upgrade_command.go
Labels: cla-signed

#63138 fix(highlighting): Update JSX/TSX highlighting to more properly label tag delimiters
  client/wildcard/src/global-styles/highlight.scss
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/tsx/highlights.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/react.jsx
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/react.tsx
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__react.jsx.snap
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__react.tsx.snap
Labels: cla-signed, team/product-platform

#63106 chore(graph): Add changelog entry for Python scip-ctags fix (second attempt)
  CHANGELOG.md
Labels: cla-signed, team/product-platform

#63156 Adds stubs for usage connection resolver
  internal/codeintel/codenav/transport/graphql/BUILD.bazel
  internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
  internal/codeintel/resolvers/codenav.go
Labels: team/graph, cla-signed, team/product-platform

#63136 chore(search): Add test case covering hack lang detection behavior
  internal/highlight/language_test.go
Labels: cla-signed, team/product-platform

#63072 chore(codenav): Resolve repo and commit in common code
  .gitignore
  deps.bzl
  doc/dependency_decisions.yml
  go.mod
  go.sum
  internal/codeintel/codenav/transport/graphql/root_resolver.go
  internal/codeintel/resolvers/BUILD.bazel
  internal/codeintel/resolvers/codenav.go
  internal/codeintel/resolvers/codenav_test.go
  internal/pbt/BUILD.bazel
  internal/pbt/README.md
  internal/pbt/api.go
  internal/pbt/api_test.go
  internal/pbt/probability.go
  internal/pbt/probability_test.go
  lib/errors/.gitignore
Labels: team/graph, cla-signed, team/product-platform

#62801 gitserver: Framework to support integration testing against gitserver
  cmd/gitserver/shared/BUILD.bazel
  cmd/gitserver/shared/shared.go
  cmd/gitserver/shared/testserver.go
  cmd/symbols/gitserver/BUILD.bazel
  cmd/symbols/gitserver/client.go
  cmd/symbols/shared/BUILD.bazel
  cmd/symbols/shared/main.go
  dev/gitserverintegration/BUILD.bazel
  dev/gitserverintegration/testtools.go
  dev/rockskipintegration/BUILD.bazel
  dev/rockskipintegration/main_test.go
  internal/gitserver/v1/BUILD.bazel
Labels: cla-signed, team/source, team/product-platform

#63147 gitserver: Remove comment about error checking
  cmd/gitserver/internal/server_grpc.go
Labels: cla-signed, team/source, team/product-platform

#63157 release: never use build number in image family
  cmd/executor/docker-mirror/_ami.build.sh
  cmd/executor/docker-mirror/_ami.push.sh
  cmd/executor/vm-image/_ami.build.sh
  cmd/executor/vm-image/_ami.push.sh
  dev/ci/internal/ci/executor_operations.go
Labels: cla-signed

#63141 Svelte: allow popovers to have external targets
  client/web-sveltekit/src/lib/Popover.svelte
  client/web-sveltekit/src/lib/TreeNode.svelte
  client/web-sveltekit/src/lib/TreeView.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Labels: cla-signed

#63126 Svelte: add sentry
  client/web-sveltekit/BUILD.bazel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/hooks.client.ts
  client/web-sveltekit/vite.config.ts
  pnpm-lock.yaml
Labels: cla-signed

#63159 feat/enterprise-portal: return all attributes, even when access is disabled
  cmd/enterprise-portal/internal/codyaccessservice/BUILD.bazel
  cmd/enterprise-portal/internal/codyaccessservice/adapters.go
  cmd/enterprise-portal/internal/codyaccessservice/adapters_test.go
Labels: cla-signed

#63162 fix/enterprise-portal: ignore empty hashes for Cody Gateway access tokens
  cmd/enterprise-portal/internal/codyaccessservice/adapters.go
  cmd/enterprise-portal/internal/codyaccessservice/adapters_test.go
  cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
Labels: cla-signed

#62934 feat/cody-gateway: use Enterprise Portal for actor/productsubscriptions
  cmd/cody-gateway/internal/actor/actor.go
  cmd/cody-gateway/internal/actor/actor_test.go
  cmd/cody-gateway/internal/actor/productsubscription/BUILD.bazel
  cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/BUILD.bazel
  cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/enterpriseportal.go
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription_test.go
  cmd/cody-gateway/internal/actor/productsubscription/productsubscriptiontest/BUILD.bazel
  cmd/cody-gateway/internal/actor/productsubscription/productsubscriptiontest/mocks.go
  cmd/cody-gateway/internal/actor/source.go
  cmd/cody-gateway/internal/auth/BUILD.bazel
  cmd/cody-gateway/internal/auth/auth_test.go
  cmd/cody-gateway/internal/dotcom/dotcom_test.go
  cmd/cody-gateway/internal/dotcom/operations.go
  cmd/cody-gateway/internal/dotcom/operations.graphql
  cmd/cody-gateway/internal/httpapi/BUILD.bazel
  cmd/cody-gateway/internal/httpapi/attribution/handler.go
  cmd/cody-gateway/internal/httpapi/attribution/handler_test.go
  cmd/cody-gateway/internal/httpapi/maintenance.go
  cmd/cody-gateway/internal/notify/rate_limit.go
  cmd/cody-gateway/internal/notify/rate_limit_test.go
  cmd/cody-gateway/shared/BUILD.bazel
  cmd/cody-gateway/shared/config/BUILD.bazel
  cmd/cody-gateway/shared/config/config.go
  cmd/cody-gateway/shared/main.go
  cmd/enterprise-portal/internal/codyaccessservice/v1.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql.go
  dev/BUILD.bazel
  internal/codygateway/consts.go
  internal/grpc/grpcoauth/BUILD.bazel
  internal/grpc/grpcoauth/grpcoauth.go
  lib/background/background.go
  lib/background/background_test.go
  lib/enterpriseportal/BUILD.bazel
  lib/enterpriseportal/README.md
  lib/enterpriseportal/enterpriseportal.go
  mockgen.test.yaml
  sg.config.yaml
Labels: cla-signed

#63163 feat(cody-gateway): add Google Gemini stable models to allowed models
  cmd/cody-gateway/shared/config/config.go
  cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
  cmd/frontend/internal/httpapi/completions/chat.go
  internal/conf/computed.go
Labels: cla-signed

#63169 chore/cody-gateway: instrument removeUnseenTokens
  cmd/cody-gateway/internal/actor/productsubscription/BUILD.bazel
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
  cmd/cody-gateway/internal/actor/productsubscription/productsubscription_test.go
Labels: cla-signed

#63165 msp/deploy: encode commit_message as base64
  dev/ci/msp_deploy.sh
Labels: cla-signed

#63172 Cody Gateway: handle streams with trailing newline in Gemini response
  cmd/cody-gateway/internal/httpapi/completions/google.go
  cmd/cody-gateway/internal/httpapi/completions/google_test.go
Labels: cla-signed

#63183 dotcom: fix issue with dotcom emails
  cmd/frontend/graphqlbackend/BUILD.bazel
  cmd/frontend/graphqlbackend/person.go
  cmd/frontend/graphqlbackend/person_test.go
Labels: cla-signed

#63187 enterprise-portal: temporarily disable local DB migrate
  cmd/enterprise-portal/internal/database/migrate.go
Labels: cla-signed

#63188 SSC: Fix "Make admin" and "Revoke admin" button actions
  client/web/src/cody/team/TeamMemberList.tsx
Labels: cla-signed

#63190 SSC: Fix checkout links
  client/web/src/cody/subscription/CodySubscriptionPage.tsx
Labels: cla-signed

#63192 [Svelte]: Fix standard click-based popover flow
  client/web-sveltekit/src/lib/Popover.svelte
Labels: cla-signed

#62803 feat/internal/memcmd: add internal/memcmd package to allow for memory tracking of exec.Cmd processes
  go.mod
  internal/memcmd/BUILD.bazel
  internal/memcmd/observer.go
  internal/memcmd/observer_darwin.go
  internal/memcmd/observer_darwin_test.go
  internal/memcmd/observer_example_test.go
  internal/memcmd/observer_linux.go
  internal/memcmd/observer_linux_test.go
  internal/memcmd/observer_test.go
Labels: cla-signed, team/source, team/product-platform

#63114 feat/cmd/gitserver: add memory tracking for both linux and macos
  cmd/gitserver/internal/git/gitcli/BUILD.bazel
  cmd/gitserver/internal/git/gitcli/command.go
  sg.config.yaml
Labels: cla-signed, team/source, team/product-platform

#63177 chore: Validate driver type immediately
  internal/database/dbconn/open.go
Labels: team/graph, cla-signed, team/product-platform

#63182 fix(search): Contributors page errors with empty date string
  client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
Labels: cla-signed

#63184 fix(search/svelte): Hide diff view when closing bottom panel
  client/web-sveltekit/package.json
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
  client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
Labels: cla-signed

#63195 sg: cloud eph - improve missing tag/version message
  dev/sg/internal/cloud/deploy_command.go
Labels: cla-signed

#63111 refactor: upgrade to rules_oci 2.0
  WORKSPACE
  doc/dev/background-information/bazel/containers.md
  doc/dev/background-information/bazel/faq.md
  doc/dev/background-information/sg/index.md
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  sg.config.yaml
Labels: cla-signed

#63180 Adds a search client to the codenav service
  internal/codeintel/codenav/BUILD.bazel
  internal/codeintel/codenav/init.go
  internal/codeintel/codenav/service.go
  internal/codeintel/codenav/service_closest_uploads_test.go
  internal/codeintel/codenav/service_diagnostics_test.go
  internal/codeintel/codenav/service_hover_test.go
  internal/codeintel/codenav/service_new_test.go
  internal/codeintel/codenav/service_ranges_test.go
  internal/codeintel/codenav/service_snapshot_test.go
  internal/codeintel/codenav/service_stencil_test.go
Labels: team/graph, cla-signed, team/product-platform

#63200 Revert "refactor: upgrade to rules_oci 2.0"
  WORKSPACE
  doc/dev/background-information/bazel/containers.md
  doc/dev/background-information/bazel/faq.md
  doc/dev/background-information/sg/index.md
  docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
  sg.config.yaml
Labels: cla-signed

#63201 fix(tests): Clean up mocks after test
  cmd/frontend/graphqlbackend/person_test.go
Labels: cla-signed

#63202 sg: cloud eph - set max deployment name
  dev/sg/internal/cloud/deploy_command.go
  dev/sg/internal/cloud/upgrade_command.go
Labels: cla-signed

#63197 chore(security): update dependencies
  deps.bzl
  dev/linters/go.mod
  dev/linters/go.sum
  go.mod
  go.sum
  lib/go.mod
  lib/go.sum
  lib/managedservicesplatform/go.mod
  lib/managedservicesplatform/go.sum
  monitoring/go.mod
  monitoring/go.sum
Labels: cla-signed, SSDLC

#63155 fix(highlighting): Improve highlighting for Magik language
  docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/magik.magik
  docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__magik.magik.snap
Labels: cla-signed, team/product-platform

#63110 feat(search): Support Magik language file filter in search
  client/common/src/languages.ts
  internal/search/job/jobutil/BUILD.bazel
  internal/search/job/jobutil/job.go
  internal/search/job/jobutil/job_test.go
  internal/search/query/BUILD.bazel
  internal/search/query/helpers.go
  internal/search/query/validate.go
  internal/search/zoekt/BUILD.bazel
  internal/search/zoekt/query.go
  lib/codeintel/languages/extensions.go
  lib/codeintel/languages/extensions_test.go
Labels: cla-signed, team/product-platform

#63193 Fix(search): querying event logs breaks when "id" column value > int32
  internal/database/event_logs.go
  internal/database/event_logs_test.go
Labels: cla-signed

#63166 Cody Gateway: Add support for Google non-streaming endpoint
  cmd/cody-gateway/internal/httpapi/completions/google.go
  cmd/cody-gateway/internal/httpapi/completions/google_test.go
  cmd/cody-gateway/internal/httpapi/handler.go
  cmd/cody-gateway/qa/google.go
  cmd/frontend/internal/httpapi/completions/codecompletion.go
  internal/completions/client/google/google.go
  internal/completions/client/google/types.go
Labels: cla-signed

#63164 feat/msp/runtime: PG_QUERY_LOGGING=true for local dev query logging
  lib/managedservicesplatform/runtime/contract/BUILD.bazel
  lib/managedservicesplatform/runtime/contract/contract.go
  lib/managedservicesplatform/runtime/contract/postgresql.go
Labels: cla-signed

#63206 fix/internal/memcmd: fix goroutine leak in linux observer
  go.mod
  internal/memcmd/BUILD.bazel
  internal/memcmd/observer_linux.go
  internal/memcmd/observer_linux_test.go
Labels: cla-signed, team/source, team/product-platform

#63208 feat/internal/memcmd: ignore context cancellation errors from Stop()
  internal/memcmd/BUILD.bazel
  internal/memcmd/observer_linux.go
  internal/memcmd/observer_linux_test.go
Labels: cla-signed, team/source, team/product-platform

#63210 feat/gitserver: don't log memoryObservation error if it occured b/c context cancellation
  cmd/gitserver/internal/git/gitcli/command.go
Labels: cla-signed, team/source, team/product-platform

#63186 Extend instructions for running CG locally
  doc/dev/how-to/cody_gateway.md
Labels: cla-signed

#63219 chore(schema): Add implementation status for codeGraphData
  cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Labels: team/graph, cla-signed, team/product-platform
